import hashlib
import re
from collections import defaultdict

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "SYN07 Team"
SEMANTIC_MAP_ENGINE = "SYN07_document_assembler"

SEMANTIC_MAP = {
    # Template Architecture and Design
    "template": "template",
    "templates": "template",
    "doc_template": "template",
    "document template": "template",
    "templating": "template",
    "template architecture": "template_architecture",
    "template design": "template_design",
    "template structure": "template_structure",
    "template layout": "template_layout",
    "template format": "template_format",
    "template framework": "template_framework",
    "template schema": "template_schema",
    "template blueprint": "template_blueprint",
    "template model": "template_model",
    "template pattern": "template_pattern",
    "template configuration": "template_configuration",
    "template customization": "template_customization",
    "template version": "template_version",
    "template lifecycle": "template_lifecycle",
    "template management": "template_management",
    "template repository": "template_repository",
    "template library": "template_library",
    "template taxonomy": "template_taxonomy",
    "template governance": "template_governance",
    "template approval": "template_approval",
    "template workflow": "template_workflow",
    "template testing": "template_testing",
    "template QA": "template_testing",
    "template quality assurance": "template_testing",
    "template compliance": "template_compliance",
    "template audit": "template_audit",
    "template error handling": "template_error_handling",
    "template recovery": "template_recovery",
    "template scalability": "template_scalability",
    "template performance": "template_performance",
    "template customization": "template_customization",
    "template jurisdiction": "jurisdictional_customization",
    "jurisdictional customization": "jurisdictional_customization",
    "jurisdictional compliance": "jurisdictional_compliance",
    "jurisdictional adaptation": "jurisdictional_customization",
    "jurisdictional requirements": "jurisdictional_compliance",
    "jurisdictional standards": "jurisdictional_compliance",
    "jurisdictional formatting": "jurisdictional_customization",
    "template branching": "template_branching",
    "template version control": "template_version_control",
    "template lifecycle management": "template_lifecycle",
    "template branching": "template_branching",
    "template merge": "template_merge",
    "template fork": "template_fork",
    "template split": "template_split",
    "template consolidation": "template_consolidation",
    "template rollback": "template_rollback",
    "template revert": "template_rollback",
    "template history": "template_history",
    "template audit trail": "template_audit_trail",
    "template log": "template_audit_trail",
    "template trace": "template_audit_trail",

    # Clause Library Organization and Taxonomy
    "clause": "clause",
    "clauses": "clause",
    "clause library": "clause_library",
    "clause repository": "clause_library",
    "clause taxonomy": "clause_taxonomy",
    "clause classification": "clause_taxonomy",
    "clause organization": "clause_organization",
    "clause structure": "clause_structure",
    "clause hierarchy": "clause_hierarchy",
    "clause grouping": "clause_grouping",
    "clause catalog": "clause_library",
    "clause database": "clause_library",
    "clause collection": "clause_library",
    "clause set": "clause_library",
    "clause approval": "clause_approval",
    "clause governance": "clause_governance",
    "clause workflow": "clause_workflow",
    "clause lifecycle": "clause_lifecycle",
    "clause version": "clause_version",
    "clause version control": "clause_version_control",
    "clause management": "clause_management",
    "clause customization": "clause_customization",
    "clause adaptation": "clause_customization",
    "clause compliance": "clause_compliance",
    "clause audit": "clause_audit",
    "clause error handling": "clause_error_handling",
    "clause recovery": "clause_recovery",
    "clause scalability": "clause_scalability",
    "clause performance": "clause_performance",
    "clause testing": "clause_testing",
    "clause QA": "clause_testing",
    "clause quality assurance": "clause_testing",
    "clause library management": "clause_library_management",
    "clause library taxonomy": "clause_library_taxonomy",
    "clause library organization": "clause_library_organization",
    "clause library structure": "clause_library_structure",
    "clause library hierarchy": "clause_library_hierarchy",
    "clause library grouping": "clause_library_grouping",
    "clause library catalog": "clause_library_catalog",
    "clause library database": "clause_library_database",
    "clause library collection": "clause_library_collection",
    "clause library set": "clause_library_set",

    # Conditional Inclusion and Assembly Logic
    "conditional inclusion": "conditional_inclusion",
    "conditional assembly": "conditional_inclusion",
    "conditional logic": "conditional_logic",
    "conditional clause": "conditional_inclusion",
    "conditional template": "conditional_inclusion",
    "conditional section": "conditional_inclusion",
    "conditional exhibit": "conditional_inclusion",
    "conditional schedule": "conditional_inclusion",
    "conditional block": "conditional_inclusion",
    "conditional paragraph": "conditional_inclusion",
    "conditional term": "conditional_inclusion",
    "conditional defined term": "conditional_inclusion",
    "conditional reference": "conditional_inclusion",
    "conditional cross-reference": "conditional_inclusion",
    "conditional variable": "conditional_inclusion",
    "conditional substitution": "conditional_inclusion",
    "conditional binding": "conditional_inclusion",
    "conditional data binding": "conditional_inclusion",
    "conditional assembly logic": "conditional_logic",
    "assembly logic": "assembly_logic",
    "assembly rules": "assembly_logic",
    "assembly conditions": "assembly_logic",
    "assembly triggers": "assembly_logic",
    "assembly workflow": "assembly_workflow",
    "assembly process": "assembly_process",
    "assembly engine": "assembly_engine",
    "assembly framework": "assembly_framework",
    "assembly schema": "assembly_schema",
    "assembly configuration": "assembly_configuration",
    "assembly customization": "assembly_customization",
    "assembly adaptation": "assembly_customization",
    "assembly compliance": "assembly_compliance",
    "assembly audit": "assembly_audit",
    "assembly error handling": "assembly_error_handling",
    "assembly recovery": "assembly_recovery",
    "assembly scalability": "assembly_scalability",
    "assembly performance": "assembly_performance",
    "assembly testing": "assembly_testing",
    "assembly QA": "assembly_testing",
    "assembly quality assurance": "assembly_testing",

    # Variable Substitution and Data Binding
    "variable": "variable",
    "variables": "variable",
    "variable substitution": "variable_substitution",
    "variable binding": "variable_binding",
    "variable data binding": "variable_binding",
    "variable mapping": "variable_mapping",
    "variable assignment": "variable_assignment",
    "variable definition": "variable_definition",
    "variable declaration": "variable_definition",
    "variable reference": "variable_reference",
    "variable cross-reference": "variable_reference",
    "variable value": "variable_value",
    "variable input": "variable_input",
    "variable output": "variable_output",
    "variable parameter": "variable_parameter",
    "variable argument": "variable_argument",
    "variable placeholder": "variable_placeholder",
    "variable token": "variable_token",
    "variable field": "variable_field",
    "variable slot": "variable_slot",
    "variable tag": "variable_tag",
    "variable template": "variable_template",
    "variable schema": "variable_schema",
    "variable configuration": "variable_configuration",
    "variable customization": "variable_customization",
    "variable adaptation": "variable_customization",
    "variable compliance": "variable_compliance",
    "variable audit": "variable_audit",
    "variable error handling": "variable_error_handling",
    "variable recovery": "variable_recovery",
    "variable scalability": "variable_scalability",
    "variable performance": "variable_performance",
    "variable testing": "variable_testing",
    "variable QA": "variable_testing",
    "variable quality assurance": "variable_testing",

    # Cross-Reference Management and Integrity
    "cross-reference": "cross_reference",
    "cross references": "cross_reference",
    "crossref": "cross_reference",
    "xref": "cross_reference",
    "cross reference": "cross_reference",
    "cross referencing": "cross_reference",
    "cross-reference management": "cross_reference_management",
    "cross-reference integrity": "cross_reference_integrity",
    "cross-reference validation": "cross_reference_validation",
    "cross-reference audit": "cross_reference_audit",
    "cross-reference error handling": "cross_reference_error_handling",
    "cross-reference recovery": "cross_reference_recovery",
    "cross-reference scalability": "cross_reference_scalability",
    "cross-reference performance": "cross_reference_performance",
    "cross-reference testing": "cross_reference_testing",
    "cross-reference QA": "cross_reference_testing",
    "cross-reference quality assurance": "cross_reference_testing",
    "cross-reference compliance": "cross_reference_compliance",
    "cross-reference customization": "cross_reference_customization",
    "cross-reference adaptation": "cross_reference_customization",
    "cross-reference configuration": "cross_reference_configuration",
    "cross-reference schema": "cross_reference_schema",
    "cross-reference template": "cross_reference_template",

    # Defined Terms Consistency and Management
    "defined term": "defined_term",
    "defined terms": "defined_term",
    "definition": "defined_term",
    "definitions": "defined_term",
    "defined term management": "defined_term_management",
    "defined term consistency": "defined_term_consistency",
    "defined term validation": "defined_term_validation",
    "defined term audit": "defined_term_audit",
    "defined term error handling": "defined_term_error_handling",
    "defined term recovery": "defined_term_recovery",
    "defined term scalability": "defined_term_scalability",
    "defined term performance": "defined_term_performance",
    "defined term testing": "defined_term_testing",
    "defined term QA": "defined_term_testing",
    "defined term quality assurance": "defined_term_testing",
    "defined term compliance": "defined_term_compliance",
    "defined term customization": "defined_term_customization",
    "defined term adaptation": "defined_term_customization",
    "defined term configuration": "defined_term_configuration",
    "defined term schema": "defined_term_schema",
    "defined term template": "defined_term_template",

    # Exhibit and Schedule Auto-Generation
    "exhibit": "exhibit",
    "exhibits": "exhibit",
    "schedule": "schedule",
    "schedules": "schedule",
    "exhibit auto-generation": "exhibit_auto_generation",
    "schedule auto-generation": "schedule_auto_generation",
    "exhibit generation": "exhibit_auto_generation",
    "schedule generation": "schedule_auto_generation",
    "exhibit creation": "exhibit_auto_generation",
    "schedule creation": "schedule_auto_generation",
    "exhibit assembly": "exhibit_auto_generation",
    "schedule assembly": "schedule_auto_generation",
    "exhibit template": "exhibit_template",
    "schedule template": "schedule_template",
    "exhibit customization": "exhibit_customization",
    "schedule customization": "schedule_customization",
    "exhibit adaptation": "exhibit_customization",
    "schedule adaptation": "schedule_customization",
    "exhibit compliance": "exhibit_compliance",
    "schedule compliance": "schedule_compliance",
    "exhibit audit": "exhibit_audit",
    "schedule audit": "schedule_audit",
    "exhibit error handling": "exhibit_error_handling",
    "schedule error handling": "schedule_error_handling",
    "exhibit recovery": "exhibit_recovery",
    "schedule recovery": "schedule_recovery",
    "exhibit scalability": "exhibit_scalability",
    "schedule scalability": "schedule_scalability",
    "exhibit performance": "exhibit_performance",
    "schedule performance": "schedule_performance",
    "exhibit testing": "exhibit_testing",
    "schedule testing": "schedule_testing",
    "exhibit QA": "exhibit_testing",
    "schedule QA": "schedule_testing",
    "exhibit quality assurance": "exhibit_testing",
    "schedule quality assurance": "schedule_testing",

    # Redlining and Document Comparison
    "redline": "redlining",
    "redlining": "redlining",
    "redlined": "redlining",
    "document comparison": "document_comparison",
    "doc comparison": "document_comparison",
    "compare documents": "document_comparison",
    "comparison": "document_comparison",
    "diff": "document_comparison",
    "diffing": "document_comparison",
    "track changes": "redlining",
    "change tracking": "redlining",
    "markup": "redlining",
    "mark-up": "redlining",
    "document diff": "document_comparison",
    "document differences": "document_comparison",
    "document version comparison": "document_comparison",
    "document change analysis": "document_comparison",
    "document audit": "document_audit",
    "document error handling": "document_error_handling",
    "document recovery": "document_recovery",
    "document scalability": "document_scalability",
    "document performance": "document_performance",
    "document testing": "document_testing",
    "document QA": "document_testing",
    "document quality assurance": "document_testing",

    # Document Version Control and Branching
    "version control": "version_control",
    "doc version control": "version_control",
    "document version control": "version_control",
    "versioning": "version_control",
    "branching": "branching",
    "document branching": "branching",
    "doc branching": "branching",
    "document merge": "merge",
    "doc merge": "merge",
    "document fork": "fork",
    "doc fork": "fork",
    "document split": "split",
    "doc split": "split",
    "document consolidation": "consolidation",
    "doc consolidation": "consolidation",
    "document rollback": "rollback",
    "doc rollback": "rollback",
    "document revert": "rollback",
    "doc revert": "rollback",
    "document history": "history",
    "doc history": "history",
    "document audit trail": "audit_trail",
    "doc audit trail": "audit_trail",
    "document log": "audit_trail",
    "doc log": "audit_trail",
    "document trace": "audit_trail",
    "doc trace": "audit_trail",

    # Signature Block Standards and Formatting
    "signature block": "signature_block",
    "signature blocks": "signature_block",
    "signatory block": "signature_block",
    "signatory blocks": "signature_block",
    "signature formatting": "signature_formatting",
    "signature standards": "signature_standards",
    "signature template": "signature_template",
    "signature schema": "signature_schema",
    "signature configuration": "signature_configuration",
    "signature customization": "signature_customization",
    "signature adaptation": "signature_customization",
    "signature compliance": "signature_compliance",
    "signature audit": "signature_audit",
    "signature error handling": "signature_error_handling",
    "signature recovery": "signature_recovery",
    "signature scalability": "signature_scalability",
    "signature performance": "signature_performance",
    "signature testing": "signature_testing",
    "signature QA": "signature_testing",
    "signature quality assurance": "signature_testing",

    # Template Version Control and Lifecycle
    "template version control": "template_version_control",
    "template versioning": "template_version_control",
    "template lifecycle": "template_lifecycle",
    "template lifecycle management": "template_lifecycle",
    "template history": "template_history",
    "template audit trail": "template_audit_trail",
    "template log": "template_audit_trail",
    "template trace": "template_audit_trail",

    # Clause Approval and Governance Workflow
    "clause approval": "clause_approval",
    "clause governance": "clause_governance",
    "clause workflow": "clause_workflow",
    "clause lifecycle": "clause_lifecycle",
    "clause version control": "clause_version_control",

    # Integration with External Data Sources
    "external data source": "external_data_source",
    "external data sources": "external_data_source",
    "external source": "external_data_source",
    "external sources": "external_data_source",
    "integration": "integration",
    "data integration": "integration",
    "external integration": "integration",
    "external data integration": "integration",
    "data source integration": "integration",
    "external API": "external_api",
    "external apis": "external_api",
    "api integration": "external_api",
    "external database": "external_database",
    "external databases": "external_database",
    "database integration": "external_database",
    "external system": "external_system",
    "external systems": "external_system",
    "system integration": "external_system",

    # Multi-Format Output Generation
    "output generation": "output_generation",
    "multi-format output": "multi_format_output",
    "multi-format generation": "multi_format_output",
    "multi-format export": "multi_format_output",
    "multi-format rendering": "multi_format_output",
    "multi-format conversion": "multi_format_output",
    "multi-format distribution": "multi_format_output",
    "multi-format delivery": "multi_format_output",
    "multi-format publishing": "multi_format_output",
    "multi-format output generation": "multi_format_output",
    "pdf output": "pdf_output",
    "word output": "word_output",
    "docx output": "word_output",
    "html output": "html_output",
    "xml output": "xml_output",
    "json output": "json_output",
    "csv output": "csv_output",
    "txt output": "txt_output",
    "text output": "txt_output",
    "output format": "output_format",
    "output formats": "output_format",
    "output customization": "output_customization",
    "output adaptation": "output_customization",
    "output compliance": "output_compliance",
    "output audit": "output_audit",
    "output error handling": "output_error_handling",
    "output recovery": "output_recovery",
    "output scalability": "output_scalability",
    "output performance": "output_performance",
    "output testing": "output_testing",
    "output QA": "output_testing",
    "output quality assurance": "output_testing",

    # Assembly Performance and Scalability
    "assembly performance": "assembly_performance",
    "assembly scalability": "assembly_scalability",
    "assembly optimization": "assembly_performance",
    "assembly speed": "assembly_performance",
    "assembly throughput": "assembly_performance",
    "assembly efficiency": "assembly_performance",
    "assembly load": "assembly_performance",
    "assembly stress": "assembly_performance",
    "assembly benchmarking": "assembly_performance",
    "assembly metrics": "assembly_performance",

    # Assembly Audit Trail and Compliance
    "assembly audit trail": "assembly_audit_trail",
    "assembly log": "assembly_audit_trail",
    "assembly trace": "assembly_audit_trail",
    "assembly compliance": "assembly_compliance",
    "assembly validation": "assembly_compliance",
    "assembly certification": "assembly_compliance",
    "assembly standards": "assembly_compliance",
    "assembly regulatory": "assembly_compliance",
    "assembly regulation": "assembly_compliance",
    "assembly legal": "assembly_compliance",

    # Assembly Error Handling and Recovery
    "assembly error handling": "assembly_error_handling",
    "assembly recovery": "assembly_recovery",
    "assembly failover": "assembly_recovery",
    "assembly fallback": "assembly_recovery",
    "assembly resilience": "assembly_recovery",
    "assembly robustness": "assembly_recovery",
    "assembly exception": "assembly_error_handling",
    "assembly exception handling": "assembly_error_handling",
    "assembly error": "assembly_error_handling",
    "assembly bug": "assembly_error_handling",
    "assembly issue": "assembly_error_handling",

    # Template Testing and Quality Assurance
    "template testing": "template_testing",
    "template QA": "template_testing",
    "template quality assurance": "template_testing",
    "template validation": "template_testing",
    "template verification": "template_testing",
    "template test": "template_testing",
    "template test case": "template_testing",
    "template test suite": "template_testing",
    "template test coverage": "template_testing",
    "template test plan": "template_testing",
    "template bug": "template_testing",
    "template issue": "template_testing",

    # User Interface for Document Assembly
    "user interface": "user_interface",
    "UI": "user_interface",
    "document UI": "user_interface",
    "doc UI": "user_interface",
    "assembly UI": "user_interface",
    "assembly user interface": "user_interface",
    "document user interface": "user_interface",
    "doc user interface": "user_interface",
    "assembly interface": "user_interface",
    "document interface": "user_interface",
    "doc interface": "user_interface",
    "assembly dashboard": "user_interface",
    "document dashboard": "user_interface",
    "doc dashboard": "user_interface",
    "assembly portal": "user_interface",
    "document portal": "user_interface",
    "doc portal": "user_interface",

    # Bulk Document Generation and Batch Processing
    "bulk generation": "bulk_generation",
    "bulk document generation": "bulk_generation",
    "batch processing": "batch_processing",
    "batch document processing": "batch_processing",
    "batch generation": "batch_processing",
    "batch document generation": "batch_processing",
    "bulk processing": "bulk_generation",
    "bulk document processing": "bulk_generation",
    "bulk assembly": "bulk_generation",
    "batch assembly": "batch_processing",
    "bulk output": "bulk_generation",
    "batch output": "batch_processing",

    # Collaborative Document Assembly
    "collaborative assembly": "collaborative_assembly",
    "collaborative document assembly": "collaborative_assembly",
    "collaborative doc assembly": "collaborative_assembly",
    "collaborative editing": "collaborative_assembly",
    "collaborative document editing": "collaborative_assembly",
    "collaborative doc editing": "collaborative_assembly",
    "collaborative workflow": "collaborative_assembly",
    "collaborative process": "collaborative_assembly",
    "collaborative engine": "collaborative_assembly",
    "collaborative framework": "collaborative_assembly",
    "collaborative schema": "collaborative_assembly",
    "collaborative configuration": "collaborative_assembly",
    "collaborative customization": "collaborative_assembly",
    "collaborative adaptation": "collaborative_assembly",
    "collaborative compliance": "collaborative_assembly",
    "collaborative audit": "collaborative_assembly",
    "collaborative error handling": "collaborative_assembly",
    "collaborative recovery": "collaborative_assembly",
    "collaborative scalability": "collaborative_assembly",
    "collaborative performance": "collaborative_assembly",
    "collaborative testing": "collaborative_assembly",
    "collaborative QA": "collaborative_assembly",
    "collaborative quality assurance": "collaborative_assembly",

    # Regulatory Compliance Document Generation
    "regulatory compliance": "regulatory_compliance",
    "regulatory document generation": "regulatory_compliance",
    "regulatory doc generation": "regulatory_compliance",
    "regulatory generation": "regulatory_compliance",
    "regulatory output": "regulatory_compliance",
    "regulatory document output": "regulatory_compliance",
    "regulatory doc output": "regulatory_compliance",
    "regulatory document processing": "regulatory_compliance",
    "regulatory doc processing": "regulatory_compliance",
    "regulatory processing": "regulatory_compliance",
    "regulatory audit": "regulatory_compliance",
    "regulatory error handling": "regulatory_compliance",
    "regulatory recovery": "regulatory_compliance",
    "regulatory scalability": "regulatory_compliance",
    "regulatory performance": "regulatory_compliance",
    "regulatory testing": "regulatory_compliance",
    "regulatory QA": "regulatory_compliance",
    "regulatory quality assurance": "regulatory_compliance",

    # Change Impact Analysis for Templates
    "change impact analysis": "change_impact_analysis",
    "template change impact analysis": "change_impact_analysis",
    "doc change impact analysis": "change_impact_analysis",
    "document change impact analysis": "change_impact_analysis",
    "change analysis": "change_impact_analysis",
    "impact analysis": "change_impact_analysis",
    "template impact analysis": "change_impact_analysis",
    "doc impact analysis": "change_impact_analysis",
    "document impact analysis": "change_impact_analysis",
    "change impact": "change_impact_analysis",
    "template change impact": "change_impact_analysis",
    "doc change impact": "change_impact_analysis",
    "document change impact": "change_impact_analysis",

    # Integration with Contract Lifecycle Management
    "contract lifecycle management": "contract_lifecycle_management",
    "CLM": "contract_lifecycle_management",
    "contract management": "contract_lifecycle_management",
    "contract lifecycle": "contract_lifecycle_management",
    "contract workflow": "contract_lifecycle_management",
    "contract approval": "contract_lifecycle_management",
    "contract governance": "contract_lifecycle_management",
    "contract version control": "contract_lifecycle_management",
    "contract versioning": "contract_lifecycle_management",
    "contract branching": "contract_lifecycle_management",
    "contract merge": "contract_lifecycle_management",
    "contract fork": "contract_lifecycle_management",
    "contract split": "contract_lifecycle_management",
    "contract consolidation": "contract_lifecycle_management",
    "contract rollback": "contract_lifecycle_management",
    "contract revert": "contract_lifecycle_management",
    "contract history": "contract_lifecycle_management",
    "contract audit trail": "contract_lifecycle_management",
    "contract log": "contract_lifecycle_management",
    "contract trace": "contract_lifecycle_management",

    # AI-Assisted Natural Language Generation
    "AI-assisted generation": "ai_assisted_generation",
    "AI assisted generation": "ai_assisted_generation",
    "ai generation": "ai_assisted_generation",
    "natural language generation": "ai_assisted_generation",
    "NLG": "ai_assisted_generation",
    "AI NLG": "ai_assisted_generation",
    "AI natural language generation": "ai_assisted_generation",
    "document generation AI": "ai_assisted_generation",
    "doc generation AI": "ai_assisted_generation",
    "document AI": "ai_assisted_generation",
    "doc AI": "ai_assisted_generation",
    "AI document generation": "ai_assisted_generation",
    "AI doc generation": "ai_assisted_generation",
    "AI document": "ai_assisted_generation",
    "AI doc": "ai_assisted_generation",
    "AI language generation": "ai_assisted_generation",
    "AI text generation": "ai_assisted_generation",
    "AI content generation": "ai_assisted_generation",
    "AI writing": "ai_assisted_generation",
    "AI drafting": "ai_assisted_generation",
    "AI authoring": "ai_assisted_generation",
    "AI editing": "ai_assisted_generation",
    "AI review": "ai_assisted_generation",
    "AI revision": "ai_assisted_generation",
    "AI redlining": "ai_assisted_generation",
    "AI markup": "ai_assisted_generation",
    "AI mark-up": "ai_assisted_generation",
    "AI comparison": "ai_assisted_generation",
    "AI diff": "ai_assisted_generation",
    "AI diffing": "ai_assisted_generation",
    "AI track changes": "ai_assisted_generation",
    "AI change tracking": "ai_assisted_generation",
    "AI audit": "ai_assisted_generation",
    "AI error handling": "ai_assisted_generation",
    "AI recovery": "ai_assisted_generation",
    "AI scalability": "ai_assisted_generation",
    "AI performance": "ai_assisted_generation",
    "AI testing": "ai_assisted_generation",
    "AI QA": "ai_assisted_generation",
    "AI quality assurance": "ai_assisted_generation",
}

# Misspellings, abbreviations, acronyms, and additional synonyms
misspellings_synonyms = {
    "templat": "template",
    "templete": "template",
    "templte": "template",
    "templte arch": "template_architecture",
    "templ arch": "template_architecture",
    "templ desgn": "template_design",
    "claus": "clause",
    "cluase": "clause",
    "clause lib": "clause_library",
    "clause repo": "clause_library",
    "clause tax": "clause_taxonomy",
    "clause org": "clause_organization",
    "cond incl": "conditional_inclusion",
    "cond logic": "conditional_logic",
    "cond clause": "conditional_inclusion",
    "cond template": "conditional_inclusion",
    "cond section": "conditional_inclusion",
    "cond exhibit": "conditional_inclusion",
    "cond schedule": "conditional_inclusion",
    "cond block": "conditional_inclusion",
    "cond paragraph": "conditional_inclusion",
    "cond term": "conditional_inclusion",
    "cond defined term": "conditional_inclusion",
    "cond reference": "conditional_inclusion",
    "cond cross-reference": "conditional_inclusion",
    "cond variable": "conditional_inclusion",
    "cond substitution": "conditional_inclusion",
    "cond binding": "conditional_inclusion",
    "cond data binding": "conditional_inclusion",
    "cond assembly logic": "conditional_logic",
    "var substitution": "variable_substitution",
    "var binding": "variable_binding",
    "var data binding": "variable_binding",
    "var mapping": "variable_mapping",
    "var assignment": "variable_assignment",
    "var definition": "variable_definition",
    "var declaration": "variable_definition",
    "var reference": "variable_reference",
    "var cross-reference": "variable_reference",
    "var value": "variable_value",
    "var input": "variable_input",
    "var output": "variable_output",
    "var parameter": "variable_parameter",
    "var argument": "variable_argument",
    "var placeholder": "variable_placeholder",
    "var token": "variable_token",
    "var field": "variable_field",
    "var slot": "variable_slot",
    "var tag": "variable_tag",
    "var template": "variable_template",
    "var schema": "variable_schema",
    "var configuration": "variable_configuration",
    "var customization": "variable_customization",
    "var adaptation": "variable_customization",
    "var compliance": "variable_compliance",
    "var audit": "variable_audit",
    "var error handling": "variable_error_handling",
    "var recovery": "variable_recovery",
    "var scalability": "variable_scalability",
    "var performance": "variable_performance",
    "var testing": "variable_testing",
    "var QA": "variable_testing",
    "var quality assurance": "variable_testing",
    "crossref mgmt": "cross_reference_management",
    "crossref integrity": "cross_reference_integrity",
    "crossref validation": "cross_reference_validation",
    "crossref audit": "cross_reference_audit",
    "crossref error handling": "cross_reference_error_handling",
    "crossref recovery": "cross_reference_recovery",
    "crossref scalability": "cross_reference_scalability",
    "crossref performance": "cross_reference_performance",
    "crossref testing": "cross_reference_testing",
    "crossref QA": "cross_reference_testing",
    "crossref quality assurance": "cross_reference_testing",
    "crossref compliance": "cross_reference_compliance",
    "crossref customization": "cross_reference_customization",
    "crossref adaptation": "cross_reference_customization",
    "crossref configuration": "cross_reference_configuration",
    "crossref schema": "cross_reference_schema",
    "crossref template": "cross_reference_template",
    "def term": "defined_term",
    "def terms": "defined_term",
    "definition mgmt": "defined_term_management",
    "definition consistency": "defined_term_consistency",
    "definition validation": "defined_term_validation",
    "definition audit": "defined_term_audit",
    "definition error handling": "defined_term_error_handling",
    "definition recovery": "defined_term_recovery",
    "definition scalability": "defined_term_scalability",
    "definition performance": "defined_term_performance",
    "definition testing": "defined_term_testing",
    "definition QA": "defined_term_testing",
    "definition quality assurance": "defined_term_testing",
    "definition compliance": "defined_term_compliance",
    "definition customization": "defined_term_customization",
    "definition adaptation": "defined_term_customization",
    "definition configuration": "defined_term_configuration",
    "definition schema": "defined_term_schema",
    "definition template": "defined_term_template",
    "exh": "exhibit",
    "exhibt": "exhibit",
    "sched": "schedule",
    "exh auto-gen": "exhibit_auto_generation",
    "sched auto-gen": "schedule_auto_generation",
    "exh gen": "exhibit_auto_generation",
    "sched gen": "schedule_auto_generation",
    "exh creation": "exhibit_auto_generation",
    "sched creation": "schedule_auto_generation",
    "exh assembly": "exhibit_auto_generation",
    "sched assembly": "schedule_auto_generation",
    "exh template": "exhibit_template",
    "sched template": "schedule_template",
    "exh customization": "exhibit_customization",
    "sched customization": "schedule_customization",
    "exh adaptation": "exhibit_customization",
    "sched adaptation": "schedule_customization",
    "exh compliance": "exhibit_compliance",
    "sched compliance": "schedule_compliance",
    "exh audit": "exhibit_audit",
    "sched audit": "schedule_audit",
    "exh error handling": "exhibit_error_handling",
    "sched error handling": "schedule_error_handling",
    "exh recovery": "exhibit_recovery",
    "sched recovery": "schedule_recovery",
    "exh scalability": "exhibit_scalability",
    "sched scalability": "schedule_scalability",
    "exh performance": "exhibit_performance",
    "sched performance": "schedule_performance",
    "exh testing": "exhibit_testing",
    "sched testing": "schedule_testing",
    "exh QA": "exhibit_testing",
    "sched QA": "schedule_testing",
    "exh quality assurance": "exhibit_testing",
    "sched quality assurance": "schedule_testing",
    "redlineing": "redlining",
    "redlinning": "redlining",
    "redlined document": "redlining",
    "doc comparison": "document_comparison",
    "doc diff": "document_comparison",
    "doc differences": "document_comparison",
    "doc version comparison": "document_comparison",
    "doc change analysis": "document_comparison",
    "doc audit": "document_audit",
    "doc error handling": "document_error_handling",
    "doc recovery": "document_recovery",
    "doc scalability": "document_scalability",
    "doc performance": "document_performance",
    "doc testing": "document_testing",
    "doc QA": "document_testing",
    "doc quality assurance": "document_testing",
    "ver control": "version_control",
    "doc ver control": "version_control",
    "vering": "version_control",
    "doc branching": "branching",
    "doc merge": "merge",
    "doc fork": "fork",
    "doc split": "split",
    "doc consolidation": "consolidation",
    "doc rollback": "rollback",
    "doc revert": "rollback",
    "doc history": "history",
    "doc audit trail": "audit_trail",
    "doc log": "audit_trail",
    "doc trace": "audit_trail",
    "sig block": "signature_block",
    "sig blocks": "signature_block",
    "sig formatting": "signature_formatting",
    "sig standards": "signature_standards",
    "sig template": "signature_template",
    "sig schema": "signature_schema",
    "sig configuration": "signature_configuration",
    "sig customization": "signature_customization",
    "sig adaptation": "signature_customization",
    "sig compliance": "signature_compliance",
    "sig audit": "signature_audit",
    "sig error handling": "signature_error_handling",
    "sig recovery": "signature_recovery",
    "sig scalability": "signature_scalability",
    "sig performance": "signature_performance",
    "sig testing": "signature_testing",
    "sig QA": "signature_testing",
    "sig quality assurance": "signature_testing",
    "external datasource": "external_data_source",
    "external datasources": "external_data_source",
    "ext source": "external_data_source",
    "ext sources": "external_data_source",
    "ext integration": "integration",
    "ext data integration": "integration",
    "ext api": "external_api",
    "ext apis": "external_api",
    "ext database": "external_database",
    "ext databases": "external_database",
    "ext system": "external_system",
    "ext systems": "external_system",
    "multi format output": "multi_format_output",
    "multi format generation": "multi_format_output",
    "multi format export": "multi_format_output",
    "multi format rendering": "multi_format_output",
    "multi format conversion": "multi_format_output",
    "multi format distribution": "multi_format_output",
    "multi format delivery": "multi_format_output",
    "multi format publishing": "multi_format_output",
    "multi format output generation": "multi_format_output",
    "output gen": "output_generation",
    "pdf gen": "pdf_output",
    "word gen": "word_output",
    "docx gen": "word_output",
    "html gen": "html_output",
    "xml gen": "xml_output",
    "json gen": "json_output",
    "csv gen": "csv_output",
    "txt gen": "txt_output",
    "text gen": "txt_output",
    "output fmt": "output_format",
    "output fmts": "output_format",
    "output custom": "output_customization",
    "output adapt": "output_customization",
    "output comp": "output_compliance",
    "output aud": "output_audit",
    "output err handling": "output_error_handling",
    "output recov": "output_recovery",
    "output scale": "output_scalability",
    "output perf": "output_performance",
    "output test": "output_testing",
    "output QA": "output_testing",
    "output QA": "output_testing",
    "output qual assurance": "output_testing",
    "assembly perf": "assembly_performance",
    "assembly scale": "assembly_scalability",
    "assembly opt": "assembly_performance",
    "assembly spd": "assembly_performance",
    "assembly thrpt": "assembly_performance",
    "assembly eff": "assembly_performance",
    "assembly ld": "assembly_performance",
    "assembly strss": "assembly_performance",
    "assembly bench": "assembly_performance",
    "assembly met": "assembly_performance",
    "assembly aud trail": "assembly_audit_trail",
    "assembly lg": "assembly_audit_trail",
    "assembly trc": "assembly_audit_trail",
    "assembly comp": "assembly_compliance",
    "assembly val": "assembly_compliance",
    "assembly cert": "assembly_compliance",
    "assembly stds": "assembly_compliance",
    "assembly reg": "assembly_compliance",
    "assembly legal": "assembly_compliance",
    "assembly err handling": "assembly_error_handling",
    "assembly recov": "assembly_recovery",
    "assembly fail": "assembly_recovery",
    "assembly fallback": "assembly_recovery",
    "assembly resil": "assembly_recovery",
    "assembly robust": "assembly_recovery",
    "assembly exc": "assembly_error_handling",
    "assembly exc handling": "assembly_error_handling",
    "assembly bug": "assembly_error_handling",
    "assembly issue": "assembly_error_handling",
    "template val": "template_testing",
    "template verif": "template_testing",
    "template tst": "template_testing",
    "template tst case": "template_testing",
    "template tst suite": "template_testing",
    "template tst coverage": "template_testing",
    "template tst plan": "template_testing",
    "template bug": "template_testing",
    "template issue": "template_testing",
    "UI dashboard": "user_interface",
    "UI portal": "user_interface",
    "bulk gen": "bulk_generation",
    "batch gen": "batch_processing",
    "bulk proc": "bulk_generation",
    "batch proc": "batch_processing",
    "bulk asm": "bulk_generation",
    "batch asm": "batch_processing",
    "bulk out": "bulk_generation",
    "batch out": "batch_processing",
    "collab asm": "collaborative_assembly",
    "collab doc asm": "collaborative_assembly",
    "collab edit": "collaborative_assembly",
    "collab doc edit": "collaborative_assembly",
    "collab workflow": "collaborative_assembly",
    "collab process": "collaborative_assembly",
    "collab engine": "collaborative_assembly",
    "collab framework": "collaborative_assembly",
    "collab schema": "collaborative_assembly",
    "collab configuration": "collaborative_assembly",
    "collab customization": "collaborative_assembly",
    "collab adaptation": "collaborative_assembly",
    "collab compliance": "collaborative_assembly",
    "collab audit": "collaborative_assembly",
    "collab error handling": "collaborative_assembly",
    "collab recovery": "collaborative_assembly",
    "collab scalability": "collaborative_assembly",
    "collab performance": "collaborative_assembly",
    "collab testing": "collaborative_assembly",
    "collab QA": "collaborative_assembly",
    "collab quality assurance": "collaborative_assembly",
    "reg compliance": "regulatory_compliance",
    "reg doc gen": "regulatory_compliance",
    "reg gen": "regulatory_compliance",
    "reg out": "regulatory_compliance",
    "reg doc out": "regulatory_compliance",
    "reg doc proc": "regulatory_compliance",
    "reg proc": "regulatory_compliance",
    "reg audit": "regulatory_compliance",
    "reg err handling": "regulatory_compliance",
    "reg recovery": "regulatory_compliance",
    "reg scalability": "regulatory_compliance",
    "reg performance": "regulatory_compliance",
    "reg testing": "regulatory_compliance",
    "reg QA": "regulatory_compliance",
    "reg quality assurance": "regulatory_compliance",
    "change impact": "change_impact_analysis",
    "change analysis": "change_impact_analysis",
    "impact analysis": "change_impact_analysis",
    "template impact analysis": "change_impact_analysis",
    "doc impact analysis": "change_impact_analysis",
    "contract lifecycle mgmt": "contract_lifecycle_management",
    "contract mgmt": "contract_lifecycle_management",
    "contract LC": "contract_lifecycle_management",
    "contract workflow": "contract_lifecycle_management",
    "contract approval": "contract_lifecycle_management",
    "contract governance": "contract_lifecycle_management",
    "contract ver control": "contract_lifecycle_management",
    "contract vering": "contract_lifecycle_management",
    "contract branching": "contract_lifecycle_management",
    "contract merge": "contract_lifecycle_management",
    "contract fork": "contract_lifecycle_management",
    "contract split": "contract_lifecycle_management",
    "contract consolidation": "contract_lifecycle_management",
    "contract rollback": "contract_lifecycle_management",
    "contract revert": "contract_lifecycle_management",
    "contract history": "contract_lifecycle_management",
    "contract audit trail": "contract_lifecycle_management",
    "contract log": "contract_lifecycle_management",
    "contract trace": "contract_lifecycle_management",
    "AI gen": "ai_assisted_generation",
    "AI NLG": "ai_assisted_generation",
    "AI doc gen": "ai_assisted_generation",
    "AI doc": "ai_assisted_generation",
    "AI lang gen": "ai_assisted_generation",
    "AI text gen": "ai_assisted_generation",
    "AI content gen": "ai_assisted_generation",
    "AI writing": "ai_assisted_generation",
    "AI drafting": "ai_assisted_generation",
    "AI authoring": "ai_assisted_generation",
    "AI editing": "ai_assisted_generation",
    "AI review": "ai_assisted_generation",
    "AI revision": "ai_assisted_generation",
    "AI redlining": "ai_assisted_generation",
    "AI markup": "ai_assisted_generation",
    "AI mark-up": "ai_assisted_generation",
    "AI comparison": "ai_assisted_generation",
    "AI diff": "ai_assisted_generation",
    "AI diffing": "ai_assisted_generation",
    "AI track changes": "ai_assisted_generation",
    "AI change tracking": "ai_assisted_generation",
    "AI audit": "ai_assisted_generation",
    "AI error handling": "ai_assisted_generation",
    "AI recovery": "ai_assisted_generation",
    "AI scalability": "ai_assisted_generation",
    "AI performance": "ai_assisted_generation",
    "AI testing": "ai_assisted_generation",
    "AI QA": "ai_assisted_generation",
    "AI quality assurance": "ai_assisted_generation",
}

SEMANTIC_MAP.update(misspellings_synonyms)

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)