import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "SYN05_negotiation_strategist"
SEMANTIC_MAP_ENGINE = "SYN05"

SEMANTIC_MAP = {
    # Principled Negotiation Framework
    "principled negotiation": "principled_negotiation",
    "getting to yes": "principled_negotiation",
    "interest-based negotiation": "principled_negotiation",
    "integrative negotiation": "integrative_negotiation",
    "win-win negotiation": "integrative_negotiation",
    "distributive negotiation": "distributive_negotiation",
    "win-lose negotiation": "distributive_negotiation",
    "positional bargaining": "distributive_negotiation",
    "hard bargaining": "distributive_negotiation",
    "soft bargaining": "principled_negotiation",
    "mutual gains": "integrative_negotiation",
    "mutual gains approach": "integrative_negotiation",
    "separating people from the problem": "principled_negotiation",
    "focus on interests not positions": "principled_negotiation",
    "invent options for mutual gain": "integrative_negotiation",
    "objective criteria": "objective_criteria",
    "objective standards": "objective_criteria",
    "objective benchmarks": "objective_criteria",
    "criteria of legitimacy": "objective_criteria",
    "legitimate standards": "objective_criteria",
    "legitimacy": "objective_criteria",
    "people problem": "people_problem",
    "relationship issues": "people_problem",
    "communication barriers": "people_problem",
    "active listening": "active_listening",
    "listening skills": "active_listening",
    "assertive communication": "assertive_communication",
    "empathic listening": "active_listening",
    "empathy": "active_listening",
    "paraphrasing": "active_listening",
    "reframing": "reframing",
    "reframe": "reframing",
    "reframing issues": "reframing",
    "BATNA": "batna",
    "batna": "batna",
    "Best Alternative to a Negotiated Agreement": "batna",
    "best alternative": "batna",
    "walk-away alternative": "batna",
    "fallback option": "batna",
    "reservation price": "reservation_price",
    "walk-away point": "reservation_price",
    "bottom line": "reservation_price",
    "minimum acceptable": "reservation_price",
    "resistance point": "reservation_price",
    "ZOPA": "zopa",
    "zone of possible agreement": "zopa",
    "bargaining zone": "zopa",
    "overlap": "zopa",
    "negotiation range": "zopa",
    "settlement range": "zopa",
    "anchoring": "anchoring",
    "anchor": "anchoring",
    "anchoring heuristic": "anchoring",
    "adjustment heuristic": "adjustment_heuristic",
    "anchoring and adjustment": "anchoring_adjustment",
    "anchoring and adjustment heuristic": "anchoring_adjustment",
    "first offer": "anchoring",
    "opening offer": "anchoring",
    "extreme offer": "anchoring",
    "concession": "concession",
    "concessions": "concession",
    "concession strategy": "concession_strategy",
    "concession pattern": "concession_strategy",
    "concession making": "concession_strategy",
    "reciprocal concessions": "concession_strategy",
    "integrative": "integrative_negotiation",
    "integrative strategy": "integrative_negotiation",
    "value creation": "integrative_negotiation",
    "expanding the pie": "integrative_negotiation",
    "logrolling": "logrolling",
    "trade-offs": "logrolling",
    "package deals": "logrolling",
    "distributive": "distributive_negotiation",
    "distributive strategy": "distributive_negotiation",
    "claiming value": "distributive_negotiation",
    "fixed pie": "distributive_negotiation",
    "zero-sum": "distributive_negotiation",
    "win-lose": "distributive_negotiation",
    "lose-win": "distributive_negotiation",
    "multiparty negotiation": "multiparty_negotiation",
    "multi-party negotiation": "multiparty_negotiation",
    "multiparty dynamics": "multiparty_negotiation",
    "coalition building": "coalition_building",
    "coalitions": "coalition_building",
    "alliance formation": "coalition_building",
    "group negotiation": "multiparty_negotiation",
    "impasse": "impasse",
    "deadlock": "impasse",
    "stalemate": "impasse",
    "impasse breaking": "impasse_breaking",
    "dispute resolution": "dispute_resolution",
    "resolution ladder": "dispute_resolution_ladder",
    "dispute resolution ladder": "dispute_resolution_ladder",
    "escalation ladder": "dispute_resolution_ladder",
    "mediation": "mediation",
    "arbitration": "arbitration",
    "third-party intervention": "third_party_intervention",
    "neutral facilitator": "third_party_intervention",
    "deal structure": "deal_structure",
    "deal terms": "deal_structure",
    "term prioritization": "term_prioritization",
    "prioritizing interests": "term_prioritization",
    "trade-off analysis": "term_prioritization",
    "information asymmetry": "information_asymmetry",
    "asymmetric information": "information_asymmetry",
    "information advantage": "information_asymmetry",
    "signaling": "signaling",
    "signal": "signaling",
    "signaling intent": "signaling",
    "information disclosure": "signaling",
    "strategic disclosure": "signaling",
    "Mnookin framework": "mnookin_framework",
    "beyond winning": "mnookin_framework",
    "mnookin beyond winning": "mnookin_framework",
    "mnookin": "mnookin_framework",
    "game theory": "game_theory",
    "game theory applications": "game_theory",
    "prisoner's dilemma": "game_theory",
    "zero sum game": "game_theory",
    "non-zero sum": "game_theory",
    "nash equilibrium": "game_theory",
    "deadline pressure": "deadline_pressure",
    "time tactics": "deadline_pressure",
    "time pressure": "deadline_pressure",
    "last minute": "deadline_pressure",
    "time constraint": "deadline_pressure",
    "exploding offer": "deadline_pressure",
    "cross-cultural negotiation": "cross_cultural_negotiation",
    "cross cultural negotiation": "cross_cultural_negotiation",
    "cultural dynamics": "cross_cultural_negotiation",
    "cultural differences": "cross_cultural_negotiation",
    "high context": "cross_cultural_negotiation",
    "low context": "cross_cultural_negotiation",
    "email negotiation": "virtual_negotiation",
    "virtual negotiation": "virtual_negotiation",
    "e-negotiation": "virtual_negotiation",
    "online negotiation": "virtual_negotiation",
    "asynchronous negotiation": "virtual_negotiation",
    "power dynamics": "power_dynamics",
    "leverage": "power_dynamics",
    "sources of power": "power_dynamics",
    "power imbalance": "power_dynamics",
    "power tactics": "power_dynamics",
    "reactive devaluation": "reactive_devaluation",
    "psychological biases": "psychological_biases",
    "cognitive bias": "psychological_biases",
    "confirmation bias": "psychological_biases",
    "framing effect": "psychological_biases",
    "loss aversion": "psychological_biases",
    "endowment effect": "psychological_biases",
    "negotiating with agents": "agents_and_principals",
    "agents and principals": "agents_and_principals",
    "principal-agent problem": "agents_and_principals",
    "contingent contract": "contingent_contract",
    "contingent contracts": "contingent_contract",
    "risk management": "risk_management",
    "risk allocation": "risk_management",
    "post-settlement settlement": "post_settlement_settlement",
    "post settlement settlement": "post_settlement_settlement",
    "continuous improvement": "continuous_improvement",
    "after action review": "continuous_improvement",
    "negotiation ethics": "negotiation_ethics",
    "ethics": "negotiation_ethics",
    "ethical negotiation": "negotiation_ethics",
    "deception": "deception",
    "lying": "deception",
    "misrepresentation": "deception",
    "internal alignment": "internal_alignment",
    "stakeholder management": "stakeholder_management",
    "stakeholder alignment": "stakeholder_management",
    "internal consensus": "internal_alignment",
    "gender in negotiation": "gender_diversity_negotiation",
    "diversity in negotiation": "gender_diversity_negotiation",
    "gender bias": "gender_diversity_negotiation",
    "diversity bias": "gender_diversity_negotiation",
    "relationship focus": "relationship_focus",
    "transaction focus": "transaction_focus",
    "relationship vs transaction": "relationship_vs_transaction",
    "relationship vs. transaction": "relationship_vs_transaction",
    "relationship-oriented": "relationship_focus",
    "transaction-oriented": "transaction_focus",
    "relationship management": "relationship_focus",
    "trust building": "relationship_focus",
    "rapport": "relationship_focus",
    "trust": "relationship_focus",
    "trustworthiness": "relationship_focus",
    "credibility": "relationship_focus",
    "fairness": "negotiation_ethics",
    "integrity": "negotiation_ethics",
    "honesty": "negotiation_ethics",
    "bluffing": "deception",
    "good faith": "negotiation_ethics",
    "bad faith": "deception",
    "hardball tactics": "distributive_negotiation",
    "hardball": "distributive_negotiation",
    "soft tactics": "principled_negotiation",
    "soft": "principled_negotiation",
    "win-win": "integrative_negotiation",
    "win lose": "distributive_negotiation",
    "lose lose": "distributive_negotiation",
    "collaborative negotiation": "integrative_negotiation",
    "competitive negotiation": "distributive_negotiation",
    "collaboration": "integrative_negotiation",
    "competition": "distributive_negotiation",
    "compromise": "concession_strategy",
    "accommodation": "concession_strategy",
    "avoidance": "impasse",
    "forcing": "distributive_negotiation",
    "problem solving": "integrative_negotiation",
    "problem-solving": "integrative_negotiation",
    "joint problem solving": "integrative_negotiation",
    "joint gains": "integrative_negotiation",
    "separating people": "people_problem",
    "separate people": "people_problem",
    "separating issues": "reframing",
    "issue framing": "reframing",
    "issue definition": "reframing",
    "issue identification": "reframing",
    "BATNA analysis": "batna_analysis",
    "batna analysis": "batna_analysis",
    "analyzing batna": "batna_analysis",
    "batna development": "batna_analysis",
    "reservation value": "reservation_price",
    "walkaway point": "reservation_price",
    "walk away point": "reservation_price",
    "walk-away": "reservation_price",
    "walkaway": "reservation_price",
    "aspiration price": "aspiration_price",
    "target price": "aspiration_price",
    "aspiration level": "aspiration_price",
    "target point": "aspiration_price",
    "aspiration": "aspiration_price",
    "opening position": "anchoring",
    "opening statement": "anchoring",
    "opening demand": "anchoring",
    "counteroffer": "concession_strategy",
    "counter offer": "concession_strategy",
    "reciprocity": "concession_strategy",
    "reciprocal": "concession_strategy",
    "integrative solution": "integrative_negotiation",
    "integrative outcome": "integrative_negotiation",
    "distributive outcome": "distributive_negotiation",
    "distributive solution": "distributive_negotiation",
    "expanding the pie": "integrative_negotiation",
    "claiming the pie": "distributive_negotiation",
    "slicing the pie": "distributive_negotiation",
    "splitting the difference": "compromise",
    "middle ground": "compromise",
    "fixed sum": "distributive_negotiation",
    "fixed-sum": "distributive_negotiation",
    "reservation": "reservation_price",
    "walk away": "reservation_price",
    "walkaway value": "reservation_price",
    "walk-away value": "reservation_price",
    "zone of agreement": "zopa",
    "agreement zone": "zopa",
    "negotiation zone": "zopa",
    "negotiation table": "negotiation_table",
    "table dynamics": "negotiation_table",
    "table tactics": "negotiation_table",
    "negotiation process": "negotiation_process",
    "negotiation stages": "negotiation_process",
    "negotiation steps": "negotiation_process",
    "negotiation preparation": "negotiation_preparation",
    "preparation": "negotiation_preparation",
    "pre-negotiation": "negotiation_preparation",
    "pre negotiation": "negotiation_preparation",
    "negotiation planning": "negotiation_preparation",
    "planning": "negotiation_preparation",
    "agenda setting": "negotiation_preparation",
    "agenda": "negotiation_preparation",
    "opening": "anchoring",
    "bargaining": "bargaining",
    "closing": "closing",
    "agreement": "agreement",
    "settlement": "agreement",
    "final agreement": "agreement",
    "contract": "agreement",
    "memorandum of understanding": "agreement",
    "mou": "agreement",
    "letter of intent": "agreement",
    "loi": "agreement",
    "deal": "agreement",
    "negotiation outcome": "agreement",
    "outcome": "agreement",
    "negotiation result": "agreement",
    "result": "agreement",
    "negotiation success": "agreement",
    "success": "agreement",
    "failure": "impasse",
    "no deal": "impasse",
    "walk away": "reservation_price",
    "walked away": "reservation_price",
    "walks away": "reservation_price",
    "walk-away": "reservation_price",
    "walkaway": "reservation_price",
    "agreement reached": "agreement",
    "no agreement": "impasse",
    "impasse reached": "impasse",
    "deadlock reached": "impasse",
    "escalation": "dispute_resolution_ladder",
    "de-escalation": "dispute_resolution_ladder",
    "cooling-off": "dispute_resolution_ladder",
    "cooling off": "dispute_resolution_ladder",
    "cool-off": "dispute_resolution_ladder",
    "cool off": "dispute_resolution_ladder",
    "third party": "third_party_intervention",
    "third-party": "third_party_intervention",
    "neutral party": "third_party_intervention",
    "facilitator": "third_party_intervention",
    "ombudsman": "third_party_intervention",
    "mediator": "mediation",
    "arbitrator": "arbitration",
    "binding arbitration": "arbitration",
    "non-binding arbitration": "arbitration",
    "conciliation": "mediation",
    "conciliation process": "mediation",
    "negotiation team": "negotiation_team",
    "team negotiation": "negotiation_team",
    "team dynamics": "negotiation_team",
    "internal team": "negotiation_team",
    "internal communication": "internal_alignment",
    "internal negotiation": "internal_alignment",
    "stakeholder": "stakeholder_management",
    "stakeholders": "stakeholder_management",
    "stakeholder interests": "stakeholder_management",
    "stakeholder analysis": "stakeholder_management",
    "stakeholder mapping": "stakeholder_management",
    "stakeholder engagement": "stakeholder_management",
    "stakeholder buy-in": "stakeholder_management",
    "buy-in": "stakeholder_management",
    "buy in": "stakeholder_management",
    "buyin": "stakeholder_management",
    "principal": "agents_and_principals",
    "agent": "agents_and_principals",
    "principal agent": "agents_and_principals",
    "agent principal": "agents_and_principals",
    "principal-agent": "agents_and_principals",
    "agent-principal": "agents_and_principals",
    "contingency": "contingent_contract",
    "contingencies": "contingent_contract",
    "contingent": "contingent_contract",
    "risk": "risk_management",
    "uncertainty": "risk_management",
    "risk sharing": "risk_management",
    "risk allocation": "risk_management",
    "risk mitigation": "risk_management",
    "risk assessment": "risk_management",
    "risk analysis": "risk_management",
    "post negotiation": "post_settlement_settlement",
    "post-negotiation": "post_settlement_settlement",
    "post settlement": "post_settlement_settlement",
    "after negotiation": "post_settlement_settlement",
    "post-mortem": "continuous_improvement",
    "lessons learned": "continuous_improvement",
    "feedback": "continuous_improvement",
    "review": "continuous_improvement",
    "improvement": "continuous_improvement",
    "continuous learning": "continuous_improvement",
    "learning": "continuous_improvement",
    "ethics in negotiation": "negotiation_ethics",
    "ethical issues": "negotiation_ethics",
    "unethical": "deception",
    "unethical behavior": "deception",
    "misleading": "deception",
    "truthfulness": "negotiation_ethics",
    "transparency": "negotiation_ethics",
    "honest": "negotiation_ethics",
    "dishonest": "deception",
    "deceit": "deception",
    "trickery": "deception",
    "manipulation": "deception",
    "manipulative": "deception",
    "internal politics": "internal_alignment",
    "organizational politics": "internal_alignment",
    "organizational alignment": "internal_alignment",
    "internal stakeholders": "internal_alignment",
    "gender": "gender_diversity_negotiation",
    "diversity": "gender_diversity_negotiation",
    "diversity management": "gender_diversity_negotiation",
    "gender diversity": "gender_diversity_negotiation",
    "diversity issues": "gender_diversity_negotiation",
    "gender issues": "gender_diversity_negotiation",
    "diversity challenges": "gender_diversity_negotiation",
    "gender challenges": "gender_diversity_negotiation",
    "diversity negotiation": "gender_diversity_negotiation",
    "gender negotiation": "gender_diversity_negotiation",
    "relationship": "relationship_focus",
    "transaction": "transaction_focus",
    "relationship orientation": "relationship_focus",
    "transaction orientation": "transaction_focus",
    "relationship-based": "relationship_focus",
    "transaction-based": "transaction_focus",
    "relationship building": "relationship_focus",
    "relationship development": "relationship_focus",
    "transactional": "transaction_focus",
    "relational": "relationship_focus",
    "relationship value": "relationship_focus",
    "transaction value": "transaction_focus",
    "relationship capital": "relationship_focus",
    "transaction cost": "transaction_focus",
    "relationship cost": "relationship_focus",
    "transactional negotiation": "transaction_focus",
    "relational negotiation": "relationship_focus",
    "relationship negotiation": "relationship_focus",
    "transaction negotiation": "transaction_focus",
    "relationship vs transaction focus": "relationship_vs_transaction",
    "relationship vs. transaction focus": "relationship_vs_transaction",
    "relationship/transaction": "relationship_vs_transaction",
    "relationship-transaction": "relationship_vs_transaction",
    "relationship or transaction": "relationship_vs_transaction",
    "transaction or relationship": "relationship_vs_transaction",
    # Misspellings and variants
    "batnas": "batna",
    "zopas": "zopa",
    "anchoringg": "anchoring",
    "concesion": "concession",
    "concesions": "concession",
    "concesion strategy": "concession_strategy",
    "distributve negotiation": "distributive_negotiation",
    "integrattive negotiation": "integrative_negotiation",
    "negociation": "negotiation",
    "negociator": "negotiator",
    "negoiation": "negotiation",
    "negoitation": "negotiation",
    "negoatiation": "negotiation",
    "negoatiator": "negotiator",
    "negoitator": "negotiator",
    "negoiator": "negotiator",
    "nego": "negotiation",
    "neg": "negotiation",
    "bargaing": "bargaining",
    "bargining": "bargaining",
    "barganing": "bargaining",
    "barganing zone": "zopa",
    "barganing range": "zopa",
    "arbitation": "arbitration",
    "arbitraion": "arbitration",
    "mediaton": "mediation",
    "mediationn": "mediation",
    "mediatior": "mediator",
    "arbitator": "arbitrator",
    "concilliation": "mediation",
    "concilliator": "mediator",
    "escaltion": "dispute_resolution_ladder",
    "deescalation": "dispute_resolution_ladder",
    "stakehoder": "stakeholder_management",
    "stakehoders": "stakeholder_management",
    "stakehldr": "stakeholder_management",
    "stakehldrs": "stakeholder_management",
    "coaltion": "coalition_building",
    "coalittion": "coalition_building",
    "coalitons": "coalition_building",
    "collaboratve negotiation": "integrative_negotiation",
    "collaborative negotation": "integrative_negotiation",
    "collaborative negociation": "integrative_negotiation",
    "collaborative negotitation": "integrative_negotiation",
    "collaborative negotioation": "integrative_negotiation",
    "collaborative negotioator": "negotiator",
    "collaborative negotator": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotatior": "negotiator",
    "collaborative negotat