import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MATH08_engine_team"
SEMANTIC_MAP_ENGINE = "MATH08_graph_theory"

SEMANTIC_MAP = {
    # Core graph theory terms
    "graph": "graph",
    "graphs": "graph",
    "digraph": "directed_graph",
    "directed graph": "directed_graph",
    "undirected graph": "undirected_graph",
    "simple graph": "simple_graph",
    "multigraph": "multigraph",
    "weighted graph": "weighted_graph",
    "unweighted graph": "unweighted_graph",
    "vertex": "vertex",
    "vertices": "vertex",
    "node": "vertex",
    "nodes": "vertex",
    "edge": "edge",
    "edges": "edge",
    "arc": "edge",
    "arcs": "edge",
    "link": "edge",
    "links": "edge",
    "adjacent": "adjacent",
    "adjacency": "adjacent",
    "adjacency matrix": "adjacency_matrix",
    "adjacency list": "adjacency_list",
    "incidence matrix": "incidence_matrix",
    "degree": "degree",
    "degrees": "degree",
    "in-degree": "in_degree",
    "out-degree": "out_degree",
    "indegree": "in_degree",
    "outdegree": "out_degree",
    "valency": "degree",
    "neighbor": "neighbor",
    "neighbour": "neighbor",
    "neighbours": "neighbor",
    "neighbors": "neighbor",
    "path": "path",
    "paths": "path",
    "walk": "walk",
    "walks": "walk",
    "trail": "trail",
    "trails": "trail",
    "cycle": "cycle",
    "cycles": "cycle",
    "circuit": "cycle",
    "circuits": "cycle",
    "closed walk": "cycle",
    "open walk": "walk",
    "loop": "loop",
    "loops": "loop",
    "self-loop": "loop",
    "parallel edges": "parallel_edges",
    "multiple edges": "parallel_edges",
    "connected": "connected",
    "connectivity": "connected",
    "disconnected": "disconnected",
    "component": "component",
    "components": "component",
    "connected component": "component",
    "strongly connected": "strongly_connected",
    "weakly connected": "weakly_connected",
    "strong connectivity": "strongly_connected",
    "weak connectivity": "weakly_connected",
    "bridge": "bridge",
    "bridges": "bridge",
    "cut-edge": "bridge",
    "cut edge": "bridge",
    "cut-vertex": "cut_vertex",
    "cut vertex": "cut_vertex",
    "articulation point": "cut_vertex",
    "articulation points": "cut_vertex",
    "block": "block",
    "blocks": "block",
    "clique": "clique",
    "cliques": "clique",
    "complete graph": "complete_graph",
    "complete graphs": "complete_graph",
    "k-complete graph": "complete_graph",
    "K_n": "complete_graph",
    "empty graph": "empty_graph",
    "null graph": "empty_graph",
    "subgraph": "subgraph",
    "subgraphs": "subgraph",
    "induced subgraph": "induced_subgraph",
    "spanning subgraph": "spanning_subgraph",
    "spanning tree": "spanning_tree",
    "spanning trees": "spanning_tree",
    "tree": "tree",
    "trees": "tree",
    "forest": "forest",
    "forests": "forest",
    "leaf": "leaf",
    "leaves": "leaf",
    "root": "root",
    "roots": "root",
    "branch": "branch",
    "branches": "branch",
    "binary tree": "binary_tree",
    "binary trees": "binary_tree",
    "directed acyclic graph": "dag",
    "DAG": "dag",
    "dags": "dag",
    "acyclic graph": "acyclic_graph",
    "cycle-free graph": "acyclic_graph",
    "planar graph": "planar_graph",
    "planar graphs": "planar_graph",
    "nonplanar graph": "nonplanar_graph",
    "non-planar graph": "nonplanar_graph",
    "bipartite graph": "bipartite_graph",
    "bipartite graphs": "bipartite_graph",
    "complete bipartite graph": "complete_bipartite_graph",
    "K_mn": "complete_bipartite_graph",
    "matching": "matching",
    "matchings": "matching",
    "maximum matching": "maximum_matching",
    "maximal matching": "maximal_matching",
    "perfect matching": "perfect_matching",
    "vertex cover": "vertex_cover",
    "vertex covers": "vertex_cover",
    "edge cover": "edge_cover",
    "edge covers": "edge_cover",
    "independent set": "independent_set",
    "independent sets": "independent_set",
    "stable set": "independent_set",
    "clique number": "clique_number",
    "chromatic number": "chromatic_number",
    "coloring": "coloring",
    "colouring": "coloring",
    "vertex coloring": "vertex_coloring",
    "edge coloring": "edge_coloring",
    "vertex colouring": "vertex_coloring",
    "edge colouring": "edge_coloring",
    "proper coloring": "proper_coloring",
    "proper colouring": "proper_coloring",
    "Hamiltonian cycle": "hamiltonian_cycle",
    "Hamiltonian path": "hamiltonian_path",
    "Eulerian cycle": "eulerian_cycle",
    "Eulerian path": "eulerian_path",
    "Euler circuit": "eulerian_cycle",
    "Euler path": "eulerian_path",
    "Hamilton circuit": "hamiltonian_cycle",
    "Hamilton path": "hamiltonian_path",
    "isomorphism": "isomorphism",
    "isomorphic": "isomorphism",
    "graph isomorphism": "isomorphism",
    "automorphism": "automorphism",
    "automorphisms": "automorphism",
    "homeomorphism": "homeomorphism",
    "minor": "minor",
    "graph minor": "minor",
    "contract": "contract",
    "contraction": "contraction",
    "expand": "expand",
    "expansion": "expansion",
    "embedding": "embedding",
    "embeddings": "embedding",
    "map": "embedding",
    "mapping": "embedding",
    "label": "label",
    "labels": "label",
    "labeling": "labeling",
    "labelling": "labeling",
    "vertex labeling": "vertex_labeling",
    "edge labeling": "edge_labeling",
    "vertex labelling": "vertex_labeling",
    "edge labelling": "edge_labeling",
    "distance": "distance",
    "distances": "distance",
    "diameter": "diameter",
    "radius": "radius",
    "eccentricity": "eccentricity",
    "center": "center",
    "centers": "center",
    "central vertex": "center",
    "central vertices": "center",
    "girth": "girth",
    "order": "order",
    "size": "size",
    "order of graph": "order",
    "size of graph": "size",
    "adjacent vertices": "adjacent",
    "adjacent edges": "adjacent",
    "incident": "incident",
    "incident edge": "incident",
    "incident vertex": "incident",
    "incident edges": "incident",
    "incident vertices": "incident",
    "neighboring": "neighbor",
    "neighboring vertex": "neighbor",
    "neighboring vertices": "neighbor",
    "distance matrix": "distance_matrix",
    "diameter of graph": "diameter",
    "radius of graph": "radius",
    "eccentricity of vertex": "eccentricity",
    "girth of graph": "girth",
    "planarity": "planar_graph",
    "nonplanarity": "nonplanar_graph",
    "Kuratowski's theorem": "kuratowski_theorem",
    "kuratowski theorem": "kuratowski_theorem",
    "k5": "complete_graph",
    "k3,3": "complete_bipartite_graph",
    "petersen graph": "petersen_graph",
    "petersen": "petersen_graph",
    "cubic graph": "cubic_graph",
    "regular graph": "regular_graph",
    "k-regular graph": "regular_graph",
    "degree sequence": "degree_sequence",
    "degree distribution": "degree_distribution",
    "random graph": "random_graph",
    "erdos-renyi graph": "random_graph",
    "erdős–rényi graph": "random_graph",
    "erdos renyi": "random_graph",
    "small-world graph": "small_world_graph",
    "small world graph": "small_world_graph",
    "scale-free graph": "scale_free_graph",
    "scale free graph": "scale_free_graph",
    "network": "graph",
    "networks": "graph",
    "social network": "graph",
    "flow network": "flow_network",
    "flow": "flow",
    "max-flow": "max_flow",
    "min-cut": "min_cut",
    "maximum flow": "max_flow",
    "minimum cut": "min_cut",
    "ford-fulkerson": "ford_fulkerson",
    "ford fulkerson": "ford_fulkerson",
    "edmonds-karp": "edmonds_karp",
    "edmonds karp": "edmonds_karp",
    "push-relabel": "push_relabel",
    "push relabel": "push_relabel",
    "vertex connectivity": "vertex_connectivity",
    "edge connectivity": "edge_connectivity",
    "k-connected": "k_connected",
    "k-connected graph": "k_connected",
    "k-edge-connected": "k_edge_connected",
    "k-edge-connected graph": "k_edge_connected",
    "vertex separator": "vertex_separator",
    "edge separator": "edge_separator",
    "separator": "separator",
    "separators": "separator",
    "dominating set": "dominating_set",
    "dominating sets": "dominating_set",
    "domination number": "domination_number",
    "cover": "vertex_cover",
    "covers": "vertex_cover",
    "covering": "vertex_cover",
    "coverings": "vertex_cover",
    "independent": "independent_set",
    "stable": "independent_set",
    "stable sets": "independent_set",
    "vertex independence number": "independence_number",
    "edge independence number": "edge_independence_number",
    "vertex partition": "vertex_partition",
    "edge partition": "edge_partition",
    "partition": "partition",
    "partitions": "partition",
    "partitioning": "partition",
    "partitionings": "partition",
    "vertex coloring number": "chromatic_number",
    "edge coloring number": "edge_chromatic_number",
    "chromatic polynomial": "chromatic_polynomial",
    "chromatic index": "chromatic_index",
    "color": "coloring",
    "colour": "coloring",
    "colors": "coloring",
    "colours": "coloring",
    "colorings": "coloring",
    "colourings": "coloring",
    "greedy coloring": "greedy_coloring",
    "greedy colouring": "greedy_coloring",
    "vertex color": "vertex_coloring",
    "edge color": "edge_coloring",
    "vertex colour": "vertex_coloring",
    "edge colour": "edge_coloring",
    "edge chromatic number": "edge_chromatic_number",
    "vertex chromatic number": "chromatic_number",
    "chromatic": "chromatic_number",
    "chromatic numbers": "chromatic_number",
    "chromatic indices": "chromatic_index",
    "chromatic polynomials": "chromatic_polynomial",
    "greedy": "greedy_coloring",
    "greedy algorithm": "greedy_coloring",
    "greedy algorithms": "greedy_coloring",
    "greedy coloring algorithm": "greedy_coloring",
    "greedy colouring algorithm": "greedy_coloring",
    "planar": "planar_graph",
    "nonplanar": "nonplanar_graph",
    "planar embedding": "planar_embedding",
    "planar embeddings": "planar_embedding",
    "face": "face",
    "faces": "face",
    "region": "face",
    "regions": "face",
    "outer face": "face",
    "inner face": "face",
    "dual graph": "dual_graph",
    "dual graphs": "dual_graph",
    "line graph": "line_graph",
    "line graphs": "line_graph",
    "graph product": "graph_product",
    "graph products": "graph_product",
    "cartesian product": "cartesian_product",
    "cartesian products": "cartesian_product",
    "tensor product": "tensor_product",
    "tensor products": "tensor_product",
    "strong product": "strong_product",
    "strong products": "strong_product",
    "lexicographic product": "lexicographic_product",
    "lexicographic products": "lexicographic_product",
    "join": "join",
    "joins": "join",
    "union": "union",
    "unions": "union",
    "intersection": "intersection",
    "intersections": "intersection",
    "complement": "complement",
    "complements": "complement",
    "graph complement": "complement",
    "complement graph": "complement",
    "graph union": "union",
    "graph intersection": "intersection",
    "graph join": "join",
    "graph difference": "difference",
    "difference": "difference",
    "differences": "difference",
    "edge difference": "difference",
    "vertex difference": "difference",
    "edge contraction": "contraction",
    "vertex contraction": "contraction",
    "edge expansion": "expansion",
    "vertex expansion": "expansion",
    "subdivision": "subdivision",
    "subdivisions": "subdivision",
    "graph subdivision": "subdivision",
    "vertex subdivision": "subdivision",
    "edge subdivision": "subdivision",
    "minor graph": "minor",
    "minor graphs": "minor",
    "homeomorphic": "homeomorphism",
    "homeomorphic graphs": "homeomorphism",
    "homeomorphisms": "homeomorphism",
    "graph homeomorphism": "homeomorphism",
    "graph automorphism": "automorphism",
    "automorphic": "automorphism",
    "automorphic graphs": "automorphism",
    "graph automorphisms": "automorphism",
    "graph isomorphic": "isomorphism",
    "isomorphic graphs": "isomorphism",
    "isomorphisms": "isomorphism",
    "nonisomorphic": "nonisomorphic",
    "non-isomorphic": "nonisomorphic",
    "nonisomorphic graphs": "nonisomorphic",
    "non-isomorphic graphs": "nonisomorphic",
    "nonisomorphism": "nonisomorphic",
    "non-isomorphism": "nonisomorphic",
    "nonisomorphisms": "nonisomorphic",
    "non-isomorphisms": "nonisomorphic",
    "adjacency": "adjacent",
    "adjacencies": "adjacent",
    "adjacent vertex": "adjacent",
    "adjacent edge": "adjacent",
    "adjacent vertices": "adjacent",
    "adjacent edges": "adjacent",
    "incident": "incident",
    "incidence": "incident",
    "incidences": "incident",
    "incident vertex": "incident",
    "incident edge": "incident",
    "incident vertices": "incident",
    "incident edges": "incident",
    "neighbor": "neighbor",
    "neighbour": "neighbor",
    "neighbours": "neighbor",
    "neighbors": "neighbor",
    "neighboring": "neighbor",
    "neighbouring": "neighbor",
    "neighboring vertex": "neighbor",
    "neighboring vertices": "neighbor",
    "neighbouring vertex": "neighbor",
    "neighbouring vertices": "neighbor",
    "distance": "distance",
    "distances": "distance",
    "distance matrix": "distance_matrix",
    "diameter": "diameter",
    "radius": "radius",
    "eccentricity": "eccentricity",
    "center": "center",
    "central vertex": "center",
    "central vertices": "center",
    "girth": "girth",
    "order": "order",
    "size": "size",
    "order of graph": "order",
    "size of graph": "size",
    "adjacent vertices": "adjacent",
    "adjacent edges": "adjacent",
    "incident": "incident",
    "incident edge": "incident",
    "incident vertex": "incident",
    "incident edges": "incident",
    "incident vertices": "incident",
    "neighboring": "neighbor",
    "neighboring vertex": "neighbor",
    "neighboring vertices": "neighbor",
    "distance matrix": "distance_matrix",
    "diameter of graph": "diameter",
    "radius of graph": "radius",
    "eccentricity of vertex": "eccentricity",
    "girth of graph": "girth",
    "planarity": "planar_graph",
    "nonplanarity": "nonplanar_graph",
    "Kuratowski's theorem": "kuratowski_theorem",
    "kuratowski theorem": "kuratowski_theorem",
    "k5": "complete_graph",
    "k3,3": "complete_bipartite_graph",
    "petersen graph": "petersen_graph",
    "petersen": "petersen_graph",
    "cubic graph": "cubic_graph",
    "regular graph": "regular_graph",
    "k-regular graph": "regular_graph",
    "degree sequence": "degree_sequence",
    "degree distribution": "degree_distribution",
    "random graph": "random_graph",
    "erdos-renyi graph": "random_graph",
    "erdős–rényi graph": "random_graph",
    "erdos renyi": "random_graph",
    "small-world graph": "small_world_graph",
    "small world graph": "small_world_graph",
    "scale-free graph": "scale_free_graph",
    "scale free graph": "scale_free_graph",
    "network": "graph",
    "networks": "graph",
    "social network": "graph",
    "flow network": "flow_network",
    "flow": "flow",
    "max-flow": "max_flow",
    "min-cut": "min_cut",
    "maximum flow": "max_flow",
    "minimum cut": "min_cut",
    "ford-fulkerson": "ford_fulkerson",
    "ford fulkerson": "ford_fulkerson",
    "edmonds-karp": "edmonds_karp",
    "edmonds karp": "edmonds_karp",
    "push-relabel": "push_relabel",
    "push relabel": "push_relabel",
    "vertex connectivity": "vertex_connectivity",
    "edge connectivity": "edge_connectivity",
    "k-connected": "k_connected",
    "k-connected graph": "k_connected",
    "k-edge-connected": "k_edge_connected",
    "k-edge-connected graph": "k_edge_connected",
    "vertex separator": "vertex_separator",
    "edge separator": "edge_separator",
    "separator": "separator",
    "separators": "separator",
    "dominating set": "dominating_set",
    "dominating sets": "dominating_set",
    "domination number": "domination_number",
    "cover": "vertex_cover",
    "covers": "vertex_cover",
    "covering": "vertex_cover",
    "coverings": "vertex_cover",
    "independent": "independent_set",
    "stable": "independent_set",
    "stable sets": "independent_set",
    "vertex independence number": "independence_number",
    "edge independence number": "edge_independence_number",
    "vertex partition": "vertex_partition",
    "edge partition": "edge_partition",
    "partition": "partition",
    "partitions": "partition",
    "partitioning": "partition",
    "partitionings": "partition",
    "vertex coloring number": "chromatic_number",
    "edge coloring number": "edge_chromatic_number",
    "chromatic polynomial": "chromatic_polynomial",
    "chromatic index": "chromatic_index",
    "color": "coloring",
    "colour": "coloring",
    "colors": "coloring",
    "colours": "coloring",
    "colorings": "coloring",
    "colourings": "coloring",
    "greedy coloring": "greedy_coloring",
    "greedy colouring": "greedy_coloring",
    "vertex color": "vertex_coloring",
    "edge color": "edge_coloring",
    "vertex colour": "vertex_coloring",
    "edge colour": "edge_coloring",
    "edge chromatic number": "edge_chromatic_number",
    "vertex chromatic number": "chromatic_number",
    "chromatic": "chromatic_number",
    "chromatic numbers": "chromatic_number",
    "chromatic indices": "chromatic_index",
    "chromatic polynomials": "chromatic_polynomial",
    "greedy": "greedy_coloring",
    "greedy algorithm": "greedy_coloring",
    "greedy algorithms": "greedy_coloring",
    "greedy coloring algorithm": "greedy_coloring",
    "greedy colouring algorithm": "greedy_coloring",
    "planar": "planar_graph",
    "nonplanar": "nonplanar_graph",
    "planar embedding": "planar_embedding",
    "planar embeddings": "planar_embedding",
    "face": "face",
    "faces": "face",
    "region": "face",
    "regions": "face",
    "outer face": "face",
    "inner face": "face",
    "dual graph": "dual_graph",
    "dual graphs": "dual_graph",
    "line graph": "line_graph",
    "line graphs": "line_graph",
    "graph product": "graph_product",
    "graph products": "graph_product",
    "cartesian product": "cartesian_product",
    "cartesian products": "cartesian_product",
    "tensor product": "tensor_product",
    "tensor products": "tensor_product",
    "strong product": "strong_product",
    "strong products": "strong_product",
    "lexicographic product": "lexicographic_product",
    "lexicographic products": "lexicographic_product",
    "join": "join",
    "joins": "join",
    "union": "union",
    "unions": "union",
    "intersection": "intersection",
    "intersections": "intersection",
    "complement": "complement",
    "complements": "complement",
    "graph complement": "complement",
    "complement graph": "complement",
    "graph union": "union",
    "graph intersection": "intersection",
    "graph join": "join",
    "graph difference": "difference",
    "difference": "difference",
    "differences": "difference",
    "edge difference": "difference",
    "vertex difference": "difference",
    "edge contraction": "contraction",
    "vertex contraction": "contraction",
    "edge expansion": "expansion",
    "vertex expansion": "expansion",
    "subdivision": "subdivision",
    "subdivisions": "subdivision",
    "graph subdivision": "subdivision",
    "vertex subdivision": "subdivision",
    "edge subdivision": "subdivision",
    "minor graph": "minor",
    "minor graphs": "minor",
    "homeomorphic": "homeomorphism",
    "homeomorphic graphs": "homeomorphism",
    "homeomorphisms": "homeomorphism",
    "graph homeomorphism": "homeomorphism",
    "graph automorphism": "automorphism",
    "automorphic": "automorphism",
    "automorphic graphs": "automorphism",
    "graph automorphisms": "automorphism",
    "graph isomorphic": "isomorphism",
    "isomorphic graphs": "isomorphism",
    "isomorphisms": "isomorphism",
    "nonisomorphic": "nonisomorphic",
    "non-isomorphic": "nonisomorphic",
    "nonisomorphic graphs": "nonisomorphic",
    "non-isomorphic graphs": "nonisomorphic",
    "nonisomorphism": "nonisomorphic",
    "non-isomorphism": "nonisomorphic",
    "nonisomorphisms": "nonisomorphic",
    "non-isomorphisms": "nonisomorphic",
    "adjacency": "adjacent",
    "adjacencies": "adjacent",
    "adjacent vertex": "adjacent",
    "adjacent edge": "adjacent",
    "adjacent vertices": "adjacent",
    "adjacent edges": "adjacent",
    "incident": "incident",
    "incidence": "incident",
    "incidences": "incident",
    "incident vertex": "incident",
    "incident edge": "incident",
    "incident vertices": "incident",
    "incident edges": "incident",
    "neighbor": "neighbor",
    "neighbour": "neighbor",
    "neighbours": "neighbor",
    "neighbors": "neighbor",
    "neighboring": "neighbor",
    "neighbouring": "neighbor",
    "neighboring vertex": "neighbor",
    "neighboring vertices": "neighbor",
    "neighbouring vertex": "neighbor",
    "neighbouring vertices": "neighbor",
    "distance": "distance",
    "distances": "distance",
    "distance matrix": "distance_matrix",
    "diameter": "diameter",
    "radius": "radius",
    "eccentricity": "eccentricity",
    "center": "center",
    "central vertex": "center",
    "central vertices": "center",
    "girth": "girth",
    "order": "order",
    "size": "size",
    "order of graph": "order",
    "size of graph": "size",
    "adjacent vertices": "adjacent",
    "adjacent edges": "adjacent",
    "incident": "incident",
    "incident edge": "incident",
    "incident vertex": "incident",
    "incident edges": "incident",
    "incident vertices": "incident",
    "neighboring": "neighbor",
    "neighboring vertex": "neighbor",
    "neighboring vertices": "neighbor",
    "distance matrix": "distance_matrix",
    "diameter of graph": "diameter",
    "radius of graph": "radius",
    "eccentricity of vertex": "eccentricity",
    "girth of graph": "girth",
    "planarity": "planar_graph",
    "nonplanarity": "nonplanar_graph",
    "Kuratowski's theorem": "kuratowski_theorem",
    "kuratowski theorem": "kuratowski_theorem",
    "k5": "complete_graph",
    "k3,3": "complete_bipartite_graph",
    "petersen graph": "petersen_graph",
    "petersen": "petersen_graph",
    "cubic graph": "cubic_graph",
    "regular graph": "regular_graph",
    "k-regular graph": "regular_graph",
    "degree sequence": "degree_sequence",
    "degree distribution": "degree_distribution",
    "random graph": "random_graph",
    "erdos-renyi graph": "random_graph",
    "erdős–rényi graph": "random_graph",
    "erdos renyi": "random_graph",
    "small-world graph": "small_world_graph",
    "small world graph": "small_world_graph",
    "scale-free graph": "scale_free_graph",
    "scale free graph": "scale_free_graph",
    "network": "graph",
    "networks": "graph",
    "social network": "graph",
    "flow network": "flow_network",
    "flow": "flow",
    "max-flow": "max_flow",
    "min-cut": "min_cut",
    "maximum flow": "max_flow",
    "minimum cut": "min_cut",
    "ford-fulkerson": "ford_fulkerson",
    "ford fulkerson": "ford_fulkerson",
    "edmonds-karp": "edmonds_karp",
    "edmonds karp": "edmonds_karp",
    "push-relabel": "push_relabel",
    "push relabel": "push_relabel",
    "vertex connectivity": "vertex_connectivity",
    "edge connectivity": "edge_connectivity",
    "k-connected": "k_connected",
    "k-connected graph": "k_connected",
    "k-edge-connected": "k_edge_connected",
    "k-edge-connected graph": "k_edge_connected",
    "vertex separator": "vertex_separator",
    "edge separator": "edge_separator",
    "separator": "separator",
    "separators": "separator",
    "dominating set": "dominating_set",
    "dominating sets": "dominating_set",
    "domination number": "domination_number",
    "cover": "vertex_cover",
    "covers": "vertex_cover",
    "covering": "vertex_cover",
    "coverings": "vertex_cover",
    "independent": "independent_set",
    "stable": "independent_set",
    "stable sets": "independent_set",
    "vertex independence number": "independence_number",
    "edge independence number": "edge_independence_number",
    "vertex partition": "vertex_partition",
    "edge partition": "edge_partition",
    "partition": "partition",
    "partitions": "partition",
    "partitioning": "partition",
    "partitionings": "partition",
    "vertex coloring number": "chromatic_number",
    "edge coloring number": "edge_chromatic_number",
    "chromatic polynomial": "chromatic_polynomial",
    "chromatic index": "chromatic_index",
    "color": "coloring",
    "colour": "coloring",
    "colors": "coloring",
    "colours": "coloring",
    "colorings": "coloring",
    "colourings": "coloring",
    "greedy coloring": "greedy_coloring",
    "greedy colouring": "greedy_coloring",
    "vertex color": "vertex_coloring",
    "edge color": "edge_coloring",
    "vertex colour": "vertex_coloring",
    "edge colour": "edge_coloring",
    "edge chromatic number": "edge_chromatic_number",
    "vertex chromatic number": "chromatic_number",
    "chromatic": "chromatic_number",
    "chromatic numbers": "chromatic_number",
    "chromatic indices": "chromatic_index",
    "chromatic polynomials": "chromatic_polynomial",
    "greedy": "greedy_coloring",
    "greedy algorithm": "greedy_coloring",
    "greedy algorithms": "greedy_coloring",
    "greedy coloring algorithm": "greedy_coloring",
    "greedy colouring algorithm": "greedy_coloring",
    "planar": "planar_graph",
    "nonplanar": "nonplanar_graph",
    "planar embedding": "planar_embedding",
    "planar embeddings": "planar_embedding",
    "face": "face",
    "faces": "face",
    "region": "face",
    "regions": "face",
    "outer face": "face",
    "inner face": "face",
    "dual graph": "dual_graph",
    "dual graphs": "dual_graph",
    "line graph": "line_graph",
    "line graphs": "line_graph",
    "graph product": "graph_product",
    "graph products": "graph_product",
    "cartesian product": "cartesian_product",
    "cartesian products": "cartesian_product",
    "tensor product": "tensor_product",
    "tensor products": "tensor_product",
    "strong product": "strong_product",
    "strong products": "strong_product",
    "lexicographic product": "lexicographic_product",
    "lexicographic products": "lexicographic_product",
    "join": "join",
    "joins": "join",
    "union": "union",
    "unions": "union",
    "intersection": "intersection",
    "intersections": "intersection",
    "complement": "complement",
    "complements": "complement",
    "graph complement": "complement",
    "complement graph": "complement",
    "graph union": "union",
    "graph intersection": "intersection",
    "graph join": "join",
    "graph difference": "difference",
    "difference": "difference",
    "differences": "difference",
    "edge difference": "difference",
    "vertex difference": "difference",
    "edge contraction": "contraction",
    "vertex contraction": "contraction",
    "edge expansion": "expansion",
    "vertex expansion": "expansion",
    "subdivision": "subdivision",
    "subdivisions": "subdivision",
    "graph subdivision": "subdivision",
    "vertex subdivision": "subdivision",
    "edge subdivision": "subdivision",
    "minor graph": "minor",
    "minor graphs": "minor",
    "homeomorphic": "homeomorphism",
    "homeomorphic graphs": "homeomorphism",
    "homeomorphisms": "homeomorphism",
    "graph homeomorphism": "homeomorphism",
    "graph automorphism": "automorphism",
    "automorphic": "automorphism",
    "automorphic graphs": "automorphism",
    "graph automorphisms": "automorphism",
    "graph isomorphic": "isomorphism",
    "isomorphic graphs": "isomorphism",
    "isomorphisms": "isomorphism",
    "nonisomorphic": "nonisomorphic",
    "non-isomorphic": "nonisomorphic",
    "nonisomorphic graphs": "nonisomorphic",
    "non-isomorphic graphs": "nonisomorphic",
    "nonisomorphism": "nonisomorphic",
    "non-isomorphism": "nonisomorphic",
    "nonisomorphisms": "nonisomorphic",
    "non-isomorphisms": "nonisomorphic",
    # Misspellings and common errors
    "vertice": "vertex",
    "veritces": "vertex",
    "veritex": "vertex",
    "edg": "edge",
    "adjancent": "adjacent",
    "adjecent": "adjacent",
    "adjacency listt": "adjacency_list",
    "adjacency matrx": "adjacency_matrix",
    "independant set": "independent_set",
    "independant sets": "independent_set",
    "bipartitee graph": "bipartite_graph",
    "bipartitee graphs": "bipartite_graph",
    "complementt": "complement",
    "complement graphh": "complement",
    "chromaticc number": "chromatic_number",
    "chromaticc index": "chromatic_index",
    "chromaticc polynomial": "chromatic_polynomial",
    "hamiltonian cyclee": "hamiltonian_cycle",
    "hamiltonian pathh": "hamiltonian_path",
    "eulerian cyclee": "eulerian_cycle",
    "eulerian pathh": "eulerian_path",
    "isomorphis": "isomorphism",
    "isomorphisms": "isomorphism",
    "automorphis": "automorphism",
    "automorphisms": "automorphism",
    "homeomorphis": "homeomorphism",
    "homeomorphisms": "homeomorphism",
    "planar grap": "planar_graph",
    "nonplanar grap": "nonplanar_graph",
    "random grap": "random_graph",
    "scale freee graph": "scale_free_graph",
    "small worldd graph": "small_world_graph",
    "degreee sequence": "degree_sequence",
    "degreee distribution": "degree_distribution",
    "partitionn": "partition",
    "partitioningg": "partition",
    "coverr": "vertex_cover",
    "coverring": "vertex_cover",
    "dominatingg set": "dominating_set",
    "dominationn number": "domination_number",
    "separatorr": "separator",
    "separatorss": "separator",
    "blockk": "block",
    "cliquee": "clique",
    "clique numberr": "clique_number",
    "vertexx": "vertex",
    "edgee": "edge",
    "incidentt": "incident",
    "incident edgee": "incident",
    "incident vertexx": "incident",
    "neighborr": "neighbor",
    "neighbourr": "neighbor",
    "distancee": "distance",
    "diameterr": "diameter",
    "radiuss": "radius",
    "eccentricityy": "eccentricity",
    "centerer": "center",
    "girthh": "girth",
    "orderer": "order",
    "sizee": "size",
    "adjacentt": "adjacent",
    "adjacencyy": "adjacent",
    "adjacency matrixx": "adjacency_matrix",
    "adjacency listt": "adjacency_list",
    "incidencee matrix": "incidence_matrix",
    "degreee": "degree",
    "indegreee": "in_degree",
    "outdegreee": "out_degree",
    "valencyy": "degree",
    "neighborr": "neighbor",
    "neighbourr": "neighbor",
    "neighboursr": "neighbor",
    "neighborsr": "neighbor",
    "pathh": "path",
    "walkk": "walk",
    "trailss": "trail",
    "cycless": "cycle",
    "circuitss": "cycle",
    "closed walkk": "cycle",
    "open walkk": "walk",
    "loopss": "loop",
    "parallel edgess": "parallel_edges",
    "multiple edgess": "parallel_edges",
    "connecteddd": "connected",
    "connectivityy": "connected",
    "disconnecteddd": "disconnected",
    "componentss": "component",
    "strongly connecteddd": "strongly_connected",
    "weakly connecteddd": "weakly_connected",
    "strong connectivityy": "strongly_connected",
    "weak connectivityy": "weakly_connected",
    "bridgee": "bridge",
    "cut-edgess": "bridge",
    "cut vertexx": "cut_vertex",
    "articulationn point": "cut_vertex",
    "articulationn points": "cut_vertex",
    "blockss": "block",
    "cliquess": "clique",
    "complete graphh": "complete_graph",
    "empty graphh": "empty_graph",
    "null graphh": "empty_graph",
    "subgraphh": "subgraph",
    "induced subgraphh": "induced_subgraph",
    "spanning subgraphh": "spanning_subgraph",
    "spanning treee": "spanning_tree",
    "treee": "tree",
    "forests": "forest",
    "leafs": "leaf",
    "roots": "root",
    "branchs": "branch",
    "binary treee": "binary_tree",
    "directed acyclic graphh": "dag",
    "dags": "dag",
    "acyclic graphh": "acyclic_graph",
    "cycle-free graphh": "acyclic_graph",
    "planar graphh": "planar_graph",
    "nonplanar graphh": "nonplanar_graph",
    "bipartite graphh": "bipartite_graph",
    "complete bipartite graphh": "complete_bipartite_graph",
    "matchingg": "matching",
    "maximum matchingg": "maximum_matching",
    "maximal matchingg": "maximal_matching",
    "perfect matchingg": "perfect_matching",
    "vertex coverr": "vertex_cover",
    "edge coverr": "edge_cover",
    "independent setss": "independent_set",
    "stable setss": "independent_set",
    "clique numberr": "clique_number",
    "chromatic numberr": "chromatic_number",
    "coloringg": "coloring",
    "colouringg": "coloring",
    "vertex coloringg": "vertex_coloring",
    "edge coloringg": "edge_coloring",
    "proper coloringg": "proper_coloring",
    "Hamiltonian cyclee": "hamiltonian_cycle",
    "Hamiltonian pathh": "hamiltonian_path",
    "Eulerian cyclee": "eulerian_cycle",
    "Eulerian pathh": "eulerian_path",
    "Hamilton circuitt": "hamiltonian_cycle",
    "Hamilton pathh": "hamiltonian_path",
    "isomorphismm": "isomorphism",
    "isomorphicc": "isomorphism",
    "graph isomorphismm": "isomorphism",
    "automorphismm": "automorphism",
    "homeomorphismm": "homeomorphism",
    "minorr": "minor",
    "graph minorr": "minor",
    "contractt": "contract",
    "contractionn": "contraction",
    "expandd": "expand",
    "expansionn": "expansion",
    "embeddingg": "embedding",
    "labelss": "label",
    "labelingg": "labeling",
    "vertex labelingg": "vertex_labeling",
    "edge labelingg": "edge_labeling",
    "distancee": "distance",
    "diameterr": "diameter",
    "radiuss": "radius",
    "eccentricityy": "eccentricity",
    "centerer": "center",
    "girthh": "girth",
    "orderer": "order",
    "sizee": "size",
    "adjacentt": "adjacent",
    "adjacencyy": "adjacent",
    "adjacency matrixx": "adjacency_matrix",
    "adjacency listt": "adjacency_list",
    "incidencee matrix": "incidence_matrix",
    "degreee": "degree",
    "indegreee": "in_degree",
    "outdegreee": "out_degree",
    "valencyy": "degree",
    "neighborr": "neighbor",
    "neighbourr": "neighbor",
    "neighboursr": "neighbor",
    "neighborsr": "neighbor",
    "pathh": "path",
    "walkk": "walk",
    "trailss": "trail",
    "cycless": "cycle",
    "circuitss": "cycle",
    "closed walkk": "cycle",
    "open walkk": "walk",
    "loopss": "loop",
    "parallel edgess": "parallel_edges",
    "multiple edgess": "parallel_edges",
    "connecteddd": "connected",
    "connectivityy": "connected",
    "disconnecteddd": "disconnected",
    "componentss": "component",
    "strongly connecteddd": "strongly_connected",
    "weakly connecteddd": "weakly_connected",
    "strong connectivityy": "strongly_connected",
    "weak connectivityy": "weakly_connected",
    "bridgee": "bridge",
    "cut-edgess": "bridge",
    "cut vertexx": "cut_vertex",
    "articulationn point": "cut_vertex",
    "articulationn points": "cut_vertex",
    "blockss": "block",
    "cliquess": "clique",
    "complete graphh": "complete_graph",
    "empty graphh": "empty_graph",
    "null graphh": "empty_graph",
    "subgraphh": "subgraph",
    "induced subgraphh": "induced_subgraph",
    "spanning subgraphh": "spanning_subgraph",
    "spanning treee": "spanning_tree",
    "treee": "tree",
    "forests": "forest",
    "leafs": "leaf",
    "roots": "root",
    "branchs": "branch",
    "binary treee": "binary_tree",
    "directed acyclic graphh": "dag",
    "dags": "dag",
    "acyclic graphh": "acyclic_graph",
    "cycle-free graphh": "acyclic_graph",
    "planar graphh": "planar_graph",
    "nonplanar graphh": "nonplanar_graph",
    "bipartite graphh": "bipartite_graph",
    "complete bipartite graphh": "complete_bipartite_graph",
    "matchingg": "matching",
    "maximum matchingg": "maximum_matching",
    "maximal matchingg": "maximal_matching",
    "perfect matchingg": "perfect_matching",
    "vertex coverr": "vertex_cover",
    "edge coverr": "edge_cover",
    "independent setss": "independent_set",
    "stable setss": "independent_set",
    "clique numberr": "clique_number",
    "chromatic numberr": "chromatic_number",
    "coloringg": "coloring",
    "colouringg": "coloring",
    "vertex coloringg": "vertex_coloring",
    "edge coloringg": "edge_coloring",
    "proper coloringg": "proper_coloring",
    # Acronyms and abbreviations
    "adj_mat": "adjacency_matrix",
    "adj_list": "adjacency_list",
    "inc_mat": "incidence_matrix",
    "deg_seq": "degree_sequence",
    "deg_dist": "degree_distribution",
    "max_match": "maximum_matching",
    "perf_match": "perfect_matching",
    "min_cut": "min_cut",
    "max_flow": "max_flow",
    "chrom_num": "chromatic_number",
    "chrom_poly": "chromatic_polynomial",
    "chrom_idx": "chromatic_index",
    "edge_chrom_num": "edge_chromatic_number",
    "vert_chrom_num": "chromatic_number",
    "ham_cycle": "hamiltonian_cycle",
    "ham_path": "hamiltonian_path",
    "eul_cycle": "eulerian_cycle",
    "eul_path": "eulerian_path",
    "iso": "isomorphism",
    "auto": "automorphism",
    "homeo": "homeomorphism",
    "comp_graph": "complement",
    "comp_bip_graph": "complete_bipartite_graph",
    "reg_graph": "regular_graph",
    "cub_graph": "cubic_graph",
    "rand_graph": "random_graph",
    "sw_graph": "small_world_graph",
    "sf_graph": "scale_free_graph",
    "flow_net": "flow_network",
    "ford_fulk": "ford_fulkerson",
    "edm_karp": "edmonds_karp",
    "push_rel": "push_relabel",
    "vert_conn": "vertex_connectivity",
    "edge_conn": "edge_connectivity",
    "vert_sep": "vertex_separator",
    "edge_sep": "edge_separator",
    "dom_set": "dominating_set",
    "dom_num": "domination_number",
    "ind_set": "independent_set",
    "stab_set": "independent_set",
    "vert_part": "vertex_partition",
    "edge_part": "edge_partition",
    "cart_prod": "cartesian_product",
    "ten_prod": "tensor_product",
    "str_prod": "strong_product",
    "lex_prod": "lexicographic_product",
    "diff": "difference",
    "subdiv": "subdivision",
    "minor_g": "minor",
    "block_g": "block",
    "cliq_num": "clique_number",
    "comp": "complement",
    "iso_graph": "isomorphism",
    "auto_graph": "automorphism",
    "homeo_graph": "homeomorphism",
    "plan_emb": "planar_embedding",
    "dual_g": "dual_graph",
    "line_g": "line_graph",
    "prod_g": "graph_product",
    "join_g": "join",
    "union_g": "union",
    "inter_g": "intersection",
    "diff_g": "difference",
    "sub_g": "subgraph",
    "ind_sub_g": "induced_subgraph",
    "span_sub_g": "spanning_subgraph",
    "span_tree": "spanning_tree",
    "bin_tree": "binary_tree",
    "dag_g": "dag",
    "acyc_g": "acyclic_graph",
    "plan_g": "planar_graph",
    "nonplan_g": "nonplanar_graph",
    "bip_g": "bipartite_graph",
    "comp_bip_g": "complete_bipartite_graph",
    "match_g": "matching",
    "max_match_g": "maximum_matching",
    "perf_match_g": "perfect_matching",
    "min_cut_g": "min_cut",
    "max_flow_g": "max_flow",
    "chrom_poly_g": "chromatic_polynomial",
    "chrom_idx_g": "chromatic_index",
    "edge_chrom_num_g": "edge_chromatic_number",
    "vert_chrom_num_g": "chromatic_number",
    "ham_cycle_g": "hamiltonian_cycle",
    "ham_path_g": "hamiltonian_path",
    "eul_cycle_g": "eulerian_cycle",
    "eul_path_g": "eulerian_path",
    "iso_g": "isomorphism",
    "auto_g": "automorphism",
    "homeo_g": "homeomorphism",
    "comp_g": "complement",
    "reg_g": "regular_graph",
    "cub_g": "cubic_graph",
    "rand_g": "random_graph",
    "sw_g": "small_world_graph",
    "sf_g": "scale_free_graph",
    "flow_net_g": "flow_network",
    "ford_fulk_g": "ford_fulkerson",
    "edm_karp_g": "edmonds_karp",
    "push_rel_g": "push_relabel",
    "vert_conn_g": "vertex_connectivity",
    "edge_conn_g": "edge_connectivity",
    "vert_sep_g": "vertex_separator",
    "edge_sep_g": "edge_separator",
    "dom_set_g": "dominating_set",
    "dom_num_g": "domination_number",
    "ind_set_g": "independent_set",
    "stab_set_g": "independent_set",
    "vert_part_g": "vertex_partition",
    "edge_part_g": "edge_partition",
    "cart_prod_g": "cartesian_product",
    "ten_prod_g": "tensor_product",
    "str_prod_g": "strong_product",
    "lex_prod_g": "lexicographic_product",
    "diff_g": "difference",
    "subdiv_g": "subdivision",
    "minor_g_g": "minor",
    "block_g_g": "block",
    "cliq_num_g": "clique_number",
    "comp_g_g": "complement",
    "iso_graph_g": "isomorphism",
    "auto_graph_g": "automorphism",
    "homeo_graph_g": "homeomorphism",
    "plan_emb_g": "planar_embedding",
    "dual_g_g": "dual_graph",
    "line_g_g": "line_graph",
    "prod_g_g": "graph_product",
    "join_g_g": "join",
    "union_g_g": "union",
    "inter_g_g": "intersection",
    "diff_g_g": "difference",
    "sub_g_g": "subgraph",
    "ind_sub_g_g": "induced_subgraph",
    "span_sub_g_g": "spanning_subgraph",
    "span_tree_g": "spanning_tree",
    "bin_tree_g": "binary_tree",
    "dag_g_g": "dag",
    "acyc_g_g": "acyclic_graph",
    "plan_g_g": "planar_graph",
    "nonplan_g_g": "nonplanar_graph",
    "bip_g_g": "bipartite_graph",
    "comp_bip_g_g": "complete_bipartite_graph",
    "match_g_g": "matching",
    "max_match_g_g": "maximum_matching",
    "perf_match_g_g": "perfect_matching",
    "min_cut_g_g": "min_cut",
    "max_flow_g_g": "max_flow",
    "chrom_poly_g_g": "chromatic_polynomial",
    "chrom_idx_g_g": "chromatic_index",
    "edge_chrom_num_g_g": "edge_chromatic_number",
    "vert_chrom_num_g_g": "chromatic_number",
    "ham_cycle_g_g": "hamiltonian_cycle",
    "ham_path_g_g": "hamiltonian_path",
    "eul_cycle_g_g": "eulerian_cycle",
    "eul_path_g_g": "eulerian_path",
    "iso_g_g": "isomorphism",
    "auto_g_g": "automorphism",
    "homeo_g_g": "homeomorphism",
    "comp_g_g": "complement",
    "reg_g_g": "regular_graph",
    "cub_g_g": "cubic_graph",
    "rand_g_g": "random_graph",
    "sw_g_g": "small_world_graph",
    "sf_g_g": "scale_free_graph",
    "flow_net_g_g": "flow_network",
    "ford_fulk_g_g": "ford_fulkerson",
    "edm_karp_g_g": "edmonds_karp",
    "push_rel_g_g": "push_relabel",
    "vert_conn_g_g": "vertex_connectivity",
    "edge_conn_g_g": "edge_connectivity",
    "vert_sep_g_g": "vertex_separator",
    "edge_sep_g_g": "edge_separator",
    "dom_set_g_g": "dominating_set",
    "dom_num_g_g": "domination_number",
    "ind_set_g_g": "independent_set",
    "stab_set_g_g": "independent_set",
    "vert_part_g_g": "vertex_partition",
    "edge_part_g_g": "edge_partition",
    "cart_prod_g_g": "cartesian_product",
    "ten_prod_g_g": "tensor_product",
    "str_prod_g_g": "strong_product",
    "lex_prod_g_g": "lexicographic_product",
    "diff_g_g": "difference",
    "subdiv_g_g": "subdivision",
    "minor_g_g_g": "minor",
    "block_g_g_g": "block",
    "cliq_num_g_g": "clique_number",
    "comp_g_g_g": "complement",
    "iso_graph_g_g": "isomorphism",
    "auto_graph_g_g": "automorphism",
    "homeo_graph_g_g": "homeomorphism",
    "plan_emb_g_g": "planar_embedding",
    "dual_g_g_g": "dual_graph",
    "line_g_g_g": "line_graph",
    "prod_g_g_g": "graph_product",
    "join_g_g_g": "join",
    "union_g_g_g": "union",
    "inter_g_g_g": "intersection",
    "diff_g_g_g": "difference",
    "sub_g_g_g": "subgraph",
    "ind_sub_g_g_g": "induced_subgraph",
    "span_sub_g_g_g": "spanning_subgraph",
    "span_tree_g_g": "spanning_tree",
    "bin_tree_g_g": "binary_tree",
    "dag_g_g_g": "dag",
    "acyc_g_g_g": "acyclic_graph",
    "plan_g_g_g": "planar_graph",
    "nonplan_g_g_g": "nonplanar_graph",
    "bip_g_g_g": "bipartite_graph",
    "comp_bip_g_g_g": "complete_bipartite_graph",
    "match_g_g_g": "matching",
    "max_match_g_g_g": "maximum_matching",
    "perf_match_g_g_g": "perfect_matching",
    "min_cut_g_g_g": "min_cut",
    "max_flow_g_g_g": "max_flow",
    "chrom_poly_g_g_g": "chromatic_polynomial",
    "chrom_idx_g_g_g": "chromatic_index",
    "edge_chrom_num_g_g_g": "edge_chromatic_number",
    "vert_chrom_num_g_g_g": "chromatic_number",
    "ham_cycle_g_g_g": "hamiltonian_cycle",
    "ham_path_g_g_g": "hamiltonian_path",
    "eul_cycle_g_g_g": "eulerian_cycle",
    "eul_path_g_g_g": "eulerian_path",
    "iso_g_g_g": "isomorphism",
    "auto_g_g_g": "automorphism",
    "homeo_g_g_g": "homeomorphism",
    "comp_g_g_g": "complement",
    "reg_g_g_g": "regular_graph",
    "cub_g_g_g": "cubic_graph",
    "rand_g_g_g": "random_graph",
    "sw_g_g_g": "small_world_graph",
    "sf_g_g_g": "scale_free_graph",
    "flow_net_g_g_g": "flow_network",
    "ford_fulk_g_g_g": "ford_fulkerson",
    "edm_karp_g_g_g": "edmonds_karp",
    "push_rel_g_g_g": "push_relabel",
    "vert_conn_g_g_g": "vertex_connectivity",
    "edge_conn_g_g_g": "edge_connectivity",
    "vert_sep_g_g_g": "vertex_separator",
    "edge_sep_g_g_g": "edge_separator",
    "dom_set_g_g_g": "dominating_set",
    "dom_num_g_g_g": "domination_number",
    "ind_set_g_g_g": "independent_set",
    "stab_set_g_g_g": "independent_set",
    "vert_part_g_g_g": "vertex_partition",
    "edge_part_g_g_g": "edge_partition",
    "cart_prod_g_g_g": "cartesian_product",
    "ten_prod_g_g_g": "tensor_product",
    "str_prod_g_g_g": "strong_product",
    "lex_prod_g_g_g": "lexicographic_product",
    "diff_g_g_g": "difference",
    "subdiv_g_g_g": "subdivision",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)