import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AUTO01_engine_diagnostics"
SEMANTIC_MAP_ENGINE = "AUTO01"

SEMANTIC_MAP = {
    # OBD-II P0xxx Powertrain Codes
    "p0300": "random_multiple_cylinder_misfire_detected",
    "p0301": "cylinder_1_misfire_detected",
    "p0302": "cylinder_2_misfire_detected",
    "p0303": "cylinder_3_misfire_detected",
    "p0304": "cylinder_4_misfire_detected",
    "p0305": "cylinder_5_misfire_detected",
    "p0306": "cylinder_6_misfire_detected",
    "p0307": "cylinder_7_misfire_detected",
    "p0308": "cylinder_8_misfire_detected",
    "p0171": "system_too_lean_bank_1",
    "p0174": "system_too_lean_bank_2",
    "p0172": "system_too_rich_bank_1",
    "p0175": "system_too_rich_bank_2",
    "p0420": "catalyst_system_efficiency_below_threshold_bank_1",
    "p0430": "catalyst_system_efficiency_below_threshold_bank_2",
    "p0101": "maf_sensor_performance_problem",
    "p0102": "maf_sensor_low_input",
    "p0103": "maf_sensor_high_input",
    "p0113": "iat_sensor_high_input",
    "p0112": "iat_sensor_low_input",
    "p0128": "coolant_thermostat_below_regulating_temperature",
    "p0335": "crankshaft_position_sensor_a_circuit",
    "p0340": "camshaft_position_sensor_a_circuit",
    "p0351": "ignition_coil_a_primary_secondary_circuit",
    "p0352": "ignition_coil_b_primary_secondary_circuit",
    "p0353": "ignition_coil_c_primary_secondary_circuit",
    "p0354": "ignition_coil_d_primary_secondary_circuit",
    "p0440": "evap_system_malfunction",
    "p0442": "evap_system_small_leak_detected",
    "p0446": "evap_vent_control_circuit",
    "p0455": "evap_system_large_leak_detected",
    "p0401": "egr_flow_insufficient_detected",
    "p0402": "egr_flow_excessive_detected",
    "p0410": "secondary_air_injection_system_malfunction",
    "p0480": "cooling_fan_1_control_circuit",
    "p0481": "cooling_fan_2_control_circuit",
    "p0299": "turbocharger_underboost_condition",
    "p0234": "turbocharger_overboost_condition",
    "p0010": "vvt_solenoid_a_circuit_bank_1",
    "p0020": "vvt_solenoid_a_circuit_bank_2",
    "p0011": "vvt_timing_over_advanced_bank_1",
    "p0012": "vvt_timing_over_retarded_bank_1",
    "p0021": "vvt_timing_over_advanced_bank_2",
    "p0022": "vvt_timing_over_retarded_bank_2",
    "p0201": "injector_circuit_open_cylinder_1",
    "p0202": "injector_circuit_open_cylinder_2",
    "p0203": "injector_circuit_open_cylinder_3",
    "p0204": "injector_circuit_open_cylinder_4",
    "p0205": "injector_circuit_open_cylinder_5",
    "p0206": "injector_circuit_open_cylinder_6",
    "p0207": "injector_circuit_open_cylinder_7",
    "p0208": "injector_circuit_open_cylinder_8",
    "p0217": "engine_over_temperature_condition",
    "p0606": "ecm_processor_fault",
    "p0600": "serial_communication_link_malfunction",
    "p0700": "transmission_control_system_malfunction",
    "p0562": "system_voltage_low",
    "p0563": "system_voltage_high",
    "p0117": "ect_sensor_low_input",
    "p0118": "ect_sensor_high_input",
    "p0125": "insufficient_coolant_temp_for_closed_loop",
    "p0130": "o2_sensor_circuit_bank_1_sensor_1",
    "p0131": "o2_sensor_low_voltage_bank_1_sensor_1",
    "p0132": "o2_sensor_high_voltage_bank_1_sensor_1",
    "p0133": "o2_sensor_slow_response_bank_1_sensor_1",
    "p0134": "o2_sensor_no_activity_bank_1_sensor_1",
    "p0135": "o2_sensor_heater_circuit_bank_1_sensor_1",
    "p0140": "o2_sensor_no_activity_bank_1_sensor_2",
    "p0141": "o2_sensor_heater_circuit_bank_1_sensor_2",
    "p0150": "o2_sensor_circuit_bank_2_sensor_1",
    "p0151": "o2_sensor_low_voltage_bank_2_sensor_1",
    "p0152": "o2_sensor_high_voltage_bank_2_sensor_1",
    "p0153": "o2_sensor_slow_response_bank_2_sensor_1",
    "p0154": "o2_sensor_no_activity_bank_2_sensor_1",
    "p0155": "o2_sensor_heater_circuit_bank_2_sensor_1",
    "p0160": "o2_sensor_no_activity_bank_2_sensor_2",
    "p0161": "o2_sensor_heater_circuit_bank_2_sensor_2",
    "p0190": "fuel_rail_pressure_sensor_circuit",
    "p0191": "fuel_rail_pressure_sensor_range_performance",
    "p0193": "fuel_rail_pressure_sensor_high_input",
    "p0192": "fuel_rail_pressure_sensor_low_input",
    "p030x": "engine_misfire_detected",
    "p0xxx": "powertrain_code_generic",
    "obdii": "obd_ii",
    "obd-ii": "obd_ii",
    "obd2": "obd_ii",
    "obd": "obd_ii",
    "obdii_codes": "obd_ii_codes",
    "dtc": "diagnostic_trouble_code",
    "dtcs": "diagnostic_trouble_codes",
    "trouble_code": "diagnostic_trouble_code",
    "trouble_codes": "diagnostic_trouble_codes",
    "fault_code": "diagnostic_trouble_code",
    "fault_codes": "diagnostic_trouble_codes",
    "powertrain_code": "powertrain_code",
    "powertrain_codes": "powertrain_codes",
    "engine_code": "engine_code",
    "engine_codes": "engine_codes",
    "check_engine_light": "mil",
    "cel": "mil",
    "mil": "malfunction_indicator_lamp",
    "service_engine_soon": "malfunction_indicator_lamp",
    "ses": "malfunction_indicator_lamp",
    "engine_light": "malfunction_indicator_lamp",
    "malfunction_indicator_light": "malfunction_indicator_lamp",
    "malfunction_indicator_lamp": "malfunction_indicator_lamp",

    # Engine Misfire Diagnosis (P030x Codes)
    "misfire": "engine_misfire",
    "misfire_detected": "engine_misfire_detected",
    "engine_misfire": "engine_misfire",
    "cylinder_misfire": "engine_misfire",
    "cyl_misfire": "engine_misfire",
    "random_misfire": "random_multiple_cylinder_misfire_detected",
    "multiple_misfire": "random_multiple_cylinder_misfire_detected",
    "cyl1_misfire": "cylinder_1_misfire_detected",
    "cyl2_misfire": "cylinder_2_misfire_detected",
    "cyl3_misfire": "cylinder_3_misfire_detected",
    "cyl4_misfire": "cylinder_4_misfire_detected",
    "cyl5_misfire": "cylinder_5_misfire_detected",
    "cyl6_misfire": "cylinder_6_misfire_detected",
    "cyl7_misfire": "cylinder_7_misfire_detected",
    "cyl8_misfire": "cylinder_8_misfire_detected",
    "spark_misfire": "engine_misfire",
    "ignition_misfire": "engine_misfire",
    "fuel_misfire": "engine_misfire",
    "compression_misfire": "engine_misfire",
    "misfiring": "engine_misfire",

    # Gasoline Direct Injection (GDI) Systems
    "gdi": "gasoline_direct_injection",
    "direct_injection": "gasoline_direct_injection",
    "gasoline_direct_injection": "gasoline_direct_injection",
    "fsi": "gasoline_direct_injection",
    "sidi": "gasoline_direct_injection",
    "high_pressure_fuel_pump": "gdi_high_pressure_fuel_pump",
    "hpfp": "gdi_high_pressure_fuel_pump",
    "injector": "fuel_injector",
    "injectors": "fuel_injectors",
    "fuel_injector": "fuel_injector",
    "fuel_injectors": "fuel_injectors",
    "fuel_rail": "fuel_rail",
    "fuel_rail_pressure": "fuel_rail_pressure",
    "fuel_rail_sensor": "fuel_rail_pressure_sensor",
    "fuel_rail_pressure_sensor": "fuel_rail_pressure_sensor",
    "frp_sensor": "fuel_rail_pressure_sensor",
    "fuel_pressure_regulator": "fuel_pressure_regulator",

    # Catalytic Converter Diagnostics
    "catalytic_converter": "catalytic_converter",
    "catalyst": "catalytic_converter",
    "cat": "catalytic_converter",
    "cats": "catalytic_converters",
    "catalytic_converters": "catalytic_converters",
    "catalyst_monitor": "catalytic_converter_monitor",
    "cat_monitor": "catalytic_converter_monitor",
    "catalyst_efficiency": "catalyst_system_efficiency",
    "cat_efficiency": "catalyst_system_efficiency",
    "catalyst_below_threshold": "catalyst_system_efficiency_below_threshold",
    "cat_below_threshold": "catalyst_system_efficiency_below_threshold",
    "catalyst_system_efficiency_below_threshold": "catalyst_system_efficiency_below_threshold",
    "catalyst_code": "catalyst_system_efficiency_below_threshold",

    # Mass Airflow (MAF) Sensor Diagnosis
    "maf": "mass_airflow_sensor",
    "maf_sensor": "mass_airflow_sensor",
    "mass_airflow_sensor": "mass_airflow_sensor",
    "mass_air_flow_sensor": "mass_airflow_sensor",
    "airflow_sensor": "mass_airflow_sensor",
    "air_flow_sensor": "mass_airflow_sensor",
    "maf_signal": "maf_sensor_signal",
    "maf_circuit": "maf_sensor_circuit",
    "maf_performance": "maf_sensor_performance_problem",
    "maf_low": "maf_sensor_low_input",
    "maf_high": "maf_sensor_high_input",
    "maf_fault": "maf_sensor_fault",
    "maf_error": "maf_sensor_fault",

    # Turbocharger Diagnostics
    "turbo": "turbocharger",
    "turbocharger": "turbocharger",
    "turbo_charger": "turbocharger",
    "turbo_boost": "turbocharger_boost",
    "boost": "turbocharger_boost",
    "boost_pressure": "turbocharger_boost_pressure",
    "boost_sensor": "boost_pressure_sensor",
    "wastegate": "turbocharger_wastegate",
    "waste_gate": "turbocharger_wastegate",
    "underboost": "turbocharger_underboost_condition",
    "overboost": "turbocharger_overboost_condition",
    "boost_leak": "boost_leak",
    "boost_control": "boost_control",
    "boost_controller": "boost_controller",
    "intercooler": "intercooler",
    "charge_air_cooler": "intercooler",

    # Variable Valve Timing (VVT) Systems
    "vvt": "variable_valve_timing",
    "variable_valve_timing": "variable_valve_timing",
    "vvt_solenoid": "vvt_solenoid",
    "vvt_actuator": "vvt_actuator",
    "vvt_sensor": "vvt_sensor",
    "cam_phaser": "vvt_actuator",
    "camshaft_phaser": "vvt_actuator",
    "camshaft_actuator": "vvt_actuator",
    "cam_actuator": "vvt_actuator",
    "vvt_over_advanced": "vvt_timing_over_advanced",
    "vvt_over_retarded": "vvt_timing_over_retarded",
    "vvt_fault": "vvt_fault",
    "vvt_error": "vvt_fault",

    # Diesel Engine Diagnostics
    "diesel": "diesel_engine",
    "diesel_engine": "diesel_engine",
    "diesel_injector": "diesel_injector",
    "diesel_injectors": "diesel_injectors",
    "glow_plug": "glow_plug",
    "glow_plugs": "glow_plugs",
    "dpf": "diesel_particulate_filter",
    "diesel_particulate_filter": "diesel_particulate_filter",
    "regen": "dpf_regeneration",
    "regeneration": "dpf_regeneration",
    "egr": "exhaust_gas_recirculation",
    "exhaust_gas_recirculation": "exhaust_gas_recirculation",
    "egr_valve": "egr_valve",
    "egr_system": "egr_system",
    "egr_flow": "egr_flow",
    "egr_fault": "egr_fault",
    "egr_error": "egr_fault",

    # Engine Cooling System Diagnostics
    "coolant": "engine_coolant",
    "engine_coolant": "engine_coolant",
    "cooling_system": "engine_cooling_system",
    "radiator": "radiator",
    "thermostat": "thermostat",
    "coolant_temp": "coolant_temperature",
    "coolant_temperature": "coolant_temperature",
    "ect": "engine_coolant_temperature",
    "engine_coolant_temperature": "engine_coolant_temperature",
    "coolant_sensor": "coolant_temperature_sensor",
    "coolant_temp_sensor": "coolant_temperature_sensor",
    "ect_sensor": "engine_coolant_temperature_sensor",
    "cooling_fan": "cooling_fan",
    "cooling_fan_1": "cooling_fan_1",
    "cooling_fan_2": "cooling_fan_2",
    "fan_clutch": "fan_clutch",
    "fan_controller": "fan_controller",
    "fan_relay": "fan_relay",
    "overheat": "engine_over_temperature_condition",
    "overheating": "engine_over_temperature_condition",

    # Hybrid Vehicle Powertrain Basics
    "hybrid": "hybrid_vehicle",
    "hybrid_vehicle": "hybrid_vehicle",
    "hev": "hybrid_vehicle",
    "phev": "plug_in_hybrid_vehicle",
    "plug_in_hybrid": "plug_in_hybrid_vehicle",
    "battery_pack": "hybrid_battery_pack",
    "traction_battery": "hybrid_battery_pack",
    "inverter": "inverter",
    "motor_generator": "motor_generator",
    "mg1": "motor_generator_1",
    "mg2": "motor_generator_2",
    "regen_braking": "regenerative_braking",
    "regenerative_braking": "regenerative_braking",
    "dc_dc_converter": "dc_dc_converter",
    "high_voltage": "high_voltage_system",
    "hv_system": "high_voltage_system",

    # No-Start Diagnosis Decision Tree
    "no_start": "no_start_condition",
    "nostart": "no_start_condition",
    "crank_no_start": "crank_no_start_condition",
    "cranks_but_no_start": "crank_no_start_condition",
    "no_crank": "no_crank_condition",
    "no_cranking": "no_crank_condition",
    "crank": "engine_crank",
    "cranking": "engine_crank",
    "start": "engine_start",
    "starting": "engine_start",
    "won't_start": "no_start_condition",
    "will_not_start": "no_start_condition",
    "engine_no_start": "no_start_condition",
    "engine_wont_start": "no_start_condition",
    "engine_will_not_start": "no_start_condition",
    "engine_crank_no_start": "crank_no_start_condition",
    "no_spark": "no_spark_condition",
    "no_fuel": "no_fuel_condition",
    "no_compression": "no_compression_condition",

    # Oxygen Sensor Operation and Diagnosis
    "oxygen_sensor": "o2_sensor",
    "o2_sensor": "o2_sensor",
    "lambda_sensor": "o2_sensor",
    "air_fuel_sensor": "o2_sensor",
    "wideband_sensor": "wideband_o2_sensor",
    "narrowband_sensor": "narrowband_o2_sensor",
    "o2_s1": "o2_sensor_bank_1_sensor_1",
    "o2_s2": "o2_sensor_bank_1_sensor_2",
    "o2_b1s1": "o2_sensor_bank_1_sensor_1",
    "o2_b1s2": "o2_sensor_bank_1_sensor_2",
    "o2_b2s1": "o2_sensor_bank_2_sensor_1",
    "o2_b2s2": "o2_sensor_bank_2_sensor_2",
    "o2_heater": "o2_sensor_heater",
    "o2_heater_circuit": "o2_sensor_heater_circuit",
    "o2_fault": "o2_sensor_fault",
    "o2_error": "o2_sensor_fault",

    # EGR System Diagnosis
    "egr_code": "egr_fault",
    "egr_blocked": "egr_flow_insufficient_detected",
    "egr_stuck": "egr_valve_stuck",
    "egr_valve_stuck": "egr_valve_stuck",
    "egr_valve_open": "egr_valve_open",
    "egr_valve_closed": "egr_valve_closed",
    "egr_valve_position_sensor": "egr_valve_position_sensor",
    "egr_position_sensor": "egr_valve_position_sensor",

    # EVAP System Diagnosis
    "evap": "evaporative_emission_control_system",
    "evap_system": "evaporative_emission_control_system",
    "evaporative_emission_control_system": "evaporative_emission_control_system",
    "evap_leak": "evap_system_leak",
    "evap_small_leak": "evap_system_small_leak_detected",
    "evap_large_leak": "evap_system_large_leak_detected",
    "evap_vent": "evap_vent",
    "evap_vent_valve": "evap_vent_valve",
    "evap_canister": "evap_canister",
    "charcoal_canister": "evap_canister",
    "evap_purge": "evap_purge_valve",
    "purge_valve": "evap_purge_valve",
    "purge_solenoid": "evap_purge_valve",
    "evap_purge_valve": "evap_purge_valve",
    "evap_purge_solenoid": "evap_purge_valve",
    "evap_fault": "evap_system_fault",
    "evap_error": "evap_system_fault",

    # Crankshaft and Camshaft Position Sensors
    "crankshaft_sensor": "crankshaft_position_sensor",
    "crank_sensor": "crankshaft_position_sensor",
    "crank_position_sensor": "crankshaft_position_sensor",
    "crankshaft_position_sensor": "crankshaft_position_sensor",
    "ckp": "crankshaft_position_sensor",
    "crankshaft_sensor_a": "crankshaft_position_sensor_a",
    "crankshaft_position_sensor_a": "crankshaft_position_sensor_a",
    "camshaft_sensor": "camshaft_position_sensor",
    "cam_sensor": "camshaft_position_sensor",
    "cam_position_sensor": "camshaft_position_sensor",
    "camshaft_position_sensor": "camshaft_position_sensor",
    "cmp": "camshaft_position_sensor",
    "camshaft_sensor_a": "camshaft_position_sensor_a",
    "camshaft_position_sensor_a": "camshaft_position_sensor_a",
    "crankshaft_position_sensor_b": "crankshaft_position_sensor_b",
    "camshaft_position_sensor_b": "camshaft_position_sensor_b",

    # Ignition Coil Diagnosis (Coil-on-Plug)
    "ignition_coil": "ignition_coil",
    "ignition_coils": "ignition_coils",
    "coil_on_plug": "coil_on_plug",
    "cop": "coil_on_plug",
    "coil_pack": "coil_pack",
    "coil_packs": "coil_packs",
    "coil_a": "ignition_coil_a",
    "coil_b": "ignition_coil_b",
    "coil_c": "ignition_coil_c",
    "coil_d": "ignition_coil_d",
    "primary_circuit": "primary_circuit",
    "secondary_circuit": "secondary_circuit",
    "ignition_fault": "ignition_fault",
    "ignition_error": "ignition_fault",
    "coil_fault": "ignition_coil_fault",
    "coil_error": "ignition_coil_fault",

    # Additional Synonyms, Acronyms, Misspellings, Related Terms
    "maf_senor": "mass_airflow_sensor",  # misspelling
    "catayltic_converter": "catalytic_converter",  # misspelling
    "catalitic_converter": "catalytic_converter",  # misspelling
    "misfireing": "engine_misfire",  # misspelling
    "igniton_coil": "ignition_coil",  # misspelling
    "crankshaft_postion_sensor": "crankshaft_position_sensor",  # misspelling
    "camshaft_postion_sensor": "camshaft_position_sensor",  # misspelling
    "o2_senor": "o2_sensor",  # misspelling
    "oxygen_senor": "o2_sensor",  # misspelling
    "evap_purge_valv": "evap_purge_valve",  # misspelling
    "egr_valv": "egr_valve",  # misspelling
    "engine_control_module": "ecm",
    "ecm": "engine_control_module",
    "pcm": "powertrain_control_module",
    "tcm": "transmission_control_module",
    "ecu": "engine_control_unit",
    "engine_control_unit": "engine_control_unit",
    "powertrain_control_module": "powertrain_control_module",
    "transmission_control_module": "transmission_control_module",
    "throttle_position_sensor": "tps",
    "tps": "throttle_position_sensor",
    "iat": "intake_air_temperature_sensor",
    "intake_air_temperature_sensor": "intake_air_temperature_sensor",
    "iat_sensor": "intake_air_temperature_sensor",
    "map": "manifold_absolute_pressure_sensor",
    "map_sensor": "manifold_absolute_pressure_sensor",
    "manifold_absolute_pressure_sensor": "manifold_absolute_pressure_sensor",
    "knock_sensor": "knock_sensor",
    "ks": "knock_sensor",
    "fuel_pump": "fuel_pump",
    "fuel_pump_relay": "fuel_pump_relay",
    "fuel_filter": "fuel_filter",
    "spark_plug": "spark_plug",
    "spark_plugs": "spark_plugs",
    "ignition_switch": "ignition_switch",
    "starter": "starter_motor",
    "starter_motor": "starter_motor",
    "battery": "battery",
    "alternator": "alternator",
    "voltage_regulator": "voltage_regulator",
    "fuse": "fuse",
    "relay": "relay",
    "sensor": "sensor",
    "actuator": "actuator",
    "solenoid": "solenoid",
    "valve": "valve",
    "engine_sensor": "engine_sensor",
    "engine_actuator": "engine_actuator",
    "engine_control": "engine_control",
    "engine_management": "engine_control",
    "engine_management_system": "engine_control",
    "timing_chain": "timing_chain",
    "timing_belt": "timing_belt",
    "timing_gear": "timing_gear",
    "timing_cover": "timing_cover",
    "timing_mark": "timing_mark",
    "timing": "engine_timing",
    "engine_timing": "engine_timing",
    "valve_timing": "valve_timing",
    "cam_timing": "valve_timing",
    "crank_timing": "crankshaft_timing",
    "oil_pressure": "oil_pressure",
    "oil_pressure_sensor": "oil_pressure_sensor",
    "oil_level_sensor": "oil_level_sensor",
    "oil_pump": "oil_pump",
    "oil_filter": "oil_filter",
    "oil_pan": "oil_pan",
    "oil_leak": "oil_leak",
    "oil_burn": "oil_burn",
    "oil_consumption": "oil_consumption",
    "engine_oil": "engine_oil",
    "engine_oil_pressure": "oil_pressure",
    "engine_oil_level": "oil_level_sensor",
    "engine_oil_filter": "oil_filter",
    "engine_oil_pump": "oil_pump",
    "engine_oil_pan": "oil_pan",
    "engine_oil_leak": "oil_leak",
    "engine_oil_burn": "oil_burn",
    "engine_oil_consumption": "oil_consumption",
    "engine_knock": "engine_knock",
    "detonation": "engine_knock",
    "pre_ignition": "pre_ignition",
    "pinging": "engine_knock",
    "spark_knock": "engine_knock",
    "engine_noise": "engine_noise",
    "engine_vibration": "engine_vibration",
    "engine_shake": "engine_vibration",
    "rough_idle": "rough_idle",
    "idle_problem": "rough_idle",
    "idle_issue": "rough_idle",
    "idle_speed": "idle_speed",
    "high_idle": "high_idle",
    "low_idle": "low_idle",
    "stall": "engine_stall",
    "stalling": "engine_stall",
    "engine_stall": "engine_stall",
    "engine_stalling": "engine_stall",
    "engine_hesitation": "engine_hesitation",
    "hesitation": "engine_hesitation",
    "engine_surge": "engine_surge",
    "surge": "engine_surge",
    "engine_limp_mode": "limp_mode",
    "limp_mode": "limp_mode",
    "failsafe_mode": "limp_mode",
    "safe_mode": "limp_mode",
    "reduced_power": "limp_mode",
    "reduced_engine_power": "limp_mode",
    "engine_power_reduced": "limp_mode",
    "throttle_body": "throttle_body",
    "throttle_plate": "throttle_plate",
    "throttle_actuator": "throttle_actuator",
    "electronic_throttle": "electronic_throttle",
    "drive_by_wire": "electronic_throttle",
    "throttle_cable": "throttle_cable",
    "intake_manifold": "intake_manifold",
    "intake_valve": "intake_valve",
    "exhaust_valve": "exhaust_valve",
    "valve_lifter": "valve_lifter",
    "rocker_arm": "rocker_arm",
    "push_rod": "push_rod",
    "camshaft": "camshaft",
    "crankshaft": "crankshaft",
    "piston": "piston",
    "pistons": "pistons",
    "connecting_rod": "connecting_rod",
    "rod_bearing": "rod_bearing",
    "main_bearing": "main_bearing",
    "engine_block": "engine_block",
    "cylinder_head": "cylinder_head",
    "head_gasket": "head_gasket",
    "cylinder_gasket": "head_gasket",
    "valve_cover": "valve_cover",
    "valve_cover_gasket": "valve_cover_gasket",
    "timing_cover_gasket": "timing_cover_gasket",
    "oil_seal": "oil_seal",
    "rear_main_seal": "rear_main_seal",
    "front_main_seal": "front_main_seal",
    "pcv": "positive_crankcase_ventilation",
    "positive_crankcase_ventilation": "positive_crankcase_ventilation",
    "pcv_valve": "pcv_valve",
    "crankcase": "crankcase",
    "crankcase_vent": "crankcase_vent",
    "crankcase_pressure": "crankcase_pressure",
    "vacuum_leak": "vacuum_leak",
    "intake_leak": "vacuum_leak",
    "exhaust_leak": "exhaust_leak",
    "air_leak": "vacuum_leak",
    "vacuum_hose": "vacuum_hose",
    "vacuum_line": "vacuum_hose",
    "vacuum": "vacuum",
    "manifold_vacuum": "vacuum",
    "boost_vacuum": "vacuum",
    "compression": "compression",
    "compression_test": "compression_test",
    "low_compression": "low_compression",
    "high_compression": "high_compression",
    "engine_compression": "compression",
    "engine_compression_test": "compression_test",
    "timing_light": "timing_light",
    "scan_tool": "scan_tool",
    "obd_scanner": "scan_tool",
    "code_reader": "scan_tool",
    "diagnostic_tool": "scan_tool",
    "live_data": "live_data",
    "freeze_frame": "freeze_frame",
    "readiness_monitor": "readiness_monitor",
    "monitor": "monitor",
    "emissions": "emissions",
    "emission_test": "emissions_test",
    "smog_test": "emissions_test",
    "tailpipe_emissions": "emissions",
    "fuel_trim": "fuel_trim",
    "short_term_fuel_trim": "short_term_fuel_trim",
    "long_term_fuel_trim": "long_term_fuel_trim",
    "stft": "short_term_fuel_trim",
    "ltft": "long_term_fuel_trim",
    "air_fuel_ratio": "air_fuel_ratio",
    "afr": "air_fuel_ratio",
    "stoichiometric": "stoichiometric",
    "lambda": "lambda",
    "closed_loop": "closed_loop",
    "open_loop": "open_loop",
    "fuel_system": "fuel_system",
    "fuel_delivery": "fuel_system",
    "fuel_tank": "fuel_tank",
    "fuel_line": "fuel_line",
    "fuel_rail": "fuel_rail",
    "fuel_pressure": "fuel_pressure",
    "fuel_pressure_sensor": "fuel_pressure_sensor",
    "fuel_pressure_regulator": "fuel_pressure_regulator",
    "fuel_injector": "fuel_injector",
    "fuel_injectors": "fuel_injectors",
    "fuel_pump": "fuel_pump",
    "fuel_pump_relay": "fuel_pump_relay",
    "fuel_filter": "fuel_filter",
    "fuel_gauge": "fuel_gauge",
    "fuel_level_sensor": "fuel_level_sensor",
    "fuel_pump_control_module": "fuel_pump_control_module",
    "fuel_pump_module": "fuel_pump_control_module",
    "fuel_pump_driver_module": "fuel_pump_control_module",
    "fuel_pump_driver": "fuel_pump_control_module",
    "fuel_pump_fuse": "fuel_pump_fuse",
    "fuel_pump_circuit": "fuel_pump_circuit",
    "fuel_pump_wiring": "fuel_pump_wiring",
    "fuel_pump_ground": "fuel_pump_ground",
    "fuel_pump_voltage": "fuel_pump_voltage",
    "fuel_pump_current": "fuel_pump_current",
    "fuel_pump_pressure": "fuel_pump_pressure",
    "fuel_pump_flow": "fuel_pump_flow",
    "fuel_pump_noise": "fuel_pump_noise",
    "fuel_pump_failure": "fuel_pump_failure",
    "fuel_pump_problem": "fuel_pump_failure",
    "fuel_pump_issue": "fuel_pump_failure",
    "fuel_pump_fault": "fuel_pump_failure",
    "fuel_pump_error": "fuel_pump_failure",
    "fuel_pump_malfunction": "fuel_pump_failure",
    "fuel_pump_not_running": "fuel_pump_failure",
    "fuel_pump_not_working": "fuel_pump_failure",
    "fuel_pump_not_operating": "fuel_pump_failure",
    "fuel_pump_not_functioning": "fuel_pump_failure",
    "fuel_pump_not_turning_on": "fuel_pump_failure",
    "fuel_pump_not_powered": "fuel_pump_failure",
    "fuel_pump_no_power": "fuel_pump_failure",
    "fuel_pump_no_voltage": "fuel_pump_failure",
    "fuel_pump_no_current": "fuel_pump_failure",
    "fuel_pump_no_flow": "fuel_pump_failure",
    "fuel_pump_no_pressure": "fuel_pump_failure",
    "fuel_pump_no_noise": "fuel_pump_failure",
    "fuel_pump_no_sound": "fuel_pump_failure",
    "fuel_pump_no_start": "fuel_pump_failure",
    "fuel_pump_no_run": "fuel_pump_failure",
    "fuel_pump_no_go": "fuel_pump_failure",
    "fuel_pump_no_work": "fuel_pump_failure",
    "fuel_pump_no_function": "fuel_pump_failure",
    "fuel_pump_no_operation": "fuel_pump_failure",
    "fuel_pump_no_turn_on": "fuel_pump_failure",
    "fuel_pump_no_powered": "fuel_pump_failure",
    "fuel_pump_no_voltage_input": "fuel_pump_failure",
    "fuel_pump_no_current_input": "fuel_pump_failure",
    "fuel_pump_no_flow_input": "fuel_pump_failure",
    "fuel_pump_no_pressure_input": "fuel_pump_failure",
    "fuel_pump_no_noise_input": "fuel_pump_failure",
    "fuel_pump_no_sound_input": "fuel_pump_failure",
    "fuel_pump_no_start_input": "fuel_pump_failure",
    "fuel_pump_no_run_input": "fuel_pump_failure",
    "fuel_pump_no_go_input": "fuel_pump_failure",
    "fuel_pump_no_work_input": "fuel_pump_failure",
    "fuel_pump_no_function_input": "fuel_pump_failure",
    "fuel_pump_no_operation_input": "fuel_pump_failure",
    "fuel_pump_no_turn_on_input": "fuel_pump_failure",
    "fuel_pump_no_powered_input": "fuel_pump_failure",
    "fuel_pump_no_voltage_output": "fuel_pump_failure",
    "fuel_pump_no_current_output": "fuel_pump_failure",
    "fuel_pump_no_flow_output": "fuel_pump_failure",
    "fuel_pump_no_pressure_output": "fuel_pump_failure",
    "fuel_pump_no_noise_output": "fuel_pump_failure",
    "fuel_pump_no_sound_output": "fuel_pump_failure",
    "fuel_pump_no_start_output": "fuel_pump_failure",
    "fuel_pump_no_run_output": "fuel_pump_failure",
    "fuel_pump_no_go_output": "fuel_pump_failure",
    "fuel_pump_no_work_output": "fuel_pump_failure",
    "fuel_pump_no_function_output": "fuel_pump_failure",
    "fuel_pump_no_operation_output": "fuel_pump_failure",
    "fuel_pump_no_turn_on_output": "fuel_pump_failure",
    "fuel_pump_no_powered_output": "fuel_pump_failure",
    "fuel_pump_no_voltage_supply": "fuel_pump_failure",
    "fuel_pump_no_current_supply": "fuel_pump_failure",
    "fuel_pump_no_flow_supply": "fuel_pump_failure",
    "fuel_pump_no_pressure_supply": "fuel_pump_failure",
    "fuel_pump_no_noise_supply": "fuel_pump_failure",
    "fuel_pump_no_sound_supply": "fuel_pump_failure",
    "fuel_pump_no_start_supply": "fuel_pump_failure",
    "fuel_pump_no_run_supply": "fuel_pump_failure",
    "fuel_pump_no_go_supply": "fuel_pump_failure",
    "fuel_pump_no_work_supply": "fuel_pump_failure",
    "fuel_pump_no_function_supply": "fuel_pump_failure",
    "fuel_pump_no_operation_supply": "fuel_pump_failure",
    "fuel_pump_no_turn_on_supply": "fuel_pump_failure",
    "fuel_pump_no_powered_supply": "fuel_pump_failure",
    "fuel_pump_no_voltage_return": "fuel_pump_failure",
    "fuel_pump_no_current_return": "fuel_pump_failure",
    "fuel_pump_no_flow_return": "fuel_pump_failure",
    "fuel_pump_no_pressure_return": "fuel_pump_failure",
    "fuel_pump_no_noise_return": "fuel_pump_failure",
    "fuel_pump_no_sound_return": "fuel_pump_failure",
    "fuel_pump_no_start_return": "fuel_pump_failure",
    "fuel_pump_no_run_return": "fuel_pump_failure",
    "fuel_pump_no_go_return": "fuel_pump_failure",
    "fuel_pump_no_work_return": "fuel_pump_failure",
    "fuel_pump_no_function_return": "fuel_pump_failure",
    "fuel_pump_no_operation_return": "fuel_pump_failure",
    "fuel_pump_no_turn_on_return": "fuel_pump_failure",
    "fuel_pump_no_powered_return": "fuel_pump_failure",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    data = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    current_count = len(SEMANTIC_MAP)
    current_hash = _compute_map_hash()
    is_valid = (current_count == _EXPECTED_ENTRY_COUNT) and (current_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": current_count,
        "hash": current_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_string(s):
    s = s.strip().lower()
    s = unicodedata.normalize("NFKC", s)
    s = s.replace("-", "_")
    s = s.replace(" ", "_")
    return s

def normalize_term(term: str) -> str:
    key = _normalize_string(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)