import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PROD01 Team"
SEMANTIC_MAP_ENGINE = "PROD01_production_analysis"

SEMANTIC_MAP = {
    # Vogel IPR for Solution Gas Drive Reservoirs
    "vogel": "vogel_ipr",
    "vogel ipr": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel equation": "vogel_ipr",
    "vogel model": "vogel_ipr",
    "vogel curve": "vogel_ipr",
    "solution gas drive": "solution_gas_drive",
    "solution gas": "solution_gas_drive",
    "solution gas reservoir": "solution_gas_drive",
    "solution gas drive reservoir": "solution_gas_drive",
    "sgd": "solution_gas_drive",
    "vogel inflow performance": "vogel_ipr",
    "ipr vogel": "vogel_ipr",
    "inflow performance vogel": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogel inflow": "vogel_ipr",
    "vogel inflow performance": "vogel_ipr",
    "vogel inflow performance relationship": "vogel_ipr",
    "vogel inflow performance curve": "vogel_ipr",
    "vogel inflow performance equation": "vogel_ipr",
    "vogel inflow performance model": "vogel_ipr",
    "vogel inflow performance analysis": "vogel_ipr",
    "vogel inflow analysis": "vogel_ipr",
    "vogel inflow relationship": "vogel_ipr",
    "vogel inflow curve": "vogel_ipr",
    "vogel inflow equation": "vogel_ipr",
    "vogel inflow model": "vogel_ipr",
    "vogle": "vogel_ipr",
    "vogal": "vogel_ipr",
    "voguel": "vogel_ipr",
    "voguel ipr": "vogel_ipr",
    "vogal ipr": "vogel_ipr",
    "voguel inflow": "vogel_ipr",
    "vogal inflow": "vogel_ipr",
    "voguel equation": "vogel_ipr",
    "vogal equation": "vogel_ipr",
    "voguel model": "vogel_ipr",
    "vogal model": "vogel_ipr",
    "voguel curve": "vogel_ipr",
    "vogal curve": "vogel_ipr",
    "voguel inflow performance": "vogel_ipr",
    "vogal inflow performance": "vogel_ipr",
    "voguel inflow performance relationship": "vogel_ipr",
    "vogal inflow performance relationship": "vogel_ipr",
    "voguel inflow performance curve": "vogel_ipr",
    "vogal inflow performance curve": "vogel_ipr",
    "voguel inflow performance equation": "vogel_ipr",
    "vogal inflow performance equation": "vogel_ipr",
    "voguel inflow performance model": "vogel_ipr",
    "vogal inflow performance model": "vogel_ipr",
    "voguel inflow performance analysis": "vogel_ipr",
    "vogal inflow performance analysis": "vogel_ipr",
    "voguel inflow analysis": "vogel_ipr",
    "vogal inflow analysis": "vogel_ipr",
    "voguel inflow relationship": "vogel_ipr",
    "vogal inflow relationship": "vogel_ipr",
    "voguel inflow curve": "vogel_ipr",
    "vogal inflow curve": "vogel_ipr",
    "voguel inflow equation": "vogel_ipr",
    "vogal inflow equation": "vogel_ipr",
    "voguel inflow model": "vogel_ipr",
    "vogal inflow model": "vogel_ipr",

    # Fetkovich IPR for Gas Wells
    "fetkovich": "fetkovich_ipr",
    "fetkovich ipr": "fetkovich_ipr",
    "fetkovich inflow": "fetkovich_ipr",
    "fetkovich equation": "fetkovich_ipr",
    "fetkovich model": "fetkovich_ipr",
    "fetkovich curve": "fetkovich_ipr",
    "fetkovich inflow performance": "fetkovich_ipr",
    "ipr fetkovich": "fetkovich_ipr",
    "inflow performance fetkovich": "fetkovich_ipr",
    "fetkovich inflow performance relationship": "fetkovich_ipr",
    "fetkovich inflow performance curve": "fetkovich_ipr",
    "fetkovich inflow performance equation": "fetkovich_ipr",
    "fetkovich inflow performance model": "fetkovich_ipr",
    "fetkovich inflow performance analysis": "fetkovich_ipr",
    "fetkovich inflow analysis": "fetkovich_ipr",
    "fetkovich inflow relationship": "fetkovich_ipr",
    "fetkovich inflow curve": "fetkovich_ipr",
    "fetkovich inflow equation": "fetkovich_ipr",
    "fetkovich inflow model": "fetkovich_ipr",
    "fetkovich inflow": "fetkovich_ipr",
    "fetkovich inflow performance": "fetkovich_ipr",
    "fetkovich inflow performance relationship": "fetkovich_ipr",
    "fetkovich inflow performance curve": "fetkovich_ipr",
    "fetkovich inflow performance equation": "fetkovich_ipr",
    "fetkovich inflow performance model": "fetkovich_ipr",
    "fetkovich inflow performance analysis": "fetkovich_ipr",
    "fetkovich inflow analysis": "fetkovich_ipr",
    "fetkovich inflow relationship": "fetkovich_ipr",
    "fetkovich inflow curve": "fetkovich_ipr",
    "fetkovich inflow equation": "fetkovich_ipr",
    "fetkovich inflow model": "fetkovich_ipr",
    "fetkovich inflow": "fetkovich_ipr",
    "fetkovitch": "fetkovich_ipr",
    "fetkovitch ipr": "fetkovich_ipr",
    "fetkovitch inflow": "fetkovich_ipr",
    "fetkovitch equation": "fetkovich_ipr",
    "fetkovitch model": "fetkovich_ipr",
    "fetkovitch curve": "fetkovich_ipr",
    "fetkovitch inflow performance": "fetkovich_ipr",
    "ipr fetkovitch": "fetkovich_ipr",
    "inflow performance fetkovitch": "fetkovich_ipr",
    "fetkovitch inflow performance relationship": "fetkovich_ipr",
    "fetkovitch inflow performance curve": "fetkovich_ipr",
    "fetkovitch inflow performance equation": "fetkovich_ipr",
    "fetkovitch inflow performance model": "fetkovich_ipr",
    "fetkovitch inflow performance analysis": "fetkovich_ipr",
    "fetkovitch inflow analysis": "fetkovich_ipr",
    "fetkovitch inflow relationship": "fetkovich_ipr",
    "fetkovitch inflow curve": "fetkovich_ipr",
    "fetkovitch inflow equation": "fetkovich_ipr",
    "fetkovitch inflow model": "fetkovich_ipr",
    "fetkovitch inflow": "fetkovich_ipr",
    "gas well ipr": "fetkovich_ipr",
    "ipr gas well": "fetkovich_ipr",
    "gas well inflow": "fetkovich_ipr",
    "gas well inflow performance": "fetkovich_ipr",
    "gas well inflow performance relationship": "fetkovich_ipr",
    "gas well inflow performance curve": "fetkovich_ipr",
    "gas well inflow performance equation": "fetkovich_ipr",
    "gas well inflow performance model": "fetkovich_ipr",
    "gas well inflow performance analysis": "fetkovich_ipr",
    "gas well inflow analysis": "fetkovich_ipr",
    "gas well inflow relationship": "fetkovich_ipr",
    "gas well inflow curve": "fetkovich_ipr",
    "gas well inflow equation": "fetkovich_ipr",
    "gas well inflow model": "fetkovich_ipr",
    "fetkovich gas well": "fetkovich_ipr",

    # Nodal Analysis - System Optimization
    "nodal analysis": "nodal_analysis",
    "system optimization": "system_optimization",
    "nodal": "nodal_analysis",
    "system optimum": "system_optimization",
    "system opt": "system_optimization",
    "system analysis": "system_optimization",
    "nodal system": "nodal_analysis",
    "nodal system analysis": "nodal_analysis",
    "nodal optimization": "system_optimization",
    "nodal opt": "system_optimization",
    "system node analysis": "nodal_analysis",
    "system nodal analysis": "nodal_analysis",
    "system nodal": "nodal_analysis",
    "nodal optimization analysis": "system_optimization",
    "nodal system optimization": "system_optimization",
    "nodal analysis optimization": "system_optimization",
    "node analysis": "nodal_analysis",
    "node optimization": "system_optimization",

    # Skin Factor and Flow Efficiency
    "skin": "skin_factor",
    "skin factor": "skin_factor",
    "flow efficiency": "flow_efficiency",
    "wellbore skin": "skin_factor",
    "well skin": "skin_factor",
    "well skin factor": "skin_factor",
    "skin value": "skin_factor",
    "skin effect": "skin_factor",
    "well flow efficiency": "flow_efficiency",
    "relative flow efficiency": "flow_efficiency",
    "flow eff": "flow_efficiency",
    "skin calculation": "skin_factor",
    "skin estimation": "skin_factor",
    "skin analysis": "skin_factor",
    "skin measurement": "skin_factor",
    "skin evaluation": "skin_factor",
    "skin test": "skin_factor",
    "skin factor analysis": "skin_factor",
    "skin factor estimation": "skin_factor",
    "skin factor evaluation": "skin_factor",
    "skin factor calculation": "skin_factor",
    "skin factor measurement": "skin_factor",

    # Productivity Index and Reservoir Deliverability
    "productivity index": "productivity_index",
    "pi": "productivity_index",
    "well pi": "productivity_index",
    "prod index": "productivity_index",
    "prod. index": "productivity_index",
    "well productivity": "productivity_index",
    "reservoir deliverability": "reservoir_deliverability",
    "deliverability": "reservoir_deliverability",
    "well deliverability": "reservoir_deliverability",
    "reservoir productivity": "productivity_index",
    "productivity": "productivity_index",
    "deliverability curve": "reservoir_deliverability",
    "deliverability analysis": "reservoir_deliverability",
    "deliverability test": "reservoir_deliverability",
    "deliverability estimation": "reservoir_deliverability",
    "deliverability evaluation": "reservoir_deliverability",
    "deliverability calculation": "reservoir_deliverability",

    # Water Cut and GOR Trending - Reservoir Surveillance
    "water cut": "water_cut",
    "wc": "water_cut",
    "wcut": "water_cut",
    "watercut": "water_cut",
    "w/c": "water_cut",
    "watercut trending": "water_cut_trending",
    "water cut trending": "water_cut_trending",
    "watercut trend": "water_cut_trending",
    "water cut trend": "water_cut_trending",
    "gor": "gas_oil_ratio",
    "gas oil ratio": "gas_oil_ratio",
    "g/o ratio": "gas_oil_ratio",
    "g/o": "gas_oil_ratio",
    "gor trending": "gor_trending",
    "gor trend": "gor_trending",
    "gas oil ratio trending": "gor_trending",
    "gas oil ratio trend": "gor_trending",
    "reservoir surveillance": "reservoir_surveillance",
    "surveillance": "reservoir_surveillance",
    "well surveillance": "reservoir_surveillance",
    "production surveillance": "reservoir_surveillance",
    "surveillance trending": "reservoir_surveillance",
    "reservoir monitoring": "reservoir_surveillance",
    "well monitoring": "reservoir_surveillance",

    # Pressure Buildup Test Analysis
    "pressure buildup": "pressure_buildup",
    "pbu": "pressure_buildup",
    "pressure buildup test": "pressure_buildup_test",
    "pbu test": "pressure_buildup_test",
    "pressure buildup analysis": "pressure_buildup_analysis",
    "pbu analysis": "pressure_buildup_analysis",
    "buildup test": "pressure_buildup_test",
    "buildup analysis": "pressure_buildup_analysis",
    "pressure build up": "pressure_buildup",
    "pressure build up test": "pressure_buildup_test",
    "pressure build up analysis": "pressure_buildup_analysis",
    "build up test": "pressure_buildup_test",
    "build up analysis": "pressure_buildup_analysis",
    "pressure buildup survey": "pressure_buildup_test",
    "pressure build up survey": "pressure_buildup_test",

    # Material Balance Equation - Reservoir Drive
    "material balance": "material_balance",
    "material balance equation": "material_balance_equation",
    "mbe": "material_balance_equation",
    "mbal": "material_balance_equation",
    "material balance analysis": "material_balance_analysis",
    "material balance calculation": "material_balance_equation",
    "material balance evaluation": "material_balance_equation",
    "reservoir drive": "reservoir_drive",
    "drive mechanism": "reservoir_drive",
    "reservoir drive mechanism": "reservoir_drive",
    "reservoir drive analysis": "reservoir_drive",
    "drive analysis": "reservoir_drive",
    "drive calculation": "reservoir_drive",
    "drive evaluation": "reservoir_drive",

    # Flowing Bottomhole Pressure Estimation
    "flowing bottomhole pressure": "fbhp",
    "fbhp": "fbhp",
    "bottomhole pressure": "fbhp",
    "bhp": "fbhp",
    "flowing bhp": "fbhp",
    "flowing bottom hole pressure": "fbhp",
    "bottom hole pressure": "fbhp",
    "fbhp estimation": "fbhp_estimation",
    "bhp estimation": "fbhp_estimation",
    "flowing bhp estimation": "fbhp_estimation",
    "bottomhole pressure estimation": "fbhp_estimation",
    "bottom hole pressure estimation": "fbhp_estimation",
    "fbhp calculation": "fbhp_estimation",
    "bhp calculation": "fbhp_estimation",

    # Choke Sizing and Critical Flow
    "choke sizing": "choke_sizing",
    "choke size": "choke_sizing",
    "choke calculation": "choke_sizing",
    "choke design": "choke_sizing",
    "choke selection": "choke_sizing",
    "choke": "choke_sizing",
    "critical flow": "critical_flow",
    "sonic flow": "critical_flow",
    "choked flow": "critical_flow",
    "critical flow analysis": "critical_flow",
    "critical flow calculation": "critical_flow",
    "critical flow estimation": "critical_flow",
    "choke critical flow": "critical_flow",
    "choke flow": "critical_flow",

    # Production System Optimization - Economic Limit
    "production system optimization": "production_system_optimization",
    "system optimization": "production_system_optimization",
    "prod system optimization": "production_system_optimization",
    "production optimization": "production_system_optimization",
    "prod optimization": "production_system_optimization",
    "economic limit": "economic_limit",
    "econ limit": "economic_limit",
    "economic cutoff": "economic_limit",
    "production economic limit": "economic_limit",
    "system economic limit": "economic_limit",
    "economic limit test": "economic_limit",
    "economic limit analysis": "economic_limit",

    # Artificial Lift Selection - Transition from Natural Flow
    "artificial lift": "artificial_lift",
    "artificial lift selection": "artificial_lift_selection",
    "lift selection": "artificial_lift_selection",
    "als": "artificial_lift_selection",
    "artificial lift system": "artificial_lift",
    "transition from natural flow": "transition_natural_flow",
    "natural flow transition": "transition_natural_flow",
    "transition to artificial lift": "transition_natural_flow",
    "natural to artificial lift": "transition_natural_flow",
    "natural flow": "natural_flow",
    "natural flowing": "natural_flow",
    "from natural flow": "transition_natural_flow",
    "to artificial lift": "transition_natural_flow",
    "artificial lift analysis": "artificial_lift_selection",
    "artificial lift evaluation": "artificial_lift_selection",

    # Horizontal Well Productivity - Permian Unconventionals
    "horizontal well": "horizontal_well",
    "hz well": "horizontal_well",
    "h well": "horizontal_well",
    "horizontal well productivity": "horizontal_well_productivity",
    "hz well productivity": "horizontal_well_productivity",
    "permian unconventionals": "permian_unconventionals",
    "permian basin unconventionals": "permian_unconventionals",
    "permian": "permian_basin",
    "permian basin": "permian_basin",
    "unconventional": "unconventional",
    "unconventionals": "unconventional",
    "unconventional reservoir": "unconventional",
    "unconventional well": "unconventional",
    "permian horizontal": "horizontal_well",
    "permian hz": "horizontal_well",
    "permian hz well": "horizontal_well",
    "permian horizontal well": "horizontal_well",
    "permian well": "permian_basin",
    "permian production": "permian_basin",
    "permian basin production": "permian_basin",

    # Production Data Quality Control and Validation
    "production data qc": "production_data_qc",
    "production data quality control": "production_data_qc",
    "prod data qc": "production_data_qc",
    "prod data quality control": "production_data_qc",
    "production data validation": "production_data_validation",
    "prod data validation": "production_data_validation",
    "data qc": "production_data_qc",
    "data quality control": "production_data_qc",
    "data validation": "production_data_validation",
    "production data check": "production_data_qc",
    "production data review": "production_data_qc",
    "production data audit": "production_data_qc",
    "production data verification": "production_data_validation",
    "production data": "production_data_qc",

    # Multiphase Flow Correlations - Hagedorn-Brown
    "multiphase flow": "multiphase_flow",
    "multiphase": "multiphase_flow",
    "multiphase flow correlation": "multiphase_flow_correlation",
    "multiphase flow correlations": "multiphase_flow_correlation",
    "hagedorn brown": "hagedorn_brown",
    "hagedorn-brown": "hagedorn_brown",
    "hagedorn brown correlation": "hagedorn_brown",
    "hagedorn-brown correlation": "hagedorn_brown",
    "hagedorn brown multiphase": "hagedorn_brown",
    "hagedorn-brown multiphase": "hagedorn_brown",
    "hagedorn brown multiphase flow": "hagedorn_brown",
    "hagedorn-brown multiphase flow": "hagedorn_brown",
    "hagedorn brown model": "hagedorn_brown",
    "hagedorn-brown model": "hagedorn_brown",
    "hagedorn brown equation": "hagedorn_brown",
    "hagedorn-brown equation": "hagedorn_brown",
    "hagedorn brown method": "hagedorn_brown",
    "hagedorn-brown method": "hagedorn_brown",
    "hagedorn brown analysis": "hagedorn_brown",
    "hagedorn-brown analysis": "hagedorn_brown",

    # Beggs-Brill Correlation - Inclined Multiphase Flow
    "beggs brill": "beggs_brill",
    "beggs-brill": "beggs_brill",
    "beggs brill correlation": "beggs_brill",
    "beggs-brill correlation": "beggs_brill",
    "beggs brill multiphase": "beggs_brill",
    "beggs-brill multiphase": "beggs_brill",
    "beggs brill multiphase flow": "beggs_brill",
    "beggs-brill multiphase flow": "beggs_brill",
    "beggs brill model": "beggs_brill",
    "beggs-brill model": "beggs_brill",
    "beggs brill equation": "beggs_brill",
    "beggs-brill equation": "beggs_brill",
    "beggs brill method": "beggs_brill",
    "beggs-brill method": "beggs_brill",
    "beggs brill analysis": "beggs_brill",
    "beggs-brill analysis": "beggs_brill",
    "inclined multiphase flow": "inclined_multiphase_flow",
    "inclined flow": "inclined_multiphase_flow",
    "inclined multiphase": "inclined_multiphase_flow",
    "inclined flow correlation": "inclined_multiphase_flow",
    "inclined multiphase correlation": "inclined_multiphase_flow",

    # Decline Curve Analysis - Arps Equations
    "decline curve": "decline_curve",
    "decline curve analysis": "decline_curve_analysis",
    "dca": "decline_curve_analysis",
    "arps": "arps_equation",
    "arps equation": "arps_equation",
    "arps equations": "arps_equation",
    "arps decline": "arps_equation",
    "arps decline curve": "arps_equation",
    "arps decline curve analysis": "arps_equation",
    "arps dca": "arps_equation",
    "arps model": "arps_equation",
    "arps analysis": "arps_equation",
    "arps decline analysis": "arps_equation",
    "arps decline model": "arps_equation",
    "arps decline equation": "arps_equation",
    "arps decline equations": "arps_equation",
    "decline analysis": "decline_curve_analysis",
    "decline curve model": "decline_curve",
    "decline curve equation": "decline_curve",
    "decline curve equations": "decline_curve",
    "decline curve fitting": "decline_curve_analysis",
    "decline curve fit": "decline_curve_analysis",
    "decline curve estimation": "decline_curve_analysis",
    "decline curve evaluation": "decline_curve_analysis",

    # Wellbore Storage Effect in Well Testing
    "wellbore storage": "wellbore_storage",
    "wellbore storage effect": "wellbore_storage",
    "wellbore storage analysis": "wellbore_storage",
    "wellbore storage test": "wellbore_storage",
    "wellbore storage evaluation": "wellbore_storage",
    "wellbore storage calculation": "wellbore_storage",
    "well storage": "wellbore_storage",
    "well storage effect": "wellbore_storage",
    "well storage analysis": "wellbore_storage",
    "well storage test": "wellbore_storage",
    "well storage evaluation": "wellbore_storage",
    "well storage calculation": "wellbore_storage",

    # Permian Basin Production Characteristics
    "permian basin production characteristics": "permian_basin_production_characteristics",
    "permian production characteristics": "permian_basin_production_characteristics",
    "permian basin characteristics": "permian_basin_production_characteristics",
    "permian characteristics": "permian_basin_production_characteristics",
    "permian basin prod characteristics": "permian_basin_production_characteristics",
    "permian prod characteristics": "permian_basin_production_characteristics",
    "permian basin prod char": "permian_basin_production_characteristics",
    "permian prod char": "permian_basin_production_characteristics",
    "permian basin production char": "permian_basin_production_characteristics",
    "permian production char": "permian_basin_production_characteristics",

    # Production Allocation and Commingled Flow
    "production allocation": "production_allocation",
    "prod allocation": "production_allocation",
    "allocation": "production_allocation",
    "commingled flow": "commingled_flow",
    "commingled": "commingled_flow",
    "commingled production": "commingled_flow",
    "commingled well": "commingled_flow",
    "commingled allocation": "commingled_flow",
    "commingled flow allocation": "commingled_flow",
    "commingled flow analysis": "commingled_flow",
    "commingled flow evaluation": "commingled_flow",
    "commingled flow calculation": "commingled_flow",
    "commingled flow estimation": "commingled_flow",
    "commingled flow test": "commingled_flow",
    "commingled flow measurement": "commingled_flow",
    "commingled flow monitoring": "commingled_flow",
    "commingled flow control": "commingled_flow",
    "commingled flow surveillance": "commingled_flow",
    "commingled flow trending": "commingled_flow",
    "commingled flow review": "commingled_flow",
    "commingled flow audit": "commingled_flow",
    "commingled flow verification": "commingled_flow",
    "commingled flow validation": "commingled_flow",
    "commingled flow check": "commingled_flow",
    "commingled flow data": "commingled_flow",
    "commingled flow system": "commingled_flow",
    "commingled flow process": "commingled_flow",
    "commingled flow operation": "commingled_flow",
    "commingled flow optimization": "commingled_flow",
    "commingled flow performance": "commingled_flow",
    "commingled flow characteristics": "commingled_flow",
    "commingled flow properties": "commingled_flow",
    "commingled flow parameters": "commingled_flow",
    "commingled flow profile": "commingled_flow",
    "commingled flow distribution": "commingled_flow",
    "commingled flow rate": "commingled_flow",
    "commingled flow volume": "commingled_flow",
    "commingled flow capacity": "commingled_flow",
    "commingled flow potential": "commingled_flow",
    "commingled flow deliverability": "commingled_flow",
    "commingled flow productivity": "commingled_flow",
    "commingled flow allocation analysis": "commingled_flow",
    "commingled flow allocation evaluation": "commingled_flow",
    "commingled flow allocation calculation": "commingled_flow",
    "commingled flow allocation estimation": "commingled_flow",
    "commingled flow allocation test": "commingled_flow",
    "commingled flow allocation measurement": "commingled_flow",
    "commingled flow allocation monitoring": "commingled_flow",
    "commingled flow allocation control": "commingled_flow",
    "commingled flow allocation surveillance": "commingled_flow",
    "commingled flow allocation trending": "commingled_flow",
    "commingled flow allocation review": "commingled_flow",
    "commingled flow allocation audit": "commingled_flow",
    "commingled flow allocation verification": "commingled_flow",
    "commingled flow allocation validation": "commingled_flow",
    "commingled flow allocation check": "commingled_flow",
    "commingled flow allocation data": "commingled_flow",
    "commingled flow allocation system": "commingled_flow",
    "commingled flow allocation process": "commingled_flow",
    "commingled flow allocation operation": "commingled_flow",
    "commingled flow allocation optimization": "commingled_flow",
    "commingled flow allocation performance": "commingled_flow",
    "commingled flow allocation characteristics": "commingled_flow",
    "commingled flow allocation properties": "commingled_flow",
    "commingled flow allocation parameters": "commingled_flow",
    "commingled flow allocation profile": "commingled_flow",
    "commingled flow allocation distribution": "commingled_flow",
    "commingled flow allocation rate": "commingled_flow",
    "commingled flow allocation volume": "commingled_flow",
    "commingled flow allocation capacity": "commingled_flow",
    "commingled flow allocation potential": "commingled_flow",
    "commingled flow allocation deliverability": "commingled_flow",
    "commingled flow allocation productivity": "commingled_flow",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    raw = ";".join(f"{k}=>{v}" for k, v in items)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid
    }

def _normalize_string(s):
    s = s.lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.replace("-", " ").replace("_", " ")
    s = " ".join(s.split())
    return s

def normalize_term(term: str) -> str:
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)