import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENT03_engine_team"
SEMANTIC_MAP_ENGINE = "ENT03_mergers_acquisitions"

SEMANTIC_MAP = {
    # Asset Purchase vs Stock Purchase Structure
    "asset purchase": "asset_purchase",
    "asset acquisition": "asset_purchase",
    "asset sale": "asset_purchase",
    "asset deal": "asset_purchase",
    "asset transfer": "asset_purchase",
    "purchase of assets": "asset_purchase",
    "buying assets": "asset_purchase",
    "stock purchase": "stock_purchase",
    "stock acquisition": "stock_purchase",
    "stock deal": "stock_purchase",
    "stock sale": "stock_purchase",
    "share purchase": "stock_purchase",
    "share acquisition": "stock_purchase",
    "share deal": "stock_purchase",
    "share sale": "stock_purchase",
    "purchase of stock": "stock_purchase",
    "buying stock": "stock_purchase",
    "buying shares": "stock_purchase",
    "equity purchase": "stock_purchase",
    "equity acquisition": "stock_purchase",
    "equity deal": "stock_purchase",
    "equity sale": "stock_purchase",
    "purchase of equity": "stock_purchase",
    "buying equity": "stock_purchase",
    "stock vs asset": "asset_vs_stock",
    "asset vs stock": "asset_vs_stock",
    "structure asset purchase": "asset_purchase",
    "structure stock purchase": "stock_purchase",
    "deal structure": "deal_structure",
    "transaction structure": "deal_structure",
    "purchase structure": "deal_structure",
    "acquisition structure": "deal_structure",
    "merger structure": "deal_structure",
    "stock transfer": "stock_purchase",
    "asset transfer structure": "asset_purchase",
    "stock transfer structure": "stock_purchase",
    "asset purchase agreement": "asset_purchase_agreement",
    "stock purchase agreement": "stock_purchase_agreement",
    "spa": "stock_purchase_agreement",
    "apa": "asset_purchase_agreement",
    "stock purchase agmt": "stock_purchase_agreement",
    "asset purchase agmt": "asset_purchase_agreement",
    "stock purchase contract": "stock_purchase_agreement",
    "asset purchase contract": "asset_purchase_agreement",
    "stock purchase doc": "stock_purchase_agreement",
    "asset purchase doc": "asset_purchase_agreement",
    "stock purchase documentation": "stock_purchase_agreement",
    "asset purchase documentation": "asset_purchase_agreement",
    "stock purchase document": "stock_purchase_agreement",
    "asset purchase document": "asset_purchase_agreement",
    # Hart-Scott-Rodino HSR Filing Thresholds
    "hart scott rodino": "hsr",
    "hsr": "hsr",
    "hsr filing": "hsr_filing",
    "hsr threshold": "hsr_threshold",
    "hsr notification": "hsr_filing",
    "hsr premerger notification": "hsr_filing",
    "hsr act": "hsr",
    "premerger notification": "hsr_filing",
    "premerger notification act": "hsr",
    "hsr filing threshold": "hsr_threshold",
    "hsr thresholds": "hsr_threshold",
    "hsr exemption": "hsr_exemption",
    "hsr reportable": "hsr_reportable",
    "hsr reportable transaction": "hsr_reportable",
    "hsr reportable deal": "hsr_reportable",
    "hsr filing required": "hsr_required",
    "hsr required": "hsr_required",
    "hsr not required": "hsr_not_required",
    "hsr clearance": "hsr_clearance",
    "hsr waiting period": "hsr_waiting_period",
    "hsr second request": "hsr_second_request",
    "hsr early termination": "hsr_early_termination",
    "hsr antitrust": "hsr",
    "hsr antitrust review": "hsr_review",
    "hsr review": "hsr_review",
    "hsr merger review": "hsr_review",
    "hsr filing fee": "hsr_filing_fee",
    "hsr filing fees": "hsr_filing_fee",
    "hsr filing cost": "hsr_filing_fee",
    "hsr filing costs": "hsr_filing_fee",
    "hsr notification threshold": "hsr_threshold",
    "hsr notification thresholds": "hsr_threshold",
    "hsr notification exemption": "hsr_exemption",
    "hsr notification required": "hsr_required",
    "hsr notification not required": "hsr_not_required",
    "hsr notification clearance": "hsr_clearance",
    "hsr notification waiting period": "hsr_waiting_period",
    "hsr notification second request": "hsr_second_request",
    "hsr notification early termination": "hsr_early_termination",
    # CFIUS Foreign Investment Review FIRRMA
    "cfius": "cfius",
    "cfius review": "cfius_review",
    "cfius filing": "cfius_filing",
    "cfius notification": "cfius_filing",
    "cfius approval": "cfius_approval",
    "cfius clearance": "cfius_clearance",
    "cfius mandatory filing": "cfius_mandatory_filing",
    "cfius voluntary filing": "cfius_voluntary_filing",
    "cfius declaration": "cfius_declaration",
    "cfius notice": "cfius_notice",
    "cfius investigation": "cfius_investigation",
    "cfius foreign investment": "cfius_foreign_investment",
    "cfius foreign investor": "cfius_foreign_investor",
    "cfius covered transaction": "cfius_covered_transaction",
    "cfius covered deals": "cfius_covered_transaction",
    "cfius covered investments": "cfius_covered_transaction",
    "firrma": "firrma",
    "firrma review": "firrma_review",
    "firrma filing": "firrma_filing",
    "firrma notification": "firrma_filing",
    "firrma approval": "firrma_approval",
    "firrma clearance": "firrma_clearance",
    "firrma mandatory filing": "firrma_mandatory_filing",
    "firrma voluntary filing": "firrma_voluntary_filing",
    "firrma declaration": "firrma_declaration",
    "firrma notice": "firrma_notice",
    "firrma investigation": "firrma_investigation",
    "firrma foreign investment": "firrma_foreign_investment",
    "firrma foreign investor": "firrma_foreign_investor",
    "firrma covered transaction": "firrma_covered_transaction",
    "firrma covered deals": "firrma_covered_transaction",
    "firrma covered investments": "firrma_covered_transaction",
    "foreign investment review": "cfius_review",
    "foreign investment approval": "cfius_approval",
    "foreign investment clearance": "cfius_clearance",
    "foreign investment mandatory filing": "cfius_mandatory_filing",
    "foreign investment voluntary filing": "cfius_voluntary_filing",
    "foreign investment declaration": "cfius_declaration",
    "foreign investment notice": "cfius_notice",
    "foreign investment investigation": "cfius_investigation",
    "foreign investor review": "cfius_review",
    "foreign investor approval": "cfius_approval",
    "foreign investor clearance": "cfius_clearance",
    "foreign investor mandatory filing": "cfius_mandatory_filing",
    "foreign investor voluntary filing": "cfius_voluntary_filing",
    "foreign investor declaration": "cfius_declaration",
    "foreign investor notice": "cfius_notice",
    "foreign investor investigation": "cfius_investigation",
    # Tax-Free Reorganizations IRC Section 368
    "tax free reorganization": "tax_free_reorg",
    "tax-free reorganization": "tax_free_reorg",
    "tax free reorg": "tax_free_reorg",
    "tax-free reorg": "tax_free_reorg",
    "irc section 368": "irc_368",
    "section 368": "irc_368",
    "irc 368": "irc_368",
    "368 reorganization": "irc_368",
    "368 reorg": "irc_368",
    "tax-free merger": "tax_free_reorg",
    "tax free merger": "tax_free_reorg",
    "tax-free acquisition": "tax_free_reorg",
    "tax free acquisition": "tax_free_reorg",
    "tax-free exchange": "tax_free_reorg",
    "tax free exchange": "tax_free_reorg",
    "tax-free transaction": "tax_free_reorg",
    "tax free transaction": "tax_free_reorg",
    "tax-free deal": "tax_free_reorg",
    "tax free deal": "tax_free_reorg",
    "tax-free structure": "tax_free_reorg",
    "tax free structure": "tax_free_reorg",
    "tax-free reorganizations": "tax_free_reorg",
    "tax free reorganizations": "tax_free_reorg",
    "tax-free mergers": "tax_free_reorg",
    "tax free mergers": "tax_free_reorg",
    "tax-free acquisitions": "tax_free_reorg",
    "tax free acquisitions": "tax_free_reorg",
    "tax-free exchanges": "tax_free_reorg",
    "tax free exchanges": "tax_free_reorg",
    "tax-free transactions": "tax_free_reorg",
    "tax free transactions": "tax_free_reorg",
    "tax-free deals": "tax_free_reorg",
    "tax free deals": "tax_free_reorg",
    "tax-free structures": "tax_free_reorg",
    "tax free structures": "tax_free_reorg",
    "irc section 368(a)": "irc_368",
    "section 368(a)": "irc_368",
    "irc 368(a)": "irc_368",
    "368(a) reorganization": "irc_368",
    "368(a) reorg": "irc_368",
    "368(a) merger": "irc_368",
    "368(a) acquisition": "irc_368",
    "368(a) exchange": "irc_368",
    # Delaware Merger Statute DGCL Section 251
    "delaware merger statute": "dgcl_251",
    "dgcl section 251": "dgcl_251",
    "section 251": "dgcl_251",
    "dgcl 251": "dgcl_251",
    "delaware general corporation law": "dgcl",
    "dgcl": "dgcl",
    "delaware merger": "dgcl_251",
    "delaware merger law": "dgcl_251",
    "delaware merger statute section 251": "dgcl_251",
    "delaware section 251": "dgcl_251",
    "delaware corporate merger": "dgcl_251",
    "delaware corporation merger": "dgcl_251",
    "delaware corporate law": "dgcl",
    "delaware corporation law": "dgcl",
    "delaware corp law": "dgcl",
    "delaware corp merger": "dgcl_251",
    "delaware corp statute": "dgcl",
    "delaware corp merger statute": "dgcl_251",
    "delaware merger statute sec 251": "dgcl_251",
    "delaware merger statute s251": "dgcl_251",
    "delaware merger statute 251": "dgcl_251",
    "delaware merger section 251": "dgcl_251",
    "delaware merger sec 251": "dgcl_251",
    "delaware merger s251": "dgcl_251",
    "delaware merger 251": "dgcl_251",
    "dgcl section 251(a)": "dgcl_251",
    "section 251(a)": "dgcl_251",
    "dgcl 251(a)": "dgcl_251",
    "delaware merger statute section 251(a)": "dgcl_251",
    "delaware section 251(a)": "dgcl_251",
    "delaware merger section 251(a)": "dgcl_251",
    "delaware merger sec 251(a)": "dgcl_251",
    "delaware merger s251(a)": "dgcl_251",
    "delaware merger 251(a)": "dgcl_251",
    # Material Adverse Change MAC Clauses
    "material adverse change": "mac",
    "mac": "mac",
    "mac clause": "mac_clause",
    "mac clauses": "mac_clause",
    "material adverse change clause": "mac_clause",
    "material adverse change clauses": "mac_clause",
    "material adverse effect": "mac",
    "mae": "mac",
    "mae clause": "mac_clause",
    "mae clauses": "mac_clause",
    "material adverse effect clause": "mac_clause",
    "material adverse effect clauses": "mac_clause",
    "material adverse change event": "mac_event",
    "material adverse effect event": "mac_event",
    "mac event": "mac_event",
    "mae event": "mac_event",
    "mac trigger": "mac_event",
    "mae trigger": "mac_event",
    "mac provision": "mac_clause",
    "mae provision": "mac_clause",
    "mac provisions": "mac_clause",
    "mae provisions": "mac_clause",
    "material adverse change provision": "mac_clause",
    "material adverse effect provision": "mac_clause",
    "material adverse change provisions": "mac_clause",
    "material adverse effect provisions": "mac_clause",
    "mac definition": "mac_definition",
    "mae definition": "mac_definition",
    "mac definitions": "mac_definition",
    "mae definitions": "mac_definition",
    "material adverse change definition": "mac_definition",
    "material adverse effect definition": "mac_definition",
    "material adverse change definitions": "mac_definition",
    "material adverse effect definitions": "mac_definition",
    # Representations and Warranties Insurance
    "representations and warranties insurance": "rwi",
    "rep and warranty insurance": "rwi",
    "rep & warranty insurance": "rwi",
    "rwi": "rwi",
    "reps and warranties insurance": "rwi",
    "reps & warranties insurance": "rwi",
    "reps warranty insurance": "rwi",
    "reps insurance": "rwi",
    "warranty insurance": "rwi",
    "representation insurance": "rwi",
    "rep insurance": "rwi",
    "warranties insurance": "rwi",
    "rep warranty insurance": "rwi",
    "rwi policy": "rwi_policy",
    "rwi policies": "rwi_policy",
    "rwi coverage": "rwi_coverage",
    "rwi cover": "rwi_coverage",
    "rwi premium": "rwi_premium",
    "rwi premiums": "rwi_premium",
    "rwi insurer": "rwi_insurer",
    "rwi insurers": "rwi_insurer",
    "rwi broker": "rwi_broker",
    "rwi brokers": "rwi_broker",
    "rwi underwriter": "rwi_underwriter",
    "rwi underwriters": "rwi_underwriter",
    "rep and warranty policy": "rwi_policy",
    "rep & warranty policy": "rwi_policy",
    "rep and warranty coverage": "rwi_coverage",
    "rep & warranty coverage": "rwi_coverage",
    "rep and warranty premium": "rwi_premium",
    "rep & warranty premium": "rwi_premium",
    "rep and warranty insurer": "rwi_insurer",
    "rep & warranty insurer": "rwi_insurer",
    "rep and warranty broker": "rwi_broker",
    "rep & warranty broker": "rwi_broker",
    "rep and warranty underwriter": "rwi_underwriter",
    "rep & warranty underwriter": "rwi_underwriter",
    # Earnouts and Contingent Consideration
    "earnout": "earnout",
    "earnouts": "earnout",
    "contingent consideration": "contingent_consideration",
    "contingent payment": "contingent_consideration",
    "contingent payments": "contingent_consideration",
    "contingent price": "contingent_consideration",
    "contingent pricing": "contingent_consideration",
    "contingent purchase price": "contingent_consideration",
    "contingent purchase payment": "contingent_consideration",
    "contingent purchase payments": "contingent_consideration",
    "contingent consideration structure": "contingent_consideration",
    "earnout structure": "earnout",
    "earnout payment": "earnout_payment",
    "earnout payments": "earnout_payment",
    "earnout price": "earnout_payment",
    "earnout pricing": "earnout_payment",
    "earnout purchase price": "earnout_payment",
    "earnout purchase payment": "earnout_payment",
    "earnout purchase payments": "earnout_payment",
    "earnout consideration": "earnout",
    "earnout clause": "earnout_clause",
    "earnout clauses": "earnout_clause",
    "earnout provision": "earnout_clause",
    "earnout provisions": "earnout_clause",
    "contingent consideration clause": "contingent_consideration_clause",
    "contingent consideration clauses": "contingent_consideration_clause",
    "contingent consideration provision": "contingent_consideration_clause",
    "contingent consideration provisions": "contingent_consideration_clause",
    # Due Diligence and Sandbagging
    "due diligence": "due_diligence",
    "due diligence review": "due_diligence",
    "due diligence process": "due_diligence",
    "due diligence investigation": "due_diligence",
    "due diligence checklist": "due_diligence_checklist",
    "due diligence list": "due_diligence_checklist",
    "due diligence items": "due_diligence_checklist",
    "due diligence report": "due_diligence_report",
    "due diligence reports": "due_diligence_report",
    "due diligence findings": "due_diligence_report",
    "due diligence summary": "due_diligence_report",
    "due diligence request": "due_diligence_request",
    "due diligence requests": "due_diligence_request",
    "diligence": "due_diligence",
    "diligence review": "due_diligence",
    "diligence process": "due_diligence",
    "diligence investigation": "due_diligence",
    "diligence checklist": "due_diligence_checklist",
    "diligence list": "due_diligence_checklist",
    "diligence items": "due_diligence_checklist",
    "diligence report": "due_diligence_report",
    "diligence reports": "due_diligence_report",
    "diligence findings": "due_diligence_report",
    "diligence summary": "due_diligence_report",
    "diligence request": "due_diligence_request",
    "diligence requests": "due_diligence_request",
    "sandbagging": "sandbagging",
    "sandbag": "sandbagging",
    "sandbagging clause": "sandbagging_clause",
    "sandbagging clauses": "sandbagging_clause",
    "sandbagging provision": "sandbagging_clause",
    "sandbagging provisions": "sandbagging_clause",
    "sandbagging right": "sandbagging_right",
    "sandbagging rights": "sandbagging_right",
    "anti-sandbagging": "anti_sandbagging",
    "anti sandbagging": "anti_sandbagging",
    "anti-sandbagging clause": "anti_sandbagging_clause",
    "anti sandbagging clause": "anti_sandbagging_clause",
    "anti-sandbagging clauses": "anti_sandbagging_clause",
    "anti sandbagging clauses": "anti_sandbagging_clause",
    "anti-sandbagging provision": "anti_sandbagging_clause",
    "anti sandbagging provision": "anti_sandbagging_clause",
    "anti-sandbagging provisions": "anti_sandbagging_clause",
    "anti sandbagging provisions": "anti_sandbagging_clause",
    "anti-sandbagging right": "anti_sandbagging_right",
    "anti sandbagging right": "anti_sandbagging_right",
    "anti-sandbagging rights": "anti_sandbagging_right",
    "anti sandbagging rights": "anti_sandbagging_right",
    # Working Capital Adjustments
    "working capital adjustment": "working_capital_adjustment",
    "working capital adjustments": "working_capital_adjustment",
    "working capital adj": "working_capital_adjustment",
    "working capital adjmt": "working_capital_adjustment",
    "working capital adjmts": "working_capital_adjustment",
    "working capital adjustment clause": "working_capital_adjustment_clause",
    "working capital adjustment clauses": "working_capital_adjustment_clause",
    "working capital adjustment provision": "working_capital_adjustment_clause",
    "working capital adjustment provisions": "working_capital_adjustment_clause",
    "working capital adjustment right": "working_capital_adjustment_right",
    "working capital adjustment rights": "working_capital_adjustment_right",
    "working capital": "working_capital",
    "working capital clause": "working_capital_clause",
    "working capital clauses": "working_capital_clause",
    "working capital provision": "working_capital_clause",
    "working capital provisions": "working_capital_clause",
    "working capital right": "working_capital_right",
    "working capital rights": "working_capital_right",
    "wc adjustment": "working_capital_adjustment",
    "wc adjustments": "working_capital_adjustment",
    "wc adj": "working_capital_adjustment",
    "wc adjmt": "working_capital_adjustment",
    "wc adjmts": "working_capital_adjustment",
    "wc adjustment clause": "working_capital_adjustment_clause",
    "wc adjustment clauses": "working_capital_adjustment_clause",
    "wc adjustment provision": "working_capital_adjustment_clause",
    "wc adjustment provisions": "working_capital_adjustment_clause",
    "wc adjustment right": "working_capital_adjustment_right",
    "wc adjustment rights": "working_capital_adjustment_right",
    "wc": "working_capital",
    "wc clause": "working_capital_clause",
    "wc clauses": "working_capital_clause",
    "wc provision": "working_capital_clause",
    "wc provisions": "working_capital_clause",
    "wc right": "working_capital_right",
    "wc rights": "working_capital_right",
    # Tender Offers and Williams Act
    "tender offer": "tender_offer",
    "tender offers": "tender_offer",
    "tender offer structure": "tender_offer",
    "tender offer process": "tender_offer",
    "tender offer rules": "tender_offer_rules",
    "tender offer regulations": "tender_offer_rules",
    "tender offer law": "tender_offer_rules",
    "tender offer laws": "tender_offer_rules",
    "tender offer statute": "tender_offer_rules",
    "tender offer statutes": "tender_offer_rules",
    "tender offer act": "tender_offer_rules",
    "tender offer acts": "tender_offer_rules",
    "tender offer regulation": "tender_offer_rules",
    "tender offer regulations": "tender_offer_rules",
    "tender offer filing": "tender_offer_filing",
    "tender offer filings": "tender_offer_filing",
    "tender offer notice": "tender_offer_notice",
    "tender offer notices": "tender_offer_notice",
    "tender offer statement": "tender_offer_statement",
    "tender offer statements": "tender_offer_statement",
    "tender offer schedule": "tender_offer_schedule",
    "tender offer schedules": "tender_offer_schedule",
    "tender offer document": "tender_offer_document",
    "tender offer documents": "tender_offer_document",
    "tender offer documentation": "tender_offer_document",
    "tender offer docs": "tender_offer_document",
    "tender offer disclosure": "tender_offer_disclosure",
    "tender offer disclosures": "tender_offer_disclosure",
    "williams act": "williams_act",
    "williams act tender offer": "williams_act",
    "williams act rules": "williams_act",
    "williams act regulations": "williams_act",
    "williams act law": "williams_act",
    "williams act laws": "williams_act",
    "williams act statute": "williams_act",
    "williams act statutes": "williams_act",
    "williams act regulation": "williams_act",
    "williams act regulations": "williams_act",
    "williams act filing": "williams_act",
    "williams act filings": "williams_act",
    "williams act notice": "williams_act",
    "williams act notices": "williams_act",
    "williams act statement": "williams_act",
    "williams act statements": "williams_act",
    "williams act schedule": "williams_act",
    "williams act schedules": "williams_act",
    "williams act document": "williams_act",
    "williams act documents": "williams_act",
    "williams act documentation": "williams_act",
    "williams act docs": "williams_act",
    "williams act disclosure": "williams_act",
    "williams act disclosures": "williams_act",
    # Indemnification Baskets and Caps
    "indemnification basket": "indemnification_basket",
    "indemnification baskets": "indemnification_basket",
    "indemnity basket": "indemnification_basket",
    "indemnity baskets": "indemnification_basket",
    "indemnification cap": "indemnification_cap",
    "indemnification caps": "indemnification_cap",
    "indemnity cap": "indemnification_cap",
    "indemnity caps": "indemnification_cap",
    "indemnification threshold": "indemnification_basket",
    "indemnification thresholds": "indemnification_basket",
    "indemnity threshold": "indemnification_basket",
    "indemnity thresholds": "indemnification_basket",
    "indemnification basket clause": "indemnification_basket_clause",
    "indemnification basket clauses": "indemnification_basket_clause",
    "indemnification basket provision": "indemnification_basket_clause",
    "indemnification basket provisions": "indemnification_basket_clause",
    "indemnification cap clause": "indemnification_cap_clause",
    "indemnification cap clauses": "indemnification_cap_clause",
    "indemnification cap provision": "indemnification_cap_clause",
    "indemnification cap provisions": "indemnification_cap_clause",
    "indemnity basket clause": "indemnification_basket_clause",
    "indemnity basket clauses": "indemnification_basket_clause",
    "indemnity basket provision": "indemnification_basket_clause",
    "indemnity basket provisions": "indemnification_basket_clause",
    "indemnity cap clause": "indemnification_cap_clause",
    "indemnity cap clauses": "indemnification_cap_clause",
    "indemnity cap provision": "indemnification_cap_clause",
    "indemnity cap provisions": "indemnification_cap_clause",
    # Financing Conditions and Committed Financing
    "financing condition": "financing_condition",
    "financing conditions": "financing_condition",
    "committed financing": "committed_financing",
    "committed finance": "committed_financing",
    "committed funding": "committed_financing",
    "financing commitment": "committed_financing",
    "financing commitments": "committed_financing",
    "financing commitment letter": "financing_commitment_letter",
    "financing commitment letters": "financing_commitment_letter",
    "committed financing letter": "financing_commitment_letter",
    "committed financing letters": "financing_commitment_letter",
    "committed finance letter": "financing_commitment_letter",
    "committed finance letters": "financing_commitment_letter",
    "committed funding letter": "financing_commitment_letter",
    "committed funding letters": "financing_commitment_letter",
    "financing letter": "financing_commitment_letter",
    "financing letters": "financing_commitment_letter",
    "finance condition": "financing_condition",
    "finance conditions": "financing_condition",
    "finance commitment": "committed_financing",
    "finance commitments": "committed_financing",
    "finance commitment letter": "financing_commitment_letter",
    "finance commitment letters": "financing_commitment_letter",
    "finance letter": "financing_commitment_letter",
    "finance letters": "financing_commitment_letter",
    "funding condition": "financing_condition",
    "funding conditions": "financing_condition",
    "funding commitment": "committed_financing",
    "funding commitments": "committed_financing",
    "funding commitment letter": "financing_commitment_letter",
    "funding commitment letters": "financing_commitment_letter",
    "funding letter": "financing_commitment_letter",
    "funding letters": "financing_commitment_letter",
    # Regulatory Approval Conditions and Efforts Standards
    "regulatory approval": "regulatory_approval",
    "regulatory approvals": "regulatory_approval",
    "regulatory approval condition": "regulatory_approval_condition",
    "regulatory approval conditions": "regulatory_approval_condition",
    "regulatory condition": "regulatory_approval_condition",
    "regulatory conditions": "regulatory_approval_condition",
    "regulatory clearance": "regulatory_clearance",
    "regulatory clearances": "regulatory_clearance",
    "regulatory filing": "regulatory_filing",
    "regulatory filings": "regulatory_filing",
    "regulatory notification": "regulatory_filing",
    "regulatory notifications": "regulatory_filing",
    "regulatory consent": "regulatory_approval",
    "regulatory consents": "regulatory_approval",
    "regulatory effort": "regulatory_effort",
    "regulatory efforts": "regulatory_effort",
    "regulatory efforts standard": "regulatory_effort_standard",
    "regulatory efforts standards": "regulatory_effort_standard",
    "efforts standard": "regulatory_effort_standard",
    "efforts standards": "regulatory_effort_standard",
    "best efforts": "best_efforts",
    "reasonable efforts": "reasonable_efforts",
    "commercially reasonable efforts": "commercially_reasonable_efforts",
    "best efforts standard": "best_efforts",
    "reasonable efforts standard": "reasonable_efforts",
    "commercially reasonable efforts standard": "commercially_reasonable_efforts",
    "best efforts clause": "best_efforts_clause",
    "reasonable efforts clause": "reasonable_efforts_clause",
    "commercially reasonable efforts clause": "commercially_reasonable_efforts_clause",
    "best efforts provision": "best_efforts_clause",
    "reasonable efforts provision": "reasonable_efforts_clause",
    "commercially reasonable efforts provision": "commercially_reasonable_efforts_clause",
    "best efforts provisions": "best_efforts_clause",
    "reasonable efforts provisions": "reasonable_efforts_clause",
    "commercially reasonable efforts provisions": "commercially_reasonable_efforts_clause",
    # Non-Compete and Non-Solicitation Covenants
    "non-compete": "non_compete",
    "non compete": "non_compete",
    "non-compete clause": "non_compete_clause",
    "non compete clause": "non_compete_clause",
    "non-compete clauses": "non_compete_clause",
    "non compete clauses": "non_compete_clause",
    "non-compete provision": "non_compete_clause",
    "non compete provision": "non_compete_clause",
    "non-compete provisions": "non_compete_clause",
    "non compete provisions": "non_compete_clause",
    "non-compete covenant": "non_compete_covenant",
    "non compete covenant": "non_compete_covenant",
    "non-compete covenants": "non_compete_covenant",
    "non compete covenants": "non_compete_covenant",
    "non-solicitation": "non_solicitation",
    "non solicitation": "non_solicitation",
    "non-solicitation clause": "non_solicitation_clause",
    "non solicitation clause": "non_solicitation_clause",
    "non-solicitation clauses": "non_solicitation_clause",
    "non solicitation clauses": "non_solicitation_clause",
    "non-solicitation provision": "non_solicitation_clause",
    "non solicitation provision": "non_solicitation_clause",
    "non-solicitation provisions": "non_solicitation_clause",
    "non solicitation provisions": "non_solicitation_clause",
    "non-solicitation covenant": "non_solicitation_covenant",
    "non solicitation covenant": "non_solicitation_covenant",
    "non-solicitation covenants": "non_solicitation_covenant",
    "non solicitation covenants": "non_solicitation_covenant",
    "restrictive covenant": "restrictive_covenant",
    "restrictive covenants": "restrictive_covenant",
    "restrictive covenant clause": "restrictive_covenant_clause",
    "restrictive covenant clauses": "restrictive_covenant_clause",
    "restrictive covenant provision": "restrictive_covenant_clause",
    "restrictive covenant provisions": "restrictive_covenant_clause",
    "restrictive covenant agreement": "restrictive_covenant_agreement",
    "restrictive covenant agreements": "restrictive_covenant_agreement",
    "non-compete agreement": "non_compete_agreement",
    "non compete agreement": "non_compete_agreement",
    "non-compete agreements": "non_compete_agreement",
    "non compete agreements": "non_compete_agreement",
    "non-solicitation agreement": "non_solicitation_agreement",
    "non solicitation agreement": "non_solicitation_agreement",
    "non-solicitation agreements": "non_solicitation_agreement",
    "non solicitation agreements": "non_solicitation_agreement",
    # Misspellings and common variants
    "assset purchase": "asset_purchase",
    "assset sale": "asset_purchase",
    "assset transfer": "asset_purchase",
    "stcok purchase": "stock_purchase",
    "stcok acquisition": "stock_purchase",
    "stcok deal": "stock_purchase",
    "stcok sale": "stock_purchase",
    "shrae purchase": "stock_purchase",
    "shrae acquisition": "stock_purchase",
    "shrae deal": "stock_purchase",
    "shrae sale": "stock_purchase",
    "equity purchse": "stock_purchase",
    "equity acqusition": "stock_purchase",
    "equity deel": "stock_purchase",
    "equity slae": "stock_purchase",
    "purhcase of assets": "asset_purchase",
    "purhcase of stock": "stock_purchase",
    "buying asssets": "asset_purchase",
    "buying stcok": "stock_purchase",
    "buying shraes": "stock_purchase",
    "buying equtiy": "stock_purchase",
    "deal structre": "deal_structure",
    "transaction structre": "deal_structure",
    "purchase structre": "deal_structure",
    "acquisition structre": "deal_structure",
    "merger structre": "deal_structure",
    "stock tranfer": "stock_purchase",
    "asset tranfer": "asset_purchase",
    "stock tranfer structre": "stock_purchase",
    "asset tranfer structre": "asset_purchase",
    "stock purchse agreement": "stock_purchase_agreement",
    "asset purchse agreement": "asset_purchase_agreement",
    "stock purchse agmt": "stock_purchase_agreement",
    "asset purchse agmt": "asset_purchase_agreement",
    "stock purchse contract": "stock_purchase_agreement",
    "asset purchse contract": "asset_purchase_agreement",
    "stock purchse doc": "stock_purchase_agreement",
    "asset purchse doc": "asset_purchase_agreement",
    "stock purchse documentation": "stock_purchase_agreement",
    "asset purchse documentation": "asset_purchase_agreement",
    "stock purchse document": "stock_purchase_agreement",
    "asset purchse document": "asset_purchase_agreement",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.lower().strip()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)