from dataclasses import dataclass
from typing import List, Optional
from enum import Enum
from pathlib import Path

@dataclass
class DoctrineBlock:
    topic: str
    keywords: List[str]
    conclusion_template: str
    reasoning_framework: str
    key_factors: List[str]
    primary_authority: List[str]
    burden_holder: str
    adversary_position: str
    counter_arguments: List[str]
    resolution_strategy: str
    entity_scope: str
    confidence: float
    confidence_zone: str
    controlling_precedent: str

DOCTRINE_CACHE: List[DoctrineBlock] = [
    DoctrineBlock(
        topic="Alpha Decay Fundamentals",
        keywords=["alpha decay", "nuclear stability", "helium nucleus", "radioactivity", "parent-daughter relationship"],
        conclusion_template="Alpha decay occurs when a nucleus emits an alpha particle, resulting in a decrease of atomic number by 2 and mass number by 4.",
        reasoning_framework="""Alpha decay is a quantum tunneling process where the nucleus emits a helium-4 nucleus (alpha particle). The probability of decay depends on the nuclear binding energy, Coulomb barrier, and quantum mechanical tunneling. The process is favored in heavy nuclei where the binding energy per nucleon is lower and the Coulomb repulsion is significant. The decay rate is governed by the Geiger-Nuttall law, which relates the decay constant to the energy of the emitted alpha particle. The daughter nucleus is more stable due to the reduction in repulsive forces. Selection rules dictate allowed transitions based on angular momentum and parity conservation. Experimental detection relies on measuring the energy and range of alpha particles, which are highly ionizing but have limited penetration. Alpha decay contributes to the natural radioactivity observed in uranium, thorium, and actinium series.""",
        key_factors=["nuclear binding energy", "Coulomb barrier", "quantum tunneling", "parent nucleus mass", "daughter nucleus stability"],
        primary_authority=["IAEA", "Nuclear Physics textbooks", "Geiger-Nuttall law"],
        burden_holder="proponent of alpha decay mechanism",
        adversary_position="Alpha decay is not energetically favorable in all nuclei; alternative decay modes may dominate.",
        counter_arguments=["Beta decay may compete in lighter nuclei.", "Spontaneous fission may dominate in superheavy elements."],
        resolution_strategy="Compare Q-values and decay probabilities for competing modes; reference experimental decay chains.",
        entity_scope="Heavy nuclei (Z > 82)",
        confidence=0.98,
        confidence_zone="High",
        controlling_precedent="Geiger-Nuttall empirical relation"
    ),
    DoctrineBlock(
        topic="Beta Decay Modes and Neutrino Physics",
        keywords=["beta decay", "neutrino", "electron emission", "positron emission", "weak interaction", "Fermi theory"],
        conclusion_template="Beta decay transforms a neutron to a proton (or vice versa) via weak interaction, emitting an electron/positron and a neutrino/antineutrino.",
        reasoning_framework="""Beta decay is governed by the weak nuclear force, allowing transformation between neutrons and protons. There are three modes: beta-minus (neutron to proton, electron and antineutrino emission), beta-plus (proton to neutron, positron and neutrino emission), and electron capture (proton absorbs electron, emits neutrino). The process conserves lepton number, charge, and energy. The continuous energy spectrum of beta particles is explained by the emission of neutrinos, as postulated by Pauli and confirmed by Reines and Cowan. Fermi's theory describes the transition probability based on matrix elements and phase space factors. Selection rules depend on spin and parity changes. Beta decay is crucial in nuclear transmutation, radioactive dating, and neutrino physics. Experimental detection involves measuring beta spectra and neutrino interactions.""",
        key_factors=["weak interaction", "lepton conservation", "energy spectrum", "selection rules", "neutrino existence"],
        primary_authority=["Fermi theory", "Pauli neutrino hypothesis", "IAEA", "Nobel Prize experiments"],
        burden_holder="proponent of beta decay and neutrino emission",
        adversary_position="Neutrinos are undetectable; beta spectrum can be explained without neutrinos.",
        counter_arguments=["Neutrino detection experiments confirm their existence.", "Energy conservation requires neutrinos."],
        resolution_strategy="Reference Nobel-winning neutrino detection; analyze beta spectrum endpoints.",
        entity_scope="All nuclei with unstable neutron/proton ratios",
        confidence=0.97,
        confidence_zone="High",
        controlling_precedent="Fermi's beta decay theory"
    ),
    DoctrineBlock(
        topic="Gamma Emission and Internal Conversion",
        keywords=["gamma emission", "internal conversion", "nuclear de-excitation", "electromagnetic transition", "isomeric states"],
        conclusion_template="Gamma emission and internal conversion are competing de-excitation mechanisms for excited nuclei, governed by transition probabilities and selection rules.",
        reasoning_framework="""Excited nuclei return to ground state via electromagnetic transitions. Gamma emission involves photon release, while internal conversion transfers energy to an orbital electron, ejecting it from the atom. The probability of each process depends on nuclear structure, transition energy, and multipolarity (E1, M1, E2, etc.). Selection rules dictate allowed transitions based on angular momentum and parity. Internal conversion is favored in low-energy transitions and heavy nuclei due to higher electron density. Isomeric states (metastable) may persist before de-excitation. Experimental detection distinguishes gamma rays (penetrating, non-ionizing) from conversion electrons (ionizing, discrete energies). Gamma spectroscopy is a key tool in nuclear structure analysis.""",
        key_factors=["transition energy", "multipolarity", "nuclear structure", "electron density", "selection rules"],
        primary_authority=["IAEA", "Nuclear Spectroscopy textbooks", "Mössbauer effect studies"],
        burden_holder="proponent of electromagnetic de-excitation",
        adversary_position="Internal conversion dominates over gamma emission in all cases.",
        counter_arguments=["Gamma emission is favored at higher energies.", "Internal conversion coefficients vary with atomic number."],
        resolution_strategy="Calculate transition probabilities; reference experimental conversion coefficients.",
        entity_scope="Excited nuclei",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="Multipolarity selection rules"
    ),
    DoctrineBlock(
        topic="Radioactive Decay Kinetics and Secular Equilibrium",
        keywords=["radioactive decay", "kinetics", "secular equilibrium", "half-life", "parent-daughter relationship"],
        conclusion_template="Radioactive decay follows first-order kinetics; secular equilibrium occurs when parent half-life greatly exceeds daughter half-life.",
        reasoning_framework="""Radioactive decay is a stochastic process described by first-order kinetics: N(t) = N0 * exp(-λt), where λ is the decay constant. The half-life is related as t1/2 = ln(2)/λ. In decay chains, secular equilibrium arises when the parent nuclide's half-life is much longer than the daughter's, causing the daughter's activity to match the parent's. This is critical in radiometric dating and environmental monitoring. Transient equilibrium occurs when the half-lives are comparable. Mathematical modeling involves Bateman equations for multi-step decay chains. Experimental verification uses activity measurements over time. Deviations from equilibrium indicate external influences or chemical separation.""",
        key_factors=["decay constant", "half-life", "parent-daughter ratio", "Bateman equations", "activity measurement"],
        primary_authority=["IAEA", "Bateman equations", "Radiochemistry textbooks"],
        burden_holder="proponent of equilibrium conditions",
        adversary_position="Secular equilibrium is not achievable due to chemical separation or external factors.",
        counter_arguments=["Physical separation disrupts equilibrium.", "External irradiation alters decay rates."],
        resolution_strategy="Monitor activity ratios; apply Bateman equations; account for chemical separation.",
        entity_scope="Decay chains in natural and artificial systems",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="Bateman equations for decay chains"
    ),
    DoctrineBlock(
        topic="Nuclear Fission Mechanism and Energetics",
        keywords=["nuclear fission", "chain reaction", "energy release", "critical mass", "neutron emission"],
        conclusion_template="Nuclear fission splits heavy nuclei into fragments, releasing energy and neutrons; chain reactions depend on critical mass and neutron multiplication.",
        reasoning_framework="""Fission occurs when a heavy nucleus (e.g., U-235, Pu-239) absorbs a neutron and becomes unstable, splitting into two fragments and emitting neutrons. The process releases energy due to mass defect, as described by Einstein's E=mc^2. The number of emitted neutrons determines the possibility of a chain reaction. Critical mass is the minimum amount of fissile material required for a self-sustaining reaction. The fission yield distribution depends on nuclear structure and excitation energy. Control of chain reactions is achieved via moderators, control rods, and geometry. Fission is the basis of nuclear reactors and weapons. Experimental studies measure neutron multiplicity, fragment energies, and delayed neutron emission. Safety considerations include prompt criticality and reactor shutdown mechanisms.""",
        key_factors=["fissile material", "neutron emission", "critical mass", "energy release", "chain reaction control"],
        primary_authority=["IAEA", "Nuclear Reactor Physics textbooks", "Einstein's mass-energy equivalence"],
        burden_holder="proponent of fission mechanism",
        adversary_position="Fission is not energetically favorable; chain reactions are uncontrollable.",
        counter_arguments=["Fission yields are experimentally measured.", "Chain reactions are controlled in reactors."],
        resolution_strategy="Reference reactor operation data; calculate energy release and neutron economy.",
        entity_scope="Heavy nuclei (U, Pu, Th isotopes)",
        confidence=0.99,
        confidence_zone="Very High",
        controlling_precedent="Einstein's E=mc^2"
    ),
    DoctrineBlock(
        topic="Nuclear Fusion Reactions and Stellar Nucleosynthesis",
        keywords=["nuclear fusion", "stellar nucleosynthesis", "energy production", "hydrogen burning", "CNO cycle"],
        conclusion_template="Nuclear fusion combines light nuclei, releasing energy; stellar nucleosynthesis forms elements in stars via fusion cycles.",
        reasoning_framework="""Fusion occurs when light nuclei (e.g., hydrogen isotopes) overcome Coulomb repulsion and merge, forming heavier nuclei and releasing energy. The process is exothermic for elements lighter than iron, due to increasing binding energy per nucleon. In stars, fusion proceeds via the proton-proton chain and CNO cycle, synthesizing helium and heavier elements. Stellar nucleosynthesis extends to supernovae, forming elements beyond iron via neutron capture (s- and r-processes). Fusion requires high temperature and pressure, achieved in stellar cores or experimental devices (tokamaks, inertial confinement). Energy yield is calculated from mass defect. Experimental fusion is challenging due to confinement and plasma instabilities. Fusion is the basis of stellar energy and future energy technologies.""",
        key_factors=["Coulomb barrier", "binding energy", "temperature", "pressure", "fusion cycles"],
        primary_authority=["IAEA", "Astrophysics textbooks", "Bethe's fusion theory"],
        burden_holder="proponent of fusion mechanism",
        adversary_position="Fusion is not achievable under terrestrial conditions; energy input exceeds output.",
        counter_arguments=["Stellar fusion is observed.", "Experimental devices achieve fusion in short bursts."],
        resolution_strategy="Reference astrophysical observations; analyze experimental fusion data.",
        entity_scope="Light nuclei (H, He, C, N, O)",
        confidence=0.97,
        confidence_zone="High",
        controlling_precedent="Bethe's stellar nucleosynthesis theory"
    ),
    DoctrineBlock(
        topic="Radiation Detection - Gas-Filled Detectors",
        keywords=["radiation detection", "gas-filled detectors", "ionization chamber", "proportional counter", "Geiger-Müller tube"],
        conclusion_template="Gas-filled detectors measure radiation via ionization of gas; operation modes include ionization chamber, proportional counter, and Geiger-Müller tube.",
        reasoning_framework="""Gas-filled detectors operate by ionizing gas atoms when radiation passes through. The resulting ion pairs are collected by electrodes, generating a measurable current. Ionization chambers measure total ionization, proportional counters amplify the signal for energy discrimination, and Geiger-Müller tubes operate in avalanche mode for count detection. Detector response depends on gas type, pressure, electrode geometry, and applied voltage. Calibration ensures accurate measurements. Limitations include dead time, background noise, and limited energy resolution. Applications include environmental monitoring, personnel dosimetry, and nuclear industry safety. Maintenance involves gas purity and detector stability checks.""",
        key_factors=["ionization", "gas type", "voltage", "detector geometry", "calibration"],
        primary_authority=["IAEA", "Radiation Detection textbooks", "Geiger-Müller tube patents"],
        burden_holder="proponent of gas-filled detector efficacy",
        adversary_position="Gas-filled detectors lack energy resolution and are susceptible to noise.",
        counter_arguments=["Proportional counters provide energy discrimination.", "Proper shielding reduces noise."],
        resolution_strategy="Select detector type based on application; calibrate and shield appropriately.",
        entity_scope="Radiation monitoring and detection",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="Geiger-Müller tube operational principles"
    ),
    DoctrineBlock(
        topic="Scintillation Detectors and Photomultipliers",
        keywords=["scintillation detector", "photomultiplier tube", "light emission", "energy resolution", "gamma spectroscopy"],
        conclusion_template="Scintillation detectors convert radiation to light, amplified by photomultiplier tubes for energy and count measurements.",
        reasoning_framework="""Scintillation detectors use materials (e.g., NaI(Tl), CsI, plastic) that emit light when excited by ionizing radiation. The emitted photons are detected and amplified by photomultiplier tubes (PMTs), converting light to electrical signals. The system provides high sensitivity and moderate energy resolution, suitable for gamma spectroscopy and environmental monitoring. Detector performance depends on scintillator material, PMT gain, and optical coupling. Calibration ensures accurate energy measurement. Limitations include non-linear response, afterglow, and temperature dependence. Applications include medical imaging, nuclear security, and research. Maintenance involves PMT stability and scintillator integrity checks.""",
        key_factors=["scintillator material", "light yield", "PMT gain", "energy resolution", "calibration"],
        primary_authority=["IAEA", "Radiation Detection textbooks", "Photomultiplier tube patents"],
        burden_holder="proponent of scintillation detector efficacy",
        adversary_position="Scintillation detectors suffer from afterglow and limited energy resolution.",
        counter_arguments=["Modern materials reduce afterglow.", "Calibration improves energy discrimination."],
        resolution_strategy="Select appropriate scintillator; calibrate and maintain PMT performance.",
        entity_scope="Radiation detection and spectroscopy",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="Photomultiplier tube operational principles"
    ),
    DoctrineBlock(
        topic="Semiconductor Detectors - HPGe and Si(Li)",
        keywords=["semiconductor detector", "HPGe", "Si(Li)", "energy resolution", "gamma spectroscopy"],
        conclusion_template="Semiconductor detectors (HPGe, Si(Li)) provide high energy resolution for gamma and X-ray spectroscopy, requiring cooling and careful calibration.",
        reasoning_framework="""Semiconductor detectors use high-purity germanium (HPGe) or silicon-lithium (Si(Li)) crystals to detect ionizing radiation. Incident photons create electron-hole pairs, collected by electrodes to produce electrical signals. HPGe detectors offer superior energy resolution for gamma spectroscopy, while Si(Li) is used for X-ray detection. Cooling (liquid nitrogen or electric) reduces noise and leakage current. Calibration ensures accurate energy assignment. Limitations include cost, fragility, and need for cooling. Applications include nuclear research, environmental monitoring, and forensic analysis. Maintenance involves crystal integrity and cooling system checks.""",
        key_factors=["crystal purity", "cooling", "energy resolution", "calibration", "detector geometry"],
        primary_authority=["IAEA", "Radiation Detection textbooks", "HPGe patents"],
        burden_holder="proponent of semiconductor detector efficacy",
        adversary_position="Semiconductor detectors are expensive and require complex cooling.",
        counter_arguments=["Superior energy resolution justifies cost.", "Electric cooling is increasingly available."],
        resolution_strategy="Evaluate application requirements; balance cost and performance.",
        entity_scope="Gamma and X-ray spectroscopy",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="HPGe detector operational principles"
    ),
    DoctrineBlock(
        topic="Radiation Dosimetry - Absorbed Dose and Equivalent Dose",
        keywords=["radiation dosimetry", "absorbed dose", "equivalent dose", "sievert", "gray", "biological effect"],
        conclusion_template="Radiation dosimetry quantifies absorbed and equivalent dose, accounting for biological effectiveness via weighting factors.",
        reasoning_framework="""Dosimetry measures the amount of radiation absorbed by matter, typically human tissue. Absorbed dose is expressed in gray (Gy), representing energy deposited per unit mass. Equivalent dose (sievert, Sv) accounts for biological effectiveness using radiation weighting factors (e.g., alpha particles have higher weighting than gamma rays). Dose limits are set by regulatory authorities to protect workers and the public. Dosimetry methods include thermoluminescent dosimeters (TLDs), film badges, and electronic dosimeters. Biological effects depend on dose, dose rate, and radiation type. Monitoring ensures compliance with safety standards. Limitations include measurement uncertainty and individual variability.""",
        key_factors=["absorbed dose", "equivalent dose", "weighting factors", "dosimeter type", "regulatory limits"],
        primary_authority=["IAEA", "ICRP", "Radiation Protection textbooks"],
        burden_holder="proponent of dosimetry standards",
        adversary_position="Dosimetry does not accurately reflect biological risk.",
        counter_arguments=["Weighting factors are based on epidemiological data.", "Dosimetry is standardized internationally."],
        resolution_strategy="Apply ICRP weighting factors; reference regulatory standards.",
        entity_scope="Radiation workers, public, medical patients",
        confidence=0.97,
        confidence_zone="High",
        controlling_precedent="ICRP dose weighting recommendations"
    ),
    DoctrineBlock(
        topic="ALARA Principle and Radiation Protection Standards",
        keywords=["ALARA", "radiation protection", "dose limits", "optimization", "regulatory compliance"],
        conclusion_template="The ALARA principle mandates keeping radiation exposure As Low As Reasonably Achievable, balancing safety, practicality, and cost.",
        reasoning_framework="""ALARA is a cornerstone of radiation protection, requiring that exposures be minimized within practical and economic constraints. Regulatory authorities set dose limits for workers and the public, but ALARA goes further, requiring optimization of protection measures. Implementation involves engineering controls, administrative procedures, and personal protective equipment. Risk assessment considers potential exposures, accident scenarios, and cost-benefit analysis. Compliance is audited via monitoring and record-keeping. Limitations include subjective interpretation of 'reasonable' and balancing operational needs. ALARA is enforced in medical, industrial, and research settings. Continuous improvement and training are essential.""",
        key_factors=["dose limits", "optimization", "cost-benefit", "engineering controls", "regulatory compliance"],
        primary_authority=["IAEA", "ICRP", "Radiation Protection regulations"],
        burden_holder="proponent of ALARA implementation",
        adversary_position="ALARA is impractical and costly; dose limits suffice.",
        counter_arguments=["ALARA reduces risk beyond regulatory minimums.", "Cost-benefit analysis guides implementation."],
        resolution_strategy="Document optimization measures; reference regulatory audits.",
        entity_scope="Radiation facilities, medical, industrial, research",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="ICRP ALARA guidelines"
    ),
    DoctrineBlock(
        topic="Shielding Calculations - Attenuation and Buildup",
        keywords=["radiation shielding", "attenuation", "buildup factor", "material selection", "dose reduction"],
        conclusion_template="Shielding calculations use attenuation and buildup factors to design barriers that reduce radiation dose to acceptable levels.",
        reasoning_framework="""Radiation shielding relies on selecting materials (e.g., lead, concrete, water) to attenuate incident radiation. The attenuation follows exponential decay: I = I0 * exp(-μx), where μ is the linear attenuation coefficient and x is thickness. Buildup factors account for scattered radiation, increasing dose beyond simple attenuation. Material selection depends on radiation type, energy, and operational constraints. Calculations involve reference tables, Monte Carlo simulations, and regulatory guidelines. Safety margins ensure compliance with dose limits. Limitations include space, weight, and cost. Shielding is critical in medical, industrial, and nuclear facilities.""",
        key_factors=["attenuation coefficient", "buildup factor", "material density", "radiation energy", "dose limits"],
        primary_authority=["IAEA", "NCRP", "Radiation Protection textbooks"],
        burden_holder="proponent of shielding adequacy",
        adversary_position="Shielding calculations underestimate scattered radiation.",
        counter_arguments=["Buildup factors are empirically determined.", "Monte Carlo simulations improve accuracy."],
        resolution_strategy="Apply buildup factors; validate with experimental measurements.",
        entity_scope="Radiation facilities, medical, industrial",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="NCRP shielding guidelines"
    ),
    DoctrineBlock(
        topic="Nuclear Waste Classification and Management",
        keywords=["nuclear waste", "classification", "management", "disposal", "regulatory standards"],
        conclusion_template="Nuclear waste is classified by activity and half-life; management involves containment, treatment, and disposal per regulatory standards.",
        reasoning_framework="""Nuclear waste is categorized as low, intermediate, or high-level based on radioactivity and half-life. Management strategies include containment, treatment (e.g., vitrification, compaction), and disposal (e.g., near-surface, deep geological). Regulatory authorities set standards for waste handling, transport, and disposal. Safety considerations include environmental protection, long-term stability, and public acceptance. Monitoring ensures compliance and early detection of leaks. Limitations include political, economic, and technical challenges. International cooperation addresses cross-border issues. Research focuses on advanced treatment and transmutation technologies.""",
        key_factors=["waste activity", "half-life", "containment", "disposal method", "regulatory compliance"],
        primary_authority=["IAEA", "NRC", "Nuclear Waste Management textbooks"],
        burden_holder="proponent of waste management strategy",
        adversary_position="Current waste management is inadequate; risks persist for millennia.",
        counter_arguments=["Deep geological disposal is proven.", "Containment technologies are improving."],
        resolution_strategy="Reference regulatory standards; monitor and improve containment.",
        entity_scope="Nuclear facilities, medical, industrial waste generators",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA waste classification standards"
    ),
    DoctrineBlock(
        topic="Neutron Activation Analysis (NAA)",
        keywords=["neutron activation analysis", "elemental analysis", "radioisotope production", "non-destructive testing"],
        conclusion_template="NAA uses neutron irradiation to activate sample nuclei, enabling sensitive, non-destructive elemental analysis via gamma spectroscopy.",
        reasoning_framework="""Neutron activation analysis involves irradiating samples with neutrons, causing nuclei to capture neutrons and become radioactive. The resulting radioisotopes emit characteristic gamma rays, detected via spectroscopy. NAA is highly sensitive, non-destructive, and applicable to a wide range of elements. Sample preparation is minimal, and analysis is quantitative. Limitations include access to neutron sources, matrix effects, and interference from multiple isotopes. Applications include forensic science, archaeology, environmental monitoring, and industrial quality control. Calibration and standards ensure accuracy. Safety protocols address radiation exposure during irradiation and measurement.""",
        key_factors=["neutron source", "gamma spectroscopy", "elemental sensitivity", "matrix effects", "calibration"],
        primary_authority=["IAEA", "NAA textbooks", "Nuclear Analytical Methods journals"],
        burden_holder="proponent of NAA efficacy",
        adversary_position="NAA is limited by access to neutron sources and interference effects.",
        counter_arguments=["Research reactors and neutron generators are increasingly available.", "Matrix corrections improve accuracy."],
        resolution_strategy="Apply matrix correction; reference calibration standards.",
        entity_scope="Analytical laboratories, forensic, industrial, environmental",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA NAA guidelines"
    ),
    DoctrineBlock(
        topic="PUREX Process and Spent Fuel Reprocessing",
        keywords=["PUREX process", "spent fuel", "reprocessing", "plutonium separation", "solvent extraction"],
        conclusion_template="The PUREX process separates uranium and plutonium from spent nuclear fuel via solvent extraction, enabling recycling and waste reduction.",
        reasoning_framework="""PUREX (Plutonium Uranium Redox EXtraction) is the standard method for reprocessing spent nuclear fuel. It uses nitric acid dissolution and organic solvents (tributyl phosphate) to selectively extract uranium and plutonium, leaving fission products in the aqueous phase. The process enables recycling of fuel, reduction of waste volume, and recovery of valuable isotopes. Safety considerations include criticality control, radiological protection, and waste management. Limitations include proliferation risk, process complexity, and secondary waste generation. Regulatory oversight ensures compliance with safety and non-proliferation standards. Research focuses on advanced solvent systems and proliferation-resistant technologies.""",
        key_factors=["solvent extraction", "criticality safety", "waste management", "regulatory compliance", "proliferation risk"],
        primary_authority=["IAEA", "Nuclear Fuel Cycle textbooks", "PUREX patents"],
        burden_holder="proponent of PUREX process efficacy",
        adversary_position="PUREX is complex, costly, and poses proliferation risks.",
        counter_arguments=["Advanced safeguards reduce proliferation risk.", "Recycling reduces waste volume."],
        resolution_strategy="Implement safeguards; optimize process for safety and efficiency.",
        entity_scope="Nuclear fuel cycle facilities",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA PUREX process guidelines"
    ),
    DoctrineBlock(
        topic="NORM in Oil and Gas Operations",
        keywords=["NORM", "naturally occurring radioactive material", "oil and gas", "regulatory compliance", "waste management"],
        conclusion_template="NORM in oil and gas operations arises from radium, thorium, and uranium in geological formations; management requires regulatory compliance and safe disposal.",
        reasoning_framework="""NORM refers to naturally occurring radioactive materials present in oil and gas reservoirs, often concentrated during extraction and processing. Radium isotopes accumulate in scale and sludge, posing radiological risks to workers and the environment. Management involves identification, monitoring, safe handling, and disposal per regulatory standards. Dose assessment and protective measures are implemented. Limitations include variability in NORM concentration and public perception. Regulatory authorities set limits and guidelines for NORM management. Research focuses on remediation and waste minimization technologies.""",
        key_factors=["NORM concentration", "radium isotopes", "dose assessment", "regulatory limits", "waste disposal"],
        primary_authority=["IAEA", "NORM Management guidelines", "Oil and Gas industry standards"],
        burden_holder="proponent of NORM management strategy",
        adversary_position="NORM risks are underestimated; current management is insufficient.",
        counter_arguments=["Regulatory monitoring ensures safety.", "Remediation technologies are improving."],
        resolution_strategy="Monitor NORM levels; apply remediation and safe disposal.",
        entity_scope="Oil and gas extraction and processing facilities",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IAEA NORM management guidelines"
    ),
    DoctrineBlock(
        topic="Radiation Effects on Materials - Displacement Damage",
        keywords=["radiation effects", "materials", "displacement damage", "defects", "semiconductors"],
        conclusion_template="Radiation induces displacement damage in materials, creating defects that degrade mechanical and electronic properties.",
        reasoning_framework="""Displacement damage occurs when energetic particles (neutrons, ions) transfer sufficient energy to atoms in a material, displacing them from lattice sites and creating defects. The extent of damage depends on particle energy, material properties, and exposure duration. In semiconductors, displacement defects degrade electronic performance, affecting detectors and devices. In structural materials, damage reduces mechanical strength and ductility. Experimental studies use irradiation facilities and post-irradiation analysis (e.g., TEM, XRD). Mitigation involves material selection, annealing, and protective coatings. Limitations include cumulative effects and irreversibility in some cases.""",
        key_factors=["particle energy", "material properties", "defect density", "exposure duration", "mitigation strategies"],
        primary_authority=["IAEA", "Materials Science textbooks", "Radiation Effects journals"],
        burden_holder="proponent of displacement damage mechanism",
        adversary_position="Displacement damage is negligible compared to ionization effects.",
        counter_arguments=["Experimental data shows significant performance degradation.", "Ionization and displacement effects are distinct."],
        resolution_strategy="Reference experimental studies; differentiate damage mechanisms.",
        entity_scope="Semiconductors, structural materials in radiation environments",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA radiation effects guidelines"
    ),
    DoctrineBlock(
        topic="Monte Carlo Radiation Transport - MCNP Methods",
        keywords=["Monte Carlo", "radiation transport", "MCNP", "simulation", "dose calculation"],
        conclusion_template="Monte Carlo methods (e.g., MCNP) simulate radiation transport and interactions, enabling accurate dose and shielding calculations.",
        reasoning_framework="""Monte Carlo methods use random sampling to simulate the transport and interaction of radiation in matter. MCNP (Monte Carlo N-Particle) is a widely used code for modeling neutron, photon, and electron transport. Simulations account for geometry, material composition, source characteristics, and interaction cross-sections. Results provide dose distributions, shielding effectiveness, and detector response. Validation involves comparison with experimental data. Limitations include computational time, input complexity, and statistical uncertainty. Applications include reactor design, medical physics, and environmental assessment. Continuous development improves accuracy and usability.""",
        key_factors=["random sampling", "cross-sections", "geometry modeling", "validation", "statistical uncertainty"],
        primary_authority=["IAEA", "MCNP documentation", "Radiation Transport textbooks"],
        burden_holder="proponent of Monte Carlo simulation accuracy",
        adversary_position="Monte Carlo methods are computationally intensive and prone to input errors.",
        counter_arguments=["Parallel computing reduces time.", "Validation ensures reliability."],
        resolution_strategy="Validate simulations with experimental data; optimize input and computational resources.",
        entity_scope="Radiation transport modeling in nuclear, medical, environmental fields",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="MCNP code documentation"
    ),
    # Additional DoctrineBlocks for comprehensive coverage (total 40+)
    DoctrineBlock(
        topic="Decay Chain Analysis and Radioisotope Identification",
        keywords=["decay chain", "radioisotope", "identification", "gamma spectroscopy", "parent-daughter relationship"],
        conclusion_template="Decay chain analysis enables identification of radioisotopes via characteristic decay signatures and gamma emissions.",
        reasoning_framework="""Radioisotopes often decay through complex chains, producing multiple daughter products. Analysis involves tracking decay modes, half-lives, and gamma emissions. Gamma spectroscopy identifies isotopes by their unique energy peaks. Mathematical modeling uses Bateman equations to predict activity over time. Applications include environmental monitoring, nuclear forensics, and medical diagnostics. Limitations include overlapping peaks and short-lived intermediates. Calibration and reference standards improve accuracy. Safety protocols address handling of multiple radioactive species.""",
        key_factors=["decay mode", "half-life", "gamma emission", "Bateman equations", "calibration"],
        primary_authority=["IAEA", "Radiochemistry textbooks", "Gamma Spectroscopy journals"],
        burden_holder="proponent of decay chain analysis",
        adversary_position="Complex decay chains hinder accurate identification.",
        counter_arguments=["Advanced spectroscopy resolves overlapping peaks.", "Mathematical modeling predicts activity accurately."],
        resolution_strategy="Apply Bateman equations; use high-resolution spectroscopy.",
        entity_scope="Environmental, forensic, medical, nuclear facilities",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA decay chain analysis guidelines"
    ),
    DoctrineBlock(
        topic="Radiation-Induced Chemical Changes",
        keywords=["radiation chemistry", "chemical changes", "radiolysis", "water", "organic compounds"],
        conclusion_template="Radiation induces chemical changes (radiolysis) in materials, producing reactive species and altering properties.",
        reasoning_framework="""Radiation interacts with matter, breaking chemical bonds and generating reactive species (e.g., radicals, ions). Radiolysis of water produces hydrogen, oxygen, and hydroxyl radicals, affecting reactor coolant chemistry. Organic compounds undergo fragmentation, cross-linking, or polymerization. Effects depend on radiation type, dose, and material composition. Applications include sterilization, polymer modification, and environmental remediation. Limitations include unwanted degradation and secondary reactions. Experimental studies use spectroscopy and chromatography to analyze products. Mitigation involves additives and process optimization.""",
        key_factors=["radiation type", "dose", "material composition", "reactive species", "mitigation"],
        primary_authority=["IAEA", "Radiation Chemistry textbooks", "Radiolysis journals"],
        burden_holder="proponent of radiation-induced chemical change",
        adversary_position="Chemical changes are negligible at low doses.",
        counter_arguments=["Low-dose effects accumulate over time.", "Sensitive detection reveals subtle changes."],
        resolution_strategy="Monitor chemical changes; optimize process conditions.",
        entity_scope="Nuclear facilities, medical, industrial applications",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IAEA radiation chemistry guidelines"
    ),
    DoctrineBlock(
        topic="Nuclear Criticality Safety",
        keywords=["criticality safety", "neutron multiplication", "control rods", "moderator", "geometry"],
        conclusion_template="Criticality safety ensures subcritical conditions in nuclear systems via control of neutron multiplication, geometry, and material composition.",
        reasoning_framework="""Criticality safety prevents accidental chain reactions in nuclear facilities. Control involves limiting fissile material mass, optimizing geometry, using neutron absorbers (control rods), and moderating neutron energy. Calculations use neutron multiplication factors (k-effective) and Monte Carlo simulations. Regulatory authorities set safety margins and operational procedures. Limitations include human error, unexpected material accumulation, and process changes. Training and audits ensure compliance. Incident response plans address potential criticality events. Continuous improvement involves process optimization and technology upgrades.""",
        key_factors=["fissile material mass", "geometry", "neutron absorbers", "moderator", "regulatory compliance"],
        primary_authority=["IAEA", "Criticality Safety textbooks", "NRC guidelines"],
        burden_holder="proponent of criticality safety measures",
        adversary_position="Criticality safety margins are insufficient; accidents may occur.",
        counter_arguments=["Safety margins are conservative.", "Incident response plans mitigate risk."],
        resolution_strategy="Apply conservative margins; conduct regular audits and training.",
        entity_scope="Nuclear fuel cycle, reactors, waste management",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="IAEA criticality safety standards"
    ),
    DoctrineBlock(
        topic="Radiation Protection in Medical Imaging",
        keywords=["medical imaging", "radiation protection", "dose optimization", "patient safety", "ALARA"],
        conclusion_template="Radiation protection in medical imaging balances diagnostic quality and patient safety via dose optimization and ALARA implementation.",
        reasoning_framework="""Medical imaging uses ionizing radiation (X-rays, CT, nuclear medicine) for diagnosis. Protection involves minimizing patient dose while maintaining image quality. Techniques include optimized protocols, shielding, and use of alternative modalities (ultrasound, MRI). Regulatory authorities set dose limits and require justification for procedures. ALARA principle guides optimization. Limitations include variability in patient sensitivity and procedure complexity. Training and quality assurance ensure compliance. Continuous improvement involves technology upgrades and protocol refinement.""",
        key_factors=["dose optimization", "image quality", "ALARA", "regulatory limits", "quality assurance"],
        primary_authority=["IAEA", "ICRP", "Medical Imaging guidelines"],
        burden_holder="proponent of medical radiation protection",
        adversary_position="Dose optimization compromises diagnostic quality.",
        counter_arguments=["Protocols are evidence-based.", "Alternative modalities reduce exposure."],
        resolution_strategy="Balance diagnostic needs and safety; apply ALARA.",
        entity_scope="Medical imaging facilities, hospitals",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="ICRP medical imaging guidelines"
    ),
    DoctrineBlock(
        topic="Radon Monitoring and Mitigation",
        keywords=["radon", "monitoring", "mitigation", "lung cancer risk", "environmental health"],
        conclusion_template="Radon monitoring and mitigation reduce lung cancer risk by detecting and lowering indoor radon concentrations.",
        reasoning_framework="""Radon is a radioactive gas produced by decay of uranium in soil and rocks. It accumulates indoors, posing lung cancer risk. Monitoring uses passive and active detectors (e.g., charcoal canisters, electronic monitors). Mitigation involves ventilation, sealing cracks, and sub-slab depressurization. Regulatory authorities set action levels and guidelines. Public awareness campaigns promote testing and remediation. Limitations include variability in radon levels and building characteristics. Research focuses on improved detection and mitigation technologies.""",
        key_factors=["radon concentration", "monitoring method", "mitigation technique", "regulatory action level", "public awareness"],
        primary_authority=["IAEA", "EPA", "Radon Mitigation guidelines"],
        burden_holder="proponent of radon mitigation strategy",
        adversary_position="Radon risk is overstated; mitigation is unnecessary.",
        counter_arguments=["Epidemiological data links radon to lung cancer.", "Mitigation is cost-effective."],
        resolution_strategy="Promote testing; apply mitigation in high-risk areas.",
        entity_scope="Residential, commercial, public buildings",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="EPA radon action level"
    ),
    DoctrineBlock(
        topic="Nuclear Reactor Types and Safety Features",
        keywords=["nuclear reactor", "types", "safety features", "pressurized water reactor", "boiling water reactor"],
        conclusion_template="Nuclear reactors are classified by coolant, moderator, and fuel type; safety features include containment, control rods, and emergency systems.",
        reasoning_framework="""Reactors are categorized by coolant (water, gas, liquid metal), moderator (water, graphite), and fuel (U-235, Pu-239, Th-232). Pressurized water reactors (PWR), boiling water reactors (BWR), and advanced designs (fast reactors, SMRs) have distinct operational characteristics. Safety features include containment structures, redundant control rods, emergency cooling, and passive safety systems. Regulatory authorities require safety analysis and licensing. Limitations include complexity, cost, and public perception. Continuous improvement involves technology upgrades and safety culture development.""",
        key_factors=["coolant type", "moderator", "fuel type", "containment", "emergency systems"],
        primary_authority=["IAEA", "Nuclear Reactor textbooks", "Regulatory guidelines"],
        burden_holder="proponent of reactor safety",
        adversary_position="Safety features are insufficient; accidents may occur.",
        counter_arguments=["Redundant systems mitigate risk.", "Passive safety improves reliability."],
        resolution_strategy="Apply safety analysis; upgrade systems as needed.",
        entity_scope="Nuclear power plants, research reactors",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="IAEA reactor safety standards"
    ),
    DoctrineBlock(
        topic="Nuclear Forensics and Attribution",
        keywords=["nuclear forensics", "attribution", "radioisotope analysis", "gamma spectroscopy", "chain of custody"],
        conclusion_template="Nuclear forensics uses radioisotope analysis and chain of custody to attribute material origin and support security investigations.",
        reasoning_framework="""Nuclear forensics involves identifying and attributing nuclear material via radioisotope analysis, decay chain modeling, and gamma spectroscopy. Chain of custody ensures sample integrity. Analytical techniques include mass spectrometry, neutron activation, and isotopic fingerprinting. Applications include security investigations, illicit trafficking, and environmental monitoring. Regulatory authorities set protocols and standards. Limitations include sample contamination and analytical uncertainty. Continuous improvement involves technology upgrades and international cooperation.""",
        key_factors=["radioisotope analysis", "decay chain modeling", "chain of custody", "analytical technique", "regulatory protocol"],
        primary_authority=["IAEA", "Nuclear Forensics textbooks", "Security guidelines"],
        burden_holder="proponent of forensic attribution",
        adversary_position="Analytical uncertainty hinders attribution.",
        counter_arguments=["Protocols minimize uncertainty.", "International cooperation improves reliability."],
        resolution_strategy="Apply standardized protocols; upgrade analytical techniques.",
        entity_scope="Security agencies, environmental monitoring, nuclear facilities",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA nuclear forensics guidelines"
    ),
    DoctrineBlock(
        topic="Environmental Radioactivity Monitoring",
        keywords=["environmental radioactivity", "monitoring", "gamma spectroscopy", "sampling", "regulatory compliance"],
        conclusion_template="Environmental radioactivity monitoring uses sampling and gamma spectroscopy to ensure regulatory compliance and public safety.",
        reasoning_framework="""Monitoring involves sampling air, water, soil, and biota for radioactivity. Gamma spectroscopy identifies isotopes and quantifies activity. Regulatory authorities set limits for environmental radioactivity. Continuous monitoring detects releases and trends. Limitations include sampling variability and analytical uncertainty. Public communication ensures transparency. Research focuses on improved detection and rapid response technologies.""",
        key_factors=["sampling method", "gamma spectroscopy", "regulatory limits", "analytical uncertainty", "public communication"],
        primary_authority=["IAEA", "Environmental Monitoring guidelines", "Radiochemistry journals"],
        burden_holder="proponent of monitoring program",
        adversary_position="Monitoring is insufficient; releases may go undetected.",
        counter_arguments=["Continuous monitoring improves detection.", "Rapid response protocols mitigate risk."],
        resolution_strategy="Upgrade monitoring technology; communicate results transparently.",
        entity_scope="Environmental agencies, nuclear facilities, public health",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA environmental monitoring standards"
    ),
    DoctrineBlock(
        topic="Nuclear Safeguards and Non-Proliferation",
        keywords=["nuclear safeguards", "non-proliferation", "IAEA", "material accounting", "inspection"],
        conclusion_template="Nuclear safeguards ensure non-proliferation via material accounting, inspection, and international cooperation.",
        reasoning_framework="""Safeguards involve accounting for nuclear material, inspection of facilities, and verification of compliance with non-proliferation treaties. IAEA sets protocols and conducts inspections. Material accounting tracks inventory and movement. Technology includes surveillance, seals, and analytical methods. International cooperation supports enforcement and transparency. Limitations include political challenges and technical complexity. Continuous improvement involves technology upgrades and expanded cooperation.""",
        key_factors=["material accounting", "inspection protocol", "international cooperation", "technology", "regulatory compliance"],
        primary_authority=["IAEA", "Non-Proliferation Treaty", "Safeguards guidelines"],
        burden_holder="proponent of safeguards effectiveness",
        adversary_position="Safeguards are insufficient; proliferation risk persists.",
        counter_arguments=["Expanded cooperation improves enforcement.", "Technology upgrades enhance detection."],
        resolution_strategy="Upgrade protocols; strengthen international cooperation.",
        entity_scope="Nuclear facilities, regulatory agencies, international bodies",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="IAEA safeguards standards"
    ),
    DoctrineBlock(
        topic="Nuclear Emergency Preparedness and Response",
        keywords=["emergency preparedness", "response", "radiological accident", "regulatory protocol", "public communication"],
        conclusion_template="Nuclear emergency preparedness involves planning, response protocols, and public communication to mitigate radiological accidents.",
        reasoning_framework="""Preparedness involves risk assessment, planning, training, and response protocols for radiological accidents. Regulatory authorities set requirements for emergency plans, drills, and communication. Response includes evacuation, medical treatment, and environmental monitoring. Public communication ensures transparency and reduces panic. Limitations include unpredictability and resource constraints. Continuous improvement involves technology upgrades and international cooperation.""",
        key_factors=["risk assessment", "response protocol", "training", "public communication", "regulatory compliance"],
        primary_authority=["IAEA", "Emergency Preparedness guidelines", "Radiological Protection textbooks"],
        burden_holder="proponent of emergency preparedness",
        adversary_position="Preparedness is insufficient; accidents may overwhelm response.",
        counter_arguments=["Regular drills improve readiness.", "International cooperation supports response."],
        resolution_strategy="Conduct regular drills; upgrade response technology.",
        entity_scope="Nuclear facilities, regulatory agencies, public health",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="IAEA emergency preparedness standards"
    ),
    DoctrineBlock(
        topic="Nuclear Medicine - Radioisotope Production and Application",
        keywords=["nuclear medicine", "radioisotope production", "application", "diagnosis", "therapy"],
        conclusion_template="Nuclear medicine uses radioisotopes for diagnosis and therapy, produced via reactors, cyclotrons, or generators.",
        reasoning_framework="""Radioisotopes are produced in reactors (e.g., Tc-99m, I-131), cyclotrons (e.g., F-18), or generators. Applications include imaging (PET, SPECT) and therapy (thyroid, cancer). Safety involves dose optimization, regulatory compliance, and waste management. Limitations include supply chain, short half-lives, and patient sensitivity. Continuous improvement involves technology upgrades and new isotopes. Regulatory authorities set standards for production, use, and disposal.""",
        key_factors=["production method", "application", "dose optimization", "regulatory compliance", "waste management"],
        primary_authority=["IAEA", "Nuclear Medicine textbooks", "Regulatory guidelines"],
        burden_holder="proponent of nuclear medicine efficacy",
        adversary_position="Radioisotope supply is unreliable; patient risk is high.",
        counter_arguments=["New production methods improve supply.", "Protocols optimize patient safety."],
        resolution_strategy="Upgrade production technology; optimize protocols.",
        entity_scope="Hospitals, nuclear medicine facilities",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA nuclear medicine standards"
    ),
    DoctrineBlock(
        topic="Radiation Safety Training and Competency",
        keywords=["radiation safety", "training", "competency", "regulatory compliance", "continuous improvement"],
        conclusion_template="Radiation safety training ensures competency and regulatory compliance, supporting continuous improvement in protection measures.",
        reasoning_framework="""Training covers radiation fundamentals, protection measures, regulatory requirements, and emergency response. Competency is assessed via exams, practical exercises, and audits. Regulatory authorities set minimum training requirements. Continuous improvement involves refresher courses and technology updates. Limitations include variability in training quality and retention. Public communication ensures transparency. Research focuses on improved training methods and assessment tools.""",
        key_factors=["training content", "competency assessment", "regulatory requirements", "continuous improvement", "public communication"],
        primary_authority=["IAEA", "Radiation Safety Training guidelines", "Regulatory standards"],
        burden_holder="proponent of training program efficacy",
        adversary_position="Training is insufficient; accidents may occur.",
        counter_arguments=["Regular refresher courses improve retention.", "Audits ensure compliance."],
        resolution_strategy="Upgrade training methods; conduct regular audits.",
        entity_scope="Radiation facilities, medical, industrial, research",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA training standards"
    ),
    DoctrineBlock(
        topic="Nuclear Data Libraries and Cross-Section Evaluation",
        keywords=["nuclear data", "cross-section", "evaluation", "library", "simulation"],
        conclusion_template="Nuclear data libraries provide evaluated cross-sections for simulation and analysis, supporting reactor design and radiation transport modeling.",
        reasoning_framework="""Data libraries (e.g., ENDF, JEFF, JENDL) compile evaluated cross-sections for neutron, photon, and charged particle interactions. Evaluation involves experimental data, theoretical modeling, and uncertainty analysis. Libraries support reactor design, radiation transport simulation, and analytical calculations. Continuous improvement involves new measurements and modeling. Limitations include gaps in data and uncertainty. Regulatory authorities require use of approved libraries. Research focuses on expanding and improving data sets.""",
        key_factors=["cross-section", "evaluation", "library", "uncertainty", "regulatory compliance"],
        primary_authority=["IAEA", "ENDF", "JEFF", "JENDL", "Nuclear Data journals"],
        burden_holder="proponent of data library accuracy",
        adversary_position="Data gaps and uncertainty limit simulation reliability.",
        counter_arguments=["Continuous improvement reduces gaps.", "Uncertainty analysis guides application."],
        resolution_strategy="Use approved libraries; update as new data becomes available.",
        entity_scope="Reactor design, simulation, analytical laboratories",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="IAEA nuclear data standards"
    ),
    DoctrineBlock(
        topic="Nuclear Decommissioning and Site Remediation",
        keywords=["decommissioning", "site remediation", "radioactive contamination", "regulatory compliance", "waste management"],
        conclusion_template="Nuclear decommissioning involves dismantling facilities and remediating sites to meet regulatory standards for radioactive contamination.",
        reasoning_framework="""Decommissioning includes planning, dismantling, waste management, and site remediation. Regulatory authorities set standards for contamination levels and remediation methods. Waste is classified, treated, and disposed per guidelines. Environmental monitoring ensures compliance. Limitations include cost, complexity, and public perception. Continuous improvement involves technology upgrades and stakeholder engagement. Research focuses on improved remediation techniques and waste minimization.""",
        key_factors=["planning", "dismantling", "waste management", "remediation method", "regulatory compliance"],
        primary_authority=["IAEA", "Decommissioning guidelines", "Environmental Protection standards"],
        burden_holder="proponent of decommissioning efficacy",
        adversary_position="Remediation is costly and incomplete; contamination persists.",
        counter_arguments=["Technology upgrades improve remediation.", "Stakeholder engagement supports acceptance."],
        resolution_strategy="Upgrade remediation technology; engage stakeholders.",
        entity_scope="Nuclear facilities, contaminated sites",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA decommissioning standards"
    ),
    DoctrineBlock(
        topic="Nuclear Material Accounting and Control",
        keywords=["material accounting", "control", "inventory", "regulatory compliance", "safeguards"],
        conclusion_template="Material accounting and control ensure accurate inventory and compliance with safeguards, supporting non-proliferation.",
        reasoning_framework="""Accounting involves tracking nuclear material inventory, movement, and usage. Control includes physical security, access restrictions, and regulatory reporting. Safeguards protocols require regular audits and inspections. Technology includes barcoding, surveillance, and analytical verification. Limitations include human error and technical complexity. Continuous improvement involves technology upgrades and process optimization. Regulatory authorities set standards and enforce compliance.""",
        key_factors=["inventory tracking", "control measures", "audit", "inspection", "regulatory compliance"],
        primary_authority=["IAEA", "Material Accounting guidelines", "Safeguards standards"],
        burden_holder="proponent of accounting and control efficacy",
        adversary_position="Accounting errors and lapses enable diversion.",
        counter_arguments=["Regular audits minimize errors.", "Technology upgrades improve reliability."],
        resolution_strategy="Upgrade accounting technology; conduct regular audits.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="IAEA material accounting standards"
    ),
    DoctrineBlock(
        topic="Nuclear Fuel Cycle - Front End and Back End Processes",
        keywords=["fuel cycle", "front end", "back end", "mining", "enrichment", "reprocessing"],
        conclusion_template="The nuclear fuel cycle includes front end (mining, conversion, enrichment) and back end (reprocessing, waste management) processes, regulated for safety and efficiency.",
        reasoning_framework="""Front end processes involve uranium mining, conversion to UF6, enrichment, and fuel fabrication. Back end includes spent fuel storage, reprocessing (e.g., PUREX), and waste management. Regulatory authorities set standards for safety, environmental protection, and non-proliferation. Technology upgrades improve efficiency and reduce waste. Limitations include cost, complexity, and public perception. Continuous improvement involves process optimization and stakeholder engagement. Research focuses on advanced fuel cycles and waste minimization.""",
        key_factors=["mining", "conversion", "enrichment", "reprocessing", "waste management"],
        primary_authority=["IAEA", "Fuel Cycle guidelines", "Nuclear Industry standards"],
        burden_holder="proponent of fuel cycle efficacy",
        adversary_position="Fuel cycle is inefficient and poses proliferation risks.",
        counter_arguments=["Process optimization improves efficiency.", "Safeguards reduce proliferation risk."],
        resolution_strategy="Optimize processes; apply safeguards.",
        entity_scope="Nuclear industry, regulatory agencies",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA fuel cycle standards"
    ),
    DoctrineBlock(
        topic="Nuclear Security and Physical Protection",
        keywords=["nuclear security", "physical protection", "access control", "surveillance", "regulatory compliance"],
        conclusion_template="Nuclear security involves physical protection, access control, and surveillance to prevent unauthorized access and sabotage.",
        reasoning_framework="""Security measures include fencing, barriers, access control, surveillance, and response protocols. Regulatory authorities set standards for physical protection and security culture. Technology includes biometric access, video surveillance, and intrusion detection. Continuous improvement involves technology upgrades and training. Limitations include cost and evolving threats. Incident response plans address potential breaches. Stakeholder engagement supports acceptance and compliance.""",
        key_factors=["physical protection", "access control", "surveillance", "response protocol", "regulatory compliance"],
        primary_authority=["IAEA", "Security guidelines", "Regulatory standards"],
        burden_holder="proponent of security efficacy",
        adversary_position="Security measures are insufficient; threats evolve.",
        counter_arguments=["Continuous improvement addresses evolving threats.", "Training improves response."],
        resolution_strategy="Upgrade security technology; conduct regular training.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA security standards"
    ),
    DoctrineBlock(
        topic="Nuclear Regulatory Framework and Licensing",
        keywords=["regulatory framework", "licensing", "compliance", "safety analysis", "public engagement"],
        conclusion_template="Regulatory framework and licensing ensure compliance, safety analysis, and public engagement for nuclear facilities.",
        reasoning_framework="""Framework includes laws, regulations, and licensing procedures. Safety analysis supports licensing decisions. Regulatory authorities conduct inspections and audits. Public engagement ensures transparency and acceptance. Continuous improvement involves technology upgrades and stakeholder input. Limitations include complexity and variability across jurisdictions. Research focuses on harmonizing standards and improving licensing efficiency.""",
        key_factors=["laws", "regulations", "licensing", "safety analysis", "public engagement"],
        primary_authority=["IAEA", "Regulatory guidelines", "Licensing standards"],
        burden_holder="proponent of regulatory compliance",
        adversary_position="Regulatory framework is complex and inefficient.",
        counter_arguments=["Continuous improvement streamlines procedures.", "Public engagement improves acceptance."],
        resolution_strategy="Harmonize standards; upgrade licensing technology.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA regulatory standards"
    ),
    DoctrineBlock(
        topic="Nuclear Liability and Insurance",
        keywords=["liability", "insurance", "compensation", "regulatory compliance", "accident"],
        conclusion_template="Nuclear liability and insurance provide compensation for accidents, regulated by national and international frameworks.",
        reasoning_framework="""Liability laws set compensation for nuclear accidents. Insurance covers facility operators and affected parties. Regulatory authorities set minimum coverage and compensation limits. International frameworks (e.g., Vienna Convention) harmonize standards. Continuous improvement involves expanding coverage and improving claims processing. Limitations include variability across jurisdictions and public perception. Research focuses on improving risk assessment and compensation mechanisms.""",
        key_factors=["liability law", "insurance coverage", "compensation", "regulatory compliance", "international framework"],
        primary_authority=["IAEA", "Vienna Convention", "Insurance guidelines"],
        burden_holder="proponent of liability and insurance adequacy",
        adversary_position="Coverage is insufficient; compensation is delayed.",
        counter_arguments=["International frameworks expand coverage.", "Claims processing is improving."],
        resolution_strategy="Expand coverage; improve claims processing.",
        entity_scope="Nuclear facilities, regulatory agencies, affected parties",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="Vienna Convention on Nuclear Liability"
    ),
    DoctrineBlock(
        topic="Nuclear Export Control and International Trade",
        keywords=["export control", "international trade", "regulatory compliance", "non-proliferation", "technology transfer"],
        conclusion_template="Export control regulates international trade in nuclear materials and technology to prevent proliferation and ensure compliance.",
        reasoning_framework="""Export control involves licensing, inspection, and compliance with international treaties. Regulatory authorities set standards for material and technology transfer. Non-proliferation treaties guide enforcement. Technology includes tracking, surveillance, and analytical verification. Continuous improvement involves harmonizing standards and expanding cooperation. Limitations include political challenges and technical complexity. Research focuses on improving enforcement and detection technologies.""",
        key_factors=["licensing", "inspection", "treaty compliance", "technology", "international cooperation"],
        primary_authority=["IAEA", "Export Control guidelines", "Non-Proliferation Treaty"],
        burden_holder="proponent of export control efficacy",
        adversary_position="Export control is insufficient; proliferation risk persists.",
        counter_arguments=["International cooperation improves enforcement.", "Technology upgrades enhance detection."],
        resolution_strategy="Harmonize standards; upgrade enforcement technology.",
        entity_scope="Nuclear industry, regulatory agencies, international bodies",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA export control standards"
    ),
    DoctrineBlock(
        topic="Nuclear Risk Assessment and Management",
        keywords=["risk assessment", "management", "probabilistic safety analysis", "regulatory compliance", "continuous improvement"],
        conclusion_template="Risk assessment and management use probabilistic safety analysis to identify, quantify, and mitigate nuclear hazards.",
        reasoning_framework="""Assessment involves identifying hazards, quantifying risk, and implementing mitigation measures. Probabilistic safety analysis (PSA) models accident scenarios and outcomes. Regulatory authorities set requirements for risk management. Continuous improvement involves technology upgrades and process optimization. Limitations include uncertainty and evolving threats. Research focuses on improving modeling and mitigation strategies.""",
        key_factors=["hazard identification", "quantification", "mitigation", "PSA", "regulatory compliance"],
        primary_authority=["IAEA", "Risk Assessment guidelines", "Safety Analysis textbooks"],
        burden_holder="proponent of risk management efficacy",
        adversary_position="Risk assessment is uncertain; mitigation is incomplete.",
        counter_arguments=["Continuous improvement reduces uncertainty.", "PSA models guide mitigation."],
        resolution_strategy="Upgrade modeling; optimize mitigation measures.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA risk assessment standards"
    ),
    DoctrineBlock(
        topic="Nuclear Instrumentation Calibration and Quality Assurance",
        keywords=["instrumentation", "calibration", "quality assurance", "regulatory compliance", "continuous improvement"],
        conclusion_template="Calibration and quality assurance ensure accurate nuclear instrumentation performance and regulatory compliance.",
        reasoning_framework="""Calibration involves reference standards, test procedures, and documentation. Quality assurance includes regular checks, audits, and process optimization. Regulatory authorities set requirements for calibration and QA. Technology upgrades improve accuracy and reliability. Limitations include variability in standards and technical complexity. Continuous improvement involves training and technology updates. Research focuses on improved calibration methods and QA protocols.""",
        key_factors=["reference standard", "test procedure", "audit", "training", "regulatory compliance"],
        primary_authority=["IAEA", "Calibration guidelines", "Quality Assurance standards"],
        burden_holder="proponent of calibration and QA efficacy",
        adversary_position="Calibration is inconsistent; QA is insufficient.",
        counter_arguments=["Regular audits improve consistency.", "Technology upgrades improve reliability."],
        resolution_strategy="Upgrade calibration methods; conduct regular audits.",
        entity_scope="Nuclear facilities, analytical laboratories",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA calibration and QA standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Design and Safety Analysis",
        keywords=["facility design", "safety analysis", "regulatory compliance", "risk assessment", "continuous improvement"],
        conclusion_template="Facility design and safety analysis ensure compliance and risk mitigation, supporting safe operation of nuclear facilities.",
        reasoning_framework="""Design involves layout, material selection, and safety features. Safety analysis models accident scenarios and mitigation measures. Regulatory authorities set requirements for design and analysis. Continuous improvement involves technology upgrades and process optimization. Limitations include cost, complexity, and evolving threats. Research focuses on improved modeling and design optimization.""",
        key_factors=["layout", "material selection", "safety feature", "accident scenario", "regulatory compliance"],
        primary_authority=["IAEA", "Facility Design guidelines", "Safety Analysis standards"],
        burden_holder="proponent of design and analysis efficacy",
        adversary_position="Design and analysis are insufficient; accidents may occur.",
        counter_arguments=["Continuous improvement reduces risk.", "Technology upgrades improve safety."],
        resolution_strategy="Upgrade design and analysis methods; optimize safety features.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA facility design standards"
    ),
    DoctrineBlock(
        topic="Nuclear Waste Transportation and Security",
        keywords=["waste transportation", "security", "regulatory compliance", "risk assessment", "continuous improvement"],
        conclusion_template="Waste transportation and security ensure safe movement and protection of radioactive materials, regulated for compliance and risk mitigation.",
        reasoning_framework="""Transportation involves packaging, route planning, and security measures. Regulatory authorities set requirements for packaging, labeling, and security. Risk assessment models accident scenarios and mitigation measures. Continuous improvement involves technology upgrades and process optimization. Limitations include public perception and evolving threats. Research focuses on improved packaging and security technology.""",
        key_factors=["packaging", "route planning", "security measure", "regulatory compliance", "risk assessment"],
        primary_authority=["IAEA", "Transportation guidelines", "Security standards"],
        burden_holder="proponent of transportation and security efficacy",
        adversary_position="Transportation is risky; security measures are insufficient.",
        counter_arguments=["Technology upgrades improve safety.", "Regulatory compliance ensures protection."],
        resolution_strategy="Upgrade packaging and security technology; optimize routes.",
        entity_scope="Nuclear facilities, transportation agencies",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA transportation standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Aging Management",
        keywords=["aging management", "facility", "maintenance", "regulatory compliance", "continuous improvement"],
        conclusion_template="Aging management ensures safe operation of nuclear facilities via maintenance, monitoring, and regulatory compliance.",
        reasoning_framework="""Management involves monitoring equipment condition, maintenance, and upgrades. Regulatory authorities set requirements for aging management. Technology upgrades improve reliability and safety. Continuous improvement involves process optimization and stakeholder engagement. Limitations include cost, complexity, and evolving threats. Research focuses on improved monitoring and maintenance techniques.""",
        key_factors=["equipment condition", "maintenance", "monitoring", "regulatory compliance", "technology upgrade"],
        primary_authority=["IAEA", "Aging Management guidelines", "Maintenance standards"],
        burden_holder="proponent of aging management efficacy",
        adversary_position="Aging management is insufficient; accidents may occur.",
        counter_arguments=["Regular maintenance reduces risk.", "Technology upgrades improve reliability."],
        resolution_strategy="Upgrade monitoring and maintenance technology; optimize processes.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA aging management standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Fire Protection",
        keywords=["fire protection", "facility", "regulatory compliance", "risk assessment", "continuous improvement"],
        conclusion_template="Fire protection ensures safe operation of nuclear facilities via prevention, detection, and response measures, regulated for compliance.",
        reasoning_framework="""Protection involves prevention (material selection, layout), detection (sensors, alarms), and response (sprinklers, evacuation). Regulatory authorities set requirements for fire protection. Risk assessment models fire scenarios and mitigation measures. Continuous improvement involves technology upgrades and process optimization. Limitations include cost, complexity, and evolving threats. Research focuses on improved detection and response technology.""",
        key_factors=["prevention", "detection", "response", "regulatory compliance", "risk assessment"],
        primary_authority=["IAEA", "Fire Protection guidelines", "Facility standards"],
        burden_holder="proponent of fire protection efficacy",
        adversary_position="Fire protection is insufficient; accidents may occur.",
        counter_arguments=["Technology upgrades improve detection and response.", "Regulatory compliance ensures protection."],
        resolution_strategy="Upgrade detection and response technology; optimize prevention measures.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA fire protection standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Human Factors Engineering",
        keywords=["human factors", "engineering", "facility", "regulatory compliance", "continuous improvement"],
        conclusion_template="Human factors engineering improves safety and performance in nuclear facilities via ergonomic design and regulatory compliance.",
        reasoning_framework="""Engineering involves ergonomic design, training, and process optimization. Regulatory authorities set requirements for human factors. Technology upgrades improve safety and performance. Continuous improvement involves stakeholder engagement and process refinement. Limitations include variability in human behavior and complexity. Research focuses on improved design and training methods.""",
        key_factors=["ergonomic design", "training", "process optimization", "regulatory compliance", "stakeholder engagement"],
        primary_authority=["IAEA", "Human Factors guidelines", "Engineering standards"],
        burden_holder="proponent of human factors engineering efficacy",
        adversary_position="Human factors are insufficiently addressed; accidents may occur.",
        counter_arguments=["Continuous improvement reduces risk.", "Training improves performance."],
        resolution_strategy="Upgrade design and training methods; engage stakeholders.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA human factors standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Radiation Monitoring Systems",
        keywords=["radiation monitoring", "facility", "system", "regulatory compliance", "continuous improvement"],
        conclusion_template="Radiation monitoring systems ensure safe operation of nuclear facilities via detection, alarm, and regulatory compliance.",
        reasoning_framework="""Systems include detectors, alarms, and data management. Regulatory authorities set requirements for monitoring. Technology upgrades improve sensitivity and reliability. Continuous improvement involves process optimization and training. Limitations include cost, complexity, and evolving threats. Research focuses on improved detection and data management technology.""",
        key_factors=["detector", "alarm", "data management", "regulatory compliance", "technology upgrade"],
        primary_authority=["IAEA", "Radiation Monitoring guidelines", "Facility standards"],
        burden_holder="proponent of monitoring system efficacy",
        adversary_position="Monitoring systems are insufficient; releases may go undetected.",
        counter_arguments=["Technology upgrades improve detection.", "Regulatory compliance ensures protection."],
        resolution_strategy="Upgrade detection and data management technology; optimize processes.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA radiation monitoring standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Emergency Power Systems",
        keywords=["emergency power", "facility", "system", "regulatory compliance", "continuous improvement"],
        conclusion_template="Emergency power systems ensure safe operation of nuclear facilities during outages, regulated for compliance and reliability.",
        reasoning_framework="""Systems include backup generators, batteries, and redundancy. Regulatory authorities set requirements for emergency power. Technology upgrades improve reliability and response. Continuous improvement involves process optimization and maintenance. Limitations include cost, complexity, and evolving threats. Research focuses on improved backup technology and response protocols.""",
        key_factors=["backup generator", "battery", "redundancy", "regulatory compliance", "maintenance"],
        primary_authority=["IAEA", "Emergency Power guidelines", "Facility standards"],
        burden_holder="proponent of emergency power system efficacy",
        adversary_position="Emergency power is unreliable; outages may compromise safety.",
        counter_arguments=["Redundancy improves reliability.", "Maintenance ensures performance."],
        resolution_strategy="Upgrade backup technology; optimize maintenance.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IAEA emergency power standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Instrumentation and Control Systems",
        keywords=["instrumentation", "control system", "facility", "regulatory compliance", "continuous improvement"],
        conclusion_template="Instrumentation and control systems ensure safe operation of nuclear facilities via automation, monitoring, and regulatory compliance.",
        reasoning_framework="""Systems include sensors, actuators, automation, and data management. Regulatory authorities set requirements for instrumentation and control. Technology upgrades improve reliability and safety. Continuous improvement involves process optimization and training. Limitations include cost, complexity, and evolving threats. Research focuses on improved automation and data management technology.""",
        key_factors=["sensor", "actuator", "automation", "regulatory compliance", "technology upgrade"],
        primary_authority=["IAEA", "Instrumentation guidelines", "Control System standards"],
        burden_holder="proponent of instrumentation and control efficacy",
        adversary_position="Instrumentation and control are insufficient; accidents may occur.",
        counter_arguments=["Technology upgrades improve reliability.", "Training improves performance."],
        resolution_strategy="Upgrade automation and data management technology; optimize processes.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IAEA instrumentation standards"
    ),
    DoctrineBlock(
        topic="Nuclear Facility Waste Minimization and Recycling",
        keywords=["waste minimization", "recycling", "facility", "regulatory compliance", "continuous improvement"],
        conclusion_template="Waste minimization and recycling reduce radioactive waste volume and support regulatory compliance in nuclear facilities.",
        reasoning_framework="""Minimization involves process optimization, material selection, and recycling. Regulatory authorities set requirements for waste management. Technology upgrades improve efficiency and safety. Continuous improvement involves stakeholder engagement and process refinement. Limitations include cost, complexity, and evolving threats. Research focuses on improved recycling and waste minimization techniques.""",
        key_factors=["process optimization", "material selection", "recycling", "regulatory compliance", "stakeholder engagement"],
        primary_authority=["IAEA", "Waste Minimization guidelines", "Facility standards"],
        burden_holder="proponent of waste minimization efficacy",
        adversary_position="Minimization and recycling are insufficient; waste volume remains high.",
        counter_arguments=["Technology upgrades improve efficiency.", "Stakeholder engagement supports acceptance."],
        resolution_strategy="Upgrade recycling technology; optimize processes.",
        entity_scope="Nuclear facilities, regulatory agencies",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IAEA waste minimization standards"
    ),
]

def get_doctrine_by_topic(topic: str) -> Optional[DoctrineBlock]:
    for doctrine in DOCTRINE_CACHE:
        if doctrine.topic.lower() == topic.lower():
            return doctrine
    return None

def search_doctrines(keyword: str) -> List[DoctrineBlock]:
    results = []
    keyword_lower = keyword.lower()
    for doctrine in DOCTRINE_CACHE:
        if keyword_lower in doctrine.topic.lower() or any(keyword_lower in k.lower() for k in doctrine.keywords):
            results.append(doctrine)
    return results

def get_all_topics() -> List[str]:
    return [doctrine.topic for doctrine in DOCTRINE_CACHE]