import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PRB01 Semantic Team"
SEMANTIC_MAP_ENGINE = "PRB01_probate_filing_analyzer"

SEMANTIC_MAP = {
    # will_validity_formalities
    "will validity": "will_validity_formalities",
    "will formalities": "will_validity_formalities",
    "valid will": "will_validity_formalities",
    "formal will": "will_validity_formalities",
    "will execution": "will_validity_formalities",
    "execution of will": "will_validity_formalities",
    "attested will": "will_validity_formalities",
    "self-proved will": "will_validity_formalities",
    "self proved will": "will_validity_formalities",
    "holographic will": "will_validity_formalities",
    "nuncupative will": "will_validity_formalities",
    "oral will": "will_validity_formalities",
    "written will": "will_validity_formalities",
    "signed will": "will_validity_formalities",
    "testator signature": "will_validity_formalities",
    "witness signature": "will_validity_formalities",
    "witnesses": "will_validity_formalities",
    "number of witnesses": "will_validity_formalities",
    "witness requirement": "will_validity_formalities",
    "publication of will": "will_validity_formalities",
    "will publication": "will_validity_formalities",
    "will attestation": "will_validity_formalities",
    "attestation clause": "will_validity_formalities",
    "notary": "will_validity_formalities",
    "notarization": "will_validity_formalities",
    "notarized will": "will_validity_formalities",
    "will defects": "will_validity_formalities",
    "will defect": "will_validity_formalities",
    "defective will": "will_validity_formalities",
    "will compliance": "will_validity_formalities",
    "statutory will": "will_validity_formalities",
    "compliance with statute": "will_validity_formalities",
    "will statute": "will_validity_formalities",
    "will requirements": "will_validity_formalities",
    "will reqs": "will_validity_formalities",
    "will req": "will_validity_formalities",
    "will reqmt": "will_validity_formalities",
    "will reqmts": "will_validity_formalities",
    "will requisites": "will_validity_formalities",
    "will requisite": "will_validity_formalities",
    "will rules": "will_validity_formalities",
    "will rule": "will_validity_formalities",
    "will law": "will_validity_formalities",
    "will laws": "will_validity_formalities",
    "will code": "will_validity_formalities",
    "will codes": "will_validity_formalities",
    "will statute of frauds": "will_validity_formalities",
    "statute of frauds": "will_validity_formalities",
    "will frauds": "will_validity_formalities",
    "will formality": "will_validity_formalities",
    "will formalties": "will_validity_formalities",
    "will formailities": "will_validity_formalities",
    "will formalityies": "will_validity_formalities",

    # testamentary_capacity
    "testamentary capacity": "testamentary_capacity",
    "capacity to make will": "testamentary_capacity",
    "capacity to execute will": "testamentary_capacity",
    "testator capacity": "testamentary_capacity",
    "sound mind": "testamentary_capacity",
    "of sound mind": "testamentary_capacity",
    "mental capacity": "testamentary_capacity",
    "testamentary competence": "testamentary_capacity",
    "testamentary competency": "testamentary_capacity",
    "competence to make will": "testamentary_capacity",
    "competency to make will": "testamentary_capacity",
    "testator competence": "testamentary_capacity",
    "testator competency": "testamentary_capacity",
    "lucid interval": "testamentary_capacity",
    "lucid moments": "testamentary_capacity",
    "mental state": "testamentary_capacity",
    "testator mental state": "testamentary_capacity",
    "testator's mind": "testamentary_capacity",
    "testator understanding": "testamentary_capacity",
    "testator knowledge": "testamentary_capacity",
    "testator awareness": "testamentary_capacity",
    "testator intent": "testamentary_capacity",
    "testator's intent": "testamentary_capacity",
    "testator's capacity": "testamentary_capacity",
    "testator's competency": "testamentary_capacity",
    "testator's competence": "testamentary_capacity",
    "testator's soundness": "testamentary_capacity",
    "testator's mental health": "testamentary_capacity",
    "mental health": "testamentary_capacity",
    "testator's sanity": "testamentary_capacity",
    "sanity": "testamentary_capacity",
    "insanity": "testamentary_capacity",
    "incompetence": "testamentary_capacity",
    "incapacity": "testamentary_capacity",
    "incompetency": "testamentary_capacity",
    "capacity": "testamentary_capacity",
    "competence": "testamentary_capacity",
    "competency": "testamentary_capacity",
    "testamentary incapacity": "testamentary_capacity",
    "testamentary incompetence": "testamentary_capacity",
    "testamentary incompetency": "testamentary_capacity",
    "testamentary incapacity": "testamentary_capacity",

    # intestate_succession_hierarchy
    "intestate succession": "intestate_succession_hierarchy",
    "intestacy": "intestate_succession_hierarchy",
    "intestate": "intestate_succession_hierarchy",
    "succession": "intestate_succession_hierarchy",
    "intestate hierarchy": "intestate_succession_hierarchy",
    "succession hierarchy": "intestate_succession_hierarchy",
    "heirship": "intestate_succession_hierarchy",
    "heirship determination": "intestate_succession_hierarchy",
    "heir determination": "intestate_succession_hierarchy",
    "heir": "intestate_succession_hierarchy",
    "heirs": "intestate_succession_hierarchy",
    "order of heirs": "intestate_succession_hierarchy",
    "priority of heirs": "intestate_succession_hierarchy",
    "distribution order": "intestate_succession_hierarchy",
    "intestate distribution": "intestate_succession_hierarchy",
    "intestate share": "intestate_succession_hierarchy",
    "intestate shares": "intestate_succession_hierarchy",
    "intestate estate": "intestate_succession_hierarchy",
    "intestate property": "intestate_succession_hierarchy",
    "no will": "intestate_succession_hierarchy",
    "without will": "intestate_succession_hierarchy",
    "no testament": "intestate_succession_hierarchy",
    "no testamentary instrument": "intestate_succession_hierarchy",
    "no testamentary document": "intestate_succession_hierarchy",
    "default heirs": "intestate_succession_hierarchy",
    "default succession": "intestate_succession_hierarchy",
    "statutory heirs": "intestate_succession_hierarchy",
    "statutory succession": "intestate_succession_hierarchy",
    "statutory order": "intestate_succession_hierarchy",
    "statutory distribution": "intestate_succession_hierarchy",
    "statutory intestacy": "intestate_succession_hierarchy",
    "statutory intestate": "intestate_succession_hierarchy",
    "distribution by law": "intestate_succession_hierarchy",
    "distribution by statute": "intestate_succession_hierarchy",
    "heir at law": "intestate_succession_hierarchy",
    "heirs at law": "intestate_succession_hierarchy",
    "next of kin": "intestate_succession_hierarchy",
    "kin": "intestate_succession_hierarchy",
    "relatives": "intestate_succession_hierarchy",
    "family tree": "intestate_succession_hierarchy",
    "blood relatives": "intestate_succession_hierarchy",
    "descendants": "intestate_succession_hierarchy",
    "issue": "intestate_succession_hierarchy",
    "children": "intestate_succession_hierarchy",
    "child": "intestate_succession_hierarchy",
    "grandchildren": "intestate_succession_hierarchy",
    "grandchild": "intestate_succession_hierarchy",
    "spouse": "intestate_succession_hierarchy",
    "surviving spouse": "intestate_succession_hierarchy",
    "parents": "intestate_succession_hierarchy",
    "parent": "intestate_succession_hierarchy",
    "siblings": "intestate_succession_hierarchy",
    "brother": "intestate_succession_hierarchy",
    "sister": "intestate_succession_hierarchy",
    "collateral heirs": "intestate_succession_hierarchy",
    "collaterals": "intestate_succession_hierarchy",
    "ancestors": "intestate_succession_hierarchy",
    "grandparents": "intestate_succession_hierarchy",
    "grandparent": "intestate_succession_hierarchy",
    "uncles": "intestate_succession_hierarchy",
    "aunts": "intestate_succession_hierarchy",
    "uncle": "intestate_succession_hierarchy",
    "aunt": "intestate_succession_hierarchy",
    "cousins": "intestate_succession_hierarchy",
    "cousin": "intestate_succession_hierarchy",
    "escheat": "intestate_succession_hierarchy",

    # homestead_exemption_probate
    "homestead": "homestead_exemption_probate",
    "homestead exemption": "homestead_exemption_probate",
    "probate homestead": "homestead_exemption_probate",
    "homestead rights": "homestead_exemption_probate",
    "homestead right": "homestead_exemption_probate",
    "homestead allowance": "homestead_exemption_probate",
    "homestead property": "homestead_exemption_probate",
    "homestead law": "homestead_exemption_probate",
    "homestead laws": "homestead_exemption_probate",
    "homestead statutes": "homestead_exemption_probate",
    "homestead statute": "homestead_exemption_probate",
    "homestead protection": "homestead_exemption_probate",
    "homestead protections": "homestead_exemption_probate",
    "homestead claim": "homestead_exemption_probate",
    "homestead claims": "homestead_exemption_probate",
    "homestead application": "homestead_exemption_probate",
    "homestead applications": "homestead_exemption_probate",
    "homestead benefit": "homestead_exemption_probate",
    "homestead benefits": "homestead_exemption_probate",
    "homestead interest": "homestead_exemption_probate",
    "homestead interests": "homestead_exemption_probate",
    "homestead estate": "homestead_exemption_probate",
    "homestead estates": "homestead_exemption_probate",
    "homestead exemption probate": "homestead_exemption_probate",
    "probate homestead exemption": "homestead_exemption_probate",
    "homestead in probate": "homestead_exemption_probate",
    "family homestead": "homestead_exemption_probate",
    "surviving spouse homestead": "homestead_exemption_probate",
    "minor child homestead": "homestead_exemption_probate",
    "minor children homestead": "homestead_exemption_probate",
    "spousal homestead": "homestead_exemption_probate",
    "spouse homestead": "homestead_exemption_probate",
    "homestead set aside": "homestead_exemption_probate",
    "set aside homestead": "homestead_exemption_probate",
    "homestead setaside": "homestead_exemption_probate",
    "homestead set-aside": "homestead_exemption_probate",

    # independent_administration
    "independent administration": "independent_administration",
    "independent executor": "independent_administration",
    "independent executrix": "independent_administration",
    "independent personal representative": "independent_administration",
    "independent rep": "independent_administration",
    "independent pr": "independent_administration",
    "independent admin": "independent_administration",
    "independent administrator": "independent_administration",
    "independent administratrix": "independent_administration",
    "independent estate administration": "independent_administration",
    "independent probate": "independent_administration",
    "independent letters": "independent_administration",
    "letters of independent administration": "independent_administration",
    "letters independent": "independent_administration",
    "independent appointment": "independent_administration",
    "independent appointment of executor": "independent_administration",
    "independent appointment of administrator": "independent_administration",
    "independent appointment of pr": "independent_administration",
    "independent appointment of rep": "independent_administration",
    "independent appointment of personal representative": "independent_administration",
    "independent estate": "independent_administration",
    "independent estates": "independent_administration",
    "independent administration of estate": "independent_administration",
    "independent administration of estates": "independent_administration",
    "independent admin of estate": "independent_administration",
    "independent admin of estates": "independent_administration",
    "independent probate administration": "independent_administration",
    "independent probate admin": "independent_administration",
    "independent probate administrator": "independent_administration",
    "independent probate administratrix": "independent_administration",

    # will_contest_grounds
    "will contest": "will_contest_grounds",
    "contest will": "will_contest_grounds",
    "will challenge": "will_contest_grounds",
    "challenge will": "will_contest_grounds",
    "will dispute": "will_contest_grounds",
    "dispute will": "will_contest_grounds",
    "contesting will": "will_contest_grounds",
    "challenging will": "will_contest_grounds",
    "will contest grounds": "will_contest_grounds",
    "grounds for will contest": "will_contest_grounds",
    "grounds to contest will": "will_contest_grounds",
    "basis for will contest": "will_contest_grounds",
    "basis to contest will": "will_contest_grounds",
    "will invalidity": "will_contest_grounds",
    "invalid will": "will_contest_grounds",
    "will fraud": "will_contest_grounds",
    "fraudulent will": "will_contest_grounds",
    "will forgery": "will_contest_grounds",
    "forged will": "will_contest_grounds",
    "will duress": "will_contest_grounds",
    "duress": "will_contest_grounds",
    "undue influence": "will_contest_grounds",
    "undue influence will": "will_contest_grounds",
    "undue influence contest": "will_contest_grounds",
    "coercion": "will_contest_grounds",
    "coercion will": "will_contest_grounds",
    "lack of capacity": "will_contest_grounds",
    "lack of testamentary capacity": "will_contest_grounds",
    "lack of formalities": "will_contest_grounds",
    "improper execution": "will_contest_grounds",
    "improperly executed will": "will_contest_grounds",
    "improper execution of will": "will_contest_grounds",
    "mistake": "will_contest_grounds",
    "mistake in will": "will_contest_grounds",
    "mistaken will": "will_contest_grounds",
    "mistaken execution": "will_contest_grounds",
    "mistaken execution of will": "will_contest_grounds",
    "fraud": "will_contest_grounds",
    "fraud in execution": "will_contest_grounds",
    "fraud in inducement": "will_contest_grounds",
    "fraudulent inducement": "will_contest_grounds",
    "fraudulent execution": "will_contest_grounds",
    "fraudulent signature": "will_contest_grounds",
    "forgery": "will_contest_grounds",
    "forged signature": "will_contest_grounds",
    "forged testator": "will_contest_grounds",
    "forged witness": "will_contest_grounds",
    "coerced will": "will_contest_grounds",
    "coerced testator": "will_contest_grounds",
    "coerced signature": "will_contest_grounds",
    "coercion in execution": "will_contest_grounds",
    "coercion in will": "will_contest_grounds",
    "will contest period": "will_contest_grounds",
    "contest period": "will_contest_grounds",
    "contest deadline": "will_contest_grounds",
    "contest statute": "will_contest_grounds",
    "contest statutes": "will_contest_grounds",
    "contest time limit": "will_contest_grounds",
    "contest limitations": "will_contest_grounds",

    # creditor_claims_priority
    "creditor claims": "creditor_claims_priority",
    "creditor claim": "creditor_claims_priority",
    "claims against estate": "creditor_claims_priority",
    "estate claims": "creditor_claims_priority",
    "priority of claims": "creditor_claims_priority",
    "priority claims": "creditor_claims_priority",
    "claim priority": "creditor_claims_priority",
    "creditor priority": "creditor_claims_priority",
    "priority of creditor claims": "creditor_claims_priority",
    "creditor payment": "creditor_claims_priority",
    "creditor payments": "creditor_claims_priority",
    "payment of claims": "creditor_claims_priority",
    "payment of creditors": "creditor_claims_priority",
    "estate debts": "creditor_claims_priority",
    "estate debt": "creditor_claims_priority",
    "debts of estate": "creditor_claims_priority",
    "debt priority": "creditor_claims_priority",
    "debt claims": "creditor_claims_priority",
    "debt claim": "creditor_claims_priority",
    "debt payment": "creditor_claims_priority",
    "debt payments": "creditor_claims_priority",
    "order of payment": "creditor_claims_priority",
    "order of claims": "creditor_claims_priority",
    "order of creditors": "creditor_claims_priority",
    "estate obligations": "creditor_claims_priority",
    "estate obligation": "creditor_claims_priority",
    "obligations of estate": "creditor_claims_priority",
    "obligation priority": "creditor_claims_priority",
    "obligation claims": "creditor_claims_priority",
    "obligation claim": "creditor_claims_priority",
    "probate claims": "creditor_claims_priority",
    "probate claim": "creditor_claims_priority",
    "probate debts": "creditor_claims_priority",
    "probate debt": "creditor_claims_priority",
    "probate creditor": "creditor_claims_priority",
    "probate creditors": "creditor_claims_priority",
    "probate payment": "creditor_claims_priority",
    "probate payments": "creditor_claims_priority",
    "priority in probate": "creditor_claims_priority",
    "priority in estate": "creditor_claims_priority",
    "priority in administration": "creditor_claims_priority",
    "priority in distribution": "creditor_claims_priority",

    # elective_share_spousal_rights
    "elective share": "elective_share_spousal_rights",
    "spousal elective share": "elective_share_spousal_rights",
    "spouse elective share": "elective_share_spousal_rights",
    "right of election": "elective_share_spousal_rights",
    "right to elect": "elective_share_spousal_rights",
    "spousal right of election": "elective_share_spousal_rights",
    "spousal rights": "elective_share_spousal_rights",
    "spouse rights": "elective_share_spousal_rights",
    "spousal right": "elective_share_spousal_rights",
    "spouse right": "elective_share_spousal_rights",
    "spousal share": "elective_share_spousal_rights",
    "spouse share": "elective_share_spousal_rights",
    "elective share statute": "elective_share_spousal_rights",
    "elective share statutes": "elective_share_spousal_rights",
    "elective share law": "elective_share_spousal_rights",
    "elective share laws": "elective_share_spousal_rights",
    "elective share election": "elective_share_spousal_rights",
    "elective share period": "elective_share_spousal_rights",
    "elective share deadline": "elective_share_spousal_rights",
    "elective share time limit": "elective_share_spousal_rights",
    "elective share limitation": "elective_share_spousal_rights",
    "elective share limitations": "elective_share_spousal_rights",
    "spousal election": "elective_share_spousal_rights",
    "spouse election": "elective_share_spousal_rights",
    "spouse's election": "elective_share_spousal_rights",
    "spouse's right of election": "elective_share_spousal_rights",
    "spouse's elective share": "elective_share_spousal_rights",
    "spousal elective share rights": "elective_share_spousal_rights",
    "spousal elective rights": "elective_share_spousal_rights",
    "spousal election rights": "elective_share_spousal_rights",
    "forced share": "elective_share_spousal_rights",
    "forced heirship": "elective_share_spousal_rights",
    "forced share statute": "elective_share_spousal_rights",
    "forced share law": "elective_share_spousal_rights",
    "forced share election": "elective_share_spousal_rights",
    "marital share": "elective_share_spousal_rights",
    "marital rights": "elective_share_spousal_rights",
    "marital right": "elective_share_spousal_rights",
    "marital election": "elective_share_spousal_rights",
    "marital property rights": "elective_share_spousal_rights",
    "marital property right": "elective_share_spousal_rights",

    # executor_fiduciary_duties
    "executor duties": "executor_fiduciary_duties",
    "executrix duties": "executor_fiduciary_duties",
    "administrator duties": "executor_fiduciary_duties",
    "administratrix duties": "executor_fiduciary_duties",
    "personal representative duties": "executor_fiduciary_duties",
    "pr duties": "executor_fiduciary_duties",
    "fiduciary duties": "executor_fiduciary_duties",
    "executor fiduciary duties": "executor_fiduciary_duties",
    "fiduciary duty": "executor_fiduciary_duties",
    "executor duty": "executor_fiduciary_duties",
    "executrix duty": "executor_fiduciary_duties",
    "administrator duty": "executor_fiduciary_duties",
    "administratrix duty": "executor_fiduciary_duties",
    "personal representative duty": "executor_fiduciary_duties",
    "pr duty": "executor_fiduciary_duties",
    "executor obligations": "executor_fiduciary_duties",
    "executor obligation": "executor_fiduciary_duties",
    "executrix obligations": "executor_fiduciary_duties",
    "executrix obligation": "executor_fiduciary_duties",
    "administrator obligations": "executor_fiduciary_duties",
    "administrator obligation": "executor_fiduciary_duties",
    "administratrix obligations": "executor_fiduciary_duties",
    "administratrix obligation": "executor_fiduciary_duties",
    "personal representative obligations": "executor_fiduciary_duties",
    "personal representative obligation": "executor_fiduciary_duties",
    "pr obligations": "executor_fiduciary_duties",
    "pr obligation": "executor_fiduciary_duties",
    "executor responsibilities": "executor_fiduciary_duties",
    "executor responsibility": "executor_fiduciary_duties",
    "executrix responsibilities": "executor_fiduciary_duties",
    "executrix responsibility": "executor_fiduciary_duties",
    "administrator responsibilities": "executor_fiduciary_duties",
    "administrator responsibility": "executor_fiduciary_duties",
    "administratrix responsibilities": "executor_fiduciary_duties",
    "administratrix responsibility": "executor_fiduciary_duties",
    "personal representative responsibilities": "executor_fiduciary_duties",
    "personal representative responsibility": "executor_fiduciary_duties",
    "pr responsibilities": "executor_fiduciary_duties",
    "pr responsibility": "executor_fiduciary_duties",
    "executor standard of care": "executor_fiduciary_duties",
    "executor standard": "executor_fiduciary_duties",
    "executor care": "executor_fiduciary_duties",
    "executor loyalty": "executor_fiduciary_duties",
    "executor impartiality": "executor_fiduciary_duties",
    "executor accounting": "executor_fiduciary_duties",
    "executor account": "executor_fiduciary_duties",
    "executor report": "executor_fiduciary_duties",
    "executor reports": "executor_fiduciary_duties",
    "executor inventory": "executor_fiduciary_duties",
    "executor inventories": "executor_fiduciary_duties",
    "executor settlement": "executor_fiduciary_duties",
    "executor settlements": "executor_fiduciary_duties",
    "executor closing": "executor_fiduciary_duties",
    "executor close": "executor_fiduciary_duties",

    # pour_over_will_trust_integration
    "pour over will": "pour_over_will_trust_integration",
    "pour-over will": "pour_over_will_trust_integration",
    "pourover will": "pour_over_will_trust_integration",
    "pour over": "pour_over_will_trust_integration",
    "pour-over": "pour_over_will_trust_integration",
    "pourover": "pour_over_will_trust_integration",
    "pour over trust": "pour_over_will_trust_integration",
    "pour-over trust": "pour_over_will_trust_integration",
    "pourover trust": "pour_over_will_trust_integration",
    "pour over provision": "pour_over_will_trust_integration",
    "pour-over provision": "pour_over_will_trust_integration",
    "pourover provision": "pour_over_will_trust_integration",
    "pour over clause": "pour_over_will_trust_integration",
    "pour-over clause": "pour_over_will_trust_integration",
    "pourover clause": "pour_over_will_trust_integration",
    "pour over instrument": "pour_over_will_trust_integration",
    "pour-over instrument": "pour_over_will_trust_integration",
    "pourover instrument": "pour_over_will_trust_integration",
    "pour over will trust": "pour_over_will_trust_integration",
    "pour-over will trust": "pour_over_will_trust_integration",
    "pourover will trust": "pour_over_will_trust_integration",
    "will trust integration": "pour_over_will_trust_integration",
    "trust integration": "pour_over_will_trust_integration",
    "integration of will and trust": "pour_over_will_trust_integration",
    "integration of trust and will": "pour_over_will_trust_integration",
    "will and trust integration": "pour_over_will_trust_integration",
    "trust and will integration": "pour_over_will_trust_integration",
    "pour over integration": "pour_over_will_trust_integration",
    "pour-over integration": "pour_over_will_trust_integration",
    "pourover integration": "pour_over_will_trust_integration",

    # muniment_of_title
    "muniment of title": "muniment_of_title",
    "muniment": "muniment_of_title",
    "muniment probate": "muniment_of_title",
    "probate as muniment": "muniment_of_title",
    "probate as muniment of title": "muniment_of_title",
    "muniment proceeding": "muniment_of_title",
    "muniment proceedings": "muniment_of_title",
    "muniment application": "muniment_of_title",
    "muniment applications": "muniment_of_title",
    "muniment order": "muniment_of_title",
    "muniment orders": "muniment_of_title",
    "muniment judgment": "muniment_of_title",
    "muniment judgments": "muniment_of_title",
    "muniment affidavit": "muniment_of_title",
    "muniment affidavits": "muniment_of_title",
    "muniment of title probate": "muniment_of_title",
    "probate muniment": "muniment_of_title",
    "probate as muniment": "muniment_of_title",
    "title by muniment": "muniment_of_title",
    "title through muniment": "muniment_of_title",
    "title via muniment": "muniment_of_title",

    # ademption_abatement
    "ademption": "ademption_abatement",
    "ademption by extinction": "ademption_abatement",
    "ademption by satisfaction": "ademption_abatement",
    "abatement": "ademption_abatement",
    "abatement of legacy": "ademption_abatement",
    "abatement of legacies": "ademption_abatement",
    "abatement of devise": "ademption_abatement",
    "abatement of devises": "ademption_abatement",
    "adempt": "ademption_abatement",
    "adempted": "ademption_abatement",
    "adempting": "ademption_abatement",
    "abate": "ademption_abatement",
    "abated": "ademption_abatement",
    "abating": "ademption_abatement",
    "ademption and abatement": "ademption_abatement",
    "ademption/abatement": "ademption_abatement",
    "ademption & abatement": "ademption_abatement",
    "legacy abatement": "ademption_abatement",
    "devise abatement": "ademption_abatement",
    "legacy ademption": "ademption_abatement",
    "devise ademption": "ademption_abatement",
    "ademption of legacy": "ademption_abatement",
    "ademption of legacies": "ademption_abatement",
    "ademption of devise": "ademption_abatement",
    "ademption of devises": "ademption_abatement",

    # will_interpretation_intent
    "will interpretation": "will_interpretation_intent",
    "interpretation of will": "will_interpretation_intent",
    "will construction": "will_interpretation_intent",
    "construction of will": "will_interpretation_intent",
    "will intent": "will_interpretation_intent",
    "testator intent": "will_interpretation_intent",
    "testator's intent": "will_interpretation_intent",
    "testator intention": "will_interpretation_intent",
    "testator's intention": "will_interpretation_intent",
    "will meaning": "will_interpretation_intent",
    "meaning of will": "will_interpretation_intent",
    "will language": "will_interpretation_intent",
    "language of will": "will_interpretation_intent",
    "will ambiguity": "will_interpretation_intent",
    "ambiguity in will": "will_interpretation_intent",
    "ambiguous will": "will_interpretation_intent",
    "latent ambiguity": "will_interpretation_intent",
    "patent ambiguity": "will_interpretation_intent",
    "will interpretation rules": "will_interpretation_intent",
    "rules of will interpretation": "will_interpretation_intent",
    "rules of construction": "will_interpretation_intent",
    "construction rules": "will_interpretation_intent",
    "will construction rules": "will_interpretation_intent",
    "will construction principles": "will_interpretation_intent",
    "construction principles": "will_interpretation_intent",
    "will interpretation principles": "will_interpretation_intent",
    "interpretation principles": "will_interpretation_intent",
    "will interpretation statute": "will_interpretation_intent",
    "will interpretation statutes": "will_interpretation_intent",
    "will construction statute": "will_interpretation_intent",
    "will construction statutes": "will_interpretation_intent",

    # heirship_determination
    "heirship proceeding": "heirship_determination",
    "heirship proceedings": "heirship_determination",
    "determination of heirship": "heirship_determination",
    "heirship application": "heirship_determination",
    "heirship applications": "heirship_determination",
    "heirship affidavit": "heirship_determination",
    "heirship affidavits": "heirship_determination",
    "heirship suit": "heirship_determination",
    "heirship suits": "heirship_determination",
    "heirship order": "heirship_determination",
    "heirship orders": "heirship_determination",
    "heirship judgment": "heirship_determination",
    "heirship judgments": "heirship_determination",
    "proceeding to declare heirship": "heirship_determination",
    "proceedings to declare heirship": "heirship_determination",
    "application to declare heirship": "heirship_determination",
    "affidavit of heirship": "heirship_determination",
    "affidavits of heirship": "heirship_determination",
    "suit to declare heirship": "heirship_determination",
    "suits to declare heirship": "heirship_determination",
    "order declaring heirship": "heirship_determination",
    "orders declaring heirship": "heirship_determination",
    "judgment declaring heirship": "heirship_determination",
    "judgments declaring heirship": "heirship_determination",
    "declaration of heirship": "heirship_determination",
    "declarations of heirship": "heirship_determination",
    "heirship declaration": "heirship_determination",
    "heirship declarations": "heirship_determination",

    # anti_lapse_statute
    "anti-lapse": "anti_lapse_statute",
    "antilapse": "anti_lapse_statute",
    "anti lapse": "anti_lapse_statute",
    "anti-lapse statute": "anti_lapse_statute",
    "anti lapse statute": "anti_lapse_statute",
    "antilapse statute": "anti_lapse_statute",
    "anti-lapse law": "anti_lapse_statute",
    "anti lapse law": "anti_lapse_statute",
    "antilapse law": "anti_lapse_statute",
    "anti-lapse statutes": "anti_lapse_statute",
    "anti lapse statutes": "anti_lapse_statute",
    "antilapse statutes": "anti_lapse_statute",
    "anti-lapse provision": "anti_lapse_statute",
    "anti lapse provision": "anti_lapse_statute",
    "antilapse provision": "anti_lapse_statute",
    "anti-lapse provisions": "anti_lapse_statute",
    "anti lapse provisions": "anti_lapse_statute",
    "antilapse provisions": "anti_lapse_statute",
    "anti-lapse rule": "anti_lapse_statute",
    "anti lapse rule": "anti_lapse_statute",
    "antilapse rule": "anti_lapse_statute",
    "anti-lapse rules": "anti_lapse_statute",
    "anti lapse rules": "anti_lapse_statute",
    "antilapse rules": "anti_lapse_statute",
    "anti-lapse effect": "anti_lapse_statute",
    "anti lapse effect": "anti_lapse_statute",
    "antilapse effect": "anti_lapse_statute",
    "anti-lapse application": "anti_lapse_statute",
    "anti lapse application": "anti_lapse_statute",
    "antilapse application": "anti_lapse_statute",
    "anti-lapse applies": "anti_lapse_statute",
    "anti lapse applies": "anti_lapse_statute",
    "antilapse applies": "anti_lapse_statute",

    # small_estate_affidavit
    "small estate affidavit": "small_estate_affidavit",
    "small estate": "small_estate_affidavit",
    "small estates": "small_estate_affidavit",
    "small estate application": "small_estate_affidavit",
    "small estate applications": "small_estate_affidavit",
    "small estate order": "small_estate_affidavit",
    "small estate orders": "small_estate_affidavit",
    "small estate judgment": "small_estate_affidavit",
    "small estate judgments": "small_estate_affidavit",
    "small estate proceeding": "small_estate_affidavit",
    "small estate proceedings": "small_estate_affidavit",
    "small estate affidavit probate": "small_estate_affidavit",
    "probate by small estate affidavit": "small_estate_affidavit",
    "small estate probate": "small_estate_affidavit",
    "affidavit of small estate": "small_estate_affidavit",
    "affidavits of small estate": "small_estate_affidavit",
    "small estate declaration": "small_estate_affidavit",
    "small estate declarations": "small_estate_affidavit",
    "small estate process": "small_estate_affidavit",
    "small estate processes": "small_estate_affidavit",
    "small estate procedure": "small_estate_affidavit",
    "small estate procedures": "small_estate_affidavit",
    "small estate law": "small_estate_affidavit",
    "small estate laws": "small_estate_affidavit",
    "small estate statute": "small_estate_affidavit",
    "small estate statutes": "small_estate_affidavit",
    "small estate affidavit law": "small_estate_affidavit",
    "small estate affidavit laws": "small_estate_affidavit",
    "small estate affidavit statute": "small_estate_affidavit",
    "small estate affidavit statutes": "small_estate_affidavit",
}

_EXPECTED_ENTRY_COUNT = 401

def _normalize_key(term):
    if not isinstance(term, str):
        return ""
    term = term.strip().lower()
    term = unicodedata.normalize("NFKC", term)
    term = " ".join(term.split())
    return term

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    hasher = hashlib.sha256()
    for k, v in items:
        norm_k = _normalize_key(k)
        norm_v = _normalize_key(v)
        hasher.update(norm_k.encode("utf-8"))
        hasher.update(norm_v.encode("utf-8"))
    return hasher.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid
    }

def normalize_term(term):
    norm = _normalize_key(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term):
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings():
    return dict(SEMANTIC_MAP)