import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PRB04 Semantic Team"
SEMANTIC_MAP_ENGINE = "PRB04_will_contest"

SEMANTIC_MAP = {
    # testamentary_capacity_standard
    "testamentary capacity": "testamentary_capacity_standard",
    "capacity to make will": "testamentary_capacity_standard",
    "mental capacity": "testamentary_capacity_standard",
    "sound mind": "testamentary_capacity_standard",
    "testamentary competence": "testamentary_capacity_standard",
    "testamentary incapacity": "testamentary_capacity_standard",
    "lack of capacity": "testamentary_capacity_standard",
    "incapacity": "testamentary_capacity_standard",
    "testamentary standard": "testamentary_capacity_standard",
    "tc standard": "testamentary_capacity_standard",
    "testamentary cap": "testamentary_capacity_standard",
    "testamentary_cap": "testamentary_capacity_standard",
    "testamentarycap": "testamentary_capacity_standard",
    "testamentary-capacity": "testamentary_capacity_standard",
    "testamentarycapacity": "testamentary_capacity_standard",
    "testamentary capacity standard": "testamentary_capacity_standard",
    "testamentary-capacity standard": "testamentary_capacity_standard",
    "testamentary capacity std": "testamentary_capacity_standard",
    "testamentary std": "testamentary_capacity_standard",
    "testamentary standard of capacity": "testamentary_capacity_standard",
    "capacity std": "testamentary_capacity_standard",
    "testamentary cap std": "testamentary_capacity_standard",
    "testamentary cap standard": "testamentary_capacity_standard",
    "testamentary capacity requirement": "testamentary_capacity_standard",
    "requirement of capacity": "testamentary_capacity_standard",
    "capacity requirement": "testamentary_capacity_standard",
    "testamentary capacity req": "testamentary_capacity_standard",
    "testamentary req": "testamentary_capacity_standard",
    "testamentary-capacity req": "testamentary_capacity_standard",
    "testamentary capacity requirements": "testamentary_capacity_standard",
    "capacity to execute will": "testamentary_capacity_standard",
    "testamentary ability": "testamentary_capacity_standard",
    "testamentary ability to make will": "testamentary_capacity_standard",
    "testamentary-capacity requirement": "testamentary_capacity_standard",
    "testamentary-capacity requirements": "testamentary_capacity_standard",
    "testamentary capacity test": "testamentary_capacity_standard",
    "testamentary test": "testamentary_capacity_standard",
    "testamentary capacity elements": "testamentary_capacity_standard",
    "elements of testamentary capacity": "testamentary_capacity_standard",
    "testamentary capacity elements": "testamentary_capacity_standard",
    "elements of capacity": "testamentary_capacity_standard",
    "testamentary capacity factors": "testamentary_capacity_standard",
    "testamentary factors": "testamentary_capacity_standard",
    "capacity factors": "testamentary_capacity_standard",
    "testamentary capacity doctrine": "testamentary_capacity_standard",
    "testamentary doctrine": "testamentary_capacity_standard",
    "capacity doctrine": "testamentary_capacity_standard",
    # undue_influence_standard
    "undue influence": "undue_influence_standard",
    "ui": "undue_influence_standard",
    "undue infl": "undue_influence_standard",
    "undue-influence": "undue_influence_standard",
    "undueinfl": "undue_influence_standard",
    "undue influence standard": "undue_influence_standard",
    "undue-influence standard": "undue_influence_standard",
    "undue influence std": "undue_influence_standard",
    "ui standard": "undue_influence_standard",
    "ui std": "undue_influence_standard",
    "undue influence doctrine": "undue_influence_standard",
    "undue influence presumption": "undue_influence_standard",
    "presumption of undue influence": "undue_influence_standard",
    "undue influence elements": "undue_influence_standard",
    "elements of undue influence": "undue_influence_standard",
    "undue influence test": "undue_influence_standard",
    "test for undue influence": "undue_influence_standard",
    "undue influence factors": "undue_influence_standard",
    "factors of undue influence": "undue_influence_standard",
    "ui factors": "undue_influence_standard",
    "ui elements": "undue_influence_standard",
    "ui test": "undue_influence_standard",
    "undue influence requirement": "undue_influence_standard",
    "requirement of undue influence": "undue_influence_standard",
    "undue influence requirements": "undue_influence_standard",
    "ui requirement": "undue_influence_standard",
    "ui requirements": "undue_influence_standard",
    "undue influence proof": "undue_influence_standard",
    "proof of undue influence": "undue_influence_standard",
    "undue influence evidence": "undue_influence_standard",
    "evidence of undue influence": "undue_influence_standard",
    # fraud_in_execution
    "fraud in execution": "fraud_in_execution",
    "fraud in the execution": "fraud_in_execution",
    "fraudulent execution": "fraud_in_execution",
    "fraudulent will execution": "fraud_in_execution",
    "fraud execution": "fraud_in_execution",
    "fraudulent execution of will": "fraud_in_execution",
    "fraud in will execution": "fraud_in_execution",
    "fraud in ex": "fraud_in_execution",
    "fraud ex": "fraud_in_execution",
    "fraud-execution": "fraud_in_execution",
    "fraud in execution of will": "fraud_in_execution",
    "fraud in the execution of will": "fraud_in_execution",
    "fraud in execution std": "fraud_in_execution",
    "fraud in execution standard": "fraud_in_execution",
    "fraud in execution elements": "fraud_in_execution",
    "elements of fraud in execution": "fraud_in_execution",
    "fraud in execution test": "fraud_in_execution",
    "test for fraud in execution": "fraud_in_execution",
    "fraud in execution factors": "fraud_in_execution",
    "factors of fraud in execution": "fraud_in_execution",
    "fraud in execution doctrine": "fraud_in_execution",
    "fraud in execution proof": "fraud_in_execution",
    "proof of fraud in execution": "fraud_in_execution",
    "fraud in execution evidence": "fraud_in_execution",
    "evidence of fraud in execution": "fraud_in_execution",
    # improper_execution_formalities
    "improper execution": "improper_execution_formalities",
    "improper execution of will": "improper_execution_formalities",
    "improper will execution": "improper_execution_formalities",
    "improper formalities": "improper_execution_formalities",
    "execution formalities": "improper_execution_formalities",
    "execution requirements": "improper_execution_formalities",
    "formalities": "improper_execution_formalities",
    "execution of will": "improper_execution_formalities",
    "will execution": "improper_execution_formalities",
    "will formalities": "improper_execution_formalities",
    "formal execution": "improper_execution_formalities",
    "failure of formalities": "improper_execution_formalities",
    "failure to comply with formalities": "improper_execution_formalities",
    "failure of execution": "improper_execution_formalities",
    "failure to execute properly": "improper_execution_formalities",
    "improper execution std": "improper_execution_formalities",
    "improper execution standard": "improper_execution_formalities",
    "improper execution elements": "improper_execution_formalities",
    "elements of improper execution": "improper_execution_formalities",
    "improper execution test": "improper_execution_formalities",
    "test for improper execution": "improper_execution_formalities",
    "improper execution factors": "improper_execution_formalities",
    "factors of improper execution": "improper_execution_formalities",
    "improper execution doctrine": "improper_execution_formalities",
    "improper execution proof": "improper_execution_formalities",
    "proof of improper execution": "improper_execution_formalities",
    "improper execution evidence": "improper_execution_formalities",
    "evidence of improper execution": "improper_execution_formalities",
    "improper execution req": "improper_execution_formalities",
    "improper execution requirements": "improper_execution_formalities",
    "improper execution requirement": "improper_execution_formalities",
    # revocation_express_implied
    "revocation": "revocation_express_implied",
    "express revocation": "revocation_express_implied",
    "implied revocation": "revocation_express_implied",
    "revocation of will": "revocation_express_implied",
    "revoke will": "revocation_express_implied",
    "revoking will": "revocation_express_implied",
    "will revocation": "revocation_express_implied",
    "express and implied revocation": "revocation_express_implied",
    "express/implied revocation": "revocation_express_implied",
    "revocation express": "revocation_express_implied",
    "revocation implied": "revocation_express_implied",
    "express or implied revocation": "revocation_express_implied",
    "revocation std": "revocation_express_implied",
    "revocation standard": "revocation_express_implied",
    "revocation elements": "revocation_express_implied",
    "elements of revocation": "revocation_express_implied",
    "revocation test": "revocation_express_implied",
    "test for revocation": "revocation_express_implied",
    "revocation factors": "revocation_express_implied",
    "factors of revocation": "revocation_express_implied",
    "revocation doctrine": "revocation_express_implied",
    "revocation proof": "revocation_express_implied",
    "proof of revocation": "revocation_express_implied",
    "revocation evidence": "revocation_express_implied",
    "evidence of revocation": "revocation_express_implied",
    "revocation req": "revocation_express_implied",
    "revocation requirements": "revocation_express_implied",
    "revocation requirement": "revocation_express_implied",
    # holographic_will_validity
    "holographic will": "holographic_will_validity",
    "holographic": "holographic_will_validity",
    "holograph": "holographic_will_validity",
    "holographic will validity": "holographic_will_validity",
    "holographic validity": "holographic_will_validity",
    "holographic will std": "holographic_will_validity",
    "holographic will standard": "holographic_will_validity",
    "holographic will elements": "holographic_will_validity",
    "elements of holographic will": "holographic_will_validity",
    "holographic will test": "holographic_will_validity",
    "test for holographic will": "holographic_will_validity",
    "holographic will factors": "holographic_will_validity",
    "factors of holographic will": "holographic_will_validity",
    "holographic will doctrine": "holographic_will_validity",
    "holographic will proof": "holographic_will_validity",
    "proof of holographic will": "holographic_will_validity",
    "holographic will evidence": "holographic_will_validity",
    "evidence of holographic will": "holographic_will_validity",
    "holographic will req": "holographic_will_validity",
    "holographic will requirements": "holographic_will_validity",
    "holographic will requirement": "holographic_will_validity",
    "handwritten will": "holographic_will_validity",
    "handwritten": "holographic_will_validity",
    "hand written will": "holographic_will_validity",
    "hand-written will": "holographic_will_validity",
    "holographic-will": "holographic_will_validity",
    "holographic_will": "holographic_will_validity",
    "holographicwill": "holographic_will_validity",
    # no_contest_clause_enforceability
    "no contest clause": "no_contest_clause_enforceability",
    "no-contest clause": "no_contest_clause_enforceability",
    "nocontest clause": "no_contest_clause_enforceability",
    "no contest": "no_contest_clause_enforceability",
    "no-contest": "no_contest_clause_enforceability",
    "nocontest": "no_contest_clause_enforceability",
    "in terrorem clause": "no_contest_clause_enforceability",
    "interrorem clause": "no_contest_clause_enforceability",
    "in terrorem": "no_contest_clause_enforceability",
    "interrorem": "no_contest_clause_enforceability",
    "forfeiture clause": "no_contest_clause_enforceability",
    "no contest clause enforceability": "no_contest_clause_enforceability",
    "no contest clause validity": "no_contest_clause_enforceability",
    "no contest clause std": "no_contest_clause_enforceability",
    "no contest clause standard": "no_contest_clause_enforceability",
    "no contest clause elements": "no_contest_clause_enforceability",
    "elements of no contest clause": "no_contest_clause_enforceability",
    "no contest clause test": "no_contest_clause_enforceability",
    "test for no contest clause": "no_contest_clause_enforceability",
    "no contest clause factors": "no_contest_clause_enforceability",
    "factors of no contest clause": "no_contest_clause_enforceability",
    "no contest clause doctrine": "no_contest_clause_enforceability",
    "no contest clause proof": "no_contest_clause_enforceability",
    "proof of no contest clause": "no_contest_clause_enforceability",
    "no contest clause evidence": "no_contest_clause_enforceability",
    "evidence of no contest clause": "no_contest_clause_enforceability",
    "no contest clause req": "no_contest_clause_enforceability",
    "no contest clause requirements": "no_contest_clause_enforceability",
    "no contest clause requirement": "no_contest_clause_enforceability",
    # tortious_interference_with_inheritance
    "tortious interference": "tortious_interference_with_inheritance",
    "tortious interference with inheritance": "tortious_interference_with_inheritance",
    "tortious interference with expectancy": "tortious_interference_with_inheritance",
    "tortious interference with will": "tortious_interference_with_inheritance",
    "tortious interference with bequest": "tortious_interference_with_inheritance",
    "tortious interference with gift": "tortious_interference_with_inheritance",
    "tortious interference with succession": "tortious_interference_with_inheritance",
    "tortious interference with estate": "tortious_interference_with_inheritance",
    "tortious interference std": "tortious_interference_with_inheritance",
    "tortious interference standard": "tortious_interference_with_inheritance",
    "tortious interference elements": "tortious_interference_with_inheritance",
    "elements of tortious interference": "tortious_interference_with_inheritance",
    "tortious interference test": "tortious_interference_with_inheritance",
    "test for tortious interference": "tortious_interference_with_inheritance",
    "tortious interference factors": "tortious_interference_with_inheritance",
    "factors of tortious interference": "tortious_interference_with_inheritance",
    "tortious interference doctrine": "tortious_interference_with_inheritance",
    "tortious interference proof": "tortious_interference_with_inheritance",
    "proof of tortious interference": "tortious_interference_with_inheritance",
    "tortious interference evidence": "tortious_interference_with_inheritance",
    "evidence of tortious interference": "tortious_interference_with_inheritance",
    "tortious interference req": "tortious_interference_with_inheritance",
    "tortious interference requirements": "tortious_interference_with_inheritance",
    "tortious interference requirement": "tortious_interference_with_inheritance",
    "tortious interference with inheritance std": "tortious_interference_with_inheritance",
    "tortious interference with inheritance standard": "tortious_interference_with_inheritance",
    "tortious interference with inheritance elements": "tortious_interference_with_inheritance",
    "tortious interference with inheritance test": "tortious_interference_with_inheritance",
    "tortious interference with inheritance factors": "tortious_interference_with_inheritance",
    "tortious interference with inheritance doctrine": "tortious_interference_with_inheritance",
    "tortious interference with inheritance proof": "tortious_interference_with_inheritance",
    "tortious interference with inheritance evidence": "tortious_interference_with_inheritance",
    "tortious interference with inheritance req": "tortious_interference_with_inheritance",
    "tortious interference with inheritance requirements": "tortious_interference_with_inheritance",
    "tortious interference with inheritance requirement": "tortious_interference_with_inheritance",
    "tortious interference with expectancy std": "tortious_interference_with_inheritance",
    "tortious interference with expectancy standard": "tortious_interference_with_inheritance",
    "tortious interference with expectancy elements": "tortious_interference_with_inheritance",
    "tortious interference with expectancy test": "tortious_interference_with_inheritance",
    "tortious interference with expectancy factors": "tortious_interference_with_inheritance",
    "tortious interference with expectancy doctrine": "tortious_interference_with_inheritance",
    "tortious interference with expectancy proof": "tortious_interference_with_inheritance",
    "tortious interference with expectancy evidence": "tortious_interference_with_inheritance",
    "tortious interference with expectancy req": "tortious_interference_with_inheritance",
    "tortious interference with expectancy requirements": "tortious_interference_with_inheritance",
    "tortious interference with expectancy requirement": "tortious_interference_with_inheritance",
    # burden_of_proof_allocation
    "burden of proof": "burden_of_proof_allocation",
    "burden": "burden_of_proof_allocation",
    "proof burden": "burden_of_proof_allocation",
    "allocation of burden": "burden_of_proof_allocation",
    "allocation of proof": "burden_of_proof_allocation",
    "burden allocation": "burden_of_proof_allocation",
    "burden of proof allocation": "burden_of_proof_allocation",
    "burden allocation of proof": "burden_of_proof_allocation",
    "proof allocation": "burden_of_proof_allocation",
    "burden of proof std": "burden_of_proof_allocation",
    "burden of proof standard": "burden_of_proof_allocation",
    "burden of proof elements": "burden_of_proof_allocation",
    "elements of burden of proof": "burden_of_proof_allocation",
    "burden of proof test": "burden_of_proof_allocation",
    "test for burden of proof": "burden_of_proof_allocation",
    "burden of proof factors": "burden_of_proof_allocation",
    "factors of burden of proof": "burden_of_proof_allocation",
    "burden of proof doctrine": "burden_of_proof_allocation",
    "burden of proof proof": "burden_of_proof_allocation",
    "proof of burden of proof": "burden_of_proof_allocation",
    "burden of proof evidence": "burden_of_proof_allocation",
    "evidence of burden of proof": "burden_of_proof_allocation",
    "burden of proof req": "burden_of_proof_allocation",
    "burden of proof requirements": "burden_of_proof_allocation",
    "burden of proof requirement": "burden_of_proof_allocation",
    # interested_witness_rule
    "interested witness": "interested_witness_rule",
    "interested witness rule": "interested_witness_rule",
    "interested witness doctrine": "interested_witness_rule",
    "interested witness std": "interested_witness_rule",
    "interested witness standard": "interested_witness_rule",
    "interested witness elements": "interested_witness_rule",
    "elements of interested witness": "interested_witness_rule",
    "interested witness test": "interested_witness_rule",
    "test for interested witness": "interested_witness_rule",
    "interested witness factors": "interested_witness_rule",
    "factors of interested witness": "interested_witness_rule",
    "interested witness proof": "interested_witness_rule",
    "proof of interested witness": "interested_witness_rule",
    "interested witness evidence": "interested_witness_rule",
    "evidence of interested witness": "interested_witness_rule",
    "interested witness req": "interested_witness_rule",
    "interested witness requirements": "interested_witness_rule",
    "interested witness requirement": "interested_witness_rule",
    "witness with interest": "interested_witness_rule",
    "witness interest": "interested_witness_rule",
    "witness interested": "interested_witness_rule",
    # dependent_relative_revocation
    "dependent relative revocation": "dependent_relative_revocation",
    "dependent-relative revocation": "dependent_relative_revocation",
    "dependent relative revocation doctrine": "dependent_relative_revocation",
    "dependent relative revocation rule": "dependent_relative_revocation",
    "dependent relative revocation std": "dependent_relative_revocation",
    "dependent relative revocation standard": "dependent_relative_revocation",
    "dependent relative revocation elements": "dependent_relative_revocation",
    "elements of dependent relative revocation": "dependent_relative_revocation",
    "dependent relative revocation test": "dependent_relative_revocation",
    "test for dependent relative revocation": "dependent_relative_revocation",
    "dependent relative revocation factors": "dependent_relative_revocation",
    "factors of dependent relative revocation": "dependent_relative_revocation",
    "dependent relative revocation proof": "dependent_relative_revocation",
    "proof of dependent relative revocation": "dependent_relative_revocation",
    "dependent relative revocation evidence": "dependent_relative_revocation",
    "evidence of dependent relative revocation": "dependent_relative_revocation",
    "dependent relative revocation req": "dependent_relative_revocation",
    "dependent relative revocation requirements": "dependent_relative_revocation",
    "dependent relative revocation requirement": "dependent_relative_revocation",
    "dr revocation": "dependent_relative_revocation",
    "dr revocation doctrine": "dependent_relative_revocation",
    "dr revocation rule": "dependent_relative_revocation",
    # integration_incorporation_by_reference
    "integration": "integration_incorporation_by_reference",
    "incorporation by reference": "integration_incorporation_by_reference",
    "integration doctrine": "integration_incorporation_by_reference",
    "incorporation doctrine": "integration_incorporation_by_reference",
    "integration by reference": "integration_incorporation_by_reference",
    "integration std": "integration_incorporation_by_reference",
    "integration standard": "integration_incorporation_by_reference",
    "integration elements": "integration_incorporation_by_reference",
    "elements of integration": "integration_incorporation_by_reference",
    "integration test": "integration_incorporation_by_reference",
    "test for integration": "integration_incorporation_by_reference",
    "integration factors": "integration_incorporation_by_reference",
    "factors of integration": "integration_incorporation_by_reference",
    "integration proof": "integration_incorporation_by_reference",
    "proof of integration": "integration_incorporation_by_reference",
    "integration evidence": "integration_incorporation_by_reference",
    "evidence of integration": "integration_incorporation_by_reference",
    "integration req": "integration_incorporation_by_reference",
    "integration requirements": "integration_incorporation_by_reference",
    "integration requirement": "integration_incorporation_by_reference",
    "incorporation": "integration_incorporation_by_reference",
    "incorporation by ref": "integration_incorporation_by_reference",
    "incorporation by reference doctrine": "integration_incorporation_by_reference",
    "incorporation by reference std": "integration_incorporation_by_reference",
    "incorporation by reference standard": "integration_incorporation_by_reference",
    "incorporation by reference elements": "integration_incorporation_by_reference",
    "incorporation by reference test": "integration_incorporation_by_reference",
    "incorporation by reference factors": "integration_incorporation_by_reference",
    "incorporation by reference proof": "integration_incorporation_by_reference",
    "incorporation by reference evidence": "integration_incorporation_by_reference",
    "incorporation by reference req": "integration_incorporation_by_reference",
    "incorporation by reference requirements": "integration_incorporation_by_reference",
    "incorporation by reference requirement": "integration_incorporation_by_reference",
    # class_gifts_and_lapse
    "class gifts": "class_gifts_and_lapse",
    "class gift": "class_gifts_and_lapse",
    "class gifts and lapse": "class_gifts_and_lapse",
    "class gifts & lapse": "class_gifts_and_lapse",
    "class gifts lapse": "class_gifts_and_lapse",
    "lapse": "class_gifts_and_lapse",
    "lapse of gift": "class_gifts_and_lapse",
    "lapse of class gift": "class_gifts_and_lapse",
    "lapse doctrine": "class_gifts_and_lapse",
    "anti-lapse": "class_gifts_and_lapse",
    "antilapse": "class_gifts_and_lapse",
    "anti lapse": "class_gifts_and_lapse",
    "anti-lapse statute": "class_gifts_and_lapse",
    "anti-lapse doctrine": "class_gifts_and_lapse",
    "antilapse statute": "class_gifts_and_lapse",
    "antilapse doctrine": "class_gifts_and_lapse",
    "class gifts doctrine": "class_gifts_and_lapse",
    "class gifts std": "class_gifts_and_lapse",
    "class gifts standard": "class_gifts_and_lapse",
    "class gifts elements": "class_gifts_and_lapse",
    "elements of class gifts": "class_gifts_and_lapse",
    "class gifts test": "class_gifts_and_lapse",
    "test for class gifts": "class_gifts_and_lapse",
    "class gifts factors": "class_gifts_and_lapse",
    "factors of class gifts": "class_gifts_and_lapse",
    "class gifts proof": "class_gifts_and_lapse",
    "proof of class gifts": "class_gifts_and_lapse",
    "class gifts evidence": "class_gifts_and_lapse",
    "evidence of class gifts": "class_gifts_and_lapse",
    "class gifts req": "class_gifts_and_lapse",
    "class gifts requirements": "class_gifts_and_lapse",
    "class gifts requirement": "class_gifts_and_lapse",
    # ademption_by_extinction
    "ademption": "ademption_by_extinction",
    "ademption by extinction": "ademption_by_extinction",
    "ademption doctrine": "ademption_by_extinction",
    "ademption by extinction doctrine": "ademption_by_extinction",
    "ademption std": "ademption_by_extinction",
    "ademption standard": "ademption_by_extinction",
    "ademption elements": "ademption_by_extinction",
    "elements of ademption": "ademption_by_extinction",
    "ademption test": "ademption_by_extinction",
    "test for ademption": "ademption_by_extinction",
    "ademption factors": "ademption_by_extinction",
    "factors of ademption": "ademption_by_extinction",
    "ademption proof": "ademption_by_extinction",
    "proof of ademption": "ademption_by_extinction",
    "ademption evidence": "ademption_by_extinction",
    "evidence of ademption": "ademption_by_extinction",
    "ademption req": "ademption_by_extinction",
    "ademption requirements": "ademption_by_extinction",
    "ademption requirement": "ademption_by_extinction",
    # abatement_order
    "abatement": "abatement_order",
    "abatement order": "abatement_order",
    "order of abatement": "abatement_order",
    "abatement doctrine": "abatement_order",
    "abatement std": "abatement_order",
    "abatement standard": "abatement_order",
    "abatement elements": "abatement_order",
    "elements of abatement": "abatement_order",
    "abatement test": "abatement_order",
    "test for abatement": "abatement_order",
    "abatement factors": "abatement_order",
    "factors of abatement": "abatement_order",
    "abatement proof": "abatement_order",
    "proof of abatement": "abatement_order",
    "abatement evidence": "abatement_order",
    "evidence of abatement": "abatement_order",
    "abatement req": "abatement_order",
    "abatement requirements": "abatement_order",
    "abatement requirement": "abatement_order",
    # advancements_and_satisfaction
    "advancement": "advancements_and_satisfaction",
    "advancements": "advancements_and_satisfaction",
    "satisfaction": "advancements_and_satisfaction",
    "advancement doctrine": "advancements_and_satisfaction",
    "advancements doctrine": "advancements_and_satisfaction",
    "satisfaction doctrine": "advancements_and_satisfaction",
    "advancement std": "advancements_and_satisfaction",
    "advancements std": "advancements_and_satisfaction",
    "satisfaction std": "advancements_and_satisfaction",
    "advancement standard": "advancements_and_satisfaction",
    "advancements standard": "advancements_and_satisfaction",
    "satisfaction standard": "advancements_and_satisfaction",
    "advancement elements": "advancements_and_satisfaction",
    "advancements elements": "advancements_and_satisfaction",
    "satisfaction elements": "advancements_and_satisfaction",
    "elements of advancement": "advancements_and_satisfaction",
    "elements of advancements": "advancements_and_satisfaction",
    "elements of satisfaction": "advancements_and_satisfaction",
    "advancement test": "advancements_and_satisfaction",
    "advancements test": "advancements_and_satisfaction",
    "satisfaction test": "advancements_and_satisfaction",
    "test for advancement": "advancements_and_satisfaction",
    "test for advancements": "advancements_and_satisfaction",
    "test for satisfaction": "advancements_and_satisfaction",
    "advancement factors": "advancements_and_satisfaction",
    "advancements factors": "advancements_and_satisfaction",
    "satisfaction factors": "advancements_and_satisfaction",
    "factors of advancement": "advancements_and_satisfaction",
    "factors of advancements": "advancements_and_satisfaction",
    "factors of satisfaction": "advancements_and_satisfaction",
    "advancement proof": "advancements_and_satisfaction",
    "advancements proof": "advancements_and_satisfaction",
    "satisfaction proof": "advancements_and_satisfaction",
    "proof of advancement": "advancements_and_satisfaction",
    "proof of advancements": "advancements_and_satisfaction",
    "proof of satisfaction": "advancements_and_satisfaction",
    "advancement evidence": "advancements_and_satisfaction",
    "advancements evidence": "advancements_and_satisfaction",
    "satisfaction evidence": "advancements_and_satisfaction",
    "evidence of advancement": "advancements_and_satisfaction",
    "evidence of advancements": "advancements_and_satisfaction",
    "evidence of satisfaction": "advancements_and_satisfaction",
    "advancement req": "advancements_and_satisfaction",
    "advancements req": "advancements_and_satisfaction",
    "satisfaction req": "advancements_and_satisfaction",
    "advancement requirements": "advancements_and_satisfaction",
    "advancements requirements": "advancements_and_satisfaction",
    "satisfaction requirements": "advancements_and_satisfaction",
    "advancement requirement": "advancements_and_satisfaction",
    "advancements requirement": "advancements_and_satisfaction",
    "satisfaction requirement": "advancements_and_satisfaction",
    # elective_share_and_community_property
    "elective share": "elective_share_and_community_property",
    "elective share doctrine": "elective_share_and_community_property",
    "elective share std": "elective_share_and_community_property",
    "elective share standard": "elective_share_and_community_property",
    "elective share elements": "elective_share_and_community_property",
    "elements of elective share": "elective_share_and_community_property",
    "elective share test": "elective_share_and_community_property",
    "test for elective share": "elective_share_and_community_property",
    "elective share factors": "elective_share_and_community_property",
    "factors of elective share": "elective_share_and_community_property",
    "elective share proof": "elective_share_and_community_property",
    "proof of elective share": "elective_share_and_community_property",
    "elective share evidence": "elective_share_and_community_property",
    "evidence of elective share": "elective_share_and_community_property",
    "elective share req": "elective_share_and_community_property",
    "elective share requirements": "elective_share_and_community_property",
    "elective share requirement": "elective_share_and_community_property",
    "community property": "elective_share_and_community_property",
    "community property doctrine": "elective_share_and_community_property",
    "community property std": "elective_share_and_community_property",
    "community property standard": "elective_share_and_community_property",
    "community property elements": "elective_share_and_community_property",
    "elements of community property": "elective_share_and_community_property",
    "community property test": "elective_share_and_community_property",
    "test for community property": "elective_share_and_community_property",
    "community property factors": "elective_share_and_community_property",
    "factors of community property": "elective_share_and_community_property",
    "community property proof": "elective_share_and_community_property",
    "proof of community property": "elective_share_and_community_property",
    "community property evidence": "elective_share_and_community_property",
    "evidence of community property": "elective_share_and_community_property",
    "community property req": "elective_share_and_community_property",
    "community property requirements": "elective_share_and_community_property",
    "community property requirement": "elective_share_and_community_property",
    # standing_to_contest
    "standing": "standing_to_contest",
    "standing to contest": "standing_to_contest",
    "standing doctrine": "standing_to_contest",
    "standing std": "standing_to_contest",
    "standing standard": "standing_to_contest",
    "standing elements": "standing_to_contest",
    "elements of standing": "standing_to_contest",
    "standing test": "standing_to_contest",
    "test for standing": "standing_to_contest",
    "standing factors": "standing_to_contest",
    "factors of standing": "standing_to_contest",
    "standing proof": "standing_to_contest",
    "proof of standing": "standing_to_contest",
    "standing evidence": "standing_to_contest",
    "evidence of standing": "standing_to_contest",
    "standing req": "standing_to_contest",
    "standing requirements": "standing_to_contest",
    "standing requirement": "standing_to_contest",
    # venue_and_jurisdiction
    "venue": "venue_and_jurisdiction",
    "jurisdiction": "venue_and_jurisdiction",
    "venue and jurisdiction": "venue_and_jurisdiction",
    "venue jurisdiction": "venue_and_jurisdiction",
    "venue doctrine": "venue_and_jurisdiction",
    "jurisdiction doctrine": "venue_and_jurisdiction",
    "venue std": "venue_and_jurisdiction",
    "jurisdiction std": "venue_and_jurisdiction",
    "venue standard": "venue_and_jurisdiction",
    "jurisdiction standard": "venue_and_jurisdiction",
    "venue elements": "venue_and_jurisdiction",
    "jurisdiction elements": "venue_and_jurisdiction",
    "elements of venue": "venue_and_jurisdiction",
    "elements of jurisdiction": "venue_and_jurisdiction",
    "venue test": "venue_and_jurisdiction",
    "jurisdiction test": "venue_and_jurisdiction",
    "test for venue": "venue_and_jurisdiction",
    "test for jurisdiction": "venue_and_jurisdiction",
    "venue factors": "venue_and_jurisdiction",
    "jurisdiction factors": "venue_and_jurisdiction",
    "factors of venue": "venue_and_jurisdiction",
    "factors of jurisdiction": "venue_and_jurisdiction",
    "venue proof": "venue_and_jurisdiction",
    "jurisdiction proof": "venue_and_jurisdiction",
    "proof of venue": "venue_and_jurisdiction",
    "proof of jurisdiction": "venue_and_jurisdiction",
    "venue evidence": "venue_and_jurisdiction",
    "jurisdiction evidence": "venue_and_jurisdiction",
    "evidence of venue": "venue_and_jurisdiction",
    "evidence of jurisdiction": "venue_and_jurisdiction",
    "venue req": "venue_and_jurisdiction",
    "jurisdiction req": "venue_and_jurisdiction",
    "venue requirements": "venue_and_jurisdiction",
    "jurisdiction requirements": "venue_and_jurisdiction",
    "venue requirement": "venue_and_jurisdiction",
    "jurisdiction requirement": "venue_and_jurisdiction",
    # statute_of_limitations
    "statute of limitations": "statute_of_limitations",
    "statute of limitation": "statute_of_limitations",
    "statute limitations": "statute_of_limitations",
    "statute limitation": "statute_of_limitations",
    "limitations period": "statute_of_limitations",
    "limitation period": "statute_of_limitations",
    "sol": "statute_of_limitations",
    "statute of limitations doctrine": "statute_of_limitations",
    "statute of limitations std": "statute_of_limitations",
    "statute of limitations standard": "statute_of_limitations",
    "statute of limitations elements": "statute_of_limitations",
    "elements of statute of limitations": "statute_of_limitations",
    "statute of limitations test": "statute_of_limitations",
    "test for statute of limitations": "statute_of_limitations",
    "statute of limitations factors": "statute_of_limitations",
    "factors of statute of limitations": "statute_of_limitations",
    "statute of limitations proof": "statute_of_limitations",
    "proof of statute of limitations": "statute_of_limitations",
    "statute of limitations evidence": "statute_of_limitations",
    "evidence of statute of limitations": "statute_of_limitations",
    "statute of limitations req": "statute_of_limitations",
    "statute of limitations requirements": "statute_of_limitations",
    "statute of limitations requirement": "statute_of_limitations",
    # harmless_error_doctrine
    "harmless error": "harmless_error_doctrine",
    "harmless error doctrine": "harmless_error_doctrine",
    "harmless error std": "harmless_error_doctrine",
    "harmless error standard": "harmless_error_doctrine",
    "harmless error elements": "harmless_error_doctrine",
    "elements of harmless error": "harmless_error_doctrine",
    "harmless error test": "harmless_error_doctrine",
    "test for harmless error": "harmless_error_doctrine",
    "harmless error factors": "harmless_error_doctrine",
    "factors of harmless error": "harmless_error_doctrine",
    "harmless error proof": "harmless_error_doctrine",
    "proof of harmless error": "harmless_error_doctrine",
    "harmless error evidence": "harmless_error_doctrine",
    "evidence of harmless error": "harmless_error_doctrine",
    "harmless error req": "harmless_error_doctrine",
    "harmless error requirements": "harmless_error_doctrine",
    "harmless error requirement": "harmless_error_doctrine",
    "harmless-error": "harmless_error_doctrine",
    "harmlesserror": "harmless_error_doctrine",
    "harmless error rule": "harmless_error_doctrine",
    "harmless error statute": "harmless_error_doctrine",
}

_EXPECTED_ENTRY_COUNT = 410

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    s = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    expected = _EXPECTED_ENTRY_COUNT
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == expected) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "OK" if is_valid else "FAIL",
        "entries": actual_count,
        "expected_entries": expected,
        "hash": actual_hash,
        "expected_hash": _MAP_INTEGRITY_HASH,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"[_\-]", " ", t)
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    # Try exact match
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try with underscores
    t2 = t.replace(" ", "_")
    if t2 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t2]
    # Try with hyphens
    t3 = t.replace(" ", "-")
    if t3 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t3]
    # Try removing all spaces
    t4 = t.replace(" ", "")
    if t4 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t4]
    return None

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    if not norm:
        return []
    return [k for k, v in SEMANTIC_MAP.items() if v == norm]

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)