import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MECH12 Team"
SEMANTIC_MAP_ENGINE = "MECH12_pneumatic_systems"

SEMANTIC_MAP = {
    # Reciprocating Compressor Selection and Sizing
    "reciprocating compressor": "reciprocating_compressor",
    "recip compressor": "reciprocating_compressor",
    "piston compressor": "reciprocating_compressor",
    "reciprocating air compressor": "reciprocating_compressor",
    "reciprocating compressor sizing": "reciprocating_compressor_sizing",
    "reciprocating compressor selection": "reciprocating_compressor_selection",
    "piston compressor sizing": "reciprocating_compressor_sizing",
    "reciprocating compressor capacity": "reciprocating_compressor_capacity",
    "reciprocating compressor cfm": "reciprocating_compressor_capacity",
    "reciprocating compressor kw": "reciprocating_compressor_power",
    "reciprocating compressor power": "reciprocating_compressor_power",
    "reciprocating compressor efficiency": "reciprocating_compressor_efficiency",
    "reciprocating compressor performance": "reciprocating_compressor_performance",
    "reciprocating compressor duty cycle": "reciprocating_compressor_duty_cycle",
    "reciprocating compressor maintenance": "reciprocating_compressor_maintenance",
    "reciprocating compressor lubrication": "reciprocating_compressor_lubrication",
    "reciprocating compressor noise": "reciprocating_compressor_noise",
    "reciprocating compressor vibration": "reciprocating_compressor_vibration",
    "reciprocating compressor cooling": "reciprocating_compressor_cooling",
    "reciprocating compressor startup": "reciprocating_compressor_startup",
    "reciprocating compressor shutdown": "reciprocating_compressor_shutdown",
    "reciprocating compressor unload": "reciprocating_compressor_unload",
    "reciprocating compressor control": "reciprocating_compressor_control",
    "reciprocating compressor head": "reciprocating_compressor_head",
    "reciprocating compressor valve": "reciprocating_compressor_valve",
    "reciprocating compressor piston": "reciprocating_compressor_piston",
    "reciprocating compressor cylinder": "reciprocating_compressor_cylinder",
    "reciprocating compressor rod": "reciprocating_compressor_rod",
    "reciprocating compressor crankshaft": "reciprocating_compressor_crankshaft",
    "reciprocating compressor crosshead": "reciprocating_compressor_crosshead",
    "reciprocating compressor clearance": "reciprocating_compressor_clearance",
    "reciprocating compressor interstage": "reciprocating_compressor_interstage",
    "reciprocating compressor aftercooler": "reciprocating_compressor_aftercooler",
    "reciprocating compressor intercooler": "reciprocating_compressor_intercooler",
    "reciprocating compressor stages": "reciprocating_compressor_stages",
    "reciprocating compressor multi-stage": "reciprocating_compressor_stages",
    "reciprocating compressor single-stage": "reciprocating_compressor_stages",
    "reciprocating compressor two-stage": "reciprocating_compressor_stages",
    "reciprocating compressor triplex": "reciprocating_compressor_triplex",
    "reciprocating compressor duplex": "reciprocating_compressor_duplex",
    "reciprocating compressor triplex configuration": "reciprocating_compressor_triplex",
    "reciprocating compressor duplex configuration": "reciprocating_compressor_duplex",
    "reciprocating compressor airend": "reciprocating_compressor_airend",
    "reciprocating compressor air end": "reciprocating_compressor_airend",
    "reciprocating compressor oil": "reciprocating_compressor_oil",
    "reciprocating compressor oil carryover": "reciprocating_compressor_oil_carryover",
    "reciprocating compressor oil separator": "reciprocating_compressor_oil_separator",
    "reciprocating compressor filter": "reciprocating_compressor_filter",
    "reciprocating compressor inlet filter": "reciprocating_compressor_inlet_filter",
    "reciprocating compressor discharge": "reciprocating_compressor_discharge",
    "reciprocating compressor discharge pressure": "reciprocating_compressor_discharge_pressure",
    "reciprocating compressor suction": "reciprocating_compressor_suction",
    "reciprocating compressor suction pressure": "reciprocating_compressor_suction_pressure",
    "reciprocating compressor volumetric efficiency": "reciprocating_compressor_volumetric_efficiency",
    "reciprocating compressor mechanical efficiency": "reciprocating_compressor_mechanical_efficiency",
    "reciprocating compressor isothermal efficiency": "reciprocating_compressor_isothermal_efficiency",
    "reciprocating compressor polytropic efficiency": "reciprocating_compressor_polytropic_efficiency",
    "reciprocating compressor compression ratio": "reciprocating_compressor_compression_ratio",
    "reciprocating compressor pressure ratio": "reciprocating_compressor_compression_ratio",
    "reciprocating compressor rpm": "reciprocating_compressor_rpm",
    "reciprocating compressor speed": "reciprocating_compressor_rpm",
    "reciprocating compressor flow": "reciprocating_compressor_flow",
    "reciprocating compressor air flow": "reciprocating_compressor_flow",
    "reciprocating compressor f.a.d.": "reciprocating_compressor_flow",
    "reciprocating compressor free air delivery": "reciprocating_compressor_flow",
    "reciprocating compressor swept volume": "reciprocating_compressor_swept_volume",
    "reciprocating compressor displacement": "reciprocating_compressor_swept_volume",
    "reciprocating compressor bore": "reciprocating_compressor_bore",
    "reciprocating compressor stroke": "reciprocating_compressor_stroke",
    "reciprocating compressor clearance volume": "reciprocating_compressor_clearance_volume",
    "reciprocating compressor dead volume": "reciprocating_compressor_clearance_volume",
    "reciprocating compressor indicator diagram": "reciprocating_compressor_indicator_diagram",
    "reciprocating compressor p-v diagram": "reciprocating_compressor_indicator_diagram",
    "reciprocating compressor indicator card": "reciprocating_compressor_indicator_diagram",
    "reciprocating compressor indicator": "reciprocating_compressor_indicator_diagram",
    "reciprocating compressor test": "reciprocating_compressor_test",
    "reciprocating compressor acceptance test": "reciprocating_compressor_test",
    "reciprocating compressor performance test": "reciprocating_compressor_test",
    "reciprocating compressor hydrotest": "reciprocating_compressor_hydrotest",
    "reciprocating compressor hydrostatic test": "reciprocating_compressor_hydrotest",
    "reciprocating compressor pressure test": "reciprocating_compressor_pressure_test",
    "reciprocating compressor leak test": "reciprocating_compressor_leak_test",
    "reciprocating compressor air leak": "reciprocating_compressor_leak_test",
    # Rotary Screw Compressor Design and Application
    "rotary screw compressor": "rotary_screw_compressor",
    "screw compressor": "rotary_screw_compressor",
    "rotary compressor": "rotary_screw_compressor",
    "oil-injected screw compressor": "rotary_screw_compressor_oil_injected",
    "oil free screw compressor": "rotary_screw_compressor_oil_free",
    "oil-free screw compressor": "rotary_screw_compressor_oil_free",
    "oil lubricated screw compressor": "rotary_screw_compressor_oil_injected",
    "rotary screw compressor sizing": "rotary_screw_compressor_sizing",
    "rotary screw compressor selection": "rotary_screw_compressor_selection",
    "rotary screw compressor capacity": "rotary_screw_compressor_capacity",
    "rotary screw compressor cfm": "rotary_screw_compressor_capacity",
    "rotary screw compressor kw": "rotary_screw_compressor_power",
    "rotary screw compressor power": "rotary_screw_compressor_power",
    "rotary screw compressor efficiency": "rotary_screw_compressor_efficiency",
    "rotary screw compressor performance": "rotary_screw_compressor_performance",
    "rotary screw compressor duty cycle": "rotary_screw_compressor_duty_cycle",
    "rotary screw compressor maintenance": "rotary_screw_compressor_maintenance",
    "rotary screw compressor lubrication": "rotary_screw_compressor_lubrication",
    "rotary screw compressor noise": "rotary_screw_compressor_noise",
    "rotary screw compressor vibration": "rotary_screw_compressor_vibration",
    "rotary screw compressor cooling": "rotary_screw_compressor_cooling",
    "rotary screw compressor startup": "rotary_screw_compressor_startup",
    "rotary screw compressor shutdown": "rotary_screw_compressor_shutdown",
    "rotary screw compressor unload": "rotary_screw_compressor_unload",
    "rotary screw compressor control": "rotary_screw_compressor_control",
    "rotary screw compressor airend": "rotary_screw_compressor_airend",
    "rotary screw compressor air end": "rotary_screw_compressor_airend",
    "rotary screw compressor oil": "rotary_screw_compressor_oil",
    "rotary screw compressor oil carryover": "rotary_screw_compressor_oil_carryover",
    "rotary screw compressor oil separator": "rotary_screw_compressor_oil_separator",
    "rotary screw compressor filter": "rotary_screw_compressor_filter",
    "rotary screw compressor inlet filter": "rotary_screw_compressor_inlet_filter",
    "rotary screw compressor discharge": "rotary_screw_compressor_discharge",
    "rotary screw compressor discharge pressure": "rotary_screw_compressor_discharge_pressure",
    "rotary screw compressor suction": "rotary_screw_compressor_suction",
    "rotary screw compressor suction pressure": "rotary_screw_compressor_suction_pressure",
    "rotary screw compressor volumetric efficiency": "rotary_screw_compressor_volumetric_efficiency",
    "rotary screw compressor mechanical efficiency": "rotary_screw_compressor_mechanical_efficiency",
    "rotary screw compressor isothermal efficiency": "rotary_screw_compressor_isothermal_efficiency",
    "rotary screw compressor polytropic efficiency": "rotary_screw_compressor_polytropic_efficiency",
    "rotary screw compressor compression ratio": "rotary_screw_compressor_compression_ratio",
    "rotary screw compressor pressure ratio": "rotary_screw_compressor_compression_ratio",
    "rotary screw compressor rpm": "rotary_screw_compressor_rpm",
    "rotary screw compressor speed": "rotary_screw_compressor_rpm",
    "rotary screw compressor flow": "rotary_screw_compressor_flow",
    "rotary screw compressor air flow": "rotary_screw_compressor_flow",
    "rotary screw compressor f.a.d.": "rotary_screw_compressor_flow",
    "rotary screw compressor free air delivery": "rotary_screw_compressor_flow",
    "rotary screw compressor swept volume": "rotary_screw_compressor_swept_volume",
    "rotary screw compressor displacement": "rotary_screw_compressor_swept_volume",
    "rotary screw compressor lobe": "rotary_screw_compressor_lobe",
    "rotary screw compressor male rotor": "rotary_screw_compressor_male_rotor",
    "rotary screw compressor female rotor": "rotary_screw_compressor_female_rotor",
    "rotary screw compressor airend bearing": "rotary_screw_compressor_airend_bearing",
    "rotary screw compressor airend seal": "rotary_screw_compressor_airend_seal",
    "rotary screw compressor indicator diagram": "rotary_screw_compressor_indicator_diagram",
    "rotary screw compressor test": "rotary_screw_compressor_test",
    "rotary screw compressor acceptance test": "rotary_screw_compressor_test",
    "rotary screw compressor performance test": "rotary_screw_compressor_test",
    "rotary screw compressor hydrotest": "rotary_screw_compressor_hydrotest",
    "rotary screw compressor hydrostatic test": "rotary_screw_compressor_hydrotest",
    "rotary screw compressor pressure test": "rotary_screw_compressor_pressure_test",
    "rotary screw compressor leak test": "rotary_screw_compressor_leak_test",
    "rotary screw compressor air leak": "rotary_screw_compressor_leak_test",
    # Air Receiver Tank Sizing and Pressure Stabilization
    "air receiver": "air_receiver",
    "air receiver tank": "air_receiver",
    "receiver tank": "air_receiver",
    "compressed air receiver": "air_receiver",
    "air receiver sizing": "air_receiver_sizing",
    "receiver tank sizing": "air_receiver_sizing",
    "air receiver volume": "air_receiver_volume",
    "air receiver capacity": "air_receiver_volume",
    "air receiver pressure": "air_receiver_pressure",
    "air receiver pressure drop": "air_receiver_pressure_drop",
    "air receiver pressure stabilization": "air_receiver_pressure_stabilization",
    "air receiver safety valve": "air_receiver_safety_valve",
    "air receiver drain": "air_receiver_drain",
    "air receiver condensate": "air_receiver_condensate",
    "air receiver inspection": "air_receiver_inspection",
    "air receiver hydrotest": "air_receiver_hydrotest",
    "air receiver hydrostatic test": "air_receiver_hydrotest",
    "air receiver pressure test": "air_receiver_pressure_test",
    "air receiver code": "air_receiver_code",
    "air receiver asme": "air_receiver_code",
    "air receiver certification": "air_receiver_code",
    "air receiver design": "air_receiver_design",
    "air receiver corrosion": "air_receiver_corrosion",
    "air receiver shell": "air_receiver_shell",
    "air receiver head": "air_receiver_head",
    "air receiver nozzle": "air_receiver_nozzle",
    "air receiver manhole": "air_receiver_manhole",
    "air receiver support": "air_receiver_support",
    "air receiver saddle": "air_receiver_support",
    "air receiver leg": "air_receiver_support",
    "air receiver thickness": "air_receiver_thickness",
    "air receiver wall thickness": "air_receiver_thickness",
    "air receiver paint": "air_receiver_paint",
    "air receiver internal coating": "air_receiver_paint",
    "air receiver external coating": "air_receiver_paint",
    "air receiver tag": "air_receiver_tag",
    "air receiver nameplate": "air_receiver_tag",
    # Compressed Air Dryer Selection - Refrigerated vs Desiccant
    "air dryer": "air_dryer",
    "compressed air dryer": "air_dryer",
    "refrigerated air dryer": "refrigerated_air_dryer",
    "refrigeration air dryer": "refrigerated_air_dryer",
    "desiccant air dryer": "desiccant_air_dryer",
    "adsorption air dryer": "desiccant_air_dryer",
    "heatless desiccant dryer": "heatless_desiccant_air_dryer",
    "heated desiccant dryer": "heated_desiccant_air_dryer",
    "blower purge dryer": "blower_purge_desiccant_air_dryer",
    "membrane air dryer": "membrane_air_dryer",
    "air dryer selection": "air_dryer_selection",
    "air dryer sizing": "air_dryer_sizing",
    "air dryer dew point": "air_dryer_dew_point",
    "air dryer pressure drop": "air_dryer_pressure_drop",
    "air dryer purge": "air_dryer_purge",
    "air dryer regeneration": "air_dryer_regeneration",
    "air dryer switching": "air_dryer_switching",
    "air dryer cycle": "air_dryer_cycle",
    "air dryer maintenance": "air_dryer_maintenance",
    "air dryer troubleshooting": "air_dryer_troubleshooting",
    "air dryer performance": "air_dryer_performance",
    "air dryer efficiency": "air_dryer_efficiency",
    "air dryer energy consumption": "air_dryer_energy_consumption",
    "air dryer power": "air_dryer_power",
    "air dryer control": "air_dryer_control",
    "air dryer bypass": "air_dryer_bypass",
    "air dryer filter": "air_dryer_filter",
    "air dryer prefilter": "air_dryer_prefilter",
    "air dryer afterfilter": "air_dryer_afterfilter",
    "air dryer outlet": "air_dryer_outlet",
    "air dryer inlet": "air_dryer_inlet",
    "air dryer test": "air_dryer_test",
    "air dryer dewpoint sensor": "air_dryer_dew_point_sensor",
    "air dryer alarm": "air_dryer_alarm",
    # Pneumatic Cylinder Force and Sizing Calculations
    "pneumatic cylinder": "pneumatic_cylinder",
    "air cylinder": "pneumatic_cylinder",
    "double acting cylinder": "double_acting_cylinder",
    "single acting cylinder": "single_acting_cylinder",
    "pneumatic actuator": "pneumatic_cylinder",
    "cylinder force": "pneumatic_cylinder_force",
    "pneumatic cylinder force": "pneumatic_cylinder_force",
    "cylinder sizing": "pneumatic_cylinder_sizing",
    "pneumatic cylinder sizing": "pneumatic_cylinder_sizing",
    "cylinder bore": "pneumatic_cylinder_bore",
    "cylinder stroke": "pneumatic_cylinder_stroke",
    "cylinder rod": "pneumatic_cylinder_rod",
    "cylinder speed": "pneumatic_cylinder_speed",
    "cylinder cushioning": "pneumatic_cylinder_cushioning",
    "cylinder mounting": "pneumatic_cylinder_mounting",
    "cylinder end cap": "pneumatic_cylinder_end_cap",
    "cylinder seal": "pneumatic_cylinder_seal",
    "cylinder leakage": "pneumatic_cylinder_leakage",
    "cylinder repair": "pneumatic_cylinder_repair",
    "cylinder maintenance": "pneumatic_cylinder_maintenance",
    "cylinder misalignment": "pneumatic_cylinder_misalignment",
    "cylinder buckling": "pneumatic_cylinder_buckling",
    "cylinder side load": "pneumatic_cylinder_side_load",
    "cylinder thrust": "pneumatic_cylinder_force",
    "cylinder area": "pneumatic_cylinder_area",
    "cylinder pressure": "pneumatic_cylinder_pressure",
    "cylinder port": "pneumatic_cylinder_port",
    "cylinder tube": "pneumatic_cylinder_tube",
    "cylinder barrel": "pneumatic_cylinder_tube",
    "cylinder tie rod": "pneumatic_cylinder_tie_rod",
    "cylinder clevis": "pneumatic_cylinder_clevis",
    "cylinder trunnion": "pneumatic_cylinder_trunnion",
    "cylinder flange": "pneumatic_cylinder_flange",
    "cylinder stop tube": "pneumatic_cylinder_stop_tube",
    "cylinder magnetic piston": "pneumatic_cylinder_magnetic_piston",
    "cylinder non-magnetic piston": "pneumatic_cylinder_non_magnetic_piston",
    "cylinder sensor": "pneumatic_cylinder_sensor",
    "cylinder switch": "pneumatic_cylinder_sensor",
    "cylinder feedback": "pneumatic_cylinder_feedback",
    "cylinder position sensor": "pneumatic_cylinder_sensor",
    # Directional Control Valve Selection - 3/2, 5/2, 5/3 Configurations
    "directional control valve": "directional_control_valve",
    "dcv": "directional_control_valve",
    "3/2 valve": "directional_control_valve_3_2",
    "3 2 valve": "directional_control_valve_3_2",
    "three two valve": "directional_control_valve_3_2",
    "5/2 valve": "directional_control_valve_5_2",
    "5 2 valve": "directional_control_valve_5_2",
    "five two valve": "directional_control_valve_5_2",
    "5/3 valve": "directional_control_valve_5_3",
    "5 3 valve": "directional_control_valve_5_3",
    "five three valve": "directional_control_valve_5_3",
    "solenoid valve": "solenoid_valve",
    "pneumatic valve": "directional_control_valve",
    "pilot valve": "pilot_valve",
    "manual valve": "manual_valve",
    "mechanical valve": "mechanical_valve",
    "valve actuation": "valve_actuation",
    "valve spring return": "valve_spring_return",
    "valve detent": "valve_detent",
    "valve spool": "valve_spool",
    "valve poppet": "valve_poppet",
    "valve seat": "valve_seat",
    "valve port": "valve_port",
    "valve body": "valve_body",
    "valve seal": "valve_seal",
    "valve leakage": "valve_leakage",
    "valve mounting": "valve_mounting",
    "valve manifold": "valve_manifold",
    "valve response time": "valve_response_time",
    "valve switching time": "valve_response_time",
    "valve flow rate": "valve_flow_rate",
    "valve kv": "valve_flow_coefficient",
    "valve cv": "valve_flow_coefficient",
    "valve flow coefficient": "valve_flow_coefficient",
    "valve pressure drop": "valve_pressure_drop",
    "valve pressure rating": "valve_pressure_rating",
    "valve test": "valve_test",
    "valve maintenance": "valve_maintenance",
    "valve troubleshooting": "valve_troubleshooting",
    "valve repair": "valve_repair",
    # Pneumatic Flow Control - Meter-In vs Meter-Out
    "flow control valve": "flow_control_valve",
    "meter-in": "meter_in",
    "meter in": "meter_in",
    "meter-out": "meter_out",
    "meter out": "meter_out",
    "meter-in control": "meter_in",
    "meter-out control": "meter_out",
    "meter-in circuit": "meter_in",
    "meter-out circuit": "meter_out",
    "needle valve": "needle_valve",
    "throttle valve": "throttle_valve",
    "restrictor valve": "restrictor_valve",
    "flow restrictor": "restrictor_valve",
    "speed control valve": "flow_control_valve",
    "cylinder speed control": "pneumatic_cylinder_speed_control",
    "flow regulator": "flow_control_valve",
    "pressure compensated flow control": "pressure_compensated_flow_control",
    "non-compensated flow control": "non_compensated_flow_control",
    "quick exhaust valve": "quick_exhaust_valve",
    "quick release valve": "quick_exhaust_valve",
    "exhaust restrictor": "exhaust_restrictor",
    # Vacuum Generation - Ejector vs Mechanical Pump Selection
    "vacuum generator": "vacuum_generator",
    "vacuum ejector": "vacuum_ejector",
    "venturi vacuum": "vacuum_ejector",
    "mechanical vacuum pump": "mechanical_vacuum_pump",
    "vacuum pump": "mechanical_vacuum_pump",
    "rotary vane vacuum pump": "rotary_vane_vacuum_pump",
    "oil free vacuum pump": "oil_free_vacuum_pump",
    "oil lubricated vacuum pump": "oil_lubricated_vacuum_pump",
    "vacuum level": "vacuum_level",
    "vacuum pressure": "vacuum_level",
    "vacuum flow": "vacuum_flow",
    "vacuum capacity": "vacuum_flow",
    "vacuum selection": "vacuum_selection",
    "vacuum sizing": "vacuum_sizing",
    "vacuum efficiency": "vacuum_efficiency",
    "vacuum maintenance": "vacuum_maintenance",
    "vacuum leakage": "vacuum_leakage",
    "vacuum test": "vacuum_test",
    "vacuum gauge": "vacuum_gauge",
    "vacuum switch": "vacuum_switch",
    "vacuum sensor": "vacuum_sensor",
    "vacuum filter": "vacuum_filter",
    "vacuum reservoir": "vacuum_reservoir",
    "vacuum tank": "vacuum_reservoir",
    "vacuum cup": "vacuum_cup",
    "suction cup": "vacuum_cup",
    "vacuum pad": "vacuum_cup",
    "vacuum cup gripper": "vacuum_cup_gripper",
    "vacuum gripper": "vacuum_cup_gripper",
    "suction gripper": "vacuum_cup_gripper",
    "vacuum cup force": "vacuum_cup_force",
    "suction force": "vacuum_cup_force",
    "vacuum cup sizing": "vacuum_cup_sizing",
    # Compressed Air Quality per ISO 8573-1 Classification
    "compressed air quality": "compressed_air_quality",
    "air quality class": "compressed_air_quality_class",
    "iso 8573": "iso_8573_1",
    "iso 8573-1": "iso_8573_1",
    "iso8573-1": "iso_8573_1",
    "iso8573": "iso_8573_1",
    "compressed air class": "compressed_air_quality_class",
    "oil content": "compressed_air_oil_content",
    "particulate class": "compressed_air_particulate_class",
    "water class": "compressed_air_water_class",
    "dew point class": "compressed_air_dew_point_class",
    "air purity": "compressed_air_quality",
    "air cleanliness": "compressed_air_quality",
    "compressed air testing": "compressed_air_testing",
    "compressed air analysis": "compressed_air_testing",
    "compressed air monitoring": "compressed_air_testing",
    "compressed air filter": "compressed_air_filter",
    "coalescing filter": "coalescing_filter",
    "particulate filter": "particulate_filter",
    "oil removal filter": "oil_removal_filter",
    "activated carbon filter": "activated_carbon_filter",
    "sterile filter": "sterile_filter",
    # Compressed Air Energy Audit and Specific Power Analysis
    "energy audit": "compressed_air_energy_audit",
    "compressed air audit": "compressed_air_energy_audit",
    "air audit": "compressed_air_energy_audit",
    "specific power": "compressed_air_specific_power",
    "specific energy": "compressed_air_specific_power",
    "kw/100cfm": "compressed_air_specific_power",
    "kw per 100 cfm": "compressed_air_specific_power",
    "energy efficiency": "compressed_air_energy_efficiency",
    "compressed air efficiency": "compressed_air_energy_efficiency",
    "energy savings": "compressed_air_energy_savings",
    "compressed air savings": "compressed_air_energy_savings",
    "energy consumption": "compressed_air_energy_consumption",
    "compressed air consumption": "compressed_air_energy_consumption",
    "compressed air cost": "compressed_air_cost",
    "compressed air monitoring": "compressed_air_monitoring",
    "compressed air metering": "compressed_air_monitoring",
    "compressed air data logging": "compressed_air_monitoring",
    # Compressed Air Leak Detection and Management Program
    "air leak": "compressed_air_leak",
    "compressed air leak": "compressed_air_leak",
    "leak detection": "compressed_air_leak_detection",
    "ultrasonic leak detection": "compressed_air_leak_detection_ultrasonic",
    "leak management": "compressed_air_leak_management",
    "leak survey": "compressed_air_leak_survey",
    "leak audit": "compressed_air_leak_survey",
    "leak repair": "compressed_air_leak_repair",
    "leak tagging": "compressed_air_leak_tagging",
    "leak documentation": "compressed_air_leak_tagging",
    # Pneumatic Logic Circuits and Sequential Control
    "pneumatic logic": "pneumatic_logic",
    "pneumatic logic circuit": "pneumatic_logic_circuit",
    "sequential control": "pneumatic_sequential_control",
    "pneumatic sequence": "pneumatic_sequential_control",
    "pneumatic timer": "pneumatic_timer",
    "pneumatic delay": "pneumatic_timer",
    "pneumatic and": "pneumatic_logic_and",
    "pneumatic or": "pneumatic_logic_or",
    "pneumatic not": "pneumatic_logic_not",
    "pneumatic memory": "pneumatic_logic_memory",
    "pneumatic flip flop": "pneumatic_logic_memory",
    "pneumatic bistable": "pneumatic_logic_memory",
    "pneumatic signal": "pneumatic_signal",
    "pneumatic relay": "pneumatic_relay",
    "pneumatic sensor": "pneumatic_sensor",
    # Vacuum Cup Gripper Design and Suction Force Calculation
    "vacuum cup design": "vacuum_cup_design",
    "vacuum cup calculation": "vacuum_cup_calculation",
    "vacuum cup force calculation": "vacuum_cup_force_calculation",
    "vacuum cup selection": "vacuum_cup_selection",
    "vacuum cup sizing": "vacuum_cup_sizing",
    "vacuum cup area": "vacuum_cup_area",
    "vacuum cup diameter": "vacuum_cup_diameter",
    "vacuum cup material": "vacuum_cup_material",
    "vacuum cup hardness": "vacuum_cup_material",
    "vacuum cup mounting": "vacuum_cup_mounting",
    "vacuum cup fitting": "vacuum_cup_fitting",
    "vacuum cup stem": "vacuum_cup_stem",
    "vacuum cup thread": "vacuum_cup_thread",
    "vacuum cup bellows": "vacuum_cup_bellows",
    "vacuum cup flat": "vacuum_cup_flat",
    "vacuum cup oval": "vacuum_cup_oval",
    "vacuum cup round": "vacuum_cup_round",
    # Pneumatic Pipe Sizing and Pressure Drop Calculation
    "pneumatic pipe": "pneumatic_pipe",
    "compressed air pipe": "pneumatic_pipe",
    "air line": "pneumatic_pipe",
    "pipe sizing": "pneumatic_pipe_sizing",
    "air line sizing": "pneumatic_pipe_sizing",
    "pipe pressure drop": "pneumatic_pipe_pressure_drop",
    "air line pressure drop": "pneumatic_pipe_pressure_drop",
    "pipe flow": "pneumatic_pipe_flow",
    "pipe velocity": "pneumatic_pipe_velocity",
    "pipe length": "pneumatic_pipe_length",
    "pipe diameter": "pneumatic_pipe_diameter",
    "pipe material": "pneumatic_pipe_material",
    "pipe roughness": "pneumatic_pipe_roughness",
    "pipe fittings": "pneumatic_pipe_fittings",
    "pipe bends": "pneumatic_pipe_fittings",
    "pipe tee": "pneumatic_pipe_fittings",
    "pipe reducer": "pneumatic_pipe_fittings",
    "pipe branch": "pneumatic_pipe_fittings",
    "pipe manifold": "pneumatic_pipe_manifold",
    "pipe header": "pneumatic_pipe_header",
    "pipe drop": "pneumatic_pipe_drop",
    "pipe support": "pneumatic_pipe_support",
    "pipe hanger": "pneumatic_pipe_support",
    "pipe clamp": "pneumatic_pipe_support",
    "pipe expansion": "pneumatic_pipe_expansion",
    "pipe contraction": "pneumatic_pipe_contraction",
    "pipe insulation": "pneumatic_pipe_insulation",
    "pipe corrosion": "pneumatic_pipe_corrosion",
    "pipe leak": "pneumatic_pipe_leak",
    "pipe test": "pneumatic_pipe_test",
    "pipe hydrotest": "pneumatic_pipe_hydrotest",
    "pipe pressure test": "pneumatic_pipe_pressure_test",
    # OSHA Compressed Air Safety - 29 CFR 1910.242 and 1910.169
    "osha compressed air": "osha_compressed_air",
    "osha 1910.242": "osha_1910_242",
    "osha 1910.169": "osha_1910_169",
    "compressed air safety": "compressed_air_safety",
    "compressed air nozzle": "compressed_air_nozzle",
    "safety nozzle": "compressed_air_nozzle",
    "air blow gun": "compressed_air_nozzle",
    "compressed air blow gun": "compressed_air_nozzle",
    "compressed air hazard": "compressed_air_hazard",
    "compressed air injury": "compressed_air_hazard",
    "compressed air accident": "compressed_air_hazard",
    "compressed air ppe": "compressed_air_ppe",
    "compressed air personal protective equipment": "compressed_air_ppe",
    "compressed air signage": "compressed_air_signage",
    "compressed air label": "compressed_air_signage",
    # ISO 4414 Pneumatic System Design Rules and Safety
    "iso 4414": "iso_4414",
    "iso4414": "iso_4414",
    "pneumatic safety": "pneumatic_safety",
    "pneumatic system safety": "pneumatic_safety",
    "pneumatic system design": "pneumatic_system_design",
    "pneumatic circuit design": "pneumatic_system_design",
    "pneumatic risk assessment": "pneumatic_risk_assessment",
    "pneumatic safety circuit": "pneumatic_safety_circuit",
    "pneumatic safety valve": "pneumatic_safety_valve",
    "pneumatic safety function": "pneumatic_safety_function",
    "pneumatic safety relay": "pneumatic_safety_relay",
    "pneumatic lockout": "pneumatic_lockout",
    "pneumatic tagout": "pneumatic_lockout",
    "pneumatic emergency stop": "pneumatic_emergency_stop",
    "pneumatic e-stop": "pneumatic_emergency_stop",
    # Heat Recovery from Compressed Air Systems
    "heat recovery": "compressed_air_heat_recovery",
    "compressed air heat recovery": "compressed_air_heat_recovery",
    "compressor heat recovery": "compressed_air_heat_recovery",
    "heat exchanger": "heat_exchanger",
    "air to water heat exchanger": "air_to_water_heat_exchanger",
    "air to air heat exchanger": "air_to_air_heat_exchanger",
    "waste heat": "compressed_air_heat_recovery",
    "waste heat recovery": "compressed_air_heat_recovery",
    "heat reclaim": "compressed_air_heat_recovery",
    # Variable Speed Drive (VSD) Compressor Energy Savings
    "vsd compressor": "vsd_compressor",
    "variable speed compressor": "vsd_compressor",
    "variable speed drive compressor": "vsd_compressor",
    "frequency inverter compressor": "vsd_compressor",
    "inverter compressor": "vsd_compressor",
    "vsd energy savings": "vsd_compressor_energy_savings",
    "vsd efficiency": "vsd_compressor_efficiency",
    "vsd control": "vsd_compressor_control",
    "vsd compressor selection": "vsd_compressor_selection",
    "vsd compressor sizing": "vsd_compressor_sizing",
    "vsd compressor performance": "vsd_compressor_performance",
    "vsd compressor maintenance": "vsd_compressor_maintenance",
    "vsd compressor troubleshooting": "vsd_compressor_troubleshooting",
    # Altitude Derating of Compressors and Pneumatic Equipment
    "altitude derating": "altitude_derating",
    "compressor derating": "altitude_derating",
    "pneumatic derating": "altitude_derating",
    "altitude correction": "altitude_derating",
    "altitude correction factor": "altitude_derating",
    "compressor altitude": "altitude_derating",
    "altitude capacity loss": "altitude_derating",
    # Filter-Regulator-Lubricator (FRL) Unit Selection and Maintenance
    "frl": "frl_unit",
    "f.r.l.": "frl_unit",
    "filter regulator lubricator": "frl_unit",
    "frl unit": "frl_unit",
    "frl assembly": "frl_unit",
    "frl selection": "frl_unit_selection",
    "frl sizing": "frl_unit_sizing",
    "frl maintenance": "frl_unit_maintenance",
    "frl troubleshooting": "frl_unit_troubleshooting",
    "frl repair": "frl_unit_repair",
    "air filter": "compressed_air_filter",
    "regulator": "air_pressure_regulator",
    "pressure regulator": "air_pressure_regulator",
    "air lubricator": "air_lubricator",
    "lubricator": "air_lubricator",
    "frl bowl": "frl_unit_bowl",
    "frl drain": "frl_unit_drain",
    "frl element": "frl_unit_element",
    "frl pressure gauge": "frl_unit_pressure_gauge",
    "frl mounting": "frl_unit_mounting",
    "frl bracket": "frl_unit_mounting",
    "frl filter": "frl_unit_filter",
    "frl regulator": "frl_unit_regulator",
    "frl lubricator": "frl_unit_lubricator",
    # General/Related
    "cfm": "flow_cfm",
    "scfm": "flow_scfm",
    "nl/min": "flow_nl_min",
    "nlpm": "flow_nl_min",
    "l/min": "flow_l_min",
    "lpm": "flow_l_min",
    "kw": "power_kw",
    "hp": "power_hp",
    "bar": "pressure_bar",
    "psi": "pressure_psi",
    "mpa": "pressure_mpa",
    "pa": "pressure_pa",
    "kpa": "pressure_kpa",
    "gauge pressure": "pressure_gauge",
    "absolute pressure": "pressure_absolute",
    "ambient temperature": "ambient_temperature",
    "ambient humidity": "ambient_humidity",
    "relative humidity": "ambient_humidity",
    "dew point": "dew_point",
    "pressure dew point": "dew_point",
    "temperature": "temperature",
    "humidity": "humidity",
    "pressure": "pressure",
    "flow": "flow",
    "velocity": "velocity",
    "volume": "volume",
    "capacity": "capacity",
    "power": "power",
    "efficiency": "efficiency",
    "energy": "energy",
    "consumption": "energy_consumption",
    "safety": "safety",
    "maintenance": "maintenance",
    "inspection": "inspection",
    "test": "test",
    "troubleshooting": "troubleshooting",
    "repair": "repair",
    "selection": "selection",
    "sizing": "sizing",
    "audit": "audit",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "gauge": "gauge",
    "switch": "switch",
    "alarm": "alarm",
    "control": "control",
    "circuit": "circuit",
    "diagram": "diagram",
    "drawing": "diagram",
    "design": "design",
    "application": "application",
    "performance": "performance",
    "rating": "rating",
    "class": "class",
    "standard": "standard",
    "code": "code",
    "regulation": "regulation",
    "rule": "rule",
    "requirement": "requirement",
    "specification": "specification",
    "data": "data",
    "logging": "logging",
    "documentation": "documentation",
    "program": "program",
    "management": "management",
    "tag": "tag",
    "label": "label",
    "nameplate": "tag",
    "bowl": "bowl",
    "element": "element",
    "drain": "drain",
    "nozzle": "nozzle",
    "fitting": "fitting",
    "thread": "thread",
    "mounting": "mounting",
    "support": "support",
    "bracket": "bracket",
    "header": "header",
    "manifold": "manifold",
    "drop": "drop",
    "expansion": "expansion",
    "contraction": "contraction",
    "insulation": "insulation",
    "corrosion": "corrosion",
    "leak": "leak",
    "hydrotest": "hydrotest",
    "pressure test": "pressure_test",
    "acceptance test": "test",
    "hydrostatic test": "hydrotest",
    "indicator diagram": "indicator_diagram",
    "p-v diagram": "indicator_diagram",
    "indicator card": "indicator_diagram",
    "indicator": "indicator_diagram",
    "triplex": "triplex",
    "duplex": "duplex",
    "multi-stage": "stages",
    "single-stage": "stages",
    "two-stage": "stages",
    "male rotor": "male_rotor",
    "female rotor": "female_rotor",
    "airend": "airend",
    "air end": "airend",
    "shell": "shell",
    "head": "head",
    "nozzle": "nozzle",
    "manhole": "manhole",
    "saddle": "saddle",
    "leg": "leg",
    "wall thickness": "thickness",
    "internal coating": "paint",
    "external coating": "paint",
    "paint": "paint",
    "stop tube": "stop_tube",
    "tie rod": "tie_rod",
    "clevis": "clevis",
    "trunnion": "trunnion",
    "flange": "flange",
    "magnetic piston": "magnetic_piston",
    "non-magnetic piston": "non_magnetic_piston",
    "feedback": "feedback",
    "memory": "memory",
    "bistable": "memory",
    "flip flop": "memory",
    "and": "logic_and",
    "or": "logic_or",
    "not": "logic_not",
    "delay": "timer",
    "timer": "timer",
    "relay": "relay",
    "signal": "signal",
    "purge": "purge",
    "regeneration": "regeneration",
    "switching": "switching",
    "cycle": "cycle",
    "bypass": "bypass",
    "prefilter": "prefilter",
    "afterfilter": "afterfilter",
    "outlet": "outlet",
    "inlet": "inlet",
    "area": "area",
    "diameter": "diameter",
    "material": "material",
    "hardness": "hardness",
    "bellows": "bellows",
    "flat": "flat",
    "oval": "oval",
    "round": "round",
    "roughness": "roughness",
    "bends": "bends",
    "tee": "tee",
    "reducer": "reducer",
    "branch": "branch",
    "contraction": "contraction",
    "insulation": "insulation",
    "hanger": "hanger",
    "clamp": "clamp",
    "expansion": "expansion",
    "contraction": "contraction",
    "test": "test",
    "acceptance test": "test",
    "hydrostatic test": "hydrotest",
    "indicator diagram": "indicator_diagram",
    "indicator card": "indicator_diagram",
    "indicator": "indicator_diagram",
    "triplex": "triplex",
    "duplex": "duplex",
    "multi-stage": "stages",
    "single-stage": "stages",
    "two-stage": "stages",
    "male rotor": "male_rotor",
    "female rotor": "female_rotor",
    "airend": "airend",
    "air end": "airend",
    "shell": "shell",
    "head": "head",
    "nozzle": "nozzle",
    "manhole": "manhole",
    "saddle": "saddle",
    "leg": "leg",
    "wall thickness": "thickness",
    "internal coating": "paint",
    "external coating": "paint",
    "paint": "paint",
    "stop tube": "stop_tube",
    "tie rod": "tie_rod",
    "clevis": "clevis",
    "trunnion": "trunnion",
    "flange": "flange",
    "magnetic piston": "magnetic_piston",
    "non-magnetic piston": "non_magnetic_piston",
    "feedback": "feedback",
    "memory": "memory",
    "bistable": "memory",
    "flip flop": "memory",
    "and": "logic_and",
    "or": "logic_or",
    "not": "logic_not",
    "delay": "timer",
    "timer": "timer",
    "relay": "relay",
    "signal": "signal",
    "purge": "purge",
    "regeneration": "regeneration",
    "switching": "switching",
    "cycle": "cycle",
    "bypass": "bypass",
    "prefilter": "prefilter",
    "afterfilter": "afterfilter",
    "outlet": "outlet",
    "inlet": "inlet",
    "area": "area",
    "diameter": "diameter",
    "material": "material",
    "hardness": "hardness",
    "bellows": "bellows",
    "flat": "flat",
    "oval": "oval",
    "round": "round",
    "roughness": "roughness",
    "bends": "bends",
    "tee": "tee",
    "reducer": "reducer",
    "branch": "branch",
    "contraction": "contraction",
    "insulation": "insulation",
    "hanger": "hanger",
    "clamp": "clamp",
    "expansion": "expansion",
    "contraction": "contraction",
    # Misspellings and common typos
    "reciprocating comprssor": "reciprocating_compressor",
    "rotary screw comprssor": "rotary_screw_compressor",
    "air reciever": "air_receiver",
    "desicant dryer": "desiccant_air_dryer",
    "pneumatic cyliner": "pneumatic_cylinder",
    "directional control vavle": "directional_control_valve",
    "meterin": "meter_in",
    "meterout": "meter_out",
    "vaccum": "vacuum",
    "vaccum pump": "mechanical_vacuum_pump",
    "vaccum cup": "vacuum_cup",
    "iso8573": "iso_8573_1",
    "iso4414": "iso_4414",
    "frlunit": "frl_unit",
    "pneumatc": "pneumatic",
    "pneumatics": "pneumatic",
    "compresor": "compressor",
    "comressor": "compressor",
    "comprssor": "compressor",
    "pressur": "pressure",
    "presure": "pressure",
    "preassure": "pressure",
    "guage": "gauge",
    "gage": "gauge",
    "regualtor": "regulator",
    "lubricater": "lubricator",
    "maintainance": "maintenance",
    "maintanance": "maintenance",
    "maintenence": "maintenance",
    "troubleshoting": "troubleshooting",
    "troubleshhoting": "troubleshooting",
    "troubleshoooting": "troubleshooting",
    "troubleshouting": "troubleshooting",
    "siezing": "sizing",
    "seizing": "sizing",
    "selction": "selection",
    "audt": "audit",
    "monitroing": "monitoring",
    "senor": "sensor",
    "senser": "sensor",
    "swich": "switch",
    "alrm": "alarm",
    "contrl": "control",
    "cicruit": "circuit",
    "diagaram": "diagram",
    "drawng": "diagram",
    "desgin": "design",
    "aplication": "application",
    "performnace": "performance",
    "ratng": "rating",
    "clas": "class",
    "standrad": "standard",
    "cod": "code",
    "regualtion": "regulation",
    "rul": "rule",
    "requirment": "requirement",
    "specifcation": "specification",
    "dat": "data",
    "loging": "logging",
    "documetation": "documentation",
    "progrm": "program",
    "managment": "management",
    "taag": "tag",
    "lable": "label",
    "nameplte": "tag",
    "bowel": "bowl",
    "elment": "element",
    "drin": "drain",
    "nozel": "nozzle",
    "fiting": "fitting",
    "thred": "thread",
    "mouting": "mounting",
    "suport": "support",
    "braket": "bracket",
    "heade": "header",
    "manifoldd": "manifold",
    "dropp": "drop",
    "expantion": "expansion",
    "contration": "contraction",
    "insulaton": "insulation",
    "corosion": "corrosion",
    "leek": "leak",
    "hydrotes": "hydrotest",
    "presure test": "pressure_test",
    "acceptence test": "test",
    "hydrostatc test": "hydrotest",
    "indcator diagram": "indicator_diagram",
    "indcator card": "indicator_diagram",
    "indcator": "indicator_diagram",
    "trplex": "triplex",
    "duplx": "duplex",
    "multi stage": "stages",
    "single stage": "stages",
    "two stage": "stages",
    "male rotr": "male_rotor",
    "female rotr": "female_rotor",
    "airendd": "airend",
    "shelll": "shell",
    "headd": "head",
    "nozle": "nozzle",
    "manholee": "manhole",
    "sadle": "saddle",
    "legg": "leg",
    "wall thicknes": "thickness",
    "internal coatin": "paint",
    "external coatin": "paint",
    "paintt": "paint",
    "stop tubee": "stop_tube",
    "tie rod": "tie_rod",
    "cleivs": "clevis",
    "trunon": "trunnion",
    "flage": "flange",
    "magnetic piston": "magnetic_piston",
    "non magnetic piston": "non_magnetic_piston",
    "feedbak": "feedback",
    "memry": "memory",
    "bistabel": "memory",
    "flipflop": "memory",
    "adn": "logic_and",
    "ro": "logic_or",
    "nto": "logic_not",
    "dely": "timer",
    "timr": "timer",
    "relai": "relay",
    "sigal": "signal",
    "pruge": "purge",
    "regeneraton": "regeneration",
    "swiching": "switching",
    "cycel": "cycle",
    "bypss": "bypass",
    "prefiltr": "prefilter",
    "afterfiltr": "afterfilter",
    "outlt": "outlet",
    "inlt": "inlet",
    "areaa": "area",
    "diamter": "diameter",
    "materil": "material",
    "hardnes": "hardness",
    "bellos": "bellows",
    "flaat": "flat",
    "ovall": "oval",
    "roun": "round",
    "roughnes": "roughness",
    "bendsd": "bends",
    "tee": "tee",
    "reducerr": "reducer",
    "brnch": "branch",
    "contrction": "contraction",
    "insulatoin": "insulation",
    "hager": "hanger",
    "clmp": "clamp",
    "expnsion": "expansion",
    "contrction": "contraction",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    entries = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (entries == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "fail",
        "entries": entries,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def _normalize_key(term):
    if not isinstance(term, str):
        return ""
    term = term.lower()
    term = re.sub(r"[^a-z0-9/.\- ]+", "", term)
    term = re.sub(r"\s+", " ", term)
    return term.strip()

def normalize_term(term):
    key = _normalize_key(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term):
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings():
    return dict(SEMANTIC_MAP)