import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AERO03 Python Semantic Team"
SEMANTIC_MAP_ENGINE = "AERO03_aircraft_structures"

SEMANTIC_MAP = {
    # Safe Life Design Philosophy
    "safe life": "safe_life_design_philosophy",
    "safe-life": "safe_life_design_philosophy",
    "safelife": "safe_life_design_philosophy",
    "safe life design": "safe_life_design_philosophy",
    "safe life philosophy": "safe_life_design_philosophy",
    "safe life approach": "safe_life_design_philosophy",
    "safe life method": "safe_life_design_philosophy",
    "safe life principle": "safe_life_design_philosophy",
    "safe life concept": "safe_life_design_philosophy",
    "safe life criteria": "safe_life_design_philosophy",
    "safe life structure": "safe_life_design_philosophy",
    "safe life structures": "safe_life_design_philosophy",
    "safe life design philosophy": "safe_life_design_philosophy",
    "sldp": "safe_life_design_philosophy",
    "sld": "safe_life_design_philosophy",
    "fail safe": "fail_safe_design_philosophy",
    "fail-safe": "fail_safe_design_philosophy",
    "failsafe": "fail_safe_design_philosophy",
    "fail safe design": "fail_safe_design_philosophy",
    "fail safe philosophy": "fail_safe_design_philosophy",
    "fail safe approach": "fail_safe_design_philosophy",
    "fail safe method": "fail_safe_design_philosophy",
    "fail safe principle": "fail_safe_design_philosophy",
    "fail safe concept": "fail_safe_design_philosophy",
    "fail safe criteria": "fail_safe_design_philosophy",
    "fail safe structure": "fail_safe_design_philosophy",
    "fail safe structures": "fail_safe_design_philosophy",
    "fail safe design philosophy": "fail_safe_design_philosophy",
    "fsdp": "fail_safe_design_philosophy",
    "fsd": "fail_safe_design_philosophy",
    "fail safe philosophy": "fail_safe_design_philosophy",
    "damage tolerant": "damage_tolerant_design",
    "damage-tolerant": "damage_tolerant_design",
    "damagetolerant": "damage_tolerant_design",
    "damage tolerant design": "damage_tolerant_design",
    "damage tolerance": "damage_tolerant_design",
    "damage tolerant approach": "damage_tolerant_design",
    "damage tolerant method": "damage_tolerant_design",
    "damage tolerant principle": "damage_tolerant_design",
    "damage tolerant concept": "damage_tolerant_design",
    "damage tolerant criteria": "damage_tolerant_design",
    "damage tolerant structure": "damage_tolerant_design",
    "damage tolerant structures": "damage_tolerant_design",
    "damage tolerant design philosophy": "damage_tolerant_design",
    "dtdp": "damage_tolerant_design",
    "dtd": "damage_tolerant_design",
    "dt": "damage_tolerant_design",
    "damage tolerance design": "damage_tolerant_design",
    # Stress Analysis Methods
    "stress analysis": "stress_analysis_methods",
    "stress analysis method": "stress_analysis_methods",
    "stress analysis methods": "stress_analysis_methods",
    "stress analysis technique": "stress_analysis_methods",
    "stress analysis techniques": "stress_analysis_methods",
    "stress calculation": "stress_analysis_methods",
    "stress calculations": "stress_analysis_methods",
    "stress evaluation": "stress_analysis_methods",
    "stress evaluation method": "stress_analysis_methods",
    "stress evaluation techniques": "stress_analysis_methods",
    "structural analysis": "stress_analysis_methods",
    "structural analysis method": "stress_analysis_methods",
    "structural analysis techniques": "stress_analysis_methods",
    "finite element analysis": "stress_analysis_methods",
    "fea": "stress_analysis_methods",
    "fem": "stress_analysis_methods",
    "hand calculation": "stress_analysis_methods",
    "hand calculations": "stress_analysis_methods",
    "classical stress analysis": "stress_analysis_methods",
    "analytical stress analysis": "stress_analysis_methods",
    "numerical stress analysis": "stress_analysis_methods",
    "stress modeling": "stress_analysis_methods",
    "stress model": "stress_analysis_methods",
    "stress models": "stress_analysis_methods",
    # Fatigue Life Prediction SN Curves
    "fatigue life": "fatigue_life_prediction_SN_curves",
    "fatigue life prediction": "fatigue_life_prediction_SN_curves",
    "fatigue prediction": "fatigue_life_prediction_SN_curves",
    "fatigue analysis": "fatigue_life_prediction_SN_curves",
    "fatigue curve": "fatigue_life_prediction_SN_curves",
    "fatigue curves": "fatigue_life_prediction_SN_curves",
    "sn curve": "fatigue_life_prediction_SN_curves",
    "s-n curve": "fatigue_life_prediction_SN_curves",
    "sn curves": "fatigue_life_prediction_SN_curves",
    "s-n curves": "fatigue_life_prediction_SN_curves",
    "wohler curve": "fatigue_life_prediction_SN_curves",
    "wohler curves": "fatigue_life_prediction_SN_curves",
    "fatigue test": "fatigue_life_prediction_SN_curves",
    "fatigue testing": "fatigue_life_prediction_SN_curves",
    "fatigue data": "fatigue_life_prediction_SN_curves",
    "fatigue strength": "fatigue_life_prediction_SN_curves",
    "fatigue limit": "fatigue_life_prediction_SN_curves",
    "endurance limit": "fatigue_life_prediction_SN_curves",
    "endurance strength": "fatigue_life_prediction_SN_curves",
    "fatigue failure": "fatigue_life_prediction_SN_curves",
    "fatigue crack": "fatigue_life_prediction_SN_curves",
    "fatigue cracks": "fatigue_life_prediction_SN_curves",
    "fatigue phenomenon": "fatigue_life_prediction_SN_curves",
    "fatigue behavior": "fatigue_life_prediction_SN_curves",
    "fatigue response": "fatigue_life_prediction_SN_curves",
    "fatigue property": "fatigue_life_prediction_SN_curves",
    "fatigue properties": "fatigue_life_prediction_SN_curves",
    # Fracture Mechanics Paris Law
    "fracture mechanics": "fracture_mechanics_paris_law",
    "fracture mechanic": "fracture_mechanics_paris_law",
    "fracture analysis": "fracture_mechanics_paris_law",
    "fracture law": "fracture_mechanics_paris_law",
    "paris law": "fracture_mechanics_paris_law",
    "paris' law": "fracture_mechanics_paris_law",
    "paris equation": "fracture_mechanics_paris_law",
    "crack growth": "fracture_mechanics_paris_law",
    "crack growth rate": "fracture_mechanics_paris_law",
    "crack propagation": "fracture_mechanics_paris_law",
    "crack propagation rate": "fracture_mechanics_paris_law",
    "da/dn": "fracture_mechanics_paris_law",
    "da dn": "fracture_mechanics_paris_law",
    "delta k": "fracture_mechanics_paris_law",
    "stress intensity factor": "fracture_mechanics_paris_law",
    "sif": "fracture_mechanics_paris_law",
    "fracture toughness": "fracture_mechanics_paris_law",
    "kic": "fracture_mechanics_paris_law",
    "fracture criterion": "fracture_mechanics_paris_law",
    "fracture criteria": "fracture_mechanics_paris_law",
    "linear elastic fracture mechanics": "fracture_mechanics_paris_law",
    "lefm": "fracture_mechanics_paris_law",
    "fatigue crack growth": "fracture_mechanics_paris_law",
    "crack tip": "fracture_mechanics_paris_law",
    "crack tip opening displacement": "fracture_mechanics_paris_law",
    "ctod": "fracture_mechanics_paris_law",
    # Composite Materials Carbon Fiber
    "composite": "composite_materials_carbon_fiber",
    "composites": "composite_materials_carbon_fiber",
    "composite material": "composite_materials_carbon_fiber",
    "composite materials": "composite_materials_carbon_fiber",
    "carbon fiber": "composite_materials_carbon_fiber",
    "carbon fibre": "composite_materials_carbon_fiber",
    "carbon fibre reinforced polymer": "composite_materials_carbon_fiber",
    "carbon fiber reinforced polymer": "composite_materials_carbon_fiber",
    "cfrp": "composite_materials_carbon_fiber",
    "carbon fiber composite": "composite_materials_carbon_fiber",
    "carbon fiber composites": "composite_materials_carbon_fiber",
    "carbon fibre composite": "composite_materials_carbon_fiber",
    "carbon fibre composites": "composite_materials_carbon_fiber",
    "graphite epoxy": "composite_materials_carbon_fiber",
    "graphite composite": "composite_materials_carbon_fiber",
    "graphite composites": "composite_materials_carbon_fiber",
    "polymer matrix composite": "composite_materials_carbon_fiber",
    "pmc": "composite_materials_carbon_fiber",
    "fiber reinforced polymer": "composite_materials_carbon_fiber",
    "frp": "composite_materials_carbon_fiber",
    "fiber reinforced plastic": "composite_materials_carbon_fiber",
    "laminate": "composite_materials_carbon_fiber",
    "laminates": "composite_materials_carbon_fiber",
    "composite laminate": "composite_materials_carbon_fiber",
    "composite laminates": "composite_materials_carbon_fiber",
    "unidirectional composite": "composite_materials_carbon_fiber",
    "unidirectional carbon fiber": "composite_materials_carbon_fiber",
    "woven carbon fiber": "composite_materials_carbon_fiber",
    "woven composite": "composite_materials_carbon_fiber",
    # Composite Failure Criteria Tsai Wu
    "composite failure": "composite_failure_criteria_tsai_wu",
    "composite failure criteria": "composite_failure_criteria_tsai_wu",
    "failure criteria": "composite_failure_criteria_tsai_wu",
    "failure criterion": "composite_failure_criteria_tsai_wu",
    "tsai wu": "composite_failure_criteria_tsai_wu",
    "tsai-wu": "composite_failure_criteria_tsai_wu",
    "tsai wu criterion": "composite_failure_criteria_tsai_wu",
    "tsai wu criteria": "composite_failure_criteria_tsai_wu",
    "tsai-wu criterion": "composite_failure_criteria_tsai_wu",
    "tsai-wu criteria": "composite_failure_criteria_tsai_wu",
    "max stress criterion": "composite_failure_criteria_tsai_wu",
    "max strain criterion": "composite_failure_criteria_tsai_wu",
    "hashin criterion": "composite_failure_criteria_tsai_wu",
    "hashin criteria": "composite_failure_criteria_tsai_wu",
    "failure envelope": "composite_failure_criteria_tsai_wu",
    "failure envelopes": "composite_failure_criteria_tsai_wu",
    "failure mode": "composite_failure_criteria_tsai_wu",
    "failure modes": "composite_failure_criteria_tsai_wu",
    "matrix failure": "composite_failure_criteria_tsai_wu",
    "fiber failure": "composite_failure_criteria_tsai_wu",
    "delamination": "composite_failure_criteria_tsai_wu",
    "delaminations": "composite_failure_criteria_tsai_wu",
    "interlaminar failure": "composite_failure_criteria_tsai_wu",
    "intralayer failure": "composite_failure_criteria_tsai_wu",
    "progressive failure": "composite_failure_criteria_tsai_wu",
    # Aluminum Alloys 2024 7075
    "aluminum": "aluminum_alloys_2024_7075",
    "aluminium": "aluminum_alloys_2024_7075",
    "aluminum alloy": "aluminum_alloys_2024_7075",
    "aluminium alloy": "aluminum_alloys_2024_7075",
    "aluminum alloys": "aluminum_alloys_2024_7075",
    "aluminium alloys": "aluminum_alloys_2024_7075",
    "2024": "aluminum_alloys_2024_7075",
    "7075": "aluminum_alloys_2024_7075",
    "2024-t3": "aluminum_alloys_2024_7075",
    "7075-t6": "aluminum_alloys_2024_7075",
    "2024 t3": "aluminum_alloys_2024_7075",
    "7075 t6": "aluminum_alloys_2024_7075",
    "alclad": "aluminum_alloys_2024_7075",
    "duralumin": "aluminum_alloys_2024_7075",
    "duraluminum": "aluminum_alloys_2024_7075",
    "al alloy": "aluminum_alloys_2024_7075",
    "al alloys": "aluminum_alloys_2024_7075",
    "al": "aluminum_alloys_2024_7075",
    "high strength aluminum": "aluminum_alloys_2024_7075",
    "aircraft aluminum": "aluminum_alloys_2024_7075",
    "aircraft alloy": "aluminum_alloys_2024_7075",
    "aircraft alloys": "aluminum_alloys_2024_7075",
    # Corrosion Types Galvanic Pitting
    "corrosion": "corrosion_types_galvanic_pitting",
    "corrosions": "corrosion_types_galvanic_pitting",
    "corrosion type": "corrosion_types_galvanic_pitting",
    "corrosion types": "corrosion_types_galvanic_pitting",
    "galvanic corrosion": "corrosion_types_galvanic_pitting",
    "pitting corrosion": "corrosion_types_galvanic_pitting",
    "intergranular corrosion": "corrosion_types_galvanic_pitting",
    "exfoliation corrosion": "corrosion_types_galvanic_pitting",
    "crevice corrosion": "corrosion_types_galvanic_pitting",
    "stress corrosion": "corrosion_types_galvanic_pitting",
    "stress corrosion cracking": "corrosion_types_galvanic_pitting",
    "scc": "corrosion_types_galvanic_pitting",
    "filiform corrosion": "corrosion_types_galvanic_pitting",
    "uniform corrosion": "corrosion_types_galvanic_pitting",
    "surface corrosion": "corrosion_types_galvanic_pitting",
    "corrosion fatigue": "corrosion_types_galvanic_pitting",
    "corrosion pit": "corrosion_types_galvanic_pitting",
    "corrosion pits": "corrosion_types_galvanic_pitting",
    "galvanic cell": "corrosion_types_galvanic_pitting",
    "anodic corrosion": "corrosion_types_galvanic_pitting",
    "cathodic corrosion": "corrosion_types_galvanic_pitting",
    "oxidation": "corrosion_types_galvanic_pitting",
    "passivation": "corrosion_types_galvanic_pitting",
    "corrosion resistance": "corrosion_types_galvanic_pitting",
    "corrosion resistant": "corrosion_types_galvanic_pitting",
    # NDT Methods Ultrasonic Eddy Current
    "ndt": "ndt_methods_ultrasonic_eddy_current",
    "nondestructive testing": "ndt_methods_ultrasonic_eddy_current",
    "non-destructive testing": "ndt_methods_ultrasonic_eddy_current",
    "non destructive testing": "ndt_methods_ultrasonic_eddy_current",
    "ndt method": "ndt_methods_ultrasonic_eddy_current",
    "ndt methods": "ndt_methods_ultrasonic_eddy_current",
    "ultrasonic testing": "ndt_methods_ultrasonic_eddy_current",
    "ultrasonic inspection": "ndt_methods_ultrasonic_eddy_current",
    "ultrasonics": "ndt_methods_ultrasonic_eddy_current",
    "ut": "ndt_methods_ultrasonic_eddy_current",
    "eddy current": "ndt_methods_ultrasonic_eddy_current",
    "eddy current testing": "ndt_methods_ultrasonic_eddy_current",
    "eddy current inspection": "ndt_methods_ultrasonic_eddy_current",
    "ect": "ndt_methods_ultrasonic_eddy_current",
    "magnetic particle inspection": "ndt_methods_ultrasonic_eddy_current",
    "mpi": "ndt_methods_ultrasonic_eddy_current",
    "dye penetrant inspection": "ndt_methods_ultrasonic_eddy_current",
    "liquid penetrant inspection": "ndt_methods_ultrasonic_eddy_current",
    "penetrant inspection": "ndt_methods_ultrasonic_eddy_current",
    "visual inspection": "ndt_methods_ultrasonic_eddy_current",
    "radiography": "ndt_methods_ultrasonic_eddy_current",
    "x-ray inspection": "ndt_methods_ultrasonic_eddy_current",
    "infrared thermography": "ndt_methods_ultrasonic_eddy_current",
    "shearography": "ndt_methods_ultrasonic_eddy_current",
    "acoustic emission": "ndt_methods_ultrasonic_eddy_current",
    "acoustic emission testing": "ndt_methods_ultrasonic_eddy_current",
    # Structural Repair Manual Procedures
    "structural repair": "structural_repair_manual_procedures",
    "structural repairs": "structural_repair_manual_procedures",
    "repair manual": "structural_repair_manual_procedures",
    "repair manuals": "structural_repair_manual_procedures",
    "structural repair manual": "structural_repair_manual_procedures",
    "structural repair manuals": "structural_repair_manual_procedures",
    "srm": "structural_repair_manual_procedures",
    "repair procedure": "structural_repair_manual_procedures",
    "repair procedures": "structural_repair_manual_procedures",
    "structural repair procedure": "structural_repair_manual_procedures",
    "structural repair procedures": "structural_repair_manual_procedures",
    "maintenance manual": "structural_repair_manual_procedures",
    "maintenance procedures": "structural_repair_manual_procedures",
    "structural maintenance": "structural_repair_manual_procedures",
    "structural maintenance procedure": "structural_repair_manual_procedures",
    "structural maintenance procedures": "structural_repair_manual_procedures",
    "field repair": "structural_repair_manual_procedures",
    "field repairs": "structural_repair_manual_procedures",
    "field repair procedure": "structural_repair_manual_procedures",
    "field repair procedures": "structural_repair_manual_procedures",
    "temporary repair": "structural_repair_manual_procedures",
    "permanent repair": "structural_repair_manual_procedures",
    # Pressurized Fuselage Hoop Stress
    "pressurized fuselage": "pressurized_fuselage_hoop_stress",
    "fuselage pressurization": "pressurized_fuselage_hoop_stress",
    "fuselage pressure": "pressurized_fuselage_hoop_stress",
    "fuselage hoop stress": "pressurized_fuselage_hoop_stress",
    "hoop stress": "pressurized_fuselage_hoop_stress",
    "hoop stresses": "pressurized_fuselage_hoop_stress",
    "circumferential stress": "pressurized_fuselage_hoop_stress",
    "circumferential stresses": "pressurized_fuselage_hoop_stress",
    "longitudinal stress": "pressurized_fuselage_hoop_stress",
    "longitudinal stresses": "pressurized_fuselage_hoop_stress",
    "fuselage stress": "pressurized_fuselage_hoop_stress",
    "fuselage stresses": "pressurized_fuselage_hoop_stress",
    "cylinder stress": "pressurized_fuselage_hoop_stress",
    "cylinder stresses": "pressurized_fuselage_hoop_stress",
    "thin wall cylinder": "pressurized_fuselage_hoop_stress",
    "thin walled cylinder": "pressurized_fuselage_hoop_stress",
    "thin-walled cylinder": "pressurized_fuselage_hoop_stress",
    "thin wall pressure vessel": "pressurized_fuselage_hoop_stress",
    "thin walled pressure vessel": "pressurized_fuselage_hoop_stress",
    "thin-walled pressure vessel": "pressurized_fuselage_hoop_stress",
    "pressure vessel": "pressurized_fuselage_hoop_stress",
    "pressure vessels": "pressurized_fuselage_hoop_stress",
    "fuselage shell": "pressurized_fuselage_hoop_stress",
    "fuselage shell stress": "pressurized_fuselage_hoop_stress",
    "fuselage shell stresses": "pressurized_fuselage_hoop_stress",
    # Wing Structural Design Spar Rib Skin
    "wing structure": "wing_structural_design_spar_rib_skin",
    "wing structures": "wing_structural_design_spar_rib_skin",
    "wing structural design": "wing_structural_design_spar_rib_skin",
    "wing design": "wing_structural_design_spar_rib_skin",
    "wing spar": "wing_structural_design_spar_rib_skin",
    "wing spars": "wing_structural_design_spar_rib_skin",
    "spar": "wing_structural_design_spar_rib_skin",
    "spars": "wing_structural_design_spar_rib_skin",
    "wing rib": "wing_structural_design_spar_rib_skin",
    "wing ribs": "wing_structural_design_spar_rib_skin",
    "rib": "wing_structural_design_spar_rib_skin",
    "ribs": "wing_structural_design_spar_rib_skin",
    "wing skin": "wing_structural_design_spar_rib_skin",
    "wing skins": "wing_structural_design_spar_rib_skin",
    "skin": "wing_structural_design_spar_rib_skin",
    "skins": "wing_structural_design_spar_rib_skin",
    "wing box": "wing_structural_design_spar_rib_skin",
    "wing panel": "wing_structural_design_spar_rib_skin",
    "wing panels": "wing_structural_design_spar_rib_skin",
    "wing cover": "wing_structural_design_spar_rib_skin",
    "wing covers": "wing_structural_design_spar_rib_skin",
    "wing assembly": "wing_structural_design_spar_rib_skin",
    "wing assemblies": "wing_structural_design_spar_rib_skin",
    "wing substructure": "wing_structural_design_spar_rib_skin",
    "wing substructures": "wing_structural_design_spar_rib_skin",
    "wing chord": "wing_structural_design_spar_rib_skin",
    "wing span": "wing_structural_design_spar_rib_skin",
    # Certification AC25571 Damage Tolerance
    "certification": "certification_AC25571_damage_tolerance",
    "certify": "certification_AC25571_damage_tolerance",
    "certified": "certification_AC25571_damage_tolerance",
    "certification requirement": "certification_AC25571_damage_tolerance",
    "certification requirements": "certification_AC25571_damage_tolerance",
    "ac 25.571": "certification_AC25571_damage_tolerance",
    "ac25.571": "certification_AC25571_damage_tolerance",
    "ac25571": "certification_AC25571_damage_tolerance",
    "ac 25571": "certification_AC25571_damage_tolerance",
    "advisory circular 25.571": "certification_AC25571_damage_tolerance",
    "advisory circular 25571": "certification_AC25571_damage_tolerance",
    "advisory circular ac 25.571": "certification_AC25571_damage_tolerance",
    "advisory circular ac25571": "certification_AC25571_damage_tolerance",
    "damage tolerance certification": "certification_AC25571_damage_tolerance",
    "damage tolerance requirement": "certification_AC25571_damage_tolerance",
    "damage tolerance requirements": "certification_AC25571_damage_tolerance",
    "damage tolerant certification": "certification_AC25571_damage_tolerance",
    "damage tolerant requirements": "certification_AC25571_damage_tolerance",
    "faa certification": "certification_AC25571_damage_tolerance",
    "faa ac 25.571": "certification_AC25571_damage_tolerance",
    "faa ac25571": "certification_AC25571_damage_tolerance",
    "faa advisory circular": "certification_AC25571_damage_tolerance",
    "faa advisory circular 25.571": "certification_AC25571_damage_tolerance",
    "faa advisory circular ac25571": "certification_AC25571_damage_tolerance",
    # Fastener Selection Rivets HiLok
    "fastener": "fastener_selection_rivets_hilok",
    "fasteners": "fastener_selection_rivets_hilok",
    "fastener selection": "fastener_selection_rivets_hilok",
    "fastener type": "fastener_selection_rivets_hilok",
    "fastener types": "fastener_selection_rivets_hilok",
    "rivet": "fastener_selection_rivets_hilok",
    "rivets": "fastener_selection_rivets_hilok",
    "solid rivet": "fastener_selection_rivets_hilok",
    "solid rivets": "fastener_selection_rivets_hilok",
    "blind rivet": "fastener_selection_rivets_hilok",
    "blind rivets": "fastener_selection_rivets_hilok",
    "hilok": "fastener_selection_rivets_hilok",
    "hi-lok": "fastener_selection_rivets_hilok",
    "hi lok": "fastener_selection_rivets_hilok",
    "hiloks": "fastener_selection_rivets_hilok",
    "hi-loks": "fastener_selection_rivets_hilok",
    "hi loks": "fastener_selection_rivets_hilok",
    "lockbolt": "fastener_selection_rivets_hilok",
    "lockbolts": "fastener_selection_rivets_hilok",
    "bolt": "fastener_selection_rivets_hilok",
    "bolts": "fastener_selection_rivets_hilok",
    "nutplate": "fastener_selection_rivets_hilok",
    "nutplates": "fastener_selection_rivets_hilok",
    "screw": "fastener_selection_rivets_hilok",
    "screws": "fastener_selection_rivets_hilok",
    "pin": "fastener_selection_rivets_hilok",
    "pins": "fastener_selection_rivets_hilok",
    "washer": "fastener_selection_rivets_hilok",
    "washers": "fastener_selection_rivets_hilok",
    "fastener installation": "fastener_selection_rivets_hilok",
    "fastener removal": "fastener_selection_rivets_hilok",
    "fastener inspection": "fastener_selection_rivets_hilok",
    "fastener maintenance": "fastener_selection_rivets_hilok",
    "fastener failure": "fastener_selection_rivets_hilok",
    "fastener failures": "fastener_selection_rivets_hilok",
    "fastener fatigue": "fastener_selection_rivets_hilok",
    "fastener joint": "fastener_selection_rivets_hilok",
    "fastener joints": "fastener_selection_rivets_hilok",
    "joint fastener": "fastener_selection_rivets_hilok",
    "joint fasteners": "fastener_selection_rivets_hilok",
    "mechanical fastener": "fastener_selection_rivets_hilok",
    "mechanical fasteners": "fastener_selection_rivets_hilok",
    "structural fastener": "fastener_selection_rivets_hilok",
    "structural fasteners": "fastener_selection_rivets_hilok",
}

# Add misspellings and common typos for coverage
_misspellings = {
    "safel ife": "safe_life_design_philosophy",
    "fail safe": "fail_safe_design_philosophy",
    "damge tolerant": "damage_tolerant_design",
    "stres analysis": "stress_analysis_methods",
    "fatige life": "fatigue_life_prediction_SN_curves",
    "fracture mechancis": "fracture_mechanics_paris_law",
    "composite materals": "composite_materials_carbon_fiber",
    "tsaiwu": "composite_failure_criteria_tsai_wu",
    "alumnium": "aluminum_alloys_2024_7075",
    "corosion": "corrosion_types_galvanic_pitting",
    "nddt": "ndt_methods_ultrasonic_eddy_current",
    "structural repiar": "structural_repair_manual_procedures",
    "pressurised fuselage": "pressurized_fuselage_hoop_stress",
    "wing structre": "wing_structural_design_spar_rib_skin",
    "certifcation": "certification_AC25571_damage_tolerance",
    "fastner": "fastener_selection_rivets_hilok",
}
SEMANTIC_MAP.update(_misspellings)

# Build related terms index for fast lookup
_RELATED_TERMS = {}
for k, v in SEMANTIC_MAP.items():
    _RELATED_TERMS.setdefault(v, set()).add(k)
for v in _RELATED_TERMS:
    _RELATED_TERMS[v] = sorted(_RELATED_TERMS[v])

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (
        actual_count == _EXPECTED_ENTRY_COUNT
        and actual_hash == _MAP_INTEGRITY_HASH
    )
    return {
        "status": "OK" if is_valid else "FAIL",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_input(term):
    if not isinstance(term, str):
        return ""
    t = term.lower().strip()
    t = re.sub(r"[\s\-_]+", " ", t)
    t = t.replace(".", "").replace(",", "")
    t = t.strip()
    return t

def normalize_term(term):
    t = _normalize_input(term)
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try alternative normalization
    t2 = t.replace(" ", "")
    if t2 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t2]
    t3 = t.replace(" ", "-")
    if t3 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t3]
    t4 = t.replace(" ", "_")
    if t4 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t4]
    return None

def get_related_terms(term):
    norm = normalize_term(term)
    if not norm:
        return []
    return list(_RELATED_TERMS.get(norm, []))

def get_all_mappings():
    return dict(SEMANTIC_MAP)