import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "G04 Engine Team"
SEMANTIC_MAP_ENGINE = "G04_gis_layer_integrator"

# --- SEMANTIC MAP ---

SEMANTIC_MAP = {
    # Well Data
    "rrc well": "well",
    "rrc wells": "well",
    "well": "well",
    "wells": "well",
    "oil well": "well",
    "gas well": "well",
    "injection well": "well",
    "production well": "well",
    "well bore": "well",
    "wellbore": "well",
    "wellhead": "wellhead",
    "well pad": "well pad",
    "well location": "well",
    "well site": "well",
    "well data": "well",
    "well info": "well",
    "well information": "well",
    "well identifier": "well id",
    "well id": "well id",
    "api number": "well id",
    "api no": "well id",
    "api code": "well id",
    "api": "well id",
    "well permit": "well permit",
    "permit number": "well permit",
    "permit no": "well permit",
    "permit": "well permit",
    "well status": "well status",
    "status": "well status",
    "completion": "completion",
    "completion date": "completion",
    "completion status": "completion",
    "spud date": "spud date",
    "spud": "spud date",
    "drill date": "spud date",
    "operator": "operator",
    "well operator": "operator",
    "lease operator": "operator",
    "operator name": "operator",
    "operator id": "operator id",
    "operator identifier": "operator id",
    "lease name": "lease",
    "lease": "lease",
    "lease id": "lease id",
    "lease identifier": "lease id",
    "lease number": "lease id",
    "lease no": "lease id",
    "lease boundary": "lease boundary",
    "lease boundaries": "lease boundary",
    "lease area": "lease boundary",
    "lease polygon": "lease boundary",
    "lease map": "lease boundary",
    "lease overlay": "lease boundary",
    "lease integration": "lease boundary",
    "lease qa/qc": "lease boundary",
    "lease quality": "lease boundary",
    "lease validation": "lease boundary",
    "lease check": "lease boundary",
    "lease review": "lease boundary",
    "lease audit": "lease boundary",
    "lease verification": "lease boundary",
    "lease join": "lease boundary",
    "lease merge": "lease boundary",
    "lease combine": "lease boundary",
    "lease union": "lease boundary",
    "lease dissolve": "lease boundary",
    "lease intersect": "lease boundary",
    "lease clip": "lease boundary",
    "lease buffer": "lease boundary",
    "lease centroid": "lease boundary",
    "lease geometry": "lease boundary",
    "lease feature": "lease boundary",
    "lease attribute": "lease boundary",
    "lease record": "lease boundary",
    "lease table": "lease boundary",
    "lease layer": "lease boundary",
    "lease shapefile": "lease boundary",
    "lease geojson": "lease boundary",
    "lease kml": "lease boundary",
    "lease gdb": "lease boundary",
    "lease database": "lease boundary",
    "lease spatial": "lease boundary",
    "lease gis": "lease boundary",
    "lease map layer": "lease boundary",
    "lease mapping": "lease boundary",
    "lease cartography": "lease boundary",
    "lease symbology": "lease boundary",
    "lease styling": "lease boundary",
    "lease crs": "lease boundary",
    "lease projection": "lease boundary",
    "lease coordinate": "lease boundary",
    "lease datum": "lease boundary",
    "lease transformation": "lease boundary",
    "lease alignment": "lease boundary",
    "lease overlay validation": "lease boundary",
    "lease overlay qa/qc": "lease boundary",
    "lease overlay check": "lease boundary",
    "lease overlay review": "lease boundary",
    "lease overlay audit": "lease boundary",
    "lease overlay verification": "lease boundary",
    "lease overlay join": "lease boundary",
    "lease overlay merge": "lease boundary",
    "lease overlay combine": "lease boundary",
    "lease overlay union": "lease boundary",
    "lease overlay dissolve": "lease boundary",
    "lease overlay intersect": "lease boundary",
    "lease overlay clip": "lease boundary",
    "lease overlay buffer": "lease boundary",
    "lease overlay centroid": "lease boundary",
    "lease overlay geometry": "lease boundary",
    "lease overlay feature": "lease boundary",
    "lease overlay attribute": "lease boundary",
    "lease overlay record": "lease boundary",
    "lease overlay table": "lease boundary",
    "lease overlay layer": "lease boundary",
    "lease overlay shapefile": "lease boundary",
    "lease overlay geojson": "lease boundary",
    "lease overlay kml": "lease boundary",
    "lease overlay gdb": "lease boundary",
    "lease overlay database": "lease boundary",
    "lease overlay spatial": "lease boundary",
    "lease overlay gis": "lease boundary",
    "lease overlay map layer": "lease boundary",
    "lease overlay mapping": "lease boundary",
    "lease overlay cartography": "lease boundary",
    "lease overlay symbology": "lease boundary",
    "lease overlay styling": "lease boundary",
    "lease overlay crs": "lease boundary",
    "lease overlay projection": "lease boundary",
    "lease overlay coordinate": "lease boundary",
    "lease overlay datum": "lease boundary",
    "lease overlay transformation": "lease boundary",
    "lease overlay alignment": "lease boundary",
    # Pipeline
    "pipeline": "pipeline",
    "pipelines": "pipeline",
    "pipeline route": "pipeline route",
    "pipeline routing": "pipeline route",
    "pipeline path": "pipeline route",
    "pipeline alignment": "pipeline route",
    "pipeline overlay": "pipeline route",
    "pipeline integration": "pipeline route",
    "pipeline mapping": "pipeline route",
    "pipeline map": "pipeline route",
    "pipeline layer": "pipeline route",
    "pipeline feature": "pipeline route",
    "pipeline attribute": "pipeline route",
    "pipeline record": "pipeline route",
    "pipeline table": "pipeline route",
    "pipeline shapefile": "pipeline route",
    "pipeline geojson": "pipeline route",
    "pipeline kml": "pipeline route",
    "pipeline gdb": "pipeline route",
    "pipeline database": "pipeline route",
    "pipeline spatial": "pipeline route",
    "pipeline gis": "pipeline route",
    "pipeline cartography": "pipeline route",
    "pipeline symbology": "pipeline route",
    "pipeline styling": "pipeline route",
    "pipeline crs": "pipeline route",
    "pipeline projection": "pipeline route",
    "pipeline coordinate": "pipeline route",
    "pipeline datum": "pipeline route",
    "pipeline transformation": "pipeline route",
    "pipeline generalization": "pipeline route",
    "pipeline simplification": "pipeline route",
    "pipeline validation": "pipeline route",
    "pipeline qa/qc": "pipeline route",
    "pipeline check": "pipeline route",
    "pipeline review": "pipeline route",
    "pipeline audit": "pipeline route",
    "pipeline verification": "pipeline route",
    "pipeline join": "pipeline route",
    "pipeline merge": "pipeline route",
    "pipeline combine": "pipeline route",
    "pipeline union": "pipeline route",
    "pipeline dissolve": "pipeline route",
    "pipeline intersect": "pipeline route",
    "pipeline clip": "pipeline route",
    "pipeline buffer": "pipeline route",
    "pipeline centroid": "pipeline route",
    "pipeline geometry": "pipeline route",
    # Surface Features
    "surface feature": "surface feature",
    "surface features": "surface feature",
    "surface overlay": "surface feature",
    "surface integration": "surface feature",
    "surface mapping": "surface feature",
    "surface map": "surface feature",
    "surface layer": "surface feature",
    "surface attribute": "surface feature",
    "surface record": "surface feature",
    "surface table": "surface feature",
    "surface shapefile": "surface feature",
    "surface geojson": "surface feature",
    "surface kml": "surface feature",
    "surface gdb": "surface feature",
    "surface database": "surface feature",
    "surface spatial": "surface feature",
    "surface gis": "surface feature",
    "surface cartography": "surface feature",
    "surface symbology": "surface feature",
    "surface styling": "surface feature",
    "surface crs": "surface feature",
    "surface projection": "surface feature",
    "surface coordinate": "surface feature",
    "surface datum": "surface feature",
    "surface transformation": "surface feature",
    "surface alignment": "surface feature",
    "surface validation": "surface feature",
    "surface qa/qc": "surface feature",
    "surface check": "surface feature",
    "surface review": "surface feature",
    "surface audit": "surface feature",
    "surface verification": "surface feature",
    "surface join": "surface feature",
    "surface merge": "surface feature",
    "surface combine": "surface feature",
    "surface union": "surface feature",
    "surface dissolve": "surface feature",
    "surface intersect": "surface feature",
    "surface clip": "surface feature",
    "surface buffer": "surface feature",
    "surface centroid": "surface feature",
    "surface geometry": "surface feature",
    # Surface Owner
    "surface owner": "surface owner",
    "surface owners": "surface owner",
    "surface boundary": "surface owner boundary",
    "surface owner boundary": "surface owner boundary",
    "surface owner boundaries": "surface owner boundary",
    "surface owner overlay": "surface owner boundary",
    "surface owner integration": "surface owner boundary",
    "surface owner mapping": "surface owner boundary",
    "surface owner map": "surface owner boundary",
    "surface owner layer": "surface owner boundary",
    "surface owner attribute": "surface owner boundary",
    "surface owner record": "surface owner boundary",
    "surface owner table": "surface owner boundary",
    "surface owner shapefile": "surface owner boundary",
    "surface owner geojson": "surface owner boundary",
    "surface owner kml": "surface owner boundary",
    "surface owner gdb": "surface owner boundary",
    "surface owner database": "surface owner boundary",
    "surface owner spatial": "surface owner boundary",
    "surface owner gis": "surface owner boundary",
    "surface owner cartography": "surface owner boundary",
    "surface owner symbology": "surface owner boundary",
    "surface owner styling": "surface owner boundary",
    "surface owner crs": "surface owner boundary",
    "surface owner projection": "surface owner boundary",
    "surface owner coordinate": "surface owner boundary",
    "surface owner datum": "surface owner boundary",
    "surface owner transformation": "surface owner boundary",
    "surface owner alignment": "surface owner boundary",
    "surface owner validation": "surface owner boundary",
    "surface owner qa/qc": "surface owner boundary",
    "surface owner check": "surface owner boundary",
    "surface owner review": "surface owner boundary",
    "surface owner audit": "surface owner boundary",
    "surface owner verification": "surface owner boundary",
    "surface owner join": "surface owner boundary",
    "surface owner merge": "surface owner boundary",
    "surface owner combine": "surface owner boundary",
    "surface owner union": "surface owner boundary",
    "surface owner dissolve": "surface owner boundary",
    "surface owner intersect": "surface owner boundary",
    "surface owner clip": "surface owner boundary",
    "surface owner buffer": "surface owner boundary",
    "surface owner centroid": "surface owner boundary",
    "surface owner geometry": "surface owner boundary",
    # Mineral Owner
    "mineral owner": "mineral owner",
    "mineral owners": "mineral owner",
    "mineral boundary": "mineral owner boundary",
    "mineral owner boundary": "mineral owner boundary",
    "mineral owner boundaries": "mineral owner boundary",
    "mineral owner overlay": "mineral owner boundary",
    "mineral owner integration": "mineral owner boundary",
    "mineral owner mapping": "mineral owner boundary",
    "mineral owner map": "mineral owner boundary",
    "mineral owner layer": "mineral owner boundary",
    "mineral owner attribute": "mineral owner boundary",
    "mineral owner record": "mineral owner boundary",
    "mineral owner table": "mineral owner boundary",
    "mineral owner shapefile": "mineral owner boundary",
    "mineral owner geojson": "mineral owner boundary",
    "mineral owner kml": "mineral owner boundary",
    "mineral owner gdb": "mineral owner boundary",
    "mineral owner database": "mineral owner boundary",
    "mineral owner spatial": "mineral owner boundary",
    "mineral owner gis": "mineral owner boundary",
    "mineral owner cartography": "mineral owner boundary",
    "mineral owner symbology": "mineral owner boundary",
    "mineral owner styling": "mineral owner boundary",
    "mineral owner crs": "mineral owner boundary",
    "mineral owner projection": "mineral owner boundary",
    "mineral owner coordinate": "mineral owner boundary",
    "mineral owner datum": "mineral owner boundary",
    "mineral owner transformation": "mineral owner boundary",
    "mineral owner alignment": "mineral owner boundary",
    "mineral owner validation": "mineral owner boundary",
    "mineral owner qa/qc": "mineral owner boundary",
    "mineral owner check": "mineral owner boundary",
    "mineral owner review": "mineral owner boundary",
    "mineral owner audit": "mineral owner boundary",
    "mineral owner verification": "mineral owner boundary",
    "mineral owner join": "mineral owner boundary",
    "mineral owner merge": "mineral owner boundary",
    "mineral owner combine": "mineral owner boundary",
    "mineral owner union": "mineral owner boundary",
    "mineral owner dissolve": "mineral owner boundary",
    "mineral owner intersect": "mineral owner boundary",
    "mineral owner clip": "mineral owner boundary",
    "mineral owner buffer": "mineral owner boundary",
    "mineral owner centroid": "mineral owner boundary",
    "mineral owner geometry": "mineral owner boundary",
    # Unit Boundary
    "unit boundary": "unit boundary",
    "unit boundaries": "unit boundary",
    "unit overlay": "unit boundary",
    "unit integration": "unit boundary",
    "unit mapping": "unit boundary",
    "unit map": "unit boundary",
    "unit layer": "unit boundary",
    "unit attribute": "unit boundary",
    "unit record": "unit boundary",
    "unit table": "unit boundary",
    "unit shapefile": "unit boundary",
    "unit geojson": "unit boundary",
    "unit kml": "unit boundary",
    "unit gdb": "unit boundary",
    "unit database": "unit boundary",
    "unit spatial": "unit boundary",
    "unit gis": "unit boundary",
    "unit cartography": "unit boundary",
    "unit symbology": "unit boundary",
    "unit styling": "unit boundary",
    "unit crs": "unit boundary",
    "unit projection": "unit boundary",
    "unit coordinate": "unit boundary",
    "unit datum": "unit boundary",
    "unit transformation": "unit boundary",
    "unit alignment": "unit boundary",
    "unit validation": "unit boundary",
    "unit qa/qc": "unit boundary",
    "unit check": "unit boundary",
    "unit review": "unit boundary",
    "unit audit": "unit boundary",
    "unit verification": "unit boundary",
    "unit join": "unit boundary",
    "unit merge": "unit boundary",
    "unit combine": "unit boundary",
    "unit union": "unit boundary",
    "unit dissolve": "unit boundary",
    "unit intersect": "unit boundary",
    "unit clip": "unit boundary",
    "unit buffer": "unit boundary",
    "unit centroid": "unit boundary",
    "unit geometry": "unit boundary",
    # Survey Abstract
    "survey abstract": "survey abstract",
    "survey abstracts": "survey abstract",
    "survey boundary": "survey abstract boundary",
    "survey abstract boundary": "survey abstract boundary",
    "survey abstract boundaries": "survey abstract boundary",
    "survey abstract overlay": "survey abstract boundary",
    "survey abstract integration": "survey abstract boundary",
    "survey abstract mapping": "survey abstract boundary",
    "survey abstract map": "survey abstract boundary",
    "survey abstract layer": "survey abstract boundary",
    "survey abstract attribute": "survey abstract boundary",
    "survey abstract record": "survey abstract boundary",
    "survey abstract table": "survey abstract boundary",
    "survey abstract shapefile": "survey abstract boundary",
    "survey abstract geojson": "survey abstract boundary",
    "survey abstract kml": "survey abstract boundary",
    "survey abstract gdb": "survey abstract boundary",
    "survey abstract database": "survey abstract boundary",
    "survey abstract spatial": "survey abstract boundary",
    "survey abstract gis": "survey abstract boundary",
    "survey abstract cartography": "survey abstract boundary",
    "survey abstract symbology": "survey abstract boundary",
    "survey abstract styling": "survey abstract boundary",
    "survey abstract crs": "survey abstract boundary",
    "survey abstract projection": "survey abstract boundary",
    "survey abstract coordinate": "survey abstract boundary",
    "survey abstract datum": "survey abstract boundary",
    "survey abstract transformation": "survey abstract boundary",
    "survey abstract alignment": "survey abstract boundary",
    "survey abstract validation": "survey abstract boundary",
    "survey abstract qa/qc": "survey abstract boundary",
    "survey abstract check": "survey abstract boundary",
    "survey abstract review": "survey abstract boundary",
    "survey abstract audit": "survey abstract boundary",
    "survey abstract verification": "survey abstract boundary",
    "survey abstract join": "survey abstract boundary",
    "survey abstract merge": "survey abstract boundary",
    "survey abstract combine": "survey abstract boundary",
    "survey abstract union": "survey abstract boundary",
    "survey abstract dissolve": "survey abstract boundary",
    "survey abstract intersect": "survey abstract boundary",
    "survey abstract clip": "survey abstract boundary",
    "survey abstract buffer": "survey abstract boundary",
    "survey abstract centroid": "survey abstract boundary",
    "survey abstract geometry": "survey abstract boundary",
    # County Boundary
    "county boundary": "county boundary",
    "county boundaries": "county boundary",
    "county overlay": "county boundary",
    "county integration": "county boundary",
    "county mapping": "county boundary",
    "county map": "county boundary",
    "county layer": "county boundary",
    "county attribute": "county boundary",
    "county record": "county boundary",
    "county table": "county boundary",
    "county shapefile": "county boundary",
    "county geojson": "county boundary",
    "county kml": "county boundary",
    "county gdb": "county boundary",
    "county database": "county boundary",
    "county spatial": "county boundary",
    "county gis": "county boundary",
    "county cartography": "county boundary",
    "county symbology": "county boundary",
    "county styling": "county boundary",
    "county crs": "county boundary",
    "county projection": "county boundary",
    "county coordinate": "county boundary",
    "county datum": "county boundary",
    "county transformation": "county boundary",
    "county alignment": "county boundary",
    "county validation": "county boundary",
    "county qa/qc": "county boundary",
    "county check": "county boundary",
    "county review": "county boundary",
    "county audit": "county boundary",
    "county verification": "county boundary",
    "county join": "county boundary",
    "county merge": "county boundary",
    "county combine": "county boundary",
    "county union": "county boundary",
    "county dissolve": "county boundary",
    "county intersect": "county boundary",
    "county clip": "county boundary",
    "county buffer": "county boundary",
    "county centroid": "county boundary",
    "county geometry": "county boundary",
    # Road Infrastructure
    "road": "road infrastructure",
    "roads": "road infrastructure",
    "road infrastructure": "road infrastructure",
    "road overlay": "road infrastructure",
    "road integration": "road infrastructure",
    "road mapping": "road infrastructure",
    "road map": "road infrastructure",
    "road layer": "road infrastructure",
    "road attribute": "road infrastructure",
    "road record": "road infrastructure",
    "road table": "road infrastructure",
    "road shapefile": "road infrastructure",
    "road geojson": "road infrastructure",
    "road kml": "road infrastructure",
    "road gdb": "road infrastructure",
    "road database": "road infrastructure",
    "road spatial": "road infrastructure",
    "road gis": "road infrastructure",
    "road cartography": "road infrastructure",
    "road symbology": "road infrastructure",
    "road styling": "road infrastructure",
    "road crs": "road infrastructure",
    "road projection": "road infrastructure",
    "road coordinate": "road infrastructure",
    "road datum": "road infrastructure",
    "road transformation": "road infrastructure",
    "road alignment": "road infrastructure",
    "road validation": "road infrastructure",
    "road qa/qc": "road infrastructure",
    "road check": "road infrastructure",
    "road review": "road infrastructure",
    "road audit": "road infrastructure",
    "road verification": "road infrastructure",
    "road join": "road infrastructure",
    "road merge": "road infrastructure",
    "road combine": "road infrastructure",
    "road union": "road infrastructure",
    "road dissolve": "road infrastructure",
    "road intersect": "road infrastructure",
    "road clip": "road infrastructure",
    "road buffer": "road infrastructure",
    "road centroid": "road infrastructure",
    "road geometry": "road infrastructure",
    # Topographic Features
    "topography": "topographic feature",
    "topographic feature": "topographic feature",
    "topographic features": "topographic feature",
    "topo feature": "topographic feature",
    "topo features": "topographic feature",
    "topo": "topographic feature",
    "topographic overlay": "topographic feature",
    "topographic integration": "topographic feature",
    "topographic mapping": "topographic feature",
    "topographic map": "topographic feature",
    "topographic layer": "topographic feature",
    "topographic attribute": "topographic feature",
    "topographic record": "topographic feature",
    "topographic table": "topographic feature",
    "topographic shapefile": "topographic feature",
    "topographic geojson": "topographic feature",
    "topographic kml": "topographic feature",
    "topographic gdb": "topographic feature",
    "topographic database": "topographic feature",
    "topographic spatial": "topographic feature",
    "topographic gis": "topographic feature",
    "topographic cartography": "topographic feature",
    "topographic symbology": "topographic feature",
    "topographic styling": "topographic feature",
    "topographic crs": "topographic feature",
    "topographic projection": "topographic feature",
    "topographic coordinate": "topographic feature",
    "topographic datum": "topographic feature",
    "topographic transformation": "topographic feature",
    "topographic alignment": "topographic feature",
    "topographic validation": "topographic feature",
    "topographic qa/qc": "topographic feature",
    "topographic check": "topographic feature",
    "topographic review": "topographic feature",
    "topographic audit": "topographic feature",
    "topographic verification": "topographic feature",
    "topographic join": "topographic feature",
    "topographic merge": "topographic feature",
    "topographic combine": "topographic feature",
    "topographic union": "topographic feature",
    "topographic dissolve": "topographic feature",
    "topographic intersect": "topographic feature",
    "topographic clip": "topographic feature",
    "topographic buffer": "topographic feature",
    "topographic centroid": "topographic feature",
    "topographic geometry": "topographic feature",
    # Hydrology
    "hydrology": "hydrology",
    "hydrologic feature": "hydrology",
    "hydrologic features": "hydrology",
    "hydro feature": "hydrology",
    "hydro features": "hydrology",
    "hydro": "hydrology",
    "hydrology overlay": "hydrology",
    "hydrology integration": "hydrology",
    "hydrology mapping": "hydrology",
    "hydrology map": "hydrology",
    "hydrology layer": "hydrology",
    "hydrology attribute": "hydrology",
    "hydrology record": "hydrology",
    "hydrology table": "hydrology",
    "hydrology shapefile": "hydrology",
    "hydrology geojson": "hydrology",
    "hydrology kml": "hydrology",
    "hydrology gdb": "hydrology",
    "hydrology database": "hydrology",
    "hydrology spatial": "hydrology",
    "hydrology gis": "hydrology",
    "hydrology cartography": "hydrology",
    "hydrology symbology": "hydrology",
    "hydrology styling": "hydrology",
    "hydrology crs": "hydrology",
    "hydrology projection": "hydrology",
    "hydrology coordinate": "hydrology",
    "hydrology datum": "hydrology",
    "hydrology transformation": "hydrology",
    "hydrology alignment": "hydrology",
    "hydrology validation": "hydrology",
    "hydrology qa/qc": "hydrology",
    "hydrology check": "hydrology",
    "hydrology review": "hydrology",
    "hydrology audit": "hydrology",
    "hydrology verification": "hydrology",
    "hydrology join": "hydrology",
    "hydrology merge": "hydrology",
    "hydrology combine": "hydrology",
    "hydrology union": "hydrology",
    "hydrology dissolve": "hydrology",
    "hydrology intersect": "hydrology",
    "hydrology clip": "hydrology",
    "hydrology buffer": "hydrology",
    "hydrology centroid": "hydrology",
    "hydrology geometry": "hydrology",
    "hydrology conflict resolution": "hydrology",
    "hydrology conflict": "hydrology",
    "hydrology resolution": "hydrology",
    # Soil Classification
    "soil": "soil classification",
    "soils": "soil classification",
    "soil classification": "soil classification",
    "soil overlay": "soil classification",
    "soil integration": "soil classification",
    "soil mapping": "soil classification",
    "soil map": "soil classification",
    "soil layer": "soil classification",
    "soil attribute": "soil classification",
    "soil record": "soil classification",
    "soil table": "soil classification",
    "soil shapefile": "soil classification",
    "soil geojson": "soil classification",
    "soil kml": "soil classification",
    "soil gdb": "soil classification",
    "soil database": "soil classification",
    "soil spatial": "soil classification",
    "soil gis": "soil classification",
    "soil cartography": "soil classification",
    "soil symbology": "soil classification",
    "soil styling": "soil classification",
    "soil crs": "soil classification",
    "soil projection": "soil classification",
    "soil coordinate": "soil classification",
    "soil datum": "soil classification",
    "soil transformation": "soil classification",
    "soil alignment": "soil classification",
    "soil validation": "soil classification",
    "soil qa/qc": "soil classification",
    "soil check": "soil classification",
    "soil review": "soil classification",
    "soil audit": "soil classification",
    "soil verification": "soil classification",
    "soil join": "soil classification",
    "soil merge": "soil classification",
    "soil combine": "soil classification",
    "soil union": "soil classification",
    "soil dissolve": "soil classification",
    "soil intersect": "soil classification",
    "soil clip": "soil classification",
    "soil buffer": "soil classification",
    "soil centroid": "soil classification",
    "soil geometry": "soil classification",
    # Land Use Classification
    "land use": "land use classification",
    "land use classification": "land use classification",
    "land use overlay": "land use classification",
    "land use integration": "land use classification",
    "land use mapping": "land use classification",
    "land use map": "land use classification",
    "land use layer": "land use classification",
    "land use attribute": "land use classification",
    "land use record": "land use classification",
    "land use table": "land use classification",
    "land use shapefile": "land use classification",
    "land use geojson": "land use classification",
    "land use kml": "land use classification",
    "land use gdb": "land use classification",
    "land use database": "land use classification",
    "land use spatial": "land use classification",
    "land use gis": "land use classification",
    "land use cartography": "land use classification",
    "land use symbology": "land use classification",
    "land use styling": "land use classification",
    "land use crs": "land use classification",
    "land use projection": "land use classification",
    "land use coordinate": "land use classification",
    "land use datum": "land use classification",
    "land use transformation": "land use classification",
    "land use alignment": "land use classification",
    "land use validation": "land use classification",
    "land use qa/qc": "land use classification",
    "land use check": "land use classification",
    "land use review": "land use classification",
    "land use audit": "land use classification",
    "land use verification": "land use classification",
    "land use join": "land use classification",
    "land use merge": "land use classification",
    "land use combine": "land use classification",
    "land use union": "land use classification",
    "land use dissolve": "land use classification",
    "land use intersect": "land use classification",
    "land use clip": "land use classification",
    "land use buffer": "land use classification",
    "land use centroid": "land use classification",
    "land use geometry": "land use classification",
    # Aerial Imagery
    "aerial imagery": "aerial imagery",
    "aerial image": "aerial imagery",
    "aerial images": "aerial imagery",
    "aerial overlay": "aerial imagery",
    "aerial integration": "aerial imagery",
    "aerial mapping": "aerial imagery",
    "aerial map": "aerial imagery",
    "aerial layer": "aerial imagery",
    "aerial attribute": "aerial imagery",
    "aerial record": "aerial imagery",
    "aerial table": "aerial imagery",
    "aerial shapefile": "aerial imagery",
    "aerial geojson": "aerial imagery",
    "aerial kml": "aerial imagery",
    "aerial gdb": "aerial imagery",
    "aerial database": "aerial imagery",
    "aerial spatial": "aerial imagery",
    "aerial gis": "aerial imagery",
    "aerial cartography": "aerial imagery",
    "aerial symbology": "aerial imagery",
    "aerial styling": "aerial imagery",
    "aerial crs": "aerial imagery",
    "aerial projection": "aerial imagery",
    "aerial coordinate": "aerial imagery",
    "aerial datum": "aerial imagery",
    "aerial transformation": "aerial imagery",
    "aerial alignment": "aerial imagery",
    "aerial validation": "aerial imagery",
    "aerial qa/qc": "aerial imagery",
    "aerial check": "aerial imagery",
    "aerial review": "aerial imagery",
    "aerial audit": "aerial imagery",
    "aerial verification": "aerial imagery",
    "aerial join": "aerial imagery",
    "aerial merge": "aerial imagery",
    "aerial combine": "aerial imagery",
    "aerial union": "aerial imagery",
    "aerial dissolve": "aerial imagery",
    "aerial intersect": "aerial imagery",
    "aerial clip": "aerial imagery",
    "aerial buffer": "aerial imagery",
    "aerial centroid": "aerial imagery",
    "aerial geometry": "aerial imagery",
    # Feature Attribute Joining
    "feature attribute": "feature attribute",
    "feature attributes": "feature attribute",
    "feature join": "feature attribute",
    "feature merge": "feature attribute",
    "feature combine": "feature attribute",
    "feature union": "feature attribute",
    "feature dissolve": "feature attribute",
    "feature intersect": "feature attribute",
    "feature clip": "feature attribute",
    "feature buffer": "feature attribute",
    "feature centroid": "feature attribute",
    "feature geometry": "feature attribute",
    "feature record": "feature attribute",
    "feature table": "feature attribute",
    "feature shapefile": "feature attribute",
    "feature geojson": "feature attribute",
    "feature kml": "feature attribute",
    "feature gdb": "feature attribute",
    "feature database": "feature attribute",
    "feature spatial": "feature attribute",
    "feature gis": "feature attribute",
    "feature cartography": "feature attribute",
    "feature symbology": "feature attribute",
    "feature styling": "feature attribute",
    "feature crs": "feature attribute",
    "feature projection": "feature attribute",
    "feature coordinate": "feature attribute",
    "feature datum": "feature attribute",
    "feature transformation": "feature attribute",
    "feature alignment": "feature attribute",
    "feature validation": "feature attribute",
    "feature qa/qc": "feature attribute",
    "feature check": "feature attribute",
    "feature review": "feature attribute",
    "feature audit": "feature attribute",
    "feature verification": "feature attribute",
    # Spatial Query Operations
    "spatial query": "spatial query",
    "spatial queries": "spatial query",
    "spatial operation": "spatial query",
    "spatial operations": "spatial query",
    "spatial validation": "spatial query",
    "spatial qa/qc": "spatial query",
    "spatial check": "spatial query",
    "spatial review": "spatial query",
    "spatial audit": "spatial query",
    "spatial verification": "spatial query",
    "spatial join": "spatial query",
    "spatial merge": "spatial query",
    "spatial combine": "spatial query",
    "spatial union": "spatial query",
    "spatial dissolve": "spatial query",
    "spatial intersect": "spatial query",
    "spatial clip": "spatial query",
    "spatial buffer": "spatial query",
    "spatial centroid": "spatial query",
    "spatial geometry": "spatial query",
    "spatial record": "spatial query",
    "spatial table": "spatial query",
    "spatial shapefile": "spatial query",
    "spatial geojson": "spatial query",
    "spatial kml": "spatial query",
    "spatial gdb": "spatial query",
    "spatial database": "spatial query",
    "spatial gis": "spatial query",
    "spatial cartography": "spatial query",
    "spatial symbology": "spatial query",
    "spatial styling": "spatial query",
    "spatial crs": "spatial query",
    "spatial projection": "spatial query",
    "spatial coordinate": "spatial query",
    "spatial datum": "spatial query",
    "spatial transformation": "spatial query",
    "spatial alignment": "spatial query",
    # Layer Styling and Symbology
    "layer styling": "layer styling",
    "layer symbology": "layer symbology",
    "layer style": "layer styling",
    "layer symbol": "layer symbology",
    "layer cartography": "layer styling",
    "layer map": "layer styling",
    "layer overlay": "layer styling",
    "layer integration": "layer styling",
    "layer mapping": "layer styling",
    "layer attribute": "layer styling",
    "layer record": "layer styling",
    "layer table": "layer styling",
    "layer shapefile": "layer styling",
    "layer geojson": "layer styling",
    "layer kml": "layer styling",
    "layer gdb": "layer styling",
    "layer database": "layer styling",
    "layer spatial": "layer styling",
    "layer gis": "layer styling",
    "layer crs": "layer styling",
    "layer projection": "layer styling",
    "layer coordinate": "layer styling",
    "layer datum": "layer styling",
    "layer transformation": "layer styling",
    "layer alignment": "layer styling",
    "layer validation": "layer styling",
    "layer qa/qc": "layer styling",
    "layer check": "layer styling",
    "layer review": "layer styling",
    "layer audit": "layer styling",
    "layer verification": "layer styling",
    "layer join": "layer styling",
    "layer merge": "layer styling",
    "layer combine": "layer styling",
    "layer union": "layer styling",
    "layer dissolve": "layer styling",
    "layer intersect": "layer styling",
    "layer clip": "layer styling",
    "layer buffer": "layer styling",
    "layer centroid": "layer styling",
    "layer geometry": "layer styling",
    # CRS Alignment and Transformation
    "crs": "crs alignment",
    "coordinate reference system": "crs alignment",
    "coordinate system": "crs alignment",
    "projection": "crs alignment",
    "datum": "crs alignment",
    "transformation": "crs alignment",
    "crs alignment": "crs alignment",
    "crs transformation": "crs alignment",
    "crs overlay": "crs alignment",
    "crs integration": "crs alignment",
    "crs mapping": "crs alignment",
    "crs map": "crs alignment",
    "crs layer": "crs alignment",
    "crs attribute": "crs alignment",
    "crs record": "crs alignment",
    "crs table": "crs alignment",
    "crs shapefile": "crs alignment",
    "crs geojson": "crs alignment",
    "crs kml": "crs alignment",
    "crs gdb": "crs alignment",
    "crs database": "crs alignment",
    "crs spatial": "crs alignment",
    "crs gis": "crs alignment",
    "crs cartography": "crs alignment",
    "crs symbology": "crs alignment",
    "crs styling": "crs alignment",
    "crs validation": "crs alignment",
    "crs qa/qc": "crs alignment",
    "crs check": "crs alignment",
    "crs review": "crs alignment",
    "crs audit": "crs alignment",
    "crs verification": "crs alignment",
    "crs join": "crs alignment",
    "crs merge": "crs alignment",
    "crs combine": "crs alignment",
    "crs union": "crs alignment",
    "crs dissolve": "crs alignment",
    "crs intersect": "crs alignment",
    "crs clip": "crs alignment",
    "crs buffer": "crs alignment",
    "crs centroid": "crs alignment",
    "crs geometry": "crs alignment",
    # Feature Generalization and Simplification
    "feature generalization": "feature generalization",
    "feature simplification": "feature simplification",
    "generalization": "feature generalization",
    "simplification": "feature simplification",
    "feature simplify": "feature simplification",
    "feature generalize": "feature generalization",
    "feature aggregation": "feature generalization",
    "feature reduce": "feature simplification",
    "feature abstraction": "feature generalization",
    "feature dissolve": "feature generalization",
    "feature union": "feature generalization",
    "feature merge": "feature generalization",
    "feature combine": "feature generalization",
    "feature overlay": "feature generalization",
    "feature mapping": "feature generalization",
    "feature cartography": "feature generalization",
    "feature styling": "feature generalization",
    "feature symbology": "feature generalization",
    "feature crs": "feature generalization",
    "feature projection": "feature generalization",
    "feature coordinate": "feature generalization",
    "feature datum": "feature generalization",
    "feature transformation": "feature generalization",
    "feature alignment": "feature generalization",
    "feature validation": "feature generalization",
    "feature qa/qc": "feature generalization",
    "feature check": "feature generalization",
    "feature review": "feature generalization",
    "feature audit": "feature generalization",
    "feature verification": "feature generalization",
    # Misspellings, Abbreviations, Synonyms
    "welll": "well",
    "wll": "well",
    "wellsites": "well",
    "pipline": "pipeline",
    "pipelines": "pipeline",
    "pipelin": "pipeline",
    "pipelne": "pipeline",
    "surv abstract": "survey abstract",
    "surv abs": "survey abstract",
    "county bndry": "county boundary",
    "cnty boundary": "county boundary",
    "cnty bndry": "county boundary",
    "rd infrastructure": "road infrastructure",
    "road infrastucture": "road infrastructure",
    "road infrstructure": "road infrastructure",
    "topo feat": "topographic feature",
    "topo ftr": "topographic feature",
    "hydro ftr": "hydrology",
    "hydro feat": "hydrology",
    "soil class": "soil classification",
    "soil cls": "soil classification",
    "lu classification": "land use classification",
    "landuse": "land use classification",
    "arial imagery": "aerial imagery",
    "arial image": "aerial imagery",
    "feature attr": "feature attribute",
    "spatial qry": "spatial query",
    "spatial qury": "spatial query",
    "layer symb": "layer symbology",
    "layer styl": "layer styling",
    "crs align": "crs alignment",
    "crs transf": "crs alignment",
    "feat generalization": "feature generalization",
    "feat simplification": "feature simplification",
    "feat simplify": "feature simplification",
    "feat generalize": "feature generalization",
    "feat aggregation": "feature generalization",
    "feat reduce": "feature simplification",
    "feat abstraction": "feature generalization",
    "feat dissolve": "feature generalization",
    "feat union": "feature generalization",
    "feat merge": "feature generalization",
    "feat combine": "feature generalization",
    "feat overlay": "feature generalization",
    "feat mapping": "feature generalization",
    "feat cartography": "feature generalization",
    "feat styling": "feature generalization",
    "feat symbology": "feature generalization",
    "feat crs": "feature generalization",
    "feat projection": "feature generalization",
    "feat coordinate": "feature generalization",
    "feat datum": "feature generalization",
    "feat transformation": "feature generalization",
    "feat alignment": "feature generalization",
    "feat validation": "feature generalization",
    "feat qa/qc": "feature generalization",
    "feat check": "feature generalization",
    "feat review": "feature generalization",
    "feat audit": "feature generalization",
    "feat verification": "feature generalization",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)