import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "DRL01 Semantic Team"
SEMANTIC_MAP_ENGINE = "DRL01_drilling_fluid_systems"

SEMANTIC_MAP = {
    # Mud Types
    "wbm": "water_based_mud",
    "water based mud": "water_based_mud",
    "water-based mud": "water_based_mud",
    "waterbase mud": "water_based_mud",
    "wb mud": "water_based_mud",
    "water mud": "water_based_mud",
    "obm": "oil_based_mud",
    "oil based mud": "oil_based_mud",
    "oil-based mud": "oil_based_mud",
    "oilbase mud": "oil_based_mud",
    "ob mud": "oil_based_mud",
    "oil mud": "oil_based_mud",
    "sbm": "synthetic_based_mud",
    "synthetic based mud": "synthetic_based_mud",
    "synthetic-based mud": "synthetic_based_mud",
    "syn mud": "synthetic_based_mud",
    "synthetic mud": "synthetic_based_mud",
    "emulsion mud": "oil_based_mud",
    "invert emulsion": "oil_based_mud",
    "invert mud": "oil_based_mud",
    "emulsion based mud": "oil_based_mud",
    "emulsion-based mud": "oil_based_mud",
    "completion fluid": "completion_fluid",
    "workover fluid": "workover_fluid",
    "clear brine": "clear_brine",
    "brine": "clear_brine",
    "formate brine": "formate_brine",
    "potassium formate": "formate_brine",
    "cesium formate": "formate_brine",
    "low solids mud": "low_solids_mud",
    "low-solids mud": "low_solids_mud",
    "ls mud": "low_solids_mud",
    "high solids mud": "high_solids_mud",
    "high-solids mud": "high_solids_mud",
    "hs mud": "high_solids_mud",

    # Mud Weight & Barite
    "mud weight": "mud_weight",
    "mudweight": "mud_weight",
    "density": "mud_weight",
    "ppg": "mud_weight",
    "sg": "mud_weight",
    "specific gravity": "mud_weight",
    "barite": "barite",
    "barium sulfate": "barite",
    "barite addition": "barite_addition",
    "barite sag": "barite_sag",
    "sag": "barite_sag",
    "barite sag prevention": "barite_sag_prevention",
    "barite sagging": "barite_sag",
    "barite calculation": "barite_addition",
    "barite dosage": "barite_addition",
    "mud weight control": "mud_weight_control",
    "weighting agent": "barite",
    "weight material": "barite",

    # Rheology
    "rheology": "mud_rheology",
    "plastic viscosity": "plastic_viscosity",
    "pv": "plastic_viscosity",
    "yield point": "yield_point",
    "yp": "yield_point",
    "gel strength": "gel_strength",
    "gs": "gel_strength",
    "viscosity": "mud_rheology",
    "apparent viscosity": "apparent_viscosity",
    "av": "apparent_viscosity",
    "flow curve": "mud_rheology",
    "flow behavior": "mud_rheology",
    "rheogram": "mud_rheology",
    "flow index": "flow_index",
    "consistency index": "consistency_index",
    "n value": "flow_index",
    "k value": "consistency_index",
    "bingham plastic": "bingham_plastic",
    "herschel-bulkley": "herschel_bulkley",
    "power law": "power_law_model",

    # Fluid Loss
    "fluid loss": "fluid_loss",
    "filtrate loss": "fluid_loss",
    "api filtrate": "api_filtrate",
    "api fluid loss": "api_filtrate",
    "api loss": "api_filtrate",
    "hpht filtration": "hpht_filtration",
    "hpht fluid loss": "hpht_filtration",
    "high pressure high temperature filtration": "hpht_filtration",
    "spurt loss": "spurt_loss",
    "spurt": "spurt_loss",
    "cake thickness": "filter_cake_thickness",
    "filter cake": "filter_cake",
    "filter cake thickness": "filter_cake_thickness",
    "fluid loss control": "fluid_loss_control",
    "fluid loss additive": "fluid_loss_additive",
    "fluid loss agent": "fluid_loss_additive",
    "filtration control": "fluid_loss_control",

    # Shale Inhibition
    "shale inhibition": "shale_inhibition",
    "kcl mud": "kcl_mud",
    "potassium chloride mud": "kcl_mud",
    "kcl": "kcl_mud",
    "kcl-polymer mud": "kcl_mud",
    "kcl-polymer": "kcl_mud",
    "shale inhibitor": "shale_inhibitor",
    "glycol mud": "glycol_mud",
    "amine mud": "amine_mud",
    "amine shale inhibitor": "amine_shale_inhibitor",
    "glycol shale inhibitor": "glycol_shale_inhibitor",
    "glycol": "glycol_shale_inhibitor",
    "amine": "amine_shale_inhibitor",
    "shale stabilizer": "shale_inhibitor",
    "shale stabilisation": "shale_inhibition",
    "shale stabilization": "shale_inhibition",

    # Lost Circulation
    "lost circulation": "lost_circulation",
    "lost circulation material": "lost_circulation_material",
    "lcm": "lost_circulation_material",
    "bridging agent": "bridging_agent",
    "bridging material": "bridging_agent",
    "sealing agent": "sealing_agent",
    "sealing material": "sealing_agent",
    "lost circulation control": "lost_circulation_control",
    "loss zone": "lost_circulation_zone",
    "losses": "lost_circulation",
    "loss circulation": "lost_circulation",
    "loss control": "lost_circulation_control",
    "loss pill": "lost_circulation_pill",
    "lcm pill": "lost_circulation_pill",
    "loss prevention": "lost_circulation_control",
    "fibrous lcm": "fibrous_lcm",
    "granular lcm": "granular_lcm",
    "flake lcm": "flake_lcm",

    # Solids Control Equipment
    "solids control": "solids_control",
    "shale shaker": "shale_shaker",
    "shale shakers": "shale_shaker",
    "shaker screen": "shale_shaker",
    "shaker": "shale_shaker",
    "desander": "desander",
    "desilter": "desilter",
    "mud cleaner": "mud_cleaner",
    "centrifuge": "centrifuge",
    "decanter centrifuge": "centrifuge",
    "decanter": "centrifuge",
    "degasser": "degasser",
    "mud gas separator": "degasser",
    "vacuum degasser": "degasser",
    "solids removal": "solids_control",
    "solids control equipment": "solids_control_equipment",
    "cuttings dryer": "cuttings_dryer",
    "cuttings": "drill_cuttings",
    "drill cuttings": "drill_cuttings",

    # Cement Contamination
    "cement contamination": "cement_contamination",
    "cementing contamination": "cement_contamination",
    "cement contamination diagnosis": "cement_contamination_diagnosis",
    "cement contamination treatment": "cement_contamination_treatment",
    "cement contamination removal": "cement_contamination_treatment",
    "cement contamination mitigation": "cement_contamination_treatment",
    "cement contamination control": "cement_contamination_treatment",
    "cement pill": "cement_contamination",
    "cement invasion": "cement_contamination",
    "cement solids": "cement_contamination",

    # HPHT
    "hpht": "hpht",
    "high pressure high temperature": "hpht",
    "hpht mud": "hpht_mud",
    "hpht drilling fluid": "hpht_mud",
    "hpht fluid": "hpht_mud",
    "hpht system": "hpht_mud",
    "ultra hpht": "ultra_hpht",
    "ultra-hpht": "ultra_hpht",
    "ultra hpht mud": "ultra_hpht_mud",
    "ultra high pressure high temperature": "ultra_hpht",

    # Completion & Workover
    "completion fluid": "completion_fluid",
    "workover fluid": "workover_fluid",
    "clear brine": "clear_brine",
    "formate brine": "formate_brine",
    "potassium formate": "formate_brine",
    "cesium formate": "formate_brine",
    "low solids system": "low_solids_system",
    "low-solids system": "low_solids_system",
    "low solids fluid": "low_solids_fluid",
    "low-solids fluid": "low_solids_fluid",

    # Environmental Regulations
    "environmental regulation": "environmental_regulation",
    "environmental regulations": "environmental_regulation",
    "fluid disposal": "fluid_disposal",
    "mud disposal": "fluid_disposal",
    "fluid discharge": "fluid_discharge",
    "mud discharge": "fluid_discharge",
    "cuttings discharge": "cuttings_discharge",
    "zero discharge": "zero_discharge",
    "offshore discharge": "offshore_discharge",
    "onshore discharge": "onshore_discharge",
    "environmental compliance": "environmental_compliance",
    "environmental advantage": "environmental_advantage",
    "sbm environmental advantage": "environmental_advantage",

    # pH & Alkalinity
    "ph": "ph",
    "p h": "ph",
    "alkalinity": "alkalinity",
    "ph control": "ph_control",
    "alkalinity control": "alkalinity_control",
    "ph management": "ph_control",
    "alkalinity management": "alkalinity_control",
    "caustic soda": "caustic_soda",
    "naoh": "caustic_soda",
    "lime": "lime",
    "slaked lime": "lime",
    "hydrated lime": "lime",
    "buffer": "buffer",
    "buffering agent": "buffer",
    "carbonate": "carbonate",
    "bicarbonate": "bicarbonate",
    "sodium carbonate": "carbonate",
    "sodium bicarbonate": "bicarbonate",

    # Wellbore Stability
    "wellbore stability": "wellbore_stability",
    "borehole stability": "wellbore_stability",
    "wellbore stability analysis": "wellbore_stability_analysis",
    "mud weight window": "mud_weight_window",
    "pressure window": "mud_weight_window",
    "fracture pressure": "fracture_pressure",
    "pore pressure": "pore_pressure",
    "collapse pressure": "collapse_pressure",
    "kick tolerance": "kick_tolerance",
    "wellbore collapse": "wellbore_collapse",
    "wellbore breakout": "wellbore_breakout",

    # Glycol & Amine Shale Inhibitors
    "glycol": "glycol_shale_inhibitor",
    "amine": "amine_shale_inhibitor",
    "glycol inhibitor": "glycol_shale_inhibitor",
    "amine inhibitor": "amine_shale_inhibitor",
    "polyol": "glycol_shale_inhibitor",
    "polyol mud": "glycol_mud",
    "polyol inhibitor": "glycol_shale_inhibitor",
    "polyamine": "amine_shale_inhibitor",
    "polyamine mud": "amine_mud",
    "polyamine inhibitor": "amine_shale_inhibitor",

    # Barite Sag Prevention
    "barite sag prevention": "barite_sag_prevention",
    "sag prevention": "barite_sag_prevention",
    "barite sag control": "barite_sag_prevention",
    "barite sag mitigation": "barite_sag_prevention",
    "barite sag diagnosis": "barite_sag_diagnosis",
    "barite sag treatment": "barite_sag_treatment",
    "barite sag analysis": "barite_sag_analysis",
    "barite sag test": "barite_sag_test",
    "barite sag measurement": "barite_sag_test",
    "barite sag index": "barite_sag_index",

    # Emulsion Stability
    "emulsion stability": "emulsion_stability",
    "emulsion stable": "emulsion_stability",
    "emulsion destabilization": "emulsion_destabilization",
    "emulsion breaker": "emulsion_breaker",
    "emulsifier": "emulsifier",
    "emulsification": "emulsification",
    "emulsified mud": "emulsion_mud",
    "emulsified system": "emulsion_mud",
    "emulsion": "emulsion_mud",

    # Salt Contamination
    "salt contamination": "salt_contamination",
    "salt contamination diagnosis": "salt_contamination_diagnosis",
    "salt contamination treatment": "salt_contamination_treatment",
    "salt contamination removal": "salt_contamination_treatment",
    "salt contamination mitigation": "salt_contamination_treatment",
    "salt pill": "salt_contamination",
    "salt invasion": "salt_contamination",
    "salt solids": "salt_contamination",
    "salt water contamination": "salt_contamination",
    "sodium chloride contamination": "salt_contamination",

    # Anhydrite Contamination
    "anhydrite contamination": "anhydrite_contamination",
    "caco4 contamination": "anhydrite_contamination",
    "caso4 contamination": "anhydrite_contamination",
    "anhydrite contamination diagnosis": "anhydrite_contamination_diagnosis",
    "anhydrite contamination treatment": "anhydrite_contamination_treatment",
    "anhydrite contamination removal": "anhydrite_contamination_treatment",
    "anhydrite contamination mitigation": "anhydrite_contamination_treatment",
    "anhydrite pill": "anhydrite_contamination",
    "anhydrite invasion": "anhydrite_contamination",
    "anhydrite solids": "anhydrite_contamination",
    "calcium sulfate contamination": "anhydrite_contamination",

    # Drilling Fluid Hydraulics & ECD
    "hydraulics": "drilling_fluid_hydraulics",
    "fluid hydraulics": "drilling_fluid_hydraulics",
    "mud hydraulics": "drilling_fluid_hydraulics",
    "equivalent circulating density": "equivalent_circulating_density",
    "ecd": "equivalent_circulating_density",
    "pressure drop": "pressure_drop",
    "annular pressure": "annular_pressure",
    "annular pressure loss": "annular_pressure_loss",
    "pressure loss": "pressure_drop",
    "pressure profile": "pressure_profile",
    "annular velocity": "annular_velocity",

    # SBM Environmental Advantages
    "sbm environmental advantage": "environmental_advantage",
    "synthetic mud environmental advantage": "environmental_advantage",
    "synthetic-based mud environmental advantage": "environmental_advantage",
    "synthetic mud environmental benefit": "environmental_advantage",
    "sbm environmental benefit": "environmental_advantage",

    # Managed Pressure Drilling (MPD)
    "mpd": "managed_pressure_drilling",
    "managed pressure drilling": "managed_pressure_drilling",
    "mpd fluid": "mpd_fluid",
    "mpd system": "mpd_fluid",
    "mpd mud": "mpd_fluid",
    "managed pressure drilling fluid": "mpd_fluid",
    "mpd control": "mpd_control",
    "mpd operation": "mpd_operation",

    # Underbalanced Drilling (UBD)
    "ubd": "underbalanced_drilling",
    "underbalanced drilling": "underbalanced_drilling",
    "ubd fluid": "ubd_fluid",
    "ubd system": "ubd_fluid",
    "ubd mud": "ubd_fluid",
    "underbalanced drilling fluid": "ubd_fluid",
    "ubd control": "ubd_control",
    "ubd operation": "ubd_operation",
    "gas mud": "ubd_fluid",
    "foam mud": "ubd_fluid",
    "aerated mud": "ubd_fluid",
    "gas drilling fluid": "ubd_fluid",
    "foam drilling fluid": "ubd_fluid",
    "aerated drilling fluid": "ubd_fluid",

    # API RP 13B-1 Testing Procedures
    "api rp 13b-1": "api_rp_13b_1",
    "api 13b-1": "api_rp_13b_1",
    "api rp 13b1": "api_rp_13b_1",
    "api 13b1": "api_rp_13b_1",
    "api testing": "api_testing",
    "api test": "api_testing",
    "api rp 13b-1 testing": "api_testing",
    "api rp 13b-1 procedure": "api_testing",
    "api rp 13b-1 standard": "api_testing",
    "api rp 13b-1 qa/qc": "api_qa_qc",
    "api qa/qc": "api_qa_qc",
    "api quality control": "api_qa_qc",
    "api standardization": "api_standardization",
    "api procedure": "api_testing",

    # General/Related
    "drilling fluid": "drilling_fluid",
    "drilling fluids": "drilling_fluid",
    "mud": "drilling_fluid",
    "drilling mud": "drilling_fluid",
    "fluid": "drilling_fluid",
    "base fluid": "base_fluid",
    "base oil": "base_oil",
    "base brine": "base_brine",
    "additive": "additive",
    "additives": "additive",
    "chemical": "additive",
    "chemicals": "additive",
    "formulation": "formulation",
    "formulation design": "formulation_design",
    "mud formulation": "formulation_design",
    "fluid formulation": "formulation_design",
    "system design": "formulation_design",
    "design": "formulation_design",
    "treatment": "treatment",
    "diagnosis": "diagnosis",
    "removal": "removal",
    "mitigation": "mitigation",
    "control": "control",
    "prevention": "prevention",
    "analysis": "analysis",
    "test": "test",
    "testing": "test",
    "measurement": "measurement",
    "standardization": "standardization",
    "qa/qc": "qa_qc",
    "quality assurance": "qa_qc",
    "quality control": "qa_qc",
    "procedure": "procedure",
    "operation": "operation",
    "system": "system",
    "equipment": "equipment",
    "device": "equipment",
    "tool": "equipment",
    "material": "material",
    "agent": "additive",
    "pill": "pill",
    "zone": "zone",
    "window": "window",
    "profile": "profile",
    "index": "index",
    "value": "value",
    "parameter": "parameter",
    "property": "property",
    "properties": "property",
    "mud system": "drilling_fluid_system",
    "drilling fluid system": "drilling_fluid_system",
    "fluid system": "drilling_fluid_system",
    "drilling system": "drilling_fluid_system",
    "well": "well",
    "wellbore": "wellbore",
    "borehole": "wellbore",
    "formation": "formation",
    "reservoir": "formation",
    "zone": "zone",
    "window": "window",
    "operation": "operation",
    "process": "operation",
    "procedure": "procedure",
    "test": "test",
    "testing": "test",
    "measurement": "measurement",
    "analysis": "analysis",
    "diagnosis": "diagnosis",
    "treatment": "treatment",
    "removal": "removal",
    "mitigation": "mitigation",
    "control": "control",
    "prevention": "prevention",
    "management": "management",
    "compliance": "compliance",
    "advantage": "advantage",
    "benefit": "advantage",
    "disposal": "disposal",
    "discharge": "discharge",
    "cuttings": "drill_cuttings",
    "drill cuttings": "drill_cuttings",
    "solids": "solids",
    "solids removal": "solids_control",
    "solids control": "solids_control",
    "solids control equipment": "solids_control_equipment",
    "equipment": "equipment",
    "device": "equipment",
    "tool": "equipment",
    "material": "material",
    "agent": "additive",
    "pill": "pill",
    "zone": "zone",
    "window": "window",
    "profile": "profile",
    "index": "index",
    "value": "value",
    "parameter": "parameter",
    "property": "property",
    "properties": "property",
    "system": "system",
    "design": "formulation_design",
    "formulation": "formulation",
    "formulation design": "formulation_design",
    "mud formulation": "formulation_design",
    "fluid formulation": "formulation_design",
    "system design": "formulation_design",
    "drilling fluid system": "drilling_fluid_system",
    "mud system": "drilling_fluid_system",
    "fluid system": "drilling_fluid_system",
    "drilling system": "drilling_fluid_system",
    "well": "well",
    "wellbore": "wellbore",
    "borehole": "wellbore",
    "formation": "formation",
    "reservoir": "formation",
    "zone": "zone",
    "window": "window",
    "operation": "operation",
    "process": "operation",
    "procedure": "procedure",
    "test": "test",
    "testing": "test",
    "measurement": "measurement",
    "analysis": "analysis",
    "diagnosis": "diagnosis",
    "treatment": "treatment",
    "removal": "removal",
    "mitigation": "mitigation",
    "control": "control",
    "prevention": "prevention",
    "management": "management",
    "compliance": "compliance",
    "advantage": "advantage",
    "benefit": "advantage",
    "disposal": "disposal",
    "discharge": "discharge",
    "cuttings": "drill_cuttings",
    "drill cuttings": "drill_cuttings",
    "solids": "solids",
    "solids removal": "solids_control",
    "solids control": "solids_control",
    "solids control equipment": "solids_control_equipment",
    "equipment": "equipment",
    "device": "equipment",
    "tool": "equipment",
    "material": "material",
    "agent": "additive",
    "pill": "pill",
    "zone": "zone",
    "window": "window",
    "profile": "profile",
    "index": "index",
    "value": "value",
    "parameter": "parameter",
    "property": "property",
    "properties": "property",
    "system": "system",
}

# Remove duplicates, ensure keys are unique, and count
SEMANTIC_MAP = dict(SEMANTIC_MAP)
_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    hasher = hashlib.sha256()
    for k, v in items:
        hasher.update(k.encode("utf-8"))
        hasher.update(b":")
        hasher.update(v.encode("utf-8"))
        hasher.update(b";")
    return hasher.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def normalize_term(term: str) -> str:
    if not isinstance(term, str):
        return ""
    t = term.strip().lower()
    t = re.sub(r"[_\-]+", " ", t)
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    return SEMANTIC_MAP.get(t, t.replace(" ", "_"))

def get_related_terms(term: str) -> list:
    if not isinstance(term, str):
        return []
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)