import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "CHEM10_electrochemistry"
SEMANTIC_MAP_ENGINE = "CHEM10"

# SEMANTIC_MAP: 200+ entries, including synonyms, abbreviations, acronyms, misspellings, related terms
SEMANTIC_MAP = {
    # Nernst Equation and Electrode Potential
    "nernst equation": "nernst_equation",
    "nernst eq": "nernst_equation",
    "nernst": "nernst_equation",
    "nernst potential": "electrode_potential",
    "electrode potential": "electrode_potential",
    "cell potential": "electrode_potential",
    "emf": "electrode_potential",
    "electromotive force": "electrode_potential",
    "standard electrode potential": "standard_electrode_potential",
    "standard potential": "standard_electrode_potential",
    "e0": "standard_electrode_potential",
    "e°": "standard_electrode_potential",
    "reduction potential": "standard_electrode_potential",
    "oxidation potential": "standard_electrode_potential",
    "half-cell potential": "standard_electrode_potential",
    "reference electrode": "reference_electrode",
    "saturated calomel electrode": "reference_electrode",
    "sce": "reference_electrode",
    "silver/silver chloride electrode": "reference_electrode",
    "ag/agcl": "reference_electrode",
    "hydrogen electrode": "reference_electrode",
    "she": "reference_electrode",
    "standard hydrogen electrode": "reference_electrode",
    "quasi-reference electrode": "reference_electrode",
    "pseudo-reference electrode": "reference_electrode",
    "open circuit potential": "open_circuit_potential",
    "ocp": "open_circuit_potential",
    "open circuit voltage": "open_circuit_potential",
    "ocv": "open_circuit_potential",
    "activity": "activity",
    "ionic activity": "activity",
    "concentration": "concentration",
    "molarity": "concentration",
    "molality": "concentration",
    "logarithm": "logarithm",
    "ln": "logarithm",
    "log": "logarithm",
    "temperature": "temperature",
    "kelvin": "temperature",
    "t": "temperature",
    "gas constant": "gas_constant",
    "r": "gas_constant",
    "faraday constant": "faraday_constant",
    "f": "faraday_constant",
    "charge": "charge",
    "electron": "electron",
    "n": "number_of_electrons",
    "number of electrons": "number_of_electrons",
    "stoichiometry": "stoichiometry",
    "redox": "redox",
    "redox reaction": "redox",
    "oxidation": "oxidation",
    "reduction": "reduction",
    "electrochemical cell": "electrochemical_cell",
    "galvanic cell": "electrochemical_cell",
    "voltaic cell": "electrochemical_cell",
    "electrolytic cell": "electrochemical_cell",
    "cell diagram": "cell_diagram",
    "cell notation": "cell_diagram",
    "salt bridge": "salt_bridge",
    "junction": "salt_bridge",
    "electrolyte": "electrolyte",
    "supporting electrolyte": "electrolyte",
    "ionic strength": "ionic_strength",
    "debye length": "debye_length",
    "double layer": "double_layer",
    "electrical double layer": "double_layer",
    "helmholtz layer": "helmholtz_layer",
    "diffuse layer": "diffuse_layer",
    "stern layer": "stern_layer",

    # Butler-Volmer Kinetics and Exchange Current Density
    "butler-volmer equation": "butler_volmer_equation",
    "butler volmer": "butler_volmer_equation",
    "butler-volmer kinetics": "butler_volmer_equation",
    "exchange current density": "exchange_current_density",
    "j0": "exchange_current_density",
    "j_0": "exchange_current_density",
    "current density": "current_density",
    "overpotential": "overpotential",
    "eta": "overpotential",
    "activation overpotential": "activation_overpotential",
    "concentration overpotential": "concentration_overpotential",
    "ohmic overpotential": "ohmic_overpotential",
    "polarization": "polarization",
    "polarization curve": "polarization_curve",
    "tafel plot": "tafel_plot",
    "tafel equation": "tafel_equation",
    "tafel slope": "tafel_slope",
    "alpha": "transfer_coefficient",
    "transfer coefficient": "transfer_coefficient",
    "symmetry factor": "transfer_coefficient",
    "charge transfer": "charge_transfer",
    "charge transfer resistance": "charge_transfer_resistance",
    "rct": "charge_transfer_resistance",
    "electrochemical kinetics": "electrochemical_kinetics",
    "kinetic current": "kinetic_current",
    "limiting current": "limiting_current",
    "il": "limiting_current",
    "mass transport": "mass_transport",
    "diffusion": "diffusion",
    "diffusion coefficient": "diffusion_coefficient",
    "d": "diffusion_coefficient",
    "migration": "migration",
    "convection": "convection",
    "electrode reaction": "electrode_reaction",
    "surface coverage": "surface_coverage",
    "adsorption": "adsorption",
    "desorption": "desorption",
    "reaction rate": "reaction_rate",
    "rate constant": "rate_constant",
    "k": "rate_constant",

    # Cyclic Voltammetry Interpretation
    "cyclic voltammetry": "cyclic_voltammetry",
    "cv": "cyclic_voltammetry",
    "cyclic voltammogram": "cyclic_voltammetry",
    "voltammetry": "voltammetry",
    "linear sweep voltammetry": "linear_sweep_voltammetry",
    "lsv": "linear_sweep_voltammetry",
    "square wave voltammetry": "square_wave_voltammetry",
    "swv": "square_wave_voltammetry",
    "pulse voltammetry": "pulse_voltammetry",
    "differential pulse voltammetry": "differential_pulse_voltammetry",
    "dpv": "differential_pulse_voltammetry",
    "anodic peak": "anodic_peak",
    "cathodic peak": "cathodic_peak",
    "peak current": "peak_current",
    "ip": "peak_current",
    "peak potential": "peak_potential",
    "ep": "peak_potential",
    "scan rate": "scan_rate",
    "v/s": "scan_rate",
    "reversibility": "reversibility",
    "quasi-reversible": "quasi_reversible",
    "irreversible": "irreversible",
    "reversible": "reversible",
    "randles-sevcik equation": "randles_sevcik_equation",
    "randles sevcik": "randles_sevcik_equation",
    "randles circuit": "randles_circuit",
    "background current": "background_current",
    "capacitive current": "capacitive_current",
    "faradaic current": "faradaic_current",
    "charging current": "capacitive_current",
    "baseline": "baseline",
    "electrode surface area": "electrode_surface_area",
    "a": "electrode_surface_area",
    "surface area": "electrode_surface_area",
    "electrode modification": "electrode_modification",
    "surface functionalization": "electrode_modification",
    "electrode material": "electrode_material",
    "glassy carbon": "electrode_material",
    "platinum electrode": "electrode_material",
    "gold electrode": "electrode_material",
    "carbon electrode": "electrode_material",
    "working electrode": "working_electrode",
    "counter electrode": "counter_electrode",
    "auxiliary electrode": "counter_electrode",

    # Electrochemical Impedance Spectroscopy (EIS)
    "electrochemical impedance spectroscopy": "eis",
    "eis": "eis",
    "impedance spectroscopy": "eis",
    "impedance": "impedance",
    "nyquist plot": "nyquist_plot",
    "bode plot": "bode_plot",
    "frequency response": "frequency_response",
    "ac impedance": "impedance",
    "alternating current impedance": "impedance",
    "real impedance": "real_impedance",
    "imaginary impedance": "imaginary_impedance",
    "z'": "real_impedance",
    "z''": "imaginary_impedance",
    "phase angle": "phase_angle",
    "modulus": "impedance_modulus",
    "admittance": "admittance",
    "conductance": "conductance",
    "capacitance": "capacitance",
    "c": "capacitance",
    "resistance": "resistance",
    "r": "resistance",
    "warburg impedance": "warburg_impedance",
    "warburg element": "warburg_impedance",
    "constant phase element": "constant_phase_element",
    "cpe": "constant_phase_element",
    "randles circuit": "randles_circuit",
    "equivalent circuit": "equivalent_circuit",
    "model fitting": "model_fitting",
    "curve fitting": "model_fitting",
    "frequency": "frequency",
    "f": "frequency",
    "high frequency": "high_frequency",
    "low frequency": "low_frequency",
    "interfacial impedance": "interfacial_impedance",
    "bulk impedance": "bulk_impedance",
    "electrolyte resistance": "electrolyte_resistance",
    "solution resistance": "electrolyte_resistance",
    "rs": "electrolyte_resistance",
    "r_s": "electrolyte_resistance",

    # Lithium-Ion Battery Electrochemistry
    "lithium-ion battery": "lithium_ion_battery",
    "li-ion battery": "lithium_ion_battery",
    "li ion battery": "lithium_ion_battery",
    "li-ion": "lithium_ion_battery",
    "lib": "lithium_ion_battery",
    "lithium battery": "lithium_ion_battery",
    "anode": "anode",
    "cathode": "cathode",
    "separator": "separator",
    "electrolyte": "electrolyte",
    "solid electrolyte": "solid_electrolyte",
    "li metal": "lithium_metal",
    "lithium metal": "lithium_metal",
    "graphite": "graphite",
    "lco": "lithium_cobalt_oxide",
    "lithium cobalt oxide": "lithium_cobalt_oxide",
    "nmc": "lithium_nickel_manganese_cobalt_oxide",
    "lithium nickel manganese cobalt oxide": "lithium_nickel_manganese_cobalt_oxide",
    "lmo": "lithium_manganese_oxide",
    "lithium manganese oxide": "lithium_manganese_oxide",
    "lto": "lithium_titanate",
    "lithium titanate": "lithium_titanate",
    "lfo": "lithium_iron_oxide",
    "lithium iron oxide": "lithium_iron_oxide",
    "lithium iron phosphate": "lithium_iron_phosphate",
    "lfp": "lithium_iron_phosphate",
    "state of charge": "state_of_charge",
    "soc": "state_of_charge",
    "depth of discharge": "depth_of_discharge",
    "dod": "depth_of_discharge",
    "cycle life": "cycle_life",
    "capacity": "capacity",
    "specific capacity": "specific_capacity",
    "energy density": "energy_density",
    "power density": "power_density",
    "c-rate": "c_rate",
    "c rate": "c_rate",
    "charge rate": "c_rate",
    "discharge rate": "c_rate",
    "charging": "charging",
    "discharging": "discharging",
    "charge/discharge": "charge_discharge",
    "charge discharge": "charge_discharge",
    "intercalation": "intercalation",
    "deintercalation": "deintercalation",
    "solid electrolyte interphase": "sei",
    "sei": "sei",
    "electrochemical window": "electrochemical_window",
    "thermal runaway": "thermal_runaway",
    "battery management system": "battery_management_system",
    "bms": "battery_management_system",
    "battery pack": "battery_pack",
    "cell balancing": "cell_balancing",
    "calendar life": "calendar_life",
    "self discharge": "self_discharge",
    "self-discharge": "self_discharge",
    "battery degradation": "battery_degradation",
    "aging": "battery_degradation",
    "capacity fade": "capacity_fade",
    "electrochemical performance": "electrochemical_performance",

    # Proton Exchange Membrane Fuel Cells (PEMFC)
    "proton exchange membrane fuel cell": "pemfc",
    "pem fuel cell": "pemfc",
    "pemfc": "pemfc",
    "fuel cell": "fuel_cell",
    "membrane electrode assembly": "mea",
    "mea": "mea",
    "proton exchange membrane": "proton_exchange_membrane",
    "pem": "proton_exchange_membrane",
    "nafion": "nafion",
    "gas diffusion layer": "gdl",
    "gdl": "gdl",
    "catalyst layer": "catalyst_layer",
    "platinum catalyst": "platinum_catalyst",
    "pt catalyst": "platinum_catalyst",
    "hydrogen oxidation reaction": "hor",
    "hor": "hor",
    "oxygen reduction reaction": "orr",
    "orr": "orr",
    "water management": "water_management",
    "humidification": "humidification",
    "backpressure": "backpressure",
    "current collector": "current_collector",
    "flow field": "flow_field",
    "bipolar plate": "bipolar_plate",
    "single cell": "single_cell",
    "stack": "stack",
    "power output": "power_output",
    "efficiency": "efficiency",
    "start-up": "start_up",
    "start up": "start_up",
    "shutdown": "shutdown",
    "cold start": "cold_start",
    "hot start": "hot_start",
    "operating temperature": "operating_temperature",
    "operating pressure": "operating_pressure",
    "purge": "purge",
    "flooding": "flooding",
    "dry-out": "dry_out",
    "dry out": "dry_out",
    "cross-over": "cross_over",
    "cross over": "cross_over",
    "hydrogen cross-over": "cross_over",
    "oxygen cross-over": "cross_over",
    "carbon monoxide poisoning": "co_poisoning",
    "co poisoning": "co_poisoning",
    "degradation": "degradation",
    "durability": "durability",

    # Water Electrolysis (Alkaline, PEM, SOEC)
    "water electrolysis": "water_electrolysis",
    "electrolysis": "water_electrolysis",
    "alkaline electrolysis": "alkaline_electrolysis",
    "pem electrolysis": "pem_electrolysis",
    "soec": "soec",
    "solid oxide electrolysis cell": "soec",
    "solid oxide electrolysis": "soec",
    "hydrogen evolution reaction": "her",
    "her": "her",
    "oxygen evolution reaction": "oer",
    "oer": "oer",
    "electrolyzer": "electrolyzer",
    "electrolyser": "electrolyzer",
    "cathodic reaction": "cathodic_reaction",
    "anodic reaction": "anodic_reaction",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "current efficiency": "current_efficiency",
    "faradaic efficiency": "faradaic_efficiency",
    "hydrogen production": "hydrogen_production",
    "oxygen production": "oxygen_production",
    "gas purity": "gas_purity",
    "gas separation": "gas_separation",
    "membrane": "membrane",
    "diaphragm": "diaphragm",
    "alkaline electrolyte": "alkaline_electrolyte",
    "potassium hydroxide": "alkaline_electrolyte",
    "koh": "alkaline_electrolyte",
    "acidic electrolyte": "acidic_electrolyte",
    "proton conductor": "proton_conductor",
    "solid oxide": "solid_oxide",
    "zirconia": "zirconia",
    "yttria-stabilized zirconia": "yttria_stabilized_zirconia",
    "ysz": "yttria_stabilized_zirconia",
    "nickel electrode": "nickel_electrode",
    "iridium electrode": "iridium_electrode",
    "ruthenium electrode": "ruthenium_electrode",
    "electrocatalyst": "electrocatalyst",
    "catalyst": "electrocatalyst",
    "electrocatalysis": "electrocatalysis",
    "electrodeposition": "electrodeposition",
    "deposition": "electrodeposition",
    "coating": "electrodeposition",

    # Corrosion Electrochemistry and Polarization Curves
    "corrosion": "corrosion",
    "corrosion electrochemistry": "corrosion",
    "corrosion cell": "corrosion_cell",
    "corrosion rate": "corrosion_rate",
    "polarization curve": "polarization_curve",
    "polarization resistance": "polarization_resistance",
    "rp": "polarization_resistance",
    "r_p": "polarization_resistance",
    "passivation": "passivation",
    "passive film": "passive_film",
    "active corrosion": "active_corrosion",
    "localized corrosion": "localized_corrosion",
    "uniform corrosion": "uniform_corrosion",
    "pitting corrosion": "pitting_corrosion",
    "crevice corrosion": "crevice_corrosion",
    "intergranular corrosion": "intergranular_corrosion",
    "stress corrosion": "stress_corrosion",
    "stress corrosion cracking": "stress_corrosion",
    "galvanic corrosion": "galvanic_corrosion",
    "electrochemical noise": "electrochemical_noise",
    "electrochemical monitoring": "electrochemical_monitoring",
    "corrosion inhibitor": "corrosion_inhibitor",
    "inhibitor": "corrosion_inhibitor",
    "protection": "corrosion_protection",
    "cathodic protection": "cathodic_protection",
    "anodic protection": "anodic_protection",
    "coating": "corrosion_protection",
    "sacrificial anode": "sacrificial_anode",
    "zinc anode": "sacrificial_anode",
    "magnesium anode": "sacrificial_anode",
    "corrosion potential": "corrosion_potential",
    "ecorr": "corrosion_potential",
    "e_corr": "corrosion_potential",
    "tafel extrapolation": "tafel_extrapolation",
    "tafel slope": "tafel_slope",
    "electrochemical impedance": "impedance",
    "electrochemical polarization": "polarization",
    "polarization measurement": "polarization_measurement",

    # Electroplating and Electrodeposition
    "electroplating": "electroplating",
    "electrodeposition": "electrodeposition",
    "plating": "electroplating",
    "metal plating": "electroplating",
    "galvanization": "galvanization",
    "galvanic plating": "electroplating",
    "anodizing": "anodizing",
    "anodisation": "anodizing",
    "anodic oxidation": "anodizing",
    "cathodic plating": "electroplating",
    "electroforming": "electroforming",
    "electropolishing": "electropolishing",
    "electrorefining": "electrorefining",
    "electrowinning": "electrowinning",
    "metal deposition": "electrodeposition",
    "current efficiency": "current_efficiency",
    "throwing power": "throwing_power",
    "brightener": "brightener",
    "leveler": "leveler",
    "additive": "additive",
    "bath": "bath",
    "electrolyte bath": "bath",
    "solution": "bath",
    "substrate": "substrate",
    "surface preparation": "surface_preparation",
    "cleaning": "surface_preparation",
    "activation": "activation",
    "seed layer": "seed_layer",
    "nucleation": "nucleation",
    "growth": "growth",
    "grain size": "grain_size",
    "microstructure": "microstructure",
    "crystallinity": "crystallinity",
    "porosity": "porosity",
    "adhesion": "adhesion",
    "coating thickness": "coating_thickness",
    "layer thickness": "coating_thickness",
    "current distribution": "current_distribution",
    "potential distribution": "potential_distribution",

    # Supercapacitors and Double-Layer Capacitance
    "supercapacitor": "supercapacitor",
    "ultracapacitor": "supercapacitor",
    "electrochemical capacitor": "supercapacitor",
    "edlc": "edlc",
    "electric double layer capacitor": "edlc",
    "double layer capacitance": "double_layer_capacitance",
    "pseudocapacitance": "pseudocapacitance",
    "faradaic capacitance": "pseudocapacitance",
    "capacitance": "capacitance",
    "specific capacitance": "specific_capacitance",
    "energy density": "energy_density",
    "power density": "power_density",
    "charge storage": "charge_storage",
    "charge/discharge": "charge_discharge",
    "charge discharge": "charge_discharge",
    "cycling": "cycling",
    "cycle life": "cycle_life",
    "electrode material": "electrode_material",
    "carbon material": "carbon_material",
    "activated carbon": "carbon_material",
    "carbon nanotube": "carbon_nanotube",
    "cnt": "carbon_nanotube",
    "graphene": "graphene",
    "conducting polymer": "conducting_polymer",
    "polyaniline": "polyaniline",
    "polypyrrole": "polypyrrole",
    "redox capacitor": "redox_capacitor",
    "hybrid capacitor": "hybrid_capacitor",
    "asymmetric capacitor": "asymmetric_capacitor",
    "symmetrical capacitor": "symmetrical_capacitor",
    "electrolyte": "electrolyte",
    "aqueous electrolyte": "aqueous_electrolyte",
    "organic electrolyte": "organic_electrolyte",
    "ionic liquid": "ionic_liquid",
    "separator": "separator",
    "self discharge": "self_discharge",
    "self-discharge": "self_discharge",
    "leakage current": "leakage_current",
    "esr": "equivalent_series_resistance",
    "equivalent series resistance": "equivalent_series_resistance",
    "impedance": "impedance",
    "charging": "charging",
    "discharging": "discharging",

    # Potentiostats and Electrochemical Instrumentation
    "potentiostat": "potentiostat",
    "galvanostat": "galvanostat",
    "electrochemical workstation": "electrochemical_workstation",
    "electrochemical analyzer": "electrochemical_analyzer",
    "instrumentation": "instrumentation",
    "three-electrode system": "three_electrode_system",
    "three electrode system": "three_electrode_system",
    "two-electrode system": "two_electrode_system",
    "two electrode system": "two_electrode_system",
    "reference electrode": "reference_electrode",
    "working electrode": "working_electrode",
    "counter electrode": "counter_electrode",
    "auxiliary electrode": "counter_electrode",
    "cell": "electrochemical_cell",
    "cell holder": "cell_holder",
    "sample holder": "cell_holder",
    "electrode holder": "cell_holder",
    "electrode array": "electrode_array",
    "multichannel potentiostat": "multichannel_potentiostat",
    "multichannel": "multichannel_potentiostat",
    "data acquisition": "data_acquisition",
    "daq": "data_acquisition",
    "software": "software",
    "control": "control",
    "measurement": "measurement",
    "current measurement": "current_measurement",
    "voltage measurement": "voltage_measurement",
    "scan rate": "scan_rate",
    "sampling rate": "sampling_rate",
    "sampling": "sampling",
    "calibration": "calibration",
    "noise": "noise",
    "shielding": "shielding",
    "grounding": "grounding",
    "filtering": "filtering",
    "amplifier": "amplifier",
    "current amplifier": "current_amplifier",
    "voltage amplifier": "voltage_amplifier",
    "feedback": "feedback",
    "control loop": "control_loop",
    "power supply": "power_supply",
    "dc power supply": "power_supply",
    "ac power supply": "power_supply",
    "battery": "battery",
    "battery holder": "battery_holder",

    # Electrochemical Sensors and Biosensors
    "electrochemical sensor": "electrochemical_sensor",
    "sensor": "electrochemical_sensor",
    "biosensor": "biosensor",
    "electrochemical biosensor": "biosensor",
    "enzyme sensor": "enzyme_sensor",
    "glucose sensor": "glucose_sensor",
    "immunosensor": "immunosensor",
    "dna sensor": "dna_sensor",
    "rna sensor": "rna_sensor",
    "aptasensor": "aptasensor",
    "microelectrode": "microelectrode",
    "nanoelectrode": "nanoelectrode",
    "microelectrode array": "microelectrode_array",
    "nanoelectrode array": "nanoelectrode_array",
    "screen printed electrode": "screen_printed_electrode",
    "spe": "screen_printed_electrode",
    "interdigitated electrode": "interdigitated_electrode",
    "ide": "interdigitated_electrode",
    "label-free detection": "label_free_detection",
    "label free detection": "label_free_detection",
    "amperometric sensor": "amperometric_sensor",
    "potentiometric sensor": "potentiometric_sensor",
    "conductometric sensor": "conductometric_sensor",
    "voltammetric sensor": "voltammetric_sensor",
    "impedimetric sensor": "impedimetric_sensor",
    "electrochemical detection": "electrochemical_detection",
    "signal amplification": "signal_amplification",
    "transducer": "transducer",
    "recognition element": "recognition_element",
    "bioreceptor": "recognition_element",
    "antibody": "recognition_element",
    "antigen": "recognition_element",
    "enzyme": "enzyme",
    "probe": "probe",
    "target": "target",
    "analyte": "analyte",
    "sample": "sample",
    "sample preparation": "sample_preparation",
    "pre-treatment": "sample_preparation",
    "pretreatment": "sample_preparation",
    "calibration curve": "calibration_curve",
    "response": "response",
    "signal": "signal",
    "limit of detection": "limit_of_detection",
    "lod": "limit_of_detection",
    "sensitivity": "sensitivity",
    "selectivity": "selectivity",
    "specificity": "specificity",
    "linear range": "linear_range",
    "dynamic range": "dynamic_range",
    "reproducibility": "reproducibility",
    "stability": "stability",

    # Electrochemical Capacitors vs Batteries
    "electrochemical capacitor": "supercapacitor",
    "supercapacitor": "supercapacitor",
    "battery": "battery",
    "lithium-ion battery": "lithium_ion_battery",
    "li-ion battery": "lithium_ion_battery",
    "energy density": "energy_density",
    "power density": "power_density",
    "cycle life": "cycle_life",
    "charging": "charging",
    "discharging": "discharging",
    "charge/discharge": "charge_discharge",
    "charge discharge": "charge_discharge",
    "self discharge": "self_discharge",
    "self-discharge": "self_discharge",
    "specific capacity": "specific_capacity",
    "specific capacitance": "specific_capacitance",
    "rate capability": "rate_capability",
    "c-rate": "c_rate",
    "c rate": "c_rate",
    "voltage": "voltage",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "electrolyte": "electrolyte",
    "separator": "separator",
    "electrode": "electrode",
    "electrode material": "electrode_material",
    "carbon material": "carbon_material",
    "activated carbon": "carbon_material",
    "carbon nanotube": "carbon_nanotube",
    "cnt": "carbon_nanotube",
    "graphene": "graphene",
    "conducting polymer": "conducting_polymer",
    "polyaniline": "polyaniline",
    "polypyrrole": "polypyrrole",
    "redox capacitor": "redox_capacitor",
    "hybrid capacitor": "hybrid_capacitor",
    "asymmetric capacitor": "asymmetric_capacitor",
    "symmetrical capacitor": "symmetrical_capacitor",

    # Electrowinning and Electrorefining of Metals
    "electrowinning": "electrowinning",
    "electrorefining": "electrorefining",
    "metal extraction": "electrowinning",
    "metal refining": "electrorefining",
    "hydrometallurgy": "hydrometallurgy",
    "pyrometallurgy": "pyrometallurgy",
    "leaching": "leaching",
    "solvent extraction": "solvent_extraction",
    "precipitation": "precipitation",
    "purification": "purification",
    "electrolyte": "electrolyte",
    "anode": "anode",
    "cathode": "cathode",
    "current density": "current_density",
    "overpotential": "overpotential",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "electrochemical cell": "electrochemical_cell",
    "electrolytic cell": "electrochemical_cell",
    "impurity": "impurity",
    "impurities": "impurity",
    "deposit": "deposit",
    "metal deposit": "deposit",
    "sludge": "sludge",
    "waste": "waste",
    "recycling": "recycling",
    "recovery": "recovery",
    "efficiency": "efficiency",

    # Electron Transfer Kinetics and Marcus Theory
    "electron transfer": "electron_transfer",
    "electron transfer kinetics": "electron_transfer_kinetics",
    "marcus theory": "marcus_theory",
    "marcus equation": "marcus_theory",
    "marcus model": "marcus_theory",
    "reorganization energy": "reorganization_energy",
    "lambda": "reorganization_energy",
    "activation energy": "activation_energy",
    "rate constant": "rate_constant",
    "k": "rate_constant",
    "transfer coefficient": "transfer_coefficient",
    "symmetry factor": "transfer_coefficient",
    "charge transfer": "charge_transfer",
    "charge transfer resistance": "charge_transfer_resistance",
    "rct": "charge_transfer_resistance",
    "r_ct": "charge_transfer_resistance",
    "electron tunneling": "electron_tunneling",
    "tunneling": "electron_tunneling",
    "quantum tunneling": "electron_tunneling",
    "adiabatic transfer": "adiabatic_transfer",
    "nonadiabatic transfer": "nonadiabatic_transfer",
    "adiabatic": "adiabatic_transfer",
    "nonadiabatic": "nonadiabatic_transfer",
    "outer sphere": "outer_sphere",
    "inner sphere": "inner_sphere",
    "solvent reorganization": "solvent_reorganization",
    "solvent effect": "solvent_effect",
    "electronic coupling": "electronic_coupling",
    "coupling": "electronic_coupling",
    "transition state": "transition_state",
    "reaction coordinate": "reaction_coordinate",
    "potential energy surface": "potential_energy_surface",

    # Electrochemical CO2 Reduction
    "co2 reduction": "co2_reduction",
    "electrochemical co2 reduction": "co2_reduction",
    "ecr": "co2_reduction",
    "carbon dioxide reduction": "co2_reduction",
    "co2 electrolysis": "co2_reduction",
    "co2 conversion": "co2_reduction",
    "co2 utilization": "co2_reduction",
    "co2 fixation": "co2_reduction",
    "co2 capture": "co2_capture",
    "co2 sequestration": "co2_capture",
    "co2 storage": "co2_capture",
    "catalyst": "electrocatalyst",
    "electrocatalyst": "electrocatalyst",
    "copper catalyst": "copper_catalyst",
    "silver catalyst": "silver_catalyst",
    "gold catalyst": "gold_catalyst",
    "product selectivity": "product_selectivity",
    "faradaic efficiency": "faradaic_efficiency",
    "current efficiency": "current_efficiency",
    "gas diffusion electrode": "gas_diffusion_electrode",
    "gde": "gas_diffusion_electrode",
    "flow cell": "flow_cell",
    "membrane": "membrane",
    "electrolyte": "electrolyte",
    "ph": "ph",
    "ph effect": "ph_effect",
    "ph dependence": "ph_effect",
    "overpotential": "overpotential",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "reaction pathway": "reaction_pathway",
    "intermediate": "intermediate",
    "product distribution": "product_distribution",
    "selectivity": "selectivity",
    "conversion": "conversion",
    "yield": "yield",
    "carbon monoxide": "carbon_monoxide",
    "formate": "formate",
    "methanol": "methanol",
    "ethanol": "ethanol",
    "acetate": "acetate",
    "hydrocarbon": "hydrocarbon",

    # Ionic Conductivity in Solid Electrolytes
    "ionic conductivity": "ionic_conductivity",
    "ion conductivity": "ionic_conductivity",
    "conductivity": "conductivity",
    "solid electrolyte": "solid_electrolyte",
    "li conductor": "solid_electrolyte",
    "li ion conductor": "solid_electrolyte",
    "ceramic electrolyte": "solid_electrolyte",
    "polymer electrolyte": "polymer_electrolyte",
    "glass electrolyte": "glass_electrolyte",
    "sulfide electrolyte": "sulfide_electrolyte",
    "oxide electrolyte": "oxide_electrolyte",
    "proton conductor": "proton_conductor",
    "proton conductivity": "proton_conductivity",
    "ionic transport": "ionic_transport",
    "ion transport": "ionic_transport",
    "migration": "migration",
    "diffusion": "diffusion",
    "diffusion coefficient": "diffusion_coefficient",
    "activation energy": "activation_energy",
    "arrhenius equation": "arrhenius_equation",
    "arrhenius plot": "arrhenius_plot",
    "impedance": "impedance",
    "electrochemical impedance": "impedance",
    "nyquist plot": "nyquist_plot",
    "bode plot": "bode_plot",
    "electrochemical window": "electrochemical_window",
    "stability window": "electrochemical_window",
    "electrochemical stability": "electrochemical_window",
    "grain boundary": "grain_boundary",
    "interface": "interface",
    "interfacial resistance": "interfacial_resistance",
    "bulk resistance": "bulk_resistance",
    "total resistance": "total_resistance",

    # Redox Flow Batteries
    "redox flow battery": "redox_flow_battery",
    "flow battery": "redox_flow_battery",
    "rfb": "redox_flow_battery",
    "vanadium redox battery": "vanadium_redox_battery",
    "vrb": "vanadium_redox_battery",
    "vanadium flow battery": "vanadium_redox_battery",
    "electrolyte": "electrolyte",
    "anolyte": "anolyte",
    "catholyte": "catholyte",
    "membrane": "membrane",
    "separator": "separator",
    "cell": "electrochemical_cell",
    "stack": "stack",
    "tank": "tank",
    "pump": "pump",
    "flow cell": "flow_cell",
    "current density": "current_density",
    "overpotential": "overpotential",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "energy efficiency": "energy_efficiency",
    "coulombic efficiency": "coulombic_efficiency",
    "voltage efficiency": "voltage_efficiency",
    "power density": "power_density",
    "energy density": "energy_density",
    "cycle life": "cycle_life",
    "charging": "charging",
    "discharging": "discharging",
    "charge/discharge": "charge_discharge",
    "charge discharge": "charge_discharge",
    "self discharge": "self_discharge",
    "self-discharge": "self_discharge",
    "electrode": "electrode",
    "carbon felt": "carbon_felt",
    "graphite felt": "carbon_felt",
    "electrochemical performance": "electrochemical_performance",

    # pH Measurement and Glass Electrode
    "ph": "ph",
    "ph measurement": "ph_measurement",
    "ph meter": "ph_meter",
    "glass electrode": "glass_electrode",
    "reference electrode": "reference_electrode",
    "calibration": "calibration",
    "buffer solution": "buffer_solution",
    "buffer": "buffer_solution",
    "standard solution": "standard_solution",
    "electrolyte": "electrolyte",
    "junction potential": "junction_potential",
    "temperature compensation": "temperature_compensation",
    "automatic temperature compensation": "temperature_compensation",
    "atc": "temperature_compensation",
    "response time": "response_time",
    "drift": "drift",
    "slope": "slope",
    "intercept": "intercept",
    "electrode maintenance": "electrode_maintenance",
    "cleaning": "electrode_maintenance",
    "storage": "storage",
    "electrode aging": "electrode_aging",
    "electrode calibration": "electrode_calibration",
    "measurement": "measurement",
    "signal": "signal",
    "output": "output",
    "display": "display",
    "readout": "display",

    # Electrochemical Machining (ECM)
    "electrochemical machining": "ecm",
    "ecm": "ecm",
    "electrochemical milling": "ecm",
    "electrochemical drilling": "ecm",
    "electrochemical grinding": "ecm",
    "electrochemical shaping": "ecm",
    "electrochemical cutting": "ecm",
    "electrochemical removal": "ecm",
    "machining": "machining",
    "material removal": "material_removal",
    "tool": "tool",
    "cathode": "cathode",
    "workpiece": "workpiece",
    "anode": "anode",
    "electrolyte": "electrolyte",
    "current density": "current_density",
    "overpotential": "overpotential",
    "cell voltage": "cell_voltage",
    "cell potential": "cell_voltage",
    "gap": "gap",
    "interelectrode gap": "gap",
    "feed rate": "feed_rate",
    "surface finish": "surface_finish",
    "precision": "precision",
    "accuracy": "accuracy",
    "efficiency": "efficiency",
    "waste": "waste",
    "sludge": "sludge",
    "recycling": "recycling",
    "cooling": "cooling",
    "temperature": "temperature",
    "control": "control",
    "automation": "automation",
    "process monitoring": "process_monitoring",
    "process control": "process_control",
    "electrochemical process": "electrochemical_process",
    "electrochemical reaction": "electrochemical_reaction",
    "passivation": "passivation",
    "corrosion": "corrosion",
    "electrochemical corrosion": "corrosion",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}:{SEMANTIC_MAP_AUTHOR}:{SEMANTIC_MAP_ENGINE}:{_EXPECTED_ENTRY_COUNT}"
    data = meta + "|" + joined
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.lower().strip()
    t = re.sub(r"[\s\-_/]+", " ", t)
    t = t.replace("°", "0")
    t = t.replace("'", "")
    t = t.replace("\"", "")
    t = t.replace(".", "")
    t = t.replace(",", "")
    t = t.replace("–", "-")
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try removing plural
    if t.endswith("s") and t[:-1] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-1]]
    # Try removing "-ed" or "-ing"
    if t.endswith("ed") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    if t.endswith("ing") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    # Try removing "-es"
    if t.endswith("es") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing "-er"
    if t.endswith("er") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing "-ly"
    if t.endswith("ly") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing "-ment"
    if t.endswith("ment") and t[:-4] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-4]]
    # Try removing "-ion"
    if t.endswith("ion") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    # Try removing "-ity"
    if t.endswith("ity") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    return t

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == norm and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)