import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MATH10_engine_team"
SEMANTIC_MAP_ENGINE = "MATH10_geometry"

SEMANTIC_MAP = {
    "triangle": "triangle",
    "triangles": "triangle",
    "tri": "triangle",
    "trngl": "triangle",
    "trngle": "triangle",
    "trangle": "triangle",
    "trigon": "triangle",
    "triad": "triangle",
    "3-sided polygon": "triangle",
    "equilateral triangle": "equilateral_triangle",
    "eq triangle": "equilateral_triangle",
    "eq_trngl": "equilateral_triangle",
    "equal triangle": "equilateral_triangle",
    "equi triangle": "equilateral_triangle",
    "equiangular triangle": "equilateral_triangle",
    "isosceles triangle": "isosceles_triangle",
    "iso triangle": "isosceles_triangle",
    "iso_trngl": "isosceles_triangle",
    "isosc triangle": "isosceles_triangle",
    "isoceles triangle": "isosceles_triangle",
    "isoc triangle": "isosceles_triangle",
    "scalene triangle": "scalene_triangle",
    "scalene trngl": "scalene_triangle",
    "scalene tri": "scalene_triangle",
    "right triangle": "right_triangle",
    "rt triangle": "right_triangle",
    "rt_trngl": "right_triangle",
    "right-angled triangle": "right_triangle",
    "right angle triangle": "right_triangle",
    "rightangled triangle": "right_triangle",
    "acute triangle": "acute_triangle",
    "acute trngl": "acute_triangle",
    "acute tri": "acute_triangle",
    "obtuse triangle": "obtuse_triangle",
    "obtuse trngl": "obtuse_triangle",
    "obtuse tri": "obtuse_triangle",
    "polygon": "polygon",
    "polygons": "polygon",
    "poly": "polygon",
    "plgn": "polygon",
    "polygone": "polygon",
    "n-gon": "polygon",
    "ngon": "polygon",
    "regular polygon": "regular_polygon",
    "reg polygon": "regular_polygon",
    "reg_poly": "regular_polygon",
    "regular poly": "regular_polygon",
    "quadrilateral": "quadrilateral",
    "quadrilaterals": "quadrilateral",
    "quad": "quadrilateral",
    "quadrlateral": "quadrilateral",
    "qudrilateral": "quadrilateral",
    "4-sided polygon": "quadrilateral",
    "rectangle": "rectangle",
    "rect": "rectangle",
    "rectngle": "rectangle",
    "rectangl": "rectangle",
    "rectangular": "rectangle",
    "square": "square",
    "sq": "square",
    "sqr": "square",
    "squre": "square",
    "parallelogram": "parallelogram",
    "parallelograms": "parallelogram",
    "parallelogramm": "parallelogram",
    "parallogram": "parallelogram",
    "parallelogramme": "parallelogram",
    "rhombus": "rhombus",
    "rhomb": "rhombus",
    "rhomboid": "rhombus",
    "rhombuses": "rhombus",
    "trapezoid": "trapezoid",
    "trapezium": "trapezoid",
    "trap": "trapezoid",
    "trapezoids": "trapezoid",
    "trapezia": "trapezoid",
    "kite": "kite",
    "kites": "kite",
    "circle": "circle",
    "circles": "circle",
    "circ": "circle",
    "cercle": "circle",
    "circumference": "circumference",
    "circumferance": "circumference",
    "circum": "circumference",
    "radius": "radius",
    "radii": "radius",
    "rad": "radius",
    "diameter": "diameter",
    "diam": "diameter",
    "diamerter": "diameter",
    "center": "center",
    "centre": "center",
    "centroid": "centroid",
    "center of mass": "centroid",
    "circumcenter": "circumcenter",
    "circumcentre": "circumcenter",
    "incenter": "incenter",
    "incentre": "incenter",
    "orthocenter": "orthocenter",
    "orthocentre": "orthocenter",
    "median": "median",
    "medians": "median",
    "altitude": "altitude",
    "altitudes": "altitude",
    "height": "altitude",
    "heights": "altitude",
    "perpendicular": "perpendicular",
    "perpendiculars": "perpendicular",
    "perp": "perpendicular",
    "parallel": "parallel",
    "parallels": "parallel",
    "parl": "parallel",
    "line": "line",
    "lines": "line",
    "ln": "line",
    "segment": "segment",
    "segments": "segment",
    "sgmt": "segment",
    "ray": "ray",
    "rays": "ray",
    "angle": "angle",
    "angles": "angle",
    "ang": "angle",
    "vertex": "vertex",
    "vertices": "vertex",
    "vert": "vertex",
    "side": "side",
    "sides": "side",
    "edge": "side",
    "edges": "side",
    "base": "base",
    "bases": "base",
    "apex": "apex",
    "apices": "apex",
    "area": "area",
    "areas": "area",
    "surface area": "area",
    "perimeter": "perimeter",
    "perimeters": "perimeter",
    "perim": "perimeter",
    "volume": "volume",
    "vol": "volume",
    "volumes": "volume",
    "length": "length",
    "width": "width",
    "breadth": "width",
    "height": "height",
    "altitude": "height",
    "distance": "distance",
    "dist": "distance",
    "arc": "arc",
    "arcs": "arc",
    "sector": "sector",
    "sectors": "sector",
    "segment (circle)": "circle_segment",
    "circle segment": "circle_segment",
    "chord": "chord",
    "chords": "chord",
    "tangent": "tangent",
    "tangents": "tangent",
    "secant": "secant",
    "secants": "secant",
    "ellipse": "ellipse",
    "ellipses": "ellipse",
    "oval": "ellipse",
    "major axis": "major_axis",
    "minor axis": "minor_axis",
    "focus": "focus",
    "foci": "focus",
    "hyperbola": "hyperbola",
    "hyperbolas": "hyperbola",
    "asymptote": "asymptote",
    "asymptotes": "asymptote",
    "parabola": "parabola",
    "parabolas": "parabola",
    "directrix": "directrix",
    "directrices": "directrix",
    "locus": "locus",
    "loci": "locus",
    "coordinate": "coordinate",
    "coordinates": "coordinate",
    "cartesian": "cartesian",
    "cartesian plane": "cartesian_plane",
    "xy-plane": "cartesian_plane",
    "plane": "plane",
    "planes": "plane",
    "space": "space",
    "dimension": "dimension",
    "dimensions": "dimension",
    "2d": "2d",
    "2-d": "2d",
    "two dimensional": "2d",
    "3d": "3d",
    "3-d": "3d",
    "three dimensional": "3d",
    "point": "point",
    "points": "point",
    "pt": "point",
    "intersection": "intersection",
    "intersections": "intersection",
    "union": "union",
    "unions": "union",
    "set": "set",
    "sets": "set",
    "congruent": "congruent",
    "congruence": "congruent",
    "congruent figures": "congruent",
    "similar": "similar",
    "similarity": "similar",
    "similar figures": "similar",
    "equal": "equal",
    "equality": "equal",
    "equidistant": "equidistant",
    "equidistance": "equidistant",
    "bisector": "bisector",
    "bisectors": "bisector",
    "angle bisector": "angle_bisector",
    "midpoint": "midpoint",
    "midpoints": "midpoint",
    "mid point": "midpoint",
    "reflection": "reflection",
    "reflections": "reflection",
    "mirror": "reflection",
    "rotation": "rotation",
    "rotations": "rotation",
    "translate": "translation",
    "translation": "translation",
    "translations": "translation",
    "dilation": "dilation",
    "dilations": "dilation",
    "scaling": "dilation",
    "scale": "dilation",
    "enlargement": "dilation",
    "reduction": "dilation",
    "transformation": "transformation",
    "transformations": "transformation",
    "symmetry": "symmetry",
    "symmetries": "symmetry",
    "line of symmetry": "line_of_symmetry",
    "axis of symmetry": "axis_of_symmetry",
    "center of symmetry": "center_of_symmetry",
    "central symmetry": "center_of_symmetry",
    "rotational symmetry": "rotational_symmetry",
    "reflectional symmetry": "reflectional_symmetry",
    "mirror symmetry": "reflectional_symmetry",
    "pattern": "pattern",
    "patterns": "pattern",
    "tiling": "tiling",
    "tessellation": "tiling",
    "tessellations": "tiling",
    "grid": "grid",
    "grids": "grid",
    "lattice": "lattice",
    "lattices": "lattice",
    "vertex angle": "vertex_angle",
    "base angle": "base_angle",
    "interior angle": "interior_angle",
    "internal angle": "interior_angle",
    "exterior angle": "exterior_angle",
    "external angle": "exterior_angle",
    "supplementary angle": "supplementary_angle",
    "complementary angle": "complementary_angle",
    "adjacent angle": "adjacent_angle",
    "vertical angle": "vertical_angle",
    "opposite angle": "vertical_angle",
    "alternate angle": "alternate_angle",
    "corresponding angle": "corresponding_angle",
    "right angle": "right_angle",
    "acute angle": "acute_angle",
    "obtuse angle": "obtuse_angle",
    "straight angle": "straight_angle",
    "reflex angle": "reflex_angle",
    "full angle": "full_angle",
    "complete angle": "full_angle",
    "degree": "degree",
    "degrees": "degree",
    "deg": "degree",
    "radian": "radian",
    "radians": "radian",
    "rad": "radian",
    "pi": "pi",
    "π": "pi",
    "circumscribed": "circumscribed",
    "inscribed": "inscribed",
    "incircle": "incircle",
    "in circle": "incircle",
    "circumcircle": "circumcircle",
    "circum circle": "circumcircle",
    "tangent circle": "tangent_circle",
    "concentric": "concentric",
    "concentric circles": "concentric",
    "eccentric": "eccentric",
    "eccentric circles": "eccentric",
    "arc length": "arc_length",
    "sector area": "sector_area",
    "segment area": "segment_area",
    "chord length": "chord_length",
    "diameter length": "diameter_length",
    "radius length": "radius_length",
    "base length": "base_length",
    "height length": "height_length",
    "side length": "side_length",
    "edge length": "side_length",
    "perpendicular bisector": "perpendicular_bisector",
    "angle sum": "angle_sum",
    "angle total": "angle_sum",
    "angle difference": "angle_difference",
    "angle subtraction": "angle_difference",
    "angle addition": "angle_sum",
    "angle product": "angle_product",
    "angle ratio": "angle_ratio",
    "angle division": "angle_ratio",
    "angle measure": "angle_measure",
    "angle measurement": "angle_measure",
    "angle notation": "angle_notation",
    "angle symbol": "angle_notation",
    "polygonal": "polygon",
    "polygonal shape": "polygon",
    "polygon shape": "polygon",
    "polyhedron": "polyhedron",
    "polyhedra": "polyhedron",
    "solid": "solid",
    "solids": "solid",
    "prism": "prism",
    "prisms": "prism",
    "cube": "cube",
    "cuboid": "cuboid",
    "cuboids": "cuboid",
    "rectangular prism": "cuboid",
    "rectangular solid": "cuboid",
    "pyramid": "pyramid",
    "pyramids": "pyramid",
    "tetrahedron": "tetrahedron",
    "tetrahedra": "tetrahedron",
    "octahedron": "octahedron",
    "octahedra": "octahedron",
    "dodecahedron": "dodecahedron",
    "dodecahedra": "dodecahedron",
    "icosahedron": "icosahedron",
    "icosahedra": "icosahedron",
    "sphere": "sphere",
    "spheres": "sphere",
    "hemisphere": "hemisphere",
    "hemispheres": "hemisphere",
    "cylinder": "cylinder",
    "cylinders": "cylinder",
    "cone": "cone",
    "cones": "cone",
    "frustum": "frustum",
    "frustums": "frustum",
    "torus": "torus",
    "tori": "torus",
    "annulus": "annulus",
    "annuli": "annulus",
    "base area": "base_area",
    "lateral area": "lateral_area",
    "total area": "total_area",
    "surface": "surface",
    "surfaces": "surface",
    "face": "face",
    "faces": "face",
    "vertex": "vertex",
    "vertices": "vertex",
    "edge": "side",
    "edges": "side",
    "Euler's formula": "euler_formula",
    "euler formula": "euler_formula",
    "euler": "euler_formula",
    "net": "net",
    "nets": "net",
    "plan": "plan",
    "plans": "plan",
    "projection": "projection",
    "projections": "projection",
    "cross section": "cross_section",
    "cross-section": "cross_section",
    "section": "cross_section",
    "sections": "cross_section",
    "slice": "cross_section",
    "slices": "cross_section",
    "diagonal": "diagonal",
    "diagonals": "diagonal",
    "diagonal length": "diagonal_length",
    "diagonal area": "diagonal_area",
    "diagonal sum": "diagonal_sum",
    "diagonal difference": "diagonal_difference",
    "diagonal product": "diagonal_product",
    "diagonal ratio": "diagonal_ratio",
    "diagonal measure": "diagonal_measure",
    "diagonal notation": "diagonal_notation",
    "diagonal symbol": "diagonal_notation",
    "distance formula": "distance_formula",
    "midpoint formula": "midpoint_formula",
    "slope": "slope",
    "slopes": "slope",
    "gradient": "slope",
    "inclination": "slope",
    "intercept": "intercept",
    "intercepts": "intercept",
    "y-intercept": "y_intercept",
    "x-intercept": "x_intercept",
    "equation": "equation",
    "equations": "equation",
    "linear equation": "linear_equation",
    "quadratic equation": "quadratic_equation",
    "system of equations": "system_of_equations",
    "formula": "formula",
    "formulas": "formula",
    "theorem": "theorem",
    "theorems": "theorem",
    "lemma": "lemma",
    "lemmas": "lemma",
    "corollary": "corollary",
    "corollaries": "corollary",
    "proof": "proof",
    "proofs": "proof",
    "axiom": "axiom",
    "axioms": "axiom",
    "postulate": "postulate",
    "postulates": "postulate",
    "construction": "construction",
    "constructions": "construction",
    "draw": "construction",
    "drawing": "construction",
    "drawings": "construction",
    "sketch": "construction",
    "sketches": "construction",
    "diagram": "diagram",
    "diagrams": "diagram",
    "figure": "figure",
    "figures": "figure",
    "notation": "notation",
    "notations": "notation",
    "symbol": "notation",
    "symbols": "notation",
    "label": "label",
    "labels": "label",
    "mark": "label",
    "marks": "label",
    "property": "property",
    "properties": "property",
    "attribute": "property",
    "attributes": "property",
    "characteristic": "property",
    "characteristics": "property",
    "feature": "property",
    "features": "property",
    "relation": "relation",
    "relations": "relation",
    "relationship": "relation",
    "relationships": "relation",
    "proportion": "proportion",
    "proportions": "proportion",
    "ratio": "ratio",
    "ratios": "ratio",
    "fraction": "fraction",
    "fractions": "fraction",
    "part": "part",
    "parts": "part",
    "whole": "whole",
    "wholes": "whole",
    "segment": "segment",
    "segments": "segment",
    "partition": "partition",
    "partitions": "partition",
    "divide": "partition",
    "division": "partition",
    "divisions": "partition",
    "split": "partition",
    "splits": "partition",
    "join": "union",
    "joins": "union",
    "combine": "union",
    "combines": "union",
    "union": "union",
    "unions": "union",
    "intersection": "intersection",
    "intersections": "intersection",
    "overlap": "intersection",
    "overlaps": "intersection",
    "touch": "intersection",
    "touches": "intersection",
    "meet": "intersection",
    "meets": "intersection",
    "cross": "intersection",
    "crosses": "intersection",
    "adjacent": "adjacent",
    "adjacency": "adjacent",
    "neighbor": "adjacent",
    "neighbors": "adjacent",
    "next to": "adjacent",
    "beside": "adjacent",
    "contiguous": "adjacent",
    "continuous": "continuous",
    "continuity": "continuous",
    "discrete": "discrete",
    "discreteness": "discrete",
    "boundary": "boundary",
    "boundaries": "boundary",
    "border": "boundary",
    "borders": "boundary",
    "limit": "boundary",
    "limits": "boundary",
    "enclosure": "boundary",
    "enclosures": "boundary",
    "inside": "interior",
    "interior": "interior",
    "outside": "exterior",
    "exterior": "exterior",
    "internal": "interior",
    "external": "exterior",
    "contained": "interior",
    "contain": "interior",
    "contains": "interior",
    "outside of": "exterior",
    "outside the": "exterior",
    "outside area": "exterior",
    "inside area": "interior",
    "enclosed": "interior",
    "enclosing": "interior",
    "enclose": "interior",
    "open": "open",
    "closed": "closed",
    "closure": "closed",
    "open set": "open",
    "closed set": "closed",
    "open region": "open",
    "closed region": "closed",
    "open interval": "open",
    "closed interval": "closed",
    "interval": "interval",
    "intervals": "interval",
    "range": "interval",
    "ranges": "interval",
    "domain": "domain",
    "domains": "domain",
    "codomain": "codomain",
    "codomains": "codomain",
    "mapping": "mapping",
    "mappings": "mapping",
    "function": "function",
    "functions": "function",
    "map": "mapping",
    "maps": "mapping",
    "projection": "projection",
    "projections": "projection",
    "image": "image",
    "images": "image",
    "preimage": "preimage",
    "preimages": "preimage",
    "inverse": "inverse",
    "inverses": "inverse",
    "invert": "inverse",
    "inverted": "inverse",
    "reflection": "reflection",
    "reflections": "reflection",
    "mirror": "reflection",
    "mirrors": "reflection",
    "flip": "reflection",
    "flips": "reflection",
    "rotate": "rotation",
    "rotates": "rotation",
    "rotated": "rotation",
    "turn": "rotation",
    "turns": "rotation",
    "spin": "rotation",
    "spins": "rotation",
    "translate": "translation",
    "translates": "translation",
    "translated": "translation",
    "move": "translation",
    "moves": "translation",
    "moved": "translation",
    "shift": "translation",
    "shifts": "translation",
    "shifted": "translation",
    "slide": "translation",
    "slides": "translation",
    "slided": "translation",
    "dilate": "dilation",
    "dilates": "dilation",
    "dilated": "dilation",
    "enlarge": "dilation",
    "enlarges": "dilation",
    "enlarged": "dilation",
    "reduce": "dilation",
    "reduces": "dilation",
    "reduced": "dilation",
    "scale": "dilation",
    "scales": "dilation",
    "scaled": "dilation",
    "magnify": "dilation",
    "magnifies": "dilation",
    "magnified": "dilation",
    "shrink": "dilation",
    "shrinks": "dilation",
    "shrunk": "dilation",
    "compress": "dilation",
    "compresses": "dilation",
    "compressed": "dilation",
    "stretch": "dilation",
    "stretches": "dilation",
    "stretched": "dilation",
    "expand": "dilation",
    "expands": "dilation",
    "expanded": "dilation",
    "contract": "dilation",
    "contracts": "dilation",
    "contracted": "dilation",
    "transform": "transformation",
    "transforms": "transformation",
    "transformed": "transformation",
    "change": "transformation",
    "changes": "transformation",
    "changed": "transformation",
    "morph": "transformation",
    "morphs": "transformation",
    "morphed": "transformation",
    "symmetry": "symmetry",
    "symmetries": "symmetry",
    "symmetric": "symmetry",
    "symmetrical": "symmetry",
    "asymmetric": "asymmetry",
    "asymmetrical": "asymmetry",
    "asymmetry": "asymmetry",
    "pattern": "pattern",
    "patterns": "pattern",
    "repeat": "pattern",
    "repeats": "pattern",
    "repeated": "pattern",
    "repetition": "pattern",
    "tessellation": "tiling",
    "tessellate": "tiling",
    "tessellates": "tiling",
    "tessellated": "tiling",
    "tiling": "tiling",
    "tile": "tiling",
    "tiles": "tiling",
    "tiled": "tiling",
    "grid": "grid",
    "grids": "grid",
    "lattice": "lattice",
    "lattices": "lattice",
    "array": "grid",
    "arrays": "grid",
    "matrix": "grid",
    "matrices": "grid",
    "network": "graph",
    "networks": "graph",
    "graph": "graph",
    "graphs": "graph",
    "node": "vertex",
    "nodes": "vertex",
    "edge": "side",
    "edges": "side",
    "arc": "arc",
    "arcs": "arc",
    "loop": "arc",
    "loops": "arc",
    "cycle": "cycle",
    "cycles": "cycle",
    "path": "path",
    "paths": "path",
    "walk": "path",
    "walks": "path",
    "route": "path",
    "routes": "path",
    "trail": "path",
    "trails": "path",
    "circuit": "cycle",
    "circuits": "cycle",
    "tree": "tree",
    "trees": "tree",
    "leaf": "leaf",
    "leaves": "leaf",
    "root": "root",
    "roots": "root",
    "branch": "branch",
    "branches": "branch",
    "degree (vertex)": "degree_vertex",
    "degree of vertex": "degree_vertex",
    "degree (angle)": "degree",
    "degree of angle": "degree",
    "adjacent vertex": "adjacent_vertex",
    "adjacent edge": "adjacent_edge",
    "incident": "incident",
    "incidence": "incident",
    "incident edge": "incident_edge",
    "incident vertex": "incident_vertex",
    "planar": "planar",
    "planarity": "planar",
    "nonplanar": "nonplanar",
    "non-planar": "nonplanar",
    "embedding": "embedding",
    "embeddings": "embedding",
    "face (graph)": "face_graph",
    "faces (graph)": "face_graph",
    "region (graph)": "face_graph",
    "regions (graph)": "face_graph",
    "complete graph": "complete_graph",
    "cycle graph": "cycle_graph",
    "path graph": "path_graph",
    "tree graph": "tree_graph",
    "connected": "connected",
    "connectivity": "connected",
    "disconnected": "disconnected",
    "disconnection": "disconnected",
    "component": "component",
    "components": "component",
    "subgraph": "subgraph",
    "subgraphs": "subgraph",
    "graph theory": "graph_theory",
    "topology": "topology",
    "topological": "topology",
    "topological space": "topology",
    "homeomorphism": "homeomorphism",
    "homeomorphic": "homeomorphism",
    "isomorphism": "isomorphism",
    "isomorphic": "isomorphism",
    "automorphism": "automorphism",
    "automorphic": "automorphism",
    "embedding": "embedding",
    "embedding space": "embedding",
    "embedding dimension": "embedding",
    "dimension": "dimension",
    "dimensions": "dimension",
    "dim": "dimension",
    "coordinate": "coordinate",
    "coordinates": "coordinate",
    "coordinate system": "coordinate_system",
    "cartesian coordinate": "cartesian_coordinate",
    "cartesian coordinates": "cartesian_coordinate",
    "polar coordinate": "polar_coordinate",
    "polar coordinates": "polar_coordinate",
    "spherical coordinate": "spherical_coordinate",
    "spherical coordinates": "spherical_coordinate",
    "cylindrical coordinate": "cylindrical_coordinate",
    "cylindrical coordinates": "cylindrical_coordinate",
    "origin": "origin",
    "axes": "axis",
    "axis": "axis",
    "x-axis": "x_axis",
    "y-axis": "y_axis",
    "z-axis": "z_axis",
    "x": "x_axis",
    "y": "y_axis",
    "z": "z_axis",
    "coordinate plane": "cartesian_plane",
    "coordinate space": "cartesian_space",
    "cartesian space": "cartesian_space",
    "polar plane": "polar_plane",
    "polar space": "polar_space",
    "spherical space": "spherical_space",
    "cylindrical space": "cylindrical_space",
    "projection": "projection",
    "projections": "projection",
    "perspective": "perspective",
    "perspectives": "perspective",
    "view": "perspective",
    "views": "perspective",
    "angle of view": "perspective",
    "field of view": "perspective",
    "vanishing point": "vanishing_point",
    "vanishing points": "vanishing_point",
    "horizon": "horizon",
    "horizons": "horizon",
    "depth": "depth",
    "deep": "depth",
    "shallow": "depth",
    "distance": "distance",
    "distances": "distance",
    "length": "length",
    "width": "width",
    "height": "height",
    "thickness": "thickness",
    "thin": "thickness",
    "thick": "thickness",
    "flat": "plane",
    "curved": "curve",
    "curve": "curve",
    "curves": "curve",
    "straight": "line",
    "straight line": "line",
    "linear": "line",
    "nonlinear": "curve",
    "non-linear": "curve",
    "arc": "arc",
    "circle": "circle",
    "ellipse": "ellipse",
    "parabola": "parabola",
    "hyperbola": "hyperbola",
    "spiral": "spiral",
    "spirals": "spiral",
    "helix": "helix",
    "helices": "helix",
    "conic": "conic",
    "conics": "conic",
    "conic section": "conic_section",
    "conic sections": "conic_section",
    "quadratic curve": "conic_section",
    "quadratic curves": "conic_section",
    "circle equation": "circle_equation",
    "ellipse equation": "ellipse_equation",
    "parabola equation": "parabola_equation",
    "hyperbola equation": "hyperbola_equation",
    "focus": "focus",
    "foci": "focus",
    "directrix": "directrix",
    "directrices": "directrix",
    "eccentricity": "eccentricity",
    "eccentricities": "eccentricity",
    "axis": "axis",
    "axes": "axis",
    "major axis": "major_axis",
    "minor axis": "minor_axis",
    "center": "center",
    "centre": "center",
    "radius": "radius",
    "diameter": "diameter",
    "chord": "chord",
    "tangent": "tangent",
    "secant": "secant",
    "segment": "segment",
    "sector": "sector",
    "arc": "arc",
    "angle": "angle",
    "vertex": "vertex",
    "point": "point",
    "line": "line",
    "plane": "plane",
    "space": "space",
    "solid": "solid",
    "surface": "surface",
    "face": "face",
    "edge": "side",
    "side": "side",
    "base": "base",
    "apex": "apex",
    "height": "height",
    "length": "length",
    "width": "width",
    "depth": "depth",
    "thickness": "thickness",
    "area": "area",
    "perimeter": "perimeter",
    "volume": "volume",
    "surface area": "area",
    "lateral area": "lateral_area",
    "base area": "base_area",
    "total area": "total_area",
    "diagonal": "diagonal",
    "cross section": "cross_section",
    "net": "net",
    "projection": "projection",
    "plan": "plan",
    "diagram": "diagram",
    "figure": "figure",
    "notation": "notation",
    "label": "label",
    "property": "property",
    "relation": "relation",
    "proportion": "proportion",
    "ratio": "ratio",
    "fraction": "fraction",
    "part": "part",
    "whole": "whole",
    "partition": "partition",
    "union": "union",
    "intersection": "intersection",
    "adjacent": "adjacent",
    "continuous": "continuous",
    "discrete": "discrete",
    "boundary": "boundary",
    "interior": "interior",
    "exterior": "exterior",
    "open": "open",
    "closed": "closed",
    "interval": "interval",
    "domain": "domain",
    "codomain": "codomain",
    "mapping": "mapping",
    "function": "function",
    "inverse": "inverse",
    "reflection": "reflection",
    "rotation": "rotation",
    "translation": "translation",
    "dilation": "dilation",
    "transformation": "transformation",
    "symmetry": "symmetry",
    "pattern": "pattern",
    "tiling": "tiling",
    "grid": "grid",
    "lattice": "lattice",
    "graph": "graph",
    "tree": "tree",
    "leaf": "leaf",
    "root": "root",
    "branch": "branch",
    "degree_vertex": "degree_vertex",
    "adjacent_vertex": "adjacent_vertex",
    "adjacent_edge": "adjacent_edge",
    "incident": "incident",
    "planar": "planar",
    "embedding": "embedding",
    "face_graph": "face_graph",
    "complete_graph": "complete_graph",
    "cycle_graph": "cycle_graph",
    "path_graph": "path_graph",
    "tree_graph": "tree_graph",
    "connected": "connected",
    "disconnected": "disconnected",
    "component": "component",
    "subgraph": "subgraph",
    "graph_theory": "graph_theory",
    "topology": "topology",
    "homeomorphism": "homeomorphism",
    "isomorphism": "isomorphism",
    "automorphism": "automorphism",
    "coordinate_system": "coordinate_system",
    "cartesian_coordinate": "cartesian_coordinate",
    "polar_coordinate": "polar_coordinate",
    "spherical_coordinate": "spherical_coordinate",
    "cylindrical_coordinate": "cylindrical_coordinate",
    "origin": "origin",
    "x_axis": "x_axis",
    "y_axis": "y_axis",
    "z_axis": "z_axis",
    "cartesian_plane": "cartesian_plane",
    "cartesian_space": "cartesian_space",
    "polar_plane": "polar_plane",
    "polar_space": "polar_space",
    "spherical_space": "spherical_space",
    "cylindrical_space": "cylindrical_space",
    "perspective": "perspective",
    "vanishing_point": "vanishing_point",
    "horizon": "horizon",
    "depth": "depth",
    "curve": "curve",
    "spiral": "spiral",
    "helix": "helix",
    "conic": "conic",
    "conic_section": "conic_section",
    "circle_equation": "circle_equation",
    "ellipse_equation": "ellipse_equation",
    "parabola_equation": "parabola_equation",
    "hyperbola_equation": "hyperbola_equation",
    "eccentricity": "eccentricity",
    "major_axis": "major_axis",
    "minor_axis": "minor_axis",
    "diagonal_length": "diagonal_length",
    "diagonal_area": "diagonal_area",
    "diagonal_sum": "diagonal_sum",
    "diagonal_difference": "diagonal_difference",
    "diagonal_product": "diagonal_product",
    "diagonal_ratio": "diagonal_ratio",
    "diagonal_measure": "diagonal_measure",
    "diagonal_notation": "diagonal_notation",
    "distance_formula": "distance_formula",
    "midpoint_formula": "midpoint_formula",
    "slope": "slope",
    "gradient": "slope",
    "intercept": "intercept",
    "y_intercept": "y_intercept",
    "x_intercept": "x_intercept",
    "linear_equation": "linear_equation",
    "quadratic_equation": "quadratic_equation",
    "system_of_equations": "system_of_equations",
    "euler_formula": "euler_formula",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}:{SEMANTIC_MAP_AUTHOR}:{SEMANTIC_MAP_ENGINE}:{_EXPECTED_ENTRY_COUNT}"
    full = meta + joined
    return hashlib.sha256(full.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == norm and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)