import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AERO02 Python Semantic Engine"
SEMANTIC_MAP_ENGINE = "AERO02_aerodynamics"

SEMANTIC_MAP = {
    # Bernoulli Theory
    "bernoulli": "bernoulli_theory_of_lift",
    "bernoulli's principle": "bernoulli_theory_of_lift",
    "bernoulli principle": "bernoulli_theory_of_lift",
    "bernoulli equation": "bernoulli_theory_of_lift",
    "pressure differential": "bernoulli_theory_of_lift",
    "pressure difference": "bernoulli_theory_of_lift",
    "velocity increase": "bernoulli_theory_of_lift",
    "dynamic pressure": "bernoulli_theory_of_lift",
    "static pressure": "bernoulli_theory_of_lift",
    "lift from pressure": "bernoulli_theory_of_lift",
    "misconception of lift": "bernoulli_theory_of_lift",
    "equal transit time": "bernoulli_theory_of_lift",
    "airfoil pressure": "bernoulli_theory_of_lift",

    # Circulation Theory
    "circulation": "circulation_theory_of_lift",
    "circulation theory": "circulation_theory_of_lift",
    "kutta-joukowski": "circulation_theory_of_lift",
    "kutta joukowski": "circulation_theory_of_lift",
    "kutta-joukowski theorem": "circulation_theory_of_lift",
    "kutta condition": "circulation_theory_of_lift",
    "joukowski": "circulation_theory_of_lift",
    "vorticity": "circulation_theory_of_lift",
    "bound vortex": "circulation_theory_of_lift",
    "starting vortex": "circulation_theory_of_lift",
    "lift from circulation": "circulation_theory_of_lift",
    "wingtip vortices": "circulation_theory_of_lift",
    "circulatory lift": "circulation_theory_of_lift",
    "potential flow": "circulation_theory_of_lift",

    # Drag Decomposition
    "drag": "drag_decomposition",
    "drag force": "drag_decomposition",
    "total drag": "drag_decomposition",
    "parasitic drag": "parasitic_drag",
    "profile drag": "parasitic_drag",
    "form drag": "parasitic_drag",
    "skin friction": "parasitic_drag",
    "skin friction drag": "parasitic_drag",
    "surface drag": "parasitic_drag",
    "induced drag": "induced_drag",
    "lift-induced drag": "induced_drag",
    "vortex drag": "induced_drag",
    "wave drag": "wave_drag",
    "compressibility drag": "wave_drag",
    "transonic drag": "wave_drag",
    "shock drag": "wave_drag",
    "drag bucket": "wave_drag",
    "drag polar": "drag_decomposition",
    "drag curve": "drag_decomposition",
    "drag coefficient": "drag_decomposition",
    "cd": "drag_decomposition",
    "c_d": "drag_decomposition",
    "drag reduction": "drag_decomposition",

    # NACA Airfoil Designation and Characteristics
    "naca": "naca_airfoil_designation",
    "naca airfoil": "naca_airfoil_designation",
    "naca series": "naca_airfoil_designation",
    "naca 4-digit": "naca_airfoil_designation",
    "naca 5-digit": "naca_airfoil_designation",
    "naca 6-series": "naca_airfoil_designation",
    "naca designation": "naca_airfoil_designation",
    "airfoil designation": "naca_airfoil_designation",
    "airfoil shape": "naca_airfoil_designation",
    "airfoil thickness": "naca_airfoil_characteristics",
    "airfoil camber": "naca_airfoil_characteristics",
    "airfoil chord": "naca_airfoil_characteristics",
    "airfoil leading edge": "naca_airfoil_characteristics",
    "airfoil trailing edge": "naca_airfoil_characteristics",
    "airfoil max thickness": "naca_airfoil_characteristics",
    "airfoil max camber": "naca_airfoil_characteristics",
    "airfoil performance": "naca_airfoil_characteristics",
    "airfoil lift curve": "naca_airfoil_characteristics",
    "airfoil stall": "naca_airfoil_characteristics",
    "airfoil reynolds number": "naca_airfoil_characteristics",

    # Boundary Layer Transition and Turbulence
    "boundary layer": "boundary_layer_transition",
    "boundary layer transition": "boundary_layer_transition",
    "laminar flow": "boundary_layer_transition",
    "laminar boundary layer": "boundary_layer_transition",
    "turbulent flow": "boundary_layer_turbulence",
    "turbulent boundary layer": "boundary_layer_turbulence",
    "transition point": "boundary_layer_transition",
    "reynolds number": "boundary_layer_transition",
    "critical reynolds number": "boundary_layer_transition",
    "flow separation": "boundary_layer_transition",
    "separation point": "boundary_layer_transition",
    "skin friction coefficient": "boundary_layer_transition",
    "bl": "boundary_layer_transition",
    "boundary layer thickness": "boundary_layer_transition",
    "boundary layer control": "boundary_layer_transition",
    "boundary layer suction": "boundary_layer_transition",
    "boundary layer trip": "boundary_layer_transition",
    "boundary layer turbulence": "boundary_layer_turbulence",
    "turbulence intensity": "boundary_layer_turbulence",
    "turbulence": "boundary_layer_turbulence",

    # Stall Characteristics: Leading Edge vs Trailing Edge
    "stall": "stall_characteristics",
    "stall angle": "stall_characteristics",
    "stall speed": "stall_characteristics",
    "stall warning": "stall_characteristics",
    "stall margin": "stall_characteristics",
    "stall recovery": "stall_characteristics",
    "leading edge stall": "leading_edge_stall",
    "trailing edge stall": "trailing_edge_stall",
    "deep stall": "stall_characteristics",
    "tip stall": "stall_characteristics",
    "root stall": "stall_characteristics",
    "stall strip": "stall_characteristics",
    "stall indicator": "stall_characteristics",
    "stall buffet": "stall_characteristics",
    "stall vortex": "stall_characteristics",
    "stall pattern": "stall_characteristics",
    "stall progression": "stall_characteristics",

    # High-Lift Devices: Slats, Flaps, Krueger Flaps
    "high-lift device": "high_lift_devices",
    "high lift device": "high_lift_devices",
    "slat": "slats",
    "slats": "slats",
    "leading edge slat": "slats",
    "flap": "flaps",
    "flaps": "flaps",
    "trailing edge flap": "flaps",
    "plain flap": "flaps",
    "split flap": "flaps",
    "fowler flap": "flaps",
    "double slotted flap": "flaps",
    "triple slotted flap": "flaps",
    "krueger flap": "krueger_flaps",
    "krueger flaps": "krueger_flaps",
    "leading edge device": "slats",
    "trailing edge device": "flaps",
    "flap deployment": "flaps",
    "flap effectiveness": "flaps",
    "flap deflection": "flaps",

    # Wing Planform Design: Aspect Ratio, Sweep, Taper
    "wing planform": "wing_planform_design",
    "planform": "wing_planform_design",
    "aspect ratio": "aspect_ratio",
    "wing aspect ratio": "aspect_ratio",
    "ar": "aspect_ratio",
    "wing sweep": "wing_sweep",
    "sweep angle": "wing_sweep",
    "swept wing": "wing_sweep",
    "taper ratio": "wing_taper",
    "wing taper": "wing_taper",
    "tapered wing": "wing_taper",
    "elliptical wing": "wing_planform_design",
    "rectangular wing": "wing_planform_design",
    "delta wing": "wing_planform_design",
    "wing area": "wing_planform_design",
    "wing span": "wing_planform_design",
    "span": "wing_planform_design",
    "root chord": "wing_planform_design",
    "tip chord": "wing_planform_design",
    "mean aerodynamic chord": "wing_planform_design",
    "mac": "wing_planform_design",
    "planform efficiency": "wing_planform_design",

    # Compressibility Effects and Critical Mach Number
    "compressibility": "compressibility_effects",
    "compressibility effects": "compressibility_effects",
    "critical mach number": "critical_mach_number",
    "mach number": "critical_mach_number",
    "mach": "critical_mach_number",
    "transonic": "compressibility_effects",
    "transonic regime": "compressibility_effects",
    "transonic flow": "compressibility_effects",
    "shock wave": "compressibility_effects",
    "shock": "compressibility_effects",
    "shock formation": "compressibility_effects",
    "shock stall": "compressibility_effects",
    "drag rise": "compressibility_effects",
    "wave drag": "wave_drag",
    "supersonic": "supersonic_aerodynamics",
    "supersonic flow": "supersonic_aerodynamics",
    "supersonic regime": "supersonic_aerodynamics",
    "expansion fan": "supersonic_aerodynamics",
    "expansion waves": "supersonic_aerodynamics",
    "oblique shock": "supersonic_aerodynamics",
    "normal shock": "supersonic_aerodynamics",
    "bow shock": "supersonic_aerodynamics",
    "shock expansion": "supersonic_aerodynamics",
    "wave drag": "wave_drag",

    # Supersonic Aerodynamics: Shocks, Expansion Fans, Wave Drag
    "supersonic aerodynamics": "supersonic_aerodynamics",
    "supersonic lift": "supersonic_aerodynamics",
    "supersonic drag": "supersonic_aerodynamics",
    "supersonic wing": "supersonic_aerodynamics",
    "supersonic airfoil": "supersonic_aerodynamics",
    "supersonic shock": "supersonic_aerodynamics",
    "supersonic expansion": "supersonic_aerodynamics",
    "supersonic critical mach": "supersonic_aerodynamics",
    "shock wave drag": "wave_drag",
    "shock expansion fan": "supersonic_aerodynamics",
    "shock expansion": "supersonic_aerodynamics",
    "wave drag": "wave_drag",
    "drag divergence mach number": "critical_mach_number",
    "drag divergence": "critical_mach_number",

    # Longitudinal Stability: Static Margin and Neutral Point
    "longitudinal stability": "longitudinal_stability",
    "static margin": "static_margin",
    "neutral point": "neutral_point",
    "center of gravity": "longitudinal_stability",
    "cg": "longitudinal_stability",
    "aft cg": "longitudinal_stability",
    "forward cg": "longitudinal_stability",
    "tail volume": "longitudinal_stability",
    "stability margin": "static_margin",
    "pitch stability": "longitudinal_stability",
    "pitching moment": "longitudinal_stability",
    "moment coefficient": "longitudinal_stability",
    "cm": "longitudinal_stability",
    "c_m": "longitudinal_stability",
    "static stability": "longitudinal_stability",
    "dynamic stability": "longitudinal_stability",
    "trim": "longitudinal_stability",
    "trim point": "longitudinal_stability",

    # Aircraft Performance: Breguet Range Equation
    "aircraft performance": "aircraft_performance",
    "performance": "aircraft_performance",
    "range": "aircraft_performance",
    "breguet range": "breguet_range_equation",
    "breguet range equation": "breguet_range_equation",
    "range equation": "breguet_range_equation",
    "fuel efficiency": "breguet_range_equation",
    "specific fuel consumption": "breguet_range_equation",
    "sfc": "breguet_range_equation",
    "lift-to-drag ratio": "breguet_range_equation",
    "l/d": "breguet_range_equation",
    "ld": "breguet_range_equation",
    "endurance": "aircraft_performance",
    "payload": "aircraft_performance",
    "gross weight": "aircraft_performance",
    "takeoff weight": "aircraft_performance",
    "empty weight": "aircraft_performance",
    "maximum range": "aircraft_performance",
    "maximum endurance": "aircraft_performance",
    "cruise": "aircraft_performance",
    "cruise speed": "aircraft_performance",
    "cruise altitude": "aircraft_performance",

    # V-Speeds: Vs, Vmc, Vr, V1, Vx, Vy, Vne
    "v-speeds": "v_speeds",
    "v speeds": "v_speeds",
    "vs": "stall_speed",
    "v_s": "stall_speed",
    "stall speed": "stall_speed",
    "vmc": "minimum_control_speed",
    "v_mc": "minimum_control_speed",
    "minimum control speed": "minimum_control_speed",
    "vr": "rotation_speed",
    "v_r": "rotation_speed",
    "rotation speed": "rotation_speed",
    "v1": "decision_speed",
    "v_1": "decision_speed",
    "decision speed": "decision_speed",
    "vx": "best_angle_climb_speed",
    "v_x": "best_angle_climb_speed",
    "best angle of climb": "best_angle_climb_speed",
    "best angle climb speed": "best_angle_climb_speed",
    "vy": "best_rate_climb_speed",
    "v_y": "best_rate_climb_speed",
    "best rate of climb": "best_rate_climb_speed",
    "best rate climb speed": "best_rate_climb_speed",
    "vne": "never_exceed_speed",
    "v_ne": "never_exceed_speed",
    "never exceed speed": "never_exceed_speed",
    "vno": "maximum_operating_speed",
    "v_no": "maximum_operating_speed",
    "maximum operating speed": "maximum_operating_speed",
    "va": "maneuvering_speed",
    "v_a": "maneuvering_speed",
    "maneuvering speed": "maneuvering_speed",
    "vfe": "maximum_flap_extended_speed",
    "v_fe": "maximum_flap_extended_speed",
    "maximum flap extended speed": "maximum_flap_extended_speed",

    # Propeller Aerodynamics: Blade Element Theory
    "propeller": "propeller_aerodynamics",
    "propeller aerodynamics": "propeller_aerodynamics",
    "blade element theory": "blade_element_theory",
    "blade element": "blade_element_theory",
    "propeller blade": "blade_element_theory",
    "blade pitch": "blade_element_theory",
    "blade angle": "blade_element_theory",
    "propeller pitch": "blade_element_theory",
    "propeller efficiency": "propeller_aerodynamics",
    "propeller slip": "propeller_aerodynamics",
    "propeller thrust": "propeller_aerodynamics",
    "propeller torque": "propeller_aerodynamics",
    "propeller rpm": "propeller_aerodynamics",
    "propeller advance ratio": "propeller_aerodynamics",
    "propeller performance": "propeller_aerodynamics",
    "propeller drag": "propeller_aerodynamics",

    # Rotary Wing Aerodynamics: Momentum Theory and Blade Flapping
    "rotary wing": "rotary_wing_aerodynamics",
    "rotary wing aerodynamics": "rotary_wing_aerodynamics",
    "helicopter aerodynamics": "rotary_wing_aerodynamics",
    "momentum theory": "rotary_wing_momentum_theory",
    "rotor momentum theory": "rotary_wing_momentum_theory",
    "blade flapping": "rotary_wing_blade_flapping",
    "flapping": "rotary_wing_blade_flapping",
    "rotor flapping": "rotary_wing_blade_flapping",
    "rotor blade flapping": "rotary_wing_blade_flapping",
    "rotor blade": "rotary_wing_blade_flapping",
    "rotor rpm": "rotary_wing_aerodynamics",
    "rotor thrust": "rotary_wing_aerodynamics",
    "rotor drag": "rotary_wing_aerodynamics",
    "rotor torque": "rotary_wing_aerodynamics",
    "rotor performance": "rotary_wing_aerodynamics",
    "rotor efficiency": "rotary_wing_aerodynamics",
    "rotor disk": "rotary_wing_aerodynamics",
    "disk loading": "rotary_wing_aerodynamics",
    "blade loading": "rotary_wing_aerodynamics",
    "autorotation": "rotary_wing_aerodynamics",

    # Wind Tunnel Testing: Scaling, Reynolds Number Effects
    "wind tunnel": "wind_tunnel_testing",
    "wind tunnel testing": "wind_tunnel_testing",
    "tunnel testing": "wind_tunnel_testing",
    "scaling": "wind_tunnel_scaling",
    "model scaling": "wind_tunnel_scaling",
    "scale effect": "wind_tunnel_scaling",
    "reynolds number effect": "wind_tunnel_reynolds_number_effects",
    "reynolds effect": "wind_tunnel_reynolds_number_effects",
    "reynolds scaling": "wind_tunnel_reynolds_number_effects",
    "dynamic similarity": "wind_tunnel_scaling",
    "geometric similarity": "wind_tunnel_scaling",
    "flow visualization": "wind_tunnel_testing",
    "smoke visualization": "wind_tunnel_testing",
    "pressure measurement": "wind_tunnel_testing",
    "force measurement": "wind_tunnel_testing",
    "lift measurement": "wind_tunnel_testing",
    "drag measurement": "wind_tunnel_testing",

    # Ground Effect: Reduced Induced Drag, Increased Lift
    "ground effect": "ground_effect",
    "ground proximity": "ground_effect",
    "reduced induced drag": "ground_effect",
    "increased lift": "ground_effect",
    "wing in ground effect": "ground_effect",
    "wig": "ground_effect",
    "ground effect lift": "ground_effect",
    "ground effect drag": "ground_effect",
    "ground effect vortex": "ground_effect",
    "ground effect stall": "ground_effect",

    # Atmospheric Effects: Density Altitude, Wind Shear, Icing
    "atmospheric effects": "atmospheric_effects",
    "atmosphere": "atmospheric_effects",
    "density altitude": "density_altitude",
    "pressure altitude": "density_altitude",
    "altitude": "density_altitude",
    "temperature": "atmospheric_effects",
    "humidity": "atmospheric_effects",
    "wind shear": "wind_shear",
    "shear": "wind_shear",
    "microburst": "wind_shear",
    "icing": "icing",
    "airframe icing": "icing",
    "engine icing": "icing",
    "carburetor icing": "icing",
    "ice accretion": "icing",
    "ice formation": "icing",
    "anti-icing": "icing",
    "de-icing": "icing",
    "icing hazard": "icing",
    "icing effects": "icing",
    "icing drag": "icing",
    "icing lift": "icing",
    "icing stall": "icing",

    # Additional Synonyms, Misspellings, Related Terms
    "airfoil": "naca_airfoil_designation",
    "aerofoil": "naca_airfoil_designation",
    "wing": "wing_planform_design",
    "plane": "aircraft_performance",
    "aircraft": "aircraft_performance",
    "flight": "aircraft_performance",
    "takeoff": "aircraft_performance",
    "landing": "aircraft_performance",
    "climb": "aircraft_performance",
    "descent": "aircraft_performance",
    "cruise": "aircraft_performance",
    "speed": "aircraft_performance",
    "altitude": "density_altitude",
    "weight": "aircraft_performance",
    "payload": "aircraft_performance",
    "fuel": "aircraft_performance",
    "engine": "aircraft_performance",
    "thrust": "aircraft_performance",
    "lift": "bernoulli_theory_of_lift",
    "drag": "drag_decomposition",
    "moment": "longitudinal_stability",
    "pitch": "longitudinal_stability",
    "yaw": "longitudinal_stability",
    "roll": "longitudinal_stability",
    "control": "minimum_control_speed",
    "stability": "longitudinal_stability",
    "efficiency": "aircraft_performance",
    "performance": "aircraft_performance",
    "reynolds": "boundary_layer_transition",
    "mach": "critical_mach_number",
    "shock": "compressibility_effects",
    "expansion": "supersonic_aerodynamics",
    "fan": "supersonic_aerodynamics",
    "vortex": "circulation_theory_of_lift",
    "turbulence": "boundary_layer_turbulence",
    "laminar": "boundary_layer_transition",
    "separation": "boundary_layer_transition",
    "stall": "stall_characteristics",
    "flap": "flaps",
    "slat": "slats",
    "krueger": "krueger_flaps",
    "wingtip": "circulation_theory_of_lift",
    "root": "wing_planform_design",
    "tip": "wing_planform_design",
    "chord": "wing_planform_design",
    "span": "wing_planform_design",
    "area": "wing_planform_design",
    "planform": "wing_planform_design",
    "sweep": "wing_sweep",
    "taper": "wing_taper",
    "delta": "wing_planform_design",
    "elliptical": "wing_planform_design",
    "rectangular": "wing_planform_design",
    "mean aerodynamic chord": "wing_planform_design",
    "mac": "wing_planform_design",
    "static": "static_margin",
    "neutral": "neutral_point",
    "cg": "longitudinal_stability",
    "tail": "longitudinal_stability",
    "trim": "longitudinal_stability",
    "breguet": "breguet_range_equation",
    "range": "aircraft_performance",
    "endurance": "aircraft_performance",
    "payload": "aircraft_performance",
    "gross weight": "aircraft_performance",
    "takeoff weight": "aircraft_performance",
    "empty weight": "aircraft_performance",
    "maximum range": "aircraft_performance",
    "maximum endurance": "aircraft_performance",
    "cruise": "aircraft_performance",
    "cruise speed": "aircraft_performance",
    "cruise altitude": "aircraft_performance",
    "v-speeds": "v_speeds",
    "vs": "stall_speed",
    "vmc": "minimum_control_speed",
    "vr": "rotation_speed",
    "v1": "decision_speed",
    "vx": "best_angle_climb_speed",
    "vy": "best_rate_climb_speed",
    "vne": "never_exceed_speed",
    "vno": "maximum_operating_speed",
    "va": "maneuvering_speed",
    "vfe": "maximum_flap_extended_speed",
    "propeller": "propeller_aerodynamics",
    "blade": "blade_element_theory",
    "rotor": "rotary_wing_aerodynamics",
    "wind tunnel": "wind_tunnel_testing",
    "ground effect": "ground_effect",
    "density altitude": "density_altitude",
    "pressure altitude": "density_altitude",
    "wind shear": "wind_shear",
    "icing": "icing",
    "ice": "icing",
    "anti-icing": "icing",
    "de-icing": "icing",
    "airfoil": "naca_airfoil_designation",
    "aerofoil": "naca_airfoil_designation",
    "wing": "wing_planform_design",
    "plane": "aircraft_performance",
    "aircraft": "aircraft_performance",
    "flight": "aircraft_performance",
    "takeoff": "aircraft_performance",
    "landing": "aircraft_performance",
    "climb": "aircraft_performance",
    "descent": "aircraft_performance",
    "cruise": "aircraft_performance",
    "speed": "aircraft_performance",
    "altitude": "density_altitude",
    "weight": "aircraft_performance",
    "payload": "aircraft_performance",
    "fuel": "aircraft_performance",
    "engine": "aircraft_performance",
    "thrust": "aircraft_performance",
    "lift": "bernoulli_theory_of_lift",
    "drag": "drag_decomposition",
    "moment": "longitudinal_stability",
    "pitch": "longitudinal_stability",
    "yaw": "longitudinal_stability",
    "roll": "longitudinal_stability",
    "control": "minimum_control_speed",
    "stability": "longitudinal_stability",
    "efficiency": "aircraft_performance",
    "performance": "aircraft_performance",
    "reynolds": "boundary_layer_transition",
    "mach": "critical_mach_number",
    "shock": "compressibility_effects",
    "expansion": "supersonic_aerodynamics",
    "fan": "supersonic_aerodynamics",
    "vortex": "circulation_theory_of_lift",
    "turbulence": "boundary_layer_turbulence",
    "laminar": "boundary_layer_transition",
    "separation": "boundary_layer_transition",
    "stall": "stall_characteristics",
    "flap": "flaps",
    "slat": "slats",
    "krueger": "krueger_flaps",
    "wingtip": "circulation_theory_of_lift",
    "root": "wing_planform_design",
    "tip": "wing_planform_design",
    "chord": "wing_planform_design",
    "span": "wing_planform_design",
    "area": "wing_planform_design",
    "planform": "wing_planform_design",
    "sweep": "wing_sweep",
    "taper": "wing_taper",
    "delta": "wing_planform_design",
    "elliptical": "wing_planform_design",
    "rectangular": "wing_planform_design",
    "mean aerodynamic chord": "wing_planform_design",
    "mac": "wing_planform_design",
    "static": "static_margin",
    "neutral": "neutral_point",
    "cg": "longitudinal_stability",
    "tail": "longitudinal_stability",
    "trim": "longitudinal_stability",
    "breguet": "breguet_range_equation",
    "range": "aircraft_performance",
    "endurance": "aircraft_performance",
    "payload": "aircraft_performance",
    "gross weight": "aircraft_performance",
    "takeoff weight": "aircraft_performance",
    "empty weight": "aircraft_performance",
    "maximum range": "aircraft_performance",
    "maximum endurance": "aircraft_performance",
    "cruise": "aircraft_performance",
    "cruise speed": "aircraft_performance",
    "cruise altitude": "aircraft_performance",
    "v-speeds": "v_speeds",
    "vs": "stall_speed",
    "vmc": "minimum_control_speed",
    "vr": "rotation_speed",
    "v1": "decision_speed",
    "vx": "best_angle_climb_speed",
    "vy": "best_rate_climb_speed",
    "vne": "never_exceed_speed",
    "vno": "maximum_operating_speed",
    "va": "maneuvering_speed",
    "vfe": "maximum_flap_extended_speed",
    "propeller": "propeller_aerodynamics",
    "blade": "blade_element_theory",
    "rotor": "rotary_wing_aerodynamics",
    "wind tunnel": "wind_tunnel_testing",
    "ground effect": "ground_effect",
    "density altitude": "density_altitude",
    "pressure altitude": "density_altitude",
    "wind shear": "wind_shear",
    "icing": "icing",
    "ice": "icing",
    "anti-icing": "icing",
    "de-icing": "icing"
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "OK" if is_valid else "ERROR",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"[^a-z0-9 _\-]", "", t)
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)