import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ET03 Team"
SEMANTIC_MAP_ENGINE = "ET03_speech_assembler"

SEMANTIC_MAP = {
    # Conversational State Machine Fundamentals
    "state machine": "conversational_state_machine",
    "state-machine": "conversational_state_machine",
    "conversation state": "conversational_state_machine",
    "dialogue state": "conversational_state_machine",
    "dialog state": "conversational_state_machine",
    "state tracking": "conversational_state_machine",
    "statemachine": "conversational_state_machine",
    "state mgmt": "conversational_state_machine",
    "state management": "conversational_state_machine",
    "state mgr": "conversational_state_machine",
    "state": "conversational_state_machine",
    "fsm": "conversational_state_machine",
    "finite state machine": "conversational_state_machine",
    "conversation flow": "conversational_state_machine",
    "dialogue flow": "conversational_state_machine",
    "dialog flow": "conversational_state_machine",
    "flow control": "conversational_state_machine",
    "flow mgmt": "conversational_state_machine",
    "flow management": "conversational_state_machine",
    "turn-taking": "turn_taking_management",
    "turn taking": "turn_taking_management",
    "turn mgmt": "turn_taking_management",
    "turn management": "turn_taking_management",
    "turn": "turn_taking_management",
    "speaker change": "turn_taking_management",
    "speaker switch": "turn_taking_management",
    "speaker handoff": "turn_taking_management",
    "turn allocation": "turn_taking_management",
    "turn transfer": "turn_taking_management",
    "turn exchange": "turn_taking_management",
    "turns": "turn_taking_management",
    "context window": "context_window_management",
    "context mgmt": "context_window_management",
    "context management": "context_window_management",
    "sliding window": "context_window_management",
    "windowed context": "context_window_management",
    "contextual window": "context_window_management",
    "memory window": "context_window_management",
    "context buffer": "context_window_management",
    "conversation window": "context_window_management",
    "dialogue window": "context_window_management",
    "40-message window": "context_window_management",
    "sliding 40-message": "context_window_management",
    "sliding 40 message": "context_window_management",
    "40msg window": "context_window_management",
    "context limit": "context_window_management",
    "context cap": "context_window_management",
    "contextual limit": "context_window_management",
    "response chunking": "response_chunking_tts",
    "chunking": "response_chunking_tts",
    "tts chunking": "response_chunking_tts",
    "chunked response": "response_chunking_tts",
    "response segmentation": "response_chunking_tts",
    "segmentation": "response_chunking_tts",
    "tts segmentation": "response_chunking_tts",
    "speech chunking": "response_chunking_tts",
    "speech segmentation": "response_chunking_tts",
    "chunk": "response_chunking_tts",
    "ssml": "ssml_markup_generation",
    "ssml markup": "ssml_markup_generation",
    "ssml generation": "ssml_markup_generation",
    "ssml gen": "ssml_markup_generation",
    "ssml markup generation": "ssml_markup_generation",
    "speech markup": "ssml_markup_generation",
    "markup generation": "ssml_markup_generation",
    "markup gen": "ssml_markup_generation",
    "ssml tags": "ssml_markup_generation",
    "ssml tag": "ssml_markup_generation",
    "pause insertion": "pause_insertion_rules",
    "pause rules": "pause_insertion_rules",
    "pause mgmt": "pause_insertion_rules",
    "pause management": "pause_insertion_rules",
    "pause handling": "pause_insertion_rules",
    "insert pause": "pause_insertion_rules",
    "inserting pause": "pause_insertion_rules",
    "pause": "pause_insertion_rules",
    "break insertion": "pause_insertion_rules",
    "break rule": "pause_insertion_rules",
    "breaks": "pause_insertion_rules",
    "emphasis marking": "emphasis_marking_speech_output",
    "emphasis": "emphasis_marking_speech_output",
    "emphasis tag": "emphasis_marking_speech_output",
    "emphasize": "emphasis_marking_speech_output",
    "emphasising": "emphasis_marking_speech_output",
    "emphasizing": "emphasis_marking_speech_output",
    "emph": "emphasis_marking_speech_output",
    "highlighting": "emphasis_marking_speech_output",
    "highlight": "emphasis_marking_speech_output",
    "stress marking": "emphasis_marking_speech_output",
    "prosody hints": "prosody_hints_voice_output",
    "prosody": "prosody_hints_voice_output",
    "prosody hint": "prosody_hints_voice_output",
    "prosodic hints": "prosody_hints_voice_output",
    "prosodic": "prosody_hints_voice_output",
    "prosody tag": "prosody_hints_voice_output",
    "prosody tags": "prosody_hints_voice_output",
    "voice hints": "prosody_hints_voice_output",
    "voice hint": "prosody_hints_voice_output",
    "intonation hints": "prosody_hints_voice_output",
    "intonation": "prosody_hints_voice_output",
    "voice output": "prosody_hints_voice_output",
    "voiceout": "prosody_hints_voice_output",
    "response length optimization": "response_length_optimization_voice",
    "response length": "response_length_optimization_voice",
    "length optimization": "response_length_optimization_voice",
    "length opt": "response_length_optimization_voice",
    "response optimization": "response_length_optimization_voice",
    "voice length": "response_length_optimization_voice",
    "voice response length": "response_length_optimization_voice",
    "optimize response": "response_length_optimization_voice",
    "response size": "response_length_optimization_voice",
    "response size opt": "response_length_optimization_voice",
    "multi-part response": "multi_part_response_assembly",
    "multipart response": "multi_part_response_assembly",
    "multi part response": "multi_part_response_assembly",
    "multi-part": "multi_part_response_assembly",
    "multipart": "multi_part_response_assembly",
    "response assembly": "multi_part_response_assembly",
    "response assembler": "multi_part_response_assembly",
    "response assembling": "multi_part_response_assembly",
    "response composition": "multi_part_response_assembly",
    "compose response": "multi_part_response_assembly",
    "follow-up question": "followup_question_generation",
    "followup question": "followup_question_generation",
    "follow up question": "followup_question_generation",
    "follow-up": "followup_question_generation",
    "followup": "followup_question_generation",
    "follow up": "followup_question_generation",
    "follow-up generation": "followup_question_generation",
    "followup generation": "followup_question_generation",
    "follow up generation": "followup_question_generation",
    "question generation": "followup_question_generation",
    "clarification request": "clarification_request_handling",
    "clarification": "clarification_request_handling",
    "clarify": "clarification_request_handling",
    "clarification handling": "clarification_request_handling",
    "clarification mgmt": "clarification_request_handling",
    "clarification management": "clarification_request_handling",
    "clarification req": "clarification_request_handling",
    "clarification request handling": "clarification_request_handling",
    "clarify request": "clarification_request_handling",
    "clarification question": "clarification_request_handling",
    "conversation summary": "conversation_summary_generation",
    "summary generation": "conversation_summary_generation",
    "conversation summarization": "conversation_summary_generation",
    "summarization": "conversation_summary_generation",
    "summarize conversation": "conversation_summary_generation",
    "summarize": "conversation_summary_generation",
    "summarise": "conversation_summary_generation",
    "summary": "conversation_summary_generation",
    "dialogue summary": "conversation_summary_generation",
    "topic tracking": "topic_tracking_dialogue",
    "topic mgmt": "topic_tracking_dialogue",
    "topic management": "topic_tracking_dialogue",
    "track topic": "topic_tracking_dialogue",
    "tracking topic": "topic_tracking_dialogue",
    "topic": "topic_tracking_dialogue",
    "topic detection": "topic_tracking_dialogue",
    "topic identification": "topic_tracking_dialogue",
    "anaphora resolution": "anaphora_resolution_dialogue",
    "anaphora": "anaphora_resolution_dialogue",
    "anaphora resolving": "anaphora_resolution_dialogue",
    "anaphora handling": "anaphora_resolution_dialogue",
    "anaphora mgmt": "anaphora_resolution_dialogue",
    "anaphora management": "anaphora_resolution_dialogue",
    "anaphor resolution": "anaphora_resolution_dialogue",
    "pronoun resolution": "anaphora_resolution_dialogue",
    "reference resolution": "anaphora_resolution_dialogue",
    "conversation flow template": "conversation_flow_templates",
    "conversation template": "conversation_flow_templates",
    "flow template": "conversation_flow_templates",
    "flow templates": "conversation_flow_templates",
    "conversation templates": "conversation_flow_templates",
    "dialogue template": "conversation_flow_templates",
    "dialog template": "conversation_flow_templates",
    "template": "conversation_flow_templates",
    "conversation flow templates": "conversation_flow_templates",
    "interruption handling": "interruption_handling_dialogue",
    "interruption": "interruption_handling_dialogue",
    "interrupt": "interruption_handling_dialogue",
    "interrupt handling": "interruption_handling_dialogue",
    "interrupt mgmt": "interruption_handling_dialogue",
    "interrupt management": "interruption_handling_dialogue",
    "interruption mgmt": "interruption_handling_dialogue",
    "interruption management": "interruption_handling_dialogue",
    "barge-in": "barge_in_support_voice_output",
    "barge in": "barge_in_support_voice_output",
    "bargein": "barge_in_support_voice_output",
    "barge-in support": "barge_in_support_voice_output",
    "barge in support": "barge_in_support_voice_output",
    "bargein support": "barge_in_support_voice_output",
    "voice barge-in": "barge_in_support_voice_output",
    "voice barge in": "barge_in_support_voice_output",
    "voice bargein": "barge_in_support_voice_output",
    "interruptible output": "barge_in_support_voice_output",
    "barge": "barge_in_support_voice_output",
    "conversation timeout": "conversation_timeout_handling",
    "timeout": "conversation_timeout_handling",
    "timeout handling": "conversation_timeout_handling",
    "timeout mgmt": "conversation_timeout_handling",
    "timeout management": "conversation_timeout_handling",
    "conversation timeout handling": "conversation_timeout_handling",
    "timeout handler": "conversation_timeout_handling",
    "timeout event": "conversation_timeout_handling",
    "graceful ending": "graceful_conversation_ending",
    "graceful conversation ending": "graceful_conversation_ending",
    "conversation ending": "graceful_conversation_ending",
    "ending": "graceful_conversation_ending",
    "end conversation": "graceful_conversation_ending",
    "conversation end": "graceful_conversation_ending",
    "end gracefully": "graceful_conversation_ending",
    "graceful end": "graceful_conversation_ending",
    "exit conversation": "graceful_conversation_ending",
    "exit gracefully": "graceful_conversation_ending",
    "exit": "graceful_conversation_ending",
    # Common misspellings, abbreviations, and related terms
    "statemachin": "conversational_state_machine",
    "statemachien": "conversational_state_machine",
    "turntakin": "turn_taking_management",
    "turntaking": "turn_taking_management",
    "contextwin": "context_window_management",
    "contextwindow": "context_window_management",
    "chunkin": "response_chunking_tts",
    "chunkin'": "response_chunking_tts",
    "ssmlgen": "ssml_markup_generation",
    "ssmlmark": "ssml_markup_generation",
    "pauze": "pause_insertion_rules",
    "emphsis": "emphasis_marking_speech_output",
    "prosodi": "prosody_hints_voice_output",
    "responce length": "response_length_optimization_voice",
    "multi-part responce": "multi_part_response_assembly",
    "followup q": "followup_question_generation",
    "clarify req": "clarification_request_handling",
    "summery": "conversation_summary_generation",
    "topictrack": "topic_tracking_dialogue",
    "anaphor": "anaphora_resolution_dialogue",
    "flowtemplate": "conversation_flow_templates",
    "interupt": "interruption_handling_dialogue",
    "bargein sup": "barge_in_support_voice_output",
    "time out": "conversation_timeout_handling",
    "gracefull ending": "graceful_conversation_ending",
    # Additional synonyms and related terms
    "dialogue": "conversational_state_machine",
    "conversation": "conversational_state_machine",
    "speech assembler": "multi_part_response_assembly",
    "assembler": "multi_part_response_assembly",
    "tts": "response_chunking_tts",
    "speech output": "multi_part_response_assembly",
    "voice": "prosody_hints_voice_output",
    "voice synthesis": "prosody_hints_voice_output",
    "speech synthesis": "prosody_hints_voice_output",
    "voice assistant": "conversational_state_machine",
    "assistant": "conversational_state_machine",
    "user turn": "turn_taking_management",
    "system turn": "turn_taking_management",
    "utterance": "turn_taking_management",
    "utterances": "turn_taking_management",
    "history window": "context_window_management",
    "history buffer": "context_window_management",
    "buffer": "context_window_management",
    "message window": "context_window_management",
    "message buffer": "context_window_management",
    "window": "context_window_management",
    "chunked": "response_chunking_tts",
    "segmented": "response_chunking_tts",
    "markup": "ssml_markup_generation",
    "tag": "ssml_markup_generation",
    "tags": "ssml_markup_generation",
    "break": "pause_insertion_rules",
    "pause inserted": "pause_insertion_rules",
    "stressed": "emphasis_marking_speech_output",
    "highlighted": "emphasis_marking_speech_output",
    "intoned": "prosody_hints_voice_output",
    "optimized": "response_length_optimization_voice",
    "composed": "multi_part_response_assembly",
    "assembled": "multi_part_response_assembly",
    "follow-up q": "followup_question_generation",
    "clarification needed": "clarification_request_handling",
    "summarized": "conversation_summary_generation",
    "tracked": "topic_tracking_dialogue",
    "resolved": "anaphora_resolution_dialogue",
    "templated": "conversation_flow_templates",
    "interrupted": "interruption_handling_dialogue",
    "barge-in event": "barge_in_support_voice_output",
    "timed out": "conversation_timeout_handling",
    "ended": "graceful_conversation_ending",
    # Lowercase variants and misspellings
    "statemachin": "conversational_state_machine",
    "turntakng": "turn_taking_management",
    "contxt window": "context_window_management",
    "responce chunking": "response_chunking_tts",
    "ssml markp": "ssml_markup_generation",
    "paus insertion": "pause_insertion_rules",
    "emphsis marking": "emphasis_marking_speech_output",
    "prosody hint": "prosody_hints_voice_output",
    "responce length opt": "response_length_optimization_voice",
    "multi part responce": "multi_part_response_assembly",
    "follow up q": "followup_question_generation",
    "clarification reqst": "clarification_request_handling",
    "summarisation": "conversation_summary_generation",
    "topic trakcing": "topic_tracking_dialogue",
    "anaphora resoluton": "anaphora_resolution_dialogue",
    "flow templat": "conversation_flow_templates",
    "interuption": "interruption_handling_dialogue",
    "barge in sup": "barge_in_support_voice_output",
    "timeout event": "conversation_timeout_handling",
    "graceful endng": "graceful_conversation_ending",
    # Plurals and more variants
    "states": "conversational_state_machine",
    "turns": "turn_taking_management",
    "contexts": "context_window_management",
    "chunks": "response_chunking_tts",
    "markups": "ssml_markup_generation",
    "pauses": "pause_insertion_rules",
    "emphases": "emphasis_marking_speech_output",
    "prosodies": "prosody_hints_voice_output",
    "responses": "response_length_optimization_voice",
    "assemblies": "multi_part_response_assembly",
    "questions": "followup_question_generation",
    "clarifications": "clarification_request_handling",
    "summaries": "conversation_summary_generation",
    "topics": "topic_tracking_dialogue",
    "anaphoras": "anaphora_resolution_dialogue",
    "templates": "conversation_flow_templates",
    "interruptions": "interruption_handling_dialogue",
    "barges": "barge_in_support_voice_output",
    "timeouts": "conversation_timeout_handling",
    "endings": "graceful_conversation_ending",
    # More abbreviations and acronyms
    "ctx window": "context_window_management",
    "ctx mgmt": "context_window_management",
    "ctx": "context_window_management",
    "msg window": "context_window_management",
    "msg buffer": "context_window_management",
    "msg": "context_window_management",
    "resp chunk": "response_chunking_tts",
    "resp": "response_length_optimization_voice",
    "clar req": "clarification_request_handling",
    "summ gen": "conversation_summary_generation",
    "topic track": "topic_tracking_dialogue",
    "ana res": "anaphora_resolution_dialogue",
    "flow temp": "conversation_flow_templates",
    "int handl": "interruption_handling_dialogue",
    "b-in": "barge_in_support_voice_output",
    "to handling": "conversation_timeout_handling",
    "grace end": "graceful_conversation_ending",
    # Related terms
    "dialogue management": "conversational_state_machine",
    "dialogue manager": "conversational_state_machine",
    "conversation manager": "conversational_state_machine",
    "dialogue control": "conversational_state_machine",
    "conversation control": "conversational_state_machine",
    "turn control": "turn_taking_management",
    "turn handler": "turn_taking_management",
    "window handler": "context_window_management",
    "chunk handler": "response_chunking_tts",
    "markup handler": "ssml_markup_generation",
    "pause handler": "pause_insertion_rules",
    "emphasis handler": "emphasis_marking_speech_output",
    "prosody handler": "prosody_hints_voice_output",
    "length handler": "response_length_optimization_voice",
    "assembly handler": "multi_part_response_assembly",
    "question handler": "followup_question_generation",
    "clarification handler": "clarification_request_handling",
    "summary handler": "conversation_summary_generation",
    "topic handler": "topic_tracking_dialogue",
    "anaphora handler": "anaphora_resolution_dialogue",
    "template handler": "conversation_flow_templates",
    "interruption handler": "interruption_handling_dialogue",
    "barge handler": "barge_in_support_voice_output",
    "timeout handler": "conversation_timeout_handling",
    "ending handler": "graceful_conversation_ending",
    # Even more variants
    "statemachine handler": "conversational_state_machine",
    "turntaking handler": "turn_taking_management",
    "contextwindow handler": "context_window_management",
    "chunking handler": "response_chunking_tts",
    "ssml handler": "ssml_markup_generation",
    "pauseinsertion handler": "pause_insertion_rules",
    "emphasismarking handler": "emphasis_marking_speech_output",
    "prosodyhints handler": "prosody_hints_voice_output",
    "responselength handler": "response_length_optimization_voice",
    "multipartresponse handler": "multi_part_response_assembly",
    "followupquestion handler": "followup_question_generation",
    "clarificationrequest handler": "clarification_request_handling",
    "conversationsummary handler": "conversation_summary_generation",
    "topictracking handler": "topic_tracking_dialogue",
    "anaphoraresolution handler": "anaphora_resolution_dialogue",
    "conversationflowtemplate handler": "conversation_flow_templates",
    "interruptionhandling handler": "interruption_handling_dialogue",
    "bargein handler": "barge_in_support_voice_output",
    "conversationtimeout handler": "conversation_timeout_handling",
    "gracefulending handler": "graceful_conversation_ending",
    # Misspellings and typos
    "statemachien": "conversational_state_machine",
    "turntkaing": "turn_taking_management",
    "contxtwindow": "context_window_management",
    "responcechunking": "response_chunking_tts",
    "ssmlmarkp": "ssml_markup_generation",
    "pausinsertion": "pause_insertion_rules",
    "emphsis marking": "emphasis_marking_speech_output",
    "prosodyhint": "prosody_hints_voice_output",
    "responcelength opt": "response_length_optimization_voice",
    "multipart responce": "multi_part_response_assembly",
    "followupq": "followup_question_generation",
    "clarificationreq": "clarification_request_handling",
    "summariz": "conversation_summary_generation",
    "topictrackng": "topic_tracking_dialogue",
    "anaphoraresoluton": "anaphora_resolution_dialogue",
    "flowtemplat": "conversation_flow_templates",
    "interuptionhandling": "interruption_handling_dialogue",
    "bargeinsup": "barge_in_support_voice_output",
    "timeout event": "conversation_timeout_handling",
    "gracefulendng": "graceful_conversation_ending",
    # Lowercase and whitespace-insensitive
    " state machine ": "conversational_state_machine",
    " turn taking ": "turn_taking_management",
    " context window ": "context_window_management",
    " response chunking ": "response_chunking_tts",
    " ssml markup ": "ssml_markup_generation",
    " pause insertion ": "pause_insertion_rules",
    " emphasis marking ": "emphasis_marking_speech_output",
    " prosody hints ": "prosody_hints_voice_output",
    " response length optimization ": "response_length_optimization_voice",
    " multi-part response ": "multi_part_response_assembly",
    " follow-up question ": "followup_question_generation",
    " clarification request ": "clarification_request_handling",
    " conversation summary ": "conversation_summary_generation",
    " topic tracking ": "topic_tracking_dialogue",
    " anaphora resolution ": "anaphora_resolution_dialogue",
    " conversation flow template ": "conversation_flow_templates",
    " interruption handling ": "interruption_handling_dialogue",
    " barge-in support ": "barge_in_support_voice_output",
    " conversation timeout ": "conversation_timeout_handling",
    " graceful ending ": "graceful_conversation_ending",
}

_EXPECTED_ENTRY_COUNT = 213

def _normalize_key(key):
    return re.sub(r"\s+", " ", key.strip().lower())

def _compute_map_hash():
    items = sorted((k.strip().lower(), v) for k, v in SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "mismatch",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def normalize_term(term: str) -> str:
    key = _normalize_key(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)