import hashlib

SEMANTIC_MAP_ENGINE = "CHEM01_organic_chemistry"
SEMANTIC_MAP_AUTHOR = "ExpertPythonEngineer"
SEMANTIC_MAP_VERSION = "1.0.0"

SEMANTIC_MAP = {
    # SN2 Nucleophilic Substitution
    "sn2": "sn2_nucleophilic_substitution",
    "sn-2": "sn2_nucleophilic_substitution",
    "s n 2": "sn2_nucleophilic_substitution",
    "bimolecular nucleophilic substitution": "sn2_nucleophilic_substitution",
    "backside attack": "sn2_nucleophilic_substitution",
    "concerted substitution": "sn2_nucleophilic_substitution",
    "primary alkyl halide substitution": "sn2_nucleophilic_substitution",
    "sn2 reaction": "sn2_nucleophilic_substitution",
    "sn2 mech": "sn2_nucleophilic_substitution",
    "sn2 mech.": "sn2_nucleophilic_substitution",
    "sn2 mechanism": "sn2_nucleophilic_substitution",
    "sn2 substitution": "sn2_nucleophilic_substitution",
    "sn2 nucleophilic substitution": "sn2_nucleophilic_substitution",
    "sn2 substitution reaction": "sn2_nucleophilic_substitution",
    "sn2 substitution mech": "sn2_nucleophilic_substitution",
    "sn2 substitution mechanism": "sn2_nucleophilic_substitution",
    "sn2 substitution mech.": "sn2_nucleophilic_substitution",
    "sn2 path": "sn2_nucleophilic_substitution",
    "sn2 path.": "sn2_nucleophilic_substitution",
    "sn2 pathway": "sn2_nucleophilic_substitution",
    "sn2 pathway.": "sn2_nucleophilic_substitution",
    "sn2 kinetics": "sn2_nucleophilic_substitution",
    "sn2 rate": "sn2_nucleophilic_substitution",
    "sn2 rate law": "sn2_nucleophilic_substitution",
    "sn2 rate equation": "sn2_nucleophilic_substitution",
    "sn2 rate mechanism": "sn2_nucleophilic_substitution",
    "sn2 rate mech": "sn2_nucleophilic_substitution",
    "sn2 rate mech.": "sn2_nucleophilic_substitution",
    "sn2 rate kinetics": "sn2_nucleophilic_substitution",
    "sn2 rate kinetics mech": "sn2_nucleophilic_substitution",
    "sn2 rate kinetics mechanism": "sn2_nucleophilic_substitution",
    "sn2 rate kinetics mech.": "sn2_nucleophilic_substitution",
    "sn2 stereochemistry": "sn2_nucleophilic_substitution",
    "sn2 stereochemical outcome": "sn2_nucleophilic_substitution",
    "sn2 stereochemical inversion": "sn2_nucleophilic_substitution",
    "sn2 inversion": "sn2_nucleophilic_substitution",
    "sn2 walden inversion": "sn2_nucleophilic_substitution",
    "walden inversion": "sn2_nucleophilic_substitution",
    "inversion of configuration": "sn2_nucleophilic_substitution",
    "inversion stereochemistry": "sn2_nucleophilic_substitution",
    "inversion stereochemical": "sn2_nucleophilic_substitution",
    "sn2 nucleophile": "sn2_nucleophilic_substitution",
    "sn2 nucleophilic attack": "sn2_nucleophilic_substitution",
    "sn2 nucleophile strength": "sn2_nucleophilic_substitution",
    "sn2 nucleophile basicity": "sn2_nucleophilic_substitution",
    "sn2 nucleophile nucleophilicity": "sn2_nucleophilic_substitution",
    "sn2 leaving group": "sn2_nucleophilic_substitution",
    "sn2 leaving group ability": "sn2_nucleophilic_substitution",
    "sn2 leaving group strength": "sn2_nucleophilic_substitution",
    "sn2 solvent": "sn2_nucleophilic_substitution",
    "sn2 solvent effects": "sn2_nucleophilic_substitution",
    "sn2 polar aprotic solvent": "sn2_nucleophilic_substitution",
    "sn2 polar protic solvent": "sn2_nucleophilic_substitution",
    "sn2 substrate": "sn2_nucleophilic_substitution",
    "sn2 substrate structure": "sn2_nucleophilic_substitution",
    "sn2 primary substrate": "sn2_nucleophilic_substitution",
    "sn2 secondary substrate": "sn2_nucleophilic_substitution",
    "sn2 tertiary substrate": "sn2_nucleophilic_substitution",
    "sn2 alkyl halide": "sn2_nucleophilic_substitution",
    "sn2 alkyl halide substitution": "sn2_nucleophilic_substitution",
    "sn2 alkyl halide reaction": "sn2_nucleophilic_substitution",

    # SN1 Nucleophilic Substitution
    "sn1": "sn1_nucleophilic_substitution",
    "sn-1": "sn1_nucleophilic_substitution",
    "s n 1": "sn1_nucleophilic_substitution",
    "unimolecular nucleophilic substitution": "sn1_nucleophilic_substitution",
    "carbocation intermediate": "sn1_nucleophilic_substitution",
    "sn1 reaction": "sn1_nucleophilic_substitution",
    "sn1 mech": "sn1_nucleophilic_substitution",
    "sn1 mech.": "sn1_nucleophilic_substitution",
    "sn1 mechanism": "sn1_nucleophilic_substitution",
    "sn1 substitution": "sn1_nucleophilic_substitution",
    "sn1 substitution reaction": "sn1_nucleophilic_substitution",
    "sn1 substitution mech": "sn1_nucleophilic_substitution",
    "sn1 substitution mechanism": "sn1_nucleophilic_substitution",
    "sn1 substitution mech.": "sn1_nucleophilic_substitution",
    "sn1 path": "sn1_nucleophilic_substitution",
    "sn1 path.": "sn1_nucleophilic_substitution",
    "sn1 pathway": "sn1_nucleophilic_substitution",
    "sn1 pathway.": "sn1_nucleophilic_substitution",
    "sn1 kinetics": "sn1_nucleophilic_substitution",
    "sn1 rate": "sn1_nucleophilic_substitution",
    "sn1 rate law": "sn1_nucleophilic_substitution",
    "sn1 rate equation": "sn1_nucleophilic_substitution",
    "sn1 rate mechanism": "sn1_nucleophilic_substitution",
    "sn1 rate mech": "sn1_nucleophilic_substitution",
    "sn1 rate mech.": "sn1_nucleophilic_substitution",
    "sn1 rate kinetics": "sn1_nucleophilic_substitution",
    "sn1 rate kinetics mech": "sn1_nucleophilic_substitution",
    "sn1 rate kinetics mechanism": "sn1_nucleophilic_substitution",
    "sn1 rate kinetics mech.": "sn1_nucleophilic_substitution",
    "sn1 stereochemistry": "sn1_nucleophilic_substitution",
    "sn1 stereochemical outcome": "sn1_nucleophilic_substitution",
    "sn1 racemization": "sn1_nucleophilic_substitution",
    "sn1 racemic mixture": "sn1_nucleophilic_substitution",
    "sn1 nucleophile": "sn1_nucleophilic_substitution",
    "sn1 nucleophilic attack": "sn1_nucleophilic_substitution",
    "sn1 nucleophile strength": "sn1_nucleophilic_substitution",
    "sn1 nucleophile basicity": "sn1_nucleophilic_substitution",
    "sn1 nucleophile nucleophilicity": "sn1_nucleophilic_substitution",
    "sn1 leaving group": "sn1_nucleophilic_substitution",
    "sn1 leaving group ability": "sn1_nucleophilic_substitution",
    "sn1 leaving group strength": "sn1_nucleophilic_substitution",
    "sn1 solvent": "sn1_nucleophilic_substitution",
    "sn1 solvent effects": "sn1_nucleophilic_substitution",
    "sn1 polar protic solvent": "sn1_nucleophilic_substitution",
    "sn1 substrate": "sn1_nucleophilic_substitution",
    "sn1 substrate structure": "sn1_nucleophilic_substitution",
    "sn1 primary substrate": "sn1_nucleophilic_substitution",
    "sn1 secondary substrate": "sn1_nucleophilic_substitution",
    "sn1 tertiary substrate": "sn1_nucleophilic_substitution",
    "sn1 alkyl halide": "sn1_nucleophilic_substitution",
    "sn1 alkyl halide substitution": "sn1_nucleophilic_substitution",
    "sn1 alkyl halide reaction": "sn1_nucleophilic_substitution",

    # E2 Elimination
    "e2": "e2_elimination",
    "e-2": "e2_elimination",
    "bimolecular elimination": "e2_elimination",
    "e2 reaction": "e2_elimination",
    "e2 mech": "e2_elimination",
    "e2 mech.": "e2_elimination",
    "e2 mechanism": "e2_elimination",
    "e2 elimination": "e2_elimination",
    "e2 elimination reaction": "e2_elimination",
    "e2 elimination mech": "e2_elimination",
    "e2 elimination mechanism": "e2_elimination",
    "e2 elimination mech.": "e2_elimination",
    "e2 path": "e2_elimination",
    "e2 path.": "e2_elimination",
    "e2 pathway": "e2_elimination",
    "e2 pathway.": "e2_elimination",
    "e2 kinetics": "e2_elimination",
    "e2 rate": "e2_elimination",
    "e2 rate law": "e2_elimination",
    "e2 rate equation": "e2_elimination",
    "e2 rate mechanism": "e2_elimination",
    "e2 rate mech": "e2_elimination",
    "e2 rate mech.": "e2_elimination",
    "e2 rate kinetics": "e2_elimination",
    "e2 rate kinetics mech": "e2_elimination",
    "e2 rate kinetics mechanism": "e2_elimination",
    "e2 rate kinetics mech.": "e2_elimination",
    "e2 stereochemistry": "e2_elimination",
    "e2 stereochemical outcome": "e2_elimination",
    "e2 anti periplanar": "e2_elimination",
    "anti periplanar": "e2_elimination",
    "e2 base": "e2_elimination",
    "e2 base strength": "e2_elimination",
    "e2 base basicity": "e2_elimination",
    "e2 base nucleophilicity": "e2_elimination",
    "e2 leaving group": "e2_elimination",
    "e2 leaving group ability": "e2_elimination",
    "e2 leaving group strength": "e2_elimination",
    "e2 solvent": "e2_elimination",
    "e2 solvent effects": "e2_elimination",
    "e2 polar aprotic solvent": "e2_elimination",
    "e2 polar protic solvent": "e2_elimination",
    "e2 substrate": "e2_elimination",
    "e2 substrate structure": "e2_elimination",
    "e2 primary substrate": "e2_elimination",
    "e2 secondary substrate": "e2_elimination",
    "e2 tertiary substrate": "e2_elimination",
    "e2 alkyl halide": "e2_elimination",
    "e2 alkyl halide elimination": "e2_elimination",
    "e2 alkyl halide reaction": "e2_elimination",

    # Grignard Reagent Chemistry
    "grignard": "grignard_reagent_chemistry",
    "grignard reagent": "grignard_reagent_chemistry",
    "grignard reagents": "grignard_reagent_chemistry",
    "rmg": "grignard_reagent_chemistry",
    "r-mg": "grignard_reagent_chemistry",
    "grignard formation": "grignard_reagent_chemistry",
    "grignard synthesis": "grignard_reagent_chemistry",
    "grignard reaction": "grignard_reagent_chemistry",
    "grignard addition": "grignard_reagent_chemistry",
    "grignard nucleophile": "grignard_reagent_chemistry",
    "grignard nucleophilic addition": "grignard_reagent_chemistry",
    "grignard carbonyl addition": "grignard_reagent_chemistry",
    "grignard carbonyl reaction": "grignard_reagent_chemistry",
    "grignard organomagnesium": "grignard_reagent_chemistry",
    "grignard organomagnesium reagent": "grignard_reagent_chemistry",
    "grignard organomagnesium reagents": "grignard_reagent_chemistry",
    "grignard alkyl magnesium halide": "grignard_reagent_chemistry",
    "grignard alkylmagnesium halide": "grignard_reagent_chemistry",
    "grignard alkylmagnesium halides": "grignard_reagent_chemistry",
    "grignard reagent preparation": "grignard_reagent_chemistry",
    "grignard reagent handling": "grignard_reagent_chemistry",
    "grignard reagent safety": "grignard_reagent_chemistry",
    "grignard reagent reactivity": "grignard_reagent_chemistry",
    "grignard reagent mechanism": "grignard_reagent_chemistry",
    "grignard reagent mech": "grignard_reagent_chemistry",
    "grignard reagent mech.": "grignard_reagent_chemistry",
    "grignard reagent solvent": "grignard_reagent_chemistry",
    "grignard reagent solvent effects": "grignard_reagent_chemistry",
    "grignard reagent quenching": "grignard_reagent_chemistry",
    "grignard reagent workup": "grignard_reagent_chemistry",
    "grignard reagent hydrolysis": "grignard_reagent_chemistry",

    # Wittig Reaction
    "wittig": "wittig_reaction",
    "wittig reaction": "wittig_reaction",
    "wittig olefination": "wittig_reaction",
    "wittig reagent": "wittig_reaction",
    "wittig reagent formation": "wittig_reaction",
    "wittig reagent synthesis": "wittig_reaction",
    "wittig reagent preparation": "wittig_reaction",
    "wittig reagent mechanism": "wittig_reaction",
    "wittig reagent mech": "wittig_reaction",
    "wittig reagent mech.": "wittig_reaction",
    "wittig reaction mechanism": "wittig_reaction",
    "wittig reaction mech": "wittig_reaction",
    "wittig reaction mech.": "wittig_reaction",
    "wittig reaction stereochemistry": "wittig_reaction",
    "wittig reaction stereochemical outcome": "wittig_reaction",
    "wittig reaction stereoselectivity": "wittig_reaction",
    "wittig reaction stereospecificity": "wittig_reaction",
    "wittig reaction e/z selectivity": "wittig_reaction",
    "wittig reaction e/z stereochemistry": "wittig_reaction",
    "ylide": "wittig_reaction",
    "phosphonium ylide": "wittig_reaction",
    "phosphonium ylide formation": "wittig_reaction",
    "phosphonium ylide synthesis": "wittig_reaction",
    "phosphonium ylide preparation": "wittig_reaction",
    "ylide formation": "wittig_reaction",
    "ylide synthesis": "wittig_reaction",
    "ylide preparation": "wittig_reaction",
    "ylide mechanism": "wittig_reaction",
    "ylide mech": "wittig_reaction",
    "ylide mech.": "wittig_reaction",
    "ylide reactivity": "wittig_reaction",
    "ylide stability": "wittig_reaction",
    "ylide resonance": "wittig_reaction",
    "ylide resonance structures": "wittig_reaction",
    "ylide resonance stabilization": "wittig_reaction",
    "ylide resonance stabilization structures": "wittig_reaction",

    # Diels-Alder Reaction
    "diels-alder": "diels_alder_reaction",
    "diels alder": "diels_alder_reaction",
    "diels-alder reaction": "diels_alder_reaction",
    "diels alder reaction": "diels_alder_reaction",
    "diels-alder cycloaddition": "diels_alder_reaction",
    "diels alder cycloaddition": "diels_alder_reaction",
    "diels-alder mechanism": "diels_alder_reaction",
    "diels alder mechanism": "diels_alder_reaction",
    "diels-alder mech": "diels_alder_reaction",
    "diels alder mech": "diels_alder_reaction",
    "diels-alder mech.": "diels_alder_reaction",
    "diels alder mech.": "diels_alder_reaction",
    "diels-alder stereochemistry": "diels_alder_reaction",
    "diels alder stereochemistry": "diels_alder_reaction",
    "diels-alder stereochemical outcome": "diels_alder_reaction",
    "diels alder stereochemical outcome": "diels_alder_reaction",
    "diels-alder regioselectivity": "diels_alder_reaction",
    "diels alder regioselectivity": "diels_alder_reaction",
    "diels-alder diene": "diels_alder_reaction",
    "diels alder diene": "diels_alder_reaction",
    "diels-alder dienophile": "diels_alder_reaction",
    "diels alder dienophile": "diels_alder_reaction",
    "diene": "diels_alder_reaction",
    "dienophile": "diels_alder_reaction",
    "diels-alder concerted": "diels_alder_reaction",
    "diels alder concerted": "diels_alder_reaction",
    "pericyclic reaction": "diels_alder_reaction",
    "pericyclic reactions": "diels_alder_reaction",
    "diels-alder pericyclic": "diels_alder_reaction",
    "diels alder pericyclic": "diels_alder_reaction",

    # Aldol Condensation
    "aldol": "aldol_condensation",
    "aldol condensation": "aldol_condensation",
    "aldol reaction": "aldol_condensation",
    "aldol addition": "aldol_condensation",
    "aldol condensation reaction": "aldol_condensation",
    "aldol condensation mech": "aldol_condensation",
    "aldol condensation mech.": "aldol_condensation",
    "aldol condensation mechanism": "aldol_condensation",
    "aldol condensation stereochemistry": "aldol_condensation",
    "aldol condensation stereochemical outcome": "aldol_condensation",
    "aldol condensation stereoselectivity": "aldol_condensation",
    "aldol condensation stereospecificity": "aldol_condensation",
    "aldol condensation kinetics": "aldol_condensation",
    "aldol condensation rate": "aldol_condensation",
    "aldol condensation rate law": "aldol_condensation",
    "aldol condensation rate equation": "aldol_condensation",
    "aldol condensation rate mechanism": "aldol_condensation",
    "aldol condensation rate mech": "aldol_condensation",
    "aldol condensation rate mech.": "aldol_condensation",
    "aldol condensation base catalyzed": "aldol_condensation",
    "aldol condensation acid catalyzed": "aldol_condensation",
    "aldol condensation enolate": "aldol_condensation",
    "aldol condensation enolate ion": "aldol_condensation",
    "aldol condensation enolate formation": "aldol_condensation",
    "aldol condensation enolate intermediate": "aldol_condensation",
    "aldol condensation enolate chemistry": "aldol_condensation",
    "aldol condensation enolate mechanism": "aldol_condensation",
    "aldol condensation enolate mech": "aldol_condensation",
    "aldol condensation enolate mech.": "aldol_condensation",
    "aldol condensation enolate stability": "aldol_condensation",
    "aldol condensation dehydration": "aldol_condensation",
    "aldol condensation dehydration step": "aldol_condensation",
    "aldol condensation dehydration mechanism": "aldol_condensation",
    "aldol condensation dehydration mech": "aldol_condensation",
    "aldol condensation dehydration mech.": "aldol_condensation",
    "aldol condensation product": "aldol_condensation",
    "aldol condensation product formation": "aldol_condensation",
    "aldol condensation product stereochemistry": "aldol_condensation",

    # Protecting Groups Strategy
    "protecting group": "protecting_groups_strategy",
    "protecting groups": "protecting_groups_strategy",
    "protecting group strategy": "protecting_groups_strategy",
    "protecting group chemistry": "protecting_groups_strategy",
    "protecting group protection": "protecting_groups_strategy",
    "protecting group deprotection": "protecting_groups_strategy",
    "protecting group removal": "protecting_groups_strategy",
    "protecting group selection": "protecting_groups_strategy",
    "protecting group types": "protecting_groups_strategy",
    "protecting group examples": "protecting_groups_strategy",
    "protecting group alcohol": "protecting_groups_strategy",
    "protecting group amine": "protecting_groups_strategy",
    "protecting group carbonyl": "protecting_groups_strategy",
    "protecting group thiol": "protecting_groups_strategy",
    "protecting group silyl ether": "protecting_groups_strategy",
    "protecting group tbdms": "protecting_groups_strategy",
    "protecting group tbdms ether": "protecting_groups_strategy",
    "protecting group tms": "protecting_groups_strategy",
    "protecting group tms ether": "protecting_groups_strategy",
    "protecting group boc": "protecting_groups_strategy",
    "protecting group cbz": "protecting_groups_strategy",
    "protecting group fmoc": "protecting_groups_strategy",
    "protecting group trityl": "protecting_groups_strategy",
    "protecting group strategy planning": "protecting_groups_strategy",
    "protecting group strategy design": "protecting_groups_strategy",
    "protecting group strategy synthesis": "protecting_groups_strategy",
    "protecting group strategy retrosynthesis": "protecting_groups_strategy",

    # Oxidation Reactions Alcohols
    "oxidation alcohol": "oxidation_reactions_alcohols",
    "alcohol oxidation": "oxidation_reactions_alcohols",
    "oxidation of alcohols": "oxidation_reactions_alcohols",
    "oxidation reactions alcohols": "oxidation_reactions_alcohols",
    "oxidation reaction alcohol": "oxidation_reactions_alcohols",
    "oxidation reaction alcohols": "oxidation_reactions_alcohols",
    "primary alcohol oxidation": "oxidation_reactions_alcohols",
    "secondary alcohol oxidation": "oxidation_reactions_alcohols",
    "tertiary alcohol oxidation": "oxidation_reactions_alcohols",
    "oxidizing agent alcohol": "oxidation_reactions_alcohols",
    "oxidizing agents alcohol": "oxidation_reactions_alcohols",
    "oxidizing agent for alcohol": "oxidation_reactions_alcohols",
    "oxidizing agents for alcohols": "oxidation_reactions_alcohols",
    "oxidizing agent examples alcohol": "oxidation_reactions_alcohols",
    "oxidizing agent examples alcohols": "oxidation_reactions_alcohols",
    "oxidizing agent chromium": "oxidation_reactions_alcohols",
    "oxidizing agent PCC": "oxidation_reactions_alcohols",
    "oxidizing agent pcc": "oxidation_reactions_alcohols",
    "oxidizing agent KMnO4": "oxidation_reactions_alcohols",
    "oxidizing agent kmno4": "oxidation_reactions_alcohols",
    "oxidizing agent chromic acid": "oxidation_reactions_alcohols",
    "oxidizing agent jones reagent": "oxidation_reactions_alcohols",
    "oxidizing agent jones": "oxidation_reactions_alcohols",
    "oxidation mechanism alcohol": "oxidation_reactions_alcohols",
    "oxidation mechanism alcohols": "oxidation_reactions_alcohols",
    "oxidation mech alcohol": "oxidation_reactions_alcohols",
    "oxidation mech alcohols": "oxidation_reactions_alcohols",
    "oxidation mech. alcohol": "oxidation_reactions_alcohols",
    "oxidation mech. alcohols": "oxidation_reactions_alcohols",
    "oxidation product alcohol": "oxidation_reactions_alcohols",
    "oxidation product alcohols": "oxidation_reactions_alcohols",
    "aldehyde formation": "oxidation_reactions_alcohols",
    "ketone formation": "oxidation_reactions_alcohols",
    "carboxylic acid formation": "oxidation_reactions_alcohols",
    "alcohol to aldehyde": "oxidation_reactions_alcohols",
    "alcohol to ketone": "oxidation_reactions_alcohols",
    "alcohol to carboxylic acid": "oxidation_reactions_alcohols",

    # Reduction Reactions Carbonyls
    "reduction carbonyl": "reduction_reactions_carbonyls",
    "carbonyl reduction": "reduction_reactions_carbonyls",
    "reduction of carbonyls": "reduction_reactions_carbonyls",
    "reduction reactions carbonyls": "reduction_reactions_carbonyls",
    "reduction reaction carbonyl": "reduction_reactions_carbonyls",
    "reduction reaction carbonyls": "reduction_reactions_carbonyls",
    "aldehyde reduction": "reduction_reactions_carbonyls",
    "ketone reduction": "reduction_reactions_carbonyls",
    "reductant carbonyl": "reduction_reactions_carbonyls",
    "reductants carbonyl": "reduction_reactions_carbonyls",
    "reducing agent carbonyl": "reduction_reactions_carbonyls",
    "reducing agents carbonyl": "reduction_reactions_carbonyls",
    "reducing agent examples carbonyl": "reduction_reactions_carbonyls",
    "reducing agent examples carbonyls": "reduction_reactions_carbonyls",
    "reducing agent NaBH4": "reduction_reactions_carbonyls",
    "reducing agent nabh4": "reduction_reactions_carbonyls",
    "reducing agent LiAlH4": "reduction_reactions_carbonyls",
    "reducing agent lialh4": "reduction_reactions_carbonyls",
    "reduction mechanism carbonyl": "reduction_reactions_carbonyls",
    "reduction mechanism carbonyls": "reduction_reactions_carbonyls",
    "reduction mech carbonyl": "reduction_reactions_carbonyls",
    "reduction mech carbonyls": "reduction_reactions_carbonyls",
    "reduction mech. carbonyl": "reduction_reactions_carbonyls",
    "reduction mech. carbonyls": "reduction_reactions_carbonyls",
    "reduction product carbonyl": "reduction_reactions_carbonyls",
    "reduction product carbonyls": "reduction_reactions_carbonyls",
    "alcohol formation": "reduction_reactions_carbonyls",
    "carbonyl to alcohol": "reduction_reactions_carbonyls",
    "aldehyde to alcohol": "reduction_reactions_carbonyls",
    "ketone to alcohol": "reduction_reactions_carbonyls",

    # Electrophilic Aromatic Substitution
    "eas": "electrophilic_aromatic_substitution",
    "electrophilic aromatic substitution": "electrophilic_aromatic_substitution",
    "electrophilic aromatic substitution reaction": "electrophilic_aromatic_substitution",
    "electrophilic aromatic substitution mech": "electrophilic_aromatic_substitution",
    "electrophilic aromatic substitution mech.": "electrophilic_aromatic_substitution",
    "electrophilic aromatic substitution mechanism": "electrophilic_aromatic_substitution",
    "eas reaction": "electrophilic_aromatic_substitution",
    "eas mech": "electrophilic_aromatic_substitution",
    "eas mech.": "electrophilic_aromatic_substitution",
    "eas mechanism": "electrophilic_aromatic_substitution",
    "eas substitution": "electrophilic_aromatic_substitution",
    "eas substitution reaction": "electrophilic_aromatic_substitution",
    "eas substitution mech": "electrophilic_aromatic_substitution",
    "eas substitution mechanism": "electrophilic_aromatic_substitution",
    "eas substitution mech.": "electrophilic_aromatic_substitution",
    "eas path": "electrophilic_aromatic_substitution",
    "eas path.": "electrophilic_aromatic_substitution",
    "eas pathway": "electrophilic_aromatic_substitution",
    "eas pathway.": "electrophilic_aromatic_substitution",
    "eas kinetics": "electrophilic_aromatic_substitution",
    "eas rate": "electrophilic_aromatic_substitution",
    "eas rate law": "electrophilic_aromatic_substitution",
    "eas rate equation": "electrophilic_aromatic_substitution",
    "eas rate mechanism": "electrophilic_aromatic_substitution",
    "eas rate mech": "electrophilic_aromatic_substitution",
    "eas rate mech.": "electrophilic_aromatic_substitution",
    "eas rate kinetics": "electrophilic_aromatic_substitution",
    "eas rate kinetics mech": "electrophilic_aromatic_substitution",
    "eas rate kinetics mechanism": "electrophilic_aromatic_substitution",
    "eas rate kinetics mech.": "electrophilic_aromatic_substitution",
    "eas electrophile": "electrophilic_aromatic_substitution",
    "eas electrophilic attack": "electrophilic_aromatic_substitution",
    "eas electrophile examples": "electrophilic_aromatic_substitution",
    "eas catalyst": "electrophilic_aromatic_substitution",
    "eas catalyst examples": "electrophilic_aromatic_substitution",
    "eas aromatic ring": "electrophilic_aromatic_substitution",
    "eas aromatic substitution": "electrophilic_aromatic_substitution",
    "eas directing groups": "electrophilic_aromatic_substitution",
    "eas ortho para director": "electrophilic_aromatic_substitution",
    "eas meta director": "electrophilic_aromatic_substitution",
    "eas substituent effects": "electrophilic_aromatic_substitution",
    "eas resonance effects": "electrophilic_aromatic_substitution",
    "eas inductive effects": "electrophilic_aromatic_substitution",
    "eas rate determining step": "electrophilic_aromatic_substitution",
    "eas rds": "electrophilic_aromatic_substitution",
    "eas intermediate": "electrophilic_aromatic_substitution",
    "arenium ion": "electrophilic_aromatic_substitution",
    "sigma complex": "electrophilic_aromatic_substitution",
    "sigma complex intermediate": "electrophilic_aromatic_substitution",

    # Nucleophilic Aromatic Substitution
    "nas": "nucleophilic_aromatic_substitution",
    "nucleophilic aromatic substitution": "nucleophilic_aromatic_substitution",
    "nucleophilic aromatic substitution reaction": "nucleophilic_aromatic_substitution",
    "nucleophilic aromatic substitution mech": "nucleophilic_aromatic_substitution",
    "nucleophilic aromatic substitution mech.": "nucleophilic_aromatic_substitution",
    "nucleophilic aromatic substitution mechanism": "nucleophilic_aromatic_substitution",
    "nas reaction": "nucleophilic_aromatic_substitution",
    "nas mech": "nucleophilic_aromatic_substitution",
    "nas mech.": "nucleophilic_aromatic_substitution",
    "nas mechanism": "nucleophilic_aromatic_substitution",
    "nas substitution": "nucleophilic_aromatic_substitution",
    "nas substitution reaction": "nucleophilic_aromatic_substitution",
    "nas substitution mech": "nucleophilic_aromatic_substitution",
    "nas substitution mechanism": "nucleophilic_aromatic_substitution",
    "nas substitution mech.": "nucleophilic_aromatic_substitution",
    "nas path": "nucleophilic_aromatic_substitution",
    "nas path.": "nucleophilic_aromatic_substitution",
    "nas pathway": "nucleophilic_aromatic_substitution",
    "nas pathway.": "nucleophilic_aromatic_substitution",
    "nas kinetics": "nucleophilic_aromatic_substitution",
    "nas rate": "nucleophilic_aromatic_substitution",
    "nas rate law": "nucleophilic_aromatic_substitution",
    "nas rate equation": "nucleophilic_aromatic_substitution",
    "nas rate mechanism": "nucleophilic_aromatic_substitution",
    "nas rate mech": "nucleophilic_aromatic_substitution",
    "nas rate mech.": "nucleophilic_aromatic_substitution",
    "nas rate kinetics": "nucleophilic_aromatic_substitution",
    "nas rate kinetics mech": "nucleophilic_aromatic_substitution",
    "nas rate kinetics mechanism": "nucleophilic_aromatic_substitution",
    "nas rate kinetics mech.": "nucleophilic_aromatic_substitution",
    "nas nucleophile": "nucleophilic_aromatic_substitution",
    "nas nucleophilic attack": "nucleophilic_aromatic_substitution",
    "nas nucleophile strength": "nucleophilic_aromatic_substitution",
    "nas nucleophile basicity": "nucleophilic_aromatic_substitution",
    "nas nucleophile nucleophilicity": "nucleophilic_aromatic_substitution",
    "nas leaving group": "nucleophilic_aromatic_substitution",
    "nas leaving group ability": "nucleophilic_aromatic_substitution",
    "nas leaving group strength": "nucleophilic_aromatic_substitution",
    "nas solvent": "nucleophilic_aromatic_substitution",
    "nas solvent effects": "nucleophilic_aromatic_substitution",
    "nas substrate": "nucleophilic_aromatic_substitution",
    "nas substrate structure": "nucleophilic_aromatic_substitution",
    "nas aromatic ring": "nucleophilic_aromatic_substitution",
    "nas aromatic substitution": "nucleophilic_aromatic_substitution",
    "nas intermediate": "nucleophilic_aromatic_substitution",
    "meisenheimer complex": "nucleophilic_aromatic_substitution",
    "meisenheimer intermediate": "nucleophilic_aromatic_substitution",

    # Stereochemistry Chirality
    "stereochemistry": "stereochemistry_chirality",
    "chirality": "stereochemistry_chirality",
    "chiral": "stereochemistry_chirality",
    "chiral center": "stereochemistry_chirality",
    "chiral centers": "stereochemistry_chirality",
    "chirality center": "stereochemistry_chirality",
    "chirality centers": "stereochemistry_chirality",
    "stereocenter": "stereochemistry_chirality",
    "stereocenters": "stereochemistry_chirality",
    "stereogenic center": "stereochemistry_chirality",
    "stereogenic centers": "stereochemistry_chirality",
    "enantiomer": "stereochemistry_chirality",
    "enantiomers": "stereochemistry_chirality",
    "diastereomer": "stereochemistry_chirality",
    "diastereomers": "stereochemistry_chirality",
    "meso compound": "stereochemistry_chirality",
    "meso compounds": "stereochemistry_chirality",
    "optical activity": "stereochemistry_chirality",
    "optical rotation": "stereochemistry_chirality",
    "racemic mixture": "stereochemistry_chirality",
    "racemate": "stereochemistry_chirality",
    "resolution": "stereochemistry_chirality",
    "absolute configuration": "stereochemistry_chirality",
    "r configuration": "stereochemistry_chirality",
    "s configuration": "stereochemistry_chirality",
    "cahn-ingold-prelog": "stereochemistry_chirality",
    "cip rules": "stereochemistry_chirality",
    "cip priority": "stereochemistry_chirality",
    "cip system": "stereochemistry_chirality",
    "stereochemical nomenclature": "stereochemistry_chirality",
    "stereochemical descriptors": "stereochemistry_chirality",
    "stereochemical descriptors r s": "stereochemistry_chirality",
    "stereochemical descriptors e z": "stereochemistry_chirality",
    "e/z isomerism": "stereochemistry_chirality",
    "cis/trans isomerism": "stereochemistry_chirality",
    "geometric isomerism": "stereochemistry_chirality",
    "optical isomerism": "stereochemistry_chirality",
    "chiral molecule": "stereochemistry_chirality",
    "chiral molecules": "stereochemistry_chirality",
    "chirality center": "stereochemistry_chirality",
    "chirality centers": "stereochemistry_chirality",

    # Retrosynthetic Analysis
    "retrosynthesis": "retrosynthetic_analysis",
    "retrosynthetic analysis": "retrosynthetic_analysis",
    "retrosynthetic approach": "retrosynthetic_analysis",
    "retrosynthetic strategy": "retrosynthetic_analysis",
    "retrosynthetic planning": "retrosynthetic_analysis",
    "retrosynthetic disconnection": "retrosynthetic_analysis",
    "retrosynthetic disconnections": "retrosynthetic_analysis",
    "retrosynthetic steps": "retrosynthetic_analysis",
    "retrosynthetic route": "retrosynthetic_analysis",
    "retrosynthetic routes": "retrosynthetic_analysis",
    "retrosynthetic synthesis": "retrosynthetic_analysis",
    "retrosynthetic design": "retrosynthetic_analysis",
    "retrosynthetic tree": "retrosynthetic_analysis",
    "retrosynthetic scheme": "retrosynthetic_analysis",
    "retrosynthetic scheme design": "retrosynthetic_analysis",
    "retrosynthetic target": "retrosynthetic_analysis",
    "retrosynthetic target molecule": "retrosynthetic_analysis",
    "retrosynthetic target compound": "retrosynthetic_analysis",
    "retrosynthetic precursor": "retrosynthetic_analysis",
    "retrosynthetic precursors": "retrosynthetic_analysis",
    "retrosynthetic intermediate": "retrosynthetic_analysis",
    "retrosynthetic intermediates": "retrosynthetic_analysis",
    "retrosynthetic synthesis plan": "retrosynthetic_analysis",
    "retrosynthetic synthesis strategy": "retrosynthetic_analysis",
    "retrosynthetic synthesis route": "retrosynthetic_analysis",
    "retrosynthetic synthesis routes": "retrosynthetic_analysis",

    # NMR Spectroscopy
    "nmr": "nmr_spectroscopy",
    "nmr spectroscopy": "nmr_spectroscopy",
    "nuclear magnetic resonance": "nmr_spectroscopy",
    "nuclear magnetic resonance spectroscopy": "nmr_spectroscopy",
    "proton nmr": "nmr_spectroscopy",
    "1h nmr": "nmr_spectroscopy",
    "carbon nmr": "nmr_spectroscopy",
    "13c nmr": "nmr_spectroscopy",
    "chemical shift": "nmr_spectroscopy",
    "chemical shifts": "nmr_spectroscopy",
    "coupling constant": "nmr_spectroscopy",
    "coupling constants": "nmr_spectroscopy",
    "spin-spin coupling": "nmr_spectroscopy",
    "multiplet": "nmr_spectroscopy",
    "singlet": "nmr_spectroscopy",
    "doublet": "nmr_spectroscopy",
    "triplet": "nmr_spectroscopy",
    "quartet": "nmr_spectroscopy",
    "multiplicity": "nmr_spectroscopy",
    "integration": "nmr_spectroscopy",
    "nmr solvent": "nmr_spectroscopy",
    "nmr solvent effects": "nmr_spectroscopy",
    "nmr spectrum": "nmr_spectroscopy",
    "nmr spectra": "nmr_spectroscopy",
    "nmr interpretation": "nmr_spectroscopy",
    "nmr analysis": "nmr_spectroscopy",
    "nmr peak": "nmr_spectroscopy",
    "nmr peaks": "nmr_spectroscopy",
    "nmr splitting": "nmr_spectroscopy",
    "nmr splitting pattern": "nmr_spectroscopy",
    "nmr chemical environment": "nmr_spectroscopy",
    "nmr chemical environments": "nmr_spectroscopy",
    "nmr deshielding": "nmr_spectroscopy",
    "nmr shielding": "nmr_spectroscopy",
    "nmr reference standard": "nmr_spectroscopy",
    "nmr tetramethylsilane": "nmr_spectroscopy",
    "nmr tms": "nmr_spectroscopy",

    # IR Spectroscopy
    "ir": "ir_spectroscopy",
    "infrared": "ir_spectroscopy",
    "infrared spectroscopy": "ir_spectroscopy",
    "ir spectroscopy": "ir_spectroscopy",
    "ir spectrum": "ir_spectroscopy",
    "ir spectra": "ir_spectroscopy",
    "ir absorption": "ir_spectroscopy",
    "ir absorptions": "ir_spectroscopy",
    "ir peak": "ir_spectroscopy",
    "ir peaks": "ir_spectroscopy",
    "ir band": "ir_spectroscopy",
    "ir bands": "ir_spectroscopy",
    "ir fingerprint region": "ir_spectroscopy",
    "ir functional groups": "ir_spectroscopy",
    "ir stretching frequency": "ir_spectroscopy",
    "ir bending frequency": "ir_spectroscopy",
    "ir vibrational frequency": "ir_spectroscopy",
    "ir vibrational frequencies": "ir_spectroscopy",
    "ir carbonyl stretch": "ir_spectroscopy",
    "ir oh stretch": "ir_spectroscopy",
    "ir nh stretch": "ir_spectroscopy",
    "ir c-h stretch": "ir_spectroscopy",
    "ir c=c stretch": "ir_spectroscopy",
    "ir c≡c stretch": "ir_spectroscopy",
    "ir c≡n stretch": "ir_spectroscopy",
    "ir n-h stretch": "ir_spectroscopy",
    "ir o-h stretch": "ir_spectroscopy",
    "ir functional group identification": "ir_spectroscopy",
    "ir interpretation": "ir_spectroscopy",
    "ir analysis": "ir_spectroscopy",

    # Mass Spectrometry
    "ms": "mass_spectrometry",
    "mass spectrometry": "mass_spectrometry",
    "mass spec": "mass_spectrometry",
    "mass spectrum": "mass_spectrometry",
    "mass spectra": "mass_spectrometry",
    "mass fragmentation": "mass_spectrometry",
    "mass fragmentation pattern": "mass_spectrometry",
    "mass fragmentation patterns": "mass_spectrometry",
    "mass fragmentation mechanism": "mass_spectrometry",
    "mass fragmentation mech": "mass_spectrometry",
    "mass fragmentation mech.": "mass_spectrometry",
    "mass to charge ratio": "mass_spectrometry",
    "m/z": "mass_spectrometry",
    "m over z": "mass_spectrometry",
    "m over z ratio": "mass_spectrometry",
    "m over z values": "mass_spectrometry",
    "m over z peaks": "mass_spectrometry",
    "m over z peak": "mass_spectrometry",
    "m over z fragment": "mass_spectrometry",
    "m over z fragments": "mass_spectrometry",
    "mass spec ionization": "mass_spectrometry",
    "mass spec ionization methods": "mass_spectrometry",
    "mass spec ionization technique": "mass_spectrometry",
    "mass spec ionization techniques": "mass_spectrometry",
    "mass spec ionization fragmentation": "mass_spectrometry",
    "mass spec ionization fragmentation pattern": "mass_spectrometry",
    "mass spec ionization fragmentation patterns": "mass_spectrometry",
    "mass spec ionization fragmentation mechanism": "mass_spectrometry",
    "mass spec ionization fragmentation mech": "mass_spectrometry",
    "mass spec ionization fragmentation mech.": "mass_spectrometry",
    "mass spec molecular ion": "mass_spectrometry",
    "mass spec molecular ion peak": "mass_spectrometry",
    "mass spec base peak": "mass_spectrometry",
    "mass spec base peak intensity": "mass_spectrometry",
    "mass spec isotope pattern": "mass_spectrometry",
    "mass spec isotope distribution": "mass_spectrometry",
    "mass spec isotope peaks": "mass_spectrometry",
    "mass spec isotope peak": "mass_spectrometry",
    "mass spec interpretation": "mass_spectrometry",
    "mass spec analysis": "mass_spectrometry",

    # Radical Reactions
    "radical reaction": "radical_reactions",
    "radical reactions": "radical_reactions",
    "radical mechanism": "radical_reactions",
    "radical mech": "radical_reactions",
    "radical mech.": "radical_reactions",
    "radical initiation": "radical_reactions",
    "radical propagation": "radical_reactions",
    "radical termination": "radical_reactions",
    "radical chain reaction": "radical_reactions",
    "radical chain mechanism": "radical_reactions",
    "radical chain mech": "radical_reactions",
    "radical chain mech.": "radical_reactions",
    "radical intermediate": "radical_reactions",
    "radical intermediates": "radical_reactions",
    "radical stability": "radical_reactions",
    "radical formation": "radical_reactions",
    "radical generation": "radical_reactions",
    "radical initiator": "radical_reactions",
    "radical initiators": "radical_reactions",
    "radical inhibitor": "radical_reactions",
    "radical inhibitors": "radical_reactions",
    "radical scavenger": "radical_reactions",
    "radical scavengers": "radical_reactions",
    "radical substitution": "radical_reactions",
    "radical addition": "radical_reactions",
    "radical rearrangement": "radical_reactions",
    "radical abstraction": "radical_reactions",
    "radical halogenation": "radical_reactions",
    "radical bromination": "radical_reactions",
    "radical chlorination": "radical_reactions",

    # Pericyclic Reactions
    "pericyclic reaction": "pericyclic_reactions",
    "pericyclic reactions": "pericyclic_reactions",
    "cycloaddition": "pericyclic_reactions",
    "electrocyclic reaction": "pericyclic_reactions",
    "sigmatropic rearrangement": "pericyclic_reactions",
    "pericyclic reaction mechanism": "pericyclic_reactions",
    "pericyclic reaction mech": "pericyclic_reactions",
    "pericyclic reaction mech.": "pericyclic_reactions",
    "pericyclic reaction stereochemistry": "pericyclic_reactions",
    "pericyclic reaction stereochemical outcome": "pericyclic_reactions",
    "pericyclic reaction stereoselectivity": "pericyclic_reactions",
    "pericyclic reaction stereospecificity": "pericyclic_reactions",
    "pericyclic reaction examples": "pericyclic_reactions",
    "pericyclic reaction types": "pericyclic_reactions",
    "pericyclic reaction classification": "pericyclic_reactions",
    "pericyclic reaction theory": "pericyclic_reactions",
    "woodward-hoffmann rules": "pericyclic_reactions",
    "woodward hoffmann rules": "pericyclic_reactions",
    "woodward-hoffmann": "pericyclic_reactions",
    "woodward hoffmann": "pericyclic_reactions",
    "conrotatory": "pericyclic_reactions",
    "disrotatory": "pericyclic_reactions",
    "thermal pericyclic": "pericyclic_reactions",
    "photochemical pericyclic": "pericyclic_reactions",
    "pericyclic reaction orbital symmetry": "pericyclic_reactions",
    "pericyclic reaction frontier orbitals": "pericyclic_reactions",

    # Green Chemistry Principles
    "green chemistry": "green_chemistry_principles",
    "green chemistry principles": "green_chemistry_principles",
    "green chemistry concept": "green_chemistry_principles",
    "green chemistry concepts": "green_chemistry_principles",
    "green chemistry goals": "green_chemistry_principles",
    "green chemistry objectives": "green_chemistry_principles",
    "green chemistry 12 principles": "green_chemistry_principles",
    "green chemistry 12 principles list": "green_chemistry_principles",
    "green chemistry atom economy": "green_chemistry_principles",
    "green chemistry atom efficiency": "green_chemistry_principles",
    "green chemistry waste reduction": "green_chemistry_principles",
    "green chemistry energy efficiency": "green_chemistry_principles",
    "green chemistry renewable feedstocks": "green_chemistry_principles",
    "green chemistry safer solvents": "green_chemistry_principles",
    "green chemistry catalysis": "green_chemistry_principles",
    "green chemistry biodegradability": "green_chemistry_principles",
    "green chemistry toxicity reduction": "green_chemistry_principles",
    "green chemistry environmental impact": "green_chemistry_principles",
    "green chemistry sustainability": "green_chemistry_principles",
    "green chemistry sustainable synthesis": "green_chemistry_principles",

    # Polymer Chemistry Fundamentals
    "polymer chemistry": "polymer_chemistry_fundamentals",
    "polymer chemistry fundamentals": "polymer_chemistry_fundamentals",
    "polymerization": "polymer_chemistry_fundamentals",
    "polymerization reaction": "polymer_chemistry_fundamentals",
    "polymerization mechanisms": "polymer_chemistry_fundamentals",
    "polymerization mechanism": "polymer_chemistry_fundamentals",
    "polymerization types": "polymer_chemistry_fundamentals",
    "polymerization type": "polymer_chemistry_fundamentals",
    "addition polymerization": "polymer_chemistry_fundamentals",
    "condensation polymerization": "polymer_chemistry_fundamentals",
    "step growth polymerization": "polymer_chemistry_fundamentals",
    "chain growth polymerization": "polymer_chemistry_fundamentals",
    "radical polymerization": "polymer_chemistry_fundamentals",
    "cationic polymerization": "polymer_chemistry_fundamentals",
    "anionic polymerization": "polymer_chemistry_fundamentals",
    "polymer properties": "polymer_chemistry_fundamentals",
    "polymer structure": "polymer_chemistry_fundamentals",
    "polymer molecular weight": "polymer_chemistry_fundamentals",
    "polymer molecular weight distribution": "polymer_chemistry_fundamentals",
    "polymer tacticity": "polymer_chemistry_fundamentals",
    "polymer crystallinity": "polymer_chemistry_fundamentals",
    "polymer morphology": "polymer_chemistry_fundamentals",
    "polymer applications": "polymer_chemistry_fundamentals",

    # Carbohydrate Chemistry
    "carbohydrate": "carbohydrate_chemistry",
    "carbohydrates": "carbohydrate_chemistry",
    "carbohydrate chemistry": "carbohydrate_chemistry",
    "monosaccharide": "carbohydrate_chemistry",
    "monosaccharides": "carbohydrate_chemistry",
    "disaccharide": "carbohydrate_chemistry",
    "disaccharides": "carbohydrate_chemistry",
    "oligosaccharide": "carbohydrate_chemistry",
    "oligosaccharides": "carbohydrate_chemistry",
    "polysaccharide": "carbohydrate_chemistry",
    "polysaccharides": "carbohydrate_chemistry",
    "glycosidic bond": "carbohydrate_chemistry",
    "glycosidic linkage": "carbohydrate_chemistry",
    "glycosidic linkages": "carbohydrate_chemistry",
    "glycosylation": "carbohydrate_chemistry",
    "glycosylation reaction": "carbohydrate_chemistry",
    "carbohydrate stereochemistry": "carbohydrate_chemistry",
    "carbohydrate configuration": "carbohydrate_chemistry",
    "carbohydrate conformation": "carbohydrate_chemistry",
    "carbohydrate ring forms": "carbohydrate_chemistry",
    "carbohydrate furanose": "carbohydrate_chemistry",
    "carbohydrate pyranose": "carbohydrate_chemistry",
    "carbohydrate mutarotation": "carbohydrate_chemistry",
    "carbohydrate reducing sugar": "carbohydrate_chemistry",
    "carbohydrate nonreducing sugar": "carbohydrate_chemistry",
    "carbohydrate oxidation": "carbohydrate_chemistry",
    "carbohydrate reduction": "carbohydrate_chemistry",

    # Amino Acid Peptide Chemistry
    "amino acid": "amino_acid_peptide_chemistry",
    "amino acids": "amino_acid_peptide_chemistry",
    "peptide": "amino_acid_peptide_chemistry",
    "peptides": "amino_acid_peptide_chemistry",
    "amino acid chemistry": "amino_acid_peptide_chemistry",
    "peptide chemistry": "amino_acid_peptide_chemistry",
    "amino acid structure": "amino_acid_peptide_chemistry",
    "amino acid stereochemistry": "amino_acid_peptide_chemistry",
    "amino acid configuration": "amino_acid_peptide_chemistry",
    "amino acid properties": "amino_acid_peptide_chemistry",
    "amino acid side chain": "amino_acid_peptide_chemistry",
    "amino acid side chains": "amino_acid_peptide_chemistry",
    "peptide bond": "amino_acid_peptide_chemistry",
    "peptide bonds": "amino_acid_peptide_chemistry",
    "peptide synthesis": "amino_acid_peptide_chemistry",
    "peptide bond formation": "amino_acid_peptide_chemistry",
    "peptide bond cleavage": "amino_acid_peptide_chemistry",
    "peptide sequencing": "amino_acid_peptide_chemistry",
    "amino acid ionization": "amino_acid_peptide_chemistry",
    "amino acid zwitterion": "amino_acid_peptide_chemistry",
    "amino acid pka": "amino_acid_peptide_chemistry",
    "amino acid isoelectric point": "amino_acid_peptide_chemistry",
    "amino acid titration": "amino_acid_peptide_chemistry",

    # Lipid Chemistry
    "lipid": "lipid_chemistry",
    "lipids": "lipid_chemistry",
    "lipid chemistry": "lipid_chemistry",
    "fatty acid": "lipid_chemistry",
    "fatty acids": "lipid_chemistry",
    "triglyceride": "lipid_chemistry",
    "triglycerides": "lipid_chemistry",
    "phospholipid": "lipid_chemistry",
    "phospholipids": "lipid_chemistry",
    "steroid": "lipid_chemistry",
    "steroids": "lipid_chemistry",
    "lipid structure": "lipid_chemistry",
    "lipid function": "lipid_chemistry",
    "lipid biosynthesis": "lipid_chemistry",
    "lipid metabolism": "lipid_chemistry",
    "lipid oxidation": "lipid_chemistry",
    "lipid reduction": "lipid_chemistry",
    "lipid saturation": "lipid_chemistry",
    "lipid unsaturation": "lipid_chemistry",
    "lipid double bonds": "lipid_chemistry",
    "lipid esterification": "lipid_chemistry",
    "lipid hydrolysis": "lipid_chemistry",
    "lipid saponification": "lipid_chemistry",

    # Organometallic Cross Coupling
    "organometallic cross coupling": "organometallic_cross_coupling",
    "cross coupling": "organometallic_cross_coupling",
    "cross-coupling": "organometallic_cross_coupling",
    "organometallic coupling": "organometallic_cross_coupling",
    "palladium catalyzed coupling": "organometallic_cross_coupling",
    "palladium catalyzed cross coupling": "organometallic_cross_coupling",
    "palladium catalyzed cross-coupling": "organometallic_cross_coupling",
    "palladium catalyzed coupling reaction": "organometallic_cross_coupling",
    "palladium catalyzed coupling reactions": "organometallic_cross_coupling",
    "palladium catalyzed cross coupling reaction": "organometallic_cross_coupling",
    "palladium catalyzed cross coupling reactions": "organometallic_cross_coupling",
    "palladium catalyzed cross-coupling reaction": "organometallic_cross_coupling",
    "palladium catalyzed cross-coupling reactions": "organometallic_cross_coupling",
    "suzuki coupling": "organometallic_cross_coupling",
    "suzuki reaction": "organometallic_cross_coupling",
    "suzuki-miyaura coupling": "organometallic_cross_coupling",
    "suzuki-miyaura reaction": "organometallic_cross_coupling",
    "heck reaction": "organometallic_cross_coupling",
    "heck coupling": "organometallic_cross_coupling",
    "negishi coupling": "organometallic_cross_coupling",
    "negishi reaction": "organometallic_cross_coupling",
    "stille coupling": "organometallic_cross_coupling",
    "stille reaction": "organometallic_cross_coupling",
    "sonogashira coupling": "organometallic_cross_coupling",
    "sonogashira reaction": "organometallic_cross_coupling",
    "organometallic catalyst": "organometallic_cross_coupling",
    "organometallic catalyst palladium": "organometallic_cross_coupling",
    "organometallic catalyst nickel": "organometallic_cross_coupling",
    "organometallic catalyst copper": "organometallic_cross_coupling",
    "organometallic catalyst ligand": "organometallic_cross_coupling",
    "organometallic catalyst ligands": "organometallic_cross_coupling",
    "organometallic catalyst mechanism": "organometallic_cross_coupling",
    "organometallic catalyst mech": "organometallic_cross_coupling",
    "organometallic catalyst mech.": "organometallic_cross_coupling",

    # Safety Handling Organic Reagents
    "safety": "safety_handling_organic_reagents",
    "safety handling": "safety_handling_organic_reagents",
    "safety handling organic reagents": "safety_handling_organic_reagents",
    "organic reagent safety": "safety_handling_organic_reagents",
    "organic reagent handling": "safety_handling_organic_reagents",
    "chemical safety": "safety_handling_organic_reagents",
    "chemical handling": "safety_handling_organic_reagents",
    "chemical safety procedures": "safety_handling_organic_reagents",
    "chemical safety protocols": "safety_handling_organic_reagents",
    "chemical safety guidelines": "safety_handling_organic_reagents",
    "personal protective equipment": "safety_handling_organic_reagents",
    "ppe": "safety_handling_organic_reagents",
    "gloves": "safety_handling_organic_reagents",
    "lab coat": "safety_handling_organic_reagents",
    "goggles": "safety_handling_organic_reagents",
    "fume hood": "safety_handling_organic_reagents",
    "ventilation": "safety_handling_organic_reagents",
    "spill cleanup": "safety_handling_organic_reagents",
    "spill response": "safety_handling_organic_reagents",
    "fire safety": "safety_handling_organic_reagents",
    "fire extinguisher": "safety_handling_organic_reagents",
    "flammable reagents": "safety_handling_organic_reagents",
    "toxic reagents": "safety_handling_organic_reagents",
    "corrosive reagents": "safety_handling_organic_reagents",
    "hazardous reagents": "safety_handling_organic_reagents",
    "waste disposal": "safety_handling_organic_reagents",
    "chemical waste disposal": "safety_handling_organic_reagents",
    "emergency procedures": "safety_handling_organic_reagents",
    "first aid": "safety_handling_organic_reagents",
    "msds": "safety_handling_organic_reagents",
    "material safety data sheet": "safety_handling_organic_reagents",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    m = hashlib.sha256()
    # Sort keys to ensure consistent hash
    for key in sorted(SEMANTIC_MAP.keys()):
        value = SEMANTIC_MAP[key]
        m.update(key.encode('utf-8'))
        m.update(b'\0')
        m.update(value.encode('utf-8'))
        m.update(b'\0')
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "corrupt",
        "entries": actual_count,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "hash": actual_hash,
        "expected_hash": _MAP_INTEGRITY_HASH,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    if not isinstance(term, str):
        raise TypeError("term must be a string")
    term_lower = term.strip().lower()
    return SEMANTIC_MAP.get(term_lower, term_lower)

def get_related_terms(term: str) -> list[str]:
    if not isinstance(term, str):
        raise TypeError("term must be a string")
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)