import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AUTO13 Diesel Systems Team"
SEMANTIC_MAP_ENGINE = "AUTO13_diesel_systems"

SEMANTIC_MAP = {
    # Common Rail High Pressure Fuel System Diagnostics
    "common rail": "common_rail_high_pressure_fuel_system",
    "cr": "common_rail_high_pressure_fuel_system",
    "common rail system": "common_rail_high_pressure_fuel_system",
    "common rail fuel system": "common_rail_high_pressure_fuel_system",
    "crdi": "common_rail_high_pressure_fuel_system",
    "common rail direct injection": "common_rail_high_pressure_fuel_system",
    "high pressure fuel": "common_rail_high_pressure_fuel_system",
    "high pressure pump": "high_pressure_fuel_pump",
    "fuel rail": "fuel_rail",
    "fuel rail pressure": "fuel_rail_pressure",
    "rail pressure sensor": "fuel_rail_pressure_sensor",
    "fuel pressure sensor": "fuel_rail_pressure_sensor",
    "fuel pressure regulator": "fuel_pressure_regulator",
    "pressure control valve": "fuel_pressure_regulator",
    "pcv": "fuel_pressure_regulator",
    "fuel metering valve": "fuel_metering_valve",
    "fmv": "fuel_metering_valve",
    "fuel return line": "fuel_return_line",
    "leak off line": "fuel_return_line",
    "fuel leak off": "fuel_return_line",
    "fuel injector": "fuel_injector",
    "injector": "fuel_injector",
    "piezo injector": "fuel_injector",
    "solenoid injector": "fuel_injector",
    "injector solenoid": "fuel_injector",
    "injector circuit": "fuel_injector_circuit",
    "injector wiring": "fuel_injector_circuit",
    "injector harness": "fuel_injector_circuit",
    "injector driver": "fuel_injector_driver",
    "edc": "electronic_diesel_control",
    "electronic diesel control": "electronic_diesel_control",
    "edc module": "electronic_diesel_control",
    "edc unit": "electronic_diesel_control",
    "fuel delivery": "fuel_delivery_system",
    "fuel supply": "fuel_delivery_system",
    "fuel supply pump": "fuel_supply_pump",
    "lift pump": "fuel_supply_pump",
    "priming pump": "fuel_supply_pump",
    "fuel filter": "fuel_filter",
    "fuel filter head": "fuel_filter",
    "fuel filter housing": "fuel_filter",
    "fuel water separator": "fuel_water_separator",
    "water separator": "fuel_water_separator",
    "fuel contamination": "fuel_contamination",
    "fuel quality": "fuel_quality",
    "fuel sample": "fuel_quality",
    "fuel analysis": "fuel_quality",
    "diesel fuel analysis": "fuel_quality",
    "fuel test": "fuel_quality",
    "fuel contamination test": "fuel_contamination",
    "water in fuel": "fuel_contamination",
    "diesel bug": "fuel_contamination",
    "microbial contamination": "fuel_contamination",
    "algae in fuel": "fuel_contamination",
    "fuel sediment": "fuel_contamination",
    "fuel gel": "fuel_gelling",
    "fuel waxing": "fuel_gelling",
    "fuel gelling": "fuel_gelling",
    "cold filter plugging point": "fuel_gelling",
    "cfpp": "fuel_gelling",
    "fuel system diagnostics": "common_rail_high_pressure_fuel_system_diagnostics",
    "fuel system test": "common_rail_high_pressure_fuel_system_diagnostics",
    "fuel pressure test": "fuel_rail_pressure_test",
    "leak down test": "fuel_leak_down_test",
    "injector leak test": "fuel_leak_down_test",
    "high pressure leak": "fuel_leak_down_test",
    "fuel system leak": "fuel_leak_down_test",
    "return flow test": "fuel_return_flow_test",
    "injector return flow": "fuel_return_flow_test",
    "injector balance test": "injector_flow_balance_test",
    "injector flow balance": "injector_flow_balance_test",
    "injector quantity test": "injector_flow_balance_test",
    "injector coding": "injector_coding",
    "injector calibration": "injector_coding",
    "injector adaptation": "injector_coding",
    "pilot injection": "pilot_injection",
    "main injection": "main_injection",
    "post injection": "post_injection",
    "multiple injection": "multiple_injection",
    "injection event": "injection_event",
    "injection timing": "injection_timing",
    "timing synchronization": "injection_timing",
    "timing control": "injection_timing",
    "crankshaft sensor": "crankshaft_position_sensor",
    "ckp": "crankshaft_position_sensor",
    "camshaft sensor": "camshaft_position_sensor",
    "cmp": "camshaft_position_sensor",
    "synchronization error": "injection_timing_sync_error",
    "sync error": "injection_timing_sync_error",
    "timing error": "injection_timing_sync_error",
    "fuel pulse": "injection_event",
    "fuel pulse width": "injection_event",
    "injector pulse": "injection_event",
    "fuel system fault": "common_rail_high_pressure_fuel_system_fault",
    "fuel system error": "common_rail_high_pressure_fuel_system_fault",
    "fuel system warning": "common_rail_high_pressure_fuel_system_fault",
    "fuel system malfunction": "common_rail_high_pressure_fuel_system_fault",

    # Turbocharger Boost Control and Compressor Surge Analysis
    "turbo": "turbocharger",
    "turbocharger": "turbocharger",
    "turbine": "turbocharger_turbine",
    "compressor": "turbocharger_compressor",
    "boost": "boost_pressure",
    "boost pressure": "boost_pressure",
    "boost control": "boost_control",
    "boost solenoid": "boost_control_solenoid",
    "wastegate": "wastegate",
    "wastegate actuator": "wastegate_actuator",
    "electronic actuator": "wastegate_actuator",
    "pneumatic actuator": "wastegate_actuator",
    "vgt": "variable_geometry_turbocharger",
    "variable geometry turbo": "variable_geometry_turbocharger",
    "variable nozzle turbo": "variable_geometry_turbocharger",
    "vnt": "variable_geometry_turbocharger",
    "vgt actuator": "vgt_actuator",
    "vnt actuator": "vgt_actuator",
    "turbo actuator": "vgt_actuator",
    "turbo lag": "turbo_lag",
    "turbo response": "turbo_lag",
    "turbo surge": "compressor_surge",
    "compressor surge": "compressor_surge",
    "surge event": "compressor_surge",
    "boost spike": "compressor_surge",
    "overboost": "overboost_condition",
    "underboost": "underboost_condition",
    "boost leak": "boost_leak",
    "charge air leak": "boost_leak",
    "intercooler leak": "boost_leak",
    "intercooler": "intercooler",
    "charge air cooler": "intercooler",
    "cac": "intercooler",
    "charge air temperature": "charge_air_temperature",
    "cat": "charge_air_temperature",
    "intake air temperature": "charge_air_temperature",
    "iat": "charge_air_temperature",
    "boost sensor": "boost_pressure_sensor",
    "map sensor": "boost_pressure_sensor",
    "manifold absolute pressure sensor": "boost_pressure_sensor",
    "boost control fault": "boost_control_fault",
    "boost control error": "boost_control_fault",
    "boost control warning": "boost_control_fault",
    "turbo fault": "turbocharger_fault",
    "turbo error": "turbocharger_fault",
    "turbo warning": "turbocharger_fault",
    "turbo malfunction": "turbocharger_fault",
    "wastegate fault": "wastegate_fault",
    "wastegate error": "wastegate_fault",
    "wastegate warning": "wastegate_fault",
    "wastegate malfunction": "wastegate_fault",
    "vgt fault": "vgt_fault",
    "vgt error": "vgt_fault",
    "vgt warning": "vgt_fault",
    "vgt malfunction": "vgt_fault",

    # Diesel Particulate Filter Regeneration and Ash Loading
    "dpf": "diesel_particulate_filter",
    "diesel particulate filter": "diesel_particulate_filter",
    "particulate filter": "diesel_particulate_filter",
    "soot filter": "diesel_particulate_filter",
    "dpf regen": "dpf_regeneration",
    "dpf regeneration": "dpf_regeneration",
    "regeneration": "dpf_regeneration",
    "forced regen": "dpf_regeneration_forced",
    "manual regen": "dpf_regeneration_forced",
    "active regen": "dpf_regeneration_active",
    "passive regen": "dpf_regeneration_passive",
    "soot loading": "dpf_soot_loading",
    "soot mass": "dpf_soot_loading",
    "soot accumulation": "dpf_soot_loading",
    "ash loading": "dpf_ash_loading",
    "ash accumulation": "dpf_ash_loading",
    "ash content": "dpf_ash_loading",
    "dpf pressure": "dpf_pressure",
    "dpf differential pressure": "dpf_pressure",
    "dpf pressure sensor": "dpf_pressure_sensor",
    "dpf temp sensor": "dpf_temperature_sensor",
    "dpf temperature sensor": "dpf_temperature_sensor",
    "dpf temp": "dpf_temperature_sensor",
    "dpf fault": "dpf_fault",
    "dpf error": "dpf_fault",
    "dpf warning": "dpf_fault",
    "dpf malfunction": "dpf_fault",
    "dpf blocked": "dpf_blocked",
    "dpf clogged": "dpf_blocked",
    "dpf restriction": "dpf_blocked",
    "dpf filter blocked": "dpf_blocked",
    "dpf filter clogged": "dpf_blocked",
    "dpf filter restriction": "dpf_blocked",
    "dpf cleaning": "dpf_cleaning",
    "dpf service": "dpf_cleaning",
    "dpf maintenance": "dpf_cleaning",
    "dpf replacement": "dpf_replacement",
    "dpf delete": "dpf_delete",
    "dpf removal": "dpf_delete",
    "dpf off": "dpf_delete",
    "dpf bypass": "dpf_delete",

    # Selective Catalytic Reduction DEF System Diagnostics
    "scr": "selective_catalytic_reduction",
    "selective catalytic reduction": "selective_catalytic_reduction",
    "urea system": "selective_catalytic_reduction",
    "def": "diesel_exhaust_fluid",
    "diesel exhaust fluid": "diesel_exhaust_fluid",
    "adblue": "diesel_exhaust_fluid",
    "def tank": "def_tank",
    "def pump": "def_pump",
    "def injector": "def_injector",
    "def dosing valve": "def_injector",
    "def dosing module": "def_injector",
    "def line": "def_line",
    "def heater": "def_heater",
    "def quality": "def_quality",
    "def concentration": "def_quality",
    "def contamination": "def_contamination",
    "def crystallization": "def_crystallization",
    "def freeze": "def_crystallization",
    "def frozen": "def_crystallization",
    "def sensor": "def_sensor",
    "def level sensor": "def_level_sensor",
    "def quality sensor": "def_quality_sensor",
    "def temperature sensor": "def_temperature_sensor",
    "def pressure sensor": "def_pressure_sensor",
    "scr catalyst": "scr_catalyst",
    "scr converter": "scr_catalyst",
    "scr fault": "scr_fault",
    "scr error": "scr_fault",
    "scr warning": "scr_fault",
    "scr malfunction": "scr_fault",
    "def fault": "def_fault",
    "def error": "def_fault",
    "def warning": "def_fault",
    "def malfunction": "def_fault",
    "no x sensor": "nox_sensor",
    "nox sensor": "nox_sensor",
    "nox": "nox_sensor",
    "nox reduction": "nox_reduction",
    "nox control": "nox_reduction",
    "nox catalyst": "nox_catalyst",
    "ammonia slip": "ammonia_slip",
    "ammonia sensor": "ammonia_sensor",
    "scr efficiency": "scr_efficiency",
    "scr conversion": "scr_efficiency",

    # Glow Plug System Operation and Pre-Heat Diagnostics
    "glow plug": "glow_plug",
    "glow plugs": "glow_plug",
    "glow plug relay": "glow_plug_relay",
    "glow relay": "glow_plug_relay",
    "glow plug module": "glow_plug_control_module",
    "glow plug controller": "glow_plug_control_module",
    "glow plug control": "glow_plug_control_module",
    "glow plug timer": "glow_plug_timer",
    "pre heat": "glow_plug_preheat",
    "preheat": "glow_plug_preheat",
    "pre heat time": "glow_plug_preheat",
    "post heat": "glow_plug_postheat",
    "postheat": "glow_plug_postheat",
    "after glow": "glow_plug_postheat",
    "afterglow": "glow_plug_postheat",
    "glow plug fault": "glow_plug_fault",
    "glow plug error": "glow_plug_fault",
    "glow plug warning": "glow_plug_fault",
    "glow plug malfunction": "glow_plug_fault",
    "glow plug light": "glow_plug_indicator",
    "glow indicator": "glow_plug_indicator",
    "glow plug lamp": "glow_plug_indicator",
    "glow plug circuit": "glow_plug_circuit",
    "glow plug wiring": "glow_plug_circuit",

    # Diesel Fuel Quality Assessment and Contamination Analysis
    "diesel quality": "fuel_quality",
    "diesel contamination": "fuel_contamination",
    "fuel bacteria": "fuel_contamination",
    "fuel fungus": "fuel_contamination",
    "fuel oxidation": "fuel_contamination",
    "fuel degradation": "fuel_contamination",
    "fuel stability": "fuel_quality",
    "cetane number": "cetane_number",
    "cetane index": "cetane_number",
    "cetane rating": "cetane_number",
    "cloud point": "cloud_point",
    "pour point": "pour_point",
    "flash point": "flash_point",
    "water content": "fuel_contamination",
    "sulfur content": "sulfur_content",
    "lubricity": "fuel_lubricity",
    "fuel lubricity": "fuel_lubricity",
    "viscosity": "fuel_viscosity",
    "fuel viscosity": "fuel_viscosity",
    "density": "fuel_density",
    "fuel density": "fuel_density",
    "bio diesel": "biodiesel",
    "biodiesel": "biodiesel",
    "fame": "biodiesel",
    "ester content": "biodiesel",
    "fuel blend": "fuel_blend",
    "fuel mixture": "fuel_blend",
    "diesel blend": "fuel_blend",
    "b7": "fuel_blend",
    "b20": "fuel_blend",
    "b100": "fuel_blend",

    # Diesel Engine Compression Testing and Cylinder Sealing
    "compression test": "compression_testing",
    "compression testing": "compression_testing",
    "cylinder compression": "compression_testing",
    "cylinder pressure": "compression_testing",
    "leak down": "cylinder_leak_down",
    "leakdown": "cylinder_leak_down",
    "leak down test": "cylinder_leak_down",
    "cylinder leak down": "cylinder_leak_down",
    "cylinder leakage": "cylinder_leak_down",
    "blowby": "blowby",
    "blow by": "blowby",
    "crankcase blowby": "blowby",
    "piston ring blowby": "blowby",
    "valve leakage": "valve_leakage",
    "valve seal": "valve_leakage",
    "valve seat leakage": "valve_leakage",
    "cylinder sealing": "cylinder_sealing",
    "head gasket": "head_gasket",
    "head gasket leak": "head_gasket",
    "head gasket failure": "head_gasket",
    "gasket failure": "head_gasket",
    "cylinder head crack": "cylinder_head_crack",
    "cracked head": "cylinder_head_crack",
    "cracked block": "cylinder_block_crack",
    "block crack": "cylinder_block_crack",

    # Diesel Injection Timing and Valve Train Synchronization
    "timing": "injection_timing",
    "timing test": "injection_timing",
    "timing check": "injection_timing",
    "timing mark": "timing_marks",
    "timing marks": "timing_marks",
    "timing chain": "timing_chain",
    "timing belt": "timing_belt",
    "timing gear": "timing_gear",
    "timing cover": "timing_cover",
    "cam timing": "camshaft_timing",
    "camshaft timing": "camshaft_timing",
    "valve timing": "valve_timing",
    "valve train": "valve_train",
    "valve train synchronization": "valve_train_synchronization",
    "valve train sync": "valve_train_synchronization",
    "valve lash": "valve_lash",
    "valve clearance": "valve_lash",
    "tappet clearance": "valve_lash",
    "rocker clearance": "valve_lash",
    "valve adjustment": "valve_lash",
    "camshaft": "camshaft",
    "cam": "camshaft",
    "camshaft sensor": "camshaft_position_sensor",
    "cam sensor": "camshaft_position_sensor",
    "crankshaft": "crankshaft",
    "crank": "crankshaft",
    "crankshaft sensor": "crankshaft_position_sensor",
    "crank sensor": "crankshaft_position_sensor",

    # EGR System Diagnostics and Cooler Fouling Analysis
    "egr": "exhaust_gas_recirculation",
    "exhaust gas recirculation": "exhaust_gas_recirculation",
    "egr valve": "egr_valve",
    "egr cooler": "egr_cooler",
    "egr bypass": "egr_bypass",
    "egr flow": "egr_flow",
    "egr flow rate": "egr_flow",
    "egr flow sensor": "egr_flow_sensor",
    "egr temp sensor": "egr_temperature_sensor",
    "egr temperature sensor": "egr_temperature_sensor",
    "egr temp": "egr_temperature_sensor",
    "egr fault": "egr_fault",
    "egr error": "egr_fault",
    "egr warning": "egr_fault",
    "egr malfunction": "egr_fault",
    "egr stuck": "egr_valve_stuck",
    "egr blocked": "egr_valve_stuck",
    "egr clogged": "egr_valve_stuck",
    "egr fouling": "egr_cooler_fouling",
    "egr cooler fouling": "egr_cooler_fouling",
    "egr cooler blockage": "egr_cooler_fouling",
    "egr cooler leak": "egr_cooler_leak",
    "egr leak": "egr_leak",
    "egr system": "exhaust_gas_recirculation",
    "egr delete": "egr_delete",
    "egr off": "egr_delete",
    "egr removal": "egr_delete",
    "egr bypass": "egr_bypass",

    # Diesel Engine Oil Analysis and Wear Metal Trending
    "oil analysis": "engine_oil_analysis",
    "engine oil analysis": "engine_oil_analysis",
    "oil sample": "engine_oil_analysis",
    "oil test": "engine_oil_analysis",
    "oil quality": "engine_oil_analysis",
    "oil contamination": "engine_oil_contamination",
    "oil dilution": "engine_oil_contamination",
    "fuel in oil": "engine_oil_contamination",
    "diesel in oil": "engine_oil_contamination",
    "oil wear metals": "oil_wear_metals",
    "wear metals": "oil_wear_metals",
    "iron in oil": "oil_wear_metals",
    "copper in oil": "oil_wear_metals",
    "lead in oil": "oil_wear_metals",
    "tin in oil": "oil_wear_metals",
    "oil viscosity": "engine_oil_viscosity",
    "oil pressure": "engine_oil_pressure",
    "oil pressure sensor": "engine_oil_pressure_sensor",
    "oil temp": "engine_oil_temperature",
    "oil temperature": "engine_oil_temperature",
    "oil temp sensor": "engine_oil_temperature_sensor",
    "oil filter": "engine_oil_filter",
    "oil filter bypass": "engine_oil_filter_bypass",
    "oil filter restriction": "engine_oil_filter_restriction",
    "oil change": "engine_oil_change",
    "oil service": "engine_oil_change",
    "oil interval": "engine_oil_change_interval",
    "oil drain": "engine_oil_change",
    "oil pan": "engine_oil_pan",
    "oil sump": "engine_oil_pan",
    "oil pump": "engine_oil_pump",

    # Diesel Engine Cooling System and Cavitation Analysis
    "cooling system": "engine_cooling_system",
    "engine cooling": "engine_cooling_system",
    "coolant": "engine_coolant",
    "coolant temp": "engine_coolant_temperature",
    "coolant temperature": "engine_coolant_temperature",
    "coolant temp sensor": "engine_coolant_temperature_sensor",
    "coolant sensor": "engine_coolant_temperature_sensor",
    "coolant pressure": "engine_coolant_pressure",
    "coolant pressure sensor": "engine_coolant_pressure_sensor",
    "coolant leak": "engine_coolant_leak",
    "coolant loss": "engine_coolant_leak",
    "coolant hose": "engine_coolant_hose",
    "coolant pump": "engine_coolant_pump",
    "water pump": "engine_coolant_pump",
    "radiator": "engine_radiator",
    "radiator cap": "engine_radiator_cap",
    "radiator hose": "engine_radiator_hose",
    "thermostat": "engine_thermostat",
    "cooling fan": "engine_cooling_fan",
    "fan clutch": "engine_cooling_fan_clutch",
    "fan relay": "engine_cooling_fan_relay",
    "cavitation": "cooling_system_cavitation",
    "cavitation erosion": "cooling_system_cavitation",
    "liner pitting": "cooling_system_cavitation",
    "cylinder liner pitting": "cooling_system_cavitation",
    "coolant analysis": "coolant_analysis",
    "coolant test": "coolant_analysis",
    "coolant sample": "coolant_analysis",
    "coolant quality": "coolant_analysis",
    "coolant contamination": "coolant_contamination",
    "coolant additive": "coolant_additive",
    "sca": "coolant_additive",
    "supplemental coolant additive": "coolant_additive",
    "coolant filter": "coolant_filter",
    "coolant filter restriction": "coolant_filter_restriction",

    # Diesel Engine Electrical System and Charging Analysis
    "electrical system": "engine_electrical_system",
    "engine electrical": "engine_electrical_system",
    "charging system": "engine_charging_system",
    "alternator": "alternator",
    "generator": "alternator",
    "voltage regulator": "voltage_regulator",
    "battery": "battery",
    "battery voltage": "battery_voltage",
    "battery test": "battery_test",
    "battery analysis": "battery_test",
    "battery load test": "battery_load_test",
    "starter": "starter_motor",
    "starter motor": "starter_motor",
    "starter relay": "starter_relay",
    "starter solenoid": "starter_solenoid",
    "starter circuit": "starter_circuit",
    "starter wiring": "starter_circuit",
    "starter fault": "starter_fault",
    "starter error": "starter_fault",
    "starter warning": "starter_fault",
    "starter malfunction": "starter_fault",
    "alternator fault": "alternator_fault",
    "alternator error": "alternator_fault",
    "alternator warning": "alternator_fault",
    "alternator malfunction": "alternator_fault",
    "charging fault": "engine_charging_system_fault",
    "charging error": "engine_charging_system_fault",
    "charging warning": "engine_charging_system_fault",
    "charging malfunction": "engine_charging_system_fault",
    "voltage drop": "voltage_drop",
    "ground fault": "ground_fault",
    "ground error": "ground_fault",
    "ground warning": "ground_fault",
    "ground malfunction": "ground_fault",

    # Diesel Fuel Injector Flow Balance and Pattern Testing
    "injector test": "injector_flow_balance_test",
    "injector flow test": "injector_flow_balance_test",
    "injector pattern test": "injector_pattern_test",
    "injector spray pattern": "injector_pattern_test",
    "injector spray": "injector_pattern_test",
    "injector atomization": "injector_pattern_test",
    "injector dribble": "injector_pattern_test",
    "injector leakage": "injector_leakage",
    "injector leak": "injector_leakage",
    "injector return": "injector_return",
    "injector return flow": "injector_return",
    "injector backflow": "injector_return",
    "injector stuck": "injector_stuck",
    "injector blocked": "injector_stuck",
    "injector clogged": "injector_stuck",
    "injector fouling": "injector_stuck",
    "injector misfire": "injector_misfire",
    "injector short": "injector_electrical_fault",
    "injector open": "injector_electrical_fault",
    "injector electrical fault": "injector_electrical_fault",
    "injector circuit fault": "injector_electrical_fault",
    "injector circuit error": "injector_electrical_fault",
    "injector circuit warning": "injector_electrical_fault",
    "injector circuit malfunction": "injector_electrical_fault",

    # Diesel Crankcase Ventilation and Blowby Management
    "crankcase ventilation": "crankcase_ventilation",
    "ccv": "crankcase_ventilation",
    "pcv": "crankcase_ventilation",
    "positive crankcase ventilation": "crankcase_ventilation",
    "crankcase breather": "crankcase_breather",
    "breather": "crankcase_breather",
    "breather filter": "crankcase_breather_filter",
    "oil separator": "crankcase_oil_separator",
    "blowby meter": "blowby_meter",
    "blowby test": "blowby_meter",
    "blowby measurement": "blowby_meter",
    "blowby sensor": "blowby_sensor",
    "blowby control": "blowby_management",
    "blowby management": "blowby_management",
    "crankcase pressure": "crankcase_pressure",
    "crankcase pressure sensor": "crankcase_pressure_sensor",
    "crankcase oil mist": "crankcase_oil_mist",
    "oil mist separator": "crankcase_oil_separator",
    "oil mist": "crankcase_oil_mist",
    "oil mist filter": "crankcase_oil_separator",
    "oil vapor": "crankcase_oil_mist",
    "oil vapor separator": "crankcase_oil_separator",
    "oil vapor filter": "crankcase_oil_separator",
    "crankcase filter": "crankcase_breather_filter",
    "crankcase oil separator": "crankcase_oil_separator",
    "crankcase oil mist separator": "crankcase_oil_separator",
    "crankcase oil mist filter": "crankcase_oil_separator",
    "crankcase emission": "crankcase_emission",
    "crankcase emission control": "crankcase_emission",
    "crankcase emission system": "crankcase_emission",
    "blowby emission": "crankcase_emission",
    "blowby emission control": "crankcase_emission",
    "blowby emission system": "crankcase_emission",
    "blowby filter": "crankcase_breather_filter",
    "blowby oil separator": "crankcase_oil_separator",
    "blowby oil mist separator": "crankcase_oil_separator",
    "blowby oil mist filter": "crankcase_oil_separator",
}

_EXPECTED_ENTRY_COUNT = 260

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    map_bytes = b""
    for k, v in items:
        map_bytes += k.encode("utf-8") + b"=" + v.encode("utf-8") + b";"
    map_bytes += SEMANTIC_MAP_VERSION.encode("utf-8")
    map_bytes += SEMANTIC_MAP_AUTHOR.encode("utf-8")
    map_bytes += SEMANTIC_MAP_ENGINE.encode("utf-8")
    map_bytes += str(_EXPECTED_ENTRY_COUNT).encode("utf-8")
    return hashlib.sha256(map_bytes).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (
        actual_count == _EXPECTED_ENTRY_COUNT and
        actual_hash == _MAP_INTEGRITY_HASH
    )
    return {
        "status": "ok" if is_valid else "invalid",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_key(term):
    if not isinstance(term, str):
        return ""
    t = term.strip().lower()
    t = re.sub(r"[^a-z0-9\s\-_/\.]", "", t)
    t = re.sub(r"\s+", " ", t)
    t = t.replace("-", " ")
    t = t.replace("_", " ")
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    return t

def normalize_term(term: str) -> str:
    key = _normalize_key(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list:
    key = _normalize_key(term)
    norm = SEMANTIC_MAP.get(key, key)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)