import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MECH08 Team"
SEMANTIC_MAP_ENGINE = "MECH08_welding_inspection"

SEMANTIC_MAP = {
    # SMAW Stick Welding Process Selection
    "smaw": "shielded metal arc welding",
    "stick welding": "shielded metal arc welding",
    "manual arc welding": "shielded metal arc welding",
    "arc welding": "shielded metal arc welding",
    "smaw process": "shielded metal arc welding",
    "smaw stick": "shielded metal arc welding",
    "stick electrode": "shielded metal arc welding",
    "smaw electrode": "shielded metal arc welding",
    "smaw selection": "smaw process selection",
    "stick process selection": "smaw process selection",
    "shielded metal arc": "shielded metal arc welding",
    "shielded metal arc weld": "shielded metal arc welding",
    "stick weld": "shielded metal arc welding",
    "arc stick": "shielded metal arc welding",
    "arc stick welding": "shielded metal arc welding",
    "smaw welding": "shielded metal arc welding",
    "smaw stick weld": "shielded metal arc welding",
    "smaw stick welding": "shielded metal arc welding",
    "smaw stick process": "shielded metal arc welding",
    "stick": "shielded metal arc welding",
    "stick process": "shielded metal arc welding",
    "stick selection": "smaw process selection",
    "smaw stick selection": "smaw process selection",
    "stick weld selection": "smaw process selection",
    "smaw stick weld selection": "smaw process selection",

    # GMAW/MIG Welding Process Parameters
    "mig": "gas metal arc welding",
    "mig welding": "gas metal arc welding",
    "gmaw": "gas metal arc welding",
    "gmaw welding": "gas metal arc welding",
    "gmaw process": "gas metal arc welding",
    "mig process": "gas metal arc welding",
    "metal inert gas": "gas metal arc welding",
    "metal inert gas welding": "gas metal arc welding",
    "gas metal arc": "gas metal arc welding",
    "gas metal arc weld": "gas metal arc welding",
    "mig weld": "gas metal arc welding",
    "mig parameters": "gmaw process parameters",
    "gmaw parameters": "gmaw process parameters",
    "mig settings": "gmaw process parameters",
    "gmaw settings": "gmaw process parameters",
    "mig process parameters": "gmaw process parameters",
    "gmaw process parameters": "gmaw process parameters",
    "mig wire": "gmaw filler wire",
    "gmaw wire": "gmaw filler wire",
    "mig electrode": "gmaw filler wire",
    "gmaw electrode": "gmaw filler wire",
    "mig filler": "gmaw filler wire",
    "gmaw filler": "gmaw filler wire",

    # GTAW/TIG Welding for Critical Applications
    "tig": "gas tungsten arc welding",
    "tig welding": "gas tungsten arc welding",
    "gtaw": "gas tungsten arc welding",
    "gtaw welding": "gas tungsten arc welding",
    "gtaw process": "gas tungsten arc welding",
    "tig process": "gas tungsten arc welding",
    "gas tungsten arc": "gas tungsten arc welding",
    "gas tungsten arc weld": "gas tungsten arc welding",
    "tig weld": "gas tungsten arc welding",
    "tig for critical": "gtaw for critical applications",
    "gtaw for critical": "gtaw for critical applications",
    "critical tig": "gtaw for critical applications",
    "critical gtaw": "gtaw for critical applications",
    "critical welding": "gtaw for critical applications",
    "critical application welding": "gtaw for critical applications",
    "critical applications": "gtaw for critical applications",
    "critical welds": "gtaw for critical applications",
    "tig electrode": "gtaw filler rod",
    "gtaw electrode": "gtaw filler rod",
    "tig filler": "gtaw filler rod",
    "gtaw filler": "gtaw filler rod",
    "tig rod": "gtaw filler rod",
    "gtaw rod": "gtaw filler rod",

    # Welding Procedure Specification (WPS) per ASME Section IX
    "wps": "welding procedure specification",
    "welding procedure specification": "welding procedure specification",
    "welding procedure": "welding procedure specification",
    "procedure specification": "welding procedure specification",
    "welding spec": "welding procedure specification",
    "welding specification": "welding procedure specification",
    "welding procedure spec": "welding procedure specification",
    "welding procedure specifications": "welding procedure specification",
    "wps asme ix": "welding procedure specification asme section ix",
    "wps asme section ix": "welding procedure specification asme section ix",
    "welding procedure specification asme ix": "welding procedure specification asme section ix",
    "welding procedure specification asme section ix": "welding procedure specification asme section ix",
    "asme ix wps": "welding procedure specification asme section ix",
    "asme section ix wps": "welding procedure specification asme section ix",
    "asme ix welding procedure": "welding procedure specification asme section ix",
    "asme section ix welding procedure": "welding procedure specification asme section ix",
    "asme ix welding procedure specification": "welding procedure specification asme section ix",
    "asme section ix welding procedure specification": "welding procedure specification asme section ix",

    # Welder Performance Qualification per ASME Section IX
    "welder qualification": "welder performance qualification",
    "welder performance qualification": "welder performance qualification",
    "wpq": "welder performance qualification",
    "performance qualification": "welder performance qualification",
    "welder performance": "welder performance qualification",
    "welder performance test": "welder performance qualification",
    "welder test": "welder performance qualification",
    "welder qualification asme ix": "welder performance qualification asme section ix",
    "welder qualification asme section ix": "welder performance qualification asme section ix",
    "welder performance qualification asme ix": "welder performance qualification asme section ix",
    "welder performance qualification asme section ix": "welder performance qualification asme section ix",
    "asme ix welder qualification": "welder performance qualification asme section ix",
    "asme section ix welder qualification": "welder performance qualification asme section ix",
    "asme ix welder performance qualification": "welder performance qualification asme section ix",
    "asme section ix welder performance qualification": "welder performance qualification asme section ix",

    # Preheat and Interpass Temperature Requirements
    "preheat": "preheat temperature",
    "preheat temperature": "preheat temperature",
    "preheat requirements": "preheat temperature requirements",
    "preheat temp": "preheat temperature",
    "preheating": "preheat temperature",
    "preheat temp requirements": "preheat temperature requirements",
    "preheat requirement": "preheat temperature requirements",
    "interpass": "interpass temperature",
    "interpass temperature": "interpass temperature",
    "interpass temp": "interpass temperature",
    "interpass requirements": "interpass temperature requirements",
    "interpass temp requirements": "interpass temperature requirements",
    "interpass requirement": "interpass temperature requirements",
    "preheat and interpass": "preheat and interpass temperature requirements",
    "preheat and interpass temperature": "preheat and interpass temperature requirements",
    "preheat and interpass requirements": "preheat and interpass temperature requirements",
    "preheat and interpass temp": "preheat and interpass temperature requirements",
    "preheat interpass": "preheat and interpass temperature requirements",
    "preheat interpass requirements": "preheat and interpass temperature requirements",

    # Post-Weld Heat Treatment (PWHT) Requirements
    "pwht": "post-weld heat treatment",
    "post-weld heat treatment": "post-weld heat treatment",
    "post weld heat treatment": "post-weld heat treatment",
    "postweld heat treatment": "post-weld heat treatment",
    "post weld heat treat": "post-weld heat treatment",
    "post-weld heat treat": "post-weld heat treatment",
    "pwht requirements": "post-weld heat treatment requirements",
    "pwht requirement": "post-weld heat treatment requirements",
    "post-weld heat treatment requirements": "post-weld heat treatment requirements",
    "post weld heat treatment requirements": "post-weld heat treatment requirements",
    "postweld heat treatment requirements": "post-weld heat treatment requirements",
    "post weld heat treat requirements": "post-weld heat treatment requirements",
    "post-weld heat treat requirements": "post-weld heat treatment requirements",

    # Filler Metal Selection and AWS Classification
    "filler metal": "filler metal selection",
    "filler metal selection": "filler metal selection",
    "filler selection": "filler metal selection",
    "filler": "filler metal selection",
    "filler rod": "filler metal selection",
    "filler wire": "filler metal selection",
    "welding filler": "filler metal selection",
    "welding filler metal": "filler metal selection",
    "welding filler rod": "filler metal selection",
    "welding filler wire": "filler metal selection",
    "filler metal aws": "filler metal aws classification",
    "filler metal aws classification": "filler metal aws classification",
    "aws filler metal": "filler metal aws classification",
    "aws classification": "filler metal aws classification",
    "aws filler": "filler metal aws classification",
    "aws filler classification": "filler metal aws classification",
    "filler aws": "filler metal aws classification",
    "filler aws classification": "filler metal aws classification",
    "filler metal class": "filler metal aws classification",
    "filler metal classification": "filler metal aws classification",

    # Weld Joint Design and Preparation
    "weld joint": "weld joint design",
    "weld joint design": "weld joint design",
    "joint design": "weld joint design",
    "joint preparation": "weld joint preparation",
    "weld joint preparation": "weld joint preparation",
    "joint prep": "weld joint preparation",
    "weld joint prep": "weld joint preparation",
    "joint design and preparation": "weld joint design and preparation",
    "weld joint design and preparation": "weld joint design and preparation",
    "joint design prep": "weld joint design and preparation",
    "weld joint design prep": "weld joint design and preparation",
    "joint design preparation": "weld joint design and preparation",

    # Weld Defects - Porosity
    "porosity": "weld porosity",
    "weld porosity": "weld porosity",
    "porous weld": "weld porosity",
    "porosity defect": "weld porosity",
    "porosity defects": "weld porosity",
    "porosity in weld": "weld porosity",
    "weld porosity defect": "weld porosity",
    "weld porosity defects": "weld porosity",
    "porosity issue": "weld porosity",
    "porosity issues": "weld porosity",

    # Weld Defects - Lack of Fusion and Incomplete Penetration
    "lack of fusion": "weld lack of fusion",
    "weld lack of fusion": "weld lack of fusion",
    "fusion defect": "weld lack of fusion",
    "fusion defects": "weld lack of fusion",
    "lack of fusion defect": "weld lack of fusion",
    "lack of fusion defects": "weld lack of fusion",
    "incomplete fusion": "weld lack of fusion",
    "incomplete fusion defect": "weld lack of fusion",
    "incomplete fusion defects": "weld lack of fusion",
    "incomplete penetration": "weld incomplete penetration",
    "weld incomplete penetration": "weld incomplete penetration",
    "penetration defect": "weld incomplete penetration",
    "penetration defects": "weld incomplete penetration",
    "incomplete penetration defect": "weld incomplete penetration",
    "incomplete penetration defects": "weld incomplete penetration",
    "lack of penetration": "weld incomplete penetration",
    "lack of penetration defect": "weld incomplete penetration",
    "lack of penetration defects": "weld incomplete penetration",

    # Weld Defects - Cracks (Hot Cracks and Cold Cracks)
    "crack": "weld crack",
    "cracks": "weld crack",
    "weld crack": "weld crack",
    "weld cracks": "weld crack",
    "hot crack": "weld hot crack",
    "hot cracks": "weld hot crack",
    "weld hot crack": "weld hot crack",
    "weld hot cracks": "weld hot crack",
    "hot cracking": "weld hot crack",
    "hot crack defect": "weld hot crack",
    "hot crack defects": "weld hot crack",
    "cold crack": "weld cold crack",
    "cold cracks": "weld cold crack",
    "weld cold crack": "weld cold crack",
    "weld cold cracks": "weld cold crack",
    "cold cracking": "weld cold crack",
    "cold crack defect": "weld cold crack",
    "cold crack defects": "weld cold crack",

    # Ultrasonic Testing (UT) for Weld Inspection
    "ut": "ultrasonic testing",
    "ultrasonic testing": "ultrasonic testing",
    "ultrasonic test": "ultrasonic testing",
    "ultrasonic inspection": "ultrasonic testing",
    "ut inspection": "ultrasonic testing",
    "ut test": "ultrasonic testing",
    "ut testing": "ultrasonic testing",
    "ultrasonic weld inspection": "ultrasonic testing",
    "ultrasonic weld testing": "ultrasonic testing",
    "ultrasonic weld test": "ultrasonic testing",
    "ultrasonic weld": "ultrasonic testing",

    # Radiographic Testing (RT) for Weld Inspection
    "rt": "radiographic testing",
    "radiographic testing": "radiographic testing",
    "radiographic test": "radiographic testing",
    "radiographic inspection": "radiographic testing",
    "rt inspection": "radiographic testing",
    "rt test": "radiographic testing",
    "rt testing": "radiographic testing",
    "radiographic weld inspection": "radiographic testing",
    "radiographic weld testing": "radiographic testing",
    "radiographic weld test": "radiographic testing",
    "radiographic weld": "radiographic testing",
    "x-ray inspection": "radiographic testing",
    "x-ray test": "radiographic testing",
    "x-ray testing": "radiographic testing",
    "x-ray weld inspection": "radiographic testing",
    "x-ray weld testing": "radiographic testing",
    "x-ray weld test": "radiographic testing",
    "x-ray weld": "radiographic testing",

    # Magnetic Particle Testing (MT) for Surface Crack Detection
    "mt": "magnetic particle testing",
    "magnetic particle testing": "magnetic particle testing",
    "magnetic particle test": "magnetic particle testing",
    "magnetic particle inspection": "magnetic particle testing",
    "mt inspection": "magnetic particle testing",
    "mt test": "magnetic particle testing",
    "mt testing": "magnetic particle testing",
    "magnetic particle weld inspection": "magnetic particle testing",
    "magnetic particle weld testing": "magnetic particle testing",
    "magnetic particle weld test": "magnetic particle testing",
    "magnetic particle weld": "magnetic particle testing",
    "mag particle testing": "magnetic particle testing",
    "mag particle test": "magnetic particle testing",
    "mag particle inspection": "magnetic particle testing",
    "mag particle weld inspection": "magnetic particle testing",
    "mag particle weld testing": "magnetic particle testing",
    "mag particle weld test": "magnetic particle testing",
    "mag particle weld": "magnetic particle testing",

    # Liquid Penetrant Testing (PT) for Non-Magnetic Materials
    "pt": "liquid penetrant testing",
    "liquid penetrant testing": "liquid penetrant testing",
    "liquid penetrant test": "liquid penetrant testing",
    "liquid penetrant inspection": "liquid penetrant testing",
    "pt inspection": "liquid penetrant testing",
    "pt test": "liquid penetrant testing",
    "pt testing": "liquid penetrant testing",
    "penetrant testing": "liquid penetrant testing",
    "penetrant test": "liquid penetrant testing",
    "penetrant inspection": "liquid penetrant testing",
    "penetrant weld inspection": "liquid penetrant testing",
    "penetrant weld testing": "liquid penetrant testing",
    "penetrant weld test": "liquid penetrant testing",
    "penetrant weld": "liquid penetrant testing",
    "dye penetrant testing": "liquid penetrant testing",
    "dye penetrant test": "liquid penetrant testing",
    "dye penetrant inspection": "liquid penetrant testing",
    "dye penetrant weld inspection": "liquid penetrant testing",
    "dye penetrant weld testing": "liquid penetrant testing",
    "dye penetrant weld test": "liquid penetrant testing",
    "dye penetrant weld": "liquid penetrant testing",

    # Visual Inspection (VT) and Acceptance Criteria
    "vt": "visual inspection",
    "visual inspection": "visual inspection",
    "visual test": "visual inspection",
    "visual testing": "visual inspection",
    "visual weld inspection": "visual inspection",
    "visual weld testing": "visual inspection",
    "visual weld test": "visual inspection",
    "visual weld": "visual inspection",
    "vt inspection": "visual inspection",
    "vt test": "visual inspection",
    "vt testing": "visual inspection",
    "acceptance criteria": "weld acceptance criteria",
    "weld acceptance criteria": "weld acceptance criteria",
    "acceptance": "weld acceptance criteria",
    "weld acceptance": "weld acceptance criteria",
    "acceptance requirement": "weld acceptance criteria",
    "acceptance requirements": "weld acceptance criteria",
    "weld acceptance requirement": "weld acceptance criteria",
    "weld acceptance requirements": "weld acceptance criteria",

    # API 1104 Pipeline Welding Standard
    "api 1104": "api 1104 pipeline welding standard",
    "api1104": "api 1104 pipeline welding standard",
    "api 1104 welding": "api 1104 pipeline welding standard",
    "api 1104 standard": "api 1104 pipeline welding standard",
    "api 1104 pipeline": "api 1104 pipeline welding standard",
    "api 1104 pipeline welding": "api 1104 pipeline welding standard",
    "api1104 pipeline welding": "api 1104 pipeline welding standard",
    "api1104 welding": "api 1104 pipeline welding standard",
    "api1104 standard": "api 1104 pipeline welding standard",
    "api1104 pipeline": "api 1104 pipeline welding standard",

    # AWS D1.1 Structural Welding Code - Steel
    "aws d1.1": "aws d1.1 structural welding code steel",
    "aws d1.1 code": "aws d1.1 structural welding code steel",
    "aws d1.1 steel": "aws d1.1 structural welding code steel",
    "aws d1.1 welding": "aws d1.1 structural welding code steel",
    "aws d1.1 structural welding": "aws d1.1 structural welding code steel",
    "aws d1.1 structural welding code": "aws d1.1 structural welding code steel",
    "aws d1.1 structural code": "aws d1.1 structural welding code steel",
    "aws d1.1 structural": "aws d1.1 structural welding code steel",
    "aws d1.1 structural welding code steel": "aws d1.1 structural welding code steel",
    "d1.1": "aws d1.1 structural welding code steel",
    "d1.1 code": "aws d1.1 structural welding code steel",
    "d1.1 steel": "aws d1.1 structural welding code steel",
    "d1.1 welding": "aws d1.1 structural welding code steel",
    "d1.1 structural welding": "aws d1.1 structural welding code steel",
    "d1.1 structural welding code": "aws d1.1 structural welding code steel",
    "d1.1 structural code": "aws d1.1 structural welding code steel",
    "d1.1 structural": "aws d1.1 structural welding code steel",
    "d1.1 structural welding code steel": "aws d1.1 structural welding code steel",

    # NACE MR0175/ISO 15156 Sour Service Welding Requirements
    "nace mr0175": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 welding": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 standard": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 sour service": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 sour service welding": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 iso 15156": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 iso 15156 welding": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 iso 15156 standard": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 iso 15156 sour service": "nace mr0175 iso 15156 sour service welding requirements",
    "nace mr0175 iso 15156 sour service welding": "nace mr0175 iso 15156 sour service welding requirements",
    "mr0175": "nace mr0175 iso 15156 sour service welding requirements",
    "mr0175 welding": "nace mr0175 iso 15156 sour service welding requirements",
    "mr0175 standard": "nace mr0175 iso 15156 sour service welding requirements",
    "mr0175 sour service": "nace mr0175 iso 15156 sour service welding requirements",
    "mr0175 sour service welding": "nace mr0175 iso 15156 sour service welding requirements",
    "iso 15156": "nace mr0175 iso 15156 sour service welding requirements",
    "iso 15156 welding": "nace mr0175 iso 15156 sour service welding requirements",
    "iso 15156 standard": "nace mr0175 iso 15156 sour service welding requirements",
    "iso 15156 sour service": "nace mr0175 iso 15156 sour service welding requirements",
    "iso 15156 sour service welding": "nace mr0175 iso 15156 sour service welding requirements",

    # Repair Welding Procedures and Limitations
    "repair welding": "repair welding procedures",
    "repair weld": "repair welding procedures",
    "repair welding procedure": "repair welding procedures",
    "repair welding procedures": "repair welding procedures",
    "repair weld procedure": "repair welding procedures",
    "repair weld procedures": "repair welding procedures",
    "weld repair": "repair welding procedures",
    "weld repair procedure": "repair welding procedures",
    "weld repair procedures": "repair welding procedures",
    "repair welding limitations": "repair welding limitations",
    "repair weld limitations": "repair welding limitations",
    "weld repair limitations": "repair welding limitations",
    "repair limitations": "repair welding limitations",
    "repair procedure limitations": "repair welding limitations",
    "repair procedures limitations": "repair welding limitations",
    "repair welding procedure limitations": "repair welding limitations",
    "repair welding procedures limitations": "repair welding limitations",

    # Weld Documentation and Traceability
    "weld documentation": "weld documentation and traceability",
    "welding documentation": "weld documentation and traceability",
    "weld docs": "weld documentation and traceability",
    "welding docs": "weld documentation and traceability",
    "weld records": "weld documentation and traceability",
    "welding records": "weld documentation and traceability",
    "weld traceability": "weld documentation and traceability",
    "welding traceability": "weld documentation and traceability",
    "weld document": "weld documentation and traceability",
    "welding document": "weld documentation and traceability",
    "weld trace": "weld documentation and traceability",
    "welding trace": "weld documentation and traceability",
    "weld documentation traceability": "weld documentation and traceability",
    "welding documentation traceability": "weld documentation and traceability",
    "weld doc traceability": "weld documentation and traceability",
    "welding doc traceability": "weld documentation and traceability",
    "weld docs traceability": "weld documentation and traceability",
    "welding docs traceability": "weld documentation and traceability",
    "weld record traceability": "weld documentation and traceability",
    "welding record traceability": "weld documentation and traceability",
    "weld records traceability": "weld documentation and traceability",
    "welding records traceability": "weld documentation and traceability",

    # Misspellings and common variants
    "sheilded metal arc welding": "shielded metal arc welding",
    "sheilded metal arc": "shielded metal arc welding",
    "sheilded metal arc weld": "shielded metal arc welding",
    "sheilded metal arc welds": "shielded metal arc welding",
    "stickwelding": "shielded metal arc welding",
    "migwelding": "gas metal arc welding",
    "migweld": "gas metal arc welding",
    "gtawwelding": "gas tungsten arc welding",
    "tigwelding": "gas tungsten arc welding",
    "tigweld": "gas tungsten arc welding",
    "welding porosity": "weld porosity",
    "welding lack of fusion": "weld lack of fusion",
    "welding incomplete penetration": "weld incomplete penetration",
    "welding crack": "weld crack",
    "welding cracks": "weld crack",
    "welding hot crack": "weld hot crack",
    "welding cold crack": "weld cold crack",
    "ultrasonic weld": "ultrasonic testing",
    "radiographic weld": "radiographic testing",
    "magnetic particle weld": "magnetic particle testing",
    "liquid penetrant weld": "liquid penetrant testing",
    "visual weld": "visual inspection",
    "repairwelding": "repair welding procedures",
    "repairweld": "repair welding procedures",
    "weldrepair": "repair welding procedures",
    "weldingrepair": "repair welding procedures",
    "welddocumentation": "weld documentation and traceability",
    "weldingdocumentation": "weld documentation and traceability",
    "weldtraceability": "weld documentation and traceability",
    "weldingtraceability": "weld documentation and traceability",

    # Additional synonyms and related terms
    "arc": "shielded metal arc welding",
    "mig arc": "gas metal arc welding",
    "tig arc": "gas tungsten arc welding",
    "manual welding": "shielded metal arc welding",
    "manual stick welding": "shielded metal arc welding",
    "manual arc stick welding": "shielded metal arc welding",
    "manual arc stick": "shielded metal arc welding",
    "manual arc weld": "shielded metal arc welding",
    "manual arc welding": "shielded metal arc welding",
    "manual arc": "shielded metal arc welding",
    "manual stick": "shielded metal arc welding",
    "manual weld": "shielded metal arc welding",
    "manual welding process": "shielded metal arc welding",
    "manual welding selection": "smaw process selection",
    "manual welding parameters": "smaw process parameters",
    "manual welding electrode": "smaw electrode",
    "manual welding filler": "smaw electrode",
    "manual welding rod": "smaw electrode",
    "manual welding wire": "smaw electrode",
    "manual welding filler rod": "smaw electrode",
    "manual welding filler wire": "smaw electrode",
    "manual welding filler metal": "smaw electrode",
    "manual welding filler metal selection": "smaw electrode",
    "manual welding filler metal aws classification": "smaw electrode",
    "manual welding filler aws classification": "smaw electrode",
    "manual welding filler aws": "smaw electrode",
    "manual welding filler class": "smaw electrode",
    "manual welding filler classification": "smaw electrode",
    "manual welding filler rod aws classification": "smaw electrode",
    "manual welding filler wire aws classification": "smaw electrode",

    # More synonyms for filler metal selection
    "electrode selection": "filler metal selection",
    "electrode": "filler metal selection",
    "weld electrode": "filler metal selection",
    "welding electrode": "filler metal selection",
    "weld rod": "filler metal selection",
    "welding rod": "filler metal selection",
    "weld wire": "filler metal selection",
    "welding wire": "filler metal selection",

    # More synonyms for weld defects
    "defect": "weld defect",
    "defects": "weld defect",
    "weld defect": "weld defect",
    "weld defects": "weld defect",
    "welding defect": "weld defect",
    "welding defects": "weld defect",
    "weld flaw": "weld defect",
    "weld flaws": "weld defect",
    "welding flaw": "weld defect",
    "welding flaws": "weld defect",

    # More synonyms for testing and inspection
    "nondestructive testing": "weld inspection",
    "nondestructive test": "weld inspection",
    "nondestructive inspection": "weld inspection",
    "ndt": "weld inspection",
    "ndt inspection": "weld inspection",
    "ndt test": "weld inspection",
    "ndt testing": "weld inspection",
    "weld inspection": "weld inspection",
    "welding inspection": "weld inspection",
    "inspection": "weld inspection",
    "weld test": "weld inspection",
    "welding test": "weld inspection",
    "weld testing": "weld inspection",
    "welding testing": "weld inspection",

    # More synonyms for standards
    "api standard": "api 1104 pipeline welding standard",
    "aws standard": "aws d1.1 structural welding code steel",
    "nace standard": "nace mr0175 iso 15156 sour service welding requirements",
    "iso standard": "nace mr0175 iso 15156 sour service welding requirements",
    "asme standard": "welding procedure specification asme section ix",
    "asme ix standard": "welding procedure specification asme section ix",
    "asme section ix standard": "welding procedure specification asme section ix",

    # More synonyms for qualification
    "qualification": "welder performance qualification",
    "performance qualification test": "welder performance qualification",
    "welder qualification test": "welder performance qualification",
    "welder performance qualification test": "welder performance qualification",
    "welder performance qualification testing": "welder performance qualification",
    "welder qualification testing": "welder performance qualification",
    "welder performance testing": "welder performance qualification",
    "welder testing": "welder performance qualification",
    "welder performance qualification asme ix test": "welder performance qualification asme section ix",
    "welder performance qualification asme section ix test": "welder performance qualification asme section ix",
    "welder performance qualification asme ix testing": "welder performance qualification asme section ix",
    "welder performance qualification asme section ix testing": "welder performance qualification asme section ix",
    "welder qualification asme ix test": "welder performance qualification asme section ix",
    "welder qualification asme section ix test": "welder performance qualification asme section ix",
    "welder qualification asme ix testing": "welder performance qualification asme section ix",
    "welder qualification asme section ix testing": "welder performance qualification asme section ix",

    # More synonyms for temperature requirements
    "temperature requirements": "preheat and interpass temperature requirements",
    "temperature requirement": "preheat and interpass temperature requirements",
    "weld temperature requirements": "preheat and interpass temperature requirements",
    "weld temperature requirement": "preheat and interpass temperature requirements",
    "weld preheat requirements": "preheat temperature requirements",
    "weld preheat requirement": "preheat temperature requirements",
    "weld interpass requirements": "interpass temperature requirements",
    "weld interpass requirement": "interpass temperature requirements",
    "weld preheat and interpass requirements": "preheat and interpass temperature requirements",
    "weld preheat and interpass temperature requirements": "preheat and interpass temperature requirements",

    # More synonyms for heat treatment
    "heat treatment": "post-weld heat treatment",
    "heat treatment requirements": "post-weld heat treatment requirements",
    "heat treatment requirement": "post-weld heat treatment requirements",
    "weld heat treatment": "post-weld heat treatment",
    "weld heat treatment requirements": "post-weld heat treatment requirements",
    "weld heat treatment requirement": "post-weld heat treatment requirements",
    "welding heat treatment": "post-weld heat treatment",
    "welding heat treatment requirements": "post-weld heat treatment requirements",
    "welding heat treatment requirement": "post-weld heat treatment requirements",

    # More synonyms for documentation and traceability
    "documentation": "weld documentation and traceability",
    "documentation and traceability": "weld documentation and traceability",
    "traceability": "weld documentation and traceability",
    "weld trace": "weld documentation and traceability",
    "welding trace": "weld documentation and traceability",
    "documentation traceability": "weld documentation and traceability",
    "doc traceability": "weld documentation and traceability",
    "docs traceability": "weld documentation and traceability",
    "record traceability": "weld documentation and traceability",
    "records traceability": "weld documentation and traceability",

    # More synonyms for standards
    "pipeline standard": "api 1104 pipeline welding standard",
    "structural welding code": "aws d1.1 structural welding code steel",
    "structural code": "aws d1.1 structural welding code steel",
    "structural welding code steel": "aws d1.1 structural welding code steel",
    "sour service standard": "nace mr0175 iso 15156 sour service welding requirements",
    "sour service welding standard": "nace mr0175 iso 15156 sour service welding requirements",

    # More synonyms for repair welding
    "repair": "repair welding procedures",
    "repair procedure": "repair welding procedures",
    "repair procedures": "repair welding procedures",
    "repair weld procedure": "repair welding procedures",
    "repair weld procedures": "repair welding procedures",
    "repair welding limitation": "repair welding limitations",
    "repair weld limitation": "repair welding limitations",
    "weld repair limitation": "repair welding limitations",
    "repair limitation": "repair welding limitations",
    "repair procedure limitation": "repair welding limitations",
    "repair procedures limitation": "repair welding limitations",
    "repair welding procedure limitation": "repair welding limitations",
    "repair welding procedures limitation": "repair welding limitations",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list[str]:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)