import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "RAIL06 Engineering Team"
SEMANTIC_MAP_ENGINE = "RAIL06_rolling_stock_maintenance"

SEMANTIC_MAP = {
    # Locomotive Prime Mover Overhaul Cycles
    "prime mover": "locomotive_prime_mover",
    "locomotive engine": "locomotive_prime_mover",
    "diesel engine": "locomotive_prime_mover",
    "prime mover overhaul": "prime_mover_overhaul_cycle",
    "engine overhaul": "prime_mover_overhaul_cycle",
    "overhaul cycle": "prime_mover_overhaul_cycle",
    "overhaul interval": "prime_mover_overhaul_cycle",
    "overhaul schedule": "prime_mover_overhaul_cycle",
    "engine rebuild": "prime_mover_overhaul_cycle",
    "prime mover rebuild": "prime_mover_overhaul_cycle",
    "prime mover maintenance": "prime_mover_overhaul_cycle",
    "engine maintenance": "prime_mover_overhaul_cycle",
    "locomotive overhaul": "prime_mover_overhaul_cycle",
    "locomotive rebuild": "prime_mover_overhaul_cycle",
    "prime mover cycle": "prime_mover_overhaul_cycle",
    "engine cycle": "prime_mover_overhaul_cycle",
    "overhaul": "prime_mover_overhaul_cycle",
    "rebuild": "prime_mover_overhaul_cycle",
    "pm overhaul": "prime_mover_overhaul_cycle",
    "pm cycle": "prime_mover_overhaul_cycle",
    "prime mover interval": "prime_mover_overhaul_cycle",
    "prime mover schedule": "prime_mover_overhaul_cycle",
    "prime mover service": "prime_mover_overhaul_cycle",
    "engine service": "prime_mover_overhaul_cycle",
    "locomotive service": "prime_mover_overhaul_cycle",
    "prime mover inspection": "prime_mover_overhaul_cycle",
    "engine inspection": "prime_mover_overhaul_cycle",
    "locomotive inspection": "prime_mover_overhaul_cycle",
    "prime mover replacement": "prime_mover_overhaul_cycle",
    "engine replacement": "prime_mover_overhaul_cycle",
    "locomotive replacement": "prime_mover_overhaul_cycle",

    # Wheel Impact Load Detector (WILD) Response and Wheel Condemning Limits
    "wild": "wheel_impact_load_detector",
    "wheel impact load detector": "wheel_impact_load_detector",
    "wheel impact detector": "wheel_impact_load_detector",
    "wheel impact": "wheel_impact_load_detector",
    "impact load detector": "wheel_impact_load_detector",
    "wheel load detector": "wheel_impact_load_detector",
    "wheel impact response": "wild_response",
    "wild response": "wild_response",
    "wheel condemning limit": "wheel_condemning_limit",
    "wheel condemn limit": "wheel_condemning_limit",
    "condemning limit": "wheel_condemning_limit",
    "condemn limit": "wheel_condemning_limit",
    "wheel defect": "wheel_condemning_limit",
    "wheel defect limit": "wheel_condemning_limit",
    "wheel threshold": "wheel_condemning_limit",
    "wheel rejection limit": "wheel_condemning_limit",
    "wheel removal limit": "wheel_condemning_limit",
    "wheel removal criteria": "wheel_condemning_limit",
    "wheel condemn criteria": "wheel_condemning_limit",
    "wheel impact threshold": "wheel_condemning_limit",
    "wheel impact criteria": "wheel_condemning_limit",
    "wheel condemn": "wheel_condemning_limit",
    "wheel removal": "wheel_condemning_limit",
    "wheel replacement": "wheel_condemning_limit",
    "wheel discard": "wheel_condemning_limit",
    "wheel out-of-round": "wheel_condemning_limit",
    "wheel flat": "wheel_condemning_limit",
    "wheel shelling": "wheel_condemning_limit",
    "wheel spalling": "wheel_condemning_limit",
    "wheel crack": "wheel_condemning_limit",
    "wheel fracture": "wheel_condemning_limit",
    "wheel defect detection": "wheel_condemning_limit",
    "wheel defect response": "wheel_condemning_limit",
    "wheel defect removal": "wheel_condemning_limit",
    "wheel defect replacement": "wheel_condemning_limit",
    "wheel defect condemn": "wheel_condemning_limit",
    "wheel defect discard": "wheel_condemning_limit",
    "wheel defect threshold": "wheel_condemning_limit",

    # Air Brake Testing Requirements - Class I/IA/III Freight Car Inspections
    "air brake": "air_brake_system",
    "air brake test": "air_brake_testing",
    "air brake testing": "air_brake_testing",
    "brake test": "air_brake_testing",
    "brake testing": "air_brake_testing",
    "class i inspection": "class_i_freight_car_inspection",
    "class ia inspection": "class_ia_freight_car_inspection",
    "class iii inspection": "class_iii_freight_car_inspection",
    "class 1 inspection": "class_i_freight_car_inspection",
    "class 1a inspection": "class_ia_freight_car_inspection",
    "class 3 inspection": "class_iii_freight_car_inspection",
    "freight car inspection": "freight_car_inspection",
    "freight car test": "freight_car_inspection",
    "freight car brake test": "air_brake_testing",
    "freight car brake testing": "air_brake_testing",
    "air brake inspection": "air_brake_testing",
    "brake inspection": "air_brake_testing",
    "class i brake test": "air_brake_testing",
    "class ia brake test": "air_brake_testing",
    "class iii brake test": "air_brake_testing",
    "class i brake testing": "air_brake_testing",
    "class ia brake testing": "air_brake_testing",
    "class iii brake testing": "air_brake_testing",
    "class i air brake test": "air_brake_testing",
    "class ia air brake test": "air_brake_testing",
    "class iii air brake test": "air_brake_testing",
    "class i air brake testing": "air_brake_testing",
    "class ia air brake testing": "air_brake_testing",
    "class iii air brake testing": "air_brake_testing",
    "freight car air brake test": "air_brake_testing",
    "freight car air brake testing": "air_brake_testing",
    "freight car air brake inspection": "air_brake_testing",
    "freight car brake inspection": "air_brake_testing",
    "freight car inspection requirements": "freight_car_inspection",
    "freight car testing requirements": "freight_car_inspection",
    "freight car brake requirements": "air_brake_testing",
    "air brake requirements": "air_brake_testing",
    "brake requirements": "air_brake_testing",
    "air brake test requirements": "air_brake_testing",
    "brake test requirements": "air_brake_testing",
    "air brake testing requirements": "air_brake_testing",
    "brake testing requirements": "air_brake_testing",
    "class i requirements": "class_i_freight_car_inspection",
    "class ia requirements": "class_ia_freight_car_inspection",
    "class iii requirements": "class_iii_freight_car_inspection",
    "class 1 requirements": "class_i_freight_car_inspection",
    "class 1a requirements": "class_ia_freight_car_inspection",
    "class 3 requirements": "class_iii_freight_car_inspection",

    # Journal Bearing Hot Box Detection and Failure Prevention
    "journal bearing": "journal_bearing",
    "hot box": "journal_bearing_hot_box",
    "hotbox": "journal_bearing_hot_box",
    "journal bearing hot box": "journal_bearing_hot_box",
    "journal bearing hotbox": "journal_bearing_hot_box",
    "hot box detection": "journal_bearing_hot_box_detection",
    "hotbox detection": "journal_bearing_hot_box_detection",
    "journal bearing hot box detection": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detection": "journal_bearing_hot_box_detection",
    "hot box detector": "journal_bearing_hot_box_detection",
    "hotbox detector": "journal_bearing_hot_box_detection",
    "journal bearing hot box detector": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detector": "journal_bearing_hot_box_detection",
    "hot box failure": "journal_bearing_failure",
    "hotbox failure": "journal_bearing_failure",
    "journal bearing failure": "journal_bearing_failure",
    "journal bearing hot box failure": "journal_bearing_failure",
    "journal bearing hotbox failure": "journal_bearing_failure",
    "hot box prevention": "journal_bearing_failure_prevention",
    "hotbox prevention": "journal_bearing_failure_prevention",
    "journal bearing hot box prevention": "journal_bearing_failure_prevention",
    "journal bearing hotbox prevention": "journal_bearing_failure_prevention",
    "journal bearing prevention": "journal_bearing_failure_prevention",
    "journal bearing failure prevention": "journal_bearing_failure_prevention",
    "hot box prevention methods": "journal_bearing_failure_prevention",
    "hotbox prevention methods": "journal_bearing_failure_prevention",
    "journal bearing hot box prevention methods": "journal_bearing_failure_prevention",
    "journal bearing hotbox prevention methods": "journal_bearing_failure_prevention",
    "hot box detection methods": "journal_bearing_hot_box_detection",
    "hotbox detection methods": "journal_bearing_hot_box_detection",
    "journal bearing hot box detection methods": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detection methods": "journal_bearing_hot_box_detection",
    "hot box detector methods": "journal_bearing_hot_box_detection",
    "hotbox detector methods": "journal_bearing_hot_box_detection",
    "journal bearing hot box detector methods": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detector methods": "journal_bearing_hot_box_detection",

    # Coupler Knuckle Inspection and Replacement Criteria
    "coupler knuckle": "coupler_knuckle",
    "knuckle": "coupler_knuckle",
    "coupler knuckle inspection": "coupler_knuckle_inspection",
    "knuckle inspection": "coupler_knuckle_inspection",
    "coupler knuckle replacement": "coupler_knuckle_replacement",
    "knuckle replacement": "coupler_knuckle_replacement",
    "coupler knuckle criteria": "coupler_knuckle_replacement_criteria",
    "knuckle criteria": "coupler_knuckle_replacement_criteria",
    "coupler knuckle replacement criteria": "coupler_knuckle_replacement_criteria",
    "knuckle replacement criteria": "coupler_knuckle_replacement_criteria",
    "coupler knuckle condemn": "coupler_knuckle_replacement_criteria",
    "knuckle condemn": "coupler_knuckle_replacement_criteria",
    "coupler knuckle discard": "coupler_knuckle_replacement_criteria",
    "knuckle discard": "coupler_knuckle_replacement_criteria",
    "coupler knuckle removal": "coupler_knuckle_replacement_criteria",
    "knuckle removal": "coupler_knuckle_replacement_criteria",
    "coupler knuckle defect": "coupler_knuckle_replacement_criteria",
    "knuckle defect": "coupler_knuckle_replacement_criteria",
    "coupler knuckle defect inspection": "coupler_knuckle_inspection",
    "knuckle defect inspection": "coupler_knuckle_inspection",
    "coupler knuckle defect replacement": "coupler_knuckle_replacement",
    "knuckle defect replacement": "coupler_knuckle_replacement",
    "coupler knuckle defect criteria": "coupler_knuckle_replacement_criteria",
    "knuckle defect criteria": "coupler_knuckle_replacement_criteria",
    "coupler knuckle failure": "coupler_knuckle_replacement_criteria",
    "knuckle failure": "coupler_knuckle_replacement_criteria",
    "coupler knuckle failure inspection": "coupler_knuckle_inspection",
    "knuckle failure inspection": "coupler_knuckle_inspection",
    "coupler knuckle failure replacement": "coupler_knuckle_replacement",
    "knuckle failure replacement": "coupler_knuckle_replacement",

    # Tank Car Qualification - DOT-111 vs DOT-117 Standards
    "tank car": "tank_car",
    "dot-111": "dot_111_tank_car",
    "dot 111": "dot_111_tank_car",
    "dot111": "dot_111_tank_car",
    "dot-117": "dot_117_tank_car",
    "dot 117": "dot_117_tank_car",
    "dot117": "dot_117_tank_car",
    "tank car qualification": "tank_car_qualification",
    "tank car qualification criteria": "tank_car_qualification",
    "dot-111 qualification": "dot_111_tank_car_qualification",
    "dot 111 qualification": "dot_111_tank_car_qualification",
    "dot111 qualification": "dot_111_tank_car_qualification",
    "dot-117 qualification": "dot_117_tank_car_qualification",
    "dot 117 qualification": "dot_117_tank_car_qualification",
    "dot117 qualification": "dot_117_tank_car_qualification",
    "tank car standards": "tank_car_standard",
    "tank car standard": "tank_car_standard",
    "dot-111 standard": "dot_111_tank_car_standard",
    "dot 111 standard": "dot_111_tank_car_standard",
    "dot111 standard": "dot_111_tank_car_standard",
    "dot-117 standard": "dot_117_tank_car_standard",
    "dot 117 standard": "dot_117_tank_car_standard",
    "dot117 standard": "dot_117_tank_car_standard",
    "tank car inspection": "tank_car_inspection",
    "tank car testing": "tank_car_testing",
    "tank car test": "tank_car_testing",
    "tank car qualification test": "tank_car_qualification",
    "tank car qualification testing": "tank_car_qualification",
    "tank car qualification inspection": "tank_car_qualification",
    "dot-111 inspection": "dot_111_tank_car_inspection",
    "dot 111 inspection": "dot_111_tank_car_inspection",
    "dot111 inspection": "dot_111_tank_car_inspection",
    "dot-117 inspection": "dot_117_tank_car_inspection",
    "dot 117 inspection": "dot_117_tank_car_inspection",
    "dot117 inspection": "dot_117_tank_car_inspection",
    "dot-111 testing": "dot_111_tank_car_testing",
    "dot 111 testing": "dot_111_tank_car_testing",
    "dot111 testing": "dot_111_tank_car_testing",
    "dot-117 testing": "dot_117_tank_car_testing",
    "dot 117 testing": "dot_117_tank_car_testing",
    "dot117 testing": "dot_117_tank_car_testing",

    # Traction Motor Inspection and Commutator Maintenance
    "traction motor": "traction_motor",
    "traction motor inspection": "traction_motor_inspection",
    "traction motor maintenance": "traction_motor_maintenance",
    "traction motor commutator": "traction_motor_commutator",
    "commutator": "traction_motor_commutator",
    "commutator inspection": "traction_motor_commutator_inspection",
    "commutator maintenance": "traction_motor_commutator_maintenance",
    "traction motor commutator inspection": "traction_motor_commutator_inspection",
    "traction motor commutator maintenance": "traction_motor_commutator_maintenance",
    "traction motor replacement": "traction_motor_replacement",
    "traction motor repair": "traction_motor_maintenance",
    "traction motor cleaning": "traction_motor_maintenance",
    "traction motor testing": "traction_motor_testing",
    "traction motor test": "traction_motor_testing",
    "traction motor failure": "traction_motor_failure",
    "traction motor failure inspection": "traction_motor_inspection",
    "traction motor failure maintenance": "traction_motor_maintenance",
    "traction motor failure replacement": "traction_motor_replacement",
    "traction motor failure repair": "traction_motor_maintenance",
    "traction motor failure cleaning": "traction_motor_maintenance",
    "traction motor failure testing": "traction_motor_testing",
    "traction motor failure test": "traction_motor_testing",

    # Condition-Based Maintenance Using Vibration Analysis and Oil Sampling
    "condition-based maintenance": "condition_based_maintenance",
    "cbm": "condition_based_maintenance",
    "vibration analysis": "vibration_analysis",
    "vibration monitoring": "vibration_analysis",
    "vibration test": "vibration_analysis",
    "vibration testing": "vibration_analysis",
    "vibration inspection": "vibration_analysis",
    "vibration": "vibration_analysis",
    "oil sampling": "oil_sampling",
    "oil sample": "oil_sampling",
    "oil analysis": "oil_sampling",
    "oil monitoring": "oil_sampling",
    "oil test": "oil_sampling",
    "oil testing": "oil_sampling",
    "oil inspection": "oil_sampling",
    "oil": "oil_sampling",
    "condition-based maintenance vibration": "condition_based_maintenance",
    "condition-based maintenance oil": "condition_based_maintenance",
    "cbm vibration": "condition_based_maintenance",
    "cbm oil": "condition_based_maintenance",
    "cbm vibration analysis": "condition_based_maintenance",
    "cbm oil sampling": "condition_based_maintenance",
    "cbm oil analysis": "condition_based_maintenance",
    "cbm oil monitoring": "condition_based_maintenance",
    "cbm oil test": "condition_based_maintenance",
    "cbm oil testing": "condition_based_maintenance",
    "cbm oil inspection": "condition_based_maintenance",
    "cbm vibration test": "condition_based_maintenance",
    "cbm vibration testing": "condition_based_maintenance",
    "cbm vibration inspection": "condition_based_maintenance",
    "cbm vibration monitoring": "condition_based_maintenance",

    # Locomotive Fuel System Maintenance - Injector Testing and Cleaning
    "fuel system": "locomotive_fuel_system",
    "locomotive fuel system": "locomotive_fuel_system",
    "fuel injector": "fuel_injector",
    "injector": "fuel_injector",
    "fuel injector test": "fuel_injector_testing",
    "injector test": "fuel_injector_testing",
    "fuel injector testing": "fuel_injector_testing",
    "injector testing": "fuel_injector_testing",
    "fuel injector inspection": "fuel_injector_inspection",
    "injector inspection": "fuel_injector_inspection",
    "fuel injector cleaning": "fuel_injector_cleaning",
    "injector cleaning": "fuel_injector_cleaning",
    "fuel injector maintenance": "fuel_injector_maintenance",
    "injector maintenance": "fuel_injector_maintenance",
    "fuel injector replacement": "fuel_injector_replacement",
    "injector replacement": "fuel_injector_replacement",
    "fuel injector repair": "fuel_injector_maintenance",
    "injector repair": "fuel_injector_maintenance",
    "fuel injector failure": "fuel_injector_failure",
    "injector failure": "fuel_injector_failure",
    "fuel injector failure inspection": "fuel_injector_inspection",
    "injector failure inspection": "fuel_injector_inspection",
    "fuel injector failure testing": "fuel_injector_testing",
    "injector failure testing": "fuel_injector_testing",
    "fuel injector failure cleaning": "fuel_injector_cleaning",
    "injector failure cleaning": "fuel_injector_cleaning",
    "fuel injector failure maintenance": "fuel_injector_maintenance",
    "injector failure maintenance": "fuel_injector_maintenance",
    "fuel injector failure replacement": "fuel_injector_replacement",
    "injector failure replacement": "fuel_injector_replacement",
    "fuel injector failure repair": "fuel_injector_maintenance",
    "injector failure repair": "fuel_injector_maintenance",

    # Locomotive Cooling System Maintenance - Radiator and Coolant Management
    "cooling system": "locomotive_cooling_system",
    "locomotive cooling system": "locomotive_cooling_system",
    "radiator": "locomotive_radiator",
    "radiator inspection": "locomotive_radiator_inspection",
    "radiator maintenance": "locomotive_radiator_maintenance",
    "radiator cleaning": "locomotive_radiator_cleaning",
    "radiator testing": "locomotive_radiator_testing",
    "radiator test": "locomotive_radiator_testing",
    "radiator replacement": "locomotive_radiator_replacement",
    "radiator repair": "locomotive_radiator_maintenance",
    "coolant": "locomotive_coolant",
    "coolant inspection": "locomotive_coolant_inspection",
    "coolant maintenance": "locomotive_coolant_maintenance",
    "coolant cleaning": "locomotive_coolant_cleaning",
    "coolant testing": "locomotive_coolant_testing",
    "coolant test": "locomotive_coolant_testing",
    "coolant replacement": "locomotive_coolant_replacement",
    "coolant repair": "locomotive_coolant_maintenance",
    "coolant management": "locomotive_coolant_management",
    "cooling system inspection": "locomotive_cooling_system_inspection",
    "cooling system maintenance": "locomotive_cooling_system_maintenance",
    "cooling system cleaning": "locomotive_cooling_system_cleaning",
    "cooling system testing": "locomotive_cooling_system_testing",
    "cooling system test": "locomotive_cooling_system_testing",
    "cooling system replacement": "locomotive_cooling_system_replacement",
    "cooling system repair": "locomotive_cooling_system_maintenance",
    "cooling system management": "locomotive_cooling_system_management",

    # Truck (Bogie) Frame Inspection and Crack Detection
    "truck frame": "bogie_frame",
    "bogie frame": "bogie_frame",
    "truck": "bogie_frame",
    "bogie": "bogie_frame",
    "truck frame inspection": "bogie_frame_inspection",
    "bogie frame inspection": "bogie_frame_inspection",
    "truck inspection": "bogie_frame_inspection",
    "bogie inspection": "bogie_frame_inspection",
    "truck frame crack": "bogie_frame_crack_detection",
    "bogie frame crack": "bogie_frame_crack_detection",
    "truck crack": "bogie_frame_crack_detection",
    "bogie crack": "bogie_frame_crack_detection",
    "truck frame crack detection": "bogie_frame_crack_detection",
    "bogie frame crack detection": "bogie_frame_crack_detection",
    "truck crack detection": "bogie_frame_crack_detection",
    "bogie crack detection": "bogie_frame_crack_detection",
    "truck frame failure": "bogie_frame_failure",
    "bogie frame failure": "bogie_frame_failure",
    "truck failure": "bogie_frame_failure",
    "bogie failure": "bogie_frame_failure",
    "truck frame repair": "bogie_frame_maintenance",
    "bogie frame repair": "bogie_frame_maintenance",
    "truck repair": "bogie_frame_maintenance",
    "bogie repair": "bogie_frame_maintenance",
    "truck frame replacement": "bogie_frame_replacement",
    "bogie frame replacement": "bogie_frame_replacement",
    "truck replacement": "bogie_frame_replacement",
    "bogie replacement": "bogie_frame_replacement",
    "truck frame maintenance": "bogie_frame_maintenance",
    "bogie frame maintenance": "bogie_frame_maintenance",
    "truck maintenance": "bogie_frame_maintenance",
    "bogie maintenance": "bogie_frame_maintenance",

    # Safety Appliance Inspection - Ladders, Handholds, and Sill Steps
    "safety appliance": "safety_appliance",
    "safety appliance inspection": "safety_appliance_inspection",
    "ladder": "ladder",
    "ladder inspection": "ladder_inspection",
    "ladder maintenance": "ladder_maintenance",
    "ladder repair": "ladder_maintenance",
    "ladder replacement": "ladder_replacement",
    "ladder failure": "ladder_failure",
    "ladder failure inspection": "ladder_inspection",
    "ladder failure maintenance": "ladder_maintenance",
    "ladder failure replacement": "ladder_replacement",
    "ladder failure repair": "ladder_maintenance",
    "handhold": "handhold",
    "handhold inspection": "handhold_inspection",
    "handhold maintenance": "handhold_maintenance",
    "handhold repair": "handhold_maintenance",
    "handhold replacement": "handhold_replacement",
    "handhold failure": "handhold_failure",
    "handhold failure inspection": "handhold_inspection",
    "handhold failure maintenance": "handhold_maintenance",
    "handhold failure replacement": "handhold_replacement",
    "handhold failure repair": "handhold_maintenance",
    "sill step": "sill_step",
    "sill step inspection": "sill_step_inspection",
    "sill step maintenance": "sill_step_maintenance",
    "sill step repair": "sill_step_maintenance",
    "sill step replacement": "sill_step_replacement",
    "sill step failure": "sill_step_failure",
    "sill step failure inspection": "sill_step_inspection",
    "sill step failure maintenance": "sill_step_maintenance",
    "sill step failure replacement": "sill_step_replacement",
    "sill step failure repair": "sill_step_maintenance",
    "safety appliance maintenance": "safety_appliance_maintenance",
    "safety appliance repair": "safety_appliance_maintenance",
    "safety appliance replacement": "safety_appliance_replacement",
    "safety appliance failure": "safety_appliance_failure",
    "safety appliance failure inspection": "safety_appliance_inspection",
    "safety appliance failure maintenance": "safety_appliance_maintenance",
    "safety appliance failure replacement": "safety_appliance_replacement",
    "safety appliance failure repair": "safety_appliance_maintenance",

    # Misspellings, abbreviations, and synonyms
    "prime mover overhall": "prime_mover_overhaul_cycle",
    "prime mover overhaull": "prime_mover_overhaul_cycle",
    "prime mover overhaul cycle": "prime_mover_overhaul_cycle",
    "prime mover overhaul cycles": "prime_mover_overhaul_cycle",
    "engine overhall": "prime_mover_overhaul_cycle",
    "engine overhaull": "prime_mover_overhaul_cycle",
    "engine overhaul cycle": "prime_mover_overhaul_cycle",
    "engine overhaul cycles": "prime_mover_overhaul_cycle",
    "overhall cycle": "prime_mover_overhaul_cycle",
    "overhaull cycle": "prime_mover_overhaul_cycle",
    "overhall interval": "prime_mover_overhaul_cycle",
    "overhaull interval": "prime_mover_overhaul_cycle",
    "overhall schedule": "prime_mover_overhaul_cycle",
    "overhaull schedule": "prime_mover_overhaul_cycle",
    "overhall": "prime_mover_overhaul_cycle",
    "overhaull": "prime_mover_overhaul_cycle",
    "rebuild cycle": "prime_mover_overhaul_cycle",
    "rebuild interval": "prime_mover_overhaul_cycle",
    "rebuild schedule": "prime_mover_overhaul_cycle",
    "rebuild maintenance": "prime_mover_overhaul_cycle",
    "rebuild inspection": "prime_mover_overhaul_cycle",
    "rebuild replacement": "prime_mover_overhaul_cycle",
    "rebuild service": "prime_mover_overhaul_cycle",
    "rebuild replacement": "prime_mover_overhaul_cycle",
    "rebuild": "prime_mover_overhaul_cycle",
    "pm overhall": "prime_mover_overhaul_cycle",
    "pm overhaull": "prime_mover_overhaul_cycle",
    "pm overhaul cycle": "prime_mover_overhaul_cycle",
    "pm overhaul cycles": "prime_mover_overhaul_cycle",
    "pm interval": "prime_mover_overhaul_cycle",
    "pm schedule": "prime_mover_overhaul_cycle",
    "pm service": "prime_mover_overhaul_cycle",
    "pm inspection": "prime_mover_overhaul_cycle",
    "pm replacement": "prime_mover_overhaul_cycle",

    # Misspellings and abbreviations for WILD and wheel limits
    "wheel impact load detctor": "wheel_impact_load_detector",
    "wheel impact load detecor": "wheel_impact_load_detector",
    "wheel impact load detetor": "wheel_impact_load_detector",
    "wheel impact load detctor response": "wild_response",
    "wheel impact load detecor response": "wild_response",
    "wheel impact load detetor response": "wild_response",
    "wheel condeming limit": "wheel_condemning_limit",
    "wheel condemning limt": "wheel_condemning_limit",
    "wheel condeming limt": "wheel_condemning_limit",
    "wheel condemm limit": "wheel_condemning_limit",
    "wheel condemmning limit": "wheel_condemning_limit",
    "wheel condemmning limt": "wheel_condemning_limit",
    "wheel condemm limit": "wheel_condemning_limit",
    "wheel condemmning limit": "wheel_condemning_limit",
    "wheel condemmning limt": "wheel_condemning_limit",
    "wheel condemm criteria": "wheel_condemning_limit",
    "wheel condemmning criteria": "wheel_condemning_limit",
    "wheel condemmning criteri": "wheel_condemning_limit",
    "wheel condemmning criteriia": "wheel_condemning_limit",
    "wheel condemning criteri": "wheel_condemning_limit",
    "wheel condemning criteriia": "wheel_condemning_limit",

    # Misspellings and abbreviations for air brake testing
    "air brake test req": "air_brake_testing",
    "air brake testing req": "air_brake_testing",
    "air brake req": "air_brake_testing",
    "brake test req": "air_brake_testing",
    "brake testing req": "air_brake_testing",
    "brake req": "air_brake_testing",
    "class i req": "class_i_freight_car_inspection",
    "class ia req": "class_ia_freight_car_inspection",
    "class iii req": "class_iii_freight_car_inspection",
    "class 1 req": "class_i_freight_car_inspection",
    "class 1a req": "class_ia_freight_car_inspection",
    "class 3 req": "class_iii_freight_car_inspection",
    "freight car req": "freight_car_inspection",
    "freight car test req": "freight_car_inspection",
    "freight car brake req": "air_brake_testing",
    "air brake test requirement": "air_brake_testing",
    "air brake testing requirement": "air_brake_testing",
    "brake test requirement": "air_brake_testing",
    "brake testing requirement": "air_brake_testing",
    "class i requirement": "class_i_freight_car_inspection",
    "class ia requirement": "class_ia_freight_car_inspection",
    "class iii requirement": "class_iii_freight_car_inspection",
    "class 1 requirement": "class_i_freight_car_inspection",
    "class 1a requirement": "class_ia_freight_car_inspection",
    "class 3 requirement": "class_iii_freight_car_inspection",
    "freight car requirement": "freight_car_inspection",
    "freight car test requirement": "freight_car_inspection",
    "freight car brake requirement": "air_brake_testing",

    # Misspellings and abbreviations for journal bearing hot box
    "journal bearing hotbox detction": "journal_bearing_hot_box_detection",
    "journal bearing hot box detction": "journal_bearing_hot_box_detection",
    "hotbox detction": "journal_bearing_hot_box_detection",
    "hot box detction": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detctor": "journal_bearing_hot_box_detection",
    "journal bearing hot box detctor": "journal_bearing_hot_box_detection",
    "hotbox detctor": "journal_bearing_hot_box_detection",
    "hot box detctor": "journal_bearing_hot_box_detection",
    "journal bearing hotbox failur": "journal_bearing_failure",
    "journal bearing hot box failur": "journal_bearing_failure",
    "hotbox failur": "journal_bearing_failure",
    "hot box failur": "journal_bearing_failure",
    "journal bearing hotbox preventon": "journal_bearing_failure_prevention",
    "journal bearing hot box preventon": "journal_bearing_failure_prevention",
    "hotbox preventon": "journal_bearing_failure_prevention",
    "hot box preventon": "journal_bearing_failure_prevention",
    "journal bearing hotbox detction methods": "journal_bearing_hot_box_detection",
    "journal bearing hot box detction methods": "journal_bearing_hot_box_detection",
    "hotbox detction methods": "journal_bearing_hot_box_detection",
    "hot box detction methods": "journal_bearing_hot_box_detection",
    "journal bearing hotbox detctor methods": "journal_bearing_hot_box_detection",
    "journal bearing hot box detctor methods": "journal_bearing_hot_box_detection",
    "hotbox detctor methods": "journal_bearing_hot_box_detection",
    "hot box detctor methods": "journal_bearing_hot_box_detection",

    # Misspellings and abbreviations for coupler knuckle
    "coupler knuckle inspecton": "coupler_knuckle_inspection",
    "knuckle inspecton": "coupler_knuckle_inspection",
    "coupler knuckle replacment": "coupler_knuckle_replacement",
    "knuckle replacment": "coupler_knuckle_replacement",
    "coupler knuckle criteri": "coupler_knuckle_replacement_criteria",
    "knuckle criteri": "coupler_knuckle_replacement_criteria",
    "coupler knuckle replacment criteri": "coupler_knuckle_replacement_criteria",
    "knuckle replacment criteri": "coupler_knuckle_replacement_criteria",
    "coupler knuckle condem": "coupler_knuckle_replacement_criteria",
    "knuckle condem": "coupler_knuckle_replacement_criteria",
    "coupler knuckle discard": "coupler_knuckle_replacement_criteria",
    "knuckle discard": "coupler_knuckle_replacement_criteria",
    "coupler knuckle removl": "coupler_knuckle_replacement_criteria",
    "knuckle removl": "coupler_knuckle_replacement_criteria",
    "coupler knuckle defect": "coupler_knuckle_replacement_criteria",
    "knuckle defect": "coupler_knuckle_replacement_criteria",
    "coupler knuckle defect inspecton": "coupler_knuckle_inspection",
    "knuckle defect inspecton": "coupler_knuckle_inspection",
    "coupler knuckle defect replacment": "coupler_knuckle_replacement",
    "knuckle defect replacment": "coupler_knuckle_replacement",
    "coupler knuckle defect criteri": "coupler_knuckle_replacement_criteria",
    "knuckle defect criteri": "coupler_knuckle_replacement_criteria",
    "coupler knuckle failur": "coupler_knuckle_replacement_criteria",
    "knuckle failur": "coupler_knuckle_replacement_criteria",
    "coupler knuckle failur inspecton": "coupler_knuckle_inspection",
    "knuckle failur inspecton": "coupler_knuckle_inspection",
    "coupler knuckle failur replacment": "coupler_knuckle_replacement",
    "knuckle failur replacment": "coupler_knuckle_replacement",

    # Misspellings and abbreviations for tank car qualification
    "tank car qualfication": "tank_car_qualification",
    "tank car qualifcation": "tank_car_qualification",
    "tank car qualificaion": "tank_car_qualification",
    "tank car qualifiaction": "tank_car_qualification",
    "tank car qualifiaction criteria": "tank_car_qualification",
    "dot-111 qualfication": "dot_111_tank_car_qualification",
    "dot 111 qualfication": "dot_111_tank_car_qualification",
    "dot111 qualfication": "dot_111_tank_car_qualification",
    "dot-117 qualfication": "dot_117_tank_car_qualification",
    "dot 117 qualfication": "dot_117_tank_car_qualification",
    "dot117 qualfication": "dot_117_tank_car_qualification",
    "tank car stadards": "tank_car_standard",
    "tank car stadard": "tank_car_standard",
    "dot-111 stadard": "dot_111_tank_car_standard",
    "dot 111 stadard": "dot_111_tank_car_standard",
    "dot111 stadard": "dot_111_tank_car_standard",
    "dot-117 stadard": "dot_117_tank_car_standard",
    "dot 117 stadard": "dot_117_tank_car_standard",
    "dot117 stadard": "dot_117_tank_car_standard",
    "tank car inspecton": "tank_car_inspection",
    "tank car testng": "tank_car_testing",
    "tank car test": "tank_car_testing",
    "tank car qualfication test": "tank_car_qualification",
    "tank car qualfication testing": "tank_car_qualification",
    "tank car qualfication inspecton": "tank_car_qualification",
    "dot-111 inspecton": "dot_111_tank_car_inspection",
    "dot 111 inspecton": "dot_111_tank_car_inspection",
    "dot111 inspecton": "dot_111_tank_car_inspection",
    "dot-117 inspecton": "dot_117_tank_car_inspection",
    "dot 117 inspecton": "dot_117_tank_car_inspection",
    "dot117 inspecton": "dot_117_tank_car_inspection",
    "dot-111 testng": "dot_111_tank_car_testing",
    "dot 111 testng": "dot_111_tank_car_testing",
    "dot111 testng": "dot_111_tank_car_testing",
    "dot-117 testng": "dot_117_tank_car_testing",
    "dot 117 testng": "dot_117_tank_car_testing",
    "dot117 testng": "dot_117_tank_car_testing",

    # Misspellings and abbreviations for traction motor
    "traction moter": "traction_motor",
    "traction moter inspection": "traction_motor_inspection",
    "traction moter maintenance": "traction_motor_maintenance",
    "traction moter commutator": "traction_motor_commutator",
    "commutator inspecton": "traction_motor_commutator_inspection",
    "commutator maintenence": "traction_motor_commutator_maintenance",
    "traction moter commutator inspecton": "traction_motor_commutator_inspection",
    "traction moter commutator maintenence": "traction_motor_commutator_maintenance",
    "traction moter replacement": "traction_motor_replacement",
    "traction moter repair": "traction_motor_maintenance",
    "traction moter cleaning": "traction_motor_maintenance",
    "traction moter testing": "traction_motor_testing",
    "traction moter test": "traction_motor_testing",
    "traction moter failure": "traction_motor_failure",
    "traction moter failure inspection": "traction_motor_inspection",
    "traction moter failure maintenance": "traction_motor_maintenance",
    "traction moter failure replacement": "traction_motor_replacement",
    "traction moter failure repair": "traction_motor_maintenance",
    "traction moter failure cleaning": "traction_motor_maintenance",
    "traction moter failure testing": "traction_motor_testing",
    "traction moter failure test": "traction_motor_testing",

    # Misspellings and abbreviations for CBM, vibration, oil
    "condition based maintenance": "condition_based_maintenance",
    "conditon-based maintenance": "condition_based_maintenance",
    "conditon based maintenance": "condition_based_maintenance",
    "cbm vibration analysys": "condition_based_maintenance",
    "cbm oil samplng": "condition_based_maintenance",
    "cbm oil analysys": "condition_based_maintenance",
    "cbm oil monitorng": "condition_based_maintenance",
    "cbm oil testng": "condition_based_maintenance",
    "cbm oil inspecton": "condition_based_maintenance",
    "cbm vibration testng": "condition_based_maintenance",
    "cbm vibration inspecton": "condition_based_maintenance",
    "cbm vibration monitorng": "condition_based_maintenance",
    "vibration analysys": "vibration_analysis",
    "vibration monitorng": "vibration_analysis",
    "vibration testng": "vibration_analysis",
    "vibration inspecton": "vibration_analysis",
    "oil samplng": "oil_sampling",
    "oil analysys": "oil_sampling",
    "oil monitorng": "oil_sampling",
    "oil testng": "oil_sampling",
    "oil inspecton": "oil_sampling",

    # Misspellings and abbreviations for fuel injector
    "fuel injecter": "fuel_injector",
    "injecter": "fuel_injector",
    "fuel injecter test": "fuel_injector_testing",
    "injecter test": "fuel_injector_testing",
    "fuel injecter testing": "fuel_injector_testing",
    "injecter testing": "fuel_injector_testing",
    "fuel injecter inspection": "fuel_injector_inspection",
    "injecter inspection": "fuel_injector_inspection",
    "fuel injecter cleaning": "fuel_injector_cleaning",
    "injecter cleaning": "fuel_injector_cleaning",
    "fuel injecter maintenance": "fuel_injector_maintenance",
    "injecter maintenance": "fuel_injector_maintenance",
    "fuel injecter replacement": "fuel_injector_replacement",
    "injecter replacement": "fuel_injector_replacement",
    "fuel injecter repair": "fuel_injector_maintenance",
    "injecter repair": "fuel_injector_maintenance",
    "fuel injecter failure": "fuel_injector_failure",
    "injecter failure": "fuel_injector_failure",
    "fuel injecter failure inspection": "fuel_injector_inspection",
    "injecter failure inspection": "fuel_injector_inspection",
    "fuel injecter failure testing": "fuel_injector_testing",
    "injecter failure testing": "fuel_injector_testing",
    "fuel injecter failure cleaning": "fuel_injector_cleaning",
    "injecter failure cleaning": "fuel_injector_cleaning",
    "fuel injecter failure maintenance": "fuel_injector_maintenance",
    "injecter failure maintenance": "fuel_injector_maintenance",
    "fuel injecter failure replacement": "fuel_injector_replacement",
    "injecter failure replacement": "fuel_injector_replacement",
    "fuel injecter failure repair": "fuel_injector_maintenance",
    "injecter failure repair": "fuel_injector_maintenance",

    # Misspellings and abbreviations for cooling system
    "cooling sytem": "locomotive_cooling_system",
    "locomotive cooling sytem": "locomotive_cooling_system",
    "radiator inspecton": "locomotive_radiator_inspection",
    "radiator maintenence": "locomotive_radiator_maintenance",
    "radiator cleanng": "locomotive_radiator_cleaning",
    "radiator testng": "locomotive_radiator_testing",
    "radiator replacment": "locomotive_radiator_replacement",
    "radiator repair": "locomotive_radiator_maintenance",
    "coolant inspecton": "locomotive_coolant_inspection",
    "coolant maintenence": "locomotive_coolant_maintenance",
    "coolant cleanng": "locomotive_coolant_cleaning",
    "coolant testng": "locomotive_coolant_testing",
    "coolant replacment": "locomotive_coolant_replacement",
    "coolant repair": "locomotive_coolant_maintenance",
    "coolant managment": "locomotive_coolant_management",
    "cooling sytem inspection": "locomotive_cooling_system_inspection",
    "cooling sytem maintenance": "locomotive_cooling_system_maintenance",
    "cooling sytem cleaning": "locomotive_cooling_system_cleaning",
    "cooling sytem testing": "locomotive_cooling_system_testing",
    "cooling sytem test": "locomotive_cooling_system_testing",
    "cooling sytem replacement": "locomotive_cooling_system_replacement",
    "cooling sytem repair": "locomotive_cooling_system_maintenance",
    "cooling sytem managment": "locomotive_cooling_system_management",

    # Misspellings and abbreviations for truck (bogie) frame
    "truck fram": "bogie_frame",
    "bogie fram": "bogie_frame",
    "truck fram inspection": "bogie_frame_inspection",
    "bogie fram inspection": "bogie_frame_inspection",
    "truck fram crack": "bogie_frame_crack_detection",
    "bogie fram crack": "bogie_frame_crack_detection",
    "truck fram crack detection": "bogie_frame_crack_detection",
    "bogie fram crack detection": "bogie_frame_crack_detection",
    "truck fram failure": "bogie_frame_failure",
    "bogie fram failure": "bogie_frame_failure",
    "truck fram repair": "bogie_frame_maintenance",
    "bogie fram repair": "bogie_frame_maintenance",
    "truck fram replacement": "bogie_frame_replacement",
    "bogie fram replacement": "bogie_frame_replacement",
    "truck fram maintenance": "bogie_frame_maintenance",
    "bogie fram maintenance": "bogie_frame_maintenance",
    "truck maintenence": "bogie_frame_maintenance",
    "bogie maintenence": "bogie_frame_maintenance",

    # Misspellings and abbreviations for safety appliance, ladder, handhold, sill step
    "saftey appliance": "safety_appliance",
    "saftey appliance inspection": "safety_appliance_inspection",
    "ladder inspecton": "ladder_inspection",
    "ladder maintenence": "ladder_maintenance",
    "ladder repair": "ladder_maintenance",
    "ladder replacment": "ladder_replacement",
    "ladder failur": "ladder_failure",
    "ladder failur inspection": "ladder_inspection",
    "ladder failur maintenance": "ladder_maintenance",
    "ladder failur replacment": "ladder_replacement",
    "ladder failur repair": "ladder_maintenance",
    "handhold inspecton": "handhold_inspection",
    "handhold maintenence": "handhold_maintenance",
    "handhold repair": "handhold_maintenance",
    "handhold replacment": "handhold_replacement",
    "handhold failur": "handhold_failure",
    "handhold failur inspection": "handhold_inspection",
    "handhold failur maintenance": "handhold_maintenance",
    "handhold failur replacment": "handhold_replacement",
    "handhold failur repair": "handhold_maintenance",
    "sill step inspecton": "sill_step_inspection",
    "sill step maintenence": "sill_step_maintenance",
    "sill step repair": "sill_step_maintenance",
    "sill step replacment": "sill_step_replacement",
    "sill step failur": "sill_step_failure",
    "sill step failur inspection": "sill_step_inspection",
    "sill step failur maintenance": "sill_step_maintenance",
    "sill step failur replacment": "sill_step_replacement",
    "sill step failur repair": "sill_step_maintenance",
    "saftey appliance maintenance": "safety_appliance_maintenance",
    "saftey appliance repair": "safety_appliance_maintenance",
    "saftey appliance replacment": "safety_appliance_replacement",
    "saftey appliance failur": "safety_appliance_failure",
    "saftey appliance failur inspection": "safety_appliance_inspection",
    "saftey appliance failur maintenance": "safety_appliance_maintenance",
    "saftey appliance failur replacment": "safety_appliance_replacement",
    "saftey appliance failur repair": "safety_appliance_maintenance",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    m = hashlib.sha256()
    for k, v in items:
        m.update(k.encode('utf-8'))
        m.update(b'->')
        m.update(v.encode('utf-8'))
    m.update(str(_EXPECTED_ENTRY_COUNT).encode('utf-8'))
    m.update(SEMANTIC_MAP_VERSION.encode('utf-8'))
    m.update(SEMANTIC_MAP_ENGINE.encode('utf-8'))
    m.update(SEMANTIC_MAP_AUTHOR.encode('utf-8'))
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
        "version": SEMANTIC_MAP_VERSION,
        "engine": SEMANTIC_MAP_ENGINE,
        "author": SEMANTIC_MAP_AUTHOR,
    }

def normalize_term(term: str) -> str:
    term = term.lower()
    term = re.sub(r'[\s\-]+', ' ', term)
    term = term.strip()
    return SEMANTIC_MAP.get(term, term)

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)