import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "S07_slo_monitor_team"
SEMANTIC_MAP_ENGINE = "S07"

SEMANTIC_MAP = {
    # SLO Definition Standards
    "slo": "service_level_objective",
    "service level objective": "service_level_objective",
    "service-level objective": "service_level_objective",
    "servicelevelobjective": "service_level_objective",
    "slo definition": "service_level_objective",
    "slo standard": "service_level_objective",
    "objective": "service_level_objective",
    "objectives": "service_level_objective",
    "slo spec": "service_level_objective",
    "slo specification": "service_level_objective",
    "slo config": "service_level_objective",
    "slo configuration": "service_level_objective",
    "slo policy": "service_level_objective",
    "slo policies": "service_level_objective",
    "slo doc": "service_level_objective",
    "slo document": "service_level_objective",
    "slo documents": "service_level_objective",
    "slo def": "service_level_objective",
    "slo defs": "service_level_objective",
    "slo-def": "service_level_objective",
    "slo-defs": "service_level_objective",
    "service objective": "service_level_objective",
    "service objectives": "service_level_objective",
    "service obj": "service_level_objective",
    "service objs": "service_level_objective",
    "slo standardization": "service_level_objective",
    "slo std": "service_level_objective",
    "slo stds": "service_level_objective",
    "slo-definitions": "service_level_objective",
    "slo-defn": "service_level_objective",
    "slo-defns": "service_level_objective",
    "slo-defination": "service_level_objective",
    "slo-definations": "service_level_objective",
    "slo_def": "service_level_objective",
    "slo_defs": "service_level_objective",
    "slo_standard": "service_level_objective",
    "slo_standards": "service_level_objective",
    "slo_config": "service_level_objective",
    "slo_configs": "service_level_objective",
    "slo_spec": "service_level_objective",
    "slo_specs": "service_level_objective",
    "slo_policy": "service_level_objective",
    "slo_policies": "service_level_objective",
    "slo_document": "service_level_objective",
    "slo_documents": "service_level_objective",
    "slo_definition": "service_level_objective",
    "slo_definitions": "service_level_objective",
    "service level objectives": "service_level_objective",
    "service-level objectives": "service_level_objective",

    # Error Budget Calculation
    "error budget": "error_budget",
    "error budgets": "error_budget",
    "errorbudget": "error_budget",
    "errorbudgeting": "error_budget",
    "err budget": "error_budget",
    "err budgets": "error_budget",
    "errbudget": "error_budget",
    "errbudgets": "error_budget",
    "error_budget": "error_budget",
    "error_budgets": "error_budget",
    "errorbudget calculation": "error_budget",
    "error budget calculation": "error_budget",
    "error_budget_calculation": "error_budget",
    "error budget calc": "error_budget",
    "errorbudget calc": "error_budget",
    "error_budget_calc": "error_budget",
    "error allowance": "error_budget",
    "error allowances": "error_budget",
    "error margin": "error_budget",
    "error margins": "error_budget",
    "eb": "error_budget",
    "eb calc": "error_budget",
    "eb calculation": "error_budget",
    "eb calculations": "error_budget",
    "ebc": "error_budget",
    "eb calcualtion": "error_budget",
    "errorbudget calcualtion": "error_budget",
    "errorbudget calcualtions": "error_budget",

    # Burn Rate Analysis
    "burn rate": "burn_rate",
    "burnrate": "burn_rate",
    "burn rates": "burn_rate",
    "burn_rate": "burn_rate",
    "burn_rate analysis": "burn_rate",
    "burn rate analysis": "burn_rate",
    "burnrate analysis": "burn_rate",
    "burnrate analyses": "burn_rate",
    "burn rate analyses": "burn_rate",
    "burn_rate analyses": "burn_rate",
    "burn rate calc": "burn_rate",
    "burnrate calc": "burn_rate",
    "burn_rate_calc": "burn_rate",
    "burn_rate_calculation": "burn_rate",
    "burn rate calculation": "burn_rate",
    "burnrate calculation": "burn_rate",
    "burnrate calculations": "burn_rate",
    "burn rate calculations": "burn_rate",
    "burn_rate calculations": "burn_rate",
    "br": "burn_rate",
    "br analysis": "burn_rate",
    "br analyses": "burn_rate",
    "br calc": "burn_rate",
    "br calculation": "burn_rate",
    "br calculations": "burn_rate",
    "burnrateanalyzer": "burn_rate",
    "burnrateanalyser": "burn_rate",

    # Latency Percentile Tracking
    "latency": "latency",
    "latency tracking": "latency_tracking",
    "latency percentile": "latency_percentile",
    "latency percentiles": "latency_percentile",
    "latency percentile tracking": "latency_percentile_tracking",
    "latency percentile monitor": "latency_percentile_tracking",
    "latency percentile monitoring": "latency_percentile_tracking",
    "latency p50": "latency_p50",
    "latency p95": "latency_p95",
    "latency p99": "latency_p99",
    "p50": "latency_p50",
    "p95": "latency_p95",
    "p99": "latency_p99",
    "p50 latency": "latency_p50",
    "p95 latency": "latency_p95",
    "p99 latency": "latency_p99",
    "latency_p50": "latency_p50",
    "latency_p95": "latency_p95",
    "latency_p99": "latency_p99",
    "latency-p50": "latency_p50",
    "latency-p95": "latency_p95",
    "latency-p99": "latency_p99",
    "median latency": "latency_p50",
    "95th percentile latency": "latency_p95",
    "99th percentile latency": "latency_p99",
    "50th percentile latency": "latency_p50",
    "percentile latency": "latency_percentile",
    "percentiles": "latency_percentile",
    "latency percentil": "latency_percentile",
    "latency percentil tracking": "latency_percentile_tracking",
    "latency percentil monitor": "latency_percentile_tracking",
    "latency percentil monitoring": "latency_percentile_tracking",
    "latency percentiles tracking": "latency_percentile_tracking",
    "latency percentiles monitor": "latency_percentile_tracking",
    "latency percentiles monitoring": "latency_percentile_tracking",

    # Throughput SLI Measurement
    "throughput": "throughput",
    "throughput sli": "throughput_sli",
    "throughput_sli": "throughput_sli",
    "throughput measurement": "throughput_sli",
    "throughput measurements": "throughput_sli",
    "throughput monitor": "throughput_sli",
    "throughput monitoring": "throughput_sli",
    "throughput calc": "throughput_sli",
    "throughput calculation": "throughput_sli",
    "throughput calculations": "throughput_sli",
    "tp": "throughput",
    "tp sli": "throughput_sli",
    "tp_sli": "throughput_sli",
    "tp measurement": "throughput_sli",
    "tp measurements": "throughput_sli",
    "tp monitor": "throughput_sli",
    "tp monitoring": "throughput_sli",
    "tp calc": "throughput_sli",
    "tp calculation": "throughput_sli",
    "tp calculations": "throughput_sli",
    "through put": "throughput",
    "through put sli": "throughput_sli",
    "through put measurement": "throughput_sli",
    "through put measurements": "throughput_sli",

    # Availability Calculation
    "availability": "availability",
    "availability calculation": "availability_calculation",
    "availability calc": "availability_calculation",
    "availability_calculation": "availability_calculation",
    "availability calculations": "availability_calculation",
    "availability monitoring": "availability_calculation",
    "availability monitor": "availability_calculation",
    "avail": "availability",
    "avail calc": "availability_calculation",
    "avail calculation": "availability_calculation",
    "avail calculations": "availability_calculation",
    "avail monitoring": "availability_calculation",
    "avail monitor": "availability_calculation",
    "uptime": "availability",
    "uptime calculation": "availability_calculation",
    "uptime calc": "availability_calculation",
    "uptime calculations": "availability_calculation",
    "downtime": "downtime",
    "downtime calculation": "downtime_calculation",
    "downtime calc": "downtime_calculation",
    "downtime calculations": "downtime_calculation",
    "availability percent": "availability",
    "availability percentage": "availability",
    "availability rate": "availability",
    "availability ratio": "availability",
    "avail percent": "availability",
    "avail percentage": "availability",
    "avail rate": "availability",
    "avail ratio": "availability",

    # SLO Violation Alerting
    "slo violation": "slo_violation",
    "slo violations": "slo_violation",
    "slo_violation": "slo_violation",
    "slo_violation alert": "slo_violation_alerting",
    "slo violation alert": "slo_violation_alerting",
    "slo violation alerting": "slo_violation_alerting",
    "slo violation alerts": "slo_violation_alerting",
    "slo_violation_alert": "slo_violation_alerting",
    "slo_violation_alerts": "slo_violation_alerting",
    "slo alert": "slo_violation_alerting",
    "slo alerts": "slo_violation_alerting",
    "slo alerting": "slo_violation_alerting",
    "slo breach": "slo_violation",
    "slo breaches": "slo_violation",
    "slo_breach": "slo_violation",
    "slo_breaches": "slo_violation",
    "slo breach alert": "slo_violation_alerting",
    "slo breach alerting": "slo_violation_alerting",
    "slo breach alerts": "slo_violation_alerting",
    "slo_breach_alert": "slo_violation_alerting",
    "slo_breach_alerts": "slo_violation_alerting",
    "slo fail": "slo_violation",
    "slo fails": "slo_violation",
    "slo failure": "slo_violation",
    "slo failures": "slo_violation",
    "slo_failure": "slo_violation",
    "slo_failures": "slo_violation",
    "slo failure alert": "slo_violation_alerting",
    "slo failure alerting": "slo_violation_alerting",
    "slo failure alerts": "slo_violation_alerting",
    "slo_failure_alert": "slo_violation_alerting",
    "slo_failure_alerts": "slo_violation_alerting",

    # Error Budget Exhaustion Prediction
    "error budget exhaustion": "error_budget_exhaustion",
    "error_budget_exhaustion": "error_budget_exhaustion",
    "error budget exhaustion prediction": "error_budget_exhaustion_prediction",
    "error_budget_exhaustion_prediction": "error_budget_exhaustion_prediction",
    "error budget exhaustion predictions": "error_budget_exhaustion_prediction",
    "error_budget_exhaustion_predictions": "error_budget_exhaustion_prediction",
    "error budget depletion": "error_budget_exhaustion",
    "error budget depletion prediction": "error_budget_exhaustion_prediction",
    "error budget depletion predictions": "error_budget_exhaustion_prediction",
    "error_budget_depletion": "error_budget_exhaustion",
    "error_budget_depletion_prediction": "error_budget_exhaustion_prediction",
    "error_budget_depletion_predictions": "error_budget_exhaustion_prediction",
    "eb exhaustion": "error_budget_exhaustion",
    "eb exhaustion prediction": "error_budget_exhaustion_prediction",
    "eb exhaustion predictions": "error_budget_exhaustion_prediction",
    "eb_exhaustion": "error_budget_exhaustion",
    "eb_exhaustion_prediction": "error_budget_exhaustion_prediction",
    "eb_exhaustion_predictions": "error_budget_exhaustion_prediction",
    "eb depletion": "error_budget_exhaustion",
    "eb depletion prediction": "error_budget_exhaustion_prediction",
    "eb depletion predictions": "error_budget_exhaustion_prediction",
    "eb_depletion": "error_budget_exhaustion",
    "eb_depletion_prediction": "error_budget_exhaustion_prediction",
    "eb_depletion_predictions": "error_budget_exhaustion_prediction",

    # Multi-Window SLO Rolling
    "multi-window slo": "multi_window_slo",
    "multi window slo": "multi_window_slo",
    "multiwindow slo": "multi_window_slo",
    "multi_window_slo": "multi_window_slo",
    "multi-window slo rolling": "multi_window_slo_rolling",
    "multi window slo rolling": "multi_window_slo_rolling",
    "multiwindow slo rolling": "multi_window_slo_rolling",
    "multi_window_slo_rolling": "multi_window_slo_rolling",
    "multi-window rolling": "multi_window_slo_rolling",
    "multi window rolling": "multi_window_slo_rolling",
    "multiwindow rolling": "multi_window_slo_rolling",
    "multi_window_rolling": "multi_window_slo_rolling",
    "multi-window": "multi_window_slo",
    "multiwindow": "multi_window_slo",
    "multi window": "multi_window_slo",
    "multiwindow slo roll": "multi_window_slo_rolling",
    "multi window slo roll": "multi_window_slo_rolling",
    "multiwindow roll": "multi_window_slo_rolling",
    "multi window roll": "multi_window_slo_rolling",

    # Composite SLO from Multiple SLIs
    "composite slo": "composite_slo",
    "composite_slo": "composite_slo",
    "composite slo from multiple slis": "composite_slo",
    "composite slo multi sli": "composite_slo",
    "composite slo multisli": "composite_slo",
    "composite slo multi-sli": "composite_slo",
    "composite slo multi_sli": "composite_slo",
    "composite slo from slis": "composite_slo",
    "composite slo from multiple sli": "composite_slo",
    "composite slo from sli": "composite_slo",
    "composite slo aggregation": "composite_slo",
    "composite slo aggregate": "composite_slo",
    "composite slo aggregates": "composite_slo",
    "composite slo aggregations": "composite_slo",
    "composite slo rollup": "composite_slo",
    "composite slo rollups": "composite_slo",
    "composite slo roll-up": "composite_slo",
    "composite slo roll-ups": "composite_slo",
    "composite slo combining": "composite_slo",
    "composite slo combination": "composite_slo",
    "composite slo combinations": "composite_slo",
    "composite slo composed": "composite_slo",
    "composite slo compose": "composite_slo",
    "composite slo composition": "composite_slo",
    "composite slo compositions": "composite_slo",
    "composite slo set": "composite_slo",
    "composite slo sets": "composite_slo",
    "composite slo group": "composite_slo",
    "composite slo groups": "composite_slo",
    "composite slo grouping": "composite_slo",
    "composite slo groupings": "composite_slo",
    "composite slo definition": "composite_slo",
    "composite slo definitions": "composite_slo",
    "composite slo def": "composite_slo",
    "composite slo defs": "composite_slo",

    # Composite (general)
    "composite": "composite",
    "composites": "composite",
    "composite metric": "composite",
    "composite metrics": "composite",
    "composite indicator": "composite",
    "composite indicators": "composite",
    "composite sli": "composite_sli",
    "composite slis": "composite_sli",
    "composite_sli": "composite_sli",
    "composite-sli": "composite_sli",
    "composite sli definition": "composite_sli",
    "composite sli definitions": "composite_sli",
    "composite sli def": "composite_sli",
    "composite sli defs": "composite_sli",
    "composite_sli_def": "composite_sli",
    "composite_sli_defs": "composite_sli",
    "composite_sli_definition": "composite_sli",
    "composite_sli_definitions": "composite_sli",
    "composite indicator definition": "composite",
    "composite indicator definitions": "composite",
    "composite metric definition": "composite",
    "composite metric definitions": "composite",
    "composite metric def": "composite",
    "composite metric defs": "composite",
    "composite indicator def": "composite",
    "composite indicator defs": "composite",
    "composite set": "composite",
    "composite sets": "composite",
    "composite group": "composite",
    "composite groups": "composite",
    "composite grouping": "composite",
    "composite groupings": "composite",

    # SLI
    "sli": "service_level_indicator",
    "service level indicator": "service_level_indicator",
    "service-level indicator": "service_level_indicator",
    "servicelevelindicator": "service_level_indicator",
    "sli definition": "service_level_indicator",
    "sli definitions": "service_level_indicator",
    "sli def": "service_level_indicator",
    "sli defs": "service_level_indicator",
    "sli config": "service_level_indicator",
    "sli configuration": "service_level_indicator",
    "sli spec": "service_level_indicator",
    "sli specification": "service_level_indicator",
    "sli policy": "service_level_indicator",
    "sli document": "service_level_indicator",
    "sli documents": "service_level_indicator",
    "sli standard": "service_level_indicator",
    "sli standards": "service_level_indicator",
    "sli metrics": "service_level_indicator",
    "sli metric": "service_level_indicator",
    "sli monitoring": "service_level_indicator",
    "sli monitor": "service_level_indicator",
    "sli tracking": "service_level_indicator",
    "sli track": "service_level_indicator",
    "sli tracked": "service_level_indicator",
    "sli measured": "service_level_indicator",
    "sli measure": "service_level_indicator",
    "sli measurement": "service_level_indicator",
    "sli measurements": "service_level_indicator",
    "sli indicator": "service_level_indicator",
    "sli indicators": "service_level_indicator",
    "service indicator": "service_level_indicator",
    "service indicators": "service_level_indicator",
    "service indicator definition": "service_level_indicator",
    "service indicator definitions": "service_level_indicator",
    "service indicator def": "service_level_indicator",
    "service indicator defs": "service_level_indicator",
    "service indicator config": "service_level_indicator",
    "service indicator configuration": "service_level_indicator",
    "service indicator spec": "service_level_indicator",
    "service indicator specification": "service_level_indicator",
    "service indicator policy": "service_level_indicator",
    "service indicator document": "service_level_indicator",
    "service indicator documents": "service_level_indicator",
    "service indicator standard": "service_level_indicator",
    "service indicator standards": "service_level_indicator",
    "service indicator metrics": "service_level_indicator",
    "service indicator metric": "service_level_indicator",
    "service indicator monitoring": "service_level_indicator",
    "service indicator monitor": "service_level_indicator",
    "service indicator tracking": "service_level_indicator",
    "service indicator track": "service_level_indicator",
    "service indicator tracked": "service_level_indicator",
    "service indicator measured": "service_level_indicator",
    "service indicator measure": "service_level_indicator",
    "service indicator measurement": "service_level_indicator",
    "service indicator measurements": "service_level_indicator",
    "service indicator indicator": "service_level_indicator",
    "service indicator indicators": "service_level_indicator",
    "sli-definition": "service_level_indicator",
    "sli-definitions": "service_level_indicator",
    "sli-def": "service_level_indicator",
    "sli-defs": "service_level_indicator",
    "sli_config": "service_level_indicator",
    "sli_configuration": "service_level_indicator",
    "sli_spec": "service_level_indicator",
    "sli_specification": "service_level_indicator",
    "sli_policy": "service_level_indicator",
    "sli_document": "service_level_indicator",
    "sli_documents": "service_level_indicator",
    "sli_standard": "service_level_indicator",
    "sli_standards": "service_level_indicator",
    "sli_metric": "service_level_indicator",
    "sli_metrics": "service_level_indicator",
    "sli_monitoring": "service_level_indicator",
    "sli_monitor": "service_level_indicator",
    "sli_tracking": "service_level_indicator",
    "sli_track": "service_level_indicator",
    "sli_tracked": "service_level_indicator",
    "sli_measured": "service_level_indicator",
    "sli_measure": "service_level_indicator",
    "sli_measurement": "service_level_indicator",
    "sli_measurements": "service_level_indicator",
    "sli_indicator": "service_level_indicator",
    "sli_indicators": "service_level_indicator",

    # Misspellings / Common Typos
    "servce level objective": "service_level_objective",
    "servce level indicator": "service_level_indicator",
    "servce-level indicator": "service_level_indicator",
    "servce-level objective": "service_level_objective",
    "servic level objective": "service_level_objective",
    "servic level indicator": "service_level_indicator",
    "servic-level indicator": "service_level_indicator",
    "servic-level objective": "service_level_objective",
    "servicelvel objective": "service_level_objective",
    "servicelvel indicator": "service_level_indicator",
    "servicelvelindicator": "service_level_indicator",
    "servicelvelobjective": "service_level_objective",
    "servicelvl objective": "service_level_objective",
    "servicelvl indicator": "service_level_indicator",
    "servicelvlindicator": "service_level_indicator",
    "servicelvlobjective": "service_level_objective",
    "servicelvl obj": "service_level_objective",
    "servicelvl ind": "service_level_indicator",
    "servicelvl objs": "service_level_objective",
    "servicelvl inds": "service_level_indicator",
    "servicelvl": "service_level_indicator",
    "servicelvlobj": "service_level_objective",
    "servicelvlind": "service_level_indicator",
    "servicelvlobjs": "service_level_objective",
    "servicelvlinds": "service_level_indicator",
    "servicelvl objctive": "service_level_objective",
    "servicelvl indcator": "service_level_indicator",
    "servicelvl objctives": "service_level_objective",
    "servicelvl indcators": "service_level_indicator",
    "latency percentil": "latency_percentile",
    "latency percentiles": "latency_percentile",
    "latency percentil tracking": "latency_percentile_tracking",
    "latency percentiles tracking": "latency_percentile_tracking",
    "latency percentil monitor": "latency_percentile_tracking",
    "latency percentiles monitor": "latency_percentile_tracking",
    "latency percentil monitoring": "latency_percentile_tracking",
    "latency percentiles monitoring": "latency_percentile_tracking",
    "through put": "throughput",
    "through put sli": "throughput_sli",
    "through put measurement": "throughput_sli",
    "through put measurements": "throughput_sli",
    "errorbudget calcualtion": "error_budget",
    "errorbudget calcualtions": "error_budget",
    "burnrateanalyzer": "burn_rate",
    "burnrateanalyser": "burn_rate",
    "availablity": "availability",
    "availablity calculation": "availability_calculation",
    "availablity calc": "availability_calculation",
    "availablity calculations": "availability_calculation",
    "availablity monitoring": "availability_calculation",
    "availablity monitor": "availability_calculation",
    "downtime calcuation": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calulation": "downtime_calculation",
    "downtime caluclation": "downtime_calculation",
    "downtime caluclations": "downtime_calculation",
    "downtime calulcation": "downtime_calculation",
    "downtime calulcations": "downtime_calculation",
    "downtime caluclations": "downtime_calculation",
    "downtime caluclation": "downtime_calculation",
    "downtime calcuations": "downtime_calculation",
    "downtime calcuation": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "downtime_calculation",
    "downtime calcs": "