import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AERO05 Engineering Team"
SEMANTIC_MAP_ENGINE = "AERO05_avionics_navigation"

SEMANTIC_MAP = {
    # VOR DME ILS Approach Navigation
    "vor": "very high frequency omnidirectional range",
    "v.o.r.": "very high frequency omnidirectional range",
    "vortac": "vor tactical air navigation",
    "vor station": "very high frequency omnidirectional range",
    "dme": "distance measuring equipment",
    "d.m.e.": "distance measuring equipment",
    "dme arc": "dme arc procedure",
    "dme arc turn": "dme arc procedure turn",
    "dme arc procedure": "dme arc procedure",
    "ils": "instrument landing system",
    "i.l.s.": "instrument landing system",
    "ils approach": "instrument landing system approach",
    "localizer": "ils localizer",
    "loc": "ils localizer",
    "glideslope": "ils glideslope",
    "gs": "ils glideslope",
    "marker beacon": "ils marker beacon",
    "outer marker": "ils outer marker",
    "middle marker": "ils middle marker",
    "inner marker": "ils inner marker",
    "approach": "approach procedure",
    "precision approach": "instrument landing system approach",
    "non-precision approach": "non-precision approach",
    "missed approach": "missed approach procedure",
    "final approach": "final approach segment",
    "initial approach": "initial approach segment",
    "intermediate approach": "intermediate approach segment",
    "procedure turn": "procedure turn",
    "holding pattern": "holding pattern",
    "transition": "approach transition",
    "waypoint": "navigation waypoint",
    "fix": "navigation fix",
    "navigation fix": "navigation fix",
    "flight path": "flight path",
    "flight segment": "flight segment",
    "runway": "runway",
    "runway threshold": "runway threshold",
    "decision height": "decision height",
    "dh": "decision height",
    "minimums": "approach minimums",
    "approach minimums": "approach minimums",
    "missed approach point": "missed approach point",
    "map": "missed approach point",
    "final approach fix": "final approach fix",
    "faf": "final approach fix",
    "initial approach fix": "initial approach fix",
    "iaf": "initial approach fix",
    "intermediate fix": "intermediate fix",
    "if": "intermediate fix",
    "stepdown fix": "stepdown fix",
    "step down fix": "stepdown fix",
    "altitude restriction": "altitude restriction",
    "altitude constraint": "altitude restriction",
    "altitude limit": "altitude restriction",
    "altitude": "altitude",
    "vertical profile": "vertical profile",
    "horizontal profile": "horizontal profile",
    "course": "course",
    "track": "track",
    "heading": "heading",
    "bearing": "bearing",
    "radial": "radial",
    "distance": "distance",
    "nm": "nautical mile",
    "nautical mile": "nautical mile",
    "mile": "nautical mile",
    "statute mile": "statute mile",
    "sm": "statute mile",
    "gps": "global positioning system",
    "g.p.s.": "global positioning system",
    "waas": "wide area augmentation system",
    "w.a.a.s.": "wide area augmentation system",
    "sbas": "satellite based augmentation system",
    "gbas": "ground based augmentation system",
    "g.b.a.s.": "ground based augmentation system",
    "augmentation": "augmentation system",
    "augmentation system": "augmentation system",
    "gps waas": "global positioning system wide area augmentation system",
    "gps sbas": "global positioning system satellite based augmentation system",
    "gps gbas": "global positioning system ground based augmentation system",
    "gnss": "global navigation satellite system",
    "g.n.s.s.": "global navigation satellite system",
    "satnav": "satellite navigation",
    "satellite navigation": "satellite navigation",
    "ins": "inertial navigation system",
    "i.n.s.": "inertial navigation system",
    "inertial navigation": "inertial navigation system",
    "inertial system": "inertial navigation system",
    "inertial reference": "inertial reference system",
    "irs": "inertial reference system",
    "i.r.s.": "inertial reference system",
    "kalman filter": "kalman filtering",
    "kalman filtering": "kalman filtering",
    "filtering": "kalman filtering",
    "sensor fusion": "kalman filtering",
    "fms": "flight management system",
    "flight management system": "flight management system",
    "cdu": "control display unit",
    "control display unit": "control display unit",
    "fms cdu": "flight management system control display unit",
    "flight plan": "flight plan",
    "flight planning": "flight plan",
    "route": "flight route",
    "flight route": "flight route",
    "leg": "flight leg",
    "segment": "flight segment",
    "waypoint entry": "navigation waypoint",
    "waypoint editing": "navigation waypoint",
    "direct to": "direct to waypoint",
    "direct to waypoint": "direct to waypoint",
    "lateral navigation": "lateral navigation",
    "vertical navigation": "vertical navigation",
    "lnav": "lateral navigation",
    "vnav": "vertical navigation",
    "performance management": "performance monitoring",
    "performance monitoring": "performance monitoring",
    "altitude management": "altitude management",
    "altitude monitoring": "altitude management",
    "altitude deviation": "altitude deviation",
    "altitude alert": "altitude alert",
    "altitude constraint": "altitude restriction",
    "altitude restriction": "altitude restriction",
    "altitude limit": "altitude restriction",
    "rvsm": "reduced vertical separation minimum",
    "reduced vertical separation": "reduced vertical separation minimum",
    "reduced vertical separation minimum": "reduced vertical separation minimum",
    "vertical separation": "vertical separation",
    "vertical deviation": "vertical deviation",
    "vertical guidance": "vertical guidance",
    "horizontal guidance": "horizontal guidance",
    "navigation database": "navigation database",
    "database management": "navigation database management",
    "navigation database management": "navigation database management",
    "database integrity": "integrity monitoring",
    "integrity monitoring": "integrity monitoring",
    "system integrity": "integrity monitoring",
    "system redundancy": "system redundancy",
    "redundancy": "system redundancy",
    "backup system": "system redundancy",
    "failover": "system redundancy",
    "flight data monitoring": "flight data monitoring",
    "flight data recorder": "flight data recorder",
    "cockpit voice recorder": "cockpit voice recorder",
    "cvr": "cockpit voice recorder",
    "fdr": "flight data recorder",
    "elt": "emergency locator transmitter",
    "emergency locator": "emergency locator transmitter",
    "emergency locator transmitter": "emergency locator transmitter",
    "emergency communications": "emergency communications",
    "emergency comms": "emergency communications",
    "distress call": "emergency communications",
    "mayday": "emergency communications",
    "surveillance": "surveillance",
    "ads-b": "automatic dependent surveillance broadcast",
    "adsb": "automatic dependent surveillance broadcast",
    "automatic dependent surveillance": "automatic dependent surveillance broadcast",
    "automatic dependent surveillance broadcast": "automatic dependent surveillance broadcast",
    "transponder": "transponder",
    "transponder mode": "transponder mode",
    "mode a": "transponder mode a",
    "mode c": "transponder mode c",
    "mode s": "transponder mode s",
    "mode a transponder": "transponder mode a",
    "mode c transponder": "transponder mode c",
    "mode s transponder": "transponder mode s",
    "squawk": "transponder code",
    "squawk code": "transponder code",
    "transponder code": "transponder code",
    "ident": "transponder ident",
    "ident button": "transponder ident",
    "tcas": "traffic collision avoidance system",
    "traffic collision avoidance system": "traffic collision avoidance system",
    "collision avoidance": "collision avoidance",
    "resolution advisory": "resolution advisory",
    "ra": "resolution advisory",
    "tcas ra": "resolution advisory",
    "traffic advisory": "traffic advisory",
    "ta": "traffic advisory",
    "tcas ta": "traffic advisory",
    "egpws": "enhanced ground proximity warning system",
    "enhanced ground proximity warning system": "enhanced ground proximity warning system",
    "terrain awareness": "terrain awareness",
    "terrain warning": "terrain awareness",
    "gpws": "ground proximity warning system",
    "ground proximity warning system": "ground proximity warning system",
    "weather radar": "weather radar",
    "wxr": "weather radar",
    "wx radar": "weather radar",
    "weather radar interpretation": "weather radar interpretation",
    "radar interpretation": "weather radar interpretation",
    "radar": "weather radar",
    "hf radio": "high frequency radio",
    "high frequency radio": "high frequency radio",
    "vhf radio": "very high frequency radio",
    "very high frequency radio": "very high frequency radio",
    "satcom": "satellite communication",
    "satellite communication": "satellite communication",
    "radio system": "radio system",
    "radio systems": "radio system",
    "datalink": "datalink",
    "acars": "aircraft communications addressing and reporting system",
    "aircraft communications addressing and reporting system": "aircraft communications addressing and reporting system",
    "cpdlc": "controller pilot datalink communications",
    "controller pilot datalink communications": "controller pilot datalink communications",
    "glass cockpit": "glass cockpit",
    "efis": "electronic flight instrument system",
    "electronic flight instrument system": "electronic flight instrument system",
    "pfd": "primary flight display",
    "primary flight display": "primary flight display",
    "nd": "navigation display",
    "navigation display": "navigation display",
    "eicas": "engine indicating and crew alerting system",
    "engine indicating and crew alerting system": "engine indicating and crew alerting system",
    "autopilot": "autopilot",
    "flight director": "flight director",
    "servo mode": "autopilot servo mode",
    "autopilot servo mode": "autopilot servo mode",
    "autopilot mode": "autopilot mode",
    "autopilot flight director": "autopilot flight director",
    "fd": "flight director",
    "air data computer": "air data computer",
    "adc": "air data computer",
    "pitot static": "pitot static",
    "pitot tube": "pitot static",
    "static port": "pitot static",
    "pressure altitude": "pressure altitude",
    "radio altimeter": "radio altimeter",
    "radalt": "radio altimeter",
    "decision height": "decision height",
    "dme arc": "dme arc procedure",
    "arc turn": "dme arc procedure turn",
    "arc procedure": "dme arc procedure",
    "rnav": "area navigation",
    "area navigation": "area navigation",
    "rnp": "required navigation performance",
    "required navigation performance": "required navigation performance",
    "rnav approach": "area navigation approach",
    "rnp approach": "required navigation performance approach",
    "approach procedure": "approach procedure",
    "procedure turn": "procedure turn",
    "turn": "procedure turn",
    "rvsm": "reduced vertical separation minimum",
    "altitude separation": "vertical separation",
    "vertical separation minimum": "reduced vertical separation minimum",
    "flight plan management": "flight plan management",
    "plan management": "flight plan management",
    "flight planning": "flight plan management",
    "cockpit display": "cockpit display",
    "display management": "cockpit display management",
    "cockpit display management": "cockpit display management",
    "monitoring": "performance monitoring",
    "performance monitoring": "performance monitoring",
    "system monitoring": "performance monitoring",
    "integrity monitoring": "integrity monitoring",
    "surveillance integrity monitoring": "surveillance integrity monitoring",
    "surveillance monitoring": "surveillance integrity monitoring",
    "flight data monitoring": "flight data monitoring",
    "flight monitoring": "flight data monitoring",
    "autopilot servo modes": "autopilot servo mode",
    "servo modes": "autopilot servo mode",
    "autopilot modes": "autopilot mode",
    "autopilot operation": "autopilot mode",
    "flight director modes": "flight director",
    "flight director operation": "flight director",
    "air data": "air data computer",
    "pitot static system": "pitot static",
    "radio altimeter": "radio altimeter",
    "decision height": "decision height",
    "dme arc procedure turns": "dme arc procedure turn",
    "arc procedure turns": "dme arc procedure turn",
    "rnav rnp approaches": "required navigation performance approach",
    "rnp approaches": "required navigation performance approach",
    "rnav approaches": "area navigation approach",
    "rvsm reduced vertical separation": "reduced vertical separation minimum",
    "reduced vertical separation minimum": "reduced vertical separation minimum",
    "elt emergency locator": "emergency locator transmitter",
    "cockpit voice recorder flight data recorder": "cockpit voice recorder flight data recorder",
    "performance monitoring": "performance monitoring",
    "altitude management": "altitude management",
    "surveillance integrity monitoring": "surveillance integrity monitoring",
    "cockpit display management": "cockpit display management",
    "emergency communications": "emergency communications",
    "flight plan management": "flight plan management",
    "system redundancy": "system redundancy",
    "integrity monitoring": "integrity monitoring",
    "navigation database management": "navigation database management",
    "flight data monitoring": "flight data monitoring",
    "autopilot servo modes": "autopilot servo mode",
    # Synonyms, misspellings, related terms
    "ils loc": "ils localizer",
    "ils gs": "ils glideslope",
    "ils marker": "ils marker beacon",
    "ils outer": "ils outer marker",
    "ils middle": "ils middle marker",
    "ils inner": "ils inner marker",
    "ils dh": "decision height",
    "ils minimums": "approach minimums",
    "ils map": "missed approach point",
    "ils faf": "final approach fix",
    "ils iaf": "initial approach fix",
    "ils if": "intermediate fix",
    "ils stepdown": "stepdown fix",
    "ils altitude restriction": "altitude restriction",
    "ils course": "course",
    "ils track": "track",
    "ils heading": "heading",
    "ils bearing": "bearing",
    "ils radial": "radial",
    "ils distance": "distance",
    "ils nm": "nautical mile",
    "ils mile": "nautical mile",
    "ils gps": "global positioning system",
    "ils waas": "wide area augmentation system",
    "ils sbas": "satellite based augmentation system",
    "ils gbas": "ground based augmentation system",
    "ils gnss": "global navigation satellite system",
    "ils satnav": "satellite navigation",
    "ils ins": "inertial navigation system",
    "ils irs": "inertial reference system",
    "ils kalman": "kalman filtering",
    "ils sensor fusion": "kalman filtering",
    "ils fms": "flight management system",
    "ils cdu": "control display unit",
    "ils flight plan": "flight plan",
    "ils route": "flight route",
    "ils leg": "flight leg",
    "ils segment": "flight segment",
    "ils waypoint": "navigation waypoint",
    "ils fix": "navigation fix",
    "ils direct to": "direct to waypoint",
    "ils lnav": "lateral navigation",
    "ils vnav": "vertical navigation",
    "ils performance": "performance monitoring",
    "ils altitude management": "altitude management",
    "ils rvsm": "reduced vertical separation minimum",
    "ils vertical separation": "vertical separation",
    "ils navigation database": "navigation database",
    "ils integrity": "integrity monitoring",
    "ils redundancy": "system redundancy",
    "ils backup": "system redundancy",
    "ils failover": "system redundancy",
    "ils flight data": "flight data monitoring",
    "ils cvr": "cockpit voice recorder",
    "ils fdr": "flight data recorder",
    "ils elt": "emergency locator transmitter",
    "ils emergency": "emergency communications",
    "ils surveillance": "surveillance",
    "ils ads-b": "automatic dependent surveillance broadcast",
    "ils transponder": "transponder",
    "ils tcas": "traffic collision avoidance system",
    "ils egpws": "enhanced ground proximity warning system",
    "ils terrain": "terrain awareness",
    "ils weather radar": "weather radar",
    "ils hf radio": "high frequency radio",
    "ils vhf radio": "very high frequency radio",
    "ils satcom": "satellite communication",
    "ils datalink": "datalink",
    "ils acars": "aircraft communications addressing and reporting system",
    "ils cpdlc": "controller pilot datalink communications",
    "ils glass cockpit": "glass cockpit",
    "ils efis": "electronic flight instrument system",
    "ils pfd": "primary flight display",
    "ils nd": "navigation display",
    "ils eicas": "engine indicating and crew alerting system",
    "ils autopilot": "autopilot",
    "ils flight director": "flight director",
    "ils servo mode": "autopilot servo mode",
    "ils autopilot mode": "autopilot mode",
    "ils air data computer": "air data computer",
    "ils adc": "air data computer",
    "ils pitot static": "pitot static",
    "ils radio altimeter": "radio altimeter",
    "ils dme arc": "dme arc procedure",
    "ils arc turn": "dme arc procedure turn",
    "ils arc procedure": "dme arc procedure",
    "ils rnav": "area navigation",
    "ils rnp": "required navigation performance",
    "ils rnav approach": "area navigation approach",
    "ils rnp approach": "required navigation performance approach",
    "ils approach procedure": "approach procedure",
    "ils procedure turn": "procedure turn",
    "ils turn": "procedure turn",
    "ils altitude separation": "vertical separation",
    "ils vertical separation minimum": "reduced vertical separation minimum",
    "ils flight plan management": "flight plan management",
    "ils plan management": "flight plan management",
    "ils flight planning": "flight plan management",
    "ils cockpit display": "cockpit display",
    "ils display management": "cockpit display management",
    "ils cockpit display management": "cockpit display management",
    "ils monitoring": "performance monitoring",
    "ils system monitoring": "performance monitoring",
    "ils integrity monitoring": "integrity monitoring",
    "ils surveillance integrity monitoring": "surveillance integrity monitoring",
    "ils flight data monitoring": "flight data monitoring",
    "ils flight monitoring": "flight data monitoring",
    "ils autopilot servo modes": "autopilot servo mode",
    "ils servo modes": "autopilot servo mode",
    "ils autopilot modes": "autopilot mode",
    "ils autopilot operation": "autopilot mode",
    "ils flight director modes": "flight director",
    "ils flight director operation": "flight director",
    "ils air data": "air data computer",
    "ils pitot static system": "pitot static",
    "ils radio altimeter": "radio altimeter",
    "ils decision height": "decision height",
    "ils dme arc procedure turns": "dme arc procedure turn",
    "ils arc procedure turns": "dme arc procedure turn",
    "ils rnav rnp approaches": "required navigation performance approach",
    "ils rnp approaches": "required navigation performance approach",
    "ils rnav approaches": "area navigation approach",
    "ils rvsm reduced vertical separation": "reduced vertical separation minimum",
    "ils reduced vertical separation minimum": "reduced vertical separation minimum",
    "ils elt emergency locator": "emergency locator transmitter",
    "ils cockpit voice recorder flight data recorder": "cockpit voice recorder flight data recorder",
    "ils performance monitoring": "performance monitoring",
    "ils altitude management": "altitude management",
    "ils surveillance integrity monitoring": "surveillance integrity monitoring",
    "ils cockpit display management": "cockpit display management",
    "ils emergency communications": "emergency communications",
    "ils flight plan management": "flight plan management",
    "ils system redundancy": "system redundancy",
    "ils integrity monitoring": "integrity monitoring",
    "ils navigation database management": "navigation database management",
    "ils flight data monitoring": "flight data monitoring",
    "ils autopilot servo modes": "autopilot servo mode",
    # Misspellings, abbreviations, variants
    "ilss": "instrument landing system",
    "ils app": "instrument landing system approach",
    "ils appr": "instrument landing system approach",
    "ils approach": "instrument landing system approach",
    "ils apr": "instrument landing system approach",
    "ils apch": "instrument landing system approach",
    "ils proc": "approach procedure",
    "ils turn": "procedure turn",
    "ils hold": "holding pattern",
    "ils trans": "approach transition",
    "ils wp": "navigation waypoint",
    "ils fix": "navigation fix",
    "ils seg": "flight segment",
    "ils rw": "runway",
    "ils thr": "runway threshold",
    "ils dh": "decision height",
    "ils min": "approach minimums",
    "ils map": "missed approach point",
    "ils faf": "final approach fix",
    "ils iaf": "initial approach fix",
    "ils if": "intermediate fix",
    "ils sdf": "stepdown fix",
    "ils alt": "altitude",
    "ils vert": "vertical profile",
    "ils horiz": "horizontal profile",
    "ils crs": "course",
    "ils trk": "track",
    "ils hdg": "heading",
    "ils brg": "bearing",
    "ils rad": "radial",
    "ils dist": "distance",
    "ils nm": "nautical mile",
    "ils sm": "statute mile",
    "ils gps": "global positioning system",
    "ils waas": "wide area augmentation system",
    "ils sbas": "satellite based augmentation system",
    "ils gbas": "ground based augmentation system",
    "ils gnss": "global navigation satellite system",
    "ils satnav": "satellite navigation",
    "ils ins": "inertial navigation system",
    "ils irs": "inertial reference system",
    "ils kalman": "kalman filtering",
    "ils fms": "flight management system",
    "ils cdu": "control display unit",
    "ils fp": "flight plan",
    "ils rte": "flight route",
    "ils leg": "flight leg",
    "ils seg": "flight segment",
    "ils wp": "navigation waypoint",
    "ils fix": "navigation fix",
    "ils dct": "direct to waypoint",
    "ils lnav": "lateral navigation",
    "ils vnav": "vertical navigation",
    "ils perf": "performance monitoring",
    "ils altmgmt": "altitude management",
    "ils rvsm": "reduced vertical separation minimum",
    "ils sep": "vertical separation",
    "ils navdb": "navigation database",
    "ils integ": "integrity monitoring",
    "ils red": "system redundancy",
    "ils bkup": "system redundancy",
    "ils fail": "system redundancy",
    "ils fdm": "flight data monitoring",
    "ils cvr": "cockpit voice recorder",
    "ils fdr": "flight data recorder",
    "ils elt": "emergency locator transmitter",
    "ils emcom": "emergency communications",
    "ils surv": "surveillance",
    "ils adsb": "automatic dependent surveillance broadcast",
    "ils xpdr": "transponder",
    "ils tcas": "traffic collision avoidance system",
    "ils egpws": "enhanced ground proximity warning system",
    "ils terr": "terrain awareness",
    "ils wxr": "weather radar",
    "ils hf": "high frequency radio",
    "ils vhf": "very high frequency radio",
    "ils sat": "satellite communication",
    "ils dl": "datalink",
    "ils acars": "aircraft communications addressing and reporting system",
    "ils cpdlc": "controller pilot datalink communications",
    "ils glass": "glass cockpit",
    "ils efis": "electronic flight instrument system",
    "ils pfd": "primary flight display",
    "ils nd": "navigation display",
    "ils eicas": "engine indicating and crew alerting system",
    "ils ap": "autopilot",
    "ils fd": "flight director",
    "ils servo": "autopilot servo mode",
    "ils apmode": "autopilot mode",
    "ils adc": "air data computer",
    "ils pitot": "pitot static",
    "ils radalt": "radio altimeter",
    "ils arc": "dme arc procedure",
    "ils rnav": "area navigation",
    "ils rnp": "required navigation performance",
    "ils rnavapp": "area navigation approach",
    "ils rnpapp": "required navigation performance approach",
    "ils proc": "approach procedure",
    "ils turn": "procedure turn",
    "ils sep": "vertical separation",
    "ils rvsm": "reduced vertical separation minimum",
    "ils fpman": "flight plan management",
    "ils disp": "cockpit display",
    "ils dispman": "cockpit display management",
    "ils mon": "performance monitoring",
    "ils sysmon": "performance monitoring",
    "ils integmon": "integrity monitoring",
    "ils survmon": "surveillance integrity monitoring",
    "ils fdmon": "flight data monitoring",
    "ils apservo": "autopilot servo mode",
    # Related terms
    "navigation": "navigation",
    "approach": "approach procedure",
    "departure": "departure procedure",
    "arrival": "arrival procedure",
    "enroute": "enroute",
    "en route": "enroute",
    "enroute segment": "enroute",
    "en route segment": "enroute",
    "sid": "standard instrument departure",
    "standard instrument departure": "standard instrument departure",
    "star": "standard terminal arrival route",
    "standard terminal arrival route": "standard terminal arrival route",
    "transition": "approach transition",
    "transition fix": "approach transition",
    "transition segment": "approach transition",
    "transition waypoint": "approach transition",
    "holding": "holding pattern",
    "hold": "holding pattern",
    "holding fix": "holding pattern",
    "holding waypoint": "holding pattern",
    "holding entry": "holding pattern",
    "holding exit": "holding pattern",
    "holding procedure": "holding pattern",
    "procedure": "procedure turn",
    "turn": "procedure turn",
    "procedure turn": "procedure turn",
    "procedure entry": "procedure turn",
    "procedure exit": "procedure turn",
    "procedure segment": "procedure turn",
    "procedure waypoint": "procedure turn",
    "fix": "navigation fix",
    "waypoint": "navigation waypoint",
    "segment": "flight segment",
    "leg": "flight leg",
    "route": "flight route",
    "flight plan": "flight plan",
    "flight plan segment": "flight segment",
    "flight plan leg": "flight leg",
    "flight plan waypoint": "navigation waypoint",
    "flight plan fix": "navigation fix",
    "flight plan route": "flight route",
    "flight plan entry": "flight plan",
    "flight plan exit": "flight plan",
    "flight plan transition": "approach transition",
    "flight plan procedure": "approach procedure",
    "flight plan minimums": "approach minimums",
    "flight plan missed approach": "missed approach procedure",
    "flight plan final approach": "final approach segment",
    "flight plan initial approach": "initial approach segment",
    "flight plan intermediate approach": "intermediate approach segment",
    "flight plan stepdown": "stepdown fix",
    "flight plan altitude restriction": "altitude restriction",
    "flight plan altitude constraint": "altitude restriction",
    "flight plan altitude limit": "altitude restriction",
    "flight plan altitude": "altitude",
    "flight plan vertical profile": "vertical profile",
    "flight plan horizontal profile": "horizontal profile",
    "flight plan course": "course",
    "flight plan track": "track",
    "flight plan heading": "heading",
    "flight plan bearing": "bearing",
    "flight plan radial": "radial",
    "flight plan distance": "distance",
    "flight plan nm": "nautical mile",
    "flight plan mile": "nautical mile",
    "flight plan gps": "global positioning system",
    "flight plan waas": "wide area augmentation system",
    "flight plan sbas": "satellite based augmentation system",
    "flight plan gbas": "ground based augmentation system",
    "flight plan gnss": "global navigation satellite system",
    "flight plan satnav": "satellite navigation",
    "flight plan ins": "inertial navigation system",
    "flight plan irs": "inertial reference system",
    "flight plan kalman": "kalman filtering",
    "flight plan sensor fusion": "kalman filtering",
    "flight plan fms": "flight management system",
    "flight plan cdu": "control display unit",
    "flight plan flight plan": "flight plan",
    "flight plan route": "flight route",
    "flight plan leg": "flight leg",
    "flight plan segment": "flight segment",
    "flight plan waypoint": "navigation waypoint",
    "flight plan fix": "navigation fix",
    "flight plan direct to": "direct to waypoint",
    "flight plan lnav": "lateral navigation",
    "flight plan vnav": "vertical navigation",
    "flight plan performance": "performance monitoring",
    "flight plan altitude management": "altitude management",
    "flight plan rvsm": "reduced vertical separation minimum",
    "flight plan vertical separation": "vertical separation",
    "flight plan navigation database": "navigation database",
    "flight plan integrity": "integrity monitoring",
    "flight plan redundancy": "system redundancy",
    "flight plan backup": "system redundancy",
    "flight plan failover": "system redundancy",
    "flight plan flight data": "flight data monitoring",
    "flight plan cvr": "cockpit voice recorder",
    "flight plan fdr": "flight data recorder",
    "flight plan elt": "emergency locator transmitter",
    "flight plan emergency": "emergency communications",
    "flight plan surveillance": "surveillance",
    "flight plan ads-b": "automatic dependent surveillance broadcast",
    "flight plan transponder": "transponder",
    "flight plan tcas": "traffic collision avoidance system",
    "flight plan egpws": "enhanced ground proximity warning system",
    "flight plan terrain": "terrain awareness",
    "flight plan weather radar": "weather radar",
    "flight plan hf radio": "high frequency radio",
    "flight plan vhf radio": "very high frequency radio",
    "flight plan satcom": "satellite communication",
    "flight plan datalink": "datalink",
    "flight plan acars": "aircraft communications addressing and reporting system",
    "flight plan cpdlc": "controller pilot datalink communications",
    "flight plan glass cockpit": "glass cockpit",
    "flight plan efis": "electronic flight instrument system",
    "flight plan pfd": "primary flight display",
    "flight plan nd": "navigation display",
    "flight plan eicas": "engine indicating and crew alerting system",
    "flight plan autopilot": "autopilot",
    "flight plan flight director": "flight director",
    "flight plan servo mode": "autopilot servo mode",
    "flight plan autopilot mode": "autopilot mode",
    "flight plan air data computer": "air data computer",
    "flight plan adc": "air data computer",
    "flight plan pitot static": "pitot static",
    "flight plan radio altimeter": "radio altimeter",
    "flight plan dme arc": "dme arc procedure",
    "flight plan arc turn": "dme arc procedure turn",
    "flight plan arc procedure": "dme arc procedure",
    "flight plan rnav": "area navigation",
    "flight plan rnp": "required navigation performance",
    "flight plan rnav approach": "area navigation approach",
    "flight plan rnp approach": "required navigation performance approach",
    "flight plan approach procedure": "approach procedure",
    "flight plan procedure turn": "procedure turn",
    "flight plan turn": "procedure turn",
    "flight plan altitude separation": "vertical separation",
    "flight plan vertical separation minimum": "reduced vertical separation minimum",
    "flight plan flight plan management": "flight plan management",
    "flight plan plan management": "flight plan management",
    "flight plan flight planning": "flight plan management",
    "flight plan cockpit display": "cockpit display",
    "flight plan display management": "cockpit display management",
    "flight plan cockpit display management": "cockpit display management",
    "flight plan monitoring": "performance monitoring",
    "flight plan system monitoring": "performance monitoring",
    "flight plan integrity monitoring": "integrity monitoring",
    "flight plan surveillance integrity monitoring": "surveillance integrity monitoring",
    "flight plan flight data monitoring": "flight data monitoring",
    "flight plan flight monitoring": "flight data monitoring",
    "flight plan autopilot servo modes": "autopilot servo mode",
    "flight plan servo modes": "autopilot servo mode",
    "flight plan autopilot modes": "autopilot mode",
    "flight plan autopilot operation": "autopilot mode",
    "flight plan flight director modes": "flight director",
    "flight plan flight director operation": "flight director",
    "flight plan air data": "air data computer",
    "flight plan pitot static system": "pitot static",
    "flight plan radio altimeter": "radio altimeter",
    "flight plan decision height": "decision height",
    "flight plan dme arc procedure turns": "dme arc procedure turn",
    "flight plan arc procedure turns": "dme arc procedure turn",
    "flight plan rnav rnp approaches": "required navigation performance approach",
    "flight plan rnp approaches": "required navigation performance approach",
    "flight plan rnav approaches": "area navigation approach",
    "flight plan rvsm reduced vertical separation": "reduced vertical separation minimum",
    "flight plan reduced vertical separation minimum": "reduced vertical separation minimum",
    "flight plan elt emergency locator": "emergency locator transmitter",
    "flight plan cockpit voice recorder flight data recorder": "cockpit voice recorder flight data recorder",
    "flight plan performance monitoring": "performance monitoring",
    "flight plan altitude management": "altitude management",
    "flight plan surveillance integrity monitoring": "surveillance integrity monitoring",
    "flight plan cockpit display management": "cockpit display management",
    "flight plan emergency communications": "emergency communications",
    "flight plan flight plan management": "flight plan management",
    "flight plan system redundancy": "system redundancy",
    "flight plan integrity monitoring": "integrity monitoring",
    "flight plan navigation database management": "navigation database management",
    "flight plan flight data monitoring": "flight data monitoring",
    "flight plan autopilot servo modes": "autopilot servo mode",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    map_bytes = "".join(f"{k}:{v};" for k, v in items).encode("utf-8")
    return hashlib.sha256(map_bytes).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_hash = _compute_map_hash()
    is_valid = actual_hash == _MAP_INTEGRITY_HASH
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": _EXPECTED_ENTRY_COUNT,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"[^\w\s\-\.]", "", t)
    t = t.replace("_", " ")
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == norm and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)