import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "E02_summary_generator"
SEMANTIC_MAP_ENGINE = "E02"

SEMANTIC_MAP = {
    # Executive Summary Structure
    "executive summary": "executive_summary",
    "summary": "executive_summary",
    "overview": "executive_summary",
    "synopsis": "executive_summary",
    "abstract": "executive_summary",
    "high-level summary": "executive_summary",
    "management summary": "executive_summary",
    "summary section": "executive_summary",
    "summary statement": "executive_summary",
    "summary paragraph": "executive_summary",
    "summary report": "executive_summary",
    "summarization": "executive_summary",
    "summery": "executive_summary",
    "exective summary": "executive_summary",
    "exsum": "executive_summary",
    "exec sum": "executive_summary",
    "ex sum": "executive_summary",
    "es": "executive_summary",

    # Key Findings Extraction
    "key findings": "key_findings",
    "findings": "key_findings",
    "main findings": "key_findings",
    "major findings": "key_findings",
    "critical findings": "key_findings",
    "important findings": "key_findings",
    "salient findings": "key_findings",
    "principal findings": "key_findings",
    "core findings": "key_findings",
    "essential findings": "key_findings",
    "notable findings": "key_findings",
    "findings extraction": "key_findings",
    "findings summary": "key_findings",
    "key points": "key_findings",
    "main points": "key_findings",
    "main takeaways": "key_findings",
    "takeaways": "key_findings",
    "key takeaways": "key_findings",
    "highlights": "key_findings",
    "highlighted findings": "key_findings",
    "highlighted points": "key_findings",
    "findings section": "key_findings",
    "findngs": "key_findings",
    "keyfinding": "key_findings",
    "kf": "key_findings",

    # Risk Highlight Formatting
    "risk highlight": "risk_highlight",
    "risk highlights": "risk_highlight",
    "risk summary": "risk_highlight",
    "risk overview": "risk_highlight",
    "risk assessment": "risk_highlight",
    "risk evaluation": "risk_highlight",
    "risk identification": "risk_highlight",
    "risk analysis": "risk_highlight",
    "risk factors": "risk_highlight",
    "risk items": "risk_highlight",
    "risks": "risk_highlight",
    "key risks": "risk_highlight",
    "major risks": "risk_highlight",
    "critical risks": "risk_highlight",
    "significant risks": "risk_highlight",
    "material risks": "risk_highlight",
    "risk points": "risk_highlight",
    "risk findings": "risk_highlight",
    "risk issues": "risk_highlight",
    "risk section": "risk_highlight",
    "risk format": "risk_highlight",
    "risk formatting": "risk_highlight",
    "risk highlight formatting": "risk_highlight",
    "risk highlight section": "risk_highlight",
    "risk hightlight": "risk_highlight",
    "risk hi-lite": "risk_highlight",
    "risk hi light": "risk_highlight",
    "risk hi-lights": "risk_highlight",
    "risk hi lights": "risk_highlight",
    "rhf": "risk_highlight",

    # Recommendation Synthesis
    "recommendations": "recommendation_synthesis",
    "recommendation": "recommendation_synthesis",
    "recommendation synthesis": "recommendation_synthesis",
    "synthesized recommendations": "recommendation_synthesis",
    "synthesizing recommendations": "recommendation_synthesis",
    "recommendation summary": "recommendation_synthesis",
    "recommendation section": "recommendation_synthesis",
    "recommendation findings": "recommendation_synthesis",
    "recommendation extraction": "recommendation_synthesis",
    "recommendation generation": "recommendation_synthesis",
    "recommendation creation": "recommendation_synthesis",
    "rec synthesis": "recommendation_synthesis",
    "rec synth": "recommendation_synthesis",
    "rec summary": "recommendation_synthesis",
    "recs": "recommendation_synthesis",
    "reco": "recommendation_synthesis",
    "reccomendations": "recommendation_synthesis",
    "recomendations": "recommendation_synthesis",
    "rcmd": "recommendation_synthesis",
    "rcmds": "recommendation_synthesis",
    "rcmnd": "recommendation_synthesis",
    "rcmnds": "recommendation_synthesis",
    "rcmd synth": "recommendation_synthesis",

    # Multi-Source Aggregation
    "multi-source aggregation": "multi_source_aggregation",
    "multi source aggregation": "multi_source_aggregation",
    "multi-source synthesis": "multi_source_aggregation",
    "multi source synthesis": "multi_source_aggregation",
    "multi-source integration": "multi_source_aggregation",
    "multi source integration": "multi_source_aggregation",
    "multi-source consolidation": "multi_source_aggregation",
    "multi source consolidation": "multi_source_aggregation",
    "multi-source summary": "multi_source_aggregation",
    "multi source summary": "multi_source_aggregation",
    "aggregation": "multi_source_aggregation",
    "aggregating": "multi_source_aggregation",
    "aggregated sources": "multi_source_aggregation",
    "source aggregation": "multi_source_aggregation",
    "source synthesis": "multi_source_aggregation",
    "source integration": "multi_source_aggregation",
    "source consolidation": "multi_source_aggregation",
    "multi-doc aggregation": "multi_source_aggregation",
    "multidoc aggregation": "multi_source_aggregation",
    "multi-document aggregation": "multi_source_aggregation",
    "multi document aggregation": "multi_source_aggregation",
    "msa": "multi_source_aggregation",

    # Document Abstract Generation
    "document abstract": "document_abstract_generation",
    "abstract generation": "document_abstract_generation",
    "doc abstract": "document_abstract_generation",
    "doc abs": "document_abstract_generation",
    "abstract": "document_abstract_generation",
    "abstracting": "document_abstract_generation",
    "abstract generation section": "document_abstract_generation",
    "abstract summary": "document_abstract_generation",
    "generate abstract": "document_abstract_generation",
    "abstract creation": "document_abstract_generation",
    "abstract synthesis": "document_abstract_generation",
    "abstract generator": "document_abstract_generation",
    "document abs": "document_abstract_generation",
    "docab": "document_abstract_generation",
    "docabs": "document_abstract_generation",
    "dag": "document_abstract_generation",

    # Findings Prioritization
    "findings prioritization": "findings_prioritization",
    "prioritization": "findings_prioritization",
    "prioritizing findings": "findings_prioritization",
    "findings ranking": "findings_prioritization",
    "ranking findings": "findings_prioritization",
    "findings order": "findings_prioritization",
    "findings ordering": "findings_prioritization",
    "findings hierarchy": "findings_prioritization",
    "findings importance": "findings_prioritization",
    "findings weight": "findings_prioritization",
    "findings weighting": "findings_prioritization",
    "priority findings": "findings_prioritization",
    "key findings prioritization": "findings_prioritization",
    "main findings prioritization": "findings_prioritization",
    "prioritize findings": "findings_prioritization",
    "prioritise findings": "findings_prioritization",
    "findings prioritisation": "findings_prioritization",
    "fp": "findings_prioritization",

    # Materiality Filtering
    "materiality filtering": "materiality_filtering",
    "material filtering": "materiality_filtering",
    "materiality filter": "materiality_filtering",
    "material filter": "materiality_filtering",
    "materiality assessment": "materiality_filtering",
    "materiality evaluation": "materiality_filtering",
    "materiality analysis": "materiality_filtering",
    "materiality screening": "materiality_filtering",
    "materiality check": "materiality_filtering",
    "materiality review": "materiality_filtering",
    "materiality": "materiality_filtering",
    "material": "materiality_filtering",
    "materiality selection": "materiality_filtering",
    "materiality prioritization": "materiality_filtering",
    "materiality prioritisation": "materiality_filtering",
    "mat filter": "materiality_filtering",
    "mat filtering": "materiality_filtering",
    "mat assessment": "materiality_filtering",
    "mat evaluation": "materiality_filtering",
    "mat analysis": "materiality_filtering",
    "mat screening": "materiality_filtering",
    "mat check": "materiality_filtering",
    "mat review": "materiality_filtering",
    "mat": "materiality_filtering",
    "mf": "materiality_filtering",

    # Audience-Appropriate Language
    "audience-appropriate language": "audience_appropriate_language",
    "audience appropriate language": "audience_appropriate_language",
    "audience language": "audience_appropriate_language",
    "audience targeting": "audience_appropriate_language",
    "audience adaptation": "audience_appropriate_language",
    "audience fit": "audience_appropriate_language",
    "audience suitability": "audience_appropriate_language",
    "audience appropriateness": "audience_appropriate_language",
    "language adaptation": "audience_appropriate_language",
    "language suitability": "audience_appropriate_language",
    "language appropriateness": "audience_appropriate_language",
    "language fit": "audience_appropriate_language",
    "appropriate language": "audience_appropriate_language",
    "suitable language": "audience_appropriate_language",
    "tailored language": "audience_appropriate_language",
    "targeted language": "audience_appropriate_language",
    "audience-appropriate": "audience_appropriate_language",
    "audience appropriate": "audience_appropriate_language",
    "aal": "audience_appropriate_language",

    # Summary Length Optimization
    "summary length optimization": "summary_length_optimization",
    "summary length": "summary_length_optimization",
    "length optimization": "summary_length_optimization",
    "length control": "summary_length_optimization",
    "length management": "summary_length_optimization",
    "summary optimization": "summary_length_optimization",
    "summary length control": "summary_length_optimization",
    "summary length management": "summary_length_optimization",
    "summary size": "summary_length_optimization",
    "summary sizing": "summary_length_optimization",
    "summary length tuning": "summary_length_optimization",
    "summary length adjustment": "summary_length_optimization",
    "summary length regulation": "summary_length_optimization",
    "summary length balancing": "summary_length_optimization",
    "summary length moderation": "summary_length_optimization",
    "summary length reduction": "summary_length_optimization",
    "summary length increase": "summary_length_optimization",
    "summary length decrease": "summary_length_optimization",
    "summary length maximization": "summary_length_optimization",
    "summary length minimization": "summary_length_optimization",
    "slo": "summary_length_optimization",

    # Bullet Point Distillation
    "bullet point distillation": "bullet_point_distillation",
    "bullet distillation": "bullet_point_distillation",
    "bullet points": "bullet_point_distillation",
    "bullets": "bullet_point_distillation",
    "bulleting": "bullet_point_distillation",
    "bullet summary": "bullet_point_distillation",
    "bullet list": "bullet_point_distillation",
    "bullet extraction": "bullet_point_distillation",
    "bullet generation": "bullet_point_distillation",
    "bullet creation": "bullet_point_distillation",
    "bullet synthesis": "bullet_point_distillation",
    "bullet point summary": "bullet_point_distillation",
    "bulleted summary": "bullet_point_distillation",
    "bulleted list": "bullet_point_distillation",
    "bulleted points": "bullet_point_distillation",
    "bulletized summary": "bullet_point_distillation",
    "bulletized points": "bullet_point_distillation",
    "bulletize": "bullet_point_distillation",
    "bulletize summary": "bullet_point_distillation",
    "bp distillation": "bullet_point_distillation",
    "bp": "bullet_point_distillation",

    # Related terms, misspellings, abbreviations, and more synonyms
    "summarize": "executive_summary",
    "summarise": "executive_summary",
    "summarising": "executive_summary",
    "summarizing": "executive_summary",
    "summarized": "executive_summary",
    "summarised": "executive_summary",
    "summarizer": "executive_summary",
    "summariser": "executive_summary",
    "summary generator": "executive_summary",
    "summary generation": "executive_summary",
    "sumary": "executive_summary",
    "sumarry": "executive_summary",
    "summarry": "executive_summary",
    "sum-up": "executive_summary",
    "sum up": "executive_summary",

    "findings extraction": "key_findings",
    "finding extraction": "key_findings",
    "findings extract": "key_findings",
    "finding extract": "key_findings",
    "key finding": "key_findings",
    "main finding": "key_findings",
    "critical finding": "key_findings",
    "important finding": "key_findings",
    "salient finding": "key_findings",
    "principal finding": "key_findings",
    "core finding": "key_findings",
    "essential finding": "key_findings",
    "notable finding": "key_findings",
    "highlight": "key_findings",
    "highlights section": "key_findings",

    "risk": "risk_highlight",
    "rsk": "risk_highlight",
    "risc": "risk_highlight",
    "riks": "risk_highlight",
    "rsk highlight": "risk_highlight",
    "rsk highlights": "risk_highlight",

    "recommend": "recommendation_synthesis",
    "recommending": "recommendation_synthesis",
    "recommended": "recommendation_synthesis",
    "recommender": "recommendation_synthesis",
    "rec": "recommendation_synthesis",
    "recommendations section": "recommendation_synthesis",
    "recommendations summary": "recommendation_synthesis",

    "aggregate": "multi_source_aggregation",
    "aggregator": "multi_source_aggregation",
    "aggregated": "multi_source_aggregation",
    "aggregation section": "multi_source_aggregation",
    "aggregation summary": "multi_source_aggregation",

    "abstract section": "document_abstract_generation",
    "abstracts": "document_abstract_generation",
    "abstracted": "document_abstract_generation",

    "prioritize": "findings_prioritization",
    "prioritise": "findings_prioritization",
    "prioritized": "findings_prioritization",
    "prioritised": "findings_prioritization",
    "prioritizing": "findings_prioritization",
    "prioritising": "findings_prioritization",
    "prioritization section": "findings_prioritization",
    "prioritisation": "findings_prioritization",

    "filtering": "materiality_filtering",
    "filter": "materiality_filtering",
    "filtered": "materiality_filtering",
    "filters": "materiality_filtering",
    "filter section": "materiality_filtering",

    "audience": "audience_appropriate_language",
    "audiences": "audience_appropriate_language",
    "audience section": "audience_appropriate_language",
    "audience summary": "audience_appropriate_language",

    "length": "summary_length_optimization",
    "length section": "summary_length_optimization",
    "length summary": "summary_length_optimization",

    "bullet": "bullet_point_distillation",
    "bulleted": "bullet_point_distillation",
    "bulletpoint": "bullet_point_distillation",
    "bulletpoints": "bullet_point_distillation",
    "bulletpoint summary": "bullet_point_distillation",
    "bulletpoint distillation": "bullet_point_distillation",
    "bulletpoint extraction": "bullet_point_distillation",
    "bulletpoint generation": "bullet_point_distillation",
    "bulletpoint creation": "bullet_point_distillation",
    "bulletpoint synthesis": "bullet_point_distillation",
    "bp summary": "bullet_point_distillation",
    "bp section": "bullet_point_distillation",

    # Add more synonyms, misspellings, and abbreviations to reach 200+ entries
    "summarising section": "executive_summary",
    "summarizing section": "executive_summary",
    "summarized section": "executive_summary",
    "summarised section": "executive_summary",
    "summary section": "executive_summary",
    "synopsys": "executive_summary",
    "synopses": "executive_summary",
    "synopsys section": "executive_summary",
    "overview section": "executive_summary",
    "overview summary": "executive_summary",
    "overview paragraph": "executive_summary",
    "overview statement": "executive_summary",
    "overview report": "executive_summary",
    "management overview": "executive_summary",
    "management synopsis": "executive_summary",
    "management abstract": "executive_summary",
    "management sum": "executive_summary",
    "mgmt summary": "executive_summary",
    "mgmt sum": "executive_summary",
    "mgmt overview": "executive_summary",

    "finding": "key_findings",
    "findng": "key_findings",
    "findngs": "key_findings",
    "keypoint": "key_findings",
    "keypoints": "key_findings",
    "mainpoint": "key_findings",
    "mainpoints": "key_findings",
    "takeaway": "key_findings",
    "take aways": "key_findings",
    "take-aways": "key_findings",
    "take-away": "key_findings",
    "highlight section": "key_findings",
    "highlighted": "key_findings",

    "risk finding": "risk_highlight",
    "risk issue": "risk_highlight",
    "risk factor": "risk_highlight",
    "risk assessment section": "risk_highlight",
    "risk evaluation section": "risk_highlight",
    "risk analysis section": "risk_highlight",
    "risk identification section": "risk_highlight",
    "risk summary section": "risk_highlight",
    "risk overview section": "risk_highlight",
    "risk section": "risk_highlight",

    "recommend section": "recommendation_synthesis",
    "recommend summary": "recommendation_synthesis",
    "recommendation synth": "recommendation_synthesis",
    "recommendation synthesize": "recommendation_synthesis",
    "recommendation synthesise": "recommendation_synthesis",
    "recommendation synthesized": "recommendation_synthesis",
    "recommendation synthesised": "recommendation_synthesis",
    "recommendation generator": "recommendation_synthesis",
    "recommendation generation section": "recommendation_synthesis",

    "aggregation findings": "multi_source_aggregation",
    "aggregation generator": "multi_source_aggregation",
    "aggregation generation": "multi_source_aggregation",
    "aggregation creation": "multi_source_aggregation",
    "aggregation synthesis": "multi_source_aggregation",
    "aggregation synthesize": "multi_source_aggregation",
    "aggregation synthesise": "multi_source_aggregation",
    "aggregation synthesized": "multi_source_aggregation",
    "aggregation synthesised": "multi_source_aggregation",

    "abstract generator": "document_abstract_generation",
    "abstract generators": "document_abstract_generation",
    "abstract generators section": "document_abstract_generation",
    "document abstract section": "document_abstract_generation",

    "priority": "findings_prioritization",
    "prioritization findings": "findings_prioritization",
    "prioritization generator": "findings_prioritization",
    "prioritization generation": "findings_prioritization",
    "prioritization creation": "findings_prioritization",
    "prioritization synthesis": "findings_prioritization",
    "prioritization synthesize": "findings_prioritization",
    "prioritization synthesise": "findings_prioritization",
    "prioritization synthesized": "findings_prioritization",
    "prioritization synthesised": "findings_prioritization",

    "materiality generator": "materiality_filtering",
    "materiality generators": "materiality_filtering",
    "materiality generators section": "materiality_filtering",
    "materiality section": "materiality_filtering",
    "materiality summary": "materiality_filtering",

    "audience generator": "audience_appropriate_language",
    "audience generators": "audience_appropriate_language",
    "audience generators section": "audience_appropriate_language",
    "audience language section": "audience_appropriate_language",
    "audience language summary": "audience_appropriate_language",

    "length generator": "summary_length_optimization",
    "length generators": "summary_length_optimization",
    "length generators section": "summary_length_optimization",
    "length optimization section": "summary_length_optimization",
    "length optimization summary": "summary_length_optimization",

    "bullet generator": "bullet_point_distillation",
    "bullet generators": "bullet_point_distillation",
    "bullet generators section": "bullet_point_distillation",
    "bullet distillation section": "bullet_point_distillation",
    "bullet distillation summary": "bullet_point_distillation",
    "bullet summary section": "bullet_point_distillation",
    "bulleted summary section": "bullet_point_distillation",
    "bulleted list section": "bullet_point_distillation",

    # Even more synonyms, misspellings, and abbreviations
    "summarization section": "executive_summary",
    "summarization summary": "executive_summary",
    "summarisation": "executive_summary",
    "summarisation section": "executive_summary",
    "summarisation summary": "executive_summary",
    "sum-up section": "executive_summary",
    "sum-up summary": "executive_summary",
    "sum up section": "executive_summary",
    "sum up summary": "executive_summary",
    "mgmt": "executive_summary",

    "finding section": "key_findings",
    "finding summary": "key_findings",
    "finding synth": "key_findings",
    "finding synthesize": "key_findings",
    "finding synthesise": "key_findings",
    "finding synthesized": "key_findings",
    "finding synthesised": "key_findings",
    "findings synth": "key_findings",
    "findings synthesize": "key_findings",
    "findings synthesise": "key_findings",
    "findings synthesized": "key_findings",
    "findings synthesised": "key_findings",

    "risk synth": "risk_highlight",
    "risk synthesize": "risk_highlight",
    "risk synthesise": "risk_highlight",
    "risk synthesized": "risk_highlight",
    "risk synthesised": "risk_highlight",

    "rec synthesize": "recommendation_synthesis",
    "rec synthesise": "recommendation_synthesis",
    "rec synthesized": "recommendation_synthesis",
    "rec synthesised": "recommendation_synthesis",

    "agg": "multi_source_aggregation",
    "aggs": "multi_source_aggregation",
    "agg synth": "multi_source_aggregation",
    "agg synthesize": "multi_source_aggregation",
    "agg synthesise": "multi_source_aggregation",
    "agg synthesized": "multi_source_aggregation",
    "agg synthesised": "multi_source_aggregation",

    "abs": "document_abstract_generation",
    "abs synth": "document_abstract_generation",
    "abs synthesize": "document_abstract_generation",
    "abs synthesise": "document_abstract_generation",
    "abs synthesized": "document_abstract_generation",
    "abs synthesised": "document_abstract_generation",

    "prio": "findings_prioritization",
    "prios": "findings_prioritization",
    "prio synth": "findings_prioritization",
    "prio synthesize": "findings_prioritization",
    "prio synthesise": "findings_prioritization",
    "prio synthesized": "findings_prioritization",
    "prio synthesised": "findings_prioritization",

    "mat synth": "materiality_filtering",
    "mat synthesize": "materiality_filtering",
    "mat synthesise": "materiality_filtering",
    "mat synthesized": "materiality_filtering",
    "mat synthesised": "materiality_filtering",

    "aud synth": "audience_appropriate_language",
    "aud synthesize": "audience_appropriate_language",
    "aud synthesise": "audience_appropriate_language",
    "aud synthesized": "audience_appropriate_language",
    "aud synthesised": "audience_appropriate_language",

    "len synth": "summary_length_optimization",
    "len synthesize": "summary_length_optimization",
    "len synthesise": "summary_length_optimization",
    "len synthesized": "summary_length_optimization",
    "len synthesised": "summary_length_optimization",

    "bp synth": "bullet_point_distillation",
    "bp synthesize": "bullet_point_distillation",
    "bp synthesise": "bullet_point_distillation",
    "bp synthesized": "bullet_point_distillation",
    "bp synthesised": "bullet_point_distillation",
}

_EXPECTED_ENTRY_COUNT = 236

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def _normalize_string(s):
    s = s.strip().lower()
    s = unicodedata.normalize("NFKC", s)
    return s

def normalize_term(term: str) -> str:
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    return [k for k, v in SEMANTIC_MAP.items() if v == norm]

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)