import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AUTO11_tire_systems"
SEMANTIC_MAP_ENGINE = "AUTO11"
# --- Start of SEMANTIC_MAP ---
SEMANTIC_MAP = {
    # Radial vs Bias-Ply Construction
    "radial": "radial_construction",
    "radial tire": "radial_construction",
    "radial tyres": "radial_construction",
    "radial ply": "radial_construction",
    "radial-ply": "radial_construction",
    "radial construction": "radial_construction",
    "r-ply": "radial_construction",
    "r ply": "radial_construction",
    "radials": "radial_construction",
    "r tire": "radial_construction",
    "r tyre": "radial_construction",
    "bias": "bias_ply_construction",
    "bias-ply": "bias_ply_construction",
    "bias ply": "bias_ply_construction",
    "bias tire": "bias_ply_construction",
    "bias tyres": "bias_ply_construction",
    "cross ply": "bias_ply_construction",
    "cross-ply": "bias_ply_construction",
    "diagonal ply": "bias_ply_construction",
    "d ply": "bias_ply_construction",
    "d-ply": "bias_ply_construction",
    "bias belted": "bias_ply_construction",
    "belted bias": "bias_ply_construction",
    "belted-bias": "bias_ply_construction",
    "ply rating": "ply_rating",
    "plyrate": "ply_rating",
    "ply-rate": "ply_rating",
    "ply": "ply_rating",
    "plys": "ply_rating",
    "ply count": "ply_rating",
    "ply-count": "ply_rating",
    "ply number": "ply_rating",
    "plynumber": "ply_rating",
    "ply construction": "ply_rating",
    "tire construction": "tire_construction",
    "tyre construction": "tire_construction",
    "construction type": "tire_construction",
    "tire build": "tire_construction",
    "tyre build": "tire_construction",
    "tire structure": "tire_construction",
    "tyre structure": "tire_construction",

    # Center Wear Pattern Analysis
    "center wear": "center_wear_pattern",
    "centre wear": "center_wear_pattern",
    "central wear": "center_wear_pattern",
    "middle wear": "center_wear_pattern",
    "overinflation wear": "center_wear_pattern",
    "over-inflation wear": "center_wear_pattern",
    "over inflated wear": "center_wear_pattern",
    "over-inflated wear": "center_wear_pattern",
    "overinflated": "over_inflation",
    "over-inflated": "over_inflation",
    "overinflation": "over_inflation",
    "over inflation": "over_inflation",
    "center tread wear": "center_wear_pattern",
    "tread center wear": "center_wear_pattern",
    "tread middle wear": "center_wear_pattern",
    "treadwear center": "center_wear_pattern",
    "tread wear center": "center_wear_pattern",
    "treadwear middle": "center_wear_pattern",

    # Shoulder Wear Pattern Analysis
    "shoulder wear": "shoulder_wear_pattern",
    "edge wear": "shoulder_wear_pattern",
    "shoulder tread wear": "shoulder_wear_pattern",
    "tread shoulder wear": "shoulder_wear_pattern",
    "tread edge wear": "shoulder_wear_pattern",
    "side wear": "shoulder_wear_pattern",
    "side tread wear": "shoulder_wear_pattern",
    "underinflation wear": "shoulder_wear_pattern",
    "under-inflation wear": "shoulder_wear_pattern",
    "underinflated": "under_inflation",
    "under-inflated": "under_inflation",
    "underinflation": "under_inflation",
    "under inflation": "under_inflation",
    "shoulder feathering": "shoulder_wear_pattern",
    "shoulder cupping": "shoulder_wear_pattern",

    # Cupping and Scalloping Wear
    "cupping": "cupping_scalloping_wear",
    "scalloping": "cupping_scalloping_wear",
    "tire cupping": "cupping_scalloping_wear",
    "tyre cupping": "cupping_scalloping_wear",
    "tire scalloping": "cupping_scalloping_wear",
    "tyre scalloping": "cupping_scalloping_wear",
    "heel toe wear": "cupping_scalloping_wear",
    "heel-toe wear": "cupping_scalloping_wear",
    "heel and toe wear": "cupping_scalloping_wear",
    "high low wear": "cupping_scalloping_wear",
    "high-low wear": "cupping_scalloping_wear",
    "wavy wear": "cupping_scalloping_wear",
    "bumpy wear": "cupping_scalloping_wear",
    "patchy wear": "cupping_scalloping_wear",
    "spotty wear": "cupping_scalloping_wear",
    "choppy wear": "cupping_scalloping_wear",
    "irregular wear": "cupping_scalloping_wear",
    "scalloped": "cupping_scalloping_wear",
    "cupped": "cupping_scalloping_wear",

    # Feathering Wear Pattern
    "feathering": "feathering_wear_pattern",
    "feathered wear": "feathering_wear_pattern",
    "tire feathering": "feathering_wear_pattern",
    "tyre feathering": "feathering_wear_pattern",
    "feather edge": "feathering_wear_pattern",
    "feathered edge": "feathering_wear_pattern",
    "tread feathering": "feathering_wear_pattern",
    "feather wear": "feathering_wear_pattern",
    "scrub wear": "feathering_wear_pattern",
    "scrubbing": "feathering_wear_pattern",
    "toe wear": "feathering_wear_pattern",
    "alignment feathering": "feathering_wear_pattern",
    "toe in wear": "feathering_wear_pattern",
    "toe-in wear": "feathering_wear_pattern",
    "toe out wear": "feathering_wear_pattern",
    "toe-out wear": "feathering_wear_pattern",

    # Load Index and Speed Rating Compliance
    "load index": "load_index",
    "load rating": "load_index",
    "load capacity": "load_index",
    "load range": "load_index",
    "li": "load_index",
    "speed rating": "speed_rating",
    "speed symbol": "speed_rating",
    "speed code": "speed_rating",
    "sr": "speed_rating",
    "max speed": "speed_rating",
    "maximum speed": "speed_rating",
    "max load": "load_index",
    "maximum load": "load_index",
    "load limit": "load_index",
    "service description": "load_speed_compliance",
    "load/speed rating": "load_speed_compliance",
    "load & speed rating": "load_speed_compliance",
    "load and speed rating": "load_speed_compliance",
    "load/speed index": "load_speed_compliance",
    "load & speed index": "load_speed_compliance",
    "load and speed index": "load_speed_compliance",
    "load compliance": "load_speed_compliance",
    "speed compliance": "load_speed_compliance",

    # Seasonal Tire Selection - Winter vs All-Season
    "winter tire": "winter_tire",
    "winter tyres": "winter_tire",
    "snow tire": "winter_tire",
    "snow tyres": "winter_tire",
    "studless": "winter_tire",
    "studded": "winter_tire",
    "ice tire": "winter_tire",
    "ice tyres": "winter_tire",
    "all season": "all_season_tire",
    "all-season": "all_season_tire",
    "all season tire": "all_season_tire",
    "all season tyres": "all_season_tire",
    "all-weather": "all_season_tire",
    "all weather": "all_season_tire",
    "all weather tire": "all_season_tire",
    "all weather tyres": "all_season_tire",
    "summer tire": "summer_tire",
    "summer tyres": "summer_tire",
    "performance tire": "summer_tire",
    "performance tyres": "summer_tire",
    "seasonal tire": "seasonal_tire_selection",
    "seasonal tyres": "seasonal_tire_selection",
    "seasonal selection": "seasonal_tire_selection",
    "tire selection": "seasonal_tire_selection",
    "tyre selection": "seasonal_tire_selection",
    "seasonal change": "seasonal_tire_selection",
    "seasonal swap": "seasonal_tire_selection",
    "tire swap": "seasonal_tire_selection",
    "tyre swap": "seasonal_tire_selection",
    "tire changeover": "seasonal_tire_selection",
    "tyre changeover": "seasonal_tire_selection",
    "tire change": "seasonal_tire_selection",
    "tyre change": "seasonal_tire_selection",

    # Tire Pressure Monitoring System (TPMS) Function and Limitations
    "tpms": "tpms",
    "tire pressure monitoring system": "tpms",
    "tyre pressure monitoring system": "tpms",
    "tpms sensor": "tpms",
    "tpms sensors": "tpms",
    "tpms warning": "tpms",
    "tpms light": "tpms",
    "tpms malfunction": "tpms",
    "tpms error": "tpms",
    "tpms reset": "tpms",
    "tpms fault": "tpms",
    "tpms limitation": "tpms_limitations",
    "tpms limitations": "tpms_limitations",
    "tpms function": "tpms_function",
    "tpms functions": "tpms_function",
    "tpms operation": "tpms_function",
    "tpms working": "tpms_function",
    "tpms accuracy": "tpms_limitations",
    "tpms range": "tpms_limitations",
    "tpms battery": "tpms_limitations",
    "tpms life": "tpms_limitations",
    "tpms replacement": "tpms_limitations",
    "tpms system": "tpms",
    "direct tpms": "tpms_direct",
    "indirect tpms": "tpms_indirect",
    "tpms direct": "tpms_direct",
    "tpms indirect": "tpms_indirect",

    # Sidewall Impact Damage and Bubble Formation
    "sidewall damage": "sidewall_impact_damage",
    "sidewall impact": "sidewall_impact_damage",
    "sidewall bubble": "sidewall_bubble_formation",
    "sidewall bulge": "sidewall_bubble_formation",
    "sidewall blister": "sidewall_bubble_formation",
    "sidewall separation": "sidewall_impact_damage",
    "sidewall crack": "sidewall_impact_damage",
    "sidewall split": "sidewall_impact_damage",
    "sidewall cut": "sidewall_impact_damage",
    "sidewall tear": "sidewall_impact_damage",
    "sidewall puncture": "sidewall_impact_damage",
    "bubble": "sidewall_bubble_formation",
    "bulge": "sidewall_bubble_formation",
    "blister": "sidewall_bubble_formation",
    "bubble on tire": "sidewall_bubble_formation",
    "bubble on tyre": "sidewall_bubble_formation",
    "bulge on tire": "sidewall_bubble_formation",
    "bulge on tyre": "sidewall_bubble_formation",
    "sidewall defect": "sidewall_impact_damage",
    "sidewall weakness": "sidewall_impact_damage",
    "sidewall failure": "sidewall_impact_damage",
    "impact break": "sidewall_impact_damage",
    "impact damage": "sidewall_impact_damage",

    # Hydroplaning Dynamics and Tread Depth Requirements
    "hydroplaning": "hydroplaning_dynamics",
    "hydroplaning dynamics": "hydroplaning_dynamics",
    "hydroplaning risk": "hydroplaning_dynamics",
    "hydroplaning danger": "hydroplaning_dynamics",
    "hydroplaning speed": "hydroplaning_dynamics",
    "hydroplaning threshold": "hydroplaning_dynamics",
    "aquaplaning": "hydroplaning_dynamics",
    "aquaplaning dynamics": "hydroplaning_dynamics",
    "aquaplaning risk": "hydroplaning_dynamics",
    "tread depth": "tread_depth_requirement",
    "tread depth requirement": "tread_depth_requirement",
    "minimum tread depth": "tread_depth_requirement",
    "min tread depth": "tread_depth_requirement",
    "treadwear depth": "tread_depth_requirement",
    "tread wear depth": "tread_depth_requirement",
    "tread gauge": "tread_depth_requirement",
    "tread measurement": "tread_depth_requirement",
    "tread depth gauge": "tread_depth_requirement",
    "tread depth check": "tread_depth_requirement",
    "tread depth test": "tread_depth_requirement",
    "tread depth indicator": "tread_depth_requirement",
    "tread indicator": "tread_depth_requirement",
    "tread wear indicator": "tread_depth_requirement",
    "twi": "tread_depth_requirement",

    # Tire Age and Date Code Interpretation
    "tire age": "tire_age",
    "tyre age": "tire_age",
    "tire date": "tire_date_code",
    "tyre date": "tire_date_code",
    "tire date code": "tire_date_code",
    "tyre date code": "tire_date_code",
    "dot code": "tire_date_code",
    "dot number": "tire_date_code",
    "dot marking": "tire_date_code",
    "dot": "tire_date_code",
    "manufacture date": "tire_date_code",
    "manufacturing date": "tire_date_code",
    "production date": "tire_date_code",
    "date of manufacture": "tire_date_code",
    "date of production": "tire_date_code",
    "date code": "tire_date_code",
    "age code": "tire_date_code",
    "tire expiry": "tire_age",
    "tire expiration": "tire_age",
    "tire shelf life": "tire_age",
    "tyre shelf life": "tire_age",
    "tire life": "tire_age",
    "tyre life": "tire_age",
    "tire lifespan": "tire_age",
    "tyre lifespan": "tire_age",
    "tire aging": "tire_age",
    "tyre aging": "tire_age",
    "tire old": "tire_age",
    "tyre old": "tire_age",

    # Run-Flat Tire Technology and Limitations
    "run flat": "run_flat_tire",
    "run-flat": "run_flat_tire",
    "runflat": "run_flat_tire",
    "run flat tire": "run_flat_tire",
    "run flat tyres": "run_flat_tire",
    "run-flat tire": "run_flat_tire",
    "run-flat tyres": "run_flat_tire",
    "rft": "run_flat_tire",
    "rsc": "run_flat_tire",
    "runflat technology": "run_flat_tire",
    "run-flat technology": "run_flat_tire",
    "run flat technology": "run_flat_tire",
    "runflat limitation": "run_flat_limitations",
    "run-flat limitation": "run_flat_limitations",
    "run flat limitation": "run_flat_limitations",
    "runflat limitations": "run_flat_limitations",
    "run-flat limitations": "run_flat_limitations",
    "run flat limitations": "run_flat_limitations",
    "runflat drawbacks": "run_flat_limitations",
    "run-flat drawbacks": "run_flat_limitations",
    "run flat drawbacks": "run_flat_limitations",
    "runflat disadvantage": "run_flat_limitations",
    "run-flat disadvantage": "run_flat_limitations",
    "run flat disadvantage": "run_flat_limitations",
    "runflat disadvantages": "run_flat_limitations",
    "run-flat disadvantages": "run_flat_limitations",
    "run flat disadvantages": "run_flat_limitations",

    # Wheel Balance and Vibration Diagnosis
    "wheel balance": "wheel_balance",
    "wheel balancing": "wheel_balance",
    "tire balance": "wheel_balance",
    "tyre balance": "wheel_balance",
    "tire balancing": "wheel_balance",
    "tyre balancing": "wheel_balance",
    "unbalanced wheel": "wheel_balance",
    "unbalanced tire": "wheel_balance",
    "unbalanced tyre": "wheel_balance",
    "vibration": "vibration_diagnosis",
    "wheel vibration": "vibration_diagnosis",
    "tire vibration": "vibration_diagnosis",
    "tyre vibration": "vibration_diagnosis",
    "vibration diagnosis": "vibration_diagnosis",
    "vibration issue": "vibration_diagnosis",
    "vibration problem": "vibration_diagnosis",
    "vibration complaint": "vibration_diagnosis",
    "shimmy": "vibration_diagnosis",
    "wobble": "vibration_diagnosis",
    "wheel shimmy": "vibration_diagnosis",
    "wheel wobble": "vibration_diagnosis",
    "tire shimmy": "vibration_diagnosis",
    "tyre shimmy": "vibration_diagnosis",
    "tire wobble": "vibration_diagnosis",
    "tyre wobble": "vibration_diagnosis",
    "out of balance": "wheel_balance",
    "out-of-balance": "wheel_balance",
    "imbalance": "wheel_balance",
    "dynamic balance": "wheel_balance",
    "static balance": "wheel_balance",
    "dynamic balancing": "wheel_balance",
    "static balancing": "wheel_balance",
    "road force": "vibration_diagnosis",
    "road force variation": "vibration_diagnosis",
    "rfv": "vibration_diagnosis",

    # Nitrogen Inflation vs Compressed Air
    "nitrogen inflation": "nitrogen_inflation",
    "nitrogen fill": "nitrogen_inflation",
    "nitrogen": "nitrogen_inflation",
    "n2 inflation": "nitrogen_inflation",
    "n2 fill": "nitrogen_inflation",
    "n2": "nitrogen_inflation",
    "compressed air": "compressed_air_inflation",
    "air inflation": "compressed_air_inflation",
    "air fill": "compressed_air_inflation",
    "air": "compressed_air_inflation",
    "air vs nitrogen": "nitrogen_vs_air",
    "nitrogen vs air": "nitrogen_vs_air",
    "nitrogen versus air": "nitrogen_vs_air",
    "air versus nitrogen": "nitrogen_vs_air",
    "nitrogen benefits": "nitrogen_inflation",
    "nitrogen advantage": "nitrogen_inflation",
    "nitrogen disadvantages": "nitrogen_inflation",
    "nitrogen drawback": "nitrogen_inflation",
    "nitrogen purity": "nitrogen_inflation",
    "nitrogen loss": "nitrogen_inflation",
    "air loss": "compressed_air_inflation",
    "moisture in air": "compressed_air_inflation",
    "moisture in nitrogen": "nitrogen_inflation",

    # Tire Rotation Patterns and Intervals
    "tire rotation": "tire_rotation",
    "tyre rotation": "tire_rotation",
    "rotation pattern": "tire_rotation_pattern",
    "rotation patterns": "tire_rotation_pattern",
    "rotation interval": "tire_rotation_interval",
    "rotation intervals": "tire_rotation_interval",
    "rotation schedule": "tire_rotation_interval",
    "rotation frequency": "tire_rotation_interval",
    "rotation timing": "tire_rotation_interval",
    "rotation advice": "tire_rotation_interval",
    "rotation recommendation": "tire_rotation_interval",
    "rotation procedure": "tire_rotation_pattern",
    "rotation method": "tire_rotation_pattern",
    "rotation diagram": "tire_rotation_pattern",
    "rotation chart": "tire_rotation_pattern",
    "cross rotation": "tire_rotation_pattern",
    "forward cross": "tire_rotation_pattern",
    "rearward cross": "tire_rotation_pattern",
    "x pattern": "tire_rotation_pattern",
    "x-pattern": "tire_rotation_pattern",
    "front to rear": "tire_rotation_pattern",
    "rear to front": "tire_rotation_pattern",
    "side to side": "tire_rotation_pattern",
    "side-to-side": "tire_rotation_pattern",
    "four tire rotation": "tire_rotation_pattern",
    "five tire rotation": "tire_rotation_pattern",
    "rotation mileage": "tire_rotation_interval",
    "rotation km": "tire_rotation_interval",
    "rotation kilometers": "tire_rotation_interval",
    "rotation miles": "tire_rotation_interval",

    # Plus-Sizing and Minus-Sizing Tire Changes
    "plus sizing": "plus_sizing",
    "plus-sizing": "plus_sizing",
    "plus size": "plus_sizing",
    "plus-size": "plus_sizing",
    "plus sized": "plus_sizing",
    "plus-sized": "plus_sizing",
    "upsizing": "plus_sizing",
    "up sizing": "plus_sizing",
    "up-size": "plus_sizing",
    "up size": "plus_sizing",
    "up-sized": "plus_sizing",
    "up sized": "plus_sizing",
    "upsize": "plus_sizing",
    "up-size tire": "plus_sizing",
    "upsize tire": "plus_sizing",
    "upsize tyres": "plus_sizing",
    "up-size tyres": "plus_sizing",
    "larger wheels": "plus_sizing",
    "bigger wheels": "plus_sizing",
    "minus sizing": "minus_sizing",
    "minus-sizing": "minus_sizing",
    "minus size": "minus_sizing",
    "minus-size": "minus_sizing",
    "minus sized": "minus_sizing",
    "minus-sized": "minus_sizing",
    "downsizing": "minus_sizing",
    "down sizing": "minus_sizing",
    "down-size": "minus_sizing",
    "down size": "minus_sizing",
    "down-sized": "minus_sizing",
    "down sized": "minus_sizing",
    "downsize": "minus_sizing",
    "down-size tire": "minus_sizing",
    "downsize tire": "minus_sizing",
    "downsize tyres": "minus_sizing",
    "down-size tyres": "minus_sizing",
    "smaller wheels": "minus_sizing",
    "smaller rims": "minus_sizing",
    "bigger tires": "plus_sizing",
    "bigger tyres": "plus_sizing",
    "smaller tires": "minus_sizing",
    "smaller tyres": "minus_sizing",
    "wheel plus sizing": "plus_sizing",
    "wheel minus sizing": "minus_sizing",
    "tire plus sizing": "plus_sizing",
    "tyre plus sizing": "plus_sizing",
    "tire minus sizing": "minus_sizing",
    "tyre minus sizing": "minus_sizing",
    "tire upsizing": "plus_sizing",
    "tyre upsizing": "plus_sizing",
    "tire downsizing": "minus_sizing",
    "tyre downsizing": "minus_sizing",
    "rim upsizing": "plus_sizing",
    "rim downsizing": "minus_sizing",
    "plus one": "plus_sizing",
    "plus two": "plus_sizing",
    "minus one": "minus_sizing",
    "minus two": "minus_sizing",
    "upgrading wheels": "plus_sizing",
    "downgrading wheels": "minus_sizing",
    "upgrading rims": "plus_sizing",
    "downgrading rims": "minus_sizing",
    "plus size conversion": "plus_sizing",
    "minus size conversion": "minus_sizing",
    "plus size fitment": "plus_sizing",
    "minus size fitment": "minus_sizing",
    "plus size tire": "plus_sizing",
    "minus size tire": "minus_sizing",
    "plus size rim": "plus_sizing",
    "minus size rim": "minus_sizing",
    "plus size wheel": "plus_sizing",
    "minus size wheel": "minus_sizing",
    "plus fitment": "plus_sizing",
    "minus fitment": "minus_sizing",
    "plus sizing effect": "plus_sizing",
    "minus sizing effect": "minus_sizing",
    "plus sizing pros": "plus_sizing",
    "plus sizing cons": "plus_sizing",
    "minus sizing pros": "minus_sizing",
    "minus sizing cons": "minus_sizing",
    "plus sizing advantages": "plus_sizing",
    "plus sizing disadvantages": "plus_sizing",
    "minus sizing advantages": "minus_sizing",
    "minus sizing disadvantages": "minus_sizing",
}

_EXPECTED_ENTRY_COUNT = 271

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    expected_count = _EXPECTED_ENTRY_COUNT
    status = "OK" if actual_count == expected_count else "COUNT_MISMATCH"
    hash_now = _compute_map_hash()
    is_valid = (hash_now == _MAP_INTEGRITY_HASH) and (actual_count == expected_count)
    return {
        "status": status,
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
        "expected_count": expected_count,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_string(s):
    s = s.lower()
    s = s.replace("’", "'")
    s = re.sub(r"[\u2013\u2014]", "-", s)
    s = re.sub(r"\s+", " ", s)
    s = s.strip()
    return s

def normalize_term(term: str) -> str:
    term_norm = _normalize_string(term)
    return SEMANTIC_MAP.get(term_norm, term_norm)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    return [k for k, v in SEMANTIC_MAP.items() if v == norm]

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)