import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "REG10 Team"
SEMANTIC_MAP_ENGINE = "REG10_data_privacy_regulatory"

SEMANTIC_MAP = {
    # CCPA Consumer Rights
    "ccpa": "ccpa",
    "california consumer privacy act": "ccpa",
    "california privacy law": "ccpa",
    "ca privacy act": "ccpa",
    "ccpa rights": "ccpa_consumer_rights",
    "consumer rights under ccpa": "ccpa_consumer_rights",
    "access right": "ccpa_access",
    "right to access": "ccpa_access",
    "data access request": "ccpa_access",
    "access request": "ccpa_access",
    "request to know": "ccpa_access",
    "right to know": "ccpa_access",
    "know my data": "ccpa_access",
    "deletion right": "ccpa_deletion",
    "right to delete": "ccpa_deletion",
    "delete my data": "ccpa_deletion",
    "data deletion request": "ccpa_deletion",
    "erase data": "ccpa_deletion",
    "right to erasure": "ccpa_deletion",
    "portability right": "ccpa_portability",
    "right to data portability": "ccpa_portability",
    "data portability": "ccpa_portability",
    "transfer my data": "ccpa_portability",
    "download my data": "ccpa_portability",
    "data download": "ccpa_portability",
    "cpra": "cpra",
    "california privacy rights act": "cpra",
    "cpra amendments": "cpra_amendments",
    "sensitive personal information": "cpra_sensitive_personal_information",
    "spi": "cpra_sensitive_personal_information",
    "sensitive info": "cpra_sensitive_personal_information",
    "opt-out right": "cpra_opt_out",
    "opt out": "cpra_opt_out",
    "right to opt out": "cpra_opt_out",
    "do not sell": "cpra_opt_out",
    "do not share": "cpra_opt_out",
    "do not sell my info": "cpra_opt_out",
    "do not sell my data": "cpra_opt_out",
    "sale of personal information": "cpra_opt_out",
    "sharing of personal information": "cpra_opt_out",
    "opt-out of sale": "cpra_opt_out",
    "opt-out of sharing": "cpra_opt_out",
    "ccpa opt-out": "cpra_opt_out",
    "cpra opt-out": "cpra_opt_out",
    "ccpa sensitive info": "cpra_sensitive_personal_information",
    "cpra sensitive info": "cpra_sensitive_personal_information",
    "ccpa spi": "cpra_sensitive_personal_information",
    "cpra spi": "cpra_sensitive_personal_information",

    # GDPR Lawful Basis and Data Minimization
    "gdpr": "gdpr",
    "general data protection regulation": "gdpr",
    "eu gdpr": "gdpr",
    "lawful basis": "gdpr_lawful_basis",
    "legal basis": "gdpr_lawful_basis",
    "lawful grounds": "gdpr_lawful_basis",
    "legal grounds": "gdpr_lawful_basis",
    "processing basis": "gdpr_lawful_basis",
    "consent": "gdpr_lawful_basis_consent",
    "explicit consent": "gdpr_lawful_basis_consent",
    "informed consent": "gdpr_lawful_basis_consent",
    "contractual necessity": "gdpr_lawful_basis_contract",
    "contract": "gdpr_lawful_basis_contract",
    "performance of contract": "gdpr_lawful_basis_contract",
    "legitimate interests": "gdpr_lawful_basis_legitimate_interest",
    "legitimate interest": "gdpr_lawful_basis_legitimate_interest",
    "public interest": "gdpr_lawful_basis_public_interest",
    "vital interests": "gdpr_lawful_basis_vital_interest",
    "legal obligation": "gdpr_lawful_basis_legal_obligation",
    "data minimization": "gdpr_data_minimization",
    "minimize data": "gdpr_data_minimization",
    "minimization": "gdpr_data_minimization",
    "minimal data": "gdpr_data_minimization",
    "only necessary data": "gdpr_data_minimization",
    "necessary data": "gdpr_data_minimization",
    "purpose limitation": "gdpr_purpose_limitation",
    "purpose limited": "gdpr_purpose_limitation",
    "limit purpose": "gdpr_purpose_limitation",

    # GDPR Data Subject Rights
    "data subject rights": "gdpr_data_subject_rights",
    "subject rights": "gdpr_data_subject_rights",
    "rights of data subjects": "gdpr_data_subject_rights",
    "right to access": "gdpr_access",
    "access right": "gdpr_access",
    "data access request": "gdpr_access",
    "right to rectification": "gdpr_rectification",
    "rectification right": "gdpr_rectification",
    "correct data": "gdpr_rectification",
    "correct my data": "gdpr_rectification",
    "fix data": "gdpr_rectification",
    "right to erasure": "gdpr_erasure",
    "erasure right": "gdpr_erasure",
    "delete my data": "gdpr_erasure",
    "right to be forgotten": "gdpr_erasure",
    "forgotten right": "gdpr_erasure",
    "right to data portability": "gdpr_portability",
    "portability right": "gdpr_portability",
    "data portability": "gdpr_portability",
    "transfer my data": "gdpr_portability",
    "download my data": "gdpr_portability",
    "right to restrict processing": "gdpr_restriction",
    "restriction right": "gdpr_restriction",
    "restrict processing": "gdpr_restriction",
    "right to object": "gdpr_object",
    "object right": "gdpr_object",
    "object to processing": "gdpr_object",
    "right to withdraw consent": "gdpr_withdraw_consent",
    "withdraw consent": "gdpr_withdraw_consent",
    "withdrawal of consent": "gdpr_withdraw_consent",

    # COPPA Parental Consent and Notice Requirements
    "coppa": "coppa",
    "children's online privacy protection act": "coppa",
    "child privacy law": "coppa",
    "parental consent": "coppa_parental_consent",
    "parental permission": "coppa_parental_consent",
    "parent consent": "coppa_parental_consent",
    "parental notice": "coppa_parental_notice",
    "parent notice": "coppa_parental_notice",
    "notice to parents": "coppa_parental_notice",
    "notice requirement": "coppa_parental_notice",
    "verifiable parental consent": "coppa_parental_consent",
    "vpc": "coppa_parental_consent",
    "child consent": "coppa_parental_consent",
    "children consent": "coppa_parental_consent",

    # FERPA Education Records Privacy and Disclosure Exceptions
    "ferpa": "ferpa",
    "family educational rights and privacy act": "ferpa",
    "education privacy law": "ferpa",
    "student privacy": "ferpa_student_privacy",
    "student record privacy": "ferpa_student_privacy",
    "education record": "ferpa_education_record",
    "student record": "ferpa_education_record",
    "school record": "ferpa_education_record",
    "record disclosure": "ferpa_disclosure_exception",
    "disclosure exception": "ferpa_disclosure_exception",
    "education record disclosure": "ferpa_disclosure_exception",
    "school record disclosure": "ferpa_disclosure_exception",
    "directory information": "ferpa_directory_information",
    "directory info": "ferpa_directory_information",
    "directory data": "ferpa_directory_information",
    "parental access": "ferpa_parental_access",
    "parent access": "ferpa_parental_access",
    "parent right": "ferpa_parental_access",

    # GLBA Privacy Rule and Safeguards for Financial Institutions
    "glba": "glba",
    "gramm-leach-bliley act": "glba",
    "financial privacy law": "glba",
    "privacy rule": "glba_privacy_rule",
    "glba privacy rule": "glba_privacy_rule",
    "safeguards rule": "glba_safeguards_rule",
    "glba safeguards rule": "glba_safeguards_rule",
    "financial institution": "glba_financial_institution",
    "bank privacy": "glba_financial_institution",
    "customer information": "glba_customer_information",
    "customer data": "glba_customer_information",
    "nonpublic personal information": "glba_customer_information",
    "npi": "glba_customer_information",
    "consumer information": "glba_customer_information",
    "consumer data": "glba_customer_information",

    # FTC Act Section 5 Unfair/Deceptive Privacy and Security Practices
    "ftc act": "ftc_act",
    "ftc section 5": "ftc_act_section_5",
    "section 5": "ftc_act_section_5",
    "unfair practices": "ftc_unfair_practices",
    "deceptive practices": "ftc_deceptive_practices",
    "unfair privacy practices": "ftc_unfair_practices",
    "deceptive privacy practices": "ftc_deceptive_practices",
    "unfair security practices": "ftc_unfair_practices",
    "deceptive security practices": "ftc_deceptive_practices",
    "unfair or deceptive acts": "ftc_unfair_deceptive_practices",
    "udap": "ftc_unfair_deceptive_practices",
    "unfair and deceptive acts": "ftc_unfair_deceptive_practices",
    "privacy violation": "ftc_unfair_deceptive_practices",
    "security violation": "ftc_unfair_deceptive_practices",

    # State Data Breach Notification Laws - General Obligations
    "data breach notification": "state_data_breach_notification",
    "breach notification": "state_data_breach_notification",
    "state breach notification": "state_data_breach_notification",
    "notification obligation": "state_data_breach_notification",
    "notify breach": "state_data_breach_notification",
    "breach notice": "state_data_breach_notification",
    "security breach": "state_data_breach_notification",
    "personal data breach": "state_data_breach_notification",
    "data breach law": "state_data_breach_notification",
    "state breach law": "state_data_breach_notification",
    "breach reporting": "state_data_breach_notification",
    "report breach": "state_data_breach_notification",
    "breach disclosure": "state_data_breach_notification",
    "breach obligation": "state_data_breach_notification",
    "breach notification requirement": "state_data_breach_notification",
    "breach notification law": "state_data_breach_notification",

    # GDPR Data Protection Impact Assessment (DPIA) Requirements
    "dpia": "gdpr_dpia",
    "data protection impact assessment": "gdpr_dpia",
    "impact assessment": "gdpr_dpia",
    "privacy impact assessment": "gdpr_dpia",
    "gdpr dpia": "gdpr_dpia",
    "dpia requirement": "gdpr_dpia",
    "dpia obligations": "gdpr_dpia",
    "dpia process": "gdpr_dpia",
    "dpia procedure": "gdpr_dpia",
    "dpia report": "gdpr_dpia",
    "dpia documentation": "gdpr_dpia",

    # GDPR Cross-Border Data Transfers and Standard Contractual Clauses
    "cross-border transfer": "gdpr_cross_border_transfer",
    "cross border transfer": "gdpr_cross_border_transfer",
    "international data transfer": "gdpr_cross_border_transfer",
    "data transfer": "gdpr_cross_border_transfer",
    "transfer of personal data": "gdpr_cross_border_transfer",
    "transfer outside eu": "gdpr_cross_border_transfer",
    "transfer outside eea": "gdpr_cross_border_transfer",
    "standard contractual clauses": "gdpr_scc",
    "scc": "gdpr_scc",
    "model clauses": "gdpr_scc",
    "standard clauses": "gdpr_scc",
    "eu model clauses": "gdpr_scc",
    "eu scc": "gdpr_scc",
    "scc requirement": "gdpr_scc",
    "scc obligations": "gdpr_scc",
    "scc process": "gdpr_scc",

    # Misspellings, abbreviations, synonyms, related terms (examples)
    "ccp": "ccpa",
    "cal privacy act": "ccpa",
    "california privacy": "ccpa",
    "cal privacy law": "ccpa",
    "ca privacy law": "ccpa",
    "calif privacy act": "ccpa",
    "calif privacy law": "ccpa",
    "calif privacy": "ccpa",
    "calif consumer privacy act": "ccpa",
    "calif consumer privacy": "ccpa",
    "california consumer privacy": "ccpa",
    "california consumer act": "ccpa",
    "calif consumer act": "ccpa",
    "calif privacy rights act": "cpra",
    "cal privacy rights act": "cpra",
    "california privacy rights": "cpra",
    "cal privacy rights": "cpra",
    "calif privacy rights": "cpra",
    "cal privacy rights amendment": "cpra_amendments",
    "calif privacy rights amendment": "cpra_amendments",
    "cal privacy rights amendments": "cpra_amendments",
    "calif privacy rights amendments": "cpra_amendments",
    "calif spi": "cpra_sensitive_personal_information",
    "cal spi": "cpra_sensitive_personal_information",
    "california spi": "cpra_sensitive_personal_information",
    "calif sensitive info": "cpra_sensitive_personal_information",
    "cal sensitive info": "cpra_sensitive_personal_information",
    "california sensitive info": "cpra_sensitive_personal_information",
    "calif sensitive personal information": "cpra_sensitive_personal_information",
    "cal sensitive personal information": "cpra_sensitive_personal_information",
    "california sensitive personal information": "cpra_sensitive_personal_information",
    "calif opt-out": "cpra_opt_out",
    "cal opt-out": "cpra_opt_out",
    "california opt-out": "cpra_opt_out",
    "calif opt out": "cpra_opt_out",
    "cal opt out": "cpra_opt_out",
    "california opt out": "cpra_opt_out",
    "calif do not sell": "cpra_opt_out",
    "cal do not sell": "cpra_opt_out",
    "california do not sell": "cpra_opt_out",
    "calif do not share": "cpra_opt_out",
    "cal do not share": "cpra_opt_out",
    "california do not share": "cpra_opt_out",
    "calif sale of personal information": "cpra_opt_out",
    "cal sale of personal information": "cpra_opt_out",
    "california sale of personal information": "cpra_opt_out",
    "calif sharing of personal information": "cpra_opt_out",
    "cal sharing of personal information": "cpra_opt_out",
    "california sharing of personal information": "cpra_opt_out",

    # GDPR synonyms, misspellings, abbreviations
    "gdpr rights": "gdpr_data_subject_rights",
    "eu data protection regulation": "gdpr",
    "eu privacy regulation": "gdpr",
    "eu privacy law": "gdpr",
    "eu data privacy law": "gdpr",
    "eu privacy": "gdpr",
    "eu data protection": "gdpr",
    "gdpr lawful basis": "gdpr_lawful_basis",
    "gdpr legal basis": "gdpr_lawful_basis",
    "gdpr legal grounds": "gdpr_lawful_basis",
    "gdpr lawful grounds": "gdpr_lawful_basis",
    "gdpr consent": "gdpr_lawful_basis_consent",
    "gdpr explicit consent": "gdpr_lawful_basis_consent",
    "gdpr informed consent": "gdpr_lawful_basis_consent",
    "gdpr contractual necessity": "gdpr_lawful_basis_contract",
    "gdpr contract": "gdpr_lawful_basis_contract",
    "gdpr performance of contract": "gdpr_lawful_basis_contract",
    "gdpr legitimate interests": "gdpr_lawful_basis_legitimate_interest",
    "gdpr legitimate interest": "gdpr_lawful_basis_legitimate_interest",
    "gdpr public interest": "gdpr_lawful_basis_public_interest",
    "gdpr vital interests": "gdpr_lawful_basis_vital_interest",
    "gdpr legal obligation": "gdpr_lawful_basis_legal_obligation",
    "gdpr data minimization": "gdpr_data_minimization",
    "gdpr minimize data": "gdpr_data_minimization",
    "gdpr minimization": "gdpr_data_minimization",
    "gdpr minimal data": "gdpr_data_minimization",
    "gdpr only necessary data": "gdpr_data_minimization",
    "gdpr necessary data": "gdpr_data_minimization",
    "gdpr purpose limitation": "gdpr_purpose_limitation",
    "gdpr purpose limited": "gdpr_purpose_limitation",
    "gdpr limit purpose": "gdpr_purpose_limitation",

    # GDPR Data Subject Rights synonyms
    "gdpr data subject rights": "gdpr_data_subject_rights",
    "gdpr subject rights": "gdpr_data_subject_rights",
    "gdpr rights of data subjects": "gdpr_data_subject_rights",
    "gdpr right to access": "gdpr_access",
    "gdpr access right": "gdpr_access",
    "gdpr data access request": "gdpr_access",
    "gdpr right to rectification": "gdpr_rectification",
    "gdpr rectification right": "gdpr_rectification",
    "gdpr correct data": "gdpr_rectification",
    "gdpr correct my data": "gdpr_rectification",
    "gdpr fix data": "gdpr_rectification",
    "gdpr right to erasure": "gdpr_erasure",
    "gdpr erasure right": "gdpr_erasure",
    "gdpr delete my data": "gdpr_erasure",
    "gdpr right to be forgotten": "gdpr_erasure",
    "gdpr forgotten right": "gdpr_erasure",
    "gdpr right to data portability": "gdpr_portability",
    "gdpr portability right": "gdpr_portability",
    "gdpr data portability": "gdpr_portability",
    "gdpr transfer my data": "gdpr_portability",
    "gdpr download my data": "gdpr_portability",
    "gdpr right to restrict processing": "gdpr_restriction",
    "gdpr restriction right": "gdpr_restriction",
    "gdpr restrict processing": "gdpr_restriction",
    "gdpr right to object": "gdpr_object",
    "gdpr object right": "gdpr_object",
    "gdpr object to processing": "gdpr_object",
    "gdpr right to withdraw consent": "gdpr_withdraw_consent",
    "gdpr withdraw consent": "gdpr_withdraw_consent",
    "gdpr withdrawal of consent": "gdpr_withdraw_consent",

    # COPPA synonyms, misspellings, abbreviations
    "coppa rights": "coppa",
    "coppa parental consent": "coppa_parental_consent",
    "coppa parental permission": "coppa_parental_consent",
    "coppa parent consent": "coppa_parental_consent",
    "coppa parental notice": "coppa_parental_notice",
    "coppa parent notice": "coppa_parental_notice",
    "coppa notice to parents": "coppa_parental_notice",
    "coppa notice requirement": "coppa_parental_notice",
    "coppa verifiable parental consent": "coppa_parental_consent",
    "coppa vpc": "coppa_parental_consent",
    "coppa child consent": "coppa_parental_consent",
    "coppa children consent": "coppa_parental_consent",

    # FERPA synonyms, misspellings, abbreviations
    "ferpa rights": "ferpa",
    "ferpa student privacy": "ferpa_student_privacy",
    "ferpa student record privacy": "ferpa_student_privacy",
    "ferpa education record": "ferpa_education_record",
    "ferpa student record": "ferpa_education_record",
    "ferpa school record": "ferpa_education_record",
    "ferpa record disclosure": "ferpa_disclosure_exception",
    "ferpa disclosure exception": "ferpa_disclosure_exception",
    "ferpa education record disclosure": "ferpa_disclosure_exception",
    "ferpa school record disclosure": "ferpa_disclosure_exception",
    "ferpa directory information": "ferpa_directory_information",
    "ferpa directory info": "ferpa_directory_information",
    "ferpa directory data": "ferpa_directory_information",
    "ferpa parental access": "ferpa_parental_access",
    "ferpa parent access": "ferpa_parental_access",
    "ferpa parent right": "ferpa_parental_access",

    # GLBA synonyms, misspellings, abbreviations
    "glba rights": "glba",
    "glba privacy rule": "glba_privacy_rule",
    "glba safeguards rule": "glba_safeguards_rule",
    "glba financial institution": "glba_financial_institution",
    "glba bank privacy": "glba_financial_institution",
    "glba customer information": "glba_customer_information",
    "glba customer data": "glba_customer_information",
    "glba nonpublic personal information": "glba_customer_information",
    "glba npi": "glba_customer_information",
    "glba consumer information": "glba_customer_information",
    "glba consumer data": "glba_customer_information",

    # FTC synonyms, misspellings, abbreviations
    "ftc act section 5": "ftc_act_section_5",
    "ftc section 5": "ftc_act_section_5",
    "ftc unfair practices": "ftc_unfair_practices",
    "ftc deceptive practices": "ftc_deceptive_practices",
    "ftc unfair privacy practices": "ftc_unfair_practices",
    "ftc deceptive privacy practices": "ftc_deceptive_practices",
    "ftc unfair security practices": "ftc_unfair_practices",
    "ftc deceptive security practices": "ftc_deceptive_practices",
    "ftc unfair or deceptive acts": "ftc_unfair_deceptive_practices",
    "ftc udap": "ftc_unfair_deceptive_practices",
    "ftc unfair and deceptive acts": "ftc_unfair_deceptive_practices",
    "ftc privacy violation": "ftc_unfair_deceptive_practices",
    "ftc security violation": "ftc_unfair_deceptive_practices",

    # State Data Breach Notification synonyms, misspellings, abbreviations
    "state data breach notification": "state_data_breach_notification",
    "state breach notification": "state_data_breach_notification",
    "state notification obligation": "state_data_breach_notification",
    "state notify breach": "state_data_breach_notification",
    "state breach notice": "state_data_breach_notification",
    "state security breach": "state_data_breach_notification",
    "state personal data breach": "state_data_breach_notification",
    "state data breach law": "state_data_breach_notification",
    "state breach law": "state_data_breach_notification",
    "state breach reporting": "state_data_breach_notification",
    "state report breach": "state_data_breach_notification",
    "state breach disclosure": "state_data_breach_notification",
    "state breach obligation": "state_data_breach_notification",
    "state breach notification requirement": "state_data_breach_notification",
    "state breach notification law": "state_data_breach_notification",

    # GDPR DPIA synonyms, misspellings, abbreviations
    "gdpr dpia": "gdpr_dpia",
    "gdpr data protection impact assessment": "gdpr_dpia",
    "gdpr impact assessment": "gdpr_dpia",
    "gdpr privacy impact assessment": "gdpr_dpia",
    "gdpr dpia requirement": "gdpr_dpia",
    "gdpr dpia obligations": "gdpr_dpia",
    "gdpr dpia process": "gdpr_dpia",
    "gdpr dpia procedure": "gdpr_dpia",
    "gdpr dpia report": "gdpr_dpia",
    "gdpr dpia documentation": "gdpr_dpia",

    # GDPR Cross-Border synonyms, misspellings, abbreviations
    "gdpr cross-border transfer": "gdpr_cross_border_transfer",
    "gdpr cross border transfer": "gdpr_cross_border_transfer",
    "gdpr international data transfer": "gdpr_cross_border_transfer",
    "gdpr data transfer": "gdpr_cross_border_transfer",
    "gdpr transfer of personal data": "gdpr_cross_border_transfer",
    "gdpr transfer outside eu": "gdpr_cross_border_transfer",
    "gdpr transfer outside eea": "gdpr_cross_border_transfer",
    "gdpr standard contractual clauses": "gdpr_scc",
    "gdpr scc": "gdpr_scc",
    "gdpr model clauses": "gdpr_scc",
    "gdpr standard clauses": "gdpr_scc",
    "gdpr eu model clauses": "gdpr_scc",
    "gdpr eu scc": "gdpr_scc",
    "gdpr scc requirement": "gdpr_scc",
    "gdpr scc obligations": "gdpr_scc",
    "gdpr scc process": "gdpr_scc",

    # Misspellings and variants (examples)
    "gdpr data subject right": "gdpr_data_subject_rights",
    "gdpr subject right": "gdpr_data_subject_rights",
    "gdpr right of data subject": "gdpr_data_subject_rights",
    "gdpr right of access": "gdpr_access",
    "gdpr right of rectification": "gdpr_rectification",
    "gdpr right of erasure": "gdpr_erasure",
    "gdpr right of portability": "gdpr_portability",
    "gdpr right of restriction": "gdpr_restriction",
    "gdpr right of object": "gdpr_object",
    "gdpr right of withdraw consent": "gdpr_withdraw_consent",

    # More synonyms, misspellings, abbreviations, related terms (examples)
    "ccpa consumer right": "ccpa_consumer_rights",
    "ccpa consumer access": "ccpa_access",
    "ccpa consumer deletion": "ccpa_deletion",
    "ccpa consumer portability": "ccpa_portability",
    "ccpa sensitive info": "cpra_sensitive_personal_information",
    "ccpa opt-out": "cpra_opt_out",
    "ccpa opt out": "cpra_opt_out",
    "ccpa do not sell": "cpra_opt_out",
    "ccpa do not share": "cpra_opt_out",
    "ccpa sale of personal information": "cpra_opt_out",
    "ccpa sharing of personal information": "cpra_opt_out",

    # Misspellings, abbreviations, related terms (examples)
    "ferpa education records": "ferpa_education_record",
    "ferpa student records": "ferpa_education_record",
    "ferpa school records": "ferpa_education_record",
    "ferpa record disclosures": "ferpa_disclosure_exception",
    "ferpa disclosure exceptions": "ferpa_disclosure_exception",
    "ferpa education record disclosures": "ferpa_disclosure_exception",
    "ferpa school record disclosures": "ferpa_disclosure_exception",
    "ferpa directory informations": "ferpa_directory_information",
    "ferpa directory infos": "ferpa_directory_information",
    "ferpa directory datas": "ferpa_directory_information",
    "ferpa parental accesses": "ferpa_parental_access",
    "ferpa parent accesses": "ferpa_parental_access",
    "ferpa parent rights": "ferpa_parental_access",

    # Misspellings, abbreviations, related terms (examples)
    "glba financial institutions": "glba_financial_institution",
    "glba bank privacies": "glba_financial_institution",
    "glba customer informations": "glba_customer_information",
    "glba customer datas": "glba_customer_information",
    "glba nonpublic personal informations": "glba_customer_information",
    "glba npi's": "glba_customer_information",
    "glba consumer informations": "glba_customer_information",
    "glba consumer datas": "glba_customer_information",

    # Misspellings, abbreviations, related terms (examples)
    "ftc acts": "ftc_act",
    "ftc sections 5": "ftc_act_section_5",
    "ftc unfair practicess": "ftc_unfair_practices",
    "ftc deceptive practicess": "ftc_deceptive_practices",
    "ftc unfair privacy practicess": "ftc_unfair_practices",
    "ftc deceptive privacy practicess": "ftc_deceptive_practices",
    "ftc unfair security practicess": "ftc_unfair_practices",
    "ftc deceptive security practicess": "ftc_deceptive_practices",
    "ftc unfair or deceptive actss": "ftc_unfair_deceptive_practices",
    "ftc udaps": "ftc_unfair_deceptive_practices",
    "ftc unfair and deceptive actss": "ftc_unfair_deceptive_practices",
    "ftc privacy violations": "ftc_unfair_deceptive_practices",
    "ftc security violations": "ftc_unfair_deceptive_practices",

    # Misspellings, abbreviations, related terms (examples)
    "state data breach notifications": "state_data_breach_notification",
    "state breach notifications": "state_data_breach_notification",
    "state notification obligations": "state_data_breach_notification",
    "state notify breaches": "state_data_breach_notification",
    "state breach notices": "state_data_breach_notification",
    "state security breaches": "state_data_breach_notification",
    "state personal data breaches": "state_data_breach_notification",
    "state data breach laws": "state_data_breach_notification",
    "state breach laws": "state_data_breach_notification",
    "state breach reportings": "state_data_breach_notification",
    "state report breaches": "state_data_breach_notification",
    "state breach disclosures": "state_data_breach_notification",
    "state breach obligations": "state_data_breach_notification",
    "state breach notification requirements": "state_data_breach_notification",
    "state breach notification laws": "state_data_breach_notification",

    # Misspellings, abbreviations, related terms (examples)
    "gdpr dpias": "gdpr_dpia",
    "gdpr data protection impact assessments": "gdpr_dpia",
    "gdpr impact assessments": "gdpr_dpia",
    "gdpr privacy impact assessments": "gdpr_dpia",
    "gdpr dpia requirements": "gdpr_dpia",
    "gdpr dpia obligations": "gdpr_dpia",
    "gdpr dpia processes": "gdpr_dpia",
    "gdpr dpia procedures": "gdpr_dpia",
    "gdpr dpia reports": "gdpr_dpia",
    "gdpr dpia documentations": "gdpr_dpia",

    # Misspellings, abbreviations, related terms (examples)
    "gdpr cross-border transfers": "gdpr_cross_border_transfer",
    "gdpr cross border transfers": "gdpr_cross_border_transfer",
    "gdpr international data transfers": "gdpr_cross_border_transfer",
    "gdpr data transfers": "gdpr_cross_border_transfer",
    "gdpr transfer of personal datas": "gdpr_cross_border_transfer",
    "gdpr transfer outside eus": "gdpr_cross_border_transfer",
    "gdpr transfer outside eeas": "gdpr_cross_border_transfer",
    "gdpr standard contractual clauses": "gdpr_scc",
    "gdpr sccs": "gdpr_scc",
    "gdpr model clauses": "gdpr_scc",
    "gdpr standard clauses": "gdpr_scc",
    "gdpr eu model clauses": "gdpr_scc",
    "gdpr eu sccs": "gdpr_scc",
    "gdpr scc requirements": "gdpr_scc",
    "gdpr scc obligations": "gdpr_scc",
    "gdpr scc processes": "gdpr_scc",

    # Misspellings, abbreviations, related terms (examples)
    "ccpa consumer rights": "ccpa_consumer_rights",
    "ccpa consumer accesses": "ccpa_access",
    "ccpa consumer deletions": "ccpa_deletion",
    "ccpa consumer portabilities": "ccpa_portability",
    "ccpa sensitive infos": "cpra_sensitive_personal_information",
    "ccpa opt-outs": "cpra_opt_out",
    "ccpa do not sells": "cpra_opt_out",
    "ccpa do not shares": "cpra_opt_out",
    "ccpa sale of personal informations": "cpra_opt_out",
    "ccpa sharing of personal informations": "cpra_opt_out",

    # Misspellings, abbreviations, related terms (examples)
    "coppa parental consents": "coppa_parental_consent",
    "coppa parental permissions": "coppa_parental_consent",
    "coppa parent consents": "coppa_parental_consent",
    "coppa parental notices": "coppa_parental_notice",
    "coppa parent notices": "coppa_parental_notice",
    "coppa notice to parents": "coppa_parental_notice",
    "coppa notice requirements": "coppa_parental_notice",
    "coppa verifiable parental consents": "coppa_parental_consent",
    "coppa vpcs": "coppa_parental_consent",
    "coppa child consents": "coppa_parental_consent",
    "coppa children consents": "coppa_parental_consent",

    # Misspellings, abbreviations, related terms (examples)
    "gdpr data subject rights": "gdpr_data_subject_rights",
    "gdpr subject rights": "gdpr_data_subject_rights",
    "gdpr rights of data subjects": "gdpr_data_subject_rights",
    "gdpr right to accesses": "gdpr_access",
    "gdpr access rights": "gdpr_access",
    "gdpr data access requests": "gdpr_access",
    "gdpr right to rectifications": "gdpr_rectification",
    "gdpr rectification rights": "gdpr_rectification",
    "gdpr correct datas": "gdpr_rectification",
    "gdpr correct my datas": "gdpr_rectification",
    "gdpr fix datas": "gdpr_rectification",
    "gdpr right to erasures": "gdpr_erasure",
    "gdpr erasure rights": "gdpr_erasure",
    "gdpr delete my datas": "gdpr_erasure",
    "gdpr right to be forgottens": "gdpr_erasure",
    "gdpr forgotten rights": "gdpr_erasure",
    "gdpr right to data portabilities": "gdpr_portability",
    "gdpr portability rights": "gdpr_portability",
    "gdpr data portabilities": "gdpr_portability",
    "gdpr transfer my datas": "gdpr_portability",
    "gdpr download my datas": "gdpr_portability",
    "gdpr right to restrict processings": "gdpr_restriction",
    "gdpr restriction rights": "gdpr_restriction",
    "gdpr restrict processings": "gdpr_restriction",
    "gdpr right to objects": "gdpr_object",
    "gdpr object rights": "gdpr_object",
    "gdpr object to processings": "gdpr_object",
    "gdpr right to withdraw consents": "gdpr_withdraw_consent",
    "gdpr withdraw consents": "gdpr_withdraw_consent",
    "gdpr withdrawal of consents": "gdpr_withdraw_consent",

    # Misspellings, abbreviations, related terms (examples)
    "gdpr lawful bases": "gdpr_lawful_basis",
    "gdpr legal bases": "gdpr_lawful_basis",
    "gdpr lawful grounds": "gdpr_lawful_basis",
    "gdpr legal grounds": "gdpr_lawful_basis",
    "gdpr processing bases": "gdpr_lawful_basis",
    "gdpr consents": "gdpr_lawful_basis_consent",
    "gdpr explicit consents": "gdpr_lawful_basis_consent",
    "gdpr informed consents": "gdpr_lawful_basis_consent",
    "gdpr contractual necessities": "gdpr_lawful_basis_contract",
    "gdpr contracts": "gdpr_lawful_basis_contract",
    "gdpr performance of contracts": "gdpr_lawful_basis_contract",
    "gdpr legitimate interests": "gdpr_lawful_basis_legitimate_interest",
    "gdpr legitimate interest": "gdpr_lawful_basis_legitimate_interest",
    "gdpr public interests": "gdpr_lawful_basis_public_interest",
    "gdpr vital interests": "gdpr_lawful_basis_vital_interest",
    "gdpr legal obligations": "gdpr_lawful_basis_legal_obligation",
    "gdpr data minimizations": "gdpr_data_minimization",
    "gdpr minimize datas": "gdpr_data_minimization",
    "gdpr minimizations": "gdpr_data_minimization",
    "gdpr minimal datas": "gdpr_data_minimization",
    "gdpr only necessary datas": "gdpr_data_minimization",
    "gdpr necessary datas": "gdpr_data_minimization",
    "gdpr purpose limitations": "gdpr_purpose_limitation",
    "gdpr purpose limiteds": "gdpr_purpose_limitation",
    "gdpr limit purposes": "gdpr_purpose_limitation",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join([f"{k}:{v}" for k, v in items])
    concat += f"{SEMANTIC_MAP_VERSION}:{SEMANTIC_MAP_AUTHOR}:{SEMANTIC_MAP_ENGINE}:{_EXPECTED_ENTRY_COUNT}"
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_string(s):
    s = s.lower()
    s = re.sub(r"[^a-z0-9\s\-']", "", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip()

def normalize_term(term: str) -> str:
    t = _normalize_string(term)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)