import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENRG03_wind_energy"
SEMANTIC_MAP_ENGINE = "ENRG03"

SEMANTIC_MAP = {
    # S-Corporation Reasonable Compensation
    "reasonable compensation": "s-corp reasonable compensation",
    "s corp reasonable compensation": "s-corp reasonable compensation",
    "s-corp reasonable comp": "s-corp reasonable compensation",
    "s corporation reasonable compensation": "s-corp reasonable compensation",
    "reasonable comp": "s-corp reasonable compensation",
    "reasonable salary": "s-corp reasonable compensation",
    "s corp salary": "s-corp reasonable compensation",
    "s-corp salary": "s-corp reasonable compensation",
    "shareholder salary": "s-corp reasonable compensation",
    "officer compensation": "s-corp reasonable compensation",
    "officer salary": "s-corp reasonable compensation",
    "owner compensation": "s-corp reasonable compensation",
    "owner salary": "s-corp reasonable compensation",
    "s corp owner pay": "s-corp reasonable compensation",
    "s-corp owner pay": "s-corp reasonable compensation",
    "s corp wage": "s-corp reasonable compensation",
    "s-corp wage": "s-corp reasonable compensation",
    "s corp payroll": "s-corp reasonable compensation",
    "s-corp payroll": "s-corp reasonable compensation",
    "s corp comp": "s-corp reasonable compensation",
    "s-corp comp": "s-corp reasonable compensation",

    # Capital vs Labor Profit Attribution
    "capital vs labor": "capital vs labor profit attribution",
    "capital v labor": "capital vs labor profit attribution",
    "capital versus labor": "capital vs labor profit attribution",
    "capital labor split": "capital vs labor profit attribution",
    "labor capital split": "capital vs labor profit attribution",
    "profit attribution": "capital vs labor profit attribution",
    "labor profit attribution": "capital vs labor profit attribution",
    "capital profit attribution": "capital vs labor profit attribution",
    "capital allocation": "capital vs labor profit attribution",
    "labor allocation": "capital vs labor profit attribution",
    "capital labor allocation": "capital vs labor profit attribution",
    "labor capital allocation": "capital vs labor profit attribution",
    "labor/capital split": "capital vs labor profit attribution",
    "capital/labor split": "capital vs labor profit attribution",

    # Constructive Receipt Doctrine
    "constructive receipt": "constructive receipt doctrine",
    "constructive receipt doctrine": "constructive receipt doctrine",
    "constructive reciept": "constructive receipt doctrine",
    "constructive recpt": "constructive receipt doctrine",
    "constructive recpt doctrine": "constructive receipt doctrine",
    "income constructively received": "constructive receipt doctrine",
    "constructive income": "constructive receipt doctrine",
    "unrestricted income": "constructive receipt doctrine",
    "income available": "constructive receipt doctrine",
    "income available but not received": "constructive receipt doctrine",

    # Economic Substance Doctrine
    "economic substance": "economic substance doctrine",
    "economic substance doctrine": "economic substance doctrine",
    "economic substance test": "economic substance doctrine",
    "substance over form": "economic substance doctrine",
    "business purpose doctrine": "economic substance doctrine",
    "sham transaction": "economic substance doctrine",
    "sham doctrine": "economic substance doctrine",
    "lack of economic substance": "economic substance doctrine",
    "no economic substance": "economic substance doctrine",
    "section 7701(o)": "economic substance doctrine",
    "irc 7701(o)": "economic substance doctrine",
    "7701(o)": "economic substance doctrine",

    # Hobby Loss Rules - IRC §183
    "hobby loss": "hobby loss rules",
    "hobby loss rules": "hobby loss rules",
    "hobby losses": "hobby loss rules",
    "irc 183": "hobby loss rules",
    "section 183": "hobby loss rules",
    "activity not engaged for profit": "hobby loss rules",
    "not for profit activity": "hobby loss rules",
    "not-for-profit activity": "hobby loss rules",
    "hobby income": "hobby loss rules",
    "hobby expenses": "hobby loss rules",
    "hobby deduction": "hobby loss rules",
    "hobby loss deduction": "hobby loss rules",
    "183 activity": "hobby loss rules",
    "183 rules": "hobby loss rules",

    # Home Office Deduction - IRC §280A
    "home office deduction": "home office deduction",
    "home office": "home office deduction",
    "irc 280a": "home office deduction",
    "section 280a": "home office deduction",
    "280a deduction": "home office deduction",
    "home office expense": "home office deduction",
    "home office expenses": "home office deduction",
    "office in home": "home office deduction",
    "business use of home": "home office deduction",
    "business home deduction": "home office deduction",
    "home office tax deduction": "home office deduction",
    "home office write off": "home office deduction",
    "home office write-off": "home office deduction",
    "home office simplified method": "home office deduction",
    "home office regular method": "home office deduction",

    # Passive Activity Loss Rules - IRC §469
    "passive activity loss": "passive activity loss rules",
    "passive activity losses": "passive activity loss rules",
    "passive activity loss rules": "passive activity loss rules",
    "passive loss": "passive activity loss rules",
    "passive losses": "passive activity loss rules",
    "irc 469": "passive activity loss rules",
    "section 469": "passive activity loss rules",
    "469 rules": "passive activity loss rules",
    "pal rules": "passive activity loss rules",
    "pal": "passive activity loss rules",
    "passive activity deduction": "passive activity loss rules",
    "passive activity limitation": "passive activity loss rules",
    "passive loss limitation": "passive activity loss rules",
    "passive activity limit": "passive activity loss rules",
    "passive activity carryover": "passive activity loss rules",
    "passive activity carry forward": "passive activity loss rules",
    "passive activity carryforward": "passive activity loss rules",

    # Like-Kind Exchange - IRC §1031
    "like-kind exchange": "like-kind exchange",
    "like kind exchange": "like-kind exchange",
    "like-kind exchanges": "like-kind exchange",
    "like kind exchanges": "like-kind exchange",
    "irc 1031": "like-kind exchange",
    "section 1031": "like-kind exchange",
    "1031 exchange": "like-kind exchange",
    "1031 exchanges": "like-kind exchange",
    "1031": "like-kind exchange",
    "tax deferred exchange": "like-kind exchange",
    "tax-deferred exchange": "like-kind exchange",
    "tax free exchange": "like-kind exchange",
    "tax-free exchange": "like-kind exchange",
    "property exchange": "like-kind exchange",
    "real estate exchange": "like-kind exchange",
    "real property exchange": "like-kind exchange",
    "starker exchange": "like-kind exchange",
    "delayed exchange": "like-kind exchange",
    "simultaneous exchange": "like-kind exchange",
    "reverse exchange": "like-kind exchange",
    "boot in exchange": "like-kind exchange",
    "exchange boot": "like-kind exchange",

    # Percentage Depletion - Oil & Gas (IRC §613A)
    "percentage depletion": "percentage depletion",
    "percentage depletion deduction": "percentage depletion",
    "oil and gas depletion": "percentage depletion",
    "oil & gas depletion": "percentage depletion",
    "irc 613a": "percentage depletion",
    "section 613a": "percentage depletion",
    "613a": "percentage depletion",
    "depletion deduction": "percentage depletion",
    "percentage depletion oil": "percentage depletion",
    "percentage depletion gas": "percentage depletion",
    "depletion allowance": "percentage depletion",
    "depletion oil and gas": "percentage depletion",
    "depletion oil & gas": "percentage depletion",

    # Intangible Drilling Costs (IDC) - IRC §263(c)
    "intangible drilling costs": "intangible drilling costs",
    "idc": "intangible drilling costs",
    "idcs": "intangible drilling costs",
    "intangible drilling cost": "intangible drilling costs",
    "irc 263c": "intangible drilling costs",
    "section 263c": "intangible drilling costs",
    "263c": "intangible drilling costs",
    "drilling costs": "intangible drilling costs",
    "oil and gas idc": "intangible drilling costs",
    "oil & gas idc": "intangible drilling costs",
    "idc deduction": "intangible drilling costs",
    "idc expensing": "intangible drilling costs",
    "idc capitalization": "intangible drilling costs",

    # Qualified Business Income Deduction - IRC §199A
    "qualified business income deduction": "qualified business income deduction",
    "qbi deduction": "qualified business income deduction",
    "qbi": "qualified business income deduction",
    "section 199a": "qualified business income deduction",
    "irc 199a": "qualified business income deduction",
    "199a deduction": "qualified business income deduction",
    "qualified business income": "qualified business income deduction",
    "section 199a deduction": "qualified business income deduction",
    "qualified income deduction": "qualified business income deduction",
    "qualified business deduction": "qualified business income deduction",
    "qbid": "qualified business income deduction",
    "20% business deduction": "qualified business income deduction",
    "20 percent business deduction": "qualified business income deduction",

    # Statute of Limitations - Assessment & Collection
    "statute of limitations": "statute of limitations",
    "assessment statute of limitations": "statute of limitations",
    "collection statute of limitations": "statute of limitations",
    "sol": "statute of limitations",
    "limitations period": "statute of limitations",
    "assessment period": "statute of limitations",
    "collection period": "statute of limitations",
    "irs statute of limitations": "statute of limitations",
    "tax statute of limitations": "statute of limitations",
    "statute of limitation": "statute of limitations",
    "statutes of limitations": "statute of limitations",

    # Offer in Compromise (OIC) - IRC §7122
    "offer in compromise": "offer in compromise",
    "oic": "offer in compromise",
    "irc 7122": "offer in compromise",
    "section 7122": "offer in compromise",
    "7122": "offer in compromise",
    "irs offer in compromise": "offer in compromise",
    "compromise offer": "offer in compromise",
    "tax compromise": "offer in compromise",
    "settlement offer": "offer in compromise",
    "tax settlement": "offer in compromise",
    "doubt as to collectibility": "offer in compromise",
    "doubt as to liability": "offer in compromise",

    # Employee Retention Credit (ERC) - COVID Relief
    "employee retention credit": "employee retention credit",
    "erc": "employee retention credit",
    "erc credit": "employee retention credit",
    "employee retention tax credit": "employee retention credit",
    "covid erc": "employee retention credit",
    "covid-19 erc": "employee retention credit",
    "covid employee retention credit": "employee retention credit",
    "covid-19 employee retention credit": "employee retention credit",
    "irs erc": "employee retention credit",
    "cares act erc": "employee retention credit",
    "cares act employee retention credit": "employee retention credit",
    "employee retention": "employee retention credit",

    # Worker Classification - Employee vs Independent Contractor
    "worker classification": "worker classification",
    "employee vs contractor": "worker classification",
    "employee versus contractor": "worker classification",
    "employee or contractor": "worker classification",
    "employee v contractor": "worker classification",
    "employee vs independent contractor": "worker classification",
    "independent contractor vs employee": "worker classification",
    "contractor vs employee": "worker classification",
    "contractor classification": "worker classification",
    "worker status": "worker classification",
    "employee classification": "worker classification",
    "contractor classification": "worker classification",
    "1099 vs w2": "worker classification",
    "w2 vs 1099": "worker classification",
    "w-2 vs 1099": "worker classification",
    "1099 employee": "worker classification",
    "w2 employee": "worker classification",
    "w-2 employee": "worker classification",
    "independent contractor": "worker classification",
    "employee": "worker classification",

    # Conservation Easements - Syndicated Transactions
    "conservation easement": "conservation easements",
    "conservation easements": "conservation easements",
    "syndicated conservation easement": "conservation easements",
    "syndicated conservation easements": "conservation easements",
    "syndicated easement": "conservation easements",
    "syndicated easements": "conservation easements",
    "conservation easement transaction": "conservation easements",
    "conservation easement transactions": "conservation easements",
    "irs conservation easement": "conservation easements",
    "conservation deduction": "conservation easements",
    "conservation easement deduction": "conservation easements",
    "conservation easement tax shelter": "conservation easements",
    "easement deduction": "conservation easements",

    # Micro-Captive Insurance - §831(b) Elections
    "micro-captive insurance": "micro-captive insurance",
    "micro captive insurance": "micro-captive insurance",
    "micro-captive": "micro-captive insurance",
    "micro captive": "micro-captive insurance",
    "831b": "micro-captive insurance",
    "irc 831b": "micro-captive insurance",
    "section 831b": "micro-captive insurance",
    "831(b)": "micro-captive insurance",
    "831(b) election": "micro-captive insurance",
    "micro-captive election": "micro-captive insurance",
    "micro captive election": "micro-captive insurance",
    "captive insurance": "micro-captive insurance",
    "captive insurance company": "micro-captive insurance",
    "micro-captive insurance company": "micro-captive insurance",
    "micro captive insurance company": "micro-captive insurance",

    # Related Party Transactions - §267 and §707(b)
    "related party transaction": "related party transactions",
    "related party transactions": "related party transactions",
    "section 267": "related party transactions",
    "irc 267": "related party transactions",
    "267": "related party transactions",
    "section 707b": "related party transactions",
    "irc 707b": "related party transactions",
    "707b": "related party transactions",
    "related party rules": "related party transactions",
    "related party": "related party transactions",
    "related parties": "related party transactions",
    "family member transaction": "related party transactions",
    "family member transactions": "related party transactions",
    "controlled group transaction": "related party transactions",
    "controlled group transactions": "related party transactions",
    "related entity transaction": "related party transactions",
    "related entity transactions": "related party transactions",

    # Partnership Special Allocations - §704(b)
    "partnership special allocation": "partnership special allocations",
    "partnership special allocations": "partnership special allocations",
    "special allocation": "partnership special allocations",
    "special allocations": "partnership special allocations",
    "section 704b": "partnership special allocations",
    "irc 704b": "partnership special allocations",
    "704b": "partnership special allocations",
    "704(b)": "partnership special allocations",
    "partnership allocation": "partnership special allocations",
    "partnership allocations": "partnership special allocations",
    "special allocation rules": "partnership special allocations",
    "economic effect": "partnership special allocations",
    "economic effect test": "partnership special allocations",

    # Wash Sale Rules - §1091
    "wash sale": "wash sale rules",
    "wash sale rules": "wash sale rules",
    "wash sales": "wash sale rules",
    "section 1091": "wash sale rules",
    "irc 1091": "wash sale rules",
    "1091": "wash sale rules",
    "wash sale loss": "wash sale rules",
    "wash sale disallowance": "wash sale rules",
    "wash sale stock": "wash sale rules",
    "wash sale securities": "wash sale rules",
    "wash sale period": "wash sale rules",
    "wash sale window": "wash sale rules",
    "substantially identical stock": "wash sale rules",
    "substantially identical securities": "wash sale rules",

    # Net Operating Losses - §172
    "net operating loss": "net operating losses",
    "net operating losses": "net operating losses",
    "nol": "net operating losses",
    "nols": "net operating losses",
    "section 172": "net operating losses",
    "irc 172": "net operating losses",
    "172": "net operating losses",
    "nol carryover": "net operating losses",
    "nol carryforward": "net operating losses",
    "nol carry forward": "net operating losses",
    "nol carryback": "net operating losses",
    "nol carry back": "net operating losses",
    "nol deduction": "net operating losses",
    "operating loss": "net operating losses",
    "operating losses": "net operating losses",

    # S-Corporation Shareholder Basis - Loss Limitations
    "s-corp shareholder basis": "s-corp shareholder basis",
    "s corp shareholder basis": "s-corp shareholder basis",
    "s corporation shareholder basis": "s-corp shareholder basis",
    "shareholder basis": "s-corp shareholder basis",
    "s-corp basis": "s-corp shareholder basis",
    "s corp basis": "s-corp shareholder basis",
    "basis limitation": "s-corp shareholder basis",
    "basis limitations": "s-corp shareholder basis",
    "s-corp loss limitation": "s-corp shareholder basis",
    "s corp loss limitation": "s-corp shareholder basis",
    "loss limitation": "s-corp shareholder basis",
    "loss limitations": "s-corp shareholder basis",
    "basis loss limitation": "s-corp shareholder basis",
    "basis loss limitations": "s-corp shareholder basis",

    # Self-Employment Tax - §1401
    "self-employment tax": "self-employment tax",
    "self employment tax": "self-employment tax",
    "self-employment taxes": "self-employment tax",
    "self employment taxes": "self-employment tax",
    "section 1401": "self-employment tax",
    "irc 1401": "self-employment tax",
    "1401": "self-employment tax",
    "se tax": "self-employment tax",
    "se taxes": "self-employment tax",
    "self employment": "self-employment tax",
    "self-employed tax": "self-employment tax",
    "self employed tax": "self-employment tax",

    # Hobby Loss - §183 Activity Not Engaged for Profit (duplicate for synonym coverage)
    "183 activity not engaged for profit": "hobby loss rules",
    "activity not for profit": "hobby loss rules",
    "not engaged for profit": "hobby loss rules",
    "not for profit": "hobby loss rules",
    "not-for-profit": "hobby loss rules",
    "hobby activity": "hobby loss rules",
    "hobby activities": "hobby loss rules",

    # Passive Activity Loss Limitations - §469
    "passive activity loss limitation": "passive activity loss rules",
    "passive activity loss limitations": "passive activity loss rules",
    "passive loss limitations": "passive activity loss rules",
    "passive activity limitation": "passive activity loss rules",

    # At-Risk Limitations - §465
    "at-risk limitation": "at-risk limitations",
    "at risk limitation": "at-risk limitations",
    "at-risk limitations": "at-risk limitations",
    "at risk limitations": "at-risk limitations",
    "section 465": "at-risk limitations",
    "irc 465": "at-risk limitations",
    "465": "at-risk limitations",
    "at risk rules": "at-risk limitations",
    "at-risk rules": "at-risk limitations",
    "at-risk amount": "at-risk limitations",
    "at risk amount": "at-risk limitations",
    "at-risk basis": "at-risk limitations",
    "at risk basis": "at-risk limitations",

    # Like-Kind Exchange - §1031 (duplicate for synonym coverage)
    "like kind": "like-kind exchange",
    "like-kind": "like-kind exchange",
    "1031 like kind exchange": "like-kind exchange",
    "1031 like-kind exchange": "like-kind exchange",

    # Cancellation of Debt Income - §61/§108
    "cancellation of debt": "cancellation of debt income",
    "cancellation of debt income": "cancellation of debt income",
    "cod income": "cancellation of debt income",
    "cod": "cancellation of debt income",
    "section 61": "cancellation of debt income",
    "irc 61": "cancellation of debt income",
    "61": "cancellation of debt income",
    "section 108": "cancellation of debt income",
    "irc 108": "cancellation of debt income",
    "108": "cancellation of debt income",
    "debt forgiveness income": "cancellation of debt income",
    "debt cancellation": "cancellation of debt income",
    "debt discharge": "cancellation of debt income",
    "forgiven debt": "cancellation of debt income",
    "discharged debt": "cancellation of debt income",

    # Substantial Understatement Penalty - §6662
    "substantial understatement penalty": "substantial understatement penalty",
    "substantial understatement": "substantial understatement penalty",
    "section 6662": "substantial understatement penalty",
    "irc 6662": "substantial understatement penalty",
    "6662": "substantial understatement penalty",
    "accuracy related penalty": "substantial understatement penalty",
    "accuracy-related penalty": "substantial understatement penalty",
    "accuracy penalty": "substantial understatement penalty",
    "understatement penalty": "substantial understatement penalty",

    # Home Office Deduction - §280A (duplicate for synonym coverage)
    "home office deduction 280a": "home office deduction",
    "280a home office deduction": "home office deduction",
    "home office 280a": "home office deduction",

    # Additional synonyms, misspellings, and related terms for coverage
    "s corp comp": "s-corp reasonable compensation",
    "s corp comp.": "s-corp reasonable compensation",
    "s-corp comp.": "s-corp reasonable compensation",
    "reasonable comp.": "s-corp reasonable compensation",
    "officer comp": "s-corp reasonable compensation",
    "officer comp.": "s-corp reasonable compensation",
    "owner comp": "s-corp reasonable compensation",
    "owner comp.": "s-corp reasonable compensation",
    "shareholder comp": "s-corp reasonable compensation",
    "shareholder comp.": "s-corp reasonable compensation",
    "labor/capital allocation": "capital vs labor profit attribution",
    "capital/labor allocation": "capital vs labor profit attribution",
    "economic substance doctrine test": "economic substance doctrine",
    "business purpose test": "economic substance doctrine",
    "hobby income deduction": "hobby loss rules",
    "hobby activity deduction": "hobby loss rules",
    "business use home deduction": "home office deduction",
    "passive activity": "passive activity loss rules",
    "passive income loss": "passive activity loss rules",
    "passive income losses": "passive activity loss rules",
    "passive activity income loss": "passive activity loss rules",
    "like kind property exchange": "like-kind exchange",
    "like-kind property exchange": "like-kind exchange",
    "1031 property exchange": "like-kind exchange",
    "1031 property exchanges": "like-kind exchange",
    "percentage depletion oil & gas": "percentage depletion",
    "percentage depletion oil and gas": "percentage depletion",
    "oil gas depletion": "percentage depletion",
    "oil & gas depletion deduction": "percentage depletion",
    "oil and gas depletion deduction": "percentage depletion",
    "idc oil and gas": "intangible drilling costs",
    "idc oil & gas": "intangible drilling costs",
    "qualified business income deduction 199a": "qualified business income deduction",
    "qualified business income 199a": "qualified business income deduction",
    "qualified business deduction 199a": "qualified business income deduction",
    "statute of limitations assessment": "statute of limitations",
    "statute of limitations collection": "statute of limitations",
    "offer in compromise irs": "offer in compromise",
    "erc cares act": "employee retention credit",
    "employee retention cares act": "employee retention credit",
    "worker classification test": "worker classification",
    "employee contractor test": "worker classification",
    "contractor employee test": "worker classification",
    "conservation easement syndication": "conservation easements",
    "syndicated conservation": "conservation easements",
    "micro-captive insurance 831b": "micro-captive insurance",
    "micro captive insurance 831b": "micro-captive insurance",
    "related party transaction 267": "related party transactions",
    "related party transaction 707b": "related party transactions",
    "partnership special allocation 704b": "partnership special allocations",
    "wash sale 1091": "wash sale rules",
    "net operating loss 172": "net operating losses",
    "s-corp shareholder basis limitation": "s-corp shareholder basis",
    "self-employment tax 1401": "self-employment tax",
    "hobby loss 183": "hobby loss rules",
    "passive activity loss 469": "passive activity loss rules",
    "at-risk limitation 465": "at-risk limitations",
    "like-kind exchange 1031": "like-kind exchange",
    "cancellation of debt 108": "cancellation of debt income",
    "substantial understatement penalty 6662": "substantial understatement penalty",
    "home office deduction 280a": "home office deduction",
    "passive activity income": "passive activity loss rules",
    "passive activity deduction": "passive activity loss rules",
    "passive activity loss carryover": "passive activity loss rules",
    "passive activity loss carry forward": "passive activity loss rules",
    "passive activity loss carryforward": "passive activity loss rules",
    "nol carryover deduction": "net operating losses",
    "nol carryforward deduction": "net operating losses",
    "nol carryback deduction": "net operating losses",
    "nol carry back deduction": "net operating losses",
    "nol deduction 172": "net operating losses",
    "nol 172": "net operating losses",
    "basis limitation s-corp": "s-corp shareholder basis",
    "basis limitation s corp": "s-corp shareholder basis",
    "basis limitation s corporation": "s-corp shareholder basis",
    "se tax 1401": "self-employment tax",
    "self-employment tax deduction": "self-employment tax",
    "self employment tax deduction": "self-employment tax",
    "self-employed tax deduction": "self-employment tax",
    "self employed tax deduction": "self-employment tax",
    "at-risk limitation deduction": "at-risk limitations",
    "at risk limitation deduction": "at-risk limitations",
    "at-risk deduction": "at-risk limitations",
    "at risk deduction": "at-risk limitations",
    "like-kind exchange boot": "like-kind exchange",
    "like kind exchange boot": "like-kind exchange",
    "1031 boot": "like-kind exchange",
    "1031 exchange boot": "like-kind exchange",
    "cancellation of debt exclusion": "cancellation of debt income",
    "cod exclusion": "cancellation of debt income",
    "debt cancellation exclusion": "cancellation of debt income",
    "debt forgiveness exclusion": "cancellation of debt income",
    "substantial understatement": "substantial understatement penalty",
    "accuracy penalty 6662": "substantial understatement penalty",
    "accuracy-related penalty 6662": "substantial understatement penalty",
    "accuracy related penalty 6662": "substantial understatement penalty",
    "home office deduction simplified": "home office deduction",
    "home office deduction regular": "home office deduction",
    "home office deduction method": "home office deduction",
    "home office deduction methods": "home office deduction",
    "home office deduction calculation": "home office deduction",
    "home office deduction calculation method": "home office deduction",
    "home office deduction calculation methods": "home office deduction",
    "home office deduction calculation simplified": "home office deduction",
    "home office deduction calculation regular": "home office deduction",
    "home office deduction simplified method": "home office deduction",
    "home office deduction regular method": "home office deduction",
    "home office deduction irc 280a": "home office deduction",
    "home office deduction section 280a": "home office deduction",
    "home office deduction 280a": "home office deduction",
    "home office deduction tax": "home office deduction",
    "home office deduction taxes": "home office deduction",
    "home office deduction expense": "home office deduction",
    "home office deduction expenses": "home office deduction",
    "home office deduction write off": "home office deduction",
    "home office deduction write-off": "home office deduction",
    "home office deduction write offs": "home office deduction",
    "home office deduction write-offs": "home office deduction",
    "home office deduction business use": "home office deduction",
    "home office deduction business use of home": "home office deduction",
    "home office deduction office in home": "home office deduction",
    "home office deduction business home": "home office deduction",
    "home office deduction business home deduction": "home office deduction",
    "home office deduction office": "home office deduction",
    "home office deduction home": "home office deduction",
    "home office deduction home office": "home office deduction",
    "home office deduction home office deduction": "home office deduction",
    "home office deduction home office expenses": "home office deduction",
    "home office deduction home office expense": "home office deduction",
    "home office deduction home office write off": "home office deduction",
    "home office deduction home office write-off": "home office deduction",
    "home office deduction home office write offs": "home office deduction",
    "home office deduction home office write-offs": "home office deduction",
    "home office deduction home office business use": "home office deduction",
    "home office deduction home office business use of home": "home office deduction",
    "home office deduction home office office in home": "home office deduction",
    "home office deduction home office business home": "home office deduction",
    "home office deduction home office business home deduction": "home office deduction",
    "home office deduction home office office": "home office deduction",
    "home office deduction home office home": "home office deduction",
    "home office deduction home office home office": "home office deduction",
    "home office deduction home office home office deduction": "home office deduction",
    "home office deduction home office home office expenses": "home office deduction",
    "home office deduction home office home office expense": "home office deduction",
    "home office deduction home office home office write off": "home office deduction",
    "home office deduction home office home office write-off": "home office deduction",
    "home office deduction home office home office write offs": "home office deduction",
    "home office deduction home office home office write-offs": "home office deduction",
    "home office deduction home office home office business use": "home office deduction",
    "home office deduction home office home office business use of home": "home office deduction",
    "home office deduction home office home office office in home": "home office deduction",
    "home office deduction home office home office business home": "home office deduction",
    "home office deduction home office home office business home deduction": "home office deduction",
    "home office deduction home office home office office": "home office deduction",
    "home office deduction home office home office home": "home office deduction",
    "home office deduction home office home office home office": "home office deduction",
    "home office deduction home office home office home office deduction": "home office deduction",
    "home office deduction home office home office home office expenses": "home office deduction",
    "home office deduction home office home office home office expense": "home office deduction",
    "home office deduction home office home office home office write off": "home office deduction",
    "home office deduction home office home office home office write-off": "home office deduction",
    "home office deduction home office home office home office write offs": "home office deduction",
    "home office deduction home office home office home office write-offs": "home office deduction",
    "home office deduction home office home office home office business use": "home office deduction",
    "home office deduction home office home office home office business use of home": "home office deduction",
    "home office deduction home office home office home office office in home": "home office deduction",
    "home office deduction home office home office home office business home": "home office deduction",
    "home office deduction home office home office home office business home deduction": "home office deduction",
    "home office deduction home office home office home office office": "home office deduction",
    "home office deduction home office home office home office home": "home office deduction",
    "home office deduction home office home office home office home office": "home office deduction",
    "home office deduction home office home office home office home office deduction": "home office deduction",
    "home office deduction home office home office home office home office expenses": "home office deduction",
    "home office deduction home office home office home office home office expense": "home office deduction",
    "home office deduction home office home office home office home office write off": "home office deduction",
    "home office deduction home office home office home office home office write-off": "home office deduction",
    "home office deduction home office home office home office home office write offs": "home office deduction",
    "home office deduction home office home office home office home office write-offs": "home office deduction",
    "home office deduction home office home office home office home office business use": "home office deduction",
    "home office deduction home office home office home office home office business use of home": "home office deduction",
    "home office deduction home office home office home office home office office in home": "home office deduction",
    "home office deduction home office home office home office home office business home": "home office deduction",
    "home office deduction home office home office home office home office business home deduction": "home office deduction",
    "home office deduction home office home office home office home office office": "home office deduction",
    "home office deduction home office home office home office home office home": "home office deduction",
    "home office deduction home office home office home office home office home office": "home office deduction",
    "home office deduction home office home office home office home office home office deduction": "home office deduction",
    "home office deduction home office home office home office home office home office expenses": "home office deduction",
    "home office deduction home office home office home office home office home office expense": "home office deduction",
    "home office deduction home office home office home office home office home office write off": "home office deduction",
    "home office deduction home office home office home office home office home office write-off": "home office deduction",
    "home office deduction home office home office home office home office home office write offs": "home office deduction",
    "home office deduction home office home office home office home office home office write-offs": "home office deduction",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}=>{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}|{SEMANTIC_MAP_AUTHOR}|{SEMANTIC_MAP_ENGINE}|{_EXPECTED_ENTRY_COUNT}"
    data = meta + "|" + joined
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    expected_count = _EXPECTED_ENTRY_COUNT
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == expected_count) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.lower().strip()
    t = re.sub(r"[\s\-]+", " ", t)
    t = t.replace("§", "")
    t = t.replace(".", "")
    t = t.replace(",", "")
    t = t.replace("–", "-")
    t = t.replace("—", "-")
    t = t.replace("‘", "'").replace("’", "'")
    t = t.replace("“", '"').replace("”", '"')
    t = t.replace(" ", " ")  # non-breaking space
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)