import hashlib
import re
from typing import Dict, List, Any

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "OFE12 Team"
SEMANTIC_MAP_ENGINE = "OFE12_pipeline_systems"

SEMANTIC_MAP = {
    # Pipeline Hydraulics: Darcy-Weisbach and Moody Friction
    "darcy-weisbach": "darcy_weisbach",
    "darcy weisbach": "darcy_weisbach",
    "darcyweisbach": "darcy_weisbach",
    "dw equation": "darcy_weisbach",
    "darcy equation": "darcy_weisbach",
    "moody friction": "moody_friction",
    "moody diagram": "moody_friction",
    "moody chart": "moody_friction",
    "friction factor": "moody_friction",
    "pipe friction": "moody_friction",
    "relative roughness": "moody_friction",
    "reynolds number": "reynolds_number",
    "re number": "reynolds_number",
    "reynold's number": "reynolds_number",
    "turbulent flow": "turbulent_flow",
    "laminar flow": "laminar_flow",
    "transition flow": "transition_flow",
    "flow regime": "flow_regime",
    "hydraulic gradient": "hydraulic_gradient",
    "pressure drop": "pressure_drop",
    "delta p": "pressure_drop",
    "dp": "pressure_drop",
    "head loss": "pressure_drop",
    "energy loss": "pressure_drop",
    "velocity": "velocity",
    "flow velocity": "velocity",
    "fluid velocity": "velocity",
    "average velocity": "velocity",
    "throughput": "throughput",
    "flowrate": "throughput",
    "flow rate": "throughput",
    "q": "throughput",
    "volumetric flow": "throughput",
    "mass flow": "throughput",
    "pipeline sizing": "pipeline_sizing",
    "pipe sizing": "pipeline_sizing",
    "diameter selection": "pipeline_sizing",
    "pipe diameter": "pipeline_sizing",
    "nominal diameter": "pipeline_sizing",
    "dn": "pipeline_sizing",
    "sch": "pipe_schedule",
    "schedule": "pipe_schedule",
    "pipe schedule": "pipe_schedule",
    "wall thickness": "wall_thickness",
    "pipe thickness": "wall_thickness",
    "t": "wall_thickness",
    "outside diameter": "outside_diameter",
    "od": "outside_diameter",
    "inside diameter": "inside_diameter",
    "id": "inside_diameter",
    "pipe material": "pipe_material",
    "pipeline material": "pipe_material",
    "steel grade": "pipe_material",
    "api 5l": "api_5l",
    "api5l": "api_5l",
    "api 5l x52": "api_5l_x52",
    "x52": "api_5l_x52",
    "grade x52": "api_5l_x52",
    "api 5l x65": "api_5l_x65",
    "x65": "api_5l_x65",
    "grade x65": "api_5l_x65",
    "api 5l x70": "api_5l_x70",
    "x70": "api_5l_x70",
    "grade x70": "api_5l_x70",
    "api 5l x80": "api_5l_x80",
    "x80": "api_5l_x80",
    "grade x80": "api_5l_x80",
    "pipe grade": "pipe_material",
    "carbon steel": "pipe_material",
    "cs": "pipe_material",
    "pipeline welding": "pipeline_welding",
    "welding procedure": "pipeline_welding",
    "wps": "welding_procedure_specification",
    "welding procedure specification": "welding_procedure_specification",
    "pqr": "procedure_qualification_record",
    "procedure qualification record": "procedure_qualification_record",
    "smaw": "shielded_metal_arc_welding",
    "shielded metal arc welding": "shielded_metal_arc_welding",
    "stick welding": "shielded_metal_arc_welding",
    "manual welding": "shielded_metal_arc_welding",
    "gmaw": "gas_metal_arc_welding",
    "gas metal arc welding": "gas_metal_arc_welding",
    "mig welding": "gas_metal_arc_welding",
    "semiautomatic welding": "gas_metal_arc_welding",
    "pipeline coating": "pipeline_coating",
    "pipe coating": "pipeline_coating",
    "coating": "pipeline_coating",
    "fbe": "fusion_bonded_epoxy",
    "fusion bonded epoxy": "fusion_bonded_epoxy",
    "epoxy coating": "fusion_bonded_epoxy",
    "three-layer polyethylene": "three_layer_polyethylene",
    "3lpe": "three_layer_polyethylene",
    "triple layer pe": "three_layer_polyethylene",
    "polyethylene coating": "three_layer_polyethylene",
    "pipeline construction": "pipeline_construction",
    "construction": "pipeline_construction",
    "row clearing": "row_clearing",
    "right of way clearing": "row_clearing",
    "right-of-way clearing": "row_clearing",
    "clearing": "row_clearing",
    "trenching": "trenching",
    "excavation": "trenching",
    "digging": "trenching",
    "backfill": "backfill",
    "backfilling": "backfill",
    "pipe bedding": "backfill",
    "horizontal directional drilling": "horizontal_directional_drilling",
    "hdd": "horizontal_directional_drilling",
    "directional drilling": "horizontal_directional_drilling",
    "bore crossing": "bore_crossing",
    "crossing": "bore_crossing",
    "pipeline crossing": "bore_crossing",
    "river crossing": "bore_crossing",
    "pipeline pigging": "pipeline_pigging",
    "pigging": "pipeline_pigging",
    "pig": "pipeline_pigging",
    "cleaning pig": "cleaning_pig",
    "gauging pig": "gauging_pig",
    "intelligent pig": "intelligent_pig",
    "smart pig": "intelligent_pig",
    "ili": "inline_inspection",
    "inline inspection": "inline_inspection",
    "mfl": "magnetic_flux_leakage",
    "magnetic flux leakage": "magnetic_flux_leakage",
    "ultrasonic": "ultrasonic_inspection",
    "ultrasonic inspection": "ultrasonic_inspection",
    "caliper": "caliper_inspection",
    "caliper pig": "caliper_inspection",
    "geometry pig": "caliper_inspection",
    "pipeline integrity management": "pipeline_integrity_management",
    "pims": "pipeline_integrity_management",
    "integrity management": "pipeline_integrity_management",
    "api 1160": "api_1160",
    "pipeline stress analysis": "pipeline_stress_analysis",
    "stress analysis": "pipeline_stress_analysis",
    "asme b31.4": "asme_b31_4",
    "asme b31.8": "asme_b31_8",
    "b31.4": "asme_b31_4",
    "b31.8": "asme_b31_8",
    "pipeline cathodic protection": "pipeline_cathodic_protection",
    "cathodic protection": "pipeline_cathodic_protection",
    "cp": "pipeline_cathodic_protection",
    "cp survey": "cp_survey",
    "cips": "close_interval_potential_survey",
    "close interval potential survey": "close_interval_potential_survey",
    "dcvg": "direct_current_voltage_gradient",
    "direct current voltage gradient": "direct_current_voltage_gradient",
    "pipeline scada": "pipeline_scada",
    "scada": "pipeline_scada",
    "supervisory control and data acquisition": "pipeline_scada",
    "leak detection": "leak_detection",
    "ld": "leak_detection",
    "cpm": "computational_pipeline_monitoring",
    "computational pipeline monitoring": "computational_pipeline_monitoring",
    "rttm": "real_time_transient_modeling",
    "real time transient modeling": "real_time_transient_modeling",
    "pipeline right of way acquisition": "pipeline_row_acquisition",
    "right of way acquisition": "pipeline_row_acquisition",
    "row acquisition": "pipeline_row_acquisition",
    "easement": "easement",
    "pipeline regulatory compliance": "pipeline_regulatory_compliance",
    "regulatory compliance": "pipeline_regulatory_compliance",
    "phmsa": "phmsa",
    "phmsa cfr 49": "phmsa_cfr_49",
    "cfr 49": "phmsa_cfr_49",
    "cfr 49 part 192": "phmsa_cfr_49_part_192",
    "cfr 49 part 195": "phmsa_cfr_49_part_195",
    "pipeline hydrostatic testing": "pipeline_hydrostatic_testing",
    "hydrostatic testing": "pipeline_hydrostatic_testing",
    "hydrotest": "pipeline_hydrostatic_testing",
    "strength test": "strength_test",
    "leak test": "leak_test",
    "compressor station": "compressor_station",
    "compressor": "compressor_station",
    "centrifugal compressor": "centrifugal_compressor",
    "reciprocating compressor": "reciprocating_compressor",
    "pump station": "pump_station",
    "pump": "pump_station",
    "centrifugal pump": "centrifugal_pump",
    "positive displacement pump": "positive_displacement_pump",
    "pipeline flow assurance": "pipeline_flow_assurance",
    "flow assurance": "pipeline_flow_assurance",
    "hydrate": "hydrate",
    "gas hydrate": "hydrate",
    "wax": "wax",
    "asphaltene": "asphaltene",
    "pipeline decommissioning": "pipeline_decommissioning",
    "decommissioning": "pipeline_decommissioning",
    "abandonment": "abandonment",
    "purging": "purging",
    # Synonyms, abbreviations, misspellings, related terms
    "pipe": "pipeline",
    "pipeline": "pipeline",
    "pipline": "pipeline",
    "pipelines": "pipeline",
    "transmission pipeline": "pipeline",
    "distribution pipeline": "pipeline",
    "mainline": "pipeline",
    "trunkline": "pipeline",
    "spur line": "pipeline",
    "branch line": "pipeline",
    "pipeline segment": "pipeline",
    "pipeline section": "pipeline",
    "pipeline route": "pipeline_route",
    "route": "pipeline_route",
    "alignment": "pipeline_route",
    "pipeline alignment": "pipeline_route",
    "pipeline corridor": "pipeline_route",
    "corridor": "pipeline_route",
    "pipeline survey": "pipeline_survey",
    "survey": "pipeline_survey",
    "topographic survey": "pipeline_survey",
    "geotechnical survey": "pipeline_survey",
    "hydrographic survey": "pipeline_survey",
    "environmental survey": "pipeline_survey",
    "pipeline design": "pipeline_design",
    "design": "pipeline_design",
    "engineering design": "pipeline_design",
    "pipeline engineer": "pipeline_design",
    "pipeline engineering": "pipeline_design",
    "pipeline drawing": "pipeline_drawing",
    "drawing": "pipeline_drawing",
    "isometric drawing": "pipeline_drawing",
    "p&id": "pipeline_drawing",
    "piping and instrumentation diagram": "pipeline_drawing",
    "general arrangement": "pipeline_drawing",
    "ga drawing": "pipeline_drawing",
    "pipeline specification": "pipeline_specification",
    "specification": "pipeline_specification",
    "pipe spec": "pipeline_specification",
    "material specification": "pipeline_specification",
    "pipeline procurement": "pipeline_procurement",
    "procurement": "pipeline_procurement",
    "purchase": "pipeline_procurement",
    "purchase order": "pipeline_procurement",
    "po": "pipeline_procurement",
    "pipeline logistics": "pipeline_logistics",
    "logistics": "pipeline_logistics",
    "transportation": "pipeline_logistics",
    "shipping": "pipeline_logistics",
    "pipeline storage": "pipeline_storage",
    "storage": "pipeline_storage",
    "yard": "pipeline_storage",
    "pipe yard": "pipeline_storage",
    "pipeline handling": "pipeline_handling",
    "handling": "pipeline_handling",
    "lifting": "pipeline_handling",
    "pipeline installation": "pipeline_installation",
    "installation": "pipeline_installation",
    "laying": "pipeline_installation",
    "pipe laying": "pipeline_installation",
    "pipeline testing": "pipeline_testing",
    "testing": "pipeline_testing",
    "pressure testing": "pipeline_testing",
    "pipeline commissioning": "pipeline_commissioning",
    "commissioning": "pipeline_commissioning",
    "startup": "pipeline_commissioning",
    "pipeline operation": "pipeline_operation",
    "operation": "pipeline_operation",
    "operating": "pipeline_operation",
    "pipeline maintenance": "pipeline_maintenance",
    "maintenance": "pipeline_maintenance",
    "repair": "pipeline_maintenance",
    "pipeline repair": "pipeline_maintenance",
    "pipeline monitoring": "pipeline_monitoring",
    "monitoring": "pipeline_monitoring",
    "pipeline control": "pipeline_control",
    "control": "pipeline_control",
    "pipeline automation": "pipeline_automation",
    "automation": "pipeline_automation",
    "pipeline safety": "pipeline_safety",
    "safety": "pipeline_safety",
    "safe operation": "pipeline_safety",
    "pipeline risk": "pipeline_risk",
    "risk": "pipeline_risk",
    "risk assessment": "pipeline_risk",
    "pipeline hazard": "pipeline_risk",
    "hazard": "pipeline_risk",
    "hazard analysis": "pipeline_risk",
    "pipeline emergency": "pipeline_emergency",
    "emergency": "pipeline_emergency",
    "emergency response": "pipeline_emergency",
    "pipeline incident": "pipeline_incident",
    "incident": "pipeline_incident",
    "pipeline accident": "pipeline_incident",
    "accident": "pipeline_incident",
    "pipeline leak": "pipeline_leak",
    "leak": "pipeline_leak",
    "pipeline rupture": "pipeline_rupture",
    "rupture": "pipeline_rupture",
    "pipeline failure": "pipeline_failure",
    "failure": "pipeline_failure",
    "pipeline corrosion": "pipeline_corrosion",
    "corrosion": "pipeline_corrosion",
    "internal corrosion": "pipeline_corrosion",
    "external corrosion": "pipeline_corrosion",
    "pipeline erosion": "pipeline_erosion",
    "erosion": "pipeline_erosion",
    "pipeline cracking": "pipeline_cracking",
    "cracking": "pipeline_cracking",
    "pipeline fatigue": "pipeline_fatigue",
    "fatigue": "pipeline_fatigue",
    "pipeline buckling": "pipeline_buckling",
    "buckling": "pipeline_buckling",
    "pipeline stress": "pipeline_stress",
    "stress": "pipeline_stress",
    "pipeline strain": "pipeline_strain",
    "strain": "pipeline_strain",
    "pipeline displacement": "pipeline_displacement",
    "displacement": "pipeline_displacement",
    "pipeline settlement": "pipeline_settlement",
    "settlement": "pipeline_settlement",
    "pipeline movement": "pipeline_movement",
    "movement": "pipeline_movement",
    "pipeline expansion": "pipeline_expansion",
    "expansion": "pipeline_expansion",
    "pipeline contraction": "pipeline_contraction",
    "contraction": "pipeline_contraction",
    "pipeline temperature": "pipeline_temperature",
    "temperature": "pipeline_temperature",
    "pipeline pressure": "pipeline_pressure",
    "pressure": "pipeline_pressure",
    "pipeline flow": "pipeline_flow",
    "flow": "pipeline_flow",
    "pipeline fluid": "pipeline_fluid",
    "fluid": "pipeline_fluid",
    "pipeline gas": "pipeline_gas",
    "gas": "pipeline_gas",
    "pipeline liquid": "pipeline_liquid",
    "liquid": "pipeline_liquid",
    "pipeline oil": "pipeline_oil",
    "oil": "pipeline_oil",
    "pipeline water": "pipeline_water",
    "water": "pipeline_water",
    "pipeline product": "pipeline_product",
    "product": "pipeline_product",
    "pipeline batch": "pipeline_batch",
    "batch": "pipeline_batch",
    "pipeline slug": "pipeline_slug",
    "slug": "pipeline_slug",
    "pipeline pig": "pipeline_pigging",
    "pipeline valve": "pipeline_valve",
    "valve": "pipeline_valve",
    "mainline valve": "pipeline_valve",
    "block valve": "pipeline_valve",
    "check valve": "pipeline_valve",
    "pressure relief valve": "pipeline_valve",
    "prv": "pipeline_valve",
    "pipeline flange": "pipeline_flange",
    "flange": "pipeline_flange",
    "pipeline fitting": "pipeline_fitting",
    "fitting": "pipeline_fitting",
    "pipeline tee": "pipeline_fitting",
    "tee": "pipeline_fitting",
    "pipeline elbow": "pipeline_fitting",
    "elbow": "pipeline_fitting",
    "pipeline reducer": "pipeline_fitting",
    "reducer": "pipeline_fitting",
    "pipeline cap": "pipeline_fitting",
    "cap": "pipeline_fitting",
    "pipeline coupling": "pipeline_fitting",
    "coupling": "pipeline_fitting",
    "pipeline gasket": "pipeline_gasket",
    "gasket": "pipeline_gasket",
    "pipeline bolt": "pipeline_bolt",
    "bolt": "pipeline_bolt",
    "pipeline nut": "pipeline_nut",
    "nut": "pipeline_nut",
    "pipeline support": "pipeline_support",
    "support": "pipeline_support",
    "pipe support": "pipeline_support",
    "pipeline anchor": "pipeline_anchor",
    "anchor": "pipeline_anchor",
    "pipeline guide": "pipeline_guide",
    "guide": "pipeline_guide",
    "pipeline shoe": "pipeline_shoe",
    "shoe": "pipeline_shoe",
    "pipeline saddle": "pipeline_saddle",
    "saddle": "pipeline_saddle",
    "pipeline clamp": "pipeline_clamp",
    "clamp": "pipeline_clamp",
    "pipeline hanger": "pipeline_hanger",
    "hanger": "pipeline_hanger",
    "pipeline insulation": "pipeline_insulation",
    "insulation": "pipeline_insulation",
    "pipeline heat tracing": "pipeline_heat_tracing",
    "heat tracing": "pipeline_heat_tracing",
    "pipeline painting": "pipeline_painting",
    "painting": "pipeline_painting",
    "pipeline marking": "pipeline_marking",
    "marking": "pipeline_marking",
    "pipeline signage": "pipeline_signage",
    "signage": "pipeline_signage",
    "pipeline label": "pipeline_label",
    "label": "pipeline_label",
    "pipeline tag": "pipeline_tag",
    "tag": "pipeline_tag",
    "pipeline documentation": "pipeline_documentation",
    "documentation": "pipeline_documentation",
    "document": "pipeline_documentation",
    "pipeline record": "pipeline_documentation",
    "record": "pipeline_documentation",
    "pipeline report": "pipeline_documentation",
    "report": "pipeline_documentation",
    "pipeline data": "pipeline_data",
    "data": "pipeline_data",
    "pipeline database": "pipeline_data",
    "database": "pipeline_data",
    "pipeline software": "pipeline_software",
    "software": "pipeline_software",
    "pipeline simulation": "pipeline_simulation",
    "simulation": "pipeline_simulation",
    "pipeline modeling": "pipeline_modeling",
    "modeling": "pipeline_modeling",
    "pipeline model": "pipeline_modeling",
    "model": "pipeline_modeling",
    "pipeline analysis": "pipeline_analysis",
    "analysis": "pipeline_analysis",
    "pipeline calculation": "pipeline_calculation",
    "calculation": "pipeline_calculation",
    "pipeline formula": "pipeline_calculation",
    "formula": "pipeline_calculation",
    "pipeline equation": "pipeline_calculation",
    "equation": "pipeline_calculation",
    "pipeline standard": "pipeline_standard",
    "standard": "pipeline_standard",
    "pipeline code": "pipeline_standard",
    "code": "pipeline_standard",
    "pipeline regulation": "pipeline_standard",
    "regulation": "pipeline_standard",
    "pipeline guideline": "pipeline_standard",
    "guideline": "pipeline_standard",
    "pipeline requirement": "pipeline_standard",
    "requirement": "pipeline_standard",
    "pipeline specification": "pipeline_specification",
    "specification": "pipeline_specification",
    "pipeline compliance": "pipeline_regulatory_compliance",
    "compliance": "pipeline_regulatory_compliance",
    "pipeline permit": "pipeline_permit",
    "permit": "pipeline_permit",
    "pipeline approval": "pipeline_permit",
    "approval": "pipeline_permit",
    "pipeline authorization": "pipeline_permit",
    "authorization": "pipeline_permit",
    "pipeline license": "pipeline_permit",
    "license": "pipeline_permit",
    "pipeline certification": "pipeline_certification",
    "certification": "pipeline_certification",
    "pipeline qualification": "pipeline_certification",
    "qualification": "pipeline_certification",
    "pipeline training": "pipeline_training",
    "training": "pipeline_training",
    "pipeline education": "pipeline_training",
    "education": "pipeline_training",
    "pipeline skill": "pipeline_training",
    "skill": "pipeline_training",
    "pipeline competency": "pipeline_training",
    "competency": "pipeline_training",
    "pipeline personnel": "pipeline_personnel",
    "personnel": "pipeline_personnel",
    "pipeline worker": "pipeline_personnel",
    "worker": "pipeline_personnel",
    "pipeline operator": "pipeline_personnel",
    "operator": "pipeline_personnel",
    "pipeline supervisor": "pipeline_personnel",
    "supervisor": "pipeline_personnel",
    "pipeline manager": "pipeline_personnel",
    "manager": "pipeline_personnel",
    "pipeline inspector": "pipeline_personnel",
    "inspector": "pipeline_personnel",
    "pipeline auditor": "pipeline_personnel",
    "auditor": "pipeline_personnel",
    "pipeline contractor": "pipeline_personnel",
    "contractor": "pipeline_personnel",
    "pipeline consultant": "pipeline_personnel",
    "consultant": "pipeline_personnel",
    "pipeline client": "pipeline_personnel",
    "client": "pipeline_personnel",
    "pipeline owner": "pipeline_personnel",
    "owner": "pipeline_personnel",
    "pipeline stakeholder": "pipeline_personnel",
    "stakeholder": "pipeline_personnel",
    "pipeline customer": "pipeline_personnel",
    "customer": "pipeline_personnel",
    "pipeline user": "pipeline_personnel",
    "user": "pipeline_personnel",
    "pipeline investor": "pipeline_personnel",
    "investor": "pipeline_personnel",
    "pipeline shareholder": "pipeline_personnel",
    "shareholder": "pipeline_personnel",
    "pipeline government": "pipeline_personnel",
    "government": "pipeline_personnel",
    "pipeline authority": "pipeline_personnel",
    "authority": "pipeline_personnel",
    "pipeline agency": "pipeline_personnel",
    "agency": "pipeline_personnel",
    "pipeline regulator": "pipeline_personnel",
    "regulator": "pipeline_personnel",
    "pipeline ministry": "pipeline_personnel",
    "ministry": "pipeline_personnel",
    "pipeline department": "pipeline_personnel",
    "department": "pipeline_personnel",
    "pipeline organization": "pipeline_personnel",
    "organization": "pipeline_personnel",
    "pipeline company": "pipeline_personnel",
    "company": "pipeline_personnel",
    "pipeline firm": "pipeline_personnel",
    "firm": "pipeline_personnel",
    "pipeline group": "pipeline_personnel",
    "group": "pipeline_personnel",
    "pipeline team": "pipeline_personnel",
    "team": "pipeline_personnel",
    "pipeline crew": "pipeline_personnel",
    "crew": "pipeline_personnel",
    "pipeline staff": "pipeline_personnel",
    "staff": "pipeline_personnel",
    "pipeline member": "pipeline_personnel",
    "member": "pipeline_personnel",
    "pipeline participant": "pipeline_personnel",
    "participant": "pipeline_personnel",
    "pipeline attendee": "pipeline_personnel",
    "attendee": "pipeline_personnel",
    "pipeline guest": "pipeline_personnel",
    "guest": "pipeline_personnel",
    "pipeline visitor": "pipeline_personnel",
    "visitor": "pipeline_personnel",
    "pipeline resident": "pipeline_personnel",
    "resident": "pipeline_personnel",
    "pipeline community": "pipeline_personnel",
    "community": "pipeline_personnel",
    "pipeline public": "pipeline_personnel",
    "public": "pipeline_personnel",
    "pipeline society": "pipeline_personnel",
    "society": "pipeline_personnel",
    "pipeline environment": "pipeline_environment",
    "environment": "pipeline_environment",
    "pipeline ecology": "pipeline_environment",
    "ecology": "pipeline_environment",
    "pipeline nature": "pipeline_environment",
    "nature": "pipeline_environment",
    "pipeline habitat": "pipeline_environment",
    "habitat": "pipeline_environment",
    "pipeline wildlife": "pipeline_environment",
    "wildlife": "pipeline_environment",
    "pipeline flora": "pipeline_environment",
    "flora": "pipeline_environment",
    "pipeline fauna": "pipeline_environment",
    "fauna": "pipeline_environment",
    "pipeline landscape": "pipeline_environment",
    "landscape": "pipeline_environment",
    "pipeline vegetation": "pipeline_environment",
    "vegetation": "pipeline_environment",
    "pipeline soil": "pipeline_environment",
    "soil": "pipeline_environment",
    "pipeline waterbody": "pipeline_environment",
    "waterbody": "pipeline_environment",
    "pipeline river": "pipeline_environment",
    "river": "pipeline_environment",
    "pipeline stream": "pipeline_environment",
    "stream": "pipeline_environment",
    "pipeline lake": "pipeline_environment",
    "lake": "pipeline_environment",
    "pipeline pond": "pipeline_environment",
    "pond": "pipeline_environment",
    "pipeline wetland": "pipeline_environment",
    "wetland": "pipeline_environment",
    "pipeline marsh": "pipeline_environment",
    "marsh": "pipeline_environment",
    "pipeline swamp": "pipeline_environment",
    "swamp": "pipeline_environment",
    "pipeline floodplain": "pipeline_environment",
    "floodplain": "pipeline_environment",
    "pipeline mountain": "pipeline_environment",
    "mountain": "pipeline_environment",
    "pipeline hill": "pipeline_environment",
    "hill": "pipeline_environment",
    "pipeline valley": "pipeline_environment",
    "valley": "pipeline_environment",
    "pipeline plain": "pipeline_environment",
    "plain": "pipeline_environment",
    "pipeline plateau": "pipeline_environment",
    "plateau": "pipeline_environment",
    "pipeline desert": "pipeline_environment",
    "desert": "pipeline_environment",
    "pipeline forest": "pipeline_environment",
    "forest": "pipeline_environment",
    "pipeline jungle": "pipeline_environment",
    "jungle": "pipeline_environment",
    "pipeline tundra": "pipeline_environment",
    "tundra": "pipeline_environment",
    "pipeline arctic": "pipeline_environment",
    "arctic": "pipeline_environment",
    "pipeline antarctic": "pipeline_environment",
    "antarctic": "pipeline_environment",
    "pipeline climate": "pipeline_environment",
    "climate": "pipeline_environment",
    "pipeline weather": "pipeline_environment",
    "weather": "pipeline_environment",
    "pipeline rainfall": "pipeline_environment",
    "rainfall": "pipeline_environment",
    "pipeline precipitation": "pipeline_environment",
    "precipitation": "pipeline_environment",
    "pipeline wind": "pipeline_environment",
    "wind": "pipeline_environment",
    "pipeline storm": "pipeline_environment",
    "storm": "pipeline_environment",
    "pipeline hurricane": "pipeline_environment",
    "hurricane": "pipeline_environment",
    "pipeline tornado": "pipeline_environment",
    "tornado": "pipeline_environment",
    "pipeline earthquake": "pipeline_environment",
    "earthquake": "pipeline_environment",
    "pipeline landslide": "pipeline_environment",
    "landslide": "pipeline_environment",
    "pipeline flood": "pipeline_environment",
    "flood": "pipeline_environment",
    "pipeline fire": "pipeline_environment",
    "fire": "pipeline_environment",
    "pipeline explosion": "pipeline_environment",
    "explosion": "pipeline_environment",
    "pipeline sabotage": "pipeline_environment",
    "sabotage": "pipeline_environment",
    "pipeline theft": "pipeline_environment",
    "theft": "pipeline_environment",
    "pipeline vandalism": "pipeline_environment",
    "vandalism": "pipeline_environment",
    "pipeline terrorism": "pipeline_environment",
    "terrorism": "pipeline_environment",
    "pipeline security": "pipeline_security",
    "security": "pipeline_security",
    "pipeline protection": "pipeline_security",
    "protection": "pipeline_security",
    "pipeline surveillance": "pipeline_security",
    "surveillance": "pipeline_security",
    "pipeline monitoring": "pipeline_security",
    "monitoring": "pipeline_security",
    "pipeline alarm": "pipeline_security",
    "alarm": "pipeline_security",
    "pipeline warning": "pipeline_security",
    "warning": "pipeline_security",
    "pipeline notification": "pipeline_security",
    "notification": "pipeline_security",
    "pipeline alert": "pipeline_security",
    "alert": "pipeline_security",
    "pipeline response": "pipeline_security",
    "response": "pipeline_security",
    "pipeline mitigation": "pipeline_security",
    "mitigation": "pipeline_security",
    "pipeline remediation": "pipeline_security",
    "remediation": "pipeline_security",
    "pipeline restoration": "pipeline_security",
    "restoration": "pipeline_security",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> Dict[str, Any]:
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (
        actual_count == _EXPECTED_ENTRY_COUNT and
        hash_now == _MAP_INTEGRITY_HASH
    )
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"[^\w\s\-\.]", "", t)
    t = re.sub(r"\s+", " ", t)
    t = t.replace("’", "'")
    t = t.replace("‘", "'")
    t = t.replace("`", "'")
    t = t.replace("–", "-")
    t = t.replace("—", "-")
    t = t.replace("_", " ")
    t = t.replace(".", "")
    t = t.strip()
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> List[str]:
    normalized = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == normalized and k != term:
            related.append(k)
    return related

def get_all_mappings() -> Dict[str, str]:
    return dict(SEMANTIC_MAP)