import hashlib
import re
from typing import Dict, List

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "SYN08_expert_witness"
SEMANTIC_MAP_ENGINE = "SYN08"
_EXPECTED_ENTRY_COUNT = 213

SEMANTIC_MAP: Dict[str, str] = {
    # Daubert Standard Federal Admissibility
    "daubert": "daubert_standard",
    "daubert standard": "daubert_standard",
    "daubert test": "daubert_standard",
    "daubert admissibility": "daubert_standard",
    "daubert v. merrell dow": "daubert_standard",
    "daubert v merrell dow": "daubert_standard",
    "daubert v. merrell dow pharmaceuticals": "daubert_standard",
    "daubert v merrell dow pharmaceuticals": "daubert_standard",
    "federal admissibility": "daubert_standard",
    "federal standard": "daubert_standard",
    "federal rule of evidence 702": "fre_702",
    "federal rules of evidence 702": "fre_702",
    "federal rules 702": "fre_702",
    "federal rules of evidence": "fre",
    "federal rules": "fre",
    "federal rules evidence": "fre",
    "f.r.e.": "fre",
    "f.r.e": "fre",
    "fre": "fre",
    "fre 702": "fre_702",
    "rule 702": "fre_702",
    "rule 702 fre": "fre_702",
    "702": "fre_702",
    "admissibility": "admissibility",
    "admissibility standard": "admissibility",
    "expert admissibility": "admissibility",
    "expert evidence admissibility": "admissibility",
    "expert testimony admissibility": "admissibility",
    "admissibility of expert testimony": "admissibility",
    "admissibility of expert evidence": "admissibility",
    # Frye General Acceptance Test
    "frye": "frye_test",
    "frye test": "frye_test",
    "frye standard": "frye_test",
    "frye rule": "frye_test",
    "general acceptance": "frye_test",
    "general acceptance test": "frye_test",
    "frye v. united states": "frye_test",
    "frye v united states": "frye_test",
    "frye v. us": "frye_test",
    "frye v us": "frye_test",
    "frye general acceptance": "frye_test",
    "frye admissibility": "frye_test",
    "general acceptance standard": "frye_test",
    "frye hearing": "frye_test",
    # FRE 702 Expert Testimony Requirements
    "expert testimony": "expert_testimony",
    "expert witness testimony": "expert_testimony",
    "expert evidence": "expert_testimony",
    "fre 702 requirements": "fre_702_requirements",
    "rule 702 requirements": "fre_702_requirements",
    "702 requirements": "fre_702_requirements",
    "expert qualifications": "expert_qualifications",
    "qualified expert": "expert_qualifications",
    "qualification of expert": "expert_qualifications",
    "qualification": "expert_qualifications",
    "expert qualification": "expert_qualifications",
    "expertise": "expert_qualifications",
    "reliable principles": "reliable_principles_methods",
    "reliable methods": "reliable_principles_methods",
    "reliable methodology": "reliable_principles_methods",
    "reliable techniques": "reliable_principles_methods",
    "methodology": "reliable_principles_methods",
    "principles and methods": "reliable_principles_methods",
    "scientific method": "reliable_principles_methods",
    "scientific methodology": "reliable_principles_methods",
    "helpfulness": "helpfulness",
    "assist trier of fact": "helpfulness",
    "assist jury": "helpfulness",
    "relevance": "relevance",
    "relevant evidence": "relevance",
    "fit": "fit_requirement",
    "fit requirement": "fit_requirement",
    "relevance and fit": "relevance_and_fit",
    "relevance and fit requirement": "relevance_and_fit",
    # Kumho Tire Extension to Technical Experts
    "kumho": "kumho_tire",
    "kumho tire": "kumho_tire",
    "kumho tire co. v. carmichael": "kumho_tire",
    "kumho tire co v carmichael": "kumho_tire",
    "kumho tire extension": "kumho_tire",
    "kumho extension": "kumho_tire",
    "kumho standard": "kumho_tire",
    "kumho test": "kumho_tire",
    "kumho applicability": "kumho_tire",
    "technical expert": "technical_expert",
    "technical experts": "technical_expert",
    "non-scientific expert": "technical_expert",
    "non scientific expert": "technical_expert",
    "engineering expert": "technical_expert",
    "engineering testimony": "technical_expert",
    "kumho tire application": "kumho_tire",
    # FRCP Rule 26(a)(2) Expert Disclosure
    "frcp": "frcp",
    "frcp 26": "frcp_26a2",
    "frcp 26(a)(2)": "frcp_26a2",
    "rule 26(a)(2)": "frcp_26a2",
    "rule 26": "frcp_26",
    "26(a)(2)": "frcp_26a2",
    "26a2": "frcp_26a2",
    "expert disclosure": "expert_disclosure",
    "expert witness disclosure": "expert_disclosure",
    "disclosure of experts": "expert_disclosure",
    "expert report": "expert_report",
    "expert reports": "expert_report",
    "report of expert": "expert_report",
    "expert witness report": "expert_report",
    "report content": "expert_report_content",
    "expert report content": "expert_report_content",
    "content of expert report": "expert_report_content",
    "report requirements": "expert_report_content",
    "expert report requirements": "expert_report_content",
    "requirements for expert report": "expert_report_content",
    "frcp 26(a)(2)(b)": "frcp_26a2b",
    "rule 26(a)(2)(b)": "frcp_26a2b",
    "26(a)(2)(b)": "frcp_26a2b",
    "26a2b": "frcp_26a2b",
    # FRE 703 Basis of Expert Opinion
    "fre 703": "fre_703",
    "rule 703": "fre_703",
    "703": "fre_703",
    "basis of expert opinion": "basis_expert_opinion",
    "basis for expert opinion": "basis_expert_opinion",
    "basis of opinion": "basis_expert_opinion",
    "basis for opinion": "basis_expert_opinion",
    "facts or data": "basis_expert_opinion",
    "facts and data": "basis_expert_opinion",
    "underlying facts": "basis_expert_opinion",
    "underlying data": "basis_expert_opinion",
    "expert opinion basis": "basis_expert_opinion",
    # Daubert Motion Practice and Timing
    "daubert motion": "daubert_motion",
    "daubert challenge": "daubert_motion",
    "motion to exclude expert": "daubert_motion",
    "motion to exclude expert testimony": "daubert_motion",
    "motion to strike expert": "daubert_motion",
    "motion to strike expert testimony": "daubert_motion",
    "timing of daubert motion": "daubert_motion_timing",
    "daubert motion timing": "daubert_motion_timing",
    "timing of motion": "daubert_motion_timing",
    "motion practice": "daubert_motion_practice",
    "daubert motion practice": "daubert_motion_practice",
    "motion in limine": "motion_in_limine",
    "motion in limine expert": "motion_in_limine",
    # Qualifications of Expert Witness
    "qualifications": "expert_qualifications",
    "witness qualifications": "expert_qualifications",
    "expert witness qualifications": "expert_qualifications",
    "expert witness qualification": "expert_qualifications",
    "expert witness": "expert_witness",
    "expert": "expert_witness",
    "witness": "expert_witness",
    "testifying expert": "expert_witness",
    "testifying witness": "expert_witness",
    "opinion witness": "expert_witness",
    # Hypothetical Questions to Experts
    "hypothetical question": "hypothetical_questions",
    "hypothetical questions": "hypothetical_questions",
    "hypotheticals": "hypothetical_questions",
    "posing hypotheticals": "hypothetical_questions",
    "hypothetical scenario": "hypothetical_questions",
    "hypothetical scenarios": "hypothetical_questions",
    "hypothetical to expert": "hypothetical_questions",
    "hypothetical to witness": "hypothetical_questions",
    # Cross-Examination of Expert Witnesses
    "cross examination": "cross_examination",
    "cross-examination": "cross_examination",
    "cross-examining expert": "cross_examination",
    "cross-examining witness": "cross_examination",
    "cross of expert": "cross_examination",
    "cross of witness": "cross_examination",
    "cross expert": "cross_examination",
    "cross witness": "cross_examination",
    "impeachment": "cross_examination",
    "impeach expert": "cross_examination",
    "impeach witness": "cross_examination",
    # Rebuttal Expert Testimony
    "rebuttal expert": "rebuttal_expert",
    "rebuttal expert testimony": "rebuttal_expert",
    "rebuttal testimony": "rebuttal_expert",
    "expert rebuttal": "rebuttal_expert",
    "rebuttal report": "rebuttal_expert",
    "rebuttal witness": "rebuttal_expert",
    # Expert Deposition Preparation
    "expert deposition": "expert_deposition",
    "deposition of expert": "expert_deposition",
    "expert witness deposition": "expert_deposition",
    "deposition preparation": "expert_deposition_preparation",
    "expert deposition preparation": "expert_deposition_preparation",
    "preparing expert for deposition": "expert_deposition_preparation",
    "deposition prep": "expert_deposition_preparation",
    "expert prep": "expert_deposition_preparation",
    # Opinion Scope and Ultimate Issue
    "opinion scope": "opinion_scope",
    "scope of opinion": "opinion_scope",
    "scope of expert opinion": "opinion_scope",
    "ultimate issue": "ultimate_issue",
    "ultimate issue testimony": "ultimate_issue",
    "opinion on ultimate issue": "ultimate_issue",
    "opinion on the ultimate issue": "ultimate_issue",
    "ultimate issue rule": "ultimate_issue",
    "fre 704": "fre_704",
    "rule 704": "fre_704",
    "704": "fre_704",
    # Expert Witness Immunity and Ethics
    "expert immunity": "expert_immunity",
    "witness immunity": "expert_immunity",
    "expert witness immunity": "expert_immunity",
    "expert ethics": "expert_ethics",
    "expert witness ethics": "expert_ethics",
    "ethics of expert": "expert_ethics",
    "ethics of expert witness": "expert_ethics",
    "ethical expert": "expert_ethics",
    "ethical obligations": "expert_ethics",
    "ethical duties": "expert_ethics",
    # Testability and Falsifiability Daubert Factor
    "testability": "testability",
    "falsifiability": "testability",
    "testable": "testability",
    "falsifiable": "testability",
    "daubert testability": "testability",
    "daubert falsifiability": "testability",
    "testability factor": "testability",
    "falsifiability factor": "testability",
    # Peer Review and Publication Daubert Factor
    "peer review": "peer_review_publication",
    "peer-reviewed": "peer_review_publication",
    "peer reviewed": "peer_review_publication",
    "publication": "peer_review_publication",
    "published": "peer_review_publication",
    "peer review factor": "peer_review_publication",
    "publication factor": "peer_review_publication",
    "peer review and publication": "peer_review_publication",
    "peer review publication": "peer_review_publication",
    # Known or Potential Error Rate Daubert Factor
    "error rate": "error_rate",
    "known error rate": "error_rate",
    "potential error rate": "error_rate",
    "error rate factor": "error_rate",
    "daubert error rate": "error_rate",
    "rate of error": "error_rate",
    "error rates": "error_rate",
    # Standards and Controls Daubert Factor
    "standards": "standards_controls",
    "controls": "standards_controls",
    "standards and controls": "standards_controls",
    "control procedures": "standards_controls",
    "standard procedures": "standards_controls",
    "daubert standards": "standards_controls",
    "daubert controls": "standards_controls",
    "standards factor": "standards_controls",
    "controls factor": "standards_controls",
    # General Acceptance in Scientific Community
    "scientific acceptance": "general_acceptance_scientific",
    "general acceptance in scientific community": "general_acceptance_scientific",
    "acceptance in scientific community": "general_acceptance_scientific",
    "accepted in scientific community": "general_acceptance_scientific",
    "generally accepted": "general_acceptance_scientific",
    "general acceptance factor": "general_acceptance_scientific",
    "scientific community acceptance": "general_acceptance_scientific",
    # Relevance and Fit Requirement
    "relevance and fit": "relevance_and_fit",
    "fit and relevance": "relevance_and_fit",
    "relevance fit": "relevance_and_fit",
    "fit relevance": "relevance_and_fit",
    # Supplementation of Expert Disclosures
    "supplementation": "supplementation_expert_disclosure",
    "supplement expert disclosure": "supplementation_expert_disclosure",
    "supplementation of expert disclosures": "supplementation_expert_disclosure",
    "supplemental expert disclosure": "supplementation_expert_disclosure",
    "supplemental disclosure": "supplementation_expert_disclosure",
    "supplemental report": "supplementation_expert_disclosure",
    "supplement expert report": "supplementation_expert_disclosure",
    # Exclusion of Expert Testimony as Sanction
    "exclusion": "exclusion_expert_testimony",
    "exclusion of expert testimony": "exclusion_expert_testimony",
    "exclude expert testimony": "exclusion_expert_testimony",
    "exclude expert": "exclusion_expert_testimony",
    "sanction": "exclusion_expert_testimony",
    "sanction exclusion": "exclusion_expert_testimony",
    "exclusion as sanction": "exclusion_expert_testimony",
    "sanction for nondisclosure": "exclusion_expert_testimony",
    # Court-Appointed Experts Under FRE 706
    "court appointed expert": "court_appointed_expert",
    "court-appointed expert": "court_appointed_expert",
    "court appointed experts": "court_appointed_expert",
    "court-appointed experts": "court_appointed_expert",
    "fre 706": "fre_706",
    "rule 706": "fre_706",
    "706": "fre_706",
    "court expert": "court_appointed_expert",
    "court's expert": "court_appointed_expert",
    # Treating Physician as Expert Witness
    "treating physician": "treating_physician_expert",
    "treating doctor": "treating_physician_expert",
    "treating physician expert": "treating_physician_expert",
    "physician expert": "treating_physician_expert",
    "doctor expert": "treating_physician_expert",
    "treating physician as expert": "treating_physician_expert",
    "treating physician testimony": "treating_physician_expert",
    "treating physician witness": "treating_physician_expert",
    # Ipse Dixit Rejection and Explained Methodology
    "ipse dixit": "ipse_dixit_rejection",
    "ipse dixit rejection": "ipse_dixit_rejection",
    "ipse dixit doctrine": "ipse_dixit_rejection",
    "ipse dixit expert": "ipse_dixit_rejection",
    "ipse dixit opinion": "ipse_dixit_rejection",
    "ipse dixit testimony": "ipse_dixit_rejection",
    "ipse dixit methodology": "ipse_dixit_rejection",
    "explained methodology": "ipse_dixit_rejection",
    "explained method": "ipse_dixit_rejection",
    "explanation of methodology": "ipse_dixit_rejection",
    "methodology explained": "ipse_dixit_rejection",
    "unsupported opinion": "ipse_dixit_rejection",
    "unsupported expert opinion": "ipse_dixit_rejection",
    "bare conclusion": "ipse_dixit_rejection",
    "conclusory opinion": "ipse_dixit_rejection",
    # Misspellings, abbreviations, and related terms
    "dauburt": "daubert_standard",
    "daubart": "daubert_standard",
    "fry": "frye_test",
    "frye general": "frye_test",
    "kumho tire v carmichael": "kumho_tire",
    "kumho tire v. carmichael": "kumho_tire",
    "kumho v carmichael": "kumho_tire",
    "kumho v. carmichael": "kumho_tire",
    "frcp26": "frcp_26",
    "frcp26a2": "frcp_26a2",
    "frcp26(a)(2)": "frcp_26a2",
    "frcp26a2b": "frcp_26a2b",
    "frcp26(a)(2)(b)": "frcp_26a2b",
    "expert disc": "expert_disclosure",
    "expert disc.": "expert_disclosure",
    "exp. disclosure": "expert_disclosure",
    "exp disclosure": "expert_disclosure",
    "exp report": "expert_report",
    "exp. report": "expert_report",
    "exp reports": "expert_report",
    "exp. reports": "expert_report",
    "exp witness": "expert_witness",
    "exp. witness": "expert_witness",
    "exp testimony": "expert_testimony",
    "exp. testimony": "expert_testimony",
    "exp depo": "expert_deposition",
    "exp. depo": "expert_deposition",
    "exp deposition": "expert_deposition",
    "exp. deposition": "expert_deposition",
    "exp prep": "expert_deposition_preparation",
    "exp. prep": "expert_deposition_preparation",
    "exp prep.": "expert_deposition_preparation",
    "cross exam": "cross_examination",
    "cross-exam": "cross_examination",
    "cross-exam.": "cross_examination",
    "cross exam.": "cross_examination",
    "rebuttal exp": "rebuttal_expert",
    "rebuttal exp.": "rebuttal_expert",
    "supplement exp disc": "supplementation_expert_disclosure",
    "supplement exp disc.": "supplementation_expert_disclosure",
    "supplement exp disclosure": "supplementation_expert_disclosure",
    "supplement exp. disclosure": "supplementation_expert_disclosure",
    "court expert witness": "court_appointed_expert",
    "court's expert witness": "court_appointed_expert",
    "court appointed witness": "court_appointed_expert",
    "court-appointed witness": "court_appointed_expert",
    "treating doc": "treating_physician_expert",
    "treating doc.": "treating_physician_expert",
    "treating dr": "treating_physician_expert",
    "treating dr.": "treating_physician_expert",
    "testability and falsifiability": "testability",
    "peer review publication factor": "peer_review_publication",
    "peer-reviewed publication": "peer_review_publication",
    "peer-reviewed publications": "peer_review_publication",
    "peer reviewed publications": "peer_review_publication",
    "error rate daubert": "error_rate",
    "error rate factor daubert": "error_rate",
    "error rate known": "error_rate",
    "error rate potential": "error_rate",
    "standard and control": "standards_controls",
    "standard procedure": "standards_controls",
    "control procedure": "standards_controls",
    "generally accepted in scientific community": "general_acceptance_scientific",
    "accepted by scientific community": "general_acceptance_scientific",
    "generally accepted standard": "general_acceptance_scientific",
    "supplementation of expert report": "supplementation_expert_disclosure",
    "supplemental expert report": "supplementation_expert_disclosure",
    "supplemental report expert": "supplementation_expert_disclosure",
    "exclusion sanction": "exclusion_expert_testimony",
    "sanction exclusion expert": "exclusion_expert_testimony",
    "sanction exclusion testimony": "exclusion_expert_testimony",
    "court expert appointed": "court_appointed_expert",
    "court appointed expert witness": "court_appointed_expert",
    "court-appointed expert witness": "court_appointed_expert",
    "treating physician expert witness": "treating_physician_expert",
    "ipse dixit expert opinion": "ipse_dixit_rejection",
    "ipse dixit methodology rejection": "ipse_dixit_rejection",
    "ipse dixit conclusion": "ipse_dixit_rejection",
    "ipse dixit unsupported": "ipse_dixit_rejection",
    "ipse dixit bare conclusion": "ipse_dixit_rejection",
    "ipse dixit conclusory": "ipse_dixit_rejection",
    "ipse dixit opinion rejection": "ipse_dixit_rejection",
    "ipse dixit testimony rejection": "ipse_dixit_rejection",
    "ipse dixit unsupported opinion": "ipse_dixit_rejection",
    "ipse dixit unsupported testimony": "ipse_dixit_rejection",
}

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    concat += f"version:{SEMANTIC_MAP_VERSION};author:{SEMANTIC_MAP_AUTHOR};engine:{SEMANTIC_MAP_ENGINE};"
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    expected_count = _EXPECTED_ENTRY_COUNT
    current_hash = _compute_map_hash()
    is_valid = (actual_count == expected_count) and (current_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": current_hash,
        "is_valid": is_valid,
    }

def _normalize_string(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[\.\(\)\[\]\{\},:;]", "", s)
    s = re.sub(r"[-_]", " ", s)
    s = re.sub(r"\s+", " ", s)
    s = s.strip()
    return s

def normalize_term(term: str) -> str:
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term: str) -> List[str]:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> Dict[str, str]:
    return dict(SEMANTIC_MAP)