import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MED12_dermatology_team"
SEMANTIC_MAP_ENGINE = "MED12"

SEMANTIC_MAP = {
    # Melanoma ABCDE Criteria
    "melanoma": "melanoma",
    "melanoma skin cancer": "melanoma",
    "melanoma cancer": "melanoma",
    "malignant melanoma": "melanoma",
    "melanoma abcde": "melanoma_abcde_criteria",
    "abcde melanoma": "melanoma_abcde_criteria",
    "abcde criteria": "melanoma_abcde_criteria",
    "abcde rule": "melanoma_abcde_criteria",
    "abcde": "melanoma_abcde_criteria",
    "melanoma detection": "melanoma_abcde_criteria",
    "melanoma diagnosis": "melanoma_abcde_criteria",
    "melanoma screening": "melanoma_abcde_criteria",
    "melanoma signs": "melanoma_abcde_criteria",
    "melanoma symptoms": "melanoma_abcde_criteria",
    "melanoma features": "melanoma_abcde_criteria",
    "melanoma assessment": "melanoma_abcde_criteria",
    "melanoma evaluation": "melanoma_abcde_criteria",
    "melanoma criteria": "melanoma_abcde_criteria",
    "melanoma warning signs": "melanoma_abcde_criteria",
    "melanoma check": "melanoma_abcde_criteria",
    "melanoma risk factors": "melanoma_abcde_criteria",
    "melanoma risk": "melanoma_abcde_criteria",
    "melanoma shape": "melanoma_abcde_criteria",
    "melanoma border": "melanoma_abcde_criteria",
    "melanoma color": "melanoma_abcde_criteria",
    "melanoma diameter": "melanoma_abcde_criteria",
    "melanoma evolution": "melanoma_abcde_criteria",
    "melanoma irregular border": "melanoma_abcde_criteria",
    "melanoma uneven color": "melanoma_abcde_criteria",
    "melanoma changing mole": "melanoma_abcde_criteria",
    "melanoma mole": "melanoma_abcde_criteria",
    "melanoma lesion": "melanoma_abcde_criteria",
    "melanoma spot": "melanoma_abcde_criteria",
    "melanoma mark": "melanoma_abcde_criteria",
    "melanoma patch": "melanoma_abcde_criteria",
    "melanoma growth": "melanoma_abcde_criteria",
    "melanoma pigment": "melanoma_abcde_criteria",
    "melanoma dark spot": "melanoma_abcde_criteria",
    "melanoma brown spot": "melanoma_abcde_criteria",
    "melanoma black spot": "melanoma_abcde_criteria",
    "melanoma red spot": "melanoma_abcde_criteria",
    "melanoma pink spot": "melanoma_abcde_criteria",
    "melanoma blue spot": "melanoma_abcde_criteria",
    "melanoma white spot": "melanoma_abcde_criteria",
    "melanoma skin lesion": "melanoma_abcde_criteria",
    "melanoma skin mark": "melanoma_abcde_criteria",
    "melanoma skin patch": "melanoma_abcde_criteria",
    "melanoma skin growth": "melanoma_abcde_criteria",
    "melanoma skin pigment": "melanoma_abcde_criteria",
    "melanoma skin mole": "melanoma_abcde_criteria",
    "melanoma skin spot": "melanoma_abcde_criteria",
    "melanoma skin change": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melanoma skin abnormal patch": "melanoma_abcde_criteria",
    "melanoma skin abnormal growth": "melanoma_abcde_criteria",
    "melanoma skin abnormal pigment": "melanoma_abcde_criteria",
    "melanoma skin abnormality": "melanoma_abcde_criteria",
    "melanoma skin irregularity": "melanoma_abcde_criteria",
    "melanoma skin symptom": "melanoma_abcde_criteria",
    "melanoma skin sign": "melanoma_abcde_criteria",
    "melanoma skin feature": "melanoma_abcde_criteria",
    "melanoma skin assessment": "melanoma_abcde_criteria",
    "melanoma skin evaluation": "melanoma_abcde_criteria",
    "melanoma skin criteria": "melanoma_abcde_criteria",
    "melanoma skin warning sign": "melanoma_abcde_criteria",
    "melanoma skin check": "melanoma_abcde_criteria",
    "melanoma skin risk factor": "melanoma_abcde_criteria",
    "melanoma skin risk": "melanoma_abcde_criteria",
    "melanoma skin shape": "melanoma_abcde_criteria",
    "melanoma skin border": "melanoma_abcde_criteria",
    "melanoma skin color": "melanoma_abcde_criteria",
    "melanoma skin diameter": "melanoma_abcde_criteria",
    "melanoma skin evolution": "melanoma_abcde_criteria",
    "melanoma skin irregular border": "melanoma_abcde_criteria",
    "melanoma skin uneven color": "melanoma_abcde_criteria",
    "melanoma skin changing mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal mole": "melanoma_abcde_criteria",
    "melanoma skin abnormal lesion": "melanoma_abcde_criteria",
    "melanoma skin abnormal spot": "melanoma_abcde_criteria",
    "melanoma skin abnormal mark": "melanoma_abcde_criteria",
    "melan