import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PROD03_well_testing_team"
SEMANTIC_MAP_ENGINE = "PROD03"

SEMANTIC_MAP = {
    # horner_buildup_analysis
    "horner plot": "horner_buildup_analysis",
    "horner method": "horner_buildup_analysis",
    "horner analysis": "horner_buildup_analysis",
    "horner": "horner_buildup_analysis",
    "buildup analysis": "horner_buildup_analysis",
    "pressure buildup": "horner_buildup_analysis",
    "pressure buildup analysis": "horner_buildup_analysis",
    "buildup test": "horner_buildup_analysis",
    "buildup": "horner_buildup_analysis",
    "drawdown-buildup": "horner_buildup_analysis",
    "drawdown buildup": "horner_buildup_analysis",
    "pressure build-up": "horner_buildup_analysis",
    "build up": "horner_buildup_analysis",
    "build-up": "horner_buildup_analysis",
    "horner time": "horner_buildup_analysis",
    "horner equation": "horner_buildup_analysis",
    "horner slope": "horner_buildup_analysis",
    "horner straight line": "horner_buildup_analysis",
    "horner chart": "horner_buildup_analysis",
    "horner plot interpretation": "horner_buildup_analysis",
    "horner plot method": "horner_buildup_analysis",
    "buildup curve": "horner_buildup_analysis",
    "pressure buildup curve": "horner_buildup_analysis",
    "pbu": "horner_buildup_analysis",
    "pbu test": "horner_buildup_analysis",
    "pbu analysis": "horner_buildup_analysis",
    "pressure build up": "horner_buildup_analysis",
    "pressure build-up test": "horner_buildup_analysis",
    "pressure build-up analysis": "horner_buildup_analysis",
    "build up test": "horner_buildup_analysis",
    "build-up test": "horner_buildup_analysis",
    "build-up analysis": "horner_buildup_analysis",
    "buildup interpretation": "horner_buildup_analysis",
    # bourdet_derivative_analysis
    "bourdet derivative": "bourdet_derivative_analysis",
    "bourdet derivative method": "bourdet_derivative_analysis",
    "bourdet derivative analysis": "bourdet_derivative_analysis",
    "bourdet": "bourdet_derivative_analysis",
    "pressure derivative": "bourdet_derivative_analysis",
    "pressure derivative analysis": "bourdet_derivative_analysis",
    "pressure derivative method": "bourdet_derivative_analysis",
    "bourdet formula": "bourdet_derivative_analysis",
    "bourdet plot": "bourdet_derivative_analysis",
    "bourdet calculation": "bourdet_derivative_analysis",
    "bourdet equation": "bourdet_derivative_analysis",
    "bourdet approach": "bourdet_derivative_analysis",
    "bourdet technique": "bourdet_derivative_analysis",
    "bourdet derivative curve": "bourdet_derivative_analysis",
    "pressure derivative curve": "bourdet_derivative_analysis",
    "pressure derivative plot": "bourdet_derivative_analysis",
    "pressure derivative interpretation": "bourdet_derivative_analysis",
    "bourdet derivative interpretation": "bourdet_derivative_analysis",
    "bourdet derivative diagnostic": "bourdet_derivative_analysis",
    "bourdet derivative feature": "bourdet_derivative_analysis",
    "bourdet derivative features": "bourdet_derivative_analysis",
    "bourdet derivative signature": "bourdet_derivative_analysis",
    "bourdet derivative signature analysis": "bourdet_derivative_analysis",
    "bourdet derivative diagnostic features": "bourdet_derivative_analysis",
    "bourdet derivative diagnostic feature": "bourdet_derivative_analysis",
    # skin_factor_determination
    "skin factor": "skin_factor_determination",
    "skin": "skin_factor_determination",
    "skin determination": "skin_factor_determination",
    "skin analysis": "skin_factor_determination",
    "skin calculation": "skin_factor_determination",
    "skin estimation": "skin_factor_determination",
    "skin factor estimation": "skin_factor_determination",
    "skin factor calculation": "skin_factor_determination",
    "skin factor analysis": "skin_factor_determination",
    "skin factor determination": "skin_factor_determination",
    "skin value": "skin_factor_determination",
    "skin interpretation": "skin_factor_determination",
    "skin factor interpretation": "skin_factor_determination",
    "well skin": "skin_factor_determination",
    "well skin factor": "skin_factor_determination",
    "wellbore skin": "skin_factor_determination",
    "wellbore skin factor": "skin_factor_determination",
    "skin effect": "skin_factor_determination",
    "skin effects": "skin_factor_determination",
    "skin zone": "skin_factor_determination",
    "skin region": "skin_factor_determination",
    "skin parameter": "skin_factor_determination",
    "skin parameters": "skin_factor_determination",
    "skin test": "skin_factor_determination",
    "skin factor test": "skin_factor_determination",
    # dual_porosity_interpretation
    "dual porosity": "dual_porosity_interpretation",
    "dual porosity model": "dual_porosity_interpretation",
    "dual porosity interpretation": "dual_porosity_interpretation",
    "double porosity": "dual_porosity_interpretation",
    "double porosity model": "dual_porosity_interpretation",
    "double porosity interpretation": "dual_porosity_interpretation",
    "dual-porosity": "dual_porosity_interpretation",
    "dual-porosity model": "dual_porosity_interpretation",
    "dual-porosity interpretation": "dual_porosity_interpretation",
    "fracture matrix": "dual_porosity_interpretation",
    "fracture-matrix": "dual_porosity_interpretation",
    "fracture matrix model": "dual_porosity_interpretation",
    "fracture matrix interpretation": "dual_porosity_interpretation",
    "fractured reservoir": "dual_porosity_interpretation",
    "fractured reservoir model": "dual_porosity_interpretation",
    "fractured reservoir interpretation": "dual_porosity_interpretation",
    "dual porosity reservoir": "dual_porosity_interpretation",
    "dual porosity reservoir model": "dual_porosity_interpretation",
    "dual porosity reservoir interpretation": "dual_porosity_interpretation",
    "double porosity reservoir": "dual_porosity_interpretation",
    "double porosity reservoir model": "dual_porosity_interpretation",
    "double porosity reservoir interpretation": "dual_porosity_interpretation",
    "dual porosity system": "dual_porosity_interpretation",
    "dual porosity systems": "dual_porosity_interpretation",
    "double porosity system": "dual_porosity_interpretation",
    "double porosity systems": "dual_porosity_interpretation",
    "dual porosity behavior": "dual_porosity_interpretation",
    "double porosity behavior": "dual_porosity_interpretation",
    "dual porosity response": "dual_porosity_interpretation",
    "double porosity response": "dual_porosity_interpretation",
    "dual porosity effect": "dual_porosity_interpretation",
    "double porosity effect": "dual_porosity_interpretation",
    # boundary_effect_identification
    "boundary effect": "boundary_effect_identification",
    "boundary effects": "boundary_effect_identification",
    "boundary identification": "boundary_effect_identification",
    "boundary detection": "boundary_effect_identification",
    "boundary interpretation": "boundary_effect_identification",
    "boundary response": "boundary_effect_identification",
    "boundary signature": "boundary_effect_identification",
    "boundary feature": "boundary_effect_identification",
    "boundary features": "boundary_effect_identification",
    "boundary diagnostic": "boundary_effect_identification",
    "boundary diagnostic features": "boundary_effect_identification",
    "boundary diagnostic feature": "boundary_effect_identification",
    "boundary type": "boundary_effect_identification",
    "boundary types": "boundary_effect_identification",
    "boundary condition": "boundary_effect_identification",
    "boundary conditions": "boundary_effect_identification",
    "boundary behavior": "boundary_effect_identification",
    "boundary behaviors": "boundary_effect_identification",
    "boundary model": "boundary_effect_identification",
    "boundary models": "boundary_effect_identification",
    "boundary analysis": "boundary_effect_identification",
    "boundary test": "boundary_effect_identification",
    "boundary effect identification": "boundary_effect_identification",
    "boundary effect detection": "boundary_effect_identification",
    "boundary effect interpretation": "boundary_effect_identification",
    "boundary effect response": "boundary_effect_identification",
    "boundary effect signature": "boundary_effect_identification",
    "boundary effect feature": "boundary_effect_identification",
    "boundary effect features": "boundary_effect_identification",
    "boundary effect diagnostic": "boundary_effect_identification",
    "boundary effect diagnostic features": "boundary_effect_identification",
    "boundary effect diagnostic feature": "boundary_effect_identification",
    # horizontal_well_testing
    "horizontal well": "horizontal_well_testing",
    "horizontal well test": "horizontal_well_testing",
    "horizontal well testing": "horizontal_well_testing",
    "horizontal well analysis": "horizontal_well_testing",
    "horizontal well interpretation": "horizontal_well_testing",
    "horizontal well model": "horizontal_well_testing",
    "horizontal well models": "horizontal_well_testing",
    "horizontal well behavior": "horizontal_well_testing",
    "horizontal well response": "horizontal_well_testing",
    "horizontal well signature": "horizontal_well_testing",
    "horizontal well feature": "horizontal_well_testing",
    "horizontal well features": "horizontal_well_testing",
    "horizontal well diagnostic": "horizontal_well_testing",
    "horizontal well diagnostic features": "horizontal_well_testing",
    "horizontal well diagnostic feature": "horizontal_well_testing",
    "horizontal wellbore": "horizontal_well_testing",
    "horizontal wellbore test": "horizontal_well_testing",
    "horizontal wellbore testing": "horizontal_well_testing",
    "horizontal wellbore analysis": "horizontal_well_testing",
    "horizontal wellbore interpretation": "horizontal_well_testing",
    "horizontal wellbore model": "horizontal_well_testing",
    "horizontal wellbore models": "horizontal_well_testing",
    "horizontal wellbore behavior": "horizontal_well_testing",
    "horizontal wellbore response": "horizontal_well_testing",
    "horizontal wellbore signature": "horizontal_well_testing",
    "horizontal wellbore feature": "horizontal_well_testing",
    "horizontal wellbore features": "horizontal_well_testing",
    "horizontal wellbore diagnostic": "horizontal_well_testing",
    "horizontal wellbore diagnostic features": "horizontal_well_testing",
    "horizontal wellbore diagnostic feature": "horizontal_well_testing",
    "hz well": "horizontal_well_testing",
    "hz well test": "horizontal_well_testing",
    "hz well testing": "horizontal_well_testing",
    "hz well analysis": "horizontal_well_testing",
    "hz well interpretation": "horizontal_well_testing",
    "hz well model": "horizontal_well_testing",
    "hz well models": "horizontal_well_testing",
    "hz well behavior": "horizontal_well_testing",
    "hz well response": "horizontal_well_testing",
    "hz well signature": "horizontal_well_testing",
    "hz well feature": "horizontal_well_testing",
    "hz well features": "horizontal_well_testing",
    "hz well diagnostic": "horizontal_well_testing",
    "hz well diagnostic features": "horizontal_well_testing",
    "hz well diagnostic feature": "horizontal_well_testing",
    # rate_transient_analysis_unconventional
    "rate transient analysis": "rate_transient_analysis_unconventional",
    "rta": "rate_transient_analysis_unconventional",
    "rta analysis": "rate_transient_analysis_unconventional",
    "rta method": "rate_transient_analysis_unconventional",
    "rta interpretation": "rate_transient_analysis_unconventional",
    "rta test": "rate_transient_analysis_unconventional",
    "rta techniques": "rate_transient_analysis_unconventional",
    "rta diagnostic": "rate_transient_analysis_unconventional",
    "rta diagnostic features": "rate_transient_analysis_unconventional",
    "rta diagnostic feature": "rate_transient_analysis_unconventional",
    "rate transient": "rate_transient_analysis_unconventional",
    "rate transient analysis unconventional": "rate_transient_analysis_unconventional",
    "unconventional rta": "rate_transient_analysis_unconventional",
    "unconventional rate transient analysis": "rate_transient_analysis_unconventional",
    "unconventional rate transient": "rate_transient_analysis_unconventional",
    "unconventional rta analysis": "rate_transient_analysis_unconventional",
    "unconventional rta method": "rate_transient_analysis_unconventional",
    "unconventional rta interpretation": "rate_transient_analysis_unconventional",
    "unconventional rta test": "rate_transient_analysis_unconventional",
    "unconventional rta techniques": "rate_transient_analysis_unconventional",
    "unconventional rta diagnostic": "rate_transient_analysis_unconventional",
    "unconventional rta diagnostic features": "rate_transient_analysis_unconventional",
    "unconventional rta diagnostic feature": "rate_transient_analysis_unconventional",
    "rta unconventional": "rate_transient_analysis_unconventional",
    "rta unconventional analysis": "rate_transient_analysis_unconventional",
    "rta unconventional method": "rate_transient_analysis_unconventional",
    "rta unconventional interpretation": "rate_transient_analysis_unconventional",
    "rta unconventional test": "rate_transient_analysis_unconventional",
    "rta unconventional techniques": "rate_transient_analysis_unconventional",
    "rta unconventional diagnostic": "rate_transient_analysis_unconventional",
    "rta unconventional diagnostic features": "rate_transient_analysis_unconventional",
    "rta unconventional diagnostic feature": "rate_transient_analysis_unconventional",
    "rate transient diagnostic": "rate_transient_analysis_unconventional",
    "rate transient diagnostic features": "rate_transient_analysis_unconventional",
    "rate transient diagnostic feature": "rate_transient_analysis_unconventional",
    "rate transient analysis diagnostic": "rate_transient_analysis_unconventional",
    "rate transient analysis diagnostic features": "rate_transient_analysis_unconventional",
    "rate transient analysis diagnostic feature": "rate_transient_analysis_unconventional",
    # wellbore_storage_effects
    "wellbore storage": "wellbore_storage_effects",
    "wellbore storage effect": "wellbore_storage_effects",
    "wellbore storage effects": "wellbore_storage_effects",
    "wellbore storage analysis": "wellbore_storage_effects",
    "wellbore storage interpretation": "wellbore_storage_effects",
    "wellbore storage model": "wellbore_storage_effects",
    "wellbore storage models": "wellbore_storage_effects",
    "wellbore storage behavior": "wellbore_storage_effects",
    "wellbore storage response": "wellbore_storage_effects",
    "wellbore storage signature": "wellbore_storage_effects",
    "wellbore storage feature": "wellbore_storage_effects",
    "wellbore storage features": "wellbore_storage_effects",
    "wellbore storage diagnostic": "wellbore_storage_effects",
    "wellbore storage diagnostic features": "wellbore_storage_effects",
    "wellbore storage diagnostic feature": "wellbore_storage_effects",
    "wellbore storage zone": "wellbore_storage_effects",
    "wellbore storage region": "wellbore_storage_effects",
    "wellbore storage parameter": "wellbore_storage_effects",
    "wellbore storage parameters": "wellbore_storage_effects",
    "wellbore storage test": "wellbore_storage_effects",
    "wellbore storage effect test": "wellbore_storage_effects",
    "wellbore storage effect analysis": "wellbore_storage_effects",
    "wellbore storage effect interpretation": "wellbore_storage_effects",
    "wellbore storage effect model": "wellbore_storage_effects",
    "wellbore storage effect models": "wellbore_storage_effects",
    "wellbore storage effect behavior": "wellbore_storage_effects",
    "wellbore storage effect response": "wellbore_storage_effects",
    "wellbore storage effect signature": "wellbore_storage_effects",
    "wellbore storage effect feature": "wellbore_storage_effects",
    "wellbore storage effect features": "wellbore_storage_effects",
    "wellbore storage effect diagnostic": "wellbore_storage_effects",
    "wellbore storage effect diagnostic features": "wellbore_storage_effects",
    "wellbore storage effect diagnostic feature": "wellbore_storage_effects",
    "wbs": "wellbore_storage_effects",
    "wbs effect": "wellbore_storage_effects",
    "wbs effects": "wellbore_storage_effects",
    "wbs analysis": "wellbore_storage_effects",
    "wbs interpretation": "wellbore_storage_effects",
    "wbs model": "wellbore_storage_effects",
    "wbs models": "wellbore_storage_effects",
    "wbs behavior": "wellbore_storage_effects",
    "wbs response": "wellbore_storage_effects",
    "wbs signature": "wellbore_storage_effects",
    "wbs feature": "wellbore_storage_effects",
    "wbs features": "wellbore_storage_effects",
    "wbs diagnostic": "wellbore_storage_effects",
    "wbs diagnostic features": "wellbore_storage_effects",
    "wbs diagnostic feature": "wellbore_storage_effects",
    # formation_interval_testing
    "formation interval": "formation_interval_testing",
    "formation interval test": "formation_interval_testing",
    "formation interval testing": "formation_interval_testing",
    "formation interval analysis": "formation_interval_testing",
    "formation interval interpretation": "formation_interval_testing",
    "formation interval model": "formation_interval_testing",
    "formation interval models": "formation_interval_testing",
    "formation interval behavior": "formation_interval_testing",
    "formation interval response": "formation_interval_testing",
    "formation interval signature": "formation_interval_testing",
    "formation interval feature": "formation_interval_testing",
    "formation interval features": "formation_interval_testing",
    "formation interval diagnostic": "formation_interval_testing",
    "formation interval diagnostic features": "formation_interval_testing",
    "formation interval diagnostic feature": "formation_interval_testing",
    "formation interval zone": "formation_interval_testing",
    "formation interval region": "formation_interval_testing",
    "formation interval parameter": "formation_interval_testing",
    "formation interval parameters": "formation_interval_testing",
    "formation interval test analysis": "formation_interval_testing",
    "formation interval test interpretation": "formation_interval_testing",
    "formation interval test model": "formation_interval_testing",
    "formation interval test models": "formation_interval_testing",
    "formation interval test behavior": "formation_interval_testing",
    "formation interval test response": "formation_interval_testing",
    "formation interval test signature": "formation_interval_testing",
    "formation interval test feature": "formation_interval_testing",
    "formation interval test features": "formation_interval_testing",
    "formation interval test diagnostic": "formation_interval_testing",
    "formation interval test diagnostic features": "formation_interval_testing",
    "formation interval test diagnostic feature": "formation_interval_testing",
    # interference_pulse_testing
    "interference test": "interference_pulse_testing",
    "interference testing": "interference_pulse_testing",
    "interference analysis": "interference_pulse_testing",
    "interference interpretation": "interference_pulse_testing",
    "interference model": "interference_pulse_testing",
    "interference models": "interference_pulse_testing",
    "interference behavior": "interference_pulse_testing",
    "interference response": "interference_pulse_testing",
    "interference signature": "interference_pulse_testing",
    "interference feature": "interference_pulse_testing",
    "interference features": "interference_pulse_testing",
    "interference diagnostic": "interference_pulse_testing",
    "interference diagnostic features": "interference_pulse_testing",
    "interference diagnostic feature": "interference_pulse_testing",
    "pulse test": "interference_pulse_testing",
    "pulse testing": "interference_pulse_testing",
    "pulse analysis": "interference_pulse_testing",
    "pulse interpretation": "interference_pulse_testing",
    "pulse model": "interference_pulse_testing",
    "pulse models": "interference_pulse_testing",
    "pulse behavior": "interference_pulse_testing",
    "pulse response": "interference_pulse_testing",
    "pulse signature": "interference_pulse_testing",
    "pulse feature": "interference_pulse_testing",
    "pulse features": "interference_pulse_testing",
    "pulse diagnostic": "interference_pulse_testing",
    "pulse diagnostic features": "interference_pulse_testing",
    "pulse diagnostic feature": "interference_pulse_testing",
    "interference pulse test": "interference_pulse_testing",
    "interference pulse testing": "interference_pulse_testing",
    "interference pulse analysis": "interference_pulse_testing",
    "interference pulse interpretation": "interference_pulse_testing",
    "interference pulse model": "interference_pulse_testing",
    "interference pulse models": "interference_pulse_testing",
    "interference pulse behavior": "interference_pulse_testing",
    "interference pulse response": "interference_pulse_testing",
    "interference pulse signature": "interference_pulse_testing",
    "interference pulse feature": "interference_pulse_testing",
    "interference pulse features": "interference_pulse_testing",
    "interference pulse diagnostic": "interference_pulse_testing",
    "interference pulse diagnostic features": "interference_pulse_testing",
    "interference pulse diagnostic feature": "interference_pulse_testing",
    # drill_stem_test_interpretation
    "drill stem test": "drill_stem_test_interpretation",
    "drill stem testing": "drill_stem_test_interpretation",
    "drill stem test analysis": "drill_stem_test_interpretation",
    "drill stem test interpretation": "drill_stem_test_interpretation",
    "drill stem test model": "drill_stem_test_interpretation",
    "drill stem test models": "drill_stem_test_interpretation",
    "drill stem test behavior": "drill_stem_test_interpretation",
    "drill stem test response": "drill_stem_test_interpretation",
    "drill stem test signature": "drill_stem_test_interpretation",
    "drill stem test feature": "drill_stem_test_interpretation",
    "drill stem test features": "drill_stem_test_interpretation",
    "drill stem test diagnostic": "drill_stem_test_interpretation",
    "drill stem test diagnostic features": "drill_stem_test_interpretation",
    "drill stem test diagnostic feature": "drill_stem_test_interpretation",
    "dst": "drill_stem_test_interpretation",
    "dst test": "drill_stem_test_interpretation",
    "dst testing": "drill_stem_test_interpretation",
    "dst analysis": "drill_stem_test_interpretation",
    "dst interpretation": "drill_stem_test_interpretation",
    "dst model": "drill_stem_test_interpretation",
    "dst models": "drill_stem_test_interpretation",
    "dst behavior": "drill_stem_test_interpretation",
    "dst response": "drill_stem_test_interpretation",
    "dst signature": "drill_stem_test_interpretation",
    "dst feature": "drill_stem_test_interpretation",
    "dst features": "drill_stem_test_interpretation",
    "dst diagnostic": "drill_stem_test_interpretation",
    "dst diagnostic features": "drill_stem_test_interpretation",
    "dst diagnostic feature": "drill_stem_test_interpretation",
    # type_curve_matching_methodology
    "type curve": "type_curve_matching_methodology",
    "type curve matching": "type_curve_matching_methodology",
    "type curve analysis": "type_curve_matching_methodology",
    "type curve interpretation": "type_curve_matching_methodology",
    "type curve model": "type_curve_matching_methodology",
    "type curve models": "type_curve_matching_methodology",
    "type curve behavior": "type_curve_matching_methodology",
    "type curve response": "type_curve_matching_methodology",
    "type curve signature": "type_curve_matching_methodology",
    "type curve feature": "type_curve_matching_methodology",
    "type curve features": "type_curve_matching_methodology",
    "type curve diagnostic": "type_curve_matching_methodology",
    "type curve diagnostic features": "type_curve_matching_methodology",
    "type curve diagnostic feature": "type_curve_matching_methodology",
    "type curve matching methodology": "type_curve_matching_methodology",
    "type curve matching method": "type_curve_matching_methodology",
    "type curve matching techniques": "type_curve_matching_methodology",
    "type curve matching technique": "type_curve_matching_methodology",
    "type curve matching analysis": "type_curve_matching_methodology",
    "type curve matching interpretation": "type_curve_matching_methodology",
    "type curve matching model": "type_curve_matching_methodology",
    "type curve matching models": "type_curve_matching_methodology",
    "type curve matching behavior": "type_curve_matching_methodology",
    "type curve matching response": "type_curve_matching_methodology",
    "type curve matching signature": "type_curve_matching_methodology",
    "type curve matching feature": "type_curve_matching_methodology",
    "type curve matching features": "type_curve_matching_methodology",
    "type curve matching diagnostic": "type_curve_matching_methodology",
    "type curve matching diagnostic features": "type_curve_matching_methodology",
    "type curve matching diagnostic feature": "type_curve_matching_methodology",
    # superposition_principles
    "superposition principle": "superposition_principles",
    "superposition principles": "superposition_principles",
    "superposition": "superposition_principles",
    "superposition method": "superposition_principles",
    "superposition analysis": "superposition_principles",
    "superposition interpretation": "superposition_principles",
    "superposition model": "superposition_principles",
    "superposition models": "superposition_principles",
    "superposition behavior": "superposition_principles",
    "superposition response": "superposition_principles",
    "superposition signature": "superposition_principles",
    "superposition feature": "superposition_principles",
    "superposition features": "superposition_principles",
    "superposition diagnostic": "superposition_principles",
    "superposition diagnostic features": "superposition_principles",
    "superposition diagnostic feature": "superposition_principles",
    "superposition theorem": "superposition_principles",
    "superposition theorems": "superposition_principles",
    "superposition principle method": "superposition_principles",
    "superposition principle analysis": "superposition_principles",
    "superposition principle interpretation": "superposition_principles",
    "superposition principle model": "superposition_principles",
    "superposition principle models": "superposition_principles",
    "superposition principle behavior": "superposition_principles",
    "superposition principle response": "superposition_principles",
    "superposition principle signature": "superposition_principles",
    "superposition principle feature": "superposition_principles",
    "superposition principle features": "superposition_principles",
    "superposition principle diagnostic": "superposition_principles",
    "superposition principle diagnostic features": "superposition_principles",
    "superposition principle diagnostic feature": "superposition_principles",
    # multi_rate_testing
    "multi rate test": "multi_rate_testing",
    "multi rate testing": "multi_rate_testing",
    "multi rate analysis": "multi_rate_testing",
    "multi rate interpretation": "multi_rate_testing",
    "multi rate model": "multi_rate_testing",
    "multi rate models": "multi_rate_testing",
    "multi rate behavior": "multi_rate_testing",
    "multi rate response": "multi_rate_testing",
    "multi rate signature": "multi_rate_testing",
    "multi rate feature": "multi_rate_testing",
    "multi rate features": "multi_rate_testing",
    "multi rate diagnostic": "multi_rate_testing",
    "multi rate diagnostic features": "multi_rate_testing",
    "multi rate diagnostic feature": "multi_rate_testing",
    "multirate test": "multi_rate_testing",
    "multirate testing": "multi_rate_testing",
    "multirate analysis": "multi_rate_testing",
    "multirate interpretation": "multi_rate_testing",
    "multirate model": "multi_rate_testing",
    "multirate models": "multi_rate_testing",
    "multirate behavior": "multi_rate_testing",
    "multirate response": "multi_rate_testing",
    "multirate signature": "multi_rate_testing",
    "multirate feature": "multi_rate_testing",
    "multirate features": "multi_rate_testing",
    "multirate diagnostic": "multi_rate_testing",
    "multirate diagnostic features": "multi_rate_testing",
    "multirate diagnostic feature": "multi_rate_testing",
    "multi-rate test": "multi_rate_testing",
    "multi-rate testing": "multi_rate_testing",
    "multi-rate analysis": "multi_rate_testing",
    "multi-rate interpretation": "multi_rate_testing",
    "multi-rate model": "multi_rate_testing",
    "multi-rate models": "multi_rate_testing",
    "multi-rate behavior": "multi_rate_testing",
    "multi-rate response": "multi_rate_testing",
    "multi-rate signature": "multi_rate_testing",
    "multi-rate feature": "multi_rate_testing",
    "multi-rate features": "multi_rate_testing",
    "multi-rate diagnostic": "multi_rate_testing",
    "multi-rate diagnostic features": "multi_rate_testing",
    "multi-rate diagnostic feature": "multi_rate_testing",
    # permeability_estimation_methods
    "permeability estimation": "permeability_estimation_methods",
    "permeability estimation method": "permeability_estimation_methods",
    "permeability estimation methods": "permeability_estimation_methods",
    "permeability estimation analysis": "permeability_estimation_methods",
    "permeability estimation interpretation": "permeability_estimation_methods",
    "permeability estimation model": "permeability_estimation_methods",
    "permeability estimation models": "permeability_estimation_methods",
    "permeability estimation behavior": "permeability_estimation_methods",
    "permeability estimation response": "permeability_estimation_methods",
    "permeability estimation signature": "permeability_estimation_methods",
    "permeability estimation feature": "permeability_estimation_methods",
    "permeability estimation features": "permeability_estimation_methods",
    "permeability estimation diagnostic": "permeability_estimation_methods",
    "permeability estimation diagnostic features": "permeability_estimation_methods",
    "permeability estimation diagnostic feature": "permeability_estimation_methods",
    "permeability estimation techniques": "permeability_estimation_methods",
    "permeability estimation technique": "permeability_estimation_methods",
    "permeability estimation test": "permeability_estimation_methods",
    "permeability estimation tests": "permeability_estimation_methods",
    "permeability estimation zone": "permeability_estimation_methods",
    "permeability estimation region": "permeability_estimation_methods",
    "permeability estimation parameter": "permeability_estimation_methods",
    "permeability estimation parameters": "permeability_estimation_methods",
    "permeability estimation value": "permeability_estimation_methods",
    "permeability estimation values": "permeability_estimation_methods",
    "permeability estimation approach": "permeability_estimation_methods",
    "permeability estimation approaches": "permeability_estimation_methods",
    "permeability estimation methodology": "permeability_estimation_methods",
    "permeability estimation methodologies": "permeability_estimation_methods",
    "permeability estimation feature": "permeability_estimation_methods",
    "permeability estimation features": "permeability_estimation_methods",
    # pressure_derivative_diagnostic_features
    "pressure derivative diagnostic": "pressure_derivative_diagnostic_features",
    "pressure derivative diagnostic features": "pressure_derivative_diagnostic_features",
    "pressure derivative diagnostic feature": "pressure_derivative_diagnostic_features",
    "pressure derivative feature": "pressure_derivative_diagnostic_features",
    "pressure derivative features": "pressure_derivative_diagnostic_features",
    "pressure derivative signature": "pressure_derivative_diagnostic_features",
    "pressure derivative signatures": "pressure_derivative_diagnostic_features",
    "pressure derivative response": "pressure_derivative_diagnostic_features",
    "pressure derivative responses": "pressure_derivative_diagnostic_features",
    "pressure derivative behavior": "pressure_derivative_diagnostic_features",
    "pressure derivative behaviors": "pressure_derivative_diagnostic_features",
    "pressure derivative analysis": "pressure_derivative_diagnostic_features",
    "pressure derivative interpretation": "pressure_derivative_diagnostic_features",
    "pressure derivative model": "pressure_derivative_diagnostic_features",
    "pressure derivative models": "pressure_derivative_diagnostic_features",
    "pressure derivative test": "pressure_derivative_diagnostic_features",
    "pressure derivative tests": "pressure_derivative_diagnostic_features",
    "pressure derivative zone": "pressure_derivative_diagnostic_features",
    "pressure derivative region": "pressure_derivative_diagnostic_features",
    "pressure derivative parameter": "pressure_derivative_diagnostic_features",
    "pressure derivative parameters": "pressure_derivative_diagnostic_features",
    "pressure derivative value": "pressure_derivative_diagnostic_features",
    "pressure derivative values": "pressure_derivative_diagnostic_features",
    "pressure derivative approach": "pressure_derivative_diagnostic_features",
    "pressure derivative approaches": "pressure_derivative_diagnostic_features",
    "pressure derivative methodology": "pressure_derivative_diagnostic_features",
    "pressure derivative methodologies": "pressure_derivative_diagnostic_features",
    # test_design_and_duration
    "test design": "test_design_and_duration",
    "test duration": "test_design_and_duration",
    "test planning": "test_design_and_duration",
    "test plan": "test_design_and_duration",
    "test schedule": "test_design_and_duration",
    "test scheduling": "test_design_and_duration",
    "test time": "test_design_and_duration",
    "test timing": "test_design_and_duration",
    "test length": "test_design_and_duration",
    "test period": "test_design_and_duration",
    "test window": "test_design_and_duration",
    "test interval": "test_design_and_duration",
    "test sequence": "test_design_and_duration",
    "test sequence planning": "test_design_and_duration",
    "test sequence design": "test_design_and_duration",
    "test sequence duration": "test_design_and_duration",
    "test sequence schedule": "test_design_and_duration",
    "test sequence scheduling": "test_design_and_duration",
    "test sequence time": "test_design_and_duration",
    "test sequence timing": "test_design_and_duration",
    "test sequence length": "test_design_and_duration",
    "test sequence period": "test_design_and_duration",
    "test sequence window": "test_design_and_duration",
    "test sequence interval": "test_design_and_duration",
    "test sequence plan": "test_design_and_duration",
    "test sequence planning": "test_design_and_duration",
    "test sequence methodology": "test_design_and_duration",
    "test sequence methodologies": "test_design_and_duration",
    "test sequence approach": "test_design_and_duration",
    "test sequence approaches": "test_design_and_duration",
    "test sequence strategy": "test_design_and_duration",
    "test sequence strategies": "test_design_and_duration",
    "test sequence feature": "test_design_and_duration",
    "test sequence features": "test_design_and_duration",
    "test sequence diagnostic": "test_design_and_duration",
    "test sequence diagnostic features": "test_design_and_duration",
    "test sequence diagnostic feature": "test_design_and_duration",
    "test sequence analysis": "test_design_and_duration",
    "test sequence interpretation": "test_design_and_duration",
    "test sequence model": "test_design_and_duration",
    "test sequence models": "test_design_and_duration",
    "test sequence behavior": "test_design_and_duration",
    "test sequence response": "test_design_and_duration",
    "test sequence signature": "test_design_and_duration",
    "test sequence zone": "test_design_and_duration",
    "test sequence region": "test_design_and_duration",
    "test sequence parameter": "test_design_and_duration",
    "test sequence parameters": "test_design_and_duration",
    "test sequence value": "test_design_and_duration",
    "test sequence values": "test_design_and_duration",
    "test sequence methodology": "test_design_and_duration",
    "test sequence methodologies": "test_design_and_duration",
    "test sequence approach": "test_design_and_duration",
    "test sequence approaches": "test_design_and_duration",
    "test sequence strategy": "test_design_and_duration",
    "test sequence strategies": "test_design_and_duration",
    "test sequence feature": "test_design_and_duration",
    "test sequence features": "test_design_and_duration",
    "test sequence diagnostic": "test_design_and_duration",
    "test sequence diagnostic features": "test_design_and_duration",
    "test sequence diagnostic feature": "test_design_and_duration",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}:{SEMANTIC_MAP_AUTHOR}:{SEMANTIC_MAP_ENGINE}:{_EXPECTED_ENTRY_COUNT}"
    payload = meta + joined
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"[\-_/]", " ", t)
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    # Try direct match
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try normalized match
    t2 = re.sub(r"\s+", " ", t)
    if t2 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t2]
    # Try removing plural
    if t.endswith("s") and t[:-1] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-1]]
    # Try removing 'test', 'analysis', 'interpretation', etc.
    for suffix in [
        " test", " tests", " testing", " analysis", " analyses", " interpretation", " interpretations",
        " model", " models", " behavior", " behaviors", " response", " responses", " signature", " signatures",
        " feature", " features", " diagnostic", " diagnostics", " zone", " region", " parameter", " parameters",
        " value", " values", " approach", " approaches", " methodology", " methodologies", " technique", " techniques",
        " plan", " planning", " schedule", " scheduling", " time", " timing", " length", " period", " window", " interval",
        " sequence", " strategies", " strategy"
    ]:
        if t.endswith(suffix):
            base = t[:-len(suffix)].strip()
            if base in SEMANTIC_MAP:
                return SEMANTIC_MAP[base]
    return ""

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    if not normalized:
        return []
    return [k for k, v in SEMANTIC_MAP.items() if v == normalized]

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)