import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "RAIL05 Team"
SEMANTIC_MAP_ENGINE = "RAIL05_passenger_operations"

SEMANTIC_MAP = {
    # Cyclic Timetabling and PESP Model
    "cyclic timetable": "cyclic_timetabling",
    "cyclic timetabling": "cyclic_timetabling",
    "periodic timetable": "cyclic_timetabling",
    "periodic timetabling": "cyclic_timetabling",
    "pesp": "periodic_event_scheduling_problem",
    "periodic event scheduling problem": "periodic_event_scheduling_problem",
    "event-activity network": "event_activity_network",
    "ean": "event_activity_network",
    "timetable periodicity": "cyclic_timetabling",
    "timetable cycle": "cyclic_timetabling",
    "timetable period": "cyclic_timetabling",
    "headway regularity": "cyclic_timetabling",
    "timetable regularity": "cyclic_timetabling",
    "timetable optimization": "timetable_optimization",
    "schedule optimization": "timetable_optimization",
    "train schedule optimization": "timetable_optimization",
    "train pathing": "timetable_optimization",
    "train path": "timetable_optimization",
    "train slot": "timetable_optimization",
    "train slotting": "timetable_optimization",
    "conflict-free timetable": "timetable_optimization",
    "conflict-free scheduling": "timetable_optimization",
    "robust timetable": "robust_timetabling",
    "robust timetabling": "robust_timetabling",
    "robust scheduling": "robust_timetabling",
    "buffer time": "buffer_time",
    "slack time": "buffer_time",
    "schedule slack": "buffer_time",
    "event graph": "event_activity_network",
    "activity graph": "event_activity_network",
    "event node": "event_activity_network",
    "activity arc": "event_activity_network",
    "minimum cycle time": "cycle_time_minimization",
    "cycle time minimization": "cycle_time_minimization",

    # Rolling Stock Assignment and Fleet Optimization
    "rolling stock": "rolling_stock",
    "rolling stock assignment": "rolling_stock_assignment",
    "fleet assignment": "rolling_stock_assignment",
    "fleet optimization": "fleet_optimization",
    "trainset assignment": "rolling_stock_assignment",
    "trainset scheduling": "rolling_stock_assignment",
    "vehicle rotation": "vehicle_rotation",
    "train rotation": "vehicle_rotation",
    "vehicle scheduling": "vehicle_rotation",
    "stock rotation": "vehicle_rotation",
    "stock scheduling": "vehicle_rotation",
    "fleet utilization": "fleet_optimization",
    "fleet sizing": "fleet_optimization",
    "fleet size": "fleet_optimization",
    "spare ratio": "spare_ratio",
    "spare fleet": "spare_ratio",
    "maintenance window": "maintenance_window",
    "maintenance scheduling": "maintenance_window",
    "out-of-service": "maintenance_window",
    "train availability": "fleet_availability",
    "fleet availability": "fleet_availability",
    "vehicle availability": "fleet_availability",
    "train circulation": "vehicle_rotation",
    "train consist": "train_consist",
    "consist planning": "train_consist",
    "consist": "train_consist",
    "train formation": "train_consist",
    "formation planning": "train_consist",
    "deadheading": "deadheading",
    "empty stock movement": "deadheading",
    "empty run": "deadheading",
    "empty train movement": "deadheading",
    "stock balancing": "fleet_balancing",
    "fleet balancing": "fleet_balancing",
    "stock redistribution": "fleet_balancing",

    # Crew Scheduling and Labor Compliance
    "crew scheduling": "crew_scheduling",
    "crew assignment": "crew_scheduling",
    "crew rostering": "crew_rostering",
    "crew roster": "crew_rostering",
    "crew rotation": "crew_rostering",
    "crew pairing": "crew_pairing",
    "duty pairing": "crew_pairing",
    "duty scheduling": "crew_pairing",
    "crew duty": "crew_pairing",
    "driver scheduling": "crew_scheduling",
    "driver assignment": "crew_scheduling",
    "conductor scheduling": "crew_scheduling",
    "labor compliance": "labor_compliance",
    "labor law compliance": "labor_compliance",
    "rest time": "rest_time",
    "minimum rest": "rest_time",
    "maximum duty": "duty_time_limit",
    "duty time limit": "duty_time_limit",
    "work hour limit": "duty_time_limit",
    "fatigue management": "fatigue_management",
    "union agreement": "union_agreement",
    "collective agreement": "union_agreement",
    "crew base": "crew_base",
    "crew depot": "crew_base",
    "crew home base": "crew_base",
    "crew sign-on": "crew_sign_on",
    "crew sign-off": "crew_sign_off",
    "sign-on time": "crew_sign_on",
    "sign-off time": "crew_sign_off",
    "crew change": "crew_change",
    "crew swap": "crew_change",
    "relief point": "crew_change",
    "crew relief": "crew_change",

    # Station Dwell Time Analysis and Passenger Flow
    "dwell time": "dwell_time",
    "station dwell time": "dwell_time",
    "train dwell time": "dwell_time",
    "platform dwell time": "dwell_time",
    "dwell time analysis": "dwell_time_analysis",
    "boarding time": "boarding_time",
    "alighting time": "alighting_time",
    "boarding and alighting": "boarding_alighting",
    "passenger flow": "passenger_flow",
    "station passenger flow": "passenger_flow",
    "platform crowding": "platform_crowding",
    "platform congestion": "platform_crowding",
    "station congestion": "station_crowding",
    "station crowding": "station_crowding",
    "turnback time": "turnback_time",
    "turnaround time": "turnback_time",
    "train turnaround": "turnback_time",
    "minimum dwell": "dwell_time",
    "minimum dwell time": "dwell_time",
    "dwell time distribution": "dwell_time_analysis",
    "dwell time variance": "dwell_time_analysis",
    "dwell time variability": "dwell_time_analysis",
    "passenger circulation": "passenger_flow",
    "passenger movement": "passenger_flow",
    "egress flow": "egress_flow",
    "ingress flow": "ingress_flow",
    "station throughput": "station_throughput",
    "platform throughput": "station_throughput",
    "platform utilization": "platform_utilization",
    "platform usage": "platform_utilization",
    "platform allocation": "platform_allocation",
    "platform assignment": "platform_allocation",

    # Fare Structure Design and Revenue Optimization
    "fare structure": "fare_structure",
    "fare design": "fare_structure",
    "fare policy": "fare_structure",
    "fare optimization": "fare_optimization",
    "revenue optimization": "revenue_optimization",
    "farebox recovery": "farebox_recovery",
    "farebox ratio": "farebox_recovery",
    "farebox recovery ratio": "farebox_recovery",
    "fare elasticity": "fare_elasticity",
    "price elasticity": "fare_elasticity",
    "fare class": "fare_class",
    "ticket class": "fare_class",
    "ticketing": "ticketing",
    "ticket sales": "ticketing",
    "ticket revenue": "ticket_revenue",
    "revenue management": "revenue_optimization",
    "yield management": "revenue_optimization",
    "dynamic pricing": "dynamic_pricing",
    "variable pricing": "dynamic_pricing",
    "peak pricing": "peak_pricing",
    "off-peak pricing": "off_peak_pricing",
    "discount fare": "discount_fare",
    "concession fare": "discount_fare",
    "reduced fare": "discount_fare",
    "fare evasion": "fare_evasion",
    "fare enforcement": "fare_evasion",
    "fare inspection": "fare_evasion",
    "fare gate": "fare_gate",
    "ticket barrier": "fare_gate",
    "smartcard": "smartcard",
    "contactless ticketing": "smartcard",
    "electronic ticket": "smartcard",
    "e-ticket": "smartcard",
    "mobile ticket": "mobile_ticket",
    "app ticket": "mobile_ticket",
    "qr ticket": "mobile_ticket",
    "qr code ticket": "mobile_ticket",

    # On-Time Performance (OTP) Metrics and Reliability
    "on-time performance": "on_time_performance",
    "otp": "on_time_performance",
    "punctuality": "on_time_performance",
    "reliability": "service_reliability",
    "service reliability": "service_reliability",
    "delay": "delay",
    "train delay": "delay",
    "late train": "delay",
    "arrival delay": "delay",
    "departure delay": "delay",
    "delay minutes": "delay",
    "delay minutes per train": "delay",
    "delay cause": "delay_cause",
    "delay reason": "delay_cause",
    "root cause analysis": "delay_cause",
    "primary delay": "primary_delay",
    "secondary delay": "secondary_delay",
    "knock-on delay": "secondary_delay",
    "reactionary delay": "secondary_delay",
    "delay propagation": "secondary_delay",
    "delay management": "delay_management",
    "delay mitigation": "delay_management",
    "service recovery": "delay_management",
    "service disruption": "service_disruption",
    "disruption management": "service_disruption",
    "incident management": "service_disruption",
    "service interruption": "service_disruption",
    "cancellation": "cancellation",
    "train cancellation": "cancellation",
    "service cancellation": "cancellation",
    "short turn": "short_turn",
    "turnback": "turnback_time",
    "turnback operation": "turnback_time",
    "mean distance between failures": "mdbf",
    "mdbf": "mdbf",
    "service interval": "service_interval",
    "headway": "service_interval",
    "interval time": "service_interval",

    # Platform Screen Doors (PSD) Safety and Operations
    "platform screen door": "platform_screen_door",
    "platform screen doors": "platform_screen_door",
    "psd": "platform_screen_door",
    "platform edge door": "platform_screen_door",
    "ped": "platform_screen_door",
    "platform door": "platform_screen_door",
    "platform safety door": "platform_screen_door",
    "platform barrier": "platform_screen_door",
    "platform barrier door": "platform_screen_door",
    "platform gate": "platform_screen_door",
    "platform safety": "platform_safety",
    "platform safety system": "platform_safety",
    "platform accident": "platform_accident",
    "platform incident": "platform_accident",
    "platform intrusion": "platform_intrusion",
    "intrusion detection": "platform_intrusion",
    "track intrusion": "platform_intrusion",
    "platform gap": "platform_gap",
    "gap filler": "platform_gap",
    "gap mitigation": "platform_gap",
    "gap hazard": "platform_gap",
    "platform accessibility": "platform_accessibility",

    # ADA Accessibility Compliance and Universal Design
    "ada compliance": "ada_compliance",
    "ada accessible": "ada_compliance",
    "ada": "ada_compliance",
    "accessibility": "ada_compliance",
    "universal design": "universal_design",
    "inclusive design": "universal_design",
    "barrier-free": "universal_design",
    "barrier free": "universal_design",
    "accessible station": "ada_compliance",
    "accessible platform": "ada_compliance",
    "wheelchair access": "ada_compliance",
    "step-free access": "ada_compliance",
    "step free access": "ada_compliance",
    "tactile paving": "tactile_paving",
    "tactile guidance": "tactile_paving",
    "braille signage": "braille_signage",
    "audio announcement": "audio_announcement",
    "audio information": "audio_announcement",
    "visual information": "visual_information",
    "visual signage": "visual_information",
    "hearing loop": "hearing_loop",
    "induction loop": "hearing_loop",
    "assistive technology": "assistive_technology",
    "accessible restroom": "ada_compliance",
    "accessible toilet": "ada_compliance",

    # Positive Train Control (PTC) for Passenger Rail
    "positive train control": "ptc",
    "ptc": "ptc",
    "cbtc": "cbtc",
    "communications-based train control": "cbtc",
    "automatic train protection": "atp",
    "atp": "atp",
    "automatic train operation": "ato",
    "ato": "ato",
    "train control system": "train_control_system",
    "train protection system": "atp",
    "train signaling": "train_signaling",
    "signal system": "train_signaling",
    "train signal": "train_signaling",
    "cab signaling": "cab_signaling",
    "wayside signaling": "wayside_signaling",
    "interlocking": "interlocking",
    "signal interlocking": "interlocking",
    "train detection": "train_detection",
    "track circuit": "train_detection",
    "axle counter": "train_detection",
    "train integrity": "train_integrity",
    "train separation": "train_separation",
    "block system": "train_separation",
    "moving block": "moving_block",
    "fixed block": "fixed_block",

    # Passenger Demand Forecasting and Ridership Modeling
    "passenger demand": "passenger_demand",
    "demand forecasting": "demand_forecasting",
    "ridership forecasting": "demand_forecasting",
    "ridership model": "ridership_modeling",
    "ridership modeling": "ridership_modeling",
    "demand model": "ridership_modeling",
    "demand estimation": "demand_forecasting",
    "passenger forecast": "demand_forecasting",
    "passenger estimation": "demand_forecasting",
    "passenger count": "passenger_count",
    "automatic passenger counting": "passenger_count",
    "apc": "passenger_count",
    "boarding count": "boarding_count",
    "alighting count": "alighting_count",
    "origin-destination matrix": "od_matrix",
    "od matrix": "od_matrix",
    "o-d matrix": "od_matrix",
    "origin destination matrix": "od_matrix",
    "trip matrix": "od_matrix",
    "trip distribution": "od_matrix",
    "trip assignment": "trip_assignment",
    "trip generation": "trip_generation",
    "trip attraction": "trip_attraction",
    "modal split": "modal_split",
    "mode choice": "modal_split",
    "mode share": "modal_split",
    "market segmentation": "market_segmentation",
    "market segment": "market_segmentation",
    "passenger segmentation": "market_segmentation",

    # Load Factor and Crowding Management
    "load factor": "load_factor",
    "train load factor": "load_factor",
    "vehicle load factor": "load_factor",
    "seat occupancy": "load_factor",
    "seat utilization": "load_factor",
    "occupancy rate": "load_factor",
    "crowding": "crowding_management",
    "crowding management": "crowding_management",
    "overcrowding": "crowding_management",
    "passenger density": "crowding_management",
    "standee load": "crowding_management",
    "standee capacity": "crowding_management",
    "crush load": "crowding_management",
    "passenger comfort": "passenger_comfort",
    "comfort index": "passenger_comfort",
    "comfort level": "passenger_comfort",
    "passenger satisfaction": "passenger_comfort",
    "passenger experience": "passenger_comfort",

    # FRA Passenger Equipment Safety Standards
    "fra": "fra_safety_standards",
    "federal railroad administration": "fra_safety_standards",
    "fra safety": "fra_safety_standards",
    "fra compliance": "fra_safety_standards",
    "fra passenger equipment": "fra_safety_standards",
    "fra crashworthiness": "fra_safety_standards",
    "crashworthiness": "fra_safety_standards",
    "buff strength": "fra_safety_standards",
    "tier i": "fra_safety_standards",
    "tier ii": "fra_safety_standards",
    "tier iii": "fra_safety_standards",
    "49 cfr part 238": "fra_safety_standards",
    "49 cfr 238": "fra_safety_standards",
    "cfr 238": "fra_safety_standards",
    "49cfr238": "fra_safety_standards",
    "passenger equipment safety": "fra_safety_standards",
    "passenger equipment regulation": "fra_safety_standards",
    "passenger equipment standards": "fra_safety_standards",

    # Station Parking and Park-and-Ride Facilities
    "station parking": "station_parking",
    "park and ride": "park_and_ride",
    "park-and-ride": "park_and_ride",
    "park & ride": "park_and_ride",
    "park n ride": "park_and_ride",
    "p+r": "park_and_ride",
    "parking facility": "station_parking",
    "parking lot": "station_parking",
    "parking garage": "station_parking",
    "parking structure": "station_parking",
    "parking utilization": "parking_utilization",
    "parking occupancy": "parking_utilization",
    "parking demand": "parking_demand",
    "parking supply": "parking_supply",
    "parking management": "parking_management",
    "parking fee": "parking_fee",
    "parking pricing": "parking_fee",
    "parking revenue": "parking_revenue",

    # Passenger Information Systems (PIS) and Real-Time Data
    "passenger information system": "pis",
    "pis": "pis",
    "real-time information": "real_time_information",
    "real time information": "real_time_information",
    "real-time data": "real_time_information",
    "real time data": "real_time_information",
    "real-time display": "real_time_information",
    "real time display": "real_time_information",
    "dynamic information": "real_time_information",
    "dynamic display": "real_time_information",
    "next train display": "real_time_information",
    "arrival information": "real_time_information",
    "departure information": "real_time_information",
    "train information": "real_time_information",
    "platform display": "real_time_information",
    "station display": "real_time_information",
    "public address": "public_address",
    "pa system": "public_address",
    "audio announcement": "audio_announcement",
    "visual announcement": "visual_information",
    "information screen": "real_time_information",
    "information board": "real_time_information",
    "mobile app": "mobile_app",
    "mobile application": "mobile_app",
    "journey planner": "journey_planner",
    "trip planner": "journey_planner",
    "route planner": "journey_planner",

    # Cross-Border and Inter-City Passenger Rail Operations
    "cross-border": "cross_border",
    "cross border": "cross_border",
    "international train": "cross_border",
    "international rail": "cross_border",
    "border crossing": "cross_border",
    "customs clearance": "customs_clearance",
    "immigration clearance": "customs_clearance",
    "passport control": "customs_clearance",
    "intercity": "intercity",
    "inter-city": "intercity",
    "inter city": "intercity",
    "intercity train": "intercity",
    "intercity rail": "intercity",
    "long-distance train": "intercity",
    "long distance train": "intercity",
    "regional train": "regional_train",
    "commuter train": "commuter_train",
    "suburban train": "commuter_train",
    "express train": "express_train",
    "limited express": "express_train",

    # Energy Consumption and Regenerative Braking
    "energy consumption": "energy_consumption",
    "energy use": "energy_consumption",
    "energy efficiency": "energy_efficiency",
    "energy saving": "energy_efficiency",
    "energy management": "energy_management",
    "regenerative braking": "regenerative_braking",
    "regen braking": "regenerative_braking",
    "brake energy recovery": "regenerative_braking",
    "braking energy recovery": "regenerative_braking",
    "energy metering": "energy_metering",
    "energy monitoring": "energy_metering",
    "energy billing": "energy_metering",
    "eco-driving": "eco_driving",
    "eco driving": "eco_driving",
    "efficient driving": "eco_driving",
    "driver advisory system": "eco_driving",
    "das": "eco_driving",

    # Station Design and Passenger Flow Optimization
    "station design": "station_design",
    "station layout": "station_design",
    "station planning": "station_design",
    "station architecture": "station_design",
    "station circulation": "station_circulation",
    "station flow": "station_circulation",
    "station wayfinding": "station_wayfinding",
    "wayfinding": "station_wayfinding",
    "signage": "station_wayfinding",
    "station signage": "station_wayfinding",
    "station capacity": "station_capacity",
    "station throughput": "station_throughput",
    "station bottleneck": "station_bottleneck",
    "station pinch point": "station_bottleneck",
    "station entrance": "station_entrance",
    "station exit": "station_exit",
    "station access": "station_access",
    "station egress": "station_exit",
    "station ingress": "station_entrance",

    # Service Reliability and Mean Distance Between Failures (MDBF)
    "service reliability": "service_reliability",
    "reliability": "service_reliability",
    "mean distance between failures": "mdbf",
    "mdbf": "mdbf",
    "failure rate": "failure_rate",
    "service failure": "service_failure",
    "train failure": "service_failure",
    "rolling stock failure": "service_failure",
    "equipment failure": "service_failure",
    "breakdown": "service_failure",
    "service interruption": "service_disruption",

    # Transit-Oriented Development (TOD) and Land Use Integration
    "transit-oriented development": "tod",
    "transit oriented development": "tod",
    "tod": "tod",
    "land use integration": "land_use_integration",
    "land-use integration": "land_use_integration",
    "land use planning": "land_use_integration",
    "transit land use": "land_use_integration",
    "station area development": "tod",
    "station precinct": "tod",
    "station catchment": "station_catchment",
    "station influence area": "station_catchment",
    "station area": "station_catchment",
    "first mile": "first_mile",
    "last mile": "last_mile",
    "first/last mile": "first_mile_last_mile",
    "first and last mile": "first_mile_last_mile",
    "active transportation": "active_transportation",
    "walkability": "active_transportation",
    "bikeability": "active_transportation",
    "bicycle access": "active_transportation",
    "bicycle parking": "bicycle_parking",
    "bike parking": "bicycle_parking",
    "micromobility": "micromobility",
    "shared mobility": "micromobility",
    "shared bike": "micromobility",
    "shared scooter": "micromobility",
    "ride sharing": "micromobility",
    "rideshare": "micromobility",
    "car sharing": "micromobility",
    "carshare": "micromobility",
    "mobility hub": "mobility_hub",
    "mobility as a service": "maas",
    "maas": "maas",
    "integrated mobility": "maas",
    "multimodal integration": "multimodal_integration",
    "intermodal integration": "multimodal_integration",
    "multimodal transfer": "multimodal_integration",
    "interchange": "multimodal_integration",
    "transfer station": "multimodal_integration",
    "modal interchange": "multimodal_integration",
    "transit hub": "mobility_hub",
    "transport hub": "mobility_hub",
    "station hub": "mobility_hub",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    concat = concat.encode("utf-8")
    return hashlib.sha256(concat).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    current_hash = _compute_map_hash()
    is_valid = (current_hash == _MAP_INTEGRITY_HASH) and (len(SEMANTIC_MAP) == _EXPECTED_ENTRY_COUNT)
    return {
        "status": "ok" if is_valid else "error",
        "entries": len(SEMANTIC_MAP),
        "hash": current_hash,
        "is_valid": is_valid
    }

def _normalize_string(s):
    s = s.strip().lower()
    s = unicodedata.normalize("NFKC", s)
    s = " ".join(s.split())
    return s

def normalize_term(term: str) -> str:
    key = _normalize_string(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)