import hashlib

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "BLD02_engineering_team"
SEMANTIC_MAP_ENGINE = "BLD02_threat_assessment"

SEMANTIC_MAP = {
    # Physical Security Threat
    "physical security threat": "physical_security_threat",
    "phys sec threat": "physical_security_threat",
    "physical sec threat": "physical_security_threat",
    "phys security": "physical_security_threat",
    "physical security": "physical_security_threat",
    "phys sec": "physical_security_threat",
    "phys. security": "physical_security_threat",
    "physcial security": "physical_security_threat",
    "phy sec threat": "physical_security_threat",
    "physical threat": "physical_security_threat",
    "physicalthreat": "physical_security_threat",
    "phys security threat": "physical_security_threat",
    "phys. sec. threat": "physical_security_threat",
    "physical security risk": "physical_security_threat",
    "phys security risk": "physical_security_threat",
    "physical security incident": "physical_security_threat",
    "phys security incident": "physical_security_threat",
    "ps threat": "physical_security_threat",
    "ps risk": "physical_security_threat",
    "ps incident": "physical_security_threat",
    "physical security breach": "physical_security_threat",
    "phys security breach": "physical_security_threat",
    "phys sec breach": "physical_security_threat",
    "phys sec incident": "physical_security_threat",
    "phys sec risk": "physical_security_threat",
    "phys sec alert": "physical_security_threat",
    "physical security alert": "physical_security_threat",
    "phys sec threat alert": "physical_security_threat",
    "physical security threat alert": "physical_security_threat",
    "physical security violation": "physical_security_threat",
    "phys security violation": "physical_security_threat",
    "physical security compromise": "physical_security_threat",
    "phys security compromise": "physical_security_threat",
    "physical security concern": "physical_security_threat",
    "phys security concern": "physical_security_threat",
    "physical security vulnerability": "physical_security_threat",
    "phys security vulnerability": "physical_security_threat",
    "physical security weakness": "physical_security_threat",
    "phys security weakness": "physical_security_threat",
    "physical security flaw": "physical_security_threat",
    "phys security flaw": "physical_security_threat",
    "physical security exposure": "physical_security_threat",
    "phys security exposure": "physical_security_threat",
    "physical security hazard": "physical_security_threat",
    "phys security hazard": "physical_security_threat",
    "physical security issue": "physical_security_threat",
    "phys security issue": "physical_security_threat",
    "physical security problem": "physical_security_threat",
    "phys security problem": "physical_security_threat",
    "physical security threat vector": "physical_security_threat",
    "phys security threat vector": "physical_security_threat",
    "physical security threat actor": "physical_security_threat",
    "phys security threat actor": "physical_security_threat",
    "physical security threat source": "physical_security_threat",
    "phys security threat source": "physical_security_threat",
    "physical security threat agent": "physical_security_threat",
    "phys security threat agent": "physical_security_threat",
    "physical security threat landscape": "physical_security_threat",
    "phys security threat landscape": "physical_security_threat",
    "physical security threat intel": "physical_security_threat",
    "phys security threat intel": "physical_security_threat",
    "physical security threat intelligence": "physical_security_threat",
    "phys security threat intelligence": "physical_security_threat",
    "physical security threat assessment": "physical_security_threat",
    "phys security threat assessment": "physical_security_threat",
    "physical security threat analysis": "physical_security_threat",
    "phys security threat analysis": "physical_security_threat",
    "physical security threat detection": "physical_security_threat",
    "phys security threat detection": "physical_security_threat",
    "physical security threat monitoring": "physical_security_threat",
    "phys security threat monitoring": "physical_security_threat",
    "physical security threat prevention": "physical_security_threat",
    "phys security threat prevention": "physical_security_threat",
    "physical security threat mitigation": "physical_security_threat",
    "phys security threat mitigation": "physical_security_threat",
    "physical security threat response": "physical_security_threat",
    "phys security threat response": "physical_security_threat",
    "physical security threat management": "physical_security_threat",
    "phys security threat management": "physical_security_threat",
    "physical security threat control": "physical_security_threat",
    "phys security threat control": "physical_security_threat",
    "physical security threat risk": "physical_security_threat",
    "phys security threat risk": "physical_security_threat",
    "physical security threat vulnerability": "physical_security_threat",
    "phys security threat vulnerability": "physical_security_threat",
    "physical security threat weakness": "physical_security_threat",
    "phys security threat weakness": "physical_security_threat",
    "physical security threat flaw": "physical_security_threat",
    "phys security threat flaw": "physical_security_threat",
    "physical security threat exposure": "physical_security_threat",
    "phys security threat exposure": "physical_security_threat",
    "physical security threat hazard": "physical_security_threat",
    "phys security threat hazard": "physical_security_threat",
    "physical security threat issue": "physical_security_threat",
    "phys security threat issue": "physical_security_threat",
    "physical security threat problem": "physical_security_threat",
    "phys security threat problem": "physical_security_threat",

    # Cybersecurity Threat Framework
    "cybersecurity threat framework": "cybersecurity_threat_framework",
    "cyber security threat framework": "cybersecurity_threat_framework",
    "cybersec threat framework": "cybersecurity_threat_framework",
    "cyber sec threat framework": "cybersecurity_threat_framework",
    "cybersecurity threat": "cybersecurity_threat_framework",
    "cyber security threat": "cybersecurity_threat_framework",
    "cybersec threat": "cybersecurity_threat_framework",
    "cyber sec threat": "cybersecurity_threat_framework",
    "cybersecurity threat model": "cybersecurity_threat_framework",
    "cyber security threat model": "cybersecurity_threat_framework",
    "cybersec threat model": "cybersecurity_threat_framework",
    "cyber sec threat model": "cybersecurity_threat_framework",
    "cybersecurity threat intelligence": "cybersecurity_threat_framework",
    "cyber security threat intelligence": "cybersecurity_threat_framework",
    "cybersec threat intel": "cybersecurity_threat_framework",
    "cyber sec threat intel": "cybersecurity_threat_framework",
    "cybersecurity threat intel": "cybersecurity_threat_framework",
    "cybersecurity threat assessment": "cybersecurity_threat_framework",
    "cyber security threat assessment": "cybersecurity_threat_framework",
    "cybersec threat assessment": "cybersecurity_threat_framework",
    "cyber sec threat assessment": "cybersecurity_threat_framework",
    "cybersecurity threat analysis": "cybersecurity_threat_framework",
    "cyber security threat analysis": "cybersecurity_threat_framework",
    "cybersec threat analysis": "cybersecurity_threat_framework",
    "cyber sec threat analysis": "cybersecurity_threat_framework",
    "cybersecurity threat detection": "cybersecurity_threat_framework",
    "cyber security threat detection": "cybersecurity_threat_framework",
    "cybersec threat detection": "cybersecurity_threat_framework",
    "cyber sec threat detection": "cybersecurity_threat_framework",
    "cybersecurity threat monitoring": "cybersecurity_threat_framework",
    "cyber security threat monitoring": "cybersecurity_threat_framework",
    "cybersec threat monitoring": "cybersecurity_threat_framework",
    "cyber sec threat monitoring": "cybersecurity_threat_framework",
    "cybersecurity threat prevention": "cybersecurity_threat_framework",
    "cyber security threat prevention": "cybersecurity_threat_framework",
    "cybersec threat prevention": "cybersecurity_threat_framework",
    "cyber sec threat prevention": "cybersecurity_threat_framework",
    "cybersecurity threat mitigation": "cybersecurity_threat_framework",
    "cyber security threat mitigation": "cybersecurity_threat_framework",
    "cybersec threat mitigation": "cybersecurity_threat_framework",
    "cyber sec threat mitigation": "cybersecurity_threat_framework",
    "cybersecurity threat response": "cybersecurity_threat_framework",
    "cyber security threat response": "cybersecurity_threat_framework",
    "cybersec threat response": "cybersecurity_threat_framework",
    "cyber sec threat response": "cybersecurity_threat_framework",
    "cybersecurity threat management": "cybersecurity_threat_framework",
    "cyber security threat management": "cybersecurity_threat_framework",
    "cybersec threat management": "cybersecurity_threat_framework",
    "cyber sec threat management": "cybersecurity_threat_framework",
    "cybersecurity threat control": "cybersecurity_threat_framework",
    "cyber security threat control": "cybersecurity_threat_framework",
    "cybersec threat control": "cybersecurity_threat_framework",
    "cyber sec threat control": "cybersecurity_threat_framework",
    "cybersecurity threat risk": "cybersecurity_threat_framework",
    "cyber security threat risk": "cybersecurity_threat_framework",
    "cybersec threat risk": "cybersecurity_threat_framework",
    "cyber sec threat risk": "cybersecurity_threat_framework",
    "cybersecurity threat vulnerability": "cybersecurity_threat_framework",
    "cyber security threat vulnerability": "cybersecurity_threat_framework",
    "cybersec threat vulnerability": "cybersecurity_threat_framework",
    "cyber sec threat vulnerability": "cybersecurity_threat_framework",
    "cybersecurity threat weakness": "cybersecurity_threat_framework",
    "cyber security threat weakness": "cybersecurity_threat_framework",
    "cybersec threat weakness": "cybersecurity_threat_framework",
    "cyber sec threat weakness": "cybersecurity_threat_framework",
    "cybersecurity threat flaw": "cybersecurity_threat_framework",
    "cyber security threat flaw": "cybersecurity_threat_framework",
    "cybersec threat flaw": "cybersecurity_threat_framework",
    "cyber sec threat flaw": "cybersecurity_threat_framework",
    "cybersecurity threat exposure": "cybersecurity_threat_framework",
    "cyber security threat exposure": "cybersecurity_threat_framework",
    "cybersec threat exposure": "cybersecurity_threat_framework",
    "cyber sec threat exposure": "cybersecurity_threat_framework",
    "cybersecurity threat hazard": "cybersecurity_threat_framework",
    "cyber security threat hazard": "cybersecurity_threat_framework",
    "cybersec threat hazard": "cybersecurity_threat_framework",
    "cyber sec threat hazard": "cybersecurity_threat_framework",
    "cybersecurity threat issue": "cybersecurity_threat_framework",
    "cyber security threat issue": "cybersecurity_threat_framework",
    "cybersec threat issue": "cybersecurity_threat_framework",
    "cyber sec threat issue": "cybersecurity_threat_framework",
    "cybersecurity threat problem": "cybersecurity_threat_framework",
    "cyber security threat problem": "cybersecurity_threat_framework",
    "cybersec threat problem": "cybersecurity_threat_framework",
    "cyber sec threat problem": "cybersecurity_threat_framework",
    "cybersecurity threat vector": "cybersecurity_threat_framework",
    "cyber security threat vector": "cybersecurity_threat_framework",
    "cybersec threat vector": "cybersecurity_threat_framework",
    "cyber sec threat vector": "cybersecurity_threat_framework",
    "cybersecurity threat actor": "cybersecurity_threat_framework",
    "cyber security threat actor": "cybersecurity_threat_framework",
    "cybersec threat actor": "cybersecurity_threat_framework",
    "cyber sec threat actor": "cybersecurity_threat_framework",
    "cybersecurity threat source": "cybersecurity_threat_framework",
    "cyber security threat source": "cybersecurity_threat_framework",
    "cybersec threat source": "cybersecurity_threat_framework",
    "cyber sec threat source": "cybersecurity_threat_framework",
    "cybersecurity threat agent": "cybersecurity_threat_framework",
    "cyber security threat agent": "cybersecurity_threat_framework",
    "cybersec threat agent": "cybersecurity_threat_framework",
    "cyber sec threat agent": "cybersecurity_threat_framework",
    "cybersecurity threat landscape": "cybersecurity_threat_framework",
    "cyber security threat landscape": "cybersecurity_threat_framework",
    "cybersec threat landscape": "cybersecurity_threat_framework",
    "cyber sec threat landscape": "cybersecurity_threat_framework",
    "cybersecurity threat intel": "cybersecurity_threat_framework",
    "cyber security threat intel": "cybersecurity_threat_framework",
    "cybersec threat intel": "cybersecurity_threat_framework",
    "cyber sec threat intel": "cybersecurity_threat_framework",
    "cybersecurity threat intelligence": "cybersecurity_threat_framework",
    "cyber security threat intelligence": "cybersecurity_threat_framework",
    "cybersec threat intelligence": "cybersecurity_threat_framework",
    "cyber sec threat intelligence": "cybersecurity_threat_framework",
    "csf": "cybersecurity_threat_framework",
    "nist csf": "cybersecurity_threat_framework",
    "nist cybersecurity framework": "cybersecurity_threat_framework",
    "nist cyber security framework": "cybersecurity_threat_framework",
    "nist cybersec framework": "cybersecurity_threat_framework",
    "nist cyber sec framework": "cybersecurity_threat_framework",
    "nist cybersecurity threat framework": "cybersecurity_threat_framework",
    "nist cyber security threat framework": "cybersecurity_threat_framework",
    "nist cybersec threat framework": "cybersecurity_threat_framework",
    "nist cyber sec threat framework": "cybersecurity_threat_framework",
    "nist csf threat": "cybersecurity_threat_framework",
    "nist csf threat framework": "cybersecurity_threat_framework",

    # Financial Threat Detection
    "financial threat detection": "financial_threat_detection",
    "fin threat detection": "financial_threat_detection",
    "financial threat detect": "financial_threat_detection",
    "fin threat detect": "financial_threat_detection",
    "financial fraud detection": "financial_threat_detection",
    "fin fraud detection": "financial_threat_detection",
    "financial fraud detect": "financial_threat_detection",
    "fin fraud detect": "financial_threat_detection",
    "financial crime detection": "financial_threat_detection",
    "fin crime detection": "financial_threat_detection",
    "financial crime detect": "financial_threat_detection",
    "fin crime detect": "financial_threat_detection",
    "financial risk detection": "financial_threat_detection",
    "fin risk detection": "financial_threat_detection",
    "financial risk detect": "financial_threat_detection",
    "fin risk detect": "financial_threat_detection",
    "financial threat monitoring": "financial_threat_detection",
    "fin threat monitoring": "financial_threat_detection",
    "financial threat monitor": "financial_threat_detection",
    "fin threat monitor": "financial_threat_detection",
    "financial threat analysis": "financial_threat_detection",
    "fin threat analysis": "financial_threat_detection",
    "financial threat assess": "financial_threat_detection",
    "fin threat assess": "financial_threat_detection",
    "financial threat assessment": "financial_threat_detection",
    "fin threat assessment": "financial_threat_detection",
    "financial threat intelligence": "financial_threat_detection",
    "fin threat intelligence": "financial_threat_detection",
    "financial threat intel": "financial_threat_detection",
    "fin threat intel": "financial_threat_detection",
    "financial threat response": "financial_threat_detection",
    "fin threat response": "financial_threat_detection",
    "financial threat mitigation": "financial_threat_detection",
    "fin threat mitigation": "financial_threat_detection",
    "financial threat prevention": "financial_threat_detection",
    "fin threat prevention": "financial_threat_detection",
    "financial threat control": "financial_threat_detection",
    "fin threat control": "financial_threat_detection",
    "financial threat risk": "financial_threat_detection",
    "fin threat risk": "financial_threat_detection",
    "financial threat vulnerability": "financial_threat_detection",
    "fin threat vulnerability": "financial_threat_detection",
    "financial threat weakness": "financial_threat_detection",
    "fin threat weakness": "financial_threat_detection",
    "financial threat flaw": "financial_threat_detection",
    "fin threat flaw": "financial_threat_detection",
    "financial threat exposure": "financial_threat_detection",
    "fin threat exposure": "financial_threat_detection",
    "financial threat hazard": "financial_threat_detection",
    "fin threat hazard": "financial_threat_detection",
    "financial threat issue": "financial_threat_detection",
    "fin threat issue": "financial_threat_detection",
    "financial threat problem": "financial_threat_detection",
    "fin threat problem": "financial_threat_detection",
    "financial threat vector": "financial_threat_detection",
    "fin threat vector": "financial_threat_detection",
    "financial threat actor": "financial_threat_detection",
    "fin threat actor": "financial_threat_detection",
    "financial threat source": "financial_threat_detection",
    "fin threat source": "financial_threat_detection",
    "financial threat agent": "financial_threat_detection",
    "fin threat agent": "financial_threat_detection",
    "financial threat landscape": "financial_threat_detection",
    "fin threat landscape": "financial_threat_detection",
    "financial threat intel": "financial_threat_detection",
    "fin threat intel": "financial_threat_detection",
    "financial threat intelligence": "financial_threat_detection",
    "fin threat intelligence": "financial_threat_detection",
    "financial fraud": "financial_threat_detection",
    "fin fraud": "financial_threat_detection",
    "financial crime": "financial_threat_detection",
    "fin crime": "financial_threat_detection",
    "financial risk": "financial_threat_detection",
    "fin risk": "financial_threat_detection",
    "fraud detection": "financial_threat_detection",
    "fraud detect": "financial_threat_detection",
    "fraud monitor": "financial_threat_detection",
    "fraud monitoring": "financial_threat_detection",
    "fraud assessment": "financial_threat_detection",
    "fraud analysis": "financial_threat_detection",
    "fraud intelligence": "financial_threat_detection",
    "fraud intel": "financial_threat_detection",
    "fraud risk": "financial_threat_detection",
    "fraud vulnerability": "financial_threat_detection",
    "fraud weakness": "financial_threat_detection",
    "fraud flaw": "financial_threat_detection",
    "fraud exposure": "financial_threat_detection",
    "fraud hazard": "financial_threat_detection",
    "fraud issue": "financial_threat_detection",
    "fraud problem": "financial_threat_detection",
    "financial fraud risk": "financial_threat_detection",
    "fin fraud risk": "financial_threat_detection",
    "financial fraud vulnerability": "financial_threat_detection",
    "fin fraud vulnerability": "financial_threat_detection",
    "financial fraud weakness": "financial_threat_detection",
    "fin fraud weakness": "financial_threat_detection",
    "financial fraud flaw": "financial_threat_detection",
    "fin fraud flaw": "financial_threat_detection",
    "financial fraud exposure": "financial_threat_detection",
    "fin fraud exposure": "financial_threat_detection",
    "financial fraud hazard": "financial_threat_detection",
    "fin fraud hazard": "financial_threat_detection",
    "financial fraud issue": "financial_threat_detection",
    "fin fraud issue": "financial_threat_detection",
    "financial fraud problem": "financial_threat_detection",
    "fin fraud problem": "financial_threat_detection",
    "financial crime risk": "financial_threat_detection",
    "fin crime risk": "financial_threat_detection",
    "financial crime vulnerability": "financial_threat_detection",
    "fin crime vulnerability": "financial_threat_detection",
    "financial crime weakness": "financial_threat_detection",
    "fin crime weakness": "financial_threat_detection",
    "financial crime flaw": "financial_threat_detection",
    "fin crime flaw": "financial_threat_detection",
    "financial crime exposure": "financial_threat_detection",
    "fin crime exposure": "financial_threat_detection",
    "financial crime hazard": "financial_threat_detection",
    "fin crime hazard": "financial_threat_detection",
    "financial crime issue": "financial_threat_detection",
    "fin crime issue": "financial_threat_detection",
    "financial crime problem": "financial_threat_detection",
    "fin crime problem": "financial_threat_detection",

    # Legal Threat Assessment
    "legal threat assessment": "legal_threat_assessment",
    "legal threat assess": "legal_threat_assessment",
    "legal threat evaluation": "legal_threat_assessment",
    "legal threat analysis": "legal_threat_assessment",
    "legal threat review": "legal_threat_assessment",
    "legal risk assessment": "legal_threat_assessment",
    "legal risk assess": "legal_threat_assessment",
    "legal risk evaluation": "legal_threat_assessment",
    "legal risk analysis": "legal_threat_assessment",
    "legal risk review": "legal_threat_assessment",
    "legal threat detection": "legal_threat_assessment",
    "legal threat monitor": "legal_threat_assessment",
    "legal threat monitoring": "legal_threat_assessment",
    "legal threat intelligence": "legal_threat_assessment",
    "legal threat intel": "legal_threat_assessment",
    "legal threat mitigation": "legal_threat_assessment",
    "legal threat prevention": "legal_threat_assessment",
    "legal threat response": "legal_threat_assessment",
    "legal threat management": "legal_threat_assessment",
    "legal threat control": "legal_threat_assessment",
    "legal threat risk": "legal_threat_assessment",
    "legal threat vulnerability": "legal_threat_assessment",
    "legal threat weakness": "legal_threat_assessment",
    "legal threat flaw": "legal_threat_assessment",
    "legal threat exposure": "legal_threat_assessment",
    "legal threat hazard": "legal_threat_assessment",
    "legal threat issue": "legal_threat_assessment",
    "legal threat problem": "legal_threat_assessment",
    "legal threat vector": "legal_threat_assessment",
    "legal threat actor": "legal_threat_assessment",
    "legal threat source": "legal_threat_assessment",
    "legal threat agent": "legal_threat_assessment",
    "legal threat landscape": "legal_threat_assessment",
    "legal compliance threat": "legal_threat_assessment",
    "legal compliance risk": "legal_threat_assessment",
    "legal compliance issue": "legal_threat_assessment",
    "legal compliance problem": "legal_threat_assessment",
    "legal compliance violation": "legal_threat_assessment",
    "legal compliance breach": "legal_threat_assessment",
    "legal compliance incident": "legal_threat_assessment",
    "legal compliance concern": "legal_threat_assessment",
    "legal compliance vulnerability": "legal_threat_assessment",
    "legal compliance weakness": "legal_threat_assessment",
    "legal compliance flaw": "legal_threat_assessment",
    "legal compliance exposure": "legal_threat_assessment",
    "legal compliance hazard": "legal_threat_assessment",
    "legal compliance threat assessment": "legal_threat_assessment",
    "legal compliance threat analysis": "legal_threat_assessment",
    "legal compliance threat detection": "legal_threat_assessment",
    "legal compliance threat monitoring": "legal_threat_assessment",
    "legal compliance threat mitigation": "legal_threat_assessment",
    "legal compliance threat prevention": "legal_threat_assessment",
    "legal compliance threat response": "legal_threat_assessment",
    "legal compliance threat management": "legal_threat_assessment",
    "legal compliance threat control": "legal_threat_assessment",
    "legal compliance threat risk": "legal_threat_assessment",
    "legal compliance threat vulnerability": "legal_threat_assessment",
    "legal compliance threat weakness": "legal_threat_assessment",
    "legal compliance threat flaw": "legal_threat_assessment",
    "legal compliance threat exposure": "legal_threat_assessment",
    "legal compliance threat hazard": "legal_threat_assessment",
    "legal compliance threat issue": "legal_threat_assessment",
    "legal compliance threat problem": "legal_threat_assessment",

    # Reputation Threat Monitoring
    "reputation threat monitoring": "reputation_threat_monitoring",
    "reputation threat monitor": "reputation_threat_monitoring",
    "reputation risk monitoring": "reputation_threat_monitoring",
    "reputation risk monitor": "reputation_threat_monitoring",
    "reputation threat detection": "reputation_threat_monitoring",
    "reputation threat detect": "reputation_threat_monitoring",
    "reputation risk detection": "reputation_threat_monitoring",
    "reputation risk detect": "reputation_threat_monitoring",
    "reputation threat analysis": "reputation_threat_monitoring",
    "reputation threat assess": "reputation_threat_monitoring",
    "reputation threat assessment": "reputation_threat_monitoring",
    "reputation risk assessment": "reputation_threat_monitoring",
    "reputation risk assess": "reputation_threat_monitoring",
    "reputation risk analysis": "reputation_threat_monitoring",
    "reputation risk evaluation": "reputation_threat_monitoring",
    "reputation threat intelligence": "reputation_threat_monitoring",
    "reputation threat intel": "reputation_threat_monitoring",
    "reputation risk intelligence": "reputation_threat_monitoring",
    "reputation risk intel": "reputation_threat_monitoring",
    "reputation threat mitigation": "reputation_threat_monitoring",
    "reputation threat prevention": "reputation_threat_monitoring",
    "reputation threat response": "reputation_threat_monitoring",
    "reputation threat management": "reputation_threat_monitoring",
    "reputation threat control": "reputation_threat_monitoring",
    "reputation threat risk": "reputation_threat_monitoring",
    "reputation threat vulnerability": "reputation_threat_monitoring",
    "reputation threat weakness": "reputation_threat_monitoring",
    "reputation threat flaw": "reputation_threat_monitoring",
    "reputation threat exposure": "reputation_threat_monitoring",
    "reputation threat hazard": "reputation_threat_monitoring",
    "reputation threat issue": "reputation_threat_monitoring",
    "reputation threat problem": "reputation_threat_monitoring",
    "reputation risk": "reputation_threat_monitoring",
    "reputation risk issue": "reputation_threat_monitoring",
    "reputation risk problem": "reputation_threat_monitoring",
    "reputation risk concern": "reputation_threat_monitoring",
    "reputation risk vulnerability": "reputation_threat_monitoring",
    "reputation risk weakness": "reputation_threat_monitoring",
    "reputation risk flaw": "reputation_threat_monitoring",
    "reputation risk exposure": "reputation_threat_monitoring",
    "reputation risk hazard": "reputation_threat_monitoring",
    "reputation risk threat": "reputation_threat_monitoring",
    "reputation risk threat monitoring": "reputation_threat_monitoring",
    "reputation risk threat detection": "reputation_threat_monitoring",
    "reputation risk threat analysis": "reputation_threat_monitoring",
    "reputation risk threat assessment": "reputation_threat_monitoring",
    "reputation risk threat intelligence": "reputation_threat_monitoring",
    "reputation risk threat mitigation": "reputation_threat_monitoring",
    "reputation risk threat prevention": "reputation_threat_monitoring",
    "reputation risk threat response": "reputation_threat_monitoring",
    "reputation risk threat management": "reputation_threat_monitoring",
    "reputation risk threat control": "reputation_threat_monitoring",
    "reputation risk threat vulnerability": "reputation_threat_monitoring",
    "reputation risk threat weakness": "reputation_threat_monitoring",
    "reputation risk threat flaw": "reputation_threat_monitoring",
    "reputation risk threat exposure": "reputation_threat_monitoring",
    "reputation risk threat hazard": "reputation_threat_monitoring",
    "reputation risk threat issue": "reputation_threat_monitoring",
    "reputation risk threat problem": "reputation_threat_monitoring",
    "reputation damage": "reputation_threat_monitoring",
    "reputation loss": "reputation_threat_monitoring",
    "reputation harm": "reputation_threat_monitoring",
    "reputation degradation": "reputation_threat_monitoring",
    "reputation impact": "reputation_threat_monitoring",
    "reputation threat actor": "reputation_threat_monitoring",
    "reputation threat source": "reputation_threat_monitoring",
    "reputation threat agent": "reputation_threat_monitoring",
    "reputation threat vector": "reputation_threat_monitoring",
    "reputation threat landscape": "reputation_threat_monitoring",
    "reputation threat intel": "reputation_threat_monitoring",
    "reputation threat intelligence": "reputation_threat_monitoring",

    # Insider Threat Detection
    "insider threat detection": "insider_threat_detection",
    "insider threat detect": "insider_threat_detection",
    "insider threat monitor": "insider_threat_detection",
    "insider threat monitoring": "insider_threat_detection",
    "insider threat analysis": "insider_threat_detection",
    "insider threat assessment": "insider_threat_detection",
    "insider threat intelligence": "insider_threat_detection",
    "insider threat intel": "insider_threat_detection",
    "insider threat mitigation": "insider_threat_detection",
    "insider threat prevention": "insider_threat_detection",
    "insider threat response": "insider_threat_detection",
    "insider threat management": "insider_threat_detection",
    "insider threat control": "insider_threat_detection",
    "insider threat risk": "insider_threat_detection",
    "insider threat vulnerability": "insider_threat_detection",
    "insider threat weakness": "insider_threat_detection",
    "insider threat flaw": "insider_threat_detection",
    "insider threat exposure": "insider_threat_detection",
    "insider threat hazard": "insider_threat_detection",
    "insider threat issue": "insider_threat_detection",
    "insider threat problem": "insider_threat_detection",
    "insider risk": "insider_threat_detection",
    "insider risk detection": "insider_threat_detection",
    "insider risk monitor": "insider_threat_detection",
    "insider risk monitoring": "insider_threat_detection",
    "insider risk assessment": "insider_threat_detection",
    "insider risk analysis": "insider_threat_detection",
    "insider risk intelligence": "insider_threat_detection",
    "insider risk intel": "insider_threat_detection",
    "insider risk mitigation": "insider_threat_detection",
    "insider risk prevention": "insider_threat_detection",
    "insider risk response": "insider_threat_detection",
    "insider risk management": "insider_threat_detection",
    "insider risk control": "insider_threat_detection",
    "insider risk vulnerability": "insider_threat_detection",
    "insider risk weakness": "insider_threat_detection",
    "insider risk flaw": "insider_threat_detection",
    "insider risk exposure": "insider_threat_detection",
    "insider risk hazard": "insider_threat_detection",
    "insider risk issue": "insider_threat_detection",
    "insider risk problem": "insider_threat_detection",
    "insider threat actor": "insider_threat_detection",
    "insider threat source": "insider_threat_detection",
    "insider threat agent": "insider_threat_detection",
    "insider threat vector": "insider_threat_detection",
    "insider threat landscape": "insider_threat_detection",
    "insider threat intel": "insider_threat_detection",
    "insider threat intelligence": "insider_threat_detection",
    "insider threat behavior": "insider_threat_detection",
    "insider threat activity": "insider_threat_detection",
    "insider threat event": "insider_threat_detection",
    "insider threat incident": "insider_threat_detection",
    "insider threat alert": "insider_threat_detection",
    "insider threat signal": "insider_threat_detection",
    "insider threat anomaly": "insider_threat_detection",
    "insider threat pattern": "insider_threat_detection",
    "insider threat indicator": "insider_threat_detection",
    "insider threat indicator of compromise": "insider_threat_detection",
    "insider threat ioc": "insider_threat_detection",

    # Supply Chain Threat Analysis
    "supply chain threat analysis": "supply_chain_threat_analysis",
    "supply chain threat assess": "supply_chain_threat_analysis",
    "supply chain threat assessment": "supply_chain_threat_analysis",
    "supply chain threat detection": "supply_chain_threat_analysis",
    "supply chain threat monitor": "supply_chain_threat_analysis",
    "supply chain threat monitoring": "supply_chain_threat_analysis",
    "supply chain threat intelligence": "supply_chain_threat_analysis",
    "supply chain threat intel": "supply_chain_threat_analysis",
    "supply chain threat mitigation": "supply_chain_threat_analysis",
    "supply chain threat prevention": "supply_chain_threat_analysis",
    "supply chain threat response": "supply_chain_threat_analysis",
    "supply chain threat management": "supply_chain_threat_analysis",
    "supply chain threat control": "supply_chain_threat_analysis",
    "supply chain threat risk": "supply_chain_threat_analysis",
    "supply chain threat vulnerability": "supply_chain_threat_analysis",
    "supply chain threat weakness": "supply_chain_threat_analysis",
    "supply chain threat flaw": "supply_chain_threat_analysis",
    "supply chain threat exposure": "supply_chain_threat_analysis",
    "supply chain threat hazard": "supply_chain_threat_analysis",
    "supply chain threat issue": "supply_chain_threat_analysis",
    "supply chain threat problem": "supply_chain_threat_analysis",
    "supply chain risk": "supply_chain_threat_analysis",
    "supply chain risk assessment": "supply_chain_threat_analysis",
    "supply chain risk assess": "supply_chain_threat_analysis",
    "supply chain risk analysis": "supply_chain_threat_analysis",
    "supply chain risk detection": "supply_chain_threat_analysis",
    "supply chain risk monitor": "supply_chain_threat_analysis",
    "supply chain risk monitoring": "supply_chain_threat_analysis",
    "supply chain risk intelligence": "supply_chain_threat_analysis",
    "supply chain risk intel": "supply_chain_threat_analysis",
    "supply chain risk mitigation": "supply_chain_threat_analysis",
    "supply chain risk prevention": "supply_chain_threat_analysis",
    "supply chain risk response": "supply_chain_threat_analysis",
    "supply chain risk management": "supply_chain_threat_analysis",
    "supply chain risk control": "supply_chain_threat_analysis",
    "supply chain risk vulnerability": "supply_chain_threat_analysis",
    "supply chain risk weakness": "supply_chain_threat_analysis",
    "supply chain risk flaw": "supply_chain_threat_analysis",
    "supply chain risk exposure": "supply_chain_threat_analysis",
    "supply chain risk hazard": "supply_chain_threat_analysis",
    "supply chain risk issue": "supply_chain_threat_analysis",
    "supply chain risk problem": "supply_chain_threat_analysis",
    "supply chain disruption": "supply_chain_threat_analysis",
    "supply chain disruption risk": "supply_chain_threat_analysis",
    "supply chain disruption threat": "supply_chain_threat_analysis",
    "supply chain disruption detection": "supply_chain_threat_analysis",
    "supply chain disruption monitoring": "supply_chain_threat_analysis",
    "supply chain disruption mitigation": "supply_chain_threat_analysis",
    "supply chain disruption prevention": "supply_chain_threat_analysis",
    "supply chain disruption response": "supply_chain_threat_analysis",
    "supply chain disruption management": "supply_chain_threat_analysis",
    "supply chain disruption control": "supply_chain_threat_analysis",
    "supply chain disruption vulnerability": "supply_chain_threat_analysis",
    "supply chain disruption weakness": "supply_chain_threat_analysis",
    "supply chain disruption flaw": "supply_chain_threat_analysis",
    "supply chain disruption exposure": "supply_chain_threat_analysis",
    "supply chain disruption hazard": "supply_chain_threat_analysis",
    "supply chain disruption issue": "supply_chain_threat_analysis",
    "supply chain disruption problem": "supply_chain_threat_analysis",
    "supply chain attack": "supply_chain_threat_analysis",
    "supply chain attack detection": "supply_chain_threat_analysis",
    "supply chain attack monitoring": "supply_chain_threat_analysis",
    "supply chain attack mitigation": "supply_chain_threat_analysis",
    "supply chain attack prevention": "supply_chain_threat_analysis",
    "supply chain attack response": "supply_chain_threat_analysis",
    "supply chain attack management": "supply_chain_threat_analysis",
    "supply chain attack control": "supply_chain_threat_analysis",
    "supply chain attack vulnerability": "supply_chain_threat_analysis",
    "supply chain attack weakness": "supply_chain_threat_analysis",
    "supply chain attack flaw": "supply_chain_threat_analysis",
    "supply chain attack exposure": "supply_chain_threat_analysis",
    "supply chain attack hazard": "supply_chain_threat_analysis",
    "supply chain attack issue": "supply_chain_threat_analysis",
    "supply chain attack problem": "supply_chain_threat_analysis",

    # Geopolitical Permian Basin Risk
    "geopolitical permian basin risk": "geopolitical_permian_basin_risk",
    "permian basin geopolitical risk": "geopolitical_permian_basin_risk",
    "permian basin geopolitics risk": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat": "geopolitical_permian_basin_risk",
    "permian basin geo political risk": "geopolitical_permian_basin_risk",
    "permian basin geo-political risk": "geopolitical_permian_basin_risk",
    "permian basin geopolitical risk assessment": "geopolitical_permian_basin_risk",
    "permian basin geopolitical risk analysis": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat assessment": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat analysis": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat detection": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat monitoring": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat mitigation": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat prevention": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat response": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat management": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat control": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat risk": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat vulnerability": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat weakness": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat flaw": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat exposure": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat hazard": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat issue": "geopolitical_permian_basin_risk",
    "permian basin geopolitical threat problem": "geopolitical_permian_basin_risk",
    "permian basin political risk": "geopolitical_permian_basin_risk",
    "permian basin political threat": "geopolitical_permian_basin_risk",
    "permian basin political instability": "geopolitical_permian_basin_risk",
    "permian basin political unrest": "geopolitical_permian_basin_risk",
    "permian basin political conflict": "geopolitical_permian_basin_risk",
    "permian basin political violence": "geopolitical_permian_basin_risk",
    "permian basin political crisis": "geopolitical_permian_basin_risk",
    "permian basin political disruption": "geopolitical_permian_basin_risk",
    "permian basin political hazard": "geopolitical_permian_basin_risk",
    "permian basin political issue": "geopolitical_permian_basin_risk",
    "permian basin political problem": "geopolitical_permian_basin_risk",
    "permian basin geopolitical instability": "geopolitical_permian_basin_risk",
    "permian basin geopolitical unrest": "geopolitical_permian_basin_risk",
    "permian basin geopolitical conflict": "geopolitical_permian_basin_risk",
    "permian basin geopolitical violence": "geopolitical_permian_basin_risk",
    "permian basin geopolitical crisis": "geopolitical_permian_basin_risk",
    "permian basin geopolitical disruption": "geopolitical_permian_basin_risk",
    "permian basin geopolitical hazard": "geopolitical_permian_basin_risk",
    "permian basin geopolitical issue": "geopolitical_permian_basin_risk",
    "permian basin geopolitical problem": "geopolitical_permian_basin_risk",

    # Credential Compromise Threat
    "credential compromise threat": "credential_compromise_threat",
    "credential compromise": "credential_compromise_threat",
    "credential theft": "credential_compromise_threat",
    "credential leak": "credential_compromise_threat",
    "credential exposure": "credential_compromise_threat",
    "credential breach": "credential_compromise_threat",
    "credential loss": "credential_compromise_threat",
    "credential hijack": "credential_compromise_threat",
    "credential misuse": "credential_compromise_threat",
    "credential abuse": "credential_compromise_threat",
    "credential fraud": "credential_compromise_threat",
    "credential attack": "credential_compromise_threat",
    "credential attack vector": "credential_compromise_threat",
    "credential attack surface": "credential_compromise_threat",
    "credential attack method": "credential_compromise_threat",
    "credential attack technique": "credential_compromise_threat",
    "credential attack tactic": "credential_compromise_threat",
    "credential attack procedure": "credential_compromise_threat",
    "credential attack pattern": "credential_compromise_threat",
    "credential attack indicator": "credential_compromise_threat",
    "credential attack indicator of compromise": "credential_compromise_threat",
    "credential attack ioc": "credential_compromise_threat",
    "credential attack signature": "credential_compromise_threat",
    "credential attack alert": "credential_compromise_threat",
    "credential attack detection": "credential_compromise_threat",
    "credential attack monitoring": "credential_compromise_threat",
    "credential attack mitigation": "credential_compromise_threat",
    "credential attack prevention": "credential_compromise_threat",
    "credential attack response": "credential_compromise_threat",
    "credential attack management": "credential_compromise_threat",
    "credential attack control": "credential_compromise_threat",
    "credential attack risk": "credential_compromise_threat",
    "credential attack vulnerability": "credential_compromise_threat",
    "credential attack weakness": "credential_compromise_threat",
    "credential attack flaw": "credential_compromise_threat",
    "credential attack exposure": "credential_compromise_threat",
    "credential attack hazard": "credential_compromise_threat",
    "credential attack issue": "credential_compromise_threat",
    "credential attack problem": "credential_compromise_threat",
    "credential compromise detection": "credential_compromise_threat",
    "credential compromise monitoring": "credential_compromise_threat",
    "credential compromise mitigation": "credential_compromise_threat",
    "credential compromise prevention": "credential_compromise_threat",
    "credential compromise response": "credential_compromise_threat",
    "credential compromise management": "credential_compromise_threat",
    "credential compromise control": "credential_compromise_threat",
    "credential compromise risk": "credential_compromise_threat",
    "credential compromise vulnerability": "credential_compromise_threat",
    "credential compromise weakness": "credential_compromise_threat",
    "credential compromise flaw": "credential_compromise_threat",
    "credential compromise exposure": "credential_compromise_threat",
    "credential compromise hazard": "credential_compromise_threat",
    "credential compromise issue": "credential_compromise_threat",
    "credential compromise problem": "credential_compromise_threat",
    "credential theft detection": "credential_compromise_threat",
    "credential theft monitoring": "credential_compromise_threat",
    "credential theft mitigation": "credential_compromise_threat",
    "credential theft prevention": "credential_compromise_threat",
    "credential theft response": "credential_compromise_threat",
    "credential theft management": "credential_compromise_threat",
    "credential theft control": "credential_compromise_threat",
    "credential theft risk": "credential_compromise_threat",
    "credential theft vulnerability": "credential_compromise_threat",
    "credential theft weakness": "credential_compromise_threat",
    "credential theft flaw": "credential_compromise_threat",
    "credential theft exposure": "credential_compromise_threat",
    "credential theft hazard": "credential_compromise_threat",
    "credential theft issue": "credential_compromise_threat",
    "credential theft problem": "credential_compromise_threat",

    # Ransomware Threat
    "ransomware threat": "ransomware_threat",
    "ransomware attack": "ransomware_threat",
    "ransomware infection": "ransomware_threat",
    "ransomware compromise": "ransomware_threat",
    "ransomware incident": "ransomware_threat",
    "ransomware event": "ransomware_threat",
    "ransomware detection": "ransomware_threat",
    "ransomware monitoring": "ransomware_threat",
    "ransomware mitigation": "ransomware_threat",
    "ransomware prevention": "ransomware_threat",
    "ransomware response": "ransomware_threat",
    "ransomware management": "ransomware_threat",
    "ransomware control": "ransomware_threat",
    "ransomware risk": "ransomware_threat",
    "ransomware vulnerability": "ransomware_threat",
    "ransomware weakness": "ransomware_threat",
    "ransomware flaw": "ransomware_threat",
    "ransomware exposure": "ransomware_threat",
    "ransomware hazard": "ransomware_threat",
    "ransomware issue": "ransomware_threat",
    "ransomware problem": "ransomware_threat",
    "ransomware vector": "ransomware_threat",
    "ransomware actor": "ransomware_threat",
    "ransomware source": "ransomware_threat",
    "ransomware agent": "ransomware_threat",
    "ransomware landscape": "ransomware_threat",
    "ransomware intel": "ransomware_threat",
    "ransomware intelligence": "ransomware_threat",
    "ransomware threat actor": "ransomware_threat",
    "ransomware threat source": "ransomware_threat",
    "ransomware threat agent": "ransomware_threat",
    "ransomware threat vector": "ransomware_threat",
    "ransomware threat landscape": "ransomware_threat",
    "ransomware threat intel": "ransomware_threat",
    "ransomware threat intelligence": "ransomware_threat",
    "ransomware attack vector": "ransomware_threat",
    "ransomware attack surface": "ransomware_threat",
    "ransomware attack method": "ransomware_threat",
    "ransomware attack technique": "ransomware_threat",
    "ransomware attack tactic": "ransomware_threat",
    "ransomware attack procedure": "ransomware_threat",
    "ransomware attack pattern": "ransomware_threat",
    "ransomware attack indicator": "ransomware_threat",
    "ransomware attack indicator of compromise": "ransomware_threat",
    "ransomware attack ioc": "ransomware_threat",
    "ransomware attack signature": "ransomware_threat",
    "ransomware alert": "ransomware_threat",
    "ransomware alerting": "ransomware_threat",

    # Social Engineering Threats
    "social engineering threats": "social_engineering_threats",
    "social engineering threat": "social_engineering_threats",
    "social engineering attack": "social_engineering_threats",
    "social engineering scam": "social_engineering_threats",
    "social engineering fraud": "social_engineering_threats",
    "social engineering deception": "social_engineering_threats",
    "social engineering manipulation": "social_engineering_threats",
    "social engineering phishing": "social_engineering_threats",
    "social engineering spear phishing": "social_engineering_threats",
    "social engineering whaling": "social_engineering_threats",
    "social engineering baiting": "social_engineering_threats",
    "social engineering pretexting": "social_engineering_threats",
    "social engineering tailgating": "social_engineering_threats",
    "social engineering vishing": "social_engineering_threats",
    "social engineering smishing": "social_engineering_threats",
    "social engineering attack vector": "social_engineering_threats",
    "social engineering attack surface": "social_engineering_threats",
    "social engineering attack method": "social_engineering_threats",
    "social engineering attack technique": "social_engineering_threats",
    "social engineering attack tactic": "social_engineering_threats",
    "social engineering attack procedure": "social_engineering_threats",
    "social engineering attack pattern": "social_engineering_threats",
    "social engineering attack indicator": "social_engineering_threats",
    "social engineering attack indicator of compromise": "social_engineering_threats",
    "social engineering attack ioc": "social_engineering_threats",
    "social engineering attack signature": "social_engineering_threats",
    "social engineering alert": "social_engineering_threats",
    "social engineering alerting": "social_engineering_threats",
    "social engineering detection": "social_engineering_threats",
    "social engineering monitoring": "social_engineering_threats",
    "social engineering mitigation": "social_engineering_threats",
    "social engineering prevention": "social_engineering_threats",
    "social engineering response": "social_engineering_threats",
    "social engineering management": "social_engineering_threats",
    "social engineering control": "social_engineering_threats",
    "social engineering risk": "social_engineering_threats",
    "social engineering vulnerability": "social_engineering_threats",
    "social engineering weakness": "social_engineering_threats",
    "social engineering flaw": "social_engineering_threats",
    "social engineering exposure": "social_engineering_threats",
    "social engineering hazard": "social_engineering_threats",
    "social engineering issue": "social_engineering_threats",
    "social engineering problem": "social_engineering_threats",

    # Environmental Compliance Threat
    "environmental compliance threat": "environmental_compliance_threat",
    "environmental compliance risk": "environmental_compliance_threat",
    "environmental compliance issue": "environmental_compliance_threat",
    "environmental compliance problem": "environmental_compliance_threat",
    "environmental compliance violation": "environmental_compliance_threat",
    "environmental compliance breach": "environmental_compliance_threat",
    "environmental compliance incident": "environmental_compliance_threat",
    "environmental compliance concern": "environmental_compliance_threat",
    "environmental compliance vulnerability": "environmental_compliance_threat",
    "environmental compliance weakness": "environmental_compliance_threat",
    "environmental compliance flaw": "environmental_compliance_threat",
    "environmental compliance exposure": "environmental_compliance_threat",
    "environmental compliance hazard": "environmental_compliance_threat",
    "environmental compliance threat assessment": "environmental_compliance_threat",
    "environmental compliance threat analysis": "environmental_compliance_threat",
    "environmental compliance threat detection": "environmental_compliance_threat",
    "environmental compliance threat monitoring": "environmental_compliance_threat",
    "environmental compliance threat mitigation": "environmental_compliance_threat",
    "environmental compliance threat prevention": "environmental_compliance_threat",
    "environmental compliance threat response": "environmental_compliance_threat",
    "environmental compliance threat management": "environmental_compliance_threat",
    "environmental compliance threat control": "environmental_compliance_threat",
    "environmental compliance threat risk": "environmental_compliance_threat",
    "environmental compliance threat vulnerability": "environmental_compliance_threat",
    "environmental compliance threat weakness": "environmental_compliance_threat",
    "environmental compliance threat flaw": "environmental_compliance_threat",
    "environmental compliance threat exposure": "environmental_compliance_threat",
    "environmental compliance threat hazard": "environmental_compliance_threat",
    "environmental compliance threat issue": "environmental_compliance_threat",
    "environmental compliance threat problem": "environmental_compliance_threat",
    "env compliance threat": "environmental_compliance_threat",
    "env compliance risk": "environmental_compliance_threat",
    "env compliance issue": "environmental_compliance_threat",
    "env compliance problem": "environmental_compliance_threat",
    "env compliance violation": "environmental_compliance_threat",
    "env compliance breach": "environmental_compliance_threat",
    "env compliance incident": "environmental_compliance_threat",
    "env compliance concern": "environmental_compliance_threat",
    "env compliance vulnerability": "environmental_compliance_threat",
    "env compliance weakness": "environmental_compliance_threat",
    "env compliance flaw": "environmental_compliance_threat",
    "env compliance exposure": "environmental_compliance_threat",
    "env compliance hazard": "environmental_compliance_threat",
    "env compliance threat assessment": "environmental_compliance_threat",
    "env compliance threat analysis": "environmental_compliance_threat",
    "env compliance threat detection": "environmental_compliance_threat",
    "env compliance threat monitoring": "environmental_compliance_threat",
    "env compliance threat mitigation": "environmental_compliance_threat",
    "env compliance threat prevention": "environmental_compliance_threat",
    "env compliance threat response": "environmental_compliance_threat",
    "env compliance threat management": "environmental_compliance_threat",
    "env compliance threat control": "environmental_compliance_threat",
    "env compliance threat risk": "environmental_compliance_threat",
    "env compliance threat vulnerability": "environmental_compliance_threat",
    "env compliance threat weakness": "environmental_compliance_threat",
    "env compliance threat flaw": "environmental_compliance_threat",
    "env compliance threat exposure": "environmental_compliance_threat",
    "env compliance threat hazard": "environmental_compliance_threat",
    "env compliance threat issue": "environmental_compliance_threat",
    "env compliance threat problem": "environmental_compliance_threat",

    # DDoS Service Disruption
    "ddos service disruption": "ddos_service_disruption",
    "ddos attack": "ddos_service_disruption",
    "distributed denial of service": "ddos_service_disruption",
    "denial of service attack": "ddos_service_disruption",
    "dos attack": "ddos_service_disruption",
    "ddos threat": "ddos_service_disruption",
    "ddos incident": "ddos_service_disruption",
    "ddos event": "ddos_service_disruption",
    "ddos detection": "ddos_service_disruption",
    "ddos monitoring": "ddos_service_disruption",
    "ddos mitigation": "ddos_service_disruption",
    "ddos prevention": "ddos_service_disruption",
    "ddos response": "ddos_service_disruption",
    "ddos management": "ddos_service_disruption",
    "ddos control": "ddos_service_disruption",
    "ddos risk": "ddos_service_disruption",
    "ddos vulnerability": "ddos_service_disruption",
    "ddos weakness": "ddos_service_disruption",
    "ddos flaw": "ddos_service_disruption",
    "ddos exposure": "ddos_service_disruption",
    "ddos hazard": "ddos_service_disruption",
    "ddos issue": "ddos_service_disruption",
    "ddos problem": "ddos_service_disruption",
    "ddos vector": "ddos_service_disruption",
    "ddos actor": "ddos_service_disruption",
    "ddos source": "ddos_service_disruption",
    "ddos agent": "ddos_service_disruption",
    "ddos landscape": "ddos_service_disruption",
    "ddos intel": "ddos_service_disruption",
    "ddos intelligence": "ddos_service_disruption",

    # Intellectual Property Theft
    "intellectual property theft": "intellectual_property_theft",
    "ip theft": "intellectual_property_theft",
    "intellectual property violation": "intellectual_property_theft",
    "ip violation": "intellectual_property_theft",
    "intellectual property infringement": "intellectual_property_theft",
    "ip infringement": "intellectual_property_theft",
    "intellectual property compromise": "intellectual_property_theft",
    "ip compromise": "intellectual_property_theft",
    "intellectual property loss": "intellectual_property_theft",
    "ip loss": "intellectual_property_theft",
    "intellectual property breach": "intellectual_property_theft",
    "ip breach": "intellectual_property_theft",
    "intellectual property risk": "intellectual_property_theft",
    "ip risk": "intellectual_property_theft",
    "intellectual property threat": "intellectual_property_theft",
    "ip threat": "intellectual_property_theft",
    "intellectual property attack": "intellectual_property_theft",
    "ip attack": "intellectual_property_theft",
    "intellectual property incident": "intellectual_property_theft",
    "ip incident": "intellectual_property_theft",
    "intellectual property event": "intellectual_property_theft",
    "ip event": "intellectual_property_theft",
    "intellectual property detection": "intellectual_property_theft",
    "ip detection": "intellectual_property_theft",
    "intellectual property monitoring": "intellectual_property_theft",
    "ip monitoring": "intellectual_property_theft",
    "intellectual property mitigation": "intellectual_property_theft",
    "ip mitigation": "intellectual_property_theft",
    "intellectual property prevention": "intellectual_property_theft",
    "ip prevention": "intellectual_property_theft",
    "intellectual property response": "intellectual_property_theft",
    "ip response": "intellectual_property_theft",
    "intellectual property management": "intellectual_property_theft",
    "ip management": "intellectual_property_theft",
    "intellectual property control": "intellectual_property_theft",
    "ip control": "intellectual_property_theft",
    "intellectual property vulnerability": "intellectual_property_theft",
    "ip vulnerability": "intellectual_property_theft",
    "intellectual property weakness": "intellectual_property_theft",
    "ip weakness": "intellectual_property_theft",
    "intellectual property flaw": "intellectual_property_theft",
    "ip flaw": "intellectual_property_theft",
    "intellectual property exposure": "intellectual_property_theft",
    "ip exposure": "intellectual_property_theft",
    "intellectual property hazard": "intellectual_property_theft",
    "ip hazard": "intellectual_property_theft",
    "intellectual property issue": "intellectual_property_theft",
    "ip issue": "intellectual_property_theft",
    "intellectual property problem": "intellectual_property_theft",
    "ip problem": "intellectual_property_theft",

    # Economic Downturn Market Risk
    "economic downturn market risk": "economic_downturn_market_risk",
    "economic downturn risk": "economic_downturn_market_risk",
    "market risk economic downturn": "economic_downturn_market_risk",
    "economic recession risk": "economic_downturn_market_risk",
    "economic slowdown risk": "economic_downturn_market_risk",
    "economic contraction risk": "economic_downturn_market_risk",
    "economic decline risk": "economic_downturn_market_risk",
    "economic crisis risk": "economic_downturn_market_risk",
    "economic depression risk": "economic_downturn_market_risk",
    "economic downturn threat": "economic_downturn_market_risk",
    "economic recession threat": "economic_downturn_market_risk",
    "economic slowdown threat": "economic_downturn_market_risk",
    "economic contraction threat": "economic_downturn_market_risk",
    "economic decline threat": "economic_downturn_market_risk",
    "economic crisis threat": "economic_downturn_market_risk",
    "economic depression threat": "economic_downturn_market_risk",
    "economic downturn risk assessment": "economic_downturn_market_risk",
    "economic downturn risk analysis": "economic_downturn_market_risk",
    "economic downturn risk detection": "economic_downturn_market_risk",
    "economic downturn risk monitoring": "economic_downturn_market_risk",
    "economic downturn risk mitigation": "economic_downturn_market_risk",
    "economic downturn risk prevention": "economic_downturn_market_risk",
    "economic downturn risk response": "economic_downturn_market_risk",
    "economic downturn risk management": "economic_downturn_market_risk",
    "economic downturn risk control": "economic_downturn_market_risk",
    "economic downturn risk vulnerability": "economic_downturn_market_risk",
    "economic downturn risk weakness": "economic_downturn_market_risk",
    "economic downturn risk flaw": "economic_downturn_market_risk",
    "economic downturn risk exposure": "economic_downturn_market_risk",
    "economic downturn risk hazard": "economic_downturn_market_risk",
    "economic downturn risk issue": "economic_downturn_market_risk",
    "economic downturn risk problem": "economic_downturn_market_risk",
    "economic downturn market threat": "economic_downturn_market_risk",
    "economic downturn market vulnerability": "economic_downturn_market_risk",
    "economic downturn market weakness": "economic_downturn_market_risk",
    "economic downturn market flaw": "economic_downturn_market_risk",
    "economic downturn market exposure": "economic_downturn_market_risk",
    "economic downturn market hazard": "economic_downturn_market_risk",
    "economic downturn market issue": "economic_downturn_market_risk",
    "economic downturn market problem": "economic_downturn_market_risk",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    hasher = hashlib.sha256()
    for key in sorted(SEMANTIC_MAP.keys()):
        value = SEMANTIC_MAP[key]
        entry = f"{key}=>{value}"
        hasher.update(entry.encode("utf-8"))
    return hasher.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    current_count = len(SEMANTIC_MAP)
    current_hash = _compute_map_hash()
    is_valid = (current_count == _EXPECTED_ENTRY_COUNT) and (current_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": current_count,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "hash": current_hash,
        "expected_hash": _MAP_INTEGRITY_HASH,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    if not term:
        return ""
    key = term.strip().lower()
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list[str]:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)