import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "E12_feedback_ingester"
SEMANTIC_MAP_ENGINE = "E12"

SEMANTIC_MAP = {
    # correction_intake
    "correction": "correction_intake",
    "corrections": "correction_intake",
    "correction intake": "correction_intake",
    "correction submission": "correction_intake",
    "submit correction": "correction_intake",
    "correction request": "correction_intake",
    "correction-entry": "correction_intake",
    "correctioninput": "correction_intake",
    "correctionin": "correction_intake",
    "correction intake process": "correction_intake",
    "correction form": "correction_intake",
    "correction-application": "correction_intake",
    "correction_app": "correction_intake",
    "correction intake queue": "correction_intake",
    "correction intake pipeline": "correction_intake",
    "correction intake system": "correction_intake",
    "correction-intake": "correction_intake",
    "correctionintake": "correction_intake",
    "correction intake module": "correction_intake",
    "correction-queue": "correction_intake",
    "correction intake submission": "correction_intake",
    "correction intake record": "correction_intake",
    "correction intake entry": "correction_intake",
    "correction intake event": "correction_intake",
    "correction entry": "correction_intake",
    "correction submission form": "correction_intake",
    "correction submission queue": "correction_intake",
    "correction submission event": "correction_intake",
    "correction submit": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake submission": "correction_intake",
    "correction intake form": "correction_intake",
    "correction intake request": "correction_intake",
    "correction intake record": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake entry": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake submission": "correction_intake",
    "correction intake form": "correction_intake",
    "correction intake request": "correction_intake",
    "correction intake record": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake entry": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake submission": "correction_intake",
    "correction intake form": "correction_intake",
    "correction intake request": "correction_intake",
    "correction intake record": "correction_intake",
    "correction intake event": "correction_intake",
    "correction intake entry": "correction_intake",
    "correction intake event": "correction_intake",
    # rating_aggregation
    "rating": "rating_aggregation",
    "ratings": "rating_aggregation",
    "rate": "rating_aggregation",
    "rating aggregation": "rating_aggregation",
    "aggregate rating": "rating_aggregation",
    "ratingagg": "rating_aggregation",
    "rating-agg": "rating_aggregation",
    "ratingagg.": "rating_aggregation",
    "rating aggr": "rating_aggregation",
    "rating aggr.": "rating_aggregation",
    "rating aggregator": "rating_aggregation",
    "rating-aggregator": "rating_aggregation",
    "ratingaggregation": "rating_aggregation",
    "rating aggregation process": "rating_aggregation",
    "rating aggregation module": "rating_aggregation",
    "rating aggregation system": "rating_aggregation",
    "rating aggregation pipeline": "rating_aggregation",
    "rating aggregation queue": "rating_aggregation",
    "rating aggregation event": "rating_aggregation",
    "rating aggregation record": "rating_aggregation",
    "rating aggregation entry": "rating_aggregation",
    "rating aggregation submission": "rating_aggregation",
    "rating aggregation form": "rating_aggregation",
    "rating aggregation request": "rating_aggregation",
    "rating aggregation event": "rating_aggregation",
    "rating aggregation entry": "rating_aggregation",
    "rating aggregation submission": "rating_aggregation",
    "rating aggregation form": "rating_aggregation",
    "rating aggregation request": "rating_aggregation",
    "rating aggregation record": "rating_aggregation",
    "rating aggregation event": "rating_aggregation",
    # rejection_processing
    "rejection": "rejection_processing",
    "reject": "rejection_processing",
    "rejections": "rejection_processing",
    "rejection processing": "rejection_processing",
    "process rejection": "rejection_processing",
    "rejection process": "rejection_processing",
    "rejectionproc": "rejection_processing",
    "rejection-proc": "rejection_processing",
    "rejectionproc.": "rejection_processing",
    "rejection processor": "rejection_processing",
    "rejection-processing": "rejection_processing",
    "rejectionprocessing": "rejection_processing",
    "rejection processing module": "rejection_processing",
    "rejection processing system": "rejection_processing",
    "rejection processing pipeline": "rejection_processing",
    "rejection processing queue": "rejection_processing",
    "rejection processing event": "rejection_processing",
    "rejection processing record": "rejection_processing",
    "rejection processing entry": "rejection_processing",
    "rejection processing submission": "rejection_processing",
    "rejection processing form": "rejection_processing",
    "rejection processing request": "rejection_processing",
    "rejection processing event": "rejection_processing",
    "rejection processing entry": "rejection_processing",
    # approval_tracking
    "approval": "approval_tracking",
    "approvals": "approval_tracking",
    "approve": "approval_tracking",
    "approval tracking": "approval_tracking",
    "approvaltrack": "approval_tracking",
    "approval-track": "approval_tracking",
    "approvaltrack.": "approval_tracking",
    "approval tracker": "approval_tracking",
    "approval-tracker": "approval_tracking",
    "approvaltracking": "approval_tracking",
    "approval tracking module": "approval_tracking",
    "approval tracking system": "approval_tracking",
    "approval tracking pipeline": "approval_tracking",
    "approval tracking queue": "approval_tracking",
    "approval tracking event": "approval_tracking",
    "approval tracking record": "approval_tracking",
    "approval tracking entry": "approval_tracking",
    "approval tracking submission": "approval_tracking",
    "approval tracking form": "approval_tracking",
    "approval tracking request": "approval_tracking",
    "approval tracking event": "approval_tracking",
    "approval tracking entry": "approval_tracking",
    # suggestion_processing
    "suggestion": "suggestion_processing",
    "suggestions": "suggestion_processing",
    "suggest": "suggestion_processing",
    "suggestion processing": "suggestion_processing",
    "process suggestion": "suggestion_processing",
    "suggestion process": "suggestion_processing",
    "suggestionproc": "suggestion_processing",
    "suggestion-proc": "suggestion_processing",
    "suggestionproc.": "suggestion_processing",
    "suggestion processor": "suggestion_processing",
    "suggestion-processing": "suggestion_processing",
    "suggestionprocessing": "suggestion_processing",
    "suggestion processing module": "suggestion_processing",
    "suggestion processing system": "suggestion_processing",
    "suggestion processing pipeline": "suggestion_processing",
    "suggestion processing queue": "suggestion_processing",
    "suggestion processing event": "suggestion_processing",
    "suggestion processing record": "suggestion_processing",
    "suggestion processing entry": "suggestion_processing",
    "suggestion processing submission": "suggestion_processing",
    "suggestion processing form": "suggestion_processing",
    "suggestion processing request": "suggestion_processing",
    "suggestion processing event": "suggestion_processing",
    "suggestion processing entry": "suggestion_processing",
    # flag_processing
    "flag": "flag_processing",
    "flags": "flag_processing",
    "flagged": "flag_processing",
    "flag processing": "flag_processing",
    "process flag": "flag_processing",
    "flag process": "flag_processing",
    "flagproc": "flag_processing",
    "flag-proc": "flag_processing",
    "flagproc.": "flag_processing",
    "flag processor": "flag_processing",
    "flag-processing": "flag_processing",
    "flagprocessing": "flag_processing",
    "flag processing module": "flag_processing",
    "flag processing system": "flag_processing",
    "flag processing pipeline": "flag_processing",
    "flag processing queue": "flag_processing",
    "flag processing event": "flag_processing",
    "flag processing record": "flag_processing",
    "flag processing entry": "flag_processing",
    "flag processing submission": "flag_processing",
    "flag processing form": "flag_processing",
    "flag processing request": "flag_processing",
    "flag processing event": "flag_processing",
    "flag processing entry": "flag_processing",
    # override_processing
    "override": "override_processing",
    "overrides": "override_processing",
    "override processing": "override_processing",
    "process override": "override_processing",
    "override process": "override_processing",
    "overrideproc": "override_processing",
    "override-proc": "override_processing",
    "overrideproc.": "override_processing",
    "override processor": "override_processing",
    "override-processing": "override_processing",
    "overrideprocessing": "override_processing",
    "override processing module": "override_processing",
    "override processing system": "override_processing",
    "override processing pipeline": "override_processing",
    "override processing queue": "override_processing",
    "override processing event": "override_processing",
    "override processing record": "override_processing",
    "override processing entry": "override_processing",
    "override processing submission": "override_processing",
    "override processing form": "override_processing",
    "override processing request": "override_processing",
    "override processing event": "override_processing",
    "override processing entry": "override_processing",
    # credential_validation
    "credential": "credential_validation",
    "credentials": "credential_validation",
    "credential validation": "credential_validation",
    "validate credential": "credential_validation",
    "credential validate": "credential_validation",
    "credentialvalidation": "credential_validation",
    "credential-validation": "credential_validation",
    "credential validator": "credential_validation",
    "credential validator module": "credential_validation",
    "credential validation process": "credential_validation",
    "credential validation system": "credential_validation",
    "credential validation pipeline": "credential_validation",
    "credential validation queue": "credential_validation",
    "credential validation event": "credential_validation",
    "credential validation record": "credential_validation",
    "credential validation entry": "credential_validation",
    "credential validation submission": "credential_validation",
    "credential validation form": "credential_validation",
    "credential validation request": "credential_validation",
    "credential validation event": "credential_validation",
    "credential validation entry": "credential_validation",
    # conflict_detection
    "conflict": "conflict_detection",
    "conflicts": "conflict_detection",
    "conflict detection": "conflict_detection",
    "detect conflict": "conflict_detection",
    "conflict detect": "conflict_detection",
    "conflictdetection": "conflict_detection",
    "conflict-detection": "conflict_detection",
    "conflict detector": "conflict_detection",
    "conflict detector module": "conflict_detection",
    "conflict detection process": "conflict_detection",
    "conflict detection system": "conflict_detection",
    "conflict detection pipeline": "conflict_detection",
    "conflict detection queue": "conflict_detection",
    "conflict detection event": "conflict_detection",
    "conflict detection record": "conflict_detection",
    "conflict detection entry": "conflict_detection",
    "conflict detection submission": "conflict_detection",
    "conflict detection form": "conflict_detection",
    "conflict detection request": "conflict_detection",
    "conflict detection event": "conflict_detection",
    "conflict detection entry": "conflict_detection",
    # aggregation_rules
    "aggregation rule": "aggregation_rules",
    "aggregation rules": "aggregation_rules",
    "agg rule": "aggregation_rules",
    "agg rules": "aggregation_rules",
    "aggregationrules": "aggregation_rules",
    "aggregation-rules": "aggregation_rules",
    "aggregation rule set": "aggregation_rules",
    "aggregation rule module": "aggregation_rules",
    "aggregation rule system": "aggregation_rules",
    "aggregation rule pipeline": "aggregation_rules",
    "aggregation rule queue": "aggregation_rules",
    "aggregation rule event": "aggregation_rules",
    "aggregation rule record": "aggregation_rules",
    "aggregation rule entry": "aggregation_rules",
    "aggregation rule submission": "aggregation_rules",
    "aggregation rule form": "aggregation_rules",
    "aggregation rule request": "aggregation_rules",
    "aggregation rule event": "aggregation_rules",
    "aggregation rule entry": "aggregation_rules",
    # doctrine_update_signal
    "doctrine update": "doctrine_update_signal",
    "doctrine updates": "doctrine_update_signal",
    "doctrineupdate": "doctrine_update_signal",
    "doctrine-update": "doctrine_update_signal",
    "doctrine update signal": "doctrine_update_signal",
    "doctrine update event": "doctrine_update_signal",
    "doctrine update trigger": "doctrine_update_signal",
    "doctrine update notification": "doctrine_update_signal",
    "doctrine update pipeline": "doctrine_update_signal",
    "doctrine update queue": "doctrine_update_signal",
    "doctrine update record": "doctrine_update_signal",
    "doctrine update entry": "doctrine_update_signal",
    "doctrine update submission": "doctrine_update_signal",
    "doctrine update form": "doctrine_update_signal",
    "doctrine update request": "doctrine_update_signal",
    "doctrine update event": "doctrine_update_signal",
    "doctrine update entry": "doctrine_update_signal",
    # keyword_adjustment_signal
    "keyword adjustment": "keyword_adjustment_signal",
    "keyword adjustments": "keyword_adjustment_signal",
    "keywordadjustment": "keyword_adjustment_signal",
    "keyword-adjustment": "keyword_adjustment_signal",
    "keyword adjustment signal": "keyword_adjustment_signal",
    "keyword adjustment event": "keyword_adjustment_signal",
    "keyword adjustment trigger": "keyword_adjustment_signal",
    "keyword adjustment notification": "keyword_adjustment_signal",
    "keyword adjustment pipeline": "keyword_adjustment_signal",
    "keyword adjustment queue": "keyword_adjustment_signal",
    "keyword adjustment record": "keyword_adjustment_signal",
    "keyword adjustment entry": "keyword_adjustment_signal",
    "keyword adjustment submission": "keyword_adjustment_signal",
    "keyword adjustment form": "keyword_adjustment_signal",
    "keyword adjustment request": "keyword_adjustment_signal",
    "keyword adjustment event": "keyword_adjustment_signal",
    "keyword adjustment entry": "keyword_adjustment_signal",
    # confidence_recalibration_signal
    "confidence recalibration": "confidence_recalibration_signal",
    "confidence recalibrations": "confidence_recalibration_signal",
    "confidencerecalibration": "confidence_recalibration_signal",
    "confidence-recalibration": "confidence_recalibration_signal",
    "confidence recalibration signal": "confidence_recalibration_signal",
    "confidence recalibration event": "confidence_recalibration_signal",
    "confidence recalibration trigger": "confidence_recalibration_signal",
    "confidence recalibration notification": "confidence_recalibration_signal",
    "confidence recalibration pipeline": "confidence_recalibration_signal",
    "confidence recalibration queue": "confidence_recalibration_signal",
    "confidence recalibration record": "confidence_recalibration_signal",
    "confidence recalibration entry": "confidence_recalibration_signal",
    "confidence recalibration submission": "confidence_recalibration_signal",
    "confidence recalibration form": "confidence_recalibration_signal",
    "confidence recalibration request": "confidence_recalibration_signal",
    "confidence recalibration event": "confidence_recalibration_signal",
    "confidence recalibration entry": "confidence_recalibration_signal",
    # error_pattern_detection
    "error pattern": "error_pattern_detection",
    "error patterns": "error_pattern_detection",
    "errorpattern": "error_pattern_detection",
    "error-pattern": "error_pattern_detection",
    "error pattern detection": "error_pattern_detection",
    "detect error pattern": "error_pattern_detection",
    "error pattern detect": "error_pattern_detection",
    "error pattern detector": "error_pattern_detection",
    "error pattern detector module": "error_pattern_detection",
    "error pattern detection process": "error_pattern_detection",
    "error pattern detection system": "error_pattern_detection",
    "error pattern detection pipeline": "error_pattern_detection",
    "error pattern detection queue": "error_pattern_detection",
    "error pattern detection event": "error_pattern_detection",
    "error pattern detection record": "error_pattern_detection",
    "error pattern detection entry": "error_pattern_detection",
    "error pattern detection submission": "error_pattern_detection",
    "error pattern detection form": "error_pattern_detection",
    "error pattern detection request": "error_pattern_detection",
    "error pattern detection event": "error_pattern_detection",
    "error pattern detection entry": "error_pattern_detection",
    # training_pair_generation
    "training pair": "training_pair_generation",
    "training pairs": "training_pair_generation",
    "trainingpair": "training_pair_generation",
    "training-pair": "training_pair_generation",
    "training pair generation": "training_pair_generation",
    "generate training pair": "training_pair_generation",
    "training pair generate": "training_pair_generation",
    "training pair generator": "training_pair_generation",
    "training pair generator module": "training_pair_generation",
    "training pair generation process": "training_pair_generation",
    "training pair generation system": "training_pair_generation",
    "training pair generation pipeline": "training_pair_generation",
    "training pair generation queue": "training_pair_generation",
    "training pair generation event": "training_pair_generation",
    "training pair generation record": "training_pair_generation",
    "training pair generation entry": "training_pair_generation",
    "training pair generation submission": "training_pair_generation",
    "training pair generation form": "training_pair_generation",
    "training pair generation request": "training_pair_generation",
    "training pair generation event": "training_pair_generation",
    "training pair generation entry": "training_pair_generation",
    # impact_tracking
    "impact": "impact_tracking",
    "impacts": "impact_tracking",
    "impact tracking": "impact_tracking",
    "track impact": "impact_tracking",
    "impact track": "impact_tracking",
    "impacttracking": "impact_tracking",
    "impact-tracking": "impact_tracking",
    "impact tracker": "impact_tracking",
    "impact tracker module": "impact_tracking",
    "impact tracking process": "impact_tracking",
    "impact tracking system": "impact_tracking",
    "impact tracking pipeline": "impact_tracking",
    "impact tracking queue": "impact_tracking",
    "impact tracking event": "impact_tracking",
    "impact tracking record": "impact_tracking",
    "impact tracking entry": "impact_tracking",
    "impact tracking submission": "impact_tracking",
    "impact tracking form": "impact_tracking",
    "impact tracking request": "impact_tracking",
    "impact tracking event": "impact_tracking",
    "impact tracking entry": "impact_tracking",
    # auto_apply_rules
    "auto apply rule": "auto_apply_rules",
    "auto apply rules": "auto_apply_rules",
    "autoapplyrule": "auto_apply_rules",
    "auto-apply-rule": "auto_apply_rules",
    "auto apply rule set": "auto_apply_rules",
    "auto apply rule module": "auto_apply_rules",
    "auto apply rule system": "auto_apply_rules",
    "auto apply rule pipeline": "auto_apply_rules",
    "auto apply rule queue": "auto_apply_rules",
    "auto apply rule event": "auto_apply_rules",
    "auto apply rule record": "auto_apply_rules",
    "auto apply rule entry": "auto_apply_rules",
    "auto apply rule submission": "auto_apply_rules",
    "auto apply rule form": "auto_apply_rules",
    "auto apply rule request": "auto_apply_rules",
    "auto apply rule event": "auto_apply_rules",
    "auto apply rule entry": "auto_apply_rules",
    # feedback_routing
    "feedback routing": "feedback_routing",
    "route feedback": "feedback_routing",
    "feedback route": "feedback_routing",
    "feedbackrouting": "feedback_routing",
    "feedback-routing": "feedback_routing",
    "feedback router": "feedback_routing",
    "feedback router module": "feedback_routing",
    "feedback routing process": "feedback_routing",
    "feedback routing system": "feedback_routing",
    "feedback routing pipeline": "feedback_routing",
    "feedback routing queue": "feedback_routing",
    "feedback routing event": "feedback_routing",
    "feedback routing record": "feedback_routing",
    "feedback routing entry": "feedback_routing",
    "feedback routing submission": "feedback_routing",
    "feedback routing form": "feedback_routing",
    "feedback routing request": "feedback_routing",
    "feedback routing event": "feedback_routing",
    "feedback routing entry": "feedback_routing",
    # quality_dashboard_metrics
    "quality dashboard": "quality_dashboard_metrics",
    "quality dashboards": "quality_dashboard_metrics",
    "qualitydashboard": "quality_dashboard_metrics",
    "quality-dashboard": "quality_dashboard_metrics",
    "quality dashboard metrics": "quality_dashboard_metrics",
    "quality dashboard metric": "quality_dashboard_metrics",
    "quality dash": "quality_dashboard_metrics",
    "qualitydash": "quality_dashboard_metrics",
    "quality dash metrics": "quality_dashboard_metrics",
    "quality dash metric": "quality_dashboard_metrics",
    "quality dashboard module": "quality_dashboard_metrics",
    "quality dashboard system": "quality_dashboard_metrics",
    "quality dashboard pipeline": "quality_dashboard_metrics",
    "quality dashboard queue": "quality_dashboard_metrics",
    "quality dashboard event": "quality_dashboard_metrics",
    "quality dashboard record": "quality_dashboard_metrics",
    "quality dashboard entry": "quality_dashboard_metrics",
    "quality dashboard submission": "quality_dashboard_metrics",
    "quality dashboard form": "quality_dashboard_metrics",
    "quality dashboard request": "quality_dashboard_metrics",
    "quality dashboard event": "quality_dashboard_metrics",
    "quality dashboard entry": "quality_dashboard_metrics",
    # regression_detection
    "regression": "regression_detection",
    "regressions": "regression_detection",
    "regression detection": "regression_detection",
    "detect regression": "regression_detection",
    "regression detect": "regression_detection",
    "regressiondetection": "regression_detection",
    "regression-detection": "regression_detection",
    "regression detector": "regression_detection",
    "regression detector module": "regression_detection",
    "regression detection process": "regression_detection",
    "regression detection system": "regression_detection",
    "regression detection pipeline": "regression_detection",
    "regression detection queue": "regression_detection",
    "regression detection event": "regression_detection",
    "regression detection record": "regression_detection",
    "regression detection entry": "regression_detection",
    "regression detection submission": "regression_detection",
    "regression detection form": "regression_detection",
    "regression detection request": "regression_detection",
    "regression detection event": "regression_detection",
    "regression detection entry": "regression_detection",
    # Misspellings, abbreviations, acronyms, related terms
    "correkt": "correction_intake",
    "corection": "correction_intake",
    "corretion": "correction_intake",
    "correc": "correction_intake",
    "crt intake": "correction_intake",
    "crt": "correction_intake",
    "crt submission": "correction_intake",
    "crt queue": "correction_intake",
    "crt form": "correction_intake",
    "crt event": "correction_intake",
    "crt record": "correction_intake",
    "crt entry": "correction_intake",
    "crt request": "correction_intake",
    "crt module": "correction_intake",
    "crt pipeline": "correction_intake",
    "crt system": "correction_intake",
    "crt process": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    "crt submission": "correction_intake",
    "crt event": "correction_intake",
    "crt entry": "correction_intake",
    # Add more misspellings, abbreviations, acronyms, and related terms for all domains as needed...
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    m = hashlib.sha256()
    for k, v in items:
        m.update(k.encode("utf-8"))
        m.update(b":")
        m.update(v.encode("utf-8"))
        m.update(b";")
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    current_hash = _compute_map_hash()
    is_valid = (current_hash == _MAP_INTEGRITY_HASH) and (len(SEMANTIC_MAP) == _EXPECTED_ENTRY_COUNT)
    return {
        "status": "ok" if is_valid else "corrupt",
        "entries": len(SEMANTIC_MAP),
        "hash": current_hash,
        "is_valid": is_valid,
    }

def _normalize_string(term):
    if not isinstance(term, str):
        return ""
    term = term.lower()
    term = re.sub(r"[_\-\.]", " ", term)
    term = re.sub(r"\s+", " ", term)
    term = term.strip()
    return term

def normalize_term(term):
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term):
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings():
    return dict(SEMANTIC_MAP)