import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENRG02 Team"
SEMANTIC_MAP_ENGINE = "ENRG02_solar_energy"

SEMANTIC_MAP = {
    # Photovoltaic Cell Physics - p-n Junction Operation
    "pn junction": "p-n junction",
    "p n junction": "p-n junction",
    "p-n junction": "p-n junction",
    "pn-junction": "p-n junction",
    "junction diode": "p-n junction",
    "semiconductor junction": "p-n junction",
    "pn diode": "p-n junction",
    "p-n diode": "p-n junction",
    "electron hole recombination": "recombination",
    "carrier recombination": "recombination",
    "recombination": "recombination",
    "depletion region": "depletion region",
    "space charge region": "depletion region",
    "built-in potential": "built-in potential",
    "built in potential": "built-in potential",
    "diffusion current": "diffusion current",
    "drift current": "drift current",
    "minority carrier": "minority carrier",
    "majority carrier": "majority carrier",
    "photo-generated carrier": "photo-generated carrier",
    "photogenerated carrier": "photo-generated carrier",
    "carrier lifetime": "carrier lifetime",
    "carrier mobility": "carrier mobility",
    "bandgap": "bandgap",
    "band gap": "bandgap",
    "energy gap": "bandgap",
    "forbidden gap": "bandgap",
    "intrinsic semiconductor": "intrinsic semiconductor",
    "extrinsic semiconductor": "extrinsic semiconductor",
    "doping": "doping",
    "dopant": "doping",
    "acceptor": "acceptor",
    "donor": "donor",
    "n-type": "n-type",
    "n type": "n-type",
    "p-type": "p-type",
    "p type": "p-type",
    "electron": "electron",
    "hole": "hole",
    "charge carrier": "charge carrier",
    "solar cell physics": "photovoltaic cell physics",
    "pv cell physics": "photovoltaic cell physics",
    "photovoltaic cell physics": "photovoltaic cell physics",

    # Monocrystalline vs Polycrystalline Silicon Technology
    "monocrystalline silicon": "monocrystalline silicon",
    "mono silicon": "monocrystalline silicon",
    "mono-si": "monocrystalline silicon",
    "mono crystalline": "monocrystalline silicon",
    "single crystal silicon": "monocrystalline silicon",
    "monosilicon": "monocrystalline silicon",
    "monocrystal": "monocrystalline silicon",
    "polycrystalline silicon": "polycrystalline silicon",
    "poly silicon": "polycrystalline silicon",
    "poly-si": "polycrystalline silicon",
    "multi crystalline": "polycrystalline silicon",
    "multicrystalline silicon": "polycrystalline silicon",
    "polysilicon": "polycrystalline silicon",
    "polycrystal": "polycrystalline silicon",
    "cast silicon": "polycrystalline silicon",
    "silicon wafer": "silicon wafer",
    "wafer": "silicon wafer",
    "ingot": "silicon ingot",
    "silicon ingot": "silicon ingot",
    "cz process": "czochralski process",
    "czochralski process": "czochralski process",
    "float zone": "float zone process",
    "float zone process": "float zone process",
    "grain boundary": "grain boundary",
    "crystal defect": "crystal defect",

    # Thin-Film Technologies - CdTe and CIGS
    "thin film": "thin-film",
    "thin-film": "thin-film",
    "thinfilm": "thin-film",
    "thin film solar cell": "thin-film",
    "cdte": "cadmium telluride",
    "cadmium telluride": "cadmium telluride",
    "cdte cell": "cadmium telluride",
    "cdte module": "cadmium telluride",
    "cigs": "copper indium gallium selenide",
    "cigs cell": "copper indium gallium selenide",
    "cigs module": "copper indium gallium selenide",
    "copper indium gallium selenide": "copper indium gallium selenide",
    "amorphous silicon": "amorphous silicon",
    "a-si": "amorphous silicon",
    "a-si cell": "amorphous silicon",
    "a-si module": "amorphous silicon",
    "organic pv": "organic photovoltaic",
    "organic photovoltaic": "organic photovoltaic",
    "organic solar cell": "organic photovoltaic",
    "dye-sensitized": "dye-sensitized solar cell",
    "dssc": "dye-sensitized solar cell",
    "dye sensitized solar cell": "dye-sensitized solar cell",
    "dye solar cell": "dye-sensitized solar cell",
    "flexible solar cell": "flexible solar cell",
    "flexible pv": "flexible solar cell",
    "flexible module": "flexible solar cell",

    # Perovskite Solar Cells - Emerging Technology
    "perovskite": "perovskite solar cell",
    "perovskite cell": "perovskite solar cell",
    "perovskite module": "perovskite solar cell",
    "perovskite solar cell": "perovskite solar cell",
    "hybrid perovskite": "perovskite solar cell",
    "lead halide perovskite": "perovskite solar cell",
    "emerging pv": "emerging photovoltaic technology",
    "emerging photovoltaic": "emerging photovoltaic technology",
    "next gen pv": "emerging photovoltaic technology",
    "next generation pv": "emerging photovoltaic technology",
    "new pv tech": "emerging photovoltaic technology",

    # Solar Module Design - Cell Stringing and Bypass Diodes
    "solar module": "solar module",
    "pv module": "solar module",
    "module": "solar module",
    "panel": "solar module",
    "solar panel": "solar module",
    "pv panel": "solar module",
    "cell stringing": "cell stringing",
    "stringing": "cell stringing",
    "cell interconnection": "cell stringing",
    "series connection": "cell stringing",
    "parallel connection": "cell stringing",
    "bypass diode": "bypass diode",
    "bypass diodes": "bypass diode",
    "diode": "bypass diode",
    "blocking diode": "blocking diode",
    "junction box": "junction box",
    "module frame": "module frame",
    "encapsulation": "encapsulation",
    "lamination": "encapsulation",
    "glass": "front glass",
    "front glass": "front glass",
    "backsheet": "backsheet",
    "back sheet": "backsheet",
    "eva": "encapsulation",
    "ethylene vinyl acetate": "encapsulation",
    "tedlar": "backsheet",
    "ribbon": "interconnect ribbon",
    "interconnect ribbon": "interconnect ribbon",
    "busbar": "busbar",
    "bus bar": "busbar",
    "tabbing": "tabbing",
    "tabbing wire": "tabbing",
    "module efficiency": "module efficiency",
    "module power": "module power",
    "stc": "standard test conditions",
    "standard test conditions": "standard test conditions",
    "nominal operating cell temperature": "noct",
    "noct": "noct",
    "maximum power point": "maximum power point",
    "mpp": "maximum power point",

    # Inverter Technologies - String vs Micro vs Central
    "inverter": "inverter",
    "pv inverter": "inverter",
    "solar inverter": "inverter",
    "string inverter": "string inverter",
    "micro inverter": "micro inverter",
    "microinverter": "micro inverter",
    "central inverter": "central inverter",
    "power electronics": "power electronics",
    "dc-ac converter": "inverter",
    "dc to ac converter": "inverter",
    "ac inverter": "inverter",
    "dc inverter": "inverter",
    "dc/ac inverter": "inverter",
    "dc-ac inverter": "inverter",
    "dc-ac conversion": "inverter",
    "dc/ac conversion": "inverter",
    "inverter efficiency": "inverter efficiency",
    "inverter power": "inverter power",
    "inverter rating": "inverter rating",
    "inverter output": "inverter output",
    "inverter input": "inverter input",
    "inverter losses": "inverter losses",
    "inverter topology": "inverter topology",
    "multi string inverter": "string inverter",
    "multi-string inverter": "string inverter",
    "multi string": "string inverter",
    "multi-string": "string inverter",

    # MPPT Algorithms - Perturb and Observe vs Incremental Conductance
    "mppt": "maximum power point tracking",
    "maximum power point tracking": "maximum power point tracking",
    "mppt algorithm": "maximum power point tracking",
    "perturb and observe": "perturb and observe",
    "p&o": "perturb and observe",
    "po algorithm": "perturb and observe",
    "incremental conductance": "incremental conductance",
    "inc cond": "incremental conductance",
    "inc algorithm": "incremental conductance",
    "hill climbing": "perturb and observe",
    "mppt controller": "maximum power point tracking",
    "mppt tracking": "maximum power point tracking",
    "mppt efficiency": "maximum power point tracking efficiency",
    "tracking efficiency": "maximum power point tracking efficiency",

    # Solar Resource Assessment - GHI, DNI, DHI
    "solar resource": "solar resource assessment",
    "solar resource assessment": "solar resource assessment",
    "irradiance": "irradiance",
    "solar irradiance": "irradiance",
    "insolation": "irradiance",
    "ghi": "global horizontal irradiance",
    "global horizontal irradiance": "global horizontal irradiance",
    "dhi": "diffuse horizontal irradiance",
    "diffuse horizontal irradiance": "diffuse horizontal irradiance",
    "dni": "direct normal irradiance",
    "direct normal irradiance": "direct normal irradiance",
    "beam irradiance": "direct normal irradiance",
    "diffuse irradiance": "diffuse horizontal irradiance",
    "solar radiation": "irradiance",
    "solar flux": "irradiance",
    "sunlight": "irradiance",
    "solar spectrum": "solar spectrum",
    "spectral response": "spectral response",
    "albedo": "albedo",
    "ground reflectance": "albedo",
    "reflectance": "albedo",
    "cloud cover": "cloud cover",
    "weather data": "weather data",
    "meteorological data": "weather data",
    "solar map": "solar resource assessment",
    "resource map": "solar resource assessment",
    "pvgis": "solar resource assessment",
    "solargis": "solar resource assessment",
    "nrel": "solar resource assessment",
    "nsrdb": "solar resource assessment",
    "solar atlas": "solar resource assessment",

    # PV System Sizing Methodology - DC-to-AC Ratio
    "pv system sizing": "pv system sizing",
    "system sizing": "pv system sizing",
    "sizing": "pv system sizing",
    "dc-ac ratio": "dc-ac ratio",
    "dc to ac ratio": "dc-ac ratio",
    "dc/ac ratio": "dc-ac ratio",
    "oversizing": "dc-ac ratio",
    "undersizing": "dc-ac ratio",
    "dc rating": "dc rating",
    "ac rating": "ac rating",
    "system rating": "system rating",
    "system capacity": "system capacity",
    "pv capacity": "system capacity",
    "solar capacity": "system capacity",
    "array size": "array size",
    "array rating": "array size",
    "module count": "module count",
    "string count": "string count",
    "inverter count": "inverter count",
    "system design": "system design",
    "design methodology": "system design",
    "design criteria": "system design",

    # Fixed-Tilt vs Single-Axis Tracker Systems
    "fixed tilt": "fixed-tilt",
    "fixed-tilt": "fixed-tilt",
    "fixed mount": "fixed-tilt",
    "fixed installation": "fixed-tilt",
    "tilt angle": "tilt angle",
    "tilt": "tilt angle",
    "tracker": "single-axis tracker",
    "single axis tracker": "single-axis tracker",
    "single-axis tracker": "single-axis tracker",
    "single axis": "single-axis tracker",
    "tracking system": "single-axis tracker",
    "dual axis tracker": "dual-axis tracker",
    "dual-axis tracker": "dual-axis tracker",
    "dual axis": "dual-axis tracker",
    "tracking": "single-axis tracker",
    "azimuth": "azimuth",
    "azimuth angle": "azimuth",
    "orientation": "azimuth",
    "mounting": "mounting",
    "mounting structure": "mounting",
    "rack": "mounting",
    "racking": "mounting",
    "ground mount": "ground mount",
    "roof mount": "roof mount",
    "pole mount": "pole mount",
    "ballasted mount": "ballasted mount",
    "fixed ground mount": "fixed-tilt",
    "fixed roof mount": "fixed-tilt",

    # Concentrated Solar Power - Parabolic Trough vs Power Tower
    "csp": "concentrated solar power",
    "concentrated solar power": "concentrated solar power",
    "concentrating solar power": "concentrated solar power",
    "concentrated solar": "concentrated solar power",
    "parabolic trough": "parabolic trough",
    "trough": "parabolic trough",
    "parabolic collector": "parabolic trough",
    "power tower": "power tower",
    "solar tower": "power tower",
    "central receiver": "power tower",
    "heliostat": "heliostat",
    "dish": "solar dish",
    "solar dish": "solar dish",
    "dish stirling": "solar dish",
    "stirling engine": "stirling engine",
    "thermal storage": "thermal storage",
    "molten salt": "molten salt",
    "heat transfer fluid": "heat transfer fluid",
    "htf": "heat transfer fluid",
    "receiver": "receiver",
    "collector": "collector",
    "solar collector": "collector",

    # Battery Storage Integration - Lithium-Ion vs Flow Batteries
    "battery": "battery",
    "battery storage": "battery storage",
    "energy storage": "battery storage",
    "storage": "battery storage",
    "solar storage": "battery storage",
    "pv storage": "battery storage",
    "lithium ion": "lithium-ion",
    "li-ion": "lithium-ion",
    "lithium-ion": "lithium-ion",
    "li ion": "lithium-ion",
    "li ion battery": "lithium-ion",
    "lithium battery": "lithium-ion",
    "flow battery": "flow battery",
    "redox flow battery": "flow battery",
    "vanadium battery": "flow battery",
    "vanadium redox battery": "flow battery",
    "lead acid": "lead-acid",
    "lead-acid": "lead-acid",
    "lead acid battery": "lead-acid",
    "agm battery": "lead-acid",
    "gel battery": "lead-acid",
    "nickel cadmium": "nickel-cadmium",
    "ni-cd": "nickel-cadmium",
    "nickel-cadmium": "nickel-cadmium",
    "ni cd battery": "nickel-cadmium",
    "battery bank": "battery bank",
    "battery array": "battery bank",
    "battery inverter": "battery inverter",
    "hybrid inverter": "hybrid inverter",
    "storage inverter": "battery inverter",
    "battery management system": "battery management system",
    "bms": "battery management system",
    "state of charge": "state of charge",
    "soc": "state of charge",
    "depth of discharge": "depth of discharge",
    "dod": "depth of discharge",
    "cycle life": "cycle life",
    "battery life": "cycle life",
    "round trip efficiency": "round-trip efficiency",
    "round-trip efficiency": "round-trip efficiency",

    # Grid-Tied vs Off-Grid System Design
    "grid tied": "grid-tied",
    "grid-tied": "grid-tied",
    "grid connected": "grid-tied",
    "grid connection": "grid-tied",
    "on grid": "grid-tied",
    "on-grid": "grid-tied",
    "off grid": "off-grid",
    "off-grid": "off-grid",
    "standalone": "off-grid",
    "stand-alone": "off-grid",
    "islanded": "off-grid",
    "microgrid": "microgrid",
    "micro grid": "microgrid",
    "hybrid system": "hybrid system",
    "hybrid pv": "hybrid system",
    "hybrid solar": "hybrid system",
    "grid": "grid",
    "utility": "grid",
    "utility grid": "grid",
    "grid integration": "grid integration",
    "grid interface": "grid integration",
    "grid code": "grid code",
    "interconnection": "interconnection",
    "interconnection agreement": "interconnection",
    "net metering": "net metering",
    "feed-in tariff": "feed-in tariff",
    "fit": "feed-in tariff",
    "power purchase agreement": "ppa",
    "ppa": "ppa",
    "ppa contract": "ppa",

    # PV System Losses - Soiling, Shading, Mismatch, Temperature
    "pv losses": "pv system losses",
    "system losses": "pv system losses",
    "losses": "pv system losses",
    "soiling": "soiling",
    "dirt": "soiling",
    "dust": "soiling",
    "shading": "shading",
    "shadow": "shading",
    "partial shading": "shading",
    "mismatch": "mismatch",
    "module mismatch": "mismatch",
    "string mismatch": "mismatch",
    "temperature loss": "temperature loss",
    "temperature losses": "temperature loss",
    "temperature coefficient": "temperature coefficient",
    "temp coefficient": "temperature coefficient",
    "temp loss": "temperature loss",
    "irradiance loss": "irradiance loss",
    "wiring loss": "wiring loss",
    "wire loss": "wiring loss",
    "connection loss": "wiring loss",
    "resistive loss": "wiring loss",
    "ac loss": "ac loss",
    "dc loss": "dc loss",
    "conversion loss": "conversion loss",
    "inverter loss": "inverter losses",
    "module degradation": "module degradation",
    "degradation": "module degradation",
    "aging": "module degradation",
    "performance ratio": "performance ratio",
    "pr": "performance ratio",

    # NEC Article 690 - Code Compliance
    "nec": "nec article 690",
    "nec 690": "nec article 690",
    "article 690": "nec article 690",
    "code compliance": "code compliance",
    "electrical code": "code compliance",
    "national electrical code": "nec article 690",
    "us electrical code": "nec article 690",
    "safety": "safety",
    "grounding": "grounding",
    "earthing": "grounding",
    "bonding": "bonding",
    "arc fault": "arc fault",
    "arc-fault": "arc fault",
    "arc fault protection": "arc fault",
    "afci": "arc fault",
    "rapid shutdown": "rapid shutdown",
    "shutdown": "rapid shutdown",
    "disconnect": "disconnect",
    "disconnect switch": "disconnect",
    "combiner box": "combiner box",
    "overcurrent protection": "overcurrent protection",
    "ocpd": "overcurrent protection",
    "fuse": "overcurrent protection",
    "breaker": "overcurrent protection",
    "circuit breaker": "overcurrent protection",
    "surge protection": "surge protection",
    "spd": "surge protection",
    "surge protective device": "surge protection",
    "fire safety": "fire safety",
    "fire code": "fire safety",
    "labeling": "labeling",
    "system labeling": "labeling",
    "conduit": "conduit",
    "raceway": "conduit",
    "wire management": "wire management",
    "cable management": "wire management",

    # Bifacial Modules and Albedo
    "bifacial": "bifacial module",
    "bifacial module": "bifacial module",
    "bifacial panel": "bifacial module",
    "bifacial pv": "bifacial module",
    "bifacial cell": "bifacial module",
    "albedo effect": "albedo",
    "ground albedo": "albedo",
    "rear side": "rear side",
    "rear side irradiance": "rear side",
    "rear irradiance": "rear side",
    "backside": "rear side",
    "back side": "rear side",
    "bifacial gain": "bifacial gain",
    "bifaciality": "bifacial gain",
    "bifacial performance": "bifacial gain",

    # Agrivoltaics - Dual Use of Land
    "agrivoltaics": "agrivoltaics",
    "agri voltaics": "agrivoltaics",
    "agrovoltaics": "agrivoltaics",
    "agri pv": "agrivoltaics",
    "agri-photovoltaics": "agrivoltaics",
    "dual use": "dual use of land",
    "dual use of land": "dual use of land",
    "co-location": "dual use of land",
    "co-location of pv and crops": "dual use of land",
    "pv and agriculture": "dual use of land",
    "solar farming": "dual use of land",
    "solar farm": "solar farm",
    "pv farm": "solar farm",
    "solar ranch": "solar farm",
    "pv ranch": "solar farm",
    "crop shading": "crop shading",
    "crop yield": "crop yield",
    "land use": "land use",
    "land utilization": "land use",
    "land optimization": "land use",

    # Floating Solar (Floatovoltaics)
    "floating solar": "floating solar",
    "floatovoltaics": "floating solar",
    "floatovoltaic": "floating solar",
    "floating pv": "floating solar",
    "floating module": "floating solar",
    "water solar": "floating solar",
    "water pv": "floating solar",
    "reservoir solar": "floating solar",
    "lake solar": "floating solar",
    "pond solar": "floating solar",
    "floating array": "floating solar",
    "floating structure": "floating solar",
    "buoyancy": "buoyancy",
    "anchoring": "anchoring",
    "anchor": "anchoring",
    "mooring": "anchoring",

    # Solar + Storage Economics - ITC and PTC
    "solar economics": "solar economics",
    "pv economics": "solar economics",
    "solar finance": "solar economics",
    "pv finance": "solar economics",
    "solar + storage": "solar plus storage",
    "solar plus storage": "solar plus storage",
    "pv + storage": "solar plus storage",
    "pv plus storage": "solar plus storage",
    "itc": "investment tax credit",
    "investment tax credit": "investment tax credit",
    "ptc": "production tax credit",
    "production tax credit": "production tax credit",
    "tax credit": "investment tax credit",
    "incentive": "incentive",
    "subsidy": "incentive",
    "rebate": "incentive",
    "financial incentive": "incentive",
    "lcoe": "levelized cost of energy",
    "levelized cost of energy": "levelized cost of energy",
    "cost of energy": "levelized cost of energy",
    "capex": "capital expenditure",
    "capital expenditure": "capital expenditure",
    "opex": "operational expenditure",
    "operational expenditure": "operational expenditure",
    "payback": "payback period",
    "payback period": "payback period",
    "roi": "return on investment",
    "return on investment": "return on investment",
    "npv": "net present value",
    "net present value": "net present value",
    "irr": "internal rate of return",
    "internal rate of return": "internal rate of return",
    "financial model": "financial model",
    "cash flow": "cash flow",

    # Solar Thermal Systems - Flat Plate vs Evacuated Tube
    "solar thermal": "solar thermal",
    "solar thermal system": "solar thermal",
    "thermal solar": "solar thermal",
    "flat plate collector": "flat plate collector",
    "flat plate": "flat plate collector",
    "evacuated tube collector": "evacuated tube collector",
    "evacuated tube": "evacuated tube collector",
    "et collector": "evacuated tube collector",
    "et module": "evacuated tube collector",
    "hot water": "solar hot water",
    "solar hot water": "solar hot water",
    "solar water heater": "solar hot water",
    "water heating": "solar hot water",
    "thermal storage tank": "thermal storage tank",
    "storage tank": "thermal storage tank",
    "heat exchanger": "heat exchanger",
    "thermal exchanger": "heat exchanger",
    "glycol loop": "glycol loop",
    "glycol": "glycol loop",
    "circulation pump": "circulation pump",
    "pump": "circulation pump",
    "thermal insulation": "thermal insulation",
    "insulation": "thermal insulation",
    "collector efficiency": "collector efficiency",
    "thermal efficiency": "collector efficiency",
    "collector area": "collector area",
    "thermal area": "collector area",
    "solar heating": "solar hot water",
    "space heating": "space heating",
    "solar space heating": "space heating",
    "thermal loss": "thermal loss",
    "thermal losses": "thermal loss",
    "heat loss": "thermal loss",
    "thermal conductivity": "thermal conductivity",
    "conductivity": "thermal conductivity",
    "thermal gradient": "thermal gradient",
    "gradient": "thermal gradient",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}|{SEMANTIC_MAP_AUTHOR}|{SEMANTIC_MAP_ENGINE}|{_EXPECTED_ENTRY_COUNT}"
    data = meta + "|" + joined
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def normalize_term(term: str) -> str:
    t = term.lower().strip()
    t = re.sub(r"[\s\-_/]+", " ", t)
    t = t.replace("  ", " ")
    t = t.strip()
    # Try direct match
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try removing spaces
    t_nospaces = t.replace(" ", "")
    if t_nospaces in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_nospaces]
    # Try hyphenated form
    t_hyphen = t.replace(" ", "-")
    if t_hyphen in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_hyphen]
    # Try underscore form
    t_underscore = t.replace(" ", "_")
    if t_underscore in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_underscore]
    # Try plural form
    if t.endswith("s") and t[:-1] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-1]]
    # Try singular form
    if not t.endswith("s") and (t + "s") in SEMANTIC_MAP:
        return SEMANTIC_MAP[t + "s"]
    # Try removing hyphens
    t_nohyphen = t.replace("-", "")
    if t_nohyphen in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_nohyphen]
    # Try removing underscores
    t_nounderscore = t.replace("_", "")
    if t_nounderscore in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_nounderscore]
    # Try capitalized
    t_cap = t.capitalize()
    if t_cap in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_cap]
    # Try all upper
    t_upper = t.upper()
    if t_upper in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_upper]
    # Try all lower
    t_lower = t.lower()
    if t_lower in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_lower]
    return t

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == normalized and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)