import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "REG07_engine_team"
SEMANTIC_MAP_ENGINE = "REG07_energy_regulatory"

SEMANTIC_MAP = {
    # FERC Jurisdiction Over Interstate Transmission
    "ferc jurisdiction": "ferc_jurisdiction_interstate_transmission",
    "ferc jurisdiction over transmission": "ferc_jurisdiction_interstate_transmission",
    "ferc jurisdiction over interstate transmission": "ferc_jurisdiction_interstate_transmission",
    "ferc interstate transmission": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission authority": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission regulation": "ferc_jurisdiction_interstate_transmission",
    "interstate transmission regulation": "ferc_jurisdiction_interstate_transmission",
    "interstate transmission": "ferc_jurisdiction_interstate_transmission",
    "interstate transmission lines": "ferc_jurisdiction_interstate_transmission",
    "interstate transmission facilities": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission jurisdiction": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission oversight": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission control": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission rules": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission standards": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission compliance": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission tariffs": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission rates": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission filings": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission orders": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission jurisdictional": "ferc_jurisdiction_interstate_transmission",
    "ferc regulated transmission": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission regulation": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission policy": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission service": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission access": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission open access": "ferc_jurisdiction_interstate_transmission",
    "ferc transmission interconnection": "ferc_jurisdiction_interstate_transmission",

    # NERC CIP Critical Infrastructure Protection Standards
    "nerc cip": "nerc_cip_critical_infrastructure_protection",
    "cip": "nerc_cip_critical_infrastructure_protection",
    "nerc critical infrastructure protection": "nerc_cip_critical_infrastructure_protection",
    "critical infrastructure protection": "nerc_cip_critical_infrastructure_protection",
    "cip standards": "nerc_cip_critical_infrastructure_protection",
    "nerc cip standards": "nerc_cip_critical_infrastructure_protection",
    "cip compliance": "nerc_cip_critical_infrastructure_protection",
    "nerc cip compliance": "nerc_cip_critical_infrastructure_protection",
    "cip requirements": "nerc_cip_critical_infrastructure_protection",
    "nerc cip requirements": "nerc_cip_critical_infrastructure_protection",
    "cip cyber security": "nerc_cip_critical_infrastructure_protection",
    "nerc cip cyber security": "nerc_cip_critical_infrastructure_protection",
    "cip physical security": "nerc_cip_critical_infrastructure_protection",
    "nerc cip physical security": "nerc_cip_critical_infrastructure_protection",
    "cip-002": "nerc_cip_critical_infrastructure_protection",
    "cip-003": "nerc_cip_critical_infrastructure_protection",
    "cip-004": "nerc_cip_critical_infrastructure_protection",
    "cip-005": "nerc_cip_critical_infrastructure_protection",
    "cip-006": "nerc_cip_critical_infrastructure_protection",
    "cip-007": "nerc_cip_critical_infrastructure_protection",
    "cip-008": "nerc_cip_critical_infrastructure_protection",
    "cip-009": "nerc_cip_critical_infrastructure_protection",
    "cip-010": "nerc_cip_critical_infrastructure_protection",
    "cip-011": "nerc_cip_critical_infrastructure_protection",
    "cip-012": "nerc_cip_critical_infrastructure_protection",
    "cip standards list": "nerc_cip_critical_infrastructure_protection",
    "nerc cip standards list": "nerc_cip_critical_infrastructure_protection",
    "cip audit": "nerc_cip_critical_infrastructure_protection",
    "cip enforcement": "nerc_cip_critical_infrastructure_protection",
    "cip violation": "nerc_cip_critical_infrastructure_protection",
    "cip penalty": "nerc_cip_critical_infrastructure_protection",
    "cip reporting": "nerc_cip_critical_infrastructure_protection",
    "cip self-report": "nerc_cip_critical_infrastructure_protection",
    "cip mitigation": "nerc_cip_critical_infrastructure_protection",

    # ERCOT Nodal Market Protocols and Settlement
    "ercot nodal market": "ercot_nodal_market_protocols_settlement",
    "ercot nodal protocols": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market protocols": "ercot_nodal_market_protocols_settlement",
    "nodal market protocols": "ercot_nodal_market_protocols_settlement",
    "ercot settlement": "ercot_nodal_market_protocols_settlement",
    "ercot market settlement": "ercot_nodal_market_protocols_settlement",
    "nodal market settlement": "ercot_nodal_market_protocols_settlement",
    "ercot protocols": "ercot_nodal_market_protocols_settlement",
    "ercot nodal": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market rules": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market design": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market operations": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market clearing": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market pricing": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market participants": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market registration": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market compliance": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market settlement system": "ercot_nodal_market_protocols_settlement",
    "nodal protocols": "ercot_nodal_market_protocols_settlement",
    "nodal settlement": "ercot_nodal_market_protocols_settlement",
    "nodal market": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market handbook": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market guide": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market manual": "ercot_nodal_market_protocols_settlement",
    "ercot nodal market documents": "ercot_nodal_market_protocols_settlement",

    # FERC Market-Based Rate Authority and Mitigation
    "ferc market based rate": "ferc_market_based_rate_authority_mitigation",
    "ferc market-based rate": "ferc_market_based_rate_authority_mitigation",
    "market based rate": "ferc_market_based_rate_authority_mitigation",
    "market-based rate": "ferc_market_based_rate_authority_mitigation",
    "mbr": "ferc_market_based_rate_authority_mitigation",
    "ferc mbr": "ferc_market_based_rate_authority_mitigation",
    "market based rate authority": "ferc_market_based_rate_authority_mitigation",
    "market-based rate authority": "ferc_market_based_rate_authority_mitigation",
    "market based rate mitigation": "ferc_market_based_rate_authority_mitigation",
    "market-based rate mitigation": "ferc_market_based_rate_authority_mitigation",
    "ferc market based rate mitigation": "ferc_market_based_rate_authority_mitigation",
    "ferc market-based rate mitigation": "ferc_market_based_rate_authority_mitigation",
    "market based rate filing": "ferc_market_based_rate_authority_mitigation",
    "market-based rate filing": "ferc_market_based_rate_authority_mitigation",
    "mbr authority": "ferc_market_based_rate_authority_mitigation",
    "mbr mitigation": "ferc_market_based_rate_authority_mitigation",
    "mbr compliance": "ferc_market_based_rate_authority_mitigation",
    "mbr reporting": "ferc_market_based_rate_authority_mitigation",
    "mbr application": "ferc_market_based_rate_authority_mitigation",
    "mbr order": "ferc_market_based_rate_authority_mitigation",
    "mbr tariff": "ferc_market_based_rate_authority_mitigation",
    "mbr rules": "ferc_market_based_rate_authority_mitigation",
    "mbr standards": "ferc_market_based_rate_authority_mitigation",

    # FERC Section 205 Rate Filing Requirements
    "ferc section 205": "ferc_section_205_rate_filing_requirements",
    "section 205": "ferc_section_205_rate_filing_requirements",
    "ferc 205": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing requirements": "ferc_section_205_rate_filing_requirements",
    "ferc section 205 filing": "ferc_section_205_rate_filing_requirements",
    "section 205 filing": "ferc_section_205_rate_filing_requirements",
    "section 205 rate filing": "ferc_section_205_rate_filing_requirements",
    "section 205 requirements": "ferc_section_205_rate_filing_requirements",
    "ferc 205 filing": "ferc_section_205_rate_filing_requirements",
    "ferc 205 requirements": "ferc_section_205_rate_filing_requirements",
    "ferc 205 rate filing": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing process": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing procedure": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing compliance": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing order": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing approval": "ferc_section_205_rate_filing_requirements",
    "ferc rate filing review": "ferc_section_205_rate_filing_requirements",

    # Natural Gas Pipeline Certificate Authority Under NGA Section 7
    "nga section 7": "nga_section_7_pipeline_certificate_authority",
    "natural gas pipeline certificate": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate authority": "nga_section_7_pipeline_certificate_authority",
    "nga pipeline certificate": "nga_section_7_pipeline_certificate_authority",
    "nga section 7 certificate": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate filing": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate application": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate process": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate requirements": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate review": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate approval": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate compliance": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate order": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate issuance": "nga_section_7_pipeline_certificate_authority",
    "pipeline certificate grant": "nga_section_7_pipeline_certificate_authority",
    "nga section 7 authority": "nga_section_7_pipeline_certificate_authority",
    "nga section 7 pipeline": "nga_section_7_pipeline_certificate_authority",
    "nga section 7 certificate authority": "nga_section_7_pipeline_certificate_authority",

    # Pipeline Safety Regulations 49 CFR 192 and 195
    "pipeline safety": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety regulations": "pipeline_safety_regulations_49_cfr_192_195",
    "49 cfr 192": "pipeline_safety_regulations_49_cfr_192_195",
    "49 cfr 195": "pipeline_safety_regulations_49_cfr_192_195",
    "cfr 192": "pipeline_safety_regulations_49_cfr_192_195",
    "cfr 195": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety compliance": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety standards": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety rules": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety audit": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety enforcement": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety violation": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety penalty": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety reporting": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety self-report": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety mitigation": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety order": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety review": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety approval": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety process": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety requirements": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety compliance audit": "pipeline_safety_regulations_49_cfr_192_195",
    "pipeline safety compliance review": "pipeline_safety_regulations_49_cfr_192_195",

    # PUCT Ratemaking for Texas Electric Utilities
    "puct ratemaking": "puct_ratemaking_texas_electric_utilities",
    "texas ratemaking": "puct_ratemaking_texas_electric_utilities",
    "texas electric ratemaking": "puct_ratemaking_texas_electric_utilities",
    "puct ratemaking for electric utilities": "puct_ratemaking_texas_electric_utilities",
    "puct ratemaking for texas electric utilities": "puct_ratemaking_texas_electric_utilities",
    "puct rate case": "puct_ratemaking_texas_electric_utilities",
    "puct rate filing": "puct_ratemaking_texas_electric_utilities",
    "puct rate review": "puct_ratemaking_texas_electric_utilities",
    "puct rate approval": "puct_ratemaking_texas_electric_utilities",
    "puct rate process": "puct_ratemaking_texas_electric_utilities",
    "puct rate requirements": "puct_ratemaking_texas_electric_utilities",
    "puct rate compliance": "puct_ratemaking_texas_electric_utilities",
    "puct rate audit": "puct_ratemaking_texas_electric_utilities",
    "puct rate enforcement": "puct_ratemaking_texas_electric_utilities",
    "puct rate violation": "puct_ratemaking_texas_electric_utilities",
    "puct rate penalty": "puct_ratemaking_texas_electric_utilities",
    "puct rate reporting": "puct_ratemaking_texas_electric_utilities",
    "puct rate self-report": "puct_ratemaking_texas_electric_utilities",
    "puct rate mitigation": "puct_ratemaking_texas_electric_utilities",
    "puct rate order": "puct_ratemaking_texas_electric_utilities",
    "texas electric utilities ratemaking": "puct_ratemaking_texas_electric_utilities",
    "texas utilities ratemaking": "puct_ratemaking_texas_electric_utilities",
    "texas ratemaking process": "puct_ratemaking_texas_electric_utilities",

    # Renewable Portfolio Standards and REC Compliance
    "renewable portfolio standard": "renewable_portfolio_standards_rec_compliance",
    "renewable portfolio standards": "renewable_portfolio_standards_rec_compliance",
    "rps": "renewable_portfolio_standards_rec_compliance",
    "rec": "renewable_portfolio_standards_rec_compliance",
    "renewable energy certificate": "renewable_portfolio_standards_rec_compliance",
    "renewable energy certificates": "renewable_portfolio_standards_rec_compliance",
    "rec compliance": "renewable_portfolio_standards_rec_compliance",
    "rps compliance": "renewable_portfolio_standards_rec_compliance",
    "rps requirements": "renewable_portfolio_standards_rec_compliance",
    "rec requirements": "renewable_portfolio_standards_rec_compliance",
    "rps audit": "renewable_portfolio_standards_rec_compliance",
    "rec audit": "renewable_portfolio_standards_rec_compliance",
    "rps enforcement": "renewable_portfolio_standards_rec_compliance",
    "rec enforcement": "renewable_portfolio_standards_rec_compliance",
    "rps violation": "renewable_portfolio_standards_rec_compliance",
    "rec violation": "renewable_portfolio_standards_rec_compliance",
    "rps penalty": "renewable_portfolio_standards_rec_compliance",
    "rec penalty": "renewable_portfolio_standards_rec_compliance",
    "rps reporting": "renewable_portfolio_standards_rec_compliance",
    "rec reporting": "renewable_portfolio_standards_rec_compliance",
    "rps self-report": "renewable_portfolio_standards_rec_compliance",
    "rec self-report": "renewable_portfolio_standards_rec_compliance",
    "rps mitigation": "renewable_portfolio_standards_rec_compliance",
    "rec mitigation": "renewable_portfolio_standards_rec_compliance",
    "rps order": "renewable_portfolio_standards_rec_compliance",
    "rec order": "renewable_portfolio_standards_rec_compliance",
    "rps compliance audit": "renewable_portfolio_standards_rec_compliance",
    "rec compliance audit": "renewable_portfolio_standards_rec_compliance",
    "rps compliance review": "renewable_portfolio_standards_rec_compliance",
    "rec compliance review": "renewable_portfolio_standards_rec_compliance",

    # FERC Anti-Manipulation Rule and Market Behavior
    "ferc anti manipulation": "ferc_anti_manipulation_rule_market_behavior",
    "ferc anti-manipulation": "ferc_anti_manipulation_rule_market_behavior",
    "ferc anti manipulation rule": "ferc_anti_manipulation_rule_market_behavior",
    "ferc anti-manipulation rule": "ferc_anti_manipulation_rule_market_behavior",
    "anti manipulation rule": "ferc_anti_manipulation_rule_market_behavior",
    "anti-manipulation rule": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation": "ferc_anti_manipulation_rule_market_behavior",
    "market behavior": "ferc_anti_manipulation_rule_market_behavior",
    "ferc market behavior": "ferc_anti_manipulation_rule_market_behavior",
    "ferc market manipulation": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation rule": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation compliance": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation enforcement": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation penalty": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation violation": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation reporting": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation audit": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation self-report": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation mitigation": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation order": "ferc_anti_manipulation_rule_market_behavior",
    "market manipulation review": "ferc_anti_manipulation_rule_market_behavior",

    # Large Generator Interconnection Process
    "large generator interconnection": "large_generator_interconnection_process",
    "generator interconnection": "large_generator_interconnection_process",
    "large generator interconnection process": "large_generator_interconnection_process",
    "generator interconnection process": "large_generator_interconnection_process",
    "generator interconnection application": "large_generator_interconnection_process",
    "generator interconnection filing": "large_generator_interconnection_process",
    "generator interconnection requirements": "large_generator_interconnection_process",
    "generator interconnection review": "large_generator_interconnection_process",
    "generator interconnection approval": "large_generator_interconnection_process",
    "generator interconnection compliance": "large_generator_interconnection_process",
    "generator interconnection audit": "large_generator_interconnection_process",
    "generator interconnection enforcement": "large_generator_interconnection_process",
    "generator interconnection violation": "large_generator_interconnection_process",
    "generator interconnection penalty": "large_generator_interconnection_process",
    "generator interconnection reporting": "large_generator_interconnection_process",
    "generator interconnection self-report": "large_generator_interconnection_process",
    "generator interconnection mitigation": "large_generator_interconnection_process",
    "generator interconnection order": "large_generator_interconnection_process",
    "generator interconnection standards": "large_generator_interconnection_process",
    "generator interconnection rules": "large_generator_interconnection_process",
    "generator interconnection study": "large_generator_interconnection_process",
    "generator interconnection queue": "large_generator_interconnection_process",
    "generator interconnection agreement": "large_generator_interconnection_process",

    # FERC Reliability Coordinator and Balancing Authority Registration
    "ferc reliability coordinator": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority": "ferc_reliability_coordinator_balancing_authority_registration",
    "ferc balancing authority": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator registration": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority registration": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator compliance": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority compliance": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator audit": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority audit": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator enforcement": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority enforcement": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator violation": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority violation": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator penalty": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority penalty": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator reporting": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority reporting": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator self-report": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority self-report": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator mitigation": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority mitigation": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator order": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority order": "ferc_reliability_coordinator_balancing_authority_registration",
    "reliability coordinator registration process": "ferc_reliability_coordinator_balancing_authority_registration",
    "balancing authority registration process": "ferc_reliability_coordinator_balancing_authority_registration",

    # Texas Transmission Cost Recovery Factor (TCCRF)
    "tccrf": "texas_transmission_cost_recovery_factor",
    "texas transmission cost recovery factor": "texas_transmission_cost_recovery_factor",
    "transmission cost recovery factor": "texas_transmission_cost_recovery_factor",
    "tccrf filing": "texas_transmission_cost_recovery_factor",
    "tccrf application": "texas_transmission_cost_recovery_factor",
    "tccrf process": "texas_transmission_cost_recovery_factor",
    "tccrf requirements": "texas_transmission_cost_recovery_factor",
    "tccrf compliance": "texas_transmission_cost_recovery_factor",
    "tccrf audit": "texas_transmission_cost_recovery_factor",
    "tccrf enforcement": "texas_transmission_cost_recovery_factor",
    "tccrf violation": "texas_transmission_cost_recovery_factor",
    "tccrf penalty": "texas_transmission_cost_recovery_factor",
    "tccrf reporting": "texas_transmission_cost_recovery_factor",
    "tccrf self-report": "texas_transmission_cost_recovery_factor",
    "tccrf mitigation": "texas_transmission_cost_recovery_factor",
    "tccrf order": "texas_transmission_cost_recovery_factor",
    "tccrf review": "texas_transmission_cost_recovery_factor",
    "tccrf approval": "texas_transmission_cost_recovery_factor",

    # FERC Demand Response Compensation Order 745
    "ferc order 745": "ferc_demand_response_compensation_order_745",
    "order 745": "ferc_demand_response_compensation_order_745",
    "demand response compensation": "ferc_demand_response_compensation_order_745",
    "ferc demand response compensation": "ferc_demand_response_compensation_order_745",
    "demand response compensation order": "ferc_demand_response_compensation_order_745",
    "ferc demand response": "ferc_demand_response_compensation_order_745",
    "demand response": "ferc_demand_response_compensation_order_745",
    "demand response order": "ferc_demand_response_compensation_order_745",
    "demand response compliance": "ferc_demand_response_compensation_order_745",
    "demand response audit": "ferc_demand_response_compensation_order_745",
    "demand response enforcement": "ferc_demand_response_compensation_order_745",
    "demand response violation": "ferc_demand_response_compensation_order_745",
    "demand response penalty": "ferc_demand_response_compensation_order_745",
    "demand response reporting": "ferc_demand_response_compensation_order_745",
    "demand response self-report": "ferc_demand_response_compensation_order_745",
    "demand response mitigation": "ferc_demand_response_compensation_order_745",
    "demand response order 745": "ferc_demand_response_compensation_order_745",

    # Environmental Compliance for Generation Facilities
    "environmental compliance": "environmental_compliance_generation_facilities",
    "generation facilities environmental compliance": "environmental_compliance_generation_facilities",
    "generation facility environmental compliance": "environmental_compliance_generation_facilities",
    "environmental compliance for generation facilities": "environmental_compliance_generation_facilities",
    "generation facility compliance": "environmental_compliance_generation_facilities",
    "generation facilities compliance": "environmental_compliance_generation_facilities",
    "generation facility audit": "environmental_compliance_generation_facilities",
    "generation facilities audit": "environmental_compliance_generation_facilities",
    "generation facility enforcement": "environmental_compliance_generation_facilities",
    "generation facilities enforcement": "environmental_compliance_generation_facilities",
    "generation facility violation": "environmental_compliance_generation_facilities",
    "generation facilities violation": "environmental_compliance_generation_facilities",
    "generation facility penalty": "environmental_compliance_generation_facilities",
    "generation facilities penalty": "environmental_compliance_generation_facilities",
    "generation facility reporting": "environmental_compliance_generation_facilities",
    "generation facilities reporting": "environmental_compliance_generation_facilities",
    "generation facility self-report": "environmental_compliance_generation_facilities",
    "generation facilities self-report": "environmental_compliance_generation_facilities",
    "generation facility mitigation": "environmental_compliance_generation_facilities",
    "generation facilities mitigation": "environmental_compliance_generation_facilities",
    "generation facility order": "environmental_compliance_generation_facilities",
    "generation facilities order": "environmental_compliance_generation_facilities",
    "generation facility compliance review": "environmental_compliance_generation_facilities",
    "generation facilities compliance review": "environmental_compliance_generation_facilities",

    # FERC Open Access Transmission Tariff (OATT) Administration
    "ferc oatt": "ferc_open_access_transmission_tariff_administration",
    "oatt": "ferc_open_access_transmission_tariff_administration",
    "open access transmission tariff": "ferc_open_access_transmission_tariff_administration",
    "ferc open access transmission tariff": "ferc_open_access_transmission_tariff_administration",
    "oatt administration": "ferc_open_access_transmission_tariff_administration",
    "ferc oatt administration": "ferc_open_access_transmission_tariff_administration",
    "oatt compliance": "ferc_open_access_transmission_tariff_administration",
    "oatt audit": "ferc_open_access_transmission_tariff_administration",
    "oatt enforcement": "ferc_open_access_transmission_tariff_administration",
    "oatt violation": "ferc_open_access_transmission_tariff_administration",
    "oatt penalty": "ferc_open_access_transmission_tariff_administration",
    "oatt reporting": "ferc_open_access_transmission_tariff_administration",
    "oatt self-report": "ferc_open_access_transmission_tariff_administration",
    "oatt mitigation": "ferc_open_access_transmission_tariff_administration",
    "oatt order": "ferc_open_access_transmission_tariff_administration",
    "oatt review": "ferc_open_access_transmission_tariff_administration",
    "oatt approval": "ferc_open_access_transmission_tariff_administration",
    "oatt filing": "ferc_open_access_transmission_tariff_administration",
    "oatt requirements": "ferc_open_access_transmission_tariff_administration",

    # State Renewable Energy Siting and Permitting
    "renewable energy siting": "state_renewable_energy_siting_permitting",
    "renewable energy permitting": "state_renewable_energy_siting_permitting",
    "renewable siting": "state_renewable_energy_siting_permitting",
    "renewable permitting": "state_renewable_energy_siting_permitting",
    "state renewable energy siting": "state_renewable_energy_siting_permitting",
    "state renewable energy permitting": "state_renewable_energy_siting_permitting",
    "state renewable siting": "state_renewable_energy_siting_permitting",
    "state renewable permitting": "state_renewable_energy_siting_permitting",
    "renewable siting compliance": "state_renewable_energy_siting_permitting",
    "renewable permitting compliance": "state_renewable_energy_siting_permitting",
    "renewable siting audit": "state_renewable_energy_siting_permitting",
    "renewable permitting audit": "state_renewable_energy_siting_permitting",
    "renewable siting enforcement": "state_renewable_energy_siting_permitting",
    "renewable permitting enforcement": "state_renewable_energy_siting_permitting",
    "renewable siting violation": "state_renewable_energy_siting_permitting",
    "renewable permitting violation": "state_renewable_energy_siting_permitting",
    "renewable siting penalty": "state_renewable_energy_siting_permitting",
    "renewable permitting penalty": "state_renewable_energy_siting_permitting",
    "renewable siting reporting": "state_renewable_energy_siting_permitting",
    "renewable permitting reporting": "state_renewable_energy_siting_permitting",
    "renewable siting self-report": "state_renewable_energy_siting_permitting",
    "renewable permitting self-report": "state_renewable_energy_siting_permitting",
    "renewable siting mitigation": "state_renewable_energy_siting_permitting",
    "renewable permitting mitigation": "state_renewable_energy_siting_permitting",
    "renewable siting order": "state_renewable_energy_siting_permitting",
    "renewable permitting order": "state_renewable_energy_siting_permitting",
    "renewable siting review": "state_renewable_energy_siting_permitting",
    "renewable permitting review": "state_renewable_energy_siting_permitting",
    "renewable siting approval": "state_renewable_energy_siting_permitting",
    "renewable permitting approval": "state_renewable_energy_siting_permitting",

    # Electric Reliability Council (ERCOT) Governance and Oversight
    "ercot governance": "ercot_governance_oversight",
    "ercot oversight": "ercot_governance_oversight",
    "electric reliability council governance": "ercot_governance_oversight",
    "electric reliability council oversight": "ercot_governance_oversight",
    "ercot board": "ercot_governance_oversight",
    "ercot board governance": "ercot_governance_oversight",
    "ercot board oversight": "ercot_governance_oversight",
    "ercot stakeholder governance": "ercot_governance_oversight",
    "ercot stakeholder oversight": "ercot_governance_oversight",
    "ercot market governance": "ercot_governance_oversight",
    "ercot market oversight": "ercot_governance_oversight",
    "ercot governance structure": "ercot_governance_oversight",
    "ercot oversight structure": "ercot_governance_oversight",
    "ercot governance process": "ercot_governance_oversight",
    "ercot oversight process": "ercot_governance_oversight",
    "ercot governance compliance": "ercot_governance_oversight",
    "ercot oversight compliance": "ercot_governance_oversight",
    "ercot governance audit": "ercot_governance_oversight",
    "ercot oversight audit": "ercot_governance_oversight",
    "ercot governance enforcement": "ercot_governance_oversight",
    "ercot oversight enforcement": "ercot_governance_oversight",
    "ercot governance violation": "ercot_governance_oversight",
    "ercot oversight violation": "ercot_governance_oversight",
    "ercot governance penalty": "ercot_governance_oversight",
    "ercot oversight penalty": "ercot_governance_oversight",
    "ercot governance reporting": "ercot_governance_oversight",
    "ercot oversight reporting": "ercot_governance_oversight",
    "ercot governance self-report": "ercot_governance_oversight",
    "ercot oversight self-report": "ercot_governance_oversight",
    "ercot governance mitigation": "ercot_governance_oversight",
    "ercot oversight mitigation": "ercot_governance_oversight",
    "ercot governance order": "ercot_governance_oversight",
    "ercot oversight order": "ercot_governance_oversight",

    # Tax Treatment of Renewable Energy Tax Credits
    "renewable energy tax credits": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit": "tax_treatment_renewable_energy_tax_credits",
    "tax treatment renewable energy tax credits": "tax_treatment_renewable_energy_tax_credits",
    "tax treatment renewable energy tax credit": "tax_treatment_renewable_energy_tax_credits",
    "tax treatment rec": "tax_treatment_renewable_energy_tax_credits",
    "tax treatment rps": "tax_treatment_renewable_energy_tax_credits",
    "tax credit": "tax_treatment_renewable_energy_tax_credits",
    "tax credits": "tax_treatment_renewable_energy_tax_credits",
    "renewable tax credit": "tax_treatment_renewable_energy_tax_credits",
    "renewable tax credits": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit compliance": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit audit": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit enforcement": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit violation": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit penalty": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit reporting": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit self-report": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit mitigation": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit order": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit review": "tax_treatment_renewable_energy_tax_credits",
    "renewable energy tax credit approval": "tax_treatment_renewable_energy_tax_credits",

    # FERC Compliance and Self-Reporting Obligations
    "ferc compliance": "ferc_compliance_self_reporting_obligations",
    "ferc self-reporting": "ferc_compliance_self_reporting_obligations",
    "ferc self-report": "ferc_compliance_self_reporting_obligations",
    "ferc compliance obligations": "ferc_compliance_self_reporting_obligations",
    "ferc compliance requirements": "ferc_compliance_self_reporting_obligations",
    "ferc compliance audit": "ferc_compliance_self_reporting_obligations",
    "ferc compliance enforcement": "ferc_compliance_self_reporting_obligations",
    "ferc compliance violation": "ferc_compliance_self_reporting_obligations",
    "ferc compliance penalty": "ferc_compliance_self_reporting_obligations",
    "ferc compliance reporting": "ferc_compliance_self_reporting_obligations",
    "ferc compliance mitigation": "ferc_compliance_self_reporting_obligations",
    "ferc compliance order": "ferc_compliance_self_reporting_obligations",
    "ferc compliance review": "ferc_compliance_self_reporting_obligations",
    "ferc compliance approval": "ferc_compliance_self_reporting_obligations",
    "ferc compliance process": "ferc_compliance_self_reporting_obligations",
    "ferc compliance filing": "ferc_compliance_self_reporting_obligations",

    # RTO/ISO Capacity Market Mechanisms
    "rto capacity market": "rto_iso_capacity_market_mechanisms",
    "iso capacity market": "rto_iso_capacity_market_mechanisms",
    "capacity market": "rto_iso_capacity_market_mechanisms",
    "capacity market mechanisms": "rto_iso_capacity_market_mechanisms",
    "rto capacity market mechanisms": "rto_iso_capacity_market_mechanisms",
    "iso capacity market mechanisms": "rto_iso_capacity_market_mechanisms",
    "rto capacity market compliance": "rto_iso_capacity_market_mechanisms",
    "iso capacity market compliance": "rto_iso_capacity_market_mechanisms",
    "capacity market compliance": "rto_iso_capacity_market_mechanisms",
    "capacity market audit": "rto_iso_capacity_market_mechanisms",
    "capacity market enforcement": "rto_iso_capacity_market_mechanisms",
    "capacity market violation": "rto_iso_capacity_market_mechanisms",
    "capacity market penalty": "rto_iso_capacity_market_mechanisms",
    "capacity market reporting": "rto_iso_capacity_market_mechanisms",
    "capacity market self-report": "rto_iso_capacity_market_mechanisms",
    "capacity market mitigation": "rto_iso_capacity_market_mechanisms",
    "capacity market order": "rto_iso_capacity_market_mechanisms",
    "capacity market review": "rto_iso_capacity_market_mechanisms",
    "capacity market approval": "rto_iso_capacity_market_mechanisms",

    # FERC Abandonment Authority for Pipelines
    "ferc abandonment authority": "ferc_abandonment_authority_pipelines",
    "abandonment authority": "ferc_abandonment_authority_pipelines",
    "pipeline abandonment authority": "ferc_abandonment_authority_pipelines",
    "ferc pipeline abandonment": "ferc_abandonment_authority_pipelines",
    "pipeline abandonment": "ferc_abandonment_authority_pipelines",
    "ferc abandonment": "ferc_abandonment_authority_pipelines",
    "abandonment compliance": "ferc_abandonment_authority_pipelines",
    "abandonment audit": "ferc_abandonment_authority_pipelines",
    "abandonment enforcement": "ferc_abandonment_authority_pipelines",
    "abandonment violation": "ferc_abandonment_authority_pipelines",
    "abandonment penalty": "ferc_abandonment_authority_pipelines",
    "abandonment reporting": "ferc_abandonment_authority_pipelines",
    "abandonment self-report": "ferc_abandonment_authority_pipelines",
    "abandonment mitigation": "ferc_abandonment_authority_pipelines",
    "abandonment order": "ferc_abandonment_authority_pipelines",
    "abandonment review": "ferc_abandonment_authority_pipelines",
    "abandonment approval": "ferc_abandonment_authority_pipelines",
    "abandonment filing": "ferc_abandonment_authority_pipelines",
    "abandonment requirements": "ferc_abandonment_authority_pipelines",
    "abandonment process": "ferc_abandonment_authority_pipelines",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    concat += f"version:{SEMANTIC_MAP_VERSION};author:{SEMANTIC_MAP_AUTHOR};engine:{SEMANTIC_MAP_ENGINE};count:{_EXPECTED_ENTRY_COUNT};"
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def _normalize_string(s):
    s = s.lower()
    s = re.sub(r"[\s\-]+", " ", s)
    s = s.strip()
    return s

def normalize_term(term: str) -> str:
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)