import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MED10 Team"
SEMANTIC_MAP_ENGINE = "MED10_infectious_disease"

SEMANTIC_MAP = {
    # Sepsis-3 Criteria and qSOFA Screening
    "sepsis": "sepsis",
    "sepsis-3": "sepsis",
    "sepsis criteria": "sepsis",
    "sepsis3": "sepsis",
    "septicemia": "sepsis",
    "septic shock": "septic shock",
    "septic shock criteria": "septic shock",
    "septic": "sepsis",
    "sepsis syndrome": "sepsis",
    "sirs": "systemic inflammatory response syndrome",
    "systemic inflammatory response syndrome": "systemic inflammatory response syndrome",
    "qsofa": "quick sequential organ failure assessment",
    "quick sofa": "quick sequential organ failure assessment",
    "quick sequential organ failure assessment": "quick sequential organ failure assessment",
    "sofa": "sequential organ failure assessment",
    "sequential organ failure assessment": "sequential organ failure assessment",
    "sofa score": "sequential organ failure assessment",
    "qsofa score": "quick sequential organ failure assessment",
    "altered mentation": "altered mental status",
    "altered mental status": "altered mental status",
    "ams": "altered mental status",
    "hypotension": "hypotension",
    "tachypnea": "tachypnea",
    "rr > 22": "tachypnea",
    "respiratory rate > 22": "tachypnea",
    "sbp < 100": "hypotension",
    "systolic blood pressure < 100": "hypotension",
    "organ dysfunction": "organ dysfunction",
    "lactate": "lactate",
    "elevated lactate": "lactate",
    "hyperlactatemia": "lactate",
    "infection": "infection",
    "suspected infection": "infection",
    "confirmed infection": "infection",
    "bacteremia": "bacteremia",
    "bloodstream infection": "bacteremia",
    "multi-organ dysfunction": "organ dysfunction",
    "multi organ dysfunction": "organ dysfunction",
    "mod": "organ dysfunction",
    "multi organ failure": "organ dysfunction",
    "multi-organ failure": "organ dysfunction",

    # Empiric Antibiotic Selection for Sepsis
    "empiric antibiotics": "empiric antibiotic therapy",
    "empiric antibiotic therapy": "empiric antibiotic therapy",
    "empiric abx": "empiric antibiotic therapy",
    "broad spectrum antibiotics": "broad spectrum antibiotics",
    "broad-spectrum antibiotics": "broad spectrum antibiotics",
    "broad spectrum abx": "broad spectrum antibiotics",
    "antibiotic selection": "antibiotic selection",
    "empiric therapy": "empiric antibiotic therapy",
    "initial antibiotics": "empiric antibiotic therapy",
    "sepsis antibiotics": "empiric antibiotic therapy",
    "antibiotic coverage": "antibiotic coverage",
    "antibiotic regimen": "antibiotic regimen",
    "combination therapy": "combination therapy",
    "combo therapy": "combination therapy",
    "dual therapy": "combination therapy",
    "antimicrobial therapy": "antimicrobial therapy",
    "antimicrobial selection": "antimicrobial therapy",
    "antimicrobial regimen": "antimicrobial therapy",
    "empiric coverage": "empiric antibiotic therapy",
    "source control": "source control",
    "infection source": "source control",
    "antibiotic stewardship": "antimicrobial stewardship",
    "antimicrobial stewardship": "antimicrobial stewardship",
    "antibiotic de-escalation": "antibiotic de-escalation",
    "de-escalation": "antibiotic de-escalation",
    "antibiotic escalation": "antibiotic escalation",
    "escalation": "antibiotic escalation",
    "antibiotic resistance": "antibiotic resistance",
    "mdro": "multidrug resistant organism",
    "multidrug resistant organism": "multidrug resistant organism",
    "multi-drug resistant organism": "multidrug resistant organism",

    # Blood Culture Interpretation - True Positive vs Contaminant
    "blood culture": "blood culture",
    "blood cultures": "blood culture",
    "positive blood culture": "positive blood culture",
    "negative blood culture": "negative blood culture",
    "blood culture positive": "positive blood culture",
    "blood culture negative": "negative blood culture",
    "contaminant": "contaminant",
    "contamination": "contaminant",
    "true positive": "true positive",
    "false positive": "contaminant",
    "skin flora": "contaminant",
    "coagulase negative staph": "coagulase negative staphylococcus",
    "coagulase-negative staph": "coagulase negative staphylococcus",
    "coagulase negative staphylococcus": "coagulase negative staphylococcus",
    "cns": "coagulase negative staphylococcus",
    "staph epidermidis": "coagulase negative staphylococcus",
    "staphylococcus epidermidis": "coagulase negative staphylococcus",
    "diphtheroids": "contaminant",
    "corynebacterium": "contaminant",
    "bacillus species": "contaminant",
    "propionibacterium": "contaminant",
    "propionibacterium acnes": "contaminant",
    "multiple positive cultures": "true positive",
    "multiple sets positive": "true positive",
    "single positive culture": "contaminant",
    "single set positive": "contaminant",
    "repeat blood culture": "repeat blood culture",
    "repeat cultures": "repeat blood culture",
    "drawn from line": "contaminant",
    "line draw": "contaminant",
    "peripheral draw": "peripheral draw",
    "central line": "central line",
    "central venous catheter": "central line",
    "catheter related": "central line",
    "catheter-related bloodstream infection": "central line infection",
    "clabsi": "central line infection",
    "central line infection": "central line infection",

    # MRSA Management and Vancomycin Dosing
    "mrsa": "methicillin resistant staphylococcus aureus",
    "methicillin resistant staph aureus": "methicillin resistant staphylococcus aureus",
    "methicillin-resistant staph aureus": "methicillin resistant staphylococcus aureus",
    "methicillin resistant staphylococcus aureus": "methicillin resistant staphylococcus aureus",
    "methicillin-resistant staphylococcus aureus": "methicillin resistant staphylococcus aureus",
    "staph aureus": "staphylococcus aureus",
    "staphylococcus aureus": "staphylococcus aureus",
    "vancomycin": "vancomycin",
    "vanc": "vancomycin",
    "vancomycin dosing": "vancomycin dosing",
    "vancomycin trough": "vancomycin trough",
    "vancomycin level": "vancomycin trough",
    "vanc trough": "vancomycin trough",
    "vanc level": "vancomycin trough",
    "trough level": "vancomycin trough",
    "peak level": "vancomycin peak",
    "vancomycin peak": "vancomycin peak",
    "vancomycin monitoring": "vancomycin monitoring",
    "red man syndrome": "red man syndrome",
    "vanc red man": "red man syndrome",
    "vanco red man": "red man syndrome",
    "vancomycin reaction": "red man syndrome",
    "vancomycin allergy": "vancomycin allergy",
    "mrsa coverage": "mrsa coverage",
    "mrsa infection": "methicillin resistant staphylococcus aureus",
    "mrsa bacteremia": "mrsa bacteremia",
    "mrsa pneumonia": "mrsa pneumonia",
    "linezolid": "linezolid",
    "daptomycin": "daptomycin",
    "alternative to vancomycin": "mrsa alternative therapy",
    "mrsa alternative therapy": "mrsa alternative therapy",
    "vancomycin alternative": "mrsa alternative therapy",
    "vancomycin resistant": "vancomycin resistant enterococcus",
    "vre": "vancomycin resistant enterococcus",
    "vancomycin resistant enterococcus": "vancomycin resistant enterococcus",

    # C. difficile Infection Diagnosis and Management
    "c diff": "clostridioides difficile",
    "c. diff": "clostridioides difficile",
    "clostridium difficile": "clostridioides difficile",
    "clostridioides difficile": "clostridioides difficile",
    "cdi": "clostridioides difficile",
    "c difficile": "clostridioides difficile",
    "cdiff": "clostridioides difficile",
    "cdiff infection": "clostridioides difficile infection",
    "cdi infection": "clostridioides difficile infection",
    "c difficile infection": "clostridioides difficile infection",
    "clostridium difficile infection": "clostridioides difficile infection",
    "clostridioides difficile infection": "clostridioides difficile infection",
    "cdad": "clostridioides difficile infection",
    "cdad infection": "clostridioides difficile infection",
    "cdiff colitis": "clostridioides difficile infection",
    "c diff colitis": "clostridioides difficile infection",
    "pseudomembranous colitis": "clostridioides difficile infection",
    "toxin assay": "c difficile toxin assay",
    "c diff toxin": "c difficile toxin assay",
    "c difficile toxin": "c difficile toxin assay",
    "c diff pcr": "c difficile pcr",
    "c difficile pcr": "c difficile pcr",
    "nucleic acid amplification test": "c difficile pcr",
    "naat": "c difficile pcr",
    "stool test": "c difficile diagnosis",
    "stool toxin": "c difficile toxin assay",
    "stool pcr": "c difficile pcr",
    "fidaxomicin": "fidaxomicin",
    "vancomycin oral": "oral vancomycin",
    "oral vancomycin": "oral vancomycin",
    "metronidazole": "metronidazole",
    "flagyl": "metronidazole",
    "fecal transplant": "fecal microbiota transplantation",
    "fmt": "fecal microbiota transplantation",
    "fecal microbiota transplantation": "fecal microbiota transplantation",
    "recurrent c diff": "recurrent clostridioides difficile infection",
    "recurrent cdi": "recurrent clostridioides difficile infection",
    "recurrent cdiff": "recurrent clostridioides difficile infection",
    "severe c diff": "severe clostridioides difficile infection",
    "severe cdi": "severe clostridioides difficile infection",
    "fulminant c diff": "fulminant clostridioides difficile infection",
    "fulminant cdi": "fulminant clostridioides difficile infection",

    # Antimicrobial Stewardship Program Core Elements
    "antimicrobial stewardship program": "antimicrobial stewardship program",
    "asp": "antimicrobial stewardship program",
    "stewardship program": "antimicrobial stewardship program",
    "core elements": "core elements of antimicrobial stewardship",
    "core elements of asp": "core elements of antimicrobial stewardship",
    "leadership commitment": "leadership commitment",
    "accountability": "accountability",
    "pharmacy expertise": "pharmacy expertise",
    "pharmacist expertise": "pharmacy expertise",
    "action": "action",
    "tracking": "tracking",
    "reporting": "reporting",
    "education": "education",
    "antibiotic time out": "antibiotic time out",
    "antibiotic timeout": "antibiotic time out",
    "audit and feedback": "audit and feedback",
    "audit & feedback": "audit and feedback",
    "prospective audit": "prospective audit",
    "feedback": "audit and feedback",
    "formulary restriction": "formulary restriction",
    "preauthorization": "preauthorization",
    "antibiotic preauthorization": "preauthorization",
    "antimicrobial preauthorization": "preauthorization",
    "guideline adherence": "guideline adherence",
    "protocol adherence": "guideline adherence",
    "order set": "order set",
    "clinical pathway": "clinical pathway",
    "antibiotic guideline": "guideline adherence",
    "antimicrobial guideline": "guideline adherence",
    "dose optimization": "dose optimization",
    "dosing optimization": "dose optimization",
    "duration optimization": "duration optimization",
    "antibiotic duration": "duration optimization",
    "antimicrobial duration": "duration optimization",
    "antibiotic review": "antibiotic review",
    "antibiotic reassessment": "antibiotic review",
    "antibiotic stewardship team": "antimicrobial stewardship program",
    "stewardship team": "antimicrobial stewardship program",

    # Procalcitonin-Guided Antibiotic Therapy
    "procalcitonin": "procalcitonin",
    "pct": "procalcitonin",
    "procalcitonin guided therapy": "procalcitonin guided antibiotic therapy",
    "procalcitonin-guided therapy": "procalcitonin guided antibiotic therapy",
    "procalcitonin guided antibiotics": "procalcitonin guided antibiotic therapy",
    "procalcitonin-guided antibiotics": "procalcitonin guided antibiotic therapy",
    "procalcitonin algorithm": "procalcitonin guided antibiotic therapy",
    "procalcitonin cutoff": "procalcitonin cutoff",
    "procalcitonin threshold": "procalcitonin cutoff",
    "pct cutoff": "procalcitonin cutoff",
    "pct threshold": "procalcitonin cutoff",
    "procalcitonin interpretation": "procalcitonin interpretation",
    "pct interpretation": "procalcitonin interpretation",
    "antibiotic discontinuation": "antibiotic discontinuation",
    "antibiotic stop": "antibiotic discontinuation",
    "antibiotic cessation": "antibiotic discontinuation",
    "antibiotic continuation": "antibiotic continuation",
    "antibiotic start": "antibiotic initiation",
    "antibiotic initiation": "antibiotic initiation",

    # HIV Treatment - ART Initiation and Regimens
    "hiv": "human immunodeficiency virus",
    "human immunodeficiency virus": "human immunodeficiency virus",
    "hiv infection": "human immunodeficiency virus",
    "hiv positive": "human immunodeficiency virus",
    "hiv+": "human immunodeficiency virus",
    "aids": "acquired immunodeficiency syndrome",
    "acquired immunodeficiency syndrome": "acquired immunodeficiency syndrome",
    "art": "antiretroviral therapy",
    "antiretroviral therapy": "antiretroviral therapy",
    "hiv treatment": "antiretroviral therapy",
    "hiv therapy": "antiretroviral therapy",
    "hiv regimen": "antiretroviral therapy regimen",
    "art regimen": "antiretroviral therapy regimen",
    "antiretroviral regimen": "antiretroviral therapy regimen",
    "hiv drugs": "antiretroviral therapy",
    "antiretroviral drugs": "antiretroviral therapy",
    "initiate art": "art initiation",
    "art initiation": "art initiation",
    "start art": "art initiation",
    "start hiv therapy": "art initiation",
    "hiv viral load": "hiv viral load",
    "viral load": "hiv viral load",
    "cd4 count": "cd4 count",
    "cd4": "cd4 count",
    "opportunistic infection": "opportunistic infection",
    "oi": "opportunistic infection",
    "prep": "pre-exposure prophylaxis",
    "pre-exposure prophylaxis": "pre-exposure prophylaxis",
    "pep": "post-exposure prophylaxis",
    "post-exposure prophylaxis": "post-exposure prophylaxis",
    "integrase inhibitor": "integrase strand transfer inhibitor",
    "insti": "integrase strand transfer inhibitor",
    "integrase strand transfer inhibitor": "integrase strand transfer inhibitor",
    "nrtis": "nucleoside reverse transcriptase inhibitors",
    "nucleoside reverse transcriptase inhibitors": "nucleoside reverse transcriptase inhibitors",
    "nnrtis": "non-nucleoside reverse transcriptase inhibitors",
    "non-nucleoside reverse transcriptase inhibitors": "non-nucleoside reverse transcriptase inhibitors",
    "protease inhibitor": "protease inhibitor",
    "pis": "protease inhibitor",
    "entry inhibitor": "entry inhibitor",
    "fusion inhibitor": "fusion inhibitor",
    "dolutegravir": "dolutegravir",
    "bictegravir": "bictegravir",
    "tenofovir": "tenofovir",
    "emtricitabine": "emtricitabine",
    "abacavir": "abacavir",
    "lamivudine": "lamivudine",
    "efavirenz": "efavirenz",
    "darunavir": "darunavir",
    "ritonavir": "ritonavir",
    "cobicistat": "cobicistat",

    # Tuberculosis Diagnosis and RIPE Therapy
    "tb": "tuberculosis",
    "tuberculosis": "tuberculosis",
    "mycobacterium tuberculosis": "tuberculosis",
    "pulmonary tb": "pulmonary tuberculosis",
    "extrapulmonary tb": "extrapulmonary tuberculosis",
    "latent tb": "latent tuberculosis",
    "active tb": "active tuberculosis",
    "tb infection": "tuberculosis",
    "tb disease": "tuberculosis",
    "tb diagnosis": "tuberculosis diagnosis",
    "tb test": "tuberculosis diagnosis",
    "tb screening": "tuberculosis diagnosis",
    "ppd": "tuberculin skin test",
    "tst": "tuberculin skin test",
    "tuberculin skin test": "tuberculin skin test",
    "mantoux test": "tuberculin skin test",
    "quantiferon": "interferon gamma release assay",
    "quantiferon gold": "interferon gamma release assay",
    "interferon gamma release assay": "interferon gamma release assay",
    "igra": "interferon gamma release assay",
    "tb culture": "tb culture",
    "tb pcr": "tb pcr",
    "tb smear": "tb smear",
    "acid fast bacilli": "acid fast bacilli",
    "afb": "acid fast bacilli",
    "sputum culture": "tb culture",
    "sputum smear": "tb smear",
    "sputum afb": "acid fast bacilli",
    "rife therapy": "ripe therapy",
    "ripe": "ripe therapy",
    "ripe therapy": "ripe therapy",
    "tb treatment": "ripe therapy",
    "tb regimen": "ripe therapy",
    "isoniazid": "isoniazid",
    "inh": "isoniazid",
    "rifampin": "rifampin",
    "rifampicin": "rifampin",
    "rif": "rifampin",
    "pyrazinamide": "pyrazinamide",
    "pza": "pyrazinamide",
    "ethambutol": "ethambutol",
    "emb": "ethambutol",
    "directly observed therapy": "directly observed therapy",
    "dot": "directly observed therapy",
    "dot therapy": "directly observed therapy",
    "multidrug resistant tb": "multidrug resistant tuberculosis",
    "mdr tb": "multidrug resistant tuberculosis",
    "mdrtb": "multidrug resistant tuberculosis",
    "xdr tb": "extensively drug resistant tuberculosis",
    "extensively drug resistant tb": "extensively drug resistant tuberculosis",
    "tb prophylaxis": "tb prophylaxis",
    "latent tb treatment": "latent tb treatment",
    "isoniazid prophylaxis": "isoniazid prophylaxis",

    # Carbapenem-Resistant Enterobacterales (CRE) Management
    "cre": "carbapenem resistant enterobacterales",
    "carbapenem resistant enterobacterales": "carbapenem resistant enterobacterales",
    "carbapenem-resistant enterobacterales": "carbapenem resistant enterobacterales",
    "carbapenem resistant enterobacteriaceae": "carbapenem resistant enterobacterales",
    "carbapenem-resistant enterobacteriaceae": "carbapenem resistant enterobacterales",
    "carbapenemase": "carbapenemase",
    "carbapenemase producer": "carbapenemase producing organism",
    "carbapenemase producing organism": "carbapenemase producing organism",
    "kpc": "klebsiella pneumoniae carbapenemase",
    "klebsiella pneumoniae carbapenemase": "klebsiella pneumoniae carbapenemase",
    "ndm": "new delhi metallo beta lactamase",
    "new delhi metallo beta lactamase": "new delhi metallo beta lactamase",
    "oxa-48": "oxa 48 carbapenemase",
    "oxa 48": "oxa 48 carbapenemase",
    "vab": "verona integron encoded metallo beta lactamase",
    "vim": "verona integron encoded metallo beta lactamase",
    "verona integron encoded metallo beta lactamase": "verona integron encoded metallo beta lactamase",
    "imipenem": "imipenem",
    "meropenem": "meropenem",
    "ertapenem": "ertapenem",
    "doripenem": "doripenem",
    "polymyxin": "polymyxin",
    "colistin": "colistin",
    "tigecycline": "tigecycline",
    "ceftazidime avibactam": "ceftazidime avibactam",
    "ceftazidime-avibactam": "ceftazidime avibactam",
    "avibactam": "avibactam",
    "plazomicin": "plazomicin",
    "fosfomycin": "fosfomycin",
    "aminoglycoside": "aminoglycoside",
    "aminoglycosides": "aminoglycoside",
    "combination therapy cre": "combination therapy cre",
    "cre infection": "carbapenem resistant enterobacterales",
    "cre management": "carbapenem resistant enterobacterales management",

    # Healthcare-Associated Infections (HAI) Prevention
    "hai": "healthcare associated infection",
    "healthcare associated infection": "healthcare associated infection",
    "healthcare-associated infection": "healthcare associated infection",
    "nosocomial infection": "healthcare associated infection",
    "hospital acquired infection": "healthcare associated infection",
    "hospital-acquired infection": "healthcare associated infection",
    "catheter associated uti": "catheter associated urinary tract infection",
    "catheter-associated uti": "catheter associated urinary tract infection",
    "cauti": "catheter associated urinary tract infection",
    "catheter associated urinary tract infection": "catheter associated urinary tract infection",
    "central line associated bloodstream infection": "central line infection",
    "central line-associated bloodstream infection": "central line infection",
    "clabsi": "central line infection",
    "ventilator associated pneumonia": "ventilator associated pneumonia",
    "ventilator-associated pneumonia": "ventilator associated pneumonia",
    "vap": "ventilator associated pneumonia",
    "surgical site infection": "surgical site infection",
    "ssi": "surgical site infection",
    "surgical wound infection": "surgical site infection",
    "prevention bundle": "infection prevention bundle",
    "infection prevention bundle": "infection prevention bundle",
    "prevention protocol": "infection prevention protocol",
    "infection prevention protocol": "infection prevention protocol",
    "hand hygiene": "hand hygiene",
    "handwashing": "hand hygiene",
    "hand washing": "hand hygiene",
    "alcohol based hand rub": "hand hygiene",
    "alcohol-based hand rub": "hand hygiene",
    "contact precautions": "contact precautions",
    "droplet precautions": "droplet precautions",
    "airborne precautions": "airborne precautions",
    "isolation precautions": "isolation precautions",
    "personal protective equipment": "personal protective equipment",
    "ppe": "personal protective equipment",
    "environmental cleaning": "environmental cleaning",
    "disinfection": "disinfection",
    "sterilization": "sterilization",
    "antimicrobial prophylaxis": "antimicrobial prophylaxis",
    "surgical prophylaxis": "antimicrobial prophylaxis",
    "preoperative antibiotics": "antimicrobial prophylaxis",
    "pre-op antibiotics": "antimicrobial prophylaxis",

    # Febrile Neutropenia Management
    "febrile neutropenia": "febrile neutropenia",
    "neutropenic fever": "febrile neutropenia",
    "neutropenia": "neutropenia",
    "neutropenic": "neutropenia",
    "anc": "absolute neutrophil count",
    "absolute neutrophil count": "absolute neutrophil count",
    "low anc": "neutropenia",
    "high risk neutropenia": "high risk neutropenia",
    "low risk neutropenia": "low risk neutropenia",
    "empiric antibiotics neutropenia": "empiric antibiotic therapy neutropenia",
    "empiric abx neutropenia": "empiric antibiotic therapy neutropenia",
    "antibiotic prophylaxis neutropenia": "antibiotic prophylaxis neutropenia",
    "antifungal prophylaxis": "antifungal prophylaxis",
    "antifungal therapy": "antifungal therapy",
    "antiviral prophylaxis": "antiviral prophylaxis",
    "antiviral therapy": "antiviral therapy",
    "colony stimulating factor": "colony stimulating factor",
    "csf": "colony stimulating factor",
    "g-csf": "granulocyte colony stimulating factor",
    "granulocyte colony stimulating factor": "granulocyte colony stimulating factor",
    "filgrastim": "filgrastim",
    "pegfilgrastim": "pegfilgrastim",
    "infection risk neutropenia": "infection risk neutropenia",
    "mascc score": "mascc risk index",
    "mascc risk index": "mascc risk index",
    "idsa neutropenia": "idsa neutropenia guidelines",
    "idsa neutropenia guidelines": "idsa neutropenia guidelines",

    # Antibiotic Dosing in Renal Impairment
    "renal impairment": "renal impairment",
    "renal failure": "renal impairment",
    "kidney failure": "renal impairment",
    "ckd": "chronic kidney disease",
    "chronic kidney disease": "chronic kidney disease",
    "esrd": "end stage renal disease",
    "end stage renal disease": "end stage renal disease",
    "dialysis": "dialysis",
    "hemodialysis": "hemodialysis",
    "peritoneal dialysis": "peritoneal dialysis",
    "crrt": "continuous renal replacement therapy",
    "continuous renal replacement therapy": "continuous renal replacement therapy",
    "gfr": "glomerular filtration rate",
    "glomerular filtration rate": "glomerular filtration rate",
    "creatinine clearance": "creatinine clearance",
    "crcl": "creatinine clearance",
    "dose adjustment": "dose adjustment",
    "dose modification": "dose adjustment",
    "renal dosing": "dose adjustment",
    "antibiotic dosing": "antibiotic dosing",
    "antimicrobial dosing": "antibiotic dosing",
    "dosing in renal impairment": "dose adjustment",
    "dosing in renal failure": "dose adjustment",
    "dosing in ckd": "dose adjustment",
    "dosing in esrd": "dose adjustment",
    "dosing in dialysis": "dose adjustment",
    "dosing in hemodialysis": "dose adjustment",
    "dosing in peritoneal dialysis": "dose adjustment",
    "dosing in crrt": "dose adjustment",
    "renal dose": "dose adjustment",
    "renal dose adjustment": "dose adjustment",
    "adjust for renal function": "dose adjustment",
    "adjust for gfr": "dose adjustment",
    "adjust for crcl": "dose adjustment",
    "adjust for creatinine clearance": "dose adjustment",
    "dose reduce": "dose adjustment",
    "dose reduction": "dose adjustment",
    "dose decrease": "dose adjustment",
    "dose increase": "dose adjustment",
    "dose escalation": "dose adjustment",
    "dose interval": "dose interval",
    "dosing interval": "dose interval",

    # Infection Control - Isolation Precautions
    "infection control": "infection control",
    "isolation": "isolation precautions",
    "isolation precautions": "isolation precautions",
    "contact isolation": "contact precautions",
    "contact precautions": "contact precautions",
    "droplet isolation": "droplet precautions",
    "droplet precautions": "droplet precautions",
    "airborne isolation": "airborne precautions",
    "airborne precautions": "airborne precautions",
    "reverse isolation": "reverse isolation",
    "protective isolation": "reverse isolation",
    "cohorting": "cohorting",
    "cohort isolation": "cohorting",
    "single room": "single room isolation",
    "private room": "single room isolation",
    "negative pressure room": "negative pressure room",
    "positive pressure room": "positive pressure room",
    "n95": "n95 respirator",
    "n95 mask": "n95 respirator",
    "n95 respirator": "n95 respirator",
    "surgical mask": "surgical mask",
    "face shield": "face shield",
    "gown": "gown",
    "gloves": "gloves",
    "eye protection": "eye protection",
    "hand hygiene": "hand hygiene",
    "handwashing": "hand hygiene",
    "hand washing": "hand hygiene",
    "alcohol based hand rub": "hand hygiene",
    "alcohol-based hand rub": "hand hygiene",
    "environmental cleaning": "environmental cleaning",
    "disinfection": "disinfection",
    "sterilization": "sterilization",
    "terminal cleaning": "terminal cleaning",
    "uv disinfection": "uv disinfection",
    "ultraviolet disinfection": "uv disinfection",
    "pcr test": "pcr test",
    "molecular test": "pcr test",
    "rapid test": "rapid test",
    "point of care test": "point of care test",
    "poc test": "point of care test",
    "screening test": "screening test",
    "screening swab": "screening swab",
    "surveillance culture": "surveillance culture",
    "active surveillance": "active surveillance",
    "outbreak investigation": "outbreak investigation",
    "contact tracing": "contact tracing",
    "exposure management": "exposure management",
    "source patient": "source patient",
    "index case": "index case",
    "case finding": "case finding",
    "case definition": "case definition",
    "infection preventionist": "infection preventionist",
    "infection prevention": "infection prevention",
    "infection prevention team": "infection prevention",
    "infection prevention program": "infection prevention",
    "infection control nurse": "infection preventionist",
    "infection control practitioner": "infection preventionist",
    "infection control committee": "infection prevention",
    "outbreak control": "outbreak investigation",
    "cluster investigation": "outbreak investigation",
    "epidemiology": "epidemiology",
    "epidemic": "epidemic",
    "pandemic": "pandemic",
    "endemic": "endemic",
    "surveillance": "surveillance",
    "incidence": "incidence",
    "prevalence": "prevalence",
    "case rate": "incidence",
    "attack rate": "incidence",
    "mortality rate": "mortality rate",
    "case fatality rate": "case fatality rate",
    "secondary attack rate": "secondary attack rate",
    "transmission": "transmission",
    "mode of transmission": "mode of transmission",
    "vector": "vector",
    "reservoir": "reservoir",
    "host": "host",
    "susceptible host": "susceptible host",
    "carrier": "carrier",
    "asymptomatic carrier": "carrier",
    "colonization": "colonization",
    "infection": "infection",
    "disease": "disease",
    "exposure": "exposure",
    "incubation period": "incubation period",
    "latent period": "latent period",
    "infectious period": "infectious period",
    "communicable period": "infectious period",
    "quarantine": "quarantine",
    "isolation": "isolation precautions",
    "cohort": "cohorting",
    "screening": "screening",
    "testing": "testing",
    "diagnosis": "diagnosis",
    "case management": "case management",
    "contact management": "exposure management",
    "risk assessment": "risk assessment",
    "exposure risk": "risk assessment",
    "exposure notification": "exposure management",
    "contact notification": "exposure management",
    "infection risk": "infection risk",
    "risk stratification": "risk assessment",
    "high risk": "high risk",
    "low risk": "low risk",
    "moderate risk": "moderate risk",
    "risk category": "risk assessment",
    "precaution": "isolation precautions",
    "precautions": "isolation precautions",
    "standard precautions": "standard precautions",
    "universal precautions": "standard precautions",
    "transmission based precautions": "transmission based precautions",
    "transmission-based precautions": "transmission based precautions",
    "source isolation": "source isolation",
    "barrier precautions": "barrier precautions",
    "personal protective equipment": "personal protective equipment",
    "ppe": "personal protective equipment",
    "fit testing": "fit testing",
    "fit test": "fit testing",
    "donning": "donning",
    "doffing": "doffing",
    "donning and doffing": "donning and doffing",
    "fit check": "fit testing",
    "mask fit": "fit testing",
    "respirator": "respirator",
    "face mask": "surgical mask",
    "face covering": "surgical mask",
    "eye shield": "eye protection",
    "protective eyewear": "eye protection",
    "protective clothing": "gown",
    "protective equipment": "personal protective equipment",
    "disposable gown": "gown",
    "disposable gloves": "gloves",
    "sterile gloves": "gloves",
    "non-sterile gloves": "gloves",
    "clean gloves": "gloves",
    "sterile field": "sterile field",
    "aseptic technique": "aseptic technique",
    "asepsis": "aseptic technique",
    "clean technique": "clean technique",
    "contaminated": "contaminant",
    "contamination": "contaminant",
    "cleaning": "environmental cleaning",
    "environmental disinfection": "environmental cleaning",
    "surface disinfection": "environmental cleaning",
    "surface cleaning": "environmental cleaning",
    "terminal disinfection": "terminal cleaning",
    "high touch surface": "high touch surface",
    "high-touch surface": "high touch surface",
    "fomite": "fomite",
    "vector control": "vector control",
    "rodent control": "vector control",
    "insect control": "vector control",
    "pest control": "vector control",
    "waste management": "waste management",
    "sharps disposal": "sharps disposal",
    "biohazard": "biohazard",
    "biohazard waste": "biohazard",
    "medical waste": "biohazard",
    "hazardous waste": "biohazard",
    "spill management": "spill management",
    "exposure control": "exposure management",
    "exposure protocol": "exposure management",
    "post exposure prophylaxis": "post-exposure prophylaxis",
    "post-exposure prophylaxis": "post-exposure prophylaxis",
    "pre exposure prophylaxis": "pre-exposure prophylaxis",
    "pre-exposure prophylaxis": "pre-exposure prophylaxis",
    "immunization": "immunization",
    "vaccination": "immunization",
    "vaccine": "immunization",
    "immunize": "immunization",
    "herd immunity": "herd immunity",
    "outbreak": "outbreak investigation",
    "cluster": "outbreak investigation",
    "epidemic curve": "epidemic curve",
    "epi curve": "epidemic curve",
    "case cluster": "outbreak investigation",
    "case series": "case series",
    "case report": "case report",
    "case study": "case report",
    "sentinel event": "sentinel event",
    "sentinel surveillance": "sentinel surveillance",
    "syndromic surveillance": "syndromic surveillance",
    "active surveillance": "active surveillance",
    "passive surveillance": "passive surveillance",
    "notifiable disease": "notifiable disease",
    "reportable disease": "notifiable disease",
    "mandatory reporting": "notifiable disease",
    "disease registry": "disease registry",
    "case notification": "case notification",
    "public health notification": "case notification",
    "public health reporting": "case notification",
    "public health authority": "public health authority",
    "department of health": "public health authority",
    "cdc": "centers for disease control and prevention",
    "centers for disease control": "centers for disease control and prevention",
    "centers for disease control and prevention": "centers for disease control and prevention",
    "who": "world health organization",
    "world health organization": "world health organization",
    "infection prevention and control": "infection prevention",
    "ipac": "infection prevention",
    "ipc": "infection prevention",
    "infection control program": "infection prevention",
    "infection control policy": "infection prevention",
    "infection control protocol": "infection prevention",
    "infection control guideline": "infection prevention",
    "infection control standard": "infection prevention",
    "infection control procedure": "infection prevention",
    "infection control practice": "infection prevention",
    "infection control audit": "infection prevention",
    "infection control assessment": "infection prevention",
    "infection control plan": "infection prevention",
    "infection control strategy": "infection prevention",
    "infection control training": "infection prevention",
    "infection control education": "infection prevention",
    "infection control compliance": "infection prevention",
    "infection control monitoring": "infection prevention",
    "infection control surveillance": "infection prevention",
    "infection control reporting": "infection prevention",
    "infection control evaluation": "infection prevention",
    "infection control improvement": "infection prevention",
    "infection control review": "infection prevention",
    "infection control performance": "infection prevention",
    "infection control effectiveness": "infection prevention",
    "infection control outcome": "infection prevention",
    "infection control indicator": "infection prevention",
    "infection control measure": "infection prevention",
    "infection control metric": "infection prevention",
    "infection control benchmark": "infection prevention",
    "infection control goal": "infection prevention",
    "infection control objective": "infection prevention",
    "infection control target": "infection prevention",
    "infection control result": "infection prevention",
    "infection control achievement": "infection prevention",
    "infection control success": "infection prevention",
    "infection control failure": "infection prevention",
    "infection control gap": "infection prevention",
    "infection control barrier": "infection prevention",
    "infection control challenge": "infection prevention",
    "infection control risk": "infection prevention",
    "infection control hazard": "infection prevention",
    "infection control incident": "infection prevention",
    "infection control event": "infection prevention",
    "infection control outbreak": "outbreak investigation",
    "infection control cluster": "outbreak investigation",
    "infection control epidemic": "epidemic",
    "infection control pandemic": "pandemic",
    "infection control endemic": "endemic",
    "infection control surveillance system": "infection prevention",
    "infection control reporting system": "infection prevention",
    "infection control alert": "infection prevention",
    "infection control notification": "infection prevention",
    "infection control communication": "infection prevention",
    "infection control information": "infection prevention",
    "infection control data": "infection prevention",
    "infection control record": "infection prevention",
    "infection control documentation": "infection prevention",
    "infection control log": "infection prevention",
    "infection control register": "infection prevention",
    "infection control database": "infection prevention",
    "infection control software": "infection prevention",
    "infection control system": "infection prevention",
    "infection control technology": "infection prevention",
    "infection control tool": "infection prevention",
    "infection control resource": "infection prevention",
    "infection control support": "infection prevention",
    "infection control service": "infection prevention",
    "infection control consultation": "infection prevention",
    "infection control advice": "infection prevention",
    "infection control recommendation": "infection prevention",
    "infection control guidance": "infection prevention",
    "infection control instruction": "infection prevention",
    "infection control suggestion": "infection prevention",
    "infection control tip": "infection prevention",
    "infection control hint": "infection prevention",
    "infection control pointer": "infection prevention",
    "infection control note": "infection prevention",
    "infection control message": "infection prevention",
    "infection control memo": "infection prevention",
    "infection control bulletin": "infection prevention",
    "infection control newsletter": "infection prevention",
    "infection control update": "infection prevention",
    "infection control news": "infection prevention",
    "infection control announcement": "infection prevention",
    "infection control alert": "infection prevention",
    "infection control warning": "infection prevention",
    "infection control notice": "infection prevention",
    "infection control reminder": "infection prevention",
    "infection control summary": "infection prevention",
    "infection control report": "infection prevention",
    "infection control review": "infection prevention",
    "infection control audit": "infection prevention",
    "infection control assessment": "infection prevention",
    "infection control evaluation": "infection prevention",
    "infection control monitoring": "infection prevention",
    "infection control compliance": "infection prevention",
    "infection control improvement": "infection prevention",
    "infection control effectiveness": "infection prevention",
    "infection control outcome": "infection prevention",
    "infection control indicator": "infection prevention",
    "infection control measure": "infection prevention",
    "infection control metric": "infection prevention",
    "infection control benchmark": "infection prevention",
    "infection control goal": "infection prevention",
    "infection control objective": "infection prevention",
    "infection control target": "infection prevention",
    "infection control result": "infection prevention",
    "infection control achievement": "infection prevention",
    "infection control success": "infection prevention",
    "infection control failure": "infection prevention",
    "infection control gap": "infection prevention",
    "infection control barrier": "infection prevention",
    "infection control challenge": "infection prevention",
    "infection control risk": "infection prevention",
    "infection control hazard": "infection prevention",
    "infection control incident": "infection prevention",
    "infection control event": "infection prevention",
    "infection control outbreak": "outbreak investigation",
    "infection control cluster": "outbreak investigation",
    "infection control epidemic": "epidemic",
    "infection control pandemic": "pandemic",
    "infection control endemic": "endemic",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    map_str = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(map_str.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    current_hash = _compute_map_hash()
    is_valid = current_hash == _MAP_INTEGRITY_HASH
    return {
        "status": "ok" if is_valid else "corrupt",
        "entries": len(SEMANTIC_MAP),
        "hash": current_hash,
        "is_valid": is_valid,
    }

def _normalize_string(s):
    s = s.lower()
    s = re.sub(r"[\s\-_/]+", " ", s)
    s = s.strip()
    return s

def normalize_term(term: str) -> str:
    t = _normalize_string(term)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)