import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "FRAC03 Semantic Team"
SEMANTIC_MAP_ENGINE = "FRAC03_perforation_design"
_EXPECTED_ENTRY_COUNT = 208

SEMANTIC_MAP = {
    # Deep Penetrating vs Big Hole Charge Design
    "deep penetrating charge": "deep_penetrating_charge",
    "deep penetration charge": "deep_penetrating_charge",
    "deep penetration": "deep_penetrating_charge",
    "deep charge": "deep_penetrating_charge",
    "deep charges": "deep_penetrating_charge",
    "deep penetrating": "deep_penetrating_charge",
    "big hole charge": "big_hole_charge",
    "big hole charges": "big_hole_charge",
    "big hole": "big_hole_charge",
    "large hole charge": "big_hole_charge",
    "large hole": "big_hole_charge",
    "bighole": "big_hole_charge",
    "deep vs big hole": "deep_vs_big_hole",
    "deep vs big": "deep_vs_big_hole",
    "penetration vs hole size": "deep_vs_big_hole",
    "hole size": "big_hole_charge",
    "entry hole": "big_hole_charge",
    "entry diameter": "big_hole_charge",
    "perforation diameter": "big_hole_charge",
    "perforation depth": "deep_penetrating_charge",
    "tunnel depth": "deep_penetrating_charge",
    "tunnel diameter": "big_hole_charge",
    "charge design": "charge_design",
    "perforating charge": "charge_design",
    "perforator": "charge_design",
    "perforating gun": "charge_design",
    "gun system": "charge_design",
    "gun design": "charge_design",
    "charge type": "charge_design",
    "charge performance": "charge_performance",
    "perforation performance": "charge_performance",
    "charge efficiency": "charge_performance",
    "perforation efficiency": "charge_performance",
    "penetration": "deep_penetrating_charge",
    "hole": "big_hole_charge",
    # Shot Density and Phasing for Horizontal Wells
    "shot density": "shot_density",
    "spm": "shot_density",
    "shots per meter": "shot_density",
    "shots per foot": "shot_density",
    "spf": "shot_density",
    "phasing": "phasing",
    "perforation phasing": "phasing",
    "angle phasing": "phasing",
    "phasing angle": "phasing",
    "degree phasing": "phasing",
    "60 degree phasing": "phasing_60",
    "90 degree phasing": "phasing_90",
    "120 degree phasing": "phasing_120",
    "180 degree phasing": "phasing_180",
    "360 degree phasing": "phasing_360",
    "cluster phasing": "phasing",
    "horizontal well": "horizontal_well",
    "horizontal wells": "horizontal_well",
    "hz well": "horizontal_well",
    "hz wells": "horizontal_well",
    "lateral": "horizontal_well",
    "laterals": "horizontal_well",
    # Limited Entry Perforation Friction Diversion
    "limited entry": "limited_entry",
    "limited entry perforation": "limited_entry",
    "limited entry design": "limited_entry",
    "friction diversion": "friction_diversion",
    "perforation friction": "friction_diversion",
    "entry friction": "friction_diversion",
    "friction pressure": "friction_diversion",
    "perforation friction pressure": "friction_diversion",
    "limited entry diversion": "friction_diversion",
    "friction diversion technique": "friction_diversion",
    "friction diversion method": "friction_diversion",
    "friction diversion design": "friction_diversion",
    # Underbalanced vs Overbalanced Perforating
    "underbalanced perforating": "underbalanced_perforating",
    "underbalanced": "underbalanced_perforating",
    "ub perforating": "underbalanced_perforating",
    "overbalanced perforating": "overbalanced_perforating",
    "overbalanced": "overbalanced_perforating",
    "ob perforating": "overbalanced_perforating",
    "balanced perforating": "balanced_perforating",
    "balanced": "balanced_perforating",
    "underbalance": "underbalanced_perforating",
    "overbalance": "overbalanced_perforating",
    # API RP 19B Perforating Performance Testing
    "api rp 19b": "api_rp_19b",
    "api 19b": "api_rp_19b",
    "api rp19b": "api_rp_19b",
    "api19b": "api_rp_19b",
    "api test": "api_rp_19b",
    "api testing": "api_rp_19b",
    "perforating performance test": "api_rp_19b",
    "performance test": "api_rp_19b",
    "perforation test": "api_rp_19b",
    "test tunnel": "api_rp_19b",
    # Tubing-Conveyed Perforating (TCP) vs Wireline Operations
    "tcp": "tubing_conveyed_perforating",
    "tubing conveyed perforating": "tubing_conveyed_perforating",
    "tubing conveyed": "tubing_conveyed_perforating",
    "tcp system": "tubing_conveyed_perforating",
    "tcp gun": "tubing_conveyed_perforating",
    "wireline": "wireline_operations",
    "wireline perforating": "wireline_operations",
    "wireline gun": "wireline_operations",
    "wireline operation": "wireline_operations",
    "wireline conveyed": "wireline_operations",
    "wireline conveyed perforating": "wireline_operations",
    "slickline": "wireline_operations",
    "e-line": "wireline_operations",
    "electric line": "wireline_operations",
    # Perforation Friction Pressure Calculation
    "friction pressure calculation": "friction_pressure_calculation",
    "perforation friction pressure calculation": "friction_pressure_calculation",
    "perforation friction calculation": "friction_pressure_calculation",
    "friction calc": "friction_pressure_calculation",
    "friction calculation": "friction_pressure_calculation",
    "perforation pressure drop": "friction_pressure_calculation",
    "pressure drop": "friction_pressure_calculation",
    "entry pressure drop": "friction_pressure_calculation",
    "limited entry pressure drop": "friction_pressure_calculation",
    # Gun Debris Management and Wellbore Cleanout
    "gun debris": "gun_debris_management",
    "debris management": "gun_debris_management",
    "gun debris management": "gun_debris_management",
    "wellbore cleanout": "wellbore_cleanout",
    "cleanout": "wellbore_cleanout",
    "wellbore debris": "gun_debris_management",
    "debris removal": "wellbore_cleanout",
    "debris cleanout": "wellbore_cleanout",
    "gun debris cleanout": "wellbore_cleanout",
    # Oriented Perforating for Fracture Initiation
    "oriented perforating": "oriented_perforating",
    "orientation": "oriented_perforating",
    "perforation orientation": "oriented_perforating",
    "fracture initiation": "fracture_initiation",
    "initiation": "fracture_initiation",
    "fracture start": "fracture_initiation",
    "oriented gun": "oriented_perforating",
    "oriented charges": "oriented_perforating",
    "oriented perforation": "oriented_perforating",
    # Extreme Overbalanced Perforating (EOP)
    "extreme overbalanced perforating": "eop",
    "eop": "eop",
    "extreme overbalanced": "eop",
    "extreme overbalance": "eop",
    "extreme ob": "eop",
    # Cluster Efficiency in Plug-and-Perf Completions
    "cluster efficiency": "cluster_efficiency",
    "plug and perf": "plug_and_perf",
    "plug-and-perf": "plug_and_perf",
    "plug & perf": "plug_and_perf",
    "pnp": "plug_and_perf",
    "cluster": "cluster_efficiency",
    "cluster completion": "cluster_efficiency",
    "cluster design": "cluster_efficiency",
    "cluster spacing": "cluster_efficiency",
    "cluster count": "cluster_efficiency",
    "cluster efficiency plug and perf": "cluster_efficiency",
    # Perforation Design for Hydraulic Fracturing
    "perforation design": "perforation_design",
    "perf design": "perforation_design",
    "hydraulic fracturing": "hydraulic_fracturing",
    "frac": "hydraulic_fracturing",
    "fracking": "hydraulic_fracturing",
    "fracturing": "hydraulic_fracturing",
    "hydrofrac": "hydraulic_fracturing",
    "perf for frac": "perforation_design",
    "perforation for frac": "perforation_design",
    "perforation for fracturing": "perforation_design",
    "frac design": "hydraulic_fracturing",
    # Casing Gun vs Through-Tubing Gun Selection
    "casing gun": "casing_gun",
    "casing conveyed gun": "casing_gun",
    "casing conveyed": "casing_gun",
    "through tubing gun": "through_tubing_gun",
    "through-tubing gun": "through_tubing_gun",
    "tt gun": "through_tubing_gun",
    "ttg": "through_tubing_gun",
    "through tubing": "through_tubing_gun",
    "tt": "through_tubing_gun",
    "gun selection": "gun_selection",
    "perforating gun selection": "gun_selection",
    "gun choice": "gun_selection",
    # Perforation Erosion During Hydraulic Fracturing
    "perforation erosion": "perforation_erosion",
    "erosion": "perforation_erosion",
    "perf erosion": "perforation_erosion",
    "hole erosion": "perforation_erosion",
    "tunnel erosion": "perforation_erosion",
    "fracturing erosion": "perforation_erosion",
    # Perforating in HPHT (High Pressure High Temperature) Environments
    "hpht": "hpht",
    "high pressure high temperature": "hpht",
    "high pressure": "hpht",
    "high temperature": "hpht",
    "hpht perforating": "hpht",
    "hpht environment": "hpht",
    "hpht well": "hpht",
    # Propellant-Assisted Perforating Systems
    "propellant assisted perforating": "propellant_assisted_perforating",
    "propellant-assisted perforating": "propellant_assisted_perforating",
    "propellant perforating": "propellant_assisted_perforating",
    "propellant system": "propellant_assisted_perforating",
    "propellant": "propellant_assisted_perforating",
    "propellant charge": "propellant_assisted_perforating",
    "propellant gun": "propellant_assisted_perforating",
    # Abrasive Jetting as Perforating Alternative
    "abrasive jetting": "abrasive_jetting",
    "abrasive perforating": "abrasive_jetting",
    "abrasive jet": "abrasive_jetting",
    "abrasive": "abrasive_jetting",
    "abrasive system": "abrasive_jetting",
    "abrasive alternative": "abrasive_jetting",
    "abrasive perforation": "abrasive_jetting",
    "abrasive jetting perforation": "abrasive_jetting",
    # Gun Loading and Safety Procedures
    "gun loading": "gun_loading",
    "loading gun": "gun_loading",
    "charge loading": "gun_loading",
    "charge assembly": "gun_loading",
    "gun assembly": "gun_loading",
    "gun safety": "gun_safety",
    "safety procedure": "gun_safety",
    "safety procedures": "gun_safety",
    "gun safety procedure": "gun_safety",
    "gun safety procedures": "gun_safety",
    "charge safety": "gun_safety",
    "loading safety": "gun_safety",
    # Misspellings, abbreviations, and related terms
    "perforaton": "perforation_design",
    "perforatng": "perforation_design",
    "perforate": "perforation_design",
    "perforater": "charge_design",
    "perforat": "perforation_design",
    "perf": "perforation_design",
    "perfs": "perforation_design",
    "perforations": "perforation_design",
    "perforating": "perforation_design",
    "perforation": "perforation_design",
    "perforated": "perforation_design",
    "gun": "charge_design",
    "guns": "charge_design",
    "charges": "charge_design",
    "charge": "charge_design",
    "tunnel": "deep_penetrating_charge",
    "tunnels": "deep_penetrating_charge",
    "clustered": "cluster_efficiency",
    "clusters": "cluster_efficiency",
    "phased": "phasing",
    "phased gun": "phasing",
    "phased charges": "phasing",
    "phased perforating": "phasing",
    "phased perforation": "phasing",
    "phased guns": "phasing",
    "phased system": "phasing",
    "phased design": "phasing",
    "shot": "shot_density",
    "shots": "shot_density",
    "density": "shot_density",
    "entry": "limited_entry",
    "diversion": "friction_diversion",
    "diverting": "friction_diversion",
    "divert": "friction_diversion",
    "clean": "wellbore_cleanout",
    "cleaning": "wellbore_cleanout",
    "clean out": "wellbore_cleanout",
    "clean-out": "wellbore_cleanout",
    "removal": "wellbore_cleanout",
    "removing": "wellbore_cleanout",
    "test": "api_rp_19b",
    "testing": "api_rp_19b",
    "performance": "charge_performance",
    "efficiency": "cluster_efficiency",
    "design": "perforation_design",
    "selection": "gun_selection",
    "choice": "gun_selection",
    "method": "friction_diversion",
    "procedure": "gun_safety",
    "procedures": "gun_safety",
    "safety": "gun_safety",
    "orientation": "oriented_perforating",
    "initiate": "fracture_initiation",
    "initiation": "fracture_initiation",
    "fracture": "hydraulic_fracturing",
    "fractures": "hydraulic_fracturing",
    "frac job": "hydraulic_fracturing",
    "frac jobs": "hydraulic_fracturing",
    "hydrofracking": "hydraulic_fracturing",
    "hydro-frac": "hydraulic_fracturing",
    "hydro-fracking": "hydraulic_fracturing",
    "hydrofrac": "hydraulic_fracturing",
    "hydrofrac job": "hydraulic_fracturing",
    "hydrofrac jobs": "hydraulic_fracturing",
    "plug": "plug_and_perf",
    "plugs": "plug_and_perf",
    "perf plug": "plug_and_perf",
    "perf plugs": "plug_and_perf",
    "plug perf": "plug_and_perf",
    "plugging": "plug_and_perf",
    "completion": "plug_and_perf",
    "completions": "plug_and_perf",
}

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    concat = unicodedata.normalize("NFKD", concat)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = unicodedata.normalize("NFKD", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    return [k for k, v in SEMANTIC_MAP.items() if v == norm]

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)