import hashlib
import re
from collections import defaultdict

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "W06 Engine Team"
SEMANTIC_MAP_ENGINE = "W06_seismicity_risk_assessor"
_EXPECTED_ENTRY_COUNT = 213

SEMANTIC_MAP = {
    # Induced Seismicity Mechanisms
    "induced seismicity": "induced_seismicity",
    "triggered seismicity": "induced_seismicity",
    "anthropogenic seismicity": "induced_seismicity",
    "man-made earthquakes": "induced_seismicity",
    "human-caused earthquakes": "induced_seismicity",
    "seismicity mechanisms": "induced_seismicity_mechanisms",
    "mechanisms of induced seismicity": "induced_seismicity_mechanisms",
    "seismicity mechanism": "induced_seismicity_mechanisms",
    "induced earthquake": "induced_seismicity",
    "induced earthquakes": "induced_seismicity",
    "injection-induced seismicity": "induced_seismicity",
    "reservoir-induced seismicity": "induced_seismicity",
    "RIS": "reservoir_induced_seismicity",
    "hydraulic fracturing seismicity": "induced_seismicity",
    "fracking seismicity": "induced_seismicity",
    "hydrofracturing seismicity": "induced_seismicity",
    "wastewater injection seismicity": "induced_seismicity",
    "fluid injection seismicity": "induced_seismicity",
    "fluid-induced seismicity": "induced_seismicity",
    "injection seismicity": "induced_seismicity",
    "seismic hazard": "seismic_hazard",
    "seismic risk": "seismic_risk",
    "earthquake risk": "seismic_risk",
    "earthquake hazard": "seismic_hazard",
    "seismic hazard assessment": "seismic_hazard_assessment",
    "seismic risk assessment": "seismic_risk_assessment",
    "seismic hazard mapping": "seismic_hazard_mapping",
    "hazard mapping": "seismic_hazard_mapping",
    "risk mapping": "seismic_hazard_mapping",
    "hazard map": "seismic_hazard_mapping",
    "risk map": "seismic_hazard_mapping",

    # RRC Seismicity Response Plan
    "rrc seismicity response plan": "rrc_seismicity_response_plan",
    "response plan": "rrc_seismicity_response_plan",
    "seismicity response plan": "rrc_seismicity_response_plan",
    "rrc response plan": "rrc_seismicity_response_plan",
    "texas response plan": "rrc_seismicity_response_plan",
    "rrc srp": "rrc_seismicity_response_plan",
    "seismic response plan": "rrc_seismicity_response_plan",

    # Traffic Light Protocol
    "traffic light protocol": "traffic_light_protocol",
    "tlp": "traffic_light_protocol",
    "traffic light system": "traffic_light_protocol",
    "traffic light": "traffic_light_protocol",
    "seismic traffic light": "traffic_light_protocol",
    "traffic light thresholds": "traffic_light_protocol",
    "traffic light levels": "traffic_light_protocol",
    "traffic light triggers": "traffic_light_protocol",
    "traffic light actions": "traffic_light_protocol",
    "traffic light response": "traffic_light_protocol",
    "traffic light criteria": "traffic_light_protocol",

    # TexNet Seismic Monitoring
    "texnet": "texnet_seismic_monitoring",
    "texnet seismic monitoring": "texnet_seismic_monitoring",
    "texnet monitoring": "texnet_seismic_monitoring",
    "texnet network": "texnet_seismic_monitoring",
    "texnet stations": "texnet_seismic_monitoring",
    "texnet sensors": "texnet_seismic_monitoring",
    "texnet array": "texnet_seismic_monitoring",
    "texnet data": "texnet_seismic_monitoring",
    "texnet catalog": "texnet_seismic_monitoring",
    "texnet events": "texnet_seismic_monitoring",
    "texnet earthquake catalog": "texnet_seismic_monitoring",

    # Historical Seismicity Baseline
    "historical seismicity": "historical_seismicity_baseline",
    "historical baseline": "historical_seismicity_baseline",
    "seismicity baseline": "historical_seismicity_baseline",
    "baseline seismicity": "historical_seismicity_baseline",
    "baseline earthquakes": "historical_seismicity_baseline",
    "historical earthquake data": "historical_seismicity_baseline",
    "historical earthquake catalog": "historical_seismicity_baseline",
    "historical seismicity data": "historical_seismicity_baseline",
    "historical seismicity catalog": "historical_seismicity_baseline",

    # Gutenberg-Richter b-value Analysis
    "gutenberg-richter": "gutenberg_richter_b_value_analysis",
    "gutenberg-richter law": "gutenberg_richter_b_value_analysis",
    "gutenberg richter": "gutenberg_richter_b_value_analysis",
    "gr law": "gutenberg_richter_b_value_analysis",
    "gr analysis": "gutenberg_richter_b_value_analysis",
    "b-value": "gutenberg_richter_b_value_analysis",
    "b value": "gutenberg_richter_b_value_analysis",
    "bvalue": "gutenberg_richter_b_value_analysis",
    "gutenberg-richter b-value": "gutenberg_richter_b_value_analysis",
    "gutenberg richter b value": "gutenberg_richter_b_value_analysis",
    "b-value analysis": "gutenberg_richter_b_value_analysis",
    "b-value calculation": "gutenberg_richter_b_value_analysis",
    "b-value estimation": "gutenberg_richter_b_value_analysis",
    "magnitude-frequency relationship": "gutenberg_richter_b_value_analysis",
    "magnitude frequency relationship": "gutenberg_richter_b_value_analysis",
    "magnitude-frequency distribution": "gutenberg_richter_b_value_analysis",
    "mfd": "gutenberg_richter_b_value_analysis",

    # Fault Proximity Assessment
    "fault proximity": "fault_proximity_assessment",
    "fault proximity assessment": "fault_proximity_assessment",
    "distance to fault": "fault_proximity_assessment",
    "fault distance": "fault_proximity_assessment",
    "proximity to fault": "fault_proximity_assessment",
    "fault mapping": "fault_proximity_assessment",
    "fault map": "fault_proximity_assessment",
    "fault location": "fault_proximity_assessment",
    "fault geometry": "fault_proximity_assessment",
    "fault identification": "fault_proximity_assessment",
    "fault characterization": "fault_proximity_assessment",
    "fault zone": "fault_proximity_assessment",
    "active fault": "fault_proximity_assessment",
    "active faults": "fault_proximity_assessment",
    "mapped faults": "fault_proximity_assessment",
    "fault database": "fault_proximity_assessment",

    # Coulomb Stress Transfer
    "coulomb stress": "coulomb_stress_transfer",
    "coulomb stress transfer": "coulomb_stress_transfer",
    "coulomb failure stress": "coulomb_stress_transfer",
    "coulomb stress change": "coulomb_stress_transfer",
    "coulomb stress modeling": "coulomb_stress_transfer",
    "coulomb stress analysis": "coulomb_stress_transfer",
    "coulomb stress calculation": "coulomb_stress_transfer",
    "coulomb stress increase": "coulomb_stress_transfer",
    "coulomb stress decrease": "coulomb_stress_transfer",
    "coulomb stress effect": "coulomb_stress_transfer",
    "coulomb stress impact": "coulomb_stress_transfer",
    "stress transfer": "coulomb_stress_transfer",
    "stress triggering": "coulomb_stress_transfer",
    "stress change": "coulomb_stress_transfer",
    "stress modeling": "coulomb_stress_transfer",

    # Pore Pressure Diffusion
    "pore pressure": "pore_pressure_diffusion",
    "pore pressure diffusion": "pore_pressure_diffusion",
    "pore pressure increase": "pore_pressure_diffusion",
    "pore pressure decrease": "pore_pressure_diffusion",
    "pore pressure change": "pore_pressure_diffusion",
    "pore pressure modeling": "pore_pressure_diffusion",
    "pore pressure analysis": "pore_pressure_diffusion",
    "pore pressure calculation": "pore_pressure_diffusion",
    "pore pressure propagation": "pore_pressure_diffusion",
    "fluid pressure": "pore_pressure_diffusion",
    "fluid pressure diffusion": "pore_pressure_diffusion",
    "fluid pressure increase": "pore_pressure_diffusion",
    "fluid pressure decrease": "pore_pressure_diffusion",
    "fluid pressure change": "pore_pressure_diffusion",
    "pressure diffusion": "pore_pressure_diffusion",
    "pressure propagation": "pore_pressure_diffusion",

    # Injection Volume-Seismicity Correlation
    "injection volume": "injection_volume_seismicity_correlation",
    "injection volumes": "injection_volume_seismicity_correlation",
    "volume injected": "injection_volume_seismicity_correlation",
    "injected volume": "injection_volume_seismicity_correlation",
    "volume of injection": "injection_volume_seismicity_correlation",
    "injection volume correlation": "injection_volume_seismicity_correlation",
    "injection volume-seismicity correlation": "injection_volume_seismicity_correlation",
    "injection volume seismicity correlation": "injection_volume_seismicity_correlation",
    "injection volume relationship": "injection_volume_seismicity_correlation",
    "injection volume effect": "injection_volume_seismicity_correlation",
    "injection volume impact": "injection_volume_seismicity_correlation",
    "injection volume analysis": "injection_volume_seismicity_correlation",
    "injection volume calculation": "injection_volume_seismicity_correlation",
    "injection volume estimation": "injection_volume_seismicity_correlation",

    # Magnitude-Frequency Relationships
    "magnitude-frequency relationship": "magnitude_frequency_relationships",
    "magnitude frequency relationship": "magnitude_frequency_relationships",
    "magnitude-frequency distribution": "magnitude_frequency_relationships",
    "magnitude frequency distribution": "magnitude_frequency_relationships",
    "magnitude-frequency curve": "magnitude_frequency_relationships",
    "magnitude frequency curve": "magnitude_frequency_relationships",
    "magnitude-frequency plot": "magnitude_frequency_relationships",
    "magnitude frequency plot": "magnitude_frequency_relationships",
    "magnitude-frequency analysis": "magnitude_frequency_relationships",
    "magnitude frequency analysis": "magnitude_frequency_relationships",
    "mfd": "magnitude_frequency_relationships",

    # Seismic Moment Calculations
    "seismic moment": "seismic_moment_calculations",
    "seismic moment calculation": "seismic_moment_calculations",
    "seismic moment estimation": "seismic_moment_calculations",
    "seismic moment analysis": "seismic_moment_calculations",
    "moment magnitude": "seismic_moment_calculations",
    "moment magnitude calculation": "seismic_moment_calculations",
    "moment magnitude estimation": "seismic_moment_calculations",
    "moment magnitude analysis": "seismic_moment_calculations",
    "mw": "seismic_moment_calculations",
    "moment calculation": "seismic_moment_calculations",
    "moment estimation": "seismic_moment_calculations",
    "moment analysis": "seismic_moment_calculations",

    # Ground Motion Prediction
    "ground motion": "ground_motion_prediction",
    "ground motion prediction": "ground_motion_prediction",
    "ground motion model": "ground_motion_prediction",
    "ground motion modeling": "ground_motion_prediction",
    "ground motion analysis": "ground_motion_prediction",
    "ground motion calculation": "ground_motion_prediction",
    "ground motion estimation": "ground_motion_prediction",
    "gmp": "ground_motion_prediction",
    "ground shaking": "ground_motion_prediction",
    "shaking prediction": "ground_motion_prediction",
    "shaking model": "ground_motion_prediction",
    "shaking analysis": "ground_motion_prediction",
    "shaking calculation": "ground_motion_prediction",

    # PGA/PGV Thresholds
    "pga": "pga_pgv_thresholds",
    "peak ground acceleration": "pga_pgv_thresholds",
    "pga threshold": "pga_pgv_thresholds",
    "pga thresholds": "pga_pgv_thresholds",
    "pga value": "pga_pgv_thresholds",
    "pga values": "pga_pgv_thresholds",
    "pgv": "pga_pgv_thresholds",
    "peak ground velocity": "pga_pgv_thresholds",
    "pgv threshold": "pga_pgv_thresholds",
    "pgv thresholds": "pga_pgv_thresholds",
    "pgv value": "pga_pgv_thresholds",
    "pgv values": "pga_pgv_thresholds",
    "ground acceleration": "pga_pgv_thresholds",
    "ground velocity": "pga_pgv_thresholds",
    "acceleration threshold": "pga_pgv_thresholds",
    "velocity threshold": "pga_pgv_thresholds",

    # Building Damage Assessment
    "building damage": "building_damage_assessment",
    "building damage assessment": "building_damage_assessment",
    "damage assessment": "building_damage_assessment",
    "structural damage": "building_damage_assessment",
    "structural damage assessment": "building_damage_assessment",
    "building impact": "building_damage_assessment",
    "building impact assessment": "building_damage_assessment",
    "damage estimation": "building_damage_assessment",
    "damage calculation": "building_damage_assessment",
    "damage analysis": "building_damage_assessment",
    "building vulnerability": "building_damage_assessment",
    "building vulnerability assessment": "building_damage_assessment",
    "building risk": "building_damage_assessment",
    "building risk assessment": "building_damage_assessment",

    # RRC Rule 46 Compliance
    "rrc rule 46": "rrc_rule_46_compliance",
    "rule 46": "rrc_rule_46_compliance",
    "rrc compliance": "rrc_rule_46_compliance",
    "rule 46 compliance": "rrc_rule_46_compliance",
    "rrc rule compliance": "rrc_rule_46_compliance",
    "rrc regulation 46": "rrc_rule_46_compliance",
    "rrc regulation": "rrc_rule_46_compliance",
    "rrc regulatory compliance": "rrc_rule_46_compliance",
    "regulatory compliance": "rrc_rule_46_compliance",
    "regulation 46": "rrc_rule_46_compliance",
    "regulation compliance": "rrc_rule_46_compliance",

    # Operator Notification Requirements
    "operator notification": "operator_notification_requirements",
    "notification requirements": "operator_notification_requirements",
    "operator notification requirements": "operator_notification_requirements",
    "notification protocol": "operator_notification_requirements",
    "notification procedure": "operator_notification_requirements",
    "notification process": "operator_notification_requirements",
    "notification criteria": "operator_notification_requirements",
    "operator notification protocol": "operator_notification_requirements",
    "operator notification procedure": "operator_notification_requirements",
    "operator notification process": "operator_notification_requirements",
    "operator notification criteria": "operator_notification_requirements",
    "operator reporting": "operator_notification_requirements",
    "operator reporting requirements": "operator_notification_requirements",
    "reporting requirements": "operator_notification_requirements",

    # Injection Rate Reduction Protocols
    "injection rate": "injection_rate_reduction_protocols",
    "injection rate reduction": "injection_rate_reduction_protocols",
    "injection rate reduction protocol": "injection_rate_reduction_protocols",
    "injection rate reduction protocols": "injection_rate_reduction_protocols",
    "rate reduction": "injection_rate_reduction_protocols",
    "rate reduction protocol": "injection_rate_reduction_protocols",
    "rate reduction protocols": "injection_rate_reduction_protocols",
    "injection reduction": "injection_rate_reduction_protocols",
    "injection reduction protocol": "injection_rate_reduction_protocols",
    "injection reduction protocols": "injection_rate_reduction_protocols",
    "reduction protocol": "injection_rate_reduction_protocols",
    "reduction protocols": "injection_rate_reduction_protocols",

    # Well Suspension Criteria
    "well suspension": "well_suspension_criteria",
    "well suspension criteria": "well_suspension_criteria",
    "well shut-in": "well_suspension_criteria",
    "well shut in": "well_suspension_criteria",
    "well shut-in criteria": "well_suspension_criteria",
    "well shut in criteria": "well_suspension_criteria",
    "well closure": "well_suspension_criteria",
    "well closure criteria": "well_suspension_criteria",
    "well suspension protocol": "well_suspension_criteria",
    "well suspension protocols": "well_suspension_criteria",
    "well shut-in protocol": "well_suspension_criteria",
    "well shut in protocol": "well_suspension_criteria",
    "well shut-in protocols": "well_suspension_criteria",
    "well shut in protocols": "well_suspension_criteria",
    "well closure protocol": "well_suspension_criteria",
    "well closure protocols": "well_suspension_criteria",

    # Seismic Hazard Mapping
    "seismic hazard mapping": "seismic_hazard_mapping",
    "hazard mapping": "seismic_hazard_mapping",
    "risk mapping": "seismic_hazard_mapping",
    "hazard map": "seismic_hazard_mapping",
    "risk map": "seismic_hazard_mapping",
    "seismic risk mapping": "seismic_hazard_mapping",
    "seismic map": "seismic_hazard_mapping",
    "seismic mapping": "seismic_hazard_mapping",
    "earthquake hazard mapping": "seismic_hazard_mapping",
    "earthquake risk mapping": "seismic_hazard_mapping",

    # Misspellings & Synonyms
    "seismicity": "induced_seismicity",
    "seismisity": "induced_seismicity",
    "seismcity": "induced_seismicity",
    "seismicty": "induced_seismicity",
    "seismic": "induced_seismicity",
    "earthquake": "induced_seismicity",
    "earthquakes": "induced_seismicity",
    "quake": "induced_seismicity",
    "quakes": "induced_seismicity",
    "eq": "induced_seismicity",
    "eqs": "induced_seismicity",
    "event": "induced_seismicity",
    "events": "induced_seismicity",
    "microseismicity": "induced_seismicity",
    "microseismic": "induced_seismicity",
    "microearthquake": "induced_seismicity",
    "microearthquakes": "induced_seismicity",
    "microquake": "induced_seismicity",
    "microquakes": "induced_seismicity",

    # Related Terms
    "triggering mechanism": "induced_seismicity_mechanisms",
    "triggering mechanisms": "induced_seismicity_mechanisms",
    "mechanism": "induced_seismicity_mechanisms",
    "mechanisms": "induced_seismicity_mechanisms",
    "response": "rrc_seismicity_response_plan",
    "response plan": "rrc_seismicity_response_plan",
    "protocol": "traffic_light_protocol",
    "protocols": "traffic_light_protocol",
    "monitoring": "texnet_seismic_monitoring",
    "monitor": "texnet_seismic_monitoring",
    "baseline": "historical_seismicity_baseline",
    "analysis": "gutenberg_richter_b_value_analysis",
    "assessment": "seismic_hazard_assessment",
    "mapping": "seismic_hazard_mapping",
    "compliance": "rrc_rule_46_compliance",
    "notification": "operator_notification_requirements",
    "reduction": "injection_rate_reduction_protocols",
    "suspension": "well_suspension_criteria",
    "criteria": "well_suspension_criteria",
    "moment": "seismic_moment_calculations",
    "prediction": "ground_motion_prediction",
    "thresholds": "pga_pgv_thresholds",
    "damage": "building_damage_assessment",
    "risk": "seismic_risk",
    "hazard": "seismic_hazard",

    # Extra Synonyms & Misspellings
    "seismicity risk": "seismic_risk",
    "seismic risk assessor": "seismic_risk_assessment",
    "risk assessor": "seismic_risk_assessment",
    "risk assessment": "seismic_risk_assessment",
    "hazard assessment": "seismic_hazard_assessment",
    "hazard assessor": "seismic_hazard_assessment",
    "hazard risk": "seismic_hazard",
    "hazard risk assessment": "seismic_hazard_assessment",
    "risk hazard": "seismic_hazard",
    "risk hazard assessment": "seismic_hazard_assessment",
    "seismic hazard assessor": "seismic_hazard_assessment",
    "seismic hazard risk": "seismic_hazard",
    "seismic hazard risk assessment": "seismic_hazard_assessment",
    "seismic risk mapping": "seismic_hazard_mapping",
    "seismic risk map": "seismic_hazard_mapping",
    "seismic hazard map": "seismic_hazard_mapping",
    "earthquake risk map": "seismic_hazard_mapping",
    "earthquake hazard map": "seismic_hazard_mapping",
    "earthquake mapping": "seismic_hazard_mapping",
    "earthquake map": "seismic_hazard_mapping",
    "earthquake risk assessor": "seismic_risk_assessment",
    "earthquake hazard assessor": "seismic_hazard_assessment",
    "earthquake risk assessment": "seismic_risk_assessment",
    "earthquake hazard assessment": "seismic_hazard_assessment",
    "earthquake risk": "seismic_risk",
    "earthquake hazard": "seismic_hazard",
    "earthquake notification": "operator_notification_requirements",
    "earthquake notification requirements": "operator_notification_requirements",
    "earthquake notification protocol": "operator_notification_requirements",
    "earthquake notification procedure": "operator_notification_requirements",
    "earthquake notification process": "operator_notification_requirements",
    "earthquake notification criteria": "operator_notification_requirements",
    "earthquake reporting": "operator_notification_requirements",
    "earthquake reporting requirements": "operator_notification_requirements",
    "earthquake reporting protocol": "operator_notification_requirements",
    "earthquake reporting procedure": "operator_notification_requirements",
    "earthquake reporting process": "operator_notification_requirements",
    "earthquake reporting criteria": "operator_notification_requirements",
    "earthquake reduction": "injection_rate_reduction_protocols",
    "earthquake reduction protocol": "injection_rate_reduction_protocols",
    "earthquake reduction protocols": "injection_rate_reduction_protocols",
    "earthquake suspension": "well_suspension_criteria",
    "earthquake suspension criteria": "well_suspension_criteria",
    "earthquake suspension protocol": "well_suspension_criteria",
    "earthquake suspension protocols": "well_suspension_criteria",
    "earthquake shut-in": "well_suspension_criteria",
    "earthquake shut in": "well_suspension_criteria",
    "earthquake shut-in criteria": "well_suspension_criteria",
    "earthquake shut in criteria": "well_suspension_criteria",
    "earthquake shut-in protocol": "well_suspension_criteria",
    "earthquake shut in protocol": "well_suspension_criteria",
    "earthquake shut-in protocols": "well_suspension_criteria",
    "earthquake shut in protocols": "well_suspension_criteria",
    "earthquake closure": "well_suspension_criteria",
    "earthquake closure criteria": "well_suspension_criteria",
    "earthquake closure protocol": "well_suspension_criteria",
    "earthquake closure protocols": "well_suspension_criteria",
    "earthquake moment": "seismic_moment_calculations",
    "earthquake moment calculation": "seismic_moment_calculations",
    "earthquake moment estimation": "seismic_moment_calculations",
    "earthquake moment analysis": "seismic_moment_calculations",
    "earthquake moment magnitude": "seismic_moment_calculations",
    "earthquake moment magnitude calculation": "seismic_moment_calculations",
    "earthquake moment magnitude estimation": "seismic_moment_calculations",
    "earthquake moment magnitude analysis": "seismic_moment_calculations",
    "earthquake ground motion": "ground_motion_prediction",
    "earthquake ground motion prediction": "ground_motion_prediction",
    "earthquake ground motion model": "ground_motion_prediction",
    "earthquake ground motion modeling": "ground_motion_prediction",
    "earthquake ground motion analysis": "ground_motion_prediction",
    "earthquake ground motion calculation": "ground_motion_prediction",
    "earthquake ground motion estimation": "ground_motion_prediction",
    "earthquake shaking": "ground_motion_prediction",
    "earthquake shaking prediction": "ground_motion_prediction",
    "earthquake shaking model": "ground_motion_prediction",
    "earthquake shaking analysis": "ground_motion_prediction",
    "earthquake shaking calculation": "ground_motion_prediction",
    "earthquake pga": "pga_pgv_thresholds",
    "earthquake peak ground acceleration": "pga_pgv_thresholds",
    "earthquake pga threshold": "pga_pgv_thresholds",
    "earthquake pga thresholds": "pga_pgv_thresholds",
    "earthquake pga value": "pga_pgv_thresholds",
    "earthquake pga values": "pga_pgv_thresholds",
    "earthquake pgv": "pga_pgv_thresholds",
    "earthquake peak ground velocity": "pga_pgv_thresholds",
    "earthquake pgv threshold": "pga_pgv_thresholds",
    "earthquake pgv thresholds": "pga_pgv_thresholds",
    "earthquake pgv value": "pga_pgv_thresholds",
    "earthquake pgv values": "pga_pgv_thresholds",
    "earthquake ground acceleration": "pga_pgv_thresholds",
    "earthquake ground velocity": "pga_pgv_thresholds",
    "earthquake acceleration threshold": "pga_pgv_thresholds",
    "earthquake velocity threshold": "pga_pgv_thresholds",
    "earthquake building damage": "building_damage_assessment",
    "earthquake building damage assessment": "building_damage_assessment",
    "earthquake damage assessment": "building_damage_assessment",
    "earthquake structural damage": "building_damage_assessment",
    "earthquake structural damage assessment": "building_damage_assessment",
    "earthquake building impact": "building_damage_assessment",
    "earthquake building impact assessment": "building_damage_assessment",
    "earthquake damage estimation": "building_damage_assessment",
    "earthquake damage calculation": "building_damage_assessment",
    "earthquake damage analysis": "building_damage_assessment",
    "earthquake building vulnerability": "building_damage_assessment",
    "earthquake building vulnerability assessment": "building_damage_assessment",
    "earthquake building risk": "building_damage_assessment",
    "earthquake building risk assessment": "building_damage_assessment",
    "earthquake compliance": "rrc_rule_46_compliance",
    "earthquake rule 46": "rrc_rule_46_compliance",
    "earthquake rule 46 compliance": "rrc_rule_46_compliance",
    "earthquake regulatory compliance": "rrc_rule_46_compliance",
    "earthquake regulation 46": "rrc_rule_46_compliance",
    "earthquake regulation": "rrc_rule_46_compliance",
    "earthquake regulation compliance": "rrc_rule_46_compliance",
}

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"[^a-z0-9 _\-]", "", t)
    return SEMANTIC_MAP.get(t, t.replace(" ", "_"))

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)