import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PROD06 Team"
SEMANTIC_MAP_ENGINE = "PROD06_water_cut_analysis"

SEMANTIC_MAP = {
    # Water Cut Definition and Calculation
    "water cut": "water_cut",
    "watercut": "water_cut",
    "wc": "water_cut",
    "water fraction": "water_cut",
    "produced water fraction": "water_cut",
    "water content": "water_cut",
    "water percentage": "water_cut",
    "water percent": "water_cut",
    "water production ratio": "water_cut",
    "water/oil ratio": "water_oil_ratio",
    "wor": "water_oil_ratio",
    "oil/water ratio": "oil_water_ratio",
    "owr": "oil_water_ratio",
    "liquid rate": "liquid_rate",
    "total fluid rate": "liquid_rate",
    "fluid production rate": "liquid_rate",
    "oil rate": "oil_rate",
    "oil production rate": "oil_rate",
    "oil cut": "oil_cut",
    "oil fraction": "oil_cut",
    "oil percent": "oil_cut",
    "oil percentage": "oil_cut",
    "bsw": "basic_sediment_and_water",
    "basic sediment and water": "basic_sediment_and_water",
    "sediment and water": "basic_sediment_and_water",
    "bs&w": "basic_sediment_and_water",
    "bsw measurement": "basic_sediment_and_water",
    "bsw test": "basic_sediment_and_water",
    "bsw analysis": "basic_sediment_and_water",
    "water cut test": "water_cut_test",
    "water cut measurement": "water_cut_test",
    "water cut analysis": "water_cut_analysis",
    "water cut determination": "water_cut_analysis",
    "water cut calculation": "water_cut_analysis",
    "water cut estimation": "water_cut_analysis",
    "water cut evaluation": "water_cut_analysis",
    "water cut monitoring": "water_cut_monitoring",
    "water cut tracking": "water_cut_monitoring",
    "water cut trend": "water_cut_trend",
    "water cut profile": "water_cut_profile",
    "water cut curve": "water_cut_curve",
    "water cut history": "water_cut_history",
    "water cut forecast": "water_cut_forecast",
    "water cut prediction": "water_cut_forecast",
    "water cut modeling": "water_cut_modeling",
    "water cut simulation": "water_cut_modeling",

    # BSW Measurement Techniques - Centrifuge Method
    "centrifuge method": "centrifuge_method",
    "centrifuge test": "centrifuge_method",
    "centrifuge analysis": "centrifuge_method",
    "bsw centrifuge": "centrifuge_method",
    "water cut centrifuge": "centrifuge_method",
    "manual centrifuge": "centrifuge_method",
    "field centrifuge": "centrifuge_method",
    "lab centrifuge": "centrifuge_method",
    "centrifuge tube": "centrifuge_tube",
    "centrifuge tube reading": "centrifuge_tube",
    "centrifuge reading": "centrifuge_tube",
    "centrifuge sample": "centrifuge_sample",
    "centrifuge sample preparation": "centrifuge_sample",
    "centrifuge separation": "centrifuge_separation",
    "centrifugation": "centrifuge_separation",

    # Karl Fischer Titration for Water Content
    "karl fischer titration": "karl_fischer_titration",
    "kf titration": "karl_fischer_titration",
    "karl fischer": "karl_fischer_titration",
    "karl fischer method": "karl_fischer_titration",
    "kf method": "karl_fischer_titration",
    "kf analysis": "karl_fischer_titration",
    "kf test": "karl_fischer_titration",
    "water content titration": "karl_fischer_titration",
    "water content analysis": "water_content_analysis",
    "water content measurement": "water_content_analysis",

    # Waterflood Performance - Buckley-Leverett Theory
    "waterflood": "waterflood",
    "waterflooding": "waterflood",
    "waterflood performance": "waterflood_performance",
    "waterflood analysis": "waterflood_performance",
    "waterflood evaluation": "waterflood_performance",
    "waterflood monitoring": "waterflood_monitoring",
    "waterflood trend": "waterflood_trend",
    "waterflood history": "waterflood_history",
    "waterflood forecast": "waterflood_forecast",
    "waterflood prediction": "waterflood_forecast",
    "waterflood modeling": "waterflood_modeling",
    "waterflood simulation": "waterflood_modeling",
    "buckley-leverett": "buckley_leverett_theory",
    "buckley leverett": "buckley_leverett_theory",
    "buckley leverett theory": "buckley_leverett_theory",
    "bl theory": "buckley_leverett_theory",
    "fractional flow theory": "buckley_leverett_theory",
    "fractional flow": "fractional_flow",
    "fractional flow curve": "fractional_flow_curve",
    "fractional flow analysis": "fractional_flow_analysis",
    "fractional flow modeling": "fractional_flow_modeling",
    "fractional flow simulation": "fractional_flow_modeling",

    # Water Breakthrough Prediction - Channel and Frontal Advance
    "water breakthrough": "water_breakthrough",
    "breakthrough": "water_breakthrough",
    "breakthrough prediction": "water_breakthrough_prediction",
    "water breakthrough prediction": "water_breakthrough_prediction",
    "breakthrough analysis": "water_breakthrough_analysis",
    "breakthrough modeling": "water_breakthrough_modeling",
    "breakthrough simulation": "water_breakthrough_modeling",
    "channel advance": "channel_advance",
    "frontal advance": "frontal_advance",
    "water channeling": "channel_advance",
    "water front": "frontal_advance",
    "water front advance": "frontal_advance",
    "water front movement": "frontal_advance",
    "water front propagation": "frontal_advance",
    "water front breakthrough": "water_breakthrough",

    # Chan Diagnostic Plots for Water Production Analysis
    "chan plot": "chan_plot",
    "chan diagnostic plot": "chan_plot",
    "chan diagnostic": "chan_plot",
    "chan analysis": "chan_plot",
    "chan method": "chan_plot",
    "chan technique": "chan_plot",
    "chan water production": "chan_plot",
    "chan water cut": "chan_plot",
    "chan water analysis": "chan_plot",
    "chan water plot": "chan_plot",
    "chan water production plot": "chan_plot",
    "chan water cut plot": "chan_plot",

    # Water Coning in Vertical Wells
    "water coning": "water_coning",
    "coning": "water_coning",
    "water coning analysis": "water_coning_analysis",
    "water coning modeling": "water_coning_modeling",
    "water coning simulation": "water_coning_modeling",
    "vertical well coning": "water_coning",
    "vertical well water coning": "water_coning",
    "vertical well": "vertical_well",
    "vertical well analysis": "vertical_well_analysis",
    "vertical well modeling": "vertical_well_modeling",
    "vertical well simulation": "vertical_well_modeling",

    # Produced Water Handling and Treatment
    "produced water": "produced_water",
    "produced water handling": "produced_water_handling",
    "produced water management": "produced_water_handling",
    "produced water treatment": "produced_water_treatment",
    "produced water disposal": "produced_water_disposal",
    "produced water injection": "produced_water_injection",
    "produced water reinjection": "produced_water_injection",
    "produced water recycling": "produced_water_recycling",
    "produced water reuse": "produced_water_recycling",
    "produced water quality": "produced_water_quality",
    "produced water quality analysis": "produced_water_quality_analysis",
    "produced water quality measurement": "produced_water_quality_analysis",
    "produced water quality monitoring": "produced_water_quality_monitoring",
    "produced water quality control": "produced_water_quality_control",

    # Injection Water Quality Requirements
    "injection water": "injection_water",
    "injection water quality": "injection_water_quality",
    "injection water quality requirements": "injection_water_quality_requirements",
    "injection water quality analysis": "injection_water_quality_analysis",
    "injection water quality measurement": "injection_water_quality_analysis",
    "injection water quality monitoring": "injection_water_quality_monitoring",
    "injection water quality control": "injection_water_quality_control",
    "injection water treatment": "injection_water_treatment",
    "injection water handling": "injection_water_handling",
    "injection water management": "injection_water_handling",

    # Water-Oil Ratio (WOR) Decline Analysis
    "wor analysis": "water_oil_ratio_analysis",
    "water oil ratio analysis": "water_oil_ratio_analysis",
    "wor decline": "water_oil_ratio_decline",
    "water oil ratio decline": "water_oil_ratio_decline",
    "wor decline analysis": "water_oil_ratio_decline_analysis",
    "water oil ratio decline analysis": "water_oil_ratio_decline_analysis",
    "wor trend": "water_oil_ratio_trend",
    "water oil ratio trend": "water_oil_ratio_trend",
    "wor history": "water_oil_ratio_history",
    "water oil ratio history": "water_oil_ratio_history",
    "wor forecast": "water_oil_ratio_forecast",
    "water oil ratio forecast": "water_oil_ratio_forecast",
    "wor prediction": "water_oil_ratio_forecast",
    "water oil ratio prediction": "water_oil_ratio_forecast",

    # Relative Permeability and Fractional Flow
    "relative permeability": "relative_permeability",
    "rel perm": "relative_permeability",
    "relperm": "relative_permeability",
    "relative permeability curve": "relative_permeability_curve",
    "relative permeability analysis": "relative_permeability_analysis",
    "relative permeability modeling": "relative_permeability_modeling",
    "relative permeability simulation": "relative_permeability_modeling",
    "relative permeability measurement": "relative_permeability_measurement",
    "relative permeability test": "relative_permeability_measurement",
    "relative permeability evaluation": "relative_permeability_analysis",

    # Water Cut Measurement - Online Meters vs Manual Sampling
    "water cut meter": "water_cut_meter",
    "water cut meters": "water_cut_meter",
    "online water cut meter": "water_cut_meter_online",
    "online water cut measurement": "water_cut_meter_online",
    "online water cut monitoring": "water_cut_meter_online",
    "manual water cut measurement": "water_cut_meter_manual",
    "manual water cut monitoring": "water_cut_meter_manual",
    "manual water cut sampling": "water_cut_meter_manual",
    "water cut sampling": "water_cut_sampling",
    "water cut sample": "water_cut_sampling",
    "water cut sample preparation": "water_cut_sampling",
    "water cut sample analysis": "water_cut_sampling_analysis",
    "water cut sample test": "water_cut_sampling_analysis",

    # Water Disposal Regulations - UIC Class II Wells
    "water disposal": "water_disposal",
    "water disposal regulations": "water_disposal_regulations",
    "water disposal regulation": "water_disposal_regulations",
    "water disposal compliance": "water_disposal_regulations",
    "water disposal permit": "water_disposal_regulations",
    "water disposal permitting": "water_disposal_regulations",
    "water disposal well": "water_disposal_well",
    "water disposal wells": "water_disposal_well",
    "uic class ii": "uic_class_ii_well",
    "uic class 2": "uic_class_ii_well",
    "uic class ii well": "uic_class_ii_well",
    "uic class ii wells": "uic_class_ii_well",
    "uic class 2 well": "uic_class_ii_well",
    "uic class 2 wells": "uic_class_ii_well",
    "class ii well": "uic_class_ii_well",
    "class ii wells": "uic_class_ii_well",
    "class 2 well": "uic_class_ii_well",
    "class 2 wells": "uic_class_ii_well",
    "uic well": "uic_class_ii_well",
    "uic wells": "uic_class_ii_well",

    # Declining Oil Rate with Constant Liquid Rate - Artificial Lift Constraints
    "declining oil rate": "declining_oil_rate",
    "oil rate decline": "declining_oil_rate",
    "oil rate decline analysis": "declining_oil_rate_analysis",
    "oil rate decline modeling": "declining_oil_rate_modeling",
    "oil rate decline simulation": "declining_oil_rate_modeling",
    "constant liquid rate": "constant_liquid_rate",
    "constant fluid rate": "constant_liquid_rate",
    "constant production rate": "constant_liquid_rate",
    "artificial lift": "artificial_lift",
    "artificial lift constraint": "artificial_lift_constraint",
    "artificial lift constraints": "artificial_lift_constraint",
    "artificial lift limitation": "artificial_lift_constraint",
    "artificial lift limitations": "artificial_lift_constraint",
    "artificial lift analysis": "artificial_lift_analysis",
    "artificial lift modeling": "artificial_lift_modeling",
    "artificial lift simulation": "artificial_lift_modeling",

    # Waterflood Pattern Balancing - Injection-Production Ratio
    "pattern balancing": "pattern_balancing",
    "waterflood pattern balancing": "pattern_balancing",
    "pattern balance": "pattern_balancing",
    "pattern balance analysis": "pattern_balancing_analysis",
    "pattern balance modeling": "pattern_balancing_modeling",
    "pattern balance simulation": "pattern_balancing_modeling",
    "injection production ratio": "injection_production_ratio",
    "ipr": "injection_production_ratio",
    "injection-production ratio": "injection_production_ratio",
    "injection production ratio analysis": "injection_production_ratio_analysis",
    "injection production ratio modeling": "injection_production_ratio_modeling",
    "injection production ratio simulation": "injection_production_ratio_modeling",

    # Emulsion Stability and Demulsification
    "emulsion": "emulsion",
    "emulsion stability": "emulsion_stability",
    "emulsion stability analysis": "emulsion_stability_analysis",
    "emulsion stability test": "emulsion_stability_analysis",
    "emulsion stability measurement": "emulsion_stability_analysis",
    "emulsion stability modeling": "emulsion_stability_modeling",
    "emulsion stability simulation": "emulsion_stability_modeling",
    "demulsification": "demulsification",
    "demulsifier": "demulsification",
    "demulsification analysis": "demulsification_analysis",
    "demulsification test": "demulsification_analysis",
    "demulsification measurement": "demulsification_analysis",
    "demulsification modeling": "demulsification_modeling",
    "demulsification simulation": "demulsification_modeling",

    # Water Influx from Aquifer - Material Balance
    "water influx": "water_influx",
    "aquifer influx": "water_influx",
    "aquifer water influx": "water_influx",
    "aquifer influx analysis": "water_influx_analysis",
    "aquifer influx modeling": "water_influx_modeling",
    "aquifer influx simulation": "water_influx_modeling",
    "material balance": "material_balance",
    "material balance analysis": "material_balance_analysis",
    "material balance modeling": "material_balance_modeling",
    "material balance simulation": "material_balance_modeling",
    "material balance test": "material_balance_analysis",
    "material balance measurement": "material_balance_analysis",

    # Water Saturation from Well Logs - Archie Equation
    "water saturation": "water_saturation",
    "water sat": "water_saturation",
    "sw": "water_saturation",
    "water saturation log": "water_saturation_log",
    "water saturation analysis": "water_saturation_analysis",
    "water saturation modeling": "water_saturation_modeling",
    "water saturation simulation": "water_saturation_modeling",
    "archie equation": "archie_equation",
    "archie": "archie_equation",
    "archie method": "archie_equation",
    "archie analysis": "archie_equation",
    "archie modeling": "archie_equation",
    "archie simulation": "archie_equation",
    "archie log": "archie_equation",
    "archie test": "archie_equation",
    "archie measurement": "archie_equation",

    # Produced Water Salinity and Water Type Identification
    "produced water salinity": "produced_water_salinity",
    "produced water salinity analysis": "produced_water_salinity_analysis",
    "produced water salinity measurement": "produced_water_salinity_analysis",
    "produced water salinity monitoring": "produced_water_salinity_monitoring",
    "produced water salinity control": "produced_water_salinity_control",
    "water type": "water_type",
    "water type identification": "water_type_identification",
    "water type analysis": "water_type_identification",
    "water type measurement": "water_type_identification",
    "water type monitoring": "water_type_identification",
    "water type control": "water_type_identification",

    # Waterflood Conformance - Gel and Polymer Treatments
    "waterflood conformance": "waterflood_conformance",
    "conformance": "waterflood_conformance",
    "conformance analysis": "waterflood_conformance_analysis",
    "conformance test": "waterflood_conformance_analysis",
    "conformance measurement": "waterflood_conformance_analysis",
    "conformance modeling": "waterflood_conformance_modeling",
    "conformance simulation": "waterflood_conformance_modeling",
    "gel treatment": "gel_treatment",
    "gel treatments": "gel_treatment",
    "gel injection": "gel_treatment",
    "gel conformance": "gel_treatment",
    "polymer treatment": "polymer_treatment",
    "polymer treatments": "polymer_treatment",
    "polymer injection": "polymer_treatment",
    "polymer conformance": "polymer_treatment",

    # Economic Limit - Oil Price Sensitivity and Operating Cost
    "economic limit": "economic_limit",
    "economic limit analysis": "economic_limit_analysis",
    "economic limit modeling": "economic_limit_modeling",
    "economic limit simulation": "economic_limit_modeling",
    "oil price sensitivity": "oil_price_sensitivity",
    "oil price sensitivity analysis": "oil_price_sensitivity_analysis",
    "oil price sensitivity modeling": "oil_price_sensitivity_modeling",
    "oil price sensitivity simulation": "oil_price_sensitivity_modeling",
    "operating cost": "operating_cost",
    "operating cost analysis": "operating_cost_analysis",
    "operating cost modeling": "operating_cost_modeling",
    "operating cost simulation": "operating_cost_modeling",

    # Water Production Forecasting - Koval and X-plot Methods
    "water production forecasting": "water_production_forecasting",
    "water production forecast": "water_production_forecasting",
    "water production prediction": "water_production_forecasting",
    "water production modeling": "water_production_modeling",
    "water production simulation": "water_production_modeling",
    "koval method": "koval_method",
    "koval": "koval_method",
    "koval analysis": "koval_method",
    "koval modeling": "koval_method",
    "koval simulation": "koval_method",
    "x-plot": "x_plot_method",
    "x plot": "x_plot_method",
    "xplot": "x_plot_method",
    "x-plot method": "x_plot_method",
    "x-plot analysis": "x_plot_method",
    "x-plot modeling": "x_plot_method",
    "x-plot simulation": "x_plot_method",

    # Misspellings, Synonyms, Related Terms
    "watercut analysis": "water_cut_analysis",
    "watercut measurement": "water_cut_test",
    "watercut test": "water_cut_test",
    "watercut profile": "water_cut_profile",
    "watercut curve": "water_cut_curve",
    "watercut forecast": "water_cut_forecast",
    "watercut prediction": "water_cut_forecast",
    "watercut modeling": "water_cut_modeling",
    "watercut simulation": "water_cut_modeling",
    "watercut monitoring": "water_cut_monitoring",
    "watercut tracking": "water_cut_monitoring",
    "watercut trend": "water_cut_trend",
    "watercut history": "water_cut_history",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    "watercut meter": "water_cut_meter",
    "watercut meters": "water_cut_meter",
    "online watercut meter": "water_cut_meter_online",
    "online watercut measurement": "water_cut_meter_online",
    "online watercut monitoring": "water_cut_meter_online",
    "manual watercut measurement": "water_cut_meter_manual",
    "manual watercut monitoring": "water_cut_meter_manual",
    "manual watercut sampling": "water_cut_meter_manual",
    "watercut sampling": "water_cut_sampling",
    "watercut sample": "water_cut_sampling",
    "watercut sample preparation": "water_cut_sampling",
    "watercut sample analysis": "water_cut_sampling_analysis",
    "watercut sample test": "water_cut_sampling_analysis",
    # Add more misspellings, synonyms, and related terms as needed for completeness
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}|{SEMANTIC_MAP_AUTHOR}|{SEMANTIC_MAP_ENGINE}|{_EXPECTED_ENTRY_COUNT}"
    hash_input = meta + "|" + joined
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.lower().strip()
    t = re.sub(r"[^a-z0-9\s\-\&]", "", t)
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)