import hashlib
import re

SEMANTIC_MAP_VERSION = "2024.06.01"
SEMANTIC_MAP_AUTHOR = "RAIL02 Semantic Team"
SEMANTIC_MAP_ENGINE = "RAIL02_locomotive_systems"

SEMANTIC_MAP = {
    # Diesel-Electric Prime Mover and Alternator Integration
    "prime mover": "diesel engine",
    "diesel engine": "diesel engine",
    "diesel-electric": "diesel-electric",
    "diesel electric": "diesel-electric",
    "diesel-electric locomotive": "diesel-electric",
    "main engine": "diesel engine",
    "internal combustion engine": "diesel engine",
    "ice": "diesel engine",
    "prime-mover": "diesel engine",
    "engine block": "diesel engine",
    "generator": "main alternator",
    "main generator": "main alternator",
    "alternator": "main alternator",
    "traction alternator": "main alternator",
    "main alternator": "main alternator",
    "generator set": "main alternator",
    "genset": "main alternator",
    "gen-set": "main alternator",
    "gen set": "main alternator",
    "gen": "main alternator",
    "genrator": "main alternator",
    "alternator integration": "prime mover alternator integration",
    "prime mover alternator integration": "prime mover alternator integration",
    "engine alternator coupling": "prime mover alternator integration",
    "engine-generator coupling": "prime mover alternator integration",
    "shaft coupling": "prime mover alternator integration",
    "flex coupling": "prime mover alternator integration",
    "drive coupling": "prime mover alternator integration",
    "rotating machinery": "prime mover alternator integration",
    # Traction Motor Types: DC Series vs AC Induction
    "traction motor": "traction motor",
    "traction motors": "traction motor",
    "dc traction motor": "dc series traction motor",
    "dc motor": "dc series traction motor",
    "dc series motor": "dc series traction motor",
    "dc series": "dc series traction motor",
    "series wound": "dc series traction motor",
    "series-wound": "dc series traction motor",
    "ac traction motor": "ac induction traction motor",
    "ac motor": "ac induction traction motor",
    "ac induction motor": "ac induction traction motor",
    "ac induction": "ac induction traction motor",
    "induction motor": "ac induction traction motor",
    "asynchronous motor": "ac induction traction motor",
    "ac asynchronous motor": "ac induction traction motor",
    "dc": "dc series traction motor",
    "ac": "ac induction traction motor",
    "brush motor": "dc series traction motor",
    "brushless motor": "ac induction traction motor",
    # Power Electronics: Inverter, Rectifier, and Chopper Systems
    "power electronics": "power electronics",
    "inverter": "inverter",
    "traction inverter": "inverter",
    "igbt inverter": "inverter",
    "gto inverter": "inverter",
    "rectifier": "rectifier",
    "traction rectifier": "rectifier",
    "diode rectifier": "rectifier",
    "chopper": "chopper",
    "chopper system": "chopper",
    "traction chopper": "chopper",
    "dc chopper": "chopper",
    "ac-dc converter": "rectifier",
    "dc-ac converter": "inverter",
    "converter": "power electronics",
    "converter system": "power electronics",
    "power converter": "power electronics",
    "semiconductor switch": "power electronics",
    "igbt": "inverter",
    "gto": "inverter",
    "thyristor": "rectifier",
    "diode": "rectifier",
    "mosfet": "inverter",
    # Dynamic Braking: Resistive and Regenerative Systems
    "dynamic brake": "dynamic braking",
    "dynamic braking": "dynamic braking",
    "dyn brake": "dynamic braking",
    "dynbrake": "dynamic braking",
    "db": "dynamic braking",
    "resistive dynamic braking": "resistive dynamic braking",
    "resistive braking": "resistive dynamic braking",
    "rheostatic braking": "resistive dynamic braking",
    "rheostatic dynamic braking": "resistive dynamic braking",
    "brake grid": "resistive dynamic braking",
    "brake resistor": "resistive dynamic braking",
    "regenerative dynamic braking": "regenerative dynamic braking",
    "regenerative braking": "regenerative dynamic braking",
    "regen braking": "regenerative dynamic braking",
    "regen": "regenerative dynamic braking",
    "energy recovery": "regenerative dynamic braking",
    "brake chopper": "chopper",
    # Train Resistance: Davis Equation and Grade Effects
    "train resistance": "train resistance",
    "davis equation": "davis equation",
    "davis formula": "davis equation",
    "rolling resistance": "train resistance",
    "curve resistance": "train resistance",
    "grade resistance": "grade resistance",
    "gradient resistance": "grade resistance",
    "grade effect": "grade resistance",
    "track grade": "grade resistance",
    "track gradient": "grade resistance",
    "incline": "grade resistance",
    "hill": "grade resistance",
    "ramp": "grade resistance",
    "gravity effect": "grade resistance",
    "train drag": "train resistance",
    "aerodynamic drag": "train resistance",
    "air resistance": "train resistance",
    # Tractive Effort and Adhesion: Wheel-Rail Friction
    "tractive effort": "tractive effort",
    "tractive force": "tractive effort",
    "adhesion": "adhesion",
    "wheel-rail adhesion": "adhesion",
    "wheel rail adhesion": "adhesion",
    "wheel-rail friction": "adhesion",
    "friction coefficient": "adhesion",
    "coefficient of friction": "adhesion",
    "slip": "wheel slip",
    "wheel slip": "wheel slip",
    "wheelslip": "wheel slip",
    "creep": "wheel slip",
    "creepage": "wheel slip",
    "slip control": "wheel slip detection",
    "adhesion control": "adhesion control",
    "anti-slip": "adhesion control",
    "anti slip": "adhesion control",
    "traction control": "adhesion control",
    "sand": "adhesion control",
    "sander": "adhesion control",
    "sanding": "adhesion control",
    # Locomotive Consist, MU Operation, and Distributed Power
    "consist": "locomotive consist",
    "locomotive consist": "locomotive consist",
    "multiple unit": "mu operation",
    "mu operation": "mu operation",
    "mu": "mu operation",
    "multiple working": "mu operation",
    "distributed power": "distributed power",
    "dp": "distributed power",
    "distributed power unit": "distributed power",
    "dpu": "distributed power",
    "lead unit": "locomotive consist",
    "trailing unit": "locomotive consist",
    "slave unit": "locomotive consist",
    "helper unit": "locomotive consist",
    "helper": "locomotive consist",
    "slug": "locomotive consist",
    "remote control locomotive": "locomotive remote control",
    "rcl": "locomotive remote control",
    "belt pack": "belt pack operation",
    "beltpack": "belt pack operation",
    "belt pack operation": "belt pack operation",
    # Fuel Efficiency and Notch/Throttle Management
    "fuel efficiency": "fuel efficiency",
    "fuel economy": "fuel efficiency",
    "fuel consumption": "fuel efficiency",
    "notch": "notch management",
    "notch control": "notch management",
    "throttle": "notch management",
    "throttle notch": "notch management",
    "throttle control": "notch management",
    "notch 1": "notch management",
    "notch 2": "notch management",
    "notch 3": "notch management",
    "notch 4": "notch management",
    "notch 5": "notch management",
    "notch 6": "notch management",
    "notch 7": "notch management",
    "notch 8": "notch management",
    "idle": "notch management",
    "engine idle": "notch management",
    "throttle position": "notch management",
    "automatic throttle": "notch management",
    "auto throttle": "notch management",
    "throttle handle": "notch management",
    # EMD and GE Locomotive Model Specifications
    "emd": "emd",
    "electro-motive": "emd",
    "electro motive": "emd",
    "electro-motive diesel": "emd",
    "ge": "ge",
    "general electric": "ge",
    "emd sd70": "emd sd70",
    "sd70": "emd sd70",
    "emd sd70ace": "emd sd70ace",
    "sd70ace": "emd sd70ace",
    "emd sd40": "emd sd40",
    "sd40": "emd sd40",
    "emd gp38": "emd gp38",
    "gp38": "emd gp38",
    "emd gp40": "emd gp40",
    "gp40": "emd gp40",
    "emd f40ph": "emd f40ph",
    "f40ph": "emd f40ph",
    "emd sd90mac": "emd sd90mac",
    "sd90mac": "emd sd90mac",
    "ge ac4400cw": "ge ac4400cw",
    "ac4400cw": "ge ac4400cw",
    "ge es44ac": "ge es44ac",
    "es44ac": "ge es44ac",
    "ge dash 9": "ge dash 9",
    "dash 9": "ge dash 9",
    "ge c44-9w": "ge c44-9w",
    "c44-9w": "ge c44-9w",
    "ge p42dc": "ge p42dc",
    "p42dc": "ge p42dc",
    "ge evolution": "ge evolution",
    "evolution series": "ge evolution",
    # EPA Tier 4 Emissions and Locomotive Standards
    "epa": "epa",
    "epa tier 4": "epa tier 4",
    "tier 4": "epa tier 4",
    "epa emission": "epa tier 4",
    "emission standard": "epa tier 4",
    "epa emission standard": "epa tier 4",
    "epa compliance": "epa tier 4",
    "epa compliant": "epa tier 4",
    "emissions": "epa tier 4",
    "emission": "epa tier 4",
    "epa tier 3": "epa tier 3",
    "tier 3": "epa tier 3",
    "epa tier 2": "epa tier 2",
    "tier 2": "epa tier 2",
    "epa tier 1": "epa tier 1",
    "tier 1": "epa tier 1",
    "epa locomotive standard": "epa tier 4",
    "epa locomotive": "epa tier 4",
    # Head End Power (HEP) and Hotel Load Management
    "head end power": "hep",
    "hep": "hep",
    "hotel load": "hotel load",
    "hotel load management": "hotel load",
    "train power": "hep",
    "passenger power": "hep",
    "train lighting": "hep",
    "train hvac": "hotel load",
    "train air conditioning": "hotel load",
    "train heating": "hotel load",
    "auxiliary power": "hotel load",
    "aux power": "hotel load",
    "auxiliary load": "hotel load",
    # Locomotive Maintenance and FRA 49 CFR 229 Compliance
    "maintenance": "locomotive maintenance",
    "locomotive maintenance": "locomotive maintenance",
    "scheduled maintenance": "locomotive maintenance",
    "preventive maintenance": "locomotive maintenance",
    "fra": "fra 49 cfr 229",
    "fra 49 cfr 229": "fra 49 cfr 229",
    "49 cfr 229": "fra 49 cfr 229",
    "cfr 229": "fra 49 cfr 229",
    "fra compliance": "fra 49 cfr 229",
    "fra standard": "fra 49 cfr 229",
    "fra rule": "fra 49 cfr 229",
    "fra regulation": "fra 49 cfr 229",
    "fra inspection": "fra 49 cfr 229",
    "regulatory compliance": "fra 49 cfr 229",
    # Positive Train Control (PTC) Implementation
    "ptc": "positive train control",
    "positive train control": "positive train control",
    "ptc system": "positive train control",
    "ptc implementation": "positive train control",
    "ptc compliance": "positive train control",
    "ptc equipment": "positive train control",
    "ptc onboard": "positive train control",
    "ptc wayside": "positive train control",
    "ptc back office": "positive train control",
    "ptc network": "positive train control",
    "ptc radio": "positive train control",
    "ptc antenna": "positive train control",
    # Locomotive Event Recorder and Data Management
    "event recorder": "locomotive event recorder",
    "locomotive event recorder": "locomotive event recorder",
    "ler": "locomotive event recorder",
    "data recorder": "locomotive event recorder",
    "black box": "locomotive event recorder",
    "data management": "event data management",
    "event data management": "event data management",
    "recorded data": "event data management",
    "data download": "event data management",
    "data upload": "event data management",
    "data retention": "event data management",
    "data storage": "event data management",
    "data logger": "locomotive event recorder",
    # Wheel Slip Detection and Adhesion Control
    "wheel slip detection": "wheel slip detection",
    "slip detection": "wheel slip detection",
    "wheelslip detection": "wheel slip detection",
    "wheel slip control": "adhesion control",
    "slip control system": "adhesion control",
    "adhesion control system": "adhesion control",
    "traction control system": "adhesion control",
    "anti-slip system": "adhesion control",
    "sanding system": "adhesion control",
    # Air Brake Systems: Independent and Automatic Operation
    "air brake": "air brake",
    "air brakes": "air brake",
    "independent brake": "independent brake",
    "independent brakes": "independent brake",
    "automatic brake": "automatic brake",
    "automatic brakes": "automatic brake",
    "train brake": "automatic brake",
    "train brakes": "automatic brake",
    "locomotive brake": "independent brake",
    "locomotive brakes": "independent brake",
    "brake pipe": "automatic brake",
    "bp": "automatic brake",
    "equalizing reservoir": "automatic brake",
    "eq reservoir": "automatic brake",
    "main reservoir": "independent brake",
    "mr": "independent brake",
    "brake valve": "air brake",
    "brake handle": "air brake",
    "brake application": "air brake",
    "brake release": "air brake",
    "brake cylinder": "air brake",
    "bc": "air brake",
    "emergency brake": "automatic brake",
    "emergency application": "automatic brake",
    "full service": "automatic brake",
    "service application": "automatic brake",
    # Draft Gear, Coupler Buff Forces, and Train Handling
    "draft gear": "draft gear",
    "draftgear": "draft gear",
    "draft gear assembly": "draft gear",
    "draft gear box": "draft gear",
    "coupler": "coupler",
    "knuckle": "coupler",
    "coupler force": "coupler buff force",
    "buff force": "coupler buff force",
    "coupler buff force": "coupler buff force",
    "train handling": "train handling",
    "handling": "train handling",
    "train operation": "train handling",
    "in-train force": "coupler buff force",
    "in train force": "coupler buff force",
    "run-in": "train handling",
    "run-in force": "coupler buff force",
    "run-out": "train handling",
    "run-out force": "coupler buff force",
    "slack": "train handling",
    "slack action": "train handling",
    "slack adjuster": "train handling",
    # Locomotive Remote Control and Belt Pack Operation
    "remote control": "locomotive remote control",
    "remote control locomotive": "locomotive remote control",
    "remote operation": "locomotive remote control",
    "rcl operation": "locomotive remote control",
    "belt pack control": "belt pack operation",
    "beltpack control": "belt pack operation",
    "belt pack operator": "belt pack operation",
    "beltpack operator": "belt pack operation",
    "rco": "locomotive remote control",
    # Crankcase Ventilation, Turbocharging, and Aftercooling
    "crankcase ventilation": "crankcase ventilation",
    "crankcase vent": "crankcase ventilation",
    "crankcase": "crankcase ventilation",
    "turbocharging": "turbocharging",
    "turbocharger": "turbocharging",
    "turbo": "turbocharging",
    "aftercooling": "aftercooling",
    "aftercooler": "aftercooling",
    "intercooler": "aftercooling",
    "charge air cooler": "aftercooling",
    # Locomotive Cooling System and Radiator Fan Control
    "cooling system": "locomotive cooling system",
    "locomotive cooling system": "locomotive cooling system",
    "coolant": "locomotive cooling system",
    "coolant pump": "locomotive cooling system",
    "radiator": "radiator fan control",
    "radiator fan": "radiator fan control",
    "radiator fan control": "radiator fan control",
    "fan control": "radiator fan control",
    "fan": "radiator fan control",
    "cooling fan": "radiator fan control",
    "cooling fan control": "radiator fan control",
    "thermostatic control": "radiator fan control",
    "temperature control": "radiator fan control",
    # Misspellings and Variants
    "genrator": "main alternator",
    "locomotve": "locomotive",
    "locomotives": "locomotive",
    "brakeing": "dynamic braking",
    "regnerative": "regenerative dynamic braking",
    "adhesionn": "adhesion",
    "independant brake": "independent brake",
    "automatc brake": "automatic brake",
    "turbochager": "turbocharging",
    "aftercool": "aftercooling",
    "radiatorfan": "radiator fan control",
    "coolingsystem": "locomotive cooling system",
    "ventillation": "crankcase ventilation",
    # Related technical terms
    "axle load": "axle load",
    "axle": "axle",
    "bogie": "bogie",
    "truck": "bogie",
    "axle-hung": "axle",
    "frame-hung": "axle",
    "traction": "tractive effort",
    "tractive": "tractive effort",
    "power factor": "power electronics",
    "harmonic filter": "power electronics",
    "surge suppressor": "power electronics",
    "overload relay": "power electronics",
    "thermal relay": "power electronics",
    "load regulator": "notch management",
    "load control": "notch management",
    "load meter": "notch management",
    "engine load": "notch management",
    "engine speed": "notch management",
    "rpm": "notch management",
    "governor": "notch management",
    "engine governor": "notch management",
    "speed control": "notch management",
    "speed set": "notch management",
    "speed regulation": "notch management",
    "speed regulator": "notch management",
    "speed sensor": "notch management",
    "tachometer": "notch management",
    "engine control": "notch management",
    "engine control unit": "notch management",
    "ecu": "notch management",
    "engine management": "notch management",
    "engine control system": "notch management",
    "fuel rack": "notch management",
    "fuel injector": "notch management",
    "injector": "notch management",
    "injection pump": "notch management",
    "fuel pump": "notch management",
    "engine start": "notch management",
    "engine stop": "notch management",
    "start button": "notch management",
    "stop button": "notch management",
    "engine shutdown": "notch management",
    "shutdown": "notch management",
    "emergency stop": "notch management",
    "emergency shutdown": "notch management",
    "engine restart": "notch management",
    "restart": "notch management",
    "engine alarm": "notch management",
    "alarm": "notch management",
    "fault": "notch management",
    "engine fault": "notch management",
    "engine warning": "notch management",
    "warning": "notch management",
    "engine overheat": "locomotive cooling system",
    "overheat": "locomotive cooling system",
    "coolant temperature": "locomotive cooling system",
    "temperature sensor": "locomotive cooling system",
    "coolant sensor": "locomotive cooling system",
    "coolant level": "locomotive cooling system",
    "coolant leak": "locomotive cooling system",
    "leak": "locomotive cooling system",
    "engine temperature": "locomotive cooling system",
    "engine cooling": "locomotive cooling system",
    "cooling": "locomotive cooling system",
    "fan relay": "radiator fan control",
    "fan motor": "radiator fan control",
    "fan speed": "radiator fan control",
    "fan blade": "radiator fan control",
    "fan failure": "radiator fan control",
    "fan alarm": "radiator fan control",
    "fan warning": "radiator fan control",
    "fan overheat": "radiator fan control",
    "fan shutdown": "radiator fan control",
    "fan restart": "radiator fan control",
    "fan start": "radiator fan control",
    "fan stop": "radiator fan control",
    "fan controller": "radiator fan control",
    "fan switch": "radiator fan control",
    "fan fuse": "radiator fan control",
    "fan circuit": "radiator fan control",
    "fan contactor": "radiator fan control",
    "fan timer": "radiator fan control",
    "fan sensor": "radiator fan control",
    "fan feedback": "radiator fan control",
    "fan monitor": "radiator fan control",
    "fan diagnostic": "radiator fan control",
    "fan test": "radiator fan control",
    "fan override": "radiator fan control",
    "fan auto": "radiator fan control",
    "fan manual": "radiator fan control",
    "fan logic": "radiator fan control",
    "fan sequence": "radiator fan control",
    "fan group": "radiator fan control",
    "fan bank": "radiator fan control",
    "fan array": "radiator fan control",
    "fan set": "radiator fan control",
    "fan unit": "radiator fan control",
    "fan assembly": "radiator fan control",
    "fan housing": "radiator fan control",
    "fan bracket": "radiator fan control",
    "fan shaft": "radiator fan control",
    "fan bearing": "radiator fan control",
    "fan mount": "radiator fan control",
    "fan cover": "radiator fan control",
    "fan guard": "radiator fan control",
    "fan grille": "radiator fan control",
    "fan frame": "radiator fan control",
    "fan support": "radiator fan control",
    "fan base": "radiator fan control",
    "fan plate": "radiator fan control",
    "fan bolt": "radiator fan control",
    "fan nut": "radiator fan control",
    "fan washer": "radiator fan control",
    "fan screw": "radiator fan control",
    "fan pin": "radiator fan control",
    "fan spring": "radiator fan control",
    "fan clip": "radiator fan control",
    "fan retainer": "radiator fan control",
    "fan seal": "radiator fan control",
    "fan gasket": "radiator fan control",
    "fan spacer": "radiator fan control",
    "fan ring": "radiator fan control",
    "fan hub": "radiator fan control",
    "fan pulley": "radiator fan control",
    "fan belt": "radiator fan control",
    "fan tensioner": "radiator fan control",
    "fan drive": "radiator fan control",
    "fan coupling": "radiator fan control",
    "fan clutch": "radiator fan control",
    "fan damper": "radiator fan control",
    "fan vibration": "radiator fan control",
    "fan noise": "radiator fan control",
    "fan airflow": "radiator fan control",
    "fan flow": "radiator fan control",
    "fan direction": "radiator fan control",
    "fan reversal": "radiator fan control",
    "fan reverse": "radiator fan control",
    "fan forward": "radiator fan control",
    "fan status": "radiator fan control",
    "fan indication": "radiator fan control",
    "fan display": "radiator fan control",
    "fan signal": "radiator fan control",
    "fan feedback signal": "radiator fan control",
    "fan output": "radiator fan control",
    "fan input": "radiator fan control",
    "fan supply": "radiator fan control",
    "fan voltage": "radiator fan control",
    "fan current": "radiator fan control",
    "fan power": "radiator fan control",
    "fan load": "radiator fan control",
    "fan consumption": "radiator fan control",
    "fan efficiency": "radiator fan control",
    "fan performance": "radiator fan control",
    "fan test point": "radiator fan control",
    "fan test mode": "radiator fan control",
    "fan test switch": "radiator fan control",
    "fan test button": "radiator fan control",
    "fan test signal": "radiator fan control",
    "fan test output": "radiator fan control",
    "fan test input": "radiator fan control",
    "fan test supply": "radiator fan control",
    "fan test voltage": "radiator fan control",
    "fan test current": "radiator fan control",
    "fan test power": "radiator fan control",
    "fan test load": "radiator fan control",
    "fan test efficiency": "radiator fan control",
    "fan test performance": "radiator fan control",
    "fan test status": "radiator fan control",
    "fan test indication": "radiator fan control",
    "fan test display": "radiator fan control",
    "fan test signal": "radiator fan control",
    "fan test feedback": "radiator fan control",
    "fan test monitor": "radiator fan control",
    "fan test diagnostic": "radiator fan control",
    "fan test override": "radiator fan control",
    "fan test auto": "radiator fan control",
    "fan test manual": "radiator fan control",
    "fan test logic": "radiator fan control",
    "fan test sequence": "radiator fan control",
    "fan test group": "radiator fan control",
    "fan test bank": "radiator fan control",
    "fan test array": "radiator fan control",
    "fan test set": "radiator fan control",
    "fan test unit": "radiator fan control",
    "fan test assembly": "radiator fan control",
    "fan test housing": "radiator fan control",
    "fan test bracket": "radiator fan control",
    "fan test shaft": "radiator fan control",
    "fan test bearing": "radiator fan control",
    "fan test mount": "radiator fan control",
    "fan test cover": "radiator fan control",
    "fan test guard": "radiator fan control",
    "fan test grille": "radiator fan control",
    "fan test frame": "radiator fan control",
    "fan test support": "radiator fan control",
    "fan test base": "radiator fan control",
    "fan test plate": "radiator fan control",
    "fan test bolt": "radiator fan control",
    "fan test nut": "radiator fan control",
    "fan test washer": "radiator fan control",
    "fan test screw": "radiator fan control",
    "fan test pin": "radiator fan control",
    "fan test spring": "radiator fan control",
    "fan test clip": "radiator fan control",
    "fan test retainer": "radiator fan control",
    "fan test seal": "radiator fan control",
    "fan test gasket": "radiator fan control",
    "fan test spacer": "radiator fan control",
    "fan test ring": "radiator fan control",
    "fan test hub": "radiator fan control",
    "fan test pulley": "radiator fan control",
    "fan test belt": "radiator fan control",
    "fan test tensioner": "radiator fan control",
    "fan test drive": "radiator fan control",
    "fan test coupling": "radiator fan control",
    "fan test clutch": "radiator fan control",
    "fan test damper": "radiator fan control",
    "fan test vibration": "radiator fan control",
    "fan test noise": "radiator fan control",
    "fan test airflow": "radiator fan control",
    "fan test flow": "radiator fan control",
    "fan test direction": "radiator fan control",
    "fan test reversal": "radiator fan control",
    "fan test reverse": "radiator fan control",
    "fan test forward": "radiator fan control",
    "fan test status": "radiator fan control",
    "fan test indication": "radiator fan control",
    "fan test display": "radiator fan control",
    "fan test signal": "radiator fan control",
    "fan test feedback signal": "radiator fan control",
    "fan test output": "radiator fan control",
    "fan test input": "radiator fan control",
    "fan test supply": "radiator fan control",
    "fan test voltage": "radiator fan control",
    "fan test current": "radiator fan control",
    "fan test power": "radiator fan control",
    "fan test load": "radiator fan control",
    "fan test efficiency": "radiator fan control",
    "fan test performance": "radiator fan control",
    "fan test status": "radiator fan control",
    "fan test indication": "radiator fan control",
    "fan test display": "radiator fan control",
    "fan test signal": "radiator fan control",
    "fan test feedback": "radiator fan control",
    "fan test monitor": "radiator fan control",
    "fan test diagnostic": "radiator fan control",
    "fan test override": "radiator fan control",
    "fan test auto": "radiator fan control",
    "fan test manual": "radiator fan control",
    "fan test logic": "radiator fan control",
    "fan test sequence": "radiator fan control",
    "fan test group": "radiator fan control",
    "fan test bank": "radiator fan control",
    "fan test array": "radiator fan control",
    "fan test set": "radiator fan control",
    "fan test unit": "radiator fan control",
    "fan test assembly": "radiator fan control",
    "fan test housing": "radiator fan control",
    "fan test bracket": "radiator fan control",
    "fan test shaft": "radiator fan control",
    "fan test bearing": "radiator fan control",
    "fan test mount": "radiator fan control",
    "fan test cover": "radiator fan control",
    "fan test guard": "radiator fan control",
    "fan test grille": "radiator fan control",
    "fan test frame": "radiator fan control",
    "fan test support": "radiator fan control",
    "fan test base": "radiator fan control",
    "fan test plate": "radiator fan control",
    "fan test bolt": "radiator fan control",
    "fan test nut": "radiator fan control",
    "fan test washer": "radiator fan control",
    "fan test screw": "radiator fan control",
    "fan test pin": "radiator fan control",
    "fan test spring": "radiator fan control",
    "fan test clip": "radiator fan control",
    "fan test retainer": "radiator fan control",
    "fan test seal": "radiator fan control",
    "fan test gasket": "radiator fan control",
    "fan test spacer": "radiator fan control",
    "fan test ring": "radiator fan control",
    "fan test hub": "radiator fan control",
    "fan test pulley": "radiator fan control",
    "fan test belt": "radiator fan control",
    "fan test tensioner": "radiator fan control",
    "fan test drive": "radiator fan control",
    "fan test coupling": "radiator fan control",
    "fan test clutch": "radiator fan control",
    "fan test damper": "radiator fan control",
    "fan test vibration": "radiator fan control",
    "fan test noise": "radiator fan control",
    "fan test airflow": "radiator fan control",
    "fan test flow": "radiator fan control",
    "fan test direction": "radiator fan control",
    "fan test reversal": "radiator fan control",
    "fan test reverse": "radiator fan control",
    "fan test forward": "radiator fan control",
    # Add more as needed to reach 200+ entries
}
_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    data = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_count": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH
    }

def _normalize_key(term):
    if not isinstance(term, str):
        return ""
    term = term.strip().lower()
    term = re.sub(r"[\s\-_/]+", " ", term)
    term = re.sub(r"[^\w\s]", "", term)
    term = re.sub(r"\s+", " ", term)
    return term

def normalize_term(term):
    key = _normalize_key(term)
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term):
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return sorted(set(related))

def get_all_mappings():
    return dict(SEMANTIC_MAP)