import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENRG07_hydrogen_energy_team"
SEMANTIC_MAP_ENGINE = "ENRG07"

# Core normalized forms
SEMANTIC_MAP = {
    # Green Hydrogen Production via PEM Electrolysis
    "green hydrogen": "green_hydrogen",
    "renewable hydrogen": "green_hydrogen",
    "electrolytic hydrogen": "green_hydrogen",
    "hydrogen from renewables": "green_hydrogen",
    "hydrogen from wind": "green_hydrogen",
    "hydrogen from solar": "green_hydrogen",
    "hydrogen from hydro": "green_hydrogen",
    "pem electrolysis": "pem_electrolysis",
    "proton exchange membrane electrolysis": "pem_electrolysis",
    "pem electrolyzer": "pem_electrolysis",
    "pem cell": "pem_electrolysis",
    "pem": "pem_electrolysis",
    "proton exchange membrane": "pem_electrolysis",
    "electrolyzer": "pem_electrolysis",
    "electrolysis": "electrolysis",
    "water electrolysis": "electrolysis",
    "electrolytic cell": "electrolysis",
    "electrolytic process": "electrolysis",
    "electrolytic": "electrolysis",
    "hydrogen production by electrolysis": "electrolysis",
    "hydrogen production via electrolysis": "electrolysis",
    "hydrogen production pem": "pem_electrolysis",
    "hydrogen production pem electrolysis": "pem_electrolysis",
    "hydrogen production pem cell": "pem_electrolysis",
    "hydrogen production proton exchange membrane": "pem_electrolysis",
    # Blue Hydrogen via Steam Methane Reforming with CCS
    "blue hydrogen": "blue_hydrogen",
    "hydrogen from natural gas": "blue_hydrogen",
    "hydrogen from methane": "blue_hydrogen",
    "hydrogen from smrs": "blue_hydrogen",
    "hydrogen from smr": "blue_hydrogen",
    "hydrogen from steam methane reforming": "blue_hydrogen",
    "hydrogen from fossil fuels": "blue_hydrogen",
    "hydrogen with ccs": "blue_hydrogen",
    "hydrogen with carbon capture": "blue_hydrogen",
    "hydrogen with carbon capture and storage": "blue_hydrogen",
    "hydrogen with carbon sequestration": "blue_hydrogen",
    "hydrogen with co2 capture": "blue_hydrogen",
    "steam methane reforming": "smr",
    "smr": "smr",
    "smrs": "smr",
    "steam reforming": "smr",
    "methane reforming": "smr",
    "natural gas reforming": "smr",
    "steam reformer": "smr",
    "methane reformer": "smr",
    "carbon capture and storage": "ccs",
    "carbon capture": "ccs",
    "ccs": "ccs",
    "carbon sequestration": "ccs",
    "co2 capture": "ccs",
    "co2 sequestration": "ccs",
    "carbon storage": "ccs",
    "carbon capture utilization and storage": "ccus",
    "ccus": "ccus",
    "carbon capture and utilization": "ccu",
    "ccu": "ccu",
    # Alkaline Electrolysis Technology
    "alkaline electrolysis": "alkaline_electrolysis",
    "alkaline electrolyzer": "alkaline_electrolysis",
    "alkaline cell": "alkaline_electrolysis",
    "hydrogen production alkaline": "alkaline_electrolysis",
    "hydrogen production via alkaline electrolysis": "alkaline_electrolysis",
    "hydrogen production alkaline cell": "alkaline_electrolysis",
    "hydrogen production by alkaline electrolysis": "alkaline_electrolysis",
    "alkaline": "alkaline_electrolysis",
    "alkaline water electrolysis": "alkaline_electrolysis",
    "electrolysis alkaline": "alkaline_electrolysis",
    # Type IV Compressed Hydrogen Storage at 700 bar
    "type iv storage": "type_iv_storage",
    "type 4 storage": "type_iv_storage",
    "type iv hydrogen storage": "type_iv_storage",
    "type 4 hydrogen storage": "type_iv_storage",
    "type iv cylinder": "type_iv_storage",
    "type 4 cylinder": "type_iv_storage",
    "type iv tank": "type_iv_storage",
    "type 4 tank": "type_iv_storage",
    "700 bar storage": "700_bar_storage",
    "700 bar hydrogen storage": "700_bar_storage",
    "compressed hydrogen storage": "compressed_hydrogen_storage",
    "compressed hydrogen": "compressed_hydrogen_storage",
    "high pressure hydrogen storage": "compressed_hydrogen_storage",
    "high pressure storage": "compressed_hydrogen_storage",
    "hydrogen storage tank": "compressed_hydrogen_storage",
    "hydrogen storage cylinder": "compressed_hydrogen_storage",
    "hydrogen storage vessel": "compressed_hydrogen_storage",
    "hydrogen tank": "compressed_hydrogen_storage",
    "hydrogen cylinder": "compressed_hydrogen_storage",
    "hydrogen vessel": "compressed_hydrogen_storage",
    "hydrogen storage": "hydrogen_storage",
    "storage tank": "compressed_hydrogen_storage",
    "storage cylinder": "compressed_hydrogen_storage",
    "storage vessel": "compressed_hydrogen_storage",
    # Liquid Hydrogen (LH2) Storage and Boil-Off
    "liquid hydrogen": "liquid_hydrogen",
    "lh2": "liquid_hydrogen",
    "lh2 storage": "liquid_hydrogen_storage",
    "liquid hydrogen storage": "liquid_hydrogen_storage",
    "cryogenic hydrogen": "liquid_hydrogen_storage",
    "cryogenic hydrogen storage": "liquid_hydrogen_storage",
    "cryogenic storage": "liquid_hydrogen_storage",
    "hydrogen boil-off": "hydrogen_boil_off",
    "boil-off": "hydrogen_boil_off",
    "boil off": "hydrogen_boil_off",
    "boiloff": "hydrogen_boil_off",
    "boil off gas": "hydrogen_boil_off",
    "boil-off gas": "hydrogen_boil_off",
    "boil off losses": "hydrogen_boil_off",
    "boil-off losses": "hydrogen_boil_off",
    "boil-off management": "hydrogen_boil_off_management",
    "boil off management": "hydrogen_boil_off_management",
    "liquid hydrogen tank": "liquid_hydrogen_storage",
    "liquid hydrogen vessel": "liquid_hydrogen_storage",
    "liquid hydrogen cylinder": "liquid_hydrogen_storage",
    "cryotank": "liquid_hydrogen_storage",
    "cryogenic tank": "liquid_hydrogen_storage",
    "cryogenic vessel": "liquid_hydrogen_storage",
    "cryogenic cylinder": "liquid_hydrogen_storage",
    # PEM Fuel Cell Membrane Electrode Assembly (MEA)
    "pem fuel cell": "pem_fuel_cell",
    "proton exchange membrane fuel cell": "pem_fuel_cell",
    "pemfc": "pem_fuel_cell",
    "pem fc": "pem_fuel_cell",
    "pem fuel cell stack": "pem_fuel_cell",
    "pem stack": "pem_fuel_cell",
    "membrane electrode assembly": "mea",
    "mea": "mea",
    "fuel cell membrane": "mea",
    "fuel cell electrode": "mea",
    "fuel cell catalyst": "mea",
    "pem membrane": "mea",
    "pem electrode": "mea",
    "pem catalyst": "mea",
    "electrode assembly": "mea",
    "membrane assembly": "mea",
    "electrode": "mea",
    "membrane": "mea",
    "catalyst": "mea",
    "fuel cell": "fuel_cell",
    "hydrogen fuel cell": "fuel_cell",
    "hydrogen cell": "fuel_cell",
    "hydrogen stack": "fuel_cell",
    "fuel cell stack": "fuel_cell",
    # Solid Oxide Fuel Cell (SOFC) for Stationary Power
    "solid oxide fuel cell": "sofc",
    "sofc": "sofc",
    "sofc stack": "sofc",
    "sofc cell": "sofc",
    "sofc fuel cell": "sofc",
    "solid oxide cell": "sofc",
    "solid oxide stack": "sofc",
    "stationary power": "stationary_power",
    "stationary fuel cell": "stationary_power",
    "stationary hydrogen power": "stationary_power",
    "stationary hydrogen fuel cell": "stationary_power",
    "stationary sofc": "stationary_power",
    "stationary pem": "stationary_power",
    "stationary pem fuel cell": "stationary_power",
    "stationary application": "stationary_power",
    "stationary energy": "stationary_power",
    "stationary generation": "stationary_power",
    "stationary electricity": "stationary_power",
    # Hydrogen Pipeline and Embrittlement per ASME B31.12
    "hydrogen pipeline": "hydrogen_pipeline",
    "hydrogen pipelines": "hydrogen_pipeline",
    "pipeline": "hydrogen_pipeline",
    "pipelines": "hydrogen_pipeline",
    "hydrogen transmission": "hydrogen_pipeline",
    "hydrogen transport": "hydrogen_pipeline",
    "hydrogen distribution": "hydrogen_pipeline",
    "asme b31.12": "asme_b31_12",
    "asme b3112": "asme_b31_12",
    "asme b31 12": "asme_b31_12",
    "b31.12": "asme_b31_12",
    "b3112": "asme_b31_12",
    "b31 12": "asme_b31_12",
    "pipeline embrittlement": "hydrogen_embrittlement",
    "hydrogen embrittlement": "hydrogen_embrittlement",
    "embrittlement": "hydrogen_embrittlement",
    "pipeline integrity": "hydrogen_pipeline_integrity",
    "pipeline safety": "hydrogen_pipeline_safety",
    "pipeline standard": "asme_b31_12",
    "pipeline code": "asme_b31_12",
    "pipeline regulation": "asme_b31_12",
    # Hydrogen Refueling Station Design per ISO 19880-1
    "hydrogen refueling station": "hydrogen_refueling_station",
    "hydrogen fueling station": "hydrogen_refueling_station",
    "hydrogen station": "hydrogen_refueling_station",
    "refueling station": "hydrogen_refueling_station",
    "fueling station": "hydrogen_refueling_station",
    "h2 station": "hydrogen_refueling_station",
    "h2 refueling station": "hydrogen_refueling_station",
    "h2 fueling station": "hydrogen_refueling_station",
    "iso 19880-1": "iso_19880_1",
    "iso 19880": "iso_19880_1",
    "iso19880-1": "iso_19880_1",
    "iso19880": "iso_19880_1",
    "iso 19880 1": "iso_19880_1",
    "iso19880 1": "iso_19880_1",
    "station design": "hydrogen_refueling_station_design",
    "refueling station design": "hydrogen_refueling_station_design",
    "fueling station design": "hydrogen_refueling_station_design",
    "hydrogen station design": "hydrogen_refueling_station_design",
    "hydrogen refueling station design": "hydrogen_refueling_station_design",
    "hydrogen fueling station design": "hydrogen_refueling_station_design",
    "station layout": "hydrogen_refueling_station_design",
    "station safety": "hydrogen_refueling_station_safety",
    "refueling station safety": "hydrogen_refueling_station_safety",
    "fueling station safety": "hydrogen_refueling_station_safety",
    "hydrogen station safety": "hydrogen_refueling_station_safety",
    # Hydrogen Safety per NFPA 2
    "hydrogen safety": "hydrogen_safety",
    "h2 safety": "hydrogen_safety",
    "safety": "hydrogen_safety",
    "nfpa 2": "nfpa_2",
    "nfpa2": "nfpa_2",
    "nfpa 2 hydrogen": "nfpa_2",
    "nfpa 2 code": "nfpa_2",
    "nfpa 2 standard": "nfpa_2",
    "nfpa 2 regulation": "nfpa_2",
    "nfpa 2 compliance": "nfpa_2",
    "hydrogen hazard": "hydrogen_safety",
    "hydrogen hazards": "hydrogen_safety",
    "hydrogen risk": "hydrogen_safety",
    "hydrogen risks": "hydrogen_safety",
    "hydrogen incident": "hydrogen_safety",
    "hydrogen incidents": "hydrogen_safety",
    "hydrogen accident": "hydrogen_safety",
    "hydrogen accidents": "hydrogen_safety",
    "hydrogen emergency": "hydrogen_safety",
    "hydrogen emergencies": "hydrogen_safety",
    "hydrogen fire": "hydrogen_safety",
    "hydrogen explosion": "hydrogen_safety",
    "hydrogen leak": "hydrogen_safety",
    "hydrogen leaks": "hydrogen_safety",
    "hydrogen detection": "hydrogen_safety",
    "hydrogen alarm": "hydrogen_safety",
    "hydrogen alarms": "hydrogen_safety",
    "hydrogen mitigation": "hydrogen_safety",
    "hydrogen protection": "hydrogen_safety",
    "hydrogen prevention": "hydrogen_safety",
    "hydrogen suppression": "hydrogen_safety",
    # Levelized Cost of Hydrogen (LCOH) Analysis
    "levelized cost of hydrogen": "lcoh",
    "lcoh": "lcoh",
    "hydrogen lcoh": "lcoh",
    "hydrogen cost": "lcoh",
    "hydrogen price": "lcoh",
    "hydrogen economics": "lcoh",
    "hydrogen economic analysis": "lcoh",
    "hydrogen cost analysis": "lcoh",
    "hydrogen price analysis": "lcoh",
    "hydrogen cost calculation": "lcoh",
    "hydrogen price calculation": "lcoh",
    "hydrogen cost modeling": "lcoh",
    "hydrogen price modeling": "lcoh",
    "hydrogen cost model": "lcoh",
    "hydrogen price model": "lcoh",
    "hydrogen cost estimate": "lcoh",
    "hydrogen price estimate": "lcoh",
    "hydrogen cost estimation": "lcoh",
    "hydrogen price estimation": "lcoh",
    "hydrogen cost assessment": "lcoh",
    "hydrogen price assessment": "lcoh",
    "hydrogen cost comparison": "lcoh",
    "hydrogen price comparison": "lcoh",
    "hydrogen cost benchmarking": "lcoh",
    "hydrogen price benchmarking": "lcoh",
    "hydrogen cost study": "lcoh",
    "hydrogen price study": "lcoh",
    "hydrogen cost report": "lcoh",
    "hydrogen price report": "lcoh",
    "hydrogen cost review": "lcoh",
    "hydrogen price review": "lcoh",
    "hydrogen cost summary": "lcoh",
    "hydrogen price summary": "lcoh",
    "hydrogen cost breakdown": "lcoh",
    "hydrogen price breakdown": "lcoh",
    "hydrogen cost structure": "lcoh",
    "hydrogen price structure": "lcoh",
    "hydrogen cost factors": "lcoh",
    "hydrogen price factors": "lcoh",
    "hydrogen cost drivers": "lcoh",
    "hydrogen price drivers": "lcoh",
    "hydrogen cost sensitivity": "lcoh",
    "hydrogen price sensitivity": "lcoh",
    "hydrogen cost forecast": "lcoh",
    "hydrogen price forecast": "lcoh",
    "hydrogen cost projection": "lcoh",
    "hydrogen price projection": "lcoh",
    "hydrogen cost scenario": "lcoh",
    "hydrogen price scenario": "lcoh",
    "hydrogen cost outlook": "lcoh",
    "hydrogen price outlook": "lcoh",
    # Hydrogen Color Classification and Carbon Intensity
    "hydrogen color": "hydrogen_color",
    "hydrogen colour": "hydrogen_color",
    "hydrogen classification": "hydrogen_color",
    "hydrogen class": "hydrogen_color",
    "hydrogen type": "hydrogen_color",
    "hydrogen grade": "hydrogen_color",
    "hydrogen purity": "hydrogen_color",
    "hydrogen carbon intensity": "hydrogen_carbon_intensity",
    "hydrogen ci": "hydrogen_carbon_intensity",
    "carbon intensity": "hydrogen_carbon_intensity",
    "ci": "hydrogen_carbon_intensity",
    "carbon footprint": "hydrogen_carbon_intensity",
    "hydrogen emissions": "hydrogen_carbon_intensity",
    "hydrogen ghg": "hydrogen_carbon_intensity",
    "hydrogen greenhouse gas": "hydrogen_carbon_intensity",
    "hydrogen greenhouse gases": "hydrogen_carbon_intensity",
    "hydrogen co2": "hydrogen_carbon_intensity",
    "hydrogen co2 emissions": "hydrogen_carbon_intensity",
    "hydrogen ghg emissions": "hydrogen_carbon_intensity",
    "hydrogen lifecycle emissions": "hydrogen_carbon_intensity",
    "hydrogen life cycle emissions": "hydrogen_carbon_intensity",
    "hydrogen well-to-gate emissions": "hydrogen_carbon_intensity",
    "hydrogen well to gate emissions": "hydrogen_carbon_intensity",
    "hydrogen well-to-wheel emissions": "hydrogen_carbon_intensity",
    "hydrogen well to wheel emissions": "hydrogen_carbon_intensity",
    "hydrogen cradle-to-gate emissions": "hydrogen_carbon_intensity",
    "hydrogen cradle to gate emissions": "hydrogen_carbon_intensity",
    "hydrogen cradle-to-wheel emissions": "hydrogen_carbon_intensity",
    "hydrogen cradle to wheel emissions": "hydrogen_carbon_intensity",
    # Solid-State Hydrogen Storage in Metal Hydrides
    "solid-state hydrogen storage": "solid_state_hydrogen_storage",
    "solid state hydrogen storage": "solid_state_hydrogen_storage",
    "solid hydrogen storage": "solid_state_hydrogen_storage",
    "metal hydride storage": "metal_hydride_storage",
    "metal hydrides": "metal_hydride_storage",
    "metal hydride": "metal_hydride_storage",
    "hydride storage": "metal_hydride_storage",
    "hydride": "metal_hydride_storage",
    "solid-state storage": "solid_state_hydrogen_storage",
    "solid state storage": "solid_state_hydrogen_storage",
    "solid storage": "solid_state_hydrogen_storage",
    "hydrogen hydride": "metal_hydride_storage",
    "hydrogen metal hydride": "metal_hydride_storage",
    "hydrogen metal hydrides": "metal_hydride_storage",
    "hydrogen solid-state storage": "solid_state_hydrogen_storage",
    "hydrogen solid state storage": "solid_state_hydrogen_storage",
    "hydrogen solid storage": "solid_state_hydrogen_storage",
    # Hydrogen Fuel Quality per ISO 14687 and SAE J2719
    "hydrogen fuel quality": "hydrogen_fuel_quality",
    "fuel quality": "hydrogen_fuel_quality",
    "hydrogen quality": "hydrogen_fuel_quality",
    "hydrogen purity": "hydrogen_fuel_quality",
    "hydrogen contaminants": "hydrogen_fuel_quality",
    "hydrogen impurity": "hydrogen_fuel_quality",
    "hydrogen impurities": "hydrogen_fuel_quality",
    "hydrogen specification": "hydrogen_fuel_quality",
    "hydrogen specs": "hydrogen_fuel_quality",
    "hydrogen standards": "hydrogen_fuel_quality",
    "hydrogen standard": "hydrogen_fuel_quality",
    "iso 14687": "iso_14687",
    "iso14687": "iso_14687",
    "iso 14687 hydrogen": "iso_14687",
    "iso 14687 standard": "iso_14687",
    "iso 14687 compliance": "iso_14687",
    "iso 14687 specification": "iso_14687",
    "iso 14687 fuel quality": "iso_14687",
    "iso 14687 fuel": "iso_14687",
    "iso 14687 specs": "iso_14687",
    "iso 14687 requirements": "iso_14687",
    "iso 14687 regulation": "iso_14687",
    "sae j2719": "sae_j2719",
    "sae j2719 hydrogen": "sae_j2719",
    "sae j2719 standard": "sae_j2719",
    "sae j2719 compliance": "sae_j2719",
    "sae j2719 specification": "sae_j2719",
    "sae j2719 fuel quality": "sae_j2719",
    "sae j2719 fuel": "sae_j2719",
    "sae j2719 specs": "sae_j2719",
    "sae j2719 requirements": "sae_j2719",
    "sae j2719 regulation": "sae_j2719",
    # Misspellings and common variants
    "hydrogen refuel station": "hydrogen_refueling_station",
    "hydrogen refueling stn": "hydrogen_refueling_station",
    "hydrogen fueling stn": "hydrogen_refueling_station",
    "hydrogen refuel stn": "hydrogen_refueling_station",
    "hydrogen refueling": "hydrogen_refueling_station",
    "hydrogen fueling": "hydrogen_refueling_station",
    "hydrogen refuel": "hydrogen_refueling_station",
    "hydrogen fuel": "fuel_cell",
    "hydrogen fuel cell": "fuel_cell",
    "hydrogen fuel cells": "fuel_cell",
    "hydrogen fuelcell": "fuel_cell",
    "hydrogen fuelcells": "fuel_cell",
    "hydrogen fuel-cell": "fuel_cell",
    "hydrogen fuel-cells": "fuel_cell",
    "hydrogen fuel cell stack": "fuel_cell",
    "hydrogen fuel cell stacks": "fuel_cell",
    "hydrogen fuelcell stack": "fuel_cell",
    "hydrogen fuelcell stacks": "fuel_cell",
    "hydrogen fuel-cell stack": "fuel_cell",
    "hydrogen fuel-cell stacks": "fuel_cell",
    "hydrogen fuel cell membrane": "mea",
    "hydrogen fuel cell electrode": "mea",
    "hydrogen fuel cell catalyst": "mea",
    "hydrogen fuel cell assembly": "mea",
    "hydrogen fuel cell membrane electrode assembly": "mea",
    "hydrogen fuel cell membrane assembly": "mea",
    "hydrogen fuel cell electrode assembly": "mea",
    "hydrogen fuel cell catalyst assembly": "mea",
    "hydrogen fuel cell stack assembly": "fuel_cell",
    "hydrogen fuel cell stack membrane": "mea",
    "hydrogen fuel cell stack electrode": "mea",
    "hydrogen fuel cell stack catalyst": "mea",
    "hydrogen fuel cell stack membrane assembly": "mea",
    "hydrogen fuel cell stack electrode assembly": "mea",
    "hydrogen fuel cell stack catalyst assembly": "mea",
    # More synonyms, abbreviations, acronyms, misspellings, related terms
    "hydrogen station layout": "hydrogen_refueling_station_design",
    "hydrogen station operation": "hydrogen_refueling_station_design",
    "hydrogen station operations": "hydrogen_refueling_station_design",
    "hydrogen station maintenance": "hydrogen_refueling_station_design",
    "hydrogen station commissioning": "hydrogen_refueling_station_design",
    "hydrogen station decommissioning": "hydrogen_refueling_station_design",
    "hydrogen station monitoring": "hydrogen_refueling_station_design",
    "hydrogen station control": "hydrogen_refueling_station_design",
    "hydrogen station automation": "hydrogen_refueling_station_design",
    "hydrogen station instrumentation": "hydrogen_refueling_station_design",
    "hydrogen station sensors": "hydrogen_refueling_station_design",
    "hydrogen station metering": "hydrogen_refueling_station_design",
    "hydrogen station calibration": "hydrogen_refueling_station_design",
    "hydrogen station testing": "hydrogen_refueling_station_design",
    "hydrogen station inspection": "hydrogen_refueling_station_design",
    "hydrogen station certification": "hydrogen_refueling_station_design",
    "hydrogen station compliance": "hydrogen_refueling_station_design",
    "hydrogen station regulation": "hydrogen_refueling_station_design",
    "hydrogen station standard": "hydrogen_refueling_station_design",
    "hydrogen station standards": "hydrogen_refueling_station_design",
    "hydrogen station requirements": "hydrogen_refueling_station_design",
    "hydrogen station specification": "hydrogen_refueling_station_design",
    "hydrogen station specs": "hydrogen_refueling_station_design",
    "hydrogen station guidelines": "hydrogen_refueling_station_design",
    "hydrogen station codes": "hydrogen_refueling_station_design",
    "hydrogen station policies": "hydrogen_refueling_station_design",
    "hydrogen station procedures": "hydrogen_refueling_station_design",
    "hydrogen station protocols": "hydrogen_refueling_station_design",
    "hydrogen station training": "hydrogen_refueling_station_design",
    "hydrogen station safety training": "hydrogen_refueling_station_safety",
    "hydrogen station emergency response": "hydrogen_refueling_station_safety",
    "hydrogen station fire safety": "hydrogen_refueling_station_safety",
    "hydrogen station explosion safety": "hydrogen_refueling_station_safety",
    "hydrogen station leak detection": "hydrogen_refueling_station_safety",
    "hydrogen station alarm": "hydrogen_refueling_station_safety",
    "hydrogen station alarms": "hydrogen_refueling_station_safety",
    "hydrogen station mitigation": "hydrogen_refueling_station_safety",
    "hydrogen station protection": "hydrogen_refueling_station_safety",
    "hydrogen station prevention": "hydrogen_refueling_station_safety",
    "hydrogen station suppression": "hydrogen_refueling_station_safety",
    "hydrogen station hazard": "hydrogen_refueling_station_safety",
    "hydrogen station hazards": "hydrogen_refueling_station_safety",
    "hydrogen station risk": "hydrogen_refueling_station_safety",
    "hydrogen station risks": "hydrogen_refueling_station_safety",
    "hydrogen station incident": "hydrogen_refueling_station_safety",
    "hydrogen station incidents": "hydrogen_refueling_station_safety",
    "hydrogen station accident": "hydrogen_refueling_station_safety",
    "hydrogen station accidents": "hydrogen_refueling_station_safety",
    "hydrogen station emergency": "hydrogen_refueling_station_safety",
    "hydrogen station emergencies": "hydrogen_refueling_station_safety",
    "hydrogen station fire": "hydrogen_refueling_station_safety",
    "hydrogen station explosion": "hydrogen_refueling_station_safety",
    "hydrogen station leak": "hydrogen_refueling_station_safety",
    "hydrogen station leaks": "hydrogen_refueling_station_safety",
    "hydrogen station detection": "hydrogen_refueling_station_safety",
    "hydrogen station alarm": "hydrogen_refueling_station_safety",
    "hydrogen station alarms": "hydrogen_refueling_station_safety",
    "hydrogen station mitigation": "hydrogen_refueling_station_safety",
    "hydrogen station protection": "hydrogen_refueling_station_safety",
    "hydrogen station prevention": "hydrogen_refueling_station_safety",
    "hydrogen station suppression": "hydrogen_refueling_station_safety",
    "hydrogen station monitoring": "hydrogen_refueling_station_safety",
    "hydrogen station control": "hydrogen_refueling_station_safety",
    "hydrogen station automation": "hydrogen_refueling_station_safety",
    "hydrogen station instrumentation": "hydrogen_refueling_station_safety",
    "hydrogen station sensors": "hydrogen_refueling_station_safety",
    "hydrogen station metering": "hydrogen_refueling_station_safety",
    "hydrogen station calibration": "hydrogen_refueling_station_safety",
    "hydrogen station testing": "hydrogen_refueling_station_safety",
    "hydrogen station inspection": "hydrogen_refueling_station_safety",
    "hydrogen station certification": "hydrogen_refueling_station_safety",
    "hydrogen station compliance": "hydrogen_refueling_station_safety",
    "hydrogen station regulation": "hydrogen_refueling_station_safety",
    "hydrogen station standard": "hydrogen_refueling_station_safety",
    "hydrogen station standards": "hydrogen_refueling_station_safety",
    "hydrogen station requirements": "hydrogen_refueling_station_safety",
    "hydrogen station specification": "hydrogen_refueling_station_safety",
    "hydrogen station specs": "hydrogen_refueling_station_safety",
    "hydrogen station guidelines": "hydrogen_refueling_station_safety",
    "hydrogen station codes": "hydrogen_refueling_station_safety",
    "hydrogen station policies": "hydrogen_refueling_station_safety",
    "hydrogen station procedures": "hydrogen_refueling_station_safety",
    "hydrogen station protocols": "hydrogen_refueling_station_safety",
    "hydrogen station training": "hydrogen_refueling_station_safety",
    # Misspellings for standards
    "iso 14687-1": "iso_14687",
    "iso14687-1": "iso_14687",
    "iso 14687 1": "iso_14687",
    "iso14687 1": "iso_14687",
    "iso 14687 fuel": "iso_14687",
    "iso 14687 fuel quality": "iso_14687",
    "iso 14687 fuel specification": "iso_14687",
    "iso 14687 fuel specs": "iso_14687",
    "iso 14687 fuel requirements": "iso_14687",
    "iso 14687 fuel regulation": "iso_14687",
    "iso 14687 fuel standard": "iso_14687",
    "iso 14687 fuel standards": "iso_14687",
    "iso 14687 fuel compliance": "iso_14687",
    "iso 14687 fuel certification": "iso_14687",
    "iso 14687 fuel inspection": "iso_14687",
    "iso 14687 fuel testing": "iso_14687",
    "iso 14687 fuel calibration": "iso_14687",
    "iso 14687 fuel metering": "iso_14687",
    "iso 14687 fuel sensors": "iso_14687",
    "iso 14687 fuel instrumentation": "iso_14687",
    "iso 14687 fuel automation": "iso_14687",
    "iso 14687 fuel control": "iso_14687",
    "iso 14687 fuel monitoring": "iso_14687",
    "iso 14687 fuel operation": "iso_14687",
    "iso 14687 fuel operations": "iso_14687",
    "iso 14687 fuel maintenance": "iso_14687",
    "iso 14687 fuel commissioning": "iso_14687",
    "iso 14687 fuel decommissioning": "iso_14687",
    "iso 14687 fuel guidelines": "iso_14687",
    "iso 14687 fuel codes": "iso_14687",
    "iso 14687 fuel policies": "iso_14687",
    "iso 14687 fuel procedures": "iso_14687",
    "iso 14687 fuel protocols": "iso_14687",
    "iso 14687 fuel training": "iso_14687",
    "sae j2719-1": "sae_j2719",
    "sae j2719 1": "sae_j2719",
    "sae j2719 fuel": "sae_j2719",
    "sae j2719 fuel quality": "sae_j2719",
    "sae j2719 fuel specification": "sae_j2719",
    "sae j2719 fuel specs": "sae_j2719",
    "sae j2719 fuel requirements": "sae_j2719",
    "sae j2719 fuel regulation": "sae_j2719",
    "sae j2719 fuel standard": "sae_j2719",
    "sae j2719 fuel standards": "sae_j2719",
    "sae j2719 fuel compliance": "sae_j2719",
    "sae j2719 fuel certification": "sae_j2719",
    "sae j2719 fuel inspection": "sae_j2719",
    "sae j2719 fuel testing": "sae_j2719",
    "sae j2719 fuel calibration": "sae_j2719",
    "sae j2719 fuel metering": "sae_j2719",
    "sae j2719 fuel sensors": "sae_j2719",
    "sae j2719 fuel instrumentation": "sae_j2719",
    "sae j2719 fuel automation": "sae_j2719",
    "sae j2719 fuel control": "sae_j2719",
    "sae j2719 fuel monitoring": "sae_j2719",
    "sae j2719 fuel operation": "sae_j2719",
    "sae j2719 fuel operations": "sae_j2719",
    "sae j2719 fuel maintenance": "sae_j2719",
    "sae j2719 fuel commissioning": "sae_j2719",
    "sae j2719 fuel decommissioning": "sae_j2719",
    "sae j2719 fuel guidelines": "sae_j2719",
    "sae j2719 fuel codes": "sae_j2719",
    "sae j2719 fuel policies": "sae_j2719",
    "sae j2719 fuel procedures": "sae_j2719",
    "sae j2719 fuel protocols": "sae_j2719",
    "sae j2719 fuel training": "sae_j2719",
    # Misspellings for embrittlement
    "hydrogen embrittle": "hydrogen_embrittlement",
    "hydrogen embrittled": "hydrogen_embrittlement",
    "hydrogen embrittling": "hydrogen_embrittlement",
    "hydrogen embrittlement pipeline": "hydrogen_embrittlement",
    "pipeline embrittlement hydrogen": "hydrogen_embrittlement",
    "embrittlement hydrogen": "hydrogen_embrittlement",
    "embrittlement pipeline": "hydrogen_embrittlement",
    "embrittlement pipelines": "hydrogen_embrittlement",
    "embrittlement in pipelines": "hydrogen_embrittlement",
    "embrittlement in hydrogen pipelines": "hydrogen_embrittlement",
    "embrittlement in hydrogen": "hydrogen_embrittlement",
    # Misspellings for LCOH
    "levelised cost of hydrogen": "lcoh",
    "levelized hydrogen cost": "lcoh",
    "levelised hydrogen cost": "lcoh",
    "levelized cost hydrogen": "lcoh",
    "levelised cost hydrogen": "lcoh",
    "hydrogen levelized cost": "lcoh",
    "hydrogen levelised cost": "lcoh",
    "hydrogen cost levelized": "lcoh",
    "hydrogen cost levelised": "lcoh",
    "hydrogen price levelized": "lcoh",
    "hydrogen price levelised": "lcoh",
    # Misspellings for PEM
    "proton exchange membran": "pem_electrolysis",
    "proton exchange membrana": "pem_electrolysis",
    "proton exchange membrame": "pem_electrolysis",
    "proton exchange membrame electrolysis": "pem_electrolysis",
    "proton exchange membran electrolysis": "pem_electrolysis",
    "proton exchange membrana electrolysis": "pem_electrolysis",
    "proton exchange membrame electrolyzer": "pem_electrolysis",
    "proton exchange membran electrolyzer": "pem_electrolysis",
    "proton exchange membrana electrolyzer": "pem_electrolysis",
    "proton exchange membrame cell": "pem_electrolysis",
    "proton exchange membran cell": "pem_electrolysis",
    "proton exchange membrana cell": "pem_electrolysis",
    # Misspellings for SMR
    "steam methane reform": "smr",
    "steam methane reformation": "smr",
    "steam methane reformer": "smr",
    "steam methane reforming process": "smr",
    "steam methane reforming technology": "smr",
    "steam methane reforming plant": "smr",
    "steam methane reforming unit": "smr",
    "steam methane reforming system": "smr",
    "steam methane reforming facility": "smr",
    "steam methane reforming station": "smr",
    "steam methane reforming operation": "smr",
    "steam methane reforming operations": "smr",
    "steam methane reforming maintenance": "smr",
    "steam methane reforming commissioning": "smr",
    "steam methane reforming decommissioning": "smr",
    "steam methane reforming monitoring": "smr",
    "steam methane reforming control": "smr",
    "steam methane reforming automation": "smr",
    "steam methane reforming instrumentation": "smr",
    "steam methane reforming sensors": "smr",
    "steam methane reforming metering": "smr",
    "steam methane reforming calibration": "smr",
    "steam methane reforming testing": "smr",
    "steam methane reforming inspection": "smr",
    "steam methane reforming certification": "smr",
    "steam methane reforming compliance": "smr",
    "steam methane reforming regulation": "smr",
    "steam methane reforming standard": "smr",
    "steam methane reforming standards": "smr",
    "steam methane reforming requirements": "smr",
    "steam methane reforming specification": "smr",
    "steam methane reforming specs": "smr",
    "steam methane reforming guidelines": "smr",
    "steam methane reforming codes": "smr",
    "steam methane reforming policies": "smr",
    "steam methane reforming procedures": "smr",
    "steam methane reforming protocols": "smr",
    "steam methane reforming training": "smr",
    # Misspellings for alkaline
    "alkaline electrolyser": "alkaline_electrolysis",
    "alkaline electrolizer": "alkaline_electrolysis",
    "alkaline electroliser": "alkaline_electrolysis",
    "alkaline electrolizer cell": "alkaline_electrolysis",
    "alkaline electroliser cell": "alkaline_electrolysis",
    "alkaline electrolizer stack": "alkaline_electrolysis",
    "alkaline electroliser stack": "alkaline_electrolysis",
    "alkaline electrolizer membrane": "alkaline_electrolysis",
    "alkaline electroliser membrane": "alkaline_electrolysis",
    "alkaline electrolizer electrode": "alkaline_electrolysis",
    "alkaline electroliser electrode": "alkaline_electrolysis",
    "alkaline electrolizer catalyst": "alkaline_electrolysis",
    "alkaline electroliser catalyst": "alkaline_electrolysis",
    # Misspellings for type IV
    "type iv storag": "type_iv_storage",
    "type iv storag tank": "type_iv_storage",
    "type iv storag vessel": "type_iv_storage",
    "type iv storag cylinder": "type_iv_storage",
    "type iv storag hydrogen": "type_iv_storage",
    "type iv storag hydrogen tank": "type_iv_storage",
    "type iv storag hydrogen vessel": "type_iv_storage",
    "type iv storag hydrogen cylinder": "type_iv_storage",
    "type iv storag hydrogen storage": "type_iv_storage",
    "type iv storag hydrogen storage tank": "type_iv_storage",
    "type iv storag hydrogen storage vessel": "type_iv_storage",
    "type iv storag hydrogen storage cylinder": "type_iv_storage",
    # Misspellings for LH2
    "liquid hydrogen storag": "liquid_hydrogen_storage",
    "liquid hydrogen storag tank": "liquid_hydrogen_storage",
    "liquid hydrogen storag vessel": "liquid_hydrogen_storage",
    "liquid hydrogen storag cylinder": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen tank": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen vessel": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen cylinder": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen storage": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen storage tank": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen storage vessel": "liquid_hydrogen_storage",
    "liquid hydrogen storag hydrogen storage cylinder": "liquid_hydrogen_storage",
    # Misspellings for MEA
    "membrane electrode assemb": "mea",
    "membrane electrode assemb fuel cell": "mea",
    "membrane electrode assemb stack": "mea",
    "membrane electrode assemb membrane": "mea",
    "membrane electrode assemb electrode": "mea",
    "membrane electrode assemb catalyst": "mea",
    # Misspellings for SOFC
    "solid oxide fuel cel": "sofc",
    "solid oxide fuel cel stack": "sofc",
    "solid oxide fuel cel cell": "sofc",
    "solid oxide fuel cel fuel cell": "sofc",
    "solid oxide fuel cel membrane": "sofc",
    "solid oxide fuel cel electrode": "sofc",
    "solid oxide fuel cel catalyst": "sofc",
    # Misspellings for pipeline
    "hydrogen pipelin": "hydrogen_pipeline",
    "hydrogen pipelin embrittlement": "hydrogen_embrittlement",
    "hydrogen pipelin integrity": "hydrogen_pipeline_integrity",
    "hydrogen pipelin safety": "hydrogen_pipeline_safety",
    "hydrogen pipelin standard": "asme_b31_12",
    "hydrogen pipelin code": "asme_b31_12",
    "hydrogen pipelin regulation": "asme_b31_12",
    # Misspellings for refueling station
    "hydrogen refueling stn design": "hydrogen_refueling_station_design",
    "hydrogen fueling stn design": "hydrogen_refueling_station_design",
    "hydrogen refuel stn design": "hydrogen_refueling_station_design",
    "hydrogen refueling stn safety": "hydrogen_refueling_station_safety",
    "hydrogen fueling stn safety": "hydrogen_refueling_station_safety",
    "hydrogen refuel stn safety": "hydrogen_refueling_station_safety",
    # Misspellings for NFPA 2
    "nfpa2 hydrogen": "nfpa_2",
    "nfpa2 code": "nfpa_2",
    "nfpa2 standard": "nfpa_2",
    "nfpa2 regulation": "nfpa_2",
    "nfpa2 compliance": "nfpa_2",
    # Misspellings for metal hydride
    "metal hydrid": "metal_hydride_storage",
    "metal hydrid storage": "metal_hydride_storage",
    "metal hydrid hydrogen": "metal_hydride_storage",
    "metal hydrid hydrogen storage": "metal_hydride_storage",
    "metal hydrid solid-state storage": "metal_hydride_storage",
    "metal hydrid solid state storage": "metal_hydride_storage",
    "metal hydrid solid storage": "metal_hydride_storage",
    "metal hydrid hydride": "metal_hydride_storage",
    # Misspellings for solid-state hydrogen storage
    "solid-state hydrogen storag": "solid_state_hydrogen_storage",
    "solid state hydrogen storag": "solid_state_hydrogen_storage",
    "solid hydrogen storag": "solid_state_hydrogen_storage",
    "solid-state storag": "solid_state_hydrogen_storage",
    "solid state storag": "solid_state_hydrogen_storage",
    "solid storag": "solid_state_hydrogen_storage",
    "hydrogen hydride storag": "metal_hydride_storage",
    "hydrogen metal hydride storag": "metal_hydride_storage",
    "hydrogen metal hydrid storag": "metal_hydride_storage",
    "hydrogen solid-state storag": "solid_state_hydrogen_storage",
    "hydrogen solid state storag": "solid_state_hydrogen_storage",
    "hydrogen solid storag": "solid_state_hydrogen_storage",
    # Misspellings for fuel quality
    "hydrogen fuel qualty": "hydrogen_fuel_quality",
    "hydrogen qualty": "hydrogen_fuel_quality",
    "hydrogen purty": "hydrogen_fuel_quality",
    "hydrogen contaminnts": "hydrogen_fuel_quality",
    "hydrogen impurty": "hydrogen_fuel_quality",
    "hydrogen impurites": "hydrogen_fuel_quality",
    "hydrogen specifcation": "hydrogen_fuel_quality",
    "hydrogen spcs": "hydrogen_fuel_quality",
    "hydrogen standrds": "hydrogen_fuel_quality",
    "hydrogen standrd": "hydrogen_fuel_quality",
    # Misspellings for standards
    "iso14687 fuel qualty": "iso_14687",
    "iso14687 fuel specifcation": "iso_14687",
    "iso14687 fuel spcs": "iso_14687",
    "iso14687 fuel standrds": "iso_14687",
    "iso14687 fuel standrd": "iso_14687",
    "sae j2719 fuel qualty": "sae_j2719",
    "sae j2719 fuel specifcation": "sae_j2719",
    "sae j2719 fuel spcs": "sae_j2719",
    "sae j2719 fuel standrds": "sae_j2719",
    "sae j2719 fuel standrd": "sae_j2719",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid,
    }

def _normalize_string(term: str) -> str:
    term = term.lower()
    term = term.strip()
    term = re.sub(r"[\s\-]+", " ", term)
    term = re.sub(r"[^a-z0-9\s]", "", term)
    term = re.sub(r"\s+", " ", term)
    return term

def normalize_term(term: str) -> str:
    norm = _normalize_string(term)
    return SEMANTIC_MAP.get(norm, norm)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)