import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "I04_county_filing_monitor"
SEMANTIC_MAP_ENGINE = "I04"

SEMANTIC_MAP = {
    # Filing System Reliability
    "filing system reliability": "filing_system_reliability",
    "system reliability": "filing_system_reliability",
    "reliability of filing system": "filing_system_reliability",
    "filing reliability": "filing_system_reliability",
    "kofile reliability": "filing_system_reliability",
    "clerk system reliability": "filing_system_reliability",
    "county clerk reliability": "filing_system_reliability",
    "filing platform reliability": "filing_system_reliability",
    "filing system uptime": "filing_system_reliability",
    "filing system downtime": "filing_system_reliability",
    "filing system error rate": "filing_system_reliability",
    "filing system failure": "filing_system_reliability",
    "filing system outage": "filing_system_reliability",
    "system outage": "filing_system_reliability",
    "system downtime": "filing_system_reliability",
    "system error": "filing_system_reliability",
    "system failure": "filing_system_reliability",
    "system crash": "filing_system_reliability",
    "system latency": "filing_system_reliability",

    # Tyler PublicSearch Instrument Classification
    "tyler publicsearch instrument classification": "instrument_classification",
    "instrument classification": "instrument_classification",
    "tyler instrument classification": "instrument_classification",
    "publicsearch classification": "instrument_classification",
    "instrument type classification": "instrument_classification",
    "tyler classification": "instrument_classification",
    "document classification": "instrument_classification",
    "doc classification": "instrument_classification",
    "tyler doc classification": "instrument_classification",
    "tyler publicsearch": "instrument_classification",
    "tyler": "instrument_classification",
    "publicsearch": "instrument_classification",

    # TexasFile Filing Volume Analysis
    "texasfile filing volume analysis": "filing_volume_analysis",
    "filing volume analysis": "filing_volume_analysis",
    "filing volume": "filing_volume_analysis",
    "texasfile volume": "filing_volume_analysis",
    "volume analysis": "filing_volume_analysis",
    "filing count analysis": "filing_volume_analysis",
    "filing counts": "filing_volume_analysis",
    "filing statistics": "filing_volume_analysis",
    "filing stats": "filing_volume_analysis",
    "texasfile stats": "filing_volume_analysis",
    "texasfile filing stats": "filing_volume_analysis",
    "filing volume trend": "filing_volume_analysis",
    "volume trend": "filing_volume_analysis",

    # Lease Trend Detection via Clerk Filings
    "lease trend detection via clerk filings": "lease_trend_detection",
    "lease trend detection": "lease_trend_detection",
    "lease trends": "lease_trend_detection",
    "lease trend": "lease_trend_detection",
    "lease filing trend": "lease_trend_detection",
    "lease filings trend": "lease_trend_detection",
    "lease detection": "lease_trend_detection",
    "lease activity detection": "lease_trend_detection",
    "lease activity": "lease_trend_detection",
    "lease monitoring": "lease_trend_detection",
    "lease monitor": "lease_trend_detection",
    "lease trend monitor": "lease_trend_detection",
    "lease trend analysis": "lease_trend_detection",
    "lease analysis": "lease_trend_detection",

    # Deed Transfer Pattern Analysis
    "deed transfer pattern analysis": "deed_transfer_pattern_analysis",
    "deed transfer analysis": "deed_transfer_pattern_analysis",
    "deed transfer pattern": "deed_transfer_pattern_analysis",
    "deed transfer": "deed_transfer_pattern_analysis",
    "deed pattern analysis": "deed_transfer_pattern_analysis",
    "deed pattern": "deed_transfer_pattern_analysis",
    "deed analysis": "deed_transfer_pattern_analysis",
    "deed transfers": "deed_transfer_pattern_analysis",
    "deed monitoring": "deed_transfer_pattern_analysis",
    "deed monitor": "deed_transfer_pattern_analysis",
    "deed trend": "deed_transfer_pattern_analysis",
    "deed trend analysis": "deed_transfer_pattern_analysis",

    # Lien Filing Monitoring and Classification
    "lien filing monitoring and classification": "lien_monitoring_classification",
    "lien monitoring and classification": "lien_monitoring_classification",
    "lien monitoring": "lien_monitoring_classification",
    "lien classification": "lien_monitoring_classification",
    "lien filings monitoring": "lien_monitoring_classification",
    "lien filings classification": "lien_monitoring_classification",
    "lien filing monitor": "lien_monitoring_classification",
    "lien monitor": "lien_monitoring_classification",
    "lien filing classification": "lien_monitoring_classification",
    "lien filing": "lien_monitoring_classification",
    "lien filings": "lien_monitoring_classification",
    "lien filing analysis": "lien_monitoring_classification",
    "lien analysis": "lien_monitoring_classification",

    # Lis Pendens Tracking and Alerting
    "lis pendens tracking and alerting": "lis_pendens_tracking_alerting",
    "lis pendens tracking": "lis_pendens_tracking_alerting",
    "lis pendens alerting": "lis_pendens_tracking_alerting",
    "lis pendens monitor": "lis_pendens_tracking_alerting",
    "lis pendens monitoring": "lis_pendens_tracking_alerting",
    "lis pendens alerts": "lis_pendens_tracking_alerting",
    "lis pendens alert": "lis_pendens_tracking_alerting",
    "lis pendens": "lis_pendens_tracking_alerting",
    "lis pendens filing": "lis_pendens_tracking_alerting",
    "lis pendens filings": "lis_pendens_tracking_alerting",
    "lis pendens trend": "lis_pendens_tracking_alerting",
    "lis pendens analysis": "lis_pendens_tracking_alerting",

    # Probate Filing Alerts and Monitoring
    "probate filing alerts and monitoring": "probate_filing_alerts_monitoring",
    "probate filing alerts": "probate_filing_alerts_monitoring",
    "probate filing monitoring": "probate_filing_alerts_monitoring",
    "probate filing alert": "probate_filing_alerts_monitoring",
    "probate monitoring": "probate_filing_alerts_monitoring",
    "probate alert": "probate_filing_alerts_monitoring",
    "probate alerts": "probate_filing_alerts_monitoring",
    "probate filings monitoring": "probate_filing_alerts_monitoring",
    "probate filings alerts": "probate_filing_alerts_monitoring",
    "probate filings": "probate_filing_alerts_monitoring",
    "probate filing": "probate_filing_alerts_monitoring",
    "probate analysis": "probate_filing_alerts_monitoring",

    # Assignment Chain Tracking
    "assignment chain tracking": "assignment_chain_tracking",
    "assignment chain": "assignment_chain_tracking",
    "assignment tracking": "assignment_chain_tracking",
    "assignment monitor": "assignment_chain_tracking",
    "assignment chain monitor": "assignment_chain_tracking",
    "assignment chain analysis": "assignment_chain_tracking",
    "assignment chain trend": "assignment_chain_tracking",
    "assignment chain alerts": "assignment_chain_tracking",
    "assignment chain alert": "assignment_chain_tracking",
    "assignment chain monitoring": "assignment_chain_tracking",
    "assignment chain filings": "assignment_chain_tracking",
    "assignment filings": "assignment_chain_tracking",
    "assignment filing": "assignment_chain_tracking",

    # Release of Lien Monitoring
    "release of lien monitoring": "release_of_lien_monitoring",
    "release of lien": "release_of_lien_monitoring",
    "lien release monitoring": "release_of_lien_monitoring",
    "lien release": "release_of_lien_monitoring",
    "release monitoring": "release_of_lien_monitoring",
    "release monitor": "release_of_lien_monitoring",
    "release of lien filings": "release_of_lien_monitoring",
    "release filings": "release_of_lien_monitoring",
    "release filing": "release_of_lien_monitoring",
    "release of lien alert": "release_of_lien_monitoring",
    "release of lien alerts": "release_of_lien_monitoring",

    # Mechanics Lien Detection and Monitoring
    "mechanics lien detection and monitoring": "mechanics_lien_detection_monitoring",
    "mechanics lien detection": "mechanics_lien_detection_monitoring",
    "mechanics lien monitoring": "mechanics_lien_detection_monitoring",
    "mechanics lien": "mechanics_lien_detection_monitoring",
    "mechanic lien detection": "mechanics_lien_detection_monitoring",
    "mechanic lien monitoring": "mechanics_lien_detection_monitoring",
    "mechanic lien": "mechanics_lien_detection_monitoring",
    "mechanics lien filings": "mechanics_lien_detection_monitoring",
    "mechanics lien filing": "mechanics_lien_detection_monitoring",
    "mechanics lien alert": "mechanics_lien_detection_monitoring",
    "mechanics lien alerts": "mechanics_lien_detection_monitoring",
    "mechanics lien analysis": "mechanics_lien_detection_monitoring",

    # Federal Tax Lien Tracking
    "federal tax lien tracking": "federal_tax_lien_tracking",
    "federal tax lien": "federal_tax_lien_tracking",
    "tax lien tracking": "federal_tax_lien_tracking",
    "tax lien monitor": "federal_tax_lien_tracking",
    "tax lien monitoring": "federal_tax_lien_tracking",
    "tax lien": "federal_tax_lien_tracking",
    "federal lien tracking": "federal_tax_lien_tracking",
    "federal lien": "federal_tax_lien_tracking",
    "federal tax lien filings": "federal_tax_lien_tracking",
    "tax lien filings": "federal_tax_lien_tracking",
    "tax lien filing": "federal_tax_lien_tracking",
    "federal tax lien alert": "federal_tax_lien_tracking",
    "federal tax lien alerts": "federal_tax_lien_tracking",

    # Judgment Lien Identification
    "judgment lien identification": "judgment_lien_identification",
    "judgment lien": "judgment_lien_identification",
    "judgement lien identification": "judgment_lien_identification",
    "judgement lien": "judgment_lien_identification",
    "judgment lien monitor": "judgment_lien_identification",
    "judgment lien monitoring": "judgment_lien_identification",
    "judgment lien filings": "judgment_lien_identification",
    "judgment lien filing": "judgment_lien_identification",
    "judgment lien alert": "judgment_lien_identification",
    "judgment lien alerts": "judgment_lien_identification",
    "judgment lien analysis": "judgment_lien_identification",

    # UCC Filing Monitoring
    "ucc filing monitoring": "ucc_filing_monitoring",
    "ucc monitoring": "ucc_filing_monitoring",
    "ucc filing": "ucc_filing_monitoring",
    "ucc filings": "ucc_filing_monitoring",
    "ucc monitor": "ucc_filing_monitoring",
    "ucc alert": "ucc_filing_monitoring",
    "ucc alerts": "ucc_filing_monitoring",
    "ucc filing alert": "ucc_filing_monitoring",
    "ucc filing alerts": "ucc_filing_monitoring",
    "ucc filing analysis": "ucc_filing_monitoring",

    # Plat Filing Tracking
    "plat filing tracking": "plat_filing_tracking",
    "plat tracking": "plat_filing_tracking",
    "plat filing": "plat_filing_tracking",
    "plat filings": "plat_filing_tracking",
    "plat monitor": "plat_filing_tracking",
    "plat alert": "plat_filing_tracking",
    "plat alerts": "plat_filing_tracking",
    "plat filing alert": "plat_filing_tracking",
    "plat filing alerts": "plat_filing_tracking",
    "plat filing analysis": "plat_filing_tracking",

    # New Subdivision Detection
    "new subdivision detection": "new_subdivision_detection",
    "subdivision detection": "new_subdivision_detection",
    "new subdivision": "new_subdivision_detection",
    "subdivision monitor": "new_subdivision_detection",
    "subdivision monitoring": "new_subdivision_detection",
    "subdivision filings": "new_subdivision_detection",
    "subdivision filing": "new_subdivision_detection",
    "new subdivision monitor": "new_subdivision_detection",
    "new subdivision monitoring": "new_subdivision_detection",
    "new subdivision filings": "new_subdivision_detection",
    "new subdivision filing": "new_subdivision_detection",
    "subdivision alert": "new_subdivision_detection",
    "subdivision alerts": "new_subdivision_detection",

    # ROW Acquisition Pattern Analysis
    "row acquisition pattern analysis": "row_acquisition_pattern_analysis",
    "row acquisition analysis": "row_acquisition_pattern_analysis",
    "row acquisition pattern": "row_acquisition_pattern_analysis",
    "row acquisition": "row_acquisition_pattern_analysis",
    "right of way acquisition pattern analysis": "row_acquisition_pattern_analysis",
    "right of way acquisition analysis": "row_acquisition_pattern_analysis",
    "right of way acquisition pattern": "row_acquisition_pattern_analysis",
    "right of way acquisition": "row_acquisition_pattern_analysis",
    "row acquisition monitor": "row_acquisition_pattern_analysis",
    "row acquisition monitoring": "row_acquisition_pattern_analysis",
    "row acquisition filings": "row_acquisition_pattern_analysis",
    "row acquisition filing": "row_acquisition_pattern_analysis",
    "row acquisition alert": "row_acquisition_pattern_analysis",
    "row acquisition alerts": "row_acquisition_pattern_analysis",

    # Surface Use Agreement Filings
    "surface use agreement filings": "surface_use_agreement_filings",
    "surface use agreement filing": "surface_use_agreement_filings",
    "surface use agreement": "surface_use_agreement_filings",
    "surface use agreement monitor": "surface_use_agreement_filings",
    "surface use agreement monitoring": "surface_use_agreement_filings",
    "surface use agreement alert": "surface_use_agreement_filings",
    "surface use agreement alerts": "surface_use_agreement_filings",
    "surface use agreement analysis": "surface_use_agreement_filings",

    # Pipeline Easement Filing Monitoring
    "pipeline easement filing monitoring": "pipeline_easement_filing_monitoring",
    "pipeline easement monitoring": "pipeline_easement_filing_monitoring",
    "pipeline easement filing": "pipeline_easement_filing_monitoring",
    "pipeline easement filings": "pipeline_easement_filing_monitoring",
    "pipeline easement monitor": "pipeline_easement_filing_monitoring",
    "pipeline easement alert": "pipeline_easement_filing_monitoring",
    "pipeline easement alerts": "pipeline_easement_filing_monitoring",
    "pipeline easement analysis": "pipeline_easement_filing_monitoring",

    # Operator Activity Inference from Filings
    "operator activity inference from filings": "operator_activity_inference",
    "operator activity inference": "operator_activity_inference",
    "operator activity": "operator_activity_inference",
    "operator inference": "operator_activity_inference",
    "operator activity monitor": "operator_activity_inference",
    "operator activity monitoring": "operator_activity_inference",
    "operator activity alert": "operator_activity_inference",
    "operator activity alerts": "operator_activity_inference",
    "operator activity analysis": "operator_activity_inference",

    # Instrument Type Classification Accuracy
    "instrument type classification accuracy": "instrument_type_classification_accuracy",
    "instrument classification accuracy": "instrument_type_classification_accuracy",
    "instrument type accuracy": "instrument_type_classification_accuracy",
    "instrument accuracy": "instrument_type_classification_accuracy",
    "classification accuracy": "instrument_type_classification_accuracy",
    "type classification accuracy": "instrument_type_classification_accuracy",
    "doc type classification accuracy": "instrument_type_classification_accuracy",
    "document type classification accuracy": "instrument_type_classification_accuracy",

    # Data Completeness in County Clerk Filings
    "data completeness in county clerk filings": "data_completeness_county_clerk_filings",
    "county clerk filings data completeness": "data_completeness_county_clerk_filings",
    "data completeness": "data_completeness_county_clerk_filings",
    "county clerk data completeness": "data_completeness_county_clerk_filings",
    "clerk filings data completeness": "data_completeness_county_clerk_filings",
    "filings data completeness": "data_completeness_county_clerk_filings",
    "county clerk filings completeness": "data_completeness_county_clerk_filings",
    "county clerk completeness": "data_completeness_county_clerk_filings",
    "filing completeness": "data_completeness_county_clerk_filings",
    "data completeness monitor": "data_completeness_county_clerk_filings",
    "data completeness monitoring": "data_completeness_county_clerk_filings",

    # Audit Log Completeness in Clerk Filing Systems
    "audit log completeness in clerk filing systems": "audit_log_completeness",
    "audit log completeness": "audit_log_completeness",
    "audit log": "audit_log_completeness",
    "audit log monitor": "audit_log_completeness",
    "audit log monitoring": "audit_log_completeness",
    "audit log completeness monitor": "audit_log_completeness",
    "audit log completeness monitoring": "audit_log_completeness",
    "audit log completeness analysis": "audit_log_completeness",

    # OCR Accuracy in Clerk Filing Systems
    "ocr accuracy in clerk filing systems": "ocr_accuracy",
    "ocr accuracy": "ocr_accuracy",
    "ocr": "ocr_accuracy",
    "ocr monitor": "ocr_accuracy",
    "ocr monitoring": "ocr_accuracy",
    "ocr accuracy monitor": "ocr_accuracy",
    "ocr accuracy monitoring": "ocr_accuracy",
    "ocr accuracy analysis": "ocr_accuracy",
    "optical character recognition accuracy": "ocr_accuracy",
    "optical character recognition": "ocr_accuracy",

    # API Availability and Latency in Clerk Filing Platforms
    "api availability and latency in clerk filing platforms": "api_availability_latency",
    "api availability and latency": "api_availability_latency",
    "api availability": "api_availability_latency",
    "api latency": "api_availability_latency",
    "api monitor": "api_availability_latency",
    "api monitoring": "api_availability_latency",
    "api availability monitor": "api_availability_latency",
    "api latency monitor": "api_availability_latency",
    "api availability monitoring": "api_availability_latency",
    "api latency monitoring": "api_availability_latency",
    "api availability analysis": "api_availability_latency",
    "api latency analysis": "api_availability_latency",

    # Webhook Subscription Reliability in Clerk Filing Platforms
    "webhook subscription reliability in clerk filing platforms": "webhook_subscription_reliability",
    "webhook subscription reliability": "webhook_subscription_reliability",
    "webhook reliability": "webhook_subscription_reliability",
    "webhook subscription": "webhook_subscription_reliability",
    "webhook monitor": "webhook_subscription_reliability",
    "webhook monitoring": "webhook_subscription_reliability",
    "webhook subscription monitor": "webhook_subscription_reliability",
    "webhook subscription monitoring": "webhook_subscription_reliability",
    "webhook subscription analysis": "webhook_subscription_reliability",

    # Chain-of-Custody Features in Clerk Filing Systems
    "chain-of-custody features in clerk filing systems": "chain_of_custody_features",
    "chain-of-custody features": "chain_of_custody_features",
    "chain of custody features": "chain_of_custody_features",
    "chain of custody": "chain_of_custody_features",
    "chain-of-custody": "chain_of_custody_features",
    "chain of custody monitor": "chain_of_custody_features",
    "chain of custody monitoring": "chain_of_custody_features",
    "chain-of-custody monitor": "chain_of_custody_features",
    "chain-of-custody monitoring": "chain_of_custody_features",
    "chain of custody analysis": "chain_of_custody_features",
    "chain-of-custody analysis": "chain_of_custody_features",

    # Duplicate Filing Reconciliation
    "duplicate filing reconciliation": "duplicate_filing_reconciliation",
    "duplicate reconciliation": "duplicate_filing_reconciliation",
    "duplicate filing": "duplicate_filing_reconciliation",
    "duplicate filings": "duplicate_filing_reconciliation",
    "duplicate monitor": "duplicate_filing_reconciliation",
    "duplicate monitoring": "duplicate_filing_reconciliation",
    "duplicate filing monitor": "duplicate_filing_reconciliation",
    "duplicate filing monitoring": "duplicate_filing_reconciliation",
    "duplicate filing analysis": "duplicate_filing_reconciliation",

    # Batch Polling Frequency Optimization
    "batch polling frequency optimization": "batch_polling_frequency_optimization",
    "batch polling optimization": "batch_polling_frequency_optimization",
    "batch polling frequency": "batch_polling_frequency_optimization",
    "batch polling": "batch_polling_frequency_optimization",
    "polling frequency optimization": "batch_polling_frequency_optimization",
    "polling optimization": "batch_polling_frequency_optimization",
    "batch polling monitor": "batch_polling_frequency_optimization",
    "batch polling monitoring": "batch_polling_frequency_optimization",
    "batch polling frequency monitor": "batch_polling_frequency_optimization",
    "batch polling frequency monitoring": "batch_polling_frequency_optimization",
    "batch polling frequency analysis": "batch_polling_frequency_optimization",

    # Instrument Metadata Completeness
    "instrument metadata completeness": "instrument_metadata_completeness",
    "metadata completeness": "instrument_metadata_completeness",
    "instrument metadata": "instrument_metadata_completeness",
    "metadata monitor": "instrument_metadata_completeness",
    "metadata monitoring": "instrument_metadata_completeness",
    "instrument metadata monitor": "instrument_metadata_completeness",
    "instrument metadata monitoring": "instrument_metadata_completeness",
    "instrument metadata completeness monitor": "instrument_metadata_completeness",
    "instrument metadata completeness monitoring": "instrument_metadata_completeness",
    "instrument metadata completeness analysis": "instrument_metadata_completeness",

    # Misspellings, abbreviations, acronyms, synonyms, related terms
    "filing sys reliability": "filing_system_reliability",
    "sys reliability": "filing_system_reliability",
    "filing sys": "filing_system_reliability",
    "sys uptime": "filing_system_reliability",
    "sys downtime": "filing_system_reliability",
    "sys error": "filing_system_reliability",
    "sys failure": "filing_system_reliability",
    "sys crash": "filing_system_reliability",
    "sys latency": "filing_system_reliability",
    "kofile": "filing_system_reliability",
    "kofile system": "filing_system_reliability",
    "kofile filing": "filing_system_reliability",
    "tyler ps": "instrument_classification",
    "ps classification": "instrument_classification",
    "ps": "instrument_classification",
    "doc type": "instrument_classification",
    "doc type classification": "instrument_classification",
    "doc type accuracy": "instrument_type_classification_accuracy",
    "doc accuracy": "instrument_type_classification_accuracy",
    "instrument meta completeness": "instrument_metadata_completeness",
    "meta completeness": "instrument_metadata_completeness",
    "meta monitor": "instrument_metadata_completeness",
    "meta monitoring": "instrument_metadata_completeness",
    "meta completeness monitor": "instrument_metadata_completeness",
    "meta completeness monitoring": "instrument_metadata_completeness",
    "meta completeness analysis": "instrument_metadata_completeness",
    "plat": "plat_filing_tracking",
    "subdivision": "new_subdivision_detection",
    "row": "row_acquisition_pattern_analysis",
    "right of way": "row_acquisition_pattern_analysis",
    "surface use": "surface_use_agreement_filings",
    "pipeline easement": "pipeline_easement_filing_monitoring",
    "operator": "operator_activity_inference",
    "assignment": "assignment_chain_tracking",
    "release": "release_of_lien_monitoring",
    "mechanic": "mechanics_lien_detection_monitoring",
    "mechanics": "mechanics_lien_detection_monitoring",
    "tax lien": "federal_tax_lien_tracking",
    "judgement": "judgment_lien_identification",
    "judgment": "judgment_lien_identification",
    "ucc": "ucc_filing_monitoring",
    "audit": "audit_log_completeness",
    "webhook": "webhook_subscription_reliability",
    "chain of custody feature": "chain_of_custody_features",
    "chain-of-custody feature": "chain_of_custody_features",
    "duplicate": "duplicate_filing_reconciliation",
    "batch polling freq optimization": "batch_polling_frequency_optimization",
    "batch polling freq": "batch_polling_frequency_optimization",
    "polling freq optimization": "batch_polling_frequency_optimization",
    "polling freq": "batch_polling_frequency_optimization",
    "instrument meta": "instrument_metadata_completeness",
    "meta": "instrument_metadata_completeness",

    # Misspellings
    "filing reliabilty": "filing_system_reliability",
    "reliabilty": "filing_system_reliability",
    "filing systm reliability": "filing_system_reliability",
    "filing systm": "filing_system_reliability",
    "filing platfrom reliability": "filing_system_reliability",
    "platfrom reliability": "filing_system_reliability",
    "instrument classificaton": "instrument_classification",
    "classificaton": "instrument_classification",
    "instrument type classificaton": "instrument_classification",
    "filing volme analysis": "filing_volume_analysis",
    "volme analysis": "filing_volume_analysis",
    "lease trnd detection": "lease_trend_detection",
    "trnd detection": "lease_trend_detection",
    "deed tranfer pattern analysis": "deed_transfer_pattern_analysis",
    "tranfer pattern analysis": "deed_transfer_pattern_analysis",
    "lien filng monitoring": "lien_monitoring_classification",
    "filng monitoring": "lien_monitoring_classification",
    "lis pendens traking and alerting": "lis_pendens_tracking_alerting",
    "traking and alerting": "lis_pendens_tracking_alerting",
    "probate filng alerts and monitoring": "probate_filing_alerts_monitoring",
    "filng alerts and monitoring": "probate_filing_alerts_monitoring",
    "assignment chian tracking": "assignment_chain_tracking",
    "chian tracking": "assignment_chain_tracking",
    "release of lien monitring": "release_of_lien_monitoring",
    "monitring": "release_of_lien_monitoring",
    "mechanics lien detction and monitoring": "mechanics_lien_detection_monitoring",
    "detction and monitoring": "mechanics_lien_detection_monitoring",
    "federal tax lien traking": "federal_tax_lien_tracking",
    "traking": "federal_tax_lien_tracking",
    "judgment lien identfication": "judgment_lien_identification",
    "identfication": "judgment_lien_identification",
    "ucc filng monitoring": "ucc_filing_monitoring",
    "filng monitoring": "ucc_filing_monitoring",
    "plat filng tracking": "plat_filing_tracking",
    "filng tracking": "plat_filing_tracking",
    "new subdivison detection": "new_subdivision_detection",
    "subdivison detection": "new_subdivision_detection",
    "row acquisiton pattern analysis": "row_acquisition_pattern_analysis",
    "acquisiton pattern analysis": "row_acquisition_pattern_analysis",
    "surface use agrement filings": "surface_use_agreement_filings",
    "agrement filings": "surface_use_agreement_filings",
    "pipeline easment filing monitoring": "pipeline_easement_filing_monitoring",
    "easment filing monitoring": "pipeline_easement_filing_monitoring",
    "operator activty inference from filings": "operator_activity_inference",
    "activty inference from filings": "operator_activity_inference",
    "instrument type classificaton accuracy": "instrument_type_classification_accuracy",
    "classificaton accuracy": "instrument_type_classification_accuracy",
    "data completenss in county clerk filings": "data_completeness_county_clerk_filings",
    "completenss in county clerk filings": "data_completeness_county_clerk_filings",
    "audit log completenss in clerk filing systems": "audit_log_completeness",
    "log completenss in clerk filing systems": "audit_log_completeness",
    "ocr accurcy in clerk filing systems": "ocr_accuracy",
    "accurcy in clerk filing systems": "ocr_accuracy",
    "api availabilty and latency in clerk filing platforms": "api_availability_latency",
    "availabilty and latency in clerk filing platforms": "api_availability_latency",
    "webhook subscription reliabilty in clerk filing platforms": "webhook_subscription_reliability",
    "subscription reliabilty in clerk filing platforms": "webhook_subscription_reliability",
    "chain-of-custody featuers in clerk filing systems": "chain_of_custody_features",
    "featuers in clerk filing systems": "chain_of_custody_features",
    "duplicate filing reconcilation": "duplicate_filing_reconciliation",
    "filing reconcilation": "duplicate_filing_reconciliation",
    "batch polling frequence optimization": "batch_polling_frequency_optimization",
    "frequence optimization": "batch_polling_frequency_optimization",
    "instrument metadata completenss": "instrument_metadata_completeness",
    "metadata completenss": "instrument_metadata_completeness",

    # Abbreviations
    "sys": "filing_system_reliability",
    "ps": "instrument_classification",
    "vol": "filing_volume_analysis",
    "lease": "lease_trend_detection",
    "deed": "deed_transfer_pattern_analysis",
    "lien": "lien_monitoring_classification",
    "lis pendens": "lis_pendens_tracking_alerting",
    "probate": "probate_filing_alerts_monitoring",
    "assignment": "assignment_chain_tracking",
    "release": "release_of_lien_monitoring",
    "mechanics": "mechanics_lien_detection_monitoring",
    "tax": "federal_tax_lien_tracking",
    "judgment": "judgment_lien_identification",
    "ucc": "ucc_filing_monitoring",
    "plat": "plat_filing_tracking",
    "subdivision": "new_subdivision_detection",
    "row": "row_acquisition_pattern_analysis",
    "surface use": "surface_use_agreement_filings",
    "pipeline": "pipeline_easement_filing_monitoring",
    "operator": "operator_activity_inference",
    "meta": "instrument_metadata_completeness",
    "audit": "audit_log_completeness",
    "webhook": "webhook_subscription_reliability",
    "chain": "chain_of_custody_features",
    "duplicate": "duplicate_filing_reconciliation",
    "batch polling": "batch_polling_frequency_optimization",

    # Related terms
    "county clerk": "filing_system_reliability",
    "clerk filing": "filing_system_reliability",
    "clerk filings": "filing_system_reliability",
    "clerk filing system": "filing_system_reliability",
    "county clerk filing": "filing_system_reliability",
    "county clerk filings": "filing_system_reliability",
    "county clerk system": "filing_system_reliability",
    "county clerk filing system": "filing_system_reliability",
    "county clerk filing systems": "filing_system_reliability",
    "county clerk platform": "filing_system_reliability",
    "county clerk platforms": "filing_system_reliability",
    "filing platform": "filing_system_reliability",
    "filing platforms": "filing_system_reliability",
    "filing system": "filing_system_reliability",
    "filing systems": "filing_system_reliability",
    "filing": "filing_system_reliability",
    "filings": "filing_system_reliability",
    "county": "filing_system_reliability",
    "clerk": "filing_system_reliability",

    # More synonyms and related terms
    "instrument": "instrument_classification",
    "document": "instrument_classification",
    "doc": "instrument_classification",
    "type": "instrument_classification",
    "classification": "instrument_classification",
    "analysis": "filing_volume_analysis",
    "trend": "lease_trend_detection",
    "monitoring": "filing_system_reliability",
    "monitor": "filing_system_reliability",
    "alert": "filing_system_reliability",
    "alerts": "filing_system_reliability",
    "tracking": "filing_system_reliability",
    "tracking and alerting": "lis_pendens_tracking_alerting",
    "detection": "lease_trend_detection",
    "pattern analysis": "deed_transfer_pattern_analysis",
    "pattern": "deed_transfer_pattern_analysis",
    "chain": "assignment_chain_tracking",
    "release": "release_of_lien_monitoring",
    "agreement": "surface_use_agreement_filings",
    "easement": "pipeline_easement_filing_monitoring",
    "activity": "operator_activity_inference",
    "accuracy": "instrument_type_classification_accuracy",
    "completeness": "data_completeness_county_clerk_filings",
    "metadata": "instrument_metadata_completeness",
    "reconciliation": "duplicate_filing_reconciliation",
    "optimization": "batch_polling_frequency_optimization",
    "frequency": "batch_polling_frequency_optimization",
    "features": "chain_of_custody_features",
    "feature": "chain_of_custody_features",
    "custody": "chain_of_custody_features",
    "chain-of-custody": "chain_of_custody_features",
    "chain of custody": "chain_of_custody_features",
    "polling": "batch_polling_frequency_optimization",
    "batch": "batch_polling_frequency_optimization",
    "meta": "instrument_metadata_completeness",
    "ocr": "ocr_accuracy",
    "api": "api_availability_latency",
    "webhook": "webhook_subscription_reliability",
    "subscription": "webhook_subscription_reliability",
    "log": "audit_log_completeness",
    "audit": "audit_log_completeness",
    "release of lien": "release_of_lien_monitoring",
    "mechanics lien": "mechanics_lien_detection_monitoring",
    "federal tax lien": "federal_tax_lien_tracking",
    "judgment lien": "judgment_lien_identification",
    "ucc filing": "ucc_filing_monitoring",
    "plat filing": "plat_filing_tracking",
    "new subdivision": "new_subdivision_detection",
    "row acquisition": "row_acquisition_pattern_analysis",
    "surface use agreement": "surface_use_agreement_filings",
    "pipeline easement": "pipeline_easement_filing_monitoring",
    "operator activity": "operator_activity_inference",
    "instrument type classification": "instrument_classification",
    "instrument metadata completeness": "instrument_metadata_completeness",
    "data completeness": "data_completeness_county_clerk_filings",
    "audit log completeness": "audit_log_completeness",
    "ocr accuracy": "ocr_accuracy",
    "api availability": "api_availability_latency",
    "webhook subscription reliability": "webhook_subscription_reliability",
    "chain-of-custody features": "chain_of_custody_features",
    "duplicate filing reconciliation": "duplicate_filing_reconciliation",
    "batch polling frequency optimization": "batch_polling_frequency_optimization",
    "instrument metadata completeness": "instrument_metadata_completeness",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    actual_count = len(SEMANTIC_MAP)
    hash_val = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT and hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)