import hashlib
import unicodedata

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MECH06 Team"
SEMANTIC_MAP_ENGINE = "MECH06_bearing_analysis"

SEMANTIC_MAP = {
    # Rolling Bearing Life Calculation - ISO 281
    "bearing life": "bearing_life",
    "l10 life": "bearing_life",
    "l10": "bearing_life",
    "basic rating life": "bearing_life",
    "iso 281": "bearing_life",
    "dynamic load rating": "dynamic_load_rating",
    "c rating": "dynamic_load_rating",
    "c": "dynamic_load_rating",
    "static load rating": "static_load_rating",
    "c0": "static_load_rating",
    "c0 rating": "static_load_rating",
    "equivalent dynamic load": "equivalent_dynamic_load",
    "p": "equivalent_dynamic_load",
    "axial load": "axial_load",
    "fa": "axial_load",
    "radial load": "radial_load",
    "fr": "radial_load",
    "service factor": "service_factor",
    "application factor": "service_factor",
    "reliability factor": "reliability_factor",
    "x factor": "radial_factor",
    "y factor": "axial_factor",
    "life adjustment factor": "life_adjustment_factor",
    "a1": "life_adjustment_factor",
    "a2": "life_adjustment_factor",
    "a3": "life_adjustment_factor",
    "contamination factor": "contamination_factor",
    "lubrication factor": "lubrication_factor",
    "temperature factor": "temperature_factor",
    "speed factor": "speed_factor",
    "operating hours": "operating_hours",
    "lifetime": "bearing_life",
    "expected life": "bearing_life",
    "fatigue life": "bearing_life",
    "b10 life": "bearing_life",
    "b10": "bearing_life",
    "catalog life": "bearing_life",
    "catalog rating": "dynamic_load_rating",
    "life calculation": "bearing_life",
    "bearing rating": "dynamic_load_rating",
    "bearing capacity": "dynamic_load_rating",
    "load rating": "dynamic_load_rating",
    "load capacity": "dynamic_load_rating",
    # Bearing Fit Selection - Shaft and Housing
    "bearing fit": "bearing_fit",
    "shaft fit": "shaft_fit",
    "housing fit": "housing_fit",
    "interference fit": "interference_fit",
    "press fit": "interference_fit",
    "tight fit": "interference_fit",
    "transition fit": "transition_fit",
    "clearance fit": "clearance_fit",
    "loose fit": "clearance_fit",
    "js6": "shaft_fit",
    "h7": "housing_fit",
    "k6": "shaft_fit",
    "m7": "housing_fit",
    "g6": "shaft_fit",
    "n7": "housing_fit",
    "p6": "shaft_fit",
    "r7": "housing_fit",
    "shaft tolerance": "shaft_fit",
    "housing tolerance": "housing_fit",
    "fit selection": "bearing_fit",
    "mounting fit": "bearing_fit",
    "dismounting fit": "bearing_fit",
    "fit class": "bearing_fit",
    "iso fit": "bearing_fit",
    "japanese fit": "bearing_fit",
    "american fit": "bearing_fit",
    "abec fit": "bearing_fit",
    "snug fit": "clearance_fit",
    "tightening fit": "interference_fit",
    "loose running fit": "clearance_fit",
    "pressing fit": "interference_fit",
    "slip fit": "clearance_fit",
    "drive fit": "interference_fit",
    # Bearing Lubrication Selection - Grease vs Oil
    "bearing lubrication": "bearing_lubrication",
    "lubrication": "bearing_lubrication",
    "grease lubrication": "grease_lubrication",
    "oil lubrication": "oil_lubrication",
    "grease": "grease_lubrication",
    "oil": "oil_lubrication",
    "solid lubricant": "solid_lubricant",
    "dry lubrication": "solid_lubricant",
    "ep grease": "grease_lubrication",
    "lithium grease": "grease_lubrication",
    "polyurea grease": "grease_lubrication",
    "synthetic oil": "oil_lubrication",
    "mineral oil": "oil_lubrication",
    "lubricant selection": "bearing_lubrication",
    "lubricant": "bearing_lubrication",
    "re-lubrication": "relubrication",
    "relubrication": "relubrication",
    "lubrication interval": "relubrication",
    "lubrication frequency": "relubrication",
    "oil bath": "oil_lubrication",
    "oil mist": "oil_lubrication",
    "oil jet": "oil_lubrication",
    "oil-air": "oil_lubrication",
    "oil circulation": "oil_lubrication",
    "oil injection": "oil_lubrication",
    "grease fill": "grease_lubrication",
    "grease packing": "grease_lubrication",
    "lubricant contamination": "lubricant_contamination",
    "lubricant degradation": "lubricant_degradation",
    "lubricant viscosity": "lubricant_viscosity",
    "viscosity": "lubricant_viscosity",
    "viscosity index": "lubricant_viscosity",
    "base oil viscosity": "lubricant_viscosity",
    "nlgI": "grease_lubrication",
    "nlgI grade": "grease_lubrication",
    # Bearing Failure Analysis - Fatigue Spalling
    "bearing failure": "bearing_failure",
    "failure analysis": "bearing_failure",
    "spalling": "fatigue_spalling",
    "fatigue spalling": "fatigue_spalling",
    "flaking": "fatigue_spalling",
    "pitting": "fatigue_spalling",
    "surface fatigue": "fatigue_spalling",
    "subsurface fatigue": "fatigue_spalling",
    "bearing fatigue": "fatigue_spalling",
    "peeling": "fatigue_spalling",
    "cracking": "fatigue_spalling",
    "crack initiation": "fatigue_spalling",
    "crack propagation": "fatigue_spalling",
    "spall": "fatigue_spalling",
    "microspalling": "fatigue_spalling",
    "macropitting": "fatigue_spalling",
    "micro-pitting": "fatigue_spalling",
    "white etching cracks": "white_etching_cracks",
    "wec": "white_etching_cracks",
    "white structure flaking": "white_etching_cracks",
    "wsf": "white_etching_cracks",
    "roller end flaking": "fatigue_spalling",
    "raceway spalling": "fatigue_spalling",
    "raceway pitting": "fatigue_spalling",
    "roller pitting": "fatigue_spalling",
    "inner ring spalling": "fatigue_spalling",
    "outer ring spalling": "fatigue_spalling",
    "rolling element spalling": "fatigue_spalling",
    "rolling element pitting": "fatigue_spalling",
    "spall initiation": "fatigue_spalling",
    "spall propagation": "fatigue_spalling",
    # Vibration Analysis - Bearing Defect Frequencies
    "vibration analysis": "vibration_analysis",
    "bearing vibration": "vibration_analysis",
    "defect frequency": "defect_frequency",
    "bearing defect frequency": "defect_frequency",
    "bpfo": "outer_race_defect_frequency",
    "outer race defect frequency": "outer_race_defect_frequency",
    "outer race frequency": "outer_race_defect_frequency",
    "bpfI": "inner_race_defect_frequency",
    "inner race defect frequency": "inner_race_defect_frequency",
    "inner race frequency": "inner_race_defect_frequency",
    "bsf": "ball_spin_frequency",
    "ball spin frequency": "ball_spin_frequency",
    "ball pass frequency": "ball_pass_frequency",
    "ftf": "fundamental_train_frequency",
    "fundamental train frequency": "fundamental_train_frequency",
    "cage frequency": "fundamental_train_frequency",
    "envelope analysis": "envelope_analysis",
    "demodulation": "envelope_analysis",
    "acceleration enveloping": "envelope_analysis",
    "spectral analysis": "vibration_analysis",
    "fft": "vibration_analysis",
    "frequency spectrum": "vibration_analysis",
    "harmonics": "vibration_analysis",
    "sidebands": "vibration_analysis",
    "bearing frequencies": "defect_frequency",
    "defect frequencies": "defect_frequency",
    "vibration monitoring": "vibration_analysis",
    "condition monitoring": "vibration_analysis",
    "predictive maintenance": "vibration_analysis",
    "cbm": "vibration_analysis",
    "bearing monitoring": "vibration_analysis",
    "peakvue": "envelope_analysis",
    "shock pulse": "envelope_analysis",
    "cepstrum": "vibration_analysis",
    "order analysis": "vibration_analysis",
    "time waveform": "vibration_analysis",
    # API 610 Bearing Requirements - Centrifugal Pumps
    "api 610": "api_610",
    "api": "api_610",
    "centrifugal pump": "centrifugal_pump",
    "pump bearing": "pump_bearing",
    "pump bearing requirements": "api_610",
    "api bearing": "api_610",
    "api 610 bearing": "api_610",
    "thrust bearing": "thrust_bearing",
    "radial bearing": "radial_bearing",
    "journal bearing": "journal_bearing",
    "tilting pad bearing": "tilting_pad_bearing",
    "sleeve bearing": "journal_bearing",
    "ball bearing": "rolling_bearing",
    "roller bearing": "rolling_bearing",
    "antifriction bearing": "rolling_bearing",
    "friction bearing": "journal_bearing",
    "oil ring lubrication": "oil_ring_lubrication",
    "ring oiler": "oil_ring_lubrication",
    "oil bath lubrication": "oil_lubrication",
    "oil mist lubrication": "oil_lubrication",
    "oil system": "oil_lubrication",
    "bearing housing": "bearing_housing",
    "bearing pedestal": "bearing_housing",
    "bearing bracket": "bearing_housing",
    "bearing isolator": "bearing_isolator",
    "labyrinth seal": "bearing_isolator",
    "bearing seal": "bearing_isolator",
    "shaft seal": "shaft_seal",
    "mechanical seal": "shaft_seal",
    "stuffing box": "shaft_seal",
    "seal chamber": "shaft_seal",
    "pump shaft": "shaft",
    "shaft": "shaft",
    # Journal Bearing Design - Hydrodynamic Lubrication
    "journal bearing": "journal_bearing",
    "hydrodynamic lubrication": "hydrodynamic_lubrication",
    "full film lubrication": "hydrodynamic_lubrication",
    "boundary lubrication": "boundary_lubrication",
    "mixed lubrication": "mixed_lubrication",
    "elastohydrodynamic lubrication": "elastohydrodynamic_lubrication",
    "ehdl": "elastohydrodynamic_lubrication",
    "hydrostatic lubrication": "hydrostatic_lubrication",
    "hydrostatic bearing": "hydrostatic_bearing",
    "journal": "journal_bearing",
    "babbitt": "babbitt",
    "white metal": "babbitt",
    "tin babbitt": "babbitt",
    "lead babbitt": "babbitt",
    "bearing clearance": "bearing_clearance",
    "minimum film thickness": "minimum_film_thickness",
    "film thickness": "minimum_film_thickness",
    "oil wedge": "hydrodynamic_lubrication",
    "sommerfeld number": "sommerfeld_number",
    "bearing number": "sommerfeld_number",
    "load capacity": "dynamic_load_rating",
    "pv value": "pv_value",
    "pv factor": "pv_value",
    "unit loading": "unit_loading",
    "specific loading": "unit_loading",
    "eccentricity": "eccentricity",
    "eccentricity ratio": "eccentricity_ratio",
    "attitude angle": "attitude_angle",
    "journal misalignment": "journal_misalignment",
    "misalignment": "journal_misalignment",
    "shaft misalignment": "journal_misalignment",
    "shaft deflection": "shaft_deflection",
    "shaft bending": "shaft_deflection",
    "shaft runout": "shaft_runout",
    "shaft vibration": "shaft_vibration",
    # Tilting Pad Bearing Design - Turbomachinery
    "tilting pad bearing": "tilting_pad_bearing",
    "tilting pad": "tilting_pad_bearing",
    "pivoted pad bearing": "tilting_pad_bearing",
    "pivoted pad": "tilting_pad_bearing",
    "flexure pad bearing": "tilting_pad_bearing",
    "flexure pad": "tilting_pad_bearing",
    "turbomachinery": "turbomachinery",
    "compressor bearing": "tilting_pad_bearing",
    "turbine bearing": "tilting_pad_bearing",
    "generator bearing": "tilting_pad_bearing",
    "pad temperature": "pad_temperature",
    "pad pivot": "pad_pivot",
    "pivot location": "pad_pivot",
    "load between pivots": "load_between_pivots",
    "load on pivot": "load_between_pivots",
    "pad misalignment": "pad_misalignment",
    "pad deflection": "pad_deflection",
    "pad wear": "pad_wear",
    "pad lubrication": "pad_lubrication",
    "pad clearance": "pad_clearance",
    "pad thickness": "pad_thickness",
    "pad spring": "pad_spring",
    "pad support": "pad_support",
    "pad flexibility": "pad_flexibility",
    "pad preload": "pad_preload",
    # Bearing Contamination Control - ISO 4406 Codes
    "contamination control": "contamination_control",
    "iso 4406": "iso_4406",
    "particle count": "particle_count",
    "particle contamination": "particle_contamination",
    "solid contamination": "particle_contamination",
    "liquid contamination": "water_contamination",
    "water contamination": "water_contamination",
    "dirt ingress": "particle_contamination",
    "dust ingress": "particle_contamination",
    "contaminant": "particle_contamination",
    "contaminants": "particle_contamination",
    "cleanliness code": "iso_4406",
    "cleanliness level": "iso_4406",
    "nas 1638": "nas_1638",
    "iso code": "iso_4406",
    "oil cleanliness": "iso_4406",
    "fluid cleanliness": "iso_4406",
    "contamination class": "iso_4406",
    "contamination monitoring": "contamination_monitoring",
    "oil analysis": "oil_analysis",
    "ferrography": "oil_analysis",
    "wear debris": "wear_debris",
    "debris analysis": "wear_debris",
    "contamination failure": "contamination_failure",
    "abrasive wear": "abrasive_wear",
    "adhesive wear": "adhesive_wear",
    "erosive wear": "erosive_wear",
    "corrosive wear": "corrosive_wear",
    # Bearing Brinelling vs False Brinelling
    "brinelling": "brinelling",
    "true brinelling": "brinelling",
    "false brinelling": "false_brinelling",
    "brinell marks": "brinelling",
    "brinell indentation": "brinelling",
    "brinell": "brinelling",
    "brinell damage": "brinelling",
    "brinell wear": "brinelling",
    "brinelling failure": "brinelling",
    "fretting corrosion": "false_brinelling",
    "fretting wear": "false_brinelling",
    "fretting": "false_brinelling",
    "vibration brinelling": "false_brinelling",
    "false brinell": "false_brinelling",
    "false brinell marks": "false_brinelling",
    "false brinell wear": "false_brinelling",
    "false brinell damage": "false_brinelling",
    "brinelling vs false brinelling": "brinelling_vs_false_brinelling",
    # Electrical Erosion - VFD-Induced Bearing Damage
    "electrical erosion": "electrical_erosion",
    "electrical discharge": "electrical_erosion",
    "edm": "electrical_erosion",
    "electrical discharge machining": "electrical_erosion",
    "electrical pitting": "electrical_erosion",
    "electrical fluting": "electrical_fluting",
    "fluting": "electrical_fluting",
    "fluted raceway": "electrical_fluting",
    "vfd": "vfd",
    "variable frequency drive": "vfd",
    "inverter": "vfd",
    "inverter duty": "vfd",
    "shaft voltage": "shaft_voltage",
    "shaft current": "shaft_current",
    "common mode voltage": "common_mode_voltage",
    "common mode current": "common_mode_current",
    "bearing current": "bearing_current",
    "electrical bearing damage": "electrical_erosion",
    "insulated bearing": "insulated_bearing",
    "ceramic bearing": "insulated_bearing",
    "hybrid bearing": "insulated_bearing",
    "insulation": "insulated_bearing",
    "grounding brush": "shaft_grounding",
    "shaft grounding": "shaft_grounding",
    "grounding ring": "shaft_grounding",
    "bearing protection": "shaft_grounding",
    # Bearing Preload - Angular Contact and Tapered Roller
    "bearing preload": "bearing_preload",
    "preload": "bearing_preload",
    "preload setting": "bearing_preload",
    "preload force": "bearing_preload",
    "preload spring": "preload_spring",
    "preload spacer": "preload_spacer",
    "preload adjustment": "bearing_preload",
    "preload measurement": "bearing_preload",
    "preload control": "bearing_preload",
    "angular contact bearing": "angular_contact_bearing",
    "angular contact": "angular_contact_bearing",
    "tapered roller bearing": "tapered_roller_bearing",
    "tapered roller": "tapered_roller_bearing",
    "back-to-back arrangement": "back_to_back_arrangement",
    "face-to-face arrangement": "face_to_face_arrangement",
    "tandem arrangement": "tandem_arrangement",
    "duplex bearing": "duplex_bearing",
    "matched pair": "duplex_bearing",
    "bearing arrangement": "bearing_arrangement",
    "axial rigidity": "axial_rigidity",
    "stiffness": "axial_rigidity",
    "axial stiffness": "axial_rigidity",
    "radial stiffness": "radial_rigidity",
    # Bearing Mounting and Dismounting Procedures
    "bearing mounting": "bearing_mounting",
    "mounting": "bearing_mounting",
    "mounting procedure": "bearing_mounting",
    "mounting method": "bearing_mounting",
    "cold mounting": "cold_mounting",
    "hot mounting": "hot_mounting",
    "thermal mounting": "hot_mounting",
    "induction heater": "hot_mounting",
    "heating plate": "hot_mounting",
    "oil bath heating": "hot_mounting",
    "dry ice": "cold_mounting",
    "liquid nitrogen": "cold_mounting",
    "press mounting": "cold_mounting",
    "hydraulic mounting": "hydraulic_mounting",
    "hydraulic nut": "hydraulic_mounting",
    "hydraulic pump": "hydraulic_mounting",
    "bearing dismounting": "bearing_dismounting",
    "dismounting": "bearing_dismounting",
    "dismounting procedure": "bearing_dismounting",
    "dismounting method": "bearing_dismounting",
    "puller": "bearing_dismounting",
    "mechanical puller": "bearing_dismounting",
    "hydraulic puller": "bearing_dismounting",
    "induction dismounting": "hot_dismounting",
    "hot dismounting": "hot_dismounting",
    "cold dismounting": "cold_dismounting",
    "bearing heater": "hot_mounting",
    "bearing puller": "bearing_dismounting",
    "removal tool": "bearing_dismounting",
    "mounting tool": "bearing_mounting",
    "installation tool": "bearing_mounting",
    "bearing installation": "bearing_mounting",
    "bearing removal": "bearing_dismounting",
    # General and Related Terms
    "bearing": "bearing",
    "roller": "rolling_element",
    "ball": "rolling_element",
    "rolling element": "rolling_element",
    "raceway": "raceway",
    "inner ring": "inner_ring",
    "outer ring": "outer_ring",
    "cage": "cage",
    "separator": "cage",
    "retainer": "cage",
    "seal": "seal",
    "shield": "shield",
    "snap ring": "snap_ring",
    "groove": "groove",
    "shoulder": "shoulder",
    "end cover": "end_cover",
    "locking device": "locking_device",
    "adapter sleeve": "adapter_sleeve",
    "withdrawal sleeve": "withdrawal_sleeve",
    "locknut": "locknut",
    "lock washer": "lock_washer",
    "shaft key": "shaft_key",
    "keyway": "keyway",
    "housing": "housing",
    "plummer block": "plummer_block",
    "pillow block": "plummer_block",
    "bearing unit": "bearing_unit",
    "bearing block": "plummer_block",
    "bearing seat": "bearing_seat",
    "journal seat": "bearing_seat",
    "shaft seat": "bearing_seat",
    "shaft journal": "journal_bearing",
    "shaft shoulder": "shoulder",
    "shaft end": "shaft_end",
    "shaft extension": "shaft_end",
    "shaft collar": "shaft_collar",
    "shaft sleeve": "shaft_sleeve",
    "shaft nut": "shaft_nut",
    "shaft washer": "shaft_washer",
    "shaft seal": "shaft_seal",
    "shaft arrangement": "shaft_arrangement",
    "shaft support": "shaft_support",
    "shaft alignment": "shaft_alignment",
    "shaft coupling": "shaft_coupling",
    "shaft connection": "shaft_coupling",
    "shaft mounting": "bearing_mounting",
    "shaft dismounting": "bearing_dismounting",
    "shaft installation": "bearing_mounting",
    "shaft removal": "bearing_dismounting",
    "shaft bearing": "bearing",
    "bearing shaft": "bearing",
    "bearing housing": "bearing_housing",
    "housing bore": "housing_bore",
    "housing seat": "bearing_seat",
    "housing shoulder": "shoulder",
    "housing end": "end_cover",
    "housing cover": "end_cover",
    "housing cap": "end_cover",
    "housing seal": "bearing_isolator",
    "housing mounting": "bearing_mounting",
    "housing dismounting": "bearing_dismounting",
    "housing installation": "bearing_mounting",
    "housing removal": "bearing_dismounting",
    "housing fit": "housing_fit",
    "housing tolerance": "housing_fit",
    "housing alignment": "shaft_alignment",
    "housing support": "shaft_support",
    "housing arrangement": "bearing_arrangement",
    "housing connection": "shaft_coupling",
    "housing coupling": "shaft_coupling",
    "housing block": "plummer_block",
    "housing unit": "bearing_unit",
    "housing bracket": "bearing_housing",
    "housing pedestal": "bearing_housing",
    "housing base": "bearing_housing",
    "housing seat": "bearing_seat",
    "housing journal": "journal_bearing",
    "housing ring": "outer_ring",
    "housing cage": "cage",
    "housing snap ring": "snap_ring",
    "housing groove": "groove",
    "housing key": "shaft_key",
    "housing keyway": "keyway",
    "housing nut": "locknut",
    "housing washer": "lock_washer",
    "housing sleeve": "adapter_sleeve",
    "housing collar": "shaft_collar",
    "housing spring": "pad_spring",
    "housing support": "shaft_support",
    "housing arrangement": "bearing_arrangement",
    "housing connection": "shaft_coupling",
    "housing mounting": "bearing_mounting",
    "housing dismounting": "bearing_dismounting",
    "housing installation": "bearing_mounting",
    "housing removal": "bearing_dismounting",
    "housing fit": "housing_fit",
    "housing tolerance": "housing_fit",
    "housing alignment": "shaft_alignment",
    "housing support": "shaft_support",
    "housing arrangement": "bearing_arrangement",
    "housing connection": "shaft_coupling",
    "housing coupling": "shaft_coupling",
    "housing block": "plummer_block",
    "housing unit": "bearing_unit",
    "housing bracket": "bearing_housing",
    "housing pedestal": "bearing_housing",
    "housing base": "bearing_housing",
    "housing seat": "bearing_seat",
    "housing journal": "journal_bearing",
    "housing ring": "outer_ring",
    "housing cage": "cage",
    "housing snap ring": "snap_ring",
    "housing groove": "groove",
    "housing key": "shaft_key",
    "housing keyway": "keyway",
    "housing nut": "locknut",
    "housing washer": "lock_washer",
    "housing sleeve": "adapter_sleeve",
    "housing collar": "shaft_collar",
    "housing spring": "pad_spring",
    # Misspellings and Variants
    "bearng": "bearing",
    "bearin": "bearing",
    "bearngs": "bearing",
    "bearigns": "bearing",
    "bearng housing": "bearing_housing",
    "bearng fit": "bearing_fit",
    "bearng failure": "bearing_failure",
    "bearng life": "bearing_life",
    "bearng mounting": "bearing_mounting",
    "bearng dismounting": "bearing_dismounting",
    "bearng lubrication": "bearing_lubrication",
    "bearng preload": "bearing_preload",
    "bearng arrangement": "bearing_arrangement",
    "bearng seat": "bearing_seat",
    "bearng block": "plummer_block",
    "bearng unit": "bearing_unit",
    "bearng bracket": "bearing_housing",
    "bearng pedestal": "bearing_housing",
    "bearng base": "bearing_housing",
    "bearng journal": "journal_bearing",
    "bearng ring": "outer_ring",
    "bearng cage": "cage",
    "bearng snap ring": "snap_ring",
    "bearng groove": "groove",
    "bearng key": "shaft_key",
    "bearng keyway": "keyway",
    "bearng nut": "locknut",
    "bearng washer": "lock_washer",
    "bearng sleeve": "adapter_sleeve",
    "bearng collar": "shaft_collar",
    "bearng spring": "pad_spring",
    "bearng support": "shaft_support",
    "bearng arrangement": "bearing_arrangement",
    "bearng connection": "shaft_coupling",
    "bearng mounting": "bearing_mounting",
    "bearng dismounting": "bearing_dismounting",
    "bearng installation": "bearing_mounting",
    "bearng removal": "bearing_dismounting",
    "bearng fit": "bearing_fit",
    "bearng tolerance": "bearing_fit",
    "bearng alignment": "shaft_alignment",
    "bearng support": "shaft_support",
    "bearng arrangement": "bearing_arrangement",
    "bearng connection": "shaft_coupling",
    "bearng coupling": "shaft_coupling",
    "bearng block": "plummer_block",
    "bearng unit": "bearing_unit",
    "bearng bracket": "bearing_housing",
    "bearng pedestal": "bearing_housing",
    "bearng base": "bearing_housing",
    "bearng seat": "bearing_seat",
    "bearng journal": "journal_bearing",
    "bearng ring": "outer_ring",
    "bearng cage": "cage",
    "bearng snap ring": "snap_ring",
    "bearng groove": "groove",
    "bearng key": "shaft_key",
    "bearng keyway": "keyway",
    "bearng nut": "locknut",
    "bearng washer": "lock_washer",
    "bearng sleeve": "adapter_sleeve",
    "bearng collar": "shaft_collar",
    "bearng spring": "pad_spring",
    # Abbreviations and Acronyms
    "l10h": "bearing_life",
    "b10h": "bearing_life",
    "c0": "static_load_rating",
    "c1": "life_adjustment_factor",
    "a1": "life_adjustment_factor",
    "a2": "life_adjustment_factor",
    "a3": "life_adjustment_factor",
    "fa": "axial_load",
    "fr": "radial_load",
    "nlgI": "grease_lubrication",
    "pv": "pv_value",
    "wec": "white_etching_cracks",
    "wsf": "white_etching_cracks",
    "bpfo": "outer_race_defect_frequency",
    "bpfi": "inner_race_defect_frequency",
    "bsf": "ball_spin_frequency",
    "ftf": "fundamental_train_frequency",
    "cbm": "vibration_analysis",
    "edm": "electrical_erosion",
    "api": "api_610",
    "ehdl": "elastohydrodynamic_lubrication",
    "nas": "nas_1638",
    # Lowercase normalization for common terms
    "Bearing": "bearing",
    "Bearng": "bearing",
    "Bearin": "bearing",
    "Bearngs": "bearing",
    "Bearigns": "bearing",
    "Bearng Housing": "bearing_housing",
    "Bearng Fit": "bearing_fit",
    "Bearng Failure": "bearing_failure",
    "Bearng Life": "bearing_life",
    "Bearng Mounting": "bearing_mounting",
    "Bearng Dismounting": "bearing_dismounting",
    "Bearng Lubrication": "bearing_lubrication",
    "Bearng Preload": "bearing_preload",
    "Bearng Arrangement": "bearing_arrangement",
    "Bearng Seat": "bearing_seat",
    "Bearng Block": "plummer_block",
    "Bearng Unit": "bearing_unit",
    "Bearng Bracket": "bearing_housing",
    "Bearng Pedestal": "bearing_housing",
    "Bearng Base": "bearing_housing",
    "Bearng Journal": "journal_bearing",
    "Bearng Ring": "outer_ring",
    "Bearng Cage": "cage",
    "Bearng Snap Ring": "snap_ring",
    "Bearng Groove": "groove",
    "Bearng Key": "shaft_key",
    "Bearng Keyway": "keyway",
    "Bearng Nut": "locknut",
    "Bearng Washer": "lock_washer",
    "Bearng Sleeve": "adapter_sleeve",
    "Bearng Collar": "shaft_collar",
    "Bearng Spring": "pad_spring",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    m = hashlib.sha256()
    for k, v in items:
        m.update(k.encode("utf-8"))
        m.update(b"=")
        m.update(v.encode("utf-8"))
        m.update(b";")
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "expected_hash": _MAP_INTEGRITY_HASH,
    }

def _normalize_string(s):
    s = s.strip()
    s = s.lower()
    s = unicodedata.normalize("NFKC", s)
    s = s.replace("-", " ")
    s = " ".join(s.split())
    return s

def normalize_term(term):
    t = _normalize_string(term)
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try original case
    if term in SEMANTIC_MAP:
        return SEMANTIC_MAP[term]
    # Try with hyphens replaced
    t2 = term.replace("-", " ")
    if t2 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t2]
    # Try with underscores replaced
    t3 = term.replace("_", " ")
    t3 = _normalize_string(t3)
    if t3 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t3]
    return t

def get_related_terms(term):
    norm = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == norm:
            related.append(k)
    return sorted(set(related))

def get_all_mappings():
    return dict(SEMANTIC_MAP)