import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AGI07_architect"
SEMANTIC_MAP_ENGINE = "AGI07"

SEMANTIC_MAP = {
    # Twelve-Factor App Methodology
    "12factor": "twelve-factor app",
    "12-factor": "twelve-factor app",
    "twelvefactor": "twelve-factor app",
    "twelve factor": "twelve-factor app",
    "twelve-factor": "twelve-factor app",
    "twelve-factor app": "twelve-factor app",
    "12 factor app": "twelve-factor app",
    "12f": "twelve-factor app",
    "twelve factor methodology": "twelve-factor app",
    "twelve-factor methodology": "twelve-factor app",
    "12 factor methodology": "twelve-factor app",
    "12f methodology": "twelve-factor app",
    "12fa": "twelve-factor app",
    "12fa methodology": "twelve-factor app",
    "factor app": "twelve-factor app",
    "factor methodology": "twelve-factor app",
    "12fa principles": "twelve-factor app",
    "twelve-factor principles": "twelve-factor app",
    "12f principles": "twelve-factor app",
    "twelve factor principles": "twelve-factor app",
    "12factors": "twelve-factor app",
    "twelvefactors": "twelve-factor app",
    "twelve factors": "twelve-factor app",
    "twelve-factors": "twelve-factor app",
    "12 factors": "twelve-factor app",
    "12-factors": "twelve-factor app",
    # Serverless Patterns: Cloudflare Workers & AWS Lambda
    "serverless": "serverless",
    "serverless pattern": "serverless",
    "serverless patterns": "serverless",
    "cloudflare worker": "cloudflare workers",
    "cloudflare workers": "cloudflare workers",
    "cf worker": "cloudflare workers",
    "cf workers": "cloudflare workers",
    "cloudflare wrk": "cloudflare workers",
    "cloudflare wrks": "cloudflare workers",
    "aws lambda": "aws lambda",
    "lambda": "aws lambda",
    "lambda function": "aws lambda",
    "lambda functions": "aws lambda",
    "aws lambdas": "aws lambda",
    "lambda@edge": "aws lambda",
    "lambda edge": "aws lambda",
    "lambda@ edg": "aws lambda",
    "serverless lambda": "aws lambda",
    "serverless cloudflare": "cloudflare workers",
    "serverless cf": "cloudflare workers",
    "serverless function": "serverless",
    "serverless functions": "serverless",
    "faas": "serverless",
    "function as a service": "serverless",
    "functions as a service": "serverless",
    "faas pattern": "serverless",
    "faas patterns": "serverless",
    # CDN Optimization: Cache-Control & Stale-While-Revalidate
    "cdn": "cdn",
    "content delivery network": "cdn",
    "content distribution network": "cdn",
    "cdn optimization": "cdn optimization",
    "cdn optimise": "cdn optimization",
    "cdn optimize": "cdn optimization",
    "cdn tuning": "cdn optimization",
    "cdn performance": "cdn optimization",
    "cache-control": "cache-control",
    "cache control": "cache-control",
    "cachecontrol": "cache-control",
    "cache-control header": "cache-control",
    "cache-control headers": "cache-control",
    "cache header": "cache-control",
    "cache headers": "cache-control",
    "stale-while-revalidate": "stale-while-revalidate",
    "stale while revalidate": "stale-while-revalidate",
    "swr": "stale-while-revalidate",
    "stale while-revalidate": "stale-while-revalidate",
    "stalewhile revalidate": "stale-while-revalidate",
    "stalewhilerevalidate": "stale-while-revalidate",
    "stale revalidate": "stale-while-revalidate",
    "cache swr": "stale-while-revalidate",
    "cache stale-while-revalidate": "stale-while-revalidate",
    # Containerization: Docker Multi-Stage Builds & Kubernetes Pod Design
    "containerization": "containerization",
    "containerisation": "containerization",
    "container": "containerization",
    "containers": "containerization",
    "docker": "docker",
    "docker build": "docker",
    "docker builds": "docker",
    "dockerfile": "docker",
    "dockerfiles": "docker",
    "docker multi-stage": "docker multi-stage build",
    "docker multi-stage build": "docker multi-stage build",
    "docker multistage": "docker multi-stage build",
    "docker multistage build": "docker multi-stage build",
    "docker multi stage": "docker multi-stage build",
    "multi-stage build": "docker multi-stage build",
    "multistage build": "docker multi-stage build",
    "multi stage build": "docker multi-stage build",
    "multi-stage builds": "docker multi-stage build",
    "multistage builds": "docker multi-stage build",
    "multi stage builds": "docker multi-stage build",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "kube": "kubernetes",
    "k8": "kubernetes",
    "kubernetes pod": "kubernetes pod design",
    "k8s pod": "kubernetes pod design",
    "kube pod": "kubernetes pod design",
    "pod design": "kubernetes pod design",
    "kubernetes pod design": "kubernetes pod design",
    "pod": "kubernetes pod design",
    "pods": "kubernetes pod design",
    "k8s pods": "kubernetes pod design",
    "kube pods": "kubernetes pod design",
    "pod pattern": "kubernetes pod design",
    "pod patterns": "kubernetes pod design",
    # Service Mesh: Istio, Linkerd, Envoy, and mTLS
    "service mesh": "service mesh",
    "service meshes": "service mesh",
    "istio": "istio",
    "istio mesh": "istio",
    "istio service mesh": "istio",
    "linkerd": "linkerd",
    "linkerd mesh": "linkerd",
    "linkerd service mesh": "linkerd",
    "envoy": "envoy",
    "envoy proxy": "envoy",
    "envoy service mesh": "envoy",
    "envoy mesh": "envoy",
    "mtls": "mtls",
    "m tls": "mtls",
    "mutual tls": "mtls",
    "mutual-tls": "mtls",
    "mutual transport layer security": "mtls",
    "service mesh mtls": "mtls",
    "service mesh mutual tls": "mtls",
    "service mesh mutual-tls": "mtls",
    "service mesh security": "mtls",
    # Infrastructure as Code: Terraform & Pulumi State Management
    "infrastructure as code": "infrastructure as code",
    "iac": "infrastructure as code",
    "infra as code": "infrastructure as code",
    "terraform": "terraform",
    "tf": "terraform",
    "terraform state": "terraform state",
    "terraform state management": "terraform state",
    "tfstate": "terraform state",
    "tf state": "terraform state",
    "terraform statefile": "terraform state",
    "terraform state file": "terraform state",
    "pulumi": "pulumi",
    "pulumi state": "pulumi state",
    "pulumi state management": "pulumi state",
    "pulumi statefile": "pulumi state",
    "pulumi state file": "pulumi state",
    "pulumi stack": "pulumi state",
    "pulumi stacks": "pulumi state",
    "terraform stack": "terraform state",
    "terraform stacks": "terraform state",
    "state management": "state management",
    "statefile": "state management",
    "state file": "state management",
    "statefiles": "state management",
    "state files": "state management",
    # GitOps: ArgoCD, Flux, and Reconciliation Loops
    "gitops": "gitops",
    "git ops": "gitops",
    "git-ops": "gitops",
    "argo": "argocd",
    "argocd": "argocd",
    "argo cd": "argocd",
    "argo-cd": "argocd",
    "argocd app": "argocd",
    "argocd application": "argocd",
    "argocd applications": "argocd",
    "flux": "flux",
    "fluxcd": "flux",
    "flux cd": "flux",
    "flux-cd": "flux",
    "fluxcd app": "flux",
    "fluxcd application": "flux",
    "reconciliation loop": "reconciliation loop",
    "reconciliation loops": "reconciliation loop",
    "reconcile loop": "reconciliation loop",
    "reconcile": "reconciliation loop",
    "reconciling": "reconciliation loop",
    "reconciler": "reconciliation loop",
    "gitops reconciliation": "reconciliation loop",
    "gitops loop": "reconciliation loop",
    # Database Selection: SQL, NoSQL, NewSQL, and CAP Theorem
    "database selection": "database selection",
    "db selection": "database selection",
    "db choose": "database selection",
    "db choice": "database selection",
    "database choose": "database selection",
    "database choice": "database selection",
    "sql": "sql",
    "relational": "sql",
    "relational db": "sql",
    "relational database": "sql",
    "rdbms": "sql",
    "postgres": "sql",
    "postgresql": "sql",
    "mysql": "sql",
    "mssql": "sql",
    "oracle": "sql",
    "sqlite": "sql",
    "nosql": "nosql",
    "no sql": "nosql",
    "nonrelational": "nosql",
    "non-relational": "nosql",
    "non relational": "nosql",
    "document db": "nosql",
    "document database": "nosql",
    "mongodb": "nosql",
    "dynamodb": "nosql",
    "cassandra": "nosql",
    "couchdb": "nosql",
    "newsql": "newsql",
    "new sql": "newsql",
    "cloud sql": "newsql",
    "spanner": "newsql",
    "cockroachdb": "newsql",
    "yugabytedb": "newsql",
    "cap theorem": "cap theorem",
    "cap": "cap theorem",
    "captheorem": "cap theorem",
    "cap theory": "cap theorem",
    "cap tradeoff": "cap theorem",
    "cap trade-offs": "cap theorem",
    "cap tradeoffs": "cap theorem",
    "cap triangle": "cap theorem",
    "consistency availability partition": "cap theorem",
    "consistency availability partition tolerance": "cap theorem",
    # Caching Strategies: Redis, Memcached, CDN, Write-Through & Write-Behind
    "caching": "caching",
    "cache": "caching",
    "caching strategy": "caching strategy",
    "caching strategies": "caching strategy",
    "cache strategy": "caching strategy",
    "cache strategies": "caching strategy",
    "redis": "redis",
    "memcached": "memcached",
    "memcache": "memcached",
    "cdn cache": "cdn",
    "cdn caching": "cdn",
    "write-through": "write-through",
    "write through": "write-through",
    "writethrough": "write-through",
    "write behind": "write-behind",
    "write-behind": "write-behind",
    "writebehind": "write-behind",
    "cache write-through": "write-through",
    "cache write-behind": "write-behind",
    "cache write through": "write-through",
    "cache write behind": "write-behind",
    "write through cache": "write-through",
    "write behind cache": "write-behind",
    # Message Queues: Kafka, RabbitMQ, SQS, and Ordering Guarantees
    "message queue": "message queue",
    "message queues": "message queue",
    "queue": "message queue",
    "queues": "message queue",
    "mq": "message queue",
    "kafka": "kafka",
    "apache kafka": "kafka",
    "kafka queue": "kafka",
    "kafka topic": "kafka",
    "kafka topics": "kafka",
    "rabbitmq": "rabbitmq",
    "rabbit mq": "rabbitmq",
    "rabbit": "rabbitmq",
    "rabbitmq queue": "rabbitmq",
    "rabbitmq queues": "rabbitmq",
    "sqs": "sqs",
    "aws sqs": "sqs",
    "simple queue service": "sqs",
    "sqs queue": "sqs",
    "sqs queues": "sqs",
    "ordering guarantee": "ordering guarantee",
    "ordering guarantees": "ordering guarantee",
    "queue ordering": "ordering guarantee",
    "ordered queue": "ordering guarantee",
    "ordered queues": "ordering guarantee",
    "ordered delivery": "ordering guarantee",
    "message ordering": "ordering guarantee",
    "message order": "ordering guarantee",
    "guaranteed ordering": "ordering guarantee",
    # Monitoring: Prometheus, Grafana, Datadog, RED & USE Methods, SLO, SLI, SLA, and Error Budget Burn Rate
    "monitoring": "monitoring",
    "monitor": "monitoring",
    "observability": "monitoring",
    "metrics": "monitoring",
    "prometheus": "prometheus",
    "prom": "prometheus",
    "prometheus monitoring": "prometheus",
    "grafana": "grafana",
    "grafana dashboard": "grafana",
    "grafana dashboards": "grafana",
    "datadog": "datadog",
    "data dog": "datadog",
    "datadog monitoring": "datadog",
    "red method": "red method",
    "red": "red method",
    "request error duration": "red method",
    "request error rate": "red method",
    "use method": "use method",
    "use": "use method",
    "utilization saturation errors": "use method",
    "utilization saturation error": "use method",
    "slo": "slo",
    "slos": "slo",
    "service level objective": "slo",
    "service level objectives": "slo",
    "sli": "sli",
    "slis": "sli",
    "service level indicator": "sli",
    "service level indicators": "sli",
    "sla": "sla",
    "slas": "sla",
    "service level agreement": "sla",
    "service level agreements": "sla",
    "error budget": "error budget",
    "error budgets": "error budget",
    "error budget burn rate": "error budget burn rate",
    "error burn rate": "error budget burn rate",
    "burn rate": "error budget burn rate",
    "burnrate": "error budget burn rate",
    "error rate": "error budget burn rate",
    "error rates": "error budget burn rate",
    # Additional synonyms, abbreviations, misspellings, and related terms
    "cloudflare": "cloudflare workers",
    "cf": "cloudflare workers",
    "aws": "aws lambda",
    "amazon lambda": "aws lambda",
    "amazon web services lambda": "aws lambda",
    "docker container": "docker",
    "docker containers": "docker",
    "kubernetes container": "kubernetes",
    "k8s container": "kubernetes",
    "kube container": "kubernetes",
    "kubernetes deployment": "kubernetes",
    "k8s deployment": "kubernetes",
    "kube deployment": "kubernetes",
    "kubernetes service": "kubernetes",
    "k8s service": "kubernetes",
    "kube service": "kubernetes",
    "kubernetes cluster": "kubernetes",
    "k8s cluster": "kubernetes",
    "kube cluster": "kubernetes",
    "kubernetes node": "kubernetes",
    "k8s node": "kubernetes",
    "kube node": "kubernetes",
    "kubernetes namespace": "kubernetes",
    "k8s namespace": "kubernetes",
    "kube namespace": "kubernetes",
    "kubernetes yaml": "kubernetes",
    "k8s yaml": "kubernetes",
    "kube yaml": "kubernetes",
    "kubernetes manifest": "kubernetes",
    "k8s manifest": "kubernetes",
    "kube manifest": "kubernetes",
    "kubernetes config": "kubernetes",
    "k8s config": "kubernetes",
    "kube config": "kubernetes",
    "kubernetes configuration": "kubernetes",
    "k8s configuration": "kubernetes",
    "kube configuration": "kubernetes",
    "istio gateway": "istio",
    "istio ingress": "istio",
    "istio egress": "istio",
    "istio pilot": "istio",
    "istio mixer": "istio",
    "istio citadel": "istio",
    "istio envoy": "istio",
    "linkerd2": "linkerd",
    "linkerd 2": "linkerd",
    "linkerd2 mesh": "linkerd",
    "linkerd2 service mesh": "linkerd",
    "envoy sidecar": "envoy",
    "envoy filter": "envoy",
    "envoy listener": "envoy",
    "envoy cluster": "envoy",
    "envoy route": "envoy",
    "envoy config": "envoy",
    "envoy configuration": "envoy",
    "envoyproxy": "envoy",
    "envoy proxy": "envoy",
    "terraform module": "terraform",
    "terraform modules": "terraform",
    "terraform provider": "terraform",
    "terraform providers": "terraform",
    "terraform resource": "terraform",
    "terraform resources": "terraform",
    "terraform output": "terraform",
    "terraform outputs": "terraform",
    "terraform variable": "terraform",
    "terraform variables": "terraform",
    "pulumi project": "pulumi",
    "pulumi projects": "pulumi",
    "pulumi resource": "pulumi",
    "pulumi resources": "pulumi",
    "pulumi output": "pulumi",
    "pulumi outputs": "pulumi",
    "pulumi variable": "pulumi",
    "pulumi variables": "pulumi",
    "argocd repo": "argocd",
    "argocd repos": "argocd",
    "argocd repository": "argocd",
    "argocd repositories": "argocd",
    "argocd sync": "argocd",
    "argocd project": "argocd",
    "argocd projects": "argocd",
    "flux repo": "flux",
    "flux repos": "flux",
    "flux repository": "flux",
    "flux repositories": "flux",
    "flux sync": "flux",
    "flux project": "flux",
    "flux projects": "flux",
    "database": "database selection",
    "databases": "database selection",
    "db": "database selection",
    "dbs": "database selection",
    "sql db": "sql",
    "sql database": "sql",
    "nosql db": "nosql",
    "nosql database": "nosql",
    "newsql db": "newsql",
    "newsql database": "newsql",
    "cache db": "caching",
    "cache database": "caching",
    "redis cache": "redis",
    "memcached cache": "memcached",
    "message broker": "message queue",
    "message brokers": "message queue",
    "event queue": "message queue",
    "event queues": "message queue",
    "event bus": "message queue",
    "event buses": "message queue",
    "pubsub": "message queue",
    "pub sub": "message queue",
    "publish subscribe": "message queue",
    "publish-subscribe": "message queue",
    "pub/sub": "message queue",
    "prometheus alert": "prometheus",
    "prometheus alerts": "prometheus",
    "prometheus rule": "prometheus",
    "prometheus rules": "prometheus",
    "grafana alert": "grafana",
    "grafana alerts": "grafana",
    "grafana panel": "grafana",
    "grafana panels": "grafana",
    "datadog alert": "datadog",
    "datadog alerts": "datadog",
    "datadog dashboard": "datadog",
    "datadog dashboards": "datadog",
    "red metrics": "red method",
    "use metrics": "use method",
    "slo metric": "slo",
    "slo metrics": "slo",
    "sli metric": "sli",
    "sli metrics": "sli",
    "sla metric": "sla",
    "sla metrics": "sla",
    "error budget metric": "error budget",
    "error budget metrics": "error budget",
    "burn rate metric": "error budget burn rate",
    "burn rate metrics": "error budget burn rate",
    # Misspellings and common typos
    "kubernets": "kubernetes",
    "kubernete": "kubernetes",
    "kubernetis": "kubernetes",
    "kubernets pod": "kubernetes pod design",
    "kubernete pod": "kubernetes pod design",
    "kubernetis pod": "kubernetes pod design",
    "kubernets cluster": "kubernetes",
    "kubernete cluster": "kubernetes",
    "kubernetis cluster": "kubernetes",
    "kubernets service": "kubernetes",
    "kubernete service": "kubernetes",
    "kubernetis service": "kubernetes",
    "kubernets deployment": "kubernetes",
    "kubernete deployment": "kubernetes",
    "kubernetis deployment": "kubernetes",
    "kubernets yaml": "kubernetes",
    "kubernete yaml": "kubernetes",
    "kubernetis yaml": "kubernetes",
    "kubernets manifest": "kubernetes",
    "kubernete manifest": "kubernetes",
    "kubernetis manifest": "kubernetes",
    "kubernets config": "kubernetes",
    "kubernete config": "kubernetes",
    "kubernetis config": "kubernetes",
    "kubernets configuration": "kubernetes",
    "kubernete configuration": "kubernetes",
    "kubernetis configuration": "kubernetes",
    "kubernets namespace": "kubernetes",
    "kubernete namespace": "kubernetes",
    "kubernetis namespace": "kubernetes",
    "kubernets node": "kubernetes",
    "kubernete node": "kubernetes",
    "kubernetis node": "kubernetes",
    "kubernets pod design": "kubernetes pod design",
    "kubernete pod design": "kubernetes pod design",
    "kubernetis pod design": "kubernetes pod design",
    "kubernets pods": "kubernetes pod design",
    "kubernete pods": "kubernetes pod design",
    "kubernetis pods": "kubernetes pod design",
    "kubernets deployment": "kubernetes",
    "kubernete deployment": "kubernetes",
    "kubernetis deployment": "kubernetes",
    "kubernets deployments": "kubernetes",
    "kubernete deployments": "kubernetes",
    "kubernetis deployments": "kubernetes",
    "kubernets service": "kubernetes",
    "kubernete service": "kubernetes",
    "kubernetis service": "kubernetes",
    "kubernets services": "kubernetes",
    "kubernete services": "kubernetes",
    "kubernetis services": "kubernetes",
    "kubernets cluster": "kubernetes",
    "kubernete cluster": "kubernetes",
    "kubernetis cluster": "kubernetes",
    "kubernets clusters": "kubernetes",
    "kubernete clusters": "kubernetes",
    "kubernetis clusters": "kubernetes",
    "kubernets config": "kubernetes",
    "kubernete config": "kubernetes",
    "kubernetis config": "kubernetes",
    "kubernets configuration": "kubernetes",
    "kubernete configuration": "kubernetes",
    "kubernetis configuration": "kubernetes",
    "kubernets yaml": "kubernetes",
    "kubernete yaml": "kubernetes",
    "kubernetis yaml": "kubernetes",
    "kubernets manifest": "kubernetes",
    "kubernete manifest": "kubernetes",
    "kubernetis manifest": "kubernetes",
    "kubernets namespace": "kubernetes",
    "kubernete namespace": "kubernetes",
    "kubernetis namespace": "kubernetes",
    "kubernets node": "kubernetes",
    "kubernete node": "kubernetes",
    "kubernetis node": "kubernetes",
    # Lowercase normalization for all canonical terms
    "docker multi-stage build": "docker multi-stage build",
    "kubernetes pod design": "kubernetes pod design",
    "state management": "state management",
    "argocd": "argocd",
    "flux": "flux",
    "database selection": "database selection",
    "caching strategy": "caching strategy",
    "write-through": "write-through",
    "write-behind": "write-behind",
    "ordering guarantee": "ordering guarantee",
    "red method": "red method",
    "use method": "use method",
    "error budget burn rate": "error budget burn rate",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items).encode("utf-8")
    return hashlib.sha256(hash_input).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)