import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "I03_deal_flow_analyzer"
SEMANTIC_MAP_ENGINE = "I03"

SEMANTIC_MAP = {
    # Unleased Mineral Identification
    "unleased mineral": "unleased_mineral",
    "unleased minerals": "unleased_mineral",
    "unleased acreage": "unleased_mineral",
    "open mineral": "unleased_mineral",
    "open minerals": "unleased_mineral",
    "unleased tract": "unleased_mineral",
    "unleased tracts": "unleased_mineral",
    "unleased interest": "unleased_mineral",
    "unleased interests": "unleased_mineral",
    "unleased MI": "unleased_mineral",
    "unleased mineral interest": "unleased_mineral",
    "unleased mineral interests": "unleased_mineral",
    "unleased": "unleased_mineral",
    "open": "unleased_mineral",
    "open MI": "unleased_mineral",
    "open mineral interest": "unleased_mineral",
    "open mineral interests": "unleased_mineral",
    "mineral open": "unleased_mineral",
    "mineral unleased": "unleased_mineral",
    "mineral not leased": "unleased_mineral",
    "mineral not under lease": "unleased_mineral",
    "mineral not assigned": "unleased_mineral",
    "unassigned mineral": "unleased_mineral",
    "unassigned minerals": "unleased_mineral",
    "unassigned MI": "unleased_mineral",
    "unassigned mineral interest": "unleased_mineral",
    "unassigned mineral interests": "unleased_mineral",
    "unleased mineral parcel": "unleased_mineral",
    "unleased mineral parcels": "unleased_mineral",
    "unleased mineral lot": "unleased_mineral",
    "unleased mineral lots": "unleased_mineral",
    "unleased mineral property": "unleased_mineral",
    "unleased mineral properties": "unleased_mineral",
    "unleased mineral asset": "unleased_mineral",
    "unleased mineral assets": "unleased_mineral",
    "unleased mineral right": "unleased_mineral",
    "unleased mineral rights": "unleased_mineral",
    "open mineral right": "unleased_mineral",
    "open mineral rights": "unleased_mineral",
    "mineral open right": "unleased_mineral",
    "mineral open rights": "unleased_mineral",
    "mineral not leased right": "unleased_mineral",
    "mineral not leased rights": "unleased_mineral",
    "unleased mineral share": "unleased_mineral",
    "unleased mineral shares": "unleased_mineral",
    "unleased mineral fraction": "unleased_mineral",
    "unleased mineral fractions": "unleased_mineral",
    "unleased mineral division": "unleased_mineral",
    "unleased mineral divisions": "unleased_mineral",
    "unleased mineral segment": "unleased_mineral",
    "unleased mineral segments": "unleased_mineral",
    "unleased mineral split": "unleased_mineral",
    "unleased mineral splits": "unleased_mineral",
    "unleased mineral split interest": "unleased_mineral",
    "unleased mineral split interests": "unleased_mineral",
    "unleased mineral split right": "unleased_mineral",
    "unleased mineral split rights": "unleased_mineral",
    "unleased mineral split share": "unleased_mineral",
    "unleased mineral split shares": "unleased_mineral",
    "unleased mineral split fraction": "unleased_mineral",
    "unleased mineral split fractions": "unleased_mineral",
    "unleased mineral split division": "unleased_mineral",
    "unleased mineral split divisions": "unleased_mineral",
    "unleased mineral split segment": "unleased_mineral",
    "unleased mineral split segments": "unleased_mineral",
    "unleased mineral split asset": "unleased_mineral",
    "unleased mineral split assets": "unleased_mineral",
    "unleased mineral split property": "unleased_mineral",
    "unleased mineral split properties": "unleased_mineral",
    "unleased mineral split lot": "unleased_mineral",
    "unleased mineral split lots": "unleased_mineral",
    "unleased mineral split parcel": "unleased_mineral",
    "unleased mineral split parcels": "unleased_mineral",
    "unleased mineral split tract": "unleased_mineral",
    "unleased mineral split tracts": "unleased_mineral",
    "unleased mineral split acreage": "unleased_mineral",
    "unleased mineral split acreages": "unleased_mineral",
    "unleased mineral split": "unleased_mineral",
    "unleased mineral splits": "unleased_mineral",
    "unleased mineral split MI": "unleased_mineral",
    "unleased mineral split interests": "unleased_mineral",
    "unleased mineral split rights": "unleased_mineral",
    "unleased mineral split shares": "unleased_mineral",
    "unleased mineral split fractions": "unleased_mineral",
    "unleased mineral split divisions": "unleased_mineral",
    "unleased mineral split segments": "unleased_mineral",
    "unleased mineral split assets": "unleased_mineral",
    "unleased mineral split properties": "unleased_mineral",
    "unleased mineral split lots": "unleased_mineral",
    "unleased mineral split parcels": "unleased_mineral",
    "unleased mineral split tracts": "unleased_mineral",
    "unleased mineral split acreages": "unleased_mineral",

    # Dormant Mineral Act (Texas NRC Ch. 75) Application
    "dormant mineral": "dormant_mineral",
    "dormant minerals": "dormant_mineral",
    "dormant mineral act": "dormant_mineral_act",
    "dormant mineral acts": "dormant_mineral_act",
    "dormant mineral statute": "dormant_mineral_act",
    "dormant mineral statutes": "dormant_mineral_act",
    "dormant mineral law": "dormant_mineral_act",
    "dormant mineral laws": "dormant_mineral_act",
    "texas dormant mineral act": "dormant_mineral_act",
    "texas dormant mineral acts": "dormant_mineral_act",
    "texas dormant mineral statute": "dormant_mineral_act",
    "texas dormant mineral statutes": "dormant_mineral_act",
    "texas dormant mineral law": "dormant_mineral_act",
    "texas dormant mineral laws": "dormant_mineral_act",
    "nrc ch. 75": "dormant_mineral_act",
    "nrc chapter 75": "dormant_mineral_act",
    "texas nrc ch. 75": "dormant_mineral_act",
    "texas nrc chapter 75": "dormant_mineral_act",
    "texas natural resources code chapter 75": "dormant_mineral_act",
    "texas nrc 75": "dormant_mineral_act",
    "texas nrc": "dormant_mineral_act",
    "dormant MI": "dormant_mineral",
    "dormant mineral interest": "dormant_mineral",
    "dormant mineral interests": "dormant_mineral",
    "dormant mineral right": "dormant_mineral",
    "dormant mineral rights": "dormant_mineral",
    "dormant mineral property": "dormant_mineral",
    "dormant mineral properties": "dormant_mineral",
    "dormant mineral asset": "dormant_mineral",
    "dormant mineral assets": "dormant_mineral",
    "dormant mineral parcel": "dormant_mineral",
    "dormant mineral parcels": "dormant_mineral",
    "dormant mineral tract": "dormant_mineral",
    "dormant mineral tracts": "dormant_mineral",
    "dormant mineral lot": "dormant_mineral",
    "dormant mineral lots": "dormant_mineral",
    "dormant mineral share": "dormant_mineral",
    "dormant mineral shares": "dormant_mineral",
    "dormant mineral fraction": "dormant_mineral",
    "dormant mineral fractions": "dormant_mineral",
    "dormant mineral division": "dormant_mineral",
    "dormant mineral divisions": "dormant_mineral",
    "dormant mineral segment": "dormant_mineral",
    "dormant mineral segments": "dormant_mineral",

    # Heirship Opportunity Scoring
    "heirship": "heirship",
    "heirship opportunity": "heirship_opportunity",
    "heirship opportunities": "heirship_opportunity",
    "heirship scoring": "heirship_opportunity_scoring",
    "heirship score": "heirship_opportunity_scoring",
    "heirship scores": "heirship_opportunity_scoring",
    "heirship analysis": "heirship_opportunity_scoring",
    "heirship analytics": "heirship_opportunity_scoring",
    "heirship evaluation": "heirship_opportunity_scoring",
    "heirship evaluations": "heirship_opportunity_scoring",
    "heirship assessment": "heirship_opportunity_scoring",
    "heirship assessments": "heirship_opportunity_scoring",
    "heirship review": "heirship_opportunity_scoring",
    "heirship reviews": "heirship_opportunity_scoring",
    "heirship audit": "heirship_opportunity_scoring",
    "heirship audits": "heirship_opportunity_scoring",
    "heirship opportunity score": "heirship_opportunity_scoring",
    "heirship opportunity scores": "heirship_opportunity_scoring",
    "heirship opportunity evaluation": "heirship_opportunity_scoring",
    "heirship opportunity evaluations": "heirship_opportunity_scoring",
    "heirship opportunity assessment": "heirship_opportunity_scoring",
    "heirship opportunity assessments": "heirship_opportunity_scoring",
    "heirship opportunity review": "heirship_opportunity_scoring",
    "heirship opportunity reviews": "heirship_opportunity_scoring",
    "heirship opportunity audit": "heirship_opportunity_scoring",
    "heirship opportunity audits": "heirship_opportunity_scoring",
    "heirship opportunity analytics": "heirship_opportunity_scoring",
    "heirship opportunity analysis": "heirship_opportunity_scoring",

    # Title Defect Acquisition Strategy
    "title defect": "title_defect",
    "title defects": "title_defect",
    "title defect acquisition": "title_defect_acquisition",
    "title defect acquisition strategy": "title_defect_acquisition_strategy",
    "title defect acquisition strategies": "title_defect_acquisition_strategy",
    "title defect strategy": "title_defect_acquisition_strategy",
    "title defect strategies": "title_defect_acquisition_strategy",
    "defective title": "title_defect",
    "defective titles": "title_defect",
    "defective title acquisition": "title_defect_acquisition",
    "defective title acquisition strategy": "title_defect_acquisition_strategy",
    "defective title acquisition strategies": "title_defect_acquisition_strategy",
    "defective title strategy": "title_defect_acquisition_strategy",
    "defective title strategies": "title_defect_acquisition_strategy",
    "defect title": "title_defect",
    "defect titles": "title_defect",
    "defect title acquisition": "title_defect_acquisition",
    "defect title acquisition strategy": "title_defect_acquisition_strategy",
    "defect title acquisition strategies": "title_defect_acquisition_strategy",
    "defect title strategy": "title_defect_acquisition_strategy",
    "defect title strategies": "title_defect_acquisition_strategy",
    "title defect asset": "title_defect",
    "title defect assets": "title_defect",
    "title defect property": "title_defect",
    "title defect properties": "title_defect",
    "title defect parcel": "title_defect",
    "title defect parcels": "title_defect",
    "title defect tract": "title_defect",
    "title defect tracts": "title_defect",
    "title defect lot": "title_defect",
    "title defect lots": "title_defect",
    "title defect share": "title_defect",
    "title defect shares": "title_defect",
    "title defect fraction": "title_defect",
    "title defect fractions": "title_defect",
    "title defect division": "title_defect",
    "title defect divisions": "title_defect",
    "title defect segment": "title_defect",
    "title defect segments": "title_defect",

    # Mineral Interest Fragmentation Analysis
    "fragmented mineral": "mineral_interest_fragmentation",
    "fragmented minerals": "mineral_interest_fragmentation",
    "fragmented mineral interest": "mineral_interest_fragmentation",
    "fragmented mineral interests": "mineral_interest_fragmentation",
    "mineral fragmentation": "mineral_interest_fragmentation",
    "mineral fragment": "mineral_interest_fragmentation",
    "mineral fragments": "mineral_interest_fragmentation",
    "mineral interest fragmentation": "mineral_interest_fragmentation",
    "mineral interest fragment": "mineral_interest_fragmentation",
    "mineral interest fragments": "mineral_interest_fragmentation",
    "fragmented MI": "mineral_interest_fragmentation",
    "fragmented mineral right": "mineral_interest_fragmentation",
    "fragmented mineral rights": "mineral_interest_fragmentation",
    "fragmented mineral property": "mineral_interest_fragmentation",
    "fragmented mineral properties": "mineral_interest_fragmentation",
    "fragmented mineral asset": "mineral_interest_fragmentation",
    "fragmented mineral assets": "mineral_interest_fragmentation",
    "fragmented mineral parcel": "mineral_interest_fragmentation",
    "fragmented mineral parcels": "mineral_interest_fragmentation",
    "fragmented mineral tract": "mineral_interest_fragmentation",
    "fragmented mineral tracts": "mineral_interest_fragmentation",
    "fragmented mineral lot": "mineral_interest_fragmentation",
    "fragmented mineral lots": "mineral_interest_fragmentation",
    "fragmented mineral share": "mineral_interest_fragmentation",
    "fragmented mineral shares": "mineral_interest_fragmentation",
    "fragmented mineral fraction": "mineral_interest_fragmentation",
    "fragmented mineral fractions": "mineral_interest_fragmentation",
    "fragmented mineral division": "mineral_interest_fragmentation",
    "fragmented mineral divisions": "mineral_interest_fragmentation",
    "fragmented mineral segment": "mineral_interest_fragmentation",
    "fragmented mineral segments": "mineral_interest_fragmentation",

    # Estate Planning Gaps and Mineral Acquisition
    "estate planning gap": "estate_planning_gap",
    "estate planning gaps": "estate_planning_gap",
    "estate gap": "estate_planning_gap",
    "estate gaps": "estate_planning_gap",
    "estate planning deficiency": "estate_planning_gap",
    "estate planning deficiencies": "estate_planning_gap",
    "estate deficiency": "estate_planning_gap",
    "estate deficiencies": "estate_planning_gap",
    "estate planning shortfall": "estate_planning_gap",
    "estate planning shortfalls": "estate_planning_gap",
    "estate shortfall": "estate_planning_gap",
    "estate shortfalls": "estate_planning_gap",
    "estate planning lapse": "estate_planning_gap",
    "estate planning lapses": "estate_planning_gap",
    "estate lapse": "estate_planning_gap",
    "estate lapses": "estate_planning_gap",
    "estate planning gap acquisition": "estate_planning_gap_acquisition",
    "estate planning gap acquisitions": "estate_planning_gap_acquisition",
    "estate gap acquisition": "estate_planning_gap_acquisition",
    "estate gap acquisitions": "estate_planning_gap_acquisition",
    "estate planning deficiency acquisition": "estate_planning_gap_acquisition",
    "estate planning deficiency acquisitions": "estate_planning_gap_acquisition",
    "estate deficiency acquisition": "estate_planning_gap_acquisition",
    "estate deficiency acquisitions": "estate_planning_gap_acquisition",
    "estate planning shortfall acquisition": "estate_planning_gap_acquisition",
    "estate planning shortfall acquisitions": "estate_planning_gap_acquisition",
    "estate shortfall acquisition": "estate_planning_gap_acquisition",
    "estate shortfall acquisitions": "estate_planning_gap_acquisition",
    "estate planning lapse acquisition": "estate_planning_gap_acquisition",
    "estate planning lapse acquisitions": "estate_planning_gap_acquisition",
    "estate lapse acquisition": "estate_planning_gap_acquisition",
    "estate lapse acquisitions": "estate_planning_gap_acquisition",

    # Tax Delinquent Mineral Interest Acquisition
    "tax delinquent mineral": "tax_delinquent_mineral",
    "tax delinquent minerals": "tax_delinquent_mineral",
    "tax delinquent mineral interest": "tax_delinquent_mineral",
    "tax delinquent mineral interests": "tax_delinquent_mineral",
    "tax delinquent MI": "tax_delinquent_mineral",
    "tax delinquent mineral right": "tax_delinquent_mineral",
    "tax delinquent mineral rights": "tax_delinquent_mineral",
    "tax delinquent mineral property": "tax_delinquent_mineral",
    "tax delinquent mineral properties": "tax_delinquent_mineral",
    "tax delinquent mineral asset": "tax_delinquent_mineral",
    "tax delinquent mineral assets": "tax_delinquent_mineral",
    "tax delinquent mineral parcel": "tax_delinquent_mineral",
    "tax delinquent mineral parcels": "tax_delinquent_mineral",
    "tax delinquent mineral tract": "tax_delinquent_mineral",
    "tax delinquent mineral tracts": "tax_delinquent_mineral",
    "tax delinquent mineral lot": "tax_delinquent_mineral",
    "tax delinquent mineral lots": "tax_delinquent_mineral",
    "tax delinquent mineral share": "tax_delinquent_mineral",
    "tax delinquent mineral shares": "tax_delinquent_mineral",
    "tax delinquent mineral fraction": "tax_delinquent_mineral",
    "tax delinquent mineral fractions": "tax_delinquent_mineral",
    "tax delinquent mineral division": "tax_delinquent_mineral",
    "tax delinquent mineral divisions": "tax_delinquent_mineral",
    "tax delinquent mineral segment": "tax_delinquent_mineral",
    "tax delinquent mineral segments": "tax_delinquent_mineral",
    "delinquent mineral": "tax_delinquent_mineral",
    "delinquent minerals": "tax_delinquent_mineral",
    "delinquent mineral interest": "tax_delinquent_mineral",
    "delinquent mineral interests": "tax_delinquent_mineral",
    "delinquent MI": "tax_delinquent_mineral",
    "delinquent mineral right": "tax_delinquent_mineral",
    "delinquent mineral rights": "tax_delinquent_mineral",
    "delinquent mineral property": "tax_delinquent_mineral",
    "delinquent mineral properties": "tax_delinquent_mineral",
    "delinquent mineral asset": "tax_delinquent_mineral",
    "delinquent mineral assets": "tax_delinquent_mineral",
    "delinquent mineral parcel": "tax_delinquent_mineral",
    "delinquent mineral parcels": "tax_delinquent_mineral",
    "delinquent mineral tract": "tax_delinquent_mineral",
    "delinquent mineral tracts": "tax_delinquent_mineral",
    "delinquent mineral lot": "tax_delinquent_mineral",
    "delinquent mineral lots": "tax_delinquent_mineral",
    "delinquent mineral share": "tax_delinquent_mineral",
    "delinquent mineral shares": "tax_delinquent_mineral",
    "delinquent mineral fraction": "tax_delinquent_mineral",
    "delinquent mineral fractions": "tax_delinquent_mineral",
    "delinquent mineral division": "tax_delinquent_mineral",
    "delinquent mineral divisions": "tax_delinquent_mineral",
    "delinquent mineral segment": "tax_delinquent_mineral",
    "delinquent mineral segments": "tax_delinquent_mineral",
    "tax delinquent mineral acquisition": "tax_delinquent_mineral_acquisition",
    "tax delinquent mineral acquisitions": "tax_delinquent_mineral_acquisition",
    "delinquent mineral acquisition": "tax_delinquent_mineral_acquisition",
    "delinquent mineral acquisitions": "tax_delinquent_mineral_acquisition",

    # Forced Pooling Opportunities
    "forced pooling": "forced_pooling",
    "forced pooling opportunity": "forced_pooling_opportunity",
    "forced pooling opportunities": "forced_pooling_opportunity",
    "forced pooling analysis": "forced_pooling_opportunity",
    "forced pooling analytics": "forced_pooling_opportunity",
    "forced pooling evaluation": "forced_pooling_opportunity",
    "forced pooling evaluations": "forced_pooling_opportunity",
    "forced pooling assessment": "forced_pooling_opportunity",
    "forced pooling assessments": "forced_pooling_opportunity",
    "forced pooling review": "forced_pooling_opportunity",
    "forced pooling reviews": "forced_pooling_opportunity",
    "forced pooling audit": "forced_pooling_opportunity",
    "forced pooling audits": "forced_pooling_opportunity",
    "forced pooling score": "forced_pooling_opportunity",
    "forced pooling scores": "forced_pooling_opportunity",
    "forced pooling scoring": "forced_pooling_opportunity",
    "forced pooling asset": "forced_pooling",
    "forced pooling assets": "forced_pooling",
    "forced pooling property": "forced_pooling",
    "forced pooling properties": "forced_pooling",
    "forced pooling parcel": "forced_pooling",
    "forced pooling parcels": "forced_pooling",
    "forced pooling tract": "forced_pooling",
    "forced pooling tracts": "forced_pooling",
    "forced pooling lot": "forced_pooling",
    "forced pooling lots": "forced_pooling",
    "forced pooling share": "forced_pooling",
    "forced pooling shares": "forced_pooling",
    "forced pooling fraction": "forced_pooling",
    "forced pooling fractions": "forced_pooling",
    "forced pooling division": "forced_pooling",
    "forced pooling divisions": "forced_pooling",
    "forced pooling segment": "forced_pooling",
    "forced pooling segments": "forced_pooling",

    # Farmout Opportunity Identification
    "farmout": "farmout",
    "farmout opportunity": "farmout_opportunity",
    "farmout opportunities": "farmout_opportunity",
    "farmout analysis": "farmout_opportunity",
    "farmout analytics": "farmout_opportunity",
    "farmout evaluation": "farmout_opportunity",
    "farmout evaluations": "farmout_opportunity",
    "farmout assessment": "farmout_opportunity",
    "farmout assessments": "farmout_opportunity",
    "farmout review": "farmout_opportunity",
    "farmout reviews": "farmout_opportunity",
    "farmout audit": "farmout_opportunity",
    "farmout audits": "farmout_opportunity",
    "farmout score": "farmout_opportunity",
    "farmout scores": "farmout_opportunity",
    "farmout scoring": "farmout_opportunity",
    "farmout asset": "farmout",
    "farmout assets": "farmout",
    "farmout property": "farmout",
    "farmout properties": "farmout",
    "farmout parcel": "farmout",
    "farmout parcels": "farmout",
    "farmout tract": "farmout",
    "farmout tracts": "farmout",
    "farmout lot": "farmout",
    "farmout lots": "farmout",
    "farmout share": "farmout",
    "farmout shares": "farmout",
    "farmout fraction": "farmout",
    "farmout fractions": "farmout",
    "farmout division": "farmout",
    "farmout divisions": "farmout",
    "farmout segment": "farmout",
    "farmout segments": "farmout",

    # JV Partner Matching for Acquisition
    "joint venture": "joint_venture",
    "joint ventures": "joint_venture",
    "JV": "joint_venture",
    "JV partner": "joint_venture_partner",
    "JV partners": "joint_venture_partner",
    "joint venture partner": "joint_venture_partner",
    "joint venture partners": "joint_venture_partner",
    "JV matching": "joint_venture_partner_matching",
    "JV match": "joint_venture_partner_matching",
    "joint venture matching": "joint_venture_partner_matching",
    "joint venture match": "joint_venture_partner_matching",
    "JV acquisition": "joint_venture_acquisition",
    "joint venture acquisition": "joint_venture_acquisition",
    "JV acquisition partner": "joint_venture_partner_acquisition",
    "joint venture acquisition partner": "joint_venture_partner_acquisition",
    "JV acquisition partners": "joint_venture_partner_acquisition",
    "joint venture acquisition partners": "joint_venture_partner_acquisition",
    "JV partner acquisition": "joint_venture_partner_acquisition",
    "joint venture partner acquisition": "joint_venture_partner_acquisition",
    "JV partner acquisitions": "joint_venture_partner_acquisition",
    "joint venture partner acquisitions": "joint_venture_partner_acquisition",
    "JV partner match": "joint_venture_partner_matching",
    "joint venture partner match": "joint_venture_partner_matching",
    "JV partner matches": "joint_venture_partner_matching",
    "joint venture partner matches": "joint_venture_partner_matching",
    "JV matching acquisition": "joint_venture_partner_matching_acquisition",
    "joint venture matching acquisition": "joint_venture_partner_matching_acquisition",
    "JV matching acquisitions": "joint_venture_partner_matching_acquisition",
    "joint venture matching acquisitions": "joint_venture_partner_matching_acquisition",

    # Misspellings, abbreviations, and related terms
    "unleasd mineral": "unleased_mineral",
    "unleasd minerals": "unleased_mineral",
    "unleasd MI": "unleased_mineral",
    "unleasd mineral interest": "unleased_mineral",
    "unleasd mineral interests": "unleased_mineral",
    "dormant minral": "dormant_mineral",
    "dormant minrals": "dormant_mineral",
    "dormant minral interest": "dormant_mineral",
    "dormant minral interests": "dormant_mineral",
    "heir ship": "heirship",
    "heir ship opportunity": "heirship_opportunity",
    "heir ship opportunities": "heirship_opportunity",
    "heir ship scoring": "heirship_opportunity_scoring",
    "heir ship score": "heirship_opportunity_scoring",
    "heir ship scores": "heirship_opportunity_scoring",
    "title defct": "title_defect",
    "title defcts": "title_defect",
    "title defct acquisition": "title_defect_acquisition",
    "title defct acquisition strategy": "title_defect_acquisition_strategy",
    "title defct acquisition strategies": "title_defect_acquisition_strategy",
    "fragmented minral": "mineral_interest_fragmentation",
    "fragmented minrals": "mineral_interest_fragmentation",
    "fragmented minral interest": "mineral_interest_fragmentation",
    "fragmented minral interests": "mineral_interest_fragmentation",
    "estate planing gap": "estate_planning_gap",
    "estate planing gaps": "estate_planning_gap",
    "estate planing deficiency": "estate_planning_gap",
    "estate planing deficiencies": "estate_planning_gap",
    "estate planing shortfall": "estate_planning_gap",
    "estate planing shortfalls": "estate_planning_gap",
    "estate planing lapse": "estate_planning_gap",
    "estate planing lapses": "estate_planning_gap",
    "tax delinquent minral": "tax_delinquent_mineral",
    "tax delinquent minrals": "tax_delinquent_mineral",
    "tax delinquent minral interest": "tax_delinquent_mineral",
    "tax delinquent minral interests": "tax_delinquent_mineral",
    "delinquent minral": "tax_delinquent_mineral",
    "delinquent minrals": "tax_delinquent_mineral",
    "delinquent minral interest": "tax_delinquent_mineral",
    "delinquent minral interests": "tax_delinquent_mineral",
    "forced poling": "forced_pooling",
    "forced poling opportunity": "forced_pooling_opportunity",
    "forced poling opportunities": "forced_pooling_opportunity",
    "farm out": "farmout",
    "farm out opportunity": "farmout_opportunity",
    "farm out opportunities": "farmout_opportunity",
    "farm out analysis": "farmout_opportunity",
    "farm out analytics": "farmout_opportunity",
    "farm out evaluation": "farmout_opportunity",
    "farm out evaluations": "farmout_opportunity",
    "farm out assessment": "farmout_opportunity",
    "farm out assessments": "farmout_opportunity",
    "farm out review": "farmout_opportunity",
    "farm out reviews": "farmout_opportunity",
    "farm out audit": "farmout_opportunity",
    "farm out audits": "farmout_opportunity",
    "farm out score": "farmout_opportunity",
    "farm out scores": "farmout_opportunity",
    "farm out scoring": "farmout_opportunity",
    "joint ventur": "joint_venture",
    "joint venturs": "joint_venture",
    "joint ventur partner": "joint_venture_partner",
    "joint ventur partners": "joint_venture_partner",
    "joint ventur matching": "joint_venture_partner_matching",
    "joint ventur match": "joint_venture_partner_matching",
    "joint ventur acquisition": "joint_venture_acquisition",
    "joint ventur acquisition partner": "joint_venture_partner_acquisition",
    "joint ventur acquisition partners": "joint_venture_partner_acquisition",
    "joint ventur partner acquisition": "joint_venture_partner_acquisition",
    "joint ventur partner acquisitions": "joint_venture_partner_acquisition",
    "joint ventur partner match": "joint_venture_partner_matching",
    "joint ventur partner matches": "joint_venture_partner_matching",
    "joint ventur matching acquisition": "joint_venture_partner_matching_acquisition",
    "joint ventur matching acquisitions": "joint_venture_partner_matching_acquisition",
    "JV partner acquisition": "joint_venture_partner_acquisition",
    "JV partner acquisitions": "joint_venture_partner_acquisition",
    "JV partner match": "joint_venture_partner_matching",
    "JV partner matches": "joint_venture_partner_matching",
    "JV matching acquisition": "joint_venture_partner_matching_acquisition",
    "JV matching acquisitions": "joint_venture_partner_matching_acquisition",
    "JV acquisition partner": "joint_venture_partner_acquisition",
    "JV acquisition partners": "joint_venture_partner_acquisition",
    "JV match": "joint_venture_partner_matching",
    "JV matches": "joint_venture_partner_matching",
    "JV matching": "joint_venture_partner_matching",
    "JV matching acquisition": "joint_venture_partner_matching_acquisition",
    "JV matching acquisitions": "joint_venture_partner_matching_acquisition",
    "JV acquisition": "joint_venture_acquisition",
    "JV acquisition partners": "joint_venture_partner_acquisition",
    "JV acquisition partner": "joint_venture_partner_acquisition",
    "joint venture acquisition partners": "joint_venture_partner_acquisition",
    "joint venture acquisition partner": "joint_venture_partner_acquisition",
    "joint venture matching acquisition": "joint_venture_partner_matching_acquisition",
    "joint venture matching acquisitions": "joint_venture_partner_matching_acquisition",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    hash_input += SEMANTIC_MAP_VERSION
    hash_input += SEMANTIC_MAP_AUTHOR
    hash_input += SEMANTIC_MAP_ENGINE
    hash_input += str(_EXPECTED_ENTRY_COUNT)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (
        actual_count == _EXPECTED_ENTRY_COUNT and
        actual_hash == _MAP_INTEGRITY_HASH
    )
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try removing plural 's'
    if t.endswith("s") and t[:-1] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-1]]
    # Try removing common misspellings
    t2 = t.replace("minral", "mineral").replace("minrals", "minerals")
    if t2 in SEMANTIC_MAP:
        return SEMANTIC_MAP[t2]
    return t

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)