import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "FRAC02 Team"
SEMANTIC_MAP_ENGINE = "FRAC02_proppant_selection"

SEMANTIC_MAP = {
    # Sand Types
    "northern white sand": "northern_white_sand",
    "nws": "northern_white_sand",
    "northern sand": "northern_white_sand",
    "white sand": "northern_white_sand",
    "premium white": "northern_white_sand",
    "wisconsin sand": "northern_white_sand",
    "illinois sand": "northern_white_sand",
    "regional brown sand": "regional_brown_sand",
    "brown sand": "regional_brown_sand",
    "in-basin sand": "regional_brown_sand",
    "inbasin sand": "regional_brown_sand",
    "local sand": "regional_brown_sand",
    "regional sand": "regional_brown_sand",
    "texas brown": "regional_brown_sand",
    "oklahoma brown": "regional_brown_sand",
    "arkansas brown": "regional_brown_sand",
    "brown": "regional_brown_sand",
    "white": "northern_white_sand",
    "in basin": "regional_brown_sand",
    "inbasin": "regional_brown_sand",
    "inbasin mine": "regional_brown_sand",
    "in-basin mine": "regional_brown_sand",
    "in basin mine": "regional_brown_sand",
    # Mesh Sizes
    "20/40": "mesh_20_40",
    "20 40": "mesh_20_40",
    "20-40": "mesh_20_40",
    "20x40": "mesh_20_40",
    "2040": "mesh_20_40",
    "20 40 mesh": "mesh_20_40",
    "20-40 mesh": "mesh_20_40",
    "20x40 mesh": "mesh_20_40",
    "30/50": "mesh_30_50",
    "30 50": "mesh_30_50",
    "30-50": "mesh_30_50",
    "30x50": "mesh_30_50",
    "3050": "mesh_30_50",
    "30 50 mesh": "mesh_30_50",
    "30-50 mesh": "mesh_30_50",
    "30x50 mesh": "mesh_30_50",
    "40/70": "mesh_40_70",
    "40 70": "mesh_40_70",
    "40-70": "mesh_40_70",
    "40x70": "mesh_40_70",
    "4070": "mesh_40_70",
    "40 70 mesh": "mesh_40_70",
    "40-70 mesh": "mesh_40_70",
    "40x70 mesh": "mesh_40_70",
    "100 mesh": "mesh_100",
    "100-mesh": "mesh_100",
    "100mesh": "mesh_100",
    "100": "mesh_100",
    "100 m": "mesh_100",
    "100m": "mesh_100",
    # Resin-Coated Sand
    "resin coated sand": "rcs",
    "resin-coated sand": "rcs",
    "rcs": "rcs",
    "resin sand": "rcs",
    "resin": "rcs",
    "resin coat": "rcs",
    "resin coating": "rcs",
    "resin coated": "rcs",
    "resin-coat": "rcs",
    "resincoat": "rcs",
    "rcs proppant": "rcs",
    "rcs sand": "rcs",
    "resin proppant": "rcs",
    "resin treated sand": "rcs",
    "resin treatment": "rcs",
    # Ceramic Proppants
    "ceramic": "ceramic_proppant",
    "ceramic proppant": "ceramic_proppant",
    "ceramics": "ceramic_proppant",
    "lightweight ceramic": "lightweight_ceramic",
    "lw ceramic": "lightweight_ceramic",
    "lw": "lightweight_ceramic",
    "intermediate strength ceramic": "intermediate_ceramic",
    "isc": "intermediate_ceramic",
    "intermediate ceramic": "intermediate_ceramic",
    "high strength ceramic": "high_strength_ceramic",
    "hsc": "high_strength_ceramic",
    "high strength": "high_strength_ceramic",
    "hs ceramic": "high_strength_ceramic",
    "hs": "high_strength_ceramic",
    "ultra high strength ceramic": "ultra_high_strength_ceramic",
    "uhsc": "ultra_high_strength_ceramic",
    "ultra high strength": "ultra_high_strength_ceramic",
    "bauxite": "high_strength_ceramic",
    "bauxite ceramic": "high_strength_ceramic",
    # Proppant Concentration
    "ppa": "proppant_concentration",
    "proppant concentration": "proppant_concentration",
    "pounds per gallon": "proppant_concentration",
    "lb/gal": "proppant_concentration",
    "lb per gal": "proppant_concentration",
    "lb/galus": "proppant_concentration",
    "lb/gal us": "proppant_concentration",
    "lb/ft": "proppant_concentration_per_ft",
    "lb/ft lateral": "proppant_concentration_per_ft",
    "pounds per foot": "proppant_concentration_per_ft",
    "proppant per foot": "proppant_concentration_per_ft",
    "proppant/ft": "proppant_concentration_per_ft",
    "proppant per lateral foot": "proppant_concentration_per_ft",
    "concentration schedule": "ppa_schedule",
    "ppa schedule": "ppa_schedule",
    "ppa ramp": "ppa_ramp",
    "concentration ramp": "ppa_ramp",
    "ramp design": "ppa_ramp",
    "proppant ramp": "ppa_ramp",
    "ramp up": "ppa_ramp",
    "rampdown": "ppa_ramp",
    "ramp down": "ppa_ramp",
    "tail-in": "tail_in_strategy",
    "tail in": "tail_in_strategy",
    "tailin": "tail_in_strategy",
    "tail-in strategy": "tail_in_strategy",
    "tail in strategy": "tail_in_strategy",
    "tailin strategy": "tail_in_strategy",
    "high concentration tail-in": "tail_in_strategy",
    "high conc tail-in": "tail_in_strategy",
    "tail-in proppant": "tail_in_strategy",
    "tail-in sand": "tail_in_strategy",
    "tail-in ceramic": "tail_in_strategy",
    "tail-in schedule": "tail_in_strategy",
    "tail-in ramp": "tail_in_strategy",
    # API/ISO Testing
    "api rp 19c": "api_rp_19c",
    "api 19c": "api_rp_19c",
    "api rp19c": "api_rp_19c",
    "api19c": "api_rp_19c",
    "iso 13503-2": "iso_13503_2",
    "iso13503-2": "iso_13503_2",
    "iso 13503": "iso_13503_2",
    "iso13503": "iso_13503_2",
    "api": "api_rp_19c",
    "iso": "iso_13503_2",
    "proppant testing": "proppant_testing",
    "proppant spec": "proppant_specification",
    "proppant specification": "proppant_specification",
    "specification": "proppant_specification",
    "spec": "proppant_specification",
    # Proppant Transport & Settling
    "proppant transport": "proppant_transport",
    "transport": "proppant_transport",
    "settling": "proppant_settling",
    "proppant settling": "proppant_settling",
    "settling velocity": "proppant_settling",
    "settling rate": "proppant_settling",
    "non-newtonian fluid": "non_newtonian_fluid",
    "non newtonian fluid": "non_newtonian_fluid",
    "non-newtonian": "non_newtonian_fluid",
    "non newtonian": "non_newtonian_fluid",
    "viscoelastic fluid": "non_newtonian_fluid",
    "gel fluid": "non_newtonian_fluid",
    "crosslinked gel": "non_newtonian_fluid",
    "linear gel": "non_newtonian_fluid",
    "slickwater": "slickwater",
    "slick water": "slickwater",
    "slick": "slickwater",
    # Embedment & Fines
    "proppant embedment": "proppant_embedment",
    "embedment": "proppant_embedment",
    "embedment in soft formation": "proppant_embedment",
    "soft formation": "soft_formation",
    "soft rock": "soft_formation",
    "proppant pack": "proppant_pack",
    "proppant pack damage": "proppant_pack_damage",
    "pack damage": "proppant_pack_damage",
    "proppant pack conductivity": "proppant_pack_conductivity",
    "pack conductivity": "proppant_pack_conductivity",
    "conductivity": "proppant_pack_conductivity",
    "long term conductivity": "long_term_conductivity",
    "long-term conductivity": "long_term_conductivity",
    "conductivity degradation": "long_term_conductivity",
    "long term degradation": "long_term_conductivity",
    "crush": "proppant_crush",
    "crush resistance": "proppant_crush",
    "crush strength": "proppant_crush",
    "crush test": "proppant_crush",
    "diagenesis": "diagenesis",
    "fines migration": "fines_migration",
    "fines": "fines_migration",
    "fines control": "fines_migration",
    "fines damage": "fines_migration",
    "fines production": "fines_migration",
    "proppant pack fines": "fines_migration",
    # Logistics
    "logistics": "proppant_logistics",
    "proppant logistics": "proppant_logistics",
    "sand logistics": "proppant_logistics",
    "in-basin logistics": "proppant_logistics",
    "inbasin logistics": "proppant_logistics",
    "mine logistics": "proppant_logistics",
    "supply chain": "proppant_logistics",
    "proppant supply chain": "proppant_logistics",
    "sand supply chain": "proppant_logistics",
    "in-basin mine logistics": "proppant_logistics",
    "inbasin mine logistics": "proppant_logistics",
    "proppant optimization": "proppant_optimization",
    "proppant logistics optimization": "proppant_logistics_optimization",
    "logistics optimization": "proppant_logistics_optimization",
    "sand optimization": "proppant_optimization",
    "proppant selection": "proppant_selection",
    "sand selection": "proppant_selection",
    "mesh selection": "mesh_selection",
    "mesh size selection": "mesh_selection",
    "mesh size": "mesh_selection",
    "size selection": "mesh_selection",
    # Other
    "proppant": "proppant",
    "sand": "proppant",
    "frac sand": "proppant",
    "fracsand": "proppant",
    "proppant sand": "proppant",
    "proppant material": "proppant",
    "proppant type": "proppant_type",
    "type": "proppant_type",
    "material": "proppant_type",
    "schedule": "ppa_schedule",
    "ramp": "ppa_ramp",
    "damage": "proppant_pack_damage",
    "pack": "proppant_pack",
    "formation": "formation",
    "well": "well",
    "lateral": "lateral",
    "lateral foot": "lateral",
    "ft": "lateral",
    "foot": "lateral",
    "ft.": "lateral",
    "wellbore": "wellbore",
    "well bore": "wellbore",
    "bore": "wellbore",
    "well completion": "well_completion",
    "completion": "well_completion",
    "hydraulic fracturing": "hydraulic_fracturing",
    "hydrofrac": "hydraulic_fracturing",
    "frac": "hydraulic_fracturing",
    "fracking": "hydraulic_fracturing",
    "fracturing": "hydraulic_fracturing",
    "hydraulic fracture": "hydraulic_fracturing",
    "frac job": "hydraulic_fracturing",
    "frac stage": "frac_stage",
    "stage": "frac_stage",
    "stages": "frac_stage",
    "pad": "pad",
    "pad stage": "pad",
    "flush": "flush",
    "flush stage": "flush",
    "screenout": "screenout",
    "screen out": "screenout",
    "screen-out": "screenout",
    "screening": "screenout",
    "bridging": "screenout",
    "flowback": "flowback",
    "flow back": "flowback",
    "flowback control": "flowback_control",
    "flow back control": "flowback_control",
    "proppant flowback": "flowback_control",
    "proppant flow back": "flowback_control",
    "proppant flowback control": "flowback_control",
    "proppant flow back control": "flowback_control",
    "well cleanup": "flowback_control",
    "cleanup": "flowback_control",
    "clean up": "flowback_control",
    "well clean up": "flowback_control",
    "well clean-up": "flowback_control",
    "well clean-up flowback": "flowback_control",
    "well clean up flowback": "flowback_control",
    "well clean up flow back": "flowback_control",
    "well clean-up flow back": "flowback_control",
    "proppant schedule": "ppa_schedule",
    "sand schedule": "ppa_schedule",
    "ceramic schedule": "ppa_schedule",
    "proppant ramp": "ppa_ramp",
    "sand ramp": "ppa_ramp",
    "ceramic ramp": "ppa_ramp",
    "proppant tail-in": "tail_in_strategy",
    "sand tail-in": "tail_in_strategy",
    "ceramic tail-in": "tail_in_strategy",
    "proppant tail in": "tail_in_strategy",
    "sand tail in": "tail_in_strategy",
    "ceramic tail in": "tail_in_strategy",
    "proppant tailin": "tail_in_strategy",
    "sand tailin": "tail_in_strategy",
    "ceramic tailin": "tail_in_strategy",
    "proppant tail": "tail_in_strategy",
    "sand tail": "tail_in_strategy",
    "ceramic tail": "tail_in_strategy",
    # Misspellings & Variants
    "proppant conc": "proppant_concentration",
    "proppant conc.": "proppant_concentration",
    "proppant conc per ft": "proppant_concentration_per_ft",
    "proppant conc/ft": "proppant_concentration_per_ft",
    "proppant conc per lateral foot": "proppant_concentration_per_ft",
    "proppant conc/ft lateral": "proppant_concentration_per_ft",
    "proppant conc per lateral": "proppant_concentration_per_ft",
    "proppant con": "proppant_concentration",
    "proppant con.": "proppant_concentration",
    "proppant con per ft": "proppant_concentration_per_ft",
    "proppant con/ft": "proppant_concentration_per_ft",
    "proppant con per lateral foot": "proppant_concentration_per_ft",
    "proppant con/ft lateral": "proppant_concentration_per_ft",
    "proppant con per lateral": "proppant_concentration_per_ft",
    "proppant conc per foot": "proppant_concentration_per_ft",
    "proppant con per foot": "proppant_concentration_per_ft",
    "proppant conc/foot": "proppant_concentration_per_ft",
    "proppant con/foot": "proppant_concentration_per_ft",
    "proppant conc per ft.": "proppant_concentration_per_ft",
    "proppant con per ft.": "proppant_concentration_per_ft",
    "proppant conc/ft.": "proppant_concentration_per_ft",
    "proppant con/ft.": "proppant_concentration_per_ft",
    "proppant conc per lateral ft": "proppant_concentration_per_ft",
    "proppant con per lateral ft": "proppant_concentration_per_ft",
    "proppant conc/lateral ft": "proppant_concentration_per_ft",
    "proppant con/lateral ft": "proppant_concentration_per_ft",
    "proppant conc per lateral ft.": "proppant_concentration_per_ft",
    "proppant con per lateral ft.": "proppant_concentration_per_ft",
    "proppant conc/lateral ft.": "proppant_concentration_per_ft",
    "proppant con/lateral ft.": "proppant_concentration_per_ft",
    # More mesh misspellings
    "20/40m": "mesh_20_40",
    "30/50m": "mesh_30_50",
    "40/70m": "mesh_40_70",
    "100msh": "mesh_100",
    "100ms": "mesh_100",
    "20 40m": "mesh_20_40",
    "30 50m": "mesh_30_50",
    "40 70m": "mesh_40_70",
    "100 meshm": "mesh_100",
    # More synonyms
    "conductivity loss": "long_term_conductivity",
    "conductivity impairment": "long_term_conductivity",
    "conductivity reduction": "long_term_conductivity",
    "conductivity damage": "long_term_conductivity",
    "crushability": "proppant_crush",
    "crushable": "proppant_crush",
    "crush resistance test": "proppant_crush",
    "crush test": "proppant_crush",
    "crush strength test": "proppant_crush",
    "embedment test": "proppant_embedment",
    "embedment damage": "proppant_embedment",
    "embedment loss": "proppant_embedment",
    "fines test": "fines_migration",
    "fines loss": "fines_migration",
    "fines migration test": "fines_migration",
    "fines generation": "fines_migration",
    "fines content": "fines_migration",
    "fines analysis": "fines_migration",
    "fines evaluation": "fines_migration",
    "fines screening": "fines_migration",
    "fines pack": "fines_migration",
    "fines pack damage": "fines_migration",
    "fines pack test": "fines_migration",
    "fines pack loss": "fines_migration",
    "fines pack migration": "fines_migration",
    "fines pack evaluation": "fines_migration",
    "fines pack analysis": "fines_migration",
    # More logistics
    "mine": "mine",
    "sand mine": "mine",
    "proppant mine": "mine",
    "in-basin mine": "mine",
    "inbasin mine": "mine",
    "regional mine": "mine",
    "white sand mine": "mine",
    "brown sand mine": "mine",
    "mine optimization": "proppant_logistics_optimization",
    "mine logistics": "proppant_logistics",
    "mine supply": "proppant_logistics",
    "mine supply chain": "proppant_logistics",
    "mine schedule": "ppa_schedule",
    "mine ramp": "ppa_ramp",
    # Misc
    "api test": "proppant_testing",
    "iso test": "proppant_testing",
    "api/iso test": "proppant_testing",
    "api/iso": "proppant_testing",
    "api iso": "proppant_testing",
    "api/iso specification": "proppant_specification",
    "api iso specification": "proppant_specification",
    "api/iso spec": "proppant_specification",
    "api iso spec": "proppant_specification",
    "api/iso standard": "proppant_specification",
    "api iso standard": "proppant_specification",
    "api/iso standards": "proppant_specification",
    "api iso standards": "proppant_specification",
    "api/iso testing": "proppant_testing",
    "api iso testing": "proppant_testing",
    "api/iso test method": "proppant_testing",
    "api iso test method": "proppant_testing",
    "api/iso methods": "proppant_testing",
    "api iso methods": "proppant_testing",
    "iso method": "proppant_testing",
    "api method": "proppant_testing",
    "iso methods": "proppant_testing",
    "api methods": "proppant_testing",
    "iso procedure": "proppant_testing",
    "api procedure": "proppant_testing",
    "iso procedures": "proppant_testing",
    "api procedures": "proppant_testing",
    "iso protocol": "proppant_testing",
    "api protocol": "proppant_testing",
    "iso protocols": "proppant_testing",
    "api protocols": "proppant_testing",
    # More mesh
    "mesh": "mesh_selection",
    "mesh size": "mesh_selection",
    "mesh sizes": "mesh_selection",
    "mesh selection": "mesh_selection",
    "mesh schedule": "ppa_schedule",
    "mesh ramp": "ppa_ramp",
    "mesh tail-in": "tail_in_strategy",
    "mesh tail in": "tail_in_strategy",
    "mesh tailin": "tail_in_strategy",
    "mesh tail": "tail_in_strategy",
    # More formation
    "formation damage": "proppant_pack_damage",
    "formation fines": "fines_migration",
    "formation embedment": "proppant_embedment",
    "formation loss": "proppant_pack_damage",
    "formation degradation": "long_term_conductivity",
    "formation conductivity": "proppant_pack_conductivity",
    "formation test": "proppant_testing",
    "formation evaluation": "proppant_testing",
    "formation analysis": "proppant_testing",
    # More proppant
    "proppant damage": "proppant_pack_damage",
    "proppant degradation": "long_term_conductivity",
    "proppant conductivity": "proppant_pack_conductivity",
    "proppant loss": "proppant_pack_damage",
    "proppant test": "proppant_testing",
    "proppant evaluation": "proppant_testing",
    "proppant analysis": "proppant_testing",
    # More sand
    "sand damage": "proppant_pack_damage",
    "sand degradation": "long_term_conductivity",
    "sand conductivity": "proppant_pack_conductivity",
    "sand loss": "proppant_pack_damage",
    "sand test": "proppant_testing",
    "sand evaluation": "proppant_testing",
    "sand analysis": "proppant_testing",
    # More ceramic
    "ceramic damage": "proppant_pack_damage",
    "ceramic degradation": "long_term_conductivity",
    "ceramic conductivity": "proppant_pack_conductivity",
    "ceramic loss": "proppant_pack_damage",
    "ceramic test": "proppant_testing",
    "ceramic evaluation": "proppant_testing",
    "ceramic analysis": "proppant_testing",
    # More tail-in
    "tail": "tail_in_strategy",
    "tailin": "tail_in_strategy",
    "tail-in": "tail_in_strategy",
    "tail in": "tail_in_strategy",
    # More ramp/schedule
    "ramp schedule": "ppa_schedule",
    "schedule ramp": "ppa_ramp",
    "ramp up schedule": "ppa_schedule",
    "ramp down schedule": "ppa_schedule",
    "schedule up": "ppa_ramp",
    "schedule down": "ppa_ramp",
    # More proppant types
    "sand proppant": "proppant",
    "ceramic proppant": "ceramic_proppant",
    "resin proppant": "rcs",
    "rcs proppant": "rcs",
    "bauxite proppant": "high_strength_ceramic",
    "bauxite sand": "high_strength_ceramic",
    # More
    "nonnewtonian": "non_newtonian_fluid",
    "nonnewtonian fluid": "non_newtonian_fluid",
    "non newtonian fluids": "non_newtonian_fluid",
    "non-newtonian fluids": "non_newtonian_fluid",
    "viscoelastic fluids": "non_newtonian_fluid",
    "gel fluids": "non_newtonian_fluid",
    "crosslinked gels": "non_newtonian_fluid",
    "linear gels": "non_newtonian_fluid",
    "slickwaters": "slickwater",
    "slick waters": "slickwater",
    "slick water fluids": "slickwater",
    "slickwater fluid": "slickwater",
    "slick water fluid": "slickwater",
}

_EXPECTED_ENTRY_COUNT = 280

def _compute_map_hash():
    items = sorted((k, v) for k, v in SEMANTIC_MAP.items())
    hash_input = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (_MAP_INTEGRITY_HASH == _compute_map_hash())
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "hash": _MAP_INTEGRITY_HASH,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = t.replace("’", "'").replace("–", "-").replace("—", "-")
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> list:
    norm = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == norm]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)