import hashlib

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "BLD05_legacy_archive Team"
SEMANTIC_MAP_ENGINE = "BLD05"

SEMANTIC_MAP = {
    # Sample entries expanded to 200+ entries with synonyms, abbreviations, acronyms, misspellings, related terms
    # Domain: topic
    "ai": "artificial_intelligence",
    "artificial intelligence": "artificial_intelligence",
    "artificial-intelligence": "artificial_intelligence",
    "artificialintelligence": "artificial_intelligence",
    "a.i.": "artificial_intelligence",
    "artifical intelligence": "artificial_intelligence",
    "ml": "machine_learning",
    "machine learning": "machine_learning",
    "machine-learning": "machine_learning",
    "machin learning": "machine_learning",
    "machne learning": "machine_learning",
    "m.l.": "machine_learning",
    "dl": "deep_learning",
    "deep learning": "deep_learning",
    "deep-learning": "deep_learning",
    "deeplearning": "deep_learning",
    "d.l.": "deep_learning",
    "nlp": "natural_language_processing",
    "natural language processing": "natural_language_processing",
    "natural-language-processing": "natural_language_processing",
    "naturallanguageprocessing": "natural_language_processing",
    "n.l.p.": "natural_language_processing",
    "computer vision": "computer_vision",
    "computer-vision": "computer_vision",
    "computervision": "computer_vision",
    "cv": "computer_vision",
    "c.v.": "computer_vision",
    "data science": "data_science",
    "data-science": "data_science",
    "datascience": "data_science",
    "ds": "data_science",
    "d.s.": "data_science",
    "big data": "big_data",
    "big-data": "big_data",
    "bigdata": "big_data",
    "bd": "big_data",
    "b.d.": "big_data",
    "ai ethics": "artificial_intelligence_ethics",
    "artificial intelligence ethics": "artificial_intelligence_ethics",
    "machine learning ethics": "machine_learning_ethics",
    "ml ethics": "machine_learning_ethics",
    "reinforcement learning": "reinforcement_learning",
    "reinforcement-learning": "reinforcement_learning",
    "reinforcment learning": "reinforcement_learning",
    "rl": "reinforcement_learning",
    "r.l.": "reinforcement_learning",
    "supervised learning": "supervised_learning",
    "supervised-learning": "supervised_learning",
    "unsupervised learning": "unsupervised_learning",
    "unsupervised-learning": "unsupervised_learning",
    "semi-supervised learning": "semi_supervised_learning",
    "semi supervised learning": "semi_supervised_learning",
    "semi-supervised-learning": "semi_supervised_learning",
    "semi_supervised_learning": "semi_supervised_learning",
    "svm": "support_vector_machine",
    "support vector machine": "support_vector_machine",
    "support-vector-machine": "support_vector_machine",
    "supportvector machine": "support_vector_machine",
    "cnn": "convolutional_neural_network",
    "convolutional neural network": "convolutional_neural_network",
    "convolutional-neural-network": "convolutional_neural_network",
    "convolutionalneuralnetwork": "convolutional_neural_network",
    "rnn": "recurrent_neural_network",
    "recurrent neural network": "recurrent_neural_network",
    "recurrent-neural-network": "recurrent_neural_network",
    "recurrentneuralnetwork": "recurrent_neural_network",
    "gan": "generative_adversarial_network",
    "generative adversarial network": "generative_adversarial_network",
    "generative-adversarial-network": "generative_adversarial_network",
    "generativeadversarialnetwork": "generative_adversarial_network",
    "nlp pipeline": "natural_language_processing_pipeline",
    "natural language processing pipeline": "natural_language_processing_pipeline",
    "natural-language-processing-pipeline": "natural_language_processing_pipeline",
    "nlp-pipeline": "natural_language_processing_pipeline",
    "bert": "bidirectional_encoder_representations_from_transformers",
    "bidirectional encoder representations from transformers": "bidirectional_encoder_representations_from_transformers",
    "bidirectional-encoder-representations-from-transformers": "bidirectional_encoder_representations_from_transformers",
    "transformer": "transformer_model",
    "transformers": "transformer_model",
    "transformer model": "transformer_model",
    "transformer-model": "transformer_model",
    "gpt": "generative_pretrained_transformer",
    "generative pretrained transformer": "generative_pretrained_transformer",
    "generative-pretrained-transformer": "generative_pretrained_transformer",
    "g.p.t.": "generative_pretrained_transformer",
    "tokenization": "tokenization",
    "tokenize": "tokenization",
    "tokeniser": "tokenization",
    "tokenizer": "tokenization",
    "embedding": "embedding",
    "embeddings": "embedding",
    "word embedding": "embedding",
    "word embeddings": "embedding",
    "word2vec": "word2vec",
    "word to vec": "word2vec",
    "word-to-vec": "word2vec",
    "w2v": "word2vec",
    "glove": "glove",
    "global vectors": "glove",
    "global-vectors": "glove",
    "g.l.o.v.e.": "glove",
    "attention mechanism": "attention_mechanism",
    "attention": "attention_mechanism",
    "self attention": "self_attention",
    "self-attention": "self_attention",
    "selfattention": "self_attention",
    "positional encoding": "positional_encoding",
    "positional-encoding": "positional_encoding",
    "positionalencoding": "positional_encoding",
    "overfitting": "overfitting",
    "underfitting": "underfitting",
    "cross validation": "cross_validation",
    "cross-validation": "cross_validation",
    "crossvalidation": "cross_validation",
    "cv": "cross_validation",
    "confusion matrix": "confusion_matrix",
    "confusion-matrix": "confusion_matrix",
    "confusionmatrix": "confusion_matrix",
    "precision": "precision",
    "recall": "recall",
    "f1 score": "f1_score",
    "f1-score": "f1_score",
    "f1score": "f1_score",
    "accuracy": "accuracy",
    "roc curve": "roc_curve",
    "roc-curve": "roc_curve",
    "roccurve": "roc_curve",
    "auc": "area_under_curve",
    "area under curve": "area_under_curve",
    "area-under-curve": "area_under_curve",
    "hyperparameter tuning": "hyperparameter_tuning",
    "hyper-parameter tuning": "hyperparameter_tuning",
    "hyperparameter-tuning": "hyperparameter_tuning",
    "grid search": "grid_search",
    "grid-search": "grid_search",
    "gridsearch": "grid_search",
    "random search": "random_search",
    "random-search": "random_search",
    "randomsearch": "random_search",
    "feature engineering": "feature_engineering",
    "feature-engineering": "feature_engineering",
    "featureengineering": "feature_engineering",
    "feature selection": "feature_selection",
    "feature-selection": "feature_selection",
    "featureselection": "feature_selection",
    "dimensionality reduction": "dimensionality_reduction",
    "dimensionality-reduction": "dimensionality_reduction",
    "dimensionalityreduction": "dimensionality_reduction",
    "pca": "principal_component_analysis",
    "principal component analysis": "principal_component_analysis",
    "principal-component-analysis": "principal_component_analysis",
    "principalcomponentanalysis": "principal_component_analysis",
    "tsne": "t_sne",
    "t-sne": "t_sne",
    "t s n e": "t_sne",
    "clustering": "clustering",
    "kmeans": "k_means",
    "k-means": "k_means",
    "k means": "k_means",
    "k nearest neighbors": "k_nearest_neighbors",
    "k-nearest neighbors": "k_nearest_neighbors",
    "k nearest-neighbors": "k_nearest_neighbors",
    "knn": "k_nearest_neighbors",
    "support vector machines": "support_vector_machine",
    "svms": "support_vector_machine",
    "decision tree": "decision_tree",
    "decision-tree": "decision_tree",
    "decisiontree": "decision_tree",
    "random forest": "random_forest",
    "random-forest": "random_forest",
    "randomforest": "random_forest",
    "ensemble learning": "ensemble_learning",
    "ensemble-learning": "ensemble_learning",
    "ensemblelearning": "ensemble_learning",
    "bagging": "bagging",
    "boosting": "boosting",
    "xgboost": "xgboost",
    "extreme gradient boosting": "xgboost",
    "extreme-gradient-boosting": "xgboost",
    "lightgbm": "lightgbm",
    "light gbm": "lightgbm",
    "light-gbm": "lightgbm",
    "catboost": "catboost",
    "categorical boosting": "catboost",
    "categorical-boosting": "catboost",
    "linear regression": "linear_regression",
    "linear-regression": "linear_regression",
    "linearregression": "linear_regression",
    "logistic regression": "logistic_regression",
    "logistic-regression": "logistic_regression",
    "logisticregression": "logistic_regression",
    "regression": "regression",
    "classification": "classification",
    "clustering algorithm": "clustering",
    "unsupervised clustering": "clustering",
    "time series": "time_series",
    "time-series": "time_series",
    "timeseries": "time_series",
    "forecasting": "forecasting",
    "anomaly detection": "anomaly_detection",
    "anomaly-detection": "anomaly_detection",
    "anomalydetection": "anomaly_detection",
    "outlier detection": "anomaly_detection",
    "outlier-detection": "anomaly_detection",
    "outlierdetection": "anomaly_detection",
    "data preprocessing": "data_preprocessing",
    "data-preprocessing": "data_preprocessing",
    "datapreprocessing": "data_preprocessing",
    "data cleaning": "data_cleaning",
    "data-cleaning": "data_cleaning",
    "datacleaning": "data_cleaning",
    "data augmentation": "data_augmentation",
    "data-augmentation": "data_augmentation",
    "dataaugmentation": "data_augmentation",
    "feature extraction": "feature_extraction",
    "feature-extraction": "feature_extraction",
    "featureextraction": "feature_extraction",
    "cross entropy": "cross_entropy",
    "cross-entropy": "cross_entropy",
    "crossentropy": "cross_entropy",
    "loss function": "loss_function",
    "loss-function": "loss_function",
    "lossfunction": "loss_function",
    "gradient descent": "gradient_descent",
    "gradient-descent": "gradient_descent",
    "gradientdescent": "gradient_descent",
    "stochastic gradient descent": "stochastic_gradient_descent",
    "stochastic-gradient-descent": "stochastic_gradient_descent",
    "sgd": "stochastic_gradient_descent",
    "batch normalization": "batch_normalization",
    "batch-normalization": "batch_normalization",
    "batchnormalization": "batch_normalization",
    "dropout": "dropout",
    "relu": "relu_activation",
    "rectified linear unit": "relu_activation",
    "rectified-linear-unit": "relu_activation",
    "activation function": "activation_function",
    "activation-function": "activation_function",
    "activationfunction": "activation_function",
    "softmax": "softmax_activation",
    "softmax activation": "softmax_activation",
    "softmax-activation": "softmax_activation",
    "embedding layer": "embedding_layer",
    "embedding-layer": "embedding_layer",
    "embeddinglayer": "embedding_layer",
    "token": "token",
    "tokens": "token",
    "vocabulary": "vocabulary",
    "vocab": "vocabulary",
    "wordpiece": "wordpiece",
    "sentencepiece": "sentencepiece",
    "byte pair encoding": "byte_pair_encoding",
    "byte-pair-encoding": "byte_pair_encoding",
    "bpe": "byte_pair_encoding",
    "language model": "language_model",
    "language-model": "language_model",
    "languagemodel": "language_model",
    "lm": "language_model",
    "l.m.": "language_model",
    "pretraining": "pretraining",
    "fine tuning": "fine_tuning",
    "fine-tuning": "fine_tuning",
    "finetuning": "fine_tuning",
    "zero shot learning": "zero_shot_learning",
    "zero-shot learning": "zero_shot_learning",
    "zero-shot-learning": "zero_shot_learning",
    "zero shot": "zero_shot_learning",
    "zero-shot": "zero_shot_learning",
    "transfer learning": "transfer_learning",
    "transfer-learning": "transfer_learning",
    "transferlearning": "transfer_learning",
    "few shot learning": "few_shot_learning",
    "few-shot learning": "few_shot_learning",
    "few-shot-learning": "few_shot_learning",
    "few shot": "few_shot_learning",
    "few-shot": "few_shot_learning",
    "attention head": "attention_head",
    "attention-head": "attention_head",
    "attentionhead": "attention_head",
    "multi head attention": "multi_head_attention",
    "multi-head attention": "multi_head_attention",
    "multi-head-attention": "multi_head_attention",
    "multiheadattention": "multi_head_attention",
    "positional embedding": "positional_embedding",
    "positional-embedding": "positional_embedding",
    "positionalembedding": "positional_embedding",
    "bert tokenizer": "bert_tokenizer",
    "bert-tokenizer": "bert_tokenizer",
    "berttokenizer": "bert_tokenizer",
    "tokenizer": "tokenization",
    "optimizer": "optimizer",
    "optimizers": "optimizer",
    "adam": "adam_optimizer",
    "adam optimizer": "adam_optimizer",
    "adam-optimizer": "adam_optimizer",
    "sgd optimizer": "sgd_optimizer",
    "sgd-optimizer": "sgd_optimizer",
    "sgdoptimizer": "sgd_optimizer",
    "learning rate": "learning_rate",
    "learning-rate": "learning_rate",
    "learningrate": "learning_rate",
    "batch size": "batch_size",
    "batch-size": "batch_size",
    "batchsize": "batch_size",
    "epoch": "epoch",
    "epochs": "epoch",
    "training": "training",
    "inference": "inference",
    "evaluation": "evaluation",
    "test set": "test_set",
    "test-set": "test_set",
    "testset": "test_set",
    "validation set": "validation_set",
    "validation-set": "validation_set",
    "validationset": "validation_set",
    "dataset": "dataset",
    "data set": "dataset",
    "data-set": "dataset",
    "corpus": "dataset",
    "token frequency": "token_frequency",
    "token-frequency": "token_frequency",
    "tokenfrequency": "token_frequency",
    "stop words": "stop_words",
    "stop-words": "stop_words",
    "stopwords": "stop_words",
    "stemming": "stemming",
    "lemmatization": "lemmatization",
    "lemmatisation": "lemmatization",
    "wordnet": "wordnet",
    "pos tagging": "part_of_speech_tagging",
    "pos-tagging": "part_of_speech_tagging",
    "part of speech tagging": "part_of_speech_tagging",
    "part-of-speech-tagging": "part_of_speech_tagging",
    "pos tagger": "part_of_speech_tagging",
    "named entity recognition": "named_entity_recognition",
    "named-entity-recognition": "named_entity_recognition",
    "ner": "named_entity_recognition",
    "coreference resolution": "coreference_resolution",
    "coreference-resolution": "coreference_resolution",
    "coref resolution": "coreference_resolution",
    "coref-resolution": "coreference_resolution",
    "dependency parsing": "dependency_parsing",
    "dependency-parsing": "dependency_parsing",
    "dependencyparsing": "dependency_parsing",
    "constituency parsing": "constituency_parsing",
    "constituency-parsing": "constituency_parsing",
    "constituencyparsing": "constituency_parsing",
    "word sense disambiguation": "word_sense_disambiguation",
    "word-sense-disambiguation": "word_sense_disambiguation",
    "wsd": "word_sense_disambiguation",
    "language understanding": "language_understanding",
    "language-understanding": "language_understanding",
    "languageunderstanding": "language_understanding",
    "language generation": "language_generation",
    "language-generation": "language_generation",
    "languagegeneration": "language_generation",
    "dialog systems": "dialog_systems",
    "dialog-systems": "dialog_systems",
    "dialogsystems": "dialog_systems",
    "chatbot": "dialog_systems",
    "chat bots": "dialog_systems",
    "chat-bots": "dialog_systems",
    "speech recognition": "speech_recognition",
    "speech-recognition": "speech_recognition",
    "speechrecognition": "speech_recognition",
    "automatic speech recognition": "speech_recognition",
    "automatic-speech-recognition": "speech_recognition",
    "asr": "speech_recognition",
    "text to speech": "text_to_speech",
    "text-to-speech": "text_to_speech",
    "texttospeech": "text_to_speech",
    "tts": "text_to_speech",
    "machine translation": "machine_translation",
    "machine-translation": "machine_translation",
    "machin translation": "machine_translation",
    "mt": "machine_translation",
    "speech synthesis": "speech_synthesis",
    "speech-synthesis": "speech_synthesis",
    "speechsynthesis": "speech_synthesis",
    "language model pretraining": "language_model_pretraining",
    "language-model-pretraining": "language_model_pretraining",
    "language model fine tuning": "language_model_fine_tuning",
    "language-model-fine-tuning": "language_model_fine_tuning",
    "knowledge graph": "knowledge_graph",
    "knowledge-graph": "knowledge_graph",
    "knowledgegraph": "knowledge_graph",
    "ontology": "ontology",
    "semantic web": "semantic_web",
    "semantic-web": "semantic_web",
    "semanticweb": "semantic_web",
    "linked data": "linked_data",
    "linked-data": "linked_data",
    "linkeddata": "linked_data",
    "rdf": "resource_description_framework",
    "resource description framework": "resource_description_framework",
    "resource-description-framework": "resource_description_framework",
    "sparql": "sparql",
    "owl": "web_ontology_language",
    "web ontology language": "web_ontology_language",
    "web-ontology-language": "web_ontology_language",
    "webontologylanguage": "web_ontology_language",
    "reasoning": "reasoning",
    "inference": "inference",
    "entity linking": "entity_linking",
    "entity-linking": "entity_linking",
    "entitylinking": "entity_linking",
    "topic modeling": "topic_modeling",
    "topic-modelling": "topic_modeling",
    "topic modeling": "topic_modeling",
    "lda": "latent_dirichlet_allocation",
    "latent dirichlet allocation": "latent_dirichlet_allocation",
    "latent-dirichlet-allocation": "latent_dirichlet_allocation",
    "latentdirichletallocation": "latent_dirichlet_allocation",
    "word cloud": "word_cloud",
    "word-cloud": "word_cloud",
    "wordcloud": "word_cloud",
    "text mining": "text_mining",
    "text-mining": "text_mining",
    "textmining": "text_mining",
    "information retrieval": "information_retrieval",
    "information-retrieval": "information_retrieval",
    "informationretrieval": "information_retrieval",
    "search engine": "search_engine",
    "search-engine": "search_engine",
    "searchengine": "search_engine",
    "query": "query",
    "queries": "query",
    "ranking": "ranking",
    "recommender system": "recommender_system",
    "recommender-system": "recommender_system",
    "recommendersystem": "recommender_system",
    "collaborative filtering": "collaborative_filtering",
    "collaborative-filtering": "collaborative_filtering",
    "collaborativefiltering": "collaborative_filtering",
    "content based filtering": "content_based_filtering",
    "content-based filtering": "content_based_filtering",
    "contentbasedfiltering": "content_based_filtering",
    "evaluation metrics": "evaluation_metrics",
    "evaluation-metrics": "evaluation_metrics",
    "evaluationmetrics": "evaluation_metrics",
    "precision at k": "precision_at_k",
    "precision-at-k": "precision_at_k",
    "precisionatk": "precision_at_k",
    "mean average precision": "mean_average_precision",
    "mean-average-precision": "mean_average_precision",
    "meanaverageprecision": "mean_average_precision",
    "map": "mean_average_precision",
    "ndcg": "normalized_discounted_cumulative_gain",
    "normalized discounted cumulative gain": "normalized_discounted_cumulative_gain",
    "normalized-discounted-cumulative-gain": "normalized_discounted_cumulative_gain",
    "normalizeddiscountedcumulativegain": "normalized_discounted_cumulative_gain",
    "click through rate": "click_through_rate",
    "click-through rate": "click_through_rate",
    "clickthroughrate": "click_through_rate",
    "ctr": "click_through_rate",
    "user profiling": "user_profiling",
    "user-profiling": "user_profiling",
    "userprofiling": "user_profiling",
    "sentiment analysis": "sentiment_analysis",
    "sentiment-analysis": "sentiment_analysis",
    "sentimentanalysis": "sentiment_analysis",
    "opinion mining": "sentiment_analysis",
    "opinion-mining": "sentiment_analysis",
    "opinionmining": "sentiment_analysis",
    "emotion detection": "emotion_detection",
    "emotion-detection": "emotion_detection",
    "emotiondetection": "emotion_detection",
    "text classification": "text_classification",
    "text-classification": "text_classification",
    "textclassification": "text_classification",
    "topic detection": "topic_detection",
    "topic-detection": "topic_detection",
    "topicdetection": "topic_detection",
    "text summarization": "text_summarization",
    "text-summarization": "text_summarization",
    "textsummarization": "text_summarization",
    "extractive summarization": "extractive_summarization",
    "extractive-summarization": "extractive_summarization",
    "extractivesummarization": "extractive_summarization",
    "abstractive summarization": "abstractive_summarization",
    "abstractive-summarization": "abstractive_summarization",
    "abstractivesummarization": "abstractive_summarization",
    "question answering": "question_answering",
    "question-answering": "question_answering",
    "questionanswering": "question_answering",
    "reading comprehension": "reading_comprehension",
    "reading-comprehension": "reading_comprehension",
    "readingcomprehension": "reading_comprehension",
    "knowledge distillation": "knowledge_distillation",
    "knowledge-distillation": "knowledge_distillation",
    "knowledgedistillation": "knowledge_distillation",
    "model compression": "model_compression",
    "model-compression": "model_compression",
    "modelcompression": "model_compression",
    "quantization": "quantization",
    "pruning": "pruning",
    "explainable ai": "explainable_ai",
    "explainable-ai": "explainable_ai",
    "explainableai": "explainable_ai",
    "xai": "explainable_ai",
    "fairness": "fairness",
    "bias": "bias",
    "model interpretability": "model_interpretability",
    "model-interpretability": "model_interpretability",
    "modelinterpretability": "model_interpretability",
    "causal inference": "causal_inference",
    "causal-inference": "causal_inference",
    "causalinference": "causal_inference",
    "privacy": "privacy",
    "security": "security",
    "federated learning": "federated_learning",
    "federated-learning": "federated_learning",
    "federatedlearning": "federated_learning",
    "edge computing": "edge_computing",
    "edge-computing": "edge_computing",
    "edgecomputing": "edge_computing",
    "cloud computing": "cloud_computing",
    "cloud-computing": "cloud_computing",
    "cloudcomputing": "cloud_computing",
    "internet of things": "internet_of_things",
    "internet-of-things": "internet_of_things",
    "iot": "internet_of_things",
    "robotics": "robotics",
    "autonomous vehicles": "autonomous_vehicles",
    "autonomous-vehicles": "autonomous_vehicles",
    "autonomousvehicles": "autonomous_vehicles",
    "self driving cars": "autonomous_vehicles",
    "self-driving cars": "autonomous_vehicles",
    "selfdrivingcars": "autonomous_vehicles",
    "computer graphics": "computer_graphics",
    "computer-graphics": "computer_graphics",
    "computergraphics": "computer_graphics",
    "virtual reality": "virtual_reality",
    "virtual-reality": "virtual_reality",
    "virtualreality": "virtual_reality",
    "augmented reality": "augmented_reality",
    "augmented-reality": "augmented_reality",
    "augmentedreality": "augmented_reality",
    "mixed reality": "mixed_reality",
    "mixed-reality": "mixed_reality",
    "mixedreality": "mixed_reality",
    "human computer interaction": "human_computer_interaction",
    "human-computer interaction": "human_computer_interaction",
    "humancomputerinteraction": "human_computer_interaction",
    "hci": "human_computer_interaction",
    "computer vision applications": "computer_vision",
    "cv applications": "computer_vision",
    "natural language understanding": "natural_language_understanding",
    "natural-language-understanding": "natural_language_understanding",
    "naturallanguageunderstanding": "natural_language_understanding",
    "nlu": "natural_language_understanding",
    "knowledge representation": "knowledge_representation",
    "knowledge-representation": "knowledge_representation",
    "knowledgerepresentation": "knowledge_representation",
    "semantic parsing": "semantic_parsing",
    "semantic-parsing": "semantic_parsing",
    "semanticparsing": "semantic_parsing",
    "commonsense reasoning": "commonsense_reasoning",
    "commonsense-reasoning": "commonsense_reasoning",
    "commonsensereasoning": "commonsense_reasoning",
    "multimodal learning": "multimodal_learning",
    "multimodal-learning": "multimodal_learning",
    "multimodallearning": "multimodal_learning",
    "zero shot classification": "zero_shot_learning",
    "zero-shot classification": "zero_shot_learning",
    "zero-shot-classification": "zero_shot_learning",
    "zero shot generation": "zero_shot_generation",
    "zero-shot generation": "zero_shot_generation",
    "zero-shot-generation": "zero_shot_generation",
    "zero shot translation": "zero_shot_translation",
    "zero-shot translation": "zero_shot_translation",
    "zero-shot-translation": "zero_shot_translation",
    "zero shot summarization": "zero_shot_summarization",
    "zero-shot summarization": "zero_shot_summarization",
    "zero-shot-summarization": "zero_shot_summarization",
    "multi task learning": "multi_task_learning",
    "multi-task learning": "multi_task_learning",
    "multi-task-learning": "multi_task_learning",
    "multitask learning": "multi_task_learning",
    "multitask-learning": "multi_task_learning",
    "multitasklearning": "multi_task_learning",
    "continual learning": "continual_learning",
    "continual-learning": "continual_learning",
    "continuallearning": "continual_learning",
    "lifelong learning": "continual_learning",
    "lifelong-learning": "continual_learning",
    "lifelonglearning": "continual_learning",
    "meta learning": "meta_learning",
    "meta-learning": "meta_learning",
    "metalearning": "meta_learning",
    "few shot meta learning": "few_shot_meta_learning",
    "few-shot meta learning": "few_shot_meta_learning",
    "few-shot-meta-learning": "few_shot_meta_learning",
    "fewshot metalearning": "few_shot_meta_learning",
    "fewshot-metalearning": "few_shot_meta_learning",
    "fewshotmetalearning": "few_shot_meta_learning",
    "autoencoder": "autoencoder",
    "auto encoder": "autoencoder",
    "auto-encoder": "autoencoder",
    "variational autoencoder": "variational_autoencoder",
    "variational-autoencoder": "variational_autoencoder",
    "variationalautoencoder": "variational_autoencoder",
    "vae": "variational_autoencoder",
    "generative model": "generative_model",
    "generative-model": "generative_model",
    "generativemodel": "generative_model",
    "latent variable model": "latent_variable_model",
    "latent-variable-model": "latent_variable_model",
    "latentvariablemodel": "latent_variable_model",
    "bayesian network": "bayesian_network",
    "bayesian-network": "bayesian_network",
    "bayesiannetwork": "bayesian_network",
    "markov chain": "markov_chain",
    "markov-chain": "markov_chain",
    "markovchain": "markov_chain",
    "hidden markov model": "hidden_markov_model",
    "hidden-markov-model": "hidden_markov_model",
    "hiddenmarkovmodel": "hidden_markov_model",
    "hmm": "hidden_markov_model",
    "graph neural network": "graph_neural_network",
    "graph-neural-network": "graph_neural_network",
    "graphneuralnetwork": "graph_neural_network",
    "gnn": "graph_neural_network",
    "graph convolutional network": "graph_convolutional_network",
    "graph-convolutional-network": "graph_convolutional_network",
    "graphconvolutionalnetwork": "graph_convolutional_network",
    "gcn": "graph_convolutional_network",
    "knowledge graph embedding": "knowledge_graph_embedding",
    "knowledge-graph-embedding": "knowledge_graph_embedding",
    "knowledgegraphembedding": "knowledge_graph_embedding",
    "kge": "knowledge_graph_embedding",
    "embedding learning": "embedding_learning",
    "embedding-learning": "embedding_learning",
    "embeddinglearning": "embedding_learning",
    "contrastive learning": "contrastive_learning",
    "contrastive-learning": "contrastive_learning",
    "contrastivelearning": "contrastive_learning",
    "self supervised learning": "self_supervised_learning",
    "self-supervised learning": "self_supervised_learning",
    "self-supervised-learning": "self_supervised_learning",
    "selfsupervisedlearning": "self_supervised_learning",
    "unsupervised pretraining": "unsupervised_pretraining",
    "unsupervised-pretraining": "unsupervised_pretraining",
    "unsupervisedpretraining": "unsupervised_pretraining",
    "data labeling": "data_labeling",
    "data-labeling": "data_labeling",
    "datalabeling": "data_labeling",
    "annotation": "data_labeling",
    "crowdsourcing": "crowdsourcing",
    "crowd sourcing": "crowdsourcing",
    "crowd-sourcing": "crowdsourcing",
    "active learning": "active_learning",
    "active-learning": "active_learning",
    "activelearning": "active_learning",
    "curriculum learning": "curriculum_learning",
    "curriculum-learning": "curriculum_learning",
    "curriculumlearning": "curriculum_learning",
    "neural architecture search": "neural_architecture_search",
    "neural-architecture-search": "neural_architecture_search",
    "neuralarchitecturesearch": "neural_architecture_search",
    "nas": "neural_architecture_search",
    "automl": "automl",
    "auto ml": "automl",
    "auto-ml": "automl",
    "hyperparameter optimization": "hyperparameter_optimization",
    "hyperparameter-optimization": "hyperparameter_optimization",
    "hyperparameteroptimization": "hyperparameter_optimization",
    "model selection": "model_selection",
    "model-selection": "model_selection",
    "modelselection": "model_selection",
    "cross domain learning": "cross_domain_learning",
    "cross-domain learning": "cross_domain_learning",
    "cross-domain-learning": "cross_domain_learning",
    "crossdomainlearning": "cross_domain_learning",
    "domain adaptation": "domain_adaptation",
    "domain-adaptation": "domain_adaptation",
    "domainadaptation": "domain_adaptation",
    "multi modal learning": "multimodal_learning",
    "multi-modal learning": "multimodal_learning",
    "multi-modal-learning": "multimodal_learning",
    "multimodallearning": "multimodal_learning",
    "multilingual learning": "multilingual_learning",
    "multilingual-learning": "multilingual_learning",
    "multilinguallearning": "multilingual_learning",
    "zero resource learning": "zero_resource_learning",
    "zero-resource learning": "zero_resource_learning",
    "zero-resource-learning": "zero_resource_learning",
    "zeroresourcelearning": "zero_resource_learning",
    "language acquisition": "language_acquisition",
    "language-acquisition": "language_acquisition",
    "languageacquisition": "language_acquisition",
    "speech processing": "speech_processing",
    "speech-processing": "speech_processing",
    "speechprocessing": "speech_processing",
    "phonetics": "phonetics",
    "phonology": "phonology",
    "morphology": "morphology",
    "syntax": "syntax",
    "semantics": "semantics",
    "pragmatics": "pragmatics",
    "discourse": "discourse",
    "dialogue": "dialog_systems",
    "dialog": "dialog_systems",
    "conversational ai": "dialog_systems",
    "conversational-ai": "dialog_systems",
    "conversationalai": "dialog_systems",
    "speech to text": "speech_recognition",
    "speech-to-text": "speech_recognition",
    "speechtotext": "speech_recognition",
    "automatic speech recognition": "speech_recognition",
    "automatic-speech-recognition": "speech_recognition",
    "asr": "speech_recognition",
    "language identification": "language_identification",
    "language-identification": "language_identification",
    "languageidentification": "language_identification",
    "code switching": "code_switching",
    "code-switching": "code_switching",
    "codeswitching": "code_switching",
    "multilingualism": "multilingual_learning",
    "language modeling": "language_model",
    "language-modeling": "language_model",
    "languagemodeling": "language_model",
    "tokenizer": "tokenization",
    "tokeniser": "tokenization",
    "word segmentation": "word_segmentation",
    "word-segmentation": "word_segmentation",
    "wordsegmentation": "word_segmentation",
    "sentence segmentation": "sentence_segmentation",
    "sentence-segmentation": "sentence_segmentation",
    "sentencesegmentation": "sentence_segmentation",
    "text normalization": "text_normalization",
    "text-normalization": "text_normalization",
    "textnormalization": "text_normalization",
    "language resources": "language_resources",
    "language-resources": "language_resources",
    "languageresources": "language_resources",
    "corpus linguistics": "corpus_linguistics",
    "corpus-linguistics": "corpus_linguistics",
    "corpuslinguistics": "corpus_linguistics",
    "language technology": "language_technology",
    "language-technology": "language_technology",
    "languagetechnology": "language_technology",
    "speech technology": "speech_technology",
    "speech-technology": "speech_technology",
    "speechtechnology": "speech_technology",
    "machine reading": "machine_reading",
    "machine-reading": "machine_reading",
    "machinereading": "machine_reading",
    "knowledge extraction": "knowledge_extraction",
    "knowledge-extraction": "knowledge_extraction",
    "knowledgeextraction": "knowledge_extraction",
    "information extraction": "information_extraction",
    "information-extraction": "information_extraction",
    "informationextraction": "information_extraction",
    "entity recognition": "named_entity_recognition",
    "entity-recognition": "named_entity_recognition",
    "entityrecognition": "named_entity_recognition",
    "relation extraction": "relation_extraction",
    "relation-extraction": "relation_extraction",
    "relationextraction": "relation_extraction",
    "semantic role labeling": "semantic_role_labeling",
    "semantic-role-labeling": "semantic_role_labeling",
    "semanticrolelabeling": "semantic_role_labeling",
    "srl": "semantic_role_labeling",
    "text entailment": "text_entailment",
    "text-entailment": "text_entailment",
    "textentailment": "text_entailment",
    "natural language inference": "natural_language_inference",
    "natural-language-inference": "natural_language_inference",
    "naturallanguageinference": "natural_language_inference",
    "nli": "natural_language_inference",
    "semantic similarity": "semantic_similarity",
    "semantic-similarity": "semantic_similarity",
    "semanticsimilarity": "semantic_similarity",
    "paraphrase detection": "paraphrase_detection",
    "paraphrase-detection": "paraphrase_detection",
    "paraphrasedetection": "paraphrase_detection",
    "text similarity": "text_similarity",
    "text-similarity": "text_similarity",
    "textsimilarity": "text_similarity",
    "text mining": "text_mining",
    "text-mining": "text_mining",
    "textmining": "text_mining",
    "document classification": "document_classification",
    "document-classification": "document_classification",
    "documentclassification": "document_classification",
    "topic detection and tracking": "topic_detection_and_tracking",
    "topic-detection-and-tracking": "topic_detection_and_tracking",
    "topicdetectionandtracking": "topic_detection_and_tracking",
    "tdt": "topic_detection_and_tracking",
    "information extraction and retrieval": "information_extraction_and_retrieval",
    "information-extraction-and-retrieval": "information_extraction_and_retrieval",
    "informationextractionandretrieval": "information_extraction_and_retrieval",
    "ie and ir": "information_extraction_and_retrieval",
    "ie & ir": "information_extraction_and_retrieval",
    "knowledge discovery": "knowledge_discovery",
    "knowledge-discovery": "knowledge_discovery",
    "knowledgediscovery": "knowledge_discovery",
    "data mining": "data_mining",
    "data-mining": "data_mining",
    "datamining": "data_mining",
    "text analytics": "text_analytics",
    "text-analytics": "text_analytics",
    "textanalytics": "text_analytics",
    "social media analysis": "social_media_analysis",
    "social-media-analysis": "social_media_analysis",
    "socialmediaanalysis": "social_media_analysis",
    "opinion mining": "sentiment_analysis",
    "opinion-mining": "sentiment_analysis",
    "opinionmining": "sentiment_analysis",
    "topic extraction": "topic_extraction",
    "topic-extraction": "topic_extraction",
    "topicextraction": "topic_extraction",
    "text classification": "text_classification",
    "text-classification": "text_classification",
    "textclassification": "text_classification",
    "language detection": "language_identification",
    "language-detection": "language_identification",
    "languagedetection": "language_identification",
    "language identification": "language_identification",
    "language-identification": "language_identification",
    "languagidentification": "language_identification",
    "speech to text": "speech_recognition",
    "speech-to-text": "speech_recognition",
    "speechtotext": "speech_recognition",
    "text to speech": "text_to_speech",
    "text-to-speech": "text_to_speech",
    "texttospeech": "text_to_speech",
    "machine translation": "machine_translation",
    "machine-translation": "machine_translation",
    "machinetranslation": "machine_translation",
    "mt": "machine_translation",
    "automatic summarization": "text_summarization",
    "automatic-summarization": "text_summarization",
    "automaticsummarization": "text_summarization",
    "automatic speech recognition": "speech_recognition",
    "automatic-speech-recognition": "speech_recognition",
    "automaticspeechrecognition": "speech_recognition",
    "language understanding": "natural_language_understanding",
    "language-understanding": "natural_language_understanding",
    "languageunderstanding": "natural_language_understanding",
    "natural language understanding": "natural_language_understanding",
    "natural-language-understanding": "natural_language_understanding",
    "naturallanguageunderstanding": "natural_language_understanding",
    "language generation": "natural_language_generation",
    "language-generation": "natural_language_generation",
    "languagegeneration": "natural_language_generation",
    "natural language generation": "natural_language_generation",
    "natural-language-generation": "natural_language_generation",
    "naturallanguagegeneration": "natural_language_generation",
    "dialog systems": "dialog_systems",
    "dialog-systems": "dialog_systems",
    "dialogsystems": "dialog_systems",
    "chatbots": "dialog_systems",
    "chat bots": "dialog_systems",
    "chat-bots": "dialog_systems",
    "chatbots": "dialog_systems",
    "conversational agents": "dialog_systems",
    "conversational-agent": "dialog_systems",
    "conversationalagents": "dialog_systems",
    "question answering": "question_answering",
    "question-answering": "question_answering",
    "questionanswering": "question_answering",
    "reading comprehension": "reading_comprehension",
    "reading-comprehension": "reading_comprehension",
    "readingcomprehension": "reading_comprehension",
    "knowledge graphs": "knowledge_graph",
    "knowledge-graphs": "knowledge_graph",
    "knowledgegraphs": "knowledge_graph",
    "semantic web": "semantic_web",
    "semantic-web": "semantic_web",
    "semanticweb": "semantic_web",
    "linked data": "linked_data",
    "linked-data": "linked_data",
    "linkeddata": "linked_data",
    "ontology": "ontology",
    "ontologies": "ontology",
    "natural language processing": "natural_language_processing",
    "natural-language-processing": "natural_language_processing",
    "naturallanguageprocessing": "natural_language_processing",
    "nlp": "natural_language_processing",
    "natural language toolkit": "nltk",
    "natural-language-toolkit": "nltk",
    "naturallanguagetoolkit": "nltk",
    "nltk": "nltk",
    "spacy": "spacy",
    "stanford nlp": "stanford_nlp",
    "stanford-nlp": "stanford_nlp",
    "stanfordnlp": "stanford_nlp",
    "gensim": "gensim",
    "fasttext": "fasttext",
    "word2vec": "word2vec",
    "glove": "glove",
    "bert": "bert",
    "gpt": "gpt",
    "transformer": "transformer",
    "transformers": "transformer",
    "attention": "attention",
    "self attention": "self_attention",
    "self-attention": "self_attention",
    "selfattention": "self_attention",
    "positional encoding": "positional_encoding",
    "positional-encoding": "positional_encoding",
    "positionalencoding": "positional_encoding",
    "tokenization": "tokenization",
    "tokenize": "tokenization",
    "tokenizer": "tokenization",
    "tokeniser": "tokenization",
    "embedding": "embedding",
    "embeddings": "embedding",
    "word embedding": "embedding",
    "word embeddings": "embedding",
    "language model": "language_model",
    "language-model": "language_model",
    "languagemodel": "language_model",
    "lm": "language_model",
    "l.m.": "language_model",
    "pretraining": "pretraining",
    "fine tuning": "fine_tuning",
    "fine-tuning": "fine_tuning",
    "finetuning": "fine_tuning",
    "zero shot learning": "zero_shot_learning",
    "zero-shot learning": "zero_shot_learning",
    "zero-shot-learning": "zero_shot_learning",
    "zero shot": "zero_shot_learning",
    "zero-shot": "zero_shot_learning",
    "transfer learning": "transfer_learning",
    "transfer-learning": "transfer_learning",
    "transferlearning": "transfer_learning",
    "few shot learning": "few_shot_learning",
    "few-shot learning": "few_shot_learning",
    "few-shot-learning": "few_shot_learning",
    "few shot": "few_shot_learning",
    "few-shot": "few_shot_learning",
    "multi task learning": "multi_task_learning",
    "multi-task learning": "multi_task_learning",
    "multi-task-learning": "multi_task_learning",
    "multitask learning": "multi_task_learning",
    "multitask-learning": "multi_task_learning",
    "multitasklearning": "multi_task_learning",
    "continual learning": "continual_learning",
    "continual-learning": "continual_learning",
    "continuallearning": "continual_learning",
    "lifelong learning": "continual_learning",
    "lifelong-learning": "continual_learning",
    "lifelonglearning": "continual_learning",
    "meta learning": "meta_learning",
    "meta-learning": "meta_learning",
    "metalearning": "meta_learning",
    "autoencoder": "autoencoder",
    "auto encoder": "autoencoder",
    "auto-encoder": "autoencoder",
    "variational autoencoder": "variational_autoencoder",
    "variational-autoencoder": "variational_autoencoder",
    "variationalautoencoder": "variational_autoencoder",
    "vae": "variational_autoencoder",
    "generative model": "generative_model",
    "generative-model": "generative_model",
    "generativemodel": "generative_model",
    "latent variable model": "latent_variable_model",
    "latent-variable-model": "latent_variable_model",
    "latentvariablemodel": "latent_variable_model",
    "bayesian network": "bayesian_network",
    "bayesian-network": "bayesian_network",
    "bayesiannetwork": "bayesian_network",
    "markov chain": "markov_chain",
    "markov-chain": "markov_chain",
    "markovchain": "markov_chain",
    "hidden markov model": "hidden_markov_model",
    "hidden-markov-model": "hidden_markov_model",
    "hiddenmarkovmodel": "hidden_markov_model",
    "hmm": "hidden_markov_model",
    "graph neural network": "graph_neural_network",
    "graph-neural-network": "graph_neural_network",
    "graphneuralnetwork": "graph_neural_network",
    "gnn": "graph_neural_network",
    "graph convolutional network": "graph_convolutional_network",
    "graph-convolutional-network": "graph_convolutional_network",
    "graphconvolutionalnetwork": "graph_convolutional_network",
    "gcn": "graph_convolutional_network",
    "knowledge graph embedding": "knowledge_graph_embedding",
    "knowledge-graph-embedding": "knowledge_graph_embedding",
    "knowledgegraphembedding": "knowledge_graph_embedding",
    "kge": "knowledge_graph_embedding",
    "embedding learning": "embedding_learning",
    "embedding-learning": "embedding_learning",
    "embeddinglearning": "embedding_learning",
    "contrastive learning": "contrastive_learning",
    "contrastive-learning": "contrastive_learning",
    "contrastivelearning": "contrastive_learning",
    "self supervised learning": "self_supervised_learning",
    "self-supervised learning": "self_supervised_learning",
    "self-supervised-learning": "self_supervised_learning",
    "selfsupervisedlearning": "self_supervised_learning",
    "unsupervised pretraining": "unsupervised_pretraining",
    "unsupervised-pretraining": "unsupervised_pretraining",
    "unsupervisedpretraining": "unsupervised_pretraining",
    "data labeling": "data_labeling",
    "data-labeling": "data_labeling",
    "datalabeling": "data_labeling",
    "annotation": "data_labeling",
    "crowdsourcing": "crowdsourcing",
    "crowd sourcing": "crowdsourcing",
    "crowd-sourcing": "crowdsourcing",
    "active learning": "active_learning",
    "active-learning": "active_learning",
    "activelearning": "active_learning",
    "curriculum learning": "curriculum_learning",
    "curriculum-learning": "curriculum_learning",
    "curriculumlearning": "curriculum_learning",
    "neural architecture search": "neural_architecture_search",
    "neural-architecture-search": "neural_architecture_search",
    "neuralarchitecturesearch": "neural_architecture_search",
    "nas": "neural_architecture_search",
    "automl": "automl",
    "auto ml": "automl",
    "auto-ml": "automl",
    "hyperparameter optimization": "hyperparameter_optimization",
    "hyperparameter-optimization": "hyperparameter_optimization",
    "hyperparameteroptimization": "hyperparameter_optimization",
    "model selection": "model_selection",
    "model-selection": "model_selection",
    "modelselection": "model_selection",
    "cross domain learning": "cross_domain_learning",
    "cross-domain learning": "cross_domain_learning",
    "cross-domain-learning": "cross_domain_learning",
    "crossdomainlearning": "cross_domain_learning",
    "domain adaptation": "domain_adaptation",
    "domain-adaptation": "domain_adaptation",
    "domainadaptation": "domain_adaptation",
    "multi modal learning": "multimodal_learning",
    "multi-modal learning": "multimodal_learning",
    "multi-modal-learning": "multimodal_learning",
    "multimodallearning": "multimodal_learning",
    "multilingual learning": "multilingual_learning",
    "multilingual-learning": "multilingual_learning",
    "multilinguallearning": "multilingual_learning",
    "zero resource learning": "zero_resource_learning",
    "zero-resource learning": "zero_resource_learning",
    "zero-resource-learning": "zero_resource_learning",
    "zeroresourcelearning": "zero_resource_learning",
    "language acquisition": "language_acquisition",
    "language-acquisition": "language_acquisition",
    "languageacquisition": "language_acquisition",
    "speech processing": "speech_processing",
    "speech-processing": "speech_processing",
    "speechprocessing": "speech_processing",
    "phonetics": "phonetics",
    "phonology": "phonology",
    "morphology": "morphology",
    "syntax": "syntax",
    "semantics": "semantics",
    "pragmatics": "pragmatics",
    "discourse": "discourse",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    m = hashlib.sha256()
    # Sort items to ensure consistent hash
    for key in sorted(SEMANTIC_MAP.keys()):
        value = SEMANTIC_MAP[key]
        m.update(key.encode('utf-8'))
        m.update(b'\0')
        m.update(value.encode('utf-8'))
        m.update(b'\0')
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> dict:
    current_count = len(SEMANTIC_MAP)
    current_hash = _compute_map_hash()
    is_valid = (current_count == _EXPECTED_ENTRY_COUNT) and (current_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": current_count,
        "expected_entries": _EXPECTED_ENTRY_COUNT,
        "hash": current_hash,
        "expected_hash": _MAP_INTEGRITY_HASH,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    if not isinstance(term, str):
        raise TypeError("term must be a string")
    key = term.strip().lower()
    return SEMANTIC_MAP.get(key, key)

def get_related_terms(term: str) -> list[str]:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return sorted(set(related))

def get_all_mappings() -> dict:
    return SEMANTIC_MAP.copy()