import hashlib
import re
from collections import defaultdict

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AUTO10 Team"
SEMANTIC_MAP_ENGINE = "AUTO10_autonomous_driving"

SEMANTIC_MAP = {
    # SAE J3016 Levels
    "sae j3016": "sae_j3016",
    "sae j3016 levels": "sae_j3016_levels",
    "level 0": "automation_level_0",
    "level 1": "automation_level_1",
    "level 2": "automation_level_2",
    "level 3": "automation_level_3",
    "level 4": "automation_level_4",
    "level 5": "automation_level_5",
    "no automation": "automation_level_0",
    "manual driving": "automation_level_0",
    "driver assistance": "automation_level_1",
    "partial automation": "automation_level_2",
    "conditional automation": "automation_level_3",
    "high automation": "automation_level_4",
    "full automation": "automation_level_5",
    "autonomous driving": "automation_level_5",
    "self-driving": "automation_level_5",
    "autopilot": "automation_level_5",
    "automated driving": "automation_level_5",
    "robotaxi": "automation_level_5",
    "driverless": "automation_level_5",
    "ad": "automation_level_5",
    "ads": "automation_level_5",
    "automated driving system": "automation_level_5",
    "ads system": "automation_level_5",
    "auto10": "automation_level_5",

    # LiDAR Point Cloud Processing and SLAM
    "lidar": "lidar",
    "lidar sensor": "lidar",
    "lidar point cloud": "lidar_point_cloud",
    "point cloud": "lidar_point_cloud",
    "pointcloud": "lidar_point_cloud",
    "lidar processing": "lidar_processing",
    "point cloud processing": "lidar_processing",
    "slam": "slam",
    "simultaneous localization and mapping": "slam",
    "graph slam": "graph_slam",
    "ekf slam": "ekf_slam",
    "fast slam": "fast_slam",
    "loop closure": "slam_loop_closure",
    "feature extraction": "feature_extraction",
    "feature matching": "feature_matching",
    "scan matching": "scan_matching",
    "occupancy grid": "occupancy_grid",
    "octomap": "octomap",
    "voxel grid": "voxel_grid",
    "segmentation": "segmentation",
    "clustering": "clustering",
    "ground removal": "ground_removal",
    "outlier removal": "outlier_removal",
    "normal estimation": "normal_estimation",
    "registration": "registration",
    "icp": "iterative_closest_point",
    "iterative closest point": "iterative_closest_point",
    "ndt": "normal_distributions_transform",
    "normal distributions transform": "normal_distributions_transform",
    "pcl": "point_cloud_library",
    "point cloud library": "point_cloud_library",
    "velodyne": "velodyne",
    "hesai": "hesai",
    "ouster": "ouster",
    "robosense": "robosense",
    "rslidar": "robosense",
    "lidar calibration": "lidar_calibration",
    "lidar fusion": "lidar_fusion",

    # Camera Vision CNN Object Detection (YOLO)
    "camera": "camera",
    "camera sensor": "camera",
    "rgb camera": "camera",
    "mono camera": "camera",
    "stereo camera": "stereo_camera",
    "fisheye camera": "fisheye_camera",
    "vision": "camera_vision",
    "computer vision": "camera_vision",
    "cv": "camera_vision",
    "cnn": "convolutional_neural_network",
    "convolutional neural network": "convolutional_neural_network",
    "object detection": "object_detection",
    "yolo": "yolo",
    "yolov3": "yolo",
    "yolov4": "yolo",
    "yolov5": "yolo",
    "yolov7": "yolo",
    "ssd": "single_shot_detector",
    "single shot detector": "single_shot_detector",
    "rcnn": "region_cnn",
    "region cnn": "region_cnn",
    "faster rcnn": "faster_region_cnn",
    "mask rcnn": "mask_region_cnn",
    "semantic segmentation": "semantic_segmentation",
    "instance segmentation": "instance_segmentation",
    "lane detection": "lane_detection",
    "road detection": "road_detection",
    "traffic sign detection": "traffic_sign_detection",
    "traffic light detection": "traffic_light_detection",
    "pedestrian detection": "pedestrian_detection",
    "vehicle detection": "vehicle_detection",
    "cyclist detection": "cyclist_detection",
    "image classification": "image_classification",
    "image recognition": "image_classification",
    "camera calibration": "camera_calibration",
    "camera fusion": "camera_fusion",
    "opencv": "opencv",
    "open cv": "opencv",
    "deep learning": "deep_learning",
    "neural network": "neural_network",
    "ml": "machine_learning",
    "machine learning": "machine_learning",

    # Radar Millimeter Wave Doppler Velocity
    "radar": "radar",
    "radar sensor": "radar",
    "mmwave": "millimeter_wave_radar",
    "millimeter wave radar": "millimeter_wave_radar",
    "doppler radar": "doppler_radar",
    "doppler velocity": "doppler_velocity",
    "radar processing": "radar_processing",
    "radar fusion": "radar_fusion",
    "radar calibration": "radar_calibration",
    "range rate": "doppler_velocity",
    "range measurement": "radar_range",
    "velocity measurement": "doppler_velocity",
    "azimuth": "radar_azimuth",
    "elevation": "radar_elevation",
    "radar cross section": "radar_cross_section",
    "rcs": "radar_cross_section",
    "radar tracking": "radar_tracking",
    "radar clustering": "radar_clustering",
    "radar segmentation": "radar_segmentation",
    "radar object detection": "radar_object_detection",

    # Sensor Fusion: Kalman, Extended, Unscented
    "sensor fusion": "sensor_fusion",
    "fusion": "sensor_fusion",
    "multi-sensor fusion": "sensor_fusion",
    "data fusion": "sensor_fusion",
    "kalman filter": "kalman_filter",
    "kf": "kalman_filter",
    "ekf": "extended_kalman_filter",
    "extended kalman filter": "extended_kalman_filter",
    "ukf": "unscented_kalman_filter",
    "unscented kalman filter": "unscented_kalman_filter",
    "particle filter": "particle_filter",
    "pf": "particle_filter",
    "bayesian filter": "bayesian_filter",
    "multi-object fusion": "multi_object_fusion",
    "track-to-track fusion": "track_to_track_fusion",
    "measurement fusion": "measurement_fusion",
    "state estimation": "state_estimation",
    "covariance": "covariance",
    "innovation": "innovation",
    "prediction": "prediction",
    "update": "update",
    "sensor registration": "sensor_registration",
    "sensor alignment": "sensor_alignment",
    "sensor calibration": "sensor_calibration",
    "time synchronization": "time_synchronization",
    "timestamp alignment": "time_synchronization",

    # Perception Object Tracking: Multi-Object
    "perception": "perception",
    "object tracking": "object_tracking",
    "multi-object tracking": "multi_object_tracking",
    "mot": "multi_object_tracking",
    "multi target tracking": "multi_object_tracking",
    "target tracking": "object_tracking",
    "tracking": "object_tracking",
    "track management": "track_management",
    "track initiation": "track_initiation",
    "track termination": "track_termination",
    "track confirmation": "track_confirmation",
    "track association": "track_association",
    "data association": "data_association",
    "nearest neighbor": "nearest_neighbor",
    "joint probabilistic data association": "jpda",
    "jpda": "jpda",
    "mht": "multiple_hypothesis_tracking",
    "multiple hypothesis tracking": "multiple_hypothesis_tracking",
    "gating": "gating",
    "kalman tracking": "kalman_filter",
    "extended kalman tracking": "extended_kalman_filter",
    "unscented kalman tracking": "unscented_kalman_filter",
    "particle tracking": "particle_filter",
    "track fusion": "track_to_track_fusion",
    "object classification": "object_classification",
    "object recognition": "object_classification",
    "object localization": "object_localization",
    "object identification": "object_classification",

    # Path Planning: A-star, RRT
    "path planning": "path_planning",
    "route planning": "path_planning",
    "trajectory planning": "trajectory_planning",
    "motion planning": "motion_planning",
    "astar": "a_star",
    "a-star": "a_star",
    "a star": "a_star",
    "rrt": "rapidly_exploring_random_tree",
    "rapidly exploring random tree": "rapidly_exploring_random_tree",
    "rrt*": "rrt_star",
    "rrt star": "rrt_star",
    "dijkstra": "dijkstra",
    "dijkstra's algorithm": "dijkstra",
    "graph search": "graph_search",
    "grid search": "grid_search",
    "dynamic programming": "dynamic_programming",
    "prm": "probabilistic_roadmap",
    "probabilistic roadmap": "probabilistic_roadmap",
    "waypoint planning": "waypoint_planning",
    "lane planning": "lane_planning",
    "lane change planning": "lane_change_planning",
    "behavior planning": "behavior_planning",
    "decision making": "decision_making",
    "maneuver planning": "maneuver_planning",
    "obstacle avoidance": "obstacle_avoidance",
    "collision avoidance": "collision_avoidance",
    "cost function": "cost_function",
    "heuristic": "heuristic",
    "search space": "search_space",
    "planning horizon": "planning_horizon",
    "planning": "path_planning",

    # Motion Planning: Trajectory Optimization
    "trajectory optimization": "trajectory_optimization",
    "trajectory generation": "trajectory_generation",
    "trajectory tracking": "trajectory_tracking",
    "trajectory following": "trajectory_tracking",
    "trajectory smoothing": "trajectory_smoothing",
    "trajectory interpolation": "trajectory_interpolation",
    "trajectory prediction": "trajectory_prediction",
    "motion prediction": "trajectory_prediction",
    "motion control": "motion_control",
    "kinematic model": "kinematic_model",
    "dynamic model": "dynamic_model",
    "vehicle model": "vehicle_model",
    "bicycle model": "bicycle_model",
    "kinematic bicycle model": "bicycle_model",
    "dynamic bicycle model": "bicycle_model",
    "curvature": "curvature",
    "velocity profile": "velocity_profile",
    "acceleration profile": "acceleration_profile",
    "jerk minimization": "jerk_minimization",
    "minimum jerk": "jerk_minimization",
    "minimum snap": "snap_minimization",
    "snap minimization": "snap_minimization",
    "qp": "quadratic_programming",
    "quadratic programming": "quadratic_programming",
    "optimization": "optimization",
    "constraint": "constraint",
    "feasibility": "feasibility",
    "reference trajectory": "reference_trajectory",
    "path following": "trajectory_tracking",
    "path tracking": "trajectory_tracking",

    # Control: PID, MPC Model Predictive
    "control": "control",
    "vehicle control": "vehicle_control",
    "longitudinal control": "longitudinal_control",
    "lateral control": "lateral_control",
    "pid": "pid_controller",
    "pid controller": "pid_controller",
    "proportional integral derivative": "pid_controller",
    "mpc": "model_predictive_control",
    "model predictive control": "model_predictive_control",
    "adaptive control": "adaptive_control",
    "feedforward control": "feedforward_control",
    "feedback control": "feedback_control",
    "open loop control": "open_loop_control",
    "closed loop control": "closed_loop_control",
    "gain scheduling": "gain_scheduling",
    "state feedback": "state_feedback",
    "input-output control": "input_output_control",
    "actuator control": "actuator_control",
    "steering control": "steering_control",
    "throttle control": "throttle_control",
    "brake control": "brake_control",
    "acceleration control": "acceleration_control",
    "deceleration control": "deceleration_control",
    "yaw control": "yaw_control",
    "torque control": "torque_control",
    "wheel control": "wheel_control",
    "control law": "control_law",
    "controller": "controller",

    # V2X Vehicle-to-Everything Communication: DSRC, C-V2X
    "v2x": "vehicle_to_everything",
    "vehicle to everything": "vehicle_to_everything",
    "vehicle-to-everything": "vehicle_to_everything",
    "vehicle2x": "vehicle_to_everything",
    "dsrc": "dsrc",
    "dedicated short range communication": "dsrc",
    "c-v2x": "cellular_v2x",
    "cv2x": "cellular_v2x",
    "cellular v2x": "cellular_v2x",
    "lte-v": "cellular_v2x",
    "lte v": "cellular_v2x",
    "5g v2x": "5g_v2x",
    "5g-v2x": "5g_v2x",
    "v2v": "vehicle_to_vehicle",
    "vehicle to vehicle": "vehicle_to_vehicle",
    "vehicle-to-vehicle": "vehicle_to_vehicle",
    "v2i": "vehicle_to_infrastructure",
    "vehicle to infrastructure": "vehicle_to_infrastructure",
    "vehicle-to-infrastructure": "vehicle_to_infrastructure",
    "v2p": "vehicle_to_pedestrian",
    "vehicle to pedestrian": "vehicle_to_pedestrian",
    "vehicle-to-pedestrian": "vehicle_to_pedestrian",
    "v2n": "vehicle_to_network",
    "vehicle to network": "vehicle_to_network",
    "vehicle-to-network": "vehicle_to_network",
    "v2cloud": "vehicle_to_cloud",
    "vehicle to cloud": "vehicle_to_cloud",
    "vehicle-to-cloud": "vehicle_to_cloud",
    "v2x communication": "vehicle_to_everything_communication",
    "cooperative perception": "cooperative_perception",
    "cooperative driving": "cooperative_driving",
    "cooperative vehicle": "cooperative_vehicle",
    "connected vehicle": "connected_vehicle",
    "cv": "connected_vehicle",
    "roadside unit": "roadside_unit",
    "rsu": "roadside_unit",
    "onboard unit": "onboard_unit",
    "obu": "onboard_unit",
    "message": "v2x_message",
    "cam": "cooperative_awareness_message",
    "cooperative awareness message": "cooperative_awareness_message",
    "denm": "decentralized_environment_notification_message",
    "decentralized environment notification message": "decentralized_environment_notification_message",
    "bsm": "basic_safety_message",
    "basic safety message": "basic_safety_message",
    "spat": "signal_phase_and_timing",
    "signal phase and timing": "signal_phase_and_timing",
    "map message": "map_message",
    "v2x security": "v2x_security",
    "v2x authentication": "v2x_authentication",

    # HD Mapping Localization Lane-Level
    "hd map": "hd_map",
    "hd mapping": "hd_map",
    "high definition map": "hd_map",
    "high-def map": "hd_map",
    "hdmaps": "hd_map",
    "map": "map",
    "mapping": "mapping",
    "lane-level map": "lane_level_map",
    "lane level map": "lane_level_map",
    "lane map": "lane_level_map",
    "lane marking": "lane_marking",
    "lane boundary": "lane_boundary",
    "lane centerline": "lane_centerline",
    "lane localization": "lane_localization",
    "localization": "localization",
    "pose estimation": "pose_estimation",
    "position estimation": "pose_estimation",
    "gps": "gps",
    "global positioning system": "gps",
    "gnss": "gnss",
    "global navigation satellite system": "gnss",
    "rtk": "real_time_kinematic",
    "real time kinematic": "real_time_kinematic",
    "imu": "imu",
    "inertial measurement unit": "imu",
    "odometry": "odometry",
    "wheel odometry": "wheel_odometry",
    "visual odometry": "visual_odometry",
    "lidar odometry": "lidar_odometry",
    "map matching": "map_matching",
    "map registration": "map_registration",
    "map update": "map_update",
    "map fusion": "map_fusion",
    "map accuracy": "map_accuracy",
    "map precision": "map_accuracy",
    "map resolution": "map_resolution",
    "map layer": "map_layer",
    "semantic map": "semantic_map",
    "topological map": "topological_map",
    "metric map": "metric_map",
    "feature map": "feature_map",
    "road network": "road_network",
    "road graph": "road_network",
    "road geometry": "road_geometry",
    "road attribute": "road_attribute",
    "traffic sign map": "traffic_sign_map",
    "traffic light map": "traffic_light_map",
    "stop line": "stop_line",
    "crosswalk": "crosswalk",
    "intersection": "intersection",
    "junction": "intersection",
    "turn lane": "turn_lane",
    "merge lane": "merge_lane",
    "exit lane": "exit_lane",
    "parking lot map": "parking_lot_map",
    "parking space": "parking_space",
    "parking slot": "parking_space",
    "parking localization": "parking_localization",

    # Operational Design Domain (ODD)
    "odd": "operational_design_domain",
    "operational design domain": "operational_design_domain",
    "operational domain": "operational_design_domain",
    "design domain": "operational_design_domain",
    "operation domain": "operational_design_domain",
    "use case": "use_case",
    "scenario": "scenario",
    "scenario-based": "scenario_based",
    "scenario based": "scenario_based",
    "edge case": "edge_case",
    "corner case": "corner_case",
    "edge-case": "edge_case",
    "corner-case": "corner_case",
    "test case": "test_case",
    "test scenario": "test_scenario",
    "test coverage": "test_coverage",
    "test plan": "test_plan",
    "test execution": "test_execution",
    "test result": "test_result",
    "validation": "validation",
    "verification": "verification",
    "acceptance criteria": "acceptance_criteria",
    "requirement": "requirement",
    "requirements": "requirement",
    "functional requirement": "functional_requirement",
    "non-functional requirement": "non_functional_requirement",
    "performance requirement": "performance_requirement",
    "safety requirement": "safety_requirement",
    "security requirement": "security_requirement",

    # Functional Safety: ISO 26262 ASIL
    "iso 26262": "iso_26262",
    "functional safety": "functional_safety",
    "asil": "automotive_safety_integrity_level",
    "automotive safety integrity level": "automotive_safety_integrity_level",
    "asil a": "asil_a",
    "asil b": "asil_b",
    "asil c": "asil_c",
    "asil d": "asil_d",
    "hazard analysis": "hazard_analysis",
    "risk assessment": "risk_assessment",
    "hazard": "hazard",
    "risk": "risk",
    "fault": "fault",
    "failure": "failure",
    "fault tree analysis": "fault_tree_analysis",
    "fta": "fault_tree_analysis",
    "failure mode and effects analysis": "fmea",
    "fmea": "fmea",
    "fault injection": "fault_injection",
    "safety case": "safety_case",
    "safety argument": "safety_case",
    "safety validation": "safety_validation",
    "safety verification": "safety_verification",
    "safety goal": "safety_goal",
    "safety concept": "safety_concept",
    "safety mechanism": "safety_mechanism",
    "safety function": "safety_function",
    "safety feature": "safety_function",
    "safety monitor": "safety_monitor",
    "monitoring": "monitoring",
    "diagnostics": "diagnostics",
    "diagnostic": "diagnostics",
    "redundancy": "redundancy",
    "fail-operational": "fail_operational",
    "fail operational": "fail_operational",
    "fail-safe": "fail_safe",
    "fail safe": "fail_safe",
    "fault tolerant": "fault_tolerant",
    "fault tolerance": "fault_tolerant",
    "safe state": "safe_state",
    "safe stop": "safe_stop",
    "safe fallback": "safe_fallback",
    "fallback": "safe_fallback",
    "degraded mode": "degraded_mode",
    "degradation": "degraded_mode",

    # SOTIF: ISO 21448 Safety of Intended Functionality
    "iso 21448": "iso_21448",
    "sotif": "safety_of_intended_functionality",
    "safety of intended functionality": "safety_of_intended_functionality",
    "intended functionality": "intended_functionality",
    "functional safety": "functional_safety",
    "unintended functionality": "unintended_functionality",
    "performance limitation": "performance_limitation",
    "sensor limitation": "sensor_limitation",
    "environmental limitation": "environmental_limitation",
    "design limitation": "design_limitation",
    "system limitation": "system_limitation",
    "unsafe behavior": "unsafe_behavior",
    "misuse": "misuse",
    "misbehavior": "misbehavior",
    "misinterpretation": "misinterpretation",
    "sensor error": "sensor_error",
    "software error": "software_error",
    "hardware error": "hardware_error",
    "system error": "system_error",
    "false positive": "false_positive",
    "false negative": "false_negative",
    "false alarm": "false_positive",
    "missed detection": "false_negative",
    "unexpected behavior": "unexpected_behavior",
    "unexpected scenario": "unexpected_scenario",

    # Cybersecurity: ISO SAE 21434
    "iso sae 21434": "iso_sae_21434",
    "iso 21434": "iso_sae_21434",
    "cybersecurity": "cybersecurity",
    "cyber security": "cybersecurity",
    "security": "security",
    "information security": "information_security",
    "vehicle cybersecurity": "vehicle_cybersecurity",
    "v2x security": "v2x_security",
    "v2x authentication": "v2x_authentication",
    "threat": "threat",
    "vulnerability": "vulnerability",
    "attack": "attack",
    "attack surface": "attack_surface",
    "penetration testing": "penetration_testing",
    "pen test": "penetration_testing",
    "security testing": "security_testing",
    "security validation": "security_validation",
    "security verification": "security_verification",
    "security monitor": "security_monitor",
    "security mechanism": "security_mechanism",
    "security feature": "security_feature",
    "security function": "security_feature",
    "security case": "security_case",
    "security argument": "security_case",
    "security goal": "security_goal",
    "security concept": "security_concept",
    "security requirement": "security_requirement",
    "security risk": "security_risk",
    "risk management": "risk_management",
    "risk mitigation": "risk_mitigation",
    "risk control": "risk_control",
    "risk assessment": "risk_assessment",
    "risk analysis": "risk_analysis",
    "cryptography": "cryptography",
    "encryption": "encryption",
    "authentication": "authentication",
    "authorization": "authorization",
    "access control": "access_control",
    "firewall": "firewall",
    "intrusion detection": "intrusion_detection",
    "intrusion prevention": "intrusion_prevention",
    "secure boot": "secure_boot",
    "secure communication": "secure_communication",
    "secure update": "secure_update",
    "secure storage": "secure_storage",
    "secure element": "secure_element",
    "secure enclave": "secure_enclave",

    # Simulation Testing: Scenario-Based, Edge Case and Corner Case Handling
    "simulation": "simulation",
    "simulator": "simulation",
    "simulation testing": "simulation_testing",
    "scenario-based testing": "scenario_based_testing",
    "scenario based testing": "scenario_based_testing",
    "edge case testing": "edge_case_testing",
    "corner case testing": "corner_case_testing",
    "test bench": "test_bench",
    "testbed": "test_bench",
    "hardware in the loop": "hil",
    "hil": "hil",
    "software in the loop": "sil",
    "sil": "sil",
    "model in the loop": "mil",
    "mil": "mil",
    "virtual testing": "virtual_testing",
    "virtual validation": "virtual_validation",
    "virtual verification": "virtual_verification",
    "real world testing": "real_world_testing",
    "field testing": "real_world_testing",
    "track testing": "track_testing",
    "test track": "track_testing",
    "test drive": "test_drive",
    "test vehicle": "test_vehicle",
    "test fleet": "test_fleet",
    "test driver": "test_driver",
    "test engineer": "test_engineer",
    "test manager": "test_manager",
    "test report": "test_report",
    "test documentation": "test_documentation",
    "test artifact": "test_artifact",
    "test evidence": "test_evidence",
    "test log": "test_log",
    "test result": "test_result",
    "test data": "test_data",
    "test input": "test_input",
    "test output": "test_output",
    "test metric": "test_metric",
    "test measurement": "test_metric",
    "test analysis": "test_analysis",
    "test review": "test_review",

    # Redundancy and Fail-Operational Architecture
    "redundancy": "redundancy",
    "redundant": "redundancy",
    "fail-operational": "fail_operational",
    "fail operational": "fail_operational",
    "fail-safe": "fail_safe",
    "fail safe": "fail_safe",
    "failover": "failover",
    "backup": "backup",
    "hot standby": "hot_standby",
    "cold standby": "cold_standby",
    "standby": "standby",
    "switchover": "switchover",
    "recovery": "recovery",
    "reconfiguration": "reconfiguration",
    "degraded mode": "degraded_mode",
    "degradation": "degraded_mode",
    "safe state": "safe_state",
    "safe stop": "safe_stop",
    "safe fallback": "safe_fallback",
    "fallback": "safe_fallback",
    "fault tolerant": "fault_tolerant",
    "fault tolerance": "fault_tolerant",
    "fault detection": "fault_detection",
    "fault isolation": "fault_isolation",
    "fault diagnosis": "fault_diagnosis",
    "fault recovery": "fault_recovery",
    "fault management": "fault_management",
    "fault injection": "fault_injection",
    "fault monitor": "fault_monitor",
    "fault handler": "fault_handler",
    "fault mitigation": "fault_mitigation",
    "fault prevention": "fault_prevention",
    "fault prediction": "fault_prediction",
    "fault avoidance": "fault_avoidance",

    # Ethical Decision Making: Trolley Problem
    "ethics": "ethics",
    "ethical": "ethics",
    "ethical decision": "ethical_decision",
    "ethical decision making": "ethical_decision_making",
    "trolley problem": "trolley_problem",
    "moral dilemma": "trolley_problem",
    "dilemma": "trolley_problem",
    "value alignment": "value_alignment",
    "value": "value_alignment",
    "fairness": "fairness",
    "bias": "bias",
    "discrimination": "discrimination",
    "responsibility": "responsibility",
    "accountability": "accountability",
    "transparency": "transparency",
    "explainability": "explainability",
    "interpretability": "explainability",
    "trust": "trust",
    "trustworthiness": "trust",
    "safety": "safety",
    "security": "security",
    "privacy": "privacy",
    "data privacy": "privacy",
    "data protection": "privacy",
    "data security": "privacy",
    "user privacy": "privacy",
    "user protection": "privacy",
    "user safety": "safety",

    # Regulatory Framework: NHTSA, UNECE WP.29
    "regulation": "regulation",
    "regulatory": "regulation",
    "regulatory framework": "regulatory_framework",
    "legal": "regulation",
    "law": "regulation",
    "compliance": "compliance",
    "standard": "standard",
    "standards": "standard",
    "nhtsa": "nhtsa",
    "national highway traffic safety administration": "nhtsa",
    "unece": "unece",
    "un ece": "unece",
    "wp.29": "unece_wp29",
    "wp29": "unece_wp29",
    "unece wp.29": "unece_wp29",
    "unece wp29": "unece_wp29",
    "type approval": "type_approval",
    "certification": "certification",
    "approval": "type_approval",
    "audit": "audit",
    "inspection": "inspection",
    "assessment": "assessment",
    "evaluation": "evaluation",
    "review": "review",
    "reporting": "reporting",
    "documentation": "documentation",
    "record keeping": "documentation",
    "traceability": "traceability",
    "process": "process",
    "procedure": "procedure",
    "guideline": "guideline",
    "policy": "policy",
    "regulatory requirement": "regulatory_requirement",
    "legal requirement": "regulatory_requirement",
    "standard requirement": "regulatory_requirement",
    "regulatory compliance": "regulatory_compliance",
    "legal compliance": "regulatory_compliance",
    "standard compliance": "regulatory_compliance",
    "regulatory risk": "regulatory_risk",
    "legal risk": "regulatory_risk",
    "standard risk": "regulatory_risk",
    "regulatory assessment": "regulatory_assessment",
    "legal assessment": "regulatory_assessment",
    "standard assessment": "regulatory_assessment",
    "regulatory audit": "regulatory_audit",
    "legal audit": "regulatory_audit",
    "standard audit": "regulatory_audit",
    "regulatory certification": "regulatory_certification",
    "legal certification": "regulatory_certification",
    "standard certification": "regulatory_certification",
    "regulatory approval": "regulatory_approval",
    "legal approval": "regulatory_approval",
    "standard approval": "regulatory_approval",
    "regulatory reporting": "regulatory_reporting",
    "legal reporting": "regulatory_reporting",
    "standard reporting": "regulatory_reporting",
    "regulatory documentation": "regulatory_documentation",
    "legal documentation": "regulatory_documentation",
    "standard documentation": "regulatory_documentation",
    "regulatory traceability": "regulatory_traceability",
    "legal traceability": "regulatory_traceability",
    "standard traceability": "regulatory_traceability",
    "regulatory guideline": "regulatory_guideline",
    "legal guideline": "regulatory_guideline",
    "standard guideline": "regulatory_guideline",
    "regulatory policy": "regulatory_policy",
    "legal policy": "regulatory_policy",
    "standard policy": "regulatory_policy",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    concat = "".join(f"{k}:{v}" for k, v in items)
    concat += SEMANTIC_MAP_VERSION + SEMANTIC_MAP_AUTHOR + SEMANTIC_MAP_ENGINE
    return hashlib.sha256(concat.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    hash_now = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (hash_now == _MAP_INTEGRITY_HASH)
    return {
        "status": "OK" if is_valid else "ERROR",
        "entries": actual_count,
        "hash": hash_now,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"[\s\-]+", " ", t)
    t = t.replace(".", "")
    t = t.replace(",", "")
    t = t.replace("_", " ")
    t = re.sub(r" +", " ", t)
    t = t.strip()
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try removing plural 's'
    if t.endswith("s") and t[:-1] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-1]]
    # Try removing 'ing'
    if t.endswith("ing") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    # Try removing 'ed'
    if t.endswith("ed") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing 'es'
    if t.endswith("es") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing 'er'
    if t.endswith("er") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing 'ly'
    if t.endswith("ly") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing 'ment'
    if t.endswith("ment") and t[:-4] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-4]]
    # Try removing 'ion'
    if t.endswith("ion") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    # Try removing 'al'
    if t.endswith("al") and t[:-2] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-2]]
    # Try removing 'ity'
    if t.endswith("ity") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    # Try removing 'ness'
    if t.endswith("ness") and t[:-4] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-4]]
    # Try removing 'ous'
    if t.endswith("ous") and t[:-3] in SEMANTIC_MAP:
        return SEMANTIC_MAP[t[:-3]]
    return t

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == normalized and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)

# Build reverse mapping for related terms
_REVERSE_MAP = defaultdict(list)
for k, v in SEMANTIC_MAP.items():
    _REVERSE_MAP[v].append(k)

# Add synonyms for normalized forms
for v, keys in _REVERSE_MAP.items():
    for k in keys:
        if k not in SEMANTIC_MAP:
            SEMANTIC_MAP[k] = v