import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "MATH03 Team"
SEMANTIC_MAP_ENGINE = "MATH03_calculus"

SEMANTIC_MAP = {
    # Calculus core concepts
    "derivative": "derivative",
    "differentiation": "derivative",
    "diff": "derivative",
    "deriv": "derivative",
    "derive": "derivative",
    "partial derivative": "partial_derivative",
    "partial differentiation": "partial_derivative",
    "partial diff": "partial_derivative",
    "partial deriv": "partial_derivative",
    "gradient": "gradient",
    "grad": "gradient",
    "nabla": "gradient",
    "del": "gradient",
    "jacobian": "jacobian",
    "jacobian matrix": "jacobian",
    "jacobi": "jacobian",
    "hessian": "hessian",
    "hessian matrix": "hessian",
    "second derivative": "second_derivative",
    "second order derivative": "second_derivative",
    "second diff": "second_derivative",
    "second deriv": "second_derivative",
    "third derivative": "third_derivative",
    "third order derivative": "third_derivative",
    "third diff": "third_derivative",
    "third deriv": "third_derivative",
    "integral": "integral",
    "integration": "integral",
    "integrate": "integral",
    "int": "integral",
    "indefinite integral": "indefinite_integral",
    "definite integral": "definite_integral",
    "antiderivative": "antiderivative",
    "primitive": "antiderivative",
    "reverse derivative": "antiderivative",
    "fundamental theorem of calculus": "fundamental_theorem_of_calculus",
    "ftc": "fundamental_theorem_of_calculus",
    "limit": "limit",
    "lim": "limit",
    "limiting value": "limit",
    "l'hospital's rule": "l_hospital_rule",
    "l'hopital's rule": "l_hospital_rule",
    "l hospital rule": "l_hospital_rule",
    "lhopital rule": "l_hospital_rule",
    "lhopital's rule": "l_hospital_rule",
    "continuity": "continuity",
    "continuous": "continuity",
    "discontinuity": "discontinuity",
    "discontinuous": "discontinuity",
    "point of discontinuity": "discontinuity",
    "removable discontinuity": "removable_discontinuity",
    "jump discontinuity": "jump_discontinuity",
    "infinite discontinuity": "infinite_discontinuity",
    "asymptote": "asymptote",
    "horizontal asymptote": "horizontal_asymptote",
    "vertical asymptote": "vertical_asymptote",
    "oblique asymptote": "oblique_asymptote",
    "tangent": "tangent",
    "tangency": "tangent",
    "secant": "secant",
    "secancy": "secant",
    "normal": "normal",
    "normal line": "normal",
    "critical point": "critical_point",
    "stationary point": "critical_point",
    "extremum": "extremum",
    "maximum": "maximum",
    "minimum": "minimum",
    "max": "maximum",
    "min": "minimum",
    "local maximum": "local_maximum",
    "local minimum": "local_minimum",
    "global maximum": "global_maximum",
    "global minimum": "global_minimum",
    "absolute maximum": "global_maximum",
    "absolute minimum": "global_minimum",
    "relative maximum": "local_maximum",
    "relative minimum": "local_minimum",
    "inflection point": "inflection_point",
    "point of inflection": "inflection_point",
    "concavity": "concavity",
    "concave up": "concave_up",
    "concave down": "concave_down",
    "convex": "concave_up",
    "concave": "concave_down",
    "rate of change": "rate_of_change",
    "roc": "rate_of_change",
    "slope": "slope",
    "gradient of a curve": "slope",
    "chain rule": "chain_rule",
    "product rule": "product_rule",
    "quotient rule": "quotient_rule",
    "sum rule": "sum_rule",
    "power rule": "power_rule",
    "implicit differentiation": "implicit_differentiation",
    "implicit diff": "implicit_differentiation",
    "implicit deriv": "implicit_differentiation",
    "explicit differentiation": "explicit_differentiation",
    "explicit diff": "explicit_differentiation",
    "explicit deriv": "explicit_differentiation",
    "directional derivative": "directional_derivative",
    "dir derivative": "directional_derivative",
    "dir deriv": "directional_derivative",
    "differential": "differential",
    "dx": "differential",
    "dy": "differential",
    "dz": "differential",
    "dt": "differential",
    "delta x": "differential",
    "delta y": "differential",
    "delta z": "differential",
    "delta t": "differential",
    "epsilon-delta": "epsilon_delta",
    "eps-delta": "epsilon_delta",
    "ε-δ": "epsilon_delta",
    "mean value theorem": "mean_value_theorem",
    "mvt": "mean_value_theorem",
    "rolle's theorem": "rolles_theorem",
    "rolle theorem": "rolles_theorem",
    "intermediate value theorem": "intermediate_value_theorem",
    "ivt": "intermediate_value_theorem",
    "cauchy's mean value theorem": "cauchy_mean_value_theorem",
    "cauchy mvt": "cauchy_mean_value_theorem",
    "monotonicity": "monotonicity",
    "monotone": "monotonicity",
    "increasing": "increasing",
    "decreasing": "decreasing",
    "bounded": "bounded",
    "unbounded": "unbounded",
    "upper bound": "upper_bound",
    "lower bound": "lower_bound",
    "supremum": "supremum",
    "infimum": "infimum",
    "sup": "supremum",
    "inf": "infimum",
    "domain": "domain",
    "codomain": "codomain",
    "range": "range",
    "function": "function",
    "func": "function",
    "mapping": "function",
    "input": "domain",
    "output": "range",
    "variable": "variable",
    "independent variable": "independent_variable",
    "dependent variable": "dependent_variable",
    "parameter": "parameter",
    "constant": "constant",
    "integration by parts": "integration_by_parts",
    "ibp": "integration_by_parts",
    "integration by substitution": "integration_by_substitution",
    "u substitution": "integration_by_substitution",
    "substitution rule": "integration_by_substitution",
    "integration by partial fractions": "integration_by_partial_fractions",
    "partial fractions": "integration_by_partial_fractions",
    "integration by trigonometric substitution": "integration_by_trig_substitution",
    "trig substitution": "integration_by_trig_substitution",
    "integration by reduction": "integration_by_reduction",
    "reduction formula": "integration_by_reduction",
    "integration by tables": "integration_by_tables",
    "table of integrals": "integration_by_tables",
    "integration by series": "integration_by_series",
    "series integration": "integration_by_series",
    "integration by approximation": "integration_by_approximation",
    "approximate integration": "integration_by_approximation",
    "numerical integration": "numerical_integration",
    "trapezoidal rule": "trapezoidal_rule",
    "trapezium rule": "trapezoidal_rule",
    "simpson's rule": "simpsons_rule",
    "simpson rule": "simpsons_rule",
    "midpoint rule": "midpoint_rule",
    "rectangular rule": "rectangular_rule",
    "rectangle rule": "rectangular_rule",
    "riemann sum": "riemann_sum",
    "riemann integration": "riemann_sum",
    "left riemann sum": "left_riemann_sum",
    "right riemann sum": "right_riemann_sum",
    "center riemann sum": "midpoint_riemann_sum",
    "midpoint riemann sum": "midpoint_riemann_sum",
    "upper riemann sum": "upper_riemann_sum",
    "lower riemann sum": "lower_riemann_sum",
    "lebesgue integral": "lebesgue_integral",
    "lebesgue integration": "lebesgue_integral",
    "stieltjes integral": "stieltjes_integral",
    "stieltjes integration": "stieltjes_integral",
    "improper integral": "improper_integral",
    "proper integral": "proper_integral",
    "singular integral": "singular_integral",
    "multiple integral": "multiple_integral",
    "double integral": "double_integral",
    "triple integral": "triple_integral",
    "iterated integral": "iterated_integral",
    "line integral": "line_integral",
    "curve integral": "line_integral",
    "path integral": "line_integral",
    "surface integral": "surface_integral",
    "area integral": "surface_integral",
    "volume integral": "volume_integral",
    "flux integral": "flux_integral",
    "divergence theorem": "divergence_theorem",
    "gauss's theorem": "divergence_theorem",
    "gauss theorem": "divergence_theorem",
    "green's theorem": "greens_theorem",
    "green theorem": "greens_theorem",
    "stokes' theorem": "stokes_theorem",
    "stokes theorem": "stokes_theorem",
    "curl": "curl",
    "rotation": "curl",
    "divergence": "divergence",
    "div": "divergence",
    "laplacian": "laplacian",
    "laplace operator": "laplacian",
    "laplace": "laplacian",
    "delta squared": "laplacian",
    "∇²": "laplacian",
    "vector calculus": "vector_calculus",
    "scalar field": "scalar_field",
    "vector field": "vector_field",
    "field": "vector_field",
    "parametric equations": "parametric_equations",
    "parametric curve": "parametric_equations",
    "polar coordinates": "polar_coordinates",
    "polar": "polar_coordinates",
    "cartesian coordinates": "cartesian_coordinates",
    "cartesian": "cartesian_coordinates",
    "rectangular coordinates": "cartesian_coordinates",
    "spherical coordinates": "spherical_coordinates",
    "cylindrical coordinates": "cylindrical_coordinates",
    "arc length": "arc_length",
    "length of curve": "arc_length",
    "area under curve": "area_under_curve",
    "area": "area_under_curve",
    "volume under surface": "volume_under_surface",
    "volume": "volume_under_surface",
    "subinterval": "subinterval",
    "partition": "partition",
    "epsilon": "epsilon",
    "δ": "delta",
    "delta": "delta",
    "step function": "step_function",
    "heaviside function": "step_function",
    "heaviside": "step_function",
    "dirac delta": "dirac_delta",
    "dirac function": "dirac_delta",
    "delta function": "dirac_delta",
    "singularity": "singularity",
    "singular point": "singularity",
    "regular point": "regular_point",
    "point": "point",
    "interval": "interval",
    "open interval": "open_interval",
    "closed interval": "closed_interval",
    "half-open interval": "half_open_interval",
    "half-closed interval": "half_open_interval",
    "neighborhood": "neighborhood",
    "open set": "open_set",
    "closed set": "closed_set",
    "compact set": "compact_set",
    "compactness": "compact_set",
    "connected set": "connected_set",
    "disconnected set": "disconnected_set",
    "sequence": "sequence",
    "series": "series",
    "infinite series": "infinite_series",
    "convergence": "convergence",
    "convergent": "convergence",
    "divergence (series)": "divergence_series",
    "divergent": "divergence_series",
    "absolute convergence": "absolute_convergence",
    "conditional convergence": "conditional_convergence",
    "radius of convergence": "radius_of_convergence",
    "interval of convergence": "interval_of_convergence",
    "power series": "power_series",
    "taylor series": "taylor_series",
    "taylor expansion": "taylor_series",
    "maclaurin series": "maclaurin_series",
    "maclaurin expansion": "maclaurin_series",
    "fourier series": "fourier_series",
    "fourier expansion": "fourier_series",
    "laurent series": "laurent_series",
    "laurent expansion": "laurent_series",
    "binomial series": "binomial_series",
    "binomial expansion": "binomial_series",
    "function composition": "function_composition",
    "composition": "function_composition",
    "inverse function": "inverse_function",
    "invertible function": "inverse_function",
    "bijective": "bijective",
    "injective": "injective",
    "surjective": "surjective",
    "one-to-one": "injective",
    "onto": "surjective",
    "domain restriction": "domain_restriction",
    "domain extension": "domain_extension",
    "piecewise function": "piecewise_function",
    "piecewise": "piecewise_function",
    "stepwise function": "piecewise_function",
    "discontinuous function": "discontinuity",
    "continuous function": "continuity",
    "smooth function": "smooth_function",
    "smoothness": "smooth_function",
    "analytic function": "analytic_function",
    "non-analytic function": "non_analytic_function",
    "singular function": "singular_function",
    "bounded function": "bounded_function",
    "unbounded function": "unbounded_function",
    "periodic function": "periodic_function",
    "periodicity": "periodic_function",
    "even function": "even_function",
    "odd function": "odd_function",
    "monotonic function": "monotonicity",
    "monotone function": "monotonicity",
    "increasing function": "increasing",
    "decreasing function": "decreasing",
    "constant function": "constant_function",
    "zero function": "zero_function",
    "identity function": "identity_function",
    "linear function": "linear_function",
    "affine function": "affine_function",
    "quadratic function": "quadratic_function",
    "cubic function": "cubic_function",
    "polynomial function": "polynomial_function",
    "polynomial": "polynomial_function",
    "rational function": "rational_function",
    "irrational function": "irrational_function",
    "algebraic function": "algebraic_function",
    "transcendental function": "transcendental_function",
    "exponential function": "exponential_function",
    "logarithmic function": "logarithmic_function",
    "trigonometric function": "trigonometric_function",
    "trig function": "trigonometric_function",
    "hyperbolic function": "hyperbolic_function",
    "inverse trigonometric function": "inverse_trigonometric_function",
    "inverse trig function": "inverse_trigonometric_function",
    "inverse hyperbolic function": "inverse_hyperbolic_function",
    "absolute value function": "absolute_value_function",
    "modulus function": "absolute_value_function",
    "sign function": "sign_function",
    "sgn": "sign_function",
    "floor function": "floor_function",
    "ceiling function": "ceiling_function",
    "rounding function": "rounding_function",
    "step function": "step_function",
    "heaviside step function": "step_function",
    "dirac step function": "dirac_delta",
    "delta step function": "dirac_delta",
    "piecewise step function": "step_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "piecewise identity function": "piecewise_identity_function",
    "piecewise linear function": "piecewise_linear_function",
    "piecewise affine function": "piecewise_affine_function",
    "piecewise quadratic function": "piecewise_quadratic_function",
    "piecewise cubic function": "piecewise_cubic_function",
    "piecewise polynomial function": "piecewise_polynomial_function",
    "piecewise rational function": "piecewise_rational_function",
    "piecewise irrational function": "piecewise_irrational_function",
    "piecewise algebraic function": "piecewise_algebraic_function",
    "piecewise transcendental function": "piecewise_transcendental_function",
    "piecewise exponential function": "piecewise_exponential_function",
    "piecewise logarithmic function": "piecewise_logarithmic_function",
    "piecewise trigonometric function": "piecewise_trigonometric_function",
    "piecewise hyperbolic function": "piecewise_hyperbolic_function",
    "piecewise inverse trigonometric function": "piecewise_inverse_trigonometric_function",
    "piecewise inverse hyperbolic function": "piecewise_inverse_hyperbolic_function",
    "piecewise absolute value function": "piecewise_absolute_value_function",
    "piecewise sign function": "piecewise_sign_function",
    "piecewise floor function": "piecewise_floor_function",
    "piecewise ceiling function": "piecewise_ceiling_function",
    "piecewise rounding function": "piecewise_rounding_function",
    "piecewise step function": "piecewise_step_function",
    "piecewise heaviside function": "piecewise_heaviside_function",
    "piecewise dirac function": "piecewise_dirac_function",
    "piecewise delta function": "piecewise_delta_function",
    "piecewise singular function": "piecewise_singular_function",
    "piecewise bounded function": "piecewise_bounded_function",
    "piecewise unbounded function": "piecewise_unbounded_function",
    "piecewise periodic function": "piecewise_periodic_function",
    "piecewise even function": "piecewise_even_function",
    "piecewise odd function": "piecewise_odd_function",
    "piecewise monotonic function": "piecewise_monotonic_function",
    "piecewise increasing function": "piecewise_increasing_function",
    "piecewise decreasing function": "piecewise_decreasing_function",
    "piecewise constant function": "piecewise_constant_function",
    "piecewise zero function": "piecewise_zero_function",
    "