import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENT09_international_trade"
SEMANTIC_MAP_ENGINE = "ENT09"

SEMANTIC_MAP = {
    # EAR Export License Requirements
    "ear": "export_administration_regulations",
    "export administration regulations": "export_administration_regulations",
    "export license": "export_license",
    "export licenses": "export_license",
    "export licensing": "export_license",
    "bis": "bureau_of_industry_and_security",
    "bureau of industry and security": "bureau_of_industry_and_security",
    "commerce control list": "ccl",
    "ccl": "ccl",
    "eccn": "export_control_classification_number",
    "export control classification number": "export_control_classification_number",
    "de minimis": "de_minimis_rule",
    "de minimis rule": "de_minimis_rule",
    "reexport": "reexport",
    "re-export": "reexport",
    "deemed export": "deemed_export",
    "deemed exports": "deemed_export",
    "end-use": "end_use",
    "end use": "end_use",
    "end-user": "end_user",
    "end user": "end_user",
    "entity list": "entity_list",
    "denied persons list": "denied_persons_list",
    "unverified list": "unverified_list",
    "military end use": "military_end_use",
    "military end-user": "military_end_user",
    "military end user": "military_end_user",
    "license exception": "license_exception",
    "license exceptions": "license_exception",
    "snap-r": "snap_r",
    "snap r": "snap_r",
    "self-classification": "self_classification",
    "self classification": "self_classification",
    "export compliance": "export_compliance",
    "encryption items": "encryption_items",
    "encryption": "encryption_items",
    "encryption review": "encryption_review",
    "encryption registration": "encryption_registration",
    "technology control plan": "technology_control_plan",
    "tcp": "technology_control_plan",
    "export jurisdiction": "export_jurisdiction",
    "usml": "united_states_munitions_list",
    "united states munitions list": "united_states_munitions_list",
    "itar": "international_traffic_in_arms_regulations",
    "international traffic in arms regulations": "international_traffic_in_arms_regulations",
    "itar controlled": "itar_controlled",
    "itar article": "itar_controlled",
    "itar item": "itar_controlled",
    "itar registration": "itar_registration",
    "itar license": "itar_license",
    "itar exemption": "itar_exemption",
    "itar compliance": "itar_compliance",
    "defense article": "defense_article",
    "defense articles": "defense_article",
    "defense service": "defense_service",
    "defense services": "defense_service",
    "technical data": "technical_data",
    "manufacturing license agreement": "manufacturing_license_agreement",
    "mla": "manufacturing_license_agreement",
    "technical assistance agreement": "technical_assistance_agreement",
    "taa": "technical_assistance_agreement",
    "brokering": "itar_brokering",
    "itar brokering": "itar_brokering",
    "itar violations": "itar_violation",
    "itar violation": "itar_violation",
    "itar penalties": "itar_penalty",
    "itar penalty": "itar_penalty",
    "itar enforcement": "itar_enforcement",
    "itar embargo": "itar_embargo",
    "itar embargoed country": "itar_embargoed_country",
    "itar embargoed countries": "itar_embargoed_country",
    "itar prohibited": "itar_prohibited",
    "itar prohibited countries": "itar_prohibited_country",
    "itar prohibited country": "itar_prohibited_country",
    "itar restricted": "itar_restricted",
    "itar restricted countries": "itar_restricted_country",
    "itar restricted country": "itar_restricted_country",
    "itar registration code": "itar_registration_code",
    "itar registration number": "itar_registration_code",
    "itar registration renewal": "itar_registration_renewal",
    "itar registration expiration": "itar_registration_expiration",
    "itar registration fee": "itar_registration_fee",
    "itar registration process": "itar_registration_process",
    "itar registration application": "itar_registration_application",
    "itar registration form": "itar_registration_form",
    "itar registration requirements": "itar_registration_requirements",
    "itar registration update": "itar_registration_update",
    "itar registration changes": "itar_registration_update",
    "itar registration amendment": "itar_registration_update",
    "itar registration cancellation": "itar_registration_cancellation",
    "itar registration withdrawal": "itar_registration_cancellation",
    "itar registration transfer": "itar_registration_transfer",
    "itar registration assignment": "itar_registration_transfer",
    "itar registration successor": "itar_registration_transfer",
    "itar registration successor in interest": "itar_registration_transfer",
    "itar registration successor-in-interest": "itar_registration_transfer",

    # OFAC Sanctions Compliance
    "ofac": "office_of_foreign_assets_control",
    "office of foreign assets control": "office_of_foreign_assets_control",
    "ofac sanctions": "ofac_sanctions",
    "ofac list": "ofac_list",
    "sdn": "specially_designated_nationals",
    "specially designated nationals": "specially_designated_nationals",
    "sdn list": "specially_designated_nationals_list",
    "ofac sdn list": "specially_designated_nationals_list",
    "blocked persons": "blocked_persons",
    "blocked property": "blocked_property",
    "blocked account": "blocked_account",
    "blocked accounts": "blocked_account",
    "sanctions": "sanctions",
    "sanctioned country": "sanctioned_country",
    "sanctioned countries": "sanctioned_country",
    "sanctioned entity": "sanctioned_entity",
    "sanctioned entities": "sanctioned_entity",
    "sanctioned person": "sanctioned_person",
    "sanctioned persons": "sanctioned_person",
    "sanctioned individual": "sanctioned_person",
    "sanctioned individuals": "sanctioned_person",
    "sanctioned party": "sanctioned_party",
    "sanctioned parties": "sanctioned_party",
    "sanctions compliance": "sanctions_compliance",
    "ofac compliance": "sanctions_compliance",
    "ofac screening": "ofac_screening",
    "ofac search": "ofac_screening",
    "ofac check": "ofac_screening",
    "ofac match": "ofac_screening",
    "ofac alert": "ofac_screening",
    "ofac violation": "ofac_violation",
    "ofac violations": "ofac_violation",
    "ofac penalty": "ofac_penalty",
    "ofac penalties": "ofac_penalty",
    "ofac enforcement": "ofac_enforcement",
    "ofac license": "ofac_license",
    "ofac licenses": "ofac_license",
    "ofac general license": "ofac_general_license",
    "ofac specific license": "ofac_specific_license",
    "ofac general licenses": "ofac_general_license",
    "ofac specific licenses": "ofac_specific_license",
    "ofac reporting": "ofac_reporting",
    "ofac report": "ofac_reporting",
    "ofac notification": "ofac_reporting",
    "ofac notification requirement": "ofac_reporting",
    "ofac notification requirements": "ofac_reporting",
    "ofac notification deadline": "ofac_reporting",
    "ofac notification process": "ofac_reporting",
    "ofac notification procedure": "ofac_reporting",
    "ofac notification form": "ofac_reporting",
    "ofac notification submission": "ofac_reporting",
    "ofac notification filing": "ofac_reporting",

    # HTS Classification and Tariffs
    "hts": "harmonized_tariff_schedule",
    "harmonized tariff schedule": "harmonized_tariff_schedule",
    "hts code": "hts_code",
    "hts codes": "hts_code",
    "hts classification": "hts_classification",
    "tariff classification": "hts_classification",
    "tariff code": "hts_code",
    "customs classification": "hts_classification",
    "customs code": "hts_code",
    "tariff": "tariff",
    "tariffs": "tariff",
    "tariff rate": "tariff_rate",
    "tariff rates": "tariff_rate",
    "tariff schedule": "harmonized_tariff_schedule",
    "tariff number": "hts_code",
    "tariff numbers": "hts_code",
    "tariff heading": "tariff_heading",
    "tariff subheading": "tariff_subheading",
    "tariff line": "tariff_line",
    "tariff lines": "tariff_line",
    "tariff quota": "tariff_quota",
    "tariff quotas": "tariff_quota",
    "tariff preference": "tariff_preference",
    "tariff preferences": "tariff_preference",
    "tariff concession": "tariff_concession",
    "tariff concessions": "tariff_concession",
    "tariff exemption": "tariff_exemption",
    "tariff exemptions": "tariff_exemption",
    "tariff suspension": "tariff_suspension",
    "tariff suspensions": "tariff_suspension",
    "tariff reduction": "tariff_reduction",
    "tariff reductions": "tariff_reduction",
    "tariff increase": "tariff_increase",
    "tariff increases": "tariff_increase",
    "tariff escalation": "tariff_escalation",
    "tariff escalation clause": "tariff_escalation",
    "tariff escalation clauses": "tariff_escalation",
    "tariff escalation provision": "tariff_escalation",
    "tariff escalation provisions": "tariff_escalation",

    # FCPA Anti-Bribery Provisions
    "fcpa": "foreign_corrupt_practices_act",
    "foreign corrupt practices act": "foreign_corrupt_practices_act",
    "fcpa compliance": "fcpa_compliance",
    "fcpa violation": "fcpa_violation",
    "fcpa violations": "fcpa_violation",
    "fcpa enforcement": "fcpa_enforcement",
    "fcpa penalty": "fcpa_penalty",
    "fcpa penalties": "fcpa_penalty",
    "fcpa investigation": "fcpa_investigation",
    "fcpa investigations": "fcpa_investigation",
    "fcpa audit": "fcpa_audit",
    "fcpa audits": "fcpa_audit",
    "fcpa due diligence": "fcpa_due_diligence",
    "fcpa training": "fcpa_training",
    "fcpa policy": "fcpa_policy",
    "fcpa policies": "fcpa_policy",
    "fcpa program": "fcpa_program",
    "fcpa programs": "fcpa_program",
    "fcpa controls": "fcpa_controls",
    "fcpa control": "fcpa_controls",
    "fcpa reporting": "fcpa_reporting",
    "fcpa report": "fcpa_reporting",
    "fcpa disclosure": "fcpa_disclosure",
    "fcpa disclosures": "fcpa_disclosure",
    "fcpa whistleblower": "fcpa_whistleblower",
    "fcpa whistleblowers": "fcpa_whistleblower",
    "fcpa whistleblower program": "fcpa_whistleblower",
    "fcpa whistleblower protection": "fcpa_whistleblower_protection",
    "fcpa whistleblower protections": "fcpa_whistleblower_protection",
    "fcpa anti-bribery": "fcpa_anti_bribery",
    "fcpa anti bribery": "fcpa_anti_bribery",
    "fcpa anti-bribery provisions": "fcpa_anti_bribery",
    "fcpa anti bribery provisions": "fcpa_anti_bribery",
    "anti-bribery": "anti_bribery",
    "anti bribery": "anti_bribery",
    "anti-bribery provisions": "anti_bribery",
    "anti bribery provisions": "anti_bribery",
    "anti-bribery law": "anti_bribery",
    "anti bribery law": "anti_bribery",
    "anti-bribery laws": "anti_bribery",
    "anti bribery laws": "anti_bribery",
    "anti-bribery compliance": "anti_bribery_compliance",
    "anti bribery compliance": "anti_bribery_compliance",

    # USMCA Rules of Origin
    "usmca": "us_mexico_canada_agreement",
    "us-mexico-canada agreement": "us_mexico_canada_agreement",
    "usmca rules of origin": "usmca_rules_of_origin",
    "rules of origin": "rules_of_origin",
    "origin rule": "rules_of_origin",
    "origin rules": "rules_of_origin",
    "certificate of origin": "certificate_of_origin",
    "certificates of origin": "certificate_of_origin",
    "usmca certificate": "certificate_of_origin",
    "usmca certificate of origin": "certificate_of_origin",
    "usmca origin": "usmca_origin",
    "usmca origin criteria": "usmca_origin_criteria",
    "usmca origin rule": "usmca_rules_of_origin",
    "usmca origin rules": "usmca_rules_of_origin",
    "usmca preference": "usmca_preference",
    "usmca preferences": "usmca_preference",
    "usmca tariff": "usmca_tariff",
    "usmca tariffs": "usmca_tariff",
    "usmca duty": "usmca_duty",
    "usmca duties": "usmca_duty",
    "usmca claim": "usmca_claim",
    "usmca claims": "usmca_claim",
    "usmca importer": "usmca_importer",
    "usmca importers": "usmca_importer",
    "usmca exporter": "usmca_exporter",
    "usmca exporters": "usmca_exporter",
    "usmca producer": "usmca_producer",
    "usmca producers": "usmca_producer",
    "usmca verification": "usmca_verification",
    "usmca verifications": "usmca_verification",
    "usmca audit": "usmca_audit",
    "usmca audits": "usmca_audit",
    "usmca recordkeeping": "usmca_recordkeeping",
    "usmca records": "usmca_recordkeeping",
    "usmca documentation": "usmca_documentation",
    "usmca docs": "usmca_documentation",
    "usmca doc": "usmca_documentation",

    # Antidumping and Countervailing Duties
    "antidumping": "antidumping",
    "anti-dumping": "antidumping",
    "antidumping duty": "antidumping_duty",
    "antidumping duties": "antidumping_duty",
    "anti-dumping duty": "antidumping_duty",
    "anti-dumping duties": "antidumping_duty",
    "countervailing": "countervailing",
    "countervailing duty": "countervailing_duty",
    "countervailing duties": "countervailing_duty",
    "ad/cvd": "antidumping_countervailing",
    "ad cvd": "antidumping_countervailing",
    "ad cvd duties": "antidumping_countervailing",
    "ad/cvd duties": "antidumping_countervailing",
    "ad duty": "antidumping_duty",
    "ad duties": "antidumping_duty",
    "cvd duty": "countervailing_duty",
    "cvd duties": "countervailing_duty",
    "ad order": "antidumping_order",
    "ad orders": "antidumping_order",
    "cvd order": "countervailing_order",
    "cvd orders": "countervailing_order",
    "ad/cvd order": "antidumping_countervailing_order",
    "ad/cvd orders": "antidumping_countervailing_order",
    "ad cvd order": "antidumping_countervailing_order",
    "ad cvd orders": "antidumping_countervailing_order",
    "ad/cvd investigation": "antidumping_countervailing_investigation",
    "ad/cvd investigations": "antidumping_countervailing_investigation",
    "ad cvd investigation": "antidumping_countervailing_investigation",
    "ad cvd investigations": "antidumping_countervailing_investigation",
    "ad investigation": "antidumping_investigation",
    "ad investigations": "antidumping_investigation",
    "cvd investigation": "countervailing_investigation",
    "cvd investigations": "countervailing_investigation",
    "ad/cvd case": "antidumping_countervailing_case",
    "ad/cvd cases": "antidumping_countervailing_case",
    "ad cvd case": "antidumping_countervailing_case",
    "ad cvd cases": "antidumping_countervailing_case",

    # Section 301 Tariffs on China
    "section 301": "section_301",
    "section 301 tariffs": "section_301_tariffs",
    "section 301 tariff": "section_301_tariffs",
    "301 tariffs": "section_301_tariffs",
    "301 tariff": "section_301_tariffs",
    "china tariffs": "section_301_tariffs",
    "china tariff": "section_301_tariffs",
    "section 301 exclusion": "section_301_exclusion",
    "section 301 exclusions": "section_301_exclusion",
    "section 301 exclusion request": "section_301_exclusion_request",
    "section 301 exclusion requests": "section_301_exclusion_request",
    "section 301 list": "section_301_list",
    "section 301 list 1": "section_301_list_1",
    "section 301 list 2": "section_301_list_2",
    "section 301 list 3": "section_301_list_3",
    "section 301 list 4": "section_301_list_4",
    "section 301 list 4a": "section_301_list_4a",
    "section 301 list 4b": "section_301_list_4b",
    "section 301 product list": "section_301_product_list",
    "section 301 product lists": "section_301_product_list",
    "section 301 investigation": "section_301_investigation",
    "section 301 investigations": "section_301_investigation",
    "section 301 duties": "section_301_duties",
    "section 301 duty": "section_301_duties",

    # Section 232 Steel and Aluminum Tariffs
    "section 232": "section_232",
    "section 232 tariffs": "section_232_tariffs",
    "section 232 tariff": "section_232_tariffs",
    "232 tariffs": "section_232_tariffs",
    "232 tariff": "section_232_tariffs",
    "steel tariffs": "section_232_steel_tariffs",
    "aluminum tariffs": "section_232_aluminum_tariffs",
    "section 232 steel": "section_232_steel_tariffs",
    "section 232 aluminum": "section_232_aluminum_tariffs",
    "section 232 exclusion": "section_232_exclusion",
    "section 232 exclusions": "section_232_exclusion",
    "section 232 exclusion request": "section_232_exclusion_request",
    "section 232 exclusion requests": "section_232_exclusion_request",
    "section 232 investigation": "section_232_investigation",
    "section 232 investigations": "section_232_investigation",
    "section 232 product exclusion": "section_232_exclusion",
    "section 232 product exclusions": "section_232_exclusion",

    # Foreign Trade Zones (FTZ)
    "ftz": "foreign_trade_zone",
    "foreign trade zone": "foreign_trade_zone",
    "foreign trade zones": "foreign_trade_zone",
    "ftz application": "ftz_application",
    "ftz applications": "ftz_application",
    "ftz activation": "ftz_activation",
    "ftz activations": "ftz_activation",
    "ftz admission": "ftz_admission",
    "ftz admissions": "ftz_admission",
    "ftz status": "ftz_status",
    "ftz status designation": "ftz_status",
    "ftz status designations": "ftz_status",
    "ftz status change": "ftz_status_change",
    "ftz status changes": "ftz_status_change",
    "ftz operator": "ftz_operator",
    "ftz operators": "ftz_operator",
    "ftz grantee": "ftz_grantee",
    "ftz grantees": "ftz_grantee",
    "ftz user": "ftz_user",
    "ftz users": "ftz_user",
    "ftz site": "ftz_site",
    "ftz sites": "ftz_site",
    "ftz subzone": "ftz_subzone",
    "ftz subzones": "ftz_subzone",
    "ftz boundary": "ftz_boundary",
    "ftz boundaries": "ftz_boundary",
    "ftz board": "ftz_board",
    "ftz boards": "ftz_board",
    "ftz regulations": "ftz_regulations",
    "ftz regulation": "ftz_regulations",
    "ftz compliance": "ftz_compliance",
    "ftz audit": "ftz_audit",
    "ftz audits": "ftz_audit",
    "ftz reporting": "ftz_reporting",
    "ftz report": "ftz_reporting",
    "ftz annual report": "ftz_annual_report",
    "ftz annual reports": "ftz_annual_report",

    # Customs Valuation Transaction Value
    "customs valuation": "customs_valuation",
    "transaction value": "transaction_value",
    "transaction values": "transaction_value",
    "customs value": "customs_value",
    "customs values": "customs_value",
    "appraised value": "customs_value",
    "declared value": "customs_value",
    "entered value": "customs_value",
    "invoice value": "invoice_value",
    "dutiable value": "dutiable_value",
    "dutiable values": "dutiable_value",
    "duty paid value": "dutiable_value",
    "duty-paid value": "dutiable_value",
    "duty paid values": "dutiable_value",
    "duty-paid values": "dutiable_value",
    "import value": "import_value",
    "import values": "import_value",
    "export value": "export_value",
    "export values": "export_value",
    "customs appraisement": "customs_appraisement",
    "customs appraisements": "customs_appraisement",
    "customs appraisal": "customs_appraisement",
    "customs appraisals": "customs_appraisement",
    "customs declaration": "customs_declaration",
    "customs declarations": "customs_declaration",
    "customs invoice": "customs_invoice",
    "customs invoices": "customs_invoice",
    "customs entry": "customs_entry",
    "customs entries": "customs_entry",

    # Deemed Export of Technology and Source Code
    "deemed export": "deemed_export",
    "deemed exports": "deemed_export",
    "deemed reexport": "deemed_reexport",
    "deemed re-export": "deemed_reexport",
    "deemed reexports": "deemed_reexport",
    "deemed re-exports": "deemed_reexport",
    "technology export": "technology_export",
    "technology exports": "technology_export",
    "source code export": "source_code_export",
    "source code exports": "source_code_export",
    "export of technology": "technology_export",
    "export of source code": "source_code_export",
    "release of technology": "technology_release",
    "release of source code": "source_code_release",
    "disclosure of technology": "technology_disclosure",
    "disclosure of source code": "source_code_disclosure",
    "transfer of technology": "technology_transfer",
    "transfer of source code": "source_code_transfer",
    "technology transfer": "technology_transfer",
    "technology transfers": "technology_transfer",
    "source code transfer": "source_code_transfer",
    "source code transfers": "source_code_transfer",

    # Incoterms and Risk of Loss
    "incoterms": "incoterms",
    "incoterm": "incoterms",
    "incoterms 2020": "incoterms_2020",
    "incoterms 2010": "incoterms_2010",
    "incoterms 2000": "incoterms_2000",
    "fob": "incoterm_fob",
    "cif": "incoterm_cif",
    "exw": "incoterm_exw",
    "dap": "incoterm_dap",
    "ddp": "incoterm_ddp",
    "dpu": "incoterm_dpu",
    "cfr": "incoterm_cfr",
    "cpt": "incoterm_cpt",
    "cip": "incoterm_cip",
    "fas": "incoterm_fas",
    "fca": "incoterm_fca",
    "risk of loss": "risk_of_loss",
    "risk allocation": "risk_of_loss",
    "risk transfer": "risk_of_loss",
    "delivery term": "incoterms",
    "delivery terms": "incoterms",
    "shipping term": "incoterms",
    "shipping terms": "incoterms",

    # Voluntary Self-Disclosure of Export Violations
    "voluntary self-disclosure": "voluntary_self_disclosure",
    "voluntary self disclosure": "voluntary_self_disclosure",
    "vsd": "voluntary_self_disclosure",
    "voluntary disclosure": "voluntary_self_disclosure",
    "voluntary disclosures": "voluntary_self_disclosure",
    "self-disclosure": "voluntary_self_disclosure",
    "self disclosure": "voluntary_self_disclosure",
    "self-disclosures": "voluntary_self_disclosure",
    "self disclosures": "voluntary_self_disclosure",
    "export violation": "export_violation",
    "export violations": "export_violation",
    "export enforcement": "export_enforcement",
    "export penalty": "export_penalty",
    "export penalties": "export_penalty",
    "export investigation": "export_investigation",
    "export investigations": "export_investigation",

    # Import Licensing and Quota Administration
    "import license": "import_license",
    "import licenses": "import_license",
    "import licensing": "import_license",
    "import permit": "import_license",
    "import permits": "import_license",
    "import quota": "import_quota",
    "import quotas": "import_quota",
    "import quota administration": "import_quota_administration",
    "import quota management": "import_quota_administration",
    "import quota allocation": "import_quota_allocation",
    "import quota allocations": "import_quota_allocation",
    "import quota application": "import_quota_application",
    "import quota applications": "import_quota_application",
    "import quota certificate": "import_quota_certificate",
    "import quota certificates": "import_quota_certificate",
    "import quota compliance": "import_quota_compliance",
    "import quota enforcement": "import_quota_enforcement",

    # Country of Origin Marking Requirements
    "country of origin": "country_of_origin",
    "origin country": "country_of_origin",
    "origin marking": "country_of_origin_marking",
    "country of origin marking": "country_of_origin_marking",
    "origin marking requirements": "country_of_origin_marking_requirements",
    "country of origin marking requirements": "country_of_origin_marking_requirements",
    "made in": "country_of_origin_marking",
    "marking requirement": "country_of_origin_marking_requirements",
    "marking requirements": "country_of_origin_marking_requirements",
    "origin label": "country_of_origin_marking",
    "origin labeling": "country_of_origin_marking",
    "origin labels": "country_of_origin_marking",
    "origin labelled": "country_of_origin_marking",
    "origin labeled": "country_of_origin_marking",
    "origin labelling": "country_of_origin_marking",
    "origin labeling requirements": "country_of_origin_marking_requirements",
    "origin labelling requirements": "country_of_origin_marking_requirements",

    # Letters of Credit in International Trade
    "letter of credit": "letter_of_credit",
    "letters of credit": "letter_of_credit",
    "lc": "letter_of_credit",
    "l/c": "letter_of_credit",
    "irrevocable letter of credit": "irrevocable_letter_of_credit",
    "revocable letter of credit": "revocable_letter_of_credit",
    "standby letter of credit": "standby_letter_of_credit",
    "confirmed letter of credit": "confirmed_letter_of_credit",
    "unconfirmed letter of credit": "unconfirmed_letter_of_credit",
    "transferable letter of credit": "transferable_letter_of_credit",
    "back-to-back letter of credit": "back_to_back_letter_of_credit",
    "back to back letter of credit": "back_to_back_letter_of_credit",
    "red clause letter of credit": "red_clause_letter_of_credit",
    "green clause letter of credit": "green_clause_letter_of_credit",
    "sight letter of credit": "sight_letter_of_credit",
    "usance letter of credit": "usance_letter_of_credit",
    "negotiable letter of credit": "negotiable_letter_of_credit",
    "non-negotiable letter of credit": "non_negotiable_letter_of_credit",
    "documentary letter of credit": "documentary_letter_of_credit",
    "documentary credit": "documentary_letter_of_credit",
    "documentary credits": "documentary_letter_of_credit",
    "bank guarantee": "bank_guarantee",
    "bank guarantees": "bank_guarantee",
    "trade finance": "trade_finance",
    "trade financing": "trade_finance",

    # Trade Compliance Audits and Recordkeeping
    "trade compliance": "trade_compliance",
    "trade compliance audit": "trade_compliance_audit",
    "trade compliance audits": "trade_compliance_audit",
    "trade audit": "trade_compliance_audit",
    "trade audits": "trade_compliance_audit",
    "compliance audit": "trade_compliance_audit",
    "compliance audits": "trade_compliance_audit",
    "compliance review": "trade_compliance_review",
    "compliance reviews": "trade_compliance_review",
    "compliance assessment": "trade_compliance_assessment",
    "compliance assessments": "trade_compliance_assessment",
    "compliance program": "trade_compliance_program",
    "compliance programs": "trade_compliance_program",
    "compliance manual": "trade_compliance_manual",
    "compliance manuals": "trade_compliance_manual",
    "compliance policy": "trade_compliance_policy",
    "compliance policies": "trade_compliance_policy",
    "compliance procedure": "trade_compliance_procedure",
    "compliance procedures": "trade_compliance_procedure",
    "compliance training": "trade_compliance_training",
    "compliance recordkeeping": "trade_compliance_recordkeeping",
    "compliance records": "trade_compliance_recordkeeping",
    "compliance documentation": "trade_compliance_documentation",
    "trade recordkeeping": "trade_compliance_recordkeeping",
    "trade records": "trade_compliance_recordkeeping",
    "trade documentation": "trade_compliance_documentation",
    "recordkeeping": "trade_compliance_recordkeeping",
    "record keeping": "trade_compliance_recordkeeping",
    "records management": "trade_compliance_recordkeeping",
    "records retention": "trade_compliance_recordkeeping",
    "document retention": "trade_compliance_recordkeeping",
    "document management": "trade_compliance_recordkeeping",
    "document control": "trade_compliance_recordkeeping",
    "document controls": "trade_compliance_recordkeeping",
    "audit trail": "trade_compliance_recordkeeping",
    "audit trails": "trade_compliance_recordkeeping",
    "audit log": "trade_compliance_recordkeeping",
    "audit logs": "trade_compliance_recordkeeping",
    "audit documentation": "trade_compliance_documentation",
    "audit documents": "trade_compliance_documentation",
    "audit record": "trade_compliance_recordkeeping",
    "audit records": "trade_compliance_recordkeeping",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    m = hashlib.sha256()
    for k, v in items:
        m.update(k.encode('utf-8'))
        m.update(b'->')
        m.update(v.encode('utf-8'))
    m.update(SEMANTIC_MAP_VERSION.encode('utf-8'))
    m.update(SEMANTIC_MAP_ENGINE.encode('utf-8'))
    m.update(SEMANTIC_MAP_AUTHOR.encode('utf-8'))
    return m.hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    current_hash = _compute_map_hash()
    is_valid = (
        actual_count == _EXPECTED_ENTRY_COUNT and
        current_hash == _MAP_INTEGRITY_HASH
    )
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": current_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    if not isinstance(term, str):
        return ""
    t = term.strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = t.replace("’", "'").replace("“", '"').replace("”", '"')
    t = t.replace("-", " ").replace("_", " ")
    t = re.sub(r"\s+", " ", t)
    t = t.strip()
    # Try direct mapping
    if t in SEMANTIC_MAP:
        return SEMANTIC_MAP[t]
    # Try with underscores
    t_ = t.replace(" ", "_")
    if t_ in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_]
    # Try with hyphens
    t_ = t.replace(" ", "-")
    if t_ in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_]
    # Try removing punctuation
    t_ = re.sub(r"[^\w\s]", "", t)
    if t_ in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_]
    # Try with underscores after removing punctuation
    t_ = t_.replace(" ", "_")
    if t_ in SEMANTIC_MAP:
        return SEMANTIC_MAP[t_]
    return t

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == normalized and k != term:
            related.append(k)
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)