from dataclasses import dataclass
from typing import List, Optional
from enum import Enum
from pathlib import Path

@dataclass
class DoctrineBlock:
    topic: str
    keywords: List[str]
    conclusion_template: str
    reasoning_framework: str
    key_factors: List[str]
    primary_authority: List[str]
    burden_holder: str
    adversary_position: str
    counter_arguments: List[str]
    resolution_strategy: str
    entity_scope: str
    confidence: float
    confidence_zone: str
    controlling_precedent: str

DOCTRINE_CACHE: List[DoctrineBlock] = [
    DoctrineBlock(
        topic="Pumped Hydro Storage Fundamentals",
        keywords=["pumped hydro", "energy storage", "hydroelectric", "gravity storage", "water reservoirs"],
        conclusion_template="Pumped hydro storage remains the most mature and scalable grid-scale energy storage technology.",
        reasoning_framework="""Pumped hydro storage operates by moving water between two reservoirs at different elevations, storing energy in the form of gravitational potential. Its round-trip efficiency ranges from 70% to 85%, and it can provide both short-term and long-duration storage. Key considerations include site selection, environmental impact, capital cost, and operational flexibility. Regulatory approvals and water rights are critical, as is integration with grid demand profiles. The technology is proven, but expansion is limited by geography and environmental constraints. Recent advances focus on closed-loop systems and modular designs to reduce siting barriers.""",
        key_factors=["site suitability", "environmental impact", "capital cost", "efficiency", "regulatory approval", "grid integration"],
        primary_authority=["International Hydropower Association", "US Department of Energy", "IEA"],
        burden_holder="Project developer",
        adversary_position="Environmental groups may oppose due to ecological disruption and water usage concerns.",
        counter_arguments=["Closed-loop designs minimize environmental impact.", "Modern siting tools optimize location selection.", "Regulatory frameworks can mitigate ecological risks."],
        resolution_strategy="Comprehensive environmental impact assessments and stakeholder engagement.",
        entity_scope="Utility-scale storage operators, regulators, environmental agencies",
        confidence=0.97,
        confidence_zone="High",
        controlling_precedent="FERC licensing for pumped storage projects"
    ),
    DoctrineBlock(
        topic="Compressed Air Energy Storage (CAES) Technology",
        keywords=["CAES", "compressed air", "energy storage", "underground caverns", "thermal integration"],
        conclusion_template="CAES offers scalable storage with moderate efficiency, suitable for bulk energy shifting.",
        reasoning_framework="""CAES systems store energy by compressing air and releasing it through turbines to generate electricity. Efficiency is typically 45%-55%, but advanced adiabatic designs can reach higher values. Key factors include geological suitability for underground storage, integration of thermal management systems, and capital cost. CAES is best suited for locations with suitable salt caverns or depleted gas fields. Regulatory and safety concerns focus on air containment and thermal emissions. Hybrid CAES with renewables can improve performance and economics.""",
        key_factors=["geological suitability", "thermal management", "capital cost", "efficiency", "regulatory compliance"],
        primary_authority=["Sandia National Laboratories", "US DOE", "IEA"],
        burden_holder="Project developer",
        adversary_position="Critics cite low efficiency and limited siting options.",
        counter_arguments=["Adiabatic CAES improves efficiency.", "Hybridization with renewables enhances economics.", "Advanced thermal management reduces losses."],
        resolution_strategy="Adopt advanced CAES designs and leverage hybrid integration.",
        entity_scope="Utility-scale storage operators, regulators, developers",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="Huntorf and McIntosh CAES facilities"
    ),
    DoctrineBlock(
        topic="Flywheel Energy Storage Systems",
        keywords=["flywheel", "mechanical storage", "rotational energy", "short-duration", "frequency regulation"],
        conclusion_template="Flywheel systems excel in high-power, short-duration applications such as frequency regulation.",
        reasoning_framework="""Flywheels store energy in a rotating mass, offering rapid response and high power output. Typical round-trip efficiency is 85%-95%. They are ideal for applications requiring fast discharge and recharge cycles, such as frequency regulation and voltage support. Key factors include material durability, rotational speed, containment safety, and lifecycle cost. Flywheels are less suitable for long-duration storage due to self-discharge. Safety standards must address containment and failure modes. Deployment is often distributed, supporting microgrids and ancillary services.""",
        key_factors=["material durability", "rotational speed", "containment safety", "efficiency", "lifecycle cost"],
        primary_authority=["IEEE", "US DOE", "Sandia National Laboratories"],
        burden_holder="System integrator",
        adversary_position="Concerns about containment failure and limited duration.",
        counter_arguments=["Modern containment designs mitigate risk.", "High efficiency offsets duration limitations.", "Lifecycle cost is competitive for ancillary services."],
        resolution_strategy="Adopt robust containment standards and target high-value ancillary markets.",
        entity_scope="Microgrid operators, ancillary service providers",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IEEE Std 1679.4-2017"
    ),
    DoctrineBlock(
        topic="Supercapacitor and Ultracapacitor Technology",
        keywords=["supercapacitor", "ultracapacitor", "electrochemical storage", "power density", "rapid cycling"],
        conclusion_template="Supercapacitors provide exceptional power density and rapid cycling, but limited energy capacity.",
        reasoning_framework="""Supercapacitors store energy electrostatically, enabling rapid charge/discharge cycles and high power density. They are ideal for bridging power gaps, supporting voltage stabilization, and providing backup power. Energy density is significantly lower than batteries, limiting their use to short-duration applications. Key factors include cycle life, safety, integration with power electronics, and cost. Safety standards focus on voltage management and thermal stability. Supercapacitors are increasingly used in hybrid systems to complement batteries and renewables.""",
        key_factors=["cycle life", "power density", "energy density", "integration", "cost"],
        primary_authority=["IEEE", "US DOE", "IEC"],
        burden_holder="System designer",
        adversary_position="Critics highlight limited energy capacity and cost.",
        counter_arguments=["Hybrid systems leverage strengths of both technologies.", "Long cycle life reduces replacement costs.", "Recent advances improve energy density."],
        resolution_strategy="Integrate supercapacitors in hybrid storage architectures.",
        entity_scope="Power electronics integrators, microgrid operators",
        confidence=0.89,
        confidence_zone="Medium-High",
        controlling_precedent="IEC 62391-1"
    ),
    DoctrineBlock(
        topic="Thermal Energy Storage Systems",
        keywords=["thermal storage", "phase change", "sensible heat", "latent heat", "molten salt"],
        conclusion_template="Thermal energy storage is effective for load shifting and renewable integration, especially in CSP plants.",
        reasoning_framework="""Thermal energy storage (TES) systems store energy as heat, using materials such as molten salt or phase-change substances. TES is widely used in concentrating solar power (CSP) plants to enable dispatchable generation. Efficiency depends on thermal losses, material properties, and integration with power cycles. Key factors include material selection, system insulation, cost, and operational flexibility. Environmental and safety considerations focus on containment and thermal emissions. TES can support both short-term and seasonal storage, depending on system design.""",
        key_factors=["material selection", "insulation", "cost", "efficiency", "operational flexibility"],
        primary_authority=["US DOE", "IEA", "SolarPACES"],
        burden_holder="Plant operator",
        adversary_position="Critics cite thermal losses and high material costs.",
        counter_arguments=["Improved insulation reduces losses.", "Advanced materials lower costs.", "Hybrid systems enhance flexibility."],
        resolution_strategy="Optimize material selection and system design for specific applications.",
        entity_scope="CSP operators, industrial users",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="US DOE CSP Thermal Storage Guidelines"
    ),
    DoctrineBlock(
        topic="Grid-Scale Storage Economics and Optimization",
        keywords=["storage economics", "optimization", "cost-benefit analysis", "market participation", "revenue stacking"],
        conclusion_template="Grid-scale storage economics depend on multi-service revenue stacking and optimized dispatch.",
        reasoning_framework="""Economic viability of grid-scale storage is determined by capital cost, operational cost, revenue streams, and market participation. Revenue stacking—providing multiple services such as energy arbitrage, frequency regulation, and capacity—maximizes returns. Optimization algorithms are used to schedule storage dispatch based on market prices and grid needs. Key factors include regulatory incentives, market access, technology selection, and lifecycle cost. Financial modeling must account for degradation, warranty, and replacement costs. Policy frameworks and market rules significantly impact economic outcomes.""",
        key_factors=["capital cost", "revenue stacking", "optimization", "market access", "policy incentives"],
        primary_authority=["FERC", "US DOE", "NREL"],
        burden_holder="Storage operator",
        adversary_position="Skeptics argue uncertain revenue and high upfront costs.",
        counter_arguments=["Revenue stacking diversifies income.", "Optimization improves profitability.", "Policy incentives reduce risk."],
        resolution_strategy="Develop robust financial models and participate in multiple markets.",
        entity_scope="Storage operators, investors, regulators",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="FERC Order 841"
    ),
    DoctrineBlock(
        topic="Battery Energy Storage System (BESS) Integration",
        keywords=["BESS", "battery storage", "integration", "grid", "inverter", "control systems"],
        conclusion_template="Successful BESS integration requires robust control systems, inverter technology, and grid compatibility.",
        reasoning_framework="""BESS integration involves connecting battery systems to the grid using inverters and advanced control systems. Key factors include battery chemistry, inverter selection, communication protocols, and grid compatibility. Safety standards address fire risk, thermal runaway, and electrical hazards. Integration challenges include managing state-of-charge, degradation, and dispatch optimization. Regulatory compliance is essential, with standards such as UL 9540 and NFPA 855 guiding installation and operation. Hybrid integration with renewables enhances grid flexibility and resilience.""",
        key_factors=["battery chemistry", "inverter technology", "control systems", "safety standards", "regulatory compliance"],
        primary_authority=["UL", "NFPA", "US DOE"],
        burden_holder="System integrator",
        adversary_position="Critics cite safety risks and integration complexity.",
        counter_arguments=["Advanced control systems mitigate risks.", "Compliance with standards ensures safety.", "Hybrid integration improves resilience."],
        resolution_strategy="Adopt best practices in system design and comply with relevant standards.",
        entity_scope="Utility-scale and distributed storage operators",
        confidence=0.96,
        confidence_zone="High",
        controlling_precedent="UL 9540, NFPA 855"
    ),
    DoctrineBlock(
        topic="Hybrid Storage Systems and Multi-Technology Optimization",
        keywords=["hybrid storage", "multi-technology", "optimization", "supercapacitor", "battery", "flywheel"],
        conclusion_template="Hybrid storage systems combine complementary technologies for optimized performance and flexibility.",
        reasoning_framework="""Hybrid storage integrates multiple technologies (e.g., batteries, supercapacitors, flywheels) to leverage their strengths and mitigate weaknesses. Optimization algorithms manage dispatch and cycling to maximize efficiency and lifespan. Key factors include technology selection, control architecture, cost, and operational goals. Hybrid systems are ideal for applications requiring both high power and high energy, such as grid support and renewable integration. Safety and reliability are enhanced through redundancy and intelligent control. Regulatory and market frameworks must accommodate hybrid configurations.""",
        key_factors=["technology selection", "control architecture", "cost", "operational goals", "regulatory compliance"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System designer",
        adversary_position="Critics cite complexity and integration challenges.",
        counter_arguments=["Advanced control systems simplify operation.", "Hybridization improves reliability.", "Market frameworks are evolving to support hybrids."],
        resolution_strategy="Leverage intelligent control and participate in emerging hybrid markets.",
        entity_scope="Grid operators, system designers",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IEEE Std 2030.2-2019"
    ),
    DoctrineBlock(
        topic="Long-Duration Energy Storage (LDES) Technologies",
        keywords=["LDES", "long-duration", "energy storage", "seasonal storage", "multi-day", "hydrogen", "flow batteries"],
        conclusion_template="LDES technologies are essential for deep decarbonization and renewable integration.",
        reasoning_framework="""Long-duration energy storage (LDES) enables storage and dispatch over days to weeks, supporting renewable integration and grid reliability. Technologies include flow batteries, hydrogen storage, CAES, and advanced thermal systems. Key factors are energy density, cost, scalability, and operational flexibility. LDES is critical for balancing seasonal variability and supporting high-renewable grids. Policy support and market mechanisms are evolving to incentivize LDES deployment. Technical challenges include efficiency, degradation, and safety. Demonstration projects are advancing commercial viability.""",
        key_factors=["energy density", "cost", "scalability", "operational flexibility", "policy support"],
        primary_authority=["US DOE", "IEA", "LDES Council"],
        burden_holder="Project developer",
        adversary_position="Critics cite high cost and uncertain market value.",
        counter_arguments=["Policy incentives are increasing.", "Demonstration projects show viability.", "LDES is essential for decarbonization."],
        resolution_strategy="Leverage policy support and participate in demonstration programs.",
        entity_scope="Utility-scale storage developers, policymakers",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="US DOE LDES Initiative"
    ),
    DoctrineBlock(
        topic="Storage Siting and Environmental Considerations",
        keywords=["storage siting", "environmental impact", "land use", "permitting", "community engagement"],
        conclusion_template="Storage siting must balance technical requirements with environmental and community impacts.",
        reasoning_framework="""Siting energy storage projects involves evaluating land use, environmental impact, permitting, and community engagement. Key factors include proximity to grid infrastructure, ecological sensitivity, regulatory compliance, and public acceptance. Environmental assessments address habitat disruption, emissions, and water usage. Community engagement is critical for project approval and long-term success. Regulatory frameworks guide permitting and mitigation measures. Advanced siting tools and GIS analysis optimize location selection.""",
        key_factors=["land use", "environmental impact", "permitting", "community engagement", "regulatory compliance"],
        primary_authority=["EPA", "FERC", "US DOE"],
        burden_holder="Project developer",
        adversary_position="Environmental groups and local communities may oppose projects.",
        counter_arguments=["Comprehensive impact assessments mitigate risks.", "Community engagement builds support.", "Regulatory frameworks guide mitigation."],
        resolution_strategy="Conduct thorough environmental assessments and engage stakeholders early.",
        entity_scope="Developers, regulators, environmental agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="NEPA environmental review process"
    ),
    DoctrineBlock(
        topic="Round-Trip Efficiency Analysis and Optimization",
        keywords=["round-trip efficiency", "energy losses", "optimization", "storage performance", "dispatch"],
        conclusion_template="Optimizing round-trip efficiency is key to maximizing storage value and minimizing losses.",
        reasoning_framework="""Round-trip efficiency measures the ratio of energy output to input, accounting for losses in charging, storage, and discharging. Key factors include technology selection, operational strategy, thermal management, and inverter performance. Optimization involves minimizing losses through intelligent dispatch, advanced materials, and improved system design. Efficiency impacts economic viability and environmental footprint. Standards and testing protocols guide measurement and reporting. Continuous monitoring and adaptive control improve performance over time.""",
        key_factors=["technology selection", "operational strategy", "thermal management", "inverter performance", "system design"],
        primary_authority=["IEEE", "US DOE", "IEC"],
        burden_holder="System operator",
        adversary_position="Critics cite hidden losses and measurement challenges.",
        counter_arguments=["Advanced monitoring reveals losses.", "Optimization algorithms improve efficiency.", "Standards ensure accurate reporting."],
        resolution_strategy="Implement continuous monitoring and adaptive optimization.",
        entity_scope="Storage operators, system designers",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="IEEE Std 1547.9-2021"
    ),
    DoctrineBlock(
        topic="Storage Safety Standards and Fire Protection",
        keywords=["safety standards", "fire protection", "battery storage", "thermal runaway", "NFPA 855"],
        conclusion_template="Adhering to safety standards and fire protection protocols is essential for storage system deployment.",
        reasoning_framework="""Safety standards address risks such as fire, thermal runaway, electrical hazards, and containment failure. Key factors include battery chemistry, system design, fire suppression, and emergency response planning. Standards such as NFPA 855, UL 9540, and IEC 62933 guide installation, operation, and maintenance. Fire protection measures include detection, suppression, and isolation. Regulatory compliance is mandatory, and insurance requirements may apply. Continuous training and risk assessment are critical for safe operation.""",
        key_factors=["battery chemistry", "system design", "fire suppression", "emergency response", "regulatory compliance"],
        primary_authority=["NFPA", "UL", "IEC"],
        burden_holder="System operator",
        adversary_position="Critics cite fire risk and insurance challenges.",
        counter_arguments=["Standards mitigate risks.", "Advanced suppression systems improve safety.", "Training reduces human error."],
        resolution_strategy="Comply with relevant standards and implement robust fire protection.",
        entity_scope="Storage operators, installers, regulators",
        confidence=0.98,
        confidence_zone="Very High",
        controlling_precedent="NFPA 855, UL 9540"
    ),
    DoctrineBlock(
        topic="Storage Interconnection and Grid Integration",
        keywords=["interconnection", "grid integration", "standards", "IEEE 1547", "inverter", "communication protocols"],
        conclusion_template="Storage interconnection must comply with grid standards to ensure safety and reliability.",
        reasoning_framework="""Interconnection involves connecting storage systems to the grid, requiring compliance with standards such as IEEE 1547 and UL 1741. Key factors include inverter performance, communication protocols, protection schemes, and grid compatibility. Regulatory approval is required, and interconnection studies assess impact on grid stability. Integration challenges include managing voltage, frequency, and islanding. Advanced inverters and control systems improve reliability and support ancillary services. Market rules and tariffs impact interconnection economics.""",
        key_factors=["inverter performance", "communication protocols", "protection schemes", "regulatory approval", "grid compatibility"],
        primary_authority=["IEEE", "UL", "FERC"],
        burden_holder="System integrator",
        adversary_position="Critics cite interconnection delays and technical challenges.",
        counter_arguments=["Advanced inverters simplify integration.", "Standards streamline approval.", "Interconnection studies address technical issues."],
        resolution_strategy="Comply with standards and conduct thorough interconnection studies.",
        entity_scope="Storage operators, grid operators, regulators",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="IEEE Std 1547-2018"
    ),
    DoctrineBlock(
        topic="Storage Market Participation and Revenue Stacking",
        keywords=["market participation", "revenue stacking", "ancillary services", "capacity market", "energy arbitrage"],
        conclusion_template="Maximizing storage value requires participation in multiple markets and revenue stacking.",
        reasoning_framework="""Storage systems can participate in energy, capacity, and ancillary service markets, providing multiple revenue streams. Key factors include market access, regulatory approval, technology suitability, and dispatch optimization. Revenue stacking involves providing services such as frequency regulation, voltage support, and energy arbitrage. Market rules and tariffs impact participation and profitability. Advanced control systems enable flexible dispatch and maximize returns. Policy incentives and pilot programs support market entry.""",
        key_factors=["market access", "regulatory approval", "technology suitability", "dispatch optimization", "policy incentives"],
        primary_authority=["FERC", "US DOE", "NREL"],
        burden_holder="Storage operator",
        adversary_position="Critics cite uncertain revenue and market barriers.",
        counter_arguments=["Revenue stacking diversifies income.", "Policy incentives support market entry.", "Advanced control systems optimize dispatch."],
        resolution_strategy="Participate in multiple markets and leverage policy support.",
        entity_scope="Storage operators, investors, regulators",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="FERC Order 841"
    ),
    DoctrineBlock(
        topic="Storage Degradation Modeling and Warranty Structures",
        keywords=["degradation", "modeling", "warranty", "battery life", "replacement cost"],
        conclusion_template="Accurate degradation modeling and robust warranty structures are essential for storage asset management.",
        reasoning_framework="""Degradation modeling predicts performance decline over time, informing maintenance, replacement, and warranty decisions. Key factors include battery chemistry, cycling profile, environmental conditions, and operational strategy. Warranty structures must address performance guarantees, replacement, and liability. Standards guide modeling and reporting, such as IEC 62933. Asset management strategies optimize lifecycle cost and reliability. Insurance and financial modeling incorporate degradation risk. Continuous monitoring improves accuracy and informs warranty claims.""",
        key_factors=["battery chemistry", "cycling profile", "environmental conditions", "operational strategy", "warranty structure"],
        primary_authority=["IEC", "UL", "US DOE"],
        burden_holder="Asset owner",
        adversary_position="Critics cite uncertainty in modeling and warranty enforcement.",
        counter_arguments=["Continuous monitoring improves accuracy.", "Standards guide warranty structures.", "Advanced modeling reduces uncertainty."],
        resolution_strategy="Adopt robust modeling and comply with warranty standards.",
        entity_scope="Asset owners, operators, insurers",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Seasonal and Multi-Day Storage Applications",
        keywords=["seasonal storage", "multi-day", "LDES", "hydrogen", "thermal storage", "grid reliability"],
        conclusion_template="Seasonal and multi-day storage is critical for balancing renewable variability and ensuring grid reliability.",
        reasoning_framework="""Seasonal and multi-day storage enables energy shifting over extended periods, supporting high-renewable grids and decarbonization. Technologies include hydrogen, flow batteries, CAES, and advanced thermal systems. Key factors are energy density, cost, scalability, and operational flexibility. Policy support and market mechanisms are evolving to incentivize deployment. Technical challenges include efficiency, degradation, and safety. Demonstration projects are advancing commercial viability and informing regulatory frameworks.""",
        key_factors=["energy density", "cost", "scalability", "operational flexibility", "policy support"],
        primary_authority=["US DOE", "IEA", "LDES Council"],
        burden_holder="Project developer",
        adversary_position="Critics cite high cost and uncertain market value.",
        counter_arguments=["Policy incentives are increasing.", "Demonstration projects show viability.", "Seasonal storage is essential for decarbonization."],
        resolution_strategy="Leverage policy support and participate in demonstration programs.",
        entity_scope="Utility-scale storage developers, policymakers",
        confidence=0.89,
        confidence_zone="Medium-High",
        controlling_precedent="US DOE LDES Initiative"
    ),
    DoctrineBlock(
        topic="Distributed vs. Centralized Storage Deployment",
        keywords=["distributed storage", "centralized storage", "deployment", "microgrid", "utility-scale", "resilience"],
        conclusion_template="Both distributed and centralized storage have unique advantages and deployment considerations.",
        reasoning_framework="""Distributed storage involves deploying smaller systems at multiple locations, supporting microgrids and local resilience. Centralized storage aggregates capacity at a single site, enabling bulk energy shifting and grid support. Key factors include cost, scalability, grid impact, and operational flexibility. Distributed storage enhances resilience and supports renewable integration, while centralized storage maximizes economies of scale. Regulatory frameworks and market rules impact deployment strategies. Hybrid approaches combine strengths of both models.""",
        key_factors=["cost", "scalability", "grid impact", "operational flexibility", "regulatory framework"],
        primary_authority=["US DOE", "FERC", "NREL"],
        burden_holder="Project developer",
        adversary_position="Critics cite complexity and cost trade-offs.",
        counter_arguments=["Hybrid models leverage strengths.", "Distributed storage enhances resilience.", "Centralized storage supports bulk shifting."],
        resolution_strategy="Evaluate site-specific needs and adopt hybrid deployment where feasible.",
        entity_scope="Developers, grid operators, policymakers",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="FERC Order 2222"
    ),
    DoctrineBlock(
        topic="Storage and Renewable Integration Strategies",
        keywords=["renewable integration", "storage", "solar", "wind", "dispatch", "grid flexibility"],
        conclusion_template="Storage is essential for integrating renewables and enhancing grid flexibility.",
        reasoning_framework="""Storage systems enable renewable integration by mitigating variability, enabling dispatchable generation, and providing ancillary services. Key factors include technology selection, dispatch strategy, grid compatibility, and policy support. Integration challenges include forecasting, scheduling, and managing state-of-charge. Hybrid systems and advanced control architectures improve performance. Regulatory frameworks and market incentives support integration. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology selection", "dispatch strategy", "grid compatibility", "policy support", "forecasting"],
        primary_authority=["US DOE", "IEA", "NREL"],
        burden_holder="System operator",
        adversary_position="Critics cite integration complexity and cost.",
        counter_arguments=["Advanced control systems simplify integration.", "Policy incentives support deployment.", "Hybrid systems enhance flexibility."],
        resolution_strategy="Adopt advanced control and participate in policy-supported programs.",
        entity_scope="Grid operators, renewable developers",
        confidence=0.94,
        confidence_zone="High",
        controlling_precedent="US DOE Storage Integration Guidelines"
    ),
    DoctrineBlock(
        topic="Electrochemical Battery Chemistry Selection",
        keywords=["battery chemistry", "lithium-ion", "flow battery", "lead-acid", "performance", "cost"],
        conclusion_template="Selecting appropriate battery chemistry is critical for optimizing storage performance and cost.",
        reasoning_framework="""Battery chemistry impacts energy density, cycle life, safety, cost, and operational flexibility. Lithium-ion is dominant for high energy and power, while flow batteries offer scalability and long-duration storage. Lead-acid is cost-effective for short-duration, low-power applications. Key factors include application requirements, safety, environmental impact, and lifecycle cost. Standards guide selection and integration. Emerging chemistries such as sodium-ion and solid-state batteries offer new opportunities.""",
        key_factors=["energy density", "cycle life", "safety", "cost", "application requirements"],
        primary_authority=["US DOE", "IEC", "UL"],
        burden_holder="System designer",
        adversary_position="Critics cite safety and environmental concerns.",
        counter_arguments=["Advanced chemistries improve safety.", "Lifecycle analysis informs selection.", "Standards guide integration."],
        resolution_strategy="Match chemistry to application and comply with relevant standards.",
        entity_scope="System designers, operators",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Battery Management System (BMS) Design and Operation",
        keywords=["BMS", "battery management", "state-of-charge", "thermal management", "safety"],
        conclusion_template="Robust BMS design is essential for safe, reliable, and efficient battery operation.",
        reasoning_framework="""Battery Management Systems (BMS) monitor and control battery state-of-charge, temperature, and health. Key factors include sensor accuracy, communication protocols, safety features, and integration with control systems. BMS prevents overcharging, thermal runaway, and degradation. Standards guide design and operation, such as UL 1973 and IEC 62933. Advanced BMS architectures enable predictive maintenance and real-time optimization. Continuous monitoring and adaptive control improve performance and safety.""",
        key_factors=["sensor accuracy", "communication protocols", "safety features", "integration", "predictive maintenance"],
        primary_authority=["UL", "IEC", "US DOE"],
        burden_holder="System operator",
        adversary_position="Critics cite complexity and reliability concerns.",
        counter_arguments=["Advanced BMS improves reliability.", "Standards guide design.", "Predictive maintenance reduces risk."],
        resolution_strategy="Adopt advanced BMS and comply with relevant standards.",
        entity_scope="Battery operators, system designers",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="UL 1973, IEC 62933"
    ),
    DoctrineBlock(
        topic="Energy Storage Asset Lifecycle Management",
        keywords=["asset management", "lifecycle", "maintenance", "replacement", "performance monitoring"],
        conclusion_template="Effective asset lifecycle management maximizes storage value and reliability.",
        reasoning_framework="""Asset lifecycle management involves planning, monitoring, maintenance, and replacement of storage systems. Key factors include performance monitoring, degradation modeling, maintenance scheduling, and warranty management. Standards guide asset management, such as IEC 62933. Financial modeling incorporates lifecycle cost and replacement risk. Continuous monitoring and predictive maintenance improve reliability and reduce downtime. Insurance and asset tracking support risk management and compliance.""",
        key_factors=["performance monitoring", "degradation modeling", "maintenance scheduling", "warranty management", "financial modeling"],
        primary_authority=["IEC", "US DOE", "UL"],
        burden_holder="Asset owner",
        adversary_position="Critics cite complexity and cost.",
        counter_arguments=["Predictive maintenance reduces downtime.", "Standards guide asset management.", "Financial modeling optimizes cost."],
        resolution_strategy="Adopt best practices and comply with asset management standards.",
        entity_scope="Asset owners, operators, insurers",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Cybersecurity",
        keywords=["cybersecurity", "storage system", "control systems", "data integrity", "NERC CIP"],
        conclusion_template="Cybersecurity is critical for protecting storage systems and ensuring grid reliability.",
        reasoning_framework="""Storage systems are increasingly connected and vulnerable to cyber threats. Key factors include control system security, data integrity, access management, and compliance with standards such as NERC CIP. Cybersecurity measures include encryption, intrusion detection, and incident response planning. Regulatory frameworks mandate compliance and reporting. Continuous monitoring and vulnerability assessment are essential. Training and awareness programs reduce human error and improve resilience.""",
        key_factors=["control system security", "data integrity", "access management", "regulatory compliance", "incident response"],
        primary_authority=["NERC", "US DOE", "FERC"],
        burden_holder="System operator",
        adversary_position="Critics cite complexity and cost.",
        counter_arguments=["Regulatory compliance is mandatory.", "Continuous monitoring improves resilience.", "Training reduces risk."],
        resolution_strategy="Adopt cybersecurity best practices and comply with relevant standards.",
        entity_scope="Storage operators, grid operators",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="NERC CIP standards"
    ),
    DoctrineBlock(
        topic="Energy Storage System Reliability and Redundancy",
        keywords=["reliability", "redundancy", "storage system", "backup", "failure modes"],
        conclusion_template="Reliability and redundancy are essential for mission-critical storage applications.",
        reasoning_framework="""Reliability is achieved through robust system design, redundancy, and continuous monitoring. Key factors include backup systems, failure mode analysis, maintenance scheduling, and operational flexibility. Standards guide reliability assessment, such as IEC 62933. Redundancy improves resilience and supports mission-critical applications. Predictive maintenance and real-time monitoring reduce downtime. Insurance and asset tracking support risk management. Regulatory frameworks may require reliability guarantees for certain applications.""",
        key_factors=["backup systems", "failure mode analysis", "maintenance scheduling", "operational flexibility", "predictive maintenance"],
        primary_authority=["IEC", "US DOE", "UL"],
        burden_holder="System operator",
        adversary_position="Critics cite cost and complexity.",
        counter_arguments=["Redundancy improves resilience.", "Predictive maintenance reduces downtime.", "Standards guide reliability assessment."],
        resolution_strategy="Adopt redundancy and comply with reliability standards.",
        entity_scope="Mission-critical storage operators, asset owners",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Insurance and Risk Management",
        keywords=["insurance", "risk management", "storage system", "liability", "asset protection"],
        conclusion_template="Insurance and risk management are essential for protecting storage assets and mitigating liability.",
        reasoning_framework="""Insurance covers risks such as fire, failure, liability, and business interruption. Key factors include asset value, risk assessment, compliance with safety standards, and operational history. Risk management involves continuous monitoring, maintenance, and compliance with regulatory frameworks. Insurance requirements may impact project financing and deployment. Standards guide risk assessment and reporting. Asset tracking and incident response planning improve risk mitigation.""",
        key_factors=["asset value", "risk assessment", "safety standards", "operational history", "incident response"],
        primary_authority=["UL", "IEC", "US DOE"],
        burden_holder="Asset owner",
        adversary_position="Critics cite cost and complexity.",
        counter_arguments=["Insurance is required for financing.", "Risk management reduces liability.", "Standards guide risk assessment."],
        resolution_strategy="Adopt robust risk management and comply with insurance requirements.",
        entity_scope="Asset owners, operators, insurers",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="UL 9540, IEC 62933"
    ),
    DoctrineBlock(
        topic="Energy Storage System Performance Monitoring and Reporting",
        keywords=["performance monitoring", "reporting", "storage system", "data analytics", "standards"],
        conclusion_template="Continuous performance monitoring and standardized reporting improve asset management and compliance.",
        reasoning_framework="""Performance monitoring involves collecting and analyzing data on storage system operation, efficiency, and degradation. Key factors include sensor accuracy, data analytics, reporting standards, and compliance. Standards guide data collection and reporting, such as IEC 62933. Continuous monitoring enables predictive maintenance and informs asset management decisions. Regulatory frameworks may require performance reporting for compliance and warranty claims. Data analytics improve operational efficiency and reliability.""",
        key_factors=["sensor accuracy", "data analytics", "reporting standards", "compliance", "predictive maintenance"],
        primary_authority=["IEC", "US DOE", "UL"],
        burden_holder="System operator",
        adversary_position="Critics cite data complexity and reporting burden.",
        counter_arguments=["Data analytics simplify reporting.", "Standards guide data collection.", "Continuous monitoring improves reliability."],
        resolution_strategy="Adopt advanced monitoring and comply with reporting standards.",
        entity_scope="System operators, asset owners",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Financing and Investment",
        keywords=["financing", "investment", "storage system", "project risk", "capital cost"],
        conclusion_template="Financing and investment strategies are critical for successful storage project deployment.",
        reasoning_framework="""Financing involves securing capital, managing project risk, and optimizing returns. Key factors include capital cost, revenue streams, risk assessment, and policy incentives. Investment strategies may include debt, equity, and public-private partnerships. Insurance and risk management impact financing terms. Regulatory frameworks and market rules affect project economics. Financial modeling incorporates lifecycle cost, degradation, and replacement risk. Policy incentives and pilot programs support investment and reduce risk.""",
        key_factors=["capital cost", "revenue streams", "risk assessment", "policy incentives", "financial modeling"],
        primary_authority=["US DOE", "FERC", "NREL"],
        burden_holder="Project developer",
        adversary_position="Critics cite high capital cost and uncertain returns.",
        counter_arguments=["Policy incentives reduce risk.", "Financial modeling optimizes returns.", "Insurance supports financing."],
        resolution_strategy="Leverage policy incentives and adopt robust financial modeling.",
        entity_scope="Developers, investors, financiers",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="US DOE Storage Financing Guidelines"
    ),
    DoctrineBlock(
        topic="Energy Storage System Policy and Regulatory Frameworks",
        keywords=["policy", "regulatory", "storage system", "market rules", "incentives"],
        conclusion_template="Policy and regulatory frameworks shape storage deployment, economics, and market participation.",
        reasoning_framework="""Policy frameworks include incentives, mandates, and market rules that impact storage deployment. Key factors include regulatory approval, market access, technology eligibility, and compliance. Incentives such as tax credits, grants, and pilot programs support deployment. Regulatory frameworks guide permitting, interconnection, and safety. Market rules impact participation and profitability. Policy evolution is driven by decarbonization goals and grid modernization. Stakeholder engagement informs policy development and implementation.""",
        key_factors=["regulatory approval", "market access", "technology eligibility", "incentives", "stakeholder engagement"],
        primary_authority=["FERC", "US DOE", "NREL"],
        burden_holder="Project developer",
        adversary_position="Critics cite regulatory uncertainty and market barriers.",
        counter_arguments=["Policy incentives support deployment.", "Stakeholder engagement informs policy.", "Regulatory frameworks are evolving."],
        resolution_strategy="Engage stakeholders and participate in policy-supported programs.",
        entity_scope="Developers, policymakers, regulators",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="FERC Order 841, US DOE Storage Policy Guidelines"
    ),
    DoctrineBlock(
        topic="Energy Storage System Technology Selection and Evaluation",
        keywords=["technology selection", "evaluation", "storage system", "performance", "cost"],
        conclusion_template="Selecting appropriate storage technology is critical for optimizing performance and cost.",
        reasoning_framework="""Technology selection involves evaluating performance, cost, scalability, and application requirements. Key factors include energy density, power output, cycle life, safety, and regulatory compliance. Standards guide evaluation and integration, such as IEC 62933. Financial modeling incorporates lifecycle cost and replacement risk. Application requirements determine technology suitability. Emerging technologies offer new opportunities for performance and cost optimization.""",
        key_factors=["energy density", "power output", "cycle life", "safety", "application requirements"],
        primary_authority=["US DOE", "IEC", "UL"],
        burden_holder="System designer",
        adversary_position="Critics cite complexity and uncertainty.",
        counter_arguments=["Standards guide evaluation.", "Financial modeling optimizes selection.", "Emerging technologies improve performance."],
        resolution_strategy="Match technology to application and comply with relevant standards.",
        entity_scope="System designers, operators",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Environmental Impact Assessment",
        keywords=["environmental impact", "assessment", "storage system", "permitting", "NEPA"],
        conclusion_template="Comprehensive environmental impact assessment is essential for storage project permitting and approval.",
        reasoning_framework="""Environmental impact assessment evaluates effects on land, water, air, and ecosystems. Key factors include site selection, permitting, regulatory compliance, and community engagement. Standards guide assessment and reporting, such as NEPA. Mitigation measures address habitat disruption, emissions, and water usage. Community engagement is critical for project approval and long-term success. Regulatory frameworks guide permitting and mitigation. Advanced siting tools and GIS analysis optimize location selection.""",
        key_factors=["site selection", "permitting", "regulatory compliance", "mitigation", "community engagement"],
        primary_authority=["EPA", "FERC", "US DOE"],
        burden_holder="Project developer",
        adversary_position="Environmental groups and local communities may oppose projects.",
        counter_arguments=["Comprehensive impact assessments mitigate risks.", "Community engagement builds support.", "Regulatory frameworks guide mitigation."],
        resolution_strategy="Conduct thorough environmental assessments and engage stakeholders early.",
        entity_scope="Developers, regulators, environmental agencies",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="NEPA environmental review process"
    ),
    DoctrineBlock(
        topic="Energy Storage System Operations and Maintenance",
        keywords=["operations", "maintenance", "storage system", "predictive maintenance", "downtime"],
        conclusion_template="Effective operations and maintenance maximize storage reliability and minimize downtime.",
        reasoning_framework="""Operations and maintenance involve scheduling, monitoring, and repair of storage systems. Key factors include predictive maintenance, performance monitoring, spare parts management, and compliance with standards. Standards guide maintenance and reporting, such as IEC 62933. Predictive maintenance reduces downtime and improves reliability. Asset tracking and incident response planning support risk management. Continuous training and performance analytics improve operational efficiency.""",
        key_factors=["predictive maintenance", "performance monitoring", "spare parts management", "compliance", "training"],
        primary_authority=["IEC", "US DOE", "UL"],
        burden_holder="System operator",
        adversary_position="Critics cite complexity and cost.",
        counter_arguments=["Predictive maintenance reduces downtime.", "Standards guide maintenance.", "Training improves efficiency."],
        resolution_strategy="Adopt predictive maintenance and comply with relevant standards.",
        entity_scope="System operators, asset owners",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Data Analytics and Optimization",
        keywords=["data analytics", "optimization", "storage system", "performance", "dispatch"],
        conclusion_template="Advanced data analytics and optimization improve storage performance and economic returns.",
        reasoning_framework="""Data analytics enable real-time monitoring, predictive maintenance, and dispatch optimization. Key factors include sensor accuracy, data integration, analytics platforms, and compliance with reporting standards. Optimization algorithms improve efficiency, reduce degradation, and maximize economic returns. Standards guide data collection and reporting, such as IEC 62933. Continuous monitoring and adaptive control improve performance over time. Data analytics inform asset management and warranty claims.""",
        key_factors=["sensor accuracy", "data integration", "analytics platforms", "optimization algorithms", "compliance"],
        primary_authority=["IEC", "US DOE", "UL"],
        burden_holder="System operator",
        adversary_position="Critics cite data complexity and integration challenges.",
        counter_arguments=["Analytics platforms simplify integration.", "Optimization improves returns.", "Standards guide data reporting."],
        resolution_strategy="Adopt advanced analytics and comply with reporting standards.",
        entity_scope="System operators, asset owners",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
    DoctrineBlock(
        topic="Energy Storage System Standards and Certification",
        keywords=["standards", "certification", "storage system", "UL", "IEC"],
        conclusion_template="Compliance with standards and certification is essential for storage system deployment and market access.",
        reasoning_framework="""Standards and certification guide design, installation, operation, and maintenance of storage systems. Key factors include safety, performance, interoperability, and regulatory compliance. Standards such as UL 9540, IEC 62933, and NFPA 855 address fire protection, electrical safety, and performance. Certification is required for market access and financing. Regulatory frameworks mandate compliance and reporting. Continuous training and certification improve reliability and safety.""",
        key_factors=["safety", "performance", "interoperability", "regulatory compliance", "certification"],
        primary_authority=["UL", "IEC", "NFPA"],
        burden_holder="System operator",
        adversary_position="Critics cite cost and complexity.",
        counter_arguments=["Certification is required for market access.", "Standards improve safety.", "Training enhances reliability."],
        resolution_strategy="Comply with relevant standards and obtain certification.",
        entity_scope="System operators, installers, regulators",
        confidence=0.95,
        confidence_zone="High",
        controlling_precedent="UL 9540, IEC 62933, NFPA 855"
    ),
    DoctrineBlock(
        topic="Energy Storage System Workforce Training and Development",
        keywords=["workforce training", "development", "storage system", "safety", "certification"],
        conclusion_template="Continuous workforce training and development improve storage system safety and reliability.",
        reasoning_framework="""Workforce training involves education, certification, and continuous learning for storage system operators and installers. Key factors include safety, performance, regulatory compliance, and certification. Standards guide training and certification, such as UL 9540 and IEC 62933. Continuous training improves reliability and reduces human error. Regulatory frameworks may mandate training for certain applications. Training programs support workforce development and market growth.""",
        key_factors=["safety", "performance", "regulatory compliance", "certification", "continuous learning"],
        primary_authority=["UL", "IEC", "US DOE"],
        burden_holder="System operator",
        adversary_position="Critics cite cost and time burden.",
        counter_arguments=["Training improves safety.", "Certification supports market access.", "Continuous learning enhances reliability."],
        resolution_strategy="Adopt training programs and comply with certification requirements.",
        entity_scope="System operators, installers, regulators",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="UL 9540, IEC 62933"
    ),
    DoctrineBlock(
        topic="Energy Storage System Incident Response and Recovery",
        keywords=["incident response", "recovery", "storage system", "fire", "failure"],
        conclusion_template="Robust incident response and recovery protocols are essential for minimizing storage system downtime and liability.",
        reasoning_framework="""Incident response involves planning, detection, suppression, and recovery from events such as fire, failure, or cyberattack. Key factors include emergency response planning, detection systems, suppression technology, and recovery protocols. Standards guide response and reporting, such as NFPA 855 and UL 9540. Insurance and risk management support recovery and liability mitigation. Continuous training and incident drills improve response effectiveness. Regulatory frameworks may mandate incident response planning.""",
        key_factors=["emergency response", "detection systems", "suppression technology", "recovery protocols", "insurance"],
        primary_authority=["NFPA", "UL", "US DOE"],
        burden_holder="System operator",
        adversary_position="Critics cite cost and complexity.",
        counter_arguments=["Insurance supports recovery.", "Training improves response.", "Standards guide planning."],
        resolution_strategy="Adopt robust incident response protocols and comply with relevant standards.",
        entity_scope="System operators, asset owners, insurers",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="NFPA 855, UL 9540"
    ),
    DoctrineBlock(
        topic="Energy Storage System Community Engagement and Stakeholder Management",
        keywords=["community engagement", "stakeholder management", "storage system", "permitting", "public acceptance"],
        conclusion_template="Community engagement and stakeholder management are essential for successful storage project deployment.",
        reasoning_framework="""Community engagement involves informing, consulting, and collaborating with stakeholders and local communities. Key factors include transparency, public acceptance, regulatory compliance, and mitigation of environmental and social impacts. Standards guide engagement and reporting, such as NEPA. Early engagement builds support and reduces opposition. Regulatory frameworks mandate stakeholder consultation for permitting and approval. Continuous communication and feedback improve project outcomes and long-term success.""",
        key_factors=["transparency", "public acceptance", "regulatory compliance", "mitigation", "communication"],
        primary_authority=["EPA", "FERC", "US DOE"],
        burden_holder="Project developer",
        adversary_position="Local communities and environmental groups may oppose projects.",
        counter_arguments=["Early engagement builds support.", "Regulatory frameworks guide consultation.", "Mitigation measures address concerns."],
        resolution_strategy="Engage stakeholders early and comply with consultation requirements.",
        entity_scope="Developers, regulators, communities",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="NEPA stakeholder engagement process"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Electric Vehicle Infrastructure",
        keywords=["EV integration", "storage system", "electric vehicle", "charging", "grid impact"],
        conclusion_template="Storage system integration with EV infrastructure enhances grid flexibility and supports decarbonization.",
        reasoning_framework="""Integrating storage systems with EV infrastructure enables managed charging, demand response, and grid support. Key factors include technology compatibility, communication protocols, regulatory compliance, and market incentives. Storage systems can support fast charging, reduce grid impact, and enable vehicle-to-grid (V2G) services. Standards guide integration and operation, such as IEEE 2030. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "communication protocols", "regulatory compliance", "market incentives", "V2G services"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System integrator",
        adversary_position="Critics cite integration complexity and cost.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "V2G services enhance flexibility."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="EV operators, storage integrators, grid operators",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IEEE Std 2030.1.1-2021"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Distributed Energy Resources (DER)",
        keywords=["DER integration", "storage system", "distributed energy", "solar", "microgrid"],
        conclusion_template="Storage system integration with DER enhances grid resilience and supports renewable deployment.",
        reasoning_framework="""Integrating storage with distributed energy resources (DER) enables local energy management, resilience, and renewable integration. Key factors include technology compatibility, communication protocols, regulatory compliance, and market incentives. Storage supports microgrids, demand response, and peak shaving. Standards guide integration and operation, such as IEEE 1547. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "communication protocols", "regulatory compliance", "market incentives", "microgrid support"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System integrator",
        adversary_position="Critics cite integration complexity and cost.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "Microgrids enhance resilience."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="DER operators, storage integrators, grid operators",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEEE Std 1547-2018"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Renewable Hydrogen",
        keywords=["hydrogen integration", "storage system", "renewable hydrogen", "LDES", "grid support"],
        conclusion_template="Integration with renewable hydrogen enables long-duration storage and supports decarbonization.",
        reasoning_framework="""Storage system integration with renewable hydrogen enables long-duration energy shifting, grid support, and decarbonization. Key factors include technology compatibility, regulatory compliance, cost, and operational flexibility. Hydrogen storage supports seasonal and multi-day applications. Standards guide integration and operation, such as IEC 62282. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "regulatory compliance", "cost", "operational flexibility", "policy incentives"],
        primary_authority=["IEC", "US DOE", "IEA"],
        burden_holder="Project developer",
        adversary_position="Critics cite cost and integration complexity.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "Hydrogen enables long-duration storage."],
        resolution_strategy="Leverage policy support and comply with integration standards.",
        entity_scope="Hydrogen producers, storage developers, grid operators",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="IEC 62282"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Grid Modernization Initiatives",
        keywords=["grid modernization", "storage system", "smart grid", "advanced metering", "demand response"],
        conclusion_template="Storage system integration is central to grid modernization and supports advanced grid services.",
        reasoning_framework="""Grid modernization initiatives include smart grid deployment, advanced metering, and demand response programs. Storage system integration enables flexible dispatch, supports ancillary services, and improves reliability. Key factors include technology compatibility, communication protocols, regulatory compliance, and market incentives. Standards guide integration and operation, such as IEEE 2030. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "communication protocols", "regulatory compliance", "market incentives", "smart grid support"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System integrator",
        adversary_position="Critics cite integration complexity and cost.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "Smart grid improves reliability."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="Grid operators, storage integrators, policymakers",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEEE Std 2030-2015"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Demand Response Programs",
        keywords=["demand response", "storage system", "grid support", "dispatch", "market participation"],
        conclusion_template="Storage system integration with demand response programs enhances grid flexibility and supports market participation.",
        reasoning_framework="""Integrating storage with demand response programs enables flexible dispatch, peak shaving, and grid support. Key factors include technology compatibility, communication protocols, regulatory compliance, and market incentives. Storage systems can participate in demand response markets, providing revenue stacking and ancillary services. Standards guide integration and operation, such as IEEE 2030. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "communication protocols", "regulatory compliance", "market incentives", "dispatch optimization"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System operator",
        adversary_position="Critics cite integration complexity and uncertain revenue.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "Demand response improves flexibility."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="Storage operators, demand response aggregators, grid operators",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IEEE Std 2030-2015"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Utility Rate Structures",
        keywords=["utility rate structure", "storage system", "tariff", "market participation", "cost optimization"],
        conclusion_template="Storage system integration with utility rate structures enables cost optimization and market participation.",
        reasoning_framework="""Integrating storage with utility rate structures enables cost optimization through time-of-use tariffs, demand charges, and market participation. Key factors include tariff design, regulatory compliance, technology compatibility, and dispatch optimization. Storage systems can participate in energy and capacity markets, providing revenue stacking and ancillary services. Standards guide integration and operation, such as IEEE 2030. Policy incentives support deployment and market growth. Financial modeling informs cost optimization and market participation.""",
        key_factors=["tariff design", "regulatory compliance", "technology compatibility", "dispatch optimization", "financial modeling"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System operator",
        adversary_position="Critics cite complexity and uncertain returns.",
        counter_arguments=["Financial modeling optimizes cost.", "Policy incentives support deployment.", "Standards guide integration."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="Storage operators, utilities, regulators",
        confidence=0.90,
        confidence_zone="Medium-High",
        controlling_precedent="IEEE Std 2030-2015"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Microgrid Applications",
        keywords=["microgrid", "storage system", "resilience", "renewable integration", "grid support"],
        conclusion_template="Storage system integration with microgrid applications enhances resilience and supports renewable deployment.",
        reasoning_framework="""Integrating storage with microgrid applications enables local energy management, resilience, and renewable integration. Key factors include technology compatibility, communication protocols, regulatory compliance, and market incentives. Storage supports demand response, peak shaving, and grid support. Standards guide integration and operation, such as IEEE 1547. Policy incentives support deployment and market growth. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["technology compatibility", "communication protocols", "regulatory compliance", "market incentives", "resilience"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System integrator",
        adversary_position="Critics cite integration complexity and cost.",
        counter_arguments=["Policy incentives support deployment.", "Standards guide integration.", "Microgrids enhance resilience."],
        resolution_strategy="Adopt best practices and comply with integration standards.",
        entity_scope="Microgrid operators, storage integrators, grid operators",
        confidence=0.92,
        confidence_zone="High",
        controlling_precedent="IEEE Std 1547-2018"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Advanced Control Architectures",
        keywords=["advanced control", "storage system", "optimization", "dispatch", "grid support"],
        conclusion_template="Advanced control architectures optimize storage dispatch and improve grid support.",
        reasoning_framework="""Advanced control architectures enable real-time optimization, flexible dispatch, and improved grid support. Key factors include control system design, communication protocols, regulatory compliance, and technology compatibility. Optimization algorithms improve efficiency, reduce degradation, and maximize economic returns. Standards guide control system design and operation, such as IEEE 2030. Continuous monitoring and adaptive control improve performance over time. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["control system design", "communication protocols", "regulatory compliance", "optimization algorithms", "continuous monitoring"],
        primary_authority=["IEEE", "US DOE", "NREL"],
        burden_holder="System operator",
        adversary_position="Critics cite complexity and integration challenges.",
        counter_arguments=["Optimization improves returns.", "Standards guide control system design.", "Continuous monitoring improves performance."],
        resolution_strategy="Adopt advanced control architectures and comply with relevant standards.",
        entity_scope="Storage operators, grid operators, system designers",
        confidence=0.93,
        confidence_zone="High",
        controlling_precedent="IEEE Std 2030-2015"
    ),
    DoctrineBlock(
        topic="Energy Storage System Integration with Artificial Intelligence and Machine Learning",
        keywords=["AI", "machine learning", "storage system", "optimization", "predictive maintenance"],
        conclusion_template="AI and machine learning integration optimize storage performance and enable predictive maintenance.",
        reasoning_framework="""AI and machine learning enable real-time optimization, predictive maintenance, and improved asset management for storage systems. Key factors include data quality, algorithm selection, integration with control systems, and regulatory compliance. AI improves efficiency, reduces degradation, and maximizes economic returns. Standards guide data collection and reporting, such as IEC 62933. Continuous monitoring and adaptive control improve performance over time. Demonstration projects inform best practices and commercial viability.""",
        key_factors=["data quality", "algorithm selection", "integration", "regulatory compliance", "continuous monitoring"],
        primary_authority=["IEC", "US DOE", "NREL"],
        burden_holder="System operator",
        adversary_position="Critics cite data complexity and integration challenges.",
        counter_arguments=["AI improves optimization.", "Predictive maintenance reduces downtime.", "Standards guide data reporting."],
        resolution_strategy="Adopt AI and machine learning and comply with reporting standards.",
        entity_scope="System operators, asset owners",
        confidence=0.91,
        confidence_zone="High",
        controlling_precedent="IEC 62933-2-1"
    ),
]

def get_doctrine_by_topic(topic: str) -> Optional[DoctrineBlock]:
    for doctrine in DOCTRINE_CACHE:
        if doctrine.topic.lower() == topic.lower():
            return doctrine
    return None

def search_doctrines(keyword: str) -> List[DoctrineBlock]:
    keyword_lower = keyword.lower()
    results = []
    for doctrine in DOCTRINE_CACHE:
        if keyword_lower in doctrine.topic.lower() or any(keyword_lower in k.lower() for k in doctrine.keywords):
            results.append(doctrine)
    return results

def get_all_topics() -> List[str]:
    return [doctrine.topic for doctrine in DOCTRINE_CACHE]