import hashlib
import re
from typing import Dict, List

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "ENRG12 Python Team"
SEMANTIC_MAP_ENGINE = "ENRG12_energy_storage"

# Domain terms and their normalized forms
SEMANTIC_MAP = {
    # Pumped Hydro Storage Fundamentals
    "pumped hydro storage": "pumped_hydro_storage",
    "phs": "pumped_hydro_storage",
    "pumped hydro": "pumped_hydro_storage",
    "hydroelectric storage": "pumped_hydro_storage",
    "hydro storage": "pumped_hydro_storage",
    "hydro energy storage": "pumped_hydro_storage",
    "hydro power storage": "pumped_hydro_storage",
    "water reservoir storage": "pumped_hydro_storage",
    "gravity storage": "pumped_hydro_storage",
    "pumped storage": "pumped_hydro_storage",
    "pumped hydroelectric": "pumped_hydro_storage",
    "phs system": "pumped_hydro_storage",
    "phs plant": "pumped_hydro_storage",
    "phs technology": "pumped_hydro_storage",
    "pumped hydroelectric storage": "pumped_hydro_storage",
    "pumped hydro energy storage": "pumped_hydro_storage",
    "pumped hydro power": "pumped_hydro_storage",
    "water storage": "pumped_hydro_storage",
    "hydro pumped storage": "pumped_hydro_storage",
    "hydro pumped energy": "pumped_hydro_storage",
    "hydro pumped": "pumped_hydro_storage",
    "hydro pump storage": "pumped_hydro_storage",
    "hydro pump": "pumped_hydro_storage",
    "phs fundamentals": "pumped_hydro_storage",
    "phs basics": "pumped_hydro_storage",
    "phs principle": "pumped_hydro_storage",
    "phs operation": "pumped_hydro_storage",
    "phs efficiency": "pumped_hydro_storage",
    "phs economics": "pumped_hydro_storage",
    "phs optimization": "pumped_hydro_storage",
    "phs siting": "pumped_hydro_storage",
    "phs environmental": "pumped_hydro_storage",
    "phs round-trip efficiency": "pumped_hydro_storage",
    "phs safety": "pumped_hydro_storage",
    "phs integration": "pumped_hydro_storage",
    "phs market": "pumped_hydro_storage",
    "phs degradation": "pumped_hydro_storage",
    "phs warranty": "pumped_hydro_storage",
    "phs seasonal": "pumped_hydro_storage",
    "phs distributed": "pumped_hydro_storage",
    "phs centralized": "pumped_hydro_storage",
    "phs renewable integration": "pumped_hydro_storage",

    # Compressed Air Energy Storage (CAES) Technology
    "compressed air energy storage": "caes",
    "caes": "caes",
    "compressed air storage": "caes",
    "compressed air": "caes",
    "caes system": "caes",
    "caes plant": "caes",
    "caes technology": "caes",
    "caes fundamentals": "caes",
    "caes basics": "caes",
    "caes principle": "caes",
    "caes operation": "caes",
    "caes efficiency": "caes",
    "caes economics": "caes",
    "caes optimization": "caes",
    "caes siting": "caes",
    "caes environmental": "caes",
    "caes round-trip efficiency": "caes",
    "caes safety": "caes",
    "caes integration": "caes",
    "caes market": "caes",
    "caes degradation": "caes",
    "caes warranty": "caes",
    "caes seasonal": "caes",
    "caes distributed": "caes",
    "caes centralized": "caes",
    "caes renewable integration": "caes",
    "compressed air plant": "caes",
    "compressed air technology": "caes",
    "compressed air fundamentals": "caes",
    "compressed air basics": "caes",
    "compressed air principle": "caes",
    "compressed air operation": "caes",
    "compressed air efficiency": "caes",
    "compressed air economics": "caes",
    "compressed air optimization": "caes",
    "compressed air siting": "caes",
    "compressed air environmental": "caes",
    "compressed air round-trip efficiency": "caes",
    "compressed air safety": "caes",
    "compressed air integration": "caes",
    "compressed air market": "caes",
    "compressed air degradation": "caes",
    "compressed air warranty": "caes",
    "compressed air seasonal": "caes",
    "compressed air distributed": "caes",
    "compressed air centralized": "caes",
    "compressed air renewable integration": "caes",

    # Flywheel Energy Storage Systems
    "flywheel energy storage": "flywheel",
    "flywheel storage": "flywheel",
    "flywheel": "flywheel",
    "flywheel system": "flywheel",
    "flywheel technology": "flywheel",
    "flywheel fundamentals": "flywheel",
    "flywheel basics": "flywheel",
    "flywheel principle": "flywheel",
    "flywheel operation": "flywheel",
    "flywheel efficiency": "flywheel",
    "flywheel economics": "flywheel",
    "flywheel optimization": "flywheel",
    "flywheel siting": "flywheel",
    "flywheel environmental": "flywheel",
    "flywheel round-trip efficiency": "flywheel",
    "flywheel safety": "flywheel",
    "flywheel integration": "flywheel",
    "flywheel market": "flywheel",
    "flywheel degradation": "flywheel",
    "flywheel warranty": "flywheel",
    "flywheel seasonal": "flywheel",
    "flywheel distributed": "flywheel",
    "flywheel centralized": "flywheel",
    "flywheel renewable integration": "flywheel",
    "rotational energy storage": "flywheel",
    "kinetic energy storage": "flywheel",
    "flywheel energy": "flywheel",
    "flywheel plant": "flywheel",

    # Supercapacitor and Ultracapacitor Technology
    "supercapacitor": "supercapacitor",
    "ultracapacitor": "supercapacitor",
    "supercapacitor energy storage": "supercapacitor",
    "ultracapacitor energy storage": "supercapacitor",
    "supercap": "supercapacitor",
    "ultracap": "supercapacitor",
    "supercap storage": "supercapacitor",
    "ultracap storage": "supercapacitor",
    "supercapacitor system": "supercapacitor",
    "ultracapacitor system": "supercapacitor",
    "supercapacitor technology": "supercapacitor",
    "ultracapacitor technology": "supercapacitor",
    "supercapacitor fundamentals": "supercapacitor",
    "ultracapacitor fundamentals": "supercapacitor",
    "supercapacitor basics": "supercapacitor",
    "ultracapacitor basics": "supercapacitor",
    "supercapacitor principle": "supercapacitor",
    "ultracapacitor principle": "supercapacitor",
    "supercapacitor operation": "supercapacitor",
    "ultracapacitor operation": "supercapacitor",
    "supercapacitor efficiency": "supercapacitor",
    "ultracapacitor efficiency": "supercapacitor",
    "supercapacitor economics": "supercapacitor",
    "ultracapacitor economics": "supercapacitor",
    "supercapacitor optimization": "supercapacitor",
    "ultracapacitor optimization": "supercapacitor",
    "supercapacitor siting": "supercapacitor",
    "ultracapacitor siting": "supercapacitor",
    "supercapacitor environmental": "supercapacitor",
    "ultracapacitor environmental": "supercapacitor",
    "supercapacitor round-trip efficiency": "supercapacitor",
    "ultracapacitor round-trip efficiency": "supercapacitor",
    "supercapacitor safety": "supercapacitor",
    "ultracapacitor safety": "supercapacitor",
    "supercapacitor integration": "supercapacitor",
    "ultracapacitor integration": "supercapacitor",
    "supercapacitor market": "supercapacitor",
    "ultracapacitor market": "supercapacitor",
    "supercapacitor degradation": "supercapacitor",
    "ultracapacitor degradation": "supercapacitor",
    "supercapacitor warranty": "supercapacitor",
    "ultracapacitor warranty": "supercapacitor",
    "supercapacitor seasonal": "supercapacitor",
    "ultracapacitor seasonal": "supercapacitor",
    "supercapacitor distributed": "supercapacitor",
    "ultracapacitor distributed": "supercapacitor",
    "supercapacitor centralized": "supercapacitor",
    "ultracapacitor centralized": "supercapacitor",
    "supercapacitor renewable integration": "supercapacitor",
    "ultracapacitor renewable integration": "supercapacitor",
    "electrochemical capacitor": "supercapacitor",
    "electric double-layer capacitor": "supercapacitor",
    "edlc": "supercapacitor",

    # Thermal Energy Storage Systems
    "thermal energy storage": "thermal_storage",
    "thermal storage": "thermal_storage",
    "tes": "thermal_storage",
    "tes system": "thermal_storage",
    "tes plant": "thermal_storage",
    "tes technology": "thermal_storage",
    "tes fundamentals": "thermal_storage",
    "tes basics": "thermal_storage",
    "tes principle": "thermal_storage",
    "tes operation": "thermal_storage",
    "tes efficiency": "thermal_storage",
    "tes economics": "thermal_storage",
    "tes optimization": "thermal_storage",
    "tes siting": "thermal_storage",
    "tes environmental": "thermal_storage",
    "tes round-trip efficiency": "thermal_storage",
    "tes safety": "thermal_storage",
    "tes integration": "thermal_storage",
    "tes market": "thermal_storage",
    "tes degradation": "thermal_storage",
    "tes warranty": "thermal_storage",
    "tes seasonal": "thermal_storage",
    "tes distributed": "thermal_storage",
    "tes centralized": "thermal_storage",
    "tes renewable integration": "thermal_storage",
    "heat storage": "thermal_storage",
    "thermal plant": "thermal_storage",
    "thermal technology": "thermal_storage",
    "thermal fundamentals": "thermal_storage",
    "thermal basics": "thermal_storage",
    "thermal principle": "thermal_storage",
    "thermal operation": "thermal_storage",
    "thermal efficiency": "thermal_storage",
    "thermal economics": "thermal_storage",
    "thermal optimization": "thermal_storage",
    "thermal siting": "thermal_storage",
    "thermal environmental": "thermal_storage",
    "thermal round-trip efficiency": "thermal_storage",
    "thermal safety": "thermal_storage",
    "thermal integration": "thermal_storage",
    "thermal market": "thermal_storage",
    "thermal degradation": "thermal_storage",
    "thermal warranty": "thermal_storage",
    "thermal seasonal": "thermal_storage",
    "thermal distributed": "thermal_storage",
    "thermal centralized": "thermal_storage",
    "thermal renewable integration": "thermal_storage",
    "latent heat storage": "thermal_storage",
    "sensible heat storage": "thermal_storage",
    "phase change material storage": "thermal_storage",
    "pcm storage": "thermal_storage",

    # Grid-Scale Storage Economics and Optimization
    "grid-scale storage": "grid_scale_storage",
    "grid scale storage": "grid_scale_storage",
    "grid storage": "grid_scale_storage",
    "grid-scale economics": "grid_scale_storage",
    "grid-scale optimization": "grid_scale_storage",
    "grid-scale siting": "grid_scale_storage",
    "grid-scale environmental": "grid_scale_storage",
    "grid-scale round-trip efficiency": "grid_scale_storage",
    "grid-scale safety": "grid_scale_storage",
    "grid-scale integration": "grid_scale_storage",
    "grid-scale market": "grid_scale_storage",
    "grid-scale degradation": "grid_scale_storage",
    "grid-scale warranty": "grid_scale_storage",
    "grid-scale seasonal": "grid_scale_storage",
    "grid-scale distributed": "grid_scale_storage",
    "grid-scale centralized": "grid_scale_storage",
    "grid-scale renewable integration": "grid_scale_storage",
    "grid economics": "grid_scale_storage",
    "grid optimization": "grid_scale_storage",
    "grid siting": "grid_scale_storage",
    "grid environmental": "grid_scale_storage",
    "grid round-trip efficiency": "grid_scale_storage",
    "grid safety": "grid_scale_storage",
    "grid integration": "grid_scale_storage",
    "grid market": "grid_scale_storage",
    "grid degradation": "grid_scale_storage",
    "grid warranty": "grid_scale_storage",
    "grid seasonal": "grid_scale_storage",
    "grid distributed": "grid_scale_storage",
    "grid centralized": "grid_scale_storage",
    "grid renewable integration": "grid_scale_storage",
    "storage economics": "grid_scale_storage",
    "storage optimization": "grid_scale_storage",
    "storage siting": "grid_scale_storage",
    "storage environmental": "grid_scale_storage",
    "storage round-trip efficiency": "grid_scale_storage",
    "storage safety": "grid_scale_storage",
    "storage integration": "grid_scale_storage",
    "storage market": "grid_scale_storage",
    "storage degradation": "grid_scale_storage",
    "storage warranty": "grid_scale_storage",
    "storage seasonal": "grid_scale_storage",
    "storage distributed": "grid_scale_storage",
    "storage centralized": "grid_scale_storage",
    "storage renewable integration": "grid_scale_storage",

    # Battery Energy Storage System (BESS) Integration
    "battery energy storage system": "bess",
    "bess": "bess",
    "battery storage": "bess",
    "battery system": "bess",
    "battery technology": "bess",
    "bess system": "bess",
    "bess plant": "bess",
    "bess technology": "bess",
    "bess fundamentals": "bess",
    "bess basics": "bess",
    "bess principle": "bess",
    "bess operation": "bess",
    "bess efficiency": "bess",
    "bess economics": "bess",
    "bess optimization": "bess",
    "bess siting": "bess",
    "bess environmental": "bess",
    "bess round-trip efficiency": "bess",
    "bess safety": "bess",
    "bess integration": "bess",
    "bess market": "bess",
    "bess degradation": "bess",
    "bess warranty": "bess",
    "bess seasonal": "bess",
    "bess distributed": "bess",
    "bess centralized": "bess",
    "bess renewable integration": "bess",
    "battery fundamentals": "bess",
    "battery basics": "bess",
    "battery principle": "bess",
    "battery operation": "bess",
    "battery efficiency": "bess",
    "battery economics": "bess",
    "battery optimization": "bess",
    "battery siting": "bess",
    "battery environmental": "bess",
    "battery round-trip efficiency": "bess",
    "battery safety": "bess",
    "battery integration": "bess",
    "battery market": "bess",
    "battery degradation": "bess",
    "battery warranty": "bess",
    "battery seasonal": "bess",
    "battery distributed": "bess",
    "battery centralized": "bess",
    "battery renewable integration": "bess",
    "lithium ion battery": "bess",
    "li-ion battery": "bess",
    "lithium-ion battery": "bess",
    "li ion battery": "bess",
    "lead acid battery": "bess",
    "flow battery": "bess",
    "redox flow battery": "bess",
    "vanadium battery": "bess",
    "battery energy": "bess",

    # Hybrid Storage Systems and Multi-Technology Optimization
    "hybrid storage system": "hybrid_storage",
    "hybrid storage": "hybrid_storage",
    "hybrid energy storage": "hybrid_storage",
    "hybrid system": "hybrid_storage",
    "multi-technology optimization": "hybrid_storage",
    "multi technology optimization": "hybrid_storage",
    "multi-tech optimization": "hybrid_storage",
    "hybrid optimization": "hybrid_storage",
    "hybrid economics": "hybrid_storage",
    "hybrid siting": "hybrid_storage",
    "hybrid environmental": "hybrid_storage",
    "hybrid round-trip efficiency": "hybrid_storage",
    "hybrid safety": "hybrid_storage",
    "hybrid integration": "hybrid_storage",
    "hybrid market": "hybrid_storage",
    "hybrid degradation": "hybrid_storage",
    "hybrid warranty": "hybrid_storage",
    "hybrid seasonal": "hybrid_storage",
    "hybrid distributed": "hybrid_storage",
    "hybrid centralized": "hybrid_storage",
    "hybrid renewable integration": "hybrid_storage",
    "multi-storage": "hybrid_storage",
    "multi storage": "hybrid_storage",
    "multi energy storage": "hybrid_storage",
    "multi system": "hybrid_storage",
    "multi-storage optimization": "hybrid_storage",
    "multi-storage economics": "hybrid_storage",
    "multi-storage siting": "hybrid_storage",
    "multi-storage environmental": "hybrid_storage",
    "multi-storage round-trip efficiency": "hybrid_storage",
    "multi-storage safety": "hybrid_storage",
    "multi-storage integration": "hybrid_storage",
    "multi-storage market": "hybrid_storage",
    "multi-storage degradation": "hybrid_storage",
    "multi-storage warranty": "hybrid_storage",
    "multi-storage seasonal": "hybrid_storage",
    "multi-storage distributed": "hybrid_storage",
    "multi-storage centralized": "hybrid_storage",
    "multi-storage renewable integration": "hybrid_storage",

    # Long-Duration Energy Storage (LDES) Technologies
    "long-duration energy storage": "ldes",
    "ldes": "ldes",
    "long duration energy storage": "ldes",
    "long duration storage": "ldes",
    "long-duration storage": "ldes",
    "ldes system": "ldes",
    "ldes plant": "ldes",
    "ldes technology": "ldes",
    "ldes fundamentals": "ldes",
    "ldes basics": "ldes",
    "ldes principle": "ldes",
    "ldes operation": "ldes",
    "ldes efficiency": "ldes",
    "ldes economics": "ldes",
    "ldes optimization": "ldes",
    "ldes siting": "ldes",
    "ldes environmental": "ldes",
    "ldes round-trip efficiency": "ldes",
    "ldes safety": "ldes",
    "ldes integration": "ldes",
    "ldes market": "ldes",
    "ldes degradation": "ldes",
    "ldes warranty": "ldes",
    "ldes seasonal": "ldes",
    "ldes distributed": "ldes",
    "ldes centralized": "ldes",
    "ldes renewable integration": "ldes",
    "long-term storage": "ldes",
    "long term storage": "ldes",
    "long term energy storage": "ldes",
    "long-term energy storage": "ldes",

    # Storage Siting and Environmental Considerations
    "storage siting": "storage_siting",
    "siting": "storage_siting",
    "site selection": "storage_siting",
    "site assessment": "storage_siting",
    "storage site": "storage_siting",
    "storage location": "storage_siting",
    "storage environmental": "storage_environmental",
    "environmental": "storage_environmental",
    "environmental impact": "storage_environmental",
    "environmental assessment": "storage_environmental",
    "environmental considerations": "storage_environmental",
    "storage impact": "storage_environmental",
    "storage assessment": "storage_environmental",
    "storage considerations": "storage_environmental",
    "storage permitting": "storage_environmental",
    "storage regulation": "storage_environmental",
    "storage compliance": "storage_environmental",
    "storage footprint": "storage_environmental",

    # Round-Trip Efficiency Analysis and Optimization
    "round-trip efficiency": "round_trip_efficiency",
    "round trip efficiency": "round_trip_efficiency",
    "rte": "round_trip_efficiency",
    "storage efficiency": "round_trip_efficiency",
    "energy efficiency": "round_trip_efficiency",
    "efficiency analysis": "round_trip_efficiency",
    "efficiency optimization": "round_trip_efficiency",
    "efficiency improvement": "round_trip_efficiency",
    "efficiency assessment": "round_trip_efficiency",

    # Storage Safety Standards and Fire Protection
    "storage safety": "storage_safety",
    "safety": "storage_safety",
    "fire protection": "storage_safety",
    "fire safety": "storage_safety",
    "safety standards": "storage_safety",
    "safety compliance": "storage_safety",
    "safety assessment": "storage_safety",
    "safety regulation": "storage_safety",
    "safety permitting": "storage_safety",
    "safety footprint": "storage_safety",

    # Storage Interconnection and Grid Integration
    "storage interconnection": "storage_interconnection",
    "interconnection": "storage_interconnection",
    "grid integration": "storage_interconnection",
    "storage integration": "storage_interconnection",
    "integration": "storage_interconnection",
    "interconnection standards": "storage_interconnection",
    "interconnection compliance": "storage_interconnection",
    "interconnection permitting": "storage_interconnection",
    "interconnection assessment": "storage_interconnection",
    "interconnection regulation": "storage_interconnection",

    # Storage Market Participation and Revenue Stacking
    "storage market": "storage_market",
    "market participation": "storage_market",
    "market": "storage_market",
    "revenue stacking": "storage_market",
    "market stacking": "storage_market",
    "market optimization": "storage_market",
    "market economics": "storage_market",
    "market assessment": "storage_market",
    "market regulation": "storage_market",
    "market compliance": "storage_market",

    # Storage Degradation Modeling and Warranty Structures
    "storage degradation": "storage_degradation",
    "degradation": "storage_degradation",
    "degradation modeling": "storage_degradation",
    "degradation assessment": "storage_degradation",
    "degradation optimization": "storage_degradation",
    "degradation economics": "storage_degradation",
    "degradation regulation": "storage_degradation",
    "degradation compliance": "storage_degradation",
    "storage warranty": "storage_warranty",
    "warranty": "storage_warranty",
    "warranty structure": "storage_warranty",
    "warranty modeling": "storage_warranty",
    "warranty assessment": "storage_warranty",
    "warranty optimization": "storage_warranty",
    "warranty economics": "storage_warranty",
    "warranty regulation": "storage_warranty",
    "warranty compliance": "storage_warranty",

    # Seasonal and Multi-Day Storage Applications
    "seasonal storage": "seasonal_storage",
    "seasonal": "seasonal_storage",
    "multi-day storage": "seasonal_storage",
    "multi day storage": "seasonal_storage",
    "multi-day": "seasonal_storage",
    "multi day": "seasonal_storage",
    "seasonal application": "seasonal_storage",
    "seasonal optimization": "seasonal_storage",
    "seasonal economics": "seasonal_storage",
    "seasonal assessment": "seasonal_storage",
    "seasonal regulation": "seasonal_storage",
    "seasonal compliance": "seasonal_storage",

    # Distributed vs. Centralized Storage Deployment
    "distributed storage": "distributed_storage",
    "distributed": "distributed_storage",
    "distributed deployment": "distributed_storage",
    "distributed optimization": "distributed_storage",
    "distributed economics": "distributed_storage",
    "distributed assessment": "distributed_storage",
    "distributed regulation": "distributed_storage",
    "distributed compliance": "distributed_storage",
    "centralized storage": "centralized_storage",
    "centralized": "centralized_storage",
    "centralized deployment": "centralized_storage",
    "centralized optimization": "centralized_storage",
    "centralized economics": "centralized_storage",
    "centralized assessment": "centralized_storage",
    "centralized regulation": "centralized_storage",
    "centralized compliance": "centralized_storage",

    # Storage and Renewable Integration Strategies
    "renewable integration": "renewable_integration",
    "storage renewable integration": "renewable_integration",
    "renewable storage": "renewable_integration",
    "renewable strategy": "renewable_integration",
    "renewable optimization": "renewable_integration",
    "renewable economics": "renewable_integration",
    "renewable assessment": "renewable_integration",
    "renewable regulation": "renewable_integration",
    "renewable compliance": "renewable_integration",
    "renewable siting": "renewable_integration",
    "renewable environmental": "renewable_integration",
    "renewable round-trip efficiency": "renewable_integration",
    "renewable safety": "renewable_integration",
    "renewable market": "renewable_integration",
    "renewable degradation": "renewable_integration",
    "renewable warranty": "renewable_integration",
    "renewable seasonal": "renewable_integration",
    "renewable distributed": "renewable_integration",
    "renewable centralized": "renewable_integration",

    # Misspellings and common variants
    "pumped hydro storge": "pumped_hydro_storage",
    "compresed air energy storage": "caes",
    "flywheel enery storage": "flywheel",
    "supercapcitor": "supercapacitor",
    "ultracapcitor": "supercapacitor",
    "thermal enery storage": "thermal_storage",
    "grid scale storge": "grid_scale_storage",
    "battery enery storage system": "bess",
    "hybrid storge system": "hybrid_storage",
    "long duration enery storage": "ldes",
    "storage sitng": "storage_siting",
    "storage saftey": "storage_safety",
    "storage interconection": "storage_interconnection",
    "storage market participaton": "storage_market",
    "storage degradaton": "storage_degradation",
    "storage waranty": "storage_warranty",
    "seasonal storge": "seasonal_storage",
    "distributed storge": "distributed_storage",
    "centralized storge": "centralized_storage",
    "renewable integraton": "renewable_integration",
    "round trip efficency": "round_trip_efficiency",
    "efficency analysis": "round_trip_efficiency",
    "fire protction": "storage_safety",
    "warrenty": "storage_warranty",
    "degradaton": "storage_degradation",
    "interconection": "storage_interconnection",
    "market participaton": "storage_market",
    "storge": "grid_scale_storage",
    "energi storage": "grid_scale_storage",
    "storag": "grid_scale_storage",
    "storag system": "grid_scale_storage",
    "storag technology": "grid_scale_storage",
    "storag optimization": "grid_scale_storage",
    "storag economics": "grid_scale_storage",
    "storag siting": "grid_scale_storage",
    "storag environmental": "grid_scale_storage",
    "storag round-trip efficiency": "grid_scale_storage",
    "storag safety": "grid_scale_storage",
    "storag integration": "grid_scale_storage",
    "storag market": "grid_scale_storage",
    "storag degradation": "grid_scale_storage",
    "storag warranty": "grid_scale_storage",
    "storag seasonal": "grid_scale_storage",
    "storag distributed": "grid_scale_storage",
    "storag centralized": "grid_scale_storage",
    "storag renewable integration": "grid_scale_storage",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    raw = "".join(f"{k}:{v};" for k, v in items)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> Dict[str, object]:
    actual_count = len(SEMANTIC_MAP)
    actual_hash = _compute_map_hash()
    is_valid = (actual_count == _EXPECTED_ENTRY_COUNT) and (actual_hash == _MAP_INTEGRITY_HASH)
    return {
        "status": "ok" if is_valid else "error",
        "entries": actual_count,
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def _normalize_string(s: str) -> str:
    s = s.lower()
    s = s.strip()
    s = re.sub(r"[^a-z0-9\- ]", "", s)
    s = re.sub(r"\s+", " ", s)
    return s

def normalize_term(term: str) -> str:
    t = _normalize_string(term)
    return SEMANTIC_MAP.get(t, t)

def get_related_terms(term: str) -> List[str]:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return sorted(related)

def get_all_mappings() -> Dict[str, str]:
    return dict(SEMANTIC_MAP)