import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "AUTO09_emissions_control"
SEMANTIC_MAP_ENGINE = "AUTO09"

SEMANTIC_MAP = {
    # Three-Way Catalytic Converter Chemistry and Light-Off Temperature
    "three-way catalyst": "three_way_catalytic_converter",
    "three way catalyst": "three_way_catalytic_converter",
    "twc": "three_way_catalytic_converter",
    "catalytic converter": "three_way_catalytic_converter",
    "catalyst": "three_way_catalytic_converter",
    "catalyst chemistry": "three_way_catalytic_converter_chemistry",
    "catalyst light-off": "catalyst_light_off_temperature",
    "light-off temperature": "catalyst_light_off_temperature",
    "light off temperature": "catalyst_light_off_temperature",
    "catalyst light off": "catalyst_light_off_temperature",
    "catalyst activation temperature": "catalyst_light_off_temperature",
    "catalyst warm-up": "catalyst_light_off_temperature",
    "catalyst warm up": "catalyst_light_off_temperature",
    "catalyst lightoff": "catalyst_light_off_temperature",
    "catalyst threshold temperature": "catalyst_light_off_temperature",
    "catalyst efficiency": "catalyst_conversion_efficiency",
    "conversion efficiency": "catalyst_conversion_efficiency",
    "catalyst conversion": "catalyst_conversion_efficiency",
    "catalyst performance": "catalyst_conversion_efficiency",
    "catalyst precious metals": "catalyst_precious_metals",
    "platinum catalyst": "catalyst_precious_metals",
    "palladium catalyst": "catalyst_precious_metals",
    "rhodium catalyst": "catalyst_precious_metals",
    "catalyst aging": "catalyst_aging",
    "catalyst degradation": "catalyst_aging",
    "catalyst poisoning": "catalyst_poisoning",
    "sulfur poisoning": "catalyst_poisoning",
    "lead poisoning": "catalyst_poisoning",
    "catalyst washcoat": "catalyst_washcoat",
    "washcoat": "catalyst_washcoat",
    "catalyst substrate": "catalyst_substrate",
    "monolith": "catalyst_substrate",
    "ceramic substrate": "catalyst_substrate",
    "metal substrate": "catalyst_substrate",
    "catalyst loading": "catalyst_precious_metals",
    "catalyst volume": "catalyst_volume",
    "catalyst cell density": "catalyst_cell_density",
    "catalyst porosity": "catalyst_porosity",
    "catalyst surface area": "catalyst_surface_area",
    "catalyst durability": "catalyst_durability",
    "catalyst temperature": "catalyst_temperature",
    "catalyst exotherm": "catalyst_exotherm",
    "catalyst heat-up": "catalyst_light_off_temperature",
    "catalyst heat up": "catalyst_light_off_temperature",

    # Diesel Particulate Filter Regeneration Strategies and Ash Accumulation
    "diesel particulate filter": "dpf",
    "dpf": "dpf",
    "particulate filter": "dpf",
    "soot filter": "dpf",
    "diesel filter": "dpf",
    "dpf regeneration": "dpf_regeneration",
    "regeneration": "dpf_regeneration",
    "active regeneration": "dpf_active_regeneration",
    "passive regeneration": "dpf_passive_regeneration",
    "thermal regeneration": "dpf_active_regeneration",
    "fuel injection regeneration": "dpf_active_regeneration",
    "exothermic regeneration": "dpf_active_regeneration",
    "dpf ash accumulation": "dpf_ash_accumulation",
    "ash accumulation": "dpf_ash_accumulation",
    "ash loading": "dpf_ash_accumulation",
    "ash buildup": "dpf_ash_accumulation",
    "dpf cleaning": "dpf_cleaning",
    "filter cleaning": "dpf_cleaning",
    "dpf maintenance": "dpf_cleaning",
    "dpf pressure drop": "dpf_pressure_drop",
    "filter pressure drop": "dpf_pressure_drop",
    "dpf backpressure": "dpf_pressure_drop",
    "dpf efficiency": "dpf_efficiency",
    "dpf performance": "dpf_efficiency",
    "dpf substrate": "dpf_substrate",
    "cordierite dpf": "dpf_substrate",
    "silicon carbide dpf": "dpf_substrate",
    "dpf durability": "dpf_durability",
    "dpf failure": "dpf_failure",
    "dpf cracks": "dpf_failure",
    "dpf melting": "dpf_failure",
    "dpf plugging": "dpf_plugging",
    "filter plugging": "dpf_plugging",
    "dpf soot loading": "dpf_soot_loading",
    "soot loading": "dpf_soot_loading",
    "soot accumulation": "dpf_soot_loading",
    "dpf monitoring": "dpf_monitoring",
    "dpf sensor": "dpf_monitoring",
    "dpf pressure sensor": "dpf_monitoring",
    "dpf temperature sensor": "dpf_monitoring",
    "dpf differential pressure": "dpf_monitoring",
    "dpf replacement": "dpf_replacement",

    # Selective Catalytic Reduction (SCR) and Diesel Exhaust Fluid (DEF) Dosing Control
    "selective catalytic reduction": "scr",
    "scr": "scr",
    "urea scr": "scr",
    "scr catalyst": "scr_catalyst",
    "scr dosing": "scr_dosing_control",
    "scr control": "scr_dosing_control",
    "scr efficiency": "scr_efficiency",
    "scr performance": "scr_efficiency",
    "scr ammonia slip": "scr_ammonia_slip",
    "ammonia slip": "scr_ammonia_slip",
    "scr temperature": "scr_temperature",
    "scr light-off": "scr_light_off_temperature",
    "scr light off": "scr_light_off_temperature",
    "scr activation temperature": "scr_light_off_temperature",
    "scr warm-up": "scr_light_off_temperature",
    "scr warm up": "scr_light_off_temperature",
    "scr catalyst aging": "scr_catalyst_aging",
    "scr catalyst degradation": "scr_catalyst_aging",
    "scr catalyst poisoning": "scr_catalyst_poisoning",
    "scr substrate": "scr_substrate",
    "scr washcoat": "scr_washcoat",
    "diesel exhaust fluid": "def",
    "def": "def",
    "adblue": "def",
    "urea solution": "def",
    "def dosing": "def_dosing_control",
    "def injection": "def_dosing_control",
    "def control": "def_dosing_control",
    "def quality": "def_quality",
    "def concentration": "def_quality",
    "def purity": "def_quality",
    "def crystallization": "def_crystallization",
    "def freeze": "def_crystallization",
    "def tank": "def_tank",
    "def pump": "def_pump",
    "def heater": "def_heater",
    "def sensor": "def_sensor",
    "def level sensor": "def_sensor",
    "def temperature sensor": "def_sensor",
    "def pressure sensor": "def_sensor",
    "def line": "def_line",
    "def injector": "def_injector",
    "def system": "def_system",
    "def refill": "def_refill",
    "def consumption": "def_consumption",
    "def usage": "def_consumption",
    "def warning": "def_warning",
    "def indicator": "def_warning",

    # Exhaust Gas Recirculation (EGR) System Design and Cooled EGR Benefits
    "exhaust gas recirculation": "egr",
    "egr": "egr",
    "egr system": "egr",
    "egr valve": "egr_valve",
    "egr control valve": "egr_valve",
    "egr actuator": "egr_actuator",
    "egr cooler": "egr_cooler",
    "cooled egr": "egr_cooler",
    "egr cooling": "egr_cooler",
    "egr bypass": "egr_bypass",
    "egr rate": "egr_rate",
    "egr flow": "egr_rate",
    "egr flow rate": "egr_rate",
    "egr efficiency": "egr_efficiency",
    "egr performance": "egr_efficiency",
    "egr temperature": "egr_temperature",
    "egr pressure": "egr_pressure",
    "egr sensor": "egr_sensor",
    "egr position sensor": "egr_sensor",
    "egr temperature sensor": "egr_sensor",
    "egr pressure sensor": "egr_sensor",
    "egr fault": "egr_fault",
    "egr malfunction": "egr_fault",
    "egr stuck": "egr_fault",
    "egr blocked": "egr_fault",
    "egr clogging": "egr_fault",
    "egr cleaning": "egr_cleaning",
    "egr maintenance": "egr_cleaning",
    "egr calibration": "egr_calibration",
    "egr map": "egr_calibration",
    "egr tuning": "egr_calibration",
    "egr benefits": "egr_benefits",
    "cooled egr benefits": "egr_benefits",
    "egr emissions": "egr_emissions_reduction",
    "egr emission reduction": "egr_emissions_reduction",
    "egr nox reduction": "egr_emissions_reduction",
    "egr soot reduction": "egr_emissions_reduction",

    # Evaporative Emission Control System (EVAP) and Leak Detection Standards
    "evaporative emission control": "evap",
    "evap": "evap",
    "evap system": "evap",
    "evap canister": "evap_canister",
    "charcoal canister": "evap_canister",
    "carbon canister": "evap_canister",
    "evap purge valve": "evap_purge_valve",
    "purge valve": "evap_purge_valve",
    "evap vent valve": "evap_vent_valve",
    "vent valve": "evap_vent_valve",
    "evap line": "evap_line",
    "evap hose": "evap_line",
    "evap leak": "evap_leak_detection",
    "evap leak detection": "evap_leak_detection",
    "evap test": "evap_leak_detection",
    "evap monitor": "evap_monitor",
    "evap readiness": "evap_monitor",
    "evap sensor": "evap_sensor",
    "evap pressure sensor": "evap_sensor",
    "evap temperature sensor": "evap_sensor",
    "evap code": "evap_fault",
    "evap fault": "evap_fault",
    "evap malfunction": "evap_fault",
    "evap failure": "evap_fault",
    "evap calibration": "evap_calibration",
    "evap standards": "evap_leak_detection_standards",
    "evap leak standards": "evap_leak_detection_standards",
    "evap regulation": "evap_leak_detection_standards",
    "evap emission standards": "evap_leak_detection_standards",
    "evap compliance": "evap_leak_detection_standards",
    "evap certification": "evap_leak_detection_standards",
    "evap testing": "evap_leak_detection_standards",

    # OBDII Catalyst Efficiency Monitor and Oxygen Sensor Ratio Method
    "obdii catalyst monitor": "obdii_catalyst_efficiency_monitor",
    "obd catalyst monitor": "obdii_catalyst_efficiency_monitor",
    "obd2 catalyst monitor": "obdii_catalyst_efficiency_monitor",
    "catalyst monitor": "obdii_catalyst_efficiency_monitor",
    "catalyst efficiency monitor": "obdii_catalyst_efficiency_monitor",
    "catalyst monitoring": "obdii_catalyst_efficiency_monitor",
    "catalyst readiness": "obdii_catalyst_efficiency_monitor",
    "obdii oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "obd oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "obd2 oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "oxygen sensor ratio": "obdii_oxygen_sensor_ratio_method",
    "sensor ratio method": "obdii_oxygen_sensor_ratio_method",
    "oxygen sensor efficiency": "obdii_oxygen_sensor_ratio_method",
    "sensor efficiency": "obdii_oxygen_sensor_ratio_method",
    "upstream oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "downstream oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "pre-cat oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "post-cat oxygen sensor": "obdii_oxygen_sensor_ratio_method",
    "lambda sensor": "obdii_oxygen_sensor_ratio_method",
    "wideband sensor": "obdii_oxygen_sensor_ratio_method",
    "narrowband sensor": "obdii_oxygen_sensor_ratio_method",
    "o2 sensor": "obdii_oxygen_sensor_ratio_method",
    "o2 sensor ratio": "obdii_oxygen_sensor_ratio_method",
    "o2 sensor method": "obdii_oxygen_sensor_ratio_method",
    "oxygen sensor monitor": "obdii_oxygen_sensor_ratio_method",

    # Gasoline Particulate Filter (GPF) and Gasoline Direct Injection (GDI) Emissions
    "gasoline particulate filter": "gpf",
    "gpf": "gpf",
    "particulate filter gasoline": "gpf",
    "gpf regeneration": "gpf_regeneration",
    "gpf cleaning": "gpf_cleaning",
    "gpf maintenance": "gpf_cleaning",
    "gpf pressure drop": "gpf_pressure_drop",
    "gpf backpressure": "gpf_pressure_drop",
    "gpf efficiency": "gpf_efficiency",
    "gpf performance": "gpf_efficiency",
    "gpf substrate": "gpf_substrate",
    "gpf durability": "gpf_durability",
    "gpf failure": "gpf_failure",
    "gpf cracks": "gpf_failure",
    "gpf melting": "gpf_failure",
    "gpf plugging": "gpf_plugging",
    "gpf soot loading": "gpf_soot_loading",
    "gpf monitoring": "gpf_monitoring",
    "gpf sensor": "gpf_monitoring",
    "gpf pressure sensor": "gpf_monitoring",
    "gpf temperature sensor": "gpf_monitoring",
    "gpf replacement": "gpf_replacement",
    "gdi": "gasoline_direct_injection",
    "gasoline direct injection": "gasoline_direct_injection",
    "direct injection gasoline": "gasoline_direct_injection",
    "gdi emissions": "gasoline_direct_injection_emissions",
    "gdi emission": "gasoline_direct_injection_emissions",
    "gdi particulate": "gasoline_direct_injection_emissions",
    "gdi soot": "gasoline_direct_injection_emissions",
    "gdi pm": "gasoline_direct_injection_emissions",
    "gdi nox": "gasoline_direct_injection_emissions",
    "gdi hc": "gasoline_direct_injection_emissions",
    "gdi co": "gasoline_direct_injection_emissions",
    "gdi emission reduction": "gasoline_direct_injection_emissions_reduction",
    "gdi emission control": "gasoline_direct_injection_emissions_reduction",

    # Cold-Start Emissions and Catalyst Light-Off Strategies
    "cold start emissions": "cold_start_emissions",
    "cold-start emissions": "cold_start_emissions",
    "cold start emission": "cold_start_emissions",
    "cold-start emission": "cold_start_emissions",
    "cold start": "cold_start_emissions",
    "cold-start": "cold_start_emissions",
    "cold start catalyst": "cold_start_catalyst_light_off",
    "cold-start catalyst": "cold_start_catalyst_light_off",
    "catalyst light-off strategy": "catalyst_light_off_strategy",
    "catalyst light off strategy": "catalyst_light_off_strategy",
    "catalyst warm-up strategy": "catalyst_light_off_strategy",
    "catalyst warm up strategy": "catalyst_light_off_strategy",
    "catalyst heat-up strategy": "catalyst_light_off_strategy",
    "catalyst heat up strategy": "catalyst_light_off_strategy",
    "catalyst preheating": "catalyst_light_off_strategy",
    "catalyst pre-heating": "catalyst_light_off_strategy",
    "catalyst pre heating": "catalyst_light_off_strategy",
    "catalyst electric heating": "catalyst_light_off_strategy",
    "catalyst electric heater": "catalyst_light_off_strategy",
    "catalyst insulation": "catalyst_light_off_strategy",
    "catalyst thermal management": "catalyst_light_off_strategy",
    "catalyst rapid light-off": "catalyst_light_off_strategy",
    "catalyst rapid light off": "catalyst_light_off_strategy",
    "catalyst fast light-off": "catalyst_light_off_strategy",
    "catalyst fast light off": "catalyst_light_off_strategy",

    # Real Driving Emissions (RDE) Testing and Portable Emissions Measurement Systems (PEMS)
    "real driving emissions": "rde",
    "rde": "rde",
    "rde testing": "rde_testing",
    "rde test": "rde_testing",
    "rde compliance": "rde_compliance",
    "rde regulation": "rde_compliance",
    "rde certification": "rde_compliance",
    "rde standards": "rde_compliance",
    "rde emission": "rde",
    "rde emissions": "rde",
    "portable emissions measurement system": "pems",
    "portable emissions measurement systems": "pems",
    "pems": "pems",
    "pems testing": "pems_testing",
    "pems test": "pems_testing",
    "pems compliance": "pems_compliance",
    "pems regulation": "pems_compliance",
    "pems certification": "pems_compliance",
    "pems standards": "pems_compliance",
    "pems emission": "pems",
    "pems emissions": "pems",
    "pems device": "pems_device",
    "pems equipment": "pems_device",
    "pems sensor": "pems_sensor",
    "pems analyzer": "pems_analyzer",
    "pems calibration": "pems_calibration",
    "pems data": "pems_data",
    "pems measurement": "pems_measurement",
    "pems accuracy": "pems_accuracy",
    "pems reliability": "pems_reliability",

    # EPA Tier 3 and CARB LEV III Emission Standards Comparison
    "epa tier 3": "epa_tier_3",
    "tier 3": "epa_tier_3",
    "epa emission standards": "epa_tier_3",
    "epa standards": "epa_tier_3",
    "epa regulation": "epa_tier_3",
    "epa compliance": "epa_tier_3",
    "epa certification": "epa_tier_3",
    "epa testing": "epa_tier_3",
    "epa emission": "epa_tier_3",
    "epa emissions": "epa_tier_3",
    "carb lev iii": "carb_lev_iii",
    "lev iii": "carb_lev_iii",
    "carb emission standards": "carb_lev_iii",
    "carb standards": "carb_lev_iii",
    "carb regulation": "carb_lev_iii",
    "carb compliance": "carb_lev_iii",
    "carb certification": "carb_lev_iii",
    "carb testing": "carb_lev_iii",
    "carb emission": "carb_lev_iii",
    "carb emissions": "carb_lev_iii",
    "epa vs carb": "epa_tier_3_vs_carb_lev_iii",
    "tier 3 vs lev iii": "epa_tier_3_vs_carb_lev_iii",
    "epa tier 3 vs carb lev iii": "epa_tier_3_vs_carb_lev_iii",
    "lev iii vs tier 3": "epa_tier_3_vs_carb_lev_iii",
    "epa carb comparison": "epa_tier_3_vs_carb_lev_iii",
    "epa carb standards": "epa_tier_3_vs_carb_lev_iii",
    "epa carb emission standards": "epa_tier_3_vs_carb_lev_iii",

    # OBDII Readiness Monitors and Emission Testing Inspection & Maintenance (I/M) Programs
    "obdii readiness monitor": "obdii_readiness_monitor",
    "obd readiness monitor": "obdii_readiness_monitor",
    "obd2 readiness monitor": "obdii_readiness_monitor",
    "readiness monitor": "obdii_readiness_monitor",
    "readiness monitors": "obdii_readiness_monitor",
    "obdii emission testing": "obdii_emission_testing",
    "obd emission testing": "obdii_emission_testing",
    "obd2 emission testing": "obdii_emission_testing",
    "emission testing": "obdii_emission_testing",
    "emission test": "obdii_emission_testing",
    "inspection and maintenance": "im_programs",
    "i/m": "im_programs",
    "im": "im_programs",
    "i m": "im_programs",
    "i-m": "im_programs",
    "i/m program": "im_programs",
    "im program": "im_programs",
    "i m program": "im_programs",
    "i-m program": "im_programs",
    "emission inspection": "im_programs",
    "emission maintenance": "im_programs",
    "emission readiness": "obdii_readiness_monitor",
    "obdii inspection": "im_programs",
    "obd inspection": "im_programs",
    "obd2 inspection": "im_programs",
    "obdii maintenance": "im_programs",
    "obd maintenance": "im_programs",
    "obd2 maintenance": "im_programs",

    # Diesel Oxidation Catalyst (DOC) and NO to NO2 Conversion for DPF/SCR
    "diesel oxidation catalyst": "doc",
    "doc": "doc",
    "oxidation catalyst": "doc",
    "doc catalyst": "doc",
    "doc efficiency": "doc_efficiency",
    "doc performance": "doc_efficiency",
    "doc substrate": "doc_substrate",
    "doc washcoat": "doc_washcoat",
    "doc durability": "doc_durability",
    "doc aging": "doc_aging",
    "doc degradation": "doc_aging",
    "doc poisoning": "doc_poisoning",
    "doc temperature": "doc_temperature",
    "doc light-off": "doc_light_off_temperature",
    "doc light off": "doc_light_off_temperature",
    "doc activation temperature": "doc_light_off_temperature",
    "doc warm-up": "doc_light_off_temperature",
    "doc warm up": "doc_light_off_temperature",
    "doc exotherm": "doc_exotherm",
    "doc heat-up": "doc_light_off_temperature",
    "doc heat up": "doc_light_off_temperature",
    "doc no to no2 conversion": "doc_no_to_no2_conversion",
    "doc nox conversion": "doc_no_to_no2_conversion",
    "doc no conversion": "doc_no_to_no2_conversion",
    "doc no2 conversion": "doc_no_to_no2_conversion",
    "no to no2 conversion": "doc_no_to_no2_conversion",
    "nox conversion": "doc_no_to_no2_conversion",
    "no conversion": "doc_no_to_no2_conversion",
    "no2 conversion": "doc_no_to_no2_conversion",
    "doc for dpf": "doc_no_to_no2_conversion",
    "doc for scr": "doc_no_to_no2_conversion",
    "doc for regeneration": "doc_no_to_no2_conversion",

    # Crankcase Emission Control (PCV System) and Oil Vapor Management
    "crankcase emission control": "pcv_system",
    "pcv": "pcv_system",
    "pcv system": "pcv_system",
    "positive crankcase ventilation": "pcv_system",
    "crankcase ventilation": "pcv_system",
    "crankcase vent": "pcv_system",
    "crankcase breather": "pcv_system",
    "pcv valve": "pcv_valve",
    "crankcase valve": "pcv_valve",
    "pcv filter": "pcv_filter",
    "pcv hose": "pcv_hose",
    "pcv line": "pcv_hose",
    "pcv tube": "pcv_hose",
    "pcv sensor": "pcv_sensor",
    "pcv pressure sensor": "pcv_sensor",
    "pcv temperature sensor": "pcv_sensor",
    "pcv fault": "pcv_fault",
    "pcv malfunction": "pcv_fault",
    "pcv failure": "pcv_fault",
    "pcv cleaning": "pcv_cleaning",
    "pcv maintenance": "pcv_cleaning",
    "pcv calibration": "pcv_calibration",
    "oil vapor management": "oil_vapor_management",
    "oil vapor": "oil_vapor_management",
    "oil mist": "oil_vapor_management",
    "oil separator": "oil_separator",
    "oil catch can": "oil_separator",
    "oil trap": "oil_separator",
    "oil filter": "oil_separator",
    "oil recirculation": "oil_vapor_management",
    "oil return": "oil_vapor_management",
    "oil blowby": "oil_vapor_management",
    "blowby": "oil_vapor_management",
    "blow-by": "oil_vapor_management",
    "oil blow by": "oil_vapor_management",
    "oil vapour": "oil_vapor_management",
    "oil vapour management": "oil_vapor_management",

    # General and Related Terms
    "emission": "emissions",
    "emissions": "emissions",
    "exhaust emission": "emissions",
    "exhaust emissions": "emissions",
    "tailpipe emission": "emissions",
    "tailpipe emissions": "emissions",
    "engine emission": "emissions",
    "engine emissions": "emissions",
    "vehicle emission": "emissions",
    "vehicle emissions": "emissions",
    "pollutant": "emissions",
    "pollutants": "emissions",
    "nox": "nitrogen_oxides",
    "nitrogen oxides": "nitrogen_oxides",
    "no": "nitrogen_oxides",
    "no2": "nitrogen_oxides",
    "pm": "particulate_matter",
    "particulate matter": "particulate_matter",
    "soot": "particulate_matter",
    "hc": "hydrocarbons",
    "hydrocarbons": "hydrocarbons",
    "co": "carbon_monoxide",
    "carbon monoxide": "carbon_monoxide",
    "co2": "carbon_dioxide",
    "carbon dioxide": "carbon_dioxide",
    "greenhouse gas": "carbon_dioxide",
    "greenhouse gases": "carbon_dioxide",
    "ghg": "carbon_dioxide",
    "volatile organic compounds": "hydrocarbons",
    "voc": "hydrocarbons",
    "smog": "emissions",
    "air pollution": "emissions",
    "pollution": "emissions",
    "clean air": "emissions_reduction",
    "emission reduction": "emissions_reduction",
    "emissions reduction": "emissions_reduction",
    "emission control": "emissions_control",
    "emissions control": "emissions_control",
    "emission strategy": "emissions_control",
    "emissions strategy": "emissions_control",
    "emission standard": "emission_standards",
    "emission standards": "emission_standards",
    "emissions standard": "emission_standards",
    "emissions standards": "emission_standards",
    "regulation": "emission_standards",
    "regulations": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "test": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "failure",
    "fault": "fault",
    "malfunction": "fault",
    "replacement": "replacement",
    "cleaning": "cleaning",
    "calibration": "calibration",
    "tuning": "calibration",
    "map": "calibration",
    "benefits": "benefits",
    "reduction": "emissions_reduction",
    "control": "emissions_control",
    "strategy": "emissions_control",
    "standard": "emission_standards",
    "standards": "emission_standards",
    "compliance": "emission_standards",
    "certification": "emission_standards",
    "testing": "emission_testing",
    "inspection": "emission_testing",
    "maintenance": "emission_testing",
    "monitor": "monitoring",
    "monitoring": "monitoring",
    "sensor": "sensor",
    "sensors": "sensor",
    "actuator": "actuator",
    "actuators": "actuator",
    "valve": "valve",
    "valves": "valve",
    "filter": "filter",
    "filters": "filter",
    "converter": "catalytic_converter",
    "converters": "catalytic_converter",
    "system": "system",
    "systems": "system",
    "device": "device",
    "devices": "device",
    "equipment": "device",
    "line": "line",
    "lines": "line",
    "hose": "line",
    "tubing": "line",
    "tube": "line",
    "canister": "canister",
    "canisters": "canister",
    "tank": "tank",
    "tanks": "tank",
    "pump": "pump",
    "pumps": "pump",
    "heater": "heater",
    "heaters": "heater",
    "trap": "trap",
    "traps": "trap",
    "catch can": "oil_separator",
    "catch cans": "oil_separator",
    "separator": "oil_separator",
    "separators": "oil_separator",
    "subtrate": "substrate",  # misspelling
    "substrate": "substrate",
    "substrates": "substrate",
    "washcoat": "washcoat",
    "washcoats": "washcoat",
    "cell density": "cell_density",
    "porosity": "porosity",
    "surface area": "surface_area",
    "volume": "volume",
    "durability": "durability",
    "aging": "aging",
    "degradation": "aging",
    "poisoning": "poisoning",
    "crystallization": "crystallization",
    "freeze": "crystallization",
    "buildup": "accumulation",
    "accumulation": "accumulation",
    "loading": "accumulation",
    "plugging": "plugging",
    "clogging": "plugging",
    "blocked": "plugging",
    "failure": "