import hashlib
import re
from typing import Dict, List

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "GS03 Engineering Team"
SEMANTIC_MAP_ENGINE = "GS03_drift_anomaly_detector"

# Domain: Z-Score Based Anomaly Detection, Interquartile Range (IQR) Outlier Detection, Isolation Forest for Anomaly Detection, Engine Performance Baseline Tracking, Response Time Drift Detection, Error Rate Drift Analysis, Confidence Score Distribution Shift, Output Quality Metric Drift, Behavioral Fingerprinting per Engine, Seasonal Pattern Accounting, Alert Fatigue Prevention: Minimum Severity Thresholds, Anomaly Correlation Across Engines, Root Cause Inference from Anomaly Patterns, Anomaly Severity Classification, Trending vs Sudden Anomalies, Phantom Load Detection, Resource Leak Pattern Detection, Memory Growth Analysis, Connection Pool Drift Detection, Cache Hit Rate Degradation, API Latency Distribution Shift, Data Quality Drift Indicators

SEMANTIC_MAP: Dict[str, str] = {
    # Z-Score Based Anomaly Detection
    "zscore": "z_score_anomaly_detection",
    "z-score": "z_score_anomaly_detection",
    "z score": "z_score_anomaly_detection",
    "z_score": "z_score_anomaly_detection",
    "zscore anomaly": "z_score_anomaly_detection",
    "z-score anomaly": "z_score_anomaly_detection",
    "zscore outlier": "z_score_anomaly_detection",
    "z-score outlier": "z_score_anomaly_detection",
    "zscore based anomaly": "z_score_anomaly_detection",
    "z-score based anomaly": "z_score_anomaly_detection",
    "zscore based detection": "z_score_anomaly_detection",
    "z-score based detection": "z_score_anomaly_detection",
    "zscore based outlier": "z_score_anomaly_detection",
    "z-score based outlier": "z_score_anomaly_detection",
    "zscore threshold": "z_score_anomaly_detection",
    "z-score threshold": "z_score_anomaly_detection",
    "zscore thresholding": "z_score_anomaly_detection",
    "z-score thresholding": "z_score_anomaly_detection",
    "zscore method": "z_score_anomaly_detection",
    "z-score method": "z_score_anomaly_detection",
    "zscore technique": "z_score_anomaly_detection",
    "z-score technique": "z_score_anomaly_detection",
    "zscore analysis": "z_score_anomaly_detection",
    "z-score analysis": "z_score_anomaly_detection",
    "zscore statistics": "z_score_anomaly_detection",
    "z-score statistics": "z_score_anomaly_detection",
    "zscore stat": "z_score_anomaly_detection",
    "z-score stat": "z_score_anomaly_detection",
    "zscore anomaly detection": "z_score_anomaly_detection",
    "z-score anomaly detection": "z_score_anomaly_detection",
    "zscore outlier detection": "z_score_anomaly_detection",
    "z-score outlier detection": "z_score_anomaly_detection",
    "zscore based outlier detection": "z_score_anomaly_detection",
    "z-score based outlier detection": "z_score_anomaly_detection",
    "zscore based anomaly detection": "z_score_anomaly_detection",
    "z-score based anomaly detection": "z_score_anomaly_detection",
    "zscore based detection method": "z_score_anomaly_detection",
    "z-score based detection method": "z_score_anomaly_detection",
    "zscore based detection technique": "z_score_anomaly_detection",
    "z-score based detection technique": "z_score_anomaly_detection",
    "zscore based analysis": "z_score_anomaly_detection",
    "z-score based analysis": "z_score_anomaly_detection",
    "zscore based statistics": "z_score_anomaly_detection",
    "z-score based statistics": "z_score_anomaly_detection",
    "zscore based stat": "z_score_anomaly_detection",
    "z-score based stat": "z_score_anomaly_detection",
    # Interquartile Range (IQR) Outlier Detection
    "iqr": "iqr_outlier_detection",
    "iqr outlier": "iqr_outlier_detection",
    "iqr outlier detection": "iqr_outlier_detection",
    "iqr anomaly": "iqr_outlier_detection",
    "iqr anomaly detection": "iqr_outlier_detection",
    "iqr method": "iqr_outlier_detection",
    "iqr technique": "iqr_outlier_detection",
    "iqr analysis": "iqr_outlier_detection",
    "iqr statistics": "iqr_outlier_detection",
    "iqr stat": "iqr_outlier_detection",
    "iqr threshold": "iqr_outlier_detection",
    "iqr thresholding": "iqr_outlier_detection",
    "iqr based detection": "iqr_outlier_detection",
    "iqr based outlier detection": "iqr_outlier_detection",
    "iqr based anomaly detection": "iqr_outlier_detection",
    "iqr based detection method": "iqr_outlier_detection",
    "iqr based detection technique": "iqr_outlier_detection",
    "iqr based analysis": "iqr_outlier_detection",
    "iqr based statistics": "iqr_outlier_detection",
    "iqr based stat": "iqr_outlier_detection",
    "interquartile range": "iqr_outlier_detection",
    "interquartile range outlier": "iqr_outlier_detection",
    "interquartile range outlier detection": "iqr_outlier_detection",
    "interquartile range anomaly": "iqr_outlier_detection",
    "interquartile range anomaly detection": "iqr_outlier_detection",
    "interquartile range method": "iqr_outlier_detection",
    "interquartile range technique": "iqr_outlier_detection",
    "interquartile range analysis": "iqr_outlier_detection",
    "interquartile range statistics": "iqr_outlier_detection",
    "interquartile range stat": "iqr_outlier_detection",
    "interquartile range threshold": "iqr_outlier_detection",
    "interquartile range thresholding": "iqr_outlier_detection",
    "iqr misspelling": "iqr_outlier_detection",
    "iqr outlier detction": "iqr_outlier_detection",
    "iqr outlier detecion": "iqr_outlier_detection",
    "iqr outlier detecton": "iqr_outlier_detection",
    # Isolation Forest for Anomaly Detection
    "isolation forest": "isolation_forest_anomaly_detection",
    "isolation forest anomaly": "isolation_forest_anomaly_detection",
    "isolation forest anomaly detection": "isolation_forest_anomaly_detection",
    "isolation forest outlier": "isolation_forest_anomaly_detection",
    "isolation forest outlier detection": "isolation_forest_anomaly_detection",
    "isolation forest method": "isolation_forest_anomaly_detection",
    "isolation forest technique": "isolation_forest_anomaly_detection",
    "isolation forest analysis": "isolation_forest_anomaly_detection",
    "isolation forest statistics": "isolation_forest_anomaly_detection",
    "isolation forest stat": "isolation_forest_anomaly_detection",
    "isolation forest threshold": "isolation_forest_anomaly_detection",
    "isolation forest thresholding": "isolation_forest_anomaly_detection",
    "iforest": "isolation_forest_anomaly_detection",
    "iforest anomaly": "isolation_forest_anomaly_detection",
    "iforest anomaly detection": "isolation_forest_anomaly_detection",
    "iforest outlier": "isolation_forest_anomaly_detection",
    "iforest outlier detection": "isolation_forest_anomaly_detection",
    "iforest method": "isolation_forest_anomaly_detection",
    "iforest technique": "isolation_forest_anomaly_detection",
    "iforest analysis": "isolation_forest_anomaly_detection",
    "iforest statistics": "isolation_forest_anomaly_detection",
    "iforest stat": "isolation_forest_anomaly_detection",
    "iforest threshold": "isolation_forest_anomaly_detection",
    "iforest thresholding": "isolation_forest_anomaly_detection",
    "isolation forest based detection": "isolation_forest_anomaly_detection",
    "isolation forest based outlier detection": "isolation_forest_anomaly_detection",
    "isolation forest based anomaly detection": "isolation_forest_anomaly_detection",
    "isolation forest based detection method": "isolation_forest_anomaly_detection",
    "isolation forest based detection technique": "isolation_forest_anomaly_detection",
    "isolation forest based analysis": "isolation_forest_anomaly_detection",
    "isolation forest based statistics": "isolation_forest_anomaly_detection",
    "isolation forest based stat": "isolation_forest_anomaly_detection",
    # Engine Performance Baseline Tracking
    "engine performance baseline": "engine_performance_baseline_tracking",
    "engine performance baseline tracking": "engine_performance_baseline_tracking",
    "engine baseline": "engine_performance_baseline_tracking",
    "engine baseline tracking": "engine_performance_baseline_tracking",
    "performance baseline": "engine_performance_baseline_tracking",
    "performance baseline tracking": "engine_performance_baseline_tracking",
    "baseline tracking": "engine_performance_baseline_tracking",
    "baseline performance tracking": "engine_performance_baseline_tracking",
    "baseline performance": "engine_performance_baseline_tracking",
    "engine perf baseline": "engine_performance_baseline_tracking",
    "engine perf baseline tracking": "engine_performance_baseline_tracking",
    "perf baseline": "engine_performance_baseline_tracking",
    "perf baseline tracking": "engine_performance_baseline_tracking",
    "baseline monitor": "engine_performance_baseline_tracking",
    "baseline monitoring": "engine_performance_baseline_tracking",
    "baseline perf": "engine_performance_baseline_tracking",
    "baseline perf tracking": "engine_performance_baseline_tracking",
    "baseline perf monitor": "engine_performance_baseline_tracking",
    "baseline perf monitoring": "engine_performance_baseline_tracking",
    "engine performance monitor": "engine_performance_baseline_tracking",
    "engine performance monitoring": "engine_performance_baseline_tracking",
    "engine perf monitor": "engine_performance_baseline_tracking",
    "engine perf monitoring": "engine_performance_baseline_tracking",
    "baseline misspelling": "engine_performance_baseline_tracking",
    "baseline trackng": "engine_performance_baseline_tracking",
    "baseline traccking": "engine_performance_baseline_tracking",
    "baseline traking": "engine_performance_baseline_tracking",
    # Response Time Drift Detection
    "response time drift": "response_time_drift_detection",
    "response time drift detection": "response_time_drift_detection",
    "response drift": "response_time_drift_detection",
    "response drift detection": "response_time_drift_detection",
    "time drift": "response_time_drift_detection",
    "time drift detection": "response_time_drift_detection",
    "response latency drift": "response_time_drift_detection",
    "response latency drift detection": "response_time_drift_detection",
    "latency drift": "response_time_drift_detection",
    "latency drift detection": "response_time_drift_detection",
    "response time shift": "response_time_drift_detection",
    "response time shift detection": "response_time_drift_detection",
    "response time change": "response_time_drift_detection",
    "response time change detection": "response_time_drift_detection",
    "response time anomaly": "response_time_drift_detection",
    "response time anomaly detection": "response_time_drift_detection",
    "response time deviation": "response_time_drift_detection",
    "response time deviation detection": "response_time_drift_detection",
    "response time trend": "response_time_drift_detection",
    "response time trend detection": "response_time_drift_detection",
    "response time misspelling": "response_time_drift_detection",
    "response tiem drift": "response_time_drift_detection",
    "response time drft": "response_time_drift_detection",
    "response time drfit": "response_time_drift_detection",
    # Error Rate Drift Analysis
    "error rate drift": "error_rate_drift_analysis",
    "error rate drift analysis": "error_rate_drift_analysis",
    "error drift": "error_rate_drift_analysis",
    "error drift analysis": "error_rate_drift_analysis",
    "rate drift": "error_rate_drift_analysis",
    "rate drift analysis": "error_rate_drift_analysis",
    "error rate shift": "error_rate_drift_analysis",
    "error rate shift analysis": "error_rate_drift_analysis",
    "error rate change": "error_rate_drift_analysis",
    "error rate change analysis": "error_rate_drift_analysis",
    "error rate anomaly": "error_rate_drift_analysis",
    "error rate anomaly analysis": "error_rate_drift_analysis",
    "error rate deviation": "error_rate_drift_analysis",
    "error rate deviation analysis": "error_rate_drift_analysis",
    "error rate trend": "error_rate_drift_analysis",
    "error rate trend analysis": "error_rate_drift_analysis",
    "error rate misspelling": "error_rate_drift_analysis",
    "error raet drift": "error_rate_drift_analysis",
    "error rate drft": "error_rate_drift_analysis",
    "error rate drfit": "error_rate_drift_analysis",
    # Confidence Score Distribution Shift
    "confidence score distribution": "confidence_score_distribution_shift",
    "confidence score distribution shift": "confidence_score_distribution_shift",
    "confidence distribution": "confidence_score_distribution_shift",
    "confidence distribution shift": "confidence_score_distribution_shift",
    "score distribution shift": "confidence_score_distribution_shift",
    "score distribution": "confidence_score_distribution_shift",
    "confidence score shift": "confidence_score_distribution_shift",
    "confidence shift": "confidence_score_distribution_shift",
    "confidence score deviation": "confidence_score_distribution_shift",
    "confidence score deviation shift": "confidence_score_distribution_shift",
    "confidence score trend": "confidence_score_distribution_shift",
    "confidence score trend shift": "confidence_score_distribution_shift",
    "confidence score anomaly": "confidence_score_distribution_shift",
    "confidence score anomaly shift": "confidence_score_distribution_shift",
    "confidence score misspelling": "confidence_score_distribution_shift",
    "confidence scroe distribution": "confidence_score_distribution_shift",
    "confidence score distrbution": "confidence_score_distribution_shift",
    "confidence score distribtion": "confidence_score_distribution_shift",
    # Output Quality Metric Drift
    "output quality metric": "output_quality_metric_drift",
    "output quality metric drift": "output_quality_metric_drift",
    "output metric drift": "output_quality_metric_drift",
    "output metric": "output_quality_metric_drift",
    "quality metric drift": "output_quality_metric_drift",
    "quality metric": "output_quality_metric_drift",
    "output quality drift": "output_quality_metric_drift",
    "output quality": "output_quality_metric_drift",
    "output metric shift": "output_quality_metric_drift",
    "output metric change": "output_quality_metric_drift",
    "output metric anomaly": "output_quality_metric_drift",
    "output metric deviation": "output_quality_metric_drift",
    "output metric trend": "output_quality_metric_drift",
    "output metric misspelling": "output_quality_metric_drift",
    "output qulaity metric": "output_quality_metric_drift",
    "output quality metrc": "output_quality_metric_drift",
    "output quality metic": "output_quality_metric_drift",
    # Behavioral Fingerprinting per Engine
    "behavioral fingerprinting": "behavioral_fingerprinting_per_engine",
    "behavioral fingerprinting per engine": "behavioral_fingerprinting_per_engine",
    "engine fingerprinting": "behavioral_fingerprinting_per_engine",
    "engine behavioral fingerprinting": "behavioral_fingerprinting_per_engine",
    "behavior fingerprinting": "behavioral_fingerprinting_per_engine",
    "behavior fingerprinting per engine": "behavioral_fingerprinting_per_engine",
    "engine behavior fingerprinting": "behavioral_fingerprinting_per_engine",
    "fingerprinting": "behavioral_fingerprinting_per_engine",
    "fingerprinting per engine": "behavioral_fingerprinting_per_engine",
    "behavioral fingerprint": "behavioral_fingerprinting_per_engine",
    "behavioral fingerprint per engine": "behavioral_fingerprinting_per_engine",
    "engine fingerprint": "behavioral_fingerprinting_per_engine",
    "engine behavioral fingerprint": "behavioral_fingerprinting_per_engine",
    "behavior fingerprint": "behavioral_fingerprinting_per_engine",
    "behavior fingerprint per engine": "behavioral_fingerprinting_per_engine",
    "engine behavior fingerprint": "behavioral_fingerprinting_per_engine",
    "fingerprint": "behavioral_fingerprinting_per_engine",
    "fingerprint per engine": "behavioral_fingerprinting_per_engine",
    "behavioral misspelling": "behavioral_fingerprinting_per_engine",
    "behavoral fingerprinting": "behavioral_fingerprinting_per_engine",
    "behavioral fingerpriting": "behavioral_fingerprinting_per_engine",
    "behavioral fingerpriting per engine": "behavioral_fingerprinting_per_engine",
    # Seasonal Pattern Accounting
    "seasonal pattern": "seasonal_pattern_accounting",
    "seasonal pattern accounting": "seasonal_pattern_accounting",
    "seasonality": "seasonal_pattern_accounting",
    "seasonality accounting": "seasonal_pattern_accounting",
    "pattern accounting": "seasonal_pattern_accounting",
    "seasonal accounting": "seasonal_pattern_accounting",
    "seasonal trend": "seasonal_pattern_accounting",
    "seasonal trend accounting": "seasonal_pattern_accounting",
    "seasonal pattern analysis": "seasonal_pattern_accounting",
    "seasonal pattern detection": "seasonal_pattern_accounting",
    "seasonal pattern tracking": "seasonal_pattern_accounting",
    "seasonal pattern monitor": "seasonal_pattern_accounting",
    "seasonal pattern monitoring": "seasonal_pattern_accounting",
    "seasonal misspelling": "seasonal_pattern_accounting",
    "seasonal patten": "seasonal_pattern_accounting",
    "seasonal patern": "seasonal_pattern_accounting",
    "seasonal pattrn": "seasonal_pattern_accounting",
    # Alert Fatigue Prevention: Minimum Severity Thresholds
    "alert fatigue prevention": "alert_fatigue_prevention_min_severity_thresholds",
    "minimum severity threshold": "alert_fatigue_prevention_min_severity_thresholds",
    "minimum severity thresholds": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue prevention minimum severity": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue prevention minimum severity threshold": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue prevention minimum severity thresholds": "alert_fatigue_prevention_min_severity_thresholds",
    "alert threshold": "alert_fatigue_prevention_min_severity_thresholds",
    "alert thresholds": "alert_fatigue_prevention_min_severity_thresholds",
    "severity threshold": "alert_fatigue_prevention_min_severity_thresholds",
    "severity thresholds": "alert_fatigue_prevention_min_severity_thresholds",
    "minimum alert threshold": "alert_fatigue_prevention_min_severity_thresholds",
    "minimum alert thresholds": "alert_fatigue_prevention_min_severity_thresholds",
    "minimum severity": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue misspelling": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatiuge prevention": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue prevetion": "alert_fatigue_prevention_min_severity_thresholds",
    "alert fatigue prevntion": "alert_fatigue_prevention_min_severity_thresholds",
    # Anomaly Correlation Across Engines
    "anomaly correlation": "anomaly_correlation_across_engines",
    "anomaly correlation across engines": "anomaly_correlation_across_engines",
    "correlation across engines": "anomaly_correlation_across_engines",
    "engine anomaly correlation": "anomaly_correlation_across_engines",
    "engine correlation": "anomaly_correlation_across_engines",
    "anomaly correlation engine": "anomaly_correlation_across_engines",
    "anomaly correlation engines": "anomaly_correlation_across_engines",
    "correlation anomaly": "anomaly_correlation_across_engines",
    "correlation anomaly engine": "anomaly_correlation_across_engines",
    "correlation anomaly engines": "anomaly_correlation_across_engines",
    "anomaly misspelling": "anomaly_correlation_across_engines",
    "anomaly correaltion": "anomaly_correlation_across_engines",
    "anomaly correlaton": "anomaly_correlation_across_engines",
    "anomaly correltion": "anomaly_correlation_across_engines",
    # Root Cause Inference from Anomaly Patterns
    "root cause inference": "root_cause_inference_from_anomaly_patterns",
    "root cause inference from anomaly patterns": "root_cause_inference_from_anomaly_patterns",
    "anomaly pattern root cause inference": "root_cause_inference_from_anomaly_patterns",
    "anomaly root cause inference": "root_cause_inference_from_anomaly_patterns",
    "pattern root cause inference": "root_cause_inference_from_anomaly_patterns",
    "root cause analysis": "root_cause_inference_from_anomaly_patterns",
    "root cause detection": "root_cause_inference_from_anomaly_patterns",
    "root cause tracking": "root_cause_inference_from_anomaly_patterns",
    "root cause monitor": "root_cause_inference_from_anomaly_patterns",
    "root cause monitoring": "root_cause_inference_from_anomaly_patterns",
    "root cause misspelling": "root_cause_inference_from_anomaly_patterns",
    "root cuase inference": "root_cause_inference_from_anomaly_patterns",
    "root cause infernce": "root_cause_inference_from_anomaly_patterns",
    "root cause inferece": "root_cause_inference_from_anomaly_patterns",
    # Anomaly Severity Classification
    "anomaly severity classification": "anomaly_severity_classification",
    "severity classification": "anomaly_severity_classification",
    "anomaly classification": "anomaly_severity_classification",
    "severity class": "anomaly_severity_classification",
    "anomaly class": "anomaly_severity_classification",
    "anomaly severity class": "anomaly_severity_classification",
    "anomaly severity": "anomaly_severity_classification",
    "severity anomaly": "anomaly_severity_classification",
    "severity anomaly classification": "anomaly_severity_classification",
    "severity anomaly class": "anomaly_severity_classification",
    "anomaly severity misspelling": "anomaly_severity_classification",
    "anomaly severty classification": "anomaly_severity_classification",
    "anomaly severity clasification": "anomaly_severity_classification",
    "anomaly severity classfication": "anomaly_severity_classification",
    # Trending vs Sudden Anomalies
    "trending anomaly": "trending_vs_sudden_anomalies",
    "trending anomalies": "trending_vs_sudden_anomalies",
    "trending vs sudden anomalies": "trending_vs_sudden_anomalies",
    "trending vs sudden anomaly": "trending_vs_sudden_anomalies",
    "sudden anomaly": "trending_vs_sudden_anomalies",
    "sudden anomalies": "trending_vs_sudden_anomalies",
    "anomaly trend": "trending_vs_sudden_anomalies",
    "anomaly trending": "trending_vs_sudden_anomalies",
    "anomaly sudden": "trending_vs_sudden_anomalies",
    "anomaly misspelling": "trending_vs_sudden_anomalies",
    "trending anomly": "trending_vs_sudden_anomalies",
    "trending anomlies": "trending_vs_sudden_anomalies",
    "trending vs suden anomalies": "trending_vs_sudden_anomalies",
    "trending vs suden anomaly": "trending_vs_sudden_anomalies",
    "sudden anomly": "trending_vs_sudden_anomalies",
    "sudden anomlies": "trending_vs_sudden_anomalies",
    # Phantom Load Detection
    "phantom load": "phantom_load_detection",
    "phantom load detection": "phantom_load_detection",
    "phantom detection": "phantom_load_detection",
    "phantom load anomaly": "phantom_load_detection",
    "phantom load anomaly detection": "phantom_load_detection",
    "phantom load outlier": "phantom_load_detection",
    "phantom load outlier detection": "phantom_load_detection",
    "phantom load misspelling": "phantom_load_detection",
    "phantom lod detection": "phantom_load_detection",
    "phantom load detction": "phantom_load_detection",
    "phantom load detecton": "phantom_load_detection",
    # Resource Leak Pattern Detection
    "resource leak": "resource_leak_pattern_detection",
    "resource leak pattern": "resource_leak_pattern_detection",
    "resource leak pattern detection": "resource_leak_pattern_detection",
    "resource leak detection": "resource_leak_pattern_detection",
    "resource leak anomaly": "resource_leak_pattern_detection",
    "resource leak anomaly detection": "resource_leak_pattern_detection",
    "resource leak outlier": "resource_leak_pattern_detection",
    "resource leak outlier detection": "resource_leak_pattern_detection",
    "resource leak misspelling": "resource_leak_pattern_detection",
    "resource leakk pattern detection": "resource_leak_pattern_detection",
    "resource leak patten detection": "resource_leak_pattern_detection",
    "resource leak pattrn detection": "resource_leak_pattern_detection",
    # Memory Growth Analysis
    "memory growth": "memory_growth_analysis",
    "memory growth analysis": "memory_growth_analysis",
    "memory analysis": "memory_growth_analysis",
    "memory growth detection": "memory_growth_analysis",
    "memory growth anomaly": "memory_growth_analysis",
    "memory growth anomaly detection": "memory_growth_analysis",
    "memory growth outlier": "memory_growth_analysis",
    "memory growth outlier detection": "memory_growth_analysis",
    "memory growth misspelling": "memory_growth_analysis",
    "memory groth analysis": "memory_growth_analysis",
    "memory growth anlaysis": "memory_growth_analysis",
    "memory growth analaysis": "memory_growth_analysis",
    # Connection Pool Drift Detection
    "connection pool drift": "connection_pool_drift_detection",
    "connection pool drift detection": "connection_pool_drift_detection",
    "connection drift": "connection_pool_drift_detection",
    "connection drift detection": "connection_pool_drift_detection",
    "pool drift": "connection_pool_drift_detection",
    "pool drift detection": "connection_pool_drift_detection",
    "connection pool anomaly": "connection_pool_drift_detection",
    "connection pool anomaly detection": "connection_pool_drift_detection",
    "connection pool outlier": "connection_pool_drift_detection",
    "connection pool outlier detection": "connection_pool_drift_detection",
    "connection pool misspelling": "connection_pool_drift_detection",
    "connection pol drift detection": "connection_pool_drift_detection",
    "connection pool drft detection": "connection_pool_drift_detection",
    "connection pool drfit detection": "connection_pool_drift_detection",
    # Cache Hit Rate Degradation
    "cache hit rate": "cache_hit_rate_degradation",
    "cache hit rate degradation": "cache_hit_rate_degradation",
    "cache hit degradation": "cache_hit_rate_degradation",
    "cache hit rate anomaly": "cache_hit_rate_degradation",
    "cache hit rate anomaly detection": "cache_hit_rate_degradation",
    "cache hit rate outlier": "cache_hit_rate_degradation",
    "cache hit rate outlier detection": "cache_hit_rate_degradation",
    "cache hit rate misspelling": "cache_hit_rate_degradation",
    "cache hit raet degradation": "cache_hit_rate_degradation",
    "cache hit rate degradtion": "cache_hit_rate_degradation",
    "cache hit rate degradtion": "cache_hit_rate_degradation",
    # API Latency Distribution Shift
    "api latency distribution": "api_latency_distribution_shift",
    "api latency distribution shift": "api_latency_distribution_shift",
    "api latency shift": "api_latency_distribution_shift",
    "api latency": "api_latency_distribution_shift",
    "api distribution shift": "api_latency_distribution_shift",
    "api distribution": "api_latency_distribution_shift",
    "api latency deviation": "api_latency_distribution_shift",
    "api latency deviation shift": "api_latency_distribution_shift",
    "api latency trend": "api_latency_distribution_shift",
    "api latency trend shift": "api_latency_distribution_shift",
    "api latency anomaly": "api_latency_distribution_shift",
    "api latency anomaly shift": "api_latency_distribution_shift",
    "api latency misspelling": "api_latency_distribution_shift",
    "api latnecy distribution": "api_latency_distribution_shift",
    "api latency distrbution": "api_latency_distribution_shift",
    "api latency distribtion": "api_latency_distribution_shift",
    # Data Quality Drift Indicators
    "data quality drift": "data_quality_drift_indicators",
    "data quality drift indicators": "data_quality_drift_indicators",
    "data drift indicators": "data_quality_drift_indicators",
    "data quality indicators": "data_quality_drift_indicators",
    "data drift": "data_quality_drift_indicators",
    "data drift indicator": "data_quality_drift_indicators",
    "data quality drift indicator": "data_quality_drift_indicators",
    "data quality indicator": "data_quality_drift_indicators",
    "data quality anomaly": "data_quality_drift_indicators",
    "data quality anomaly detection": "data_quality_drift_indicators",
    "data quality outlier": "data_quality_drift_indicators",
    "data quality outlier detection": "data_quality_drift_indicators",
    "data quality misspelling": "data_quality_drift_indicators",
    "data qulaity drift indicators": "data_quality_drift_indicators",
    "data quality drft indicators": "data_quality_drift_indicators",
    "data quality drfit indicators": "data_quality_drift_indicators",
    # Additional synonyms, abbreviations, acronyms, misspellings, related terms
    "anomaly detection": "anomaly_detection",
    "outlier detection": "anomaly_detection",
    "anomaly": "anomaly_detection",
    "outlier": "anomaly_detection",
    "anomaly analysis": "anomaly_detection",
    "outlier analysis": "anomaly_detection",
    "anomaly tracking": "anomaly_detection",
    "outlier tracking": "anomaly_detection",
    "anomaly monitor": "anomaly_detection",
    "outlier monitor": "anomaly_detection",
    "anomaly monitoring": "anomaly_detection",
    "outlier monitoring": "anomaly_detection",
    "anomaly misspelling": "anomaly_detection",
    "anomly detection": "anomaly_detection",
    "anomaly detction": "anomaly_detection",
    "anomaly detecton": "anomaly_detection",
    "anomly analysis": "anomaly_detection",
    "anomaly anlaysis": "anomaly_detection",
    "anomaly analaysis": "anomaly_detection",
    "anomly tracking": "anomaly_detection",
    "anomaly traking": "anomaly_detection",
    "anomaly traccking": "anomaly_detection",
    "anomaly monitorng": "anomaly_detection",
    "anomaly monitroing": "anomaly_detection",
    "anomaly monitring": "anomaly_detection",
    "outlier misspelling": "anomaly_detection",
    "outlier detction": "anomaly_detection",
    "outlier detecton": "anomaly_detection",
    "outlier anlaysis": "anomaly_detection",
    "outlier analaysis": "anomaly_detection",
    "outlier traking": "anomaly_detection",
    "outlier traccking": "anomaly_detection",
    "outlier monitorng": "anomaly_detection",
    "outlier monitroing": "anomaly_detection",
    "outlier monitring": "anomaly_detection",
    "drift detection": "drift_detection",
    "drift analysis": "drift_detection",
    "drift tracking": "drift_detection",
    "drift monitor": "drift_detection",
    "drift monitoring": "drift_detection",
    "drift misspelling": "drift_detection",
    "drft detection": "drift_detection",
    "drift detction": "drift_detection",
    "drift detecton": "drift_detection",
    "drft analysis": "drift_detection",
    "drift anlaysis": "drift_detection",
    "drift analaysis": "drift_detection",
    "drft tracking": "drift_detection",
    "drift traking": "drift_detection",
    "drift traccking": "drift_detection",
    "drift monitorng": "drift_detection",
    "drift monitroing": "drift_detection",
    "drift monitring": "drift_detection",
    "baseline": "engine_performance_baseline_tracking",
    "baseline detection": "engine_performance_baseline_tracking",
    "baseline analysis": "engine_performance_baseline_tracking",
    "baseline tracking": "engine_performance_baseline_tracking",
    "baseline monitor": "engine_performance_baseline_tracking",
    "baseline monitoring": "engine_performance_baseline_tracking",
    "baseline misspelling": "engine_performance_baseline_tracking",
    "basline detection": "engine_performance_baseline_tracking",
    "baseline detction": "engine_performance_baseline_tracking",
    "baseline detecton": "engine_performance_baseline_tracking",
    "basline analysis": "engine_performance_baseline_tracking",
    "baseline anlaysis": "engine_performance_baseline_tracking",
    "baseline analaysis": "engine_performance_baseline_tracking",
    "basline tracking": "engine_performance_baseline_tracking",
    "baseline traking": "engine_performance_baseline_tracking",
    "baseline traccking": "engine_performance_baseline_tracking",
    "baseline monitorng": "engine_performance_baseline_tracking",
    "baseline monitroing": "engine_performance_baseline_tracking",
    "baseline monitring": "engine_performance_baseline_tracking",
    "trend detection": "trend_detection",
    "trend analysis": "trend_detection",
    "trend tracking": "trend_detection",
    "trend monitor": "trend_detection",
    "trend monitoring": "trend_detection",
    "trend misspelling": "trend_detection",
    "trnd detection": "trend_detection",
    "trend detction": "trend_detection",
    "trend detecton": "trend_detection",
    "trnd analysis": "trend_detection",
    "trend anlaysis": "trend_detection",
    "trend analaysis": "trend_detection",
    "trnd tracking": "trend_detection",
    "trend traking": "trend_detection",
    "trend traccking": "trend_detection",
    "trend monitorng": "trend_detection",
    "trend monitroing": "trend_detection",
    "trend monitring": "trend_detection",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash() -> str:
    items = sorted(SEMANTIC_MAP.items())
    hash_input = "".join([f"{k}:{v}" for k, v in items])
    return hashlib.sha256(hash_input.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity() -> Dict[str, object]:
    actual_hash = _compute_map_hash()
    is_valid = (actual_hash == _MAP_INTEGRITY_HASH) and (len(SEMANTIC_MAP) == _EXPECTED_ENTRY_COUNT)
    return {
        "status": "ok" if is_valid else "corrupt",
        "entries": len(SEMANTIC_MAP),
        "hash": actual_hash,
        "is_valid": is_valid,
    }

def normalize_term(term: str) -> str:
    term = term.lower()
    term = re.sub(r"\s+", " ", term)
    term = term.strip()
    if term in SEMANTIC_MAP:
        return SEMANTIC_MAP[term]
    # Try removing punctuation and retry
    term_nopunct = re.sub(r"[^\w\s]", "", term)
    if term_nopunct in SEMANTIC_MAP:
        return SEMANTIC_MAP[term_nopunct]
    # Try replacing underscores with spaces and retry
    term_underscore = term.replace("_", " ")
    if term_underscore in SEMANTIC_MAP:
        return SEMANTIC_MAP[term_underscore]
    # Try removing extra spaces and retry
    term_extraspace = re.sub(r"\s+", " ", term_underscore).strip()
    if term_extraspace in SEMANTIC_MAP:
        return SEMANTIC_MAP[term_extraspace]
    return term

def get_related_terms(term: str) -> List[str]:
    norm = normalize_term(term)
    related = []
    for k, v in SEMANTIC_MAP.items():
        if v == norm and k != term:
            related.append(k)
    return related

def get_all_mappings() -> Dict[str, str]:
    return dict(SEMANTIC_MAP)