import hashlib
import re

SEMANTIC_MAP_VERSION = "1.0.0"
SEMANTIC_MAP_AUTHOR = "PROD08 Team"
SEMANTIC_MAP_ENGINE = "PROD08_sand_control"

SEMANTIC_MAP = {
    "critical drawdown pressure": "critical_drawdown_pressure",
    "cdp": "critical_drawdown_pressure",
    "drawdown limit": "critical_drawdown_pressure",
    "drawdown threshold": "critical_drawdown_pressure",
    "drawdown pressure": "critical_drawdown_pressure",
    "drawdown": "critical_drawdown_pressure",
    "sand production threshold": "critical_drawdown_pressure",
    "sand onset pressure": "critical_drawdown_pressure",
    "sand failure pressure": "critical_drawdown_pressure",
    "wellbore stability": "critical_drawdown_pressure",
    "thick wall cylinder testing": "thick_wall_cylinder_testing",
    "twct": "thick_wall_cylinder_testing",
    "thick-walled cylinder test": "thick_wall_cylinder_testing",
    "cylinder test": "thick_wall_cylinder_testing",
    "formation sand analysis": "formation_sand_analysis",
    "sand analysis": "formation_sand_analysis",
    "sand characterization": "formation_sand_analysis",
    "particle size analysis": "formation_sand_analysis",
    "grain size distribution": "formation_sand_analysis",
    "sieve analysis": "formation_sand_analysis",
    "sand sample": "formation_sand_analysis",
    "sand properties": "formation_sand_analysis",
    "sand mineralogy": "formation_sand_analysis",
    "gravel sizing criteria": "gravel_sizing_criteria",
    "gravel size selection": "gravel_sizing_criteria",
    "gravel pack sizing": "gravel_sizing_criteria",
    "gravel pack design": "gravel_sizing_criteria",
    "gravel pack": "gravel_pack_placement",
    "gravel pack placement": "gravel_pack_placement",
    "gravel placement": "gravel_pack_placement",
    "gravel packing": "gravel_pack_placement",
    "gravel pack installation": "gravel_pack_placement",
    "gravel pack completion": "gravel_pack_placement",
    "wire-wrapped screen design": "wire_wrapped_screen_design",
    "wire wrapped screen": "wire_wrapped_screen_design",
    "wire wrap screen": "wire_wrapped_screen_design",
    "wire screen": "wire_wrapped_screen_design",
    "wire-wrapped screen": "wire_wrapped_screen_design",
    "wire wrap": "wire_wrapped_screen_design",
    "premium mesh screen selection": "premium_mesh_screen_selection",
    "premium mesh screen": "premium_mesh_screen_selection",
    "mesh screen": "premium_mesh_screen_selection",
    "mesh selection": "premium_mesh_screen_selection",
    "expandable sand screen technology": "expandable_sand_screen_technology",
    "expandable sand screen": "expandable_sand_screen_technology",
    "ess": "expandable_sand_screen_technology",
    "expandable screen": "expandable_sand_screen_technology",
    "sand screen": "expandable_sand_screen_technology",
    "frac pack vs gravel pack decision": "frac_pack_vs_gravel_pack_decision",
    "frac pack": "frac_pack_vs_gravel_pack_decision",
    "gravel pack vs frac pack": "frac_pack_vs_gravel_pack_decision",
    "frac-pack": "frac_pack_vs_gravel_pack_decision",
    "frac/gravel pack": "frac_pack_vs_gravel_pack_decision",
    "frac pack selection": "frac_pack_vs_gravel_pack_decision",
    "proppant selection for frac pack": "proppant_selection_for_frac_pack",
    "proppant selection": "proppant_selection_for_frac_pack",
    "proppant": "proppant_selection_for_frac_pack",
    "proppant sizing": "proppant_selection_for_frac_pack",
    "proppant type": "proppant_selection_for_frac_pack",
    "resin consolidation systems": "resin_consolidation_systems",
    "resin consolidation": "resin_consolidation_systems",
    "resin system": "resin_consolidation_systems",
    "resin sand control": "resin_consolidation_systems",
    "resin": "resin_consolidation_systems",
    "resin coated sand": "resin_consolidation_systems",
    "acoustic sand monitoring": "acoustic_sand_monitoring",
    "acoustic monitoring": "acoustic_sand_monitoring",
    "sand monitoring": "acoustic_sand_monitoring",
    "sand detection": "acoustic_sand_monitoring",
    "acoustic sand detection": "acoustic_sand_monitoring",
    "acoustic emission": "acoustic_sand_monitoring",
    "sand sensor": "acoustic_sand_monitoring",
    "erosion monitoring and inspection": "erosion_monitoring_and_inspection",
    "erosion monitoring": "erosion_monitoring_and_inspection",
    "erosion inspection": "erosion_monitoring_and_inspection",
    "erosion detection": "erosion_monitoring_and_inspection",
    "erosion analysis": "erosion_monitoring_and_inspection",
    "sand control economics": "sand_control_economics",
    "sand economics": "sand_control_economics",
    "sand control cost": "sand_control_economics",
    "sand control budgeting": "sand_control_economics",
    "sand management economics": "sand_control_economics",
    "sand management vs sand exclusion": "sand_management_vs_sand_exclusion",
    "sand management": "sand_management_vs_sand_exclusion",
    "sand exclusion": "sand_management_vs_sand_exclusion",
    "sand exclusion strategy": "sand_management_vs_sand_exclusion",
    "sand management strategy": "sand_management_vs_sand_exclusion",
    "perforation strategy for sand control": "perforation_strategy_for_sand_control",
    "perforation strategy": "perforation_strategy_for_sand_control",
    "sand control perforation": "perforation_strategy_for_sand_control",
    "perforation design": "perforation_strategy_for_sand_control",
    "perforation": "perforation_strategy_for_sand_control",
    "slotted liner vs screen completions": "slotted_liner_vs_screen_completions",
    "slotted liner": "slotted_liner_vs_screen_completions",
    "screen completion": "slotted_liner_vs_screen_completions",
    "screen completions": "slotted_liner_vs_screen_completions",
    "slotted liner completion": "slotted_liner_vs_screen_completions",
    "slotted liner vs screen": "slotted_liner_vs_screen_completions",
    "oriented perforation for sand control": "oriented_perforation_for_sand_control",
    "oriented perforation": "oriented_perforation_for_sand_control",
    "perforation orientation": "oriented_perforation_for_sand_control",
    "multi-zone sand control completions": "multi_zone_sand_control_completions",
    "multi-zone completion": "multi_zone_sand_control_completions",
    "multi zone completion": "multi_zone_sand_control_completions",
    "multi-zone sand control": "multi_zone_sand_control_completions",
    "multi zone sand control": "multi_zone_sand_control_completions",
    "horizontal well sand control challenges": "horizontal_well_sand_control_challenges",
    "horizontal well sand control": "horizontal_well_sand_control_challenges",
    "horizontal sand control": "horizontal_well_sand_control_challenges",
    "horizontal well completion": "horizontal_well_sand_control_challenges",
    "horizontal completion": "horizontal_well_sand_control_challenges",
    "sand control challenges": "horizontal_well_sand_control_challenges",
    "wellbore sand control": "horizontal_well_sand_control_challenges",
    "wellbore sand": "horizontal_well_sand_control_challenges",
    "sand control": "sand_control",
    "sand control system": "sand_control",
    "sand control technology": "sand_control",
    "sand control method": "sand_control",
    "sand control solution": "sand_control",
    "sand control completion": "sand_control",
    "sand control design": "sand_control",
    "sand control screen": "sand_control",
    "sand control equipment": "sand_control",
    "sand control device": "sand_control",
    "sand control tool": "sand_control",
    "sand control filter": "sand_control",
    "sand control mesh": "sand_control",
    "sand control pack": "sand_control",
    "sand control liner": "sand_control",
    "sand control casing": "sand_control",
    "sand control pipe": "sand_control",
    "sand control tube": "sand_control",
    "sand control well": "sand_control",
    "sand control reservoir": "sand_control",
    "sand control formation": "sand_control",
    "sand control zone": "sand_control",
    "sand control interval": "sand_control",
    "sand control section": "sand_control",
    "sand control area": "sand_control",
    "sand control region": "sand_control",
    "sand control field": "sand_control",
    "sand control project": "sand_control",
    "sand control operation": "sand_control",
    "sand control process": "sand_control",
    "sand control procedure": "sand_control",
    "sand control practice": "sand_control",
    "sand control application": "sand_control",
    "sand control performance": "sand_control",
    "sand control efficiency": "sand_control",
    "sand control reliability": "sand_control",
    "sand control durability": "sand_control",
    "sand control longevity": "sand_control",
    "sand control maintenance": "sand_control",
    "sand control inspection": "sand_control",
    "sand control monitoring": "sand_control",
    "sand control evaluation": "sand_control",
    "sand control assessment": "sand_control",
    "sand control testing": "sand_control",
    "sand control analysis": "sand_control",
    "sand control study": "sand_control",
    "sand control research": "sand_control",
    "sand control review": "sand_control",
    "sand control report": "sand_control",
    "sand control documentation": "sand_control",
    "sand control record": "sand_control",
    "sand control data": "sand_control",
    "sand control information": "sand_control",
    "sand control knowledge": "sand_control",
    "sand control expertise": "sand_control",
    "sand control experience": "sand_control",
    "sand control training": "sand_control",
    "sand control education": "sand_control",
    "sand control qualification": "sand_control",
    "sand control certification": "sand_control",
    "sand control accreditation": "sand_control",
    "sand control license": "sand_control",
    "sand control permit": "sand_control",
    "sand control approval": "sand_control",
    "sand control authorization": "sand_control",
    "sand control compliance": "sand_control",
    "sand control regulation": "sand_control",
    "sand control standard": "sand_control",
    "sand control guideline": "sand_control",
    "sand control policy": "sand_control",
    "sand control rule": "sand_control",
    "sand control requirement": "sand_control",
    "sand control specification": "sand_control",
    "sand control criteria": "sand_control",
    "sand control parameter": "sand_control",
    "sand control factor": "sand_control",
    "sand control variable": "sand_control",
    "sand control attribute": "sand_control",
    "sand control characteristic": "sand_control",
    "sand control feature": "sand_control",
    "sand control property": "sand_control",
    "sand control aspect": "sand_control",
    "sand control element": "sand_control",
    "sand control component": "sand_control",
    "sand control part": "sand_control",
    "sand control piece": "sand_control",
    "sand control section": "sand_control",
    "sand control segment": "sand_control",
    "sand control division": "sand_control",
    "sand control subdivision": "sand_control",
    "sand control category": "sand_control",
    "sand control type": "sand_control",
    "sand control class": "sand_control",
    "sand control group": "sand_control",
    "sand control set": "sand_control",
    "sand control series": "sand_control",
    "sand control batch": "sand_control",
    "sand control lot": "sand_control",
    "sand control collection": "sand_control",
    "sand control assortment": "sand_control",
    "sand control selection": "sand_control",
    "sand control choice": "sand_control",
    "sand control option": "sand_control",
    "sand control alternative": "sand_control",
    "sand control variant": "sand_control",
    "sand control version": "sand_control",
    "sand control model": "sand_control",
    "sand control design": "sand_control",
    "sand control plan": "sand_control",
    "sand control scheme": "sand_control",
    "sand control strategy": "sand_control",
    "sand control tactic": "sand_control",
    "sand control approach": "sand_control",
    "sand control method": "sand_control",
    "sand control technique": "sand_control",
    "sand control procedure": "sand_control",
    "sand control process": "sand_control",
    "sand control operation": "sand_control",
    "sand control activity": "sand_control",
    "sand control task": "sand_control",
    "sand control job": "sand_control",
    "sand control function": "sand_control",
    "sand control role": "sand_control",
    "sand control responsibility": "sand_control",
    "sand control duty": "sand_control",
    "sand control obligation": "sand_control",
    "sand control requirement": "sand_control",
    "sand control need": "sand_control",
    "sand control demand": "sand_control",
    "sand control request": "sand_control",
    "sand control order": "sand_control",
    "sand control command": "sand_control",
    "sand control instruction": "sand_control",
    "sand control directive": "sand_control",
    "sand control guidance": "sand_control",
    "sand control advice": "sand_control",
    "sand control recommendation": "sand_control",
    "sand control suggestion": "sand_control",
    "sand control proposal": "sand_control",
    "sand control offer": "sand_control",
    "sand control bid": "sand_control",
    "sand control tender": "sand_control",
    "sand control contract": "sand_control",
    "sand control agreement": "sand_control",
    "sand control deal": "sand_control",
    "sand control arrangement": "sand_control",
    "sand control settlement": "sand_control",
    "sand control negotiation": "sand_control",
    "sand control discussion": "sand_control",
    "sand control consultation": "sand_control",
    "sand control conference": "sand_control",
    "sand control meeting": "sand_control",
    "sand control session": "sand_control",
    "sand control workshop": "sand_control",
    "sand control seminar": "sand_control",
    "sand control symposium": "sand_control",
    "sand control forum": "sand_control",
    "sand control panel": "sand_control",
    "sand control committee": "sand_control",
    "sand control board": "sand_control",
    "sand control council": "sand_control",
    "sand control group": "sand_control",
    "sand control team": "sand_control",
    "sand control staff": "sand_control",
    "sand control personnel": "sand_control",
    "sand control workforce": "sand_control",
    "sand control crew": "sand_control",
    "sand control operator": "sand_control",
    "sand control engineer": "sand_control",
    "sand control technician": "sand_control",
    "sand control specialist": "sand_control",
    "sand control expert": "sand_control",
    "sand control consultant": "sand_control",
    "sand control advisor": "sand_control",
    "sand control supervisor": "sand_control",
    "sand control manager": "sand_control",
    "sand control director": "sand_control",
    "sand control chief": "sand_control",
    "sand control leader": "sand_control",
    "sand control head": "sand_control",
    "sand control coordinator": "sand_control",
    "sand control facilitator": "sand_control",
    "sand control organizer": "sand_control",
    "sand control planner": "sand_control",
    "sand control scheduler": "sand_control",
    "sand control controller": "sand_control",
    "sand control monitor": "sand_control",
    "sand control inspector": "sand_control",
    "sand control auditor": "sand_control",
    "sand control reviewer": "sand_control",
    "sand control evaluator": "sand_control",
    "sand control assessor": "sand_control",
    "sand control tester": "sand_control",
    "sand control analyst": "sand_control",
    "sand control researcher": "sand_control",
    "sand control scientist": "sand_control",
    "sand control educator": "sand_control",
    "sand control trainer": "sand_control",
    "sand control instructor": "sand_control",
    "sand control mentor": "sand_control",
    "sand control coach": "sand_control",
    "sand control consultant": "sand_control",
    "sand control advisor": "sand_control",
    "sand control expert": "sand_control",
    "sand control specialist": "sand_control",
    "sand control engineer": "sand_control",
    "sand control technician": "sand_control",
    "sand control operator": "sand_control",
    "sand control crew": "sand_control",
    "sand control workforce": "sand_control",
    "sand control personnel": "sand_control",
    "sand control staff": "sand_control",
    "sand control team": "sand_control",
    "sand control group": "sand_control",
    "sand control committee": "sand_control",
    "sand control panel": "sand_control",
    "sand control forum": "sand_control",
    "sand control symposium": "sand_control",
    "sand control seminar": "sand_control",
    "sand control workshop": "sand_control",
    "sand control session": "sand_control",
    "sand control meeting": "sand_control",
    "sand control conference": "sand_control",
    "sand control discussion": "sand_control",
    "sand control negotiation": "sand_control",
    "sand control settlement": "sand_control",
    "sand control arrangement": "sand_control",
    "sand control deal": "sand_control",
    "sand control agreement": "sand_control",
    "sand control contract": "sand_control",
    "sand control tender": "sand_control",
    "sand control bid": "sand_control",
    "sand control offer": "sand_control",
    "sand control proposal": "sand_control",
    "sand control suggestion": "sand_control",
    "sand control recommendation": "sand_control",
    "sand control advice": "sand_control",
    "sand control guidance": "sand_control",
    "sand control directive": "sand_control",
    "sand control instruction": "sand_control",
    "sand control command": "sand_control",
    "sand control order": "sand_control",
    "sand control request": "sand_control",
    "sand control demand": "sand_control",
    "sand control need": "sand_control",
    "sand control requirement": "sand_control",
    "sand control obligation": "sand_control",
    "sand control duty": "sand_control",
    "sand control responsibility": "sand_control",
    "sand control role": "sand_control",
    "sand control function": "sand_control",
    "sand control job": "sand_control",
    "sand control task": "sand_control",
    "sand control activity": "sand_control",
    "sand control operation": "sand_control",
    "sand control process": "sand_control",
    "sand control procedure": "sand_control",
    "sand control technique": "sand_control",
    "sand control method": "sand_control",
    "sand control approach": "sand_control",
    "sand control tactic": "sand_control",
    "sand control strategy": "sand_control",
    "sand control scheme": "sand_control",
    "sand control plan": "sand_control",
    "sand control design": "sand_control",
    "sand control model": "sand_control",
    "sand control version": "sand_control",
    "sand control variant": "sand_control",
    "sand control alternative": "sand_control",
    "sand control option": "sand_control",
    "sand control choice": "sand_control",
    "sand control selection": "sand_control",
    "sand control assortment": "sand_control",
    "sand control collection": "sand_control",
    "sand control lot": "sand_control",
    "sand control batch": "sand_control",
    "sand control series": "sand_control",
    "sand control set": "sand_control",
    "sand control group": "sand_control",
    "sand control class": "sand_control",
    "sand control type": "sand_control",
    "sand control category": "sand_control",
    "sand control subdivision": "sand_control",
    "sand control division": "sand_control",
    "sand control segment": "sand_control",
    "sand control section": "sand_control",
    "sand control piece": "sand_control",
    "sand control part": "sand_control",
    "sand control component": "sand_control",
    "sand control element": "sand_control",
    "sand control aspect": "sand_control",
    "sand control feature": "sand_control",
    "sand control characteristic": "sand_control",
    "sand control attribute": "sand_control",
    "sand control variable": "sand_control",
    "sand control factor": "sand_control",
    "sand control parameter": "sand_control",
    "sand control criteria": "sand_control",
    "sand control specification": "sand_control",
    "sand control requirement": "sand_control",
    "sand control rule": "sand_control",
    "sand control policy": "sand_control",
    "sand control guideline": "sand_control",
    "sand control standard": "sand_control",
    "sand control regulation": "sand_control",
    "sand control compliance": "sand_control",
    "sand control authorization": "sand_control",
    "sand control approval": "sand_control",
    "sand control permit": "sand_control",
    "sand control license": "sand_control",
    "sand control accreditation": "sand_control",
    "sand control certification": "sand_control",
    "sand control qualification": "sand_control",
    "sand control education": "sand_control",
    "sand control training": "sand_control",
    "sand control experience": "sand_control",
    "sand control expertise": "sand_control",
    "sand control knowledge": "sand_control",
    "sand control information": "sand_control",
    "sand control data": "sand_control",
    "sand control record": "sand_control",
    "sand control documentation": "sand_control",
    "sand control report": "sand_control",
    "sand control review": "sand_control",
    "sand control research": "sand_control",
    "sand control study": "sand_control",
    "sand control analysis": "sand_control",
    "sand control testing": "sand_control",
    "sand control assessment": "sand_control",
    "sand control evaluation": "sand_control",
    "sand control monitoring": "sand_control",
    "sand control inspection": "sand_control",
    "sand control maintenance": "sand_control",
    "sand control longevity": "sand_control",
    "sand control durability": "sand_control",
    "sand control reliability": "sand_control",
    "sand control efficiency": "sand_control",
    "sand control performance": "sand_control",
    "sand control application": "sand_control",
    "sand control practice": "sand_control",
    "sand control procedure": "sand_control",
    "sand control process": "sand_control",
    "sand control operation": "sand_control",
    "sand control project": "sand_control",
    "sand control field": "sand_control",
    "sand control region": "sand_control",
    "sand control area": "sand_control",
    "sand control section": "sand_control",
    "sand control interval": "sand_control",
    "sand control zone": "sand_control",
    "sand control formation": "sand_control",
    "sand control reservoir": "sand_control",
    "sand control well": "sand_control",
    "sand control tube": "sand_control",
    "sand control pipe": "sand_control",
    "sand control casing": "sand_control",
    "sand control liner": "sand_control",
    "sand control pack": "sand_control",
    "sand control mesh": "sand_control",
    "sand control filter": "sand_control",
    "sand control tool": "sand_control",
    "sand control device": "sand_control",
    "sand control equipment": "sand_control",
    "sand control screen": "sand_control",
    "sand control design": "sand_control",
    "sand control completion": "sand_control",
    "sand control solution": "sand_control",
    "sand control method": "sand_control",
    "sand control technology": "sand_control",
    "sand control system": "sand_control",
    "sand control": "sand_control",
    "sand": "sand_control",
    "sand management": "sand_management_vs_sand_exclusion",
    "sand exclusion": "sand_management_vs_sand_exclusion",
    "sand exclusion strategy": "sand_management_vs_sand_exclusion",
    "sand management strategy": "sand_management_vs_sand_exclusion",
    "sand control economics": "sand_control_economics",
    "sand control cost": "sand_control_economics",
    "sand control budgeting": "sand_control_economics",
    "sand management economics": "sand_control_economics",
    "sand monitoring": "acoustic_sand_monitoring",
    "sand detection": "acoustic_sand_monitoring",
    "sand sensor": "acoustic_sand_monitoring",
    "erosion monitoring": "erosion_monitoring_and_inspection",
    "erosion inspection": "erosion_monitoring_and_inspection",
    "erosion detection": "erosion_monitoring_and_inspection",
    "erosion analysis": "erosion_monitoring_and_inspection",
    "resin consolidation": "resin_consolidation_systems",
    "resin system": "resin_consolidation_systems",
    "resin sand control": "resin_consolidation_systems",
    "resin": "resin_consolidation_systems",
    "resin coated sand": "resin_consolidation_systems",
    "proppant selection": "proppant_selection_for_frac_pack",
    "proppant": "proppant_selection_for_frac_pack",
    "proppant sizing": "proppant_selection_for_frac_pack",
    "proppant type": "proppant_selection_for_frac_pack",
    "frac pack": "frac_pack_vs_gravel_pack_decision",
    "gravel pack vs frac pack": "frac_pack_vs_gravel_pack_decision",
    "frac-pack": "frac_pack_vs_gravel_pack_decision",
    "frac/gravel pack": "frac_pack_vs_gravel_pack_decision",
    "frac pack selection": "frac_pack_vs_gravel_pack_decision",
    "expandable sand screen": "expandable_sand_screen_technology",
    "ess": "expandable_sand_screen_technology",
    "expandable screen": "expandable_sand_screen_technology",
    "sand screen": "expandable_sand_screen_technology",
    "premium mesh screen": "premium_mesh_screen_selection",
    "mesh screen": "premium_mesh_screen_selection",
    "mesh selection": "premium_mesh_screen_selection",
    "wire wrapped screen": "wire_wrapped_screen_design",
    "wire wrap screen": "wire_wrapped_screen_design",
    "wire screen": "wire_wrapped_screen_design",
    "wire-wrapped screen": "wire_wrapped_screen_design",
    "wire wrap": "wire_wrapped_screen_design",
    "gravel pack": "gravel_pack_placement",
    "gravel placement": "gravel_pack_placement",
    "gravel packing": "gravel_pack_placement",
    "gravel pack installation": "gravel_pack_placement",
    "gravel pack completion": "gravel_pack_placement",
    "gravel size selection": "gravel_sizing_criteria",
    "gravel pack sizing": "gravel_sizing_criteria",
    "gravel pack design": "gravel_sizing_criteria",
    "sand sample": "formation_sand_analysis",
    "sand properties": "formation_sand_analysis",
    "sand mineralogy": "formation_sand_analysis",
    "particle size analysis": "formation_sand_analysis",
    "grain size distribution": "formation_sand_analysis",
    "sieve analysis": "formation_sand_analysis",
    "sand analysis": "formation_sand_analysis",
    "sand characterization": "formation_sand_analysis",
    "cylinder test": "thick_wall_cylinder_testing",
    "twct": "thick_wall_cylinder_testing",
    "thick-walled cylinder test": "thick_wall_cylinder_testing",
    "drawdown limit": "critical_drawdown_pressure",
    "drawdown threshold": "critical_drawdown_pressure",
    "drawdown pressure": "critical_drawdown_pressure",
    "drawdown": "critical_drawdown_pressure",
    "sand production threshold": "critical_drawdown_pressure",
    "sand onset pressure": "critical_drawdown_pressure",
    "sand failure pressure": "critical_drawdown_pressure",
    "wellbore stability": "critical_drawdown_pressure",
}

_EXPECTED_ENTRY_COUNT = len(SEMANTIC_MAP)

def _compute_map_hash():
    items = sorted(SEMANTIC_MAP.items())
    joined = "".join(f"{k}:{v};" for k, v in items)
    meta = f"{SEMANTIC_MAP_VERSION}|{SEMANTIC_MAP_AUTHOR}|{SEMANTIC_MAP_ENGINE}|{_EXPECTED_ENTRY_COUNT}"
    data = meta + "|" + joined
    return hashlib.sha256(data.encode("utf-8")).hexdigest()

_MAP_INTEGRITY_HASH = _compute_map_hash()

def verify_integrity():
    actual_count = len(SEMANTIC_MAP)
    expected_count = _EXPECTED_ENTRY_COUNT
    hash_val = _compute_map_hash()
    is_valid = (actual_count == expected_count) and (hash_val == _MAP_INTEGRITY_HASH)
    return {
        "status": "valid" if is_valid else "invalid",
        "entries": actual_count,
        "hash": hash_val,
        "is_valid": is_valid
    }

def normalize_term(term: str) -> str:
    t = term.strip().lower()
    t = re.sub(r"[\s\-]+", " ", t)
    t = t.replace("  ", " ")
    t = t.strip()
    return SEMANTIC_MAP.get(t, t.replace(" ", "_"))

def get_related_terms(term: str) -> list:
    normalized = normalize_term(term)
    related = [k for k, v in SEMANTIC_MAP.items() if v == normalized]
    return related

def get_all_mappings() -> dict:
    return dict(SEMANTIC_MAP)